# -*- coding: utf-8 -*-
"""Sesja N, partia trzecia — PAŃSTWO, MEDIA, PIENIĄDZE, RELIGIA, KULTURA.

Partie pierwsza i druga trafiły w materiał, który baza w dużej części już
miała: z 989 kandydatów odpadło 566 jako duplikaty. Wniosek był taki, że
rdzeń 1 353 haseł pokrywa słownictwo podróżne i bytowe znacznie lepiej, niż
sugerował rozkład kategorii — brakowało czego innego.

Brakowało warstwy, w której toczy się rozmowa wykraczająca poza obsługę
sytuacji: państwo, pieniądze w sensie ekonomii, wiara, media, obyczaj. To
jest dokładnie ta warstwa, która odróżnia „umiem zamówić jedzenie” od
„rozumiem, o czym mówią przy stole”.

Krotka: (poziom, polski, fonetyka, pismo, podkategoria, częstość, typ,
         kategoria, uwaga, dosłownie)
"""

PN = "Praca i nauka"
ST = "Small talk"
ZK = "Zakupy i pieniądze"
LR = "Ludzie i rodzina"
PL = "Miejsca i orientacja"
AW = "Awarie i pomoc"
GR = "Gramatyka użytkowa"

SOCIETY = [

# ============================================================ PAŃSTWO
("B1", "rząd", "rát-thà-baan", "รัฐบาล", "Państwo", 3, "n", PN,
 "rát to państwo, baan to zarządzać.", "państwo zarządzać"),
("B1", "państwo, kraj (jednostka)", "rát", "รัฐ", "Państwo", 2, "n", PN,
 "prà-thêet to kraj geograficznie, rát to państwo jako władza.", ""),
("B1", "prawo (przepis)", "kòt mǎai", "กฎหมาย", "Państwo", 3, "n", PN,
 "kòt to reguła, mǎai to znak, dokument.", "reguła znak"),
("B1", "przepis, zasada", "kòt", "กฎ", "Państwo", 3, "n", PN,
 "Uwaga: homofon z „kòt” (naciskać), pisanym inaczej.", ""),
("B1", "sąd", "sǎan", "ศาล", "Państwo", 2, "n", PN,
 "To samo słowo znaczy „kapliczka duchów” — sǎan phrá phuum.", ""),
("B1", "sędzia", "phûu phí-phâak-sǎa", "ผู้พิพากษา", "Państwo", 2, "n", PN,
 "", "osoba osądzać"),
("B1", "wyrok, kara", "thôot", "โทษ", "Państwo", 2, "n", PN,
 "To samo słowo stoi w khǎw thôot — „proszę o karę”, czyli przepraszam.", ""),
("B1", "grzywna, mandat", "khâa pràp", "ค่าปรับ", "Państwo", 3, "n", PN,
 "pràp to karać, korygować.", "opłata kara"),
("B1", "więzienie", "khúk", "คุก", "Państwo", 2, "n", PN,
 "Formalnie: ruean jam.", ""),
("B1", "wybory", "lûeak tâng", "เลือกตั้ง", "Państwo", 3, "n", PN,
 "lûeak to wybierać — ten sam czasownik co przy wyborze dania.", "wybierać ustanawiać"),
("B1", "głosować", "long khá-naen", "ลงคะแนน", "Państwo", 2, "v", PN,
 "khá-naen to punkty, głosy.", "schodzić punkty"),
("B1", "polityka", "kaan mueang", "การเมือง", "Państwo", 3, "n", PN,
 "Dosłownie „sprawy miasta”. Temat, którego z obcymi lepiej nie zaczynać.", "sprawy miasto"),
("B1", "obywatel", "phon-lá-mueang", "พลเมือง", "Państwo", 2, "n", PN,
 "", "ludność miasto"),
("B1", "król", "phrá má-hǎa kà-sàt", "พระมหากษัตริย์", "Państwo", 3, "n", PN,
 "O rodzinie królewskiej mówi się wyłącznie z szacunkiem — krytyka jest karalna.", "czcigodny wielki władca"),
("B1", "wojsko", "thá-hǎan", "ทหาร", "Państwo", 3, "n", PN,
 "To samo słowo znaczy „żołnierz”.", ""),
("B1", "wojna", "sǒng-khraam", "สงคราม", "Państwo", 2, "n", PN,
 "", ""),
("B1", "pokój (brak wojny)", "sǎn-tì-phâap", "สันติภาพ", "Państwo", 2, "n", PN,
 "Nie mylić z hâwng (pokój w mieszkaniu).", ""),
("B1", "wolność", "ìt-sà-rà-phâap", "อิสรภาพ", "Państwo", 2, "n", PN,
 "-phâap to końcówka rzeczowników abstrakcyjnych, jak polskie -ość.", ""),
("B1", "sprawiedliwość", "khwaam yút-tì-tham", "ความยุติธรรม", "Państwo", 2, "n", PN,
 "", "stan sprawiedliwy"),
("B1", "prawo (uprawnienie)", "sìt", "สิทธิ์", "Państwo", 3, "n", PN,
 "mii sìt — mieć prawo do czegoś.", ""),
("B1", "obowiązek", "nâa thîi", "หน้าที่", "Państwo", 4, "n", PN,
 "Dosłownie „twarz miejsca”. Także „funkcja, rola”.", "twarz miejsce"),
("B1", "pozwolenie, licencja", "bai à-nú-yâat", "ใบอนุญาต", "Państwo", 2, "n", PN,
 "", "arkusz pozwolenie"),
("B1", "korupcja", "kaan thút-jà-rìt", "การทุจริต", "Państwo", 2, "n", PN,
 "", "czynność nieuczciwość"),
("B1", "protest", "kaan prà-thúang", "การประท้วง", "Państwo", 2, "n", PN,
 "", "czynność protestować"),

# ============================================================ MEDIA
("A2", "wiadomości", "khàao", "ข่าว", "Media", 5, "n", PN,
 "Uwaga na trójkę: khàao (wiadomości), khâao (ryż), khǎao (biały). Klasyczna pułapka.", ""),
("A2", "gazeta", "nǎng-sǔe phim", "หนังสือพิมพ์", "Media", 3, "n", PN,
 "phim to drukować.", "książka drukować"),
("A2", "telewizja", "thii-wii", "ทีวี", "Media", 4, "n", PN,
 "Formalnie: thoo-rá-thát.", ""),
("A2", "radio", "wít-thá-yú", "วิทยุ", "Media", 3, "n", PN,
 "", ""),
("A2", "reklama", "khoo-sà-naa", "โฆษณา", "Media", 3, "n", PN,
 "", ""),
("A2", "program (audycja)", "raai kaan", "รายการ", "Media", 4, "n", PN,
 "Także „lista, pozycja w menu”.", "pozycja sprawa"),
("A2", "kanał (TV)", "châwng", "ช่อง", "Media", 3, "n", PN,
 "Także „otwór, szczelina, okienko w urzędzie”.", ""),
("A2", "dziennikarz", "nák khàao", "นักข่าว", "Media", 2, "n", PN,
 "", "człowiek wiadomości"),
("A2", "artykuł, tekst", "bòt khwaam", "บทความ", "Media", 3, "n", PN,
 "bòt to rozdział, lekcja, rola.", "rozdział treść"),
("A2", "ogłoszenie", "prà-kàat", "ประกาศ", "Media", 3, "n", PN,
 "Także czasownik „ogłaszać”.", ""),
("A2", "portal społecznościowy", "sôo-chîan", "โซเชียล", "Media", 4, "n", PN,
 "Skrót od social media; w mowie codzienny.", ""),
("A2", "udostępniać, dzielić się (w sieci)", "chae", "แชร์", "Media", 4, "v", PN,
 "Zapożyczenie z angielskiego share. Także „składać się po równo”.", ""),
("A2", "komentarz", "khawm-mén", "คอมเมนต์", "Media", 3, "n", PN,
 "", ""),
("A2", "plotka, pogłoska", "khàao lue", "ข่าวลือ", "Media", 2, "n", PN,
 "lue to rozchodzić się pogłoską.", "wiadomość rozchodzić się"),

# ============================================================ PIENIĄDZE
("B1", "gospodarka", "sèet-thà-kìt", "เศรษฐกิจ", "Ekonomia", 3, "n", ZK,
 "", ""),
("B1", "dług", "nîi", "หนี้", "Ekonomia", 3, "n", ZK,
 "Uwaga: nîi (dług) kontra nîi (to) kontra nǐi (uciekać) — trzy różne wyrazy.", ""),
("B1", "kredyt, pożyczka", "ngoen kûu", "เงินกู้", "Ekonomia", 2, "n", ZK,
 "kûu to pożyczać większą kwotę; yuem dotyczy rzeczy.", "pieniądze pożyczka"),
("B1", "odsetki", "dàwk bîa", "ดอกเบี้ย", "Ekonomia", 2, "n", ZK,
 "Dosłownie „kwiat” — pieniądze, które wyrastają z kapitału.", "kwiat odsetki"),
("B1", "oszczędności", "ngoen àwm", "เงินออม", "Ekonomia", 3, "n", ZK,
 "àwm to odkładać.", "pieniądze odkładać"),
("B1", "inwestycja", "kaan long thun", "การลงทุน", "Ekonomia", 2, "n", ZK,
 "long thun — dosłownie „położyć kapitał”.", "czynność wkładać kapitał"),
("B1", "kapitał, fundusz", "thun", "ทุน", "Ekonomia", 3, "n", ZK,
 "Także stypendium: thun kaan sùek-sǎa.", ""),
("B1", "bogactwo", "khwaam ràm ruai", "ความร่ำรวย", "Ekonomia", 2, "n", ZK,
 "", "stan zamożny"),
("B1", "bieda", "khwaam jon", "ความจน", "Ekonomia", 2, "n", ZK,
 "jon to biedny. Uwaga: to samo brzmienie co jon (aż do).", "stan biedny"),
("B1", "koszt", "khâa chái jàai", "ค่าใช้จ่าย", "Ekonomia", 4, "n", ZK,
 "Dosłownie „opłata używania i wydawania”.", "opłata używać wydawać"),
("B1", "budżet", "ngóp prà-maan", "งบประมาณ", "Ekonomia", 2, "n", ZK,
 "prà-maan to znów „około” — budżet jako kwota szacowana.", "zestawienie szacunek"),
("B1", "faktura", "bai kam-kàp phaa-sǐi", "ใบกำกับภาษี", "Ekonomia", 2, "n", ZK,
 "Potrzebna przy zwrocie VAT na lotnisku.", "arkusz towarzyszący podatek"),
("B1", "hurt", "khǎai sòng", "ขายส่ง", "Ekonomia", 2, "n", ZK,
 "Detal to khǎai plìik.", "sprzedawać wysyłać"),
("B1", "detal", "khǎai plìik", "ขายปลีก", "Ekonomia", 2, "n", ZK,
 "", "sprzedawać drobno"),
("B1", "zamożny", "ràm ruai", "ร่ำรวย", "Ekonomia", 2, "adj", ZK,
 "Mocniejsze niż ruai.", ""),
("B1", "biedny (bez pieniędzy)", "jon", "จน", "Ekonomia", 3, "adj", ZK,
 "Neutralne, bez zabarwienia litości.", ""),
("B1", "opłacić z góry", "jàai lûang nâa", "จ่ายล่วงหน้า", "Ekonomia", 3, "v", ZK,
 "lûang nâa to „z wyprzedzeniem”.", "płacić wyprzedzać twarz"),
("B1", "rata", "ngûat", "งวด", "Ekonomia", 2, "n", ZK,
 "phàwn ngûat — płatność ratalna, bardzo popularna.", ""),

# ============================================================ WIARA
("A2", "buddyzm", "sàat-sà-nǎa phút", "ศาสนาพุทธ", "Wiara i obyczaj", 3, "n", ST,
 "Wyznanie około 93 procent mieszkańców.", "religia Budda"),
("A2", "religia", "sàat-sà-nǎa", "ศาสนา", "Wiara i obyczaj", 3, "n", ST,
 "thǔe sàat-sà-nǎa — wyznawać religię.", ""),
("A2", "modlić się", "sùat mon", "สวดมนต์", "Wiara i obyczaj", 3, "v", ST,
 "", "recytować modlitwa"),
("A2", "medytacja", "sà-mǎa-thí", "สมาธิ", "Wiara i obyczaj", 3, "n", ST,
 "Także „skupienie” w zwykłym sensie: mii sà-mǎa-thí.", ""),
("A2", "zasługa, dobry uczynek", "bun", "บุญ", "Wiara i obyczaj", 4, "n", ST,
 "tham bun — czynić zasługę. Pojęcie porządkujące codzienną etykę.", ""),
("A2", "grzech, zła zasługa", "bàap", "บาป", "Wiara i obyczaj", 3, "n", ST,
 "Przeciwieństwo bun. Uwaga: bàap kontra bàat (baht).", ""),
("A2", "karma, skutek uczynków", "kam", "กรรม", "Wiara i obyczaj", 3, "n", ST,
 "Potocznie wykrzyknik rezygnacji: „kam!” — taki los.", ""),
("A2", "duch, zjawa", "phǐi", "ผี", "Wiara i obyczaj", 3, "n", ST,
 "Wiara w duchy współistnieje z buddyzmem bez sprzeczności.", ""),
("A2", "kapliczka duchów", "sǎan phrá phuum", "ศาลพระภูมิ", "Wiara i obyczaj", 3, "n", ST,
 "Stoi przed niemal każdym domem i biurowcem.", "kapliczka czcigodny ziemia"),
("A2", "amulet", "phrá khrûeang", "พระเครื่อง", "Wiara i obyczaj", 2, "n", ST,
 "Nosi się na szyi; przedmiot kolekcjonerski i religijny naraz.", "czcigodny przedmiot"),
("A2", "przepowiednia, wróżba", "duu duang", "ดูดวง", "Wiara i obyczaj", 3, "n", ST,
 "duang to gwiazda przeznaczenia.", "patrzeć los"),
("A2", "szczęśliwy traf, fart", "chôok", "โชค", "Wiara i obyczaj", 4, "n", ST,
 "chôok dii — powodzenia; chôok ráai — pech.", ""),
("A2", "pech", "chôok ráai", "โชคร้าย", "Wiara i obyczaj", 3, "n", ST,
 "ráai to zły, groźny.", "los zły"),
("A2", "ofiarowywać (mnichom)", "tàk bàat", "ตักบาตร", "Wiara i obyczaj", 3, "v", ST,
 "Poranny obrzęd wkładania jedzenia do misy mnicha.", "nabierać misa"),
("A2", "festiwal, obchody", "thêet-sà-kaan", "เทศกาล", "Wiara i obyczaj", 3, "n", ST,
 "", ""),
("A2", "procesja, parada", "khà-buan", "ขบวน", "Wiara i obyczaj", 2, "n", ST,
 "Także skład pociągu.", ""),
("A2", "tradycja, obyczaj", "prà-phee-nii", "ประเพณี", "Wiara i obyczaj", 3, "n", ST,
 "", ""),
("A2", "kultura", "wát-thá-ná-tham", "วัฒนธรรม", "Wiara i obyczaj", 3, "n", ST,
 "", ""),
("A2", "zwyczaj, nawyk", "ní-sǎi", "นิสัย", "Wiara i obyczaj", 3, "n", ST,
 "Także „charakter, usposobienie”: ní-sǎi dii.", ""),
("A2", "przesąd", "khwaam chûea", "ความเชื่อ", "Wiara i obyczaj", 2, "n", ST,
 "Dosłownie „to, w co się wierzy” — bez pogardliwego odcienia.", "stan wierzyć"),

# ============================================================ SPOŁECZEŃSTWO
("B1", "społeczeństwo", "sǎng-khom", "สังคม", "Społeczeństwo", 3, "n", LR,
 "Także „towarzystwo, życie towarzyskie”.", ""),
("B1", "pokolenie", "rûn", "รุ่น", "Społeczeństwo", 3, "n", LR,
 "Także „model, rocznik” o sprzęcie i o roczniku szkolnym.", ""),
("B1", "ludność", "prà-chaa-kawn", "ประชากร", "Społeczeństwo", 2, "n", LR,
 "", ""),
("B1", "mniejszość", "chon klùm náwi", "ชนกลุ่มน้อย", "Społeczeństwo", 2, "n", LR,
 "", "ludzie grupa mało"),
("B1", "równość", "khwaam thâo thiam", "ความเท่าเทียม", "Społeczeństwo", 2, "n", LR,
 "thâo to równy — ten sam wyraz co w thâo rai.", "stan równy"),
("B1", "różnica (między ludźmi)", "khwaam tàek tàang", "ความแตกต่าง", "Społeczeństwo", 3, "n", LR,
 "tàek to pękać, rozdzielać się.", "stan rozdzielony obcy"),
("B1", "wpływ", "ìt-thí-phon", "อิทธิพล", "Społeczeństwo", 2, "n", LR,
 "", ""),
("B1", "władza, autorytet", "am-nâat", "อำนาจ", "Społeczeństwo", 2, "n", LR,
 "", ""),
("B1", "hierarchia, starszeństwo", "aa-wú-sǒo", "อาวุโส", "Społeczeństwo", 2, "n", LR,
 "Klucz do zrozumienia, dlaczego phîi i náwng są obowiązkowe.", ""),
("B1", "wzajemna przysługa", "bun khun", "บุญคุณ", "Społeczeństwo", 2, "n", LR,
 "Dług wdzięczności wobec kogoś, kto nam pomógł — pojęcie bardzo mocne.", "zasługa dobro"),
("B1", "reputacja", "chûe sǐang", "ชื่อเสียง", "Społeczeństwo", 3, "n", LR,
 "", "imię głos"),
("B1", "zaufanie", "khwaam wái wang jai", "ความไว้วางใจ", "Społeczeństwo", 2, "n", LR,
 "", "stan powierzać serce"),
("B1", "konflikt, spór", "khwaam khàt yáeng", "ความขัดแย้ง", "Społeczeństwo", 2, "n", LR,
 "", "stan sprzeciwiać się"),
("B1", "kompromis", "kaan prà-nii prà-nawm", "การประนีประนอม", "Społeczeństwo", 2, "n", PN,
 "", "czynność godzić"),
("B1", "współpraca", "kaan rûam mue", "การร่วมมือ", "Społeczeństwo", 3, "n", PN,
 "Dosłownie „łączenie rąk”.", "czynność wspólnie ręka"),
("B1", "konkurencja", "kaan khàeng khǎn", "การแข่งขัน", "Społeczeństwo", 3, "n", PN,
 "Także zawody sportowe.", "czynność ścigać się"),
("B1", "wolontariat", "aa-sǎa sà-màk", "อาสาสมัคร", "Społeczeństwo", 2, "n", PN,
 "sà-màk to zgłaszać się — ten sam wyraz co w sà-màk ngaan.", "ochotniczo zgłaszać się"),
("B1", "darowizna", "kaan bàw-rí-jàak", "การบริจาค", "Społeczeństwo", 2, "n", PN,
 "", "czynność ofiarowywać"),

# ============================================================ ZAGROŻENIA
("B1", "przestępstwo", "aat-yaa-kam", "อาชญากรรม", "Zagrożenia", 2, "n", AW,
 "", ""),
("B1", "złodziej", "khà-mooi", "หัวขโมย", "Zagrożenia", 3, "n", AW,
 "Uwaga: to samo słowo co „kraść”. Kontekst rozstrzyga rolę.", ""),
("B1", "napad", "kaan plôn", "การปล้น", "Zagrożenia", 2, "n", AW,
 "", "czynność rabować"),
("B1", "oszust", "mít-chǎa chîip", "มิจฉาชีพ", "Zagrożenia", 3, "n", AW,
 "Słowo z ostrzeżeń bankowych o telefonach naciągaczy.", "błędny zawód"),
("B1", "ryzyko", "khwaam sìang", "ความเสี่ยง", "Zagrożenia", 3, "n", AW,
 "sìang to ryzykować.", "stan ryzykować"),
("B1", "ostrzeżenie", "kham tuean", "คำเตือน", "Zagrożenia", 3, "n", AW,
 "kham to słowo — kham thǎam (pytanie), kham tàwp (odpowiedź).", "słowo ostrzegać"),
("B1", "słowo (jednostka)", "kham", "คำ", "Zagrożenia", 5, "n", GR,
 "Także klasyfikator słów: sǎwng kham.", ""),
("B1", "zdanie", "prà-yòok", "ประโยค", "Zagrożenia", 3, "n", GR,
 "", ""),
("B1", "znaczenie, sens", "khwaam mǎai", "ความหมาย", "Zagrożenia", 4, "n", GR,
 "mǎai khwaam wâa — to znaczy, że.", "stan znaczyć"),
("B1", "kontrola, nadzór", "kaan khûap khum", "การควบคุม", "Zagrożenia", 2, "n", AW,
 "", "czynność nadzorować"),
("B1", "epidemia", "rôok rá-bàat", "โรคระบาด", "Zagrożenia", 2, "n", AW,
 "rôok to choroba jako jednostka chorobowa.", "choroba rozprzestrzeniać"),
("B1", "choroba (jednostka)", "rôok", "โรค", "Zagrożenia", 4, "n", AW,
 "rôok hǔa jai — choroba serca. Inne słowo niż pùai (chorować).", ""),
("B1", "wirus", "chúea wai-rát", "เชื้อไวรัส", "Zagrożenia", 3, "n", AW,
 "chúea to zarazek — także zaczyn i pochodzenie.", "zarazek wirus"),
("B1", "zarazek, bakteria", "chúea rôok", "เชื้อโรค", "Zagrożenia", 3, "n", AW,
 "Uwaga: chúea (zarazek) kontra chûea (wierzyć).", "zarazek choroba"),
]
