# -*- coding: utf-8 -*-
"""Dialogi etapu 5 (B2) — czesc B.

Zakres: zycie osoby mieszkajacej w Tajlandii, sytuacje awaryjne wymagajace
precyzji, roznice rejestru w praktyce, naturalne rozmowy o emocjach,
idiomy w uzyciu.

Krotka: (tytul, sytuacja, poziom, rola A, rola B, kwestie, notatka)
Kwestia: (rola, polski, fonetyka, tajski)
"""

DIALOGUES_B2_B = [

("Przedłużanie wizy w urzędzie imigracyjnym", "Praca i nauka", "B2", "Obcokrajowiec", "Urzędnik", [
 ("A", "Chciałbym przedłużyć wizę.", "phǒm yàak tàw wii-sâa khráp", "ผมอยากต่อวีซ่าครับ"),
 ("B", "Poproszę paszport i wniosek.", "khǎw nǎng-sǔe doen thaang kàp khâm rǎwng khráp", "ขอหนังสือเดินทางกับคำร้องครับ"),
 ("A", "Czego brakuje w moich dokumentach?", "èek-kà-sǎan phǒm khàat à-rai bâang khráp", "เอกสารผมขาดอะไรบ้างครับ"),
 ("B", "Zaświadczenia o miejscu zamieszkania.", "khàat bai rap-rawng thîi phák khráp", "ขาดใบรับรองที่พักครับ"),
 ("A", "Gdzie je dostanę?", "khǎw dâai thîi nǎi khráp", "ขอได้ที่ไหนครับ"),
 ("B", "Na tym samym piętrze, okienko czwarte.", "chán diao kan khráp châwng thîi sìi", "ชั้นเดียวกันครับ ช่องที่สี่"),
 ("A", "Czy dobrze rozumiem: wracam dzisiaj?", "phǒm khâo-jai thùuk mǎi khráp klàp maa wan níi", "ผมเข้าใจถูกไหมครับ กลับมาวันนี้"),
 ("B", "Tak, przyjmujemy do wpół do czwartej.", "châi khráp ráp thǔeng bàai sǎam khrûeng", "ใช่ครับ รับถึงบ่ายสามครึ่ง"),
 ("A", "Ile wynosi opłata?", "khâa tham-niam thâo-rài khráp", "ค่าธรรมเนียมเท่าไหร่ครับ"),
 ("B", "Tysiąc dziewięćset, tylko gotówką.", "nùeng phan kâo ráwi ngoen sòt thâo nán khráp", "หนึ่งพันเก้าร้อย เงินสดเท่านั้นครับ"),
], "W urzędzie imigracyjnym płaci się zwykle wyłącznie gotówką. „wan tham-kaan” i godziny przyjęć warto sprawdzić przed przyjazdem."),

("Zgłoszenie wypadku pod telefon", "Awarie i pomoc", "B2", "Świadek", "Dyspozytor", [
 ("A", "Jest wypadek, potrzebuję karetki.", "mii ù-bàt-tì-hèet khǎw rót phá-yaa-baan dùan khráp", "มีอุบัติเหตุ ขอรถพยาบาลด่วนครับ"),
 ("B", "Gdzie dokładnie?", "yùu trong nǎi khráp", "อยู่ตรงไหนครับ"),
 ("A", "Na rogu, naprzeciwko sklepu całodobowego.", "trong hǔa mum thà-nǒn trong khâam ráan sà-dùak súe khráp", "ตรงหัวมุมถนน ตรงข้ามร้านสะดวกซื้อครับ"),
 ("B", "Ilu jest rannych?", "mii khon bàat jèp kìi khon khráp", "มีคนบาดเจ็บกี่คนครับ"),
 ("A", "Dwie osoby, jedna nie może wstać.", "sǎwng khon khráp khon nùeng lúk mâi dâai", "สองคนครับ คนหนึ่งลุกไม่ได้"),
 ("B", "Czy są przytomni?", "yang mii sà-tì mǎi khráp", "ยังมีสติไหมครับ"),
 ("A", "Tak, ale mocno krwawi z nogi.", "mii sà-tì khráp tàae lûeat àwk thîi khǎa mâak", "มีสติครับ แต่เลือดออกที่ขามาก"),
 ("B", "Proszę uciskać ranę i nie ruszać go.", "chûai kòt phlǎe wái láe yàa yáai tua khráp", "ช่วยกดแผลไว้และอย่าย้ายตัวครับ"),
 ("A", "Nie mówię dobrze po tajsku, proszę mówić wolno.", "phǒm phûut thai mâi khâwi dâai chûai phûut cháa cháa khráp", "ผมพูดไทยไม่ค่อยได้ ช่วยพูดช้าๆ ครับ"),
 ("B", "Dobrze. Wysyłam lokalizację, karetka jedzie.", "dâai khráp sòng phíkàt maa rót kam-lang pai", "ได้ครับ ส่งพิกัดมา รถกำลังไป"),
], "Kolejność informacji ratuje minuty: co się stało, gdzie, ilu rannych, w jakim stanie. Uprzedzenie o barierze językowej sprawia, że dyspozytor zwolni."),

("Awaria wody w mieszkaniu", "Dom i codzienność", "B2", "Lokator", "Zarządca", [
 ("A", "Zalało mi mieszkanie.", "náam thûam hâwng phǒm khráp", "น้ำท่วมห้องผมครับ"),
 ("B", "Skąd leci woda?", "náam maa jàak nǎi khráp", "น้ำมาจากไหนครับ"),
 ("A", "Chyba od sąsiada z góry.", "nâa jà maa jàak hâwng chán bon khráp", "น่าจะมาจากห้องชั้นบนครับ"),
 ("B", "Proszę zakręcić główny zawór.", "chûai pìt wáan náam làk kàwn khráp", "ช่วยปิดวาล์วน้ำหลักก่อนครับ"),
 ("A", "Gdzie jest ten zawór?", "wáan yùu thîi nǎi khráp", "วาล์วอยู่ที่ไหนครับ"),
 ("B", "Przy drzwiach wejściowych, po prawej.", "yùu khâang prà-tuu thaang khwǎa khráp", "อยู่ข้างประตูทางขวาครับ"),
 ("A", "Proszę o technika jeszcze dziś.", "khǎw châang maa wan níi loei dâai mǎi khráp", "ขอช่างมาวันนี้เลยได้ไหมครับ"),
 ("B", "Wyślę w ciągu godziny.", "jà sòng phaai-nai nùeng chûa-moong khráp", "จะส่งภายในหนึ่งชั่วโมงครับ"),
 ("A", "Kto płaci za szkody?", "khâa sǐa hǎai khrai àwk khráp", "ค่าเสียหายใครออกครับ"),
 ("B", "Zależy od przyczyny, sprawdzimy.", "khûen yùu kàp sǎa-hèet khráp dǐao trùat sàwp", "ขึ้นอยู่กับสาเหตุครับ เดี๋ยวตรวจสอบ"),
], "Przy awarii najpierw działanie, potem rozliczenie. Pytanie o koszty zadaj po opanowaniu sytuacji, nie zamiast niego."),

("Ten sam komunikat w trzech rejestrach", "Podstawy i grzeczność", "B2", "Uczący się", "Nauczyciel", [
 ("A", "Jak poprosić o rachunek w hotelowej restauracji?", "nai hâwng aa-hǎan roong raem khǎw bin yang-ngai khráp", "ในห้องอาหารโรงแรมขอบิลยังไงครับ"),
 ("B", "Formalnie powiesz: poproszę o rachunek.", "bàep thaang kaan phûut wâa khǎw bin dûai khráp", "แบบทางการพูดว่า ขอบิลด้วยครับ"),
 ("A", "A w zwykłej knajpce?", "láew ráan thammadaa lâ khráp", "แล้วร้านธรรมดาล่ะครับ"),
 ("B", "Neutralnie: poproszę rachunek.", "bàep klaang khǎw bin nòi khráp", "แบบกลาง ขอบิลหน่อยครับ"),
 ("A", "A jak mówią miejscowi na ulicy?", "khon thǎew níi phûut yang-ngai khráp", "คนแถวนี้พูดยังไงครับ"),
 ("B", "Potocznie: ile płacę?", "bàep phûut lên khít tang dûai khráp", "แบบพูดเล่น คิดตังค์ด้วยครับ"),
 ("A", "Czy potoczna wersja kogoś urazi?", "bàep nán tham hâi khon mâi phaw jai mǎi khráp", "แบบนั้นทำให้คนไม่พอใจไหมครับ"),
 ("B", "W knajpce nie, w hotelu zabrzmi niedbale.", "ráan khâang thaang mâi pen rai tàae nai roong raem jà duu mâi sù-phâap", "ร้านข้างทางไม่เป็นไร แต่ในโรงแรมจะดูไม่สุภาพ"),
 ("A", "Czyli neutralna jest najbezpieczniejsza.", "sà-rùp láew bàep klaang plàwt-phai thîi sùt", "สรุปแล้วแบบกลางปลอดภัยที่สุด"),
 ("B", "Dokładnie. Od niej zaczynaj.", "chái loei khráp rôoem jàak bàep nán", "ใช่เลยครับ เริ่มจากแบบนั้น"),
], "Ten dialog pokazuje w praktyce rejestrową trójkę z bazy: formalny, neutralny, potoczny. Zasada jest prosta — w razie wątpliwości wybierz środek."),

("Rozmowa o wypaleniu w pracy", "Ludzie i rodzina", "B2", "Przyjaciel", "Znajomy", [
 ("A", "Mam wrażenie, że jesteś ostatnio wykończony.", "rúu-sùek wâa chûang níi khun nùeai mâak ná khráp", "รู้สึกว่าช่วงนี้คุณเหนื่อยมากนะครับ"),
 ("B", "Mam tego dosyć, szczerze mówiąc.", "phûut trong trong phǒm thon mâi wǎi láew khráp", "พูดตรงๆ ผมทนไม่ไหวแล้วครับ"),
 ("A", "Opowiedz, co się dzieje.", "lâo hâi fang nòi khráp", "เล่าให้ฟังหน่อยครับ"),
 ("B", "Noszę to w sobie od miesięcy.", "phǒm kèp wái nai jai maa lǎai duean láew khráp", "ผมเก็บไว้ในใจมาหลายเดือนแล้วครับ"),
 ("A", "To musiało być trudne.", "man khong jà nàk ná khráp", "มันคงจะหนักนะครับ"),
 ("B", "Boję się, że będzie gorzej.", "phǒm klua wâa man jà nàk kwàa doem khráp", "ผมกลัวว่ามันจะหนักกว่าเดิมครับ"),
 ("A", "Rozmawiałeś z szefem?", "khoei khui kàp hǔa-nâa mǎi khráp", "เคยคุยกับหัวหน้าไหมครับ"),
 ("B", "Jeszcze nie, nie wiem, jak zacząć.", "yang khráp mâi rúu jà rôoem yang-ngai", "ยังครับ ไม่รู้จะเริ่มยังไง"),
 ("A", "Powiedz mu wprost, że potrzebujesz jasnych zasad.", "bàwk trong trong wâa khǎw kót thîi chát-jeen khráp", "บอกตรงๆ ว่าขอกฎที่ชัดเจนครับ"),
 ("B", "Spróbuję. Dobrze, że mogę o tym pogadać.", "jà lawng duu khráp dii thîi mii khon hâi khui", "จะลองดูครับ ดีที่มีคนให้คุย"),
], "„kèp wái nai jai” — trzymać w sercu — opisuje bardzo tajski sposób radzenia sobie z problemem. Rozmowa o tym jest już przełamaniem."),

("Idiomy w rozmowie o pechu", "Small talk", "B2", "Znajomy", "Znajoma", [
 ("A", "Ostatnio mam pecha jak nigdy.", "chûang níi duang tòk mâak khráp", "ช่วงนี้ดวงตกมากครับ"),
 ("B", "Co się stało tym razem?", "khráng níi kòet à-rai khûen khâ", "ครั้งนี้เกิดอะไรขึ้นคะ"),
 ("A", "Zmieniłem pracę i wpadłem z deszczu pod rynnę.", "phǒm plìan ngaan láew mǔean nǐi sǔea pà jaw-rá-khêe", "ผมเปลี่ยนงานแล้วเหมือนหนีเสือปะจระเข้"),
 ("B", "O rany, aż tak źle?", "óo hǒo nàk khà-nàat nán lǒe khâ", "โอ้โห หนักขนาดนั้นเหรอคะ"),
 ("A", "Tłumaczenie im czegokolwiek to rzucanie grochem o ścianę.", "à-thí-baai pai kâw mǔean sǐi sáw hâi khwaai fang", "อธิบายไปก็เหมือนสีซอให้ควายฟัง"),
 ("B", "Nie bierz sobie tego do serca.", "yàa kèp maa khít mâak ná khâ", "อย่าเก็บมาคิดมากนะคะ"),
 ("A", "Wiem, ale trudno się nie stresować.", "rúu khráp tàae kâw khrîat yùu dii", "รู้ครับ แต่ก็เครียดอยู่ดี"),
 ("B", "Krok po kroku dojdziesz.", "khôi pen khôi pai khâ", "ค่อยเป็นค่อยไปค่ะ"),
 ("A", "Masz rację. Odpuszczam, nie warto.", "khun phûut thùuk khâ chàng man thòe mâi khúm", "คุณพูดถูก ช่างมันเถอะ ไม่คุ้ม"),
], "Uwaga na „sǐi sáw hâi khwaai fang”: nazwanie kogoś bawołem to ciężka obraza, więc idiomu używa się o sytuacji, nie o rozmówcy."),

("Zapisywanie dziecka do szkoły", "Praca i nauka", "B2", "Rodzic", "Sekretarka", [
 ("A", "Chciałbym zapisać dziecko do szkoły.", "phǒm yàak sà-màk rian hâi lûuk khráp", "ผมอยากสมัครเรียนให้ลูกครับ"),
 ("B", "W jakim wieku jest dziecko?", "lûuk aa-yú thâo-rài khráp", "ลูกอายุเท่าไหร่ครับ"),
 ("A", "Siedem lat, nie mówi jeszcze po tajsku.", "jèt khùap khráp yang phûut thai mâi dâai", "เจ็ดขวบครับ ยังพูดไทยไม่ได้"),
 ("B", "Mamy zajęcia wyrównawcze z języka.", "raw mii khláat sǒoem phaa-sǎa khráp", "เรามีคลาสเสริมภาษาครับ"),
 ("A", "Jakie dokumenty są potrzebne?", "tâwng chái èek-kà-sǎan à-rai bâang khráp", "ต้องใช้เอกสารอะไรบ้างครับ"),
 ("B", "Paszport dziecka, wiza i zaświadczenie o adresie.", "nǎng-sǔe doen thaang khǎwng dèk wii-sâa láe bai rap-rawng thîi phák khráp", "หนังสือเดินทางของเด็ก วีซ่า และใบรับรองที่พักครับ"),
 ("A", "Ile wynosi czesne za semestr?", "khâa thoem thâo-rài khráp", "ค่าเทอมเท่าไหร่ครับ"),
 ("B", "Dwadzieścia tysięcy z posiłkami.", "sǎwng mùen ruam khâa aa-hǎan khráp", "สองหมื่นรวมค่าอาหารครับ"),
 ("A", "Czy mogę porozmawiać z wychowawcą?", "khǎw khui kàp khruu prà-jam chán dâai mǎi khráp", "ขอคุยกับครูประจำชั้นได้ไหมครับ"),
 ("B", "Oczywiście, w piątek po lekcjach.", "dâai khráp wan sùk lǎng lôek rian", "ได้ครับ วันศุกร์หลังเลิกเรียน"),
], "„khùap” liczy lata dzieci do jedenastu, potem używa się „pii”. To rozróżnienie brzmi naturalnie i od razu zdradza dobrą znajomość języka."),

("Kradzież w autobusie", "Awarie i pomoc", "B2", "Poszkodowany", "Policjant", [
 ("A", "Okradziono mnie w autobusie.", "phǒm thùuk khà-mooi bon rót mee khráp", "ผมถูกขโมยบนรถเมล์ครับ"),
 ("B", "Co zginęło?", "khǎwng à-rai hǎai khráp", "ของอะไรหายครับ"),
 ("A", "Portfel z kartą i gotówką.", "krà-pǎo tang phráwm bàt láe ngoen sòt khráp", "กระเป๋าตังค์พร้อมบัตรและเงินสดครับ"),
 ("B", "Kiedy to zauważyłeś?", "rúu tua tawn nǎi khráp", "รู้ตัวตอนไหนครับ"),
 ("A", "Około drugiej po południu, przy dworcu.", "prà-maan bàai sǎwng moong trong sà-thǎa-nii khráp", "ประมาณบ่ายสองโมง ตรงสถานีครับ"),
 ("B", "Widziałeś kogoś podejrzanego?", "hěn khon nâa sǒng-sǎi mǎi khráp", "เห็นคนน่าสงสัยไหมครับ"),
 ("A", "Mężczyzna w czerwonej koszulce, wysoki.", "phûu chaai sûea sǐi daaeng tua sǔung khráp", "ผู้ชายเสื้อสีแดงตัวสูงครับ"),
 ("B", "Zgłosiłeś blokadę karty?", "à-yàt bàt láew rǔe yang khráp", "อายัดบัตรแล้วหรือยังครับ"),
 ("A", "Tak, od razu. Proszę o kopię protokołu.", "à-yàt láew khráp khǎw sǎm-nao bai jâeng khwaam dûai", "อายัดแล้วครับ ขอสำเนาใบแจ้งความด้วย"),
 ("B", "Wydamy za pół godziny.", "ràw khrûeng chûa-moong khráp", "รอครึ่งชั่วโมงครับ"),
], "Kopia „bai jâeng khwaam” jest niezbędna przy zgłoszeniu do ubezpieczyciela. Poproś o nią zawsze, nawet jeśli nikt nie zaproponuje."),

("Godzenie się po sprzeczce", "Ludzie i rodzina", "B2", "Partner", "Partnerka", [
 ("A", "Chciałbym wrócić do wczorajszej rozmowy.", "khǎw yáwn klàp pai thîi khui mûea waan khráp", "ขอย้อนกลับไปที่คุยเมื่อวานครับ"),
 ("B", "Dobrze, ale bez podnoszenia głosu.", "dâai khâ tàae yàa sǐang dang kan", "ได้ค่ะ แต่อย่าเสียงดังกัน"),
 ("A", "Zgoda. Może to moja wina.", "tòk long khráp àat jà pen thîi phǒm eeng kâw dâai", "ตกลงครับ อาจจะเป็นที่ผมเองก็ได้"),
 ("B", "Poczułam się pominięta przy tej decyzji.", "chǎn rúu-sùek thùuk mawng khâam tawn tàt-sǐn jai khâ", "ฉันรู้สึกถูกมองข้ามตอนตัดสินใจค่ะ"),
 ("A", "Nie zamierzałem cię urazić.", "phǒm mâi dâai tâng-jai hâi khun mâi sà-baai jai khráp", "ผมไม่ได้ตั้งใจให้คุณไม่สบายใจครับ"),
 ("B", "Wiem. Po prostu chcę być pytana.", "rúu khâ chǎn khâe yàak hâi thǎam kàwn", "รู้ค่ะ ฉันแค่อยากให้ถามก่อน"),
 ("A", "Masz rację. Następnym razem zapytam.", "khun phûut thùuk khráp khráng nâa jà thǎam kàwn", "คุณพูดถูกครับ ครั้งหน้าจะถามก่อน"),
 ("B", "Nie mam do ciebie żalu.", "chǎn mâi dâai thǔe sǎa khâ", "ฉันไม่ได้ถือสาค่ะ"),
 ("A", "Ważniejsza jest dla mnie relacja niż ta sprawa.", "khwaam sǎm-phan sǎm-khan kwàa rûeang níi khráp", "ความสัมพันธ์สำคัญกว่าเรื่องนี้ครับ"),
], "Kobieta kończy zdania na „khâ” i mówi o sobie „chǎn”. „nòi jai” i „thùuk mawng khâam” to uczucia bez dokładnego polskiego odpowiednika."),

("Otwieranie konta w banku", "Zakupy i pieniądze", "B2", "Klient", "Pracownik banku", [
 ("A", "Chciałbym otworzyć konto oszczędnościowe.", "phǒm yàak pòoet ban-chii àwm sáp khráp", "ผมอยากเปิดบัญชีออมทรัพย์ครับ"),
 ("B", "Poproszę paszport i pozwolenie na pracę.", "khǎw nǎng-sǔe doen thaang kàp bai à-nú-yâat tham-ngaan khráp", "ขอหนังสือเดินทางกับใบอนุญาตทำงานครับ"),
 ("A", "Nie mam pozwolenia, mam wizę emerytalną.", "phǒm mâi mii khráp phǒm thǔe wii-sâa kà-sǐan", "ผมไม่มีครับ ผมถือวีซ่าเกษียณ"),
 ("B", "Wtedy potrzebne zaświadczenie o adresie.", "ngán tâwng chái bai rap-rawng thîi phák khráp", "งั้นต้องใช้ใบรับรองที่พักครับ"),
 ("A", "Jakie są opłaty miesięczne?", "khâa tham-niam raai duean thâo-rài khráp", "ค่าธรรมเนียมรายเดือนเท่าไหร่ครับ"),
 ("B", "Za konto nic, za kartę sto pięćdziesiąt rocznie.", "ban-chii mâi mii khráp bàt pii lá nùeng ráwi hâa sìp", "บัญชีไม่มีครับ บัตรปีละหนึ่งร้อยห้าสิบ"),
 ("A", "Czy mogę ustawić płatność automatyczną?", "tâng jàai àt-tà-noo-mát dâai mǎi khráp", "ตั้งจ่ายอัตโนมัติได้ไหมครับ"),
 ("B", "Tak, za prąd, wodę i internet.", "dâai khráp khâa fai khâa náam láe khâa nét", "ได้ครับ ค่าไฟ ค่าน้ำ และค่าเน็ต"),
 ("A", "Czy dobrze rozumiem: wracam z zaświadczeniem?", "phǒm khâo-jai thùuk mǎi khráp klàp maa phráwm bai rap-rawng", "ผมเข้าใจถูกไหมครับ กลับมาพร้อมใบรับรอง"),
 ("B", "Zgadza się, wtedy zrobimy wszystko od ręki.", "thùuk tâwng khráp láew tham hâi sèt loei", "ถูกต้องครับ แล้วทำให้เสร็จเลย"),
], "Wymogi bankowe wobec obcokrajowców różnią się między oddziałami. Pytanie o dokumenty przed przyjazdem oszczędza dwie wizyty."),

("Umawianie technika przez telefon", "Dom i codzienność", "B2", "Klient", "Serwis", [
 ("A", "Dzwonię w sprawie klimatyzacji.", "thoo maa rûeang aae khráp", "โทรมาเรื่องแอร์ครับ"),
 ("B", "Co się dzieje z urządzeniem?", "khrûeng pen à-rai khráp", "เครื่องเป็นอะไรครับ"),
 ("A", "Nie chłodzi, choć się włącza.", "man tòat láew tàae mâi yen khráp", "มันติดแล้วแต่ไม่เย็นครับ"),
 ("B", "Od kiedy tak jest?", "pen maa naan thâo-rài láew khráp", "เป็นมานานเท่าไหร่แล้วครับ"),
 ("A", "Od trzech dni, tylko czasami.", "sǎam wan láew khráp pen baang khráng", "สามวันแล้วครับ เป็นบางครั้ง"),
 ("B", "Czyszczono filtr w tym roku?", "pii níi láang fin-tôoe rǔe yang khráp", "ปีนี้ล้างฟิลเตอร์หรือยังครับ"),
 ("A", "Nie, dopiero się wprowadziłem.", "yang khráp phǒm phôoeng yáai maa", "ยังครับ ผมเพิ่งย้ายมา"),
 ("B", "Przyjedziemy jutro rano, opłata za dojazd trzysta.", "phrûng-níi cháo khráp khâa doen thaang sǎam ráwi", "พรุ่งนี้เช้าครับ ค่าเดินทางสามร้อย"),
 ("A", "Proszę o wycenę przed naprawą.", "khǎw prà-mâan raa-khaa kàwn sâwm khráp", "ขอประมาณราคาก่อนซ่อมครับ"),
 ("B", "Oczywiście, technik zadzwoni przed przyjazdem.", "dâai khráp châang jà thoo kàwn thǔeng", "ได้ครับ ช่างจะโทรก่อนถึง"),
], "Serwisant zawsze pyta „zawsze czy czasami”. Przygotuj tę odpowiedź zawczasu — skraca rozmowę o połowę."),

("Rozmowa z sąsiadami po wprowadzce", "Ludzie i rodzina", "B2", "Nowy lokator", "Sąsiadka", [
 ("A", "Dzień dobry, wprowadziłem się obok.", "sà-wàt-dii khráp phǒm yáai maa yùu khâang khâang", "สวัสดีครับ ผมย้ายมาอยู่ข้างๆ"),
 ("B", "Miło mi. Skąd pan jest?", "yin dii thîi dâai rúu-jàk khâ maa jàak thîi nǎi khá", "ยินดีที่ได้รู้จักค่ะ มาจากที่ไหนคะ"),
 ("A", "Z Polski, mieszkam tu od roku.", "jàak poo-laen khráp yùu thîi níi maa nùeng pii láew", "จากโปแลนด์ครับ อยู่ที่นี่มาหนึ่งปีแล้ว"),
 ("B", "Mówi pan dobrze po tajsku.", "phûut thai dâai dii ná khá", "พูดไทยได้ดีนะคะ"),
 ("A", "Poprawiaj mnie, proszę, chcę mówić lepiej.", "chûai kâe hâi dûai ná khráp phǒm yàak phûut hâi dii khûen", "ช่วยแก้ให้ด้วยนะครับ ผมอยากพูดให้ดีขึ้น"),
 ("B", "Chętnie. A tak w ogóle — gdzie pan pracuje?", "yin dii khâ wâa tàae wâa tham-ngaan thîi nǎi khá", "ยินดีค่ะ ว่าแต่ว่าทำงานที่ไหนคะ"),
 ("A", "Zdalnie, dla firmy z Europy.", "tham-ngaan thaang-klai hâi bɔɔ-rí-sàt yú-ròhp khráp", "ทำงานทางไกลให้บริษัทยุโรปครับ"),
 ("B", "Gdyby czegoś pan potrzebował, proszę mówić.", "thâa tâwng-kaan à-rai bàwk dâai loei ná khá", "ถ้าต้องการอะไรบอกได้เลยนะคะ"),
 ("A", "Dziękuję, gdzie wyrzuca się śmieci segregowane?", "khàwp-khun khráp thíng khà-yà yâek prà-phêet thîi nǎi khráp", "ขอบคุณครับ ทิ้งขยะแยกประเภทที่ไหนครับ"),
 ("B", "Za bramą, po lewej stronie.", "lǎng prà-tuu thaang sáai khâ", "หลังประตูทางซ้ายค่ะ"),
], "Prośba „chûai kâe hâi dûai” jest konieczna — bez niej Tajowie zwykle nie poprawiają obcokrajowca, żeby go nie zawstydzić."),

("Wyjaśnianie objawów lekarzowi", "Zdrowie", "B2", "Pacjent", "Lekarz", [
 ("A", "Boli mnie przy poruszaniu.", "pùat tawn khà-yàp khráp", "ปวดตอนขยับครับ"),
 ("B", "Od jak dawna to trwa?", "pen maa naan thâo-rài láew khráp", "เป็นมานานเท่าไหร่แล้วครับ"),
 ("A", "Od dwóch tygodni, coraz mocniej.", "sǎwng aa-thít láew khráp nàk khûen rûeai rûeai", "สองอาทิตย์แล้วครับ หนักขึ้นเรื่อยๆ"),
 ("B", "W spoczynku też boli?", "tawn yùu chǒoei chǒoei pùat mǎi khráp", "ตอนอยู่เฉยๆ ปวดไหมครับ"),
 ("A", "Prawie wcale, tylko przy schylaniu.", "kùeap mâi pùat khráp pùat tawn kôm", "เกือบไม่ปวดครับ ปวดตอนก้ม"),
 ("B", "Brał pan coś przeciwbólowego?", "kin yaa kâe pùat mǎi khráp", "กินยาแก้ปวดไหมครับ"),
 ("A", "Tak, pomaga na kilka godzin.", "kin khráp chûai dâai sǎwng sǎam chûa-moong", "กินครับ ช่วยได้สองสามชั่วโมง"),
 ("B", "Zrobimy zdjęcie i zobaczymy.", "jà èks-reet duu kàwn khráp", "จะเอกซเรย์ดูก่อนครับ"),
 ("A", "Czy moje ubezpieczenie to pokryje?", "prà-kan khǎwng phǒm khrâwp khlum mǎi khráp", "ประกันของผมครอบคลุมไหมครับ"),
 ("B", "Recepcja sprawdzi przed badaniem.", "phà-nàek tâwn ráp jà trùat sàwp hâi kàwn khráp", "แผนกต้อนรับจะตรวจสอบให้ก่อนครับ"),
], "Precyzja opisu bólu — kiedy, jak długo, co pomaga — skraca diagnozę bardziej niż bogate słownictwo medyczne."),

("Negocjowanie czynszu przy przedłużeniu", "Dom i codzienność", "B2", "Najemca", "Właściciel", [
 ("A", "Chcę przedłużyć umowę na kolejny rok.", "phǒm yàak tàw sǎn-yaa ìik nùeng pii khráp", "ผมอยากต่อสัญญาอีกหนึ่งปีครับ"),
 ("B", "Cieszę się, ale czynsz idzie w górę.", "dii jai khráp tàae khâa châo khûen nòi", "ดีใจครับ แต่ค่าเช่าขึ้นหน่อย"),
 ("A", "O ile dokładnie?", "khûen thâo-rài khráp", "ขึ้นเท่าไหร่ครับ"),
 ("B", "O tysiąc miesięcznie.", "duean lá nùeng phan khráp", "เดือนละหนึ่งพันครับ"),
 ("A", "To raczej odrobinę za dużo naraz.", "man khâwn khâang jà yóe pai nòi khráp", "มันค่อนข้างจะเยอะไปหน่อยครับ"),
 ("B", "Ceny wszędzie wzrosły.", "raa-khaa khûen thúk thîi khráp", "ราคาขึ้นทุกที่ครับ"),
 ("A", "Zgadzam się co do zasady, ale płacę zawsze na czas.", "lák kaan phǒm hěn dûai khráp tàae phǒm jàai trong wee-laa sà-mǒoe", "หลักการผมเห็นด้วยครับ แต่ผมจ่ายตรงเวลาเสมอ"),
 ("B", "To prawda, nigdy nie było problemu.", "jing khráp mâi khoei mii pan-hǎa", "จริงครับ ไม่เคยมีปัญหา"),
 ("A", "Może pięćset i podpiszemy na dwa lata?", "hâa ráwi láew sen sǎwng pii dii mǎi khráp", "ห้าร้อยแล้วเซ็นสองปีดีไหมครับ"),
 ("B", "Zgoda, umowa stoi.", "tòk long taam nán khráp", "ตกลงตามนั้นครับ"),
], "Argument z historii płatności działa w Tajlandii mocniej niż porównanie cen. Dobry najemca to dla właściciela wartość sama w sobie."),

("Zgubiony bagaż na lotnisku", "Transport", "B2", "Pasażer", "Obsługa", [
 ("A", "Moja walizka nie przyjechała.", "krà-pǎo phǒm mâi maa khráp", "กระเป๋าผมไม่มาครับ"),
 ("B", "Poproszę kartę pokładową i kwit bagażowy.", "khǎw bàt khûen khrûeang kàp bai ráp krà-pǎo khráp", "ขอบัตรขึ้นเครื่องกับใบรับกระเป๋าครับ"),
 ("A", "Proszę bardzo. Duża, czarna, na kółkach.", "níi khráp bai yài sǐi dam mii lâw", "นี่ครับ ใบใหญ่สีดำมีล้อ"),
 ("B", "Jest coś charakterystycznego?", "mii jùt sǎng-kèet à-rai mǎi khráp", "มีจุดสังเกตอะไรไหมครับ"),
 ("A", "Czerwona wstążka przy uchwycie.", "mii ríp-bîn sǐi daaeng thîi mûe jàp khráp", "มีริบบิ้นสีแดงที่มือจับครับ"),
 ("B", "Sprawdzę i oddzwonię.", "dǐao trùat sàwp láew thoo klàp khráp", "เดี๋ยวตรวจสอบแล้วโทรกลับครับ"),
 ("A", "Kiedy dostanę potwierdzenie?", "jà dâai kaan yuen-yan mûea rài khráp", "จะได้การยืนยันเมื่อไหร่ครับ"),
 ("B", "W ciągu doby, wysyłamy do hotelu.", "phaai-nai yîi sìp sìi chûa-moong sòng thǔeng roong raem khráp", "ภายในยี่สิบสี่ชั่วโมง ส่งถึงโรงแรมครับ"),
 ("A", "Czy dostanę zwrot za rzeczy pierwszej potrzeby?", "bòoek khâa khǎwng jam pen khuen dâai mǎi khráp", "เบิกค่าของจำเป็นคืนได้ไหมครับ"),
 ("B", "Tak, proszę zachować paragony.", "dâai khráp kèp bai-sèt wái dûai", "ได้ครับ เก็บใบเสร็จไว้ด้วย"),
], "„bòoek … khuen” to zwrot kosztów za okazaniem paragonu. Zapamiętaj go razem z „bai-sèt” — bez paragonu nie ma zwrotu."),

("Prośba o ciszę w hotelu późną nocą", "Hotel", "B2", "Gość", "Recepcjonista", [
 ("A", "Dzwonię z pokoju czterysta dwa.", "thoo jàak hâwng sìi ráwi sǎwng khráp", "โทรจากห้องสี่ร้อยสองครับ"),
 ("B", "Słucham, w czym mogę pomóc?", "khráp hâi chûai à-rai dii khráp", "ครับ ให้ช่วยอะไรดีครับ"),
 ("A", "Z sąsiedniego pokoju jest bardzo głośno.", "hâwng khâang khâang sǐang dang mâak khráp", "ห้องข้างๆ เสียงดังมากครับ"),
 ("B", "Od jak dawna?", "pen maa naan thâo-rài láew khráp", "เป็นมานานเท่าไหร่แล้วครับ"),
 ("A", "Od godziny, jest już po pierwszej.", "nùeng chûa-moong láew khráp tii nùeng kwàa", "หนึ่งชั่วโมงแล้วครับ ตีหนึ่งกว่า"),
 ("B", "Przepraszam za niedogodności, wyślę ochronę.", "khǎw à-phai nai khwaam mâi sà-dùak khráp jà sòng yaam khûen pai", "ขออภัยในความไม่สะดวกครับ จะส่งยามขึ้นไป"),
 ("A", "Jeśli to nie pomoże, poproszę o inny pokój.", "thâa yang mâi dii khǎw plìan hâwng khráp", "ถ้ายังไม่ดีขอเปลี่ยนห้องครับ"),
 ("B", "Mamy wolny pokój na szóstym piętrze.", "mii hâwng wâang chán hòk khráp", "มีห้องว่างชั้นหกครับ"),
 ("A", "Dziękuję za szybką reakcję.", "khàwp-khun thîi jàt kaan hâi réw khráp", "ขอบคุณที่จัดการให้เร็วครับ"),
], "„tii nùeng” to pierwsza w nocy. Tajski dzieli dobę na cztery bloki godzinowe — warto to opanować przed nocnym telefonem."),

("Rozmowa o różnicach kulturowych w pracy", "Praca i nauka", "B2", "Obcokrajowiec", "Kolega z pracy", [
 ("A", "Mam pytanie nie na temat.", "khǎw thǎam nâwk rûeang nòi khráp", "ขอถามนอกเรื่องหน่อยครับ"),
 ("B", "Śmiało.", "thǎam dâai loei khráp", "ถามได้เลยครับ"),
 ("A", "Dlaczego nikt nie mówi wprost na zebraniu?", "tham-mai mâi mii khrai phûut trong trong nai thîi prà-chum khráp", "ทำไมไม่มีใครพูดตรงๆ ในที่ประชุมครับ"),
 ("B", "Bo nikt nie chce, żeby ktoś stracił twarz.", "phráw mâi mii khrai yàak hâi khon ùen sǐa nâa khráp", "เพราะไม่มีใครอยากให้คนอื่นเสียหน้าครับ"),
 ("A", "Czyli krytykę mówi się na osobności?", "ngán tì kan tawn sǎwng tàw sǎwng châi mǎi khráp", "งั้นติกันตอนสองต่อสองใช่ไหมครับ"),
 ("B", "Dokładnie tak. To działa lepiej.", "chái loei khráp bàep nán dâi phǒn kwàa", "ใช่เลยครับ แบบนั้นได้ผลกว่า"),
 ("A", "A jak zgłosić problem, żeby nikogo nie urazić?", "láew jà bàwk pan-hǎa yang-ngai hâi mâi mii khrai sǐa jai khráp", "แล้วจะบอกปัญหายังไงให้ไม่มีใครเสียใจครับ"),
 ("B", "Mów o sprawie, nie o osobie.", "phûut thǔeng rûeang mâi tâwng phûut thǔeng khon khráp", "พูดถึงเรื่อง ไม่ต้องพูดถึงคนครับ"),
 ("A", "To bardzo pomocne, dziękuję.", "chûai dâai yóe loei khráp khàwp-khun mâak", "ช่วยได้เยอะเลยครับ ขอบคุณมาก"),
], "„rák-sǎa nâa” i „sǐa nâa” — zachować i stracić twarz — to klucz do zrozumienia całej tajskiej komunikacji zawodowej."),

("Zamawianie z uwzględnieniem alergii", "Restauracja", "B2", "Gość", "Kelner", [
 ("A", "Mam alergię, muszę zapytać o skład.", "phǒm mii aa-kaan pháe tâwng thǎam sùan phà-sǒm khráp", "ผมมีอาการแพ้ ต้องถามส่วนผสมครับ"),
 ("B", "Na co dokładnie pan reaguje?", "pháe à-rai khráp", "แพ้อะไรครับ"),
 ("A", "Na orzeszki ziemne i owoce morza.", "pháe thùa lí-sǒng kàp aa-hǎan tha-lee khráp", "แพ้ถั่วลิสงกับอาหารทะเลครับ"),
 ("B", "To danie zawiera sos rybny.", "aa-hǎan jaan níi mii náam plaa khráp", "อาหารจานนี้มีน้ำปลาครับ"),
 ("A", "Czy da się zrobić bez niego?", "tham bàep mâi sài dâai mǎi khráp", "ทำแบบไม่ใส่ได้ไหมครับ"),
 ("B", "Tak, użyjemy sosu sojowego.", "dâai khráp chái sii-íu thaen", "ได้ครับ ใช้ซีอิ๊วแทน"),
 ("A", "A czy patelnia jest wspólna z owocami morza?", "krà-thá thîi chái yâek jàak aa-hǎan tha-lee mǎi khráp", "กระทะที่ใช้แยกจากอาหารทะเลไหมครับ"),
 ("B", "Powiem kucharzowi, żeby użył osobnej.", "jà bàwk phâw khrua hâi chái krà-thá yâek khráp", "จะบอกพ่อครัวให้ใช้กระทะแยกครับ"),
 ("A", "Dziękuję, to dla mnie ważne.", "khàwp-khun khráp rûeang níi sǎm-khan sǎm-ràp phǒm", "ขอบคุณครับ เรื่องนี้สำคัญสำหรับผม"),
], "Pytanie o wspólną patelnię jest ważniejsze niż pytanie o składniki. Sos rybny jest w większości dań, także tych „bez ryby”."),

("Rezygnacja z usługi abonamentowej", "Zakupy i pieniądze", "B2", "Klient", "Konsultant", [
 ("A", "Chciałbym zrezygnować z abonamentu.", "phǒm yàak yók lôek pàek-kèet khráp", "ผมอยากยกเลิกแพ็กเกจครับ"),
 ("B", "Czy coś było nie tak z usługą?", "mii pan-hǎa rûeang brí-kaan mǎi khráp", "มีปัญหาเรื่องบริการไหมครับ"),
 ("A", "Nie, po prostu się wyprowadzam.", "mâi mii khráp phǒm khâe jà yáai bâan", "ไม่มีครับ ผมแค่จะย้ายบ้าน"),
 ("B", "Możemy przenieść usługę pod nowy adres.", "yáai brí-kaan pai thîi yùu mài dâai khráp", "ย้ายบริการไปที่อยู่ใหม่ได้ครับ"),
 ("A", "Wyjeżdżam z kraju, więc to nie pomoże.", "phǒm jà klàp prà-thêet kâw loei mâi chûai khráp", "ผมจะกลับประเทศ ก็เลยไม่ช่วยครับ"),
 ("B", "Rozumiem. Umowa kończy się za dwa miesiące.", "khâo-jai khráp sǎn-yaa jòp ìik sǎwng duean", "เข้าใจครับ สัญญาจบอีกสองเดือน"),
 ("A", "Czy grozi mi kara za wcześniejsze zerwanie?", "thâa yók lôek kàwn tâwng sǐa khâa pràp mǎi khráp", "ถ้ายกเลิกก่อนต้องเสียค่าปรับไหมครับ"),
 ("B", "Tak, tysiąc pięćset, chyba że dostarczy pan bilet.", "sǐa nùeng phan hâa ráwi khráp yók wén mii tǔa khrûeang bin", "เสียหนึ่งพันห้าร้อยครับ ยกเว้นมีตั๋วเครื่องบิน"),
 ("A", "Mam bilet, wyślę kopię dzisiaj.", "phǒm mii tǔa khráp jà sòng sǎm-nao wan níi", "ผมมีตั๋วครับ จะส่งสำเนาวันนี้"),
 ("B", "Wtedy zwolnimy z opłaty.", "ngán yók wén khâa pràp hâi khráp", "งั้นยกเว้นค่าปรับให้ครับ"),
], "Warto pytać o wyjątki od kary umownej — w Tajlandii bilet lotniczy albo zaświadczenie o wyjeździe często je uruchamia."),

("Rozmowa o planach na przyszły rok", "Small talk", "B2", "Znajomy", "Znajoma", [
 ("A", "Myślisz o zostaniu tu na dłużej?", "khít jà yùu thîi níi yaao yaao mǎi khráp", "คิดจะอยู่ที่นี่ยาวๆ ไหมครับ"),
 ("B", "Prawdę mówiąc, sama nie wiem.", "jing jing láew chǎn kâw mâi nâe-jai khâ", "จริงๆ แล้วฉันก็ไม่แน่ใจค่ะ"),
 ("A", "Co by cię przekonało?", "à-rai jà tham hâi tàt-sǐn jai dâai khráp", "อะไรจะทำให้ตัดสินใจได้ครับ"),
 ("B", "Stabilna praca i dobra szkoła dla dziecka.", "ngaan thîi mân-khong kàp roong rian dii sǎm-ràp lûuk khâ", "งานที่มั่นคงกับโรงเรียนดีสำหรับลูกค่ะ"),
 ("A", "To zależy od dzielnicy, różnie bywa.", "láew tàae yâan khâ tàae lá thîi mâi mǔean kan", "แล้วแต่ย่านค่ะ แต่ละที่ไม่เหมือนกัน"),
 ("B", "Właśnie się nad tym zastanawiałam.", "chǎn kam-lang khít yùu phaw dii khâ", "ฉันกำลังคิดอยู่พอดีค่ะ"),
 ("A", "Krok po kroku dojdziesz do decyzji.", "khôi pen khôi pai khráp dǐao kâw tàt-sǐn jai dâai", "ค่อยเป็นค่อยไปครับ เดี๋ยวก็ตัดสินใจได้"),
 ("B", "Masz rację. Nie ma co się spieszyć.", "khun phûut thùuk khâ mâi tâwng rîip", "คุณพูดถูกค่ะ ไม่ต้องรีบ"),
 ("A", "Trzymajmy kontakt, dam znać o mieszkaniach.", "tìt tàw kan wái ná khráp mii hâwng jà bàwk", "ติดต่อกันไว้นะครับ มีห้องจะบอก"),
], "Kobieta mówi o sobie „chǎn” i kończy na „khâ”; mężczyzna używa „phǒm” i „khráp”. Ta para form jest widoczna w całym dialogu."),
]
