# -*- coding: utf-8 -*-
"""Leksyka etapu 5 (B2) — czesc E.

Zakres: rozmowy zawodowe i obsluga klienta. Zebrania, raportowanie postepu,
delegowanie, opinia zwrotna, rozmowa z klientem, wyjasnianie problemow
i procedur krok po kroku, jezyk reklamacji po stronie uslugodawcy.

Format jak w lex_b2_core_a.py.
"""

CORE_E = [

# =====================================================================
# ZEBRANIA I RAPORTOWANIE
# =====================================================================
("zwołajmy krótkie spotkanie", "nát prà-chum sân sân kan ná khráp", "นัดประชุมสั้นๆ กันนะครับ",
 "Praca i nauka", "Zebrania", "sentence", 4, "n", "", "",
 ("Zwołajmy krótkie spotkanie po lunchu.", "nát prà-chum sân sân lǎng aa-hǎan klaang wan ná khráp", "นัดประชุมสั้นๆ หลังอาหารกลางวันนะครับ")),
("na czym stanęliśmy ostatnio?", "khráng thîi láew khui thǔeng nǎi khráp", "ครั้งที่แล้วคุยถึงไหนครับ",
 "Praca i nauka", "Zebrania", "sentence", 4, "n", "", "",
 ("Na czym stanęliśmy ostatnio z budżetem?", "rûeang ngóp khráng thîi láew khui thǔeng nǎi khráp", "เรื่องงบครั้งที่แล้วคุยถึงไหนครับ")),
("przejdźmy do punktu drugiego", "khâo khâw thîi sǎwng khráp", "เข้าข้อที่สองครับ", "Praca i nauka", "Zebrania", "sentence", 3, "f", "", "",
 ("Przejdźmy do punktu drugiego, czasu mało.", "khâo khâw thîi sǎwng khráp wee-laa mâi mâak", "เข้าข้อที่สองครับ เวลาไม่มาก")),
("jak wygląda postęp prac?", "khwaam khûep nâa pen yang-ngai bâang khráp", "ความคืบหน้าเป็นยังไงบ้างครับ",
 "Praca i nauka", "Zebrania", "sentence", 4, "f",
 "„khwaam khûep nâa” = postęp. Podstawowe słowo w tajskim raportowaniu.", "",
 ("Jak wygląda postęp prac przy pierwszym etapie?", "fâet râek khwaam khûep nâa pen yang-ngai bâang khráp", "เฟสแรกความคืบหน้าเป็นยังไงบ้างครับ")),
("jesteśmy w połowie", "tham pai dâai khrûeng nùeng láew khráp", "ทำไปได้ครึ่งหนึ่งแล้วครับ",
 "Praca i nauka", "Zebrania", "sentence", 4, "n", "", "",
 ("Jesteśmy w połowie, reszta do piątku.", "tham pai dâai khrûeng nùeng láew khráp thîi lǔea sèt wan sùk", "ทำไปได้ครึ่งหนึ่งแล้วครับ ที่เหลือเสร็จวันศุกร์")),
("mamy opóźnienie dwóch dni", "cháa kwàa kam-nòt sǎwng wan khráp", "ช้ากว่ากำหนดสองวันครับ",
 "Praca i nauka", "Zebrania", "sentence", 4, "n",
 "Zgłaszaj opóźnienie z liczbą — bez niej Taj usłyszy „trochę później” i nie zareaguje.", "",
 ("Mamy opóźnienie dwóch dni z powodu dostawy.", "cháa kwàa kam-nòt sǎwng wan phráw khǎwng maa cháa khráp", "ช้ากว่ากำหนดสองวันเพราะของมาช้าครับ")),
("zdążymy na czas", "sèt than kam-nòt nâe nawn khráp", "เสร็จทันกำหนดแน่นอนครับ",
 "Praca i nauka", "Zebrania", "sentence", 4, "n", "", "",
 ("Zdążymy na czas, jeśli dostaniemy dane dziś.", "sèt than kam-nòt nâe nawn khráp thâa dâai khâw-muun wan níi", "เสร็จทันกำหนดแน่นอนครับ ถ้าได้ข้อมูลวันนี้")),
("potrzebuję więcej zasobów", "khǎw khon phôoem ìik khráp", "ขอคนเพิ่มอีกครับ", "Praca i nauka", "Zebrania", "sentence", 3, "n", "", "",
 ("Potrzebuję więcej zasobów, dwie osoby wystarczą.", "khǎw khon phôoem ìik sǎwng khon kâw phaw khráp", "ขอคนเพิ่มอีกสองคนก็พอครับ")),
("kto to przejmie?", "khrai jà ráp chûang tàw khráp", "ใครจะรับช่วงต่อครับ", "Praca i nauka", "Zebrania", "sentence", 3, "f",
 "„ráp chûang tàw” = przejąć po kimś zadanie. Częste przy przekazywaniu obowiązków.", "",
 ("Kto to przejmie na czas mojego urlopu?", "tawn phǒm laa phák khrai jà ráp chûang tàw khráp", "ตอนผมลาพักใครจะรับช่วงต่อครับ")),
("podsumuję ustalenia i wyślę", "dǐao sà-rùp láew sòng hâi khráp", "เดี๋ยวสรุปแล้วส่งให้ครับ",
 "Praca i nauka", "Zebrania", "sentence", 4, "n", "", "",
 ("Podsumuję ustalenia i wyślę wszystkim wieczorem.", "dǐao sà-rùp láew sòng hâi thúk khon tawn yen khráp", "เดี๋ยวสรุปแล้วส่งให้ทุกคนตอนเย็นครับ")),

# =====================================================================
# DELEGOWANIE I USTALANIE ODPOWIEDZIALNOSCI
# =====================================================================
("mógłbyś się tym zająć?", "chûai duu rûeang níi hâi nòi dâai mǎi khráp", "ช่วยดูเรื่องนี้ให้หน่อยได้ไหมครับ",
 "Praca i nauka", "Delegowanie", "sentence", 5, "n", "", "",
 ("Mógłbyś się tym zająć do środy?", "chûai duu rûeang níi hâi kàwn wan phút dâai mǎi khráp", "ช่วยดูเรื่องนี้ให้ก่อนวันพุธได้ไหมครับ")),
("zostawiam to w twoich rękach", "fàak wái kàp khun ná khráp", "ฝากไว้กับคุณนะครับ", "Praca i nauka", "Delegowanie", "sentence", 4, "n",
 "„fàak” = powierzyć. Bardzo ciepłe słowo, buduje zaufanie w zespole.", "",
 ("Zostawiam to w twoich rękach, ufam ci.", "fàak wái kàp khun ná khráp phǒm wái jai", "ฝากไว้กับคุณนะครับ ผมไว้ใจ")),
("dokładnie czego oczekujesz?", "khun tâwng-kaan hâi tham à-rai bâang khráp", "คุณต้องการให้ทำอะไรบ้างครับ",
 "Praca i nauka", "Delegowanie", "sentence", 4, "n", "", "",
 ("Dokładnie czego oczekujesz ode mnie w tym tygodniu?", "aa-thít níi khun tâwng-kaan hâi phǒm tham à-rai bâang khráp", "อาทิตย์นี้คุณต้องการให้ผมทำอะไรบ้างครับ")),
("do kiedy potrzebujesz?", "tâwng-kaan mûea rài khráp", "ต้องการเมื่อไหร่ครับ", "Praca i nauka", "Delegowanie", "sentence", 5, "n", "", "",
 ("Do kiedy potrzebujesz, żebym to skończył?", "tâwng-kaan hâi sèt mûea rài khráp", "ต้องการให้เสร็จเมื่อไหร่ครับ")),
("zrobię to, ale nie dziś", "tham hâi dâai khráp tàae mâi châi wan níi", "ทำให้ได้ครับ แต่ไม่ใช่วันนี้",
 "Praca i nauka", "Delegowanie", "sentence", 4, "n", "", "",
 ("Zrobię to, ale nie dziś — jutro rano.", "tham hâi dâai khráp tàae mâi châi wan níi phrûng-níi cháo", "ทำให้ได้ครับ แต่ไม่ใช่วันนี้ พรุ่งนี้เช้า")),
("to nie leży w moim zakresie", "an níi mâi yùu nai nâa thîi phǒm khráp", "อันนี้ไม่อยู่ในหน้าที่ผมครับ",
 "Praca i nauka", "Delegowanie", "sentence", 3, "f",
 "„nâa thîi” = obowiązki służbowe. Zdanie brzmi twardo — dodaj propozycję, kto się tym zajmie.", "",
 ("To nie leży w moim zakresie, ale zapytam kogo dotyczy.", "an níi mâi yùu nai nâa thîi phǒm khráp dǐao thǎam hâi wâa khrai duu-lae", "อันนี้ไม่อยู่ในหน้าที่ผมครับ เดี๋ยวถามให้ว่าใครดูแล")),
("przekażę to dalej", "dǐao sòng tàw hâi khráp", "เดี๋ยวส่งต่อให้ครับ", "Praca i nauka", "Delegowanie", "sentence", 5, "n", "", "",
 ("Przekażę to dalej do działu technicznego.", "dǐao sòng tàw hâi fàai thék-nìk khráp", "เดี๋ยวส่งต่อให้ฝ่ายเทคนิคครับ")),
("potrzebuję twojej akceptacji", "khǎw kaan à-nú-mát jàak khun khráp", "ขอการอนุมัติจากคุณครับ",
 "Praca i nauka", "Delegowanie", "sentence", 3, "f",
 "„à-nú-mát” = zatwierdzenie. Kluczowe słowo w każdej tajskiej firmie i urzędzie.", "",
 ("Potrzebuję twojej akceptacji przed wysłaniem.", "khǎw kaan à-nú-mát jàak khun kàwn sòng khráp", "ขอการอนุมัติจากคุณก่อนส่งครับ")),
("zajmę się tym osobiście", "phǒm jà duu eeng khráp", "ผมจะดูเองครับ", "Praca i nauka", "Delegowanie", "sentence", 4, "n", "", "",
 ("Zajmę się tym osobiście, żeby nie było pomyłki.", "phǒm jà duu eeng khráp jà dâai mâi phìt phlâat", "ผมจะดูเองครับ จะได้ไม่ผิดพลาด")),

# =====================================================================
# OPINIA ZWROTNA
# =====================================================================
("dobra robota, naprawdę", "tham dâai dii mâak khráp", "ทำได้ดีมากครับ", "Praca i nauka", "Opinia zwrotna", "sentence", 5, "n", "", "",
 ("Dobra robota, naprawdę, klient był zadowolony.", "tham dâai dii mâak khráp lûuk-kháa phaw jai", "ทำได้ดีมากครับ ลูกค้าพอใจ")),
("jedna rzecz do poprawy", "mii nùeng jùt thîi kâe dâai khráp", "มีหนึ่งจุดที่แก้ได้ครับ",
 "Praca i nauka", "Opinia zwrotna", "sentence", 4, "n",
 "Krytykę w Tajlandii podaje się pojedynczo i po pochwale. Lista wad zostanie odebrana jako atak.", "",
 ("Jedna rzecz do poprawy: format daty.", "mii nùeng jùt thîi kâe dâai khráp rûup bàep wan thîi", "มีหนึ่งจุดที่แก้ได้ครับ รูปแบบวันที่")),
("następnym razem zrób to wcześniej", "khráng nâa tham hâi réw khûen nòi ná khráp", "ครั้งหน้าทำให้เร็วขึ้นหน่อยนะครับ",
 "Praca i nauka", "Opinia zwrotna", "sentence", 4, "n", "", "",
 ("Następnym razem zrób to wcześniej, unikniemy stresu.", "khráng nâa tham hâi réw khûen nòi ná khráp jà dâai mâi khrîat", "ครั้งหน้าทำให้เร็วขึ้นหน่อยนะครับ จะได้ไม่เครียด")),
("doceniam twoje zaangażowanie", "phǒm hěn khwaam tâng-jai khǎwng khun khráp", "ผมเห็นความตั้งใจของคุณครับ",
 "Praca i nauka", "Opinia zwrotna", "sentence", 4, "f", "", "",
 ("Doceniam twoje zaangażowanie w ostatnich tygodniach.", "phǒm hěn khwaam tâng-jai khǎwng khun chûang níi khráp", "ผมเห็นความตั้งใจของคุณช่วงนี้ครับ")),
("chciałbym usłyszeć twoją opinię o mnie", "yàak fang khwaam hěn khǎwng khun rûeang phǒm khráp", "อยากฟังความเห็นของคุณเรื่องผมครับ",
 "Praca i nauka", "Opinia zwrotna", "sentence", 3, "f", "", "",
 ("Chciałbym usłyszeć twoją opinię o mnie jako szefie.", "yàak fang khwaam hěn khǎwng khun rûeang phǒm nai thǎa-ná hǔa-nâa khráp", "อยากฟังความเห็นของคุณเรื่องผมในฐานะหัวหน้าครับ")),
("przyjmuję uwagę", "ráp fang khráp jà pai kâe", "รับฟังครับ จะไปแก้", "Praca i nauka", "Opinia zwrotna", "sentence", 4, "n", "", "",
 ("Przyjmuję uwagę, poprawię do jutra.", "ráp fang khráp jà pai kâe hâi kàwn phrûng-níi", "รับฟังครับ จะไปแก้ให้ก่อนพรุ่งนี้")),
("to była moja pomyłka w liczbach", "phǒm khít tua lêek phìt eeng khráp", "ผมคิดตัวเลขผิดเองครับ",
 "Praca i nauka", "Opinia zwrotna", "sentence", 3, "n", "", "",
 ("To była moja pomyłka w liczbach, już poprawione.", "phǒm khít tua lêek phìt eeng khráp kâe riap ráwi láew", "ผมคิดตัวเลขผิดเองครับ แก้เรียบร้อยแล้ว")),
("nie chcę cię krytykować, tylko pomóc", "mâi dâai tì ná khráp yàak chûai", "ไม่ได้ตินะครับ อยากช่วย",
 "Praca i nauka", "Opinia zwrotna", "sentence", 4, "n",
 "„tì” = czepiać się, krytykować. Uprzedzenie tym słowem chroni rozmówcę przed utratą twarzy.", "",
 ("Nie chcę cię krytykować, tylko pomóc to dopracować.", "mâi dâai tì ná khráp yàak chûai hâi man dii khûen", "ไม่ได้ตินะครับ อยากช่วยให้มันดีขึ้น")),

# =====================================================================
# ROZMOWA Z KLIENTEM
# =====================================================================
("w czym mogę pomóc?", "hâi chûai à-rai dii khráp", "ให้ช่วยอะไรดีครับ", "Praca i nauka", "Klient", "sentence", 5, "f", "", "",
 ("Dzień dobry, w czym mogę pomóc?", "sà-wàt-dii khráp hâi chûai à-rai dii khráp", "สวัสดีครับ ให้ช่วยอะไรดีครับ")),
("proszę mi opisać problem", "chûai lâo pan-hǎa hâi fang nòi khráp", "ช่วยเล่าปัญหาให้ฟังหน่อยครับ",
 "Praca i nauka", "Klient", "sentence", 4, "f", "", "",
 ("Proszę mi opisać problem od początku.", "chûai lâo pan-hǎa tâng tàae râek hâi fang nòi khráp", "ช่วยเล่าปัญหาตั้งแต่แรกให้ฟังหน่อยครับ")),
("rozumiem pana frustrację", "phǒm khâo-jai khwaam rúu-sùek khǎwng khun khráp", "ผมเข้าใจความรู้สึกของคุณครับ",
 "Praca i nauka", "Klient", "sentence", 4, "f",
 "Uznanie emocji przed rozwiązaniem. W obsłudze klienta obowiązkowe.", "",
 ("Rozumiem pana frustrację, zajmę się tym natychmiast.", "phǒm khâo-jai khwaam rúu-sùek khǎwng khun khráp dǐao jàt kaan hâi than-thii", "ผมเข้าใจความรู้สึกของคุณครับ เดี๋ยวจัดการให้ทันที")),
("przepraszam za niedogodności", "khǎw à-phai nai khwaam mâi sà-dùak khráp", "ขออภัยในความไม่สะดวกครับ",
 "Praca i nauka", "Klient", "sentence", 4, "f",
 "Formuła z komunikatów publicznych. Usłyszysz ją na dworcach i w bankach.", "",
 ("Przepraszam za niedogodności, system był wyłączony.", "khǎw à-phai nai khwaam mâi sà-dùak khráp rá-bòp pìt prap prung", "ขออภัยในความไม่สะดวกครับ ระบบปิดปรับปรุง")),
("sprawdzę to i oddzwonię", "dǐao chék hâi láew thoo klàp khráp", "เดี๋ยวเช็คให้แล้วโทรกลับครับ",
 "Praca i nauka", "Klient", "sentence", 5, "f", "", "",
 ("Sprawdzę to i oddzwonię w ciągu godziny.", "dǐao chék hâi láew thoo klàp phaai-nai nùeng chûa-moong khráp", "เดี๋ยวเช็คให้แล้วโทรกลับภายในหนึ่งชั่วโมงครับ")),
("proszę o numer zamówienia", "khǎw lêek thîi kaan sàng súe khráp", "ขอเลขที่การสั่งซื้อครับ",
 "Praca i nauka", "Klient", "sentence", 4, "f", "", "",
 ("Proszę o numer zamówienia, sprawdzę status.", "khǎw lêek thîi kaan sàng súe khráp dǐao chék sà-thǎa-ná hâi", "ขอเลขที่การสั่งซื้อครับ เดี๋ยวเช็คสถานะให้")),
("mamy dwa rozwiązania do wyboru", "mii sǎwng thaang lûeak khráp", "มีสองทางเลือกครับ",
 "Praca i nauka", "Klient", "sentence", 4, "f", "", "",
 ("Mamy dwa rozwiązania do wyboru: wymiana albo zwrot.", "mii sǎwng thaang lûeak khráp plìan an mài rǔe khuen ngoen", "มีสองทางเลือกครับ เปลี่ยนอันใหม่หรือคืนเงิน")),
("zwrócimy pieniądze w ciągu tygodnia", "khuen ngoen phaai-nai nùeng aa-thít khráp", "คืนเงินภายในหนึ่งอาทิตย์ครับ",
 "Zakupy i pieniądze", "Klient", "sentence", 4, "f", "", "",
 ("Zwrócimy pieniądze w ciągu tygodnia na to samo konto.", "khuen ngoen phaai-nai nùeng aa-thít khâo ban-chii doem khráp", "คืนเงินภายในหนึ่งอาทิตย์เข้าบัญชีเดิมครับ")),
("czy jest pan zadowolony z rozwiązania?", "khun phaw jai kàp thaang àwk níi mǎi khráp", "คุณพอใจกับทางออกนี้ไหมครับ",
 "Praca i nauka", "Klient", "sentence", 4, "f", "", "",
 ("Czy jest pan zadowolony z rozwiązania, które proponuję?", "khun phaw jai kàp thaang àwk thîi phǒm sà-nǒoe mǎi khráp", "คุณพอใจกับทางออกที่ผมเสนอไหมครับ")),
("dziękujemy za wyrozumiałość", "khàwp-khun thîi hâi oo-kàat khráp", "ขอบคุณที่ให้โอกาสครับ",
 "Praca i nauka", "Klient", "sentence", 4, "f", "", "",
 ("Dziękujemy za wyrozumiałość i za powrót do nas.", "khàwp-khun thîi hâi oo-kàat láe klàp maa chái brí-kaan khráp", "ขอบคุณที่ให้โอกาสและกลับมาใช้บริการครับ")),
("proszę zachować paragon", "kèp bai-sèt wái dûai ná khráp", "เก็บใบเสร็จไว้ด้วยนะครับ",
 "Zakupy i pieniądze", "Klient", "sentence", 4, "n", "", "",
 ("Proszę zachować paragon, będzie potrzebny do reklamacji.", "kèp bai-sèt wái dûai ná khráp tâwng chái tawn khleem", "เก็บใบเสร็จไว้ด้วยนะครับ ต้องใช้ตอนเคลม")),
("gwarancja obejmuje rok", "prà-kan nùeng pii khráp", "ประกันหนึ่งปีครับ", "Zakupy i pieniądze", "Klient", "sentence", 4, "n", "", "",
 ("Gwarancja obejmuje rok od daty zakupu.", "prà-kan nùeng pii náp jàak wan thîi súe khráp", "ประกันหนึ่งปีนับจากวันที่ซื้อครับ")),

# =====================================================================
# WYJASNIANIE PROCEDUR
# =====================================================================
("wyjaśnię krok po kroku", "phǒm jà à-thí-baai pen khân tawn khráp", "ผมจะอธิบายเป็นขั้นตอนครับ",
 "Praca i nauka", "Procedury", "sentence", 4, "f",
 "„khân tawn” = etap procedury. Słowo obowiązkowe w urzędzie i w banku.", "",
 ("Wyjaśnię krok po kroku, proszę pytać w razie czego.", "phǒm jà à-thí-baai pen khân tawn khráp mâi khâo-jai thǎam dâai", "ผมจะอธิบายเป็นขั้นตอนครับ ไม่เข้าใจถามได้")),
("najpierw trzeba złożyć wniosek", "khân râek tâwng yûen khâm rǎwng kàwn khráp", "ขั้นแรกต้องยื่นคำร้องก่อนครับ",
 "Praca i nauka", "Procedury", "sentence", 4, "f",
 "„yûen khâm rǎwng” = złożyć podanie. Zapamiętaj razem — to jedna całość w urzędzie.", "",
 ("Najpierw trzeba złożyć wniosek, potem czekać na termin.", "khân râek tâwng yûen khâm rǎwng kàwn láew khôi raw nát khráp", "ขั้นแรกต้องยื่นคำร้องก่อน แล้วค่อยรอนัดครับ")),
("potem dostanie pan potwierdzenie", "jàak nán jà dâai bai ráp khráp", "จากนั้นจะได้ใบรับครับ",
 "Praca i nauka", "Procedury", "sentence", 3, "f", "", "",
 ("Potem dostanie pan potwierdzenie z numerem sprawy.", "jàak nán jà dâai bai ráp phráwm lêek thîi khráp", "จากนั้นจะได้ใบรับพร้อมเลขที่ครับ")),
("na końcu trzeba odebrać dokument", "khân sùt tháai maa ráp èek-kà-sǎan khráp", "ขั้นสุดท้ายมารับเอกสารครับ",
 "Praca i nauka", "Procedury", "sentence", 3, "f", "", "",
 ("Na końcu trzeba odebrać dokument osobiście.", "khân sùt tháai tâwng maa ráp èek-kà-sǎan dûai tua eeng khráp", "ขั้นสุดท้ายต้องมารับเอกสารด้วยตัวเองครับ")),
("to zajmuje zwykle trzy dni robocze", "pòk-kà-tì chái wee-laa sǎam wan tham-kaan khráp", "ปกติใช้เวลาสามวันทำการครับ",
 "Praca i nauka", "Procedury", "sentence", 4, "f",
 "„wan tham-kaan” = dzień roboczy. Bez tego słowa urzędnik policzy też weekend.", "",
 ("To zajmuje zwykle trzy dni robocze, bez weekendu.", "pòk-kà-tì chái wee-laa sǎam wan tham-kaan mâi náp sǎo aa-thít khráp", "ปกติใช้เวลาสามวันทำการ ไม่นับเสาร์อาทิตย์ครับ")),
("jakich dokumentów potrzeba?", "tâwng chái èek-kà-sǎan à-rai bâang khráp", "ต้องใช้เอกสารอะไรบ้างครับ",
 "Praca i nauka", "Procedury", "sentence", 5, "f", "", "",
 ("Jakich dokumentów potrzeba do przedłużenia?", "tàw aa-yú tâwng chái èek-kà-sǎan à-rai bâang khráp", "ต่ออายุต้องใช้เอกสารอะไรบ้างครับ")),
("czy kopia wystarczy?", "chái sǎm-nao dâai mǎi khráp", "ใช้สำเนาได้ไหมครับ", "Praca i nauka", "Procedury", "sentence", 4, "f",
 "„sǎm-nao” = kopia dokumentu. W Tajlandii często wymagany jest też podpis na każdej kopii.", "",
 ("Czy kopia wystarczy, czy potrzebny oryginał?", "chái sǎm-nao dâai mǎi khráp rǔe tâwng chái tua jing", "ใช้สำเนาได้ไหมครับ หรือต้องใช้ตัวจริง")),
("gdzie się to składa?", "yûen thîi nǎi khráp", "ยื่นที่ไหนครับ", "Praca i nauka", "Procedury", "sentence", 4, "f", "", "",
 ("Gdzie się to składa — tutaj czy w innym okienku?", "yûen thîi nǎi khráp thîi nîi rǔe châwng ùen", "ยื่นที่ไหนครับ ที่นี่หรือช่องอื่น")),
("ile to kosztuje?", "khâa tham-niam thâo-rài khráp", "ค่าธรรมเนียมเท่าไหร่ครับ",
 "Zakupy i pieniądze", "Procedury", "sentence", 5, "f",
 "„khâa tham-niam” = opłata urzędowa. Inne słowo niż zwykłe „raa-khaa”.", "",
 ("Ile to kosztuje i czy płaci się gotówką?", "khâa tham-niam thâo-rài khráp láe jàai ngoen sòt mǎi", "ค่าธรรมเนียมเท่าไหร่ครับ และจ่ายเงินสดไหม")),
("czy można to zrobić przez internet?", "tham àwn-lai dâai mǎi khráp", "ทำออนไลน์ได้ไหมครับ",
 "Praca i nauka", "Procedury", "sentence", 4, "n", "", "",
 ("Czy można to zrobić przez internet, żeby nie jechać?", "tham àwn-lai dâai mǎi khráp jà dâai mâi tâwng maa", "ทำออนไลน์ได้ไหมครับ จะได้ไม่ต้องมา")),
("czy trzeba umówić wizytę?", "tâwng nát lûang nâa mǎi khráp", "ต้องนัดล่วงหน้าไหมครับ",
 "Praca i nauka", "Procedury", "sentence", 4, "f", "", "",
 ("Czy trzeba umówić wizytę, czy można przyjść?", "tâwng nát lûang nâa mǎi khráp rǔe maa dâai loei", "ต้องนัดล่วงหน้าไหมครับ หรือมาได้เลย")),
("proszę wypełnić tę część", "chûai kràwk sùan níi khráp", "ช่วยกรอกส่วนนี้ครับ", "Praca i nauka", "Procedury", "sentence", 4, "f",
 "„kràwk” = wypełnić formularz. Usłyszysz to przy każdym okienku.", "",
 ("Proszę wypełnić tę część i podpisać na dole.", "chûai kràwk sùan níi láew sen khâang lâang khráp", "ช่วยกรอกส่วนนี้แล้วเซ็นข้างล่างครับ")),
("czego brakuje w moich dokumentach?", "èek-kà-sǎan phǒm khàat à-rai bâang khráp", "เอกสารผมขาดอะไรบ้างครับ",
 "Praca i nauka", "Procedury", "sentence", 4, "f", "", "",
 ("Czego brakuje w moich dokumentach, żebym doniósł raz?", "èek-kà-sǎan phǒm khàat à-rai bâang khráp jà dâai maa khráng diao", "เอกสารผมขาดอะไรบ้างครับ จะได้มาครั้งเดียว")),

# =====================================================================
# WYJASNIANIE PROBLEMU TECHNICZNEGO
# =====================================================================
("problem polega na tym, że", "pan-hǎa khue wâa", "ปัญหาคือว่า", "Praca i nauka", "Wyjaśnianie", "phrase", 5, "n", "", "",
 ("Problem polega na tym, że system nie zapisuje danych.", "pan-hǎa khue wâa rá-bòp mâi bantúek khâw-muun khráp", "ปัญหาคือว่าระบบไม่บันทึกข้อมูลครับ")),
("zaczęło się wczoraj wieczorem", "rôoem pen tâng tàae mûea khuen khráp", "เริ่มเป็นตั้งแต่เมื่อคืนครับ",
 "Praca i nauka", "Wyjaśnianie", "sentence", 4, "n", "", "",
 ("Zaczęło się wczoraj wieczorem, wcześniej działało.", "rôoem pen tâng tàae mûea khuen khráp kàwn nâa nán pòk-kà-tì", "เริ่มเป็นตั้งแต่เมื่อคืนครับ ก่อนหน้านั้นปกติ")),
("dzieje się to tylko czasami", "pen baang khráng thâo nán khráp", "เป็นบางครั้งเท่านั้นครับ",
 "Praca i nauka", "Wyjaśnianie", "sentence", 4, "n",
 "Rozróżnienie „zawsze / czasami” jest pierwszym pytaniem każdego serwisanta. Warto mieć je gotowe.", "",
 ("Dzieje się to tylko czasami, głównie rano.", "pen baang khráng thâo nán khráp sùan yài tawn cháo", "เป็นบางครั้งเท่านั้นครับ ส่วนใหญ่ตอนเช้า")),
("próbowałem już wszystkiego", "phǒm lawng maa mòt láew khráp", "ผมลองมาหมดแล้วครับ",
 "Praca i nauka", "Wyjaśnianie", "sentence", 4, "n", "", "",
 ("Próbowałem już wszystkiego, restart nie pomaga.", "phǒm lawng maa mòt láew khráp rîi-sàat kâw mâi chûai", "ผมลองมาหมดแล้วครับ รีสตาร์ทก็ไม่ช่วย")),
("podejrzewam, że przyczyną jest", "phǒm sǒng-sǎi wâa sǎa-hèet khue", "ผมสงสัยว่าสาเหตุคือ",
 "Praca i nauka", "Wyjaśnianie", "phrase", 3, "f",
 "„sǎa-hèet” = przyczyna. Formalniejsze niż „phráw”, dobre przy zgłoszeniu serwisowym.", "",
 ("Podejrzewam, że przyczyną jest stara instalacja.", "phǒm sǒng-sǎi wâa sǎa-hèet khue rá-bòp fai kào khráp", "ผมสงสัยว่าสาเหตุคือระบบไฟเก่าครับ")),
("to nie jest wina użytkownika", "mâi châi khwaam phìt khǎwng phûu chái khráp", "ไม่ใช่ความผิดของผู้ใช้ครับ",
 "Praca i nauka", "Wyjaśnianie", "sentence", 3, "f", "", "",
 ("To nie jest wina użytkownika, tylko konfiguracji.", "mâi châi khwaam phìt khǎwng phûu chái khráp pen thîi kaan tâng khâa", "ไม่ใช่ความผิดของผู้ใช้ครับ เป็นที่การตั้งค่า")),
("da się to naprawić na miejscu?", "sâwm thîi nîi loei dâai mǎi khráp", "ซ่อมที่นี่เลยได้ไหมครับ",
 "Dom i codzienność", "Wyjaśnianie", "sentence", 4, "n", "", "",
 ("Da się to naprawić na miejscu, czy zabieracie do serwisu?", "sâwm thîi nîi loei dâai mǎi khráp rǔe tâwng ao khâo suun", "ซ่อมที่นี่เลยได้ไหมครับ หรือต้องเอาเข้าศูนย์")),
("ile potrwa naprawa?", "sâwm chái wee-laa naan thâo-rài khráp", "ซ่อมใช้เวลานานเท่าไหร่ครับ",
 "Dom i codzienność", "Wyjaśnianie", "sentence", 4, "n", "", "",
 ("Ile potrwa naprawa i ile będzie kosztować?", "sâwm chái wee-laa naan thâo-rài láe khâa sâwm thâo-rài khráp", "ซ่อมใช้เวลานานเท่าไหร่และค่าซ่อมเท่าไหร่ครับ")),
("proszę o wycenę przed naprawą", "khǎw prà-mâan raa-khaa kàwn sâwm khráp", "ขอประมาณราคาก่อนซ่อมครับ",
 "Dom i codzienność", "Wyjaśnianie", "sentence", 4, "f",
 "Bez tej prośby rachunek bywa niespodzianką. Warto ją wypowiedzieć zawsze.", "",
 ("Proszę o wycenę przed naprawą, potem zdecyduję.", "khǎw prà-mâan raa-khaa kàwn sâwm khráp láew khôi tàt-sǐn jai", "ขอประมาณราคาก่อนซ่อมครับ แล้วค่อยตัดสินใจ")),
("czy to się może powtórzyć?", "man jà pen ìik mǎi khráp", "มันจะเป็นอีกไหมครับ", "Praca i nauka", "Wyjaśnianie", "sentence", 3, "n", "", "",
 ("Czy to się może powtórzyć po naprawie?", "lǎng sâwm láew man jà pen ìik mǎi khráp", "หลังซ่อมแล้วมันจะเป็นอีกไหมครับ")),
]
