# -*- coding: utf-8 -*-
"""Sesja F — CZASOWNIKI III: percepcja, relacje, obsluga, ruch przedmiotow."""

CZ = "Czasowniki"

VERBS_C = [

# --------------------------------------------------------------- percepcja
("A2", "zauważyć", "sǎng-kèet hěn", "สังเกตเห็น", CZ, "Percepcja", 3, "n",
 "„sǎng-kèet” samo znaczy obserwować, przyglądać się uważnie.",
 "obserwować widzieć",
 [("Zauważyłem, że jest zamknięte.", "phǒm sǎng-kèet hěn wâa pìt khráp", "ผมสังเกตเห็นว่าปิดครับ"),
  ("Nie zauważyłem.", "phǒm mâi dâai sǎng-kèet khráp", "ผมไม่ได้สังเกตครับ")],
 ["widzieć", "patrzeć"], []),

("A2", "szukać", "hǎa", "หา", CZ, "Percepcja", 5, "n",
 "„hǎa” to szukać i odwiedzać kogoś: „pai hǎa phûean” — pójść do przyjaciela.",
 "",
 [("Szukam hotelu.", "phǒm hǎa roong raem khráp", "ผมหาโรงแรมครับ"),
  ("Nie mogę tego znaleźć.", "phǒm hǎa mâi jooe khráp", "ผมหาไม่เจอครับ")],
 ["znajdować", "gubić"], []),

("A2", "znajdować", "jooe", "เจอ", CZ, "Percepcja", 5, "p",
 "„jooe” to zarazem znaleźć i spotkać kogoś: „jooe kan phrûng-níi” — do jutra.",
 "",
 [("Znalazłem.", "phǒm jooe láew khráp", "ผมเจอแล้วครับ"),
  ("Do zobaczenia jutro.", "jooe kan phrûng-níi khráp", "เจอกันพรุ่งนี้ครับ")],
 ["szukać", "spotykać się"], ["spotkać"]),

("A2", "słyszeć", "dâi yin", "ได้ยิน", CZ, "Percepcja", 4, "n",
 "Różnica od „fang” (słuchać): „dâi yin” to bierne usłyszenie, „fang” to celowe słuchanie.",
 "dostać słyszeć",
 [("Nie słyszę pana.", "phǒm mâi dâi yin khráp", "ผมไม่ได้ยินครับ"),
  ("Słyszałem, że jest tanio.", "phǒm dâi yin wâa thùuk khráp", "ผมได้ยินว่าถูกครับ")],
 ["słuchać", "ucho", "głośny"], []),

("A2", "wąchać", "dom", "ดม", CZ, "Percepcja", 2, "n",
 "„hǒm” to przyjemny zapach, „mǐen” to nieprzyjemny — dwa różne słowa na zapach.",
 "",
 [("Powąchaj to.", "lawng dom duu khráp", "ลองดมดูครับ"),
  ("Ładnie pachnie.", "hǒm dii khráp", "หอมดีครับ")],
 ["pachnący", "śmierdzący"], []),

("A2", "dotykać", "tàe", "แตะ", CZ, "Percepcja", 3, "n",
 "Ważna zasada kulturowa: nie dotyka się cudzej głowy, nawet dziecka, i nie wskazuje stopą.",
 "",
 [("Proszę nie dotykać.", "yàa tàe khráp", "อย่าแตะครับ"),
  ("Nie wolno dotykać mnicha.", "tàe phrá mâi dâai khráp", "แตะพระไม่ได้ครับ")],
 ["mnich", "głowa"], []),

# --------------------------------------------------------------- relacje
("A2", "poznawać (kogoś)", "rúu-jàk", "รู้จัก", CZ, "Relacje", 5, "n",
 "Uwaga: „rúu” to wiedzieć o czymś, „rúu-jàk” to znać kogoś lub coś osobiście.",
 "wiedzieć znać",
 [("Znam go.", "phǒm rúu-jàk kháo khráp", "ผมรู้จักเขาครับ"),
  ("Nie znam tego miejsca.", "phǒm mâi rúu-jàk thîi nîi khráp", "ผมไม่รู้จักที่นี่ครับ")],
 ["wiedzieć", "przyjaciel"], ["znać"]),

("A2", "przedstawiać (kogoś)", "nǎe-nam hâi rúu-jàk", "แนะนำให้รู้จัก", CZ, "Relacje", 3, "n",
 "To samo „nǎe-nam” co przy poleceniu dania — czasownik służy i do rekomendacji, i do przedstawiania osób.",
 "polecać dać znać",
 [("Przedstawię pana koledze.", "phǒm jà nǎe-nam hâi rúu-jàk khráp", "ผมจะแนะนำให้รู้จักครับ"),
  ("To mój przyjaciel.", "níi phûean phǒm khráp", "นี่เพื่อนผมครับ")],
 ["polecać", "poznawać (kogoś)"], []),

("A2", "zapraszać", "chuan", "ชวน", CZ, "Relacje", 4, "n",
 "„chuan” to zaprosić do wspólnej czynności. Formalne zaproszenie to „chooen”.",
 "",
 [("Zaprosił mnie na kolację.", "kháo chuan phǒm pai kin khâao khráp", "เขาชวนผมไปกินข้าวครับ"),
  ("Zapraszam.", "chooen khráp", "เชิญครับ")],
 ["zapraszać do środka", "kolacja"], []),

("A2", "odwiedzać", "pai yîam", "ไปเยี่ยม", CZ, "Relacje", 3, "n",
 "„yîam” dotyczy zwłaszcza odwiedzin chorego lub rodziny.",
 "iść odwiedzać",
 [("Odwiedzę babcię.", "phǒm jà pai yîam yâa khráp", "ผมจะไปเยี่ยมย่าครับ"),
  ("Odwiedzam go w szpitalu.", "phǒm pai yîam kháo thîi roong phá-yaa-baan khráp", "ผมไปเยี่ยมเขาที่โรงพยาบาลครับ")],
 ["szpital", "babcia"], []),

("A2", "pożyczać (od kogoś)", "yuem", "ยืม", CZ, "Relacje", 4, "n",
 "Uwaga na parę: „yuem” to pożyczyć od kogoś, „hâi yuem” to pożyczyć komuś. Przy pieniądzach używa się „yuem ngoen”.",
 "",
 [("Czy mogę pożyczyć długopis?", "khǎw yuem pàak-kaa nòi khráp", "ขอยืมปากกาหน่อยครับ"),
  ("Pożyczyłem mu pieniądze.", "phǒm hâi kháo yuem ngoen khráp", "ผมให้เขายืมเงินครับ")],
 ["oddawać", "długopis", "pieniądze"], []),

("A2", "oddawać", "khuen", "คืน", CZ, "Relacje", 4, "n",
 "To samo słowo w „khuen ngoen” (zwrot pieniędzy) i „khuen sǐn kháa” (zwrot towaru).",
 "",
 [("Oddam jutro.", "phǒm jà khuen phrûng-níi khráp", "ผมจะคืนพรุ่งนี้ครับ"),
  ("Proszę oddać klucz.", "khuen kun-jae dûai khráp", "คืนกุญแจด้วยครับ")],
 ["pożyczać (od kogoś)", "zwrot towaru", "klucz"], []),

("A2", "dzielić się", "bàeng", "แบ่ง", CZ, "Relacje", 3, "n",
 "„bàeng kan” to podzielić między siebie — także o rachunku.",
 "",
 [("Podzielimy się.", "bàeng kan khráp", "แบ่งกันครับ"),
  ("Podziel na pół.", "bàeng khrûeng khráp", "แบ่งครึ่งครับ")],
 ["połowa", "rachunek", "osobno"], []),

("A2", "pomagać sobie nawzajem", "chûai lǔea kan", "ช่วยเหลือกัน", CZ, "Relacje", 3, "f",
 "„kan” na końcu oznacza wzajemność — „rák kan” (kochać się), „rúu-jàk kan” (znać się).",
 "pomagać ratować razem",
 [("Pomagamy sobie.", "rao chûai lǔea kan khráp", "เราช่วยเหลือกันครับ"),
  ("Znamy się.", "rao rúu-jàk kan khráp", "เรารู้จักกันครับ")],
 ["pomagać", "poznawać (kogoś)"], []),

("A2", "kłócić się", "thá-ló kan", "ทะเลาะกัน", CZ, "Relacje", 3, "n",
 "Publiczna kłótnia to poważna utrata twarzy — Tajowie unikają jej nawet w konflikcie.",
 "kłócić się razem",
 [("Pokłócili się.", "kháo thá-ló kan khráp", "เขาทะเลาะกันครับ"),
  ("Nie kłóćmy się.", "yàa thá-ló kan loei khráp", "อย่าทะเลาะกันเลยครับ")],
 ["gniewać się", "godzić się"], []),

("A2", "godzić się", "khuen dii kan", "คืนดีกัน", CZ, "Relacje", 2, "n",
 "Dosłownie „wrócić do dobra razem”.",
 "wracać dobry razem",
 [("Pogodzili się.", "kháo khuen dii kan láew khráp", "เขาคืนดีกันแล้วครับ"),
  ("Pogódźcie się.", "khuen dii kan thòe khráp", "คืนดีกันเถอะครับ")],
 ["kłócić się", "przepraszać"], []),

("A2", "ufać", "wái jai dâai", "ไว้ใจได้", CZ, "Relacje", 3, "n",
 "„wái jai dâai” to „godny zaufania” jako cecha. Sam czasownik to „wái jai”.",
 "powierzać serce móc",
 [("Można mu ufać.", "kháo wái jai dâai khráp", "เขาไว้ใจได้ครับ"),
  ("Nie ufam temu sklepowi.", "phǒm mâi wái jai ráan níi khráp", "ผมไม่ไว้ใจร้านนี้ครับ")],
 ["wierzyć", "uczciwy"], []),

("A2", "tęsknić", "khít thǔeng", "คิดถึง", CZ, "Relacje", 4, "n",
 "Dosłownie „myśleć aż do”. Zwrot bardzo częsty i ciepły, mówiony też przyjaciołom.",
 "myśleć docierać",
 [("Tęsknię za tobą.", "khít thǔeng khun khráp", "คิดถึงคุณครับ"),
  ("Tęsknię za domem.", "phǒm khít thǔeng bâan khráp", "ผมคิดถึงบ้านครับ")],
 ["myśleć", "kochać", "dom"], []),

# --------------------------------------------------------------- obsluga
("A2", "rezerwować", "jawng", "จอง", CZ, "Obsługa", 4, "n",
 "„jawng” obejmuje rezerwację pokoju, stolika, biletu i miejsca w kolejce.",
 "",
 [("Rezerwowałem pokój.", "phǒm jawng hâwng wái khráp", "ผมจองห้องไว้ครับ"),
  ("Chcę zarezerwować stolik.", "phǒm yàak jawng tó khráp", "ผมอยากจองโต๊ะครับ")],
 ["hotel", "stolik", "odwoływać"], []),

("A2", "odwoływać", "yók lôoek", "ยกเลิก", CZ, "Obsługa", 3, "f",
 "„yók” to podnieść, „lôoek” to zakończyć. Razem: anulować.",
 "podnosić kończyć",
 [("Chcę odwołać rezerwację.", "phǒm yàak yók lôoek kaan jawng khráp", "ผมอยากยกเลิกการจองครับ"),
  ("Lot został odwołany.", "thîao bin thùuk yók lôoek khráp", "เที่ยวบินถูกยกเลิกครับ")],
 ["rezerwować", "samolot", "przekładać"], ["anulować"]),

("A2", "przekładać (termin)", "lûean", "เลื่อน", CZ, "Obsługa", 3, "n",
 "„lûean” to też fizycznie przesunąć: „lûean tó” — przesuń stół.",
 "",
 [("Spotkanie przełożone.", "prà-chum lûean khráp", "ประชุมเลื่อนครับ"),
  ("Czy można przełożyć na jutro?", "lûean pen phrûng-níi dâai mǎi khráp", "เลื่อนเป็นพรุ่งนี้ได้ไหมครับ")],
 ["odwoływać", "spotkanie", "jutro"], []),

("A2", "potwierdzać", "yuen yan", "ยืนยัน", CZ, "Obsługa", 3, "f",
 "„yuen” znaczy stać. Dosłownie „stać twardo przy czymś”.",
 "stać twardo",
 [("Proszę potwierdzić rezerwację.", "chûai yuen yan kaan jawng khráp", "ช่วยยืนยันการจองครับ"),
  ("Potwierdzam.", "yuen yan khráp", "ยืนยันครับ")],
 ["rezerwować", "obiecywać"], []),

("A2", "sprawdzać", "trùat", "ตรวจ", CZ, "Obsługa", 4, "n",
 "„trùat” to kontrola urzędowa i badanie lekarskie: „trùat sù-khà-phâap” — badanie zdrowia.",
 "",
 [("Proszę sprawdzić rachunek.", "chûai trùat bin dûai khráp", "ช่วยตรวจบิลด้วยครับ"),
  ("Muszę zrobić badania.", "phǒm tâwng pai trùat sù-khà-phâap khráp", "ผมต้องไปตรวจสุขภาพครับ")],
 ["rachunek", "lekarz", "badanie"], ["kontrolować"]),

("A2", "naprawiać", "sâwm", "ซ่อม", CZ, "Obsługa", 4, "n",
 "Uwaga na parę minimalną: „sâwm” (naprawiać) i „sâwm” (widelec) brzmią tak samo — rozróżnia kontekst.",
 "",
 [("Klimatyzacja wymaga naprawy.", "âe tâwng sâwm khráp", "แอร์ต้องซ่อมครับ"),
  ("Gdzie naprawię telefon?", "sâwm thoo-rá-sàp thîi nǎi khráp", "ซ่อมโทรศัพท์ที่ไหนครับ")],
 ["psuć się", "narzędzie", "widelec"], []),

("A2", "instalować", "tìt tâng", "ติดตั้ง", CZ, "Obsługa", 2, "f",
 "„tìt” samo znaczy „przykleić, przyczepić, być włączonym”.",
 "przyczepiać ustawiać",
 [("Zainstalowali internet.", "kháo tìt tâng nét láew khráp", "เขาติดตั้งเน็ตแล้วครับ"),
  ("Proszę zainstalować aplikację.", "chûai tìt tâng áep khráp", "ช่วยติดตั้งแอปครับ")],
 ["internet", "aplikacja"], []),

("A2", "włączać", "pòoet", "เปิด", CZ, "Obsługa", 5, "n",
 "Jedno słowo na: otworzyć, włączyć i „być otwartym” o sklepie.",
 "",
 [("Proszę włączyć klimatyzację.", "chûai pòoet âe dûai khráp", "ช่วยเปิดแอร์ด้วยครับ"),
  ("Sklep jest otwarty.", "ráan pòoet khráp", "ร้านเปิดครับ")],
 ["wyłączać", "otwarty", "klimatyzacja"], ["otwierać"]),

("A2", "wyłączać", "pìt", "ปิด", CZ, "Obsługa", 5, "n",
 "Analogicznie: zamknąć, wyłączyć, „być zamkniętym”.",
 "",
 [("Proszę wyłączyć światło.", "chûai pìt fai dûai khráp", "ช่วยปิดไฟด้วยครับ"),
  ("Kuchnia jest już zamknięta.", "khrua pìt láew khráp", "ครัวปิดแล้วครับ")],
 ["włączać", "zamknięty", "światło"], ["zamykać"]),

("A2", "podłączać", "tàw", "ต่อ", CZ, "Obsługa", 4, "n",
 "„tàw” znaczy też „kontynuować” i „przesiadać się”: „tàw rót” — przesiąść się.",
 "",
 [("Podłącz do prądu.", "tàw fai khráp", "ต่อไฟครับ"),
  ("Muszę się przesiąść.", "phǒm tâwng tàw rót khráp", "ผมต่อรถครับ")],
 ["prąd", "przesiadać się", "kolejka"], []),

("A2", "ładować (urządzenie)", "chárt", "ชาร์จ", CZ, "Obsługa", 3, "n",
 "Zapożyczenie z angielskiego. „chárt bàet” — ładować baterię.",
 "",
 [("Muszę naładować telefon.", "phǒm tâwng chárt thoo-rá-sàp khráp", "ผมต้องชาร์จโทรศัพท์ครับ"),
  ("Czy mogę tu naładować?", "chárt thîi nîi dâai mǎi khráp", "ชาร์จที่นี่ได้ไหมครับ")],
 ["ładowarka", "bateria", "telefon"], []),

("A2", "drukować", "prín", "ปริ๊นท์", CZ, "Obsługa", 2, "p",
 "Potocznie od angielskiego „print”. Formalnie „phim”, które znaczy też „pisać na klawiaturze”.",
 "",
 [("Czy mogę tu wydrukować?", "prín thîi nîi dâai mǎi khráp", "ปริ๊นท์ที่นี่ได้ไหมครับ"),
  ("Proszę wydrukować dwie kopie.", "prín sǎwng chút khráp", "ปริ๊นท์สองชุดครับ")],
 ["dokument", "kopia", "papier"], []),

("A2", "wypełniać (formularz)", "kràwk", "กรอก", CZ, "Obsługa", 3, "f",
 "Używane wyłącznie o dokumentach. Do napełniania płynem służy „tooem”.",
 "",
 [("Proszę wypełnić formularz.", "chûai kràwk bàep fawm khráp", "ช่วยกรอกแบบฟอร์มครับ"),
  ("Nie wiem, jak wypełnić.", "phǒm mâi rúu wâa kràwk yang-ngai khráp", "ผมไม่รู้ว่ากรอกยังไงครับ")],
 ["formularz", "dokument", "podpis"], []),

("A2", "dolewać", "tooem", "เติม", CZ, "Obsługa", 3, "n",
 "„tooem ngoen” to doładować telefon, „tooem nám man” to zatankować.",
 "",
 [("Proszę dolać wody.", "chûai tooem nám dûai khráp", "ช่วยเติมน้ำด้วยครับ"),
  ("Muszę doładować telefon.", "phǒm tâwng tooem ngoen khráp", "ผมต้องเติมเงินครับ")],
 ["olej", "woda", "telefon"], ["doładować"]),

# ------------------------------------------------------- ruch przedmiotow
("A2", "podnosić z ziemi", "kèp", "เก็บ", CZ, "Czynności", 4, "n",
 "„kèp” to bardzo szerokie słowo: pozbierać, schować, odłożyć, a także „kèp ngoen” — pobrać zapłatę.",
 "",
 [("Proszę posprzątać ze stołu.", "chûai kèp tó dûai khráp", "ช่วยเก็บโต๊ะด้วยครับ"),
  ("Schowałem to.", "phǒm kèp wái láew khráp", "ผมเก็บไว้แล้วครับ")],
 ["sprzątać", "chować", "oszczędzać"], ["zbierać"]),

("A2", "chować", "sâwn", "ซ่อน", CZ, "Czynności", 2, "n",
 "„sâwn” to schować przed kimś, w odróżnieniu od „kèp”, które jest neutralne.",
 "",
 [("Schował klucz.", "kháo sâwn kun-jae khráp", "เขาซ่อนกุญแจครับ"),
  ("Gdzie to schowałeś?", "sâwn wái thîi nǎi khráp", "ซ่อนไว้ที่ไหนครับ")],
 ["podnosić z ziemi", "szukać", "klucz"], []),

("A2", "otwierać (paczkę)", "kàe", "แกะ", CZ, "Czynności", 2, "n",
 "„kàe” to rozpakować, obrać, odkleić — czynność drobna i precyzyjna.",
 "",
 [("Rozpakuj paczkę.", "kàe hàw khráp", "แกะห่อครับ"),
  ("Obierz krewetkę.", "kàe kûng khráp", "แกะกุ้งครับ")],
 ["pakować", "krewetka", "pudełko"], ["rozpakować"]),

("A2", "zawijać", "hàw", "ห่อ", CZ, "Czynności", 3, "n",
 "„hàw” to i czasownik, i rzeczownik: „nùeng hàw” to jedna paczuszka — częsta jednostka przy ulicznym jedzeniu.",
 "",
 [("Proszę zawinąć.", "chûai hàw hâi nòi khráp", "ช่วยห่อให้หน่อยครับ"),
  ("Poproszę dwie paczuszki.", "khǎw sǎwng hàw khráp", "ขอสองห่อครับ")],
 ["pakować", "otwierać (paczkę)", "porcja"], []),

("A2", "wieszać", "khwǎen wái", "แขวนไว้", CZ, "Czynności", 2, "n",
 "„wái” po czasowniku znaczy „zostawić w tym stanie” — bardzo częsta konstrukcja.",
 "wieszać zostawić",
 [("Powieś ubranie.", "khwǎen sûea wái khráp", "แขวนเสื้อไว้ครับ"),
  ("Gdzie mogę powiesić ręcznik?", "khwǎen phâa chét tua thîi nǎi khráp", "แขวนผ้าเช็ดตัวที่ไหนครับ")],
 ["ubranie", "ręcznik"], []),

("A2", "mieszać (łyżką)", "khon hâi khâo kan", "คนให้เข้ากัน", CZ, "Czynności", 2, "n",
 "„khâo kan” znaczy „połączyć się razem” — używane też o ludziach, którzy się dogadują.",
 "mieszać dać wejść razem",
 [("Wymieszaj dobrze.", "khon hâi khâo kan khráp", "คนให้เข้ากันครับ"),
  ("Oni dobrze się dogadują.", "kháo khâo kan dâai dii khráp", "เขาเข้ากันได้ดีครับ")],
 ["mieszać", "gotować"], []),

("A2", "wylewać", "thee", "เท", CZ, "Czynności", 2, "n",
 "Krótkie i użyteczne w kuchni. „thee thíng” — wylać i wyrzucić.",
 "",
 [("Wylej wodę.", "thee nám thíng khráp", "เทน้ำทิ้งครับ"),
  ("Nalej do szklanki.", "thee sài kâew khráp", "เทใส่แก้วครับ")],
 ["nalewać", "wyrzucić", "szklanka"], []),

("A2", "rozlać (przypadkiem)", "tham nám hòk", "ทำน้ำหก", CZ, "Czynności", 2, "n",
 "Konstrukcja „tham + rzecz + hòk” oznacza niezamierzone rozlanie. Sam „hòk” to też liczba sześć.",
 "robić woda rozlać",
 [("Przepraszam, rozlałem wodę.", "khǎw thôot tham nám hòk khráp", "ขอโทษทำน้ำหกครับ"),
  ("Uważaj, żeby nie rozlać.", "rá-wang yàa hâi hòk khráp", "ระวังอย่าให้หกครับ")],
 ["woda", "uważać", "przepraszać"], []),

("A2", "napełniać", "tham hâi tem", "ทำให้เต็ม", CZ, "Czynności", 2, "n",
 "Konstrukcja „tham hâi + przymiotnik” tworzy czasowniki sprawcze: tham hâi ráwn (podgrzać), tham hâi sà-àat (wyczyścić).",
 "robić dać pełny",
 [("Napełnij szklankę.", "tham hâi tem kâew khráp", "ทำให้เต็มแก้วครับ"),
  ("Zbiornik jest pełny.", "thǎng tem láew khráp", "ถังเต็มแล้วครับ")],
 ["pełny", "wiadro", "dolewać"], []),

("A2", "ciągnąć", "dueng", "ดึง", CZ, "Czynności", 3, "n",
 "Na drzwiach w Tajlandii często widnieje „dueng” (ciągnąć) albo „phlàk” (pchać).",
 "",
 [("Pociągnij drzwi.", "dueng prà-tuu khráp", "ดึงประตูครับ"),
  ("Nie ciągnij tak mocno.", "yàa dueng raeng khráp", "อย่าดึงแรงครับ")],
 ["pchać", "drzwi", "mocny"], []),

("A2", "kopać (nogą)", "tè", "เตะ", CZ, "Czynności", 2, "n",
 "„tè bawn” to grać w piłkę nożną — po tajsku dosłownie „kopać piłkę”.",
 "",
 [("Gramy w piłkę.", "rao tè bawn khráp", "เราเตะบอลครับ"),
  ("Proszę nie kopać.", "yàa tè khráp", "อย่าเตะครับ")],
 ["piłka nożna", "noga"], []),

("A2", "biegać", "wîng", "วิ่ง", CZ, "Czynności", 4, "n",
 "„wîng àwk kam-lang kaai” to bieganie jako ćwiczenie. „wîng” dotyczy też kursowania autobusu.",
 "",
 [("Biegam co rano.", "phǒm wîng thúk cháo khráp", "ผมวิ่งทุกเช้าครับ"),
  ("Ten autobus tu nie kursuje.", "rót mee mâi wîng thǎew níi khráp", "รถเมล์ไม่วิ่งแถวนี้ครับ")],
 ["ćwiczyć", "chodzić", "autobus"], []),

("A2", "pływać", "wâai nám", "ว่ายน้ำ", CZ, "Czynności", 3, "n",
 "„wâai nám mâi pen” — nie umiem pływać. Konstrukcja „mâi pen” oznacza brak umiejętności.",
 "pływać woda",
 [("Nie umiem pływać.", "phǒm wâai nám mâi pen khráp", "ผมว่ายน้ำไม่เป็นครับ"),
  ("Idziemy popływać.", "rao pai wâai nám khráp", "เราไปว่ายน้ำครับ")],
 ["morze", "basen", "umieć"], []),

("A2", "skakać", "krà-dòot", "กระโดด", CZ, "Czynności", 2, "n",
 "Trzysylabowe, warto ćwiczyć rytm: krà-DOOT z akcentem na drugą część.",
 "",
 [("Nie skacz.", "yàa krà-dòot khráp", "อย่ากระโดดครับ"),
  ("Skoczył do wody.", "kháo krà-dòot long nám khráp", "เขากระโดดลงน้ำครับ")],
 ["pływać", "woda"], []),

("A2", "wspinać się", "pìin", "ปีน", CZ, "Czynności", 2, "n",
 "„pìin khǎo” to wspinaczka górska, popularna w Krabi.",
 "",
 [("Wspinamy się na górę.", "rao pìin khǎo khráp", "เราปีนเขาครับ"),
  ("To niebezpieczne.", "an-tà-raai khráp", "อันตรายครับ")],
 ["góra", "niebezpieczny"], []),

("A2", "odpoczywać", "phák", "พัก", CZ, "Czynności", 4, "n",
 "„phák” znaczy też „zatrzymać się na nocleg”: „phák thîi roong raem”.",
 "",
 [("Odpocznijmy chwilę.", "phák sàk khrûu khráp", "พักสักครู่ครับ"),
  ("Nocuję w hotelu.", "phǒm phák thîi roong raem khráp", "ผมพักที่โรงแรมครับ")],
 ["hotel", "spać", "zmęczony"], []),

("A2", "budzić kogoś", "plùk", "ปลุก", CZ, "Czynności", 3, "n",
 "Różnica od „tùen” (samemu się obudzić). „plùk” wymaga dopełnienia.",
 "",
 [("Proszę mnie obudzić o szóstej.", "chûai plùk phǒm hòk moong khráp", "ช่วยปลุกผมหกโมงครับ"),
  ("Nie budź go.", "yàa plùk kháo khráp", "อย่าปลุกเขาครับ")],
 ["budzić się", "spać", "rano"], []),

("A2", "czekać na kogoś", "raw", "รอ", CZ, "Czynności", 5, "n",
 "„raw sàk khrûu” — poczekaj chwilę, jeden z najczęstszych zwrotów obsługi.",
 "",
 [("Proszę chwilę poczekać.", "raw sàk khrûu khráp", "รอสักครู่ครับ"),
  ("Czekam na przyjaciela.", "phǒm raw phûean khráp", "ผมรอเพื่อนครับ")],
 ["chwila", "przyjaciel", "spóźnić się"], ["czekać"]),

("A2", "przygotowywać", "triam", "เตรียม", CZ, "Czynności", 3, "n",
 "„triam tua” to przygotować się osobiście — dosłownie „przygotować ciało”.",
 "",
 [("Przygotuję dokumenty.", "phǒm jà triam èek-kà-sǎan khráp", "ผมจะเตรียมเอกสารครับ"),
  ("Przygotuj się.", "triam tua wái khráp", "เตรียมตัวไว้ครับ")],
 ["gotowy", "dokument"], []),

("A2", "zapisywać", "jòt", "จด", CZ, "Czynności", 3, "n",
 "„jòt wái” — zanotować sobie. Przydatne przy zapisywaniu adresu dla taksówkarza.",
 "",
 [("Zapiszę adres.", "phǒm jà jòt thîi yùu khráp", "ผมจะจดที่อยู่ครับ"),
  ("Proszę to zapisać.", "chûai jòt hâi nòi khráp", "ช่วยจดให้หน่อยครับ")],
 ["zeszyt", "adres", "pisać"], ["notować"]),

("A2", "liczyć", "náp", "นับ", CZ, "Czynności", 3, "n",
 "„náp” to liczyć sztuki. „khít ngoen” to policzyć rachunek — inne słowo.",
 "",
 [("Policz, ile jest.", "náp duu wâa mii thâo-rài khráp", "นับดูว่ามีเท่าไหร่ครับ"),
  ("Policzę pieniądze.", "phǒm jà náp ngoen khráp", "ผมจะนับเงินครับ")],
 ["liczba", "pieniądze", "rachunek"], []),

("A2", "mierzyć", "wát", "วัด", CZ, "Czynności", 3, "n",
 "Uwaga: to samo brzmienie co „wát” — świątynia. Rozróżnia wyłącznie kontekst.",
 "",
 [("Proszę zmierzyć temperaturę.", "chûai wát khâi dûai khráp", "ช่วยวัดไข้ด้วยครับ"),
  ("Zmierzę rozmiar.", "phǒm jà wát khà-nàat khráp", "ผมจะวัดขนาดครับ")],
 ["świątynia", "rozmiar", "gorączka"], []),

("A2", "ważyć", "châng", "ชั่ง", CZ, "Czynności", 2, "n",
 "„châng nám-nàk” to ważyć — na targu i na lotnisku.",
 "",
 [("Proszę zważyć bagaż.", "chûai châng krà-pǎo dûai khráp", "ช่วยชั่งกระเป๋าด้วยครับ"),
  ("Ile to waży?", "nàk thâo-rài khráp", "หนักเท่าไหร่ครับ")],
 ["ciężki", "bagaż", "waga"], []),
]
