# -*- coding: utf-8 -*-
"""Sesja F — PRZYSLOWKI: czestotliwosci, stopnia i sposobu.

Uwaga skladniowa, ktora warto miec z tylu glowy: tajski przyslowek sposobu
stoi PO czasowniku („phûut cháa cháa” — mow wolno), a przyslowek
czestotliwosci zwykle przed czasownikiem albo na poczatku zdania.
Podwojenie sylaby („cháa cháa”, „reo reo”, „bao bao”) lagodzi polecenie
i jest w mowie codziennej normą, nie ozdobnikiem.
"""

CG = "Gramatyka użytkowa"
SF = "Przysłówki częstotliwości"
SD = "Przysłówki stopnia"
SM = "Przysłówki sposobu"

ADV = [

# ======================================================== CZESTOTLIWOSC
("A1", "zwykle", "taam pòk-kà-tì", "ตามปกติ", CG, SF, 4, "n",
 "Samo „pòk-kà-tì” na początku zdania wystarcza w mowie codziennej. Wersja z „taam” jest nieco pełniejsza.",
 "według normalnie",
 [("Zwykle wstaję o szóstej.", "pòk-kà-tì phǒm tùen hòk mohng khráp", "ปกติผมตื่นหกโมงครับ"),
  ("Jak zwykle.", "taam pòk-kà-tì khráp", "ตามปกติครับ")],
 ["normalny", "codziennie"], ["zazwyczaj"]),

("A2", "co tydzień", "thúk aa-thít", "ทุกอาทิตย์", CG, SF, 4, "n",
 "„thúk” znaczy „każdy” i łączy się z każdą jednostką czasu: thúk wan, thúk duean, thúk pii.",
 "każdy tydzień",
 [("Chodzę tam co tydzień.", "phǒm pai thîi nân thúk aa-thít khráp", "ผมไปที่นั่นทุกอาทิตย์ครับ"),
  ("Sprzątam co tydzień.", "phǒm tham khwaam sà-àat thúk aa-thít khráp", "ผมทำความสะอาดทุกอาทิตย์ครับ")],
 ["co miesiąc", "tydzień", "codziennie"], []),

("A2", "co miesiąc", "thúk duean", "ทุกเดือน", CG, SF, 4, "n",
 "Ten sam wzorzec z „thúk”. Częste przy czynszu i rachunkach.",
 "każdy miesiąc",
 [("Płacę czynsz co miesiąc.", "phǒm jàai khâa châo thúk duean khráp", "ผมจ่ายค่าเช่าทุกเดือนครับ"),
  ("Co miesiąc jeżdżę do Bangkoku.", "phǒm pai krung-thêep thúk duean khráp", "ผมไปกรุงเทพทุกเดือนครับ")],
 ["co tydzień", "miesiąc", "czynsz"], []),

("A2", "raz na jakiś czas", "naan naan thii", "นานๆที", CG, SF, 3, "n",
 "Dosłownie „długo długo raz”. Podwojenie „naan” wydłuża odstęp między zdarzeniami.",
 "długo długo raz",
 [("Bywam tu raz na jakiś czas.", "phǒm maa thîi nîi naan naan thii khráp", "ผมมาที่นี่นานๆทีครับ"),
  ("Raz na jakiś czas piję kawę.", "naan naan thii phǒm dùuem kaa-fae khráp", "นานๆทีผมดื่มกาแฟครับ")],
 ["rzadko", "często"], []),

("A2", "ciągle", "tà-làwt wee-laa", "ตลอดเวลา", CG, SF, 4, "n",
 "Dosłownie „przez cały czas”. Bywa użyte z odcieniem skargi, jak polskie „bez przerwy”.",
 "przez cały czas",
 [("Ciągle pada.", "fǒn tòk tà-làwt wee-laa khráp", "ฝนตกตลอดเวลาครับ"),
  ("Ciągle narzeka.", "kháo bòn tà-làwt wee-laa khráp", "เขาบ่นตลอดเวลาครับ")],
 ["nadal", "narzekać"], ["bez przerwy"]),

("A1", "nadal", "yang", "ยัง", CG, SF, 5, "n",
 "Kluczowe słowo gramatyczne. „yang mâi” to „jeszcze nie” — najczęstsza odpowiedź na pytanie, czy coś już zrobione.",
 "",
 [("Jeszcze nie skończyłem.", "phǒm yang mâi sèt khráp", "ผมยังไม่เสร็จครับ"),
  ("Nadal czekam.", "phǒm yang raw yùu khráp", "ผมยังรออยู่ครับ"),
  ("Jeszcze nie jadłem.", "phǒm yang mâi dâai kin khráp", "ผมยังไม่ได้กินครับ")],
 ["już", "ciągle", "czekać"], ["jeszcze"]),

("A1", "już", "láew", "แล้ว", CG, SF, 5, "n",
 "Partykuła kończąca zdanie, oznaczająca zmianę stanu. „kin láew” — już zjadłem. Para do „yang”.",
 "",
 [("Już zjadłem.", "phǒm kin láew khráp", "ผมกินแล้วครับ"),
  ("Już przyszedł.", "kháo maa láew khráp", "เขามาแล้วครับ"),
  ("Już wystarczy.", "phaw láew khráp", "พอแล้วครับ")],
 ["nadal", "wystarczyć"], []),

("A2", "kiedyś (miałem okazję)", "khoei", "เคย", CG, SF, 5, "n",
 "Oznacza doświadczenie w przeszłości, nie konkretny moment. „khoei pai mǎi” — byłeś tam kiedyś? Zaprzeczenie „mâi khoei” znaczy „nigdy”.",
 "",
 [("Byłem tam kiedyś.", "phǒm khoei pai khráp", "ผมเคยไปครับ"),
  ("Nigdy tego nie jadłem.", "phǒm mâi khoei kin khráp", "ผมไม่เคยกินครับ"),
  ("Byłeś kiedyś w Tajlandii?", "khun khoei maa thai mǎi khráp", "คุณเคยมาไทยไหมครับ")],
 ["nigdy", "wkrótce"], []),

("A2", "wkrótce", "reo reo níi", "เร็วๆนี้", CG, SF, 4, "n",
 "Dosłownie „szybko szybko to”. Podwojenie „reo” daje znaczenie „w niedalekiej przyszłości”.",
 "szybko szybko to",
 [("Wkrótce wracam.", "phǒm jà klàp reo reo níi khráp", "ผมจะกลับเร็วๆนี้ครับ"),
  ("Wkrótce się spotkamy.", "rao jà jòoe kan reo reo níi khráp", "เราจะเจอกันเร็วๆนี้ครับ")],
 ["niedawno", "szybko"], []),

("A2", "niedawno", "mûea mâi naan maa níi", "เมื่อไม่นานมานี้", CG, SF, 3, "n",
 "Dosłownie „gdy niedługo przyszło to”. Dłuższe, ale to jedyne naturalne określenie.",
 "gdy nie długo przyjść to",
 [("Niedawno tu byłem.", "phǒm maa thîi nîi mûea mâi naan maa níi khráp", "ผมมาที่นี่เมื่อไม่นานมานี้ครับ"),
  ("Niedawno się przeprowadziłem.", "phǒm yáai maa mûea mâi naan maa níi khráp", "ผมย้ายมาเมื่อไม่นานมานี้ครับ")],
 ["wkrótce", "wczoraj"], []),

("A2", "znowu", "ìik", "อีก", CG, SF, 5, "n",
 "Znaczy „jeszcze, ponownie, więcej”. „ao ìik” — poproszę jeszcze, „maa ìik” — przyjdź znowu.",
 "",
 [("Poproszę jeszcze raz.", "khǎw ìik thii khráp", "ขออีกทีครับ"),
  ("Znowu pada.", "fǒn tòk ìik láew khráp", "ฝนตกอีกแล้วครับ"),
  ("Przyjdź znowu.", "maa ìik ná khráp", "มาอีกนะครับ")],
 ["powtórzyć", "zwiększać"], []),

# ============================================================== STOPIEN
("A1", "bardzo", "mâak", "มาก", CG, SD, 5, "n",
 "Stoi PO tym, co określa: „à-ròi mâak” — bardzo smaczne. Odwrotnie niż po polsku.",
 "",
 [("Bardzo smaczne.", "à-ròi mâak khráp", "อร่อยมากครับ"),
  ("Bardzo dziękuję.", "khàwp khun mâak khráp", "ขอบคุณมากครับ"),
  ("Jest bardzo gorąco.", "ráwn mâak khráp", "ร้อนมากครับ")],
 ["trochę", "zbyt"], []),

("A1", "trochę", "nít nòi", "นิดหน่อย", CG, SD, 5, "n",
 "Też stoi po określanym słowie. Samo „nòi” na końcu prośby ją łagodzi: „chûai nòi khráp”.",
 "",
 [("Trochę ostre.", "phèt nít nòi khráp", "เผ็ดนิดหน่อยครับ"),
  ("Mówię trochę po tajsku.", "phǒm phûut thai dâai nít nòi khráp", "ผมพูดไทยได้นิดหน่อยครับ")],
 ["bardzo", "mało"], []),

("A2", "zbyt", "koen pai", "เกินไป", CG, SD, 5, "n",
 "Dosłownie „przekracza idzie”. Stoi po przymiotniku: „phaeng koen pai” — za drogo. Bardzo przydatne przy targowaniu.",
 "przekraczać iść",
 [("Za drogo.", "phaeng koen pai khráp", "แพงเกินไปครับ"),
  ("Za ostre dla mnie.", "phèt koen pai khráp", "เผ็ดเกินไปครับ"),
  ("Jest za duże.", "yài koen pai khráp", "ใหญ่เกินไปครับ")],
 ["bardzo", "targować się", "drogi"], ["za bardzo"]),

("A2", "dość (całkiem)", "khâwn khâang", "ค่อนข้าง", CG, SD, 4, "n",
 "Osłabia ocenę i stoi PRZED przymiotnikiem — inaczej niż „mâak”. „khâwn khâang phaeng” — dość drogo.",
 "",
 [("Jest dość drogo.", "khâwn khâang phaeng khráp", "ค่อนข้างแพงครับ"),
  ("To dość daleko.", "khâwn khâang klai khráp", "ค่อนข้างไกลครับ")],
 ["bardzo", "trochę"], ["całkiem"]),

("A2", "w ogóle nie", "mâi ... loei", "ไม่...เลย", CG, SD, 5, "n",
 "Konstrukcja obejmująca: „mâi phèt loei” — w ogóle nie jest ostre. „loei” zamyka zdanie i wzmacnia przeczenie.",
 "nie ... wcale",
 [("W ogóle nie jest ostre.", "mâi phèt loei khráp", "ไม่เผ็ดเลยครับ"),
  ("W ogóle nie rozumiem.", "phǒm mâi khâo jai loei khráp", "ผมไม่เข้าใจเลยครับ"),
  ("Wcale nie boli.", "mâi jèp loei khráp", "ไม่เจ็บเลยครับ")],
 ["bardzo", "rozumieć"], ["wcale nie"]),

("A2", "tylko", "khâe", "แค่", CG, SD, 5, "n",
 "Stoi przed liczbą albo rzeczownikiem. Wersja pełniejsza „thâo nán” zamyka zdanie.",
 "",
 [("Tylko sto batów.", "khâe nùeng ráwi bàat khráp", "แค่หนึ่งร้อยบาทครับ"),
  ("Chcę tylko popatrzeć.", "khâe duu chǒoei chǒoei khráp", "แค่ดูเฉยๆครับ")],
 ["co najmniej", "cena"], []),

("A2", "co najmniej", "yàang nói", "อย่างน้อย", CG, SD, 4, "n",
 "Dosłownie „w sposób mały”. Para do „yàang mâak” (najwyżej).",
 "sposób mało",
 [("Co najmniej dwa dni.", "yàang nói sǎwng wan khráp", "อย่างน้อยสองวันครับ"),
  ("Zajmie co najmniej godzinę.", "chái wee-laa yàang nói nùeng chûa-mohng khráp", "ใช้เวลาอย่างน้อยหนึ่งชั่วโมงครับ")],
 ["najwyżej", "tylko"], []),

("A2", "najwyżej", "yàang mâak", "อย่างมาก", CG, SD, 3, "n",
 "Para do „yàang nói”. Ogranicza od góry.",
 "sposób dużo",
 [("Najwyżej dwieście batów.", "yàang mâak sǎwng ráwi bàat khráp", "อย่างมากสองร้อยบาทครับ"),
  ("Najwyżej trzy dni.", "yàang mâak sǎam wan khráp", "อย่างมากสามวันครับ")],
 ["co najmniej", "około (godziny)"], []),

("A2", "coraz bardziej", "... khûen rûeai rûeai", "ขึ้นเรื่อยๆ", CG, SD, 3, "n",
 "Dosłownie „w górę stopniowo”. Opisuje narastanie w czasie.",
 "w górę stopniowo",
 [("Robi się coraz goręcej.", "ráwn khûen rûeai rûeai khráp", "ร้อนขึ้นเรื่อยๆครับ"),
  ("Ceny rosną coraz bardziej.", "raa-khaa khûen rûeai rûeai khráp", "ราคาขึ้นเรื่อยๆครับ")],
 ["zwiększać", "wchodzić na górę"], []),

# ============================================================== SPOSOB
("A1", "powoli", "cháa cháa", "ช้าๆ", CG, SM, 5, "n",
 "Podwojenie łagodzi polecenie. Dla uczącego się to zdanie ratunkowe: „phûut cháa cháa nòi khráp”.",
 "",
 [("Proszę mówić powoli.", "phûut cháa cháa nòi khráp", "พูดช้าๆหน่อยครับ"),
  ("Idź powoli.", "doen cháa cháa khráp", "เดินช้าๆครับ")],
 ["szybko", "wolny (powolny)", "powtórzyć"], []),

("A2", "szybko", "reo reo", "เร็วๆ", CG, SM, 5, "n",
 "Para do „cháa cháa”. Podwojone brzmi jak prośba, nie rozkaz.",
 "",
 [("Proszę szybciej.", "reo reo nòi khráp", "เร็วๆหน่อยครับ"),
  ("Jedz szybko, spóźnimy się.", "kin reo reo dǐao sǎai khráp", "กินเร็วๆเดี๋ยวสายครับ")],
 ["powoli", "spieszyć się"], []),

("A2", "ostrożnie", "rá-wang", "ระวัง", CG, SM, 5, "n",
 "Samo w sobie działa jak ostrzeżenie: „rá-wang!” — uwaga! Zobaczysz to słowo na tabliczkach.",
 "",
 [("Uważaj.", "rá-wang ná khráp", "ระวังนะครับ"),
  ("Prowadź ostrożnie.", "khàp rót rá-wang ná khráp", "ขับรถระวังนะครับ"),
  ("Uważaj na schodach.", "rá-wang ban-dai khráp", "ระวังบันไดครับ")],
 ["uważaj", "prowadzić (pojazd)"], []),

("A2", "cicho", "bao bao", "เบาๆ", CG, SM, 4, "n",
 "„bao” znaczy lekki i cichy zarazem. „phûut bao bao” — mów ciszej.",
 "lekko lekko",
 [("Mów ciszej, proszę.", "phûut bao bao nòi khráp", "พูดเบาๆหน่อยครับ"),
  ("Ściszysz trochę?", "bao long nòi dâai mǎi khráp", "เบาลงหน่อยได้ไหมครับ")],
 ["głośno", "milczeć"], []),

("A2", "głośno", "dang dang", "ดังๆ", CG, SM, 3, "n",
 "Para do „bao bao”. „phûut dang dang nòi” — mów głośniej, proszę.",
 "",
 [("Mów głośniej, proszę.", "phûut dang dang nòi khráp", "พูดดังๆหน่อยครับ"),
  ("Za głośno.", "dang koen pai khráp", "ดังเกินไปครับ")],
 ["cicho", "sławny"], []),

("A1", "razem", "dûai kan", "ด้วยกัน", CG, SM, 5, "n",
 "„pai dûai kan” — chodźmy razem. Samo „dûai” znaczy „również, także”.",
 "",
 [("Idziemy razem.", "pai dûai kan khráp", "ไปด้วยกันครับ"),
  ("Zjedzmy razem.", "kin dûai kan ná khráp", "กินด้วยกันนะครับ")],
 ["osobno", "samodzielnie"], []),

("A2", "osobno", "yâek kan", "แยกกัน", CG, SM, 4, "n",
 "W restauracji kluczowe: „jàai yâek kan” — płacimy osobno.",
 "rozdzielić razem",
 [("Płacimy osobno.", "jàai yâek kan khráp", "จ่ายแยกกันครับ"),
  ("Poproszę osobno zapakować.", "yâek thǔng hâi nòi khráp", "แยกถุงให้หน่อยครับ")],
 ["razem", "płacić", "rachunek"], []),

("A2", "samodzielnie", "eeng", "เอง", CG, SM, 5, "n",
 "Stoi po zaimku albo czasowniku: „phǒm tham eeng” — zrobię sam. Znaczy też „osobiście”.",
 "",
 [("Zrobię to sam.", "phǒm tham eeng khráp", "ผมทำเองครับ"),
  ("Przyszedłem sam.", "phǒm maa khon diao khráp", "ผมมาคนเดียวครับ")],
 ["razem", "samotny"], ["sam"]),

("A2", "naprawdę", "jing jing", "จริงๆ", CG, SM, 5, "n",
 "Podwojone „jing” wzmacnia. Bywa też pytaniem z rosnącą intonacją: „jing jing rǒoe” — serio?",
 "",
 [("Naprawdę smaczne.", "à-ròi jing jing khráp", "อร่อยจริงๆครับ"),
  ("Naprawdę przepraszam.", "khǎw thôot jing jing khráp", "ขอโทษจริงๆครับ")],
 ["na pewno", "prawdziwy"], []),

("A2", "na pewno", "nâe nawn", "แน่นอน", CG, SM, 5, "n",
 "Działa też jako samodzielna odpowiedź twierdząca — odpowiednik „oczywiście”.",
 "",
 [("Na pewno przyjdę.", "phǒm maa nâe nawn khráp", "ผมมาแน่นอนครับ"),
  ("Oczywiście.", "nâe nawn khráp", "แน่นอนครับ")],
 ["pewny (przekonany)", "naprawdę"], ["oczywiście"]),

("A2", "natychmiast", "than-thii", "ทันที", CG, SM, 4, "n",
 "Formalniejsze niż „dǐao níi”. W rozmowie codziennej częściej usłyszysz „lóei” albo „diǎo”.",
 "",
 [("Zrobię to natychmiast.", "phǒm jà tham than-thii khráp", "ผมจะทำทันทีครับ"),
  ("Proszę zadzwonić natychmiast.", "kà-rú-naa thoo than-thii khráp", "กรุณาโทรทันทีครับ")],
 ["zaraz", "spieszyć się"], []),

("A2", "najpierw", "kàwn", "ก่อน", CG, SM, 5, "n",
 "Stoi po czasowniku: „kin kàwn” — najpierw zjedz. Znaczy też „przed” w czasie.",
 "",
 [("Najpierw zjem.", "phǒm kin kàwn khráp", "ผมกินก่อนครับ"),
  ("Chwileczkę, najpierw zapłacę.", "sák khrûu ná khráp jàai kàwn", "สักครู่นะครับจ่ายก่อน")],
 ["potem", "w końcu"], []),

("A2", "potem", "láew kâw", "แล้วก็", CG, SM, 5, "n",
 "Łączy kolejne czynności w opowiadaniu. Dosłownie „i wtedy też”.",
 "już i",
 [("Zjem, a potem pójdę.", "phǒm kin láew kâw pai khráp", "ผมกินแล้วก็ไปครับ"),
  ("Najpierw tam, potem tutaj.", "pai thîi nân kàwn láew kâw maa thîi nîi khráp", "ไปที่นั่นก่อนแล้วก็มาที่นี่ครับ")],
 ["najpierw", "w końcu"], []),

("A2", "w końcu", "nai thîi sùt", "ในที่สุด", CG, SM, 3, "n",
 "Zamyka opowiadanie. Bardziej opisowe niż „láew kâw”.",
 "w miejscu ostatnim",
 [("W końcu przyszedł.", "nai thîi sùt kháo kâw maa khráp", "ในที่สุดเขาก็มาครับ"),
  ("W końcu znalazłem.", "nai thîi sùt phǒm kâw jòoe khráp", "ในที่สุดผมก็เจอครับ")],
 ["potem", "ostatni"], []),

("A2", "przypadkiem", "bang-oen", "บังเอิญ", CG, SM, 3, "n",
 "O zbiegu okoliczności. „bang-oen jòoe kan” — przypadkiem się spotkaliśmy.",
 "",
 [("Przypadkiem go spotkałem.", "phǒm bang-oen jòoe kháo khráp", "ผมบังเอิญเจอเขาครับ"),
  ("To był przypadek.", "man bang-oen khráp", "มันบังเอิญครับ")],
 ["celowo", "spotykać"], []),

("A2", "celowo", "tâng jai", "ตั้งใจ", CG, SM, 4, "n",
 "Dosłownie „ustawić serce”. Znaczy też „starać się, przykładać się”: „tâng jai rian”.",
 "ustawić serce",
 [("Nie zrobiłem tego celowo.", "phǒm mâi dâai tâng jai khráp", "ผมไม่ได้ตั้งใจครับ"),
  ("Ucz się pilnie.", "tâng jai rian ná khráp", "ตั้งใจเรียนนะครับ")],
 ["przypadkiem", "uczyć się"], []),

("A2", "szczególnie", "doi chà-phǎw", "โดยเฉพาะ", CG, SM, 3, "f",
 "Wyróżnia jeden element z grupy. Nieco formalne, ale częste w wyjaśnieniach.",
 "",
 [("Lubię owoce, szczególnie mango.", "phǒm châwp phǒn-lá-mái doi chà-phǎw má-mûang khráp", "ผมชอบผลไม้โดยเฉพาะมะม่วงครับ"),
  ("Szczególnie latem.", "doi chà-phǎw nâa ráwn khráp", "โดยเฉพาะหน้าร้อนครับ")],
 ["na przykład", "mango"], []),

("A2", "na przykład", "chên", "เช่น", CG, SM, 4, "n",
 "Wprowadza przykład. Krótkie i bardzo częste w wyjaśnieniach.",
 "",
 [("Na przykład to danie.", "chên aa-hǎan jaan níi khráp", "เช่นอาหารจานนี้ครับ"),
  ("Lubię owoce, na przykład mango.", "phǒm châwp phǒn-lá-mái chên má-mûang khráp", "ผมชอบผลไม้เช่นมะม่วงครับ")],
 ["szczególnie", "owoce"], []),

("A2", "w sumie", "tháng mòt", "ทั้งหมด", CG, SD, 5, "n",
 "Kluczowe przy płaceniu: „tháng mòt thâo-rài khráp” — ile w sumie?",
 "wszystko całkowicie",
 [("Ile w sumie?", "tháng mòt thâo-rài khráp", "ทั้งหมดเท่าไหร่ครับ"),
  ("W sumie pięć osób.", "tháng mòt hâa khon khráp", "ทั้งหมดห้าคนครับ")],
 ["płacić", "rachunek"], ["łącznie"]),

("A2", "przynajmniej tyle", "khâe níi kâw phaw", "แค่นี้ก็พอ", CG, SD, 3, "n",
 "Uprzejme zamknięcie zamówienia albo prośby. Dosłownie „tyle i wystarczy”.",
 "tyle i wystarczy",
 [("To wszystko, dziękuję.", "khâe níi kâw phaw khráp khàwp khun", "แค่นี้ก็พอครับขอบคุณ"),
  ("Tyle wystarczy.", "khâe níi kâw phaw láew khráp", "แค่นี้ก็พอแล้วครับ")],
 ["wystarczyć", "tylko"], []),

("A2", "prawie wcale", "mâi khâwi", "ไม่ค่อย", CG, SD, 5, "n",
 "Łagodne przeczenie, bardzo tajskie. Zamiast powiedzieć wprost „nie lubię”, mówi się „mâi khâwi châwp” — niezbyt lubię.",
 "nie bardzo",
 [("Niezbyt lubię.", "phǒm mâi khâwi châwp khráp", "ผมไม่ค่อยชอบครับ"),
  ("Prawie wcale nie rozumiem.", "phǒm mâi khâwi khâo jai khráp", "ผมไม่ค่อยเข้าใจครับ")],
 ["w ogóle nie", "trochę"], ["niezbyt"]),
]
