# -*- coding: utf-8 -*-
"""Sesja F — PRZYMIOTNIKI II.

Uwaga systemowa: tajski przymiotnik jest zarazem orzeczeniem. „aa-hǎan
à-ròi” to zarowno „smaczne jedzenie”, jak i „jedzenie jest smaczne” —
czasownik „byc” nie wystepuje. Stad kazdy przymiotnik z tej listy da sie
uzyc bez zadnego dodatkowego slowa.
"""

CO = "Cechy i opinie"

ADJ_B = [

# ------------------------------------------------------------- ocena rzeczy
("A2", "podobny", "khláai", "คล้าย", CO, "Ocena", 3, "n",
 "„khláai kan” to podobne do siebie. Mocniejsze „mǔean” znaczy „taki sam”.",
 "",
 [("To jest podobne.", "an níi khláai kan khráp", "อันนี้คล้ายกันครับ"),
  ("Podobny do tamtego.", "khláai kàp an nán khráp", "คล้ายกับอันนั้นครับ")],
 ["taki sam", "inny"], []),

("A2", "prawdziwy", "tháe", "แท้", CO, "Ocena", 3, "n",
 "Ważne przy zakupach na targu: „thawng tháe” to prawdziwe złoto, „khǎwng plawm” to podróbka.",
 "",
 [("Czy to prawdziwe złoto?", "thawng tháe rǔe plào khráp", "ทองแท้หรือเปล่าครับ"),
  ("To podróbka.", "an níi plawm khráp", "อันนี้ปลอมครับ")],
 ["złoty", "fałszywy"], []),

("A2", "wygodny", "sà-baai", "สบาย", CO, "Ocena", 5, "n",
 "„sà-baai” to jedno z kluczowych słów kultury — wygoda, spokój, dobre samopoczucie. „sà-baai dii mǎi” to „jak się masz”.",
 "",
 [("Krzesło jest wygodne.", "kâo-îi nâng sà-baai khráp", "เก้าอี้นั่งสบายครับ"),
  ("Jak się pan czuje?", "sà-baai dii mǎi khráp", "สบายดีไหมครับ")],
 ["krzesło", "spokojny", "zdrowy"], []),

("A2", "niewygodny", "mâi sà-baai", "ไม่สบาย", CO, "Ocena", 4, "n",
 "Uwaga na pułapkę: „mâi sà-baai” w kontekście osoby znaczy „źle się czuję, jestem chory”, nie „jest mi niewygodnie”.",
 "nie wygodny",
 [("Źle się czuję.", "phǒm mâi sà-baai khráp", "ผมไม่สบายครับ"),
  ("To łóżko jest niewygodne.", "tiang níi nawn mâi sà-baai khráp", "เตียงนี้นอนไม่สบายครับ")],
 ["wygodny", "chory", "łóżko"], ["chory"]),

("A2", "bezpieczny", "plàwt phai", "ปลอดภัย", CO, "Ocena", 4, "f",
 "„plàwt” znaczy „wolny od”. „phai” to niebezpieczeństwo.",
 "wolny niebezpieczeństwo",
 [("Czy tu jest bezpiecznie?", "thîi nîi plàwt phai mǎi khráp", "ที่นี่ปลอดภัยไหมครับ"),
  ("Szerokiej drogi.", "doen thaang plàwt phai ná khráp", "เดินทางปลอดภัยนะครับ")],
 ["niebezpieczny", "uważać"], []),

("A2", "niebezpieczny", "an-tà-raai", "อันตราย", CO, "Ocena", 4, "n",
 "Częste na tablicach ostrzegawczych. Warto rozpoznawać także w wersji pisanej.",
 "",
 [("Tu jest niebezpiecznie.", "thîi nîi an-tà-raai khráp", "ที่นี่อันตรายครับ"),
  ("Nocą jest niebezpiecznie.", "tawn klaang khuen an-tà-raai khráp", "ตอนกลางคืนอันตรายครับ")],
 ["bezpieczny", "uważać", "noc"], []),

("A2", "przydatny", "mii prà-yòot", "มีประโยชน์", CO, "Ocena", 3, "f",
 "„prà-yòot” to korzyść, pożytek. Przeciwieństwo: „mâi mii prà-yòot”.",
 "mieć korzyść",
 [("To bardzo przydatne.", "an níi mii prà-yòot mâak khráp", "อันนี้มีประโยชน์มากครับ"),
  ("To bezużyteczne.", "mâi mii prà-yòot khráp", "ไม่มีประโยชน์ครับ")],
 ["potrzebny", "dobry"], []),

("A2", "dokładny", "lá-ìat", "ละเอียด", CO, "Ocena", 2, "n",
 "„lá-ìat” znaczy też drobno zmielony — o mące, cukrze, mięsie.",
 "",
 [("Wyjaśnił dokładnie.", "kháo à-thí-baai lá-ìat khráp", "เขาอธิบายละเอียดครับ"),
  ("Drobno posiekane.", "sàp lá-ìat khráp", "สับละเอียดครับ")],
 ["wyjaśniać", "siekać"], []),

("A2", "gruby (o rzeczy)", "nǎa", "หนา", CO, "Wymiary", 3, "n",
 "O człowieku nie mówi się „nǎa”, tylko „ûan”. Pomylenie brzmi niegrzecznie.",
 "",
 [("Książka jest gruba.", "nǎng-sǔe nǎa khráp", "หนังสือหนาครับ"),
  ("Poproszę grubszy koc.", "khǎw phâa hòm nǎa kwàa níi khráp", "ขอผ้าห่มหนากว่านี้ครับ")],
 ["cienki", "koc", "książka"], []),

("A2", "wąski", "khâep", "แคบ", CO, "Wymiary", 3, "n",
 "Częste przy opisie uliczki: „sawi khâep” — wąski zaułek.",
 "",
 [("Ulica jest wąska.", "thà-nǒn khâep khráp", "ถนนแคบครับ"),
  ("Pokój jest ciasny.", "hâwng khâep khráp", "ห้องแคบครับ")],
 ["szeroki", "ulica", "pokój"], ["ciasny"]),

("A2", "głęboki", "lúek", "ลึก", CO, "Wymiary", 3, "n",
 "Ważne przy pytaniu o wodę na plaży: „nám lúek mǎi khráp”.",
 "",
 [("Czy woda jest głęboka?", "nám lúek mǎi khráp", "น้ำลึกไหมครับ"),
  ("Tu jest płytko.", "trong níi tûen khráp", "ตรงนี้ตื้นครับ")],
 ["płytki", "woda", "pływać"], []),

("A2", "płytki", "tûen", "ตื้น", CO, "Wymiary", 2, "n",
 "Przeciwieństwo „lúek”. Nie mylić z „tùen” (obudzić się) — różni je ton.",
 "",
 [("Tu jest płytko, można stanąć.", "trong níi tûen yuen dâai khráp", "ตรงนี้ตื้นยืนได้ครับ"),
  ("Basen jest płytki.", "sà wâai nám tûen khráp", "สระว่ายน้ำตื้นครับ")],
 ["głęboki", "budzić się", "basen"], []),

("A2", "prosty (nie kręty)", "trong", "ตรง", CO, "Wymiary", 4, "n",
 "„trong” to także „prosto” w wskazówkach drogi i „punktualnie” o czasie.",
 "",
 [("Droga jest prosta.", "thaang trong khráp", "ทางตรงครับ"),
  ("Proszę jechać prosto.", "trong pai khráp", "ตรงไปครับ")],
 ["prosto", "punktualnie", "droga"], []),

("A2", "krzywy", "bìao", "เบี้ยว", CO, "Wymiary", 2, "p",
 "Potocznie „bìao” znaczy też „wystawić kogoś, nie dotrzymać słowa”.",
 "",
 [("Obraz wisi krzywo.", "rûup khwǎen bìao khráp", "รูปแขวนเบี้ยวครับ"),
  ("Wystawił mnie.", "kháo bìao phǒm khráp", "เขาเบี้ยวผมครับ")],
 ["prosty (nie kręty)", "zdjęcie"], []),

# -------------------------------------------------------------- stan rzeczy
("A2", "nowy", "mài", "ใหม่", CO, "Stan", 5, "n",
 "Uwaga na trzy podobne sylaby: „mài” (nowy), „mâi” (nie), „mǎi” (partykuła pytajna). Ton decyduje o sensie.",
 "",
 [("To nowy telefon.", "thoo-rá-sàp mài khráp", "โทรศัพท์ใหม่ครับ"),
  ("Poproszę nowy.", "khǎw an mài khráp", "ขออันใหม่ครับ")],
 ["stary (o rzeczy)", "telefon"], []),

("A2", "stary (o rzeczy)", "kào", "เก่า", CO, "Stan", 4, "n",
 "O ludziach używa się „kàe”, nie „kào”. Pomylenie jest wyraźnym błędem.",
 "",
 [("Ten samochód jest stary.", "rót khan níi kào khráp", "รถคันนี้เก่าครับ"),
  ("Mój stary przyjaciel.", "phûean kào khráp", "เพื่อนเก่าครับ")],
 ["nowy", "stary (o człowieku)", "samochód"], []),

("A2", "zepsuty", "sǐa", "เสีย", CO, "Stan", 5, "n",
 "„sǐa” pokrywa: zepsuty sprzęt, zepsute jedzenie i stratę pieniędzy („sǐa ngoen”).",
 "",
 [("Klimatyzacja jest zepsuta.", "âe sǐa khráp", "แอร์เสียครับ"),
  ("Jedzenie się zepsuło.", "aa-hǎan sǐa láew khráp", "อาหารเสียแล้วครับ")],
 ["naprawiać", "klimatyzacja", "jedzenie"], []),

("A2", "pęknięty", "tàek", "แตก", CO, "Stan", 3, "n",
 "„tàek” o szkle i ekranie, „hàk” o rzeczach podłużnych — kiju, kości, kluczu.",
 "",
 [("Ekran jest pęknięty.", "nâa jaw tàek khráp", "หน้าจอแตกครับ"),
  ("Szklanka pękła.", "kâew tàek khráp", "แก้วแตกครับ")],
 ["ekran", "szklanka", "łamać"], []),

("A2", "mokry", "pìak", "เปียก", CO, "Stan", 4, "n",
 "„pìak fǒn” — przemoczony deszczem, częste w porze deszczowej.",
 "",
 [("Ubranie jest mokre.", "sûea phâa pìak khráp", "เสื้อผ้าเปียกครับ"),
  ("Zmokłem.", "phǒm pìak fǒn khráp", "ผมเปียกฝนครับ")],
 ["suchy", "deszcz", "ubranie"], []),

("A2", "suchy", "hâeng", "แห้ง", CO, "Stan", 3, "n",
 "„hâeng” w menu znaczy „bez zupy”: „kǔai-tǐao hâeng”.",
 "",
 [("Ubranie już suche.", "sûea phâa hâeng láew khráp", "เสื้อผ้าแห้งแล้วครับ"),
  ("Makaron bez zupy.", "kǔai-tǐao hâeng khráp", "ก๋วยเตี๋ยวแห้งครับ")],
 ["mokry", "makaron w rosole", "prać"], []),

("A2", "otwarty", "pòoet yùu", "เปิดอยู่", CO, "Stan", 4, "n",
 "„yùu” po czasowniku oznacza stan trwający — odpowiednik polskiego „jest otwarte”.",
 "otwarty być",
 [("Sklep jest jeszcze otwarty.", "ráan yang pòoet yùu khráp", "ร้านยังเปิดอยู่ครับ"),
  ("Do której otwarte?", "pòoet thǔeng kìi moong khráp", "เปิดถึงกี่โมงครับ")],
 ["włączać", "zamknięty", "sklep"], []),

("A2", "zamknięty", "pìt yùu", "ปิดอยู่", CO, "Stan", 4, "n",
 "Częsta odpowiedź na targu po zmroku: „pìt láew khráp” — już zamknięte.",
 "zamknięty być",
 [("Już zamknięte.", "pìt láew khráp", "ปิดแล้วครับ"),
  ("W poniedziałek zamknięte.", "wan jan pìt khráp", "วันจันทร์ปิดครับ")],
 ["wyłączać", "otwarty", "poniedziałek"], []),

("A2", "gotowy", "sèt", "เสร็จ", CO, "Stan", 5, "n",
 "„sèt láew” to „już gotowe, skończone” — codzienne słowo w restauracji i pracy.",
 "",
 [("Już gotowe.", "sèt láew khráp", "เสร็จแล้วครับ"),
  ("Kiedy będzie gotowe?", "sèt mûea-rài khráp", "เสร็จเมื่อไหร่ครับ")],
 ["kończyć", "przygotowywać"], []),

("A2", "brakujący", "khàat", "ขาด", CO, "Stan", 3, "n",
 "„khàat” to zarazem brakować, urwać się i opuścić zajęcia: „khàat rian”.",
 "",
 [("Brakuje jednego.", "khàat pai nùeng an khráp", "ขาดไปหนึ่งอันครับ"),
  ("Opuściłem lekcję.", "phǒm khàat rian khráp", "ผมขาดเรียนครับ")],
 ["pełny", "lekcja"], []),

("A2", "dodatkowy", "phôoem", "เพิ่ม", CO, "Stan", 4, "n",
 "„khǎw … phôoem” to prosić o dokładkę — bardzo praktyczne w jadłodajni.",
 "",
 [("Poproszę dokładkę ryżu.", "khǎw khâao phôoem khráp", "ขอข้าวเพิ่มครับ"),
  ("Za dodatkową opłatą.", "jàai phôoem khráp", "จ่ายเพิ่มครับ")],
 ["ryż", "płacić", "jeszcze"], []),

# ------------------------------------------------------------------- smaki
("A2", "smaczny", "à-ròi", "อร่อย", CO, "Smak", 5, "n",
 "Najczęstszy komplement w Tajlandii. Wzmocnienie: „à-ròi mâak” albo „à-ròi jang loei”.",
 "",
 [("Bardzo smaczne.", "à-ròi mâak khráp", "อร่อยมากครับ"),
  ("Czy to smaczne?", "à-ròi mǎi khráp", "อร่อยไหมครับ")],
 ["jedzenie", "niesmaczny"], []),

("A2", "niesmaczny", "mâi à-ròi", "ไม่อร่อย", CO, "Smak", 3, "n",
 "Mówione rzadko i ostrożnie — bezpośrednia krytyka jedzenia bywa odbierana jako nietakt.",
 "nie smaczny",
 [("Nie jest zbyt smaczne.", "mâi khâwi à-ròi khráp", "ไม่ค่อยอร่อยครับ"),
  ("Wolę tamto.", "phǒm châwp an nán mâak kwàa khráp", "ผมชอบอันนั้นมากกว่าครับ")],
 ["smaczny", "wolę"], []),

("A2", "kwaśny", "prîao", "เปรี้ยว", CO, "Smak", 4, "n",
 "Potocznie o osobie „prîao” znaczy „wyzywająca, kokietka” — używać ostrożnie.",
 "",
 [("Za kwaśne.", "prîao koen pai khráp", "เปรี้ยวเกินไปครับ"),
  ("Mango jest kwaśne.", "má-mûang prîao khráp", "มะม่วงเปรี้ยวครับ")],
 ["słodki", "limonka", "mango"], []),

("A2", "gorzki", "khǒm", "ขม", CO, "Smak", 3, "n",
 "Uwaga na parę: „khǒm” (gorzki) i „khom” (ostry o krawędzi) różni tylko ton.",
 "",
 [("Kawa jest gorzka.", "kaa-fae khǒm khráp", "กาแฟขมครับ"),
  ("Lek jest gorzki.", "yaa khǒm khráp", "ยาขมครับ")],
 ["kawa", "lek", "ostry (o krawędzi)"], []),

("A2", "mdły", "cùet", "จืด", CO, "Smak", 3, "n",
 "„kaeng cùet” to łagodna zupa bez przypraw — bezpieczny wybór dla chorego żołądka.",
 "",
 [("To jest mdłe.", "cùet pai nòi khráp", "จืดไปหน่อยครับ"),
  ("Poproszę łagodną zupę.", "khǎw kaeng cùet khráp", "ขอแกงจืดครับ")],
 ["słony", "zupa", "chory"], ["bez smaku"]),

("A2", "tłusty", "man", "มัน", CO, "Smak", 3, "n",
 "„man” to także „on, to” jako zaimek nieformalny — kontekst rozstrzyga.",
 "",
 [("Za tłuste.", "man koen pai khráp", "มันเกินไปครับ"),
  ("Mniej oleju, proszę.", "sài nám man nói nói khráp", "ใส่น้ำมันน้อยๆครับ")],
 ["olej", "smażyć na patelni"], []),

("A2", "świeży", "sòt", "สด", CO, "Smak", 4, "n",
 "„aa-hǎan tá-lee sòt” to świeże owoce morza — hasło na szyldach nadmorskich restauracji.",
 "",
 [("Czy ryba jest świeża?", "plaa sòt mǎi khráp", "ปลาสดไหมครับ"),
  ("Świeży sok.", "nám phǒn-lá-mái sòt khráp", "น้ำผลไม้สดครับ")],
 ["ryba", "owoc", "stary (o rzeczy)"], []),

# -------------------------------------------------------------- ludzie
("A2", "zajęty (o osobie)", "mâi wâang", "ไม่ว่าง", CO, "Ludzie", 4, "n",
 "„mâi wâang” to zarazem „nie mam czasu” i „zajęte” o miejscu czy toalecie.",
 "nie wolny",
 [("Jestem dziś zajęty.", "wan níi phǒm mâi wâang khráp", "วันนี้ผมไม่ว่างครับ"),
  ("Toaleta zajęta.", "hâwng-nám mâi wâang khráp", "ห้องน้ำไม่ว่างครับ")],
 ["wolny (o czasie)", "łazienka", "czas"], []),

("A2", "uczciwy", "sûe sàt", "ซื่อสัตย์", CO, "Ludzie", 3, "f",
 "Cecha ceniona i chwalona wprost, w odróżnieniu od krytyki, którą wypowiada się pośrednio.",
 "",
 [("To uczciwy człowiek.", "kháo pen khon sûe sàt khráp", "เขาเป็นคนซื่อสัตย์ครับ"),
  ("Można mu ufać.", "wái jai dâai khráp", "ไว้ใจได้ครับ")],
 ["ufać", "kłamać"], []),

("A2", "cierpliwy", "jai yen", "ใจเย็น", CO, "Ludzie", 4, "n",
 "Dosłownie „chłodne serce”. Powiedziane komuś zdenerwowanemu znaczy „spokojnie”.",
 "serce zimne",
 [("Proszę zachować spokój.", "jai yen yen khráp", "ใจเย็นๆครับ"),
  ("Jest bardzo cierpliwy.", "kháo jai yen mâak khráp", "เขาใจเย็นมากครับ")],
 ["spokojny", "nerwowy"], ["spokojny"]),

("A2", "nerwowy", "jai ráwn", "ใจร้อน", CO, "Ludzie", 3, "n",
 "Dosłownie „gorące serce”. Cecha oceniana wyraźnie negatywnie — okazywanie złości obniża status.",
 "serce gorące",
 [("Jest niecierpliwy.", "kháo jai ráwn khráp", "เขาใจร้อนครับ"),
  ("Nie denerwuj się.", "yàa jai ráwn khráp", "อย่าใจร้อนครับ")],
 ["cierpliwy", "gniewać się"], ["niecierpliwy"]),

("A2", "wesoły", "râa-rooeng", "ร่าเริง", CO, "Ludzie", 2, "n",
 "Pozytywna cecha charakteru, częsta w opisie dziecka.",
 "",
 [("To wesołe dziecko.", "dèk khon níi râa-rooeng khráp", "เด็กคนนี้ร่าเริงครับ"),
  ("Wygląda na wesołego.", "duu râa-rooeng dii khráp", "ดูร่าเริงดีครับ")],
 ["smutny", "dziecko", "śmiać się"], []),

("A2", "smutny", "sâo", "เศร้า", CO, "Ludzie", 3, "n",
 "„sâo” to smutek głębszy. Codzienne „nie w humorze” to „aa-rom mâi dii”.",
 "",
 [("Dlaczego jesteś smutny?", "tham-mai thǔeng sâo khráp", "ทำไมถึงเศร้าครับ"),
  ("Nie jestem w humorze.", "aa-rom mâi dii khráp", "อารมณ์ไม่ดีครับ")],
 ["wesoły", "płakać", "nastrój"], []),

("A2", "zdenerwowany", "tùen tên", "ตื่นเต้น", CO, "Ludzie", 3, "n",
 "Uwaga: „tùen tên” obejmuje zarówno tremę, jak i pozytywne podekscytowanie.",
 "budzić się drżeć",
 [("Jestem zdenerwowany.", "phǒm tùen tên khráp", "ผมตื่นเต้นครับ"),
  ("Nie denerwuj się.", "mâi tâwng tùen tên khráp", "ไม่ต้องตื่นเต้นครับ")],
 ["bać się", "spokojny"], ["podekscytowany"]),

("A2", "dumny", "phuum jai", "ภูมิใจ", CO, "Ludzie", 2, "f",
 "Kolejne złożenie z „jai”. Rodzina słów z sercem to jeden z najbardziej produktywnych wzorców tajszczyzny.",
 "grunt serce",
 [("Jestem dumny z syna.", "phǒm phuum jai nai lûuk khráp", "ผมภูมิใจในลูกครับ"),
  ("To powód do dumy.", "nâa phuum jai khráp", "น่าภูมิใจครับ")],
 ["syn", "szczęśliwy"], []),

("A2", "zawstydzony", "aai", "อาย", CO, "Ludzie", 3, "n",
 "„khîi aai” to nieśmiały jako cecha stała, „aai” to chwilowe zawstydzenie.",
 "",
 [("Wstydzę się.", "phǒm aai khráp", "ผมอายครับ"),
  ("Jest nieśmiały.", "kháo khîi aai khráp", "เขาขี้อายครับ")],
 ["nieśmiały", "śmiać się"], []),

("A2", "zazdrosny", "ìt-chǎa", "อิจฉา", CO, "Ludzie", 2, "n",
 "Uwaga: w mowie potocznej „ìt-chǎa” bywa mówione żartem, jako komplement — „zazdroszczę ci”.",
 "",
 [("Zazdroszczę ci.", "ìt-chǎa jang loei khráp", "อิจฉาจังเลยครับ"),
  ("Nie zazdrość.", "yàa ìt-chǎa khráp", "อย่าอิจฉาครับ")],
 ["szczęśliwy", "chcieć"], ["zazdroszczę"]),

("A2", "samotny", "ngǎo", "เหงา", CO, "Ludzie", 3, "n",
 "„ngǎo” to uczucie samotności, nie fakt bycia samemu — do tego służy „khon diao”.",
 "",
 [("Czuję się samotny.", "phǒm ngǎo khráp", "ผมเหงาครับ"),
  ("Mieszkam sam.", "phǒm yùu khon diao khráp", "ผมอยู่คนเดียวครับ")],
 ["smutny", "sam", "przyjaciel"], []),

("A2", "głodny", "hǐu", "หิว", CO, "Ludzie", 5, "n",
 "„hǐu nám” to być spragnionym — dosłownie „głodny wody”.",
 "",
 [("Jestem głodny.", "phǒm hǐu khráp", "ผมหิวครับ"),
  ("Chce mi się pić.", "phǒm hǐu nám khráp", "ผมหิวน้ำครับ")],
 ["najedzony", "jeść", "woda"], []),

("A2", "najedzony", "ìm", "อิ่ม", CO, "Ludzie", 4, "n",
 "„ìm láew khráp” to uprzejma odmowa dokładki, częsta i oczekiwana.",
 "",
 [("Jestem najedzony.", "ìm láew khráp", "อิ่มแล้วครับ"),
  ("Dziękuję, wystarczy.", "phaw láew khráp khàwp khun khráp", "พอแล้วครับ ขอบคุณครับ")],
 ["głodny", "jeść", "wystarczy"], []),

("A2", "pijany", "mao", "เมา", CO, "Ludzie", 3, "p",
 "„mao rót” to choroba lokomocyjna — to samo słowo, inne znaczenie.",
 "",
 [("Jest pijany.", "kháo mao khráp", "เขาเมาครับ"),
  ("Mam chorobę lokomocyjną.", "phǒm mao rót khráp", "ผมเมารถครับ")],
 ["alkohol", "samochód", "chory"], []),

("A2", "śpiący", "ngûang", "ง่วง", CO, "Ludzie", 4, "n",
 "„ngûang nawn” to pełna forma. Częste wyjaśnienie przy wcześniejszym pożegnaniu.",
 "",
 [("Chce mi się spać.", "phǒm ngûang khráp", "ผมง่วงครับ"),
  ("Jestem śpiący, idę spać.", "ngûang láew pai nawn khráp", "ง่วงแล้วไปนอนครับ")],
 ["spać", "zmęczony", "noc"], []),

("A2", "zajęty pracą", "ngaan yúng", "งานยุ่ง", CO, "Ludzie", 3, "n",
 "„yúng” samo znaczy „zabałaganiony, skomplikowany” — także o sytuacji.",
 "praca zagmatwany",
 [("Mam dużo pracy.", "ngaan yúng khráp", "งานยุ่งครับ"),
  ("Sytuacja jest skomplikowana.", "rûeang yúng khráp", "เรื่องยุ่งครับ")],
 ["praca", "zajęty (o osobie)"], []),
]
