# -*- coding: utf-8 -*-
"""Sesja N, partia piąta — CZASOWNIKI II, MATERIAŁY, NARZĘDZIA, PRZEDMIOTY SZKOLNE.

Ostatnia partia domyka trzy luki, które zostały po poprzednich czterech:

1. **Czasowniki drugiego rzutu.** Baza miała ruch, jedzenie i mówienie.
   Nie miała czasowników działania na świecie: budować, niszczyć, chronić,
   atakować, tworzyć, odkrywać, ukrywać, mierzyć, ważyć, liczyć na kogoś.
2. **Materiały i narzędzia.** Bez nich nie da się opisać żadnej awarii ani
   naprawy, a to jest sytuacja, w której uczący się faktycznie musi mówić.
3. **Przedmioty szkolne i dziedziny.** Pierwsze pytanie po „czym się
   zajmujesz” dotyczy dziedziny, a baza nie miała ani jednej nazwy.

Krotka: (poziom, polski, fonetyka, pismo, podkategoria, częstość, typ,
         kategoria, uwaga, dosłownie)
"""

CZ = "Czasowniki"
DM = "Dom i codzienność"
PN = "Praca i nauka"
CO = "Cechy i opinie"
LI = "Liczby i liczenie"
ZK = "Zakupy i pieniądze"
GR = "Gramatyka użytkowa"
JN = "Jedzenie i napoje"

ACT = [

# ============================================================ CZASOWNIKI DZIAŁANIA
("A2", "budować", "sâang", "สร้าง", "Działanie", 4, "v", CZ,
 "Także „tworzyć, zakładać”: sâang khrâwp khrua — założyć rodzinę.", ""),
("A2", "niszczyć", "tham laai", "ทำลาย", "Działanie", 3, "v", CZ,
 "laai samo znaczy „rozpadać się”.", "robić rozpad"),
("A2", "chronić, strzec", "pâwng kan", "ป้องกัน", "Działanie", 3, "v", CZ,
 "kan to zapobiegać — ten sam wyraz co w mùak kan náwk.", "bronić zapobiegać"),
("A2", "atakować", "joom tii", "โจมตี", "Działanie", 2, "v", CZ,
 "tii samo to uderzać.", "napadać uderzać"),
("A2", "uderzać", "tii", "ตี", "Działanie", 3, "v", CZ,
 "Także „wybijać godzinę” — tii nùeng to pierwsza w nocy.", ""),
("A2", "bronić się", "tàw sûu", "ต่อสู้", "Działanie", 2, "v", CZ,
 "Także „walczyć o coś”.", "przeciw walczyć"),
("A2", "tworzyć, wymyślać", "khít khôn", "คิดค้น", "Działanie", 2, "v", CZ,
 "khôn to poszukiwać, badać.", "myśleć badać"),
("A2", "odkrywać", "khón phóp", "ค้นพบ", "Działanie", 2, "v", CZ,
 "phóp to spotkać, natrafić.", "szukać spotykać"),
("A2", "ukrywać (coś)", "sâwn", "ซ่อน", "Działanie", 3, "v", CZ,
 "sâwn tua — ukrywać się.", ""),
("A2", "pokazywać, prezentować", "sà-daeng", "แสดง", "Działanie", 4, "v", CZ,
 "Także „grać rolę, występować”.", ""),
("A2", "mierzyć", "wát", "วัด", "Działanie", 4, "v", CZ,
 "Homofon z wát (świątynia) — ten sam zapis, dwa wyrazy.", ""),
("A2", "ważyć (coś)", "châng", "ชั่ง", "Działanie", 3, "v", CZ,
 "châng nám-nàk — zważyć.", ""),
("A2", "liczyć na kogoś", "phûeng", "พึ่ง", "Działanie", 3, "v", CZ,
 "phûeng dâi — można na nim polegać.", ""),
("A2", "polegać, ufać w działaniu", "wái wang jai", "ไว้วางใจ", "Działanie", 2, "v", CZ,
 "", "powierzać kłaść serce"),
("A2", "pilnować, doglądać", "fâo", "เฝ้า", "Działanie", 3, "v", CZ,
 "fâo bâan — pilnować domu.", ""),
("A2", "naprawić usterkę", "kâe", "แก้", "Działanie", 5, "v", CZ,
 "Bardzo produktywne: kâe pan-hǎa (rozwiązać problem), kâe phèt (złagodzić ostrość), yaa kâe pùat.", ""),
("A2", "poprawić, zmienić na lepsze", "prap prung", "ปรับปรุง", "Działanie", 3, "v", CZ,
 "Słowo z każdej tabliczki „przepraszamy za remont”.", ""),
("A2", "dostosować, wyregulować", "prap", "ปรับ", "Działanie", 3, "v", CZ,
 "Uwaga: to samo brzmienie co „karać” — khâa pràp to mandat.", ""),
("A2", "zamówić z wyprzedzeniem", "sàng láew ráw", "สั่งแล้วรอ", "Działanie", 2, "v", CZ,
 "", "zamawiać potem czekać"),
("A2", "dostarczyć", "sòng thǔeng", "ส่งถึง", "Działanie", 3, "v", CZ,
 "", "wysyłać docierać"),
("A2", "odebrać, podnieść (telefon)", "ráp sǎai", "รับสาย", "Działanie", 4, "v", CZ,
 "sǎai to linia — także autobusowa.", "przyjmować linia"),
("A2", "rozłączyć się", "waang sǎai", "วางสาย", "Działanie", 3, "v", CZ,
 "Dosłownie „odłożyć linię”.", "kłaść linia"),
("A2", "spróbować jeszcze raz", "lawng ìik khráng", "ลองอีกครั้ง", "Działanie", 4, "v", CZ,
 "", "próbować jeszcze raz"),
("A2", "poddać się, zrezygnować", "yawm phǽe", "ยอมแพ้", "Działanie", 3, "v", CZ,
 "yawm to godzić się, ustępować.", "godzić się przegrywać"),
("A2", "zgodzić się na coś", "yawm", "ยอม", "Działanie", 4, "v", CZ,
 "Odcień ustępstwa, nie entuzjazmu.", ""),
("A2", "nalegać", "yuen yan", "ยืนยัน", "Działanie", 3, "v", CZ,
 "Także „potwierdzać”: yuen yan kaan jawng.", "stać trwać"),
("A2", "narzekać oficjalnie, złożyć skargę", "ráwng rian", "ร้องเรียน", "Działanie", 2, "v", CZ,
 "", "wołać zgłaszać"),
("A2", "przeprosić formalnie", "khǎw à-phai", "ขออภัย", "Działanie", 3, "v", CZ,
 "Sztywniejsze niż khǎw thôot; napis w komunikatach.", "prosić wybaczenie"),
("A2", "podziękować za coś", "khàwp khun sǎm-ràp", "ขอบคุณสำหรับ", "Działanie", 3, "v", CZ,
 "", "dziękować za"),
("A2", "przypomnieć sobie nagle", "nùek dâi", "นึกได้", "Działanie", 4, "v", CZ,
 "", "myśleć móc"),
("A2", "zauważyć różnicę", "hěn khwaam tàek tàang", "เห็นความแตกต่าง", "Działanie", 2, "v", CZ,
 "", "widzieć różnica"),
("A2", "sprzątnąć ze stołu", "kèp tó", "เก็บโต๊ะ", "Działanie", 3, "v", CZ,
 "", "zbierać stół"),
("A2", "podlewać", "rót nám", "รดน้ำ", "Działanie", 2, "v", CZ,
 "Uwaga: rót to tu „polewać”, homofon z rót (pojazd).", "polewać woda"),
("A2", "karmić zwierzę", "hâi aa-hǎan sàt", "ให้อาหารสัตว์", "Działanie", 2, "v", CZ,
 "", "dawać jedzenie zwierzę"),
("A2", "hodować", "líang sàt", "เลี้ยงสัตว์", "Działanie", 2, "v", CZ,
 "Znów líang — karmić, utrzymywać.", "karmić zwierzę"),

# ============================================================ MATERIAŁY
("A2", "materiał, tworzywo", "wát-sà-dù", "วัสดุ", "Materiały", 3, "n", DM,
 "", ""),
("A2", "żelazo, stal", "lèk", "เหล็ก", "Materiały", 3, "n", DM,
 "Uwaga: lèk (żelazo) kontra lék (mały) — sam ton.", ""),
("A2", "złoto", "thawng", "ทอง", "Materiały", 4, "n", DM,
 "Sklepy ze złotem mają stałą cenę dzienną, wywieszoną na tablicy.", ""),
("A2", "srebro", "ngoen", "เงิน", "Materiały", 4, "n", DM,
 "To samo słowo znaczy „pieniądze”.", ""),
("A2", "miedź", "thawng daeng", "ทองแดง", "Materiały", 2, "n", DM,
 "", "złoto czerwony"),
("A2", "beton", "khawn-krìit", "คอนกรีต", "Materiały", 2, "n", DM,
 "", ""),
("A2", "cegła", "ìt", "อิฐ", "Materiały", 2, "n", DM,
 "", ""),
("A2", "cement", "puun", "ปูน", "Materiały", 2, "n", DM,
 "", ""),
("A2", "guma, kauczuk", "yaang", "ยาง", "Materiały", 3, "n", DM,
 "Także opona i żywica. Kauczuk to duży towar eksportowy południa.", ""),
("A2", "skóra (materiał)", "nǎng sàt", "หนังสัตว์", "Materiały", 2, "n", DM,
 "Samo nǎng to skóra i film.", "skóra zwierzę"),
("A2", "wełna", "khǒn sàt", "ขนสัตว์", "Materiały", 2, "n", DM,
 "khǒn to sierść, pióro, włos na ciele.", "sierść zwierzę"),
("A2", "len", "phâa lin-nin", "ผ้าลินิน", "Materiały", 2, "n", DM,
 "", "tkanina len"),
("A2", "porcelana", "khrûeang lai khraam", "เครื่องลายคราม", "Materiały", 2, "n", DM,
 "", "wyrób wzór błękit"),
("A2", "glina", "din nǐao", "ดินเหนียว", "Materiały", 2, "n", DM,
 "nǐao to kleisty — to samo słowo co w khâao nǐao.", "ziemia kleisty"),

# ============================================================ NARZĘDZIA
("A2", "narzędzie ręczne", "khrûeang mue", "เครื่องมือ", "Narzędzia", 3, "n", DM,
 "", "urządzenie ręka"),
("A2", "piła", "lûeai", "เลื่อย", "Narzędzia", 2, "n", DM,
 "Uwaga: lûeai (piła) kontra lûean (przesuwać).", ""),
("A2", "wiertarka", "sà-wàan", "สว่าน", "Narzędzia", 2, "n", DM,
 "", ""),
("A2", "śruba", "nàwt", "น็อต", "Narzędzia", 2, "n", DM,
 "Z angielskiego nut. Ten sam wyraz w mùak kan náwk.", ""),
("A2", "klucz płaski", "prà-jae", "ประแจ", "Narzędzia", 2, "n", DM,
 "Nie mylić z kun-jae (klucz do drzwi).", ""),
("A2", "drabina", "ban-dai lûean thîi", "บันไดพาด", "Narzędzia", 2, "n", DM,
 "Samo ban-dai znaczy i schody, i drabinę.", "schody oparty"),
("A2", "lina, sznur", "chûeak", "เชือก", "Narzędzia", 3, "n", DM,
 "Także klasyfikator słoni — jeden z osobliwszych w języku.", ""),
("A2", "kabel, przewód", "sǎai fai", "สายไฟ", "Narzędzia", 3, "n", DM,
 "Znów sǎai — linia.", "linia prąd"),
("A2", "bezpiecznik, korek", "fíu", "ฟิวส์", "Narzędzia", 2, "n", DM,
 "", ""),
("A2", "pompa", "pám", "ปั๊ม", "Narzędzia", 2, "n", DM,
 "To samo słowo co w pám nám man.", ""),
("A2", "generator prądu", "khrûeang pàn fai", "เครื่องปั่นไฟ", "Narzędzia", 2, "n", DM,
 "pàn to kręcić, miksować.", "maszyna kręcić prąd"),
("A2", "silnik", "khrûeang yon", "เครื่องยนต์", "Narzędzia", 2, "n", DM,
 "", "maszyna mechanizm"),
("A2", "bateria słoneczna", "phaen soo-lâa", "แผงโซลาร์", "Narzędzia", 2, "n", DM,
 "", "panel solarny"),

# ============================================================ DZIEDZINY
("A2", "matematyka", "khá-nít-tà-sàat", "คณิตศาสตร์", "Dziedziny", 3, "n", PN,
 "Końcówka -sàat oznacza dziedzinę wiedzy, jak polskie -ologia.", ""),
("A2", "historia", "prà-wàt-tì-sàat", "ประวัติศาสตร์", "Dziedziny", 3, "n", PN,
 "prà-wàt samo znaczy „życiorys, przebieg”.", ""),
("A2", "geografia", "phuu-mí-sàat", "ภูมิศาสตร์", "Dziedziny", 2, "n", PN,
 "phuu-mí to teren — ten sam człon co w phuu-mí-aa-kàat.", ""),
("A2", "biologia", "chii-wá-wít-thá-yaa", "ชีววิทยา", "Dziedziny", 2, "n", PN,
 "chii-wá to życie — od chîi-wít.", "życie nauka"),
("A2", "chemia", "kee-mii", "เคมี", "Dziedziny", 2, "n", PN,
 "", ""),
("A2", "fizyka", "fí-sìk", "ฟิสิกส์", "Dziedziny", 2, "n", PN,
 "", ""),
("A2", "informatyka", "khawm-phíu-tôe", "วิทยาการคอมพิวเตอร์", "Dziedziny", 3, "n", PN,
 "W mowie skracane do samego khawm.", ""),
("A2", "ekonomia (kierunek)", "sèet-thà-sàat", "เศรษฐศาสตร์", "Dziedziny", 2, "n", PN,
 "", ""),
("A2", "medycyna (kierunek)", "phâet-thá-sàat", "แพทยศาสตร์", "Dziedziny", 2, "n", PN,
 "phâet to lekarz w rejestrze formalnym.", ""),
("A2", "prawo (kierunek)", "ní-tì-sàat", "นิติศาสตร์", "Dziedziny", 2, "n", PN,
 "", ""),
("A2", "sztuka", "sǐn-lá-pà", "ศิลปะ", "Dziedziny", 3, "n", PN,
 "sǐn-lá-pin — artysta.", ""),
("A2", "literatura", "wan-ná-khá-dii", "วรรณคดี", "Dziedziny", 2, "n", PN,
 "", ""),
("A2", "filozofia", "prat-yaa", "ปรัชญา", "Dziedziny", 2, "n", PN,
 "", ""),
("A2", "psychologia", "jìt-tà-wít-thá-yaa", "จิตวิทยา", "Dziedziny", 2, "n", PN,
 "jìt to umysł, psychika.", "umysł nauka"),
("A2", "architektura", "sà-thǎa-pàt-tà-yá-kam", "สถาปัตยกรรม", "Dziedziny", 2, "n", PN,
 "", ""),
("A2", "rolnictwo", "kà-sèet", "เกษตร", "Dziedziny", 2, "n", PN,
 "kà-sèet-tà-kawn — rolnik w rejestrze formalnym.", ""),
("A2", "turystyka", "kaan thâwng thîao", "การท่องเที่ยว", "Dziedziny", 3, "n", PN,
 "Największa gałąź gospodarki kraju.", "czynność podróżować"),

# ============================================================ KLASYFIKATORY
("A2", "sztuka (klasyfikator ogólny)", "an", "อัน", "Klasyfikatory", 5, "n", LI,
 "Ratunek, gdy nie znamy właściwego klasyfikatora. Zrozumiały zawsze, choć nie zawsze poprawny.", ""),
("A2", "arkusz (klasyfikator płaskich)", "bai", "ใบ", "Klasyfikatory", 5, "n", LI,
 "Liście, bilety, dokumenty, torby, owoce.", ""),
("A2", "sztuka (klasyfikator zwierząt i ubrań)", "tua", "ตัว", "Klasyfikatory", 5, "n", LI,
 "Zwierzęta, koszule, spodnie, krzesła, stoły. Także „ciało, ja sam”.", ""),
("A2", "sztuka (klasyfikator ludzi)", "khon", "คน", "Klasyfikatory", 5, "n", LI,
 "Do mnichów i osób królewskich używa się innych.", ""),
("A2", "butelka (klasyfikator)", "khùat", "ขวด", "Klasyfikatory", 4, "n", LI,
 "nám sǎwng khùat — dwie butelki wody.", ""),
("A2", "szklanka (klasyfikator)", "kâew", "แก้ว", "Klasyfikatory", 4, "n", LI,
 "Także samo szkło i kryształ.", ""),
("A2", "sztuka (klasyfikator maszyn)", "khrûeang", "เครื่อง", "Klasyfikatory", 3, "n", LI,
 "Ten sam wyraz co „maszyna”.", ""),
("A2", "sztuka (klasyfikator pojazdów)", "khan", "คัน", "Klasyfikatory", 4, "n", LI,
 "Samochody, rowery, parasole, łyżki.", ""),
("A2", "sztuka (klasyfikator książek)", "lêm", "เล่ม", "Klasyfikatory", 4, "n", LI,
 "Książki, zeszyty, noże.", ""),
("A2", "sztuka (klasyfikator budynków)", "lǎng", "หลัง", "Klasyfikatory", 3, "n", LI,
 "Ten sam wyraz co „plecy, za”.", ""),
("A2", "kawałek, bryła (klasyfikator)", "kâwn", "ก้อน", "Klasyfikatory", 3, "n", LI,
 "Kamienie, kostki lodu, mydło, chmury.", ""),
("A2", "para (klasyfikator butów)", "khûu", "คู่", "Klasyfikatory", 4, "n", LI,
 "Ten sam wyraz co „para ludzi”.", ""),
("A2", "sztuka (klasyfikator owoców okrągłych)", "lûuk", "ลูก", "Klasyfikatory", 4, "n", LI,
 "Ten sam wyraz co „dziecko”. Także piłki i góry.", ""),
("A2", "porcja, talerz (klasyfikator)", "thîi", "ที่", "Klasyfikatory", 4, "n", LI,
 "sǎwng thîi — dwie porcje. Ten sam wyraz co „miejsce”.", ""),

# ============================================================ DROBNE UZUPEŁNIENIA
("A2", "co najwyżej, maksymalnie", "yàang mâak thîi sùt", "อย่างมากที่สุด", "Partykuły", 3, "w", GR,
 "", "sposób dużo najbardziej"),
("A2", "coraz bardziej", "yîng khûen", "ยิ่งขึ้น", "Partykuły", 3, "w", GR,
 "yîng … yîng — im bardziej, tym bardziej.", "tym bardziej wznosić"),
("A2", "wręcz przeciwnie", "trong kan khâam", "ตรงกันข้าม", "Partykuły", 3, "w", GR,
 "Także „naprzeciwko” w sensie miejsca.", "prosto nawzajem przeciw"),
("A2", "w zasadzie, generalnie", "doi thûa pai", "โดยทั่วไป", "Partykuły", 3, "w", GR,
 "doi- tworzy przysłówki sposobu.", "przez ogólnie"),
("A2", "szczególnie, zwłaszcza", "doi chà-phǽ", "โดยเฉพาะ", "Partykuły", 4, "w", GR,
 "", "przez szczególnie"),
("A2", "przynajmniej", "yàang náwi thîi sùt", "อย่างน้อยที่สุด", "Partykuły", 3, "w", GR,
 "", "sposób mało najbardziej"),
("A2", "poza tym, w dodatku", "nâwk jàak níi", "นอกจากนี้", "Partykuły", 4, "w", GR,
 "", "oprócz to"),
("A2", "innymi słowy", "phûut ìik yàang", "พูดอีกอย่าง", "Partykuły", 3, "w", GR,
 "", "mówić jeszcze sposób"),
("A2", "krótko mówiąc", "sà-rùp wâa", "สรุปว่า", "Partykuły", 3, "w", GR,
 "sà-rùp to podsumowywać.", "podsumowywać że"),
("A2", "podsumowanie", "khâw sà-rùp", "ข้อสรุป", "Partykuły", 3, "n", PN,
 "", "punkt podsumowanie"),
("A2", "przyprawa do zupy", "khrûeang kaeng", "เครื่องแกง", "Składniki", 3, "n", JN,
 "Gotowa pasta curry — podstawa domowego gotowania.", "wyposażenie curry"),
("A2", "sos chili", "náam phrík", "น้ำพริก", "Składniki", 4, "n", JN,
 "Cała rodzina past chili, jadanych z warzywami i ryżem.", "woda chili"),
("A2", "przystawka do piwa", "kàp klâem", "กับแกล้ม", "Potrawy", 3, "n", JN,
 "Osobna kategoria w menu — jedzenie do picia, nie posiłek.", "z zagryzka"),
("A2", "danie jednogarnkowe z ryżem", "khâao raat kaeng", "ข้าวราดแกง", "Potrawy", 4, "n", JN,
 "Wskazujesz palcem, co ma wylądować na ryżu. Najtańszy sposób jedzenia.", "ryż polewać curry"),
("A2", "przepis (kulinarny)", "sùut aa-hǎan", "สูตรอาหาร", "Potrawy", 2, "n", JN,
 "sùut to formuła, wzór.", "formuła jedzenie"),
("A2", "porcja na wynos w pudełku", "khâao klàwng", "ข้าวกล่อง", "Potrawy", 3, "n", JN,
 "", "ryż pudełko"),
("A2", "wybredny w jedzeniu", "lûeak kin", "เลือกกิน", "Ocena", 3, "adj", CO,
 "", "wybierać jeść"),
("A2", "na diecie", "lót nám-nàk", "ลดน้ำหนัก", "Ocena", 3, "v", ZK,
 "Dosłownie „obniżać wagę”.", "obniżać waga"),
]
