# -*- coding: utf-8 -*-
"""Wzorce zdaniowe etapu 3 (A2) — czesc B: konstrukcje przymiotnikowe.

Biale listy: przymiotnik trafia do wzorca tylko wtedy, gdy polskie zdanie brzmi
naturalnie. Dlatego np. wzorzec „Robi sie coraz …" nie obejmuje „prawdziwy",
a wzorzec „Czuje sie …" tylko stany emocjonalne.

Pozycja: (polskie haslo rekordu, polskie haslo bazowe, polski przyklad)
"""

TPL_B = [

# =====================================================================
# … kwaa — stopien wyzszy
# =====================================================================
dict(key="KWAA", ty="collocation", cat="Gramatyka użytkowa", sub="Porównania", reg="n",
     ph="{ph} kwàa", th="{th}กว่า",
     lit="kwàa po przymiotniku = stopień wyższy",
     note="Tajski nie zmienia formy przymiotnika — dokleja „kwàa”. Drugi człon porównania idzie po nim.",
     ex_ph="an níi {ph} kwàa khráp", ex_th="อันนี้{th}กว่าครับ",
     items=[
       ("większy", "duży", "Ten jest większy."),
       ("mniejszy", "mały", "Ten jest mniejszy."),
       ("dłuższy", "długi", "Ten jest dłuższy."),
       ("krótszy", "krótki", "Ten jest krótszy."),
       ("droższy", "drogi", "Ten jest droższy."),
       ("tańszy", "tani", "Ten jest tańszy."),
       ("nowszy", "nowy", "Ten jest nowszy."),
       ("starszy", "stary", "Ten jest starszy."),
       ("szybszy", "szybki", "Ten jest szybszy."),
       ("wolniejszy", "wolny (powolny)", "Ten jest wolniejszy."),
       ("cieplejszy", "gorący", "Ten jest cieplejszy."),
       ("zimniejszy", "zimny (o napoju)", "Ten jest zimniejszy."),
       ("cięższy", "ciężki", "Ten jest cięższy."),
       ("lżejszy", "lekki", "Ten jest lżejszy."),
       ("czystszy", "czysty", "Ten jest czystszy."),
       ("jaśniejszy", "jasny", "Ten jest jaśniejszy."),
       ("ciemniejszy", "ciemny", "Ten jest ciemniejszy."),
       ("głośniejszy", "głośny", "Ten jest głośniejszy."),
       ("cichszy", "cichy / spokojny", "Ten jest cichszy."),
       ("łatwiejszy", "łatwy", "Ten jest łatwiejszy."),
       ("trudniejszy", "trudny", "Ten jest trudniejszy."),
       ("ciekawszy", "interesujący", "Ten jest ciekawszy."),
       ("nudniejszy", "nudny", "Ten jest nudniejszy."),
       ("ważniejszy", "ważny", "To jest ważniejsze."),
       ("wygodniejszy", "wygodny", "Ten jest wygodniejszy."),
       ("bezpieczniejszy", "bezpieczny", "Ten jest bezpieczniejszy."),
       ("smaczniejszy", "smaczny", "Ten jest smaczniejszy."),
       ("słodszy", "słodki", "Ten jest słodszy."),
       ("bardziej słony", "słony", "Ten jest bardziej słony."),
       ("ostrzejszy", "ostry (pikantny)", "Ten jest ostrzejszy."),
       ("świeższy", "świeży", "Ten jest świeższy."),
       ("bliższy", "bliski", "Ten jest bliższy."),
       ("dalszy", "daleki", "Ten jest dalszy."),
       ("wyższy", "wysoki", "Ten jest wyższy."),
       ("głębszy", "głęboki", "Ten jest głębszy."),
       ("mocniejszy", "silny, mocny", "Ten jest mocniejszy."),
       ("słabszy", "słaby", "Ten jest słabszy."),
       ("twardszy", "twardy", "Ten jest twardszy."),
       ("bardziej miękki", "miękki", "Ten jest bardziej miękki."),
       ("ładniejszy", "ładny", "Ten jest ładniejszy."),
       ("brudniejszy", "brudny", "Ten jest brudniejszy."),
       ("gorszy w jakości", "zły / kiepski", "Ten jest gorszy."),
     ]),

# =====================================================================
# … thii sut — stopien najwyzszy
# =====================================================================
dict(key="THISUT", ty="collocation", cat="Gramatyka użytkowa", sub="Porównania", reg="n",
     ph="{ph} thîi sùt", th="{th}ที่สุด",
     lit="thîi sùt = najbardziej ze wszystkich",
     note="Dokładnie jak „kwàa”, tylko zamiast porównania z jednym obiektem — z całym zbiorem.",
     ex_ph="an nǎi {ph} thîi sùt khráp", ex_th="อันไหน{th}ที่สุดครับ",
     items=[
       ("największy", "duży", "Który jest największy?"),
       ("najmniejszy", "mały", "Który jest najmniejszy?"),
       ("najdłuższy", "długi", "Który jest najdłuższy?"),
       ("najkrótszy", "krótki", "Który jest najkrótszy?"),
       ("najdroższy", "drogi", "Który jest najdroższy?"),
       ("najtańszy", "tani", "Który jest najtańszy?"),
       ("najnowszy", "nowy", "Który jest najnowszy?"),
       ("najstarszy", "stary", "Który jest najstarszy?"),
       ("najszybszy", "szybki", "Który jest najszybszy?"),
       ("najwolniejszy", "wolny (powolny)", "Który jest najwolniejszy?"),
       ("najcięższy", "ciężki", "Który jest najcięższy?"),
       ("najlżejszy", "lekki", "Który jest najlżejszy?"),
       ("najczystszy", "czysty", "Który jest najczystszy?"),
       ("najgłośniejszy", "głośny", "Który jest najgłośniejszy?"),
       ("najcichszy", "cichy / spokojny", "Który jest najcichszy?"),
       ("najłatwiejszy", "łatwy", "Który jest najłatwiejszy?"),
       ("najtrudniejszy", "trudny", "Który jest najtrudniejszy?"),
       ("najciekawszy", "interesujący", "Który jest najciekawszy?"),
       ("najnudniejszy", "nudny", "Który jest najnudniejszy?"),
       ("najważniejszy", "ważny", "Który jest najważniejszy?"),
       ("najwygodniejszy", "wygodny", "Który jest najwygodniejszy?"),
       ("najbezpieczniejszy", "bezpieczny", "Który jest najbezpieczniejszy?"),
       ("najsmaczniejszy", "smaczny", "Który jest najsmaczniejszy?"),
       ("najsłodszy", "słodki", "Który jest najsłodszy?"),
       ("najostrzejszy", "ostry (pikantny)", "Który jest najostrzejszy?"),
       ("najświeższy", "świeży", "Który jest najświeższy?"),
       ("najbliższy", "bliski", "Który jest najbliższy?"),
       ("najdalszy", "daleki", "Który jest najdalszy?"),
       ("najwyższy", "wysoki", "Który jest najwyższy?"),
       ("najgłębszy", "głęboki", "Który jest najgłębszy?"),
       ("najmocniejszy", "silny, mocny", "Który jest najmocniejszy?"),
       ("najładniejszy", "ładny", "Który jest najładniejszy?"),
       ("najbardziej uroczy", "uroczy", "Który jest najbardziej uroczy?"),
       ("najzabawniejszy", "fajny / zabawny", "Który jest najzabawniejszy?"),
       ("najbardziej zajęty", "pełny / zajęty", "Który jest najbardziej zajęty?"),
     ]),

# =====================================================================
# … koen pai — „za bardzo"
# =====================================================================
dict(key="KOENPAI", ty="collocation", cat="Cechy i opinie", sub="Ocena", reg="n",
     ph="{ph} koen pai", th="{th}เกินไป",
     lit="koen pai = ponad miarę, za bardzo",
     note="Mocniejsze niż samo „pai”. Przy targowaniu brzmi jak konkretny zarzut, nie narzekanie.",
     ex_ph="{ph} koen pai sǎm-ràp phǒm khráp", ex_th="{th}เกินไปสำหรับผมครับ",
     items=[
       ("za duży", "duży", "Dla mnie za duży."),
       ("za mały", "mały", "Dla mnie za mały."),
       ("za długi", "długi", "Dla mnie za długi."),
       ("za krótki", "krótki", "Dla mnie za krótki."),
       ("za drogi", "drogi", "Dla mnie za drogi."),
       ("za gorący", "gorący", "Dla mnie za gorący."),
       ("za zimny", "zimny (o napoju)", "Dla mnie za zimny."),
       ("za ciężki", "ciężki", "Dla mnie za ciężki."),
       ("za jasny", "jasny", "Dla mnie za jasny."),
       ("za ciemny", "ciemny", "Dla mnie za ciemny."),
       ("za głośny", "głośny", "Dla mnie za głośny."),
       ("za szybki", "szybki", "Dla mnie za szybki."),
       ("za wolny", "wolny (powolny)", "Dla mnie za wolny."),
       ("za trudny", "trudny", "Dla mnie za trudny."),
       ("za ostry", "ostry (pikantny)", "Dla mnie za ostry."),
       ("za słodki", "słodki", "Dla mnie za słodki."),
       ("za słony", "słony", "Dla mnie za słony."),
       ("za kwaśny", "kwaśny", "Dla mnie za kwaśny."),
       ("za gorzki", "gorzki", "Dla mnie za gorzki."),
       ("za twardy", "twardy", "Dla mnie za twardy."),
       ("za daleki", "daleki", "Dla mnie za daleko."),
       ("za wysoki", "wysoki", "Dla mnie za wysoki."),
       ("za mocny", "silny, mocny", "Dla mnie za mocny."),
       ("za nowy", "nowy", "Ten jest dla mnie za nowy."),
       ("za stary", "stary", "Ten jest dla mnie za stary."),
     ]),

# =====================================================================
# mai khawi — „niezbyt"
# =====================================================================
dict(key="MAIKHAWI", ty="collocation", cat="Cechy i opinie", sub="Ocena", reg="n",
     ph="mâi khâwi {ph}", th="ไม่ค่อย{th}",
     lit="mâi khâwi = niezbyt, nieszczególnie",
     note="Najuprzejmiejszy sposób powiedzenia „nie” o cesze. Tajowie rzadko zaprzeczają wprost.",
     ex_ph="wan níi mâi khâwi {ph} khráp", ex_th="วันนี้ไม่ค่อย{th}ครับ",
     items=[
       ("niezbyt dobry", "dobry", "Dziś niezbyt dobrze."),
       ("niezbyt duży", "duży", "Dziś niezbyt duży."),
       ("niezbyt drogi", "drogi", "Dziś niezbyt drogo."),
       ("niezbyt gorący", "gorący", "Dziś niezbyt gorąco."),
       ("niezbyt zimny", "zimny (o napoju)", "Dziś niezbyt zimno."),
       ("niezbyt szybki", "szybki", "Dziś niezbyt szybko."),
       ("niezbyt czysty", "czysty", "Dziś niezbyt czysto."),
       ("niezbyt głośny", "głośny", "Dziś niezbyt głośno."),
       ("niezbyt trudny", "trudny", "Dziś niezbyt trudno."),
       ("niezbyt łatwy", "łatwy", "Dziś niezbyt łatwo."),
       ("niezbyt ciekawy", "interesujący", "Dziś niezbyt ciekawie."),
       ("niezbyt ważny", "ważny", "To niezbyt ważne."),
       ("niezbyt wygodny", "wygodny", "Dziś niezbyt wygodnie."),
       ("niezbyt bezpieczny", "bezpieczny", "Tu niezbyt bezpiecznie."),
       ("niezbyt smaczny", "smaczny", "Dziś niezbyt smacznie."),
       ("niezbyt słodki", "słodki", "Dziś niezbyt słodko."),
       ("niezbyt ostry", "ostry (pikantny)", "Dziś niezbyt ostro."),
       ("niezbyt świeży", "świeży", "Dziś niezbyt świeżo."),
       ("niezbyt daleki", "daleki", "To niezbyt daleko."),
       ("niezbyt zmęczony", "zmęczony", "Dziś niezbyt zmęczony."),
       ("niezbyt głodny", "głodny", "Dziś niezbyt głodny."),
       ("niezbyt szczęśliwy", "szczęśliwy", "Dziś niezbyt szczęśliwy."),
       ("niezbyt zadowolony", "zadowolony", "Dziś niezbyt zadowolony."),
       ("niezbyt zajęty", "pełny / zajęty", "Dziś niezbyt zajęto."),
       ("niezbyt mocny", "silny, mocny", "Dziś niezbyt mocno."),
     ]),

# =====================================================================
# mai … loei — „wcale nie"
# =====================================================================
dict(key="LOEINEG", ty="collocation", cat="Cechy i opinie", sub="Ocena", reg="i",
     ph="mâi {ph} loei", th="ไม่{th}เลย",
     lit="mâi … loei = ani trochę",
     note="Mocne zaprzeczenie. Wobec nieznajomych brzmi ostro — lepiej użyć „mâi khâwi”.",
     ex_ph="an níi mâi {ph} loei khráp", ex_th="อันนี้ไม่{th}เลยครับ",
     items=[
       ("wcale nie dobry", "dobry", "Ten wcale nie jest dobry."),
       ("wcale nie drogi", "drogi", "Ten wcale nie jest drogi."),
       ("wcale nie gorący", "gorący", "Ten wcale nie jest gorący."),
       ("wcale nie zimny", "zimny (o napoju)", "Ten wcale nie jest zimny."),
       ("wcale nie szybki", "szybki", "Ten wcale nie jest szybki."),
       ("wcale nie ciężki", "ciężki", "Ten wcale nie jest ciężki."),
       ("wcale nie czysty", "czysty", "Ten wcale nie jest czysty."),
       ("wcale nie trudny", "trudny", "To wcale nie jest trudne."),
       ("wcale nie łatwy", "łatwy", "To wcale nie jest łatwe."),
       ("wcale nie ciekawy", "interesujący", "To wcale nie jest ciekawe."),
       ("wcale nie nudny", "nudny", "To wcale nie jest nudne."),
       ("wcale nie wygodny", "wygodny", "Ten wcale nie jest wygodny."),
       ("wcale nie smaczny", "smaczny", "To wcale nie jest smaczne."),
       ("wcale nie ostry", "ostry (pikantny)", "To wcale nie jest ostre."),
       ("wcale nie słodki", "słodki", "To wcale nie jest słodkie."),
       ("wcale nie świeży", "świeży", "To wcale nie jest świeże."),
       ("wcale nie daleki", "daleki", "To wcale nie jest daleko."),
       ("wcale nie zmęczony", "zmęczony", "Wcale nie jestem zmęczony."),
       ("wcale nie głodny", "głodny", "Wcale nie jestem głodny."),
       ("wcale nie smutny", "smutny", "Wcale nie jestem smutny."),
       ("wcale nie zdenerwowany", "zdenerwowany", "Wcale nie jestem zdenerwowany."),
       ("wcale nie zaskoczony", "zaskoczony", "Wcale nie jestem zaskoczony."),
     ]),

# =====================================================================
# khit waa … — „mysle, ze to"
# =====================================================================
dict(key="KHITWAA", ty="sentence", cat="Cechy i opinie", sub="Opinie", reg="n",
     ph="phǒm khít wâa {ph} khráp", th="ผมคิดว่า{th}ครับ",
     lit="khít wâa = sądzę, że",
     note="Po „wâa” idzie całe zdanie podrzędne — tu skrócone do samego przymiotnika.",
     ex_ph="khít wâa {ph} rǔe khráp", ex_th="คิดว่า{th}หรือครับ",
     items=[
       ("Myślę, że to dobre.", "dobry", "Uważasz, że dobre?"),
       ("Myślę, że to za drogie.", "drogi", "Uważasz, że drogie?"),
       ("Myślę, że to tanie.", "tani", "Uważasz, że tanie?"),
       ("Myślę, że to za duże.", "duży", "Uważasz, że duże?"),
       ("Myślę, że to za małe.", "mały", "Uważasz, że małe?"),
       ("Myślę, że to szybkie.", "szybki", "Uważasz, że szybkie?"),
       ("Myślę, że to wolne.", "wolny (powolny)", "Uważasz, że wolne?"),
       ("Myślę, że to trudne.", "trudny", "Uważasz, że trudne?"),
       ("Myślę, że to łatwe.", "łatwy", "Uważasz, że łatwe?"),
       ("Myślę, że to ciekawe.", "interesujący", "Uważasz, że ciekawe?"),
       ("Myślę, że to nudne.", "nudny", "Uważasz, że nudne?"),
       ("Myślę, że to ważne.", "ważny", "Uważasz, że ważne?"),
       ("Myślę, że to wygodne.", "wygodny", "Uważasz, że wygodne?"),
       ("Myślę, że to bezpieczne.", "bezpieczny", "Uważasz, że bezpieczne?"),
       ("Myślę, że to niebezpieczne.", "niebezpieczny", "Uważasz, że niebezpieczne?"),
       ("Myślę, że to smaczne.", "smaczny", "Uważasz, że smaczne?"),
       ("Myślę, że to za ostre.", "ostry (pikantny)", "Uważasz, że ostre?"),
       ("Myślę, że to świeże.", "świeży", "Uważasz, że świeże?"),
       ("Myślę, że to daleko.", "daleki", "Uważasz, że daleko?"),
       ("Myślę, że to blisko.", "bliski", "Uważasz, że blisko?"),
       ("Myślę, że to prawdziwe.", "prawdziwy", "Uważasz, że prawdziwe?"),
       ("Myślę, że to ładne.", "ładny", "Uważasz, że ładne?"),
       ("Myślę, że to kiepskie.", "zły / kiepski", "Uważasz, że kiepskie?"),
       ("Myślę, że jest zajęte.", "pełny / zajęty", "Uważasz, że zajęte?"),
       ("Myślę, że jest wolne.", "wolny (dostępny)", "Uważasz, że wolne?"),
     ]),

# =====================================================================
# duu … na — „wyglada na"
# =====================================================================
dict(key="DUUNA", ty="sentence", cat="Cechy i opinie", sub="Ocena", reg="i",
     ph="duu {ph} ná khráp", th="ดู{th}นะครับ",
     lit="duu … = wygląda na, sprawia wrażenie",
     note="„duu” przed przymiotnikiem osłabia sąd do wrażenia — bardzo przydatne, gdy nie chcemy przesądzać.",
     ex_ph="duu {ph} mâak loei khráp", ex_th="ดู{th}มากเลยครับ",
     items=[
       ("Wygląda dobrze.", "dobry", "Wygląda naprawdę dobrze."),
       ("Wygląda drogo.", "drogi", "Wygląda naprawdę drogo."),
       ("Wygląda tanio.", "tani", "Wygląda naprawdę tanio."),
       ("Wygląda na nowe.", "nowy", "Wygląda naprawdę nowo."),
       ("Wygląda na stare.", "stary", "Wygląda naprawdę staro."),
       ("Wygląda na czyste.", "czysty", "Wygląda naprawdę czysto."),
       ("Wygląda na brudne.", "brudny", "Wygląda naprawdę brudno."),
       ("Wygląda na ciężkie.", "ciężki", "Wygląda naprawdę ciężko."),
       ("Wygląda na wygodne.", "wygodny", "Wygląda naprawdę wygodnie."),
       ("Wygląda na niebezpieczne.", "niebezpieczny", "Wygląda naprawdę niebezpiecznie."),
       ("Wygląda na trudne.", "trudny", "Wygląda naprawdę trudno."),
       ("Wygląda na łatwe.", "łatwy", "Wygląda naprawdę łatwo."),
       ("Wygląda ciekawie.", "interesujący", "Wygląda naprawdę ciekawie."),
       ("Wygląda smacznie.", "smaczny", "Wygląda naprawdę smacznie."),
       ("Wygląda świeżo.", "świeży", "Wygląda naprawdę świeżo."),
       ("Wygląda na dojrzałe.", "dojrzały", "Wygląda naprawdę dojrzale."),
       ("Wygląda ładnie.", "ładny", "Wygląda naprawdę ładnie."),
       ("Wyglądasz na zmęczonego.", "zmęczony", "Wyglądasz bardzo na zmęczonego."),
       ("Wyglądasz na szczęśliwego.", "szczęśliwy", "Wyglądasz bardzo na szczęśliwego."),
       ("Wyglądasz na smutnego.", "smutny", "Wyglądasz bardzo na smutnego."),
       ("Wyglądasz na zestresowanego.", "zestresowany", "Wyglądasz bardzo na zestresowanego."),
       ("Wyglądasz na chorego.", "chory", "Wyglądasz bardzo na chorego."),
       ("Wyglądasz na zadowolonego.", "zadowolony", "Wyglądasz bardzo na zadowolonego."),
       ("Wyglądasz na znudzonego.", "znudzony", "Wyglądasz bardzo na znudzonego."),
     ]),

# =====================================================================
# … jang loei — okrzyk podziwu lub zdziwienia
# =====================================================================
dict(key="JANG", ty="phrase", cat="Small talk", sub="Reakcje", reg="p",
     ph="{ph} jang loei khráp", th="{th}จังเลยครับ",
     lit="… jang loei = ależ to…!",
     note="Potoczny okrzyk. W rozmowie służbowej lepiej użyć „mâak khráp”.",
     ex_ph="{ph} jang loei ná khráp", ex_th="{th}จังเลยนะครับ",
     items=[
       ("Ależ duże!", "duży", "Ależ to duże!"),
       ("Ależ małe!", "mały", "Ależ to małe!"),
       ("Ależ drogie!", "drogi", "Ależ to drogie!"),
       ("Ależ tanie!", "tani", "Ależ to tanie!"),
       ("Ależ gorąco!", "gorący", "Ależ tu gorąco!"),
       ("Ależ szybko!", "szybki", "Ależ to szybko!"),
       ("Ależ ładne!", "ładny", "Ależ to ładne!"),
       ("Ależ smaczne!", "smaczny", "Ależ to smaczne!"),
       ("Ależ słodkie!", "słodki", "Ależ to słodkie!"),
       ("Ależ ostre!", "ostry (pikantny)", "Ależ to ostre!"),
       ("Ależ głośno!", "głośny", "Ależ tu głośno!"),
       ("Ależ daleko!", "daleki", "Ależ to daleko!"),
       ("Ależ ciekawe!", "interesujący", "Ależ to ciekawe!"),
       ("Ależ zabawne!", "fajny / zabawny", "Ależ to zabawne!"),
       ("Ależ urocze!", "uroczy", "Ależ to urocze!"),
       ("Ależ zmęczony jestem!", "zmęczony", "Ależ jestem zmęczony!"),
       ("Ależ głodny jestem!", "głodny", "Ależ jestem głodny!"),
       ("Ależ spragniony jestem!", "spragniony", "Ależ chce mi się pić!"),
       ("Ależ szczęśliwy jestem!", "szczęśliwy", "Ależ jestem szczęśliwy!"),
       ("Ależ kiepsko!", "zły / kiepski", "Ależ to kiepskie!"),
     ]),

# =====================================================================
# naa ja — „chyba jest"
# =====================================================================
dict(key="NAAJA", ty="sentence", cat="Cechy i opinie", sub="Opinie", reg="n",
     ph="nâa jà {ph} khráp", th="น่าจะ{th}ครับ",
     lit="nâa jà = pewnie, zapewne",
     note="Ostrożny domysł. Bardzo przydatne, gdy nie chcemy się mylić z przekonaniem.",
     ex_ph="nâa jà {ph} ná khráp", ex_th="น่าจะ{th}นะครับ",
     items=[
       ("Chyba jest dobre.", "dobry", "Chyba dobre, prawda?"),
       ("Chyba jest drogie.", "drogi", "Chyba drogie, prawda?"),
       ("Chyba jest tanie.", "tani", "Chyba tanie, prawda?"),
       ("Chyba jest za duże.", "duży", "Chyba duże, prawda?"),
       ("Chyba jest za małe.", "mały", "Chyba małe, prawda?"),
       ("Chyba jest nowe.", "nowy", "Chyba nowe, prawda?"),
       ("Chyba jest stare.", "stary", "Chyba stare, prawda?"),
       ("Chyba jest zajęte.", "pełny / zajęty", "Chyba zajęte, prawda?"),
       ("Chyba jest wolne.", "wolny (dostępny)", "Chyba wolne, prawda?"),
       ("Chyba jest daleko.", "daleki", "Chyba daleko, prawda?"),
       ("Chyba jest blisko.", "bliski", "Chyba blisko, prawda?"),
       ("Chyba jest trudne.", "trudny", "Chyba trudne, prawda?"),
       ("Chyba jest łatwe.", "łatwy", "Chyba łatwe, prawda?"),
       ("Chyba jest bezpieczne.", "bezpieczny", "Chyba bezpieczne, prawda?"),
       ("Chyba jest niebezpieczne.", "niebezpieczny", "Chyba niebezpieczne, prawda?"),
       ("Chyba jest smaczne.", "smaczny", "Chyba smaczne, prawda?"),
       ("Chyba jest świeże.", "świeży", "Chyba świeże, prawda?"),
       ("Chyba jest ostre.", "ostry (pikantny)", "Chyba ostre, prawda?"),
       ("Chyba jest ważne.", "ważny", "Chyba ważne, prawda?"),
       ("Chyba jest zepsute i kiepskie.", "zły / kiepski", "Chyba kiepskie, prawda?"),
     ]),

# =====================================================================
# … khuen — „coraz bardziej"
# =====================================================================
dict(key="KHUEN", ty="collocation", cat="Gramatyka użytkowa", sub="Zmiana", reg="n",
     ph="{ph} khûen", th="{th}ขึ้น",
     lit="… khûen = wzrost cechy: coraz bardziej",
     note="„khûen” to dosłownie „w górę”. Przeciwieństwo to „long” — w dół.",
     ex_ph="chûang níi {ph} khûen khráp", ex_th="ช่วงนี้{th}ขึ้นครับ",
     items=[
       ("robi się coraz lepiej", "dobry", "Ostatnio jest coraz lepiej."),
       ("robi się coraz gorzej", "zły / kiepski", "Ostatnio jest coraz gorzej."),
       ("robi się coraz drożej", "drogi", "Ostatnio jest coraz drożej."),
       ("robi się coraz taniej", "tani", "Ostatnio jest coraz taniej."),
       ("robi się coraz cieplej", "gorący", "Ostatnio jest coraz cieplej."),
       ("robi się coraz głośniej", "głośny", "Ostatnio jest coraz głośniej."),
       ("robi się coraz szybciej", "szybki", "Ostatnio jest coraz szybciej."),
       ("robi się coraz trudniej", "trudny", "Ostatnio jest coraz trudniej."),
       ("robi się coraz łatwiej", "łatwy", "Ostatnio jest coraz łatwiej."),
       ("robi się coraz ciekawiej", "interesujący", "Ostatnio jest coraz ciekawiej."),
       ("robi się coraz bardziej zatłoczone", "pełny / zajęty", "Ostatnio jest coraz bardziej zatłoczono."),
       ("jestem coraz bardziej zmęczony", "zmęczony", "Ostatnio jestem coraz bardziej zmęczony."),
       ("jestem coraz bardziej głodny", "głodny", "Ostatnio jestem coraz bardziej głodny."),
       ("jestem coraz szczęśliwszy", "szczęśliwy", "Ostatnio jestem coraz szczęśliwszy."),
       ("jestem coraz bardziej zestresowany", "zestresowany", "Ostatnio jestem coraz bardziej zestresowany."),
       ("robi się coraz ładniej", "ładny", "Ostatnio jest coraz ładniej."),
     ]),

# =====================================================================
# ruu-suek — „czuje sie"
# =====================================================================
dict(key="RUUSUEK", ty="sentence", cat="Cechy i opinie", sub="Samopoczucie", reg="n",
     ph="phǒm rúu-sùek {ph} khráp", th="ผมรู้สึก{th}ครับ",
     lit="rúu-sùek = czuć, odczuwać",
     note="Dotyczy wyłącznie stanów wewnętrznych — nie mówimy tak o cenie czy rozmiarze.",
     ex_ph="rúu-sùek {ph} rǔe khráp", ex_th="รู้สึก{th}หรือครับ",
     items=[
       ("Czuję się zmęczony.", "zmęczony", "Czujesz się zmęczony?"),
       ("Czuję się szczęśliwy.", "szczęśliwy", "Czujesz się szczęśliwy?"),
       ("Czuję się smutny.", "smutny", "Czujesz się smutny?"),
       ("Czuję się samotny.", "samotny", "Czujesz się samotny?"),
       ("Czuję się zdenerwowany.", "zdenerwowany", "Czujesz się zdenerwowany?"),
       ("Czuję się zestresowany.", "zestresowany", "Czujesz się zestresowany?"),
       ("Czuję się znudzony.", "znudzony", "Czujesz się znudzony?"),
       ("Czuję się zadowolony.", "zadowolony", "Czujesz się zadowolony?"),
       ("Czuję się zaskoczony.", "zaskoczony", "Czujesz się zaskoczony?"),
       ("Czuję się rozczarowany.", "rozczarowany", "Czujesz się rozczarowany?"),
       ("Czuję się przestraszony.", "przestraszony", "Czujesz się przestraszony?"),
       ("Czuję się nieśmiały.", "zawstydzony, nieśmiały", "Czujesz się skrępowany?"),
       ("Czuję się dumny.", "dumny", "Czujesz się dumny?"),
       ("Czuję się spokojny.", "spokojny, opanowany", "Czujesz się spokojny?"),
       ("Czuję się chory.", "chory", "Czujesz się chory?"),
       ("Czuję się głodny.", "głodny", "Czujesz się głodny?"),
       ("Czuję się spragniony.", "spragniony", "Chce ci się pić?"),
       ("Czuję się najedzony.", "najedzony", "Jesteś najedzony?"),
       ("Czuję się bezpiecznie.", "bezpieczny", "Czujesz się bezpiecznie?"),
       ("Czuję się swobodnie.", "wolny (dostępny)", "Czujesz się swobodnie?"),
     ]),

# =====================================================================
# an nai … kwaa — pytanie porownawcze
# =====================================================================
dict(key="ANNAI", ty="question", cat="Pytania", sub="Porównania", reg="n",
     ph="an nǎi {ph} kwàa khráp", th="อันไหน{th}กว่าครับ",
     lit="an nǎi = który z nich",
     note="„an” to uniwersalne słowo miarowe dla przedmiotów, gdy nie znamy właściwego.",
     ex_ph="an níi {ph} kwàa khráp", ex_th="อันนี้{th}กว่าครับ",
     items=[
       ("Który jest większy?", "duży", "Ten jest większy."),
       ("Który jest mniejszy?", "mały", "Ten jest mniejszy."),
       ("Który jest droższy?", "drogi", "Ten jest droższy."),
       ("Który jest tańszy?", "tani", "Ten jest tańszy."),
       ("Który jest nowszy?", "nowy", "Ten jest nowszy."),
       ("Który jest szybszy?", "szybki", "Ten jest szybszy."),
       ("Który jest lepszy?", "dobry", "Ten jest lepszy."),
       ("Który jest cięższy?", "ciężki", "Ten jest cięższy."),
       ("Który jest lżejszy?", "lekki", "Ten jest lżejszy."),
       ("Który jest dłuższy?", "długi", "Ten jest dłuższy."),
       ("Który jest wygodniejszy?", "wygodny", "Ten jest wygodniejszy."),
       ("Który jest smaczniejszy?", "smaczny", "Ten jest smaczniejszy."),
       ("Który jest ostrzejszy?", "ostry (pikantny)", "Ten jest ostrzejszy."),
       ("Który jest świeższy?", "świeży", "Ten jest świeższy."),
       ("Który jest bliższy?", "bliski", "Ten jest bliższy."),
       ("Który jest bezpieczniejszy?", "bezpieczny", "Ten jest bezpieczniejszy."),
       ("Który jest łatwiejszy?", "łatwy", "Ten jest łatwiejszy."),
       ("Który jest ładniejszy?", "ładny", "Ten jest ładniejszy."),
     ]),

# =====================================================================
# … kwaa nii dai mai — prosba o zmiane stopnia
# =====================================================================
dict(key="KWAANII", ty="question", cat="Pytania", sub="Prośby", reg="n",
     ph="{ph} kwàa níi dâai mǎi khráp", th="{th}กว่านี้ได้ไหมครับ",
     lit="… kwàa níi = bardziej niż to",
     note="Codzienna prośba w sklepie, hotelu i taksówce: „a może trochę bardziej…?”.",
     ex_ph="khǎw {ph} kwàa níi nòi khráp", ex_th="ขอ{th}กว่านี้หน่อยครับ",
     items=[
       ("Czy może być tańsze?", "tani", "Poproszę coś tańszego."),
       ("Czy może być większe?", "duży", "Poproszę coś większego."),
       ("Czy może być mniejsze?", "mały", "Poproszę coś mniejszego."),
       ("Czy może być nowsze?", "nowy", "Poproszę coś nowszego."),
       ("Czy może być szybciej?", "szybki", "Poproszę trochę szybciej."),
       ("Czy może być wolniej?", "wolny (powolny)", "Poproszę trochę wolniej."),
       ("Czy może być ciszej?", "cichy / spokojny", "Poproszę trochę ciszej."),
       ("Czy może być czyściej?", "czysty", "Poproszę coś czystszego."),
       ("Czy może być cieplejsze?", "gorący", "Poproszę coś cieplejszego."),
       ("Czy może być zimniejsze?", "zimny (o napoju)", "Poproszę coś zimniejszego."),
       ("Czy może być lżejsze?", "lekki", "Poproszę coś lżejszego."),
       ("Czy może być krótsze?", "krótki", "Poproszę coś krótszego."),
       ("Czy może być dłuższe?", "długi", "Poproszę coś dłuższego."),
       ("Czy może być jaśniejsze?", "jasny", "Poproszę coś jaśniejszego."),
       ("Czy może być ciemniejsze?", "ciemny", "Poproszę coś ciemniejszego."),
       ("Czy może być ostrzejsze?", "ostry (pikantny)", "Poproszę coś ostrzejszego."),
       ("Czy może być słodsze?", "słodki", "Poproszę coś słodszego."),
       ("Czy może być świeższe?", "świeży", "Poproszę coś świeższego."),
       ("Czy może być wygodniejsze?", "wygodny", "Poproszę coś wygodniejszego."),
       ("Czy może być bliżej?", "bliski", "Poproszę coś bliżej."),
     ]),

# =====================================================================
# … maak loei — mocne wzmocnienie
# =====================================================================
dict(key="MAAKLOEI", ty="collocation", cat="Cechy i opinie", sub="Ocena", reg="i",
     ph="{ph} mâak loei", th="{th}มากเลย",
     lit="mâak loei = naprawdę bardzo",
     note="„loei” po „mâak” dodaje emocję. Sam „mâak” jest neutralny.",
     ex_ph="an níi {ph} mâak loei khráp", ex_th="อันนี้{th}มากเลยครับ",
     items=[
       ("naprawdę bardzo dobry", "dobry", "Ten jest naprawdę bardzo dobry."),
       ("naprawdę bardzo drogi", "drogi", "Ten jest naprawdę bardzo drogi."),
       ("naprawdę bardzo tani", "tani", "Ten jest naprawdę bardzo tani."),
       ("naprawdę bardzo gorący", "gorący", "Ten jest naprawdę bardzo gorący."),
       ("naprawdę bardzo zimny", "zimny (o napoju)", "Ten jest naprawdę bardzo zimny."),
       ("naprawdę bardzo szybki", "szybki", "Ten jest naprawdę bardzo szybki."),
       ("naprawdę bardzo czysty", "czysty", "Ten jest naprawdę bardzo czysty."),
       ("naprawdę bardzo brudny", "brudny", "Ten jest naprawdę bardzo brudny."),
       ("naprawdę bardzo głośny", "głośny", "Ten jest naprawdę bardzo głośny."),
       ("naprawdę bardzo trudny", "trudny", "Ten jest naprawdę bardzo trudny."),
       ("naprawdę bardzo smaczny", "smaczny", "Ten jest naprawdę bardzo smaczny."),
       ("naprawdę bardzo ostry", "ostry (pikantny)", "Ten jest naprawdę bardzo ostry."),
       ("naprawdę bardzo świeży", "świeży", "Ten jest naprawdę bardzo świeży."),
       ("naprawdę bardzo daleki", "daleki", "To jest naprawdę bardzo daleko."),
       ("naprawdę bardzo ładny", "ładny", "Ten jest naprawdę bardzo ładny."),
       ("naprawdę bardzo ciekawy", "interesujący", "Ten jest naprawdę bardzo ciekawy."),
       ("naprawdę bardzo wygodny", "wygodny", "Ten jest naprawdę bardzo wygodny."),
       ("naprawdę bardzo mocny", "silny, mocny", "Ten jest naprawdę bardzo mocny."),
     ]),

# =====================================================================
# … nit noi — „troche"
# =====================================================================
dict(key="NITNOI2", ty="collocation", cat="Cechy i opinie", sub="Ocena", reg="n",
     ph="{ph} nít nòi", th="{th}นิดหน่อย",
     lit="nít nòi = odrobinę, troszkę",
     note="Uprzejmy sposób zgłoszenia zastrzeżenia: zamiast „za słone” — „trochę słone”.",
     ex_ph="wan níi {ph} nít nòi khráp", ex_th="วันนี้{th}นิดหน่อยครับ",
     items=[
       ("trochę gorący", "gorący", "Dziś jest trochę gorąco."),
       ("trochę zimny", "zimny (o napoju)", "Dziś jest trochę zimno."),
       ("trochę drogi", "drogi", "Dziś jest trochę drogo."),
       ("trochę głośny", "głośny", "Dziś jest trochę głośno."),
       ("trochę brudny", "brudny", "Dziś jest trochę brudno."),
       ("trochę ciężki", "ciężki", "To jest trochę ciężkie."),
       ("trochę trudny", "trudny", "To jest trochę trudne."),
       ("trochę ostry", "ostry (pikantny)", "To jest trochę ostre."),
       ("trochę słony", "słony", "To jest trochę słone."),
       ("trochę słodki", "słodki", "To jest trochę słodkie."),
       ("trochę kwaśny", "kwaśny", "To jest trochę kwaśne."),
       ("trochę twardy", "twardy", "To jest trochę twarde."),
       ("trochę daleki", "daleki", "To jest trochę daleko."),
       ("trochę zmęczony", "zmęczony", "Jestem dziś trochę zmęczony."),
       ("trochę głodny", "głodny", "Jestem dziś trochę głodny."),
       ("trochę smutny", "smutny", "Jestem dziś trochę smutny."),
       ("trochę zdenerwowany", "zdenerwowany", "Jestem dziś trochę zdenerwowany."),
       ("trochę chory", "chory", "Jestem dziś trochę chory."),
     ]),
]
