# -*- coding: utf-8 -*-
"""Leksyka etapu 4 (B1) — naturalne reakcje rozmowcy.

Zakres: krotkie wtracenia, potwierdzenia, wyrazy zaskoczenia, wspolodczuwania,
watpliwosci, podtrzymywanie rozmowy, reakcje na dobra i zla wiadomosc.

To material, ktorego brakuje najbardziej uczacym sie z podrecznika: bez tych
kilkudziesieciu drobiazgow rozmowa brzmi jak przesluchanie, a nie jak rozmowa.

Rejestry sa tu istotne. Czesc tych wyrazen jest wylacznie potoczna i zostala
oznaczona ostrzezeniem w polu notatki.

Format jak w lex_b1_core_a.py.
"""

CORE_REACT = [

# =====================================================================
# POTWIERDZANIE, ZE SLUCHAM
# =====================================================================
("Tak, tak.", "khráp khráp", "ครับๆ", "Small talk", "Reakcje", "phrase", 5, "n",
 "Powtórzona partykuła to sygnał „słucham dalej”, nie zniecierpliwienie.", "",
 ("Więc jak mówiłem…", "kâw thîi bàwk pai", "ก็ที่บอกไป")),
("Mhm, słucham.", "khráp fang yùu", "ครับ ฟังอยู่", "Small talk", "Reakcje", "phrase", 5, "n", "", "",
 ("To było tak…", "man pen yàang níi", "มันเป็นอย่างนี้")),
("Aha.", "âw", "อ๋อ", "Small talk", "Reakcje", "phrase", 5, "i",
 "„âw” to dźwięk zrozumienia — moment, w którym coś do ciebie dociera.", "",
 ("Teraz jasne?", "khâo-jai láew mǎi khráp", "เข้าใจแล้วไหมครับ")),
("Aha, o to chodzi.", "âw yàang níi níi eeng", "อ๋อ อย่างนี้นี่เอง",
 "Small talk", "Reakcje", "phrase", 4, "i", "„… níi eeng” = a więc o to chodziło.", "",
 ("Właśnie.", "châi loei khráp", "ใช่เลยครับ")),
("Rozumiem, rozumiem.", "khâo-jai láew khráp khâo-jai", "เข้าใจแล้วครับ เข้าใจ",
 "Small talk", "Reakcje", "phrase", 4, "n", "", "",
 ("To dobrze.", "dii khráp", "ดีครับ")),
("Jasne.", "âw khráp", "อ๋อครับ", "Small talk", "Reakcje", "phrase", 4, "i", "", "",
 ("Idziemy dalej.", "tàw loei khráp", "ต่อเลยครับ")),
("No dobrze.", "kâw dâai khráp", "ก็ได้ครับ", "Small talk", "Reakcje", "phrase", 4, "n",
 "„kâw dâai” to zgoda z lekkim ustępstwem, nie entuzjazm.", "",
 ("Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ")),
("I co dalej?", "láew ngai tàw khráp", "แล้วไงต่อครับ", "Small talk", "Reakcje", "question", 5, "i",
 "Najczęstsze pytanie podtrzymujące opowieść. W rozmowie z przełożonym lepiej: „láew pen yang-ngai tàw khráp”.", "",
 ("Zaraz opowiem.", "dǐao lâo tàw khráp", "เดี๋ยวเล่าต่อครับ")),
("A potem?", "láew lǎng jàak nán khráp", "แล้วหลังจากนั้นครับ",
 "Small talk", "Reakcje", "question", 4, "n", "", "",
 ("Potem wyszedłem.", "lǎng jàak nán phǒm kâw àwk maa khráp", "หลังจากนั้นผมก็ออกมาครับ")),
("Mów dalej.", "wâa tàw loei khráp", "ว่าต่อเลยครับ", "Small talk", "Reakcje", "phrase", 4, "i", "", "",
 ("Dobrze.", "khráp", "ครับ")),
("Słucham cię.", "fang yùu khráp", "ฟังอยู่ครับ", "Small talk", "Reakcje", "phrase", 4, "n", "", "",
 ("Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ")),
("I jak?", "pen yang-ngai bâang khráp", "เป็นยังไงบ้างครับ",
 "Small talk", "Reakcje", "question", 5, "n",
 "Uniwersalne pytanie: o samopoczucie, o pracę, o wczorajszy wieczór.", "",
 ("Nieźle.", "kâw dii khráp", "ก็ดีครับ")),
("Co ty powiesz.", "jing rǒe khráp", "จริงหรือครับ", "Small talk", "Reakcje", "phrase", 5, "n", "", "",
 ("Naprawdę.", "jing jing khráp", "จริงๆ ครับ")),

# =====================================================================
# ZASKOCZENIE
# =====================================================================
("Serio, naprawdę?", "jing jing rǒe khráp", "จริงๆ หรือครับ",
 "Small talk", "Reakcje", "question", 5, "n", "", "",
 ("Przysięgam.", "jing khráp", "จริงครับ")),
("Coś takiego!", "âo jing dûai", "อ้าว จริงด้วย", "Small talk", "Reakcje", "phrase", 4, "i",
 "„âo” to wykrzyknik zaskoczenia zmieszanego z konsternacją.", "",
 ("No właśnie mówię.", "kâw bàwk láew ngai", "ก็บอกแล้วไง")),
("Nie do wiary.", "mâi nâa chûea loei", "ไม่น่าเชื่อเลย",
 "Small talk", "Reakcje", "phrase", 4, "n", "„mâi nâa chûea” = aż trudno uwierzyć.", "",
 ("A jednak.", "tàae kâw jing khráp", "แต่ก็จริงครับ")),
("Żartujesz.", "phûut lên rǒe plào khráp", "พูดเล่นหรือเปล่าครับ",
 "Small talk", "Reakcje", "question", 4, "i", "„phûut lên” = żartować.", "",
 ("Wcale nie.", "mâi dâi phûut lên khráp", "ไม่ได้พูดเล่นครับ")),
("O rany.", "óo hǒo", "โอ้โห", "Small talk", "Reakcje", "phrase", 5, "i",
 "Wykrzyknik podziwu lub zdumienia. Naturalny wszędzie poza pismem urzędowym.", "",
 ("Prawda?", "châi mǎi lâ khráp", "ใช่ไหมล่ะครับ")),
("Aż tak?", "khà-nàat nán loei rǒe khráp", "ขนาดนั้นเลยหรือครับ",
 "Small talk", "Reakcje", "question", 4, "n", "", "",
 ("Tak, aż tak.", "khà-nàat nán loei khráp", "ขนาดนั้นเลยครับ")),
("Nigdy bym nie pomyślał.", "mâi khoei khít maa kàwn loei khráp", "ไม่เคยคิดมาก่อนเลยครับ",
 "Small talk", "Reakcje", "sentence", 3, "n", "", "",
 ("Ja też nie.", "phǒm kâw mǔean kan khráp", "ผมก็เหมือนกันครับ")),
("To mnie zaskoczyło.", "tòk jai loei khráp", "ตกใจเลยครับ",
 "Small talk", "Reakcje", "sentence", 4, "n", "„tòk jai” = przestraszyć się, zaskoczyć.", "spaść na serce",
 ("Mnie też.", "phǒm kâw tòk jai khráp", "ผมก็ตกใจครับ")),
("Ale numer.", "yàang ngíi kâw mii dûai", "อย่างงี้ก็มีด้วย",
 "Small talk", "Reakcje", "phrase", 3, "p",
 "SLANG: bardzo swobodne. NIE mów tego do klienta, przełożonego ani osoby starszej.", "",
 ("No właśnie.", "nân ná sì", "นั่นน่ะสิ")),
("Kto by pomyślał.", "khrai jà pai khít khráp", "ใครจะไปคิดครับ",
 "Small talk", "Reakcje", "phrase", 3, "n", "", "",
 ("Nikt.", "mâi mii khrai khráp", "ไม่มีใครครับ")),
("Naprawdę tak było?", "man pen yàang nán jing rǒe khráp", "มันเป็นอย่างนั้นจริงหรือครับ",
 "Small talk", "Reakcje", "question", 3, "n", "", "",
 ("Tak było.", "pen yàang nán khráp", "เป็นอย่างนั้นครับ")),
("Ojej.", "óoi", "โอ๊ย", "Small talk", "Reakcje", "phrase", 4, "p",
 "Wyraża ból lub zniecierpliwienie. Krzyknięty przy klientach zrobi złe wrażenie.", "",
 ("Co się stało?", "pen à-rai khráp", "เป็นอะไรครับ")),

# =====================================================================
# WSPOLODCZUWANIE
# =====================================================================
("Bardzo mi przykro.", "sǐa jai dûai jing jing khráp", "เสียใจด้วยจริงๆ ครับ",
 "Podstawy i grzeczność", "Reakcje", "phrase", 4, "f",
 "„sǐa jai dûai” to właściwa reakcja na stratę lub złą wiadomość. Nie mów tak, gdy ktoś tylko spóźnił się na autobus.", "",
 ("Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ")),
("Współczuję ci.", "khâo-jai khwaam rúu-sùek khráp", "เข้าใจความรู้สึกครับ",
 "Podstawy i grzeczność", "Reakcje", "phrase", 3, "n", "", "rozumiem to uczucie",
 ("Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ")),
("To musiało być trudne.", "khong lam-bàak mâak khráp", "คงลำบากมากครับ",
 "Podstawy i grzeczność", "Reakcje", "sentence", 3, "n", "", "",
 ("Trochę tak.", "kâw nít nùeng khráp", "ก็นิดหนึ่งครับ")),
("Trzymaj się.", "sûu sûu ná khráp", "สู้ๆ นะครับ", "Small talk", "Reakcje", "phrase", 5, "i",
 "Dosłownie „walcz”. To najczęstsze tajskie słowo wsparcia — dużo częstsze niż polskie „trzymaj się”.", "walcz, walcz",
 ("Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ")),
("Głowa do góry.", "mâi tâwng thâw ná khráp", "ไม่ต้องท้อนะครับ",
 "Small talk", "Reakcje", "phrase", 3, "n", "„thâw” = zniechęcić się, opaść z sił.", "",
 ("Postaram się.", "jà phá-yaa-yaam khráp", "จะพยายามครับ")),
("Wszystko będzie dobrze.", "dǐao kâw dii khûen eeng khráp", "เดี๋ยวก็ดีขึ้นเองครับ",
 "Small talk", "Reakcje", "sentence", 4, "n", "", "",
 ("Mam nadzieję.", "wǎng wâa yàang nán khráp", "หวังว่าอย่างนั้นครับ")),
("Rozumiem, jak się czujesz.", "phǒm khâo-jai wâa khun rúu-sùek yang-ngai khráp",
 "ผมเข้าใจว่าคุณรู้สึกยังไงครับ", "Podstawy i grzeczność", "Reakcje", "sentence", 3, "n", "", "",
 ("Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ")),
("Odpocznij trochę.", "phák phàwn bâang ná khráp", "พักผ่อนบ้างนะครับ",
 "Zdrowie", "Reakcje", "phrase", 4, "n", "", "",
 ("Dobrze.", "khráp", "ครับ")),
("Zdrowiej szybko.", "hǎai wai wai ná khráp", "หายไวๆ นะครับ",
 "Zdrowie", "Reakcje", "phrase", 4, "n", "„hǎai” = wyzdrowieć. Standardowe życzenie choremu.", "",
 ("Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ")),
("Nie przejmuj się tym.", "yàa pai sǒn jai loei khráp", "อย่าไปสนใจเลยครับ",
 "Small talk", "Reakcje", "sentence", 4, "i", "„sǒn jai” = zwracać uwagę, przejmować się.", "",
 ("Postaram się.", "phá-yaa-yaam khráp", "พยายามครับ")),
("To nie twoja wina.", "mâi châi khwaam phìt khǎwng khun khráp", "ไม่ใช่ความผิดของคุณครับ",
 "Podstawy i grzeczność", "Reakcje", "sentence", 3, "n", "", "",
 ("Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ")),
("Każdemu się zdarza.", "khrai kâw pen khráp", "ใครก็เป็นครับ",
 "Small talk", "Reakcje", "phrase", 3, "n", "", "",
 ("To prawda.", "kâw jing khráp", "ก็จริงครับ")),
("Jaka szkoda.", "nâa sǐa daai khráp", "น่าเสียดายครับ",
 "Small talk", "Reakcje", "phrase", 4, "n", "", "",
 ("No niestety.", "kâw nân lâ khráp", "ก็นั่นล่ะครับ")),
("Biedny.", "sǒng-sǎan jang", "สงสารจัง", "Small talk", "Reakcje", "phrase", 3, "i",
 "„sǒng-sǎan” = litować się, współczuć. Wobec dorosłego może zabrzmieć protekcjonalnie.", "",
 ("No właśnie.", "nân ná sì", "นั่นน่ะสิ")),

# =====================================================================
# DOBRA WIADOMOSC
# =====================================================================
("Super!", "sùt yâwt", "สุดยอด", "Small talk", "Reakcje", "phrase", 5, "i",
 "„sùt yâwt” = szczyt, najlepsze. Bardzo częste w mowie potocznej.", "",
 ("Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ")),
("Ale się cieszę!", "dii jai dûai jang loei khráp", "ดีใจด้วยจังเลยครับ",
 "Small talk", "Reakcje", "phrase", 4, "n", "„dii jai dûai” = cieszyć się razem z kimś.", "",
 ("Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ")),
("To wspaniała wiadomość.", "pen khàao dii mâak loei khráp", "เป็นข่าวดีมากเลยครับ",
 "Small talk", "Reakcje", "sentence", 3, "f", "„khàao dii” = dobra wiadomość.", "",
 ("Też się cieszę.", "phǒm kâw dii jai khráp", "ผมก็ดีใจครับ")),
("Brawo!", "kèng mâak khráp", "เก่งมากครับ", "Small talk", "Reakcje", "phrase", 4, "n",
 "„kèng” = zdolny, dobry w czymś. Chwalenie tym słowem jest w Tajlandii bardzo naturalne.", "",
 ("Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ")),
("Zasłużyłeś na to.", "khun sǒm khuan láew khráp", "คุณสมควรแล้วครับ",
 "Small talk", "Reakcje", "sentence", 2, "f", "", "",
 ("Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ")),
("Ulżyło mi.", "khôi yang chûa khráp", "ค่อยยังชั่วครับ",
 "Small talk", "Reakcje", "phrase", 3, "n",
 "Idiom bez dosłownego odpowiednika: „nareszcie lepiej”, „kamień z serca”.", "",
 ("Mnie też.", "phǒm kâw mǔean kan khráp", "ผมก็เหมือนกันครับ")),
("Całe szczęście.", "chôok dii thîi", "โชคดีที่", "Small talk", "Reakcje", "phrase", 4, "n",
 "Zwykle kontynuowane: „chôok dii thîi …” = całe szczęście, że…", "",
 ("Prawda.", "jing khráp", "จริงครับ")),
("Cieszę się razem z tobą.", "dii jai dûai khráp", "ดีใจด้วยครับ",
 "Small talk", "Reakcje", "phrase", 4, "n", "", "",
 ("Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ")),
("Nareszcie.", "nai thîi sùt kâw dâai", "ในที่สุดก็ได้",
 "Small talk", "Reakcje", "phrase", 3, "n", "„nai thîi sùt” = w końcu, ostatecznie.", "",
 ("Długo to trwało.", "naan mǔean kan khráp", "นานเหมือนกันครับ")),
("Dobra robota.", "tham dâai dii khráp", "ทำได้ดีครับ",
 "Praca i nauka", "Reakcje", "phrase", 4, "n", "", "",
 ("Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ")),

# =====================================================================
# WATPLIWOSC I OSTROZNOSC
# =====================================================================
("Hmm, nie wiem.", "ûem mâi nâe jai khráp", "เอ่อ ไม่แน่ใจครับ",
 "Small talk", "Reakcje", "phrase", 4, "n", "", "",
 ("Sprawdźmy.", "chék duu khráp", "เช็คดูครับ")),
("Chyba nie.", "khong mâi khráp", "คงไม่ครับ", "Small talk", "Reakcje", "phrase", 4, "n", "", "",
 ("Szkoda.", "âo sǐa daai khráp", "อ้าว เสียดายครับ")),
("Może i tak.", "kâw àat jà châi khráp", "ก็อาจจะใช่ครับ",
 "Small talk", "Reakcje", "phrase", 4, "n", "", "",
 ("No właśnie.", "nân sì khráp", "นั่นสิครับ")),
("Trudno powiedzieć.", "bàwk yâak khráp", "บอกยากครับ",
 "Small talk", "Reakcje", "phrase", 4, "n", "", "",
 ("Racja.", "kâw jing khráp", "ก็จริงครับ")),
("Na pewno?", "nâe jai ná khráp", "แน่ใจนะครับ", "Small talk", "Reakcje", "question", 5, "n", "", "",
 ("Na sto procent.", "nâe nawn khráp", "แน่นอนครับ")),
("Coś mi tu nie gra.", "man plàek plàek yang-ngai mâi rúu khráp", "มันแปลกๆ ยังไงไม่รู้ครับ",
 "Small talk", "Reakcje", "sentence", 3, "p",
 "Potoczne. „yang-ngai mâi rúu” = jakoś tak, sam nie wiem jak.", "",
 ("Sprawdzę.", "dǐao chék duu khráp", "เดี๋ยวเช็คดูครับ")),
("Nie sądzę.", "khít wâa mâi khráp", "คิดว่าไม่ครับ",
 "Small talk", "Reakcje", "phrase", 4, "n", "", "",
 ("Dlaczego?", "thammai khráp", "ทำไมครับ")),
("Wątpię.", "mâi nâa jà châi khráp", "ไม่น่าจะใช่ครับ",
 "Small talk", "Reakcje", "phrase", 3, "n", "„mâi nâa jà …” = raczej nie, wątpliwe, żeby.", "",
 ("Może masz rację.", "kâw àat jà thùuk khráp", "ก็อาจจะถูกครับ")),
("Zobaczymy, co będzie.", "duu kan tàw pai khráp", "ดูกันต่อไปครับ",
 "Small talk", "Reakcje", "phrase", 4, "n", "", "",
 ("Zgoda.", "khráp", "ครับ")),
("Zastanowię się.", "khǎw khít duu kàwn khráp", "ขอคิดดูก่อนครับ",
 "Small talk", "Reakcje", "phrase", 5, "n",
 "Uprzejma forma „raczej nie” — Tajowie często tak odmawiają, żeby nikt nie stracił twarzy.", "",
 ("Nie ma pośpiechu.", "mâi tâwng rîip khráp", "ไม่ต้องรีบครับ")),

# =====================================================================
# ODMOWA, WSTRZYMANIE, ZASTRZEZENIE
# =====================================================================
("Nie tym razem.", "khráng níi khǎw phàan khráp", "ครั้งนี้ขอผ่านครับ",
 "Podstawy i grzeczność", "Reakcje", "phrase", 3, "p",
 "„khǎw phàan” = pasuję, odpuszczam. Swobodne, ale nieobraźliwe.", "",
 ("Nie ma sprawy.", "mâi pen rai khráp", "ไม่เป็นไรครับ")),
("Może kiedy indziej.", "wái oo-kàat nâa khráp", "ไว้โอกาสหน้าครับ",
 "Podstawy i grzeczność", "Reakcje", "phrase", 4, "n",
 "„wái oo-kàot nâa” = odłóżmy to na następną okazję. Bardzo uprzejma odmowa.", "",
 ("Dobrze.", "dâai khráp", "ได้ครับ")),
("Wolałbym nie.", "khǎw mâi ná khráp", "ขอไม่นะครับ",
 "Podstawy i grzeczność", "Reakcje", "phrase", 4, "n", "", "",
 ("Rozumiem.", "khâo-jai khráp", "เข้าใจครับ")),
("Nie dam rady.", "khong mâi wǎi khráp", "คงไม่ไหวครับ",
 "Podstawy i grzeczność", "Reakcje", "phrase", 4, "n",
 "„mâi wǎi” = nie dam rady, nie wytrzymam. O sile i wytrzymałości, nie o umiejętności.", "",
 ("Nic nie szkodzi.", "mâi pen rai khráp", "ไม่เป็นไรครับ")),
("Dziś nie mogę.", "wan níi mâi wâang khráp", "วันนี้ไม่ว่างครับ",
 "Podstawy i grzeczność", "Reakcje", "phrase", 5, "n", "„mâi wâang” = zajęty, nie mam czasu.", "",
 ("To innym razem.", "ngán wái wan lǎng khráp", "งั้นไว้วันหลังครับ")),
("Muszę sprawdzić kalendarz.", "khǎw duu taa-raang kàwn khráp", "ขอดูตารางก่อนครับ",
 "Praca i nauka", "Reakcje", "phrase", 3, "n", "", "",
 ("Czekam na wiadomość.", "raw khàao ná khráp", "รอข่าวนะครับ")),
("Nie chcę obiecywać.", "mâi yàak sǎn-yaa khráp", "ไม่อยากสัญญาครับ",
 "Podstawy i grzeczność", "Reakcje", "sentence", 3, "n", "", "",
 ("Rozumiem.", "khâo-jai khráp", "เข้าใจครับ")),
("Zależy od pogody.", "láew tàae aa-kàat khráp", "แล้วแต่อากาศครับ",
 "Pogoda i przyroda", "Reakcje", "phrase", 3, "n", "", "",
 ("Racja.", "châi khráp", "ใช่ครับ")),

# =====================================================================
# ZACHETA I PROPOZYCJA
# =====================================================================
("No dalej!", "ao loei khráp", "เอาเลยครับ", "Small talk", "Reakcje", "phrase", 4, "i",
 "„ao loei” = śmiało, dawaj. Zachęta, nie rozkaz.", "",
 ("Dobrze, spróbuję.", "dâai khráp lawng duu", "ได้ครับ ลองดู")),
("Spróbuj.", "lawng duu sì khráp", "ลองดูสิครับ", "Small talk", "Reakcje", "phrase", 5, "i",
 "Partykuła „sì” dodaje zachęty. Bez niej zdanie brzmi płasko.", "",
 ("Dobrze.", "khráp", "ครับ")),
("Dasz radę.", "tham dâai nâe nawn khráp", "ทำได้แน่นอนครับ",
 "Small talk", "Reakcje", "phrase", 4, "n", "", "",
 ("Mam nadzieję.", "wǎng wâa yàang nán khráp", "หวังว่าอย่างนั้นครับ")),
("Chodźmy razem.", "pai dûai kan khráp", "ไปด้วยกันครับ",
 "Small talk", "Reakcje", "phrase", 4, "n", "", "",
 ("Świetnie.", "dii loei khráp", "ดีเลยครับ")),
("Może tak zrobimy?", "tham yàang níi dii mǎi khráp", "ทำอย่างนี้ดีไหมครับ",
 "Small talk", "Reakcje", "question", 4, "n", "", "",
 ("Dobry pomysł.", "khwaam-khít dii khráp", "ความคิดดีครับ")),
("Ja stawiam.", "phǒm líang eeng khráp", "ผมเลี้ยงเองครับ",
 "Restauracja", "Reakcje", "phrase", 4, "i",
 "„líang” = postawić komuś. W Tajlandii częściej płaci jedna osoba niż dzieli się rachunek.", "",
 ("Dziękuję!", "khàwp-khun khráp", "ขอบคุณครับ")),
("Podzielmy rachunek.", "yâek kan jàai ná khráp", "แยกกันจ่ายนะครับ",
 "Restauracja", "Reakcje", "phrase", 3, "n", "", "",
 ("Dobrze.", "dâai khráp", "ได้ครับ")),
("Zapraszam.", "choen khráp", "เชิญครับ", "Podstawy i grzeczność", "Reakcje", "phrase", 5, "f",
 "„choen” = proszę bardzo, zapraszam. Używane przy drzwiach, stole i oddawaniu głosu.", "",
 ("Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ")),
("Poczekam na ciebie.", "phǒm raw dâai khráp", "ผมรอได้ครับ",
 "Small talk", "Reakcje", "phrase", 4, "n", "", "",
 ("Zaraz będę.", "dǐao maa khráp", "เดี๋ยวมาครับ")),
("Nie spiesz się.", "khôi khôi kâw dâai khráp", "ค่อยๆ ก็ได้ครับ",
 "Small talk", "Reakcje", "phrase", 4, "n", "", "",
 ("Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ")),

# =====================================================================
# ROZLADOWYWANIE NAPIECIA
# =====================================================================
("Spokojnie.", "jai yen yen khráp", "ใจเย็นๆ ครับ",
 "Small talk", "Reakcje", "phrase", 5, "n",
 "Dosłownie „chłodne serce”. Podstawowa wartość w tajskiej kulturze — mówi się to bardzo często.", "chłodne serce",
 ("Już się uspokoiłem.", "jai yen láew khráp", "ใจเย็นแล้วครับ")),
("Nie ma się co złościć.", "mâi tâwng mo-hǒo khráp", "ไม่ต้องโมโหครับ",
 "Small talk", "Reakcje", "sentence", 3, "n", "„mo-hǒo” = wściekać się.", "",
 ("Wiem.", "rúu khráp", "รู้ครับ")),
("Zapomnij o tym.", "châng man thòe khráp", "ช่างมันเถอะครับ",
 "Small talk", "Reakcje", "phrase", 4, "p",
 "„châng man” = odpuść, nieważne. Bardzo tajskie podejście, ale wobec przełożonego zabrzmi lekceważąco.", "",
 ("Masz rację.", "kâw jing khráp", "ก็จริงครับ")),
("Takie życie.", "chii-wít kâw pen yàang níi khráp", "ชีวิตก็เป็นอย่างนี้ครับ",
 "Small talk", "Reakcje", "phrase", 3, "n", "", "",
 ("Zgadza się.", "châi khráp", "ใช่ครับ")),
("Nic na to nie poradzimy.", "tham à-rai mâi dâai khráp", "ทำอะไรไม่ได้ครับ",
 "Small talk", "Reakcje", "sentence", 3, "n", "", "",
 ("Wiem.", "rúu khráp", "รู้ครับ")),
("Śmiechu warte.", "khǎm jang loei", "ขำจังเลย", "Small talk", "Reakcje", "phrase", 3, "p",
 "„khǎm” = śmieszne. SLANG towarzyski: NIE używaj, gdy ktoś opowiada o swoim problemie.", "",
 ("Prawda?", "châi mǎi lâ", "ใช่ไหมล่ะ")),
("Żartowałem.", "phûut lên khráp", "พูดเล่นครับ",
 "Small talk", "Reakcje", "phrase", 4, "i", "", "",
 ("Wiedziałem.", "rúu yùu láew khráp", "รู้อยู่แล้วครับ")),
("Nie obraź się.", "yàa khîi jai ná khráp", "อย่าเคืองใจนะครับ",
 "Podstawy i grzeczność", "Reakcje", "phrase", 3, "f", "„khuean jai” = poczuć urazę.", "",
 ("Nie obrażam się.", "mâi khuean khráp", "ไม่เคืองครับ")),

# =====================================================================
# KONCZENIE ROZMOWY
# =====================================================================
("Muszę już iść.", "phǒm tâwng pai láew khráp", "ผมต้องไปแล้วครับ",
 "Podstawy i grzeczność", "Reakcje", "phrase", 5, "n", "", "",
 ("Dobrze, uważaj.", "khráp dòoen thaang plàwt phai ná", "ครับ เดินทางปลอดภัยนะ")),
("Odezwę się.", "dǐao thák pai ná khráp", "เดี๋ยวทักไปนะครับ",
 "Podstawy i grzeczność", "Reakcje", "phrase", 4, "i", "", "",
 ("Czekam.", "raw yùu khráp", "รออยู่ครับ")),
("Dam znać.", "dǐao bàwk ná khráp", "เดี๋ยวบอกนะครับ",
 "Podstawy i grzeczność", "Reakcje", "phrase", 5, "n", "", "",
 ("Dobrze.", "khráp", "ครับ")),
("Do usłyszenia.", "wái khui kan mài khráp", "ไว้คุยกันใหม่ครับ",
 "Podstawy i grzeczność", "Reakcje", "phrase", 4, "n", "", "",
 ("Do usłyszenia.", "khráp wái khui kan", "ครับ ไว้คุยกัน")),
("Miło się rozmawiało.", "khui sà-nùk dii khráp", "คุยสนุกดีครับ",
 "Small talk", "Reakcje", "phrase", 4, "n", "", "",
 ("Mnie też.", "chên kan khráp", "เช่นกันครับ")),
("Dzięki za dziś.", "khàwp-khun sǎm-ràp wan níi khráp", "ขอบคุณสำหรับวันนี้ครับ",
 "Podstawy i grzeczność", "Reakcje", "phrase", 4, "n", "", "",
 ("Nawzajem.", "chên kan khráp", "เช่นกันครับ")),
("Uważaj na siebie w drodze.", "dòoen thaang plàwt phai ná khráp", "เดินทางปลอดภัยนะครับ",
 "Podstawy i grzeczność", "Reakcje", "sentence", 4, "n", "„plàwt phai” = bezpiecznie.", "",
 ("Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ")),
("Pozdrów rodzinę.", "fàak sà-wàt-dii khrâwp-khrua dûai ná khráp",
 "ฝากสวัสดีครอบครัวด้วยนะครับ", "Ludzie i rodzina", "Reakcje", "sentence", 3, "n",
 "„fàak … dûai” = przekaż ode mnie. Konstrukcja, której nie da się zbudować z polskiego.", "",
 ("Przekażę.", "dâai khráp", "ได้ครับ")),

# =====================================================================
# DROBNE WTRACENIA
# =====================================================================
("No wiesz.", "kâw ná khráp", "ก็นะครับ", "Small talk", "Reakcje", "phrase", 4, "p",
 "Wypełniacz zawieszający zdanie, kiedy nie chcesz dokończyć myśli.", "",
 ("Rozumiem.", "khâo-jai khráp", "เข้าใจครับ")),
("Jakoś tak.", "kâw prà-maan nán khráp", "ก็ประมาณนั้นครับ",
 "Small talk", "Reakcje", "phrase", 4, "n", "", "",
 ("Jasne.", "khráp", "ครับ")),
("Coś w tym stylu.", "thamnawng nán khráp", "ทำนองนั้นครับ",
 "Small talk", "Reakcje", "phrase", 3, "n", "", "",
 ("Rozumiem.", "khâo-jai khráp", "เข้าใจครับ")),
("Mniej więcej.", "kâw prà-maan níi khráp", "ก็ประมาณนี้ครับ",
 "Small talk", "Reakcje", "phrase", 4, "n", "", "",
 ("Dobrze.", "khráp", "ครับ")),
("Tak jakby.", "bàep wâa", "แบบว่า", "Small talk", "Reakcje", "phrase", 4, "p",
 "SLANG młodzieżowy, wypełniacz. NIE używaj na rozmowie o pracę ani przy urzędniku — brzmi niepoważnie.", "",
 ("Rozumiem.", "khâo-jai khráp", "เข้าใจครับ")),
("Właśnie o to chodzi.", "nân lâ khráp prà-den", "นั่นล่ะครับประเด็น",
 "Small talk", "Reakcje", "phrase", 3, "n", "„prà-den” = sedno, kwestia.", "",
 ("Zgadza się.", "châi khráp", "ใช่ครับ")),
("W sumie racja.", "kâw jing khǎwng khun khráp", "ก็จริงของคุณครับ",
 "Small talk", "Reakcje", "phrase", 4, "i", "", "",
 ("Prawda?", "châi mǎi khráp", "ใช่ไหมครับ")),
("Chwila, chwila.", "ûe raw kàwn khráp", "เอ๊ะ รอก่อนครับ",
 "Small talk", "Reakcje", "phrase", 3, "i", "„ûe” to dźwięk konsternacji: coś się nie zgadza.", "",
 ("O co chodzi?", "à-rai rǒe khráp", "อะไรหรือครับ")),
("A właśnie!", "âw châi sì khráp", "อ๋อ ใช่สิครับ",
 "Small talk", "Reakcje", "phrase", 4, "i", "Moment przypomnienia sobie czegoś.", "",
 ("Co takiego?", "à-rai khráp", "อะไรครับ")),
("Zapomniałbym.", "kùeap luem khráp", "เกือบลืมครับ",
 "Small talk", "Reakcje", "phrase", 4, "n", "„kùeap” = prawie, o mało co.", "",
 ("O czym?", "rûeang à-rai khráp", "เรื่องอะไรครับ")),
("Przy okazji.", "wâa tàae", "ว่าแต่", "Small talk", "Reakcje", "phrase", 4, "i",
 "„wâa tàae” otwiera nowy wątek: „a tak w ogóle…”.", "",
 ("Tak?", "khráp", "ครับ")),
("Jak to?", "yang-ngai ná khráp", "ยังไงนะครับ",
 "Small talk", "Reakcje", "question", 4, "n", "", "",
 ("Wyjaśnię.", "dǐao à-thí-baai hâi khráp", "เดี๋ยวอธิบายให้ครับ")),
("Dlaczego akurat tak?", "thammai thǔeng pen yàang nán khráp", "ทำไมถึงเป็นอย่างนั้นครับ",
 "Pytania", "Reakcje", "question", 3, "n", "„thǔeng” między pytajnikiem a czasownikiem = „właściwie, akurat”.", "",
 ("To długa historia.", "man yaao khráp", "มันยาวครับ")),
("Skąd wiesz?", "rúu dâai yang-ngai khráp", "รู้ได้ยังไงครับ",
 "Pytania", "Reakcje", "question", 4, "n", "", "",
 ("Ktoś mi powiedział.", "mii khon bàwk khráp", "มีคนบอกครับ")),
("Kto ci to powiedział?", "khrai bàwk khráp", "ใครบอกครับ",
 "Pytania", "Reakcje", "question", 3, "n", "", "",
 ("Kolega z pracy.", "phûean thîi tham ngaan khráp", "เพื่อนที่ทำงานครับ")),
("Nie słyszałem o tym.", "mâi khoei dâi yin loei khráp", "ไม่เคยได้ยินเลยครับ",
 "Small talk", "Reakcje", "sentence", 3, "n", "", "",
 ("To nowość.", "phôoeng mii khráp", "เพิ่งมีครับ")),
("Wszyscy o tym mówią.", "khrai kâw phûut thǔeng khráp", "ใครก็พูดถึงครับ",
 "Small talk", "Reakcje", "sentence", 3, "n", "", "",
 ("Naprawdę?", "jing rǒe khráp", "จริงหรือครับ")),
("Ja też tak słyszałem.", "phǒm kâw dâi yin maa mǔean kan khráp", "ผมก็ได้ยินมาเหมือนกันครับ",
 "Small talk", "Reakcje", "sentence", 3, "n", "", "",
 ("Czyli to prawda.", "ngán kâw jing khráp", "งั้นก็จริงครับ")),
("Nie mam pojęcia.", "mâi mii khwaam-khít loei khráp", "ไม่มีความคิดเลยครับ",
 "Small talk", "Reakcje", "phrase", 3, "n", "", "",
 ("Sprawdźmy.", "chék duu kan khráp", "เช็คดูกันครับ")),
("Pierwsze słyszę.", "phôoeng khoei dâi yin khráp", "เพิ่งเคยได้ยินครับ",
 "Small talk", "Reakcje", "phrase", 3, "n", "", "",
 ("Serio?", "jing rǒe khráp", "จริงหรือครับ")),
("To ma sens dopiero teraz.", "thǔeng phôoeng khâo-jai tawn níi khráp", "ถึงเพิ่งเข้าใจตอนนี้ครับ",
 "Small talk", "Reakcje", "sentence", 3, "n", "", "",
 ("Dobrze.", "dii khráp", "ดีครับ")),
("Właśnie o tym myślałem.", "phǒm kâw khít yùu phaw dii khráp", "ผมก็คิดอยู่พอดีครับ",
 "Small talk", "Reakcje", "sentence", 3, "n", "„phaw dii” = akurat, w sam raz.", "",
 ("Zbieżność.", "khít trong kan khráp", "คิดตรงกันครับ")),
("Też mi to przyszło do głowy.", "phǒm kâw nùek dâai mǔean kan khráp", "ผมก็นึกได้เหมือนกันครับ",
 "Small talk", "Reakcje", "sentence", 3, "n", "„nùek” = przypomnieć sobie, wpaść na coś.", "",
 ("Świetnie.", "dii loei khráp", "ดีเลยครับ")),
("Zgadza się co do słowa.", "trong pêe loei khráp", "ตรงเป๊ะเลยครับ",
 "Small talk", "Reakcje", "phrase", 3, "p",
 "„pêe” = idealnie, co do joty. Potoczne wzmocnienie.", "",
 ("Świetnie.", "dii khráp", "ดีครับ")),
("Coś podobnego mi się zdarzyło.", "phǒm kâw jôe maa khláai kan khráp", "ผมก็เจอมาคล้ายกันครับ",
 "Small talk", "Reakcje", "sentence", 3, "n", "„jôe maa” = doświadczyć, napotkać.", "",
 ("Opowiedz.", "lâo hâi fang nòi khráp", "เล่าให้ฟังหน่อยครับ")),
("Mnie też to spotkało.", "phǒm kâw pen mǔean kan khráp", "ผมก็เป็นเหมือนกันครับ",
 "Small talk", "Reakcje", "sentence", 4, "n", "", "",
 ("No właśnie.", "nân sì khráp", "นั่นสิครับ")),
("Wiedziałem!", "rúu yùu láew", "รู้อยู่แล้ว", "Small talk", "Reakcje", "phrase", 4, "i", "", "",
 ("Naprawdę?", "jing rǒe", "จริงหรือ")),
("A nie mówiłem?", "bàwk láew ngai lâ khráp", "บอกแล้วไงล่ะครับ",
 "Small talk", "Reakcje", "question", 3, "p",
 "Potoczne i lekko triumfalne. NIE mów tak do klienta ani przełożonego.", "",
 ("No dobra.", "kâw dâai khráp", "ก็ได้ครับ")),
("Miałeś rację.", "khun phûut thùuk tâng tàae râek khráp", "คุณพูดถูกตั้งแต่แรกครับ",
 "Small talk", "Reakcje", "sentence", 3, "n", "", "",
 ("Nieważne.", "mâi pen rai khráp", "ไม่เป็นไรครับ")),
("Tak przypuszczałem.", "khâat wái láew khráp", "คาดไว้แล้วครับ",
 "Small talk", "Reakcje", "phrase", 3, "n", "„khâat” = przewidywać, spodziewać się.", "",
 ("Sprytnie.", "kèng khráp", "เก่งครับ")),
("Szczerze? Nie wiem.", "phûut trong trong khue mâi rúu khráp", "พูดตรงๆ คือไม่รู้ครับ",
 "Small talk", "Reakcje", "sentence", 3, "n", "", "",
 ("W porządku.", "mâi pen rai khráp", "ไม่เป็นไรครับ")),
("Może masz rację.", "khun àat jà thùuk kâw dâai khráp", "คุณอาจจะถูกก็ได้ครับ",
 "Small talk", "Reakcje", "sentence", 4, "n", "", "",
 ("Zobaczymy.", "duu kan tàw pai khráp", "ดูกันต่อไปครับ")),
("Wiem, co masz na myśli.", "phǒm rúu wâa khun màai thǔeng à-rai khráp",
 "ผมรู้ว่าคุณหมายถึงอะไรครับ", "Small talk", "Reakcje", "sentence", 3, "n", "", "",
 ("To dobrze.", "dii khráp", "ดีครับ")),
("Nie do końca.", "mâi thǔeng kàp khà-nàat nán khráp", "ไม่ถึงกับขนาดนั้นครับ",
 "Small talk", "Reakcje", "phrase", 3, "n", "„mâi thǔeng kàp …” = nie aż tak, nie do tego stopnia.", "",
 ("Rozumiem.", "khâo-jai khráp", "เข้าใจครับ")),
("W pewnym sensie tak.", "kâw thǔe wâa châi khráp", "ก็ถือว่าใช่ครับ",
 "Small talk", "Reakcje", "phrase", 3, "n", "", "",
 ("Rozumiem.", "khâo-jai khráp", "เข้าใจครับ")),
("Powiedzmy.", "kâw prà-maan nán lâ khráp", "ก็ประมาณนั้นล่ะครับ",
 "Small talk", "Reakcje", "phrase", 3, "p", "", "",
 ("Jasne.", "khráp", "ครับ")),
("To zmienia postać rzeczy.", "ngán kâw ìik rûeang nùeng láew khráp", "งั้นก็อีกเรื่องหนึ่งแล้วครับ",
 "Small talk", "Reakcje", "sentence", 3, "n", "", "",
 ("Właśnie.", "châi khráp", "ใช่ครับ")),
("Nie o to pytałem.", "mâi dâi thǎam yàang nán khráp", "ไม่ได้ถามอย่างนั้นครับ",
 "Small talk", "Reakcje", "sentence", 3, "n", "", "",
 ("Przepraszam.", "khǎw-thôot khráp", "ขอโทษครับ")),
("Dobrze, że mówisz.", "dii thîi bàwk khráp", "ดีที่บอกครับ",
 "Small talk", "Reakcje", "phrase", 4, "n", "", "",
 ("Nie ma za co.", "mâi pen rai khráp", "ไม่เป็นไรครับ")),
("Dzięki, że dałeś znać.", "khàwp-khun thîi bàwk khráp", "ขอบคุณที่บอกครับ",
 "Podstawy i grzeczność", "Reakcje", "phrase", 4, "n", "", "",
 ("Drobiazg.", "rûeang lék khráp", "เรื่องเล็กครับ")),
("Nie ma o czym mówić.", "rûeang lék náwi khráp", "เรื่องเล็กน้อยครับ",
 "Podstawy i grzeczność", "Reakcje", "phrase", 3, "n", "", "",
 ("Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ")),
("To żaden problem.", "mâi mii pan-hǎa loei khráp", "ไม่มีปัญหาเลยครับ",
 "Podstawy i grzeczność", "Reakcje", "phrase", 4, "n", "", "",
 ("Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ")),
("Zawsze do usług.", "yin dii chûai sà-mǒoe khráp", "ยินดีช่วยเสมอครับ",
 "Podstawy i grzeczność", "Reakcje", "phrase", 3, "f", "„yin dii” = z przyjemnością.", "",
 ("Dziękuję bardzo.", "khàwp-khun mâak khráp", "ขอบคุณมากครับ")),
("Cała przyjemność moja.", "yin dii khráp", "ยินดีครับ",
 "Podstawy i grzeczność", "Reakcje", "phrase", 4, "f", "", "",
 ("Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ")),
("Nie ma potrzeby.", "mâi jam pen khráp", "ไม่จำเป็นครับ",
 "Podstawy i grzeczność", "Reakcje", "phrase", 3, "n", "„jam pen” = konieczny.", "",
 ("Dobrze.", "khráp", "ครับ")),
("Zostawmy to tak.", "ao wái yàang níi kâwn khráp", "เอาไว้อย่างนี้ก่อนครับ",
 "Small talk", "Reakcje", "phrase", 3, "n", "", "",
 ("Zgoda.", "khráp", "ครับ")),
("Trochę tak, trochę nie.", "kâw mii thúk yàang khráp", "ก็มีทุกอย่างครับ",
 "Small talk", "Reakcje", "phrase", 3, "p", "", "",
 ("Rozumiem.", "khâo-jai khráp", "เข้าใจครับ")),
("Bywa różnie.", "láew tàae wan khráp", "แล้วแต่วันครับ",
 "Small talk", "Reakcje", "phrase", 3, "n", "", "zależy od dnia",
 ("To prawda.", "jing khráp", "จริงครับ")),
("Ostatnio rzadziej.", "chûang níi náwi long khráp", "ช่วงนี้น้อยลงครับ",
 "Small talk", "Reakcje", "phrase", 3, "n", "", "",
 ("Rozumiem.", "khâo-jai khráp", "เข้าใจครับ")),
("Jak zwykle.", "mǔean khoei khráp", "เหมือนเคยครับ",
 "Small talk", "Reakcje", "phrase", 4, "n", "„mǔean khoei” = jak zawsze, po staremu.", "",
 ("Rozumiem.", "khâo-jai khráp", "เข้าใจครับ")),
("Nic nowego.", "mâi mii à-rai mài khráp", "ไม่มีอะไรใหม่ครับ",
 "Small talk", "Reakcje", "phrase", 4, "n", "", "",
 ("Spokojnie u ciebie.", "kâw sà-ngòp dii khráp", "ก็สงบดีครับ")),
("Po staremu.", "kâw rûeay rûeay khráp", "ก็เรื่อยๆ ครับ",
 "Small talk", "Reakcje", "phrase", 4, "p",
 "„rûeay rûeay” = tak sobie, bez zmian. Bardzo częsta odpowiedź na „jak leci”.", "",
 ("Rozumiem.", "khâo-jai khráp", "เข้าใจครับ")),
("Dużo się dzieje.", "chûang níi wûn waai khráp", "ช่วงนี้วุ่นวายครับ",
 "Small talk", "Reakcje", "phrase", 3, "n", "„wûn waai” = zabiegany, chaotyczny.", "",
 ("Odpocznij trochę.", "phák bâang ná khráp", "พักบ้างนะครับ")),
]
