# -*- coding: utf-8 -*-
"""Wzorce zdaniowe etapu 5 (B2) — czesc A: konstrukcje czasownikowe.

Kazdy wzorzec ma ZAMKNIETA biala liste hasel bazowych. Konstrukcje sa dobrane
tak, zeby nie powielaly wzorcow A1, A2 ani B1. Zuzyte juz zostaly miedzy innymi:
„yàak”, „tâwng”, „khoei”, „phôoeng”, „kamlang … yùu”, „mâi khâwi”, „koen pai”,
„thâa … kâw …”, „kwàa … jà …”, „mâi wâa yang-ngai …”, „thǔeng máe wâa …”,
„yîng … yîng …”, „tham hâi …”.

Etap 5 siega po konstrukcje typowe dla mowy doroslej i biurowej: proba o czas,
kategoryczne zaprzeczenie mozliwosci, ciaglosc od zawsze, wstrzymanie
czynnosci, gotowosc warunkowa, brak koniecznosci, czynnosc o wlos niedokonana.

Pozycja: (polskie haslo rekordu, polskie haslo bazowe, polski przyklad)
"""

TPL_A = [

# =====================================================================
# khaw wee-laa … sak khruu — prosba o czas na czynnosc
# =====================================================================
dict(key="KHAWWEELA", ty="sentence", cat="Praca i nauka", sub="Prośby", reg="f",
     ph="khǎw wee-laa {ph} sák khrûu khráp", th="ขอเวลา{th}สักครู่ครับ",
     lit="khǎw wee-laa … sák khrûu = proszę o chwilę na …",
     note="Prośba o czas, nie o zgodę. W biurze i urzędzie brzmi znacznie lepiej niż samo „dǐao”.",
     ex_ph="khǎw wee-laa {ph} sák khrûu ná khráp dǐao maa", ex_th="ขอเวลา{th}สักครู่นะครับ เดี๋ยวมา",
     items=[
       ("Poproszę chwilę na przeczytanie.", "czytać", "Poproszę chwilę na przeczytanie, zaraz wracam."),
       ("Poproszę chwilę na zastanowienie.", "myśleć", "Poproszę chwilę na zastanowienie, zaraz wracam."),
       ("Poproszę chwilę na sprawdzenie.", "szukać", "Poproszę chwilę na sprawdzenie, zaraz wracam."),
       ("Poproszę chwilę na zapisanie.", "pisać", "Poproszę chwilę na zapisanie, zaraz wracam."),
       ("Poproszę chwilę na wybranie.", "wybierać", "Poproszę chwilę na wybranie, zaraz wracam."),
       ("Poproszę chwilę na przymierzenie.", "przymierzać / próbować", "Poproszę chwilę na przymierzenie, zaraz wracam."),
       ("Poproszę chwilę na zamówienie.", "zamawiać", "Poproszę chwilę na zamówienie, zaraz wracam."),
       ("Poproszę chwilę na zapłacenie.", "płacić", "Poproszę chwilę na zapłacenie, zaraz wracam."),
       ("Poproszę chwilę na spakowanie się.", "pakować się", "Poproszę chwilę na spakowanie się, zaraz wracam."),
       ("Poproszę chwilę na telefon.", "dzwonić", "Poproszę chwilę na telefon, zaraz wracam."),
       ("Poproszę chwilę na odpoczynek.", "odpoczywać", "Poproszę chwilę na odpoczynek, zaraz wracam."),
       ("Poproszę chwilę na przygotowanie.", "robić", "Poproszę chwilę na przygotowanie, zaraz wracam."),
       ("Poproszę chwilę na podpisanie.", "podpisać", "Poproszę chwilę na podpisanie, zaraz wracam."),
       ("Poproszę chwilę na wypełnienie formularza.", "wypełnić formularz", "Poproszę chwilę na wypełnienie, zaraz wracam."),
       ("Poproszę chwilę na obejrzenie.", "oglądać", "Poproszę chwilę na obejrzenie, zaraz wracam."),
       ("Poproszę chwilę na rozmowę.", "rozmawiać", "Poproszę chwilę na rozmowę, zaraz wracam."),
       ("Poproszę chwilę na zjedzenie.", "jeść", "Poproszę chwilę na zjedzenie, zaraz wracam."),
       ("Poproszę chwilę na wysłanie wiadomości.", "wysyłać", "Poproszę chwilę na wysłanie, zaraz wracam."),
       ("Poproszę chwilę na przeliczenie rachunku.", "policzyć rachunek", "Poproszę chwilę na przeliczenie, zaraz wracam."),
       ("Poproszę chwilę na spotkanie z nim.", "spotykać", "Poproszę chwilę na spotkanie, zaraz wracam."),
       ("Poproszę chwilę na zmianę ubrania.", "zmieniać", "Poproszę chwilę na zmianę, zaraz wracam."),
       ("Poproszę chwilę na rezerwację.", "rezerwować", "Poproszę chwilę na rezerwację, zaraz wracam."),
       ("Poproszę chwilę na naukę.", "uczyć się", "Poproszę chwilę na naukę, zaraz wracam."),
       ("Poproszę chwilę na wzięcie prysznica.", "brać prysznic", "Poproszę chwilę na prysznic, zaraz wracam."),
       ("Poproszę chwilę na umycie rąk.", "myć", "Poproszę chwilę na umycie rąk, zaraz wracam."),
       ("Poproszę chwilę na zrobienie zdjęć.", "robić zdjęcia", "Poproszę chwilę na zdjęcia, zaraz wracam."),
       ("Poproszę chwilę na odebranie przesyłki.", "odbierać", "Poproszę chwilę na odbiór, zaraz wracam."),
       ("Poproszę chwilę na wyjście na zewnątrz.", "wychodzić", "Poproszę chwilę na wyjście, zaraz wracam."),
       ("Poproszę chwilę na zapytanie kogoś.", "pytać", "Poproszę chwilę na zapytanie, zaraz wracam."),
       ("Poproszę chwilę na odpowiedź.", "odpowiadać", "Poproszę chwilę na odpowiedź, zaraz wracam."),
       ("Poproszę chwilę na wysłuchanie nagrania.", "słuchać", "Poproszę chwilę na wysłuchanie, zaraz wracam."),
       ("Poproszę chwilę na zapamiętanie tego.", "pamiętać", "Poproszę chwilę na zapamiętanie, zaraz wracam."),
       ("Poproszę chwilę na pokazanie tego szefowi.", "pokazać", "Poproszę chwilę na pokazanie, zaraz wracam."),
       ("Poproszę chwilę na spróbowanie.", "próbować (smakować)", "Poproszę chwilę na spróbowanie, zaraz wracam."),
       ("Poproszę chwilę na pożyczenie tego.", "pożyczyć", "Poproszę chwilę na pożyczenie, zaraz wracam."),
       ("Poproszę chwilę na wstanie.", "wstawać", "Poproszę chwilę, zaraz wstanę."),
     ]),

# =====================================================================
# mai mii thaang thii ja … dai — kategoryczne zaprzeczenie mozliwosci
# =====================================================================
dict(key="MAIMEETHAANG", ty="sentence", cat="Gramatyka użytkowa", sub="Odmowa", reg="n",
     ph="mâi mii thaang thîi jà {ph} dâai khráp", th="ไม่มีทางที่จะ{th}ได้ครับ",
     lit="mâi mii thaang = nie ma drogi, nie ma sposobu",
     note="Mocne zaprzeczenie możliwości. Wobec klienta zmiękcz je do „khong jà yâak khráp”, bo brzmi jak zatrzaśnięcie drzwi.",
     ex_ph="jing jing ná khráp mâi mii thaang thîi jà {ph} dâai", ex_th="จริงๆ นะครับ ไม่มีทางที่จะ{th}ได้",
     items=[
       ("Nie ma szans, żeby zdążyć wrócić.", "wracać", "Naprawdę nie ma szans, żeby wrócić."),
       ("Nie ma szans, żeby to sprzedać.", "sprzedawać", "Naprawdę nie ma szans, żeby to sprzedać."),
       ("Nie ma szans, żeby to naprawić dziś.", "naprawiać", "Naprawdę nie ma szans, żeby to naprawić."),
       ("Nie ma szans, żeby to anulować.", "anulować", "Naprawdę nie ma szans, żeby anulować."),
       ("Nie ma szans, żeby to zmienić.", "zmieniać", "Naprawdę nie ma szans, żeby to zmienić."),
       ("Nie ma szans, żeby to wynająć taniej.", "wynajmować", "Naprawdę nie ma szans, żeby wynająć."),
       ("Nie ma szans, żeby zapłacić dziś.", "płacić", "Naprawdę nie ma szans, żeby zapłacić."),
       ("Nie ma szans, żeby to zarezerwować.", "rezerwować", "Naprawdę nie ma szans, żeby zarezerwować."),
       ("Nie ma szans, żeby zdążyć się spakować.", "pakować się", "Naprawdę nie ma szans, żeby się spakować."),
       ("Nie ma szans, żeby się dodzwonić.", "dzwonić", "Naprawdę nie ma szans, żeby się dodzwonić."),
       ("Nie ma szans, żeby to znaleźć w tym tłumie.", "znaleźć", "Naprawdę nie ma szans, żeby to znaleźć."),
       ("Nie ma szans, żeby dziś odpocząć.", "odpocząć", "Naprawdę nie ma szans, żeby odpocząć."),
       ("Nie ma szans, żeby się dziś wyspać.", "spać", "Naprawdę nie ma szans, żeby się wyspać."),
       ("Nie ma szans, żeby to podpisać bez prawnika.", "podpisać", "Naprawdę nie ma szans, żeby podpisać."),
       ("Nie ma szans, żeby to wysłać dzisiaj.", "wysyłać", "Naprawdę nie ma szans, żeby wysłać."),
       ("Nie ma szans, żeby się z nim spotkać.", "spotykać", "Naprawdę nie ma szans, żeby się spotkać."),
       ("Nie ma szans, żeby to ugotować w godzinę.", "gotować", "Naprawdę nie ma szans, żeby ugotować."),
       ("Nie ma szans, żeby zdążyć poczekać.", "czekać", "Naprawdę nie ma szans, żeby czekać."),
       ("Nie ma szans, żeby to zrozumieć bez tłumacza.", "rozumieć", "Naprawdę nie ma szans, żeby to zrozumieć."),
       ("Nie ma szans, żeby to zapamiętać za jednym razem.", "pamiętać", "Naprawdę nie ma szans, żeby zapamiętać."),
       ("Nie ma szans, żeby tam iść pieszo.", "iść pieszo", "Naprawdę nie ma szans, żeby iść pieszo."),
       ("Nie ma szans, żeby się tu przesiąść.", "przesiadać się", "Naprawdę nie ma szans, żeby się przesiąść."),
       ("Nie ma szans, żeby to przymierzyć teraz.", "przymierzać / próbować", "Naprawdę nie ma szans, żeby przymierzyć."),
       ("Nie ma szans, żeby zdążyć zwiedzić wszystko.", "zwiedzać", "Naprawdę nie ma szans, żeby zwiedzić."),
       ("Nie ma szans, żeby to wypełnić bez danych.", "wypełnić formularz", "Naprawdę nie ma szans, żeby wypełnić."),
       ("Nie ma szans, żeby dziś pracować dłużej.", "pracować", "Naprawdę nie ma szans, żeby pracować dłużej."),
       ("Nie ma szans, żeby prowadzić po takiej nocy.", "prowadzić samochód", "Naprawdę nie ma szans, żeby prowadzić."),
       ("Nie ma szans, żeby to kupić w tej cenie.", "kupować", "Naprawdę nie ma szans, żeby to kupić."),
       ("Nie ma szans, żeby mu pomóc bez dokumentów.", "pomagać", "Naprawdę nie ma szans, żeby pomóc."),
       ("Nie ma szans, żeby zdążyć na pociąg.", "przyjść / przyjechać", "Naprawdę nie ma szans, żeby zdążyć."),
       ("Nie ma szans, żeby to teraz otworzyć.", "otwierać", "Naprawdę nie ma szans, żeby otworzyć."),
       ("Nie ma szans, żeby jeszcze coś zamówić.", "zamawiać", "Naprawdę nie ma szans, żeby zamówić."),
       ("Nie ma szans, żeby dziś popływać.", "pływać", "Naprawdę nie ma szans, żeby popływać."),
       ("Nie ma szans, żeby to wszystko przeczytać.", "czytać", "Naprawdę nie ma szans, żeby przeczytać."),
       ("Nie ma szans, żeby tego użyć bez ładowarki.", "używać", "Naprawdę nie ma szans, żeby użyć."),
       ("Nie ma szans, żeby to komuś pożyczyć.", "pożyczyć", "Naprawdę nie ma szans, żeby pożyczyć."),
     ]),

# =====================================================================
# … maa ta-lawt — czynnosc ciagla od zawsze
# =====================================================================
dict(key="TALAWT", ty="sentence", cat="Gramatyka użytkowa", sub="Przeszłość", reg="n",
     ph="phǒm {ph} maa tà-làwt khráp", th="ผม{th}มาตลอดครับ",
     lit="tà-làwt = przez cały czas, nieprzerwanie",
     note="Tajska konstrukcja dokonana o polskim znaczeniu teraźniejszym: robię to od zawsze i nadal robię. Nie tłumacz jej czasem przeszłym.",
     ex_ph="khun {ph} maa tà-làwt loei rǒe khráp", ex_th="คุณ{th}มาตลอดเลยหรือครับ",
     items=[
       ("Zawsze to robię i nic się nie zmieniło.", "robić", "Zawsze tak robisz?"),
       ("Zawsze tu pracuję, od samego początku.", "pracować", "Zawsze tu pracujesz?"),
       ("Zawsze się uczę, nawet po pracy.", "uczyć się", "Zawsze się uczysz?"),
       ("Zawsze gotuję sam w domu.", "gotować", "Zawsze gotujesz sam?"),
       ("Zawsze wracam tą samą drogą.", "wracać", "Zawsze wracasz tą drogą?"),
       ("Zawsze czekam na niego przed wejściem.", "czekać", "Zawsze na niego czekasz?"),
       ("Zawsze płacę gotówką.", "płacić", "Zawsze płacisz gotówką?"),
       ("Zawsze biegam rano.", "biegać", "Zawsze biegasz rano?"),
       ("Zawsze pomagam sąsiadom.", "pomagać", "Zawsze im pomagasz?"),
       ("Zawsze rezerwuję z wyprzedzeniem.", "rezerwować", "Zawsze rezerwujesz wcześniej?"),
       ("Zawsze pytam, zanim wejdę.", "pytać", "Zawsze pytasz przed wejściem?"),
       ("Zawsze noszę to ze sobą.", "brać", "Zawsze to ze sobą nosisz?"),
       ("Zawsze śpię przy otwartym oknie.", "spać", "Zawsze tak śpisz?"),
       ("Zawsze jem to samo na śniadanie.", "jeść", "Zawsze jesz to samo?"),
       ("Zawsze piję kawę bez cukru.", "pić", "Zawsze pijesz bez cukru?"),
       ("Zawsze piszę wszystko ręcznie.", "pisać", "Zawsze piszesz ręcznie?"),
       ("Zawsze czytam przed snem.", "czytać", "Zawsze czytasz przed snem?"),
       ("Zawsze słucham radia w drodze.", "słuchać", "Zawsze słuchasz radia?"),
       ("Zawsze budzę się przed budzikiem.", "budzić się", "Zawsze budzisz się wcześniej?"),
       ("Zawsze robię zdjęcia w podróży.", "robić zdjęcia", "Zawsze robisz zdjęcia?"),
       ("Zawsze prowadzę sam na dłuższych trasach.", "prowadzić samochód", "Zawsze prowadzisz sam?"),
       ("Zawsze wynajmuję w tej samej okolicy.", "wynajmować", "Zawsze wynajmujesz tutaj?"),
       ("Zawsze szukam najpierw w internecie.", "szukać", "Zawsze najpierw szukasz w sieci?"),
       ("Zawsze odbieram telefon od razu.", "odbierać", "Zawsze odbierasz od razu?"),
       ("Zawsze dzwonię wieczorem do rodziny.", "dzwonić", "Zawsze dzwonisz wieczorem?"),
       ("Zawsze podpisuję po przeczytaniu.", "podpisać", "Zawsze podpisujesz po przeczytaniu?"),
       ("Zawsze pakuję się dzień wcześniej.", "pakować się", "Zawsze pakujesz się wcześniej?"),
       ("Zawsze piorę w weekend.", "prać", "Zawsze pierzesz w weekend?"),
       ("Zawsze sprzątam w niedzielę.", "sprzątać", "Zawsze sprzątasz w niedzielę?"),
       ("Zawsze wybieram miejsce przy oknie.", "wybierać", "Zawsze wybierasz przy oknie?"),
       ("Zawsze siedzę z tyłu.", "siedzieć", "Zawsze siedzisz z tyłu?"),
       ("Zawsze zamawiam to samo danie.", "zamawiać", "Zawsze zamawiasz to samo?"),
       ("Zawsze pływam przed śniadaniem.", "pływać", "Zawsze pływasz rano?"),
       ("Zawsze odpoczywam po obiedzie.", "odpoczywać", "Zawsze odpoczywasz po obiedzie?"),
       ("Zawsze używam tej samej aplikacji.", "używać", "Zawsze używasz tej aplikacji?"),
       ("Zawsze wstaję o piątej.", "wstawać", "Zawsze wstajesz o piątej?"),
     ]),

# =====================================================================
# yaa phoeng … na khrap — wstrzymanie czynnosci
# =====================================================================
dict(key="YAAPHOENG", ty="sentence", cat="Gramatyka użytkowa", sub="Prośby", reg="n",
     ph="yàa phôoeng {ph} ná khráp", th="อย่าเพิ่ง{th}นะครับ",
     lit="yàa phôoeng … = nie rób tego jeszcze, wstrzymaj się",
     note="„yàa phôoeng” to nie zakaz, tylko prośba o wstrzymanie się na chwilę. Bez „phôoeng” zdanie zabrzmi jak twardy zakaz.",
     ex_ph="yàa phôoeng {ph} khráp raw ìik nít nùeng", ex_th="อย่าเพิ่ง{th}ครับ รออีกนิดหนึ่ง",
     items=[
       ("Nie podpisuj jeszcze.", "podpisać", "Nie podpisuj jeszcze, poczekaj chwilę."),
       ("Nie płać jeszcze.", "płacić", "Nie płać jeszcze, poczekaj chwilę."),
       ("Nie zamawiaj jeszcze.", "zamawiać", "Nie zamawiaj jeszcze, poczekaj chwilę."),
       ("Nie wychodź jeszcze.", "wychodzić", "Nie wychodź jeszcze, poczekaj chwilę."),
       ("Nie wracaj jeszcze.", "wracać", "Nie wracaj jeszcze, poczekaj chwilę."),
       ("Nie zamykaj jeszcze.", "zamykać", "Nie zamykaj jeszcze, poczekaj chwilę."),
       ("Nie otwieraj jeszcze.", "otwierać", "Nie otwieraj jeszcze, poczekaj chwilę."),
       ("Nie wysyłaj jeszcze.", "wysyłać", "Nie wysyłaj jeszcze, poczekaj chwilę."),
       ("Nie dzwoń jeszcze.", "dzwonić", "Nie dzwoń jeszcze, poczekaj chwilę."),
       ("Nie anuluj jeszcze.", "anulować", "Nie anuluj jeszcze, poczekaj chwilę."),
       ("Nie kupuj jeszcze.", "kupować", "Nie kupuj jeszcze, poczekaj chwilę."),
       ("Nie sprzedawaj jeszcze.", "sprzedawać", "Nie sprzedawaj jeszcze, poczekaj chwilę."),
       ("Nie zmieniaj jeszcze.", "zmieniać", "Nie zmieniaj jeszcze, poczekaj chwilę."),
       ("Nie wsiadaj jeszcze.", "wsiadać", "Nie wsiadaj jeszcze, poczekaj chwilę."),
       ("Nie wysiadaj jeszcze.", "wysiadać", "Nie wysiadaj jeszcze, poczekaj chwilę."),
       ("Nie skręcaj jeszcze.", "skręcać", "Nie skręcaj jeszcze, poczekaj chwilę."),
       ("Nie zaczynaj jeszcze.", "zaczynać", "Nie zaczynaj jeszcze, poczekaj chwilę."),
       ("Nie jedz jeszcze.", "jeść", "Nie jedz jeszcze, poczekaj chwilę."),
       ("Nie pij jeszcze.", "pić", "Nie pij jeszcze, poczekaj chwilę."),
       ("Nie pokazuj im jeszcze.", "pokazać", "Nie pokazuj jeszcze, poczekaj chwilę."),
       ("Nie odpowiadaj jeszcze.", "odpowiadać", "Nie odpowiadaj jeszcze, poczekaj chwilę."),
       ("Nie pytaj go jeszcze.", "pytać", "Nie pytaj jeszcze, poczekaj chwilę."),
       ("Nie wybieraj jeszcze.", "wybierać", "Nie wybieraj jeszcze, poczekaj chwilę."),
       ("Nie rezerwuj jeszcze.", "rezerwować", "Nie rezerwuj jeszcze, poczekaj chwilę."),
       ("Nie wynajmuj jeszcze.", "wynajmować", "Nie wynajmuj jeszcze, poczekaj chwilę."),
       ("Nie pakuj się jeszcze.", "pakować się", "Nie pakuj się jeszcze, poczekaj chwilę."),
       ("Nie myj tego jeszcze.", "myć", "Nie myj tego jeszcze, poczekaj chwilę."),
       ("Nie pierz tego jeszcze.", "prać", "Nie pierz jeszcze, poczekaj chwilę."),
       ("Nie rób jeszcze zdjęć.", "robić zdjęcia", "Nie rób zdjęć jeszcze, poczekaj chwilę."),
       ("Nie próbuj jeszcze.", "próbować (smakować)", "Nie próbuj jeszcze, poczekaj chwilę."),
       ("Nie idź tam jeszcze.", "iść / jechać", "Nie idź jeszcze, poczekaj chwilę."),
       ("Nie wstawaj jeszcze.", "wstawać", "Nie wstawaj jeszcze, poczekaj chwilę."),
       ("Nie podchodź jeszcze.", "wchodzić", "Nie wchodź jeszcze, poczekaj chwilę."),
       ("Nie przesiadaj się jeszcze.", "przesiadać się", "Nie przesiadaj się jeszcze, poczekaj chwilę."),
       ("Nie licz jeszcze rachunku.", "policzyć rachunek", "Nie licz jeszcze, poczekaj chwilę."),
       ("Nie używaj tego jeszcze.", "używać", "Nie używaj jeszcze, poczekaj chwilę."),
     ]),

# =====================================================================
# thaa jam pen tawng … kaw phrawm — gotowosc warunkowa
# =====================================================================
dict(key="JAMPEN", ty="sentence", cat="Praca i nauka", sub="Deklaracje", reg="f",
     ph="thâa jam pen tâwng {ph} phǒm kâw phráwm khráp", th="ถ้าจำเป็นต้อง{th}ผมก็พร้อมครับ",
     lit="jam pen = konieczne; phráwm = gotowy",
     note="Deklaracja gotowości z zastrzeżeniem konieczności. Brzmi dojrzale i profesjonalnie — dobra odpowiedź na trudną prośbę szefa.",
     ex_ph="thâa jam pen tâwng {ph} khun phráwm mǎi khráp", ex_th="ถ้าจำเป็นต้อง{th}คุณพร้อมไหมครับ",
     items=[
       ("Jeśli będzie trzeba pracować dłużej, jestem gotów.", "pracować", "Jesteś gotów pracować dłużej, jeśli trzeba?"),
       ("Jeśli będzie trzeba wrócić, jestem gotów.", "wracać", "Jesteś gotów wrócić, jeśli trzeba?"),
       ("Jeśli będzie trzeba zapłacić, jestem gotów.", "płacić", "Jesteś gotów zapłacić, jeśli trzeba?"),
       ("Jeśli będzie trzeba podpisać, jestem gotów.", "podpisać", "Jesteś gotów podpisać, jeśli trzeba?"),
       ("Jeśli będzie trzeba pomóc, jestem gotów.", "pomagać", "Jesteś gotów pomóc, jeśli trzeba?"),
       ("Jeśli będzie trzeba czekać, jestem gotów.", "czekać", "Jesteś gotów czekać, jeśli trzeba?"),
       ("Jeśli będzie trzeba się uczyć od nowa, jestem gotów.", "uczyć się", "Jesteś gotów uczyć się od nowa?"),
       ("Jeśli będzie trzeba prowadzić, jestem gotów.", "prowadzić samochód", "Jesteś gotów prowadzić, jeśli trzeba?"),
       ("Jeśli będzie trzeba się przesiąść, jestem gotów.", "przesiadać się", "Jesteś gotów się przesiąść?"),
       ("Jeśli będzie trzeba coś zmienić, jestem gotów.", "zmieniać", "Jesteś gotów to zmienić, jeśli trzeba?"),
       ("Jeśli będzie trzeba anulować, jestem gotów.", "anulować", "Jesteś gotów anulować, jeśli trzeba?"),
       ("Jeśli będzie trzeba zadzwonić, jestem gotów.", "dzwonić", "Jesteś gotów zadzwonić, jeśli trzeba?"),
       ("Jeśli będzie trzeba coś wysłać, jestem gotów.", "wysyłać", "Jesteś gotów to wysłać, jeśli trzeba?"),
       ("Jeśli będzie trzeba wypełnić dokumenty, jestem gotów.", "wypełnić formularz", "Jesteś gotów wypełnić dokumenty?"),
       ("Jeśli będzie trzeba się spotkać osobiście, jestem gotów.", "spotykać", "Jesteś gotów spotkać się osobiście?"),
       ("Jeśli będzie trzeba wynająć coś innego, jestem gotów.", "wynajmować", "Jesteś gotów wynająć coś innego?"),
       ("Jeśli będzie trzeba tam pojechać, jestem gotów.", "iść / jechać", "Jesteś gotów tam pojechać?"),
       ("Jeśli będzie trzeba przyjść wcześniej, jestem gotów.", "przyjść / przyjechać", "Jesteś gotów przyjść wcześniej?"),
       ("Jeśli będzie trzeba to sprzedać, jestem gotów.", "sprzedawać", "Jesteś gotów to sprzedać?"),
       ("Jeśli będzie trzeba to kupić, jestem gotów.", "kupować", "Jesteś gotów to kupić?"),
       ("Jeśli będzie trzeba to naprawić, jestem gotów.", "naprawiać", "Jesteś gotów to naprawić?"),
       ("Jeśli będzie trzeba gotować dla wszystkich, jestem gotów.", "gotować", "Jesteś gotów gotować dla wszystkich?"),
       ("Jeśli będzie trzeba wcześniej wstać, jestem gotów.", "wstawać", "Jesteś gotów wstać wcześniej?"),
       ("Jeśli będzie trzeba zrezygnować z odpoczynku, jestem gotów.", "odpoczywać", "Jesteś gotów zrezygnować z odpoczynku?"),
       ("Jeśli będzie trzeba się spakować w godzinę, jestem gotów.", "pakować się", "Jesteś gotów spakować się w godzinę?"),
       ("Jeśli będzie trzeba jeszcze poszukać, jestem gotów.", "szukać", "Jesteś gotów jeszcze poszukać?"),
       ("Jeśli będzie trzeba zapytać przełożonego, jestem gotów.", "pytać", "Jesteś gotów zapytać przełożonego?"),
       ("Jeśli będzie trzeba odpowiedzieć na piśmie, jestem gotów.", "odpowiadać", "Jesteś gotów odpowiedzieć na piśmie?"),
       ("Jeśli będzie trzeba to pokazać, jestem gotów.", "pokazać", "Jesteś gotów to pokazać?"),
       ("Jeśli będzie trzeba przeczytać całość, jestem gotów.", "czytać", "Jesteś gotów przeczytać całość?"),
       ("Jeśli będzie trzeba napisać raport, jestem gotów.", "pisać", "Jesteś gotów napisać raport?"),
       ("Jeśli będzie trzeba tam iść pieszo, jestem gotów.", "iść pieszo", "Jesteś gotów iść pieszo?"),
       ("Jeśli będzie trzeba wcześniej wysiąść, jestem gotów.", "wysiadać", "Jesteś gotów wysiąść wcześniej?"),
       ("Jeśli będzie trzeba pożyczyć sprzęt, jestem gotów.", "pożyczyć", "Jesteś gotów pożyczyć sprzęt?"),
       ("Jeśli będzie trzeba zacząć od zera, jestem gotów.", "zaczynać", "Jesteś gotów zacząć od zera?"),
       ("Jeśli będzie trzeba przestać na jakiś czas, jestem gotów.", "przestać", "Jesteś gotów przestać na jakiś czas?"),
     ]),

# =====================================================================
# mai mii khwaam jam pen tawng … — brak koniecznosci
# =====================================================================
dict(key="MAIJAMPEN", ty="sentence", cat="Gramatyka użytkowa", sub="Wyjaśnianie", reg="f",
     ph="mâi mii khwaam jam pen tâwng {ph} khráp", th="ไม่มีความจำเป็นต้อง{th}ครับ",
     lit="mâi mii khwaam jam pen = nie ma konieczności",
     note="Formalne zdjęcie obowiązku. W mowie codziennej to samo powiesz krócej: „mâi tâwng … kâw dâai”.",
     ex_ph="jing jing mâi mii khwaam jam pen tâwng {ph} loei khráp", ex_th="จริงๆ ไม่มีความจำเป็นต้อง{th}เลยครับ",
     items=[
       ("Nie ma konieczności, żeby płacić z góry.", "płacić", "Naprawdę nie ma konieczności płacić."),
       ("Nie ma konieczności, żeby czekać na miejscu.", "czekać", "Naprawdę nie ma konieczności czekać."),
       ("Nie ma konieczności, żeby przychodzić osobiście.", "przyjść / przyjechać", "Naprawdę nie ma konieczności przychodzić."),
       ("Nie ma konieczności, żeby dzwonić.", "dzwonić", "Naprawdę nie ma konieczności dzwonić."),
       ("Nie ma konieczności, żeby to podpisywać.", "podpisać", "Naprawdę nie ma konieczności podpisywać."),
       ("Nie ma konieczności, żeby wypełniać formularz.", "wypełnić formularz", "Naprawdę nie ma konieczności wypełniać."),
       ("Nie ma konieczności, żeby rezerwować.", "rezerwować", "Naprawdę nie ma konieczności rezerwować."),
       ("Nie ma konieczności, żeby to zmieniać.", "zmieniać", "Naprawdę nie ma konieczności zmieniać."),
       ("Nie ma konieczności, żeby wracać dziś.", "wracać", "Naprawdę nie ma konieczności wracać."),
       ("Nie ma konieczności, żeby to kupować.", "kupować", "Naprawdę nie ma konieczności kupować."),
       ("Nie ma konieczności, żeby pytać kierownika.", "pytać", "Naprawdę nie ma konieczności pytać."),
       ("Nie ma konieczności, żeby się spieszyć z odpowiedzią.", "odpowiadać", "Naprawdę nie ma konieczności odpowiadać."),
       ("Nie ma konieczności, żeby to wysyłać pocztą.", "wysyłać", "Naprawdę nie ma konieczności wysyłać."),
       ("Nie ma konieczności, żeby to pokazywać.", "pokazać", "Naprawdę nie ma konieczności pokazywać."),
       ("Nie ma konieczności, żeby wszystko czytać.", "czytać", "Naprawdę nie ma konieczności czytać."),
       ("Nie ma konieczności, żeby to zapisywać.", "pisać", "Naprawdę nie ma konieczności zapisywać."),
       ("Nie ma konieczności, żeby to pamiętać na pamięć.", "pamiętać", "Naprawdę nie ma konieczności pamiętać."),
       ("Nie ma konieczności, żeby brać dodatkowe rzeczy.", "brać", "Naprawdę nie ma konieczności brać."),
       ("Nie ma konieczności, żeby wynajmować samochód.", "wynajmować", "Naprawdę nie ma konieczności wynajmować."),
       ("Nie ma konieczności, żeby anulować.", "anulować", "Naprawdę nie ma konieczności anulować."),
       ("Nie ma konieczności, żeby się przesiadać.", "przesiadać się", "Naprawdę nie ma konieczności przesiadać się."),
       ("Nie ma konieczności, żeby iść pieszo.", "iść pieszo", "Naprawdę nie ma konieczności iść pieszo."),
       ("Nie ma konieczności, żeby to prać osobno.", "prać", "Naprawdę nie ma konieczności prać osobno."),
       ("Nie ma konieczności, żeby to myć teraz.", "myć", "Naprawdę nie ma konieczności myć teraz."),
       ("Nie ma konieczności, żeby gotować dla mnie.", "gotować", "Naprawdę nie ma konieczności gotować."),
       ("Nie ma konieczności, żeby mi pomagać.", "pomagać", "Naprawdę nie ma konieczności pomagać."),
       ("Nie ma konieczności, żeby zaczynać od nowa.", "zaczynać", "Naprawdę nie ma konieczności zaczynać."),
       ("Nie ma konieczności, żeby tego szukać dalej.", "szukać", "Naprawdę nie ma konieczności szukać."),
       ("Nie ma konieczności, żeby to sprzedawać.", "sprzedawać", "Naprawdę nie ma konieczności sprzedawać."),
       ("Nie ma konieczności, żeby wstawać wcześnie.", "wstawać", "Naprawdę nie ma konieczności wstawać wcześnie."),
       ("Nie ma konieczności, żeby to naprawiać samemu.", "naprawiać", "Naprawdę nie ma konieczności naprawiać."),
       ("Nie ma konieczności, żeby się przebierać.", "ubierać się", "Naprawdę nie ma konieczności się przebierać."),
       ("Nie ma konieczności, żeby sprzątać przed wyjazdem.", "sprzątać", "Naprawdę nie ma konieczności sprzątać."),
       ("Nie ma konieczności, żeby to zamawiać z wyprzedzeniem.", "zamawiać", "Naprawdę nie ma konieczności zamawiać."),
       ("Nie ma konieczności, żeby to przymierzać.", "przymierzać / próbować", "Naprawdę nie ma konieczności przymierzać."),
       ("Nie ma konieczności, żeby robić zdjęcia dokumentów.", "robić zdjęcia", "Naprawdę nie ma konieczności robić zdjęć."),
     ]),

# =====================================================================
# kueap ja … yuu laew — czynnosc o wlos niedokonana
# =====================================================================
dict(key="KUEAPJA", ty="sentence", cat="Gramatyka użytkowa", sub="Przeszłość", reg="n",
     ph="phǒm kùeap jà {ph} yùu láew khráp", th="ผมเกือบจะ{th}อยู่แล้วครับ",
     lit="kùeap jà … yùu láew = o mało co, jeszcze chwila i by się stało",
     note="Konstrukcja o czynności, która prawie się wydarzyła. Sam „kùeap” bez „yùu láew” brzmi jak zwykłe „prawie”, bez dramatyzmu.",
     ex_ph="khun kùeap jà {ph} yùu láew rǒe khráp", ex_th="คุณเกือบจะ{th}อยู่แล้วหรือครับ",
     items=[
       ("O mało co bym nie zapomniał.", "zapominać", "O mało co byś nie zapomniał?"),
       ("O mało co bym się nie spóźnił z powrotem.", "wracać", "O mało co byś nie wrócił za późno?"),
       ("O mało co bym tego nie zgubił.", "zgubić", "O mało co byś tego nie zgubił?"),
       ("O mało co bym nie zasnął.", "spać", "O mało co byś nie zasnął?"),
       ("O mało co bym nie zapłacił dwa razy.", "płacić", "O mało co byś nie zapłacił dwa razy?"),
       ("O mało co bym tego nie kupił.", "kupować", "O mało co byś tego nie kupił?"),
       ("O mało co bym tego nie podpisał.", "podpisać", "O mało co byś tego nie podpisał?"),
       ("O mało co bym nie anulował rezerwacji.", "anulować", "O mało co byś nie anulował?"),
       ("O mało co bym nie wysiadł na złym przystanku.", "wysiadać", "O mało co byś nie wysiadł źle?"),
       ("O mało co bym nie wsiadł do złego autobusu.", "wsiadać", "O mało co byś nie wsiadł źle?"),
       ("O mało co bym nie skręcił w złą uliczkę.", "skręcać", "O mało co byś nie skręcił źle?"),
       ("O mało co bym nie wysłał tego do wszystkich.", "wysyłać", "O mało co byś nie wysłał do wszystkich?"),
       ("O mało co bym nie zadzwonił w środku nocy.", "dzwonić", "O mało co byś nie zadzwonił w nocy?"),
       ("O mało co bym nie odpowiedział zbyt ostro.", "odpowiadać", "O mało co byś nie odpowiedział ostro?"),
       ("O mało co bym tego nie sprzedał za bezcen.", "sprzedawać", "O mało co byś tego nie sprzedał?"),
       ("O mało co bym nie zamówił czegoś innego.", "zamawiać", "O mało co byś nie zamówił inaczej?"),
       ("O mało co bym nie zaczął bez ciebie.", "zaczynać", "O mało co byś nie zaczął beze mnie?"),
       ("O mało co bym nie przestał się uczyć.", "przestać", "O mało co byś nie przestał?"),
       ("O mało co bym nie wyszedł bez kluczy.", "wychodzić", "O mało co byś nie wyszedł bez kluczy?"),
       ("O mało co bym nie zamknął drzwi na klucz.", "zamykać", "O mało co byś nie zamknął?"),
       ("O mało co bym nie zapomniał się spakować.", "pakować się", "O mało co byś się nie spakował?"),
       ("O mało co bym nie oddał tego komuś.", "dawać", "O mało co byś tego nie oddał?"),
       ("O mało co bym nie przegapił spotkania.", "spotykać", "O mało co byś nie przegapił spotkania?"),
       ("O mało co bym nie wynajął tego mieszkania.", "wynajmować", "O mało co byś tego nie wynajął?"),
       ("O mało co bym się nie przesiadł za wcześnie.", "przesiadać się", "O mało co byś się nie przesiadł źle?"),
       ("O mało co bym nie pojechał tam na darmo.", "iść / jechać", "O mało co byś nie pojechał na darmo?"),
       ("O mało co bym tego nie użył bez zgody.", "używać", "O mało co byś tego nie użył?"),
       ("O mało co bym tego nie wypił.", "pić", "O mało co byś tego nie wypił?"),
       ("O mało co bym tego nie zjadł.", "jeść", "O mało co byś tego nie zjadł?"),
       ("O mało co bym się nie obudził za późno.", "budzić się", "O mało co byś się nie obudził za późno?"),
       ("O mało co bym nie przegapił terminu rezerwacji.", "rezerwować", "O mało co byś nie przegapił rezerwacji?"),
       ("O mało co bym tego nie pożyczył.", "pożyczyć", "O mało co byś tego nie pożyczył?"),
       ("O mało co bym tego nie znalazł za późno.", "znaleźć", "O mało co byś tego nie znalazł?"),
       ("O mało co bym nie wypełnił złego formularza.", "wypełnić formularz", "O mało co byś nie wypełnił złego?"),
       ("O mało co bym nie pokazał tego wszystkim.", "pokazać", "O mało co byś tego nie pokazał?"),
       ("O mało co bym nie wybrał gorszej opcji.", "wybierać", "O mało co byś nie wybrał gorzej?"),
     ]),
]
