# -*- coding: utf-8 -*-
"""Leksyka etapu 5 (B2) — czesc B.

Zakres: subtelnosci grzecznosci. Prosby, odmowy i sugestie ulozone wedlug
stopnia uprzejmosci — od komendy po formule urzedowa. Kazdy rekord ma w polu
notes informacje, wobec kogo tej formy uzywac, a wobec kogo nie.

Format jak w lex_b2_core_a.py.
"""

CORE_B = [

# =====================================================================
# PROSBY — OD NAJMOCNIEJSZEJ DO NAJDELIKATNIEJSZEJ
# =====================================================================
("zrób to", "tham loei", "ทำเลย", "Podstawy i grzeczność", "Prośby stopniowane", "phrase", 3, "p",
 "Najniższy stopień: rozkaz bez partykuły. Dopuszczalny tylko wobec bliskich rówieśników albo w nagłym zagrożeniu.", "",
 ("Zrób to teraz, nie ma czasu.", "tham loei mâi mii wee-laa láew", "ทำเลย ไม่มีเวลาแล้ว")),
("zrób to, dobrze?", "tham nòi ná", "ทำหน่อยนะ", "Podstawy i grzeczność", "Prośby stopniowane", "phrase", 5, "i",
 "„nòi ná” zmiękcza polecenie do prośby koleżeńskiej. Wobec obcego wciąż za mało.", "",
 ("Zrób to do wieczora, dobrze?", "tham hâi sèt tawn yen nòi ná", "ทำให้เสร็จตอนเย็นหน่อยนะ")),
("możesz to zrobić?", "tham hâi nòi dâai mǎi", "ทำให้หน่อยได้ไหม", "Podstawy i grzeczność", "Prośby stopniowane", "sentence", 5, "n",
 "Pytanie zamiast polecenia. Standard w rozmowie z kolegą z pracy.", "",
 ("Możesz to zrobić przed spotkaniem?", "tham hâi nòi dâai mǎi kàwn prà-chum", "ทำให้หน่อยได้ไหมก่อนประชุม")),
("czy mógłbyś mi pomóc?", "chûai phǒm nòi dâai mǎi khráp", "ช่วยผมหน่อยได้ไหมครับ",
 "Podstawy i grzeczność", "Prośby stopniowane", "sentence", 5, "n", "", "",
 ("Czy mógłbyś mi pomóc z tym formularzem?", "chûai phǒm rûeang bàep fawm níi nòi dâai mǎi khráp", "ช่วยผมเรื่องแบบฟอร์มนี้หน่อยได้ไหมครับ")),
("byłbym wdzięczny, gdybyś mógł", "thâa chûai dâai jà khàwp-khun mâak khráp", "ถ้าช่วยได้จะขอบคุณมากครับ",
 "Podstawy i grzeczność", "Prośby stopniowane", "sentence", 4, "f",
 "Warunek plus podziękowanie z góry. Zostawia rozmówcy wyjście, więc wypada bardzo dobrze.", "",
 ("Byłbym wdzięczny, gdybyś mógł to sprawdzić dzisiaj.", "thâa chûai chék hâi wan níi dâai jà khàwp-khun mâak khráp", "ถ้าช่วยเช็คให้วันนี้ได้จะขอบคุณมากครับ")),
("chciałbym prosić o przysługę", "khǎw róp-kuan nòi dâai mǎi khráp", "ขอรบกวนหน่อยได้ไหมครับ",
 "Podstawy i grzeczność", "Prośby stopniowane", "sentence", 5, "f",
 "„róp-kuan” dosłownie „zakłócam spokój” — sama formuła już przeprasza za kłopot.", "prosić o zakłócenie",
 ("Chciałbym prosić o przysługę, jeśli to możliwe.", "khǎw róp-kuan nòi dâai mǎi khráp thâa mâi lam-bàak koen pai", "ขอรบกวนหน่อยได้ไหมครับ ถ้าไม่ลำบากเกินไป")),
("jeśli to nie kłopot", "thâa mâi lam-bàak koen pai", "ถ้าไม่ลำบากเกินไป", "Podstawy i grzeczność", "Prośby stopniowane", "phrase", 4, "f",
 "Dodatek podnoszący każdą prośbę o jeden stopień. Można doczepić na końcu dowolnego zdania.", "",
 ("Jeśli to nie kłopot, poproszę o kopię.", "thâa mâi lam-bàak koen pai khǎw sǎm-nao dûai khráp", "ถ้าไม่ลำบากเกินไป ขอสำเนาด้วยครับ")),
("wiem, że jesteś zajęty, ale", "rúu wâa yûng yùu khráp tàae wâa", "รู้ว่ายุ่งอยู่ครับ แต่ว่า",
 "Podstawy i grzeczność", "Prośby stopniowane", "phrase", 4, "n",
 "Uznanie cudzego czasu przed prośbą. W tajskim biurze niemal obowiązkowe.", "",
 ("Wiem, że jesteś zajęty, ale to zajmie minutę.", "rúu wâa yûng yùu khráp tàae wâa chái wee-laa khâe naa-thii diao", "รู้ว่ายุ่งอยู่ครับ แต่ว่าใช้เวลาแค่นาทีเดียว")),
("czy byłoby możliwe, żeby", "jà pen pai dâai mǎi khráp thîi jà", "จะเป็นไปได้ไหมครับที่จะ",
 "Praca i nauka", "Prośby stopniowane", "phrase", 3, "f",
 "Najwyższy rejestr prośby w rozmowie. W piśmie urzędowym zamiast tego pisze się „khǎw khwaam à-nú-khráw”.", "",
 ("Czy byłoby możliwe, żeby przesunąć termin?", "jà pen pai dâai mǎi khráp thîi jà lûean kam-nòt", "จะเป็นไปได้ไหมครับที่จะเลื่อนกำหนด")),
("z góry dziękuję", "khàwp-khun lûang nâa khráp", "ขอบคุณล่วงหน้าครับ", "Podstawy i grzeczność", "Prośby stopniowane", "phrase", 4, "f",
 "Kończy prośbę pisemną. W rozmowie brzmi lekko naciskająco — lepiej podziękować po fakcie.", "",
 ("Z góry dziękuję za pomoc.", "khàwp-khun lûang nâa sǎm-ràp khwaam chûai lǔea khráp", "ขอบคุณล่วงหน้าสำหรับความช่วยเหลือครับ")),
("nie śpieszy się", "mâi rîip khráp tham mûea wâang", "ไม่รีบครับ ทำเมื่อว่าง",
 "Podstawy i grzeczność", "Prośby stopniowane", "sentence", 5, "n",
 "Zdejmuje presję z rozmówcy. Bardzo dobrze odbierane, bo szanuje jego harmonogram.", "",
 ("Nie śpieszy się, zrób jak będziesz miał czas.", "mâi rîip khráp wâang mûea rài kâw tham", "ไม่รีบครับ ว่างเมื่อไหร่ก็ทำ")),
("byłoby idealnie, gdyby", "thâa dâai kâw jà dii mâak khráp", "ถ้าได้ก็จะดีมากครับ",
 "Podstawy i grzeczność", "Prośby stopniowane", "phrase", 4, "n", "", "",
 ("Byłoby idealnie, gdyby udało się do piątku.", "thâa dâai kàwn wan sùk kâw jà dii mâak khráp", "ถ้าได้ก่อนวันศุกร์ก็จะดีมากครับ")),
("mam prośbę nie na temat", "khǎw thǎam nâwk rûeang nòi khráp", "ขอถามนอกเรื่องหน่อยครับ",
 "Small talk", "Prośby stopniowane", "sentence", 3, "n", "", "",
 ("Mam prośbę nie na temat — masz ładowarkę?", "khǎw thǎam nâwk rûeang nòi khráp mii thîi chaat mǎi", "ขอถามนอกเรื่องหน่อยครับ มีที่ชาร์จไหม")),

# =====================================================================
# ODMOWY — OD NAJLAGODNIEJSZEJ DO STANOWCZEJ
# =====================================================================
("chyba nie dam rady", "khong mâi wǎai khráp", "คงไม่ไหวครับ", "Podstawy i grzeczność", "Odmowy stopniowane", "sentence", 5, "n",
 "„khong” osłabia odmowę do przypuszczenia. Tajski standard: nigdy nie odmawiaj wprost.", "chyba nie wytrzymam",
 ("Chyba nie dam rady w ten weekend.", "sǎo aa-thít níi khong mâi wǎai khráp", "เสาร์อาทิตย์นี้คงไม่ไหวครับ")),
("muszę sprawdzić kalendarz", "khǎw duu taa-raang kàwn ná khráp", "ขอดูตารางก่อนนะครับ",
 "Podstawy i grzeczność", "Odmowy stopniowane", "sentence", 5, "n",
 "Odmowa odroczona. Bardzo częsty tajski sposób na uniknięcie bezpośredniego „nie”.", "",
 ("Muszę sprawdzić kalendarz, odezwę się wieczorem.", "khǎw duu taa-raang kàwn ná khráp dǐao yen bàwk", "ขอดูตารางก่อนนะครับ เดี๋ยวเย็นบอก")),
("w tym tygodniu raczej nie", "aa-thít níi khong yâak nòi khráp", "อาทิตย์นี้คงยากหน่อยครับ",
 "Podstawy i grzeczność", "Odmowy stopniowane", "sentence", 4, "n",
 "„yâak” = trudne. Tajowie mówią „trudno” tam, gdzie Polak powiedziałby „nie”.", "będzie trochę trudno",
 ("W tym tygodniu raczej nie, może w przyszłym.", "aa-thít níi khong yâak nòi khráp aa-thít nâa àat jà dâai", "อาทิตย์นี้คงยากหน่อยครับ อาทิตย์หน้าอาจจะได้")),
("bardzo bym chciał, ale nie mogę", "yàak pai mâak khráp tàae tìt thù-rá", "อยากไปมากครับ แต่ติดธุระ",
 "Podstawy i grzeczność", "Odmowy stopniowane", "sentence", 5, "n",
 "„tìt thù-rá” = mam sprawę do załatwienia. Uniwersalny, nieinwazyjny powód odmowy.", "utknąłem przy sprawie",
 ("Bardzo bym chciał, ale mam już coś umówione.", "yàak pai mâak khráp tàae tìt thù-rá wái láew", "อยากไปมากครับ แต่ติดธุระไว้แล้ว")),
("może innym razem", "wái oo-kàat nâa ná khráp", "ไว้โอกาสหน้านะครับ", "Podstawy i grzeczność", "Odmowy stopniowane", "phrase", 5, "n",
 "Zamyka odmowę na przyjaznej nucie i zostawia relację otwartą.", "zostawmy na następną okazję",
 ("Może innym razem, dziś nie wyjdzie.", "wái oo-kàat nâa ná khráp wan níi khong mâi wǎai", "ไว้โอกาสหน้านะครับ วันนี้คงไม่ไหว")),
("przykro mi, ale muszę odmówić", "khǎw-thôot khráp khráng níi khǎw phàan", "ขอโทษครับ ครั้งนี้ขอผ่าน",
 "Podstawy i grzeczność", "Odmowy stopniowane", "sentence", 4, "n",
 "„khǎw phàan” = pasuję, odpuszczam tę rundę. Jasne, ale nie szorstkie.", "proszę przepuścić",
 ("Przykro mi, ale muszę odmówić tej propozycji.", "khǎw-thôot khráp khâw sà-nǒoe níi khǎw phàan", "ขอโทษครับ ข้อเสนอนี้ขอผ่าน")),
("nie mogę tego obiecać", "phǒm rap paak mâi dâai khráp", "ผมรับปากไม่ได้ครับ",
 "Praca i nauka", "Odmowy stopniowane", "sentence", 4, "n",
 "„rap paak” = dać słowo. W Tajlandii dane słowo waży dużo, więc lepiej go nie dawać na wyrost.", "przyjąć ustami",
 ("Nie mogę tego obiecać, ale spróbuję.", "phǒm rap paak mâi dâai khráp tàae jà phá-yaa-yaam", "ผมรับปากไม่ได้ครับ แต่จะพยายาม")),
("to niestety niemożliwe", "khǎw-thôot khráp an níi tham mâi dâai jing jing", "ขอโทษครับ อันนี้ทำไม่ได้จริงๆ",
 "Praca i nauka", "Odmowy stopniowane", "sentence", 4, "f",
 "Stanowcza odmowa z przeprosinami. Bez „khǎw-thôot” zabrzmi jak zatrzaśnięcie drzwi.", "",
 ("To niestety niemożliwe, taka jest procedura.", "khǎw-thôot khráp an níi tham mâi dâai jing jing pen kót", "ขอโทษครับ อันนี้ทำไม่ได้จริงๆ เป็นกฎ")),
("nie jestem osobą, która o tym decyduje", "phǒm mâi mii àm-nâat tàt-sǐn jai khráp", "ผมไม่มีอำนาจตัดสินใจครับ",
 "Praca i nauka", "Odmowy stopniowane", "sentence", 4, "f",
 "Odmowa przez wskazanie kompetencji. Zdejmuje z ciebie odpowiedzialność, nie obrażając nikogo.", "",
 ("Nie jestem osobą, która o tym decyduje, przekażę wyżej.", "phǒm mâi mii àm-nâat tàt-sǐn jai khráp dǐao sòng tàw hâi", "ผมไม่มีอำนาจตัดสินใจครับ เดี๋ยวส่งต่อให้")),
("wolałbym nie", "khǎw mâi dii kwàa khráp", "ขอไม่ดีกว่าครับ", "Podstawy i grzeczność", "Odmowy stopniowane", "sentence", 4, "n", "", "",
 ("Wolałbym nie, nie czuję się na siłach.", "khǎw mâi dii kwàa khráp phǒm mâi phráwm", "ขอไม่ดีกว่าครับ ผมไม่พร้อม")),
("dziękuję, ale nie skorzystam", "khàwp-khun khráp tàae khǎw phàan khráng níi", "ขอบคุณครับ แต่ขอผ่านครั้งนี้",
 "Podstawy i grzeczność", "Odmowy stopniowane", "sentence", 4, "n", "", "",
 ("Dziękuję, ale nie skorzystam, mam już taki.", "khàwp-khun khráp tàae khǎw phàan mii yùu láew", "ขอบคุณครับ แต่ขอผ่าน มีอยู่แล้ว")),
("nie mam nic przeciwko, ale nie teraz", "mâi wâa à-rai khráp tàae mâi châi tawn níi", "ไม่ว่าอะไรครับ แต่ไม่ใช่ตอนนี้",
 "Podstawy i grzeczność", "Odmowy stopniowane", "sentence", 3, "n", "", "",
 ("Nie mam nic przeciwko, ale nie teraz, jestem w pracy.", "mâi wâa à-rai khráp tàae mâi châi tawn níi phǒm yùu thîi tham-ngaan", "ไม่ว่าอะไรครับ แต่ไม่ใช่ตอนนี้ ผมอยู่ที่ทำงาน")),
("nie chcę składać obietnic bez pokrycia", "phǒm mâi yàak rap paak láew tham mâi dâai khráp", "ผมไม่อยากรับปากแล้วทำไม่ได้ครับ",
 "Praca i nauka", "Odmowy stopniowane", "sentence", 3, "f", "", "",
 ("Nie chcę składać obietnic bez pokrycia, wolę powiedzieć wprost.", "phǒm mâi yàak rap paak láew tham mâi dâai khráp bàwk trong trong dii kwàa", "ผมไม่อยากรับปากแล้วทำไม่ได้ครับ บอกตรงๆ ดีกว่า")),
("musiałbym się wycofać", "khǎw thǎwn tua khráp", "ขอถอนตัวครับ", "Praca i nauka", "Odmowy stopniowane", "sentence", 3, "f",
 "„thǎwn tua” = wycofać się z projektu, zespołu, umowy. Rejestr oficjalny.", "wyciągnąć ciało",
 ("Musiałbym się wycofać z tego projektu.", "phǒm khǎw thǎwn tua jàak proo-jèk níi khráp", "ผมขอถอนตัวจากโปรเจกต์นี้ครับ")),
("odmawiam, ale bez urazy", "khǎw mâi ráp ná khráp tàae mâi dâai thǔe sǎa", "ขอไม่รับนะครับ แต่ไม่ได้ถือสา",
 "Podstawy i grzeczność", "Odmowy stopniowane", "sentence", 3, "n",
 "„thǔe sǎa” = brać do siebie, chować urazę. Zwrot rozbraja napięcie po odmowie.", "",
 ("Odmawiam, ale bez urazy, wciąż jesteśmy w kontakcie.", "khǎw mâi ráp ná khráp tàae mâi dâai thǔe sǎa yang khui kan dâai", "ขอไม่รับนะครับ แต่ไม่ได้ถือสา ยังคุยกันได้")),

# =====================================================================
# SUGESTIE O ROZNEJ SILE
# =====================================================================
("może spróbujemy inaczej?", "lawng ìik bàep dii mǎi khráp", "ลองอีกแบบดีไหมครับ",
 "Praca i nauka", "Sugestie", "sentence", 5, "n", "", "",
 ("Może spróbujemy inaczej, ten sposób nie działa.", "lawng ìik bàep dii mǎi khráp bàep níi mâi wôek", "ลองอีกแบบดีไหมครับ แบบนี้ไม่เวิร์ก")),
("a gdybyśmy tak", "thâa raw jà", "ถ้าเราจะ", "Praca i nauka", "Sugestie", "phrase", 4, "n", "", "",
 ("A gdybyśmy tak przesunęli to na poniedziałek?", "thâa raw jà lûean pen wan jan lâ khráp", "ถ้าเราจะเลื่อนเป็นวันจันทร์ล่ะครับ")),
("proponuję, żebyśmy", "phǒm khǎw sà-nǒoe wâa raw khuan", "ผมขอเสนอว่าเราควร", "Praca i nauka", "Sugestie", "phrase", 4, "f",
 "„sà-nǒoe” = złożyć propozycję. Na zebraniu brzmi kompetentnie, w barze — sztywno.", "",
 ("Proponuję, żebyśmy zebrali dane przed decyzją.", "phǒm khǎw sà-nǒoe wâa raw khuan kèp khâw-muun kàwn tàt-sǐn jai khráp", "ผมขอเสนอว่าเราควรเก็บข้อมูลก่อนตัดสินใจครับ")),
("na twoim miejscu bym poczekał", "thâa pen phǒm phǒm jà raw kàwn khráp", "ถ้าเป็นผมผมจะรอก่อนครับ",
 "Cechy i opinie", "Sugestie", "sentence", 4, "n", "", "",
 ("Na twoim miejscu bym poczekał do końca miesiąca.", "thâa pen phǒm phǒm jà raw thǔeng sîn duean khráp", "ถ้าเป็นผมผมจะรอถึงสิ้นเดือนครับ")),
("warto by rozważyć", "nâa jà phí-jaa-rá-naa duu khráp", "น่าจะพิจารณาดูครับ", "Praca i nauka", "Sugestie", "phrase", 3, "f",
 "„phí-jaa-rá-naa” = rozpatrzyć. Słowo urzędowe, spotkasz je na każdym piśmie z urzędu.", "",
 ("Warto by rozważyć tańszy wariant.", "nâa jà phí-jaa-rá-naa bàep thîi thùuk kwàa duu khráp", "น่าจะพิจารณาแบบที่ถูกกว่าดูครับ")),
("radzę zrobić to wcześniej", "náe-nam hâi tham lûang nâa khráp", "แนะนำให้ทำล่วงหน้าครับ",
 "Praca i nauka", "Sugestie", "sentence", 4, "n", "", "",
 ("Radzę zrobić to wcześniej, kolejki są długie.", "náe-nam hâi tham lûang nâa khráp khon yóe mâak", "แนะนำให้ทำล่วงหน้าครับ คนเยอะมาก")),
("lepiej tego nie robić", "mâi tham dii kwàa khráp", "ไม่ทำดีกว่าครับ", "Cechy i opinie", "Sugestie", "sentence", 4, "n", "", "",
 ("Lepiej tego nie robić bez zgody właściciela.", "mâi tham dii kwàa khráp thâa jâo khǎwng yang mâi à-nú-yâat", "ไม่ทำดีกว่าครับ ถ้าเจ้าของยังไม่อนุญาต")),
("na twoim miejscu bym się nie zgodził", "thâa pen phǒm phǒm khong mâi tòk long khráp", "ถ้าเป็นผมผมคงไม่ตกลงครับ",
 "Cechy i opinie", "Sugestie", "sentence", 3, "n", "", "",
 ("Na twoim miejscu bym się nie zgodził na te warunki.", "thâa pen phǒm phǒm khong mâi tòk long kàp ngûean-khǎi níi khráp", "ถ้าเป็นผมผมคงไม่ตกลงกับเงื่อนไขนี้ครับ")),
("zdecydowanie odradzam", "mâi náe-nam loei khráp", "ไม่แนะนำเลยครับ", "Cechy i opinie", "Sugestie", "sentence", 4, "n",
 "Mocna rada. „loei” po przeczeniu wzmacnia je do kategorycznego.", "",
 ("Zdecydowanie odradzam ten warsztat.", "ùu níi mâi náe-nam loei khráp", "อู่นี้ไม่แนะนำเลยครับ")),
("to tylko luźna myśl", "pen khâe khwaam khít loi loi khráp", "เป็นแค่ความคิดลอยๆ ครับ",
 "Cechy i opinie", "Sugestie", "sentence", 3, "n",
 "„loi loi” = unoszący się, niezobowiązujący. Osłabia propozycję, żeby nikt nie poczuł nacisku.", "myśl unosząca się",
 ("To tylko luźna myśl, nie traktuj poważnie.", "pen khâe khwaam khít loi loi khráp yàa sîi-ri-át mâak", "เป็นแค่ความคิดลอยๆ ครับ อย่าซีเรียสมาก")),
("zostawiam decyzję tobie", "láew tàae khun tàt-sǐn jai khráp", "แล้วแต่คุณตัดสินใจครับ",
 "Praca i nauka", "Sugestie", "sentence", 4, "n", "", "",
 ("Zostawiam decyzję tobie, oba warianty są dobre.", "láew tàae khun tàt-sǐn jai khráp dii thâng sǎwng bàep", "แล้วแต่คุณตัดสินใจครับ ดีทั้งสองแบบ")),
("jak wolisz", "taam sà-baai khráp", "ตามสบายครับ", "Podstawy i grzeczność", "Sugestie", "phrase", 5, "n",
 "Dosłownie „jak ci wygodnie”. Uniwersalna, ciepła zgoda na cudzy wybór.", "według wygody",
 ("Jak wolisz, mnie pasuje każda opcja.", "taam sà-baai khráp phǒm dâai thúk bàep", "ตามสบายครับ ผมได้ทุกแบบ")),
("nie nalegam", "mâi bang-kháp khráp", "ไม่บังคับครับ", "Podstawy i grzeczność", "Sugestie", "phrase", 4, "n", "", "",
 ("Nie nalegam, po prostu podrzucam pomysł.", "mâi bang-kháp khráp khâe sà-nǒoe duu chǒoei chǒoei", "ไม่บังคับครับ แค่เสนอดูเฉยๆ")),
("pomyśl o tym spokojnie", "khôi khít duu ná khráp mâi tâwng rîip", "ค่อยคิดดูนะครับ ไม่ต้องรีบ",
 "Podstawy i grzeczność", "Sugestie", "sentence", 4, "n", "", "",
 ("Pomyśl o tym spokojnie i daj znać w tygodniu.", "khôi khít duu ná khráp láew bàwk phaai-nai aa-thít níi", "ค่อยคิดดูนะครับ แล้วบอกภายในอาทิตย์นี้")),

# =====================================================================
# LAGODZENIE I ZMIEKCZANIE
# =====================================================================
("trochę mi to nie pasuje", "man mâi khâwi sà-dùak khráp", "มันไม่ค่อยสะดวกครับ",
 "Podstawy i grzeczność", "Łagodzenie", "sentence", 5, "n",
 "„mâi sà-dùak” = niewygodnie mi. Najbezpieczniejszy sposób na zgłoszenie problemu.", "",
 ("Trochę mi to nie pasuje godzinowo.", "wee-laa níi man mâi khâwi sà-dùak khráp", "เวลานี้มันไม่ค่อยสะดวกครับ")),
("możliwe, że się nie zrozumieliśmy", "raw àat jà khâo-jai mâi trong kan khráp", "เราอาจจะเข้าใจไม่ตรงกันครับ",
 "Praca i nauka", "Łagodzenie", "sentence", 4, "n",
 "„khâo-jai mâi trong kan” = rozminięcie się w rozumieniu. Nikogo nie obwinia, więc rozbraja spór.", "",
 ("Możliwe, że się nie zrozumieliśmy co do terminu.", "rûeang wan raw àat jà khâo-jai mâi trong kan khráp", "เรื่องวันเราอาจจะเข้าใจไม่ตรงกันครับ")),
("nie chcę, żebyś źle to odebrał", "mâi yàak hâi khun khít mâak ná khráp", "ไม่อยากให้คุณคิดมากนะครับ",
 "Podstawy i grzeczność", "Łagodzenie", "sentence", 4, "n",
 "„khít mâak” = rozmyślać nadmiernie, brać do siebie. Bardzo częste słowo w rozmowach o emocjach.", "",
 ("Nie chcę, żebyś źle to odebrał, mówię życzliwie.", "mâi yàak hâi khun khít mâak ná khráp phǒm phûut dûai khwaam pràat-thà-nǎa dii", "ไม่อยากให้คุณคิดมากนะครับ ผมพูดด้วยความปรารถนาดี")),
("mówię to z życzliwości", "phûut dûai khwaam pràat-thà-nǎa dii khráp", "พูดด้วยความปรารถนาดีครับ",
 "Podstawy i grzeczność", "Łagodzenie", "sentence", 3, "f", "", "",
 ("Mówię to z życzliwości, nie żeby krytykować.", "phûut dûai khwaam pràat-thà-nǎa dii khráp mâi dâai tì", "พูดด้วยความปรารถนาดีครับ ไม่ได้ติ")),
("bez urazy", "yàa thǔe sǎa ná khráp", "อย่าถือสานะครับ", "Podstawy i grzeczność", "Łagodzenie", "phrase", 4, "n", "", "",
 ("Bez urazy, ale to było nieprofesjonalne.", "yàa thǔe sǎa ná khráp tàae an nán mâi mûu aa-chîip", "อย่าถือสานะครับ แต่อันนั้นไม่มืออาชีพ")),
("może to moja wina", "àat jà pen thîi phǒm eeng kâw dâai khráp", "อาจจะเป็นที่ผมเองก็ได้ครับ",
 "Podstawy i grzeczność", "Łagodzenie", "sentence", 4, "n",
 "Wzięcie części winy na siebie otwiera rozmówcę. To fundament tajskiego rozwiązywania sporów.", "",
 ("Może to moja wina, źle zapisałem termin.", "àat jà pen thîi phǒm eeng kâw dâai khráp phǒm jòt wan phìt", "อาจจะเป็นที่ผมเองก็ได้ครับ ผมจดวันผิด")),
("nie robię z tego problemu", "phǒm mâi dâai tham hâi pen rûeang yài khráp", "ผมไม่ได้ทำให้เป็นเรื่องใหญ่ครับ",
 "Podstawy i grzeczność", "Łagodzenie", "sentence", 3, "n", "", "",
 ("Nie robię z tego problemu, chcę tylko wiedzieć.", "phǒm mâi dâai tham hâi pen rûeang yài khráp khâe yàak rúu", "ผมไม่ได้ทำให้เป็นเรื่องใหญ่ครับ แค่อยากรู้")),
("spokojnie, nic się nie stało", "jai yen yen khráp mâi mii à-rai sǐa hǎai", "ใจเย็นๆ ครับ ไม่มีอะไรเสียหาย",
 "Podstawy i grzeczność", "Łagodzenie", "sentence", 5, "n", "", "",
 ("Spokojnie, nic się nie stało, poprawimy to.", "jai yen yen khráp mâi mii à-rai sǐa hǎai dǐao kâe hâi", "ใจเย็นๆ ครับ ไม่มีอะไรเสียหาย เดี๋ยวแก้ให้")),
("rozumiem twoje stanowisko", "phǒm khâo-jai mum khǎwng khun khráp", "ผมเข้าใจมุมของคุณครับ",
 "Praca i nauka", "Łagodzenie", "sentence", 4, "n", "", "",
 ("Rozumiem twoje stanowisko, choć widzę to inaczej.", "phǒm khâo-jai mum khǎwng khun khráp thǔeng jà mawng tàang", "ผมเข้าใจมุมของคุณครับ ถึงจะมองต่าง")),
("nie zamierzałem cię urazić", "mâi dâai tâng-jai hâi khun mâi sà-baai jai khráp", "ไม่ได้ตั้งใจให้คุณไม่สบายใจครับ",
 "Podstawy i grzeczność", "Łagodzenie", "sentence", 4, "n",
 "„mâi sà-baai jai” = nieswojo na sercu. Tajski mówi o dyskomforcie emocjonalnym przez ciało.", "niewygodne serce",
 ("Nie zamierzałem cię urazić, przepraszam.", "mâi dâai tâng-jai hâi khun mâi sà-baai jai khráp khǎw-thôot dûai", "ไม่ได้ตั้งใจให้คุณไม่สบายใจครับ ขอโทษด้วย")),
("nie o to mi chodziło", "phǒm mâi dâai mǎai yàang nán khráp", "ผมไม่ได้หมายอย่างนั้นครับ",
 "Podstawy i grzeczność", "Łagodzenie", "sentence", 5, "n", "", "",
 ("Nie o to mi chodziło, źle się wyraziłem.", "phǒm mâi dâai mǎai yàang nán khráp phǒm phûut mâi dii eeng", "ผมไม่ได้หมายอย่างนั้นครับ ผมพูดไม่ดีเอง")),
("pozwól, że wyjaśnię", "khǎw à-thí-baai nòi ná khráp", "ขออธิบายหน่อยนะครับ",
 "Podstawy i grzeczność", "Łagodzenie", "sentence", 5, "n", "", "",
 ("Pozwól, że wyjaśnię, zanim ocenisz.", "khǎw à-thí-baai kàwn ná khráp khôi tàt-sǐn", "ขออธิบายก่อนนะครับ ค่อยตัดสิน")),

# =====================================================================
# GRZECZNOSC WOBEC STARSZYCH I PRZELOZONYCH
# =====================================================================
("z całym szacunkiem", "dûai khwaam khaao-róp khráp", "ด้วยความเคารพครับ", "Podstawy i grzeczność", "Uprzejmość", "phrase", 3, "f",
 "Poprzedza niezgodę wobec kogoś wyżej w hierarchii. Bez tej formuły sprzeciw byłby afrontem.", "",
 ("Z całym szacunkiem, mam inne dane.", "dûai khwaam khaao-róp khráp phǒm mii khâw-muun ìik chút", "ด้วยความเคารพครับ ผมมีข้อมูลอีกชุด")),
("pozwolę sobie zauważyć", "khǎw à-nú-yâat sǎng-kèet ná khráp", "ขออนุญาตสังเกตนะครับ",
 "Praca i nauka", "Uprzejmość", "phrase", 3, "f",
 "„khǎw à-nú-yâat” = proszę o pozwolenie. Otwiera niemal każde formalne zdanie w tajskim biurze.", "",
 ("Pozwolę sobie zauważyć jedną nieścisłość.", "khǎw à-nú-yâat sǎng-kèet nùeng jùt khráp", "ขออนุญาตสังเกตหนึ่งจุดครับ")),
("proszę o wyrozumiałość", "khǎw à-phai dûai khráp", "ขออภัยด้วยครับ", "Podstawy i grzeczność", "Uprzejmość", "phrase", 3, "f",
 "„khǎw à-phai” to formalny odpowiednik „khǎw-thôot”. Usłyszysz go w komunikatach na lotnisku.", "",
 ("Proszę o wyrozumiałość, system jest przeciążony.", "khǎw à-phai dûai khráp rá-bòp nâen mâak", "ขออภัยด้วยครับ ระบบแน่นมาก")),
("czy mogę prosić o chwilę uwagi", "khǎw wee-laa sák khrûu ná khráp", "ขอเวลาสักครู่นะครับ",
 "Praca i nauka", "Uprzejmość", "sentence", 4, "f", "", "",
 ("Czy mogę prosić o chwilę uwagi przed zakończeniem?", "khǎw wee-laa sák khrûu kàwn jòp ná khráp", "ขอเวลาสักครู่ก่อนจบนะครับ")),
("dziękuję za zrozumienie", "khàwp-khun thîi khâo-jai khráp", "ขอบคุณที่เข้าใจครับ",
 "Podstawy i grzeczność", "Uprzejmość", "sentence", 4, "f", "", "",
 ("Dziękuję za zrozumienie, doceniam to.", "khàwp-khun thîi khâo-jai khráp phǒm sâap súeng", "ขอบคุณที่เข้าใจครับ ผมซาบซึ้ง")),
("to dla mnie duża pomoc", "chûai phǒm dâai yóe loei khráp", "ช่วยผมได้เยอะเลยครับ",
 "Podstawy i grzeczność", "Uprzejmość", "sentence", 4, "n", "", "",
 ("To dla mnie duża pomoc, dziękuję.", "chûai phǒm dâai yóe loei khráp khàwp-khun mâak", "ช่วยผมได้เยอะเลยครับ ขอบคุณมาก")),
("jestem zobowiązany", "pen phrá-khun mâak khráp", "เป็นพระคุณมากครับ", "Podstawy i grzeczność", "Uprzejmość", "phrase", 3, "f",
 "Mocne, ciepłe podziękowanie za realną przysługę. Wobec drobiazgu zabrzmi przesadnie.", "to wielka łaska",
 ("Jestem zobowiązany za tę pomoc.", "thîi chûai khráng níi pen phrá-khun mâak khráp", "ที่ช่วยครั้งนี้เป็นพระคุณมากครับ")),
("proszę się nie kłopotać", "mâi tâwng róp-kuan khráp", "ไม่ต้องรบกวนครับ", "Podstawy i grzeczność", "Uprzejmość", "sentence", 4, "n", "", "",
 ("Proszę się nie kłopotać, poradzę sobie.", "mâi tâwng róp-kuan khráp phǒm tham eeng dâai", "ไม่ต้องรบกวนครับ ผมทำเองได้")),
("nie ma za co, drobiazg", "mâi mii à-rai khráp rûeang lék", "ไม่มีอะไรครับ เรื่องเล็ก",
 "Podstawy i grzeczność", "Uprzejmość", "sentence", 4, "n", "", "",
 ("Nie ma za co, drobiazg, zawsze pomogę.", "mâi mii à-rai khráp rûeang lék yin dii chûai", "ไม่มีอะไรครับ เรื่องเล็ก ยินดีช่วย")),
("służę pomocą", "yin dii chûai lǔea khráp", "ยินดีช่วยเหลือครับ", "Praca i nauka", "Uprzejmość", "sentence", 4, "f", "", "",
 ("Służę pomocą, proszę dać znać.", "yin dii chûai lǔea khráp bàwk dâai loei", "ยินดีช่วยเหลือครับ บอกได้เลย")),
]
