# -*- coding: utf-8 -*-
"""Wzorce zdaniowe etapu 5 (B2) — czesc D: konstrukcje czasownikowe, druga seria.

Zakres: przymus zewnetrzny, nawyk wiekszosciowy, zamiar przerwany, ostatnia
okazja, gotowosc uslugowa, elastycznosc terminu, zal po niezrealizowanym.

Pozycja: (polskie haslo rekordu, polskie haslo bazowe, polski przyklad)
"""

TPL_D = [

# =====================================================================
# thuuk bang-khap hai … — przymus zewnetrzny
# =====================================================================
dict(key="BANGKHAP", ty="sentence", cat="Praca i nauka", sub="Przymus", reg="n",
     ph="phǒm thùuk bang-kháp hâi {ph} khráp", th="ผมถูกบังคับให้{th}ครับ",
     lit="thùuk … = strona bierna o zabarwieniu negatywnym; bang-kháp = zmuszać",
     note="„thùuk” tworzy stronę bierną tylko dla rzeczy nieprzyjemnych. Dla przyjemnych używa się „dâai ráp”.",
     ex_ph="khun thùuk bang-kháp hâi {ph} rǒe khráp", ex_th="คุณถูกบังคับให้{th}หรือครับ",
     items=[
       ("Zmuszono mnie, żebym zapłacił.", "płacić", "Zmuszono cię, żebyś zapłacił?"),
       ("Zmuszono mnie, żebym podpisał.", "podpisać", "Zmuszono cię, żebyś podpisał?"),
       ("Zmuszono mnie, żebym czekał.", "czekać", "Zmuszono cię, żebyś czekał?"),
       ("Zmuszono mnie, żebym wrócił.", "wracać", "Zmuszono cię, żebyś wrócił?"),
       ("Zmuszono mnie, żebym to zmienił.", "zmieniać", "Zmuszono cię, żebyś to zmienił?"),
       ("Zmuszono mnie, żebym anulował.", "anulować", "Zmuszono cię, żebyś anulował?"),
       ("Zmuszono mnie, żebym wypełnił formularz.", "wypełnić formularz", "Zmuszono cię, żebyś wypełnił formularz?"),
       ("Zmuszono mnie, żebym pokazał dokumenty.", "pokazać", "Zmuszono cię, żebyś pokazał dokumenty?"),
       ("Zmuszono mnie, żebym wysiadł.", "wysiadać", "Zmuszono cię, żebyś wysiadł?"),
       ("Zmuszono mnie, żebym się przesiadł.", "przesiadać się", "Zmuszono cię, żebyś się przesiadł?"),
       ("Zmuszono mnie, żebym wyszedł.", "wychodzić", "Zmuszono cię, żebyś wyszedł?"),
       ("Zmuszono mnie, żebym poczekał na zewnątrz i się przebrał.", "ubierać się", "Zmuszono cię, żebyś się przebrał?"),
       ("Zmuszono mnie, żebym pracował w weekend.", "pracować", "Zmuszono cię do pracy w weekend?"),
       ("Zmuszono mnie, żebym został dłużej i posprzątał.", "sprzątać", "Zmuszono cię, żebyś sprzątał?"),
       ("Zmuszono mnie, żebym to kupił.", "kupować", "Zmuszono cię, żebyś to kupił?"),
       ("Zmuszono mnie, żebym to sprzedał.", "sprzedawać", "Zmuszono cię, żebyś to sprzedał?"),
       ("Zmuszono mnie, żebym zadzwonił.", "dzwonić", "Zmuszono cię, żebyś zadzwonił?"),
       ("Zmuszono mnie, żebym odpowiedział od razu.", "odpowiadać", "Zmuszono cię do natychmiastowej odpowiedzi?"),
       ("Zmuszono mnie, żebym zaczął od nowa.", "zaczynać", "Zmuszono cię, żebyś zaczął od nowa?"),
       ("Zmuszono mnie, żebym przestał.", "przestać", "Zmuszono cię, żebyś przestał?"),
       ("Zmuszono mnie, żebym się spakował w pół godziny.", "pakować się", "Zmuszono cię do szybkiego pakowania?"),
       ("Zmuszono mnie, żebym się wymeldował wcześniej.", "wychodzić", "Zmuszono cię do wcześniejszego wyjścia?"),
       ("Zmuszono mnie, żebym wynajął droższy pokój.", "wynajmować", "Zmuszono cię do droższego wynajmu?"),
       ("Zmuszono mnie, żebym zarezerwował z góry.", "rezerwować", "Zmuszono cię do rezerwacji z góry?"),
       ("Zmuszono mnie, żebym zamówił coś do picia.", "zamawiać", "Zmuszono cię do zamówienia?"),
       ("Zmuszono mnie, żebym poszedł pieszo.", "iść pieszo", "Zmuszono cię, żebyś szedł pieszo?"),
       ("Zmuszono mnie, żebym prowadził w nocy.", "prowadzić samochód", "Zmuszono cię do jazdy w nocy?"),
       ("Zmuszono mnie, żebym używał ich sprzętu.", "używać", "Zmuszono cię do ich sprzętu?"),
       ("Zmuszono mnie, żebym się uczył po godzinach.", "uczyć się", "Zmuszono cię do nauki po godzinach?"),
       ("Zmuszono mnie, żebym wstał o czwartej.", "wstawać", "Zmuszono cię do wstawania o czwartej?"),
       ("Zmuszono mnie, żebym pomagał przy przeprowadzce.", "pomagać", "Zmuszono cię do pomocy?"),
       ("Zmuszono mnie, żebym zapytał kierownika.", "pytać", "Zmuszono cię, żebyś pytał kierownika?"),
       ("Zmuszono mnie, żebym wysłał to jeszcze raz.", "wysyłać", "Zmuszono cię do ponownego wysłania?"),
       ("Zmuszono mnie, żebym przeczytał całą umowę na głos.", "czytać", "Zmuszono cię do czytania na głos?"),
       ("Zmuszono mnie, żebym napisał wyjaśnienie.", "pisać", "Zmuszono cię do pisania wyjaśnienia?"),
       ("Zmuszono mnie, żebym oddał klucze.", "dawać", "Zmuszono cię do oddania kluczy?"),
     ]),

# =====================================================================
# suan yai phom … eeng — nawyk wiekszosciowy
# =====================================================================
dict(key="SUANYAI", ty="sentence", cat="Dom i codzienność", sub="Codzienne", reg="n",
     ph="sùan yài phǒm {ph} eeng khráp", th="ส่วนใหญ่ผม{th}เองครับ",
     lit="sùan yài = w większości przypadków; eeng = sam, osobiście",
     note="„eeng” podkreśla samodzielność, nie samotność. Bez niego zdanie mówi tylko o częstotliwości.",
     ex_ph="sùan yài khun {ph} eeng rǔe hâi khon ùen tham khráp", ex_th="ส่วนใหญ่คุณ{th}เองหรือให้คนอื่นทำครับ",
     items=[
       ("Zwykle gotuję sam.", "gotować", "Zwykle gotujesz sam czy zamawiasz?"),
       ("Zwykle piorę sam.", "prać", "Zwykle pierzesz sam czy oddajesz?"),
       ("Zwykle sprzątam sam.", "sprzątać", "Zwykle sprzątasz sam czy ktoś pomaga?"),
       ("Zwykle naprawiam sam.", "naprawiać", "Zwykle naprawiasz sam czy wołasz fachowca?"),
       ("Zwykle prowadzę sam.", "prowadzić samochód", "Zwykle prowadzisz sam czy z kimś?"),
       ("Zwykle rezerwuję sam.", "rezerwować", "Zwykle rezerwujesz sam czy przez biuro?"),
       ("Zwykle zamawiam sam.", "zamawiać", "Zwykle zamawiasz sam czy ktoś za ciebie?"),
       ("Zwykle płacę sam.", "płacić", "Zwykle płacisz sam czy dzielicie się?"),
       ("Zwykle wypełniam formularze sam.", "wypełnić formularz", "Zwykle wypełniasz sam czy z pomocą?"),
       ("Zwykle podpisuję sam.", "podpisać", "Zwykle podpisujesz sam czy przez pełnomocnika?"),
       ("Zwykle wysyłam sam.", "wysyłać", "Zwykle wysyłasz sam czy przez kuriera?"),
       ("Zwykle dzwonię sam.", "dzwonić", "Zwykle dzwonisz sam czy prosisz kogoś?"),
       ("Zwykle pytam sam.", "pytać", "Zwykle pytasz sam czy przez znajomych?"),
       ("Zwykle szukam sam.", "szukać", "Zwykle szukasz sam czy przez agenta?"),
       ("Zwykle wybieram sam.", "wybierać", "Zwykle wybierasz sam czy razem?"),
       ("Zwykle pakuję się sam.", "pakować się", "Zwykle pakujesz się sam?"),
       ("Zwykle uczę się sam.", "uczyć się", "Zwykle uczysz się sam czy z nauczycielem?"),
       ("Zwykle czytam umowy sam.", "czytać", "Zwykle czytasz umowy sam?"),
       ("Zwykle piszę odpowiedzi sam.", "pisać", "Zwykle piszesz odpowiedzi sam?"),
       ("Zwykle myję to sam.", "myć", "Zwykle myjesz to sam?"),
       ("Zwykle odbieram przesyłki sam.", "odbierać", "Zwykle odbierasz przesyłki sam?"),
       ("Zwykle wracam sam.", "wracać", "Zwykle wracasz sam czy z kimś?"),
       ("Zwykle jem sam.", "jeść", "Zwykle jesz sam czy w towarzystwie?"),
       ("Zwykle robię zdjęcia sam.", "robić zdjęcia", "Zwykle robisz zdjęcia sam?"),
       ("Zwykle biegam sam.", "biegać", "Zwykle biegasz sam czy z grupą?"),
       ("Zwykle pływam sam.", "pływać", "Zwykle pływasz sam?"),
       ("Zwykle zwiedzam sam.", "zwiedzać", "Zwykle zwiedzasz sam czy z przewodnikiem?"),
       ("Zwykle wynajmuję sam.", "wynajmować", "Zwykle wynajmujesz sam czy przez agencję?"),
       ("Zwykle sprzedaję sam.", "sprzedawać", "Zwykle sprzedajesz sam czy przez pośrednika?"),
       ("Zwykle kupuję sam.", "kupować", "Zwykle kupujesz sam czy z rodziną?"),
       ("Zwykle liczę rachunek sam.", "policzyć rachunek", "Zwykle liczysz rachunek sam?"),
       ("Zwykle otwieram sklep sam.", "otwierać", "Zwykle otwierasz sam?"),
       ("Zwykle zamykam sam.", "zamykać", "Zwykle zamykasz sam?"),
       ("Zwykle budzę się sam bez budzika.", "budzić się", "Zwykle budzisz się sam?"),
       ("Zwykle odpoczywam sam.", "odpoczywać", "Zwykle odpoczywasz sam?"),
       ("Zwykle radzę sobie sam z problemami.", "robić", "Zwykle radzisz sobie sam?"),
     ]),

# =====================================================================
# kamlang khit ja … yuu phaw dii — zbieznosc zamiaru
# =====================================================================
dict(key="KHITJA", ty="sentence", cat="Gramatyka użytkowa", sub="Plany", reg="n",
     ph="phǒm kam-lang khít jà {ph} yùu phaw dii khráp", th="ผมกำลังคิดจะ{th}อยู่พอดีครับ",
     lit="khít jà … yùu phaw dii = właśnie się nad tym zastanawiałem",
     note="Zwrot wyrażający zbieżność myśli z rozmówcą. Buduje sympatię lepiej niż zwykłe „tak”.",
     ex_ph="khun kam-lang khít jà {ph} yùu mǔean kan rǒe khráp", ex_th="คุณกำลังคิดจะ{th}อยู่เหมือนกันหรือครับ",
     items=[
       ("Właśnie się zastanawiałem, czy nie zadzwonić.", "dzwonić", "Ty też myślałeś, żeby zadzwonić?"),
       ("Właśnie się zastanawiałem, czy nie wrócić.", "wracać", "Ty też myślałeś, żeby wrócić?"),
       ("Właśnie się zastanawiałem, czy nie zamówić.", "zamawiać", "Ty też myślałeś, żeby zamówić?"),
       ("Właśnie się zastanawiałem, czy nie zapytać.", "pytać", "Ty też myślałeś, żeby zapytać?"),
       ("Właśnie się zastanawiałem, czy tego nie zmienić.", "zmieniać", "Ty też myślałeś, żeby to zmienić?"),
       ("Właśnie się zastanawiałem, czy nie anulować.", "anulować", "Ty też myślałeś, żeby anulować?"),
       ("Właśnie się zastanawiałem, czy tego nie sprzedać.", "sprzedawać", "Ty też myślałeś, żeby to sprzedać?"),
       ("Właśnie się zastanawiałem, czy tego nie kupić.", "kupować", "Ty też myślałeś, żeby to kupić?"),
       ("Właśnie się zastanawiałem, czy nie poszukać czegoś innego.", "szukać", "Ty też myślałeś, żeby poszukać?"),
       ("Właśnie się zastanawiałem, czy nie odpocząć.", "odpoczywać", "Ty też myślałeś, żeby odpocząć?"),
       ("Właśnie się zastanawiałem, czy nie wyjść wcześniej.", "wychodzić", "Ty też myślałeś, żeby wyjść wcześniej?"),
       ("Właśnie się zastanawiałem, czy nie przestać.", "przestać", "Ty też myślałeś, żeby przestać?"),
       ("Właśnie się zastanawiałem, czy nie zacząć od nowa.", "zaczynać", "Ty też myślałeś, żeby zacząć od nowa?"),
       ("Właśnie się zastanawiałem, czy się nie przesiąść.", "przesiadać się", "Ty też myślałeś o przesiadce?"),
       ("Właśnie się zastanawiałem, czy nie wynająć czegoś większego.", "wynajmować", "Ty też myślałeś o wynajmie?"),
       ("Właśnie się zastanawiałem, czy nie zarezerwować.", "rezerwować", "Ty też myślałeś o rezerwacji?"),
       ("Właśnie się zastanawiałem, czy nie podpisać.", "podpisać", "Ty też myślałeś, żeby podpisać?"),
       ("Właśnie się zastanawiałem, czy nie zapłacić od razu.", "płacić", "Ty też myślałeś, żeby zapłacić od razu?"),
       ("Właśnie się zastanawiałem, czy tego nie pożyczyć.", "pożyczyć", "Ty też myślałeś, żeby to pożyczyć?"),
       ("Właśnie się zastanawiałem, czy nie napisać do nich.", "pisać", "Ty też myślałeś, żeby napisać?"),
       ("Właśnie się zastanawiałem, czy nie pojechać tam dziś.", "iść / jechać", "Ty też myślałeś, żeby tam pojechać?"),
       ("Właśnie się zastanawiałem, czy nie zwiedzić okolicy.", "zwiedzać", "Ty też myślałeś o zwiedzaniu?"),
       ("Właśnie się zastanawiałem, czy nie popływać.", "pływać", "Ty też myślałeś, żeby popływać?"),
       ("Właśnie się zastanawiałem, czy czegoś nie ugotować.", "gotować", "Ty też myślałeś, żeby coś ugotować?"),
       ("Właśnie się zastanawiałem, czy nie zjeść wcześniej.", "jeść", "Ty też myślałeś, żeby zjeść wcześniej?"),
       ("Właśnie się zastanawiałem, czy się nie spotkać.", "spotykać", "Ty też myślałeś o spotkaniu?"),
       ("Właśnie się zastanawiałem, czy nie pomóc mu.", "pomagać", "Ty też myślałeś, żeby mu pomóc?"),
       ("Właśnie się zastanawiałem, czy się nie spakować dziś.", "pakować się", "Ty też myślałeś o pakowaniu?"),
       ("Właśnie się zastanawiałem, czy nie wysłać tego dziś.", "wysyłać", "Ty też myślałeś, żeby to wysłać?"),
       ("Właśnie się zastanawiałem, czy tego nie pokazać.", "pokazać", "Ty też myślałeś, żeby to pokazać?"),
       ("Właśnie się zastanawiałem, czy nie przeczytać całości.", "czytać", "Ty też myślałeś, żeby przeczytać całość?"),
       ("Właśnie się zastanawiałem, czy się nie uczyć wieczorami.", "uczyć się", "Ty też myślałeś o nauce wieczorami?"),
       ("Właśnie się zastanawiałem, czy nie zamknąć wcześniej.", "zamykać", "Ty też myślałeś, żeby zamknąć wcześniej?"),
       ("Właśnie się zastanawiałem, czy nie wstać wcześniej.", "wstawać", "Ty też myślałeś, żeby wstać wcześniej?"),
       ("Właśnie się zastanawiałem, czy tego nie przymierzyć.", "przymierzać / próbować", "Ty też myślałeś, żeby przymierzyć?"),
       ("Właśnie się zastanawiałem, czy nie spróbować czegoś nowego.", "próbować (smakować)", "Ty też myślałeś, żeby spróbować?"),
     ]),

# =====================================================================
# thaa mai … tawn nii kaw mai mii oo-kaat laew — ostatnia okazja
# =====================================================================
dict(key="OOKAAT", ty="sentence", cat="Gramatyka użytkowa", sub="Warunek", reg="n",
     ph="thâa mâi {ph} tawn níi kâw mâi mii oo-kàat láew khráp", th="ถ้าไม่{th}ตอนนี้ก็ไม่มีโอกาสแล้วครับ",
     lit="mâi mii oo-kàat láew = nie będzie już okazji",
     note="Argument z ostatniej szansy. W negocjacjach działa mocno, więc używaj go oszczędnie.",
     ex_ph="thâa mâi {ph} tawn níi jà mii oo-kàat ìik mǎi khráp", ex_th="ถ้าไม่{th}ตอนนี้จะมีโอกาสอีกไหมครับ",
     items=[
       ("Jeśli teraz nie pojedziemy, nie będzie już okazji.", "iść / jechać", "Jeśli teraz nie pojedziemy, będzie jeszcze szansa?"),
       ("Jeśli teraz nie kupimy, nie będzie już okazji.", "kupować", "Jeśli teraz nie kupimy, będzie jeszcze szansa?"),
       ("Jeśli teraz nie sprzedamy, nie będzie już okazji.", "sprzedawać", "Jeśli teraz nie sprzedamy, będzie szansa?"),
       ("Jeśli teraz nie zarezerwujemy, nie będzie już okazji.", "rezerwować", "Jeśli teraz nie zarezerwujemy, będzie szansa?"),
       ("Jeśli teraz nie zapytamy, nie będzie już okazji.", "pytać", "Jeśli teraz nie zapytamy, będzie szansa?"),
       ("Jeśli teraz nie zapłacimy, nie będzie już okazji.", "płacić", "Jeśli teraz nie zapłacimy, będzie szansa?"),
       ("Jeśli teraz nie podpiszemy, nie będzie już okazji.", "podpisać", "Jeśli teraz nie podpiszemy, będzie szansa?"),
       ("Jeśli teraz nie spróbujemy, nie będzie już okazji.", "próbować (smakować)", "Jeśli teraz nie spróbujemy, będzie szansa?"),
       ("Jeśli teraz nie zwiedzimy, nie będzie już okazji.", "zwiedzać", "Jeśli teraz nie zwiedzimy, będzie szansa?"),
       ("Jeśli teraz nie zrobimy zdjęć, nie będzie już okazji.", "robić zdjęcia", "Jeśli teraz nie zrobimy zdjęć, będzie szansa?"),
       ("Jeśli teraz się nie spotkamy, nie będzie już okazji.", "spotykać", "Jeśli teraz się nie spotkamy, będzie szansa?"),
       ("Jeśli teraz nie zadzwonimy, nie będzie już okazji.", "dzwonić", "Jeśli teraz nie zadzwonimy, będzie szansa?"),
       ("Jeśli teraz nie wyślemy, nie będzie już okazji.", "wysyłać", "Jeśli teraz nie wyślemy, będzie szansa?"),
       ("Jeśli teraz nie zaczniemy, nie będzie już okazji.", "zaczynać", "Jeśli teraz nie zaczniemy, będzie szansa?"),
       ("Jeśli teraz tego nie zmienimy, nie będzie już okazji.", "zmieniać", "Jeśli teraz nie zmienimy, będzie szansa?"),
       ("Jeśli teraz nie anulujemy, nie będzie już okazji.", "anulować", "Jeśli teraz nie anulujemy, będzie szansa?"),
       ("Jeśli teraz nie wynajmiemy, nie będzie już okazji.", "wynajmować", "Jeśli teraz nie wynajmiemy, będzie szansa?"),
       ("Jeśli teraz nie odpoczniemy, nie będzie już okazji.", "odpoczywać", "Jeśli teraz nie odpoczniemy, będzie szansa?"),
       ("Jeśli teraz nie popływamy, nie będzie już okazji.", "pływać", "Jeśli teraz nie popływamy, będzie szansa?"),
       ("Jeśli teraz nie zjemy, nie będzie już okazji.", "jeść", "Jeśli teraz nie zjemy, będzie szansa?"),
       ("Jeśli teraz nie wrócimy, nie będzie już okazji.", "wracać", "Jeśli teraz nie wrócimy, będzie szansa?"),
       ("Jeśli teraz nie wysiądziemy, nie będzie już okazji.", "wysiadać", "Jeśli teraz nie wysiądziemy, będzie szansa?"),
       ("Jeśli teraz nie wsiądziemy, nie będzie już okazji.", "wsiadać", "Jeśli teraz nie wsiądziemy, będzie szansa?"),
       ("Jeśli teraz się nie przesiądziemy, nie będzie już okazji.", "przesiadać się", "Jeśli teraz się nie przesiądziemy, będzie szansa?"),
       ("Jeśli teraz go nie pokażemy, nie będzie już okazji.", "pokazać", "Jeśli teraz nie pokażemy, będzie szansa?"),
       ("Jeśli teraz nie odpowiemy, nie będzie już okazji.", "odpowiadać", "Jeśli teraz nie odpowiemy, będzie szansa?"),
       ("Jeśli teraz nie wybierzemy, nie będzie już okazji.", "wybierać", "Jeśli teraz nie wybierzemy, będzie szansa?"),
       ("Jeśli teraz nie pożyczymy, nie będzie już okazji.", "pożyczyć", "Jeśli teraz nie pożyczymy, będzie szansa?"),
       ("Jeśli teraz tego nie naprawimy, nie będzie już okazji.", "naprawiać", "Jeśli teraz nie naprawimy, będzie szansa?"),
       ("Jeśli teraz nie posprzątamy, nie będzie już okazji.", "sprzątać", "Jeśli teraz nie posprzątamy, będzie szansa?"),
       ("Jeśli teraz się nie spakujemy, nie będzie już okazji.", "pakować się", "Jeśli teraz się nie spakujemy, będzie szansa?"),
       ("Jeśli teraz się nie nauczymy, nie będzie już okazji.", "uczyć się", "Jeśli teraz się nie nauczymy, będzie szansa?"),
       ("Jeśli teraz nie poszukamy, nie będzie już okazji.", "szukać", "Jeśli teraz nie poszukamy, będzie szansa?"),
       ("Jeśli teraz nie pomożemy, nie będzie już okazji.", "pomagać", "Jeśli teraz nie pomożemy, będzie szansa?"),
       ("Jeśli teraz nie wypełnimy wniosku, nie będzie już okazji.", "wypełnić formularz", "Jeśli teraz nie wypełnimy, będzie szansa?"),
       ("Jeśli teraz tego nie użyjemy, nie będzie już okazji.", "używać", "Jeśli teraz nie użyjemy, będzie szansa?"),
     ]),

# =====================================================================
# phom yin dii thii ja … hai — gotowosc uslugowa
# =====================================================================
dict(key="YINDII", ty="sentence", cat="Podstawy i grzeczność", sub="Uprzejmość", reg="f",
     ph="phǒm yin dii thîi jà {ph} hâi khráp", th="ผมยินดีที่จะ{th}ให้ครับ",
     lit="yin dii = z przyjemnością; hâi = na czyjąś rzecz",
     note="„hâi” na końcu wskazuje, że robisz to dla rozmówcy. Bez niego zdanie brzmi jak deklaracja o sobie.",
     ex_ph="thâa yàak hâi phǒm {ph} hâi kâw bàwk dâai loei khráp", ex_th="ถ้าอยากให้ผม{th}ให้ก็บอกได้เลยครับ",
     items=[
       ("Chętnie ci w tym pomogę.", "pomagać", "Jeśli chcesz, żebym pomógł, powiedz."),
       ("Chętnie to dla ciebie sprawdzę.", "szukać", "Jeśli chcesz, żebym poszukał, powiedz."),
       ("Chętnie to dla ciebie zamówię.", "zamawiać", "Jeśli chcesz, żebym zamówił, powiedz."),
       ("Chętnie to dla ciebie zarezerwuję.", "rezerwować", "Jeśli chcesz, żebym zarezerwował, powiedz."),
       ("Chętnie to dla ciebie wyślę.", "wysyłać", "Jeśli chcesz, żebym wysłał, powiedz."),
       ("Chętnie do nich zadzwonię.", "dzwonić", "Jeśli chcesz, żebym zadzwonił, powiedz."),
       ("Chętnie za ciebie zapytam.", "pytać", "Jeśli chcesz, żebym zapytał, powiedz."),
       ("Chętnie ci to pokażę.", "pokazać", "Jeśli chcesz, żebym pokazał, powiedz."),
       ("Chętnie ci to przetłumaczę i przeczytam.", "czytać", "Jeśli chcesz, żebym przeczytał, powiedz."),
       ("Chętnie to za ciebie napiszę.", "pisać", "Jeśli chcesz, żebym napisał, powiedz."),
       ("Chętnie ci to wypełnię.", "wypełnić formularz", "Jeśli chcesz, żebym wypełnił, powiedz."),
       ("Chętnie po ciebie przyjadę.", "przyjść / przyjechać", "Jeśli chcesz, żebym przyjechał, powiedz."),
       ("Chętnie cię odwiozę.", "prowadzić samochód", "Jeśli chcesz, żebym cię odwiózł, powiedz."),
       ("Chętnie na ciebie poczekam.", "czekać", "Jeśli chcesz, żebym poczekał, powiedz."),
       ("Chętnie coś dla ciebie ugotuję.", "gotować", "Jeśli chcesz, żebym ugotował, powiedz."),
       ("Chętnie ci to pożyczę.", "pożyczyć", "Jeśli chcesz, żebym pożyczył, powiedz."),
       ("Chętnie ci to dam.", "dawać", "Jeśli chcesz, żebym ci to dał, powiedz."),
       ("Chętnie to dla ciebie kupię.", "kupować", "Jeśli chcesz, żebym kupił, powiedz."),
       ("Chętnie to za ciebie odbiorę.", "odbierać", "Jeśli chcesz, żebym odebrał, powiedz."),
       ("Chętnie ci to naprawię.", "naprawiać", "Jeśli chcesz, żebym naprawił, powiedz."),
       ("Chętnie ci to umyję.", "myć", "Jeśli chcesz, żebym umył, powiedz."),
       ("Chętnie ci pomogę się spakować.", "pakować się", "Jeśli chcesz pomocy przy pakowaniu, powiedz."),
       ("Chętnie ci to wyjaśnię i pokażę drogę.", "iść pieszo", "Jeśli chcesz, żebym cię zaprowadził, powiedz."),
       ("Chętnie ci to zmienię.", "zmieniać", "Jeśli chcesz, żebym zmienił, powiedz."),
       ("Chętnie za ciebie zapłacę teraz.", "płacić", "Jeśli chcesz, żebym zapłacił, powiedz."),
       ("Chętnie ci to policzę.", "policzyć rachunek", "Jeśli chcesz, żebym policzył, powiedz."),
       ("Chętnie ci to zorganizuję.", "robić", "Jeśli chcesz, żebym to zrobił, powiedz."),
       ("Chętnie cię tam oprowadzę.", "zwiedzać", "Jeśli chcesz, żebym oprowadził, powiedz."),
       ("Chętnie zrobię ci zdjęcie.", "robić zdjęcia", "Jeśli chcesz zdjęcie, powiedz."),
       ("Chętnie cię tego nauczę.", "uczyć się", "Jeśli chcesz się nauczyć, powiedz."),
       ("Chętnie odpowiem na pytania.", "odpowiadać", "Jeśli masz pytania, powiedz."),
       ("Chętnie posłucham, co masz do powiedzenia.", "słuchać", "Jeśli chcesz pogadać, powiedz."),
       ("Chętnie za ciebie anuluję.", "anulować", "Jeśli chcesz, żebym anulował, powiedz."),
       ("Chętnie ci to podpiszę jako świadek.", "podpisać", "Jeśli chcesz podpis świadka, powiedz."),
       ("Chętnie z tobą pójdę.", "iść / jechać", "Jeśli chcesz, żebym poszedł z tobą, powiedz."),
       ("Chętnie to dla ciebie wynajmę.", "wynajmować", "Jeśli chcesz, żebym wynajął, powiedz."),
     ]),

# =====================================================================
# phom phrawm ja … muea rai kaw dai — elastycznosc terminu
# =====================================================================
dict(key="MUEARAIKAWDAI", ty="sentence", cat="Praca i nauka", sub="Terminy", reg="n",
     ph="phǒm phráwm jà {ph} mûea rài kâw dâai khráp", th="ผมพร้อมจะ{th}เมื่อไหร่ก็ได้ครับ",
     lit="mûea rài kâw dâai = kiedykolwiek, obojętnie kiedy",
     note="Uprzejma elastyczność. „… kâw dâai” działa też z miejscem („thîi nǎi kâw dâai”) i sposobem („yang-ngai kâw dâai”).",
     ex_ph="khun phráwm jà {ph} mûea rài khráp", ex_th="คุณพร้อมจะ{th}เมื่อไหร่ครับ",
     items=[
       ("Jestem gotów się spotkać kiedykolwiek.", "spotykać", "Kiedy jesteś gotów się spotkać?"),
       ("Jestem gotów zacząć kiedykolwiek.", "zaczynać", "Kiedy jesteś gotów zacząć?"),
       ("Jestem gotów przyjechać kiedykolwiek.", "przyjść / przyjechać", "Kiedy jesteś gotów przyjechać?"),
       ("Jestem gotów podpisać kiedykolwiek.", "podpisać", "Kiedy jesteś gotów podpisać?"),
       ("Jestem gotów zapłacić kiedykolwiek.", "płacić", "Kiedy jesteś gotów zapłacić?"),
       ("Jestem gotów pomóc kiedykolwiek.", "pomagać", "Kiedy jesteś gotów pomóc?"),
       ("Jestem gotów zadzwonić kiedykolwiek.", "dzwonić", "Kiedy jesteś gotów zadzwonić?"),
       ("Jestem gotów odpowiedzieć kiedykolwiek.", "odpowiadać", "Kiedy jesteś gotów odpowiedzieć?"),
       ("Jestem gotów wysłać dokumenty kiedykolwiek.", "wysyłać", "Kiedy jesteś gotów wysłać dokumenty?"),
       ("Jestem gotów wrócić kiedykolwiek.", "wracać", "Kiedy jesteś gotów wrócić?"),
       ("Jestem gotów wynająć kiedykolwiek.", "wynajmować", "Kiedy jesteś gotów wynająć?"),
       ("Jestem gotów zarezerwować kiedykolwiek.", "rezerwować", "Kiedy jesteś gotów zarezerwować?"),
       ("Jestem gotów to zmienić kiedykolwiek.", "zmieniać", "Kiedy jesteś gotów to zmienić?"),
       ("Jestem gotów anulować kiedykolwiek.", "anulować", "Kiedy jesteś gotów anulować?"),
       ("Jestem gotów pokazać to kiedykolwiek.", "pokazać", "Kiedy jesteś gotów to pokazać?"),
       ("Jestem gotów pracować w każdych godzinach.", "pracować", "Kiedy jesteś gotów pracować?"),
       ("Jestem gotów się uczyć kiedykolwiek.", "uczyć się", "Kiedy jesteś gotów się uczyć?"),
       ("Jestem gotów prowadzić kiedykolwiek.", "prowadzić samochód", "Kiedy jesteś gotów prowadzić?"),
       ("Jestem gotów tam pojechać kiedykolwiek.", "iść / jechać", "Kiedy jesteś gotów tam pojechać?"),
       ("Jestem gotów odebrać przesyłkę kiedykolwiek.", "odbierać", "Kiedy jesteś gotów odebrać?"),
       ("Jestem gotów zjeść kiedykolwiek.", "jeść", "Kiedy jesteś gotów zjeść?"),
       ("Jestem gotów ugotować kiedykolwiek.", "gotować", "Kiedy jesteś gotów gotować?"),
       ("Jestem gotów posprzątać kiedykolwiek.", "sprzątać", "Kiedy jesteś gotów posprzątać?"),
       ("Jestem gotów się spakować kiedykolwiek.", "pakować się", "Kiedy jesteś gotów się spakować?"),
       ("Jestem gotów przeczytać to kiedykolwiek.", "czytać", "Kiedy jesteś gotów to przeczytać?"),
       ("Jestem gotów napisać to kiedykolwiek.", "pisać", "Kiedy jesteś gotów to napisać?"),
       ("Jestem gotów wypełnić wniosek kiedykolwiek.", "wypełnić formularz", "Kiedy jesteś gotów wypełnić wniosek?"),
       ("Jestem gotów poszukać kiedykolwiek.", "szukać", "Kiedy jesteś gotów poszukać?"),
       ("Jestem gotów zapytać kiedykolwiek.", "pytać", "Kiedy jesteś gotów zapytać?"),
       ("Jestem gotów poczekać, ile trzeba.", "czekać", "Ile jesteś gotów czekać?"),
       ("Jestem gotów wybrać kiedykolwiek.", "wybierać", "Kiedy jesteś gotów wybrać?"),
       ("Jestem gotów to sprzedać kiedykolwiek.", "sprzedawać", "Kiedy jesteś gotów to sprzedać?"),
       ("Jestem gotów to kupić kiedykolwiek.", "kupować", "Kiedy jesteś gotów to kupić?"),
       ("Jestem gotów spróbować kiedykolwiek.", "próbować (smakować)", "Kiedy jesteś gotów spróbować?"),
       ("Jestem gotów naprawić to kiedykolwiek.", "naprawiać", "Kiedy jesteś gotów to naprawić?"),
       ("Jestem gotów wstać o dowolnej porze.", "wstawać", "O której jesteś gotów wstać?"),
     ]),

# =====================================================================
# sia daai thii mai dai … — zal po niezrealizowanym
# =====================================================================
dict(key="SIADAAI", ty="sentence", cat="Cechy i opinie", sub="Żal", reg="n",
     ph="sǐa daai thîi mâi dâai {ph} khráp", th="เสียดายที่ไม่ได้{th}ครับ",
     lit="sǐa daai = szkoda; mâi dâai … = nie udało się …",
     note="„mâi dâai” przed czasownikiem oznacza, że czynność nie doszła do skutku — inaczej niż „mâi …”, które przeczy w ogóle.",
     ex_ph="sǐa daai mǎi khráp thîi mâi dâai {ph}", ex_th="เสียดายไหมครับที่ไม่ได้{th}",
     items=[
       ("Szkoda, że nie udało się tam pojechać.", "iść / jechać", "Szkoda ci, że nie pojechałeś?"),
       ("Szkoda, że nie udało się zwiedzić.", "zwiedzać", "Szkoda ci, że nie zwiedziłeś?"),
       ("Szkoda, że nie udało się spotkać.", "spotykać", "Szkoda ci, że się nie spotkaliście?"),
       ("Szkoda, że nie udało się spróbować.", "próbować (smakować)", "Szkoda ci, że nie spróbowałeś?"),
       ("Szkoda, że nie udało się popływać.", "pływać", "Szkoda ci, że nie popływałeś?"),
       ("Szkoda, że nie udało się odpocząć.", "odpoczywać", "Szkoda ci, że nie odpocząłeś?"),
       ("Szkoda, że nie udało się zrobić zdjęć.", "robić zdjęcia", "Szkoda ci, że nie zrobiłeś zdjęć?"),
       ("Szkoda, że nie udało się kupić.", "kupować", "Szkoda ci, że nie kupiłeś?"),
       ("Szkoda, że nie udało się sprzedać.", "sprzedawać", "Szkoda ci, że nie sprzedałeś?"),
       ("Szkoda, że nie udało się wynająć.", "wynajmować", "Szkoda ci, że nie wynająłeś?"),
       ("Szkoda, że nie udało się zarezerwować.", "rezerwować", "Szkoda ci, że nie zarezerwowałeś?"),
       ("Szkoda, że nie udało się zapytać.", "pytać", "Szkoda ci, że nie zapytałeś?"),
       ("Szkoda, że nie udało się odpowiedzieć.", "odpowiadać", "Szkoda ci, że nie odpowiedziałeś?"),
       ("Szkoda, że nie udało się zadzwonić.", "dzwonić", "Szkoda ci, że nie zadzwoniłeś?"),
       ("Szkoda, że nie udało się wysłać.", "wysyłać", "Szkoda ci, że nie wysłałeś?"),
       ("Szkoda, że nie udało się przeczytać.", "czytać", "Szkoda ci, że nie przeczytałeś?"),
       ("Szkoda, że nie udało się nauczyć.", "uczyć się", "Szkoda ci, że się nie nauczyłeś?"),
       ("Szkoda, że nie udało się pomóc.", "pomagać", "Szkoda ci, że nie pomogłeś?"),
       ("Szkoda, że nie udało się wrócić na czas.", "wracać", "Szkoda ci, że nie wróciłeś na czas?"),
       ("Szkoda, że nie udało się zjeść razem.", "jeść", "Szkoda ci, że nie zjedliście razem?"),
       ("Szkoda, że nie udało się ugotować.", "gotować", "Szkoda ci, że nie ugotowałeś?"),
       ("Szkoda, że nie udało się obejrzeć.", "oglądać", "Szkoda ci, że nie obejrzałeś?"),
       ("Szkoda, że nie udało się posłuchać.", "słuchać", "Szkoda ci, że nie posłuchałeś?"),
       ("Szkoda, że nie udało się zagrać.", "grać / bawić się", "Szkoda ci, że nie zagrałeś?"),
       ("Szkoda, że nie udało się potańczyć.", "tańczyć", "Szkoda ci, że nie tańczyłeś?"),
       ("Szkoda, że nie udało się zaśpiewać.", "śpiewać", "Szkoda ci, że nie zaśpiewałeś?"),
       ("Szkoda, że nie udało się poznać go bliżej.", "znać", "Szkoda ci, że go nie poznałeś?"),
       ("Szkoda, że nie udało się to podpisać.", "podpisać", "Szkoda ci, że nie podpisałeś?"),
       ("Szkoda, że nie udało się zapłacić na czas.", "płacić", "Szkoda ci, że nie zapłaciłeś na czas?"),
       ("Szkoda, że nie udało się tego pokazać.", "pokazać", "Szkoda ci, że nie pokazałeś?"),
       ("Szkoda, że nie udało się tego naprawić.", "naprawiać", "Szkoda ci, że nie naprawiłeś?"),
       ("Szkoda, że nie udało się tego znaleźć.", "znaleźć", "Szkoda ci, że nie znalazłeś?"),
       ("Szkoda, że nie udało się tego pożyczyć.", "pożyczyć", "Szkoda ci, że nie pożyczyłeś?"),
       ("Szkoda, że nie udało się dobrze wyspać.", "spać", "Szkoda ci, że się nie wyspałeś?"),
       ("Szkoda, że nie udało się tego wybrać.", "wybierać", "Szkoda ci, że tego nie wybrałeś?"),
       ("Szkoda, że nie udało się zamówić na czas.", "zamawiać", "Szkoda ci, że nie zamówiłeś?"),
     ]),
]
