# -*- coding: utf-8 -*-
"""Wzorce zdaniowe etapu 5 (B2) — czesc F: ramy grzecznosciowe i rejestrowe.

Zakres: te same czynnosci ujete w ramach o roznym stopniu uprzejmosci —
formalna prosba, lagodna odmowa, sugestia zespolowa, przeprosiny za
niemoznosc, akceptacja obu wyjsc, pytanie o doskonalenie, propozycja
kolejnosci, uprzejme upomnienie.

Pozycja: (polskie haslo rekordu, polskie haslo bazowe, polski przyklad)
"""

TPL_F = [

# =====================================================================
# khaw rop-kuan chuai … noi dai mai — prosba formalna
# =====================================================================
dict(key="ROPKUAN", ty="sentence", cat="Podstawy i grzeczność", sub="Prośby stopniowane", reg="f",
     ph="khǎw rop-kuan chûai {ph} nòi dâai mǎi khráp", th="ขอรบกวนช่วย{th}หน่อยได้ไหมครับ",
     lit="rop-kuan = zakłócać czyjś spokój, czyli: proszę o kłopot",
     note="Najwyższy rejestr prośby w mowie. Sama formuła zawiera już przeprosiny za sprawiany kłopot.",
     ex_ph="thâa mâi lam-bàak khǎw rop-kuan chûai {ph} nòi khráp", ex_th="ถ้าไม่ลำบากขอรบกวนช่วย{th}หน่อยครับ",
     items=[
       ("Czy mógłbym prosić o pomoc w tłumaczeniu i przeczytaniu?", "czytać", "Jeśli to nie kłopot, proszę o przeczytanie."),
       ("Czy mógłbym prosić o zapisanie tego?", "pisać", "Jeśli to nie kłopot, proszę o zapisanie."),
       ("Czy mógłbym prosić o sprawdzenie?", "szukać", "Jeśli to nie kłopot, proszę o sprawdzenie."),
       ("Czy mógłbym prosić o pokazanie?", "pokazać", "Jeśli to nie kłopot, proszę o pokazanie."),
       ("Czy mógłbym prosić o wyjaśnienie i odpowiedź?", "odpowiadać", "Jeśli to nie kłopot, proszę o odpowiedź."),
       ("Czy mógłbym prosić o zapytanie w moim imieniu?", "pytać", "Jeśli to nie kłopot, proszę o zapytanie."),
       ("Czy mógłbym prosić o telefon do nich?", "dzwonić", "Jeśli to nie kłopot, proszę zadzwonić."),
       ("Czy mógłbym prosić o wysłanie tego?", "wysyłać", "Jeśli to nie kłopot, proszę to wysłać."),
       ("Czy mógłbym prosić o odbiór przesyłki?", "odbierać", "Jeśli to nie kłopot, proszę odebrać."),
       ("Czy mógłbym prosić o zarezerwowanie?", "rezerwować", "Jeśli to nie kłopot, proszę zarezerwować."),
       ("Czy mógłbym prosić o zamówienie?", "zamawiać", "Jeśli to nie kłopot, proszę zamówić."),
       ("Czy mógłbym prosić o anulowanie?", "anulować", "Jeśli to nie kłopot, proszę anulować."),
       ("Czy mógłbym prosić o zmianę terminu?", "zmieniać", "Jeśli to nie kłopot, proszę zmienić."),
       ("Czy mógłbym prosić o wypełnienie formularza?", "wypełnić formularz", "Jeśli to nie kłopot, proszę wypełnić."),
       ("Czy mógłbym prosić o podpisanie?", "podpisać", "Jeśli to nie kłopot, proszę podpisać."),
       ("Czy mógłbym prosić o policzenie rachunku?", "policzyć rachunek", "Jeśli to nie kłopot, proszę policzyć."),
       ("Czy mógłbym prosić o zapłacenie za mnie na razie?", "płacić", "Jeśli to nie kłopot, proszę zapłacić."),
       ("Czy mógłbym prosić o poczekanie chwilę?", "czekać", "Jeśli to nie kłopot, proszę poczekać."),
       ("Czy mógłbym prosić o otwarcie?", "otwierać", "Jeśli to nie kłopot, proszę otworzyć."),
       ("Czy mógłbym prosić o zamknięcie?", "zamykać", "Jeśli to nie kłopot, proszę zamknąć."),
       ("Czy mógłbym prosić o naprawienie tego?", "naprawiać", "Jeśli to nie kłopot, proszę naprawić."),
       ("Czy mógłbym prosić o umycie tego?", "myć", "Jeśli to nie kłopot, proszę to umyć."),
       ("Czy mógłbym prosić o wypranie tego?", "prać", "Jeśli to nie kłopot, proszę to wyprać."),
       ("Czy mógłbym prosić o posprzątanie?", "sprzątać", "Jeśli to nie kłopot, proszę posprzątać."),
       ("Czy mógłbym prosić o przywiezienie mnie?", "prowadzić samochód", "Jeśli to nie kłopot, proszę mnie zawieźć."),
       ("Czy mógłbym prosić o zrobienie zdjęcia?", "robić zdjęcia", "Jeśli to nie kłopot, proszę o zdjęcie."),
       ("Czy mógłbym prosić o pożyczenie tego?", "pożyczyć", "Jeśli to nie kłopot, proszę mi pożyczyć."),
       ("Czy mógłbym prosić o podanie tego?", "dawać", "Jeśli to nie kłopot, proszę mi to podać."),
       ("Czy mógłbym prosić o wybranie za mnie?", "wybierać", "Jeśli to nie kłopot, proszę wybrać."),
       ("Czy mógłbym prosić o wysłuchanie mnie?", "słuchać", "Jeśli to nie kłopot, proszę mnie wysłuchać."),
       ("Czy mógłbym prosić o przyjście wcześniej?", "przyjść / przyjechać", "Jeśli to nie kłopot, proszę przyjść wcześniej."),
       ("Czy mógłbym prosić o powrót po mnie?", "wracać", "Jeśli to nie kłopot, proszę po mnie wrócić."),
       ("Czy mógłbym prosić o pomoc przy pakowaniu?", "pakować się", "Jeśli to nie kłopot, proszę o pomoc."),
       ("Czy mógłbym prosić o ugotowanie czegoś lekkiego?", "gotować", "Jeśli to nie kłopot, proszę coś ugotować."),
       ("Czy mógłbym prosić o zapamiętanie tej daty?", "pamiętać", "Jeśli to nie kłopot, proszę zapamiętać."),
       ("Czy mógłbym prosić o wynajęcie tego dla mnie?", "wynajmować", "Jeśli to nie kłopot, proszę wynająć."),
     ]),

# =====================================================================
# khrang nii phom mai sa-duak … — lagodna odmowa
# =====================================================================
dict(key="MAISADUAK", ty="sentence", cat="Podstawy i grzeczność", sub="Odmowy stopniowane", reg="n",
     ph="khráng níi phǒm mâi sà-dùak {ph} khráp", th="ครั้งนี้ผมไม่สะดวก{th}ครับ",
     lit="mâi sà-dùak = niewygodnie mi, nie na rękę",
     note="Odmowa bez podania powodu i bez utraty twarzy przez żadną ze stron. Najbezpieczniejszy wzorzec odmowy w Tajlandii.",
     ex_ph="khráng nâa {ph} dâai mǎi khráp", ex_th="ครั้งหน้า{th}ได้ไหมครับ",
     items=[
       ("Tym razem nie będzie mi wygodnie przyjechać.", "przyjść / przyjechać", "Może następnym razem przyjedziesz?"),
       ("Tym razem nie będzie mi wygodnie prowadzić.", "prowadzić samochód", "Może następnym razem poprowadzisz?"),
       ("Tym razem nie będzie mi wygodnie płacić.", "płacić", "Może następnym razem zapłacisz?"),
       ("Tym razem nie będzie mi wygodnie czekać.", "czekać", "Może następnym razem poczekasz?"),
       ("Tym razem nie będzie mi wygodnie pomóc.", "pomagać", "Może następnym razem pomożesz?"),
       ("Tym razem nie będzie mi wygodnie się spotkać.", "spotykać", "Może następnym razem się spotkacie?"),
       ("Tym razem nie będzie mi wygodnie zadzwonić.", "dzwonić", "Może następnym razem zadzwonisz?"),
       ("Tym razem nie będzie mi wygodnie gotować.", "gotować", "Może następnym razem ugotujesz?"),
       ("Tym razem nie będzie mi wygodnie sprzątać.", "sprzątać", "Może następnym razem posprzątasz?"),
       ("Tym razem nie będzie mi wygodnie zamawiać.", "zamawiać", "Może następnym razem zamówisz?"),
       ("Tym razem nie będzie mi wygodnie rezerwować.", "rezerwować", "Może następnym razem zarezerwujesz?"),
       ("Tym razem nie będzie mi wygodnie podpisywać.", "podpisać", "Może następnym razem podpiszesz?"),
       ("Tym razem nie będzie mi wygodnie wracać tak późno.", "wracać", "Może następnym razem wrócisz?"),
       ("Tym razem nie będzie mi wygodnie iść pieszo.", "iść pieszo", "Może następnym razem pójdziesz pieszo?"),
       ("Tym razem nie będzie mi wygodnie wychodzić.", "wychodzić", "Może następnym razem wyjdziesz?"),
       ("Tym razem nie będzie mi wygodnie pracować w weekend.", "pracować", "Może następnym razem popracujesz?"),
       ("Tym razem nie będzie mi wygodnie się uczyć wieczorem.", "uczyć się", "Może następnym razem się pouczysz?"),
       ("Tym razem nie będzie mi wygodnie wynajmować.", "wynajmować", "Może następnym razem wynajmiesz?"),
       ("Tym razem nie będzie mi wygodnie kupować.", "kupować", "Może następnym razem kupisz?"),
       ("Tym razem nie będzie mi wygodnie sprzedawać.", "sprzedawać", "Może następnym razem sprzedasz?"),
       ("Tym razem nie będzie mi wygodnie pożyczać.", "pożyczyć", "Może następnym razem pożyczysz?"),
       ("Tym razem nie będzie mi wygodnie wysyłać.", "wysyłać", "Może następnym razem wyślesz?"),
       ("Tym razem nie będzie mi wygodnie odbierać.", "odbierać", "Może następnym razem odbierzesz?"),
       ("Tym razem nie będzie mi wygodnie pokazywać.", "pokazać", "Może następnym razem pokażesz?"),
       ("Tym razem nie będzie mi wygodnie odpowiadać.", "odpowiadać", "Może następnym razem odpowiesz?"),
       ("Tym razem nie będzie mi wygodnie pytać.", "pytać", "Może następnym razem zapytasz?"),
       ("Tym razem nie będzie mi wygodnie zwiedzać.", "zwiedzać", "Może następnym razem pozwiedzasz?"),
       ("Tym razem nie będzie mi wygodnie pływać.", "pływać", "Może następnym razem popływasz?"),
       ("Tym razem nie będzie mi wygodnie tańczyć.", "tańczyć", "Może następnym razem zatańczysz?"),
       ("Tym razem nie będzie mi wygodnie śpiewać.", "śpiewać", "Może następnym razem zaśpiewasz?"),
       ("Tym razem nie będzie mi wygodnie jeść tak późno.", "jeść", "Może następnym razem zjesz?"),
       ("Tym razem nie będzie mi wygodnie pić alkoholu.", "pić", "Może następnym razem się napijesz?"),
       ("Tym razem nie będzie mi wygodnie robić zdjęć.", "robić zdjęcia", "Może następnym razem zrobisz zdjęcia?"),
       ("Tym razem nie będzie mi wygodnie się pakować dziś.", "pakować się", "Może następnym razem spakujesz się wcześniej?"),
       ("Tym razem nie będzie mi wygodnie się przesiadać.", "przesiadać się", "Może następnym razem się przesiądziesz?"),
       ("Tym razem nie będzie mi wygodnie wstawać tak wcześnie.", "wstawać", "Może następnym razem wstaniesz wcześniej?"),
     ]),

# =====================================================================
# phom waa raw khuan … kan maak kwaa — sugestia zespolowa
# =====================================================================
dict(key="RAWKHUAN", ty="sentence", cat="Praca i nauka", sub="Sugestie", reg="n",
     ph="phǒm wâa raw khuan {ph} kan mâak kwàa khráp", th="ผมว่าเราควร{th}กันมากกว่าครับ",
     lit="raw khuan … kan = powinniśmy zrobić to razem",
     note="„kan” oznacza wspólnotę działania. Sugestia z „raw … kan” brzmi jak propozycja, nie jak polecenie.",
     ex_ph="khun khít wâa raw khuan {ph} kan mǎi khráp", ex_th="คุณคิดว่าเราควร{th}กันไหมครับ",
     items=[
       ("Uważam, że powinniśmy raczej poczekać.", "czekać", "Uważasz, że powinniśmy poczekać?"),
       ("Uważam, że powinniśmy raczej zapytać.", "pytać", "Uważasz, że powinniśmy zapytać?"),
       ("Uważam, że powinniśmy raczej sprawdzić.", "szukać", "Uważasz, że powinniśmy poszukać?"),
       ("Uważam, że powinniśmy raczej zacząć.", "zaczynać", "Uważasz, że powinniśmy zacząć?"),
       ("Uważam, że powinniśmy raczej przestać.", "przestać", "Uważasz, że powinniśmy przestać?"),
       ("Uważam, że powinniśmy raczej wrócić.", "wracać", "Uważasz, że powinniśmy wrócić?"),
       ("Uważam, że powinniśmy raczej to zmienić.", "zmieniać", "Uważasz, że powinniśmy to zmienić?"),
       ("Uważam, że powinniśmy raczej anulować.", "anulować", "Uważasz, że powinniśmy anulować?"),
       ("Uważam, że powinniśmy raczej zarezerwować.", "rezerwować", "Uważasz, że powinniśmy zarezerwować?"),
       ("Uważam, że powinniśmy raczej zapłacić od razu.", "płacić", "Uważasz, że powinniśmy zapłacić?"),
       ("Uważam, że powinniśmy raczej podpisać.", "podpisać", "Uważasz, że powinniśmy podpisać?"),
       ("Uważam, że powinniśmy raczej wysłać to dziś.", "wysyłać", "Uważasz, że powinniśmy wysłać?"),
       ("Uważam, że powinniśmy raczej zadzwonić.", "dzwonić", "Uważasz, że powinniśmy zadzwonić?"),
       ("Uważam, że powinniśmy raczej się spotkać.", "spotykać", "Uważasz, że powinniśmy się spotkać?"),
       ("Uważam, że powinniśmy raczej odpocząć.", "odpoczywać", "Uważasz, że powinniśmy odpocząć?"),
       ("Uważam, że powinniśmy raczej pomóc.", "pomagać", "Uważasz, że powinniśmy pomóc?"),
       ("Uważam, że powinniśmy raczej wynająć coś innego.", "wynajmować", "Uważasz, że powinniśmy wynająć?"),
       ("Uważam, że powinniśmy raczej to kupić.", "kupować", "Uważasz, że powinniśmy to kupić?"),
       ("Uważam, że powinniśmy raczej to sprzedać.", "sprzedawać", "Uważasz, że powinniśmy to sprzedać?"),
       ("Uważam, że powinniśmy raczej to naprawić.", "naprawiać", "Uważasz, że powinniśmy to naprawić?"),
       ("Uważam, że powinniśmy raczej to przeczytać w całości.", "czytać", "Uważasz, że powinniśmy to przeczytać?"),
       ("Uważam, że powinniśmy raczej to zapisać.", "pisać", "Uważasz, że powinniśmy to zapisać?"),
       ("Uważam, że powinniśmy raczej wypełnić wniosek.", "wypełnić formularz", "Uważasz, że powinniśmy wypełnić?"),
       ("Uważam, że powinniśmy raczej to pokazać klientowi.", "pokazać", "Uważasz, że powinniśmy pokazać?"),
       ("Uważam, że powinniśmy raczej odpowiedzieć na piśmie.", "odpowiadać", "Uważasz, że powinniśmy odpowiedzieć?"),
       ("Uważam, że powinniśmy raczej się uczyć razem.", "uczyć się", "Uważasz, że powinniśmy uczyć się razem?"),
       ("Uważam, że powinniśmy raczej pojechać tam osobiście.", "iść / jechać", "Uważasz, że powinniśmy pojechać?"),
       ("Uważam, że powinniśmy raczej wyjść wcześniej.", "wychodzić", "Uważasz, że powinniśmy wyjść wcześniej?"),
       ("Uważam, że powinniśmy raczej się spakować dziś.", "pakować się", "Uważasz, że powinniśmy się spakować?"),
       ("Uważam, że powinniśmy raczej zamówić więcej.", "zamawiać", "Uważasz, że powinniśmy zamówić więcej?"),
       ("Uważam, że powinniśmy raczej spróbować.", "próbować (smakować)", "Uważasz, że powinniśmy spróbować?"),
       ("Uważam, że powinniśmy raczej to sprawdzić na miejscu i obejrzeć.", "oglądać", "Uważasz, że powinniśmy obejrzeć?"),
       ("Uważam, że powinniśmy raczej wybrać inaczej.", "wybierać", "Uważasz, że powinniśmy wybrać inaczej?"),
       ("Uważam, że powinniśmy raczej to razem policzyć.", "policzyć rachunek", "Uważasz, że powinniśmy policzyć?"),
       ("Uważam, że powinniśmy raczej pracować nad tym dłużej.", "pracować", "Uważasz, że powinniśmy popracować dłużej?"),
       ("Uważam, że powinniśmy raczej użyć innego rozwiązania.", "używać", "Uważasz, że powinniśmy użyć czegoś innego?"),
     ]),

# =====================================================================
# khaw-thoot khrap thii phom … mai dai — przeprosiny za niemoznosc
# =====================================================================
dict(key="THIIMAIDAI", ty="sentence", cat="Podstawy i grzeczność", sub="Przeprosiny", reg="f",
     ph="khǎw-thôot khráp thîi phǒm {ph} mâi dâai", th="ขอโทษครับที่ผม{th}ไม่ได้",
     lit="thîi … mâi dâai = za to, że nie udało mi się …",
     note="Przeprosiny za niemożność, nie za złą wolę. „mâi dâai” zdejmuje z ciebie zarzut celowego zaniedbania.",
     ex_ph="mâi pen rai khráp thîi {ph} mâi dâai", ex_th="ไม่เป็นไรครับที่{th}ไม่ได้",
     items=[
       ("Przepraszam, że nie udało mi się przyjść.", "przyjść / przyjechać", "Nic się nie stało, że nie przyszedłeś."),
       ("Przepraszam, że nie udało mi się zadzwonić.", "dzwonić", "Nic się nie stało, że nie zadzwoniłeś."),
       ("Przepraszam, że nie udało mi się odpowiedzieć.", "odpowiadać", "Nic się nie stało, że nie odpowiedziałeś."),
       ("Przepraszam, że nie udało mi się wysłać.", "wysyłać", "Nic się nie stało, że nie wysłałeś."),
       ("Przepraszam, że nie udało mi się pomóc.", "pomagać", "Nic się nie stało, że nie pomogłeś."),
       ("Przepraszam, że nie udało mi się poczekać.", "czekać", "Nic się nie stało, że nie poczekałeś."),
       ("Przepraszam, że nie udało mi się wrócić na czas.", "wracać", "Nic się nie stało, że nie wróciłeś."),
       ("Przepraszam, że nie udało mi się zapłacić.", "płacić", "Nic się nie stało, że nie zapłaciłeś."),
       ("Przepraszam, że nie udało mi się podpisać.", "podpisać", "Nic się nie stało, że nie podpisałeś."),
       ("Przepraszam, że nie udało mi się zarezerwować.", "rezerwować", "Nic się nie stało, że nie zarezerwowałeś."),
       ("Przepraszam, że nie udało mi się zamówić.", "zamawiać", "Nic się nie stało, że nie zamówiłeś."),
       ("Przepraszam, że nie udało mi się anulować.", "anulować", "Nic się nie stało, że nie anulowałeś."),
       ("Przepraszam, że nie udało mi się przeczytać.", "czytać", "Nic się nie stało, że nie przeczytałeś."),
       ("Przepraszam, że nie udało mi się napisać.", "pisać", "Nic się nie stało, że nie napisałeś."),
       ("Przepraszam, że nie udało mi się przygotować.", "robić", "Nic się nie stało, że nie zrobiłeś."),
       ("Przepraszam, że nie udało mi się tego znaleźć.", "znaleźć", "Nic się nie stało, że nie znalazłeś."),
       ("Przepraszam, że nie udało mi się tego naprawić.", "naprawiać", "Nic się nie stało, że nie naprawiłeś."),
       ("Przepraszam, że nie udało mi się tego pokazać.", "pokazać", "Nic się nie stało, że nie pokazałeś."),
       ("Przepraszam, że nie udało mi się zapytać.", "pytać", "Nic się nie stało, że nie zapytałeś."),
       ("Przepraszam, że nie udało mi się przyjść i posłuchać.", "słuchać", "Nic się nie stało, że nie posłuchałeś."),
       ("Przepraszam, że nie udało mi się odebrać.", "odbierać", "Nic się nie stało, że nie odebrałeś."),
       ("Przepraszam, że nie udało mi się wypełnić formularza.", "wypełnić formularz", "Nic się nie stało, że nie wypełniłeś."),
       ("Przepraszam, że nie udało mi się spotkać.", "spotykać", "Nic się nie stało, że się nie spotkaliśmy."),
       ("Przepraszam, że nie udało mi się ugotować.", "gotować", "Nic się nie stało, że nie ugotowałeś."),
       ("Przepraszam, że nie udało mi się posprzątać.", "sprzątać", "Nic się nie stało, że nie posprzątałeś."),
       ("Przepraszam, że nie udało mi się wyprać.", "prać", "Nic się nie stało, że nie wyprałeś."),
       ("Przepraszam, że nie udało mi się spakować.", "pakować się", "Nic się nie stało, że się nie spakowałeś."),
       ("Przepraszam, że nie udało mi się pouczyć.", "uczyć się", "Nic się nie stało, że się nie uczyłeś."),
       ("Przepraszam, że nie udało mi się popracować nad tym.", "pracować", "Nic się nie stało, że nie popracowałeś."),
       ("Przepraszam, że nie udało mi się tam pojechać.", "iść / jechać", "Nic się nie stało, że nie pojechałeś."),
       ("Przepraszam, że nie udało mi się kupić.", "kupować", "Nic się nie stało, że nie kupiłeś."),
       ("Przepraszam, że nie udało mi się sprzedać.", "sprzedawać", "Nic się nie stało, że nie sprzedałeś."),
       ("Przepraszam, że nie udało mi się wynająć.", "wynajmować", "Nic się nie stało, że nie wynająłeś."),
       ("Przepraszam, że nie udało mi się tego zapamiętać.", "pamiętać", "Nic się nie stało, że nie zapamiętałeś."),
       ("Przepraszam, że nie udało mi się wybrać na czas.", "wybierać", "Nic się nie stało, że nie wybrałeś."),
       ("Przepraszam, że nie udało mi się wstać wcześniej.", "wstawać", "Nic się nie stało, że nie wstałeś wcześniej."),
     ]),

# =====================================================================
# mai waa ja … rue mai phom kaw khao-jai — akceptacja obu wyjsc
# =====================================================================
dict(key="RUEMAIKAW", ty="sentence", cat="Podstawy i grzeczność", sub="Łagodzenie", reg="n",
     ph="mâi wâa jà {ph} rǔe mâi phǒm kâw khâo-jai khráp", th="ไม่ว่าจะ{th}หรือไม่ผมก็เข้าใจครับ",
     lit="mâi wâa jà … rǔe mâi = czy tak, czy nie",
     note="Zdejmuje presję z rozmówcy przed jego decyzją. Bardzo skuteczne, gdy prosisz o coś kłopotliwego.",
     ex_ph="khun jà {ph} rǔe mâi kâw bàwk dâai loei khráp", ex_th="คุณจะ{th}หรือไม่ก็บอกได้เลยครับ",
     items=[
       ("Zrozumiem, czy przyjdziesz, czy nie.", "przyjść / przyjechać", "Powiedz śmiało, czy przyjdziesz."),
       ("Zrozumiem, czy pomożesz, czy nie.", "pomagać", "Powiedz śmiało, czy pomożesz."),
       ("Zrozumiem, czy zapłacisz, czy nie.", "płacić", "Powiedz śmiało, czy zapłacisz."),
       ("Zrozumiem, czy podpiszesz, czy nie.", "podpisać", "Powiedz śmiało, czy podpiszesz."),
       ("Zrozumiem, czy zadzwonisz, czy nie.", "dzwonić", "Powiedz śmiało, czy zadzwonisz."),
       ("Zrozumiem, czy odpowiesz, czy nie.", "odpowiadać", "Powiedz śmiało, czy odpowiesz."),
       ("Zrozumiem, czy kupisz, czy nie.", "kupować", "Powiedz śmiało, czy kupisz."),
       ("Zrozumiem, czy sprzedasz, czy nie.", "sprzedawać", "Powiedz śmiało, czy sprzedasz."),
       ("Zrozumiem, czy wynajmiesz, czy nie.", "wynajmować", "Powiedz śmiało, czy wynajmiesz."),
       ("Zrozumiem, czy zarezerwujesz, czy nie.", "rezerwować", "Powiedz śmiało, czy zarezerwujesz."),
       ("Zrozumiem, czy zamówisz, czy nie.", "zamawiać", "Powiedz śmiało, czy zamówisz."),
       ("Zrozumiem, czy anulujesz, czy nie.", "anulować", "Powiedz śmiało, czy anulujesz."),
       ("Zrozumiem, czy zmienisz, czy nie.", "zmieniać", "Powiedz śmiało, czy zmienisz."),
       ("Zrozumiem, czy wrócisz, czy nie.", "wracać", "Powiedz śmiało, czy wrócisz."),
       ("Zrozumiem, czy poczekasz, czy nie.", "czekać", "Powiedz śmiało, czy poczekasz."),
       ("Zrozumiem, czy się spotkamy, czy nie.", "spotykać", "Powiedz śmiało, czy się spotkamy."),
       ("Zrozumiem, czy pojedziesz, czy nie.", "iść / jechać", "Powiedz śmiało, czy pojedziesz."),
       ("Zrozumiem, czy zjesz z nami, czy nie.", "jeść", "Powiedz śmiało, czy zjesz z nami."),
       ("Zrozumiem, czy się napijesz, czy nie.", "pić", "Powiedz śmiało, czy się napijesz."),
       ("Zrozumiem, czy będziesz pracował, czy nie.", "pracować", "Powiedz śmiało, czy będziesz pracował."),
       ("Zrozumiem, czy będziesz się uczył, czy nie.", "uczyć się", "Powiedz śmiało, czy będziesz się uczył."),
       ("Zrozumiem, czy przeczytasz, czy nie.", "czytać", "Powiedz śmiało, czy przeczytasz."),
       ("Zrozumiem, czy napiszesz, czy nie.", "pisać", "Powiedz śmiało, czy napiszesz."),
       ("Zrozumiem, czy wyślesz, czy nie.", "wysyłać", "Powiedz śmiało, czy wyślesz."),
       ("Zrozumiem, czy odbierzesz, czy nie.", "odbierać", "Powiedz śmiało, czy odbierzesz."),
       ("Zrozumiem, czy pokażesz, czy nie.", "pokazać", "Powiedz śmiało, czy pokażesz."),
       ("Zrozumiem, czy pożyczysz, czy nie.", "pożyczyć", "Powiedz śmiało, czy pożyczysz."),
       ("Zrozumiem, czy naprawisz, czy nie.", "naprawiać", "Powiedz śmiało, czy naprawisz."),
       ("Zrozumiem, czy posprzątasz, czy nie.", "sprzątać", "Powiedz śmiało, czy posprzątasz."),
       ("Zrozumiem, czy ugotujesz, czy nie.", "gotować", "Powiedz śmiało, czy ugotujesz."),
       ("Zrozumiem, czy spróbujesz, czy nie.", "próbować (smakować)", "Powiedz śmiało, czy spróbujesz."),
       ("Zrozumiem, czy wybierzesz, czy nie.", "wybierać", "Powiedz śmiało, czy wybierzesz."),
       ("Zrozumiem, czy zapytasz, czy nie.", "pytać", "Powiedz śmiało, czy zapytasz."),
       ("Zrozumiem, czy się spakujesz, czy nie.", "pakować się", "Powiedz śmiało, czy się spakujesz."),
       ("Zrozumiem, czy zaczniesz, czy nie.", "zaczynać", "Powiedz śmiało, czy zaczniesz."),
       ("Zrozumiem, czy przestaniesz, czy nie.", "przestać", "Powiedz śmiało, czy przestaniesz."),
     ]),

# =====================================================================
# tham yang-ngai thueng ja … dai dii khuen — pytanie o doskonalenie
# =====================================================================
dict(key="DIIKHUEN", ty="sentence", cat="Praca i nauka", sub="Rozwój", reg="n",
     ph="tham yang-ngai thǔeng jà {ph} dâai dii khûen khráp", th="ทำยังไงถึงจะ{th}ได้ดีขึ้นครับ",
     lit="tham yang-ngai thǔeng jà … = co zrobić, żeby …",
     note="Pytanie o radę, które w tajskiej kulturze buduje relację: prosisz rozmówcę o rolę nauczyciela.",
     ex_ph="phǒm yàak {ph} dâai dii khûen khráp chûai náe-nam nòi", ex_th="ผมอยาก{th}ได้ดีขึ้นครับ ช่วยแนะนำหน่อย",
     items=[
       ("Co zrobić, żeby lepiej mówić?", "mówić", "Chcę mówić lepiej — poradzisz coś?"),
       ("Co zrobić, żeby lepiej słuchać ze zrozumieniem?", "słuchać", "Chcę lepiej rozumieć ze słuchu — poradzisz coś?"),
       ("Co zrobić, żeby lepiej czytać?", "czytać", "Chcę lepiej czytać — poradzisz coś?"),
       ("Co zrobić, żeby lepiej pisać?", "pisać", "Chcę lepiej pisać — poradzisz coś?"),
       ("Co zrobić, żeby lepiej się uczyć?", "uczyć się", "Chcę lepiej się uczyć — poradzisz coś?"),
       ("Co zrobić, żeby lepiej pracować?", "pracować", "Chcę lepiej pracować — poradzisz coś?"),
       ("Co zrobić, żeby lepiej gotować?", "gotować", "Chcę lepiej gotować — poradzisz coś?"),
       ("Co zrobić, żeby lepiej prowadzić samochód?", "prowadzić samochód", "Chcę lepiej prowadzić — poradzisz coś?"),
       ("Co zrobić, żeby lepiej pływać?", "pływać", "Chcę lepiej pływać — poradzisz coś?"),
       ("Co zrobić, żeby lepiej biegać?", "biegać", "Chcę lepiej biegać — poradzisz coś?"),
       ("Co zrobić, żeby lepiej śpiewać?", "śpiewać", "Chcę lepiej śpiewać — poradzisz coś?"),
       ("Co zrobić, żeby lepiej tańczyć?", "tańczyć", "Chcę lepiej tańczyć — poradzisz coś?"),
       ("Co zrobić, żeby lepiej rozmawiać z ludźmi?", "rozmawiać", "Chcę lepiej rozmawiać — poradzisz coś?"),
       ("Co zrobić, żeby lepiej odpowiadać na trudne pytania?", "odpowiadać", "Chcę lepiej odpowiadać — poradzisz coś?"),
       ("Co zrobić, żeby lepiej pytać?", "pytać", "Chcę lepiej pytać — poradzisz coś?"),
       ("Co zrobić, żeby lepiej pamiętać słówka?", "pamiętać", "Chcę lepiej pamiętać — poradzisz coś?"),
       ("Co zrobić, żeby lepiej rozumieć w rozmowie?", "rozumieć", "Chcę lepiej rozumieć — poradzisz coś?"),
       ("Co zrobić, żeby lepiej wybierać?", "wybierać", "Chcę lepiej wybierać — poradzisz coś?"),
       ("Co zrobić, żeby lepiej się pakować?", "pakować się", "Chcę lepiej się pakować — poradzisz coś?"),
       ("Co zrobić, żeby lepiej naprawiać rzeczy?", "naprawiać", "Chcę lepiej naprawiać — poradzisz coś?"),
       ("Co zrobić, żeby lepiej negocjować przy kupowaniu?", "kupować", "Chcę lepiej kupować — poradzisz coś?"),
       ("Co zrobić, żeby lepiej sprzedawać?", "sprzedawać", "Chcę lepiej sprzedawać — poradzisz coś?"),
       ("Co zrobić, żeby lepiej pomagać innym?", "pomagać", "Chcę lepiej pomagać — poradzisz coś?"),
       ("Co zrobić, żeby lepiej odpoczywać?", "odpoczywać", "Chcę lepiej odpoczywać — poradzisz coś?"),
       ("Co zrobić, żeby lepiej spać?", "spać", "Chcę lepiej spać — poradzisz coś?"),
       ("Co zrobić, żeby lepiej wstawać rano?", "wstawać", "Chcę łatwiej wstawać — poradzisz coś?"),
       ("Co zrobić, żeby lepiej się budzić bez budzika?", "budzić się", "Chcę budzić się sam — poradzisz coś?"),
       ("Co zrobić, żeby lepiej robić zdjęcia?", "robić zdjęcia", "Chcę lepiej fotografować — poradzisz coś?"),
       ("Co zrobić, żeby lepiej planować i rezerwować?", "rezerwować", "Chcę lepiej rezerwować — poradzisz coś?"),
       ("Co zrobić, żeby lepiej zamawiać w restauracji?", "zamawiać", "Chcę lepiej zamawiać — poradzisz coś?"),
       ("Co zrobić, żeby lepiej korzystać z aplikacji?", "używać", "Chcę lepiej korzystać — poradzisz coś?"),
       ("Co zrobić, żeby lepiej zwiedzać w krótkim czasie?", "zwiedzać", "Chcę lepiej zwiedzać — poradzisz coś?"),
       ("Co zrobić, żeby lepiej szukać informacji?", "szukać", "Chcę lepiej szukać — poradzisz coś?"),
       ("Co zrobić, żeby lepiej wypełniać formularze?", "wypełnić formularz", "Chcę lepiej wypełniać — poradzisz coś?"),
       ("Co zrobić, żeby lepiej sprzątać w mniej czasu?", "sprzątać", "Chcę sprzątać sprawniej — poradzisz coś?"),
       ("Co zrobić, żeby lepiej się czuć na co dzień?", "czuć się", "Chcę czuć się lepiej — poradzisz coś?"),
     ]),

# =====================================================================
# phom khaw sa-noe hai … kawn — propozycja kolejnosci
# =====================================================================
dict(key="SANOEKAWN", ty="sentence", cat="Praca i nauka", sub="Sugestie", reg="f",
     ph="phǒm khǎw sà-nǒoe hâi {ph} kàwn khráp", th="ผมขอเสนอให้{th}ก่อนครับ",
     lit="sà-nǒoe hâi … kàwn = proponuję, żeby najpierw …",
     note="Propozycja kolejności działań na zebraniu. „khǎw sà-nǒoe” brzmi kompetentnie, ale nie narzucająco.",
     ex_ph="phǒm wâa {ph} kàwn dii kwàa mǎi khráp", ex_th="ผมว่า{th}ก่อนดีกว่าไหมครับ",
     items=[
       ("Proponuję, żeby najpierw sprawdzić.", "szukać", "Może najpierw sprawdźmy?"),
       ("Proponuję, żeby najpierw zapytać.", "pytać", "Może najpierw zapytajmy?"),
       ("Proponuję, żeby najpierw poczekać.", "czekać", "Może najpierw poczekajmy?"),
       ("Proponuję, żeby najpierw przeczytać.", "czytać", "Może najpierw przeczytajmy?"),
       ("Proponuję, żeby najpierw zapisać ustalenia.", "pisać", "Może najpierw zapiszmy?"),
       ("Proponuję, żeby najpierw zadzwonić.", "dzwonić", "Może najpierw zadzwońmy?"),
       ("Proponuję, żeby najpierw wysłać zapytanie.", "wysyłać", "Może najpierw wyślijmy?"),
       ("Proponuję, żeby najpierw się spotkać.", "spotykać", "Może najpierw się spotkajmy?"),
       ("Proponuję, żeby najpierw obejrzeć.", "oglądać", "Może najpierw obejrzyjmy?"),
       ("Proponuję, żeby najpierw spróbować.", "próbować (smakować)", "Może najpierw spróbujmy?"),
       ("Proponuję, żeby najpierw przymierzyć.", "przymierzać / próbować", "Może najpierw przymierzmy?"),
       ("Proponuję, żeby najpierw policzyć koszty.", "policzyć rachunek", "Może najpierw policzmy?"),
       ("Proponuję, żeby najpierw zapłacić zaliczkę.", "płacić", "Może najpierw zapłaćmy?"),
       ("Proponuję, żeby najpierw zarezerwować.", "rezerwować", "Może najpierw zarezerwujmy?"),
       ("Proponuję, żeby najpierw zamówić.", "zamawiać", "Może najpierw zamówmy?"),
       ("Proponuję, żeby najpierw wypełnić wniosek.", "wypełnić formularz", "Może najpierw wypełnijmy?"),
       ("Proponuję, żeby najpierw podpisać wstępną wersję.", "podpisać", "Może najpierw podpiszmy wstępnie?"),
       ("Proponuję, żeby najpierw pokazać klientowi.", "pokazać", "Może najpierw pokażmy?"),
       ("Proponuję, żeby najpierw wybrać wariant.", "wybierać", "Może najpierw wybierzmy?"),
       ("Proponuję, żeby najpierw naprawić usterkę.", "naprawiać", "Może najpierw naprawmy?"),
       ("Proponuję, żeby najpierw posprzątać.", "sprzątać", "Może najpierw posprzątajmy?"),
       ("Proponuję, żeby najpierw się spakować.", "pakować się", "Może najpierw się spakujmy?"),
       ("Proponuję, żeby najpierw odpocząć.", "odpoczywać", "Może najpierw odpocznijmy?"),
       ("Proponuję, żeby najpierw zjeść.", "jeść", "Może najpierw zjedzmy?"),
       ("Proponuję, żeby najpierw wrócić do biura.", "wracać", "Może najpierw wróćmy?"),
       ("Proponuję, żeby najpierw pojechać na miejsce.", "iść / jechać", "Może najpierw pojedźmy?"),
       ("Proponuję, żeby najpierw zacząć od małej próby.", "zaczynać", "Może najpierw zacznijmy od próby?"),
       ("Proponuję, żeby najpierw przestać i przemyśleć.", "przestać", "Może najpierw przestańmy?"),
       ("Proponuję, żeby najpierw wynająć na miesiąc.", "wynajmować", "Może najpierw wynajmijmy na miesiąc?"),
       ("Proponuję, żeby najpierw kupić jedną sztukę.", "kupować", "Może najpierw kupmy jedną?"),
       ("Proponuję, żeby najpierw pomóc temu klientowi.", "pomagać", "Może najpierw jemu pomóżmy?"),
       ("Proponuję, żeby najpierw odpowiedzieć na maile.", "odpowiadać", "Może najpierw odpowiedzmy?"),
       ("Proponuję, żeby najpierw odebrać przesyłkę.", "odbierać", "Może najpierw odbierzmy?"),
       ("Proponuję, żeby najpierw się nauczyć obsługi.", "uczyć się", "Może najpierw się nauczmy?"),
       ("Proponuję, żeby najpierw to wypróbować w praktyce.", "używać", "Może najpierw to wypróbujmy?"),
       ("Proponuję, żeby najpierw anulować stare zamówienie.", "anulować", "Może najpierw anulujmy stare?"),
     ]),

# =====================================================================
# chuai … hai duai na khrap ya luem — uprzejme upomnienie
# =====================================================================
dict(key="YAALUEM", ty="sentence", cat="Podstawy i grzeczność", sub="Przypomnienia", reg="n",
     ph="chûai {ph} dûai ná khráp yàa luem", th="ช่วย{th}ด้วยนะครับ อย่าลืม",
     lit="yàa luem = nie zapomnij",
     note="Przypomnienie zamiast pretensji. „chûai … dûai ná khráp” zmiękcza je do prośby, a „yàa luem” utrwala.",
     ex_ph="{ph} rǔe yang khráp yàa luem ná", ex_th="{th}หรือยังครับ อย่าลืมนะ",
     items=[
       ("Proszę o tym pamiętać i zapłacić.", "płacić", "Zapłaciłeś już? Nie zapomnij."),
       ("Proszę o tym pamiętać i podpisać.", "podpisać", "Podpisałeś już? Nie zapomnij."),
       ("Proszę o tym pamiętać i wysłać.", "wysyłać", "Wysłałeś już? Nie zapomnij."),
       ("Proszę o tym pamiętać i zadzwonić.", "dzwonić", "Zadzwoniłeś już? Nie zapomnij."),
       ("Proszę o tym pamiętać i odpowiedzieć.", "odpowiadać", "Odpowiedziałeś już? Nie zapomnij."),
       ("Proszę o tym pamiętać i zarezerwować.", "rezerwować", "Zarezerwowałeś już? Nie zapomnij."),
       ("Proszę o tym pamiętać i anulować.", "anulować", "Anulowałeś już? Nie zapomnij."),
       ("Proszę o tym pamiętać i wypełnić formularz.", "wypełnić formularz", "Wypełniłeś już? Nie zapomnij."),
       ("Proszę o tym pamiętać i przeczytać.", "czytać", "Przeczytałeś już? Nie zapomnij."),
       ("Proszę o tym pamiętać i zapisać.", "pisać", "Zapisałeś już? Nie zapomnij."),
       ("Proszę o tym pamiętać i zamknąć.", "zamykać", "Zamknąłeś już? Nie zapomnij."),
       ("Proszę o tym pamiętać i otworzyć.", "otwierać", "Otworzyłeś już? Nie zapomnij."),
       ("Proszę o tym pamiętać i odebrać.", "odbierać", "Odebrałeś już? Nie zapomnij."),
       ("Proszę o tym pamiętać i zamówić.", "zamawiać", "Zamówiłeś już? Nie zapomnij."),
       ("Proszę o tym pamiętać i kupić.", "kupować", "Kupiłeś już? Nie zapomnij."),
       ("Proszę o tym pamiętać i wrócić na czas.", "wracać", "Wróciłeś już? Nie zapomnij o godzinie."),
       ("Proszę o tym pamiętać i przyjść punktualnie.", "przyjść / przyjechać", "Przyszedłeś już? Nie zapomnij."),
       ("Proszę o tym pamiętać i się spakować.", "pakować się", "Spakowałeś się już? Nie zapomnij."),
       ("Proszę o tym pamiętać i posprzątać.", "sprzątać", "Posprzątałeś już? Nie zapomnij."),
       ("Proszę o tym pamiętać i wyprać.", "prać", "Wyprałeś już? Nie zapomnij."),
       ("Proszę o tym pamiętać i umyć.", "myć", "Umyłeś już? Nie zapomnij."),
       ("Proszę o tym pamiętać i naprawić.", "naprawiać", "Naprawiłeś już? Nie zapomnij."),
       ("Proszę o tym pamiętać i pokazać dokumenty.", "pokazać", "Pokazałeś już? Nie zapomnij."),
       ("Proszę o tym pamiętać i zapytać kierownika.", "pytać", "Zapytałeś już? Nie zapomnij."),
       ("Proszę o tym pamiętać i sprawdzić.", "szukać", "Sprawdziłeś już? Nie zapomnij."),
       ("Proszę o tym pamiętać i wybrać wariant.", "wybierać", "Wybrałeś już? Nie zapomnij."),
       ("Proszę o tym pamiętać i się pouczyć.", "uczyć się", "Pouczyłeś się już? Nie zapomnij."),
       ("Proszę o tym pamiętać i odpocząć.", "odpoczywać", "Odpocząłeś już? Nie zapomnij."),
       ("Proszę o tym pamiętać i zjeść.", "jeść", "Zjadłeś już? Nie zapomnij."),
       ("Proszę o tym pamiętać i pić dużo wody.", "pić", "Piłeś już wodę? Nie zapomnij."),
       ("Proszę o tym pamiętać i wziąć to ze sobą.", "brać", "Wziąłeś już? Nie zapomnij."),
       ("Proszę o tym pamiętać i oddać klucze.", "dawać", "Oddałeś już? Nie zapomnij."),
       ("Proszę o tym pamiętać i zrobić zdjęcia licznika.", "robić zdjęcia", "Zrobiłeś już zdjęcia? Nie zapomnij."),
       ("Proszę o tym pamiętać i wysiąść na właściwym przystanku.", "wysiadać", "Wysiadłeś już? Nie zapomnij."),
       ("Proszę o tym pamiętać i się przesiąść.", "przesiadać się", "Przesiadłeś się już? Nie zapomnij."),
       ("Proszę o tym pamiętać i wstać wcześniej.", "wstawać", "Wstałeś już? Nie zapomnij."),
     ]),
]
