# -*- coding: utf-8 -*-
"""Leksyka etapu 5 (B2) — czesc A.

Zakres: prowadzenie dluzszej rozmowy. Wypelniacze, granie na czas, zabieranie
i oddawanie glosu, przerywanie, wracanie do tematu, parafraza, sprawdzanie
zrozumienia, sygnalizowanie klopotu ze slowem.

Krotka: (polski, fonetyka, tajski, kategoria, podkategoria, typ, freq, rejestr,
         notatka, znaczenie doslowne, przyklad)
Rejestr: n = neutralny, f = formalny, i = nieformalny, p = potoczny
Przyklad: (polski, fonetyka, tajski)
"""

CORE_A = [

# =====================================================================
# WYPELNIACZE I GRANIE NA CZAS
# =====================================================================
("no wiesz, jakby", "bàep wâa", "แบบว่า", "Small talk", "Wypełniacze", "phrase", 5, "p",
 "Najczęstszy tajski wypełniacz w mowie młodych. W rozmowie z urzędnikiem brzmi niechlujnie.", "typu że",
 ("No wiesz, jakby nie miałem czasu.", "bàep wâa phǒm mâi mii wee-laa ná khráp", "แบบว่าผมไม่มีเวลานะครับ")),
("chodzi o to, że", "khue wâa", "คือว่า", "Small talk", "Wypełniacze", "phrase", 5, "n",
 "„khue wâa” otwiera wyjaśnienie i kupuje sekundę na ułożenie zdania. Bezpieczne w każdym rejestrze.", "to jest że",
 ("Chodzi o to, że dziś nie dam rady.", "khue wâa wan níi phǒm mâi wǎai khráp", "คือว่าวันนี้ผมไม่ไหวครับ")),
("jak by to powiedzieć", "jà phûut yang-ngai dii", "จะพูดยังไงดี", "Small talk", "Wypełniacze", "phrase", 4, "n",
 "Kupuje czas i sygnalizuje, że temat jest delikatny. Rozmówca zwykle poczeka.", "jak powiedzieć dobrze",
 ("Jak by to powiedzieć… trochę mnie to zawiodło.", "jà phûut yang-ngai dii khráp phǒm nòi jai nít nùeng", "จะพูดยังไงดีครับ ผมน้อยใจนิดหนึ่ง")),
("coś w tym stylu", "à-rai prà-maan nán", "อะไรประมาณนั้น", "Small talk", "Wypełniacze", "phrase", 5, "n",
 "Zamyka wyliczenie, którego nie chcesz kończyć. Bardzo częste na końcu zdania.", "coś mniej więcej tak",
 ("Kawa, herbata, coś w tym stylu.", "kaa-fae chaa à-rai prà-maan nán khráp", "กาแฟ ชา อะไรประมาณนั้นครับ")),
("mniej więcej tak, że", "prà-maan wâa", "ประมาณว่า", "Small talk", "Wypełniacze", "phrase", 4, "p",
 "Zapowiada streszczenie cudzej wypowiedzi. Potoczne, ale słyszy się je też w biurze.", "mniej więcej że",
 ("Powiedział mniej więcej tak, że nie zdąży.", "khǎo bàwk prà-maan wâa jà maa mâi than", "เขาบอกประมาณว่าจะมาไม่ทัน")),
("no właśnie o to chodzi", "nân ngai lâ", "นั่นไงล่ะ", "Small talk", "Wypełniacze", "phrase", 4, "p",
 "Potwierdzenie z satysfakcją: rozmówca sam doszedł do twojej myśli.", "",
 ("No właśnie o to chodzi, mówiłem to samo.", "nân ngai lâ phǒm phûut yàang nán mǎi", "นั่นไงล่ะ ผมพูดอย่างนั้นเหมือนกัน")),
("zaraz, chwileczkę", "dǐao kàwn ná khráp", "เดี๋ยวก่อนนะครับ", "Small talk", "Wypełniacze", "phrase", 5, "n",
 "Zatrzymuje rozmówcę bez obrażania go. „dǐao” samo w sobie brzmi opryskliwie.", "chwilę najpierw",
 ("Zaraz, chwileczkę, muszę to sprawdzić.", "dǐao kàwn ná khráp phǒm khǎw chék kàwn", "เดี๋ยวก่อนนะครับ ผมขอเช็คก่อน")),
("niech pomyślę", "khǎw khít kàwn ná khráp", "ขอคิดก่อนนะครับ", "Small talk", "Wypełniacze", "phrase", 4, "n",
 "Grzeczne odroczenie odpowiedzi. Lepsze niż milczenie, które Taj odbierze jako niezadowolenie.", "proszę pomyśleć najpierw",
 ("Niech pomyślę, oddzwonię za godzinę.", "khǎw khít kàwn ná khráp dǐao thoo klàp nai nùeng chûa-moong", "ขอคิดก่อนนะครับ เดี๋ยวโทรกลับในหนึ่งชั่วโมง")),
("że tak powiem", "phûut dâai wâa", "พูดได้ว่า", "Small talk", "Wypełniacze", "phrase", 3, "f",
 "Uprzedza określenie, które może zabrzmieć mocno. Rejestr bardziej staranny.", "można powiedzieć że",
 ("To był, że tak powiem, trudny rok.", "pen pii thîi phûut dâai wâa nàk khráp", "เป็นปีที่พูดได้ว่าหนักครับ")),
("prawdę mówiąc, sam nie wiem", "jing jing láew phǒm kâw mâi nâe-jai", "จริงๆ แล้วผมก็ไม่แน่ใจ",
 "Small talk", "Wypełniacze", "sentence", 4, "n",
 "Przyznanie się do niewiedzy bez utraty twarzy — bardzo tajskie rozwiązanie.", "",
 ("Prawdę mówiąc, sam nie wiem, kto to prowadzi.", "jing jing láew phǒm kâw mâi nâe-jai wâa khrai duu-lae", "จริงๆ แล้วผมก็ไม่แน่ใจว่าใครดูแล")),
("no dobrze, powiedzmy", "ao pen wâa", "เอาเป็นว่า", "Gramatyka użytkowa", "Prowadzenie rozmowy", "phrase", 4, "n",
 "Zamyka dyskusję roboczym ustaleniem. Bardzo przydatne w negocjacjach.", "weźmy że",
 ("No dobrze, powiedzmy, że spotykamy się o piątej.", "ao pen wâa jôe kan hâa moong yen ná khráp", "เอาเป็นว่าเจอกันห้าโมงเย็นนะครับ")),
("czyli ustalamy, że", "tòk long wâa", "ตกลงว่า", "Gramatyka użytkowa", "Prowadzenie rozmowy", "phrase", 4, "n",
 "Wymusza potwierdzenie. Po tym zwrocie Taj rzadko wycofa się z ustalenia.", "zgadzamy się że",
 ("Czyli ustalamy, że płacimy po odbiorze.", "tòk long wâa jàai lǎng ráp khǎwng ná khráp", "ตกลงว่าจ่ายหลังรับของนะครับ")),
("i jeszcze jedno", "láew kâw ìik yàang nùeng", "แล้วก็อีกอย่างหนึ่ง", "Gramatyka użytkowa", "Prowadzenie rozmowy", "phrase", 4, "n",
 "Dokłada punkt, zanim rozmowa się zamknie.", "",
 ("I jeszcze jedno: potrzebuję rachunku.", "láew kâw ìik yàang nùeng phǒm khǎw bai-sèt dûai khráp", "แล้วก็อีกอย่างหนึ่ง ผมขอใบเสร็จด้วยครับ")),

# =====================================================================
# ZABIERANIE I ODDAWANIE GLOSU
# =====================================================================
("przepraszam, że przerywam", "khǎw-thôot thîi khàt jang-wà khráp", "ขอโทษที่ขัดจังหวะครับ",
 "Podstawy i grzeczność", "Prowadzenie rozmowy", "sentence", 4, "f",
 "Bez tej formuły wejście w słowo jest w Tajlandii odbierane jako brak szacunku.", "przepraszam że przerywam rytm",
 ("Przepraszam, że przerywam, ale to pilne.", "khǒw-thôot thîi khàt jang-wà khráp tàae rûeang níi dùan", "ขอโทษที่ขัดจังหวะครับ แต่เรื่องนี้ด่วน")),
("pozwól, że dokończę", "khǎw phûut hâi jòp kàwn ná khráp", "ขอพูดให้จบก่อนนะครับ",
 "Podstawy i grzeczność", "Prowadzenie rozmowy", "sentence", 3, "n",
 "Zdanie broni twojej tury, ale „ná khráp” na końcu jest obowiązkowe — bez niego brzmi jak nagana.", "",
 ("Pozwól, że dokończę, zostały dwa zdania.", "khǎw phûut hâi jòp kàwn ná khráp ìik sǎwng prà-yòhk", "ขอพูดให้จบก่อนนะครับ อีกสองประโยค")),
("mogę coś dodać?", "khǎw sòoem nòi dâai mǎi khráp", "ขอเสริมหน่อยได้ไหมครับ",
 "Praca i nauka", "Prowadzenie rozmowy", "sentence", 4, "f",
 "„sòoem” = dołożyć do cudzej wypowiedzi. Na zebraniu brzmi to znacznie lepiej niż „phǒm khít wâa”.", "proszę dołożyć trochę",
 ("Mogę coś dodać do tego punktu?", "khǎw sòoem rûeang níi nòi dâai mǎi khráp", "ขอเสริมเรื่องนี้หน่อยได้ไหมครับ")),
("co ty na to?", "khun wâa ngai lâ", "คุณว่าไงล่ะ", "Small talk", "Prowadzenie rozmowy", "sentence", 5, "i",
 "Oddaje głos rozmówcy. W wersji formalnej: „khun khít hěn yàang rai khráp”.", "",
 ("Ja bym poczekał. Co ty na to?", "phǒm wâa raw kàwn khun wâa ngai lâ", "ผมว่ารอก่อน คุณว่าไงล่ะ")),
("jakie jest pana stanowisko?", "khun mii khwaam khít hěn yàang rai khráp", "คุณมีความคิดเห็นอย่างไรครับ",
 "Praca i nauka", "Prowadzenie rozmowy", "sentence", 3, "f",
 "Pełna forma pytania o opinię. „yàang rai” zamiast „yang-ngai” od razu podnosi rejestr.", "",
 ("Jakie jest pana stanowisko w tej sprawie?", "rûeang níi khun mii khwaam khít hěn yàang rai khráp", "เรื่องนี้คุณมีความคิดเห็นอย่างไรครับ")),
("słucham cię uważnie", "fang yùu khráp phûut tàw dâai loei", "ฟังอยู่ครับ พูดต่อได้เลย",
 "Small talk", "Prowadzenie rozmowy", "sentence", 4, "n",
 "Tajowie oczekują sygnałów słuchania częściej niż Polacy. Milczenie odbierane jest jako znudzenie.", "",
 ("Słucham cię uważnie, mów dalej.", "fang yùu khráp lâo tàw loei khráp", "ฟังอยู่ครับ เล่าต่อเลยครับ")),
("nie skończyłem jeszcze", "phǒm yang phûut mâi jòp khráp", "ผมยังพูดไม่จบครับ",
 "Praca i nauka", "Prowadzenie rozmowy", "sentence", 3, "n", "", "",
 ("Nie skończyłem jeszcze, jedna sprawa została.", "phǒm yang phûut mâi jòp khráp mii ìik rûeang nùeng", "ผมยังพูดไม่จบครับ มีอีกเรื่องหนึ่ง")),
("mów śmiało, nie obrażę się", "phûut trong trong dâai loei khráp phǒm mâi thǔe", "พูดตรงๆ ได้เลยครับ ผมไม่ถือ",
 "Small talk", "Prowadzenie rozmowy", "sentence", 4, "n",
 "„mâi thǔe” = nie wezmę tego do siebie. Otwiera rozmówcę, który boi się urazić.", "nie trzymam",
 ("Mów śmiało, nie obrażę się o krytykę.", "phûut trong trong dâai loei khráp phǒm mâi thǔe rûeang khwaam hěn", "พูดตรงๆ ได้เลยครับ ผมไม่ถือเรื่องความเห็น")),

# =====================================================================
# ZMIANA I DOMYKANIE TEMATU
# =====================================================================
("a tak w ogóle", "wâa tàae wâa", "ว่าแต่ว่า", "Small talk", "Prowadzenie rozmowy", "phrase", 5, "n",
 "Standardowy tajski sposób na zmianę tematu bez wrażenia ucieczki.", "",
 ("A tak w ogóle, jak poszła rozmowa?", "wâa tàae wâa khui pen yang-ngai bâang khráp", "ว่าแต่ว่าคุยเป็นยังไงบ้างครับ")),
("skoro już o tym mowa", "phûut thǔeng rûeang níi", "พูดถึงเรื่องนี้", "Small talk", "Prowadzenie rozmowy", "phrase", 4, "n",
 "Wprowadza temat powiązany. Płynniejsze niż nagłe przeskoczenie.", "mówiąc o tej sprawie",
 ("Skoro już o tym mowa, mam pytanie.", "phûut thǔeng rûeang níi phǒm mii kham thǎam khráp", "พูดถึงเรื่องนี้ ผมมีคำถามครับ")),
("wróćmy do tematu", "klàp maa rûeang doem khráp", "กลับมาเรื่องเดิมครับ", "Praca i nauka", "Prowadzenie rozmowy", "sentence", 4, "n",
 "Na zebraniu niezbędne — tajska rozmowa lubi odpływać w dygresje.", "wróćmy do starej sprawy",
 ("Wróćmy do tematu, zostało mało czasu.", "klàp maa rûeang doem khráp wee-laa nùea nói láew", "กลับมาเรื่องเดิมครับ เวลาเหลือน้อยแล้ว")),
("zostawmy to na później", "khǎw yók pai khui thii lǎng ná khráp", "ขอยกไปคุยทีหลังนะครับ",
 "Praca i nauka", "Prowadzenie rozmowy", "sentence", 4, "n",
 "„yók pai” = przenieść punkt. Bezpieczny sposób na odsunięcie niewygodnego wątku.", "podnieść i przenieść",
 ("Zostawmy to na później, teraz priorytet jest inny.", "khǎw yók pai khui thii lǎng ná khráp tawn níi mii rûeang dùan kwàa", "ขอยกไปคุยทีหลังนะครับ ตอนนี้มีเรื่องด่วนกว่า")),
("podsumowując", "sà-rùp láew", "สรุปแล้ว", "Praca i nauka", "Prowadzenie rozmowy", "phrase", 5, "n",
 "„sà-rùp” to jedno z najczęstszych słów w tajskim biurze. Warto je mieć odruchowo.", "",
 ("Podsumowując, decydujemy się na drugi wariant.", "sà-rùp láew raw lûeak bàep thîi sǎwng khráp", "สรุปแล้วเราเลือกแบบที่สองครับ")),
("krótko mówiąc", "phûut sân sân", "พูดสั้นๆ", "Small talk", "Prowadzenie rozmowy", "phrase", 4, "n", "", "",
 ("Krótko mówiąc, nie opłaca się.", "phûut sân sân khue mâi khúm khráp", "พูดสั้นๆ คือไม่คุ้มครับ")),
("na tym poprzestańmy", "ao khâe níi kàwn ná khráp", "เอาแค่นี้ก่อนนะครับ", "Praca i nauka", "Prowadzenie rozmowy", "sentence", 4, "n",
 "Zamyka spotkanie łagodnie. „khâe níi” = tyle na razie.", "weźmy tylko tyle najpierw",
 ("Na tym poprzestańmy, resztę omówimy jutro.", "ao khâe níi kàwn ná khráp thîi lǔea khui phrûng-níi", "เอาแค่นี้ก่อนนะครับ ที่เหลือคุยพรุ่งนี้")),
("to by było na tyle", "kâw prà-maan níi lâ khráp", "ก็ประมาณนี้ล่ะครับ", "Small talk", "Prowadzenie rozmowy", "sentence", 4, "n", "", "",
 ("To by było na tyle z mojej strony.", "jàak phǒm kâw prà-maan níi lâ khráp", "จากผมก็ประมาณนี้ล่ะครับ")),

# =====================================================================
# PARAFRAZA I SPRAWDZANIE ZROZUMIENIA
# =====================================================================
("czyli innymi słowy", "rǔe phûut ìik yàang nùeng kâw khue", "หรือพูดอีกอย่างหนึ่งก็คือ",
 "Gramatyka użytkowa", "Parafraza", "phrase", 4, "f",
 "Otwiera parafrazę cudzych słów. Bardzo przydatne, gdy nie masz pewności, czy dobrze zrozumiałeś.", "",
 ("Czyli innymi słowy, dostawa się opóźni.", "rǔe phûut ìik yàang nùeng kâw khue khǎwng jà maa cháa", "หรือพูดอีกอย่างหนึ่งก็คือของจะมาช้า")),
("czy dobrze rozumiem?", "phǒm khâo-jai thùuk mǎi khráp", "ผมเข้าใจถูกไหมครับ",
 "Gramatyka użytkowa", "Parafraza", "sentence", 5, "n",
 "Kluczowe pytanie w rozmowie zawodowej. Taj rzadko poprawi cię sam z siebie.", "",
 ("Czy dobrze rozumiem: płatność do piątku?", "phǒm khâo-jai thùuk mǎi khráp jàai phaai-nai wan sùk", "ผมเข้าใจถูกไหมครับ จ่ายภายในวันศุกร์")),
("czyli chodzi panu o to, że", "khun mǎai thǔeng wâa", "คุณหมายถึงว่า", "Gramatyka użytkowa", "Parafraza", "phrase", 4, "n",
 "„mǎai thǔeng” = mieć na myśli. Podstawa każdego dopytywania.", "",
 ("Czyli chodzi panu o to, że termin się przesuwa.", "khun mǎai thǔeng wâa wan nát lûean àwk pai", "คุณหมายถึงว่าวันนัดเลื่อนออกไป")),
("co dokładnie ma pan na myśli?", "mǎai thǔeng à-rai kan nâe khráp", "หมายถึงอะไรกันแน่ครับ",
 "Gramatyka użytkowa", "Parafraza", "sentence", 4, "n",
 "„kan nâe” dodaje nacisk: chcę precyzji, nie ogólnika.", "",
 ("Co dokładnie ma pan na myśli, mówiąc „wkrótce”?", "kham wâa réw réw níi mǎai thǔeng à-rai kan nâe khráp", "คำว่าเร็วๆ นี้หมายถึงอะไรกันแน่ครับ")),
("czy mówimy o tej samej sprawie?", "raw phûut rûeang diao kan rǔe plào khráp", "เราพูดเรื่องเดียวกันหรือเปล่าครับ",
 "Praca i nauka", "Parafraza", "sentence", 3, "n", "", "",
 ("Chwila — czy mówimy o tej samej sprawie?", "dǐao khráp raw phûut rûeang diao kan rǔe plào", "เดี๋ยวครับ เราพูดเรื่องเดียวกันหรือเปล่า")),
("mówię wyraźnie?", "phǒm phûut chát mǎi khráp", "ผมพูดชัดไหมครับ", "Podstawy i grzeczność", "Parafraza", "sentence", 4, "n",
 "Przerzuca ciężar niezrozumienia na siebie — bardzo uprzejme wobec rozmówcy.", "",
 ("Mówię wyraźnie? Powiedz, jeśli nie.", "phǒm phûut chát mǎi khráp thâa mâi chát bàwk dâai", "ผมพูดชัดไหมครับ ถ้าไม่ชัดบอกได้")),
("nie dosłyszałem", "phǒm fang mâi than khráp", "ผมฟังไม่ทันครับ", "Podstawy i grzeczność", "Parafraza", "sentence", 5, "n",
 "„fang mâi than” = nie nadążyłem za mową. Uczciwsze niż „mâi khâo-jai”, bo problemem jest tempo, nie treść.", "słuchać nie zdążyć",
 ("Nie dosłyszałem, mógłby pan powtórzyć?", "phǒm fang mâi than khráp phûut ìik thii dâai mǎi", "ผมฟังไม่ทันครับ พูดอีกทีได้ไหม")),
("proszę mówić trochę wolniej", "chûai phûut cháa long nòi dâai mǎi khráp", "ช่วยพูดช้าลงหน่อยได้ไหมครับ",
 "Podstawy i grzeczność", "Parafraza", "sentence", 5, "n", "", "",
 ("Proszę mówić trochę wolniej, dopiero się uczę.", "chûai phûut cháa long nòi dâai mǎi khráp phǒm phôoeng rian", "ช่วยพูดช้าลงหน่อยได้ไหมครับ ผมเพิ่งเรียน")),
("proszę powtórzyć ostatnie zdanie", "khǎw fang prà-yòhk sùt tháai ìik thii khráp", "ขอฟังประโยคสุดท้ายอีกทีครับ",
 "Podstawy i grzeczność", "Parafraza", "sentence", 3, "f", "", "",
 ("Proszę powtórzyć ostatnie zdanie, nie zanotowałem.", "khǎw fang prà-yòhk sùt tháai ìik thii khráp phǒm jòt mâi than", "ขอฟังประโยคสุดท้ายอีกทีครับ ผมจดไม่ทัน")),
("proszę o to na piśmie", "khǎw pen laai lák àk-sǎwn dâai mǎi khráp", "ขอเป็นลายลักษณ์อักษรได้ไหมครับ",
 "Praca i nauka", "Parafraza", "sentence", 3, "f",
 "Rejestr urzędowy. W rozmowie zwykłej wystarczy „khǎw pen khâw-khwaam dâai mǎi khráp”.", "prosić o formę pisemną",
 ("Proszę o to na piśmie, dla porządku.", "khǎw pen laai lák àk-sǎwn dâai mǎi khráp phûea khwaam chát-jeen", "ขอเป็นลายลักษณ์อักษรได้ไหมครับ เพื่อความชัดเจน")),
("zapiszę to, żeby nie było nieporozumień", "phǒm jòt wái kan sàp-sǒn ná khráp", "ผมจดไว้กันสับสนนะครับ",
 "Praca i nauka", "Parafraza", "sentence", 3, "n", "", "",
 ("Zapiszę to, żeby nie było nieporozumień.", "khǎw jòt wái kan sàp-sǒn ná khráp", "ขอจดไว้กันสับสนนะครับ")),

# =====================================================================
# KLOPOT ZE SLOWEM
# =====================================================================
("nie mogę znaleźć słowa", "núek kham mâi àwk khráp", "นึกคำไม่ออกครับ", "Small talk", "Wypełniacze", "sentence", 4, "n",
 "„núek … mâi àwk” = nie móc sobie przypomnieć. Ta konstrukcja działa też z imionami i miejscami.", "pomyśleć słowo nie wyjdzie",
 ("Nie mogę znaleźć słowa, zaraz mi się przypomni.", "núek kham mâi àwk khráp dǐao kâw núek àwk", "นึกคำไม่ออกครับ เดี๋ยวก็นึกออก")),
("mam to na końcu języka", "man tìt yùu thîi pàak", "มันติดอยู่ที่ปาก", "Small talk", "Wypełniacze", "sentence", 3, "p",
 "IDIOM. Obraz jest ten sam co po polsku, więc łatwo zapamiętać.", "przykleiło się przy ustach",
 ("Mam to na końcu języka, poczekaj.", "man tìt yùu thîi pàak raw dǐao ná", "มันติดอยู่ที่ปาก รอเดี๋ยวนะ")),
("jak to się mówi po tajsku?", "phaa-sǎa thai rîak wâa à-rai khráp", "ภาษาไทยเรียกว่าอะไรครับ",
 "Pytania", "Komunikacja", "sentence", 5, "n",
 "Najużyteczniejsze pytanie w całym kursie. Tajowie chętnie na nie odpowiadają.", "",
 ("Jak to się mówi po tajsku — „przedłużenie wizy”?", "tàw wii-sâa phaa-sǎa thai rîak wâa à-rai khráp", "ต่อวีซ่าภาษาไทยเรียกว่าอะไรครับ")),
("powiem to inaczej", "khǎw phûut mài ìik bàep nùeng ná khráp", "ขอพูดใหม่อีกแบบหนึ่งนะครับ",
 "Podstawy i grzeczność", "Komunikacja", "sentence", 4, "n", "", "",
 ("Powiem to inaczej, żeby było jaśniej.", "khǎw phûut mài ìik bàep nùeng hâi chát khûen ná khráp", "ขอพูดใหม่อีกแบบหนึ่งให้ชัดขึ้นนะครับ")),
("trudno mi to wytłumaczyć", "à-thí-baai yâak nít nùeng khráp", "อธิบายยากนิดหนึ่งครับ",
 "Small talk", "Komunikacja", "sentence", 4, "n", "", "",
 ("Trudno mi to wytłumaczyć po tajsku.", "à-thí-baai pen phaa-sǎa thai yâak nít nùeng khráp", "อธิบายเป็นภาษาไทยยากนิดหนึ่งครับ")),
("znam to słowo, ale nie umiem użyć", "kham níi rúu-jàk tàae chái mâi pen khráp", "คำนี้รู้จักแต่ใช้ไม่เป็นครับ",
 "Praca i nauka", "Komunikacja", "sentence", 3, "n", "", "",
 ("Znam to słowo, ale nie umiem go użyć w zdaniu.", "kham níi rúu-jàk tàae chái nai prà-yòhk mâi pen khráp", "คำนี้รู้จักแต่ใช้ในประโยคไม่เป็นครับ")),
("poprawiaj mnie, proszę", "chûai kâe hâi dûai ná khráp", "ช่วยแก้ให้ด้วยนะครับ", "Praca i nauka", "Komunikacja", "sentence", 4, "n",
 "Bez tej prośby Tajowie zwykle nie poprawiają obcokrajowca — nie chcą go zawstydzić.", "",
 ("Poprawiaj mnie, proszę, chcę mówić dobrze.", "chûai kâe hâi dûai ná khráp phǒm yàak phûut hâi thùuk", "ช่วยแก้ให้ด้วยนะครับ ผมอยากพูดให้ถูก")),
("czy tak się mówi?", "phûut yàang níi dâai mǎi khráp", "พูดอย่างนี้ได้ไหมครับ", "Pytania", "Komunikacja", "sentence", 4, "n", "", "",
 ("Czy tak się mówi, czy to brzmi dziwnie?", "phûut yàang níi dâai mǎi khráp rǔe man plàek", "พูดอย่างนี้ได้ไหมครับ หรือมันแปลก")),
("brzmi to dziwnie?", "man fang plàek mǎi khráp", "มันฟังแปลกไหมครับ", "Pytania", "Komunikacja", "sentence", 3, "n", "", "",
 ("Brzmi to dziwnie po tajsku?", "pen phaa-sǎa thai man fang plàek mǎi khráp", "เป็นภาษาไทยมันฟังแปลกไหมครับ")),

# =====================================================================
# PODTRZYMYWANIE ROZMOWY
# =====================================================================
("no i jak dalej?", "láew ngai tàw lâ", "แล้วไงต่อล่ะ", "Small talk", "Podtrzymywanie", "sentence", 5, "i", "", "",
 ("No i jak dalej? Opowiadaj.", "láew ngai tàw lâ lâo tàw sí", "แล้วไงต่อล่ะ เล่าต่อสิ")),
("naprawdę tak było?", "jing lǒe khráp", "จริงเหรอครับ", "Small talk", "Podtrzymywanie", "sentence", 5, "n",
 "Sygnał zainteresowania, nie podejrzliwości. Tajowie używają go bardzo często.", "",
 ("Naprawdę tak było? Nie wierzę.", "jing lǒe khráp mâi nâa chûea loei", "จริงเหรอครับ ไม่น่าเชื่อเลย")),
("wyobrażam sobie", "phǒm núek àwk loei khráp", "ผมนึกออกเลยครับ", "Small talk", "Podtrzymywanie", "sentence", 4, "n", "", "",
 ("Wyobrażam sobie, jak było ci ciężko.", "phǒm núek àwk loei khráp wâa man nàk khâe nǎi", "ผมนึกออกเลยครับว่ามันหนักแค่ไหน")),
("to musiało być trudne", "man khong jà nàk ná khráp", "มันคงจะหนักนะครับ", "Small talk", "Podtrzymywanie", "sentence", 4, "n", "", "",
 ("To musiało być trudne dla całej rodziny.", "man khong jà nàk sǎm-ràp thúk khon nai bâan ná khráp", "มันคงจะหนักสำหรับทุกคนในบ้านนะครับ")),
("dobrze, że się skończyło", "dii thîi man phàan pai láew khráp", "ดีที่มันผ่านไปแล้วครับ", "Small talk", "Podtrzymywanie", "sentence", 4, "n", "", "",
 ("Dobrze, że się skończyło i nikomu nic nie jest.", "dii thîi man phàan pai láew láe mâi mii khrai pen à-rai khráp", "ดีที่มันผ่านไปแล้วและไม่มีใครเป็นอะไรครับ")),
("a co było potem?", "lǎng jàak nán pen yang-ngai tàw khráp", "หลังจากนั้นเป็นยังไงต่อครับ",
 "Small talk", "Podtrzymywanie", "sentence", 4, "n", "", "",
 ("A co było potem, dostałeś odpowiedź?", "lǎng jàak nán pen yang-ngai tàw khráp dâai kham tàwp mǎi", "หลังจากนั้นเป็นยังไงต่อครับ ได้คำตอบไหม")),
("opowiedz od początku", "lâo tâng tàae râek loei khráp", "เล่าตั้งแต่แรกเลยครับ", "Small talk", "Podtrzymywanie", "sentence", 4, "n", "", "",
 ("Opowiedz od początku, nie znam tej historii.", "lâo tâng tàae râek loei khráp phǒm yang mâi rúu rûeang", "เล่าตั้งแต่แรกเลยครับ ผมยังไม่รู้เรื่อง")),
("wiem, co masz na myśli", "phǒm khâo-jai thîi khun mǎai thǔeng khráp", "ผมเข้าใจที่คุณหมายถึงครับ",
 "Small talk", "Podtrzymywanie", "sentence", 4, "n", "", "",
 ("Wiem, co masz na myśli, sam tak miałem.", "phǒm khâo-jai thîi khun mǎai thǔeng khráp phǒm kâw khoei pen", "ผมเข้าใจที่คุณหมายถึงครับ ผมก็เคยเป็น")),
("mnie też to spotkało", "phǒm kâw jôe mǎi kan khráp", "ผมก็เจอเหมือนกันครับ", "Small talk", "Podtrzymywanie", "sentence", 4, "n", "", "",
 ("Mnie też to spotkało w zeszłym roku.", "phǒm kâw jôe mǎi kan tawn pii thîi láew khráp", "ผมก็เจอเหมือนกันตอนปีที่แล้วครับ")),
("no nie mów", "mâi jing ná", "ไม่จริงน่า", "Small talk", "Podtrzymywanie", "phrase", 4, "p",
 "Wyraża zaskoczenie, nie zarzut kłamstwa. Ton musi być lekki.", "",
 ("No nie mów, i co zrobiłeś?", "mâi jing ná láew tham yang-ngai tàw", "ไม่จริงน่า แล้วทำยังไงต่อ")),
("no proszę", "âw hǒe", "อ้าวเหรอ", "Small talk", "Podtrzymywanie", "phrase", 4, "p",
 "Reakcja na niespodziewaną informację. Krótkie, bardzo naturalne.", "",
 ("No proszę, nie wiedziałem.", "âw hǒe phǒm mâi rúu maa kàwn", "อ้าวเหรอ ผมไม่รู้มาก่อน")),
("dokładnie tak", "chái loei khráp trong nán loei", "ใช่เลยครับ ตรงนั้นเลย", "Small talk", "Podtrzymywanie", "sentence", 4, "n", "", "",
 ("Dokładnie tak, sam bym tego nie ujął lepiej.", "chái loei khráp phǒm kâw jà phûut yàang nán mǔean kan", "ใช่เลยครับ ผมก็จะพูดอย่างนั้นเหมือนกัน")),
("niekoniecznie", "kâw mâi sà-mǒoe pai khráp", "ก็ไม่เสมอไปครับ", "Cechy i opinie", "Podtrzymywanie", "phrase", 4, "n",
 "Delikatne zaprzeczenie uogólnieniu — nie odbiera rozmówcy racji całkowicie.", "nie zawsze",
 ("Niekoniecznie, zdarzają się wyjątki.", "kâw mâi sà-mǒoe pai khráp baang khráng kâw mâi", "ก็ไม่เสมอไปครับ บางครั้งก็ไม่")),
("to zależy od dnia", "láew tàae wan khráp", "แล้วแต่วันครับ", "Cechy i opinie", "Podtrzymywanie", "sentence", 4, "n", "", "",
 ("To zależy od dnia, w weekend jest gorzej.", "láew tàae wan khráp sǎo aa-thít nâe kwàa", "แล้วแต่วันครับ เสาร์อาทิตย์แน่นกว่า")),

# =====================================================================
# SYGNALY NIEPEWNOSCI I ZASTRZEZENIA
# =====================================================================
("o ile wiem", "thâo thîi rúu maa", "เท่าที่รู้มา", "Gramatyka użytkowa", "Zastrzeżenia", "phrase", 4, "n",
 "Zabezpiecza przed odpowiedzialnością za nieścisłość. Bardzo częste w rozmowie zawodowej.", "tyle ile wiem",
 ("O ile wiem, biuro jest dziś zamknięte.", "thâo thîi rúu maa wan níi àwf-fít pìt khráp", "เท่าที่รู้มาวันนี้ออฟฟิศปิดครับ")),
("o ile pamiętam", "thâa jam mâi phìt", "ถ้าจำไม่ผิด", "Gramatyka użytkowa", "Zastrzeżenia", "phrase", 4, "n", "jeśli nie mylę pamięci",
 "",
 ("O ile pamiętam, umowa jest na rok.", "thâa jam mâi phìt sǎn-yaa pen raai pii khráp", "ถ้าจำไม่ผิดสัญญาเป็นรายปีครับ")),
("nie jestem pewien, ale wydaje mi się", "mâi nâe-jai ná khráp tàae rúu-sùek wâa", "ไม่แน่ใจนะครับ แต่รู้สึกว่า",
 "Gramatyka użytkowa", "Zastrzeżenia", "phrase", 4, "n", "", "",
 ("Nie jestem pewien, ale wydaje mi się, że jest taniej.", "mâi nâe-jai ná khráp tàae rúu-sùek wâa thùuk kwàa", "ไม่แน่ใจนะครับ แต่รู้สึกว่าถูกกว่า")),
("muszę to sprawdzić", "khǎw pai chék hâi kàwn ná khráp", "ขอไปเช็คให้ก่อนนะครับ", "Praca i nauka", "Zastrzeżenia", "sentence", 5, "n",
 "Lepsze niż zgadywanie. W kulturze pracy w Tajlandii nikt nie ma tego za złe.", "",
 ("Muszę to sprawdzić i wrócę z odpowiedzią.", "khǎw pai chék hâi kàwn ná khráp dǐao maa bàwk", "ขอไปเช็คให้ก่อนนะครับ เดี๋ยวมาบอก")),
("nie chcę wprowadzać cię w błąd", "phǒm mâi yàak bàwk phìt khráp", "ผมไม่อยากบอกผิดครับ",
 "Praca i nauka", "Zastrzeżenia", "sentence", 3, "n", "", "",
 ("Nie chcę wprowadzać cię w błąd, wolę zapytać.", "phǒm mâi yàak bàwk phìt khráp khǎw thǎam kàwn dii kwàa", "ผมไม่อยากบอกผิดครับ ขอถามก่อนดีกว่า")),
("to tylko moje przypuszczenie", "pen khâe kaan dâo khǎwng phǒm khráp", "เป็นแค่การเดาของผมครับ",
 "Cechy i opinie", "Zastrzeżenia", "sentence", 3, "n", "", "",
 ("To tylko moje przypuszczenie, nie traktuj jako pewnik.", "pen khâe kaan dâo khǎwng phǒm khráp yàa thǔe pen jing", "เป็นแค่การเดาของผมครับ อย่าถือเป็นจริง")),
("nie mam pełnych informacji", "phǒm mii khâw-muun mâi khróp khráp", "ผมมีข้อมูลไม่ครบครับ",
 "Praca i nauka", "Zastrzeżenia", "sentence", 3, "f", "", "",
 ("Nie mam pełnych informacji, żeby to ocenić.", "phǒm mii khâw-muun mâi khróp phaw jà pra-mooen khráp", "ผมมีข้อมูลไม่ครบพอจะประเมินครับ")),
("mogę się mylić", "phǒm àat jà khâo-jai phìt kâw dâai khráp", "ผมอาจจะเข้าใจผิดก็ได้ครับ",
 "Gramatyka użytkowa", "Zastrzeżenia", "sentence", 4, "n",
 "Otwiera furtkę wyjścia obu stronom. Klucz do sporu bez utraty twarzy.", "",
 ("Mogę się mylić, więc sprawdźmy razem.", "phǒm àat jà khâo-jai phìt kâw dâai khráp lawng chék dûai kan", "ผมอาจจะเข้าใจผิดก็ได้ครับ ลองเช็คด้วยกัน")),
("według tego, co mi powiedziano", "taam thîi dâai ráp jâeng maa", "ตามที่ได้รับแจ้งมา",
 "Praca i nauka", "Zastrzeżenia", "phrase", 3, "f",
 "Rejestr urzędowy. Przenosi źródło informacji na kogoś innego.", "",
 ("Według tego, co mi powiedziano, termin minął.", "taam thîi dâai ráp jâeng maa kam-nòt wee-laa phàan pai láew khráp", "ตามที่ได้รับแจ้งมากำหนดเวลาผ่านไปแล้วครับ")),
("z tego, co słyszałem", "thâo thîi dâai yin maa", "เท่าที่ได้ยินมา", "Gramatyka użytkowa", "Zastrzeżenia", "phrase", 4, "n", "", "",
 ("Z tego, co słyszałem, będzie zmiana kierownika.", "thâo thîi dâai yin maa jà plìan hǔa-nâa khráp", "เท่าที่ได้ยินมาจะเปลี่ยนหัวหน้าครับ")),
("trudno to teraz przesądzić", "tawn níi yang fan-thong mâi dâai khráp", "ตอนนี้ยังฟันธงไม่ได้ครับ",
 "Cechy i opinie", "Zastrzeżenia", "sentence", 3, "n",
 "„fan-thong” = przesądzić, orzec definitywnie. Bardzo częste w tajskich mediach i rozmowie biurowej.", "wbić flagę",
 ("Trudno to teraz przesądzić, poczekajmy tydzień.", "tawn níi yang fan-thong mâi dâai khráp khǎw raw ìik aa-thít nùeng", "ตอนนี้ยังฟันธงไม่ได้ครับ ขอรออีกอาทิตย์หนึ่ง")),

# =====================================================================
# UWAGA I PRZYPOMNIENIE
# =====================================================================
("dla jasności", "phûea khwaam chát-jeen", "เพื่อความชัดเจน", "Praca i nauka", "Prowadzenie rozmowy", "phrase", 3, "f", "", "",
 ("Dla jasności powtórzę ustalenia.", "phûea khwaam chát-jeen khǎw thop thuan ìik khráng khráp", "เพื่อความชัดเจนขอทบทวนอีกครั้งครับ")),
("chciałbym tylko przypomnieć", "khǎw thúeng ná khráp wâa", "ขอท้วงนะครับว่า", "Praca i nauka", "Prowadzenie rozmowy", "phrase", 3, "f",
 "„thúeng” = zgłosić zastrzeżenie. Uprzejmy sposób na zwrócenie uwagi przełożonemu.", "",
 ("Chciałbym tylko przypomnieć, że termin był inny.", "khǎw thúeng ná khráp wâa kam-nòt doem mâi châi wan níi", "ขอท้วงนะครับว่ากำหนดเดิมไม่ใช่วันนี้")),
("proszę mieć na uwadze", "khǎw hâi khum khít wái dûai ná khráp", "ขอให้คำนึงไว้ด้วยนะครับ",
 "Praca i nauka", "Prowadzenie rozmowy", "phrase", 2, "f", "", "",
 ("Proszę mieć na uwadze koszty transportu.", "khǎw hâi khum khít thǔeng khâa khǒn sòng dûai ná khráp", "ขอให้คำนึงถึงค่าขนส่งด้วยนะครับ")),
("zwróć uwagę na jedną rzecz", "sǎng-kèet ìik yàang nùeng ná khráp", "สังเกตอีกอย่างหนึ่งนะครับ",
 "Praca i nauka", "Prowadzenie rozmowy", "sentence", 3, "n", "", "",
 ("Zwróć uwagę na jedną rzecz: ceny są bez podatku.", "sǎng-kèet ìik yàang nùeng ná khráp raa-khaa yang mâi ruam phaa-sǐi", "สังเกตอีกอย่างหนึ่งนะครับ ราคายังไม่รวมภาษี")),
("jeśli można coś zasugerować", "thâa khǎw náe-nam dâai", "ถ้าขอแนะนำได้", "Praca i nauka", "Prowadzenie rozmowy", "phrase", 4, "f",
 "Formuła wejścia z radą, o którą nikt nie prosił. Bez niej rada brzmi jak krytyka.", "",
 ("Jeśli można coś zasugerować, warto zacząć wcześniej.", "thâa khǎw náe-nam dâai khuan rôoem hâi réw kwàa níi khráp", "ถ้าขอแนะนำได้ ควรเริ่มให้เร็วกว่านี้ครับ")),
("nie chcę się wtrącać, ale", "mâi yàak sǔeak ná khráp tàae wâa", "ไม่อยากเสือกนะครับ แต่ว่า",
 "Small talk", "Prowadzenie rozmowy", "phrase", 3, "p",
 "SLANG. „sǔeak” to wulgarne „wtrącać się”. Wobec obcych i w pracy użyj „mâi yàak yûng ná khráp”.", "",
 ("Nie chcę się wtrącać, ale to zły pomysł.", "mâi yàak sǔeak ná khráp tàae wâa man mâi wôek", "ไม่อยากเสือกนะครับ แต่ว่ามันไม่เวิร์ก")),
("nie chcę się wtrącać w cudzą sprawę", "mâi yàak yûng rûeang khǎwng khon ùen khráp", "ไม่อยากยุ่งเรื่องของคนอื่นครับ",
 "Small talk", "Prowadzenie rozmowy", "sentence", 4, "n",
 "Kulturalna wersja poprzedniego zwrotu. Tej używaj w pracy i wobec starszych.", "",
 ("Nie chcę się wtrącać w cudzą sprawę, przepraszam.", "khǎw-thôot khráp phǒm mâi yàak yûng rûeang khǎwng khon ùen", "ขอโทษครับ ผมไม่อยากยุ่งเรื่องของคนอื่น")),

# =====================================================================
# NATURALNE OTWARCIA I ZAMKNIECIA
# =====================================================================
("masz chwilę?", "wâang sák khrûu mǎi khráp", "ว่างสักครู่ไหมครับ", "Praca i nauka", "Prowadzenie rozmowy", "sentence", 5, "n", "", "",
 ("Masz chwilę? Chciałbym coś omówić.", "wâang sák khrûu mǎi khráp yàak khui rûeang nùeng", "ว่างสักครู่ไหมครับ อยากคุยเรื่องหนึ่ง")),
("przeszkadzam?", "róp-kuan rǔe plào khráp", "รบกวนหรือเปล่าครับ", "Podstawy i grzeczność", "Prowadzenie rozmowy", "sentence", 5, "n",
 "„róp-kuan” to podstawowy czasownik uprzejmego zawracania głowy. Warto go opanować przed wszystkim innym.", "",
 ("Przeszkadzam? Mogę wrócić później.", "róp-kuan rǔe plào khráp dǐao klàp maa mài kâw dâai", "รบกวนหรือเปล่าครับ เดี๋ยวกลับมาใหม่ก็ได้")),
("mam do ciebie sprawę", "mii rûeang jà róp-kuan nòi khráp", "มีเรื่องจะรบกวนหน่อยครับ",
 "Praca i nauka", "Prowadzenie rozmowy", "sentence", 5, "n", "", "",
 ("Mam do ciebie sprawę, zajmie pięć minut.", "mii rûeang jà róp-kuan nòi khráp chái wee-laa hâa naa-thii", "มีเรื่องจะรบกวนหน่อยครับ ใช้เวลาห้านาที")),
("dzwonię w sprawie", "thoo maa rûeang", "โทรมาเรื่อง", "Praca i nauka", "Telefon", "phrase", 5, "n",
 "Standardowe otwarcie rozmowy telefonicznej. Od razu podaj temat — Tajowie nie lubią zgadywać.", "",
 ("Dzwonię w sprawie rezerwacji na jutro.", "thoo maa rûeang jawng hâwng phrûng-níi khráp", "โทรมาเรื่องจองห้องพรุ่งนี้ครับ")),
("przepraszam, że tak późno dzwonię", "khǎw-thôot thîi thoo maa dùek khráp", "ขอโทษที่โทรมาดึกครับ",
 "Podstawy i grzeczność", "Telefon", "sentence", 3, "f", "", "",
 ("Przepraszam, że tak późno dzwonię, sprawa jest pilna.", "khǎw-thôot thîi thoo maa dùek khráp rûeang dùan jing jing", "ขอโทษที่โทรมาดึกครับ เรื่องด่วนจริงๆ")),
("nie zatrzymuję cię dłużej", "mâi róp-kuan wee-laa tàw láew khráp", "ไม่รบกวนเวลาต่อแล้วครับ",
 "Podstawy i grzeczność", "Prowadzenie rozmowy", "sentence", 4, "f", "", "",
 ("Nie zatrzymuję cię dłużej, dziękuję za czas.", "mâi róp-kuan wee-laa tàw láew khráp khàwp-khun mâak", "ไม่รบกวนเวลาต่อแล้วครับ ขอบคุณมาก")),
("odezwę się", "dǐao tìt tàw pai mài khráp", "เดี๋ยวติดต่อไปใหม่ครับ", "Praca i nauka", "Prowadzenie rozmowy", "sentence", 4, "n", "", "",
 ("Odezwę się, jak tylko będę wiedział.", "rúu mûea rài dǐao tìt tàw pai mài khráp", "รู้เมื่อไหร่เดี๋ยวติดต่อไปใหม่ครับ")),
("trzymajmy kontakt", "tìt tàw kan wái ná khráp", "ติดต่อกันไว้นะครับ", "Small talk", "Prowadzenie rozmowy", "sentence", 4, "n", "", "",
 ("Trzymajmy kontakt, może coś się pojawi.", "tìt tàw kan wái ná khráp bàang thii mii ngaan", "ติดต่อกันไว้นะครับ บางทีมีงาน")),
("miło się rozmawiało", "khui kan sà-nùk dii khráp", "คุยกันสนุกดีครับ", "Small talk", "Prowadzenie rozmowy", "sentence", 4, "n", "", "",
 ("Miło się rozmawiało, do zobaczenia.", "khui kan sà-nùk dii khráp wái jôe kan mài", "คุยกันสนุกดีครับ ไว้เจอกันใหม่")),
("dziękuję za cierpliwość", "khàwp-khun thîi jai yen ráw khráp", "ขอบคุณที่ใจเย็นรอครับ",
 "Podstawy i grzeczność", "Prowadzenie rozmowy", "sentence", 4, "f",
 "„jai yen” = chłodne serce, czyli spokój. To jedno z najważniejszych pojęć tajskiej kultury.", "chłodne serce czekać",
 ("Dziękuję za cierpliwość, już wszystko gotowe.", "khàwp-khun thîi jai yen ráw khráp riap ráwi láew", "ขอบคุณที่ใจเย็นรอครับ เรียบร้อยแล้ว")),

# =====================================================================
# TEMPO I KOLEJNOSC
# =====================================================================
("po kolei", "thii lá yàang khráp", "ทีละอย่างครับ", "Gramatyka użytkowa", "Prowadzenie rozmowy", "phrase", 4, "n",
 "„thii lá …” = po jednym naraz. Działa też z ludźmi: „thii lá khon”.", "po jednej rzeczy",
 ("Po kolei, najpierw dokumenty.", "thii lá yàang khráp rôoem jàak èek-kà-sǎan kàwn", "ทีละอย่างครับ เริ่มจากเอกสารก่อน")),
("najpierw najważniejsze", "ao rûeang sǎm-khan kàwn khráp", "เอาเรื่องสำคัญก่อนครับ",
 "Praca i nauka", "Prowadzenie rozmowy", "sentence", 4, "n", "", "",
 ("Najpierw najważniejsze: kto za to płaci?", "ao rûeang sǎm-khan kàwn khráp khrai pen khon jàai", "เอาเรื่องสำคัญก่อนครับ ใครเป็นคนจ่าย")),
("zacznijmy od tego, że", "rôoem jàak wâa", "เริ่มจากว่า", "Gramatyka użytkowa", "Prowadzenie rozmowy", "phrase", 4, "n", "", "",
 ("Zacznijmy od tego, że umowa wygasła.", "rôoem jàak wâa sǎn-yaa mòt aa-yú láew khráp", "เริ่มจากว่าสัญญาหมดอายุแล้วครับ")),
("wolniej, bo się pogubię", "cháa cháa nòi khráp dǐao phǒm ngong", "ช้าๆ หน่อยครับ เดี๋ยวผมงง",
 "Podstawy i grzeczność", "Parafraza", "sentence", 4, "i",
 "„ngong” = pogubić się, zgłupieć. Bardzo częste słowo, całkowicie neutralne emocjonalnie.", "",
 ("Wolniej, bo się pogubię w liczbach.", "cháa cháa nòi khráp dǐao phǒm ngong rûeang tua lêek", "ช้าๆ หน่อยครับ เดี๋ยวผมงงเรื่องตัวเลข")),
("dajmy sobie chwilę", "phák kan sák khrûu ná khráp", "พักกันสักครู่นะครับ", "Praca i nauka", "Prowadzenie rozmowy", "sentence", 3, "n", "", "",
 ("Dajmy sobie chwilę i wróćmy do tego.", "phák kan sák khrûu láew khôi khui tàw ná khráp", "พักกันสักครู่แล้วค่อยคุยต่อนะครับ")),
("wracam do tego, co mówiłeś", "khǎw yáwn klàp pai thîi khun phûut", "ขอย้อนกลับไปที่คุณพูด",
 "Gramatyka użytkowa", "Prowadzenie rozmowy", "phrase", 3, "n", "cofnąć się z powrotem", "",
 ("Wracam do tego, co mówiłeś o cenie.", "khǎw yáwn klàp pai thîi khun phûut rûeang raa-khaa khráp", "ขอย้อนกลับไปที่คุณพูดเรื่องราคาครับ")),
("zanim przejdziemy dalej", "kàwn jà pai tàw", "ก่อนจะไปต่อ", "Praca i nauka", "Prowadzenie rozmowy", "phrase", 4, "n", "", "",
 ("Zanim przejdziemy dalej, jedno pytanie.", "kàwn jà pai tàw khǎw thǎam nùeng khâw khráp", "ก่อนจะไปต่อ ขอถามหนึ่งข้อครับ")),
("chwilowo zostawmy szczegóły", "rai-lá-ìat khǎw wái kàwn ná khráp", "รายละเอียดขอไว้ก่อนนะครับ",
 "Praca i nauka", "Prowadzenie rozmowy", "sentence", 3, "n", "", "",
 ("Chwilowo zostawmy szczegóły, najpierw kierunek.", "rai-lá-ìat khǎw wái kàwn ná khráp ao phaap ruam kàwn", "รายละเอียดขอไว้ก่อนนะครับ เอาภาพรวมก่อน")),
("w skrócie mówiąc", "phûut hâi ngâai ngâai kâw khue", "พูดให้ง่ายๆ ก็คือ", "Gramatyka użytkowa", "Parafraza", "phrase", 4, "n", "", "",
 ("W skrócie mówiąc, trzeba złożyć wniosek jeszcze raz.", "phûut hâi ngâai ngâai kâw khue tâwng yûen mài ìik khráng khráp", "พูดให้ง่ายๆ ก็คือต้องยื่นใหม่อีกครั้งครับ")),
("chodźmy do sedna", "khâo rûeang loei dii kwàa khráp", "เข้าเรื่องเลยดีกว่าครับ",
 "Praca i nauka", "Prowadzenie rozmowy", "sentence", 4, "n",
 "„khâo rûeang” = wejść w temat. Uwaga: w Tajlandii nie zaczyna się rozmowy od sedna, ale można do niego przejść po grzecznościach.", "wejść w sprawę",
 ("Chodźmy do sedna, mamy dziesięć minut.", "khâo rûeang loei dii kwàa khráp mii wee-laa sìp naa-thii", "เข้าเรื่องเลยดีกว่าครับ มีเวลาสิบนาที")),
]
