# -*- coding: utf-8 -*-
"""Sesja N — DOM I CODZIENNOŚĆ, ZDROWIE, AWARIE I POMOC, ZAKUPY I PIENIĄDZE.

Awarie i pomoc miały 9 haseł leksykalnych na 595 rekordów — najgorszy stosunek
w całej bazie. Kategoria, w której najbardziej liczy się umiejętność złożenia
zdania samemu, była zbudowana wyłącznie z gotowców. Trudno o gorszy układ:
w kryzysie potrzebne zdanie prawie nigdy nie jest tym, którego się nauczyliśmy.

Krotka: (poziom, polski, fonetyka, pismo, podkategoria, częstość, typ,
         kategoria, uwaga, dosłownie)
"""

DM = "Dom i codzienność"
ZD = "Zdrowie"
AW = "Awarie i pomoc"
ZK = "Zakupy i pieniądze"

LIFE = [

# ============================================================ DOM
("A1", "mieszkanie", "à-phaat-mén", "อพาร์ตเมนต์", "Mieszkanie", 4, "n", DM,
 "Zapożyczenie. Tańsza forma to hâwng phák.", ""),
("A1", "pokój do wynajęcia", "hâwng châo", "ห้องเช่า", "Mieszkanie", 3, "n", DM,
 "", "pokój wynajem"),
("A1", "czynsz", "khâa châo", "ค่าเช่า", "Mieszkanie", 4, "n", DM,
 "khâa- tworzy nazwy opłat: khâa nám, khâa fai, khâa rót.", "opłata wynajem"),
("A2", "rachunek za prąd", "khâa fai", "ค่าไฟ", "Mieszkanie", 4, "n", DM,
 "fai to ogień i prąd jednocześnie.", "opłata prąd"),
("A2", "rachunek za wodę", "khâa nám", "ค่าน้ำ", "Mieszkanie", 4, "n", DM,
 "", "opłata woda"),
("A2", "kuchnia (pomieszczenie)", "hâwng khrua", "ห้องครัว", "Pomieszczenia", 4, "n", DM,
 "", "pokój kuchnia"),
("A2", "sypialnia", "hâwng nawn", "ห้องนอน", "Pomieszczenia", 4, "n", DM,
 "nawn to leżeć i spać.", "pokój spać"),
("A2", "salon", "hâwng nâng lên", "ห้องนั่งเล่น", "Pomieszczenia", 3, "n", DM,
 "Dosłownie „pokój siedzenia dla zabawy”.", "pokój siedzieć bawić się"),
("A2", "jadalnia", "hâwng aa-hǎan", "ห้องอาหาร", "Pomieszczenia", 3, "n", DM,
 "W hotelu to samo słowo znaczy restaurację.", "pokój jedzenie"),
("A2", "garaż", "roong rót", "โรงรถ", "Pomieszczenia", 2, "n", DM,
 "", "hala pojazd"),
("A2", "dach", "lǎng-khaa", "หลังคา", "Części domu", 3, "n", DM,
 "", ""),
("A2", "ściana", "phà-nǎng", "ผนัง", "Części domu", 3, "n", DM,
 "Mur zewnętrzny to kam-phaeng.", ""),
("A2", "podłoga", "phúeun", "พื้น", "Części domu", 3, "n", DM,
 "Także „powierzchnia” i „tło”.", ""),
("A2", "sufit", "phee-daan", "เพดาน", "Części domu", 2, "n", DM,
 "", ""),
("A1", "okno", "nâa tàang", "หน้าต่าง", "Części domu", 4, "n", DM,
 "Dosłownie „twarz obcy”.", "twarz obcy"),
("A2", "schody", "ban-dai", "บันได", "Części domu", 4, "n", DM,
 "Także drabina.", ""),
("A2", "brama, furtka", "prà-tuu rúa", "ประตูรั้ว", "Części domu", 2, "n", DM,
 "rúa to płot.", "drzwi płot"),
("A2", "meble", "foe-ní-jôe", "เฟอร์นิเจอร์", "Wyposażenie", 3, "n", DM,
 "", ""),
("A1", "szafa", "tûu sûea phâa", "ตู้เสื้อผ้า", "Wyposażenie", 3, "n", DM,
 "sûea phâa to ubrania zbiorczo.", "szafa ubranie"),
("A2", "półka", "chán waang khǎwng", "ชั้นวางของ", "Wyposażenie", 2, "n", DM,
 "waang to kłaść, stawiać.", "warstwa kłaść rzecz"),
("A2", "lustro", "krà-jòk ngao", "กระจกเงา", "Wyposażenie", 3, "n", DM,
 "krà-jòk samo to szkło i szyba.", "szkło cień"),
("A2", "pralka", "khrûeang sák phâa", "เครื่องซักผ้า", "Wyposażenie", 3, "n", DM,
 "khrûeang to maszyna, urządzenie — bardzo produktywny przedrostek.", "maszyna prać tkanina"),
("A2", "kuchenka", "tao", "เตา", "Wyposażenie", 3, "n", DM,
 "Także piec i palnik.", ""),
("A2", "mikrofalówka", "mai-khroo-wéep", "ไมโครเวฟ", "Wyposażenie", 2, "n", DM,
 "", ""),
("A2", "wentylator", "phát lom", "พัดลม", "Wyposażenie", 5, "n", DM,
 "Dosłownie „dmuchać wiatr”. W większości domów zamiast klimatyzacji.", "dmuchać wiatr"),
("A2", "moskitiera", "múng", "มุ้ง", "Wyposażenie", 3, "n", DM,
 "", ""),
("A2", "śmietnik", "thǎng khà-yà", "ถังขยะ", "Wyposażenie", 3, "n", DM,
 "thǎng to zbiornik, wiadro, beczka.", "wiadro śmieci"),
("A2", "miotła", "mái kwàat", "ไม้กวาด", "Sprzątanie", 2, "n", DM,
 "kwàat to zamiatać.", "drewno zamiatać"),
("A2", "zamiatać", "kwàat", "กวาด", "Sprzątanie", 3, "v", DM,
 "", ""),
("A2", "myć podłogę", "thǔu phúeun", "ถูพื้น", "Sprzątanie", 3, "v", DM,
 "thǔu to trzeć, szorować.", "trzeć podłoga"),
("A2", "zmywać naczynia", "láang jaan", "ล้างจาน", "Sprzątanie", 4, "v", DM,
 "láang to myć wodą — także ręce i zdjęcia.", "myć talerz"),
("A2", "prać", "sák phâa", "ซักผ้า", "Sprzątanie", 4, "v", DM,
 "", "prać tkanina"),
("A2", "prasować", "rîit phâa", "รีดผ้า", "Sprzątanie", 3, "v", DM,
 "", "prasować tkanina"),
("A2", "wieszać (pranie)", "taak phâa", "ตากผ้า", "Sprzątanie", 3, "v", DM,
 "taak to wystawiać na słońce — także taak dàet o sobie.", "suszyć tkanina"),
("A2", "wyrzucać", "thíng", "ทิ้ง", "Sprzątanie", 4, "v", DM,
 "Także „porzucić kogoś”.", ""),
("A2", "porządkować", "jàt", "จัด", "Sprzątanie", 4, "v", DM,
 "Bardzo produktywne: jàt hâwng, jàt kaan (zarządzać), jàt ngaan (zorganizować).", ""),
("A2", "naprawiać", "sâwm", "ซ่อม", "Sprzątanie", 4, "v", DM,
 "Homofon z sâwm (widelec) — rozstrzyga kontekst i pisownia.", ""),
("A2", "budzik", "naa-lí-kaa plùk", "นาฬิกาปลุก", "Codzienność", 3, "n", DM,
 "plùk to budzić kogoś.", "zegar budzić"),
("A2", "myć zęby", "praeng fan", "แปรงฟัน", "Codzienność", 4, "v", DM,
 "praeng to szczotka i szczotkować.", "szczotka ząb"),
("A2", "brać prysznic", "àap nám", "อาบน้ำ", "Codzienność", 5, "v", DM,
 "Dosłownie „kąpać wodę”. W tym klimacie zwykle dwa razy dziennie.", "kąpać woda"),
("A2", "ubierać się", "tàeng tua", "แต่งตัว", "Codzienność", 4, "v", DM,
 "Ten sam czasownik tàeng co w tàeng ngaan (ślub).", "ozdabiać ciało"),
("A2", "odpoczywać", "phák phàwn", "พักผ่อน", "Codzienność", 4, "v", DM,
 "phák samo znaczy też zatrzymać się na nocleg.", ""),
("A2", "drzemka", "ngîip", "งีบ", "Codzienność", 3, "n", DM,
 "Po obiedzie powszechna i akceptowana.", ""),

# ============================================================ ZDROWIE
("A1", "ból", "khwaam jèp", "ความเจ็บ", "Objawy", 3, "n", ZD,
 "jèp to boleć od urazu; pùat to ból tępy, wewnętrzny.", "stan boleć"),
("A1", "boleć (tępo)", "pùat", "ปวด", "Objawy", 5, "v", ZD,
 "pùat hǔa, pùat tháwng, pùat lǎng — głowa, brzuch, plecy.", ""),
("A1", "boleć (ostro, rana)", "jèp", "เจ็บ", "Objawy", 5, "v", ZD,
 "Różnica z pùat jest realna i lekarz o nią zapyta.", ""),
("A2", "gorączka", "khâi", "ไข้", "Objawy", 5, "n", ZD,
 "pen khâi — mieć gorączkę. Uwaga: khài to jajko, khǎi to sprzedawać.", ""),
("A2", "kaszel", "ai", "ไอ", "Objawy", 4, "n", ZD,
 "Także czasownik. Homofon ze skrótem od „ai” w mowie potocznej.", ""),
("A2", "katar", "nám mûuk", "น้ำมูก", "Objawy", 4, "n", ZD,
 "Dosłownie „woda z nosa”.", "woda nos"),
("A2", "ból gardła", "jèp khaw", "เจ็บคอ", "Objawy", 4, "n", ZD,
 "khaw to szyja i gardło.", "boleć gardło"),
("A2", "biegunka", "tháwng sǐa", "ท้องเสีย", "Objawy", 4, "n", ZD,
 "Dosłownie „brzuch się zepsuł”. Najczęstsza dolegliwość podróżnych.", "brzuch psuć się"),
("A2", "wymiotować", "aa-jian", "อาเจียน", "Objawy", 3, "v", ZD,
 "Potocznie: ûak.", ""),
("A2", "zawroty głowy", "wian hǔa", "เวียนหัว", "Objawy", 4, "n", ZD,
 "wian to krążyć — ten sam wyraz co w wong wian (rondo).", "krążyć głowa"),
("A2", "wysypka", "phùuen", "ผื่น", "Objawy", 3, "n", ZD,
 "", ""),
("A2", "swędzieć", "khan", "คัน", "Objawy", 3, "v", ZD,
 "", ""),
("A2", "opuchlizna", "buam", "บวม", "Objawy", 3, "n", ZD,
 "Także czasownik.", ""),
("A2", "skaleczenie", "phlǎe", "แผล", "Objawy", 4, "n", ZD,
 "Także rana i blizna.", ""),
("A2", "oparzenie słoneczne", "phǐu mâi dàet", "ผิวไหม้แดด", "Objawy", 3, "n", ZD,
 "phǐu to skóra, mâi to palić się.", "skóra palić się słońce"),
("A2", "ukąszenie owada", "má-laeng kàt", "แมลงกัด", "Objawy", 3, "n", ZD,
 "kàt to gryźć.", "owad gryźć"),
("A2", "alergia", "phǽe", "แพ้", "Objawy", 4, "v", ZD,
 "To samo słowo znaczy „przegrać”. phǽe thùa — uczulenie na orzeszki, zdanie ratujące życie.", ""),
("A2", "zatrucie pokarmowe", "aa-hǎan pen phít", "อาหารเป็นพิษ", "Objawy", 3, "n", ZD,
 "phít to trucizna i błąd.", "jedzenie być trucizna"),
("A2", "złamanie", "kràdùuk hàk", "กระดูกหัก", "Objawy", 2, "n", ZD,
 "kràdùuk to kość, hàk to złamać.", "kość łamać"),
("A2", "krwawić", "lûeat àwk", "เลือดออก", "Objawy", 3, "v", ZD,
 "lûeat to krew.", "krew wychodzić"),
("A1", "lekarstwo na ból", "yaa kâe pùat", "ยาแก้ปวด", "Leczenie", 5, "n", ZD,
 "kâe to naprawiać, przeciwdziałać — yaa kâe + objaw działa dla większości leków.", "lek przeciw ból"),
("A2", "antybiotyk", "yaa khâa chúea", "ยาฆ่าเชื้อ", "Leczenie", 3, "n", ZD,
 "Dosłownie „lek zabijający zarazki”.", "lek zabijać zarazek"),
("A2", "maść", "yaa thaa", "ยาทา", "Leczenie", 3, "n", ZD,
 "thaa to smarować, nakładać.", "lek smarować"),
("A2", "plaster", "phlaas-tôe", "พลาสเตอร์", "Leczenie", 3, "n", ZD,
 "", ""),
("A2", "bandaż", "phâa phan phlǎe", "ผ้าพันแผล", "Leczenie", 2, "n", ZD,
 "phan to owijać.", "tkanina owijać rana"),
("A2", "zastrzyk", "chìit yaa", "ฉีดยา", "Leczenie", 3, "n", ZD,
 "chìit to wstrzykiwać i spryskiwać.", "wstrzykiwać lek"),
("A2", "szczepienie", "chìit wák-siin", "ฉีดวัคซีน", "Leczenie", 3, "n", ZD,
 "", "wstrzykiwać szczepionka"),
("A2", "badanie, kontrola", "tùuat", "ตรวจ", "Leczenie", 4, "v", ZD,
 "Ten sam czasownik co na kontroli paszportowej.", ""),
("A2", "recepta", "bai sàng yaa", "ใบสั่งยา", "Leczenie", 3, "n", ZD,
 "sàng to zamawiać i nakazywać — także w restauracji.", "arkusz zamawiać lek"),
("A2", "dawka", "khà-nàat yaa", "ขนาดยา", "Leczenie", 3, "n", ZD,
 "khà-nàat to rozmiar — także ubrania.", "rozmiar lek"),
("A2", "po jedzeniu", "lǎng aa-hǎan", "หลังอาหาร", "Leczenie", 4, "adv", ZD,
 "Napis na każdym opakowaniu leku.", "po jedzenie"),
("A2", "przed jedzeniem", "kàwn aa-hǎan", "ก่อนอาหาร", "Leczenie", 4, "adv", ZD,
 "", "przed jedzenie"),
("A2", "szpital prywatny", "roong phá-yaa-baan èek-kà-chon", "โรงพยาบาลเอกชน", "Placówki", 3, "n", ZD,
 "Droższy, ale bez kolejki i z personelem mówiącym po angielsku.", "szpital prywatny"),
("A2", "przychodnia", "khli-ník", "คลินิก", "Placówki", 3, "n", ZD,
 "Wystarcza przy drobnych sprawach i jest tania.", ""),
("A2", "dentysta", "mǎw fan", "หมอฟัน", "Placówki", 3, "n", ZD,
 "mǎw to lekarz w mowie potocznej.", "lekarz ząb"),
("A2", "pogotowie", "rót phá-yaa-baan", "รถพยาบาล", "Placówki", 3, "n", ZD,
 "Numer alarmowy: 1669.", "pojazd szpital"),
("A2", "ubezpieczenie", "prà-kan", "ประกัน", "Placówki", 4, "n", ZD,
 "prà-kan sùk-khà-phâap — ubezpieczenie zdrowotne.", ""),
("B1", "operacja", "phàa tàt", "ผ่าตัด", "Leczenie", 2, "n", ZD,
 "phàa to rozcinać — ten sam wyraz co w fáa phàa.", "rozcinać ciąć"),
("B1", "ciśnienie krwi", "khwaam dan loo-hìt", "ความดันโลหิต", "Leczenie", 2, "n", ZD,
 "dan to naciskać.", "stan nacisk krew"),
("B1", "cukrzyca", "bao wǎan", "เบาหวาน", "Leczenie", 2, "n", ZD,
 "Dosłownie „słodki mocz” — nazwa opisowa, jak w wielu językach.", "mocz słodki"),
("B1", "zdrowieć", "hǎai", "หาย", "Leczenie", 4, "v", ZD,
 "To samo słowo znaczy „zniknąć” i „zgubić się” — choroba po prostu znika.", ""),

# ============================================================ AWARIE I POMOC
("A1", "wypadek", "ù-bàt-tì-hèet", "อุบัติเหตุ", "Sytuacje", 4, "n", AW,
 "Cztery sylaby; w mowie zlewają się do trzech.", ""),
("A1", "pożar", "fai mâi", "ไฟไหม้", "Sytuacje", 3, "n", AW,
 "Dosłownie „ogień pali”. Uwaga: mâi to tu „palić się”, nie przeczenie.", "ogień palić się"),
("A1", "kradzież", "khà-mooi", "ขโมย", "Sytuacje", 4, "n", AW,
 "Także złodziej i czasownik „ukraść”.", ""),
("A2", "oszustwo", "kohng", "โกง", "Sytuacje", 3, "n", AW,
 "Także oszukiwać w grze i w rachunku.", ""),
("A2", "zgubić coś", "tham hǎai", "ทำหาย", "Sytuacje", 5, "v", AW,
 "Dosłownie „sprawić, że zniknęło”.", "robić znikać"),
("A2", "znaleźć", "jooe", "เจอ", "Sytuacje", 5, "v", AW,
 "Także „spotkać kogoś” — to samo słowo.", ""),
("A2", "szukać", "hǎa", "หา", "Sytuacje", 5, "v", AW,
 "Uwaga na parę: hǎa (szukać) kontra hâa (pięć).", ""),
("A2", "zepsuty, zepsuć się", "sǐa", "เสีย", "Sytuacje", 5, "adj", AW,
 "Bardzo szerokie: zepsute jedzenie, zepsuty sprzęt, stracone pieniądze, śmierć.", ""),
("A2", "nie działa", "mâi tham ngaan", "ไม่ทำงาน", "Sytuacje", 4, "v", AW,
 "Dosłownie „nie pracuje”. O sprzęcie i o człowieku.", "nie robić praca"),
("A2", "zatkany", "tan", "ตัน", "Sytuacje", 3, "adj", AW,
 "O rurze, o nosie i o głowie.", ""),
("A2", "przeciekać", "rûa", "รั่ว", "Sytuacje", 3, "v", AW,
 "O dachu, o kranie i o informacji.", ""),
("A2", "utknąć", "tìt", "ติด", "Sytuacje", 5, "v", AW,
 "Także „przykleić”, „uzależnić się” i „zapalić światło”.", ""),
("A2", "brakować, kończyć się", "mòt", "หมด", "Sytuacje", 5, "v", AW,
 "nám mòt — woda się skończyła. Bardzo częste w sklepie i w restauracji.", ""),
("A2", "awaria prądu", "fai dàp", "ไฟดับ", "Sytuacje", 3, "n", AW,
 "dàp to zgasnąć, ugasić.", "prąd gasnąć"),
("A1", "niebezpieczny", "an-tà-raai", "อันตราย", "Ocena sytuacji", 4, "adj", AW,
 "Napis na znakach ostrzegawczych.", ""),
("A1", "bezpieczny", "plàwt phai", "ปลอดภัย", "Ocena sytuacji", 4, "adj", AW,
 "plàwt to wolny od czegoś; phai to zagrożenie.", "wolny zagrożenie"),
("A2", "pilne", "dùan", "ด่วน", "Ocena sytuacji", 4, "adj", AW,
 "Ten sam wyraz co w thaang dùan (droga ekspresowa).", ""),
("A2", "poważny", "raeng", "แรง", "Ocena sytuacji", 4, "adj", AW,
 "Dosłownie „silny” — o wypadku, bólu i wietrze.", ""),
("A2", "uważaj!", "rá-wang", "ระวัง", "Ocena sytuacji", 5, "v", AW,
 "Pierwsze słowo ostrzeżenia; na tabliczkach i w mowie.", ""),
("A2", "ratować", "chûai chîi-wít", "ช่วยชีวิต", "Reakcja", 3, "v", AW,
 "chîi-wít to życie.", "pomagać życie"),
("A2", "wezwać (kogoś)", "rîak", "เรียก", "Reakcja", 5, "v", AW,
 "rîak tam-rùat, rîak rót phá-yaa-baan. Także „nazywać się”.", ""),
("A2", "zgłosić na policję", "jâeng khwaam", "แจ้งความ", "Reakcja", 3, "v", AW,
 "Konieczne do zgłoszenia ubezpieczycielowi.", "zgłaszać sprawa"),
("A2", "świadek", "phá-yaan", "พยาน", "Reakcja", 2, "n", AW,
 "", ""),
("A2", "protokół, raport", "bai jâeng khwaam", "ใบแจ้งความ", "Reakcja", 2, "n", AW,
 "Dokument z posterunku.", "arkusz zgłaszać sprawa"),
("A2", "czekać na pomoc", "raw khwaam chûai lǔea", "รอความช่วยเหลือ", "Reakcja", 2, "v", AW,
 "", "czekać stan pomagać"),
("B1", "gaśnica", "thǎng dàp phloeng", "ถังดับเพลิง", "Reakcja", 2, "n", AW,
 "phloeng to płomień.", "zbiornik gasić płomień"),
("B1", "apteczka", "chút pà-thǒm phá-yaa-baan", "ชุดปฐมพยาบาล", "Reakcja", 2, "n", AW,
 "chút to zestaw, komplet — także strój.", "zestaw pierwszy pomoc"),

# ============================================================ ZAKUPY
("A1", "cena", "raa-khaa", "ราคา", "Cena", 5, "n", ZK,
 "raa-khaa thâo rai — ile kosztuje.", ""),
("A1", "tani", "thùuk", "ถูก", "Cena", 5, "adj", ZK,
 "To samo słowo znaczy „poprawny” — thùuk tâwng. Kontekst rozstrzyga.", ""),
("A1", "drogi", "phaeng", "แพง", "Cena", 5, "adj", ZK,
 "phaeng pai — za drogo, otwarcie targowania.", ""),
("A2", "zniżka, rabat", "sùan lót", "ส่วนลด", "Cena", 4, "n", ZK,
 "lót to obniżać.", "część obniżać"),
("A2", "obniżyć cenę", "lót raa-khaa", "ลดราคา", "Cena", 5, "v", ZK,
 "Prośba: lót nòi dâi mǎi.", "obniżać cena"),
("A2", "targować się", "tàw raa-khaa", "ต่อราคา", "Cena", 4, "v", ZK,
 "Na targu oczekiwane, w sklepie z ceną na metce — nie.", "przedłużać cena"),
("A2", "wyprzedaż", "lót raa-khaa phí-sèet", "ลดราคาพิเศษ", "Cena", 3, "n", ZK,
 "phí-sèet to specjalny — także o daniu poza menu.", "obniżka cena specjalny"),
("A2", "za darmo", "free", "ฟรี", "Cena", 4, "adj", ZK,
 "Zapożyczenie wymawiane bez zbitki: „fi-rii”.", ""),
("A2", "gotówka", "ngoen sòt", "เงินสด", "Płatność", 5, "n", ZK,
 "sòt to świeży — dosłownie „świeże pieniądze”.", "pieniądze świeży"),
("A2", "reszta (wydana)", "ngoen thawn", "เงินทอน", "Płatność", 4, "n", ZK,
 "thawn to wydawać resztę.", "pieniądze wydawać resztę"),
("A2", "drobne", "ngoen yâwi", "เงินย่อย", "Płatność", 4, "n", ZK,
 "Kluczowe przy taksówce i na targu — nikt nie ma reszty z tysiąca.", "pieniądze drobny"),
("A2", "banknot", "bank", "แบงก์", "Płatność", 4, "n", ZK,
 "Z angielskiego banknote. bank pha, bank rói.", ""),
("A2", "moneta", "rǐan", "เหรียญ", "Płatność", 3, "n", ZK,
 "Także medal.", ""),
("A2", "paragon", "bai sèt", "ใบเสร็จ", "Płatność", 4, "n", ZK,
 "sèt to skończony, gotowy.", "arkusz zakończony"),
("A2", "przelew", "oon ngoen", "โอนเงิน", "Płatność", 4, "n", ZK,
 "W Tajlandii płatność przelewem z telefonu jest częstsza niż karta.", "przelewać pieniądze"),
("A2", "kod QR", "khiu-aa khôot", "คิวอาร์โค้ด", "Płatność", 4, "n", ZK,
 "Nawet uliczny sprzedawca ma naklejkę z kodem.", ""),
("A2", "bankomat", "tûu ee-thii-em", "ตู้เอทีเอ็ม", "Płatność", 4, "n", ZK,
 "Pobiera prowizję od kart zagranicznych.", "szafa bankomat"),
("A2", "rozmiar", "khà-nàat", "ขนาด", "Towar", 4, "n", ZK,
 "khà-nàat lék, klaang, yài.", ""),
("A2", "przymierzyć", "lawng sài", "ลองใส่", "Towar", 4, "v", ZK,
 "lawng to próbować czegokolwiek — także jedzenia.", "próbować wkładać"),
("A2", "wymienić (towar)", "plìan", "เปลี่ยน", "Towar", 5, "v", ZK,
 "Także przesiąść się i zmienić zdanie.", ""),
("A2", "zwrócić (towar)", "khuen khǎwng", "คืนของ", "Towar", 3, "v", ZK,
 "Zwroty bywają nieprzyjęte — warto zapytać przed zakupem.", "zwracać rzecz"),
("A2", "gwarancja", "prà-kan sǐn-kháa", "ประกันสินค้า", "Towar", 3, "n", ZK,
 "", "ubezpieczenie towar"),
("A2", "torba, siatka", "thǔng", "ถุง", "Towar", 4, "n", ZK,
 "Także klasyfikator: nám nùeng thǔng.", ""),
("A2", "opakowanie", "hàw", "ห่อ", "Towar", 3, "n", ZK,
 "Także czasownik „zapakować” — hàw hâi nòi.", ""),
("A2", "na wynos", "sài thǔng", "ใส่ถุง", "Towar", 5, "v", ZK,
 "Dosłownie „włożyć do torby”. Klasyczna formuła w ulicznym barze.", "wkładać torba"),
("A2", "jakość", "khun-ná-phâap", "คุณภาพ", "Towar", 3, "n", ZK,
 "", ""),
("A2", "podróbka", "khǎwng plawm", "ของปลอม", "Towar", 3, "n", ZK,
 "plawm to fałszywy. Przeciwieństwo: khǎwng tháe.", "rzecz fałszywy"),
("A2", "oryginalny", "khǎwng tháe", "ของแท้", "Towar", 3, "n", ZK,
 "tháe to prawdziwy, autentyczny.", "rzecz prawdziwy"),
]
