# -*- coding: utf-8 -*-
"""Dialogi etapu 3 (A2) — czesc B: zdrowie, zakupy, praca, relacje, mieszkanie.

Krotka: (tytul, sytuacja, poziom, rola A, rola B, kwestie, notatka)
"""

DIALOGUES_A2_B = [

("W aptece: ból głowy", "Zdrowie", "A2", "Klient", "Farmaceuta", [
 ("A", "Dzień dobry, poproszę coś na ból głowy.", "sawàt-dii khráp khǎw yaa kâe pùat hǔa khráp", "สวัสดีครับ ขอยาแก้ปวดหัวครับ"),
 ("B", "Od kiedy boli?", "pùat maa naan rǔe yang khráp", "ปวดมานานหรือยังครับ"),
 ("A", "Od wczoraj.", "tâng tàe mûea waan khráp", "ตั้งแต่เมื่อวานครับ"),
 ("B", "Ma pan gorączkę?", "mii khâi mǎi khráp", "มีไข้ไหมครับ"),
 ("A", "Nie, tylko boli głowa.", "mâi mii khráp pùat hǔa yàang diao", "ไม่มีครับ ปวดหัวอย่างเดียว"),
 ("B", "Proszę, dwie tabletki naraz.", "nîi khráp khráng lá sǎwng mét", "นี่ครับ ครั้งละสองเม็ด"),
 ("A", "Ile razy dziennie?", "wan lá kìi khráng khráp", "วันละกี่ครั้งครับ"),
 ("B", "Trzy razy, po jedzeniu.", "wan lá sǎam khráng lǎng aa-hǎan khráp", "วันละสามครั้ง หลังอาหารครับ"),
 ("A", "Biorę już inne leki.", "phǒm kin yaa ùen yùu khráp", "ผมกินยาอื่นอยู่ครับ"),
 ("B", "Jakie dokładnie?", "yaa à-rai khráp", "ยาอะไรครับ"),
 ("A", "Witaminy, nic więcej.", "wí-taa-min khráp mâi mii à-rai ìik", "วิตามินครับ ไม่มีอะไรอีก"),
 ("B", "To bez problemu.", "ngán mâi mii panhǎa khráp", "งั้นไม่มีปัญหาครับ"),
], "Po tajsku lekarstwo się „je” — „kin yaa”. „mét” liczy tabletki, „khráng” — razy."),

("U lekarza: ból brzucha", "Zdrowie", "A2", "Pacjent", "Lekarz", [
 ("B", "Dzień dobry, co dolega?", "sawàt-dii khráp pen à-rai maa khráp", "สวัสดีครับ เป็นอะไรมาครับ"),
 ("A", "Boli mnie brzuch i mam biegunkę.", "phǒm pùat tháwng láew kâw tháwng sǐa khráp", "ผมปวดท้อง แล้วก็ท้องเสียครับ"),
 ("B", "Co pan jadł?", "kin à-rai maa khráp", "กินอะไรมาครับ"),
 ("A", "Jadłem na ulicy wczoraj wieczorem.", "mûea khuen kin aa-hǎan khâang thanǒn khráp", "เมื่อคืนกินอาหารข้างถนนครับ"),
 ("B", "Ile razy dzisiaj?", "wan níi kìi khráng láew khráp", "วันนี้กี่ครั้งแล้วครับ"),
 ("A", "Cztery razy.", "sìi khráng khráp", "สี่ครั้งครับ"),
 ("B", "Wymiotował pan?", "aa-jian mǎi khráp", "อาเจียนไหมครับ"),
 ("A", "Nie, ale jest mi niedobrze.", "mâi khráp tàe khlûen sâi", "ไม่ครับ แต่คลื่นไส้"),
 ("B", "Dam lek i płyny.", "jà hâi yaa kàp klùea râe khráp", "จะให้ยากับเกลือแร่ครับ"),
 ("A", "Czy to coś poważnego?", "raeng mǎi khráp", "แรงไหมครับ"),
 ("B", "Nic groźnego. Proszę dużo pić.", "mâi raeng khráp dùem náam yóe yóe", "ไม่แรงครับ ดื่มน้ำเยอะๆ"),
 ("A", "Poproszę zaświadczenie dla ubezpieczyciela.", "khǎw bai ráp-rawng phâet khráp", "ขอใบรับรองแพทย์ครับ"),
 ("B", "Wystawię.", "dǐao àwk hâi khráp", "เดี๋ยวออกให้ครับ"),
], "„tháwng sǐa” to biegunka — najczęstsza dolegliwość podróżnych. „klùea râe” to elektrolity."),

("Wypadek na skuterze", "Zdrowie", "A2", "Poszkodowany", "Przechodzień", [
 ("A", "Proszę o pomoc, spadłem ze skutera.", "chûai dûai khráp phǒm tòk maw-toe-sai", "ช่วยด้วยครับ ผมตกมอเตอร์ไซค์"),
 ("B", "Może pan wstać?", "lúk dâai mǎi khráp", "ลุกได้ไหมครับ"),
 ("A", "Mogę, ale boli mnie noga.", "lúk dâai khráp tàe pùat khǎa", "ลุกได้ครับ แต่ปวดขา"),
 ("B", "Krwawi pan.", "lûeat àwk khráp", "เลือดออกครับ"),
 ("A", "Rana jest chyba mała.", "phǎe nâa jà lék khráp", "แผลน่าจะเล็กครับ"),
 ("B", "Proszę wezwać pogotowie.", "chûai rîak rót phá-yaa-baan khráp", "ช่วยเรียกรถพยาบาลครับ"),
 ("A", "Wolałbym pojechać taksówką.", "phǒm yàak pai tháek-sîi mâak-kwàa khráp", "ผมอยากไปแท็กซี่มากกว่าครับ"),
 ("B", "Do której kliniki?", "pai khlí-ník nǎi khráp", "ไปคลินิกไหนครับ"),
 ("A", "Do najbliższej.", "khlí-ník thîi klâi thîi sùt khráp", "คลินิกที่ใกล้ที่สุดครับ"),
 ("B", "Pojadę z panem.", "phǒm pai dûai kan khráp", "ผมไปด้วยกันครับ"),
 ("A", "Bardzo dziękuję.", "khàwp-khun mâak khráp", "ขอบคุณมากครับ"),
], "„chûai dûai” to wołanie o pomoc. „phǎe” to rana, „lûeat àwk” — krwawienie."),

("Przymierzanie ubrań", "Zakupy i pieniądze", "A2", "Klient", "Sprzedawca", [
 ("A", "Czy mogę przymierzyć?", "lawng sài dâai mǎi khráp", "ลองใส่ได้ไหมครับ"),
 ("B", "Przymierzalnia tam.", "hâwng lawng yùu thaang nán khráp", "ห้องลองอยู่ทางนั้นครับ"),
 ("A", "To jest za ciasne.", "kháp koen pai khráp", "คับเกินไปครับ"),
 ("B", "Dam większy rozmiar.", "dǐao ao sái yài kwàa maa hâi khráp", "เดี๋ยวเอาไซส์ใหญ่กว่ามาให้ครับ"),
 ("A", "Teraz w sam raz.", "tawn níi phaw dii loei khráp", "ตอนนี้พอดีเลยครับ"),
 ("B", "Ładnie leży.", "sài láew dii khráp", "ใส่แล้วดีครับ"),
 ("A", "Czy jest w innym kolorze?", "mii sǐi ùen mǎi khráp", "มีสีอื่นไหมครับ"),
 ("B", "Jest czarny i granatowy.", "mii sǐi dam kàp sǐi náam ngoen khráp", "มีสีดำกับสีน้ำเงินครับ"),
 ("A", "Wolę ciemniejszy kolor.", "phǒm châwp sǐi khêm kwàa khráp", "ผมชอบสีเข้มกว่าครับ"),
 ("B", "To ten czarny.", "ngán ao sǐi dam khráp", "งั้นเอาสีดำครับ"),
 ("A", "Czy to się kurczy w praniu?", "sák láew hòt mǎi khráp", "ซักแล้วหดไหมครับ"),
 ("B", "Nie kurczy się.", "mâi hòt khráp", "ไม่หดครับ"),
 ("A", "Wezmę to.", "ao an níi khráp", "เอาอันนี้ครับ"),
], "„sái” to rozmiar odzieży, „lawng sài” — przymierzyć. „phaw dii” znaczy „w sam raz”."),

("Targowanie i uprzejma odmowa", "Zakupy i pieniądze", "A2", "Klient", "Sprzedawca", [
 ("B", "Zapraszam, proszę obejrzeć.", "choen khráp choen duu", "เชิญครับ เชิญดู"),
 ("A", "Nie, dziękuję, tylko oglądam.", "mâi khráp khǎw duu kàwn", "ไม่ครับ ขอดูก่อน"),
 ("B", "Ta torba jest bardzo ładna.", "krà-pǎo bai níi sǔai mâak khráp", "กระเป๋าใบนี้สวยมากครับ"),
 ("A", "Ile kosztuje?", "thâo-rài khráp", "เท่าไหร่ครับ"),
 ("B", "Osiemset batów.", "pàet ráwi bàat khráp", "แปดร้อยบาทครับ"),
 ("A", "Dla mnie to za drogo.", "phaeng koen pai sǎm-ràp phǒm khráp", "แพงเกินไปสำหรับผมครับ"),
 ("B", "Ile pan chce dać?", "hâi thâo-rài khráp", "ให้เท่าไหร่ครับ"),
 ("A", "Czy może być tańsza?", "thùuk kwàa níi dâai mǎi khráp", "ถูกกว่านี้ได้ไหมครับ"),
 ("B", "Sześćset, ostatnia cena.", "hòk ráwi khráp raa-khaa sùt tháai", "หกร้อยครับ ราคาสุดท้าย"),
 ("A", "Jeszcze się zastanowię.", "khǎw khít duu kàwn khráp", "ขอคิดดูก่อนครับ"),
 ("B", "Proszę bardzo.", "dâai khráp", "ได้ครับ"),
 ("A", "Dziękuję, może innym razem.", "khàwp-khun khráp wái khráng nâa", "ขอบคุณครับ ไว้ครั้งหน้า"),
], "„khǎw khít duu kàwn” to najgrzeczniejsze wyjście ze sklepu bez zakupu."),

("Rozmowa o pracy", "Praca i nauka", "A2", "Nowo poznany", "Rozmówca", [
 ("A", "Czym się zajmujesz?", "tham ngaan à-rai khráp", "ทำงานอะไรครับ"),
 ("B", "Pracuję w biurze. A ty?", "phǒm tham ngaan áwf-fít khráp láew khun lâ", "ผมทำงานออฟฟิศครับ แล้วคุณล่ะ"),
 ("A", "Pracuję zdalnie.", "phǒm tham ngaan thîi bâan khráp", "ผมทำงานที่บ้านครับ"),
 ("B", "Wygodnie.", "sà-dùak dii khráp", "สะดวกดีครับ"),
 ("A", "Ile godzin dziennie pracujesz?", "tham ngaan wan lá kìi chûa moong khráp", "ทำงานวันละกี่ชั่วโมงครับ"),
 ("B", "Osiem, czasem nadgodziny.", "pàet chûa moong bâang thii mii oo-thii khráp", "แปดชั่วโมง บางทีมีโอทีครับ"),
 ("A", "Kiedy kończysz pracę?", "lôek ngaan kìi moong khráp", "เลิกงานกี่โมงครับ"),
 ("B", "O piątej.", "hâa moong yen khráp", "ห้าโมงเย็นครับ"),
 ("A", "To spotkajmy się po pracy.", "ngán jôe kan lǎng lôek ngaan khráp", "งั้นเจอกันหลังเลิกงานครับ"),
 ("B", "Chętnie, ale dziś mam dużo pracy.", "dâai khráp tàe wan níi ngaan yóe", "ได้ครับ แต่วันนี้งานเยอะ"),
 ("A", "To może w piątek?", "ngán wan sùk dâai mǎi khráp", "งั้นวันศุกร์ได้ไหมครับ"),
 ("B", "Pasuje.", "dâai khráp", "ได้ครับ"),
], "„láew khun lâ” to zwrotne „a ty?”. „oo-thii” to nadgodziny, skrót od angielskiego OT."),

("Prośba o przesunięcie terminu", "Praca i nauka", "A2", "Pracownik", "Przełożony", [
 ("A", "Mam pytanie w sprawie projektu.", "phǒm mii kham thǎam rûeang khroong-kaan khráp", "ผมมีคำถามเรื่องโครงการครับ"),
 ("B", "Słucham.", "wâa maa dâai loei khráp", "ว่ามาได้เลยครับ"),
 ("A", "Kiedy jest termin?", "kam-nòt sòng mûea-rài khráp", "กำหนดส่งเมื่อไหร่ครับ"),
 ("B", "W piątek.", "wan sùk khráp", "วันศุกร์ครับ"),
 ("A", "Potrzebuję więcej czasu.", "phǒm khǎw wee-laa phôoem khráp", "ผมขอเวลาเพิ่มครับ"),
 ("B", "Ile jeszcze?", "khǎw ìik kìi wan khráp", "ขออีกกี่วันครับ"),
 ("A", "Trzy dni.", "sǎam wan khráp", "สามวันครับ"),
 ("B", "Muszę to skonsultować.", "phǒm tâwng prùek-sǎa kàwn khráp", "ผมต้องปรึกษาก่อนครับ"),
 ("A", "Rozumiem. Zajmę się tym dzisiaj.", "khâo-jai khráp wan níi phǒm jà tham hâi", "เข้าใจครับ วันนี้ผมจะทำให้"),
 ("B", "Odpowiem wieczorem.", "yen níi jà tàwp khráp", "เย็นนี้จะตอบครับ"),
 ("A", "Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ"),
], "„kam-nòt sòng” to termin oddania. „prùek-sǎa” — skonsultować z kimś wyżej."),

("Problem z internetem", "Dom i codzienność", "A2", "Klient", "Obsługa", [
 ("A", "Internet jest bardzo wolny.", "nét cháa mâak khráp", "เน็ตช้ามากครับ"),
 ("B", "Od kiedy?", "tâng tàe mûea-rài khráp", "ตั้งแต่เมื่อไหร่ครับ"),
 ("A", "Od dziś rano.", "tâng tàe cháo níi khráp", "ตั้งแต่เช้านี้ครับ"),
 ("B", "Zrestartuję router.", "dǐao rii-sèt ráo-tôe khráp", "เดี๋ยวรีเซ็ตเราเตอร์ครับ"),
 ("A", "Nie mogę się połączyć.", "phǒm chûeam tàw mâi dâai khráp", "ผมเชื่อมต่อไม่ได้ครับ"),
 ("B", "Jakie jest hasło, które pan wpisuje?", "chái phâat-woet à-rai khráp", "ใช้พาสเวิร์ดอะไรครับ"),
 ("A", "Hasło nie działa.", "phâat-woet chái mâi dâai khráp", "พาสเวิร์ดใช้ไม่ได้ครับ"),
 ("B", "Podam nowe.", "dǐao hâi phâat-woet mài khráp", "เดี๋ยวให้พาสเวิร์ดใหม่ครับ"),
 ("A", "Skończył mi się też pakiet.", "nét nai thoo-rasàp kâw mòt dûai khráp", "เน็ตในโทรศัพท์ก็หมดด้วยครับ"),
 ("B", "Można doładować w sklepie obok.", "toem dâai thîi ráan khâang khâang khráp", "เติมได้ที่ร้านข้างๆ ครับ"),
 ("A", "Dziękuję za pomoc.", "khàwp-khun thîi chûai khráp", "ขอบคุณที่ช่วยครับ"),
], "„chûeam tàw” to połączyć się z siecią. „toem” — doładować konto lub pakiet."),

("Oglądanie mieszkania", "Dom i codzienność", "A2", "Najemca", "Właściciel", [
 ("A", "Szukam mieszkania do wynajęcia.", "phǒm hǎa hâwng châo yùu khráp", "ผมหาห้องเช่าอยู่ครับ"),
 ("B", "Na jak długo?", "châo naan thâo-rài khráp", "เช่านานเท่าไหร่ครับ"),
 ("A", "Na sześć miesięcy.", "hòk duean khráp", "หกเดือนครับ"),
 ("B", "Mam pokój na trzecim piętrze.", "mii hâwng chán sǎam khráp", "มีห้องชั้นสามครับ"),
 ("A", "Ile wynosi czynsz miesięczny?", "khâa châo duean lá thâo-rài khráp", "ค่าเช่าเดือนละเท่าไหร่ครับ"),
 ("B", "Osiem tysięcy.", "pàet phan khráp", "แปดพันครับ"),
 ("A", "Czy prąd jest wliczony?", "ruam khâa fai fáa mǎi khráp", "รวมค่าไฟฟ้าไหมครับ"),
 ("B", "Płaci się osobno.", "jàai yâek khráp", "จ่ายแยกครับ"),
 ("A", "Czy mieszkanie jest umeblowane?", "mii foe-ní-jôe mǎi khráp", "มีเฟอร์นิเจอร์ไหมครับ"),
 ("B", "Jest łóżko i szafa.", "mii tiang kàp tûu sûea phâa khráp", "มีเตียงกับตู้เสื้อผ้าครับ"),
 ("A", "Jaka jest kaucja?", "khâa mát jam thâo-rài khráp", "ค่ามัดจำเท่าไหร่ครับ"),
 ("B", "Dwa czynsze.", "sǎwng duean khráp", "สองเดือนครับ"),
 ("A", "Chciałbym obejrzeć.", "phǒm yàak duu hâwng khráp", "ผมอยากดูห้องครับ"),
], "„duean lá” znaczy „miesięcznie”. „mát jam” to kaucja zwrotna."),

("Awaria w mieszkaniu", "Dom i codzienność", "A2", "Najemca", "Właściciel", [
 ("A", "Dzień dobry, nie ma wody.", "sawàt-dii khráp náam mâi lǎi khráp", "สวัสดีครับ น้ำไม่ไหลครับ"),
 ("B", "W całym budynku?", "tháng tùek rǔe plào khráp", "ทั้งตึกหรือเปล่าครับ"),
 ("A", "Nie wiem, sprawdzę u sąsiada.", "mâi rúu khráp dǐao thǎam khon khâang khâang", "ไม่รู้ครับ เดี๋ยวถามคนข้างๆ"),
 ("B", "Dobrze, proszę dać znać.", "dâai khráp bàwk dûai ná", "ได้ครับ บอกด้วยนะ"),
 ("A", "Cieknie też kran w kuchni.", "káwk náam nai khrua rûa dûai khráp", "ก๊อกน้ำในครัวรั่วด้วยครับ"),
 ("B", "Wezwę technika.", "dǐao rîak châang khráp", "เดี๋ยวเรียกช่างครับ"),
 ("A", "Kiedy przyjdzie technik?", "châang jà maa mûea-rài khráp", "ช่างจะมาเมื่อไหร่ครับ"),
 ("B", "Po południu.", "tawn bàai khráp", "ตอนบ่ายครับ"),
 ("A", "Będę w domu do piątej.", "phǒm yùu bâan thǔeng hâa moong yen khráp", "ผมอยู่บ้านถึงห้าโมงเย็นครับ"),
 ("B", "Zdąży przed piątą.", "maa than kàwn hâa moong khráp", "มาทันก่อนห้าโมงครับ"),
 ("A", "Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ"),
], "„náam mâi lǎi” to brak wody w kranie. „châang” to fachowiec, „rûa” — przeciekać."),

("Rozmowa o hobby", "Small talk", "A2", "Znajomy", "Znajoma", [
 ("A", "Co robisz w wolnym czasie?", "wee-laa wâang tham à-rai khráp", "เวลาว่างทำอะไรครับ"),
 ("B", "Lubię czytać książki. A ty?", "phǒm châwp àan nǎng-sǔe khráp láew khun lâ", "ผมชอบอ่านหนังสือครับ แล้วคุณล่ะ"),
 ("A", "Lubię robić zdjęcia.", "phǒm châwp thàai rûup khráp", "ผมชอบถ่ายรูปครับ"),
 ("B", "Często robisz zdjęcia?", "thàai rûup bàwi mǎi khráp", "ถ่ายรูปบ่อยไหมครับ"),
 ("A", "Codziennie robię zdjęcia.", "phǒm thàai rûup thúk wan khráp", "ผมถ่ายรูปทุกวันครับ"),
 ("B", "Umiesz też gotować?", "tham aa-hǎan pen mǎi khráp", "ทำอาหารเป็นไหมครับ"),
 ("A", "Nie umiem gotować.", "phǒm tham aa-hǎan mâi pen khráp", "ผมทำอาหารไม่เป็นครับ"),
 ("B", "Ja umiem, mogę nauczyć.", "phǒm tham pen khráp sǎwn hâi dâai", "ผมทำเป็นครับ สอนให้ได้"),
 ("A", "Chętnie. Pogotujemy razem?", "dii loei khráp tham aa-hǎan dûai kan mǎi", "ดีเลยครับ ทำอาหารด้วยกันไหม"),
 ("B", "Chodźmy w sobotę na targ.", "wan sǎo pai tà-làat kan thòe", "วันเสาร์ไปตลาดกันเถอะ"),
 ("A", "Świetny pomysł.", "khwaam khít dii khráp", "ความคิดดีครับ"),
], "„pen” po czasowniku znaczy „umieć”. „dûai kan” — razem, wspólnie."),

("Poznawanie się", "Ludzie i rodzina", "A2", "Turysta", "Miejscowy", [
 ("A", "Miło cię poznać.", "yin dii thîi dâi rúu-jàk khráp", "ยินดีที่ได้รู้จักครับ"),
 ("B", "Mnie również. Jesteś tu na wakacjach?", "yin dii chên kan khráp maa thîao rǔe khráp", "ยินดีเช่นกันครับ มาเที่ยวหรือครับ"),
 ("A", "Tak, jestem tu na wakacjach.", "châi khráp phǒm maa thîao", "ใช่ครับ ผมมาเที่ยว"),
 ("B", "Byłeś już w Tajlandii wcześniej?", "khoei maa mueang thai mǎi khráp", "เคยมาเมืองไทยไหมครับ"),
 ("A", "Byłem już raz, dwa lata temu.", "khoei maa khráng nùeng mûea sǎwng pii thîi láew khráp", "เคยมาครั้งหนึ่ง เมื่อสองปีที่แล้วครับ"),
 ("B", "Uczysz się tajskiego?", "rian phaa-sǎa thai rǔe khráp", "เรียนภาษาไทยหรือครับ"),
 ("A", "Uczę się od pół roku.", "phǒm rian maa khrûeng pii láew khráp", "ผมเรียนมาครึ่งปีแล้วครับ"),
 ("B", "Dobrze ci idzie.", "kèng mâak khráp", "เก่งมากครับ"),
 ("A", "Dziękuję, ale to trudniejsze, niż myślałem.", "khàwp-khun khráp tàe yâak kwàa thîi khít wái", "ขอบคุณครับ แต่ยากกว่าที่คิดไว้"),
 ("B", "Tony są trudne dla wszystkich.", "sǐang wan-ná-yúk yâak sǎm-ràp thúk khon khráp", "เสียงวรรณยุกต์ยากสำหรับทุกคนครับ"),
 ("A", "Chciałbym tu wrócić.", "phǒm yàak klàp maa ìik khráp", "ผมอยากกลับมาอีกครับ"),
 ("B", "Czekamy.", "raw yùu ná khráp", "รออยู่นะครับ"),
], "„khoei” opisuje doświadczenie. „thîi láew” po jednostce czasu znaczy „temu”."),

("Zaproszenie i uprzejma odmowa", "Small talk", "A2", "Zapraszający", "Zaproszony", [
 ("A", "Idziemy dziś wieczorem na miasto?", "yen níi pai thîao kan mǎi khráp", "เย็นนี้ไปเที่ยวกันไหมครับ"),
 ("B", "Dziś nie mogę.", "wan níi mâi dâai khráp", "วันนี้ไม่ได้ครับ"),
 ("A", "Coś się stało?", "koet à-rai khûen rǔe plào khráp", "เกิดอะไรขึ้นหรือเปล่าครับ"),
 ("B", "Mam już plany.", "phǒm mii nát láew khráp", "ผมมีนัดแล้วครับ"),
 ("A", "A jutro?", "ngán phrûng níi lâ khráp", "งั้นพรุ่งนี้ล่ะครับ"),
 ("B", "Jutro jestem bardzo zmęczony po pracy.", "phrûng níi nùeai mâak lǎng lôek ngaan khráp", "พรุ่งนี้เหนื่อยมากหลังเลิกงานครับ"),
 ("A", "Rozumiem.", "khâo-jai khráp", "เข้าใจครับ"),
 ("B", "Może innym razem.", "wái khráng nâa ná khráp", "ไว้ครั้งหน้านะครับ"),
 ("A", "Jasne, daj znać.", "dâai khráp bàwk dûai ná", "ได้ครับ บอกด้วยนะ"),
 ("B", "Dziękuję za zaproszenie.", "khàwp-khun thîi chuan khráp", "ขอบคุณที่ชวนครับ"),
], "„wái khráng nâa” to odmowa, która nie zamyka drzwi — najczęstsza forma po tajsku."),

("Rozmowa telefoniczna", "Praca i nauka", "A2", "Dzwoniący", "Odbierający", [
 ("A", "Halo, słyszysz mnie?", "hallǒo dâi yin mǎi khráp", "ฮัลโหล ได้ยินไหมครับ"),
 ("B", "Słabo, zasięg jest kiepski.", "dâi yin mâi chát khráp sǎn-yaan mâi dii", "ได้ยินไม่ชัดครับ สัญญาณไม่ดี"),
 ("A", "Wyjdę na zewnątrz.", "dǐao àwk pai khâang nâwk khráp", "เดี๋ยวออกไปข้างนอกครับ"),
 ("B", "Teraz lepiej.", "tawn níi dii khûen khráp", "ตอนนี้ดีขึ้นครับ"),
 ("A", "Dzwonię w sprawie jutra.", "thoo maa rûeang phrûng níi khráp", "โทรมาเรื่องพรุ่งนี้ครับ"),
 ("B", "Słucham.", "wâa maa dâai loei khráp", "ว่ามาได้เลยครับ"),
 ("A", "Mam mało baterii.", "baet nói láew khráp", "แบตน้อยแล้วครับ"),
 ("B", "To wyślij wiadomość.", "ngán sòng khâw-khwaam maa khráp", "งั้นส่งข้อความมาครับ"),
 ("A", "Dobrze, napiszę.", "dâai khráp dǐao tháek pai", "ได้ครับ เดี๋ยวแชทไป"),
 ("B", "Czekam.", "raw yùu khráp", "รออยู่ครับ"),
], "„dâi yin mâi chát” znaczy „słyszę niewyraźnie”. „baet” to potoczny skrót od baterii."),

("Kradzież portfela na targu", "Awarie i pomoc", "A2", "Turysta", "Przechodzień", [
 ("A", "Przepraszam, czy może mi pan pomóc?", "khǎw-thôot khráp chûai phǒm nòi dâai mǎi", "ขอโทษครับ ช่วยผมหน่อยได้ไหม"),
 ("B", "Oczywiście, co się stało?", "dâai loei khráp koet à-rai khûen", "ได้เลยครับ เกิดอะไรขึ้น"),
 ("A", "Skradziono mi portfel.", "krà-pǎo taang doon khà-mooi khráp", "กระเป๋าตังค์โดนขโมยครับ"),
 ("B", "Gdzie i kiedy?", "thîi nǎi láe mûea-rài khráp", "ที่ไหนและเมื่อไหร่ครับ"),
 ("A", "Na targu, jakieś pół godziny temu.", "thîi tà-làat prà-maan khrûeng chûa moong thîi láew khráp", "ที่ตลาด ประมาณครึ่งชั่วโมงที่แล้วครับ"),
 ("B", "Trzeba iść na policję.", "tâwng pai jâeng khwaam khráp", "ต้องไปแจ้งความครับ"),
 ("A", "Chcę zgłosić kradzież.", "phǒm yàak jâeng khwaam khráp", "ผมอยากแจ้งความครับ"),
 ("B", "Komisariat jest niedaleko.", "sà-thǎa-nii tam-rùat yùu mâi klai khráp", "สถานีตำรวจอยู่ไม่ไกลครับ"),
 ("A", "Czy ktoś tu mówi po angielsku?", "mii khrai phûut phaa-sǎa ang-krìt dâai mǎi khráp", "มีใครพูดภาษาอังกฤษได้ไหมครับ"),
 ("B", "Pójdę z panem i pomogę.", "phǒm pai dûai láew chûai khráp", "ผมไปด้วยแล้วช่วยครับ"),
 ("A", "Jest pan bardzo miły.", "khun jai dii mâak khráp", "คุณใจดีมากครับ"),
 ("B", "Drobiazg.", "mâi mii à-rai khráp", "ไม่มีอะไรครับ"),
], "„doon” tworzy stronę bierną w mowie potocznej: doon khà-mooi = zostać okradzionym."),

("Wymiana walut w kantorze", "Zakupy i pieniądze", "A2", "Klient", "Kantor", [
 ("A", "Chciałbym wymienić pieniądze.", "phǒm yàak lâek ngoen khráp", "ผมอยากแลกเงินครับ"),
 ("B", "Jaka waluta?", "ngoen sà-kun nǎi khráp", "เงินสกุลไหนครับ"),
 ("A", "Euro. Czy mogę zobaczyć kurs wymiany?", "yuu-roo khráp khǎw duu àt-traa lâek plìan nòi dâai mǎi", "ยูโรครับ ขอดูอัตราแลกเปลี่ยนหน่อยได้ไหม"),
 ("B", "Proszę, tutaj na tablicy.", "nîi khráp yùu trong pâai", "นี่ครับ อยู่ตรงป้าย"),
 ("A", "Lepiej, niż myślałem.", "dii kwàa thîi khít wái khráp", "ดีกว่าที่คิดไว้ครับ"),
 ("B", "Ile pan wymienia?", "lâek thâo-rài khráp", "แลกเท่าไหร่ครับ"),
 ("A", "Dwieście euro.", "sǎwng ráwi yuu-roo khráp", "สองร้อยยูโรครับ"),
 ("B", "Poproszę paszport.", "khǎw phaas-pàwt khráp", "ขอพาสปอร์ตครับ"),
 ("A", "Proszę mniejsze banknoty.", "khǎw baeng yói nòi khráp", "ขอแบงก์ย่อยหน่อยครับ"),
 ("B", "Dobrze, proszę policzyć.", "dâai khráp chûai náp duu", "ได้ครับ ช่วยนับดู"),
 ("A", "Zgadza się. Dziękuję.", "thùuk tâwng khráp khàwp-khun", "ถูกต้องครับ ขอบคุณ"),
], "„baeng yói” to drobne banknoty — bardzo przydatne przy taksówkach i na targu."),

("Opowiadanie o planach", "Small talk", "A2", "Turysta", "Znajomy", [
 ("A", "Co robisz w przyszłym tygodniu?", "aa-thít nâa tham à-rai khráp", "อาทิตย์หน้าทำอะไรครับ"),
 ("B", "Zamierzam pojechać na północ.", "phǒm jà pai phâak nǔea khráp", "ผมจะไปภาคเหนือครับ"),
 ("A", "Na jak długo?", "pai kìi wan khráp", "ไปกี่วันครับ"),
 ("B", "Planuję zostać tydzień.", "wǎang phǎen yùu nùeng aa-thít khráp", "วางแผนอยู่หนึ่งอาทิตย์ครับ"),
 ("A", "Byłeś tam już kiedyś?", "khoei pai mǎi khráp", "เคยไปไหมครับ"),
 ("B", "Nigdy tam nie byłem.", "phǒm mâi khoei pai khráp", "ผมไม่เคยไปครับ"),
 ("A", "Warto pojechać.", "nâa pai ná khráp", "น่าไปนะครับ"),
 ("B", "Może zostanę dłużej.", "àat jà yùu naan kwàa níi khráp", "อาจจะอยู่นานกว่านี้ครับ"),
 ("A", "A kiedy wracasz do Polski?", "láew klàp poo-laen mûea-rài khráp", "แล้วกลับโปแลนด์เมื่อไหร่ครับ"),
 ("B", "Mój lot jest w sobotę za miesiąc.", "thîao bin khǎwng phǒm wan sǎo ìik duean nùeng khráp", "เที่ยวบินของผมวันเสาร์อีกเดือนหนึ่งครับ"),
 ("A", "Szerokiej drogi.", "doen thaang plàwt-phai ná khráp", "เดินทางปลอดภัยนะครับ"),
], "„wǎang phǎen” to planować. „àat jà” — być może, ostrożny domysł o przyszłości."),

("Zamawianie masażu", "Small talk", "A2", "Klient", "Recepcja salonu", [
 ("A", "Dzień dobry, chciałbym masaż.", "sawàt-dii khráp phǒm yàak nûat khráp", "สวัสดีครับ ผมอยากนวดครับ"),
 ("B", "Tajski czy olejkowy?", "nûat thai rǔe nûat náam man khráp", "นวดไทยหรือนวดน้ำมันครับ"),
 ("A", "Tajski. Ile wynosi opłata za masaż?", "nûat thai khráp khâa nûat thâo-rài khráp", "นวดไทยครับ ค่านวดเท่าไหร่ครับ"),
 ("B", "Trzysta batów za godzinę.", "chûa moong lá sǎam ráwi bàat khráp", "ชั่วโมงละสามร้อยบาทครับ"),
 ("A", "Poproszę na dwie godziny.", "khǎw sǎwng chûa moong khráp", "ขอสองชั่วโมงครับ"),
 ("B", "Jak mocno?", "ao raeng khâe nǎi khráp", "เอาแรงแค่ไหนครับ"),
 ("A", "Proszę nie za mocno.", "chûai yàa raeng koen pai khráp", "ช่วยอย่าแรงเกินไปครับ"),
 ("B", "Boli gdzieś szczególnie?", "pùat trong nǎi phí-sèet mǎi khráp", "ปวดตรงไหนพิเศษไหมครับ"),
 ("A", "Bolą mnie plecy.", "phǒm pùat lǎng khráp", "ผมปวดหลังครับ"),
 ("B", "Zajmiemy się plecami.", "dǐao nén trong lǎng hâi khráp", "เดี๋ยวเน้นตรงหลังให้ครับ"),
 ("A", "Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ"),
], "„raeng” znaczy mocno. „yàa … koen pai” — nie za bardzo."),

("Skarga na hałas", "Dom i codzienność", "A2", "Mieszkaniec", "Ochroniarz", [
 ("A", "Dzień dobry, mam problem.", "sawàt-dii khráp phǒm mii panhǎa", "สวัสดีครับ ผมมีปัญหา"),
 ("B", "Co się dzieje?", "koet à-rai khûen khráp", "เกิดอะไรขึ้นครับ"),
 ("A", "Sąsiedzi są bardzo głośni.", "hâwng khâang khâang sǐang dang mâak khráp", "ห้องข้างๆ เสียงดังมากครับ"),
 ("B", "Od której godziny?", "tâng tàe kìi moong khráp", "ตั้งแต่กี่โมงครับ"),
 ("A", "Od jedenastej wieczorem.", "tâng tàe hâa thûm khráp", "ตั้งแต่ห้าทุ่มครับ"),
 ("B", "Codziennie?", "thúk wan loei rǔe khráp", "ทุกวันเลยหรือครับ"),
 ("A", "Prawie codziennie.", "kùeap thúk wan khráp", "เกือบทุกวันครับ"),
 ("B", "Zwrócę im uwagę.", "dǐao pai bàwk hâi khráp", "เดี๋ยวไปบอกให้ครับ"),
 ("A", "Nie mogę spać.", "phǒm nawn mâi làp khráp", "ผมนอนไม่หลับครับ"),
 ("B", "Rozumiem, zajmę się tym dziś.", "khâo-jai khráp wan níi jà jàt kaan hâi", "เข้าใจครับ วันนี้จะจัดการให้"),
 ("A", "Byłbym wdzięczny.", "khàwp-khun mâak khráp", "ขอบคุณมากครับ"),
], "„hâa thûm” to 23:00 — wieczorne godziny liczy się od 19:00 jako „nùeng thûm”."),

("Ostatni dzień i pożegnanie", "Small talk", "A2", "Wyjeżdżający", "Znajomy", [
 ("A", "Jutro wracam do Polski.", "phrûng níi phǒm klàp poo-laen khráp", "พรุ่งนี้ผมกลับโปแลนด์ครับ"),
 ("B", "Tak szybko?", "reo jang loei khráp", "เร็วจังเลยครับ"),
 ("A", "Miesiąc minął bardzo szybko.", "nùeng duean phàan pai reo mâak khráp", "หนึ่งเดือนผ่านไปเร็วมากครับ"),
 ("B", "Podobało ci się?", "châwp mǎi khráp", "ชอบไหมครับ"),
 ("A", "Bardzo mi się podobało.", "châwp mâak loei khráp", "ชอบมากเลยครับ"),
 ("B", "Co najbardziej?", "châwp à-rai thîi sùt khráp", "ชอบอะไรที่สุดครับ"),
 ("A", "Jedzenie i ludzie.", "aa-hǎan kàp phûu khon khráp", "อาหารกับผู้คนครับ"),
 ("B", "Będę tęsknić.", "jà khít thǔeng ná khráp", "จะคิดถึงนะครับ"),
 ("A", "Ja też będę tęsknić.", "phǒm kâw jà khít thǔeng mǔean kan khráp", "ผมก็จะคิดถึงเหมือนกันครับ"),
 ("B", "Wracaj do nas.", "klàp maa ìik ná khráp", "กลับมาอีกนะครับ"),
 ("A", "Na pewno wrócę. Dziękuję za wszystko.", "klàp maa nâe nawn khráp khàwp-khun sǎm-ràp thúk yàang", "กลับมาแน่นอนครับ ขอบคุณสำหรับทุกอย่าง"),
 ("B", "Szerokiej drogi i trzymaj się.", "doen thaang plàwt-phai láe duu lae tua eeng ná khráp", "เดินทางปลอดภัยและดูแลตัวเองนะครับ"),
], "„khít thǔeng” to tęsknić za kimś. „nâe nawn” — na pewno."),
]
