# -*- coding: utf-8 -*-
"""Wzorce zdaniowe etapu 5 (B2) — czesc C: konstrukcje rzeczownikowe.

Zakres: prowadzenie sprawy — otwarcie tematu, prosba o dane, wskazanie obawy,
zaleznosc od czegos, negocjowanie punktu, ustalanie odpowiedzialnosci,
potwierdzanie ustalen.

Konstrukcje nieuzywane wczesniej: „kìao kàp”, „khǎw khâw-muun … phôoem”,
„sìng thîi phǒm pen hùang khue”, „thâa mâi mii … kâw tham à-rai mâi dâai”,
„phaw jà tàw rawng dâai mǎi”, „khrai duu-lae”, „chûai yuen-yan … ìik khráng”.

Pozycja: (polskie haslo rekordu, polskie haslo bazowe, polski przyklad)
"""

TPL_C = [

# =====================================================================
# khaw khui rueang thii kiao kap … — otwarcie tematu
# =====================================================================
dict(key="KIAOKAP", ty="sentence", cat="Praca i nauka", sub="Prowadzenie rozmowy", reg="f",
     ph="phǒm khǎw khui rûeang thîi kìao kàp {ph} khráp", th="ผมขอคุยเรื่องที่เกี่ยวกับ{th}ครับ",
     lit="kìao kàp = dotyczący, związany z",
     note="„kìao kàp” otwiera temat formalnie i precyzyjnie. W mowie potocznej wystarczy samo „rûeang”.",
     ex_ph="rûeang thîi kìao kàp {ph} khui kàp khrai dii khráp", ex_th="เรื่องที่เกี่ยวกับ{th}คุยกับใครดีครับ",
     items=[
       ("Chciałbym pomówić w sprawie dotyczącej umowy.", "umowa", "Z kim rozmawiać w sprawie umowy?"),
       ("Chciałbym pomówić w sprawie dotyczącej czynszu.", "czynsz", "Z kim rozmawiać w sprawie czynszu?"),
       ("Chciałbym pomówić w sprawie dotyczącej pensji.", "pensja", "Z kim rozmawiać w sprawie pensji?"),
       ("Chciałbym pomówić w sprawie dotyczącej urlopu.", "urlop", "Z kim rozmawiać w sprawie urlopu?"),
       ("Chciałbym pomówić w sprawie dotyczącej nadgodzin.", "nadgodziny", "Z kim rozmawiać w sprawie nadgodzin?"),
       ("Chciałbym pomówić w sprawie dotyczącej projektu.", "projekt", "Z kim rozmawiać w sprawie projektu?"),
       ("Chciałbym pomówić w sprawie dotyczącej klienta.", "klient", "Z kim rozmawiać w sprawie klienta?"),
       ("Chciałbym pomówić w sprawie dotyczącej dokumentów.", "dokument", "Z kim rozmawiać w sprawie dokumentów?"),
       ("Chciałbym pomówić w sprawie dotyczącej zebrania.", "zebranie", "Z kim rozmawiać w sprawie zebrania?"),
       ("Chciałbym pomówić w sprawie dotyczącej współpracy.", "współpraca", "Z kim rozmawiać w sprawie współpracy?"),
       ("Chciałbym pomówić w sprawie dotyczącej ubezpieczenia.", "ubezpieczenie", "Z kim rozmawiać w sprawie ubezpieczenia?"),
       ("Chciałbym pomówić w sprawie dotyczącej wizy.", "wiza", "Z kim rozmawiać w sprawie wizy?"),
       ("Chciałbym pomówić w sprawie dotyczącej paszportu.", "paszport", "Z kim rozmawiać w sprawie paszportu?"),
       ("Chciałbym pomówić w sprawie dotyczącej konta.", "konto", "Z kim rozmawiać w sprawie konta?"),
       ("Chciałbym pomówić w sprawie dotyczącej przelewu.", "przelew", "Z kim rozmawiać w sprawie przelewu?"),
       ("Chciałbym pomówić w sprawie dotyczącej kaucji.", "kaucja", "Z kim rozmawiać w sprawie kaucji?"),
       ("Chciałbym pomówić w sprawie dotyczącej opłaty.", "opłata", "Z kim rozmawiać w sprawie opłaty?"),
       ("Chciałbym pomówić w sprawie dotyczącej ceny.", "cena", "Z kim rozmawiać w sprawie ceny?"),
       ("Chciałbym pomówić w sprawie dotyczącej rachunku.", "rachunek", "Z kim rozmawiać w sprawie rachunku?"),
       ("Chciałbym pomówić w sprawie dotyczącej pokoju.", "pokój", "Z kim rozmawiać w sprawie pokoju?"),
       ("Chciałbym pomówić w sprawie dotyczącej klimatyzacji.", "klimatyzacja", "Z kim rozmawiać w sprawie klimatyzacji?"),
       ("Chciałbym pomówić w sprawie dotyczącej internetu.", "internet", "Z kim rozmawiać w sprawie internetu?"),
       ("Chciałbym pomówić w sprawie dotyczącej hałasu od sąsiada z góry.", "sąsiad z góry", "Z kim rozmawiać w sprawie sąsiada?"),
       ("Chciałbym pomówić w sprawie dotyczącej właściciela mieszkania.", "właściciel", "Z kim rozmawiać w sprawie właściciela?"),
       ("Chciałbym pomówić w sprawie dotyczącej biletu.", "bilet", "Z kim rozmawiać w sprawie biletu?"),
       ("Chciałbym pomówić w sprawie dotyczącej opóźnienia.", "opóźnienie", "Z kim rozmawiać w sprawie opóźnienia?"),
       ("Chciałbym pomówić w sprawie dotyczącej bagażu.", "walizka", "Z kim rozmawiać w sprawie bagażu?"),
       ("Chciałbym pomówić w sprawie dotyczącej prawa jazdy.", "prawo jazdy", "Z kim rozmawiać w sprawie prawa jazdy?"),
       ("Chciałbym pomówić w sprawie dotyczącej badania.", "badanie", "Z kim rozmawiać w sprawie badania?"),
       ("Chciałbym pomówić w sprawie dotyczącej wyniku badania.", "wynik badania", "Z kim rozmawiać w sprawie wyniku?"),
       ("Chciałbym pomówić w sprawie dotyczącej leków.", "lek", "Z kim rozmawiać w sprawie leków?"),
       ("Chciałbym pomówić w sprawie dotyczącej alergii.", "alergia", "Z kim rozmawiać w sprawie alergii?"),
       ("Chciałbym pomówić w sprawie dotyczącej szkoły.", "szkoła", "Z kim rozmawiać w sprawie szkoły?"),
       ("Chciałbym pomówić w sprawie dotyczącej firmy.", "firma", "Z kim rozmawiać w sprawie firmy?"),
       ("Chciałbym pomówić w sprawie dotyczącej problemu z zeszłego tygodnia.", "problem", "Z kim rozmawiać w sprawie tego problemu?"),
       ("Chciałbym pomówić w sprawie dotyczącej aplikacji.", "aplikacja", "Z kim rozmawiać w sprawie aplikacji?"),
     ]),

# =====================================================================
# khaw khaw-muun rueang … phoem — prosba o dane
# =====================================================================
dict(key="KHAWMUUN", ty="sentence", cat="Praca i nauka", sub="Informacje", reg="f",
     ph="khǎw khâw-muun rûeang {ph} phôoem dâai mǎi khráp", th="ขอข้อมูลเรื่อง{th}เพิ่มได้ไหมครับ",
     lit="khâw-muun = dane, informacje; phôoem = dodatkowo",
     note="Prośba o uzupełnienie informacji, nie o powtórzenie. W urzędzie i banku to naturalne otwarcie.",
     ex_ph="khâw-muun rûeang {ph} duu dâai jàak nǎi khráp", ex_th="ข้อมูลเรื่อง{th}ดูได้จากไหนครับ",
     items=[
       ("Czy mogę prosić o więcej informacji o ubezpieczeniu?", "ubezpieczenie", "Gdzie sprawdzę informacje o ubezpieczeniu?"),
       ("Czy mogę prosić o więcej informacji o umowie?", "umowa", "Gdzie sprawdzę informacje o umowie?"),
       ("Czy mogę prosić o więcej informacji o kaucji?", "kaucja", "Gdzie sprawdzę informacje o kaucji?"),
       ("Czy mogę prosić o więcej informacji o opłatach?", "opłata", "Gdzie sprawdzę informacje o opłatach?"),
       ("Czy mogę prosić o więcej informacji o zniżce?", "zniżka", "Gdzie sprawdzę informacje o zniżce?"),
       ("Czy mogę prosić o więcej informacji o kursie wymiany?", "kurs wymiany", "Gdzie sprawdzę kurs wymiany?"),
       ("Czy mogę prosić o więcej informacji o koncie?", "konto", "Gdzie sprawdzę informacje o koncie?"),
       ("Czy mogę prosić o więcej informacji o przelewie?", "przelew", "Gdzie sprawdzę informacje o przelewie?"),
       ("Czy mogę prosić o więcej informacji o wizie?", "wiza", "Gdzie sprawdzę informacje o wizie?"),
       ("Czy mogę prosić o więcej informacji o prawie jazdy?", "prawo jazdy", "Gdzie sprawdzę informacje o prawie jazdy?"),
       ("Czy mogę prosić o więcej informacji o rozkładzie jazdy?", "rozkład jazdy", "Gdzie sprawdzę rozkład jazdy?"),
       ("Czy mogę prosić o więcej informacji o bilecie?", "bilet", "Gdzie sprawdzę informacje o bilecie?"),
       ("Czy mogę prosić o więcej informacji o opóźnieniu?", "opóźnienie", "Gdzie sprawdzę informacje o opóźnieniu?"),
       ("Czy mogę prosić o więcej informacji o hotelu?", "hotel", "Gdzie sprawdzę informacje o hotelu?"),
       ("Czy mogę prosić o więcej informacji o zameldowaniu?", "zameldowanie", "Gdzie sprawdzę zasady zameldowania?"),
       ("Czy mogę prosić o więcej informacji o wymeldowaniu?", "wymeldowanie", "Gdzie sprawdzę zasady wymeldowania?"),
       ("Czy mogę prosić o więcej informacji o mieszkaniu do wynajęcia?", "mieszkanie do wynajęcia", "Gdzie sprawdzę oferty mieszkań?"),
       ("Czy mogę prosić o więcej informacji o czynszu?", "czynsz", "Gdzie sprawdzę informacje o czynszu?"),
       ("Czy mogę prosić o więcej informacji o umowie najmu?", "umowa najmu", "Gdzie sprawdzę wzór umowy najmu?"),
       ("Czy mogę prosić o więcej informacji o kliniki dyżurach?", "klinika", "Gdzie sprawdzę godziny kliniki?"),
       ("Czy mogę prosić o więcej informacji o leku?", "lek", "Gdzie sprawdzę informacje o leku?"),
       ("Czy mogę prosić o więcej informacji o antybiotyku?", "antybiotyk", "Gdzie sprawdzę informacje o antybiotyku?"),
       ("Czy mogę prosić o więcej informacji o badaniu?", "badanie", "Gdzie sprawdzę informacje o badaniu?"),
       ("Czy mogę prosić o więcej informacji o szkole?", "szkoła", "Gdzie sprawdzę informacje o szkole?"),
       ("Czy mogę prosić o więcej informacji o uniwersytecie?", "uniwersytet", "Gdzie sprawdzę informacje o uczelni?"),
       ("Czy mogę prosić o więcej informacji o firmie?", "firma", "Gdzie sprawdzę informacje o firmie?"),
       ("Czy mogę prosić o więcej informacji o projekcie?", "projekt", "Gdzie sprawdzę informacje o projekcie?"),
       ("Czy mogę prosić o więcej informacji o kliencie?", "klient", "Gdzie sprawdzę informacje o kliencie?"),
       ("Czy mogę prosić o więcej informacji o współpracy?", "współpraca", "Gdzie sprawdzę warunki współpracy?"),
       ("Czy mogę prosić o więcej informacji o wycieczce?", "wycieczka", "Gdzie sprawdzę informacje o wycieczce?"),
       ("Czy mogę prosić o więcej informacji o przewodniku?", "przewodnik (osoba)", "Gdzie znajdę przewodnika?"),
       ("Czy mogę prosić o więcej informacji o aplikacji?", "aplikacja", "Gdzie sprawdzę informacje o aplikacji?"),
       ("Czy mogę prosić o więcej informacji o zasięgu?", "zasięg", "Gdzie sprawdzę mapę zasięgu?"),
       ("Czy mogę prosić o więcej informacji o karcie SIM?", "karta SIM", "Gdzie sprawdzę oferty kart SIM?"),
       ("Czy mogę prosić o więcej informacji o ambasadzie?", "ambasada", "Gdzie sprawdzę godziny ambasady?"),
       ("Czy mogę prosić o więcej informacji o komisariacie?", "komisariat policji", "Gdzie znajdę najbliższy komisariat?"),
     ]),

# =====================================================================
# sing thii phom pen huang khue … — wskazanie obawy
# =====================================================================
dict(key="PENHUANG", ty="sentence", cat="Cechy i opinie", sub="Wątpliwości", reg="n",
     ph="sìng thîi phǒm pen hùang khue {ph} khráp", th="สิ่งที่ผมเป็นห่วงคือ{th}ครับ",
     lit="sìng thîi … khue = to, co …, to jest …",
     note="Konstrukcja wydzielająca: najpierw zapowiadasz, o czym mowa, potem to nazywasz. Brzmi rzeczowo, nie płaczliwie.",
     ex_ph="khun mâi pen hùang rûeang {ph} rǒe khráp", ex_th="คุณไม่เป็นห่วงเรื่อง{th}หรือครับ",
     items=[
       ("Martwi mnie sprawa kaucji.", "kaucja", "Nie martwi cię sprawa kaucji?"),
       ("Martwi mnie sprawa umowy.", "umowa", "Nie martwi cię sprawa umowy?"),
       ("Martwi mnie sprawa ceny.", "cena", "Nie martwi cię sprawa ceny?"),
       ("Martwi mnie sprawa opłat.", "opłata", "Nie martwi cię sprawa opłat?"),
       ("Martwi mnie sprawa czynszu.", "czynsz", "Nie martwi cię sprawa czynszu?"),
       ("Martwi mnie sprawa wizy.", "wiza", "Nie martwi cię sprawa wizy?"),
       ("Martwi mnie sprawa paszportu.", "paszport", "Nie martwi cię sprawa paszportu?"),
       ("Martwi mnie sprawa ubezpieczenia.", "ubezpieczenie", "Nie martwi cię sprawa ubezpieczenia?"),
       ("Martwi mnie sprawa zdrowia.", "gorączka", "Nie martwi cię ta gorączka?"),
       ("Martwi mnie sprawa alergii.", "alergia", "Nie martwi cię sprawa alergii?"),
       ("Martwi mnie sprawa wyniku badania.", "wynik badania", "Nie martwi cię wynik badania?"),
       ("Martwi mnie sprawa terminu zebrania.", "zebranie", "Nie martwi cię termin zebrania?"),
       ("Martwi mnie sprawa projektu.", "projekt", "Nie martwi cię sprawa projektu?"),
       ("Martwi mnie sprawa klienta.", "klient", "Nie martwi cię sprawa klienta?"),
       ("Martwi mnie sprawa dokumentów.", "dokument", "Nie martwi cię sprawa dokumentów?"),
       ("Martwi mnie sprawa nadgodzin.", "nadgodziny", "Nie martwią cię nadgodziny?"),
       ("Martwi mnie sprawa pensji.", "pensja", "Nie martwi cię sprawa pensji?"),
       ("Martwi mnie sprawa pracy.", "praca", "Nie martwi cię sprawa pracy?"),
       ("Martwi mnie sprawa firmy.", "firma", "Nie martwi cię sprawa firmy?"),
       ("Martwi mnie sprawa konta.", "konto", "Nie martwi cię sprawa konta?"),
       ("Martwi mnie sprawa przelewu.", "przelew", "Nie martwi cię sprawa przelewu?"),
       ("Martwi mnie sprawa gotówki na miejscu.", "gotówka", "Nie martwi cię brak gotówki?"),
       ("Martwi mnie sprawa korków.", "korek uliczny", "Nie martwią cię korki?"),
       ("Martwi mnie sprawa opóźnienia.", "opóźnienie", "Nie martwi cię opóźnienie?"),
       ("Martwi mnie sprawa bagażu.", "walizka", "Nie martwi cię sprawa bagażu?"),
       ("Martwi mnie sprawa kierowcy.", "kierowca", "Nie martwi cię sprawa kierowcy?"),
       ("Martwi mnie sprawa zasięgu.", "zasięg", "Nie martwi cię brak zasięgu?"),
       ("Martwi mnie sprawa internetu.", "internet", "Nie martwi cię sprawa internetu?"),
       ("Martwi mnie sprawa hasła.", "hasło", "Nie martwi cię sprawa hasła?"),
       ("Martwi mnie sprawa sąsiada z góry.", "sąsiad z góry", "Nie martwi cię sąsiad z góry?"),
       ("Martwi mnie sprawa właściciela mieszkania.", "właściciel", "Nie martwi cię właściciel?"),
       ("Martwi mnie sprawa szkoły dziecka.", "szkoła", "Nie martwi cię sprawa szkoły?"),
       ("Martwi mnie sprawa bezpieczeństwa na ulicy.", "ulica", "Nie martwi cię ta ulica wieczorem?"),
       ("Martwi mnie sprawa jedzenia dla dziecka.", "jedzenie", "Nie martwi cię sprawa jedzenia?"),
       ("Martwi mnie sprawa wody w kranie.", "woda", "Nie martwi cię jakość wody?"),
       ("Martwi mnie ten problem od zeszłego miesiąca.", "problem", "Nie martwi cię ten problem?"),
     ]),

# =====================================================================
# thaa mai mii … kaw tham a-rai mai dai — zaleznosc
# =====================================================================
dict(key="THAAMAIMII", ty="sentence", cat="Gramatyka użytkowa", sub="Zależności", reg="n",
     ph="thâa mâi mii {ph} kâw tham à-rai mâi dâai khráp", th="ถ้าไม่มี{th}ก็ทำอะไรไม่ได้ครับ",
     lit="thâa mâi mii … kâw … mâi dâai = bez tego nic się nie da",
     note="Para „thâa …, kâw …” niesie cały warunek. Ten wzorzec przydaje się przy tłumaczeniu, czego brakuje w urzędzie.",
     ex_ph="thâa mâi mii {ph} jing jing kâw tham à-rai mâi dâai rǒe khráp", ex_th="ถ้าไม่มี{th}จริงๆ ก็ทำอะไรไม่ได้หรือครับ",
     items=[
       ("Bez paszportu nic nie zrobimy.", "paszport", "Naprawdę bez paszportu nic się nie da?"),
       ("Bez wizy nic nie zrobimy.", "wiza", "Naprawdę bez wizy nic się nie da?"),
       ("Bez dokumentów nic nie zrobimy.", "dokument", "Naprawdę bez dokumentów nic się nie da?"),
       ("Bez umowy nic nie zrobimy.", "umowa", "Naprawdę bez umowy nic się nie da?"),
       ("Bez podpisu nic nie zrobimy.", "podpis", "Naprawdę bez podpisu nic się nie da?"),
       ("Bez paragonu nic nie zrobimy.", "paragon", "Naprawdę bez paragonu nic się nie da?"),
       ("Bez ubezpieczenia nic nie zrobimy.", "ubezpieczenie", "Naprawdę bez ubezpieczenia nic się nie da?"),
       ("Bez gotówki nic nie zrobimy.", "gotówka", "Naprawdę bez gotówki nic się nie da?"),
       ("Bez karty kredytowej nic nie zrobimy.", "karta kredytowa", "Naprawdę bez karty nic się nie da?"),
       ("Bez konta nic nie zrobimy.", "konto", "Naprawdę bez konta nic się nie da?"),
       ("Bez kaucji nic nie zrobimy.", "kaucja", "Naprawdę bez kaucji nic się nie da?"),
       ("Bez biletu nic nie zrobimy.", "bilet", "Naprawdę bez biletu nic się nie da?"),
       ("Bez prawa jazdy nic nie zrobimy.", "prawo jazdy", "Naprawdę bez prawa jazdy nic się nie da?"),
       ("Bez kasku nic nie zrobimy.", "kask", "Naprawdę bez kasku nic się nie da?"),
       ("Bez benzyny nic nie zrobimy.", "benzyna", "Naprawdę bez benzyny nic się nie da?"),
       ("Bez kierowcy nic nie zrobimy.", "kierowca", "Naprawdę bez kierowcy nic się nie da?"),
       ("Bez internetu nic nie zrobimy.", "internet", "Naprawdę bez internetu nic się nie da?"),
       ("Bez wi-fi nic nie zrobimy.", "wi-fi", "Naprawdę bez wi-fi nic się nie da?"),
       ("Bez hasła nic nie zrobimy.", "hasło", "Naprawdę bez hasła nic się nie da?"),
       ("Bez zasięgu nic nie zrobimy.", "zasięg", "Naprawdę bez zasięgu nic się nie da?"),
       ("Bez karty SIM nic nie zrobimy.", "karta SIM", "Naprawdę bez karty SIM nic się nie da?"),
       ("Bez ładowarki nic nie zrobimy.", "ładowarka", "Naprawdę bez ładowarki nic się nie da?"),
       ("Bez telefonu nic nie zrobimy.", "telefon", "Naprawdę bez telefonu nic się nie da?"),
       ("Bez aplikacji nic nie zrobimy.", "aplikacja", "Naprawdę bez aplikacji nic się nie da?"),
       ("Bez klucza nic nie zrobimy.", "klucz do mieszkania", "Naprawdę bez klucza nic się nie da?"),
       ("Bez zgody właściciela nic nie zrobimy.", "właściciel", "Naprawdę bez właściciela nic się nie da?"),
       ("Bez mapy nic nie zrobimy.", "mapa", "Naprawdę bez mapy nic się nie da?"),
       ("Bez przewodnika nic nie zrobimy.", "przewodnik (osoba)", "Naprawdę bez przewodnika nic się nie da?"),
       ("Bez wyniku badania nic nie zrobimy.", "wynik badania", "Naprawdę bez wyniku nic się nie da?"),
       ("Bez lekarza nic nie zrobimy.", "lekarz", "Naprawdę bez lekarza nic się nie da?"),
       ("Bez leku nic nie zrobimy.", "lek", "Naprawdę bez leku nic się nie da?"),
       ("Bez pieniędzy nic nie zrobimy.", "pieniądze", "Naprawdę bez pieniędzy nic się nie da?"),
       ("Bez rozkładu jazdy nic nie zrobimy.", "rozkład jazdy", "Naprawdę bez rozkładu nic się nie da?"),
       ("Bez wizytówki nic nie zrobimy.", "wizytówka", "Naprawdę bez wizytówki nic się nie da?"),
       ("Bez numeru telefonu nic nie zrobimy.", "numer telefonu", "Naprawdę bez numeru nic się nie da?"),
       ("Bez prądu nic nie zrobimy.", "światło", "Naprawdę bez prądu nic się nie da?"),
     ]),

# =====================================================================
# rueang … phaw ja taw rawng dai mai — negocjowanie punktu
# =====================================================================
dict(key="TAWRAWNG", ty="sentence", cat="Zakupy i pieniądze", sub="Negocjacje", reg="f",
     ph="rûeang {ph} phaw jà tàw rawng dâai mǎi khráp", th="เรื่อง{th}พอจะต่อรองได้ไหมครับ",
     lit="tàw rawng = negocjować, targować się o warunek",
     note="„phaw jà … dâai mǎi” to najuprzejmiejszy sposób pytania o ustępstwo. Na targu wystarczy krótkie „lót dâai mǎi”.",
     ex_ph="rûeang {ph} tàw rawng mâi dâai loei rǒe khráp", ex_th="เรื่อง{th}ต่อรองไม่ได้เลยหรือครับ",
     items=[
       ("Czy cena podlega negocjacji?", "cena", "Czy cena naprawdę nie podlega negocjacji?"),
       ("Czy czynsz podlega negocjacji?", "czynsz", "Czy czynsz naprawdę nie podlega negocjacji?"),
       ("Czy kaucja podlega negocjacji?", "kaucja", "Czy kaucja naprawdę nie podlega negocjacji?"),
       ("Czy opłata podlega negocjacji?", "opłata", "Czy opłata naprawdę nie podlega negocjacji?"),
       ("Czy zniżka podlega negocjacji?", "zniżka", "Czy zniżka naprawdę nie podlega negocjacji?"),
       ("Czy pensja podlega negocjacji?", "pensja", "Czy pensja naprawdę nie podlega negocjacji?"),
       ("Czy nadgodziny podlegają negocjacji?", "nadgodziny", "Czy nadgodziny naprawdę są nienegocjowalne?"),
       ("Czy urlop podlega negocjacji?", "urlop", "Czy urlop naprawdę nie podlega negocjacji?"),
       ("Czy umowa podlega negocjacji?", "umowa", "Czy umowa naprawdę nie podlega negocjacji?"),
       ("Czy umowa najmu podlega negocjacji?", "umowa najmu", "Czy najem naprawdę nie podlega negocjacji?"),
       ("Czy warunki współpracy podlegają negocjacji?", "współpraca", "Czy współpraca naprawdę jest nienegocjowalna?"),
       ("Czy termin zebrania podlega negocjacji?", "zebranie", "Czy termin zebrania jest nienegocjowalny?"),
       ("Czy zakres projektu podlega negocjacji?", "projekt", "Czy zakres projektu jest nienegocjowalny?"),
       ("Czy cena biletu podlega negocjacji?", "bilet", "Czy cena biletu jest nienegocjowalna?"),
       ("Czy cena pokoju podlega negocjacji?", "pokój", "Czy cena pokoju jest nienegocjowalna?"),
       ("Czy godzina wymeldowania podlega negocjacji?", "wymeldowanie", "Czy wymeldowanie jest nienegocjowalne?"),
       ("Czy godzina zameldowania podlega negocjacji?", "zameldowanie", "Czy zameldowanie jest nienegocjowalne?"),
       ("Czy śniadanie w hotelu podlega negocjacji?", "śniadanie w hotelu", "Czy śniadanie jest nienegocjowalne?"),
       ("Czy kurs wymiany podlega negocjacji?", "kurs wymiany", "Czy kurs naprawdę jest nienegocjowalny?"),
       ("Czy napiwek podlega negocjacji?", "napiwek", "Czy napiwek jest tu obowiązkowy?"),
       ("Czy rachunek podlega negocjacji?", "rachunek", "Czy rachunek naprawdę jest nienegocjowalny?"),
       ("Czy rozmiar porcji podlega negocjacji?", "porcja", "Czy porcja naprawdę jest nienegocjowalna?"),
       ("Czy stolik przy oknie podlega negocjacji?", "stolik", "Czy stolik jest już przypisany na stałe?"),
       ("Czy cena wycieczki podlega negocjacji?", "wycieczka", "Czy cena wycieczki jest nienegocjowalna?"),
       ("Czy stawka przewodnika podlega negocjacji?", "przewodnik (osoba)", "Czy stawka przewodnika jest stała?"),
       ("Czy koszt naprawy podlega negocjacji?", "problem", "Czy koszt tego problemu jest stały?"),
       ("Czy termin dostawy podlega negocjacji?", "opóźnienie", "Czy opóźnienie da się skrócić?"),
       ("Czy cena kursu wymiany w kantorze podlega negocjacji?", "kantor", "Czy w kantorze da się negocjować?"),
       ("Czy opłata za taksówkę podlega negocjacji?", "taksówka", "Czy cena kursu jest stała?"),
       ("Czy cena wynajmu motocykla podlega negocjacji?", "motocykl", "Czy cena wynajmu jest stała?"),
       ("Czy cena za paliwo podlega negocjacji?", "benzyna", "Czy cena paliwa jest wszędzie taka sama?"),
       ("Czy koszt ubezpieczenia podlega negocjacji?", "ubezpieczenie", "Czy składka jest nienegocjowalna?"),
       ("Czy cena leku podlega negocjacji?", "lek", "Czy cena leku jest stała?"),
       ("Czy cena badania podlega negocjacji?", "badanie", "Czy cena badania jest stała?"),
       ("Czy czesne podlega negocjacji?", "szkoła", "Czy czesne naprawdę jest nienegocjowalne?"),
       ("Czy warunki konta podlegają negocjacji?", "konto", "Czy warunki konta są nienegocjowalne?"),
     ]),

# =====================================================================
# khrai duu-lae … — ustalanie odpowiedzialnosci
# =====================================================================
dict(key="DUULAE", ty="sentence", cat="Praca i nauka", sub="Odpowiedzialność", reg="n",
     ph="khrai duu-lae {ph} khráp", th="ใครดูแล{th}ครับ",
     lit="duu-lae = doglądać, mieć pod opieką",
     note="„duu-lae” to szerokie pojęcie: opieka, nadzór, obsługa. Pytanie o osobę odpowiedzialną zaczyna się właśnie tak.",
     ex_ph="khon thîi duu-lae {ph} yùu thîi nǎi khráp", ex_th="คนที่ดูแล{th}อยู่ที่ไหนครับ",
     items=[
       ("Kto zajmuje się umową?", "umowa", "Gdzie znajdę osobę od umowy?"),
       ("Kto zajmuje się dokumentami?", "dokument", "Gdzie znajdę osobę od dokumentów?"),
       ("Kto zajmuje się klientem?", "klient", "Gdzie znajdę osobę od klienta?"),
       ("Kto zajmuje się projektem?", "projekt", "Gdzie znajdę osobę od projektu?"),
       ("Kto zajmuje się zebraniem?", "zebranie", "Gdzie znajdę osobę od zebrania?"),
       ("Kto zajmuje się pensjami?", "pensja", "Gdzie znajdę osobę od pensji?"),
       ("Kto zajmuje się urlopami?", "urlop", "Gdzie znajdę osobę od urlopów?"),
       ("Kto zajmuje się kontem?", "konto", "Gdzie znajdę osobę od konta?"),
       ("Kto zajmuje się przelewami?", "przelew", "Gdzie znajdę osobę od przelewów?"),
       ("Kto zajmuje się kaucją?", "kaucja", "Gdzie znajdę osobę od kaucji?"),
       ("Kto zajmuje się czynszem?", "czynsz", "Gdzie znajdę osobę od czynszu?"),
       ("Kto zajmuje się mieszkaniem?", "mieszkanie do wynajęcia", "Gdzie znajdę osobę od mieszkania?"),
       ("Kto zajmuje się internetem w budynku?", "internet", "Gdzie znajdę osobę od internetu?"),
       ("Kto zajmuje się routerem?", "router", "Gdzie znajdę osobę od routera?"),
       ("Kto zajmuje się pralką?", "pralka", "Gdzie znajdę osobę od pralki?"),
       ("Kto zajmuje się klimatyzacją?", "klimatyzacja", "Gdzie znajdę osobę od klimatyzacji?"),
       ("Kto zajmuje się windą?", "winda", "Gdzie znajdę osobę od windy?"),
       ("Kto zajmuje się śmieciami?", "śmieci", "Gdzie znajdę osobę od śmieci?"),
       ("Kto zajmuje się ochroną?", "ochroniarz", "Gdzie znajdę ochroniarza?"),
       ("Kto zajmuje się recepcją?", "recepcja", "Gdzie znajdę osobę z recepcji?"),
       ("Kto zajmuje się basenem?", "basen", "Gdzie znajdę osobę od basenu?"),
       ("Kto zajmuje się sejfem?", "sejf", "Gdzie znajdę osobę od sejfu?"),
       ("Kto zajmuje się bagażem?", "walizka", "Gdzie znajdę osobę od bagażu?"),
       ("Kto zajmuje się biletami?", "bilet", "Gdzie znajdę osobę od biletów?"),
       ("Kto zajmuje się rozkładem jazdy?", "rozkład jazdy", "Gdzie znajdę osobę od rozkładu?"),
       ("Kto zajmuje się peronem?", "peron", "Gdzie znajdę osobę na peronie?"),
       ("Kto zajmuje się pasażerami?", "pasażer", "Gdzie znajdę osobę od pasażerów?"),
       ("Kto zajmuje się ubezpieczeniem?", "ubezpieczenie", "Gdzie znajdę osobę od ubezpieczenia?"),
       ("Kto zajmuje się wynikami badań?", "wynik badania", "Gdzie znajdę osobę od wyników?"),
       ("Kto zajmuje się apteką na miejscu?", "apteka", "Gdzie znajdę osobę z apteki?"),
       ("Kto zajmuje się rejestracją w klinice?", "klinika", "Gdzie znajdę rejestrację kliniki?"),
       ("Kto zajmuje się uczniami?", "student", "Gdzie znajdę opiekuna uczniów?"),
       ("Kto zajmuje się wizami?", "wiza", "Gdzie znajdę osobę od wiz?"),
       ("Kto zajmuje się tą sprawą?", "problem", "Gdzie znajdę osobę od tej sprawy?"),
       ("Kto zajmuje się współpracą z partnerami?", "współpraca", "Gdzie znajdę osobę od współpracy?"),
       ("Kto zajmuje się aplikacją?", "aplikacja", "Gdzie znajdę osobę od aplikacji?"),
     ]),

# =====================================================================
# chuai yuen-yan rueang … iik khrang — potwierdzenie ustalen
# =====================================================================
dict(key="YUENYAN", ty="sentence", cat="Praca i nauka", sub="Potwierdzanie", reg="f",
     ph="chûai yuen-yan rûeang {ph} ìik khráng khráp", th="ช่วยยืนยันเรื่อง{th}อีกครั้งครับ",
     lit="yuen-yan = potwierdzić oficjalnie",
     note="„yuen-yan” to potwierdzenie wiążące, nie zwykłe „tak”. Przy rezerwacjach i zamówieniach żądaj właśnie tego słowa.",
     ex_ph="rûeang {ph} yuen-yan láew rǔe yang khráp", ex_th="เรื่อง{th}ยืนยันแล้วหรือยังครับ",
     items=[
       ("Proszę potwierdzić sprawę rezerwacji pokoju.", "pokój", "Czy pokój jest już potwierdzony?"),
       ("Proszę potwierdzić sprawę biletu.", "bilet", "Czy bilet jest już potwierdzony?"),
       ("Proszę potwierdzić sprawę zebrania.", "zebranie", "Czy zebranie jest już potwierdzone?"),
       ("Proszę potwierdzić sprawę umowy.", "umowa", "Czy umowa jest już potwierdzona?"),
       ("Proszę potwierdzić sprawę ceny.", "cena", "Czy cena jest już potwierdzona?"),
       ("Proszę potwierdzić sprawę opłaty.", "opłata", "Czy opłata jest już potwierdzona?"),
       ("Proszę potwierdzić sprawę przelewu.", "przelew", "Czy przelew jest już potwierdzony?"),
       ("Proszę potwierdzić sprawę kaucji.", "kaucja", "Czy kaucja jest już potwierdzona?"),
       ("Proszę potwierdzić sprawę czynszu.", "czynsz", "Czy czynsz jest już potwierdzony?"),
       ("Proszę potwierdzić sprawę umowy najmu.", "umowa najmu", "Czy najem jest już potwierdzony?"),
       ("Proszę potwierdzić sprawę dokumentów.", "dokument", "Czy dokumenty są już potwierdzone?"),
       ("Proszę potwierdzić sprawę podpisu.", "podpis", "Czy podpis jest już potwierdzony?"),
       ("Proszę potwierdzić sprawę urlopu.", "urlop", "Czy urlop jest już potwierdzony?"),
       ("Proszę potwierdzić sprawę nadgodzin.", "nadgodziny", "Czy nadgodziny są już potwierdzone?"),
       ("Proszę potwierdzić sprawę pensji.", "pensja", "Czy pensja jest już potwierdzona?"),
       ("Proszę potwierdzić sprawę projektu.", "projekt", "Czy projekt jest już potwierdzony?"),
       ("Proszę potwierdzić sprawę klienta.", "klient", "Czy sprawa klienta jest potwierdzona?"),
       ("Proszę potwierdzić sprawę współpracy.", "współpraca", "Czy współpraca jest już potwierdzona?"),
       ("Proszę potwierdzić sprawę wizy.", "wiza", "Czy wiza jest już potwierdzona?"),
       ("Proszę potwierdzić sprawę ubezpieczenia.", "ubezpieczenie", "Czy ubezpieczenie jest potwierdzone?"),
       ("Proszę potwierdzić sprawę badania.", "badanie", "Czy badanie jest już potwierdzone?"),
       ("Proszę potwierdzić sprawę leku.", "lek", "Czy lek jest już potwierdzony?"),
       ("Proszę potwierdzić sprawę wizyty u lekarza.", "lekarz", "Czy wizyta jest już potwierdzona?"),
       ("Proszę potwierdzić sprawę wycieczki.", "wycieczka", "Czy wycieczka jest już potwierdzona?"),
       ("Proszę potwierdzić sprawę przewodnika.", "przewodnik (osoba)", "Czy przewodnik jest potwierdzony?"),
       ("Proszę potwierdzić sprawę zameldowania.", "zameldowanie", "Czy zameldowanie jest potwierdzone?"),
       ("Proszę potwierdzić sprawę wymeldowania.", "wymeldowanie", "Czy wymeldowanie jest potwierdzone?"),
       ("Proszę potwierdzić sprawę śniadania w hotelu.", "śniadanie w hotelu", "Czy śniadanie jest wliczone?"),
       ("Proszę potwierdzić sprawę stolika.", "stolik", "Czy stolik jest już potwierdzony?"),
       ("Proszę potwierdzić sprawę rachunku.", "rachunek", "Czy rachunek jest już potwierdzony?"),
       ("Proszę potwierdzić sprawę zniżki.", "zniżka", "Czy zniżka jest już potwierdzona?"),
       ("Proszę potwierdzić sprawę konta.", "konto", "Czy konto jest już potwierdzone?"),
       ("Proszę potwierdzić sprawę numeru telefonu.", "numer telefonu", "Czy numer jest już potwierdzony?"),
       ("Proszę potwierdzić sprawę adresu w szkole.", "szkoła", "Czy dane w szkole są potwierdzone?"),
       ("Proszę potwierdzić sprawę opóźnienia.", "opóźnienie", "Czy opóźnienie jest już potwierdzone?"),
       ("Proszę potwierdzić sprawę zgłoszonego problemu.", "problem", "Czy zgłoszenie jest już potwierdzone?"),
     ]),
]
