# -*- coding: utf-8 -*-
"""Recznie opracowane zwroty uzytkowe.
Krotka: (polski, fonetyka, tajski, kategoria, podkategoria, survival, frekwencja, notatka)
"""

PHRASES = [
# --- KOMUNIKACJA PODSTAWOWA
("Nie mówię po tajsku.", "phǒm phûut thai mâi dâai", "ผมพูดไทยไม่ได้", "Podstawy i grzeczność", "Komunikacja", 1, 5, "Kobieta mówi: chǎn phûut thai mâi dâai."),
("Mówię trochę po tajsku.", "phǒm phûut thai dâai nít nòi", "ผมพูดไทยได้นิดหน่อย", "Podstawy i grzeczność", "Komunikacja", 1, 5, ""),
("Czy mówisz po angielsku?", "khun phûut phaasǎa angkrìt dâai mǎi", "คุณพูดภาษาอังกฤษได้ไหม", "Podstawy i grzeczność", "Komunikacja", 1, 5, ""),
("Powtórz, proszę.", "phûut ìik khráng dâai mǎi", "พูดอีกครั้งได้ไหม", "Podstawy i grzeczność", "Komunikacja", 1, 5, ""),
("Mów wolniej, proszę.", "phûut cháa cháa nòi", "พูดช้าๆ หน่อย", "Podstawy i grzeczność", "Komunikacja", 1, 5, ""),
("Jak to się mówi po tajsku?", "phaasǎa thai rîak wâa à-rai", "ภาษาไทยเรียกว่าอะไร", "Podstawy i grzeczność", "Komunikacja", 1, 4, ""),
("Co to znaczy?", "plae wâa à-rai", "แปลว่าอะไร", "Podstawy i grzeczność", "Komunikacja", 1, 4, ""),
("Rozumiesz?", "khâo-jai mǎi", "เข้าใจไหม", "Podstawy i grzeczność", "Komunikacja", 1, 4, ""),
("Jak masz na imię?", "khun chûe à-rai", "คุณชื่ออะไร", "Small talk", "Poznawanie ludzi", 1, 5, ""),
("Mam na imię...", "phǒm chûe", "ผมชื่อ", "Small talk", "Poznawanie ludzi", 1, 5, "Po tym zwrocie podaj swoje imię."),
("Skąd jesteś?", "khun maa jàak thîi nǎi", "คุณมาจากที่ไหน", "Small talk", "Poznawanie ludzi", 1, 4, ""),
("Jestem z Polski.", "phǒm maa jàak poo-laen", "ผมมาจากโปแลนด์", "Small talk", "Poznawanie ludzi", 1, 4, ""),
("Ile masz lat?", "khun aayú thâo-rài", "คุณอายุเท่าไหร่", "Small talk", "Poznawanie ludzi", 0, 3, "Pytanie o wiek jest w Tajlandii normalne."),
("Jestem tu na wakacjach.", "phǒm maa thîaw", "ผมมาเที่ยว", "Small talk", "Poznawanie ludzi", 1, 4, ""),
("Jestem tu pierwszy raz.", "maa khráng râek", "มาครั้งแรก", "Small talk", "Poznawanie ludzi", 1, 3, ""),
("Bardzo mi się tu podoba.", "chôp thîi nîi mâak", "ชอบที่นี่มาก", "Small talk", "Poznawanie ludzi", 1, 4, ""),

# --- RESTAURACJA
("Poproszę menu.", "khǎw mee-nuu nòi khráp", "ขอเมนูหน่อยครับ", "Restauracja", "Zamówienie", 1, 5, ""),
("Chciałbym zamówić.", "phǒm yàak sàng aa-hǎan", "ผมอยากสั่งอาหาร", "Restauracja", "Zamówienie", 1, 5, ""),
("Co polecasz?", "náe-nam à-rai dii", "แนะนำอะไรดี", "Restauracja", "Zamówienie", 1, 4, ""),
("Nieostre, proszę.", "mâi phèt", "ไม่เผ็ด", "Restauracja", "Zamówienie", 1, 5, "Dodaj 'khráp' albo 'khâ' na koncu."),
("Trochę ostre.", "phèt nít nòi", "เผ็ดนิดหน่อย", "Restauracja", "Zamówienie", 1, 4, ""),
("Bez cukru.", "mâi sài náam-taan", "ไม่ใส่น้ำตาล", "Restauracja", "Zamówienie", 1, 4, ""),
("Bez lodu.", "mâi sài náam khǎeng", "ไม่ใส่น้ำแข็ง", "Restauracja", "Zamówienie", 1, 4, ""),
("Nie jem mięsa.", "phǒm mâi kin núea sàt", "ผมไม่กินเนื้อสัตว์", "Restauracja", "Dieta", 1, 4, ""),
("Mam alergię na orzeszki.", "phǒm pháe thùa", "ผมแพ้ถั่ว", "Restauracja", "Dieta", 1, 4, "Zamien 'thùa' na inny alergen."),
("Rachunek, proszę.", "khít ngoen dûai khráp", "คิดเงินด้วยครับ", "Restauracja", "Płatność", 1, 5, ""),
("Czy mogę zapłacić kartą?", "jàai bàt dâai mǎi", "จ่ายบัตรได้ไหม", "Restauracja", "Płatność", 1, 5, ""),
("Bardzo smaczne!", "à-ròi mâak", "อร่อยมาก", "Restauracja", "Opinie", 1, 5, ""),
("Poproszę na wynos.", "sài thǔng dâai mǎi", "ใส่ถุงได้ไหม", "Restauracja", "Zamówienie", 1, 4, ""),
("Jeszcze jedną, proszę.", "khǎw ìik nùeng thîi", "ขออีกหนึ่งที่", "Restauracja", "Zamówienie", 1, 4, ""),
("Ile to potrwa?", "chái weelaa naan mǎi", "ใช้เวลานานไหม", "Restauracja", "Obsługa", 1, 3, ""),
("To nie jest to, co zamawiałem.", "nîi mâi châi thîi sàng", "นี่ไม่ใช่ที่สั่ง", "Restauracja", "Problemy", 1, 3, ""),
("Poproszę wodę bez gazu.", "khǎw náam plào nòi", "ขอน้ำเปล่าหน่อย", "Restauracja", "Zamówienie", 1, 5, ""),

# --- TAXI I TRANSPORT
("Poproszę na lotnisko.", "pai sanǎam bin khráp", "ไปสนามบินครับ", "Transport", "Taxi", 1, 5, ""),
("Proszę włączyć taksometr.", "kòt mí-təə dûai khráp", "กดมิเตอร์ด้วยครับ", "Transport", "Taxi", 1, 5, "Kluczowy zwrot w Bangkoku."),
("Ile do centrum?", "pai nai mueang thâo-rài", "ไปในเมืองเท่าไหร่", "Transport", "Taxi", 1, 4, ""),
("Za drogo, może taniej?", "phaeng pai lót nòi dâai mǎi", "แพงไปลดหน่อยได้ไหม", "Transport", "Taxi", 1, 4, ""),
("Proszę tutaj się zatrzymać.", "jàwt trong níi khráp", "จอดตรงนี้ครับ", "Transport", "Taxi", 1, 5, ""),
("Proszę skręcić w lewo.", "líaw sáai khráp", "เลี้ยวซ้ายครับ", "Transport", "Taxi", 1, 5, ""),
("Proszę skręcić w prawo.", "líaw khwǎa khráp", "เลี้ยวขวาครับ", "Transport", "Taxi", 1, 5, ""),
("Proszę jechać prosto.", "trong pai khráp", "ตรงไปครับ", "Transport", "Taxi", 1, 5, ""),
("Spieszę się.", "phǒm rîip", "ผมรีบ", "Transport", "Taxi", 1, 3, ""),
("Proszę jechać wolniej.", "khàp cháa cháa nòi", "ขับช้าๆ หน่อย", "Transport", "Taxi", 1, 4, ""),
("O której odjeżdża autobus?", "rót àwk kìi moong", "รถออกกี่โมง", "Transport", "Rozkład", 1, 4, ""),
("Gdzie mogę kupić bilet?", "súe tǔa dâai thîi nǎi", "ซื้อตั๋วได้ที่ไหน", "Transport", "Rozkład", 1, 4, ""),
("Poproszę dwa bilety.", "khǎw tǔa sǎwng bai", "ขอตั๋วสองใบ", "Transport", "Rozkład", 1, 4, ""),
("Jak długo tam jedziemy?", "chái weelaa kìi chûa moong", "ใช้เวลากี่ชั่วโมง", "Transport", "Rozkład", 1, 4, ""),
("Czy ten autobus jedzie na targ?", "rót khan níi pai talàat mǎi", "รถคันนี้ไปตลาดไหม", "Transport", "Rozkład", 1, 4, ""),
("Chcę wynająć skuter.", "yàak châo maw-tôe-sai", "อยากเช่ามอเตอร์ไซค์", "Transport", "Wynajem", 1, 4, ""),
("Ile za dzień?", "wan lá thâo-rài", "วันละเท่าไหร่", "Transport", "Wynajem", 1, 4, ""),

# --- HOTEL
("Mam rezerwację.", "phǒm jawng wái láew", "ผมจองไว้แล้ว", "Hotel", "Recepcja", 1, 4, ""),
("Czy są wolne pokoje?", "mii hâwng wâang mǎi", "มีห้องว่างไหม", "Hotel", "Recepcja", 1, 5, ""),
("Ile za noc?", "khuen lá thâo-rài", "คืนละเท่าไหร่", "Hotel", "Recepcja", 1, 5, ""),
("Chcę zostać dwie noce.", "yàak phák sǎwng khuen", "อยากพักสองคืน", "Hotel", "Recepcja", 1, 4, ""),
("Czy jest śniadanie w cenie?", "ruam aa-hǎan cháo mǎi", "รวมอาหารเช้าไหม", "Hotel", "Recepcja", 1, 4, ""),
("Jakie jest hasło do wi-fi?", "rahàt wai-fai à-rai", "รหัสไวไฟอะไร", "Hotel", "Wyposażenie", 1, 5, ""),
("Klimatyzacja nie działa.", "ae sǐa", "แอร์เสีย", "Hotel", "Problemy", 1, 4, ""),
("Nie ma gorącej wody.", "mâi mii náam ráwn", "ไม่มีน้ำร้อน", "Hotel", "Problemy", 1, 4, ""),
("Poproszę o ręcznik.", "khǎw phâa chét tua nòi", "ขอผ้าเช็ดตัวหน่อย", "Hotel", "Wyposażenie", 1, 4, ""),
("Wymeldowuję się.", "phǒm khǎw chék-áo", "ผมขอเช็คเอาท์", "Hotel", "Recepcja", 1, 4, ""),
("Czy mogę zostawić bagaż?", "fàak krapǎo dâai mǎi", "ฝากกระเป๋าได้ไหม", "Hotel", "Recepcja", 1, 4, ""),
("O której jest wymeldowanie?", "chék-áo kìi moong", "เช็คเอาท์กี่โมง", "Hotel", "Recepcja", 1, 4, ""),

# --- ZAKUPY
("Ile to kosztuje?", "níi thâo-rài", "นี่เท่าไหร่", "Zakupy i pieniądze", "Targowanie", 1, 5, ""),
("Za drogo.", "phaeng pai", "แพงไป", "Zakupy i pieniądze", "Targowanie", 1, 5, ""),
("Może być taniej?", "lót dâai mǎi", "ลดได้ไหม", "Zakupy i pieniądze", "Targowanie", 1, 5, ""),
("Sto bahtów, dobrze?", "ráwi nùeng dâai mǎi", "ร้อยนึงได้ไหม", "Zakupy i pieniądze", "Targowanie", 1, 4, ""),
("Wezmę to.", "ao an níi", "เอาอันนี้", "Zakupy i pieniądze", "Zakup", 1, 5, ""),
("Nie, dziękuję.", "mâi ao khràp", "ไม่เอาครับ", "Zakupy i pieniądze", "Zakup", 1, 5, ""),
("Tylko oglądam.", "duu chə̌əi chə̌əi", "ดูเฉยๆ", "Zakupy i pieniądze", "Zakup", 1, 4, ""),
("Czy jest większy rozmiar?", "mii yài kwàa níi mǎi", "มีใหญ่กว่านี้ไหม", "Zakupy i pieniądze", "Ubrania", 0, 3, ""),
("Czy mogę przymierzyć?", "lawng sài dâai mǎi", "ลองใส่ได้ไหม", "Zakupy i pieniądze", "Ubrania", 0, 3, ""),
("Poproszę o resztę.", "khǎw ngoen thawn dûai", "ขอเงินทอนด้วย", "Zakupy i pieniądze", "Płatność", 1, 4, ""),
("Nie mam drobnych.", "mâi mii ngoen yôi", "ไม่มีเงินย่อย", "Zakupy i pieniądze", "Płatność", 1, 4, ""),
("Czy przyjmujecie karty?", "ráp bàt mǎi", "รับบัตรไหม", "Zakupy i pieniądze", "Płatność", 1, 4, ""),

# --- ORIENTACJA
("Gdzie jest toaleta?", "hâwng náam yùu thîi nǎi", "ห้องน้ำอยู่ที่ไหน", "Miejsca i orientacja", "Pytanie o drogę", 1, 5, ""),
("Jak tam dojść?", "pai yang-ngai", "ไปยังไง", "Miejsca i orientacja", "Pytanie o drogę", 1, 5, ""),
("Czy to daleko?", "klai mǎi", "ไกลไหม", "Miejsca i orientacja", "Pytanie o drogę", 1, 5, ""),
("Zgubiłem się.", "phǒm lǒng thaang", "ผมหลงทาง", "Miejsca i orientacja", "Pytanie o drogę", 1, 4, ""),
("Czy możesz pokazać na mapie?", "chûai chíi nai phǎen thîi dâai mǎi", "ช่วยชี้ในแผนที่ได้ไหม", "Miejsca i orientacja", "Pytanie o drogę", 1, 3, ""),
("Idź prosto, potem w lewo.", "trong pai láew líaw sáai", "ตรงไปแล้วเลี้ยวซ้าย", "Miejsca i orientacja", "Wskazówki", 1, 4, ""),
("To jest niedaleko stąd.", "yùu mâi klai jàak thîi nîi", "อยู่ไม่ไกลจากที่นี่", "Miejsca i orientacja", "Wskazówki", 0, 3, ""),
("Czy w pobliżu jest bankomat?", "thǎew níi mii tûu ee-thii-em mǎi", "แถวนี้มีตู้เอทีเอ็มไหม", "Miejsca i orientacja", "Pytanie o drogę", 1, 4, ""),

# --- ZDROWIE I AWARIE
("Źle się czuję.", "phǒm mâi sabaai", "ผมไม่สบาย", "Zdrowie", "Objawy", 1, 5, ""),
("Boli mnie tutaj.", "jèp trong níi", "เจ็บตรงนี้", "Zdrowie", "Objawy", 1, 5, ""),
("Potrzebuję lekarza.", "phǒm tâwng-kaan mǎw", "ผมต้องการหมอ", "Zdrowie", "Nagłe wypadki", 1, 5, ""),
("Proszę wezwać karetkę.", "chûai rîak rót phayaabaan", "ช่วยเรียกรถพยาบาล", "Zdrowie", "Nagłe wypadki", 1, 4, ""),
("Mam gorączkę.", "phǒm mii khâi", "ผมมีไข้", "Zdrowie", "Objawy", 1, 4, ""),
("Mam biegunkę.", "phǒm tháwng sǐa", "ผมท้องเสีย", "Zdrowie", "Objawy", 1, 4, ""),
("Gdzie jest najbliższa apteka?", "ráan khǎai yaa yùu thîi nǎi", "ร้านขายยาอยู่ที่ไหน", "Zdrowie", "Apteka", 1, 4, ""),
("Zgubiłem paszport.", "phǒm tham nǎng-sǔe dəən thaang hǎai", "ผมทำหนังสือเดินทางหาย", "Awarie i pomoc", "Nagłe wypadki", 1, 4, ""),
("Skradziono mi torbę.", "krapǎo phǒm thùuk khamooi", "กระเป๋าผมถูกขโมย", "Awarie i pomoc", "Nagłe wypadki", 1, 3, ""),
("Proszę wezwać policję.", "chûai rîak tamrùat", "ช่วยเรียกตำรวจ", "Awarie i pomoc", "Nagłe wypadki", 1, 4, ""),
("Nie czuję się bezpiecznie.", "phǒm rúu-sùek mâi plàwt phai", "ผมรู้สึกไม่ปลอดภัย", "Awarie i pomoc", "Nagłe wypadki", 1, 3, ""),
("Zgubiłem telefon.", "phǒm tham thoo-rasàp hǎai", "ผมทำโทรศัพท์หาย", "Awarie i pomoc", "Nagłe wypadki", 1, 3, ""),
("Potrzebuję pomocy.", "phǒm tâwng-kaan khwaam chûai lǔea", "ผมต้องการความช่วยเหลือ", "Awarie i pomoc", "Nagłe wypadki", 1, 4, ""),

# --- CODZIENNE REAKCJE
("Świetnie!", "yîam loei", "เยี่ยมเลย", "Cechy i opinie", "Reakcje", 1, 4, ""),
("Nie szkodzi.", "mâi pen rai", "ไม่เป็นไร", "Cechy i opinie", "Reakcje", 1, 5, ""),
("Naprawdę?", "jing rǔe", "จริงเหรอ", "Cechy i opinie", "Reakcje", 1, 4, ""),
("Nie wiem.", "mâi rúu", "ไม่รู้", "Cechy i opinie", "Reakcje", 1, 5, ""),
("Może.", "aat jà", "อาจจะ", "Cechy i opinie", "Reakcje", 0, 3, ""),
("Zgadzam się.", "hěn dûai", "เห็นด้วย", "Cechy i opinie", "Reakcje", 0, 3, ""),
("Poczekaj chwilę.", "raw dǐaw", "รอเดี๋ยว", "Cechy i opinie", "Reakcje", 1, 4, ""),
("Chodźmy.", "pai kan thòe", "ไปกันเถอะ", "Cechy i opinie", "Reakcje", 1, 4, ""),
("Nie ma problemu.", "mâi mii panhǎa", "ไม่มีปัญหา", "Cechy i opinie", "Reakcje", 1, 4, ""),
("Jestem zmęczony.", "phǒm nùeai", "ผมเหนื่อย", "Cechy i opinie", "Samopoczucie", 1, 4, ""),
("Jestem głodny.", "phǒm hǐw", "ผมหิว", "Cechy i opinie", "Samopoczucie", 1, 5, ""),
("Chce mi się pić.", "phǒm hǐw náam", "ผมหิวน้ำ", "Cechy i opinie", "Samopoczucie", 1, 4, ""),
("Jest za gorąco.", "ráwn koen pai", "ร้อนเกินไป", "Cechy i opinie", "Pogoda", 1, 4, ""),
("Pada deszcz.", "fǒn tòk", "ฝนตก", "Pogoda i przyroda", "Pogoda", 1, 4, ""),
("Jaka jutro będzie pogoda?", "phrûng níi aakàat pen yang-ngai", "พรุ่งนี้อากาศเป็นยังไง", "Pogoda i przyroda", "Pogoda", 0, 3, ""),

# --- LICZBY W UZYCIU
("Poproszę jedną sztukę.", "khǎw nùeng an", "ขอหนึ่งอัน", "Liczby i liczenie", "Użycie", 1, 4, ""),
("Dwie osoby.", "sǎwng khon", "สองคน", "Liczby i liczenie", "Użycie", 1, 5, "Odpowiedź na pytanie o liczbę gości."),
("Trzy porcje.", "sǎam thîi", "สามที่", "Liczby i liczenie", "Użycie", 1, 4, ""),
("Pół godziny.", "khrûeng chûa moong", "ครึ่งชั่วโมง", "Czas i daty", "Użycie", 1, 4, ""),
("O której godzinie?", "kìi moong", "กี่โมง", "Czas i daty", "Użycie", 1, 5, ""),
("Za dziesięć minut.", "ìik sìp naa-thii", "อีกสิบนาที", "Czas i daty", "Użycie", 1, 4, ""),
("Wczoraj wieczorem.", "mûea khuen níi", "เมื่อคืนนี้", "Czas i daty", "Użycie", 0, 3, ""),
("W przyszłym tygodniu.", "aa-thít nâa", "อาทิตย์หน้า", "Czas i daty", "Użycie", 0, 3, ""),
("Codziennie.", "thúk wan", "ทุกวัน", "Czas i daty", "Użycie", 1, 4, ""),
("Nigdy.", "mâi khoei", "ไม่เคย", "Czas i daty", "Użycie", 0, 3, ""),
("Już to robiłem.", "khoei tham láew", "เคยทำแล้ว", "Czas i daty", "Użycie", 0, 3, ""),
("Jeszcze nie.", "yang mâi dâai", "ยังไม่ได้", "Czas i daty", "Użycie", 1, 4, ""),
]
