# -*- coding: utf-8 -*-
"""Rdzenna baza leksykalna Thai All-in-One, czesc 2."""

CORE2 = [
# ------------------------------------------------------ ZAKUPY I PIENIADZE
("pieniądze", "ngoen", "เงิน", "Zakupy i pieniądze", "Płatności", "noun", "thing", "bàat|บาท|baht", 1, 5),
("baht", "bàat", "บาท", "Zakupy i pieniądze", "Płatności", "noun", "thing", "bàat|บาท|baht", 1, 5),
("cena", "raakhaa", "ราคา", "Zakupy i pieniądze", "Płatności", "noun", "thing", "raakhaa|ราคา|cena", 1, 5),
("zniżka", "sùan lót", "ส่วนลด", "Zakupy i pieniądze", "Płatności", "noun", "thing", "an|อัน|sztuka", 1, 4),
("reszta", "ngoen thawn", "เงินทอน", "Zakupy i pieniądze", "Płatności", "noun", "thing", "bàat|บาท|baht", 1, 4),
("karta kredytowa", "bàt khree-dìt", "บัตรเครดิต", "Zakupy i pieniądze", "Płatności", "noun", "thing", "bai|ใบ|sztuka", 1, 4),
("gotówka", "ngoen sòt", "เงินสด", "Zakupy i pieniądze", "Płatności", "noun", "thing", "bàat|บาท|baht", 1, 4),
("paragon", "bai sèt", "ใบเสร็จ", "Zakupy i pieniądze", "Płatności", "noun", "thing", "bai|ใบ|sztuka", 1, 3),
("rozmiar", "khanàat", "ขนาด", "Zakupy i pieniądze", "Ubrania", "noun", "thing", "khanàat|ขนาด|rozmiar", 0, 3),
("kolor", "sǐi", "สี", "Zakupy i pieniądze", "Ubrania", "noun", "thing", "sǐi|สี|kolor", 0, 4),
("koszulka", "sûea yúet", "เสื้อยืด", "Zakupy i pieniądze", "Ubrania", "noun", "thing,buy", "tua|ตัว|sztuka", 0, 3),
("spodnie", "kaang keeng", "กางเกง", "Zakupy i pieniądze", "Ubrania", "noun", "thing,buy", "tua|ตัว|sztuka", 0, 3),
("buty", "rawng tháo", "รองเท้า", "Zakupy i pieniądze", "Ubrania", "noun", "thing,buy", "khûu|คู่|para", 0, 3),
("kapelusz", "mùak", "หมวก", "Zakupy i pieniądze", "Ubrania", "noun", "thing,buy", "bai|ใบ|sztuka", 0, 3),
("okulary przeciwsłoneczne", "wâen kan dàet", "แว่นกันแดด", "Zakupy i pieniądze", "Ubrania", "noun", "thing,buy", "an|อัน|sztuka", 0, 3),
("krem z filtrem", "khriim kan dàet", "ครีมกันแดด", "Zakupy i pieniądze", "Kosmetyki", "noun", "thing,buy", "khùat|ขวด|butelka", 1, 3),
("mydło", "sabùu", "สบู่", "Dom i codzienność", "Kosmetyki", "noun", "thing,buy", "kâwn|ก้อน|kostka", 0, 3),
("papier toaletowy", "kradàat cham-rá", "กระดาษชำระ", "Dom i codzienność", "Kosmetyki", "noun", "thing,buy", "múan|ม้วน|rolka", 1, 3),
("telefon", "thoo-rasàp", "โทรศัพท์", "Dom i codzienność", "Elektronika", "noun", "thing,buy", "khrûeang|เครื่อง|sztuka", 1, 5),
("ładowarka", "thîi chàat", "ที่ชาร์จ", "Dom i codzienność", "Elektronika", "noun", "thing,buy", "an|อัน|sztuka", 1, 4),
("karta SIM", "sim kâat", "ซิมการ์ด", "Dom i codzienność", "Elektronika", "noun", "thing,buy", "an|อัน|sztuka", 1, 4),
("internet", "in-təə-nét", "อินเทอร์เน็ต", "Dom i codzienność", "Elektronika", "noun", "thing", "an|อัน|sztuka", 1, 4),
("wi-fi", "wai-fai", "ไวไฟ", "Dom i codzienność", "Elektronika", "noun", "thing", "an|อัน|sztuka", 1, 5),
("hasło", "rahàt", "รหัส", "Dom i codzienność", "Elektronika", "noun", "thing", "an|อัน|sztuka", 1, 4),
("torba", "thǔng", "ถุง", "Zakupy i pieniądze", "Ogólne", "noun", "thing,buy", "bai|ใบ|sztuka", 1, 4),
("pamiątka", "khǎwng thîi ralúek", "ของที่ระลึก", "Zakupy i pieniądze", "Ogólne", "noun", "thing,buy", "chín|ชิ้น|sztuka", 0, 3),

# ------------------------------------------------------------------ ZDROWIE
("lek", "yaa", "ยา", "Zdrowie", "Apteka", "noun", "thing,buy", "mét|เม็ด|tabletka", 1, 5),
("lek przeciwbólowy", "yaa kâe pùat", "ยาแก้ปวด", "Zdrowie", "Apteka", "noun", "thing,buy", "mét|เม็ด|tabletka", 1, 4),
("lek na gorączkę", "yaa lót khâi", "ยาลดไข้", "Zdrowie", "Apteka", "noun", "thing,buy", "mét|เม็ด|tabletka", 1, 3),
("plaster", "phlaastəə", "พลาสเตอร์", "Zdrowie", "Apteka", "noun", "thing,buy", "phàen|แผ่น|sztuka", 0, 3),
("lekarz", "mǎw", "หมอ", "Zdrowie", "Ludzie", "noun", "person", "khon|คน|osoba", 1, 5),
("pielęgniarka", "phayaabaan", "พยาบาล", "Zdrowie", "Ludzie", "noun", "person", "khon|คน|osoba", 0, 3),
("gorączka", "khâi", "ไข้", "Zdrowie", "Objawy", "noun", "thing", "an|อัน|objaw", 1, 4),
("ból głowy", "pùat hǔa", "ปวดหัว", "Zdrowie", "Objawy", "noun", "thing", "an|อัน|objaw", 1, 5),
("ból brzucha", "pùat tháwng", "ปวดท้อง", "Zdrowie", "Objawy", "noun", "thing", "an|อัน|objaw", 1, 5),
("biegunka", "tháwng sǐa", "ท้องเสีย", "Zdrowie", "Objawy", "noun", "thing", "an|อัน|objaw", 1, 4),
("alergia", "phráe", "แพ้", "Zdrowie", "Objawy", "noun", "thing", "an|อัน|objaw", 1, 4),
("rana", "bàat phlǎe", "บาดแผล", "Zdrowie", "Objawy", "noun", "thing", "phlǎe|แผล|rana", 0, 3),
("ubezpieczenie", "prakan", "ประกัน", "Zdrowie", "Formalności", "noun", "thing", "an|อัน|polisa", 0, 3),
("szpitalna izba przyjęć", "hâwng chùk chə̌ən", "ห้องฉุกเฉิน", "Zdrowie", "Obiekty", "noun", "place", "hâwng|ห้อง|pomieszczenie", 1, 3),

# ------------------------------------------------------------------- LUDZIE
("człowiek / osoba", "khon", "คน", "Ludzie i rodzina", "Ogólne", "noun", "person", "khon|คน|osoba", 1, 5),
("mężczyzna", "phûu chaai", "ผู้ชาย", "Ludzie i rodzina", "Ogólne", "noun", "person", "khon|คน|osoba", 0, 4),
("kobieta", "phûu yǐng", "ผู้หญิง", "Ludzie i rodzina", "Ogólne", "noun", "person", "khon|คน|osoba", 0, 4),
("dziecko", "dèk", "เด็ก", "Ludzie i rodzina", "Ogólne", "noun", "person", "khon|คน|osoba", 0, 4),
("przyjaciel", "phûean", "เพื่อน", "Ludzie i rodzina", "Relacje", "noun", "person", "khon|คน|osoba", 1, 5),
("rodzina", "khrâwp khrua", "ครอบครัว", "Ludzie i rodzina", "Relacje", "noun", "person", "khrâwp khrua|ครอบครัว|rodzina", 0, 4),
("tata", "phâw", "พ่อ", "Ludzie i rodzina", "Rodzina", "noun", "person", "khon|คน|osoba", 0, 4),
("mama", "mâe", "แม่", "Ludzie i rodzina", "Rodzina", "noun", "person", "khon|คน|osoba", 0, 4),
("starszy brat / starsza siostra", "phîi", "พี่", "Ludzie i rodzina", "Rodzina", "noun", "person", "khon|คน|osoba", 1, 5),
("młodsze rodzeństwo", "náwng", "น้อง", "Ludzie i rodzina", "Rodzina", "noun", "person", "khon|คน|osoba", 1, 5),
("syn / córka", "lûuk", "ลูก", "Ludzie i rodzina", "Rodzina", "noun", "person", "khon|คน|osoba", 0, 4),
("partner / partnerka", "faen", "แฟน", "Ludzie i rodzina", "Relacje", "noun", "person", "khon|คน|osoba", 0, 4),
("mąż", "sǎamii", "สามี", "Ludzie i rodzina", "Rodzina", "noun", "person", "khon|คน|osoba", 0, 3),
("żona", "phanrayaa", "ภรรยา", "Ludzie i rodzina", "Rodzina", "noun", "person", "khon|คน|osoba", 0, 3),
("imię", "chûe", "ชื่อ", "Ludzie i rodzina", "Dane osobowe", "noun", "thing", "chûe|ชื่อ|imię", 1, 5),
("Tajka / Tajowie", "khon thai", "คนไทย", "Ludzie i rodzina", "Narodowości", "noun", "person", "khon|คน|osoba", 1, 4),
("Polak / Polka", "khon poo-laen", "คนโปแลนด์", "Ludzie i rodzina", "Narodowości", "noun", "person", "khon|คน|osoba", 1, 4),
("obcokrajowiec", "chaaw tàang châat", "ชาวต่างชาติ", "Ludzie i rodzina", "Narodowości", "noun", "person", "khon|คน|osoba", 0, 3),
("policjant", "tamrùat", "ตำรวจ", "Awarie i pomoc", "Ludzie", "noun", "person", "khon|คน|osoba", 1, 4),
("kelner / obsługa", "phanák ngaan", "พนักงาน", "Restauracja", "Ludzie", "noun", "person", "khon|คน|osoba", 0, 4),
("kierowca", "khon khàp rót", "คนขับรถ", "Transport", "Ludzie", "noun", "person", "khon|คน|osoba", 1, 4),
("nauczyciel", "khruu", "ครู", "Praca i nauka", "Ludzie", "noun", "person", "khon|คน|osoba", 0, 3),
("student", "nák rian", "นักเรียน", "Praca i nauka", "Ludzie", "noun", "person", "khon|คน|osoba", 0, 3),

# ------------------------------------------------------- DOM I CODZIENNOSC
("klucz", "kunjae", "กุญแจ", "Hotel", "Wyposażenie", "noun", "thing", "dàwk|ดอก|sztuka", 1, 4),
("klimatyzacja", "ae", "แอร์", "Hotel", "Wyposażenie", "noun", "thing", "khrûeang|เครื่อง|sztuka", 1, 5),
("wentylator", "phát lom", "พัดลม", "Hotel", "Wyposażenie", "noun", "thing", "khrûeang|เครื่อง|sztuka", 0, 3),
("ręcznik", "phâa chét tua", "ผ้าเช็ดตัว", "Hotel", "Wyposażenie", "noun", "thing", "phǔuen|ผืน|sztuka", 1, 4),
("łóżko", "tiang", "เตียง", "Hotel", "Wyposażenie", "noun", "thing", "tiang|เตียง|łóżko", 0, 4),
("prysznic", "fàk bua", "ฝักบัว", "Hotel", "Wyposażenie", "noun", "thing", "an|อัน|sztuka", 0, 3),
("gorąca woda", "náam ráwn", "น้ำร้อน", "Hotel", "Wyposażenie", "noun", "thing", "an|อัน|sztuka", 1, 4),
("światło", "fai", "ไฟ", "Dom i codzienność", "Wyposażenie", "noun", "thing", "duang|ดวง|sztuka", 0, 4),
("okno", "nâa tàang", "หน้าต่าง", "Dom i codzienność", "Wyposażenie", "noun", "thing", "baan|บาน|sztuka", 0, 3),
("drzwi", "pratuu", "ประตู", "Dom i codzienność", "Wyposażenie", "noun", "thing", "baan|บาน|sztuka", 0, 3),
("praca", "ngaan", "งาน", "Praca i nauka", "Ogólne", "noun", "thing", "ngaan|งาน|praca", 0, 4),
("czas", "weelaa", "เวลา", "Czas i daty", "Ogólne", "noun", "thing", "weelaa|เวลา|czas", 1, 5),
("problem", "panhǎa", "ปัญหา", "Awarie i pomoc", "Ogólne", "noun", "thing", "khâw|ข้อ|sprawa", 1, 4),

# ---------------------------------------------------------------- CZASOWNIKI
("jeść", "kin", "กิน", "Czasowniki", "Codzienne", "verb", "verb", "", 1, 5),
("pić", "dùem", "ดื่ม", "Czasowniki", "Codzienne", "verb", "verb", "", 1, 4),
("iść / jechać", "pai", "ไป", "Czasowniki", "Ruch", "verb", "verb", "", 1, 5),
("przyjść / przyjechać", "maa", "มา", "Czasowniki", "Ruch", "verb", "verb", "", 1, 5),
("kupować", "súe", "ซื้อ", "Czasowniki", "Zakupy", "verb", "verb", "", 1, 5),
("sprzedawać", "khǎai", "ขาย", "Czasowniki", "Zakupy", "verb", "verb", "", 1, 4),
("płacić", "jàai", "จ่าย", "Czasowniki", "Zakupy", "verb", "verb", "", 1, 5),
("robić", "tham", "ทำ", "Czasowniki", "Codzienne", "verb", "verb", "", 1, 5),
("mówić", "phûut", "พูด", "Czasowniki", "Komunikacja", "verb", "verb", "", 1, 5),
("słuchać", "fang", "ฟัง", "Czasowniki", "Komunikacja", "verb", "verb", "", 0, 4),
("czytać", "àan", "อ่าน", "Czasowniki", "Komunikacja", "verb", "verb", "", 0, 4),
("pisać", "khǐan", "เขียน", "Czasowniki", "Komunikacja", "verb", "verb", "", 0, 4),
("spać", "nawn", "นอน", "Czasowniki", "Codzienne", "verb", "verb", "", 1, 5),
("budzić się", "tùen", "ตื่น", "Czasowniki", "Codzienne", "verb", "verb", "", 0, 3),
("pracować", "tham ngaan", "ทำงาน", "Czasowniki", "Praca", "verb", "verb", "", 0, 4),
("uczyć się", "rian", "เรียน", "Czasowniki", "Praca", "verb", "verb", "", 0, 4),
("lubić", "châwp", "ชอบ", "Czasowniki", "Emocje", "verb", "verb", "", 1, 5),
("kochać", "rák", "รัก", "Czasowniki", "Emocje", "verb", "verb", "", 0, 4),
("chcieć (coś zrobić)", "yàak", "อยาก", "Czasowniki", "Modalne", "verb", "verb", "", 1, 5),
("musieć", "tâwng", "ต้อง", "Czasowniki", "Modalne", "verb", "verb", "", 1, 5),
("mieć", "mii", "มี", "Czasowniki", "Podstawowe", "verb", "verb", "", 1, 5),
("dawać", "hâi", "ให้", "Czasowniki", "Podstawowe", "verb", "verb", "", 0, 4),
("brać", "ao", "เอา", "Czasowniki", "Podstawowe", "verb", "verb", "", 1, 5),
("pomagać", "chûai", "ช่วย", "Czasowniki", "Podstawowe", "verb", "verb", "", 1, 5),
("czekać", "raw", "รอ", "Czasowniki", "Podstawowe", "verb", "verb", "", 1, 4),
("szukać", "hǎa", "หา", "Czasowniki", "Podstawowe", "verb", "verb", "", 1, 4),
("spotykać", "jəə", "เจอ", "Czasowniki", "Relacje", "verb", "verb", "", 0, 4),
("wiedzieć", "rúu", "รู้", "Czasowniki", "Podstawowe", "verb", "verb", "", 1, 5),
("znać", "rúu-jàk", "รู้จัก", "Czasowniki", "Podstawowe", "verb", "verb", "", 0, 4),
("rozumieć", "khâo-jai", "เข้าใจ", "Czasowniki", "Komunikacja", "verb", "verb", "", 1, 5),
("pamiętać", "jam", "จำ", "Czasowniki", "Podstawowe", "verb", "verb", "", 0, 3),
("zapominać", "luem", "ลืม", "Czasowniki", "Podstawowe", "verb", "verb", "", 0, 3),
("otwierać", "pòet", "เปิด", "Czasowniki", "Codzienne", "verb", "verb", "", 1, 4),
("zamykać", "pìt", "ปิด", "Czasowniki", "Codzienne", "verb", "verb", "", 1, 4),
("iść pieszo", "dəən", "เดิน", "Czasowniki", "Ruch", "verb", "verb", "", 1, 4),
("biegać", "wîng", "วิ่ง", "Czasowniki", "Ruch", "verb", "verb", "", 0, 3),
("prowadzić samochód", "khàp rót", "ขับรถ", "Czasowniki", "Ruch", "verb", "verb", "", 0, 3),
("wsiadać", "khûen", "ขึ้น", "Czasowniki", "Ruch", "verb", "verb", "", 1, 4),
("wysiadać", "long", "ลง", "Czasowniki", "Ruch", "verb", "verb", "", 1, 4),
("skręcać", "líaw", "เลี้ยว", "Czasowniki", "Ruch", "verb", "verb", "", 1, 4),
("zatrzymać się", "jàwt", "จอด", "Czasowniki", "Ruch", "verb", "verb", "", 1, 4),
("przestać", "yùt", "หยุด", "Czasowniki", "Ruch", "verb", "verb", "", 1, 4),
("pytać", "thǎam", "ถาม", "Czasowniki", "Komunikacja", "verb", "verb", "", 0, 4),
("odpowiadać", "tàwp", "ตอบ", "Czasowniki", "Komunikacja", "verb", "verb", "", 0, 3),
("dzwonić", "thoo", "โทร", "Czasowniki", "Komunikacja", "verb", "verb", "", 0, 4),
("wysyłać", "sòng", "ส่ง", "Czasowniki", "Komunikacja", "verb", "verb", "", 0, 4),
("wynajmować", "châo", "เช่า", "Czasowniki", "Podróż", "verb", "verb", "", 1, 4),
("rezerwować", "jawng", "จอง", "Czasowniki", "Podróż", "verb", "verb", "", 1, 4),
("anulować", "yók lôek", "ยกเลิก", "Czasowniki", "Podróż", "verb", "verb", "", 0, 3),
("zmieniać", "plìan", "เปลี่ยน", "Czasowniki", "Podróż", "verb", "verb", "", 1, 4),
("myć", "láang", "ล้าง", "Czasowniki", "Codzienne", "verb", "verb", "", 0, 3),
("prać", "sák phâa", "ซักผ้า", "Czasowniki", "Codzienne", "verb", "verb", "", 0, 3),
("brać prysznic", "àap náam", "อาบน้ำ", "Czasowniki", "Codzienne", "verb", "verb", "", 0, 3),
("odpoczywać", "phák phàwn", "พักผ่อน", "Czasowniki", "Codzienne", "verb", "verb", "", 0, 3),
("pływać", "wâai náam", "ว่ายน้ำ", "Czasowniki", "Rozrywka", "verb", "verb", "", 0, 3),
("robić zdjęcia", "thàai rûup", "ถ่ายรูป", "Czasowniki", "Rozrywka", "verb", "verb", "", 1, 4),
("zwiedzać", "thîaw", "เที่ยว", "Czasowniki", "Rozrywka", "verb", "verb", "", 1, 5),
("próbować (smakować)", "chim", "ชิม", "Czasowniki", "Jedzenie", "verb", "verb", "", 1, 4),
("przymierzać / próbować", "lawng", "ลอง", "Czasowniki", "Zakupy", "verb", "verb", "", 1, 4),
("zamawiać", "sàng", "สั่ง", "Czasowniki", "Jedzenie", "verb", "verb", "", 1, 5),
("gotować", "tham aa-hǎan", "ทำอาหาร", "Czasowniki", "Jedzenie", "verb", "verb", "", 0, 3),
("siedzieć", "nâng", "นั่ง", "Czasowniki", "Codzienne", "verb", "verb", "", 1, 4),
("oglądać", "duu", "ดู", "Czasowniki", "Rozrywka", "verb", "verb", "", 0, 4),
("grać / bawić się", "lên", "เล่น", "Czasowniki", "Rozrywka", "verb", "verb", "", 0, 3),
("myśleć", "khít", "คิด", "Czasowniki", "Podstawowe", "verb", "verb", "", 0, 4),
("policzyć rachunek", "khít ngoen", "คิดเงิน", "Czasowniki", "Zakupy", "verb", "verb", "", 1, 5),
("odbierać", "ráp", "รับ", "Czasowniki", "Podstawowe", "verb", "verb", "", 0, 4),
("wracać", "klàp", "กลับ", "Czasowniki", "Ruch", "verb", "verb", "", 1, 4),
("wchodzić", "khâo", "เข้า", "Czasowniki", "Ruch", "verb", "verb", "", 0, 4),
("wychodzić", "àwk", "ออก", "Czasowniki", "Ruch", "verb", "verb", "", 0, 4),

# --------------------------------------------------------------- PRZYMIOTNIKI
("dobry", "dii", "ดี", "Cechy i opinie", "Ocena", "adj", "adj", "dobre", 1, 5),
("zły / kiepski", "yâe", "แย่", "Cechy i opinie", "Ocena", "adj", "adj", "kiepskie", 1, 4),
("duży", "yài", "ใหญ่", "Cechy i opinie", "Rozmiar", "adj", "adj", "duże", 1, 5),
("mały", "lék", "เล็ก", "Cechy i opinie", "Rozmiar", "adj", "adj", "małe", 1, 5),
("gorący", "ráwn", "ร้อน", "Cechy i opinie", "Temperatura", "adj", "adj", "gorące", 1, 5),
("zimny (o napoju)", "yen", "เย็น", "Cechy i opinie", "Temperatura", "adj", "adj", "zimne", 1, 5),
("zimno (o pogodzie)", "nǎaw", "หนาว", "Cechy i opinie", "Temperatura", "adj", "adj", "zimno", 0, 4),
("ostry (pikantny)", "phèt", "เผ็ด", "Cechy i opinie", "Smak", "adj", "adj", "ostre", 1, 5),
("smaczny", "à-ròi", "อร่อย", "Cechy i opinie", "Smak", "adj", "adj", "smaczne", 1, 5),
("słodki", "wǎan", "หวาน", "Cechy i opinie", "Smak", "adj", "adj", "słodkie", 1, 4),
("słony", "khem", "เค็ม", "Cechy i opinie", "Smak", "adj", "adj", "słone", 0, 3),
("kwaśny", "prîaw", "เปรี้ยว", "Cechy i opinie", "Smak", "adj", "adj", "kwaśne", 0, 3),
("gorzki", "khǒm", "ขม", "Cechy i opinie", "Smak", "adj", "adj", "gorzkie", 0, 3),
("drogi", "phaeng", "แพง", "Cechy i opinie", "Cena", "adj", "adj", "drogie", 1, 5),
("tani", "thùuk", "ถูก", "Cechy i opinie", "Cena", "adj", "adj", "tanie", 1, 5),
("ładny", "sǔai", "สวย", "Cechy i opinie", "Wygląd", "adj", "adj", "ładne", 1, 4),
("uroczy", "nâa rák", "น่ารัก", "Cechy i opinie", "Wygląd", "adj", "adj", "urocze", 0, 4),
("nowy", "mài", "ใหม่", "Cechy i opinie", "Stan", "adj", "adj", "nowe", 0, 4),
("stary", "kào", "เก่า", "Cechy i opinie", "Stan", "adj", "adj", "stare", 0, 4),
("szybki", "rew", "เร็ว", "Cechy i opinie", "Tempo", "adj", "adj", "szybkie", 1, 4),
("wolny (powolny)", "cháa", "ช้า", "Cechy i opinie", "Tempo", "adj", "adj", "wolne", 1, 4),
("daleki", "klai", "ไกล", "Cechy i opinie", "Odległość", "adj", "adj", "daleko", 1, 5),
("bliski", "klâi", "ใกล้", "Cechy i opinie", "Odległość", "adj", "adj", "blisko", 1, 5),
("łatwy", "ngâai", "ง่าย", "Cechy i opinie", "Trudność", "adj", "adj", "łatwe", 0, 3),
("trudny", "yâak", "ยาก", "Cechy i opinie", "Trudność", "adj", "adj", "trudne", 0, 3),
("czysty", "saàat", "สะอาด", "Cechy i opinie", "Stan", "adj", "adj", "czyste", 1, 4),
("brudny", "sòk-kapròk", "สกปรก", "Cechy i opinie", "Stan", "adj", "adj", "brudne", 0, 3),
("dużo", "yóe", "เยอะ", "Cechy i opinie", "Ilość", "adj", "adj", "dużo", 1, 4),
("mało", "náwi", "น้อย", "Cechy i opinie", "Ilość", "adj", "adj", "mało", 1, 4),
("wolny (dostępny)", "wâang", "ว่าง", "Cechy i opinie", "Stan", "adj", "adj", "wolne", 1, 4),
("pełny / zajęty", "tem", "เต็ม", "Cechy i opinie", "Stan", "adj", "adj", "pełne", 1, 4),
("zmęczony", "nùeai", "เหนื่อย", "Cechy i opinie", "Samopoczucie", "adj", "adj", "zmęczone", 1, 4),
("głodny", "hǐw", "หิว", "Cechy i opinie", "Samopoczucie", "adj", "adj", "głodne", 1, 5),
("najedzony", "ìm", "อิ่ม", "Cechy i opinie", "Samopoczucie", "adj", "adj", "najedzone", 1, 4),
("spragniony", "hǐw náam", "หิวน้ำ", "Cechy i opinie", "Samopoczucie", "adj", "adj", "spragnione", 1, 4),
("chory", "mâi sabaai", "ไม่สบาย", "Cechy i opinie", "Samopoczucie", "adj", "adj", "chore", 1, 5),
("szczęśliwy", "dii jai", "ดีใจ", "Cechy i opinie", "Emocje", "adj", "adj", "szczęśliwe", 0, 4),
("smutny", "sǐa jai", "เสียใจ", "Cechy i opinie", "Emocje", "adj", "adj", "smutne", 0, 3),
("zdenerwowany", "kròot", "โกรธ", "Cechy i opinie", "Emocje", "adj", "adj", "zdenerwowane", 0, 3),
("przestraszony", "klua", "กลัว", "Cechy i opinie", "Emocje", "adj", "adj", "przestraszone", 0, 3),
("znudzony", "bùea", "เบื่อ", "Cechy i opinie", "Emocje", "adj", "adj", "znudzone", 0, 3),
("fajny / zabawny", "sanùk", "สนุก", "Cechy i opinie", "Emocje", "adj", "adj", "fajne", 1, 5),
("bezpieczny", "plàwt phai", "ปลอดภัย", "Cechy i opinie", "Stan", "adj", "adj", "bezpieczne", 1, 4),
("niebezpieczny", "antaraai", "อันตราย", "Cechy i opinie", "Stan", "adj", "adj", "niebezpieczne", 1, 4),
("cichy / spokojny", "ngîap", "เงียบ", "Cechy i opinie", "Stan", "adj", "adj", "ciche", 0, 3),
("głośny", "sǐang dang", "เสียงดัง", "Cechy i opinie", "Stan", "adj", "adj", "głośne", 0, 3),

# ------------------------------------------------------------------- LICZBY
("zero", "sǔun", "ศูนย์", "Liczby i liczenie", "Liczebniki", "num", "num", "0", 1, 4),
("jeden", "nùeng", "หนึ่ง", "Liczby i liczenie", "Liczebniki", "num", "num", "1", 1, 5),
("dwa", "sǎwng", "สอง", "Liczby i liczenie", "Liczebniki", "num", "num", "2", 1, 5),
("trzy", "sǎam", "สาม", "Liczby i liczenie", "Liczebniki", "num", "num", "3", 1, 5),
("cztery", "sìi", "สี่", "Liczby i liczenie", "Liczebniki", "num", "num", "4", 1, 5),
("pięć", "hâa", "ห้า", "Liczby i liczenie", "Liczebniki", "num", "num", "5", 1, 5),
("sześć", "hòk", "หก", "Liczby i liczenie", "Liczebniki", "num", "num", "6", 1, 5),
("siedem", "jèt", "เจ็ด", "Liczby i liczenie", "Liczebniki", "num", "num", "7", 1, 5),
("osiem", "pàet", "แปด", "Liczby i liczenie", "Liczebniki", "num", "num", "8", 1, 5),
("dziewięć", "kâo", "เก้า", "Liczby i liczenie", "Liczebniki", "num", "num", "9", 1, 5),
("dziesięć", "sìp", "สิบ", "Liczby i liczenie", "Liczebniki", "num", "num", "10", 1, 5),
("jedenaście", "sìp-èt", "สิบเอ็ด", "Liczby i liczenie", "Liczebniki", "num", "num", "11", 1, 4),
("dwadzieścia", "yîi-sìp", "ยี่สิบ", "Liczby i liczenie", "Liczebniki", "num", "num", "20", 1, 5),
("trzydzieści", "sǎam-sìp", "สามสิบ", "Liczby i liczenie", "Liczebniki", "num", "num", "30", 1, 4),
("czterdzieści", "sìi-sìp", "สี่สิบ", "Liczby i liczenie", "Liczebniki", "num", "num", "40", 1, 4),
("pięćdziesiąt", "hâa-sìp", "ห้าสิบ", "Liczby i liczenie", "Liczebniki", "num", "num", "50", 1, 4),
("sto", "nùeng ráwi", "หนึ่งร้อย", "Liczby i liczenie", "Liczebniki", "num", "num", "100", 1, 5),
("dwieście", "sǎwng ráwi", "สองร้อย", "Liczby i liczenie", "Liczebniki", "num", "num", "200", 1, 4),
("pięćset", "hâa ráwi", "ห้าร้อย", "Liczby i liczenie", "Liczebniki", "num", "num", "500", 1, 4),
("tysiąc", "nùeng phan", "หนึ่งพัน", "Liczby i liczenie", "Liczebniki", "num", "num", "1000", 1, 5),
("dziesięć tysięcy", "nùeng mùen", "หนึ่งหมื่น", "Liczby i liczenie", "Liczebniki", "num", "num", "10000", 0, 3),
("milion", "nùeng láan", "หนึ่งล้าน", "Liczby i liczenie", "Liczebniki", "num", "num", "1000000", 0, 3),

# --------------------------------------------------------------- CZAS I DATY
("dzisiaj", "wan níi", "วันนี้", "Czas i daty", "Dni", "noun", "time", "wan|วัน|dzień", 1, 5),
("jutro", "phrûng níi", "พรุ่งนี้", "Czas i daty", "Dni", "noun", "time", "wan|วัน|dzień", 1, 5),
("wczoraj", "mûea waan", "เมื่อวาน", "Czas i daty", "Dni", "noun", "time", "wan|วัน|dzień", 1, 4),
("rano", "tawn cháo", "ตอนเช้า", "Czas i daty", "Pory dnia", "noun", "time", "chûa moong|ชั่วโมง|godzina", 1, 5),
("po południu", "tawn bàai", "ตอนบ่าย", "Czas i daty", "Pory dnia", "noun", "time", "chûa moong|ชั่วโมง|godzina", 1, 4),
("wieczorem", "tawn yen", "ตอนเย็น", "Czas i daty", "Pory dnia", "noun", "time", "chûa moong|ชั่วโมง|godzina", 1, 4),
("w nocy", "klaang khuen", "กลางคืน", "Czas i daty", "Pory dnia", "noun", "time", "chûa moong|ชั่วโมง|godzina", 1, 4),
("godzina", "chûa moong", "ชั่วโมง", "Czas i daty", "Jednostki", "noun", "time", "chûa moong|ชั่วโมง|godzina", 1, 5),
("minuta", "naa-thii", "นาที", "Czas i daty", "Jednostki", "noun", "time", "naa-thii|นาที|minuta", 1, 4),
("dzień", "wan", "วัน", "Czas i daty", "Jednostki", "noun", "time", "wan|วัน|dzień", 1, 5),
("tydzień", "aa-thít", "อาทิตย์", "Czas i daty", "Jednostki", "noun", "time", "aa-thít|อาทิตย์|tydzień", 1, 4),
("miesiąc", "duean", "เดือน", "Czas i daty", "Jednostki", "noun", "time", "duean|เดือน|miesiąc", 1, 4),
("rok", "pii", "ปี", "Czas i daty", "Jednostki", "noun", "time", "pii|ปี|rok", 1, 4),
("poniedziałek", "wan jan", "วันจันทร์", "Czas i daty", "Dni tygodnia", "noun", "time", "wan|วัน|dzień", 0, 4),
("wtorek", "wan angkhaan", "วันอังคาร", "Czas i daty", "Dni tygodnia", "noun", "time", "wan|วัน|dzień", 0, 4),
("środa", "wan phút", "วันพุธ", "Czas i daty", "Dni tygodnia", "noun", "time", "wan|วัน|dzień", 0, 4),
("czwartek", "wan pharúehàt", "วันพฤหัส", "Czas i daty", "Dni tygodnia", "noun", "time", "wan|วัน|dzień", 0, 4),
("piątek", "wan sùk", "วันศุกร์", "Czas i daty", "Dni tygodnia", "noun", "time", "wan|วัน|dzień", 0, 4),
("sobota", "wan sǎo", "วันเสาร์", "Czas i daty", "Dni tygodnia", "noun", "time", "wan|วัน|dzień", 0, 4),
("niedziela", "wan aa-thít", "วันอาทิตย์", "Czas i daty", "Dni tygodnia", "noun", "time", "wan|วัน|dzień", 0, 4),
("teraz", "tawn níi", "ตอนนี้", "Czas i daty", "Określenia", "adv", "time", "", 1, 5),
("później", "thii lǎng", "ทีหลัง", "Czas i daty", "Określenia", "adv", "time", "", 0, 3),
("zaraz", "dǐaw níi", "เดี๋ยวนี้", "Czas i daty", "Określenia", "adv", "time", "", 0, 3),

# ------------------------------------------------------------ PYTANIA I MOWA
("co?", "à-rai", "อะไร", "Pytania", "Słowa pytające", "question", "phrase", "", 1, 5),
("gdzie?", "thîi nǎi", "ที่ไหน", "Pytania", "Słowa pytające", "question", "phrase", "", 1, 5),
("kto?", "khrai", "ใคร", "Pytania", "Słowa pytające", "question", "phrase", "", 1, 4),
("kiedy?", "mûea rài", "เมื่อไหร่", "Pytania", "Słowa pytające", "question", "phrase", "", 1, 4),
("dlaczego?", "tham-mai", "ทำไม", "Pytania", "Słowa pytające", "question", "phrase", "", 1, 4),
("jak?", "yang-ngai", "ยังไง", "Pytania", "Słowa pytające", "question", "phrase", "", 1, 5),
("ile? (cena)", "thâo-rài", "เท่าไหร่", "Pytania", "Słowa pytające", "question", "phrase", "", 1, 5),
("ile? (sztuk)", "kìi", "กี่", "Pytania", "Słowa pytające", "question", "phrase", "", 1, 4),
("który?", "an nǎi", "อันไหน", "Pytania", "Słowa pytające", "question", "phrase", "", 0, 3),
("tutaj", "thîi nîi", "ที่นี่", "Miejsca i orientacja", "Orientacja", "adv", "phrase", "", 1, 5),
("tam", "thîi nân", "ที่นั่น", "Miejsca i orientacja", "Orientacja", "adv", "phrase", "", 1, 4),
("w lewo", "sáai", "ซ้าย", "Miejsca i orientacja", "Kierunki", "adv", "phrase", "", 1, 5),
("w prawo", "khwǎa", "ขวา", "Miejsca i orientacja", "Kierunki", "adv", "phrase", "", 1, 5),
("prosto", "trong pai", "ตรงไป", "Miejsca i orientacja", "Kierunki", "adv", "phrase", "", 1, 5),
("z tyłu / za", "khâang lǎng", "ข้างหลัง", "Miejsca i orientacja", "Kierunki", "adv", "phrase", "", 0, 3),
("z przodu / przed", "khâang nâa", "ข้างหน้า", "Miejsca i orientacja", "Kierunki", "adv", "phrase", "", 1, 4),
("obok", "khâang khâang", "ข้างๆ", "Miejsca i orientacja", "Kierunki", "adv", "phrase", "", 0, 3),
("naprzeciwko", "trong khâam", "ตรงข้าม", "Miejsca i orientacja", "Kierunki", "adv", "phrase", "", 0, 3),
]
