# -*- coding: utf-8 -*-
"""Sesja N, partia siódma — DOMKNIĘCIE PROGU.

Po sześciu partiach było 827 haseł. Ta partia domyka próg 900 i robi to
wyłącznie w kategoriach, które po wyrównaniu wciąż stały najniżej: Podstawy,
Zakupy, Liczby, Czas, Hotel, Restauracja, Dom. Praca i nauka, która po partii
trzeciej wyszła na prowadzenie ze 123 hasłami, nie dostaje tu nic.

Krotka: (poziom, polski, fonetyka, pismo, podkategoria, częstość, typ,
         kategoria, uwaga, dosłownie)
"""

PG = "Podstawy i grzeczność"
ZK = "Zakupy i pieniądze"
LI = "Liczby i liczenie"
CD = "Czas i daty"
HO = "Hotel"
RE = "Restauracja"
DM = "Dom i codzienność"
PL = "Miejsca i orientacja"
LR = "Ludzie i rodzina"
TR = "Transport"
ST = "Small talk"

CLOSE = [

# ============================================================ PODSTAWY
("A1", "witaj w domu", "yin dii tâwn ráp", "ยินดีต้อนรับ", "Zwroty grzecznościowe", 4, "w", PG,
 "Napis nad każdym wejściem — do hotelu, sklepu i lotniska.", "cieszyć się witać"),
("A1", "miło mi", "yin dii thîi dâi rúu-jàk", "ยินดีที่ได้รู้จัก", "Zwroty grzecznościowe", 4, "w", PG,
 "Pełna formuła przy poznaniu; skracana do samego yin dii.", "cieszyć się że móc poznać"),
("A1", "do zobaczenia wkrótce", "láew jooe kan", "แล้วเจอกัน", "Zwroty grzecznościowe", 5, "w", PG,
 "Potoczne pożegnanie, znacznie częstsze niż laa kàwn.", "potem spotkać nawzajem"),
("A1", "trzymaj się", "raksǎa tua dûai", "รักษาตัวด้วย", "Zwroty grzecznościowe", 3, "w", PG,
 "Dosłownie „chroń też swoje ciało”.", "chronić ciało też"),
("A1", "przekaż pozdrowienia", "fàak sà-wàt-dii dûai", "ฝากสวัสดีด้วย", "Zwroty grzecznościowe", 3, "w", PG,
 "fàak to powierzyć komuś coś do przekazania.", "powierzyć pozdrowienie też"),
("A1", "powierzyć, zostawić u kogoś", "fàak", "ฝาก", "Zwroty grzecznościowe", 4, "v", PG,
 "fàak krà-pǎo — zostawić bagaż na przechowanie. Bardzo produktywne.", ""),
("A1", "proszę mówić wolniej", "phûut cháa cháa nòi", "พูดช้าๆหน่อย", "Zwroty grzecznościowe", 5, "w", PG,
 "Podwojenie cháa łagodzi prośbę.", "mówić powoli trochę"),
("A1", "nie mówię po tajsku", "phûut thai mâi dâi", "พูดไทยไม่ได้", "Zwroty grzecznościowe", 5, "w", PG,
 "dâi po czasowniku znaczy „umieć, móc”.", "mówić tajski nie móc"),
("A1", "mówię trochę po tajsku", "phûut thai dâi nít nòi", "พูดไทยได้นิดหน่อย", "Zwroty grzecznościowe", 5, "w", PG,
 "Zdanie, które zawsze poprawia nastawienie rozmówcy.", "mówić tajski móc trochę"),
("A1", "trochę, odrobinę", "nít nòi", "นิดหน่อย", "Zwroty grzecznościowe", 5, "adv", PG,
 "", ""),
("A1", "czy mówisz po angielsku?", "phûut ang-krìt dâi mǎi", "พูดอังกฤษได้ไหม", "Zwroty grzecznościowe", 5, "w", PG,
 "", "mówić angielski móc czy"),
("A1", "język angielski", "phaa-sǎa ang-krìt", "ภาษาอังกฤษ", "Zwroty grzecznościowe", 5, "n", PG,
 "phaa-sǎa plus nazwa kraju działa dla każdego języka.", "język angielski"),
("A1", "język tajski", "phaa-sǎa thai", "ภาษาไทย", "Zwroty grzecznościowe", 5, "n", PG,
 "", "język tajski"),
("A1", "język polski", "phaa-sǎa poo-laen", "ภาษาโปแลนด์", "Zwroty grzecznościowe", 4, "n", PG,
 "", "język Polska"),
("A1", "jak się to pisze?", "khǐan yang ngai", "เขียนยังไง", "Zwroty grzecznościowe", 4, "w", PG,
 "khǐan to pisać.", "pisać jak"),
("A1", "proszę napisać", "khǐan hâi nòi", "เขียนให้หน่อย", "Zwroty grzecznościowe", 4, "w", PG,
 "hâi nòi domyka grzeczną prośbę — „zrób to dla mnie, proszę”.", "pisać dla trochę"),
("A1", "nie szkodzi, spokojnie", "châi châi", "ใจเย็นๆ", "Zwroty grzecznościowe", 4, "w", PG,
 "W praktyce mówi się „jai yen yen” — ostudź serce.", ""),

# ============================================================ ZAKUPY
("A2", "metka, etykieta", "pâai raa-khaa", "ป้ายราคา", "Cena", 4, "n", ZK,
 "Znów pâai — tablica, znak.", "tabliczka cena"),
("A2", "cena stała", "raa-khaa dìao", "ราคาเดียว", "Cena", 3, "n", ZK,
 "Sygnał, że targowanie nie wchodzi w grę.", "cena jeden"),
("A2", "za sztukę", "chín lá", "ชิ้นละ", "Cena", 4, "adv", ZK,
 "lá po klasyfikatorze znaczy „za każdy”: kì-loo lá, khon lá, wan lá.", "sztuka za"),
("A2", "za kilogram", "kì-loo lá", "กิโลละ", "Cena", 4, "adv", ZK,
 "Formuła cenowa na każdym targu.", "kilogram za"),
("A2", "trzy za sto", "sǎam an rói", "สามอันร้อย", "Cena", 4, "w", ZK,
 "Klasyczny sposób podawania ceny hurtowej na ulicy.", "trzy sztuka sto"),
("A2", "drogo jak na to", "phaeng kooen pai", "แพงเกินไป", "Cena", 5, "w", ZK,
 "Otwiera targowanie bez obrażania sprzedawcy.", "drogi przekraczać"),
("A2", "dam ci taniej", "lót hâi", "ลดให้", "Cena", 4, "v", ZK,
 "Odpowiedź sprzedawcy na targowanie.", "obniżać dla"),
("A2", "ostatnia cena", "raa-khaa sùt tháai", "ราคาสุดท้าย", "Cena", 4, "n", ZK,
 "Sygnał końca negocjacji z obu stron.", "cena ostatni"),
("A2", "przymierzalnia", "hâwng lawng sûea", "ห้องลองเสื้อ", "Towar", 3, "n", ZK,
 "", "pokój próbować koszula"),
("A2", "za duży", "yài kooen pai", "ใหญ่เกินไป", "Towar", 4, "adj", ZK,
 "", "duży przekraczać"),
("A2", "za mały", "lék kooen pai", "เล็กเกินไป", "Towar", 4, "adj", ZK,
 "", "mały przekraczać"),
("A2", "inny wzór", "lai ùen", "ลายอื่น", "Towar", 3, "n", ZK,
 "lai to wzór, deseń.", "wzór inny"),
("A2", "wzór, deseń", "lai", "ลาย", "Towar", 3, "n", ZK,
 "Także odcisk palca: lai níu mue.", ""),
("A2", "w paski", "lai thaang", "ลายทาง", "Towar", 2, "adj", ZK,
 "", "wzór droga"),
("A2", "w kratkę", "lai tà-raang", "ลายตาราง", "Towar", 2, "adj", ZK,
 "", "wzór tabela"),
("A2", "gładki, jednolity", "sǐi phúeun", "สีพื้น", "Towar", 2, "adj", ZK,
 "Znów phúeun — tło, powierzchnia.", "kolor tło"),
("A2", "wada, skaza towaru", "tam-nì", "ตำหนิ", "Towar", 2, "n", ZK,
 "Także „upomnieć kogoś”.", ""),
("A2", "gwarancja zwrotu", "khuen ngoen", "คืนเงิน", "Towar", 3, "n", ZK,
 "Znów khuen — zwracać.", "zwracać pieniądze"),
("A2", "koszyk sklepowy", "tà-krâa", "ตะกร้า", "Towar", 3, "n", ZK,
 "Także zwykły kosz wiklinowy.", ""),
("A2", "kasa samoobsługowa", "khǽt-chîa àt-tà-noo-mát", "แคชเชียร์อัตโนมัติ", "Płatność", 2, "n", ZK,
 "àt-tà-noo-mát to automatyczny.", "kasa automatyczny"),
("A2", "automatyczny", "àt-tà-noo-mát", "อัตโนมัติ", "Płatność", 3, "adj", ZK,
 "Częste na tabliczkach przy drzwiach i bramkach.", ""),

# ============================================================ LICZBY
("A2", "podwójna porcja", "phí-sèet", "พิเศษ", "Szacowanie", 5, "adj", LI,
 "W barze z makaronem „phí-sèet” znaczy większa porcja za kilka bahtów więcej.", ""),
("A2", "sztuk (ile ich jest)", "kìi chín", "กี่ชิ้น", "Zapis liczb", 4, "w", LI,
 "", "ile sztuka"),
("A2", "po kolei, jeden po drugim", "thii lá an", "ทีละอัน", "Szacowanie", 3, "adv", LI,
 "thii lá plus klasyfikator: thii lá khon, thii lá kâao.", "raz za sztuka"),
("A2", "krok po kroku", "thii lá kâao", "ทีละก้าว", "Szacowanie", 2, "adv", LI,
 "kâao to krok.", "raz za krok"),
("A2", "podwójnie tyle", "thâo tua", "เท่าตัว", "Szacowanie", 2, "adv", LI,
 "", "raz ciało"),
("A2", "tyle samo", "thâo kan", "เท่ากัน", "Szacowanie", 5, "adv", LI,
 "", "równy nawzajem"),
("A2", "niecały, poniżej", "mâi thǔeng", "ไม่ถึง", "Szacowanie", 4, "adv", LI,
 "Dosłownie „nie sięga”. mâi thǔeng rói — niecałe sto.", "nie sięgać"),
("A2", "ponad, powyżej", "kooen", "เกิน", "Szacowanie", 4, "adv", LI,
 "Przeciwieństwo mâi thǔeng.", ""),
("A2", "resztę zatrzymaj", "mâi tâwng thawn", "ไม่ต้องทอน", "Szacowanie", 4, "w", LI,
 "Znów thawn — wydawać resztę.", "nie trzeba wydawać reszty"),
("A2", "równo, bez reszty", "phaw dii phaw dii", "พอดีๆ", "Szacowanie", 3, "adv", LI,
 "", "akurat akurat"),

# ============================================================ CZAS
("A2", "przedwczoraj wieczorem", "khuen wan suen suen", "คืนวันซืนซืน", "Odcinki czasu", 2, "adv", CD,
 "Formy potoczne; w piśmie raczej opisowo.", "noc dzień przedwczoraj"),
("A2", "za trzy dni", "ìik sǎam wan", "อีกสามวัน", "Odcinki czasu", 4, "adv", CD,
 "ìik plus liczba plus jednostka — uniwersalny wzorzec przyszłości.", "jeszcze trzy dzień"),
("A2", "trzy dni temu", "sǎam wan thîi láew", "สามวันที่แล้ว", "Odcinki czasu", 4, "adv", CD,
 "thîi láew po jednostce daje przeszłość.", "trzy dzień który minął"),
("A2", "przez cały dzień", "tháng wan", "ทั้งวัน", "Odcinki czasu", 4, "adv", CD,
 "tháng to cały: tháng khuen, tháng pii, tháng khrâwp khrua.", "cały dzień"),
("A2", "cały", "tháng", "ทั้ง", "Odcinki czasu", 5, "adj", CD,
 "", ""),
("A2", "w porę, na czas", "than wee-laa", "ทันเวลา", "Odcinki czasu", 4, "adv", CD,
 "Znów than — zdążyć.", "zdążyć czas"),
("A2", "z wyprzedzeniem", "lûang nâa", "ล่วงหน้า", "Odcinki czasu", 4, "adv", CD,
 "jawng lûang nâa — zarezerwować z góry.", "wyprzedzać twarz"),
("A2", "w ostatniej chwili", "naa-thii sùt tháai", "นาทีสุดท้าย", "Odcinki czasu", 3, "adv", CD,
 "", "minuta ostatni"),
("A2", "coraz później", "sǎai khûen rûeai rûeai", "สายขึ้นเรื่อยๆ", "Odcinki czasu", 2, "adv", CD,
 "rûeai rûeai znaczy „stopniowo, ciągle”.", "późno wznosić stopniowo"),
("A2", "stopniowo, po trochu", "rûeai rûeai", "เรื่อยๆ", "Odcinki czasu", 3, "adv", CD,
 "Także odpowiedź na „jak leci” — „po staremu, jakoś leci”.", ""),

# ============================================================ HOTEL I DOM
("A2", "zaliczka przy rezerwacji", "mát jam", "มัดจำ", "Rezerwacja", 3, "n", HO,
 "Zwrotna przy oddaniu klucza bez uszkodzeń.", "wiązać zastaw"),
("A2", "regulamin", "kòt rá-bìap", "กฎระเบียบ", "Rezerwacja", 2, "n", HO,
 "rá-bìap to porządek, dyscyplina.", "reguła porządek"),
("A2", "zwierzęta niedozwolone", "hâam nam sàt líang khâo", "ห้ามนำสัตว์เลี้ยงเข้า", "Rezerwacja", 2, "w", HO,
 "nam to prowadzić, wnosić.", "zakaz wnosić zwierzę wchodzić"),
("A2", "wnosić, przyprowadzać", "nam", "นำ", "Rezerwacja", 4, "v", HO,
 "Także „przewodzić, prowadzić grupę”.", ""),
("A2", "zwierzę domowe", "sàt líang", "สัตว์เลี้ยง", "Rezerwacja", 3, "n", DM,
 "Znów líang — karmić, utrzymywać.", "zwierzę hodowany"),
("A2", "ogrzewanie wody", "khrûeang tham nám ùn", "เครื่องทำน้ำอุ่น", "Wyposażenie", 3, "n", HO,
 "ùn to ciepły, letni — mniej niż ráwn.", "urządzenie robić woda ciepły"),
("A2", "ciepły (letni)", "ùn", "อุ่น", "Wyposażenie", 4, "adj", DM,
 "Między yen a ráwn. Także „podgrzać jedzenie”.", ""),
("A2", "kran", "kók nám", "ก๊อกน้ำ", "Wyposażenie", 3, "n", DM,
 "", "kurek woda"),
("A2", "odpływ, kratka ściekowa", "thâw nám thíng", "ท่อน้ำทิ้ง", "Wyposażenie", 2, "n", DM,
 "thâw to rura.", "rura woda wyrzucać"),
("A2", "rura", "thâw", "ท่อ", "Wyposażenie", 3, "n", DM,
 "", ""),
("A2", "korek do zlewu", "jùk", "จุก", "Wyposażenie", 2, "n", DM,
 "Także zatyczka do butelki.", ""),
("A2", "listwa zasilająca", "plák phûang", "ปลั๊กพ่วง", "Wyposażenie", 3, "n", DM,
 "phûang to doczepiać.", "wtyczka doczepiony"),
("A2", "żaluzje, roleta", "mâan múan", "ม่านม้วน", "Wyposażenie", 2, "n", DM,
 "múan to zwijać.", "zasłona zwijany"),
("A2", "klimatyzacja nie chłodzi", "ae mâi yen", "แอร์ไม่เย็น", "Wyposażenie", 3, "w", DM,
 "Najczęstsza reklamacja w tanim hotelu.", "klimatyzacja nie zimny"),
("A2", "hałaśliwy sąsiad", "phûean bâan sǐang dang", "เพื่อนบ้านเสียงดัง", "Wyposażenie", 2, "n", DM,
 "", "sąsiad dźwięk głośny"),

# ============================================================ RESTAURACJA
("A2", "stragan uliczny", "ráan khǎai khǎwng khâang thaang", "ร้านขายของข้างทาง", "Obsługa", 4, "n", RE,
 "Podstawowa forma gastronomii; taniej i często lepiej niż w lokalu.", "sklep sprzedawać rzecz obok droga"),
("A2", "jadłodajnia z ryżem", "ráan khâao kaeng", "ร้านข้าวแกง", "Obsługa", 4, "n", RE,
 "Wskazujesz palcem na garnki, dostajesz na ryżu.", "sklep ryż curry"),
("A2", "otwarte całą dobę", "pòoet tà-làwt", "เปิดตลอด", "Obsługa", 3, "w", RE,
 "tà-làwt to przez cały czas, nieprzerwanie.", "otwarty nieprzerwanie"),
("A2", "przez cały czas", "tà-làwt", "ตลอด", "Obsługa", 4, "adv", RE,
 "tà-làwt wee-laa — cały czas.", ""),
("A2", "godziny otwarcia", "wee-laa tham kaan", "เวลาทำการ", "Obsługa", 3, "n", RE,
 "tham kaan to funkcjonować, urzędować.", "czas działać"),
("A2", "zamknięte w poniedziałki", "pìt wan jan", "ปิดวันจันทร์", "Obsługa", 3, "w", RE,
 "", "zamknięty dzień poniedziałek"),
("A2", "polecany przez lokalnych", "khon thǎwng thìn nǽ-nam", "คนท้องถิ่นแนะนำ", "Obsługa", 2, "w", RE,
 "thǎwng thìn to miejscowy, lokalny.", "człowiek miejscowy polecać"),
("A2", "miejscowy, lokalny", "thǎwng thìn", "ท้องถิ่น", "Obsługa", 3, "adj", PL,
 "aa-hǎan thǎwng thìn — kuchnia regionalna.", ""),
("A2", "przypalone, spalone", "mâi kròp", "ไหม้กรอบ", "Zamawianie", 2, "adj", RE,
 "kròp to chrupiący — tu w złym sensie.", "palić się chrupiący"),
("A2", "niedosmażone, surowe w środku", "mâi sùk", "ไม่สุก", "Zamawianie", 3, "adj", RE,
 "sùk to dojrzały i ugotowany. Uwaga: homofon z sùk (szczęście).", "nie ugotowany"),
("A2", "ugotowany, dojrzały", "sùk", "สุก", "Zamawianie", 4, "adj", RE,
 "sùk sùk — dobrze wysmażone.", ""),
("A2", "zimne (a powinno być gorące)", "yen chûet", "เย็นชืด", "Zamawianie", 2, "adj", RE,
 "chûet wzmacnia nieprzyjemny odcień.", "zimny zwietrzały"),
("A2", "pomyłka w zamówieniu", "sàng phìt", "สั่งผิด", "Zamawianie", 3, "n", RE,
 "", "zamawiać błędnie"),

# ============================================================ LUDZIE I ROZMOWA
("A2", "znajomy z widzenia", "khon khún nâa", "คนคุ้นหน้า", "Ludzie", 2, "n", LR,
 "khún to być przyzwyczajonym, znajomym.", "człowiek znajomy twarz"),
("A2", "kolega z podróży", "phûean rûam thaang", "เพื่อนร่วมทาง", "Ludzie", 3, "n", LR,
 "", "przyjaciel wspólnie droga"),
("A2", "gospodarz domu (u kogo mieszkamy)", "jâo khǎwng bâan", "เจ้าของบ้าน", "Ludzie", 3, "n", LR,
 "Także wynajmujący mieszkanie.", "właściciel dom"),
("A2", "dzieci (zbiorczo)", "phûak dèk", "พวกเด็ก", "Ludzie", 4, "n", LR,
 "phûak- tworzy liczbę mnogą osób: phûak raw, phûak kháw.", "grupa dziecko"),
("A2", "my (grupa)", "phûak raw", "พวกเรา", "Ludzie", 5, "n", LR,
 "Częstsze w mowie niż samo raw.", "grupa my"),
("A2", "starszy pan", "khun lung", "คุณลุง", "Ludzie", 4, "n", LR,
 "lung to starszy wuj; zwrot uprzejmy do obcego mężczyzny w wieku ojca.", "pan wujek"),
("A2", "starsza pani", "khun pâa", "คุณป้า", "Ludzie", 4, "n", LR,
 "pâa to starsza ciotka. Symetryczne do khun lung.", "pani ciotka"),
("A2", "dziadek (zwrot do obcego)", "khun taa", "คุณตา", "Ludzie", 3, "n", LR,
 "Do mężczyzny w wieku dziadka. Uwaga: taa znaczy też „oko”.", "pan dziadek"),
("A2", "rozmowa (dłuższa)", "kaan sǒn-thá-naa", "การสนทนา", "Rozmowa", 3, "n", ST,
 "W mowie częściej po prostu khui.", "czynność rozmawiać"),
("A2", "przywitać się", "thák thaai", "ทักทาย", "Rozmowa", 4, "v", ST,
 "thák samo to zagadnąć kogoś.", ""),
("A2", "zagadnąć kogoś", "thák", "ทัก", "Rozmowa", 3, "v", ST,
 "Także „zwrócić uwagę na coś u kogoś”.", ""),
("A2", "pożegnać się", "laa", "ลา", "Rozmowa", 4, "v", ST,
 "To samo słowo co „prosić o wolne”: laa pùai, laa àwk.", ""),
("A2", "zmienić temat", "plìan rûeang", "เปลี่ยนเรื่อง", "Rozmowa", 3, "v", ST,
 "", "zmieniać temat"),
("A2", "przesadzać", "wêoe", "เว่อร์", "Rozmowa", 3, "v", ST,
 "Z angielskiego „over”. Bardzo potoczne i bardzo częste wśród młodych.", ""),
("A2", "no jasne, oczywiście", "nâe sì", "แน่สิ", "Rozmowa", 4, "w", ST,
 "sì na końcu dodaje stanowczości.", "pewnie no"),
("A2", "serio? naprawdę?", "jing rǔe", "จริงหรือ", "Rozmowa", 5, "w", ST,
 "W mowie skracane do „jing dì”.", "prawdziwy czy"),
("A2", "nieważne, mniejsza z tym", "chàang man", "ช่างมัน", "Rozmowa", 4, "w", ST,
 "Bardzo tajski zwrot — bliski „mâi pen rai”, ale bardziej lekceważący.", "niech to"),

# ============================================================ MIEJSCA I TRANSPORT
("A2", "wypożyczenie z kierowcą", "châo phráwm khon khàp", "เช่าพร้อมคนขับ", "Podróż", 2, "n", TR,
 "Znów phráwm — razem z, gotowy.", "wynajem razem kierowca"),
("A2", "bagaż podręczny (limit)", "nám-nàk krà-pǎo", "น้ำหนักกระเป๋า", "Podróż", 3, "n", TR,
 "", "waga torba"),
("A2", "nadbagaż", "nám-nàk kooen", "น้ำหนักเกิน", "Podróż", 2, "n", TR,
 "Znów kooen — przekraczać.", "waga przekraczać"),
("A2", "karta pokładowa", "bàt khûen khrûeang", "บัตรขึ้นเครื่อง", "Podróż", 3, "n", TR,
 "bàt to karta — także bàt khree-dìt.", "karta wsiadać maszyna"),
("A2", "opóźnienie lotu", "thîao bin lâa cháa", "เที่ยวบินล่าช้า", "Podróż", 3, "n", TR,
 "", "lot opóźniony"),
("A2", "lot", "thîao bin", "เที่ยวบิน", "Podróż", 4, "n", TR,
 "Znów thîao — kurs, przejazd.", "kurs latać"),
("A2", "hala przylotów", "phûeun thîi phûu doi-sǎan khǎa khâo", "ผู้โดยสารขาเข้า", "Podróż", 2, "n", TR,
 "khǎa khâo to „noga przychodząca” — przyloty; khǎa àwk to odloty.", "pasażer noga wchodzić"),
("A2", "odloty", "khǎa àwk", "ขาออก", "Podróż", 3, "n", TR,
 "Napis na lotnisku i na dworcu.", "noga wychodzić"),
("A2", "przyloty", "khǎa khâo", "ขาเข้า", "Podróż", 3, "n", TR,
 "", "noga wchodzić"),
("A2", "droga w jedną stronę", "khǎa dìao", "ขาเดียว", "Podróż", 3, "n", TR,
 "", "noga jeden"),
("A2", "w obie strony", "pai klàp", "ไปกลับ", "Podróż", 4, "n", TR,
 "", "iść wracać"),
("A2", "postój taksówek", "jùt jàwt tháek-sîi", "จุดจอดแท็กซี่", "Orientacja", 3, "n", PL,
 "jàwt to parkować, zatrzymywać pojazd.", "punkt parkować taksówka"),
("A2", "parkować", "jàwt", "จอด", "Orientacja", 4, "v", PL,
 "hâam jàwt — zakaz postoju.", ""),
("A2", "zakaz parkowania", "hâam jàwt", "ห้ามจอด", "Orientacja", 3, "w", PL,
 "", "zakaz parkować"),
("A2", "ulica jednokierunkowa", "thà-nǒn wan wee", "ถนนวันเวย์", "Orientacja", 2, "n", PL,
 "Z angielskiego one way.", "ulica jednokierunkowy"),
("A2", "ślepa uliczka", "sawi tan", "ซอยตัน", "Orientacja", 3, "n", PL,
 "Znów tan — zatkany. sawi to boczna uliczka.", "uliczka zatkany"),
("A2", "numer domu", "bâan lêek thîi", "บ้านเลขที่", "Orientacja", 3, "n", PL,
 "Pierwszy człon każdego tajskiego adresu.", "dom numer miejsce"),
("A2", "kod pocztowy", "rá-hàt prai-sà-nii", "รหัสไปรษณีย์", "Orientacja", 3, "n", PL,
 "Znów rá-hàt — kod.", "kod poczta"),
]
