# -*- coding: utf-8 -*-
"""Leksyka etapu 6 — czeste czasowniki wraz z naturalnymi uzyciami.

Zasada doboru: kazdy czasownik jest zapisany razem z uzyciem, w ktorym Polak
najczesciej go potrzebuje. Sam bezokolicznik bez kontekstu jest w tajskim malo
uzyteczny, bo o znaczeniu decyduje towarzyszacy rzeczownik albo czasownik
seryjny (np. „ao … pai”, „tham … hǎai”).

Krotka: (poziom, polski, fonetyka, tajski, kategoria, podkategoria, typ,
         freq, rejestr, notatka, znaczenie doslowne, przyklad)
Rejestr: n = neutralny, f = formalny, i = nieformalny, p = potoczny
Przyklad: (polski, fonetyka, tajski)
"""

VERBS = [

# =====================================================================
# RUCH I PRZEMIESZCZANIE
# =====================================================================
("A2", "zanieść coś komuś", "ao pai hâi", "เอาไปให้", "Czasowniki", "Ruch", "phrase", 4, "n",
 "„ao … pai hâi” to jeden z najczęstszych łańcuchów czasownikowych: weź – idź – daj. Polskie „zanieść” nie ma jednego odpowiednika.", "wziąć iść dać",
 ("Zaniosę to koledze.", "phǒm jà ao pai hâi phûean khráp", "ผมจะเอาไปให้เพื่อนครับ")),
("A2", "przynieść coś tutaj", "ao maa hâi", "เอามาให้", "Czasowniki", "Ruch", "phrase", 4, "n",
 "Różnica z „ao pai hâi” to kierunek: „maa” = w stronę mówiącego, „pai” = od mówiącego.", "wziąć przyjść dać",
 ("Proszę przynieść mi rachunek.", "chûai ao bin maa hâi nòi khráp", "ช่วยเอาบิลมาให้หน่อยครับ")),
("A2", "odprowadzić kogoś", "pai sòng", "ไปส่ง", "Czasowniki", "Ruch", "verb", 4, "n",
 "„sòng” znaczy zarówno wysłać, jak i odwieźć człowieka. O ludziach mówi się „pai sòng”.", "iść wysłać",
 ("Odwiozę cię na lotnisko.", "phǒm jà pai sòng thîi sà-nǎam bin khráp", "ผมจะไปส่งที่สนามบินครับ")),
("A2", "odebrać kogoś", "pai ráp", "ไปรับ", "Czasowniki", "Ruch", "verb", 4, "n",
 "Para do „pai sòng”. Tego samego czasownika używa się o odbiorze paczki i dziecka ze szkoły.", "iść odebrać",
 ("Odbiorę cię o siódmej.", "phǒm jà pai ráp tawn jèt mohng khráp", "ผมจะไปรับตอนเจ็ดโมงครับ")),
("A2", "wracać po coś", "klàp pai ao", "กลับไปเอา", "Czasowniki", "Ruch", "phrase", 3, "n",
 "Trzy czasowniki z rzędu są w tajskim normą, nie błędem.", "wrócić iść wziąć",
 ("Muszę wrócić po telefon.", "phǒm tâwng klàp pai ao thoo-rá-sàp khráp", "ผมต้องกลับไปเอาโทรศัพท์ครับ")),
("A1", "przesunąć się", "khà-yàp", "ขยับ", "Czasowniki", "Ruch", "verb", 3, "n",
 "Grzeczna prośba w zatłoczonym autobusie: „khà-yàp nòi dâai mǎi khráp”.", "",
 ("Może się pan trochę przesunąć?", "khà-yàp nòi dâai mǎi khráp", "ขยับหน่อยได้ไหมครับ")),
("A2", "wysiąść na następnym", "long pâai nâa", "ลงป้ายหน้า", "Transport", "W autobusie", "phrase", 4, "n",
 "Standardowa informacja dla konduktora w autobusie miejskim.", "zejść przystanek następny",
 ("Wysiadam na następnym przystanku.", "phǒm long pâai nâa khráp", "ผมลงป้ายหน้าครับ")),
("A2", "zawrócić", "klàp rót", "กลับรถ", "Transport", "Kierunki", "verb", 3, "n",
 "Dosłownie „odwrócić pojazd”. Tego zwrotu używa się też o miejscach do zawracania na drodze.", "wrócić pojazd",
 ("Proszę tu zawrócić.", "chûai klàp rót trong níi nòi khráp", "ช่วยกลับรถตรงนี้หน่อยครับ")),
("A2", "iść pieszo", "doen pai", "เดินไป", "Czasowniki", "Ruch", "phrase", 4, "n",
 "„doen” samo w sobie znaczy „chodzić”; dopiero „doen pai” mówi, że idziesz gdzieś na piechotę.", "chodzić iść",
 ("Pójdę pieszo, to blisko.", "phǒm doen pai kâw dâai khráp klâi khâe níi", "ผมเดินไปก็ได้ครับ ใกล้แค่นี้")),
("B1", "podwieźć kogoś", "hâi tìt rót", "ให้ติดรถ", "Transport", "Uprzejmości", "phrase", 3, "i",
 "Zwrot używany między znajomymi. Wobec obcych lepiej „pai sòng”.", "dać przyczepić pojazd",
 ("Podwiozę cię, wsiadaj.", "phǒm hâi tìt rót pai dûai ná khûen maa loei", "ผมให้ติดรถไปด้วยนะ ขึ้นมาเลย")),

# =====================================================================
# BRANIE, DAWANIE, WYMIANA
# =====================================================================
("A2", "pożyczyć od kogoś", "yuem", "ยืม", "Czasowniki", "Wymiana", "verb", 4, "n",
 "„yuem” to pożyczyć OD kogoś. Pożyczyć KOMUŚ to „hâi yuem”. Pomylenie tych dwóch to najczęstszy błąd Polaków.", "",
 ("Mogę pożyczyć długopis?", "khǎw yuem pàak-kaa nòi dâai mǎi khráp", "ขอยืมปากกาหน่อยได้ไหมครับ")),
("A2", "pożyczyć komuś", "hâi yuem", "ให้ยืม", "Czasowniki", "Wymiana", "phrase", 3, "n",
 "Dosłownie „dać pożyczyć”. Bez „hâi” zdanie znaczy odwrotność tego, co chcesz powiedzieć.", "dać pożyczyć",
 ("Pożyczę ci ładowarkę.", "phǒm hâi yuem thîi châat khráp", "ผมให้ยืมที่ชาร์จครับ")),
("A2", "oddać, zwrócić", "khuen", "คืน", "Czasowniki", "Wymiana", "verb", 4, "n",
 "Ten sam czasownik dotyczy zwrotu towaru w sklepie i oddania pożyczonej rzeczy.", "",
 ("Oddam ci jutro.", "phrûng-níi phǒm khuen hâi ná khráp", "พรุ่งนี้ผมคืนให้นะครับ")),
("A2", "wymienić na inne", "plìan pen", "เปลี่ยนเป็น", "Zakupy i pieniądze", "Reklamacje", "phrase", 4, "n",
 "„plìan” to zmienić; „plìan pen” wskazuje, na co dokładnie.", "zmienić na",
 ("Chciałbym wymienić na większy rozmiar.", "khǎw plìan pen sái yài kwàa dâai mǎi khráp", "ขอเปลี่ยนเป็นไซส์ใหญ่กว่าได้ไหมครับ")),
("A2", "podzielić się czymś", "bàeng kan", "แบ่งกัน", "Czasowniki", "Wymiana", "phrase", 4, "n",
 "„kan” oznacza wzajemność. Bez niego „bàeng” brzmi jak podział techniczny, nie dzielenie się.", "dzielić razem",
 ("Podzielmy się rachunkiem.", "raw bàeng kan jàai ná khráp", "เราแบ่งกันจ่ายนะครับ")),
("B1", "zostawić coś u kogoś", "fàak wái", "ฝากไว้", "Czasowniki", "Wymiana", "phrase", 4, "n",
 "Bardzo tajski czasownik: powierzyć coś czyjejś opiece na czas. Dotyczy bagażu, kluczy i wiadomości.", "powierzyć zostawić",
 ("Zostawię tu walizkę na godzinę.", "khǎw fàak krà-pǎo wái sák chûa-mohng khráp", "ขอฝากกระเป๋าไว้สักชั่วโมงครับ")),
("B1", "przekazać wiadomość", "fàak bàwk", "ฝากบอก", "Czasowniki", "Wymiana", "phrase", 3, "n",
 "Ta sama konstrukcja „fàak” — powierzasz komuś wypowiedzenie czegoś za ciebie.", "powierzyć powiedzieć",
 ("Proszę mu przekazać, że dzwoniłem.", "fàak bàwk khǎo dûai wâa phǒm thoo maa khráp", "ฝากบอกเขาด้วยว่าผมโทรมาครับ")),
("A2", "podać coś", "sòng hâi", "ส่งให้", "Czasowniki", "Wymiana", "phrase", 4, "n",
 "Przy stole: podanie soli, talerza, chusteczek.", "wysłać dać",
 ("Proszę podać mi wodę.", "chûai sòng náam hâi nòi khráp", "ช่วยส่งน้ำให้หน่อยครับ")),

# =====================================================================
# MOWIENIE I POROZUMIEWANIE SIE
# =====================================================================
("A2", "powtórzyć jeszcze raz", "phûut ìik khráng", "พูดอีกครั้ง", "Podstawy i grzeczność", "Prośby", "phrase", 5, "n",
 "Najważniejszy zwrot pierwszego miesiąca. Bez „chûai … nòi” brzmi jak rozkaz.", "mówić jeszcze raz",
 ("Proszę powtórzyć jeszcze raz.", "chûai phûut ìik khráng nòi khráp", "ช่วยพูดอีกครั้งหน่อยครับ")),
("A2", "mówić wolniej", "phûut cháa cháa", "พูดช้าๆ", "Podstawy i grzeczność", "Prośby", "phrase", 5, "n",
 "Podwojenie „cháa cháa” łagodzi prośbę — po tajsku brzmi „powolutku”, nie „wolniej!”.", "mówić powoli powoli",
 ("Proszę mówić trochę wolniej.", "chûai phûut cháa cháa nòi dâai mǎi khráp", "ช่วยพูดช้าๆ หน่อยได้ไหมครับ")),
("A2", "przeliterować", "sà-kòt hâi nòi", "สะกดให้หน่อย", "Podstawy i grzeczność", "Prośby", "phrase", 3, "n",
 "Przydaje się przy nazwiskach i nazwach ulic dyktowanych przez telefon.", "przeliterować dać trochę",
 ("Proszę mi to przeliterować.", "chûai sà-kòt hâi nòi khráp", "ช่วยสะกดให้หน่อยครับ")),
("B1", "wtrącić się do rozmowy", "khǎw sǎwt", "ขอสอด", "Small talk", "Prowadzenie rozmowy", "phrase", 3, "i",
 "Uprzejme wejście w słowo. Bez „khǎw” zabrzmi jak przerwanie rozmowy.", "proszę wtrącić",
 ("Wtrącę się na chwilę.", "khǎw sǎwt nít nùeng ná khráp", "ขอสอดนิดหนึ่งนะครับ")),
("B1", "dojść do porozumienia", "tòk long kan dâai", "ตกลงกันได้", "Praca i nauka", "Ustalenia", "phrase", 3, "n",
 "„tòk long” to zarówno „zgodzić się”, jak i „umówić się na coś”.", "spaść razem móc",
 ("Doszliśmy do porozumienia.", "raw tòk long kan dâai láew khráp", "เราตกลงกันได้แล้วครับ")),
("B1", "wyjaśnić nieporozumienie", "khǎo jai phìt kan", "เข้าใจผิดกัน", "Small talk", "Nieporozumienia", "phrase", 3, "n",
 "Dosłownie „zrozumieć się nawzajem źle”. Zwrot łagodzi winę — nikt nie kłamał, tylko się nie zrozumieliście.", "zrozumieć źle razem",
 ("Chyba się nie zrozumieliśmy.", "khít wâa raw khǎo jai phìt kan ná khráp", "คิดว่าเราเข้าใจผิดกันนะครับ")),
("A2", "zapytać kogoś o coś", "thǎam duu kàwn", "ถามดูก่อน", "Pytania", "Sprawdzanie", "phrase", 4, "n",
 "„duu” po czasowniku znaczy „spróbować i zobaczyć, co wyjdzie”. Bardzo tajskie złagodzenie.", "zapytać zobaczyć najpierw",
 ("Zapytam najpierw kolegi.", "phǒm jà thǎam phûean duu kàwn khráp", "ผมจะถามเพื่อนดูก่อนครับ")),
("A2", "odpowiedzieć na wiadomość", "tàwp khâw-khwaam", "ตอบข้อความ", "Praca i nauka", "Kontakt", "phrase", 4, "n",
 "O wiadomościach w komunikatorze mówi się „khâw-khwaam”, nie „jòt-mǎai” (to list papierowy).", "odpowiedzieć wiadomość",
 ("Odpowiem wieczorem.", "dǐao tawn yen phǒm tàwp khâw-khwaam ná khráp", "เดี๋ยวตอนเย็นผมตอบข้อความนะครับ")),
("B1", "zadzwonić jeszcze raz", "thoo klàp", "โทรกลับ", "Praca i nauka", "Kontakt", "verb", 4, "n",
 "„thoo klàp” to oddzwonić. Zwykłe „thoo ìik” znaczy tylko „zadzwonić ponownie”.", "dzwonić wracać",
 ("Oddzwonię za pół godziny.", "dǐao khrûeng chûa-mohng phǒm thoo klàp ná khráp", "เดี๋ยวครึ่งชั่วโมงผมโทรกลับนะครับ")),

# =====================================================================
# MYSLENIE, DECYZJE, PAMIEC
# =====================================================================
("A2", "zastanowić się nad czymś", "khít duu kàwn", "คิดดูก่อน", "Czasowniki", "Myślenie", "phrase", 4, "n",
 "Najbezpieczniejszy sposób, żeby nie odpowiedzieć od razu i nikogo nie urazić.", "myśleć zobaczyć najpierw",
 ("Zastanowię się i dam znać.", "phǒm khǎw khít duu kàwn láew jà bàwk khráp", "ผมขอคิดดูก่อนแล้วจะบอกครับ")),
("A2", "przypomnieć sobie", "núek àwk", "นึกออก", "Czasowniki", "Myślenie", "phrase", 4, "n",
 "„núek mâi àwk” = nie mogę sobie przypomnieć. To codzienny zwrot, nie książkowy.", "pomyśleć wyjść",
 ("Nie mogę sobie przypomnieć nazwy.", "phǒm núek chûe mâi àwk khráp", "ผมนึกชื่อไม่ออกครับ")),
("A2", "zapomnieć o czymś", "luem", "ลืม", "Czasowniki", "Myślenie", "verb", 4, "n",
 "Czasownik jest krótki, ale niesie ton opadający — bez niego brzmi jak inne słowo.", "",
 ("Zapomniałem portfela.", "phǒm luem krà-pǎo tang khráp", "ผมลืมกระเป๋าตังค์ครับ")),
("A2", "przypomnieć komuś", "tuean", "เตือน", "Czasowniki", "Myślenie", "verb", 3, "n",
 "Ten sam czasownik znaczy „ostrzec”. Kontekst rozstrzyga, o które chodzi.", "",
 ("Przypomnij mi jutro rano.", "phrûng-níi cháo tuean phǒm dûai ná khráp", "พรุ่งนี้เช้าเตือนผมด้วยนะครับ")),
("B1", "zmienić zdanie", "plìan jai", "เปลี่ยนใจ", "Cechy i opinie", "Decyzje", "phrase", 3, "n",
 "Dosłownie „zmienić serce”. O decyzjach mówi się przez „jai”, nie przez „khwaam khít”.", "zmienić serce",
 ("Zmieniłem zdanie, wolę zostać.", "phǒm plìan jai láew khráp yàak yùu tàw", "ผมเปลี่ยนใจแล้วครับ อยากอยู่ต่อ")),
("B1", "podjąć decyzję", "tàt sǐn jai", "ตัดสินใจ", "Cechy i opinie", "Decyzje", "verb", 4, "n",
 "Dosłownie „odciąć osąd serca”. Standardowe słowo także w piśmie urzędowym.", "ciąć sądzić serce",
 ("Trudno mi podjąć decyzję.", "phǒm tàt sǐn jai yâak khráp", "ผมตัดสินใจยากครับ")),
("B1", "zwrócić na coś uwagę", "sǎng-kèet hěn", "สังเกตเห็น", "Czasowniki", "Myślenie", "phrase", 3, "n",
 "„sǎng-kèet” to obserwować, „hěn” dopiero mówi, że coś zauważyłeś.", "obserwować widzieć",
 ("Zauważyłem, że jest zamknięte.", "phǒm sǎng-kèet hěn wâa pìt yùu khráp", "ผมสังเกตเห็นว่าปิดอยู่ครับ")),

# =====================================================================
# CZYNNOSCI CODZIENNE
# =====================================================================
("A1", "wstawać rano", "tùen nawn", "ตื่นนอน", "Dom i codzienność", "Poranek", "verb", 4, "n",
 "Samo „tùen” znaczy „obudzić się”; z „nawn” brzmi naturalnie jako codzienna czynność.", "budzić się spać",
 ("Wstaję o szóstej.", "phǒm tùen nawn hòk mohng cháo khráp", "ผมตื่นนอนหกโมงเช้าครับ")),
("A1", "kłaść się spać", "khâo nawn", "เข้านอน", "Dom i codzienność", "Wieczór", "verb", 4, "n",
 "„khâo nawn” to iść spać; „nawn làp” to już zasnąć.", "wejść spać",
 ("Kładę się koło jedenastej.", "phǒm khâo nawn prà-maan sìp-èt thûm khráp", "ผมเข้านอนประมาณห้าทุ่มครับ")),
("A1", "brać prysznic", "àap náam", "อาบน้ำ", "Dom i codzienność", "Higiena", "verb", 4, "n",
 "Dosłownie „kąpać wodę”. Tego samego zwrotu używa się o prysznicu i o kąpieli.", "kąpać woda",
 ("Wezmę prysznic i wychodzę.", "phǒm àap náam sèt láew jà àwk khráp", "ผมอาบน้ำเสร็จแล้วจะออกครับ")),
("A1", "myć zęby", "praeng fan", "แปรงฟัน", "Dom i codzienność", "Higiena", "verb", 3, "n",
 "„praeng” to zarówno szczotka, jak i czynność szczotkowania.", "szczotkować zęby",
 ("Muszę jeszcze umyć zęby.", "phǒm tâwng praeng fan kàwn khráp", "ผมต้องแปรงฟันก่อนครับ")),
("A1", "prać ubrania", "sák phâa", "ซักผ้า", "Dom i codzienność", "Porządki", "verb", 3, "n",
 "„sák” dotyczy tylko tkanin. Naczynia myje się „láang”.", "prać tkanina",
 ("Gdzie mogę zrobić pranie?", "sák phâa dâai thîi nǎi khráp", "ซักผ้าได้ที่ไหนครับ")),
("A1", "zmywać naczynia", "láang jaan", "ล้างจาน", "Dom i codzienność", "Porządki", "verb", 3, "n",
 "„láang” to myć wodą — naczynia, ręce, samochód.", "myć talerz",
 ("Pozmywam po kolacji.", "kin khâo yen sèt láew phǒm láang jaan khráp", "กินข้าวเย็นเสร็จแล้วผมล้างจานครับ")),
("A1", "sprzątać pokój", "tham khwaam sà-àat", "ทำความสะอาด", "Dom i codzienność", "Porządki", "verb", 3, "n",
 "Dosłownie „robić czystość”. Konstrukcja „tham khwaam …” tworzy wiele rzeczowników czynnościowych.", "robić czystość",
 ("Sprzątam w niedzielę.", "phǒm tham khwaam sà-àat wan aa-thít khráp", "ผมทำความสะอาดวันอาทิตย์ครับ")),
("A2", "wyrzucić śmieci", "thíng khà-yà", "ทิ้งขยะ", "Dom i codzienność", "Porządki", "verb", 3, "n",
 "„thíng” znaczy też porzucić kogoś — w rozmowie o ludziach używaj ostrożnie.", "wyrzucić śmieci",
 ("Gdzie wyrzuca się śmieci?", "thíng khà-yà thîi nǎi khráp", "ทิ้งขยะที่ไหนครับ")),
("A2", "naładować telefon", "châat thoo-rá-sàp", "ชาร์จโทรศัพท์", "Dom i codzienność", "Technika", "verb", 4, "n",
 "„châat” to zapożyczenie z angielskiego, w mowie potocznej powszechne.", "ładować telefon",
 ("Gdzie mogę naładować telefon?", "châat thoo-rá-sàp dâai thîi nǎi khráp", "ชาร์จโทรศัพท์ได้ที่ไหนครับ")),
("A2", "podłączyć się do wi-fi", "tàw wai-fai", "ต่อไวไฟ", "Dom i codzienność", "Technika", "phrase", 4, "n",
 "„tàw” to połączyć, przedłużyć, kontynuować — jeden z najbardziej wieloznacznych tajskich czasowników.", "łączyć wi-fi",
 ("Jak podłączyć się do wi-fi?", "tàw wai-fai yang-ngai khráp", "ต่อไวไฟยังไงครับ")),
("A2", "wyłączyć klimatyzację", "pìt ae", "ปิดแอร์", "Hotel", "Pokój", "verb", 4, "n",
 "„pìt” to zamknąć i wyłączyć; „pòet” to otworzyć i włączyć. Ta para działa na wszystkie urządzenia.", "zamknąć klimatyzacja",
 ("Proszę wyłączyć klimatyzację.", "chûai pìt ae nòi khráp", "ช่วยปิดแอร์หน่อยครับ")),

# =====================================================================
# PROBA, PROBOWANIE, UDAWANIE SIE
# =====================================================================
("A2", "spróbować czegoś zrobić", "lawng tham duu", "ลองทำดู", "Czasowniki", "Próba", "phrase", 4, "n",
 "„lawng … duu” to najczęstsza konstrukcja próby. Sam „lawng” brzmi niedokończenie.", "próbować robić zobaczyć",
 ("Spróbuję to zrobić sam.", "phǒm jà lawng tham duu eeng khráp", "ผมจะลองทำดูเองครับ")),
("A2", "przymierzyć", "lawng sài duu", "ลองใส่ดู", "Zakupy i pieniądze", "Ubrania", "phrase", 4, "n",
 "W sklepie odzieżowym ta konstrukcja jest standardem: „khǎw lawng sài duu”.", "próbować włożyć zobaczyć",
 ("Mogę przymierzyć?", "khǎw lawng sài duu dâai mǎi khráp", "ขอลองใส่ดูได้ไหมครับ")),
("A2", "udało się", "tham dâai láew", "ทำได้แล้ว", "Czasowniki", "Próba", "phrase", 4, "n",
 "„dâai” po czasowniku oznacza zdolność albo powodzenie, „láew” domyka czynność.", "robić móc już",
 ("Udało się, dziękuję!", "tham dâai láew khràp khàwp khun khráp", "ทำได้แล้วครับ ขอบคุณครับ")),
("A2", "nie udało się", "tham mâi dâai", "ทำไม่ได้", "Czasowniki", "Próba", "phrase", 4, "n",
 "Przeczenie wchodzi między czasownik a „dâai”, nie przed czasownik.", "robić nie móc",
 ("Nie udało mi się tego otworzyć.", "phǒm pòet mâi dâai khráp", "ผมเปิดไม่ได้ครับ")),
("B1", "zdążyć na coś", "than", "ทัน", "Czas i daty", "Punktualność", "verb", 4, "n",
 "„than” to jeden z najużyteczniejszych krótkich czasowników: zdążyć, nadążyć, dogonić.", "",
 ("Zdążę na ostatni pociąg.", "phǒm than rót fai khà-buan sùt tháai khráp", "ผมทันรถไฟขบวนสุดท้ายครับ")),
("B1", "nie zdążyć", "mâi than", "ไม่ทัน", "Czas i daty", "Punktualność", "phrase", 4, "n",
 "Zwrot używany zarówno o spóźnieniu, jak i o niezrozumieniu zbyt szybkiej wypowiedzi.", "nie zdążyć",
 ("Nie zdążyłem, przepraszam.", "phǒm maa mâi than khǎw-thôot khráp", "ผมมาไม่ทัน ขอโทษครับ")),
("B1", "dać radę", "wǎai", "ไหว", "Czasowniki", "Możliwość", "verb", 4, "n",
 "„wǎai” dotyczy sił i wytrzymałości, „dâai” — umiejętności i pozwolenia. To rozróżnienie sprawia Polakom kłopot.", "",
 ("Nie dam rady dziś dłużej pracować.", "wan níi phǒm tham tàw mâi wǎai khráp", "วันนี้ผมทำต่อไม่ไหวครับ")),

# =====================================================================
# POMAGANIE I OBSLUGA
# =====================================================================
("A1", "pomóc komuś", "chûai", "ช่วย", "Podstawy i grzeczność", "Prośby", "verb", 5, "n",
 "„chûai” zaczyna niemal każdą uprzejmą prośbę i jednocześnie znaczy „ratunku”.", "",
 ("Może mi pan pomóc?", "chûai phǒm nòi dâai mǎi khráp", "ช่วยผมหน่อยได้ไหมครับ")),
("A2", "poczekać chwilę", "raw sák khrûu", "รอสักครู่", "Podstawy i grzeczność", "Prośby", "phrase", 5, "f",
 "Wersja formalna. Potocznie mówi się „raw dǐao”.", "czekać chwilę",
 ("Proszę chwilę poczekać.", "rá-bòp kam-lang tham ngaan khráp raw sák khrûu ná khráp", "ระบบกำลังทำงานครับ รอสักครู่นะครับ")),
("A2", "sprawdzić coś", "chék hâi", "เช็คให้", "Praca i nauka", "Obsługa", "phrase", 4, "n",
 "„chék” zapożyczone z angielskiego wyparło w mowie „trùat sàwp”, które zostało w piśmie.", "sprawdzić dać",
 ("Sprawdzę to dla pana.", "dǐao phǒm chék hâi ná khráp", "เดี๋ยวผมเช็คให้นะครับ")),
("B1", "załatwić sprawę", "jàt kaan hâi", "จัดการให้", "Praca i nauka", "Obsługa", "phrase", 4, "n",
 "„jàt kaan” to zająć się czymś i doprowadzić do końca — mocniejsze niż „tham”.", "zarządzić dać",
 ("Załatwię to do jutra.", "phǒm jà jàt kaan hâi phrûng-níi khráp", "ผมจะจัดการให้พรุ่งนี้ครับ")),
("B1", "zająć się kimś", "duu lae", "ดูแล", "Zdrowie", "Opieka", "verb", 4, "n",
 "Dosłownie „patrzeć i doglądać”. Dotyczy opieki nad ludźmi, zwierzętami i sprawami.", "patrzeć doglądać",
 ("Kto się nią opiekuje?", "khrai duu lae khǎo khráp", "ใครดูแลเขาครับ")),
("A2", "zamówić coś", "sàng", "สั่ง", "Restauracja", "Zamawianie", "verb", 5, "n",
 "Ten sam czasownik znaczy „rozkazać”. W restauracji zawsze dodawaj „khráp/khâ”.", "",
 ("Zamówiliśmy już.", "raw sàng láew khráp", "เราสั่งแล้วครับ")),
("A2", "zapłacić za coś", "jàai hâi", "จ่ายให้", "Zakupy i pieniądze", "Płatności", "phrase", 4, "n",
 "„jàai hâi” znaczy „zapłacić za kogoś” — częsty gest przy wspólnym posiłku.", "płacić dać",
 ("Dziś ja płacę.", "wan níi phǒm jàai hâi eeng khráp", "วันนี้ผมจ่ายให้เองครับ")),

# =====================================================================
# CZASOWNIKI STANU I ODCZUCIA
# =====================================================================
("A2", "czuć się dobrze", "sà-baai dii", "สบายดี", "Zdrowie", "Samopoczucie", "phrase", 5, "n",
 "To samo wyrażenie odpowiada na „jak się masz” i opisuje dobre samopoczucie.", "wygodnie dobrze",
 ("Czuję się już dobrze.", "tawn níi phǒm sà-baai dii láew khráp", "ตอนนี้ผมสบายดีแล้วครับ")),
("A2", "źle się czuć", "mâi sà-baai", "ไม่สบาย", "Zdrowie", "Samopoczucie", "phrase", 5, "n",
 "„mâi sà-baai” znaczy zarówno „źle się czuję”, jak i „jestem chory”. Tajski nie rozdziela tych stanów.", "nie wygodnie",
 ("Źle się dziś czuję.", "wan níi phǒm mâi sà-baai khráp", "วันนี้ผมไม่สบายครับ")),
("A2", "być zmęczonym", "nùeai", "เหนื่อย", "Zdrowie", "Samopoczucie", "adjective", 4, "n",
 "„nùeai” to zmęczenie fizyczne. Zmęczenie psychiczne to „bùea” albo „khrîat”.", "",
 ("Jestem bardzo zmęczony.", "phǒm nùeai mâak khráp", "ผมเหนื่อยมากครับ")),
("A2", "być głodnym", "hǐu khâo", "หิวข้าว", "Jedzenie i napoje", "Głód", "phrase", 4, "n",
 "„khâo” to ryż, ale w tym zwrocie znaczy po prostu jedzenie.", "głodny ryż",
 ("Jestem głodny, chodźmy coś zjeść.", "phǒm hǐu khâo láew pai kin kan thòe", "ผมหิวข้าวแล้ว ไปกินกันเถอะ")),
("A2", "być spragnionym", "hǐu náam", "หิวน้ำ", "Jedzenie i napoje", "Pragnienie", "phrase", 4, "n",
 "Ten sam czasownik „hǐu” obsługuje głód i pragnienie — różni je tylko rzeczownik.", "głodny woda",
 ("Chce mi się pić.", "phǒm hǐu náam khráp", "ผมหิวน้ำครับ")),
("B1", "denerwować się czymś", "kang-won", "กังวล", "Cechy i opinie", "Emocje", "verb", 3, "n",
 "„kang-won” to martwić się o coś przyszłego. Złość to „kròot”, zdenerwowanie przed występem to „tùen tên”.", "",
 ("Martwię się o wynik badań.", "phǒm kang-won rûeang phǒn trùat khráp", "ผมกังวลเรื่องผลตรวจครับ")),
("B1", "cieszyć się z czegoś", "dii jai", "ดีใจ", "Cechy i opinie", "Emocje", "adjective", 4, "n",
 "Dosłownie „dobre serce”. Rodzina wyrażeń z „jai” to klucz do mówienia o emocjach po tajsku.", "dobre serce",
 ("Cieszę się, że się udało.", "dii jai dûai ná khráp thîi sǎm-rèt", "ดีใจด้วยนะครับที่สำเร็จ")),
("B1", "być rozczarowanym", "phìt wǎng", "ผิดหวัง", "Cechy i opinie", "Emocje", "adjective", 3, "n",
 "Dosłownie „błędna nadzieja”. Mocne słowo — wobec obsługi lepiej użyć łagodniejszego „nòi jai”.", "błąd nadzieja",
 ("Jestem trochę rozczarowany.", "phǒm phìt wǎng nít nùeng khráp", "ผมผิดหวังนิดหนึ่งครับ")),
("B1", "poczuć ulgę", "long jai", "โล่งใจ", "Cechy i opinie", "Emocje", "adjective", 3, "n",
 "„long” to pusty, przestronny — ulga po tajsku to serce, w którym zrobiło się miejsce.", "przestronne serce",
 ("Odetchnąłem z ulgą.", "phǒm long jai loei khráp", "ผมโล่งใจเลยครับ")),

# =====================================================================
# ZACZYNANIE, KONCZENIE, TRWANIE
# =====================================================================
("A2", "zacząć coś robić", "rôoem", "เริ่ม", "Czasowniki", "Przebieg", "verb", 4, "n",
 "„rôoem” stoi przed czasownikiem głównym, bez żadnej partykuły łączącej.", "",
 ("Zaczynamy o dziewiątej.", "raw rôoem kâo mohng cháo khráp", "เราเริ่มเก้าโมงเช้าครับ")),
("A2", "skończyć coś", "sèt", "เสร็จ", "Czasowniki", "Przebieg", "verb", 5, "n",
 "„sèt” idzie PO czasowniku: „kin sèt láew” = skończyłem jeść.", "",
 ("Już skończyłem.", "phǒm sèt láew khráp", "ผมเสร็จแล้วครับ")),
("A2", "przerwać na chwilę", "phák kàwn", "พักก่อน", "Czasowniki", "Przebieg", "phrase", 3, "n",
 "„phák” to przerwa i odpoczynek; „phák kàwn” proponuje pauzę tu i teraz.", "odpocząć najpierw",
 ("Zróbmy przerwę.", "phák kàwn dii kwàa khráp", "พักก่อนดีกว่าครับ")),
("B1", "kontynuować", "tham tàw", "ทำต่อ", "Czasowniki", "Przebieg", "phrase", 3, "n",
 "„tàw” po czasowniku znaczy „dalej”. Działa z każdym czasownikiem czynnościowym.", "robić dalej",
 ("Kontynuujmy jutro.", "phrûng-níi raw tham tàw ná khráp", "พรุ่งนี้เราทำต่อนะครับ")),
("B1", "odłożyć na później", "lûean àwk pai", "เลื่อนออกไป", "Praca i nauka", "Terminy", "phrase", 3, "n",
 "„lûean” to przesunąć termin. Dotyczy spotkań, lotów i wizyt lekarskich.", "przesunąć wyjść iść",
 ("Przesuńmy spotkanie na przyszły tydzień.", "lûean nát àwk pai aa-thít nâa dâai mǎi khráp", "เลื่อนนัดออกไปอาทิตย์หน้าได้ไหมครับ")),
("B1", "odwołać coś", "yók lôek", "ยกเลิก", "Praca i nauka", "Terminy", "verb", 4, "n",
 "Standardowe słowo przy rezerwacjach, biletach i umowach.", "podnieść skończyć",
 ("Chciałbym odwołać rezerwację.", "khǎw yók lôek kaan jawng khráp", "ขอยกเลิกการจองครับ")),

# =====================================================================
# SZUKANIE, ZNAJDOWANIE, GUBIENIE
# =====================================================================
("A2", "szukać czegoś", "hǎa", "หา", "Czasowniki", "Szukanie", "verb", 5, "n",
 "„hǎa” znaczy szukać, ale też „odwiedzić kogoś”: „pai hǎa phûean”.", "",
 ("Szukam apteki.", "phǒm hǎa ráan khǎai yaa yùu khráp", "ผมหาร้านขายยาอยู่ครับ")),
("A2", "znaleźć coś", "jooe", "เจอ", "Czasowniki", "Szukanie", "verb", 5, "n",
 "„jooe” to znaleźć i spotkać. „hǎa mâi jooe” = szukałem i nie znalazłem.", "",
 ("Nie mogę znaleźć kluczy.", "phǒm hǎa kun-jae mâi jooe khráp", "ผมหากุญแจไม่เจอครับ")),
("A2", "zgubić coś", "tham hǎai", "ทำหาย", "Awarie i pomoc", "Zguby", "phrase", 4, "n",
 "„tham … hǎai” znaczy „spowodować zniknięcie” — to konstrukcja sprawcza, nie zwykły czasownik.", "robić zniknąć",
 ("Zgubiłem paszport.", "phǒm tham nǎng-sǔe doen thaang hǎai khráp", "ผมทำหนังสือเดินทางหายครับ")),
("B1", "zgłosić zgubę", "jâeng khwaam", "แจ้งความ", "Awarie i pomoc", "Policja", "phrase", 3, "f",
 "To formalne zgłoszenie na policji, potrzebne do ubezpieczenia i do nowego paszportu.", "zgłosić sprawę",
 ("Muszę zgłosić to na policji.", "phǒm tâwng pai jâeng khwaam thîi sà-thǎa-nii tam-rùat khráp", "ผมต้องไปแจ้งความที่สถานีตำรวจครับ")),
("B1", "odzyskać coś", "dâai khuen", "ได้คืน", "Awarie i pomoc", "Zguby", "phrase", 3, "n",
 "„dâai khuen” = dostać z powrotem. Dotyczy rzeczy i pieniędzy.", "dostać z powrotem",
 ("Odzyskałem telefon.", "phǒm dâai thoo-rá-sàp khuen láew khráp", "ผมได้โทรศัพท์คืนแล้วครับ")),

# =====================================================================
# CZASOWNIKI Z „JAI” — SERCE JAKO SIEDZIBA EMOCJI
# =====================================================================
("B1", "zrozumieć kogoś", "khâo jai", "เข้าใจ", "Czasowniki", "Serce", "verb", 5, "n",
 "Dosłownie „wejść w serce”. To najczęstszy tajski czasownik z „jai”.", "wejść serce",
 ("Rozumiem pana.", "phǒm khâo jai khun khráp", "ผมเข้าใจคุณครับ")),
("B1", "mieć do kogoś żal", "nòi jai", "น้อยใจ", "Cechy i opinie", "Serce", "verb", 3, "n",
 "Bardzo tajska emocja: nie złość, tylko poczucie, że zostało się pominiętym. Nie ma dobrego polskiego odpowiednika.", "mało serce",
 ("Trochę mi przykro, że nie zadzwoniłeś.", "phǒm nòi jai nít nùeng thîi mâi thoo maa", "ผมน้อยใจนิดหนึ่งที่ไม่โทรมา")),
("B1", "uspokoić się", "jai yen yen", "ใจเย็นๆ", "Cechy i opinie", "Serce", "phrase", 4, "n",
 "Dosłownie „chłodne serce”. Podwojenie „yen yen” zmienia rozkaz w łagodną prośbę.", "serce chłodne",
 ("Spokojnie, zdążymy.", "jai yen yen ná khráp raw than", "ใจเย็นๆ นะครับ เราทัน")),
("B1", "być hojnym, wielkodusznym", "jai dii", "ใจดี", "Cechy i opinie", "Serce", "adjective", 4, "n",
 "„jai dii” to komplement pod adresem czyjegoś charakteru, nie chwilowego nastroju.", "serce dobre",
 ("Ona jest bardzo dobra dla ludzi.", "khǎo jai dii mâak khráp", "เขาใจดีมากครับ")),
("B1", "stracić cierpliwość", "jai ráwn", "ใจร้อน", "Cechy i opinie", "Serce", "adjective", 3, "n",
 "Przeciwieństwo „jai yen”. Powiedziane o kimś, brzmi jak łagodny zarzut.", "serce gorące",
 ("Nie bądź taki niecierpliwy.", "yàa jai ráwn sì khráp", "อย่าใจร้อนสิครับ")),
("B1", "poczuć się urażonym", "sǐa jai", "เสียใจ", "Cechy i opinie", "Serce", "adjective", 4, "n",
 "„sǐa jai” to smutek i żal — także formuła kondolencji.", "stracić serce",
 ("Bardzo mi przykro z tego powodu.", "phǒm sǐa jai dûai khráp", "ผมเสียใจด้วยครับ")),
("B1", "odważyć się", "klâa", "กล้า", "Cechy i opinie", "Charakter", "verb", 3, "n",
 "„mâi klâa” = nie mieć śmiałości. Zwrot bardzo częsty przy mówieniu w obcym języku.", "",
 ("Nie miałem odwagi zapytać.", "phǒm mâi klâa thǎam khráp", "ผมไม่กล้าถามครับ")),
]
