# -*- coding: utf-8 -*-
"""Wzorce zdaniowe etapu 5 (B2) — czesc B: konstrukcje przymiotnikowe.

Konstrukcje dobrane tak, zeby nie powielaly wzorcow z poziomow nizszych.
Zuzyte juz: „kwàa”, „thîi sùt”, „koen pai”, „mâak loei”, „nít nòi”, „khûen”,
„long”, „phaw dii”, „thǔe wâa khâwn khâang”, „yîng … yîng”.

Etap 5: stopniowanie z dystansem, porownanie z oczekiwaniem spolecznym,
zaprzeczenie obiegowej opinii, ocena wystarczalnosci, tendencja w czasie.

Pozycja: (polskie haslo rekordu, polskie haslo bazowe, polski przyklad)
"""

TPL_B = [

# =====================================================================
# man khawn khaang ja … pai noi — ostrozne stopniowanie
# =====================================================================
dict(key="KHONKHANG", ty="sentence", cat="Cechy i opinie", sub="Łagodzenie", reg="f",
     ph="man khâwn khâang jà {ph} pai nòi khráp", th="มันค่อนข้างจะ{th}ไปหน่อยครับ",
     lit="khâwn khâang jà … pai nòi = raczej odrobinę zbyt …",
     note="Podwójne złagodzenie: „khâwn khâang” plus „pai nòi”. Tak Taj krytykuje, nie raniąc rozmówcy.",
     ex_ph="mâi khít wâa man khâwn khâang jà {ph} pai nòi rǒe khráp", ex_th="ไม่คิดว่ามันค่อนข้างจะ{th}ไปหน่อยหรือครับ",
     items=[
       ("To raczej odrobinę za drogie.", "drogi", "Nie sądzisz, że to trochę za drogie?"),
       ("To raczej odrobinę za ostre.", "ostry (pikantny)", "Nie sądzisz, że to trochę za ostre?"),
       ("To raczej odrobinę za słone.", "słony", "Nie sądzisz, że to trochę za słone?"),
       ("To raczej odrobinę za słodkie.", "słodki", "Nie sądzisz, że to trochę za słodkie?"),
       ("To raczej odrobinę za kwaśne.", "kwaśny", "Nie sądzisz, że to trochę za kwaśne?"),
       ("To raczej odrobinę za gorzkie.", "gorzki", "Nie sądzisz, że to trochę za gorzkie?"),
       ("To raczej odrobinę za duże.", "duży", "Nie sądzisz, że to trochę za duże?"),
       ("To raczej odrobinę za małe.", "mały", "Nie sądzisz, że to trochę za małe?"),
       ("To raczej odrobinę za długie.", "długi", "Nie sądzisz, że to trochę za długie?"),
       ("To raczej odrobinę za krótkie.", "krótki", "Nie sądzisz, że to trochę za krótkie?"),
       ("To raczej odrobinę za ciężkie.", "ciężki", "Nie sądzisz, że to trochę za ciężkie?"),
       ("To raczej odrobinę za głośne.", "głośny", "Nie sądzisz, że to trochę za głośne?"),
       ("To raczej odrobinę za jasne.", "jasny", "Nie sądzisz, że to trochę za jasne?"),
       ("To raczej odrobinę za ciemne.", "ciemny", "Nie sądzisz, że to trochę za ciemne?"),
       ("To raczej odrobinę za twarde.", "twardy", "Nie sądzisz, że to trochę za twarde?"),
       ("To raczej odrobinę za miękkie.", "miękki", "Nie sądzisz, że to trochę za miękkie?"),
       ("To raczej odrobinę za szybkie.", "szybki", "Nie sądzisz, że to trochę za szybkie?"),
       ("To raczej odrobinę za wolne.", "wolny (powolny)", "Nie sądzisz, że to trochę za wolne?"),
       ("To raczej odrobinę za daleko.", "daleki", "Nie sądzisz, że to trochę za daleko?"),
       ("To raczej odrobinę za blisko.", "bliski", "Nie sądzisz, że to trochę za blisko?"),
       ("To raczej odrobinę za trudne.", "trudny", "Nie sądzisz, że to trochę za trudne?"),
       ("To raczej odrobinę za łatwe.", "łatwy", "Nie sądzisz, że to trochę za łatwe?"),
       ("To raczej odrobinę za nowe jak na ten cel.", "nowy", "Nie sądzisz, że to trochę za nowe?"),
       ("To raczej odrobinę za stare.", "stary", "Nie sądzisz, że to trochę za stare?"),
       ("To raczej odrobinę za brudne.", "brudny", "Nie sądzisz, że to trochę za brudne?"),
       ("To raczej odrobinę za gorące.", "gorący", "Nie sądzisz, że to trochę za gorące?"),
       ("To raczej odrobinę za wysokie.", "wysoki", "Nie sądzisz, że to trochę za wysokie?"),
       ("To raczej odrobinę za tanie, aż podejrzanie.", "tani", "Nie sądzisz, że to podejrzanie tanie?"),
       ("To raczej odrobinę za mocne.", "silny, mocny", "Nie sądzisz, że to trochę za mocne?"),
       ("To raczej odrobinę za słabe.", "słaby", "Nie sądzisz, że to trochę za słabe?"),
       ("To raczej odrobinę za nudne.", "nudny", "Nie sądzisz, że to trochę nudne?"),
       ("To raczej odrobinę za ryzykowne.", "niebezpieczny", "Nie sądzisz, że to trochę ryzykowne?"),
       ("To raczej odrobinę za głębokie.", "głęboki", "Nie sądzisz, że to trochę za głębokie?"),
       ("To raczej odrobinę za tłuste.", "tłusty", "Nie sądzisz, że to trochę za tłuste?"),
       ("To raczej odrobinę za pełne jak na tę porę.", "pełny / zajęty", "Nie sądzisz, że tu trochę za tłoczno?"),
       ("To raczej odrobinę za puste jak na weekend.", "pusty", "Nie sądzisz, że tu trochę za pusto?"),
     ]),

# =====================================================================
# … ying kwaa iik — jeszcze bardziej
# =====================================================================
dict(key="YIINGKWAA", ty="sentence", cat="Cechy i opinie", sub="Porównania", reg="n",
     ph="an níi {ph} yîng kwàa ìik khráp", th="อันนี้{th}ยิ่งกว่าอีกครับ",
     lit="yîng kwàa ìik = jeszcze bardziej niż tamto",
     note="Mocniejsze niż zwykłe „kwàa”. Używaj, gdy porównujesz z czymś już skrajnym.",
     ex_ph="an nǎi {ph} yîng kwàa kan khráp", ex_th="อันไหน{th}ยิ่งกว่ากันครับ",
     items=[
       ("Ten jest jeszcze droższy.", "drogi", "Który jest jeszcze droższy?"),
       ("Ten jest jeszcze tańszy.", "tani", "Który jest jeszcze tańszy?"),
       ("Ten jest jeszcze większy.", "duży", "Który jest jeszcze większy?"),
       ("Ten jest jeszcze mniejszy.", "mały", "Który jest jeszcze mniejszy?"),
       ("Ten jest jeszcze ostrzejszy.", "ostry (pikantny)", "Który jest jeszcze ostrzejszy?"),
       ("Ten jest jeszcze smaczniejszy.", "smaczny", "Który jest jeszcze smaczniejszy?"),
       ("Ten jest jeszcze szybszy.", "szybki", "Który jest jeszcze szybszy?"),
       ("Ten jest jeszcze wolniejszy.", "wolny (powolny)", "Który jest jeszcze wolniejszy?"),
       ("Ten jest jeszcze ładniejszy.", "ładny", "Który jest jeszcze ładniejszy?"),
       ("Ten jest jeszcze trudniejszy.", "trudny", "Który jest jeszcze trudniejszy?"),
       ("Ten jest jeszcze łatwiejszy.", "łatwy", "Który jest jeszcze łatwiejszy?"),
       ("Ten jest jeszcze cięższy.", "ciężki", "Który jest jeszcze cięższy?"),
       ("Ten jest jeszcze lżejszy.", "lekki", "Który jest jeszcze lżejszy?"),
       ("Ten jest jeszcze dłuższy.", "długi", "Który jest jeszcze dłuższy?"),
       ("Ten jest jeszcze krótszy.", "krótki", "Który jest jeszcze krótszy?"),
       ("Ten jest jeszcze czystszy.", "czysty", "Który jest jeszcze czystszy?"),
       ("Ten jest jeszcze wygodniejszy.", "wygodny", "Który jest jeszcze wygodniejszy?"),
       ("Ten jest jeszcze bezpieczniejszy.", "bezpieczny", "Który jest jeszcze bezpieczniejszy?"),
       ("Ten jest jeszcze ciekawszy.", "interesujący", "Który jest jeszcze ciekawszy?"),
       ("Ten jest jeszcze nudniejszy.", "nudny", "Który jest jeszcze nudniejszy?"),
       ("Ten jest jeszcze mocniejszy.", "silny, mocny", "Który jest jeszcze mocniejszy?"),
       ("Ten jest jeszcze świeższy.", "świeży", "Który jest jeszcze świeższy?"),
       ("Ten jest jeszcze głośniejszy.", "głośny", "Który jest jeszcze głośniejszy?"),
       ("Ten jest jeszcze cichszy.", "cichy / spokojny", "Który jest jeszcze cichszy?"),
       ("Ten jest jeszcze wyższy.", "wysoki", "Który jest jeszcze wyższy?"),
       ("Ten jest jeszcze grubszy.", "gruby", "Który jest jeszcze grubszy?"),
       ("Ten jest jeszcze bardziej stromy i głęboki.", "głęboki", "Który jest jeszcze głębszy?"),
       ("Ten jest jeszcze bardziej dojrzały.", "dojrzały", "Który jest jeszcze bardziej dojrzały?"),
       ("Ten jest jeszcze bardziej słony.", "słony", "Który jest jeszcze bardziej słony?"),
       ("Ten jest jeszcze bardziej słodki.", "słodki", "Który jest jeszcze słodszy?"),
       ("Ten jest jeszcze bardziej tłusty.", "tłusty", "Który jest jeszcze bardziej tłusty?"),
       ("Ten jest jeszcze bardziej chrupiący.", "chrupiący", "Który jest jeszcze bardziej chrupiący?"),
       ("Ten jest jeszcze ważniejszy.", "ważny", "Który jest jeszcze ważniejszy?"),
       ("Ten jest jeszcze bardziej ryzykowny.", "niebezpieczny", "Który jest jeszcze bardziej ryzykowny?"),
       ("Ten jest jeszcze bardziej zniszczony.", "brudny", "Który jest jeszcze bardziej zniszczony?"),
       ("Ten jest jeszcze bardziej zatłoczony.", "pełny / zajęty", "Który jest jeszcze bardziej zatłoczony?"),
     ]),

# =====================================================================
# mai khit waa man ja … khanaat nii — zawiedzione oczekiwanie
# =====================================================================
dict(key="KHANAATNII", ty="sentence", cat="Cechy i opinie", sub="Zaskoczenie", reg="n",
     ph="mâi khít wâa man jà {ph} khà-nàat níi khráp", th="ไม่คิดว่ามันจะ{th}ขนาดนี้ครับ",
     lit="khà-nàat níi = aż w takim stopniu",
     note="„khà-nàat níi” to miara zaskoczenia. Działa i przy zachwycie, i przy rozczarowaniu — decyduje ton głosu.",
     ex_ph="khun kâw mâi khít wâa man jà {ph} khà-nàat níi mǔean kan rǒe khráp", ex_th="คุณก็ไม่คิดว่ามันจะ{th}ขนาดนี้เหมือนกันหรือครับ",
     items=[
       ("Nie sądziłem, że będzie aż tak drogo.", "drogi", "Ty też się nie spodziewałeś takiej ceny?"),
       ("Nie sądziłem, że będzie aż tak tanio.", "tani", "Ty też się nie spodziewałeś takiej ceny?"),
       ("Nie sądziłem, że będzie aż tak gorąco.", "gorący", "Ty też się nie spodziewałeś takiego upału?"),
       ("Nie sądziłem, że będzie aż tak zimno.", "zimno (o pogodzie)", "Ty też się nie spodziewałeś takiego chłodu?"),
       ("Nie sądziłem, że będzie aż tak ostro.", "ostry (pikantny)", "Ty też się nie spodziewałeś takiej ostrości?"),
       ("Nie sądziłem, że będzie aż tak smacznie.", "smaczny", "Ty też się nie spodziewałeś, że tak smaczne?"),
       ("Nie sądziłem, że będzie aż tak głośno.", "głośny", "Ty też się nie spodziewałeś takiego hałasu?"),
       ("Nie sądziłem, że będzie aż tak cicho.", "cichy / spokojny", "Ty też się nie spodziewałeś takiej ciszy?"),
       ("Nie sądziłem, że będzie aż tak daleko.", "daleki", "Ty też się nie spodziewałeś takiej odległości?"),
       ("Nie sądziłem, że będzie aż tak blisko.", "bliski", "Ty też się nie spodziewałeś, że tak blisko?"),
       ("Nie sądziłem, że będzie aż tak trudno.", "trudny", "Ty też się nie spodziewałeś takich trudności?"),
       ("Nie sądziłem, że będzie aż tak łatwo.", "łatwy", "Ty też się nie spodziewałeś, że tak łatwo?"),
       ("Nie sądziłem, że będzie aż tak brudno.", "brudny", "Ty też się nie spodziewałeś takiego brudu?"),
       ("Nie sądziłem, że będzie aż tak czysto.", "czysty", "Ty też się nie spodziewałeś takiej czystości?"),
       ("Nie sądziłem, że będzie aż tak tłoczno.", "pełny / zajęty", "Ty też się nie spodziewałeś tłumu?"),
       ("Nie sądziłem, że będzie aż tak pusto.", "pusty", "Ty też się nie spodziewałeś pustek?"),
       ("Nie sądziłem, że będzie aż tak nudno.", "nudny", "Ty też się nie spodziewałeś takiej nudy?"),
       ("Nie sądziłem, że będzie aż tak ciekawie.", "interesujący", "Ty też się nie spodziewałeś, że tak ciekawie?"),
       ("Nie sądziłem, że będzie aż tak ciężko.", "ciężki", "Ty też się nie spodziewałeś takiego ciężaru?"),
       ("Nie sądziłem, że będzie aż tak męcząco.", "zmęczony", "Ty też się nie spodziewałeś takiego zmęczenia?"),
       ("Nie sądziłem, że będzie aż tak stresująco.", "zestresowany", "Ty też się nie spodziewałeś takiego stresu?"),
       ("Nie sądziłem, że będzie aż tak ładnie.", "ładny", "Ty też się nie spodziewałeś, że tak ładnie?"),
       ("Nie sądziłem, że będzie aż tak duże.", "duży", "Ty też się nie spodziewałeś takiego rozmiaru?"),
       ("Nie sądziłem, że będzie aż tak małe.", "mały", "Ty też się nie spodziewałeś, że tak małe?"),
       ("Nie sądziłem, że będzie aż tak wolno.", "wolny (powolny)", "Ty też się nie spodziewałeś, że tak wolno?"),
       ("Nie sądziłem, że będzie aż tak szybko.", "szybki", "Ty też się nie spodziewałeś, że tak szybko?"),
       ("Nie sądziłem, że będzie aż tak niebezpiecznie.", "niebezpieczny", "Ty też się nie spodziewałeś ryzyka?"),
       ("Nie sądziłem, że będzie aż tak wygodnie.", "wygodny", "Ty też się nie spodziewałeś takiej wygody?"),
       ("Nie sądziłem, że będzie aż tak twardo.", "twardy", "Ty też się nie spodziewałeś, że tak twarde?"),
       ("Nie sądziłem, że będzie aż tak mocne.", "silny, mocny", "Ty też się nie spodziewałeś, że tak mocne?"),
       ("Nie sądziłem, że będzie aż tak słabe.", "słaby", "Ty też się nie spodziewałeś, że tak słabe?"),
       ("Nie sądziłem, że będzie aż tak świeże.", "świeży", "Ty też się nie spodziewałeś takiej świeżości?"),
       ("Nie sądziłem, że będzie aż tak głęboko.", "głęboki", "Ty też się nie spodziewałeś, że tak głęboko?"),
       ("Nie sądziłem, że będzie aż tak wysoko.", "wysoki", "Ty też się nie spodziewałeś, że tak wysoko?"),
       ("Nie sądziłem, że będzie aż tak zabawnie.", "fajny / zabawny", "Ty też się nie spodziewałeś takiej zabawy?"),
       ("Nie sądziłem, że będzie aż tak spokojnie.", "spokojny, opanowany", "Ty też się nie spodziewałeś takiego spokoju?"),
     ]),

# =====================================================================
# kaw … yuu na khrap taae yang mai phaw — ocena wystarczalnosci
# =====================================================================
dict(key="YANGMAIPHAW", ty="sentence", cat="Cechy i opinie", sub="Ocena", reg="n",
     ph="kâw {ph} yùu ná khráp tàae yang mâi phaw", th="ก็{th}อยู่นะครับ แต่ยังไม่พอ",
     lit="kâw … yùu … tàae yang mâi phaw = jest to jakieś tam …, ale wciąż za mało",
     note="Uprzejma ocena niedostateczna: najpierw uznanie, potem zastrzeżenie. Ten sam schemat co przy niezgodzie.",
     ex_ph="tâwng {ph} kwàa níi ìik thâo rài thǔeng jà phaw khráp", ex_th="ต้อง{th}กว่านี้อีกเท่าไหร่ถึงจะพอครับ",
     items=[
       ("Jest niezłe, ale to wciąż za mało.", "dobry", "O ile lepsze musiałoby być, żeby wystarczyło?"),
       ("Jest szybkie, ale to wciąż za mało.", "szybki", "O ile szybsze musiałoby być, żeby wystarczyło?"),
       ("Jest tanie, ale to wciąż za mało.", "tani", "O ile tańsze musiałoby być, żeby wystarczyło?"),
       ("Jest duże, ale to wciąż za mało.", "duży", "O ile większe musiałoby być, żeby wystarczyło?"),
       ("Jest czyste, ale to wciąż za mało.", "czysty", "O ile czystsze musiałoby być, żeby wystarczyło?"),
       ("Jest mocne, ale to wciąż za mało.", "silny, mocny", "O ile mocniejsze musiałoby być, żeby wystarczyło?"),
       ("Jest jasne, ale to wciąż za mało.", "jasny", "O ile jaśniejsze musiałoby być, żeby wystarczyło?"),
       ("Jest wygodne, ale to wciąż za mało.", "wygodny", "O ile wygodniejsze musiałoby być, żeby wystarczyło?"),
       ("Jest bezpieczne, ale to wciąż za mało.", "bezpieczny", "O ile bezpieczniejsze musiałoby być?"),
       ("Jest ciekawe, ale to wciąż za mało.", "interesujący", "O ile ciekawsze musiałoby być, żeby wystarczyło?"),
       ("Jest świeże, ale to wciąż za mało.", "świeży", "O ile świeższe musiałoby być, żeby wystarczyło?"),
       ("Jest ostre, ale to wciąż za mało.", "ostry (pikantny)", "O ile ostrzejsze musiałoby być, żeby wystarczyło?"),
       ("Jest słodkie, ale to wciąż za mało.", "słodki", "O ile słodsze musiałoby być, żeby wystarczyło?"),
       ("Jest ciepłe, ale to wciąż za mało.", "gorący", "O ile cieplejsze musiałoby być, żeby wystarczyło?"),
       ("Jest długie, ale to wciąż za mało.", "długi", "O ile dłuższe musiałoby być, żeby wystarczyło?"),
       ("Jest wysokie, ale to wciąż za mało.", "wysoki", "O ile wyższe musiałoby być, żeby wystarczyło?"),
       ("Jest lekkie, ale to wciąż za mało.", "lekki", "O ile lżejsze musiałoby być, żeby wystarczyło?"),
       ("Jest miękkie, ale to wciąż za mało.", "miękki", "O ile miększe musiałoby być, żeby wystarczyło?"),
       ("Jest ładne, ale to wciąż za mało.", "ładny", "O ile ładniejsze musiałoby być, żeby wystarczyło?"),
       ("Jest smaczne, ale to wciąż za mało.", "smaczny", "O ile smaczniejsze musiałoby być?"),
       ("Jest ciche, ale to wciąż za mało.", "cichy / spokojny", "O ile cichsze musiałoby być, żeby wystarczyło?"),
       ("Jest bliskie, ale to wciąż za mało.", "bliski", "O ile bliżej musiałoby być, żeby wystarczyło?"),
       ("Jest nowe, ale to wciąż za mało.", "nowy", "O ile nowsze musiałoby być, żeby wystarczyło?"),
       ("Jest proste, ale to wciąż za mało.", "łatwy", "O ile prostsze musiałoby być, żeby wystarczyło?"),
       ("Jest głębokie, ale to wciąż za mało.", "głęboki", "O ile głębsze musiałoby być, żeby wystarczyło?"),
       ("Jest twarde, ale to wciąż za mało.", "twardy", "O ile twardsze musiałoby być, żeby wystarczyło?"),
       ("Jest chrupiące, ale to wciąż za mało.", "chrupiący", "O ile bardziej chrupiące musiałoby być?"),
       ("Jest dojrzałe, ale to wciąż za mało.", "dojrzały", "O ile bardziej dojrzałe musiałoby być?"),
       ("Jest ważne, ale to wciąż za mało.", "ważny", "O ile ważniejsze musiałoby być, żeby wystarczyło?"),
       ("Jest zabawne, ale to wciąż za mało.", "fajny / zabawny", "O ile zabawniejsze musiałoby być?"),
       ("Jest podobne, ale to wciąż za mało.", "podobny", "O ile bardziej podobne musiałoby być?"),
       ("Jest lepsze niż wcześniej, ale to wciąż za mało.", "lepszy", "O ile lepsze musiałoby być, żeby wystarczyło?"),
       ("Jest wystarczające na papierze, ale to wciąż za mało.", "wystarczająco", "Ile jeszcze brakuje, żeby wystarczyło?"),
       ("Jest dokładne, ale to wciąż za mało.", "dokładnie", "O ile dokładniejsze musiałoby być?"),
       ("Jest prawdziwe, ale to wciąż za mało.", "prawdziwy", "Co jeszcze trzeba, żeby to potwierdzić?"),
       ("Jest gotowe w połowie, ale to wciąż za mało.", "pełny / zajęty", "Ile jeszcze brakuje do kompletu?"),
     ]),

# =====================================================================
# man mai dai … yaang thii khon phuut kan — zaprzeczenie obiegowej opinii
# =====================================================================
dict(key="KHONPHUUTKAN", ty="sentence", cat="Cechy i opinie", sub="Argumentacja", reg="n",
     ph="man mâi dâai {ph} yàang thîi khon phûut kan khráp", th="มันไม่ได้{th}อย่างที่คนพูดกันครับ",
     lit="yàang thîi khon phûut kan = tak, jak ludzie mówią",
     note="Podważenie obiegowej opinii bez atakowania rozmówcy — winna jest „plotka”, nie on. Bardzo przydatne w sporze.",
     ex_ph="jing rǒe khráp wâa man mâi dâai {ph} yàang thîi khon phûut kan", ex_th="จริงหรือครับว่ามันไม่ได้{th}อย่างที่คนพูดกัน",
     items=[
       ("Wcale nie jest tak drogo, jak mówią.", "drogi", "Naprawdę nie jest tak drogo, jak mówią?"),
       ("Wcale nie jest tak tanio, jak mówią.", "tani", "Naprawdę nie jest tak tanio, jak mówią?"),
       ("Wcale nie jest tak niebezpiecznie, jak mówią.", "niebezpieczny", "Naprawdę nie jest tak niebezpiecznie?"),
       ("Wcale nie jest tak trudno, jak mówią.", "trudny", "Naprawdę nie jest tak trudno, jak mówią?"),
       ("Wcale nie jest tak łatwo, jak mówią.", "łatwy", "Naprawdę nie jest tak łatwo, jak mówią?"),
       ("Wcale nie jest tak ostro, jak mówią.", "ostry (pikantny)", "Naprawdę nie jest tak ostro, jak mówią?"),
       ("Wcale nie jest tak smacznie, jak mówią.", "smaczny", "Naprawdę nie jest tak smacznie?"),
       ("Wcale nie jest tak brudno, jak mówią.", "brudny", "Naprawdę nie jest tak brudno, jak mówią?"),
       ("Wcale nie jest tak głośno, jak mówią.", "głośny", "Naprawdę nie jest tak głośno, jak mówią?"),
       ("Wcale nie jest tak daleko, jak mówią.", "daleki", "Naprawdę nie jest tak daleko, jak mówią?"),
       ("Wcale nie jest tak wolno, jak mówią.", "wolny (powolny)", "Naprawdę nie jest tak wolno, jak mówią?"),
       ("Wcale nie jest tak nudno, jak mówią.", "nudny", "Naprawdę nie jest tak nudno, jak mówią?"),
       ("Wcale nie jest tak ciekawie, jak mówią.", "interesujący", "Naprawdę nie jest tak ciekawie?"),
       ("Wcale nie jest tak gorąco, jak mówią.", "gorący", "Naprawdę nie jest tak gorąco, jak mówią?"),
       ("Wcale nie jest tak zimno, jak mówią.", "zimno (o pogodzie)", "Naprawdę nie jest tak zimno, jak mówią?"),
       ("Wcale nie jest tak tłoczno, jak mówią.", "pełny / zajęty", "Naprawdę nie jest tak tłoczno?"),
       ("Wcale nie jest tak czysto, jak mówią.", "czysty", "Naprawdę nie jest tak czysto, jak mówią?"),
       ("Wcale nie jest tak wygodnie, jak mówią.", "wygodny", "Naprawdę nie jest tak wygodnie?"),
       ("Wcale nie jest tak bezpiecznie, jak mówią.", "bezpieczny", "Naprawdę nie jest tak bezpiecznie?"),
       ("Wcale nie jest tak nowocześnie, jak mówią.", "nowy", "Naprawdę nie jest to takie nowe?"),
       ("Wcale nie jest tak staro, jak mówią.", "stary", "Naprawdę nie jest to takie stare?"),
       ("Wcale nie jest tak wysoko, jak mówią.", "wysoki", "Naprawdę nie jest tak wysoko, jak mówią?"),
       ("Wcale nie jest tak głęboko, jak mówią.", "głęboki", "Naprawdę nie jest tak głęboko, jak mówią?"),
       ("Wcale nie jest tak ciężko, jak mówią.", "ciężki", "Naprawdę nie jest tak ciężko, jak mówią?"),
       ("Wcale nie jest tak męcząco, jak mówią.", "zmęczony", "Naprawdę nie jest tak męcząco?"),
       ("Wcale nie jest tak stresująco, jak mówią.", "zestresowany", "Naprawdę nie jest tak stresująco?"),
       ("Wcale nie jest tak tłusto, jak mówią.", "tłusty", "Naprawdę nie jest tak tłusto, jak mówią?"),
       ("Wcale nie jest tak słono, jak mówią.", "słony", "Naprawdę nie jest tak słono, jak mówią?"),
       ("Wcale nie jest tak słodko, jak mówią.", "słodki", "Naprawdę nie jest tak słodko, jak mówią?"),
       ("Wcale nie jest tak ładnie, jak mówią.", "ładny", "Naprawdę nie jest tak ładnie, jak mówią?"),
       ("Wcale nie jest tak spokojnie, jak mówią.", "cichy / spokojny", "Naprawdę nie jest tak spokojnie?"),
       ("Wcale nie jest tak mocne, jak mówią.", "silny, mocny", "Naprawdę nie jest tak mocne, jak mówią?"),
       ("Wcale nie jest tak słabe, jak mówią.", "słaby", "Naprawdę nie jest tak słabe, jak mówią?"),
       ("Wcale nie jest tak zabawne, jak mówią.", "fajny / zabawny", "Naprawdę nie jest tak zabawne?"),
       ("Wcale nie jest tak duże, jak mówią.", "duży", "Naprawdę nie jest tak duże, jak mówią?"),
       ("Wcale nie jest tak świeże, jak mówią.", "świeży", "Naprawdę nie jest tak świeże, jak mówią?"),
     ]),

# =====================================================================
# chuang lang man … khuen rueai rueai — tendencja w czasie
# =====================================================================
dict(key="RUEAIRUEAI", ty="sentence", cat="Cechy i opinie", sub="Zmiana", reg="n",
     ph="chûang lǎng man {ph} khûen rûeai rûeai khráp", th="ช่วงหลังมัน{th}ขึ้นเรื่อยๆ ครับ",
     lit="rûeai rûeai = stopniowo, wciąż dalej w tę stronę",
     note="„rûeai rûeai” opisuje tendencję, nie stan. Bez tego dodatku zdanie mówi tylko, że coś wzrosło raz.",
     ex_ph="chûang lǎng man {ph} khûen rûeai rûeai loei rǒe khráp", ex_th="ช่วงหลังมัน{th}ขึ้นเรื่อยๆ เลยหรือครับ",
     items=[
       ("Ostatnio robi się coraz drożej.", "drogi", "Naprawdę robi się coraz drożej?"),
       ("Ostatnio robi się coraz goręcej.", "gorący", "Naprawdę robi się coraz goręcej?"),
       ("Ostatnio robi się coraz głośniej.", "głośny", "Naprawdę robi się coraz głośniej?"),
       ("Ostatnio robi się coraz trudniej.", "trudny", "Naprawdę robi się coraz trudniej?"),
       ("Ostatnio robi się coraz tłoczniej.", "pełny / zajęty", "Naprawdę robi się coraz tłoczniej?"),
       ("Ostatnio robi się coraz brudniej.", "brudny", "Naprawdę robi się coraz brudniej?"),
       ("Ostatnio robi się coraz wolniej.", "wolny (powolny)", "Naprawdę robi się coraz wolniej?"),
       ("Ostatnio robi się coraz ciekawiej.", "interesujący", "Naprawdę robi się coraz ciekawiej?"),
       ("Ostatnio robi się coraz lepiej.", "dobry", "Naprawdę robi się coraz lepiej?"),
       ("Ostatnio robi się coraz gorzej.", "zły / kiepski", "Naprawdę robi się coraz gorzej?"),
       ("Ostatnio robi się coraz ciężej.", "ciężki", "Naprawdę robi się coraz ciężej?"),
       ("Ostatnio robi się coraz bardziej męcząco.", "zmęczony", "Naprawdę robi się coraz bardziej męcząco?"),
       ("Ostatnio robi się coraz bardziej stresująco.", "zestresowany", "Naprawdę robi się coraz bardziej stresująco?"),
       ("Ostatnio robi się coraz niebezpieczniej.", "niebezpieczny", "Naprawdę robi się coraz niebezpieczniej?"),
       ("Ostatnio robi się coraz spokojniej.", "cichy / spokojny", "Naprawdę robi się coraz spokojniej?"),
       ("Ostatnio robi się coraz nudniej.", "nudny", "Naprawdę robi się coraz nudniej?"),
       ("Ostatnio robi się coraz szybciej.", "szybki", "Naprawdę robi się coraz szybciej?"),
       ("Ostatnio robi się coraz ładniej.", "ładny", "Naprawdę robi się coraz ładniej?"),
       ("Ostatnio robi się coraz nowocześniej.", "nowy", "Naprawdę robi się coraz nowocześniej?"),
       ("Ostatnio robi się coraz łatwiej.", "łatwy", "Naprawdę robi się coraz łatwiej?"),
       ("Ostatnio robi się coraz ostrzej w smaku.", "ostry (pikantny)", "Naprawdę robi się coraz ostrzej?"),
       ("Ostatnio robi się coraz słodziej.", "słodki", "Naprawdę robi się coraz słodziej?"),
       ("Ostatnio robi się coraz bardziej pusto.", "pusty", "Naprawdę robi się coraz bardziej pusto?"),
       ("Ostatnio robi się coraz jaśniej.", "jasny", "Naprawdę robi się coraz jaśniej?"),
       ("Ostatnio robi się coraz ciemniej.", "ciemny", "Naprawdę robi się coraz ciemniej?"),
       ("Ostatnio robi się coraz zimniej.", "zimno (o pogodzie)", "Naprawdę robi się coraz zimniej?"),
       ("Ostatnio robi się coraz bardziej wilgotno i twardo w ziemi.", "twardy", "Naprawdę ziemia coraz twardsza?"),
       ("Ostatnio robi się coraz bardziej miękko.", "miękki", "Naprawdę robi się coraz bardziej miękko?"),
       ("Ostatnio robi się coraz bardziej tłusto.", "tłusty", "Naprawdę robi się coraz bardziej tłusto?"),
       ("Ostatnio robi się coraz droższy czynsz i coraz ciaśniej.", "mały", "Naprawdę robi się coraz ciaśniej?"),
       ("Ostatnio robi się coraz wygodniej.", "wygodny", "Naprawdę robi się coraz wygodniej?"),
       ("Ostatnio robi się coraz czyściej.", "czysty", "Naprawdę robi się coraz czyściej?"),
       ("Ostatnio robi się coraz bezpieczniej.", "bezpieczny", "Naprawdę robi się coraz bezpieczniej?"),
       ("Ostatnio robi się coraz weselej.", "fajny / zabawny", "Naprawdę robi się coraz weselej?"),
       ("Ostatnio robi się coraz bardziej stromo pod górę.", "wysoki", "Naprawdę robi się coraz bardziej stromo?"),
       ("Ostatnio robi się coraz mocniej.", "silny, mocny", "Naprawdę robi się coraz mocniej?"),
     ]),

# =====================================================================
# sam-rap phom man … kam-lang dii — ocena subiektywna
# =====================================================================
dict(key="KAMLANGDII", ty="sentence", cat="Cechy i opinie", sub="Preferencje", reg="n",
     ph="sǎm-ràp phǒm man {ph} kam-lang dii khráp", th="สำหรับผมมัน{th}กำลังดีครับ",
     lit="kam-lang dii = akurat w sam raz",
     note="„kam-lang dii” to tajska pochwała umiaru — nie za dużo, nie za mało. Bardzo częste przy jedzeniu i cenie.",
     ex_ph="sǎm-ràp khun man {ph} kam-lang dii mǎi khráp", ex_th="สำหรับคุณมัน{th}กำลังดีไหมครับ",
     items=[
       ("Dla mnie jest w sam raz ostre.", "ostry (pikantny)", "Dla ciebie jest w sam raz ostre?"),
       ("Dla mnie jest w sam raz słodkie.", "słodki", "Dla ciebie jest w sam raz słodkie?"),
       ("Dla mnie jest w sam raz słone.", "słony", "Dla ciebie jest w sam raz słone?"),
       ("Dla mnie jest w sam raz duże.", "duży", "Dla ciebie jest w sam raz duże?"),
       ("Dla mnie jest w sam raz małe.", "mały", "Dla ciebie jest w sam raz małe?"),
       ("Dla mnie jest w sam raz drogie.", "drogi", "Dla ciebie ta cena jest w sam raz?"),
       ("Dla mnie jest w sam raz gorące.", "gorący", "Dla ciebie jest w sam raz gorące?"),
       ("Dla mnie jest w sam raz twarde.", "twardy", "Dla ciebie jest w sam raz twarde?"),
       ("Dla mnie jest w sam raz miękkie.", "miękki", "Dla ciebie jest w sam raz miękkie?"),
       ("Dla mnie jest w sam raz jasne.", "jasny", "Dla ciebie jest w sam raz jasne?"),
       ("Dla mnie jest w sam raz ciemne.", "ciemny", "Dla ciebie jest w sam raz ciemne?"),
       ("Dla mnie jest w sam raz długie.", "długi", "Dla ciebie jest w sam raz długie?"),
       ("Dla mnie jest w sam raz krótkie.", "krótki", "Dla ciebie jest w sam raz krótkie?"),
       ("Dla mnie jest w sam raz szybkie.", "szybki", "Dla ciebie jest w sam raz szybkie?"),
       ("Dla mnie jest w sam raz spokojne.", "cichy / spokojny", "Dla ciebie jest w sam raz spokojne?"),
       ("Dla mnie jest w sam raz blisko.", "bliski", "Dla ciebie jest w sam raz blisko?"),
       ("Dla mnie jest w sam raz mocne.", "silny, mocny", "Dla ciebie jest w sam raz mocne?"),
       ("Dla mnie jest w sam raz lekkie.", "lekki", "Dla ciebie jest w sam raz lekkie?"),
       ("Dla mnie jest w sam raz proste.", "łatwy", "Dla ciebie jest w sam raz proste?"),
       ("Dla mnie jest w sam raz wymagające.", "trudny", "Dla ciebie jest w sam raz wymagające?"),
       ("Dla mnie jest w sam raz świeże.", "świeży", "Dla ciebie jest w sam raz świeże?"),
       ("Dla mnie jest w sam raz dojrzałe.", "dojrzały", "Dla ciebie jest w sam raz dojrzałe?"),
       ("Dla mnie jest w sam raz chrupiące.", "chrupiący", "Dla ciebie jest w sam raz chrupiące?"),
       ("Dla mnie jest w sam raz tłuste.", "tłusty", "Dla ciebie jest w sam raz tłuste?"),
       ("Dla mnie jest w sam raz wygodne.", "wygodny", "Dla ciebie jest w sam raz wygodne?"),
       ("Dla mnie jest w sam raz wysokie.", "wysoki", "Dla ciebie jest w sam raz wysokie?"),
       ("Dla mnie jest w sam raz głośne.", "głośny", "Dla ciebie jest w sam raz głośne?"),
       ("Dla mnie jest w sam raz nowe.", "nowy", "Dla ciebie jest w sam raz nowe?"),
       ("Dla mnie jest w sam raz tanie.", "tani", "Dla ciebie jest w sam raz tanie?"),
       ("Dla mnie jest w sam raz ciepłe wieczorem.", "zimno (o pogodzie)", "Dla ciebie wieczorem jest w sam raz?"),
       ("Dla mnie jest w sam raz ciekawe.", "interesujący", "Dla ciebie jest w sam raz ciekawe?"),
       ("Dla mnie jest w sam raz smaczne.", "smaczny", "Dla ciebie jest w sam raz smaczne?"),
       ("Dla mnie jest w sam raz gorzkie.", "gorzki", "Dla ciebie jest w sam raz gorzkie?"),
       ("Dla mnie jest w sam raz kwaśne.", "kwaśny", "Dla ciebie jest w sam raz kwaśne?"),
       ("Dla mnie jest w sam raz głębokie.", "głęboki", "Dla ciebie jest w sam raz głębokie?"),
       ("Dla mnie jest w sam raz czyste.", "czysty", "Dla ciebie jest w sam raz czyste?"),
     ]),
]
