# -*- coding: utf-8 -*-
"""Sesja N — CZASOWNIKI, GRAMATYKA UŻYTKOWA, JEDZENIE, RESTAURACJA, CECHY.

Czasowniki są w mowie potocznej najgęściej powtarzaną klasą wyrazów — kilkaset
z nich wystarcza na większość wypowiedzi. Baza miała ich 181, przy 776
rekordach w tej kategorii. Gramatyka użytkowa miała 71 haseł na 1 578 rekordów,
czyli dwadzieścia dwa zdania na jedno słowo funkcyjne.

Cechy i opinie dostają najmniej nowego materiału (kategoria była już
najliczniejsza) — i wyłącznie takie hasła, których brak faktycznie blokował
budowanie zdań.

Krotka: (poziom, polski, fonetyka, pismo, podkategoria, częstość, typ,
         kategoria, uwaga, dosłownie)
"""

CZ = "Czasowniki"
GR = "Gramatyka użytkowa"
JN = "Jedzenie i napoje"
RE = "Restauracja"
CO = "Cechy i opinie"

LANG = [

# ============================================================ CZASOWNIKI RUCHU
("A1", "wchodzić", "khâo", "เข้า", "Ruch", 5, "v", CZ,
 "Bardzo produktywny: khâo jai (rozumieć), khâo ruam (dołączyć).", ""),
("A1", "wychodzić", "àwk", "ออก", "Ruch", 5, "v", CZ,
 "àwk kam-lang kai (ćwiczyć), àwk sǐang (wymawiać).", ""),
("A1", "wracać", "klàp maa", "กลับมา", "Ruch", 5, "v", CZ,
 "maa dodaje kierunek „do mówiącego”; klàp pai — z powrotem tam.", "wracać przychodzić"),
("A2", "biec", "wîng", "วิ่ง", "Ruch", 4, "v", CZ,
 "", ""),
("A2", "skakać", "krà-dòot", "กระโดด", "Ruch", 2, "v", CZ,
 "", ""),
("A2", "wspinać się", "pìin", "ปีน", "Ruch", 2, "v", CZ,
 "pìin khǎo — wspinać się na górę.", ""),
("A2", "pływać", "wâai nám", "ว่ายน้ำ", "Ruch", 4, "v", CZ,
 "", "pływać woda"),
("A2", "latać", "bin", "บิน", "Ruch", 4, "v", CZ,
 "khrûeang bin — samolot, dosłownie „maszyna lecąca”.", ""),
("A2", "spadać, upaść", "lóm", "ล้ม", "Ruch", 3, "v", CZ,
 "O człowieku; o przedmiocie raczej tòk.", ""),
("A2", "przechodzić przez", "khâam", "ข้าม", "Ruch", 4, "v", CZ,
 "khâam thà-nǒn — przejść przez ulicę.", ""),
("A2", "mijać, przechodzić obok", "phàan", "ผ่าน", "Ruch", 5, "v", CZ,
 "Także „zdać” i „minąć” o czasie.", ""),
("A2", "podążać za", "taam", "ตาม", "Ruch", 5, "v", CZ,
 "Także „zgodnie z”: taam sà-baai — jak wygodnie.", ""),
("A2", "zbliżać się", "khâo klâi", "เข้าใกล้", "Ruch", 3, "v", CZ,
 "Uwaga: klâi (blisko) kontra klai (daleko) — sam ton.", "wchodzić blisko"),
("A2", "oddalać się", "hàang àwk", "ห่างออก", "Ruch", 2, "v", CZ,
 "hàang to odległy.", "odległy wychodzić"),
("A2", "zatrzymać się", "yùt", "หยุด", "Ruch", 5, "v", CZ,
 "Napis na znaku stopu.", ""),
("A2", "czekać", "raw", "รอ", "Ruch", 5, "v", CZ,
 "raw sàk khrûu — poczekaj chwilę.", ""),
("A2", "spieszyć się", "rîip", "รีบ", "Ruch", 5, "v", CZ,
 "rîip rîip — bardzo się spieszyć.", ""),

# ============================================================ CZASOWNIKI RĘKI
("A2", "trzymać", "thǔe", "ถือ", "Czynności ręką", 4, "v", CZ,
 "Także „wyznawać religię” — thǔe sàat-sà-nǎa.", ""),
("A2", "podnosić", "yók", "ยก", "Czynności ręką", 4, "v", CZ,
 "yók hâi — dać, ofiarować.", ""),
("A2", "kłaść, stawiać", "waang", "วาง", "Czynności ręką", 5, "v", CZ,
 "waang phǎen — planować.", ""),
("A2", "wkładać, wsypywać", "sài", "ใส่", "Czynności ręką", 5, "v", CZ,
 "Bardzo częste: sài phrík (dodać chili), sài sûea (włożyć koszulę).", ""),
("A2", "wyjmować", "yìp àwk", "หยิบออก", "Czynności ręką", 3, "v", CZ,
 "yìp to wziąć palcami.", "brać wychodzić"),
("A2", "otwierać", "pòoet", "เปิด", "Czynności ręką", 5, "v", CZ,
 "Także włączać urządzenie i światło.", ""),
("A2", "zamykać", "pìt", "ปิด", "Czynności ręką", 5, "v", CZ,
 "Także wyłączać.", ""),
("A2", "ciągnąć", "dueng", "ดึง", "Czynności ręką", 3, "v", CZ,
 "Napis na drzwiach obok phlàk (pchać).", ""),
("A2", "pchać", "phlàk", "ผลัก", "Czynności ręką", 3, "v", CZ,
 "", ""),
("A2", "rzucać", "khwâang", "ขว้าง", "Czynności ręką", 2, "v", CZ,
 "", ""),
("A2", "łapać", "jàp", "จับ", "Czynności ręką", 4, "v", CZ,
 "Także „dotknąć” i „aresztować”.", ""),
("A2", "naciskać", "kòt", "กด", "Czynności ręką", 4, "v", CZ,
 "kòt ngoen — wypłacić z bankomatu, dosłownie „nacisnąć pieniądze”.", ""),
("A2", "ciąć", "tàt", "ตัด", "Czynności ręką", 4, "v", CZ,
 "tàt sǐn jai — zdecydować, dosłownie „odciąć serce”.", ""),
("A2", "wiązać", "phùuk", "ผูก", "Czynności ręką", 2, "v", CZ,
 "", ""),
("A2", "składać, zginać", "pháp", "พับ", "Czynności ręką", 2, "v", CZ,
 "", ""),

# ============================================================ CZASOWNIKI MYŚLI
("A2", "rozumieć", "khâo jai", "เข้าใจ", "Myślenie", 5, "v", CZ,
 "Dosłownie „wejść w serce”. Nie rozumieć: mâi khâo jai.", "wchodzić serce"),
("A2", "zgubić wątek, nie nadążać", "taam mâi than", "ตามไม่ทัน", "Myślenie", 4, "v", CZ,
 "Bardzo przydatne w rozmowie: mówi się, gdy ktoś mówi za szybko.", "podążać nie zdążyć"),
("A2", "zauważyć", "sǎng-kèet", "สังเกต", "Myślenie", 3, "v", CZ,
 "", ""),
("A2", "decydować", "tàt sǐn jai", "ตัดสินใจ", "Myślenie", 4, "v", CZ,
 "", "ciąć rozstrzygać serce"),
("A2", "planować", "waang phǎen", "วางแผน", "Myślenie", 4, "v", CZ,
 "", "kłaść plan"),
("A2", "porównywać", "prìap thîap", "เปรียบเทียบ", "Myślenie", 3, "v", CZ,
 "", ""),
("A2", "wybierać", "lûeak", "เลือก", "Myślenie", 5, "v", CZ,
 "Także „głosować” — lûeak tâng.", ""),
("A2", "sprawdzać", "chék", "เช็ค", "Myślenie", 5, "v", CZ,
 "Zapożyczenie; formalnie tùuat sàwp.", ""),
("A2", "wyobrażać sobie", "nùek phâap", "นึกภาพ", "Myślenie", 2, "v", CZ,
 "nùek to przychodzić na myśl.", "myśleć obraz"),
("A2", "przypominać sobie", "nùek àwk", "นึกออก", "Myślenie", 4, "v", CZ,
 "nùek mâi àwk — nie mogę sobie przypomnieć. Bardzo częste.", "myśleć wychodzić"),
("A2", "zastanawiać się", "khít duu", "คิดดู", "Myślenie", 4, "v", CZ,
 "duu po czasowniku znaczy „spróbować i zobaczyć”.", "myśleć patrzeć"),
("A2", "wierzyć", "chûea", "เชื่อ", "Myślenie", 4, "v", CZ,
 "Uwaga na parę: chûea (wierzyć) kontra chúea (zarazek).", ""),
("A2", "ufać", "wái jai", "ไว้ใจ", "Myślenie", 3, "v", CZ,
 "", "zostawiać serce"),
("A2", "martwić się", "pen hùang", "เป็นห่วง", "Myślenie", 4, "v", CZ,
 "O kogoś. O sprawę: kang-won.", "być troska"),
("A2", "denerwować się, obawiać", "kang-won", "กังวล", "Myślenie", 3, "v", CZ,
 "", ""),
("A2", "mieć nadzieję", "wǎng", "หวัง", "Myślenie", 4, "v", CZ,
 "wǎng wâa — mam nadzieję, że.", ""),

# ============================================================ CZASOWNIKI MOWY
("A2", "pytać", "thǎam", "ถาม", "Mówienie", 5, "v", CZ,
 "khǎw thǎam nòi — czy mogę zapytać.", ""),
("A2", "odpowiadać", "tàwp", "ตอบ", "Mówienie", 5, "v", CZ,
 "", ""),
("A2", "prosić kogoś, żeby…", "khǎw hâi", "ขอให้", "Mówienie", 4, "v", CZ,
 "Także formuła życzeń: khǎw hâi chôok dii.", "prosić dawać"),
("A2", "kazać, zamawiać", "sàng", "สั่ง", "Mówienie", 5, "v", CZ,
 "sàng aa-hǎan — zamówić jedzenie; sàng khǎwng — zamówić towar.", ""),
("A2", "powtórzyć", "phûut ìik thii", "พูดอีกที", "Mówienie", 5, "v", CZ,
 "Zdanie ratunkowe w każdej rozmowie: phûut ìik thii dâi mǎi.", "mówić jeszcze raz"),
("A2", "wołać, dzwonić do kogoś", "thoo hǎa", "โทรหา", "Mówienie", 5, "v", CZ,
 "thoo to skrót od telefonu.", "telefonować szukać"),
("A2", "przedstawiać się", "náe-nam tua", "แนะนำตัว", "Mówienie", 3, "v", CZ,
 "náe-nam samo znaczy też „polecać”.", "polecać ciało"),
("A2", "dziękować komuś", "khàwp khun", "ขอบคุณ", "Mówienie", 5, "v", CZ,
 "Silniejsza forma: khàwp phrá khun.", "brzeg ty"),
("A2", "ostrzegać", "tuean", "เตือน", "Mówienie", 3, "v", CZ,
 "Także „przypominać komuś”.", ""),
("A2", "obiecywać, umawiać się", "nát", "นัด", "Mówienie", 4, "v", CZ,
 "nát wee-laa — umówić godzinę.", ""),

# ============================================================ INNE CZASOWNIKI
("A2", "używać", "chái", "ใช้", "Czynności ogólne", 5, "v", CZ,
 "chái dâi — działa, nadaje się. chái wee-laa — zajmować czas.", ""),
("A2", "próbować", "lawng", "ลอง", "Czynności ogólne", 5, "v", CZ,
 "lawng duu — spróbuj. Kluczowe w sklepie i w restauracji.", ""),
("A2", "kończyć", "sèt", "เสร็จ", "Czynności ogólne", 5, "v", CZ,
 "sèt láew — gotowe, skończone.", ""),
("A2", "zaczynać", "rôoem", "เริ่ม", "Czynności ogólne", 5, "v", CZ,
 "", ""),
("A2", "kontynuować", "tham tàw", "ทำต่อ", "Czynności ogólne", 4, "v", CZ,
 "Znów tàw — łączyć, przedłużać.", "robić przedłużać"),
("A2", "przestać coś robić", "lôoek", "เลิก", "Czynności ogólne", 4, "v", CZ,
 "lôoek ngaan — skończyć pracę; lôoek kan — rozstać się.", ""),
("A2", "pożyczyć (od kogoś)", "yuem", "ยืม", "Czynności ogólne", 4, "v", CZ,
 "Kierunek do siebie. Pożyczyć komuś: hâi yuem.", ""),
("A2", "wynajmować", "châo", "เช่า", "Czynności ogólne", 4, "v", CZ,
 "châo rót — wynająć samochód.", ""),
("A2", "przygotować", "triam", "เตรียม", "Czynności ogólne", 4, "v", CZ,
 "triam tua — przygotować się.", ""),
("A2", "zbierać, gromadzić", "kèp", "เก็บ", "Czynności ogólne", 5, "v", CZ,
 "Bardzo szerokie: sprzątać, chować, pobierać opłatę. kèp taang — pobrać należność.", ""),
("A2", "dzielić się", "bàeng", "แบ่ง", "Czynności ogólne", 4, "v", CZ,
 "bàeng kan — podzielić między sobą.", ""),
("A2", "zamieniać się", "lâek plìan", "แลกเปลี่ยน", "Czynności ogólne", 3, "v", CZ,
 "", "wymieniać zmieniać"),
("A2", "zapraszać do środka", "chooen", "เชิญ", "Czynności ogólne", 4, "v", CZ,
 "Gest i słowo naraz — mówione przy przepuszczaniu w drzwiach.", ""),
("A2", "wygrywać", "chá-ná", "ชนะ", "Czynności ogólne", 3, "v", CZ,
 "", ""),
("A2", "przegrywać", "phǽe", "แพ้", "Czynności ogólne", 3, "v", CZ,
 "To samo słowo co „mieć alergię”.", ""),
("A2", "śpiewać", "ráwng phleeng", "ร้องเพลง", "Czynności ogólne", 4, "v", CZ,
 "ráwng samo to krzyczeć i płakać.", "krzyczeć piosenka"),
("A2", "tańczyć", "tên", "เต้น", "Czynności ogólne", 3, "v", CZ,
 "Także o sercu: hǔa jai tên.", ""),
("A2", "grać (w grę)", "lên", "เล่น", "Czynności ogólne", 5, "v", CZ,
 "lên kii-laa, lên mueu-thǔe. Także „żartować”.", ""),

# ============================================================ GRAMATYKA
("A2", "i (łącznik zdań)", "láew kâw", "แล้วก็", "Spójniki", 5, "w", GR,
 "W mowie znacznie częstsze niż formalne láe.", "potem też"),
("A2", "ale", "tàe", "แต่", "Spójniki", 5, "w", GR,
 "tàe wâa — ale że.", ""),
("A2", "więc, dlatego", "kâw looei", "ก็เลย", "Spójniki", 5, "w", GR,
 "Bardzo częsty łącznik potoczny.", "też więc"),
("A2", "ponieważ", "phráw wâa", "เพราะว่า", "Spójniki", 5, "w", GR,
 "Skracane do samego phráw.", "ponieważ że"),
("A2", "jeśli", "thâa", "ถ้า", "Spójniki", 5, "w", GR,
 "thâa … kâw … — jeśli, to.", ""),
("A2", "chociaż", "thǔeng máe wâa", "ถึงแม้ว่า", "Spójniki", 3, "w", GR,
 "", "aż nawet że"),
("A2", "albo", "rǔe wâa", "หรือว่า", "Spójniki", 4, "w", GR,
 "", "czy że"),
("A2", "oprócz", "nâwk jàak", "นอกจาก", "Spójniki", 4, "w", GR,
 "nâwk to zewnątrz.", "zewnątrz od"),
("A2", "dla, w celu", "phûea", "เพื่อ", "Przyimki", 4, "w", GR,
 "phûea à-rai — po co.", ""),
("A2", "z (kimś)", "kàp", "กับ", "Przyimki", 5, "w", GR,
 "pai kàp phǒm — idź ze mną.", ""),
("A2", "o (na temat)", "kìao kàp", "เกี่ยวกับ", "Przyimki", 4, "w", GR,
 "kìao to dotyczyć, zahaczać.", "dotyczyć z"),
("A2", "według, zgodnie z", "taam", "ตาม", "Przyimki", 4, "w", GR,
 "Ten sam wyraz co „podążać”.", ""),
("A2", "aż do", "jon thǔeng", "จนถึง", "Przyimki", 3, "w", GR,
 "", "aż do"),
("A2", "od (czasu)", "tâng tàe", "ตั้งแต่", "Przyimki", 4, "w", GR,
 "tâng tàe cháo — od rana.", "ustanawiać od"),
("A2", "między", "rá-wàang", "ระหว่าง", "Przyimki", 3, "w", GR,
 "Także „podczas”.", ""),
("A2", "pomimo, mimo to", "thǔeng yàang nán", "ถึงอย่างนั้น", "Spójniki", 2, "w", GR,
 "", "aż sposób tamten"),
("A2", "znowu, jeszcze raz", "ìik", "อีก", "Partykuły", 5, "w", GR,
 "ìik nùeng — jeszcze jeden. ìik thii — jeszcze raz.", ""),
("A2", "też, również", "dûai", "ด้วย", "Partykuły", 5, "w", GR,
 "Na końcu zdania. Także „za pomocą”.", ""),
("A2", "tylko", "khâe", "แค่", "Partykuły", 5, "w", GR,
 "khâe níi — tylko tyle.", ""),
("A2", "prawie", "kùeap", "เกือบ", "Partykuły", 4, "w", GR,
 "kùeap láew — prawie gotowe.", ""),
("A2", "wcale nie", "mâi … looei", "ไม่…เลย", "Partykuły", 5, "w", GR,
 "looei na końcu wzmacnia przeczenie: mâi phèt looei.", "nie wcale"),
("A2", "raczej, dość", "khâwn khâang", "ค่อนข้าง", "Partykuły", 4, "w", GR,
 "khâwn khâang phaeng — dość drogo.", ""),
("A2", "zbyt, za bardzo", "kooen pai", "เกินไป", "Partykuły", 5, "w", GR,
 "Stoi po przymiotniku: phaeng kooen pai.", "przekraczać iść"),
("A2", "na pewno", "nâe nawn", "แน่นอน", "Partykuły", 5, "w", GR,
 "Także samodzielna odpowiedź „oczywiście”.", ""),
("A2", "może, chyba", "àat jà", "อาจจะ", "Partykuły", 5, "w", GR,
 "", "móc zamiar"),
("A2", "właściwie, tak naprawdę", "jing jing láew", "จริงๆแล้ว", "Partykuły", 4, "w", GR,
 "", "prawdziwie potem"),
("A2", "w ogóle, zupełnie", "tháng mòt", "ทั้งหมด", "Partykuły", 5, "w", GR,
 "Także „w sumie, wszystko razem”.", "cały wyczerpać"),
("A2", "każdy z osobna", "tàe lá", "แต่ละ", "Partykuły", 3, "w", GR,
 "tàe lá khon — każdy z osobna.", ""),
("A2", "sam, samodzielnie", "eeng", "เอง", "Partykuły", 4, "w", GR,
 "tham eeng — zrobić samemu. Stoi po podmiocie albo na końcu.", ""),
("A2", "nawzajem, siebie", "kan", "กัน", "Partykuły", 5, "w", GR,
 "chûai kan — pomagać sobie. pai kan — idziemy razem.", ""),
("A2", "no właśnie, prawda", "châi looei", "ใช่เลย", "Partykuły", 4, "w", GR,
 "Potwierdzenie z entuzjazmem.", "tak wcale"),
("A2", "no dobrze, niech będzie", "kâw dâi", "ก็ได้", "Partykuły", 5, "w", GR,
 "Zgoda bez entuzjazmu — bardzo częste.", "też móc"),

# ============================================================ JEDZENIE
("A1", "smak", "rót", "รส", "Smaki", 5, "n", JN,
 "Uwaga: rót to także „pojazd”, pisane inaczej. rót châat — smak potrawy.", ""),
("A2", "słony", "khem", "เค็ม", "Smaki", 5, "adj", JN,
 "", ""),
("A2", "gorzki", "khǒm", "ขม", "Smaki", 3, "adj", JN,
 "", ""),
("A2", "kwaśny", "prîao", "เปรี้ยว", "Smaki", 4, "adj", JN,
 "Także o osobie: „zadziorna”.", ""),
("A2", "mdły, bez smaku", "jùet", "จืด", "Smaki", 4, "adj", JN,
 "Także o wodzie: nám jùet — woda słodka, niesłona.", ""),
("A2", "tłusty", "man", "มัน", "Smaki", 4, "adj", JN,
 "To samo słowo co zaimek „ono”.", ""),
("A2", "świeży", "sòt", "สด", "Smaki", 4, "adj", JN,
 "nám sòt — świeży sok.", ""),
("A2", "przypalony", "mâi", "ไหม้", "Smaki", 2, "adj", JN,
 "Ten sam wyraz co w fai mâi.", ""),
("A2", "smażyć na głębokim tłuszczu", "thâwt", "ทอด", "Przygotowanie", 4, "v", JN,
 "phàt to smażyć na patelni, thâwt to w głębokim oleju.", ""),
("A2", "grillować", "yâang", "ย่าง", "Przygotowanie", 4, "v", JN,
 "", ""),
("A2", "gotować na parze", "nûeng", "นึ่ง", "Przygotowanie", 3, "v", JN,
 "Uwaga: nûeng (na parze) kontra nùeng (jeden) — sam ton.", ""),
("A2", "piec", "òp", "อบ", "Przygotowanie", 3, "v", JN,
 "Także „suszyć w piecu” i o pogodzie: òp âo — duszno.", ""),
("A2", "mieszać", "phà-sǒm", "ผสม", "Przygotowanie", 3, "v", JN,
 "", ""),
("A2", "kroić w plastry", "hàn", "หั่น", "Przygotowanie", 3, "v", JN,
 "", ""),
("A2", "obierać", "pàwk", "ปอก", "Przygotowanie", 2, "v", JN,
 "", ""),
("A2", "przyprawa", "khrûeang thêet", "เครื่องเทศ", "Składniki", 3, "n", JN,
 "khrûeang znów jako „zestaw, wyposażenie”.", "wyposażenie przyprawa"),
("A2", "sos rybny", "nám plaa", "น้ำปลา", "Składniki", 5, "n", JN,
 "Podstawa całej kuchni — stoi na każdym stole.", "woda ryba"),
("A2", "sos sojowy", "sii-íu", "ซีอิ๊ว", "Składniki", 4, "n", JN,
 "", ""),
("A2", "cukier", "nám taan", "น้ำตาล", "Składniki", 5, "n", JN,
 "Dosłownie „woda z palmy cukrowej”.", "woda palma"),
("A2", "ocet", "nám sôm", "น้ำส้ม", "Składniki", 3, "n", JN,
 "Uwaga: to samo brzmienie co „sok pomarańczowy” — rozstrzyga kontekst i naczynie.", "woda kwaśny"),
("A2", "czosnek", "krà-thiam", "กระเทียม", "Składniki", 4, "n", JN,
 "", ""),
("A2", "imbir", "khǐng", "ขิง", "Składniki", 3, "n", JN,
 "", ""),
("A2", "kolendra", "phàk chii", "ผักชี", "Składniki", 4, "n", JN,
 "mâi sài phàk chii — bez kolendry. Zdanie warte zapamiętania, jeśli się jej nie znosi.", "warzywo kolendra"),
("A2", "bazylia tajska", "kà-phrao", "กะเพรา", "Składniki", 4, "n", JN,
 "Stąd phàt kà-phrao — jedno z najczęściej zamawianych dań.", ""),
("A2", "trawa cytrynowa", "tà-khrái", "ตะไคร้", "Składniki", 3, "n", JN,
 "", ""),
("A2", "limonka", "má-naao", "มะนาว", "Składniki", 5, "n", JN,
 "", ""),
("A2", "orzeszki ziemne", "thùa lí-sǒng", "ถั่วลิสง", "Składniki", 4, "n", JN,
 "phǽe thùa — mam alergię na orzeszki.", "fasola orzeszek"),
("A2", "mleko kokosowe", "kà-thí", "กะทิ", "Składniki", 4, "n", JN,
 "", ""),
("A2", "jajko sadzone", "khài daao", "ไข่ดาว", "Potrawy", 5, "n", JN,
 "Dosłownie „jajko gwiazda”.", "jajko gwiazda"),
("A2", "omlet", "khài jiao", "ไข่เจียว", "Potrawy", 4, "n", JN,
 "", ""),
("A2", "kleisty ryż", "khâao nǐao", "ข้าวเหนียว", "Potrawy", 5, "n", JN,
 "Podstawa kuchni Isanu; je się palcami.", "ryż kleisty"),
("A2", "makaron ryżowy w rosole", "kǔai-tǐao nám", "ก๋วยเตี๋ยวน้ำ", "Potrawy", 5, "n", JN,
 "Wersja bez zupy: kǔai-tǐao hâeng.", "makaron woda"),
("A2", "przekąska", "khǎwng waang", "ของว่าง", "Potrawy", 4, "n", JN,
 "", "rzecz wolny"),
("A2", "deser", "khǎwng wǎan", "ของหวาน", "Potrawy", 4, "n", JN,
 "", "rzecz słodki"),
("A2", "lód (kostki)", "nám khǎeng", "น้ำแข็ง", "Napoje", 5, "n", JN,
 "mâi sài nám khǎeng — bez lodu.", "woda twardy"),
("A2", "woda butelkowana", "nám khùat", "น้ำขวด", "Napoje", 5, "n", JN,
 "khùat to butelka i jej klasyfikator.", "woda butelka"),
("A2", "sok", "nám phǒn-lá-mái", "น้ำผลไม้", "Napoje", 4, "n", JN,
 "phǒn-lá-mái to owoce zbiorczo.", "woda owoc"),
("A2", "kawa mrożona", "kaa-fae yen", "กาแฟเย็น", "Napoje", 5, "n", JN,
 "Domyślnie bardzo słodka — trzeba prosić wàan náwi.", "kawa zimny"),
("A2", "herbata mrożona", "chaa yen", "ชาเย็น", "Napoje", 5, "n", JN,
 "", "herbata zimny"),

# ============================================================ RESTAURACJA
("A1", "menu", "mee-nuu", "เมนู", "Zamawianie", 5, "n", RE,
 "khǎw mee-nuu nòi — poproszę kartę.", ""),
("A2", "danie (porcja)", "jaan", "จาน", "Zamawianie", 5, "n", RE,
 "Także talerz i klasyfikator porcji: nùeng jaan.", ""),
("A2", "miska", "chaam", "ชาม", "Zamawianie", 4, "n", RE,
 "Klasyfikator zup i makaronów.", ""),
("A2", "specjalność lokalu", "meun ná-nam", "เมนูแนะนำ", "Zamawianie", 3, "n", RE,
 "", "menu polecany"),
("A2", "dokładka", "phôoem", "เพิ่ม", "Zamawianie", 4, "v", RE,
 "phôoem khâao — dosypać ryżu.", ""),
("A2", "bez (czegoś)", "mâi sài", "ไม่ใส่", "Zamawianie", 5, "v", RE,
 "Najważniejsza konstrukcja przy alergii i przy ostrości.", "nie wkładać"),
("A2", "mało ostre", "phèt náwi", "เผ็ดน้อย", "Zamawianie", 5, "adj", RE,
 "Uwaga: to nadal ostre. Zero chili to mâi sài phrík.", "ostry mało"),
("A2", "mniej słodkie", "wǎan náwi", "หวานน้อย", "Zamawianie", 4, "adj", RE,
 "Konieczne przy każdym napoju.", "słodki mało"),
("A2", "rachunek proszę", "kèp taang", "เก็บตังค์", "Płacenie", 5, "w", RE,
 "Potoczne i najczęstsze; formalnie chék bin.", "zbierać pieniądze"),
("A2", "płacić osobno", "jàai yâek", "จ่ายแยก", "Płacenie", 3, "v", RE,
 "yâek to rozdzielać — ten sam wyraz co w sìi yâek.", "płacić rozdzielać"),
("A2", "płacić razem", "jàai ruam", "จ่ายรวม", "Płacenie", 3, "v", RE,
 "", "płacić razem"),
("A2", "kelner, kelnerka", "phá-nák ngaan sòoep", "พนักงานเสิร์ฟ", "Obsługa", 4, "n", RE,
 "W praktyce woła się „náwng” albo „phîi”, nie tytułem.", "pracownik serwować"),
("A2", "stolik dla dwojga", "tó sǎm-ràp sǎwng khon", "โต๊ะสำหรับสองคน", "Obsługa", 3, "n", RE,
 "sǎm-ràp to „dla, przeznaczony dla”.", "stół dla dwa osoba"),
("A2", "zarezerwować stolik", "jawng tó", "จองโต๊ะ", "Obsługa", 3, "v", RE,
 "", "rezerwować stół"),
("A2", "serwetka", "krà-dàat chét pàak", "กระดาษเช็ดปาก", "Obsługa", 3, "n", RE,
 "", "papier wycierać usta"),
("A2", "słomka", "làwt", "หลอด", "Obsługa", 4, "n", RE,
 "Także rurka i klasyfikator tubek.", ""),
("A2", "pałeczki", "tà-kìap", "ตะเกียบ", "Obsługa", 3, "n", RE,
 "Do makaronu; do ryżu używa się łyżki i widelca.", ""),

# ============================================================ CECHY
("A2", "gruby (o rzeczy)", "nǎa", "หนา", "Wymiary", 3, "adj", CO,
 "O człowieku: ûan.", ""),
("A2", "cienki", "baang", "บาง", "Wymiary", 3, "adj", CO,
 "To samo słowo znaczy „niektóry”: baang khon.", ""),
("A2", "płytki", "tûen", "ตื้น", "Wymiary", 2, "adj", CO,
 "", ""),
("A2", "ostry (nóż)", "khom", "คม", "Właściwości", 3, "adj", CO,
 "Uwaga: phèt to ostry w smaku, khom to ostry jak ostrze.", ""),
("A2", "tępy", "thûe", "ทื่อ", "Właściwości", 2, "adj", CO,
 "Także o człowieku.", ""),
("A2", "gładki", "rîap", "เรียบ", "Właściwości", 3, "adj", CO,
 "Także „prosty, bez ozdób” — rîap ráwi znaczy „w porządku”.", ""),
("A2", "szorstki", "khrù-khrà", "ขรุขระ", "Właściwości", 2, "adj", CO,
 "", ""),
("A2", "mokry", "pìak", "เปียก", "Właściwości", 4, "adj", CO,
 "", ""),
("A2", "twardy", "khǎeng", "แข็ง", "Właściwości", 4, "adj", CO,
 "nám khǎeng — lód, dosłownie „twarda woda”.", ""),
("A2", "miękki", "nûm", "นุ่ม", "Właściwości", 4, "adj", CO,
 "O materiale i o mięsie.", ""),
("A2", "ciasny", "khápa", "คับ", "Właściwości", 3, "adj", CO,
 "O ubraniu. Luźny: lǔam.", ""),
("A2", "luźny", "lǔam", "หลวม", "Właściwości", 3, "adj", CO,
 "", ""),
("A2", "pusty", "plào", "เปล่า", "Właściwości", 4, "adj", CO,
 "nám plào — czysta woda. Także „nic”: plào khráp.", ""),
("A2", "pełny (najedzony)", "ìm", "อิ่ม", "Właściwości", 5, "adj", CO,
 "ìm láew — najadłem się. Odpowiedź na propozycję dokładki.", ""),
("A2", "głodny", "hǐu", "หิว", "Właściwości", 5, "adj", CO,
 "hǐu nám — spragniony.", ""),
("A2", "podobny", "khláai", "คล้าย", "Porównania", 4, "adj", CO,
 "khláai kan — podobne do siebie.", ""),
("A2", "różny, inny", "tàang kan", "ต่างกัน", "Porównania", 4, "adj", CO,
 "", "obcy nawzajem"),
("A2", "taki sam", "mǔean kan", "เหมือนกัน", "Porównania", 5, "adj", CO,
 "Także odpowiedź „ja też”.", "podobny nawzajem"),
("A2", "najlepszy", "dii thîi sùt", "ดีที่สุด", "Porównania", 5, "adj", CO,
 "thîi sùt tworzy stopień najwyższy z każdego przymiotnika.", "dobry miejsce kres"),
("A2", "najgorszy", "yâe thîi sùt", "แย่ที่สุด", "Porównania", 3, "adj", CO,
 "", "zły miejsce kres"),
]
