# -*- coding: utf-8 -*-
"""Sesja F — ZYCIE: pojecia ogolne, czas wolny, swieta, komunikacja.

Uwaga systemowa o rzeczownikach abstrakcyjnych: tajski tworzy je dwoma
przedrostkami. „kaan” przed czasownikiem daje nazwe czynnosci
(kaan doen thaang — podrozowanie), „khwaam” przed przymiotnikiem albo
czasownikiem stanu daje nazwe cechy (khwaam sùk — szczescie,
khwaam khít — mysl). Znajac te dwa przedrostki, mozna zbudowac setki
rzeczownikow z juz znanych slow.
"""

ST = "Small talk"
GU = "Gramatyka użytkowa"
CO = "Cechy i opinie"
PP = "Pogoda i przyroda"
CD = "Czas i daty"

LIFE = [

# --------------------------------------------------------- pojecia ogolne
("A2", "sprawa", "rûeang", "เรื่อง", ST, "Pojęcia", 5, "n",
 "„rûeang” to sprawa, temat, historia i film. Bardzo częste: „mâi pen rai, mâi mii rûeang” — nic się nie stało.",
 "",
 [("To poważna sprawa.", "pen rûeang yài khráp", "เป็นเรื่องใหญ่ครับ"),
  ("O co chodzi?", "rûeang à-rai khráp", "เรื่องอะไรครับ")],
 ["problem", "opowiadać", "film"], ["temat"]),

("A2", "problem", "pan-hǎa", "ปัญหา", ST, "Pojęcia", 4, "n",
 "„mâi mii pan-hǎa” to „nie ma problemu” — uprzejma zgoda.",
 "",
 [("Jest problem.", "mii pan-hǎa khráp", "มีปัญหาครับ"),
  ("Nie ma problemu.", "mâi mii pan-hǎa khráp", "ไม่มีปัญหาครับ")],
 ["sprawa", "rozwiązywać", "pomagać"], []),

("A2", "powód", "hèet phǒn", "เหตุผล", ST, "Pojęcia", 3, "f",
 "„hèet” to zdarzenie, przyczyna — to samo w „ù-bàt-tì-hèet” (wypadek).",
 "przyczyna skutek",
 [("Jaki jest powód?", "hèet phǒn à-rai khráp", "เหตุผลอะไรครับ"),
  ("Bez powodu.", "mâi mii hèet phǒn khráp", "ไม่มีเหตุผลครับ")],
 ["dlaczego", "ponieważ", "wypadek"], ["przyczyna"]),

("A2", "sposób", "wí-thii", "วิธี", ST, "Pojęcia", 4, "n",
 "„wí-thii chái” to instrukcja obsługi. Pytanie „yang-ngai” zastępuje to słowo w mowie.",
 "",
 [("Jaki jest sposób?", "mii wí-thii à-rai bâang khráp", "มีวิธีอะไรบ้างครับ"),
  ("Jak to zrobić?", "tham yang-ngai khráp", "ทำยังไงครับ")],
 ["jak", "robić", "wyjaśniać"], []),

("A2", "możliwość", "oo-kàat", "โอกาส", ST, "Pojęcia", 3, "f",
 "„mii oo-kàat” to mieć okazję. Także w życzeniach: „khǎw hâi mii oo-kàat”.",
 "",
 [("Nie miałem okazji.", "phǒm mâi mii oo-kàat khráp", "ผมไม่มีโอกาสครับ"),
  ("To dobra okazja.", "pen oo-kàat dii khráp", "เป็นโอกาสดีครับ")],
 ["szansa", "móc"], ["okazja"]),

("A2", "różnica", "khwaam tàek tàang", "ความแตกต่าง", ST, "Pojęcia", 3, "f",
 "Przedrostek „khwaam” zamienia przymiotnik „tàek tàang” (różny) w rzeczownik.",
 "cecha różny",
 [("Jaka jest różnica?", "tàek tàang kan yang-ngai khráp", "แตกต่างกันยังไงครับ"),
  ("Nie ma różnicy.", "mâi tàek tàang khráp", "ไม่แตกต่างครับ")],
 ["inny", "taki sam", "porównywać"], []),

("A2", "znaczenie", "khwaam mǎai", "ความหมาย", ST, "Pojęcia", 4, "f",
 "Kluczowe przy nauce języka: „khwaam mǎai wâa à-rai” — co to znaczy.",
 "cecha znaczyć",
 [("Jakie to ma znaczenie?", "khwaam mǎai wâa à-rai khráp", "ความหมายว่าอะไรครับ"),
  ("Nie rozumiem znaczenia.", "phǒm mâi khâo jai khwaam mǎai khráp", "ผมไม่เข้าใจความหมายครับ")],
 ["to znaczy", "rozumieć", "słownik"], []),

("A2", "szczęście (uczucie)", "khwaam sùk", "ความสุข", ST, "Pojęcia", 3, "f",
 "„sùk sǎn wan kòoet” to „wszystkiego najlepszego” — dosłownie „radosnych urodzin”.",
 "cecha radość",
 [("Życzę szczęścia.", "khǎw hâi mii khwaam sùk khráp", "ขอให้มีความสุขครับ"),
  ("Wszystkiego najlepszego.", "sùk sǎn wan kòoet khráp", "สุขสันต์วันเกิดครับ")],
 ["szczęśliwy", "urodziny", "życzyć"], []),

("A2", "prawda", "khwaam jing", "ความจริง", ST, "Pojęcia", 3, "f",
 "„jing jing rǔe” to „naprawdę?” — jedno z najczęstszych wtrąceń w rozmowie.",
 "cecha prawdziwy",
 [("Powiem prawdę.", "phǒm jà phûut khwaam jing khráp", "ผมจะพูดความจริงครับ"),
  ("Naprawdę?", "jing rǔe khráp", "จริงหรือครับ")],
 ["kłamać", "mówić", "naprawdę"], []),

("A2", "pomysł", "khwaam khít", "ความคิด", ST, "Pojęcia", 3, "f",
 "Także „myśl, opinia”. „khít wâa” to „myślę, że” — pokrewna konstrukcja.",
 "cecha myśleć",
 [("To dobry pomysł.", "pen khwaam khít thîi dii khráp", "เป็นความคิดที่ดีครับ"),
  ("Mam pomysł.", "phǒm mii khwaam khít khráp", "ผมมีความคิดครับ")],
 ["myśleć", "moim zdaniem"], ["myśl"]),

("A2", "wynik", "phǒn", "ผล", ST, "Pojęcia", 3, "f",
 "„phǒn” to też owoc — „phǒn-lá-mái” zawiera ten sam element.",
 "",
 [("Jaki wynik?", "phǒn pen yang-ngai khráp", "ผลเป็นยังไงครับ"),
  ("Wyniki będą jutro.", "phǒn àwk phrûng-níi khráp", "ผลออกพรุ่งนี้ครับ")],
 ["badanie krwi", "owoc", "egzamin"], []),

("A2", "zasada", "kòt", "กฎ", GU, "Pojęcia", 3, "f",
 "„kòt mǎai” to prawo, „kòt rá-bìap” to regulamin — częste na tablicach informacyjnych.",
 "",
 [("Taka jest zasada.", "pen kòt khráp", "เป็นกฎครับ"),
  ("To jest wbrew prawu.", "phìt kòt mǎai khráp", "ผิดกฎหมายครับ")],
 ["prawnik", "policja", "wolno"], ["reguła"]),

("A2", "część", "sùan", "ส่วน", GU, "Pojęcia", 3, "n",
 "„sùan tua” to „prywatny, osobisty”. „sùan mâak” to „przeważnie”.",
 "",
 [("Ta część jest ważna.", "sùan níi sǎm-khan khráp", "ส่วนนี้สำคัญครับ"),
  ("Przeważnie tak.", "sùan mâak kâw châi khráp", "ส่วนมากก็ใช่ครับ")],
 ["ważny", "połowa", "przeważnie"], []),

("A2", "wzór", "bàep", "แบบ", GU, "Pojęcia", 4, "n",
 "„bàep níi” to „w ten sposób, taki jak ten” — bardzo częste przy pokazywaniu w sklepie.",
 "",
 [("Poproszę taki wzór.", "khǎw bàep níi khráp", "ขอแบบนี้ครับ"),
  ("Czy jest inny model?", "mii bàep ùen mǎi khráp", "มีแบบอื่นไหมครับ")],
 ["formularz", "rozmiar", "inny"], ["model"]),

("A2", "kolejność", "lam-dàp", "ลำดับ", GU, "Pojęcia", 2, "f",
 "„taam lam-dàp” to „po kolei” — przydatne w urzędzie i przy kolejce.",
 "",
 [("Po kolei, proszę.", "taam lam-dàp khráp", "ตามลำดับครับ"),
  ("Jaka jest moja kolejka?", "khiu thîi thâo-rài khráp", "คิวที่เท่าไหร่ครับ")],
 ["kolejka", "według", "pierwszy"], []),

# ---------------------------------------------------------------- czas wolny
("A2", "hobby", "ngaan à-dì-rèek", "งานอดิเรก", ST, "Czas wolny", 3, "f",
 "Częste pytanie w small talku obok „châwp tham à-rai” — co lubisz robić.",
 "praca dodatkowa",
 [("Jakie ma pan hobby?", "ngaan à-dì-rèek khǎwng khun khue à-rai khráp", "งานอดิเรกของคุณคืออะไรครับ"),
  ("Moim hobby jest gotowanie.", "ngaan à-dì-rèek phǒm khue tham aa-hǎan khráp", "งานอดิเรกผมคือทำอาหารครับ")],
 ["lubić", "gotować", "praca"], []),

("A2", "film", "nǎng", "หนัง", ST, "Czas wolny", 4, "n",
 "„duu nǎng” to obejrzeć film. To samo słowo znaczy „skóra”.",
 "",
 [("Idziemy na film?", "pai duu nǎng mǎi khráp", "ไปดูหนังไหมครับ"),
  ("Ten film jest dobry.", "nǎng rûeang níi dii khráp", "หนังเรื่องนี้ดีครับ")],
 ["skóra (materiał)", "sprawa", "oglądać"], []),

("A2", "muzyka", "phleeng", "เพลง", ST, "Czas wolny", 4, "n",
 "„phleeng” to konkretna piosenka; „don-trii” to muzyka jako dziedzina.",
 "",
 [("Lubię tę piosenkę.", "phǒm châwp phleeng níi khráp", "ผมชอบเพลงนี้ครับ"),
  ("Proszę ściszyć muzykę.", "chûai bao phleeng nòi khráp", "ช่วยเบาเพลงหน่อยครับ")],
 ["słuchać", "głośnik", "głośny"], ["piosenka"]),

("A2", "książka", "nǎng-sǔe", "หนังสือ", ST, "Czas wolny", 4, "n",
 "„àan nǎng-sǔe” to czytać książkę, ale też „uczyć się” w mowie potocznej.",
 "",
 [("Czytam książkę.", "phǒm àan nǎng-sǔe khráp", "ผมอ่านหนังสือครับ"),
  ("Muszę się pouczyć.", "phǒm tâwng àan nǎng-sǔe khráp", "ผมต้องอ่านหนังสือครับ")],
 ["czytać", "uczyć się", "zeszyt"], []),

("A2", "gra", "kem", "เกม", ST, "Czas wolny", 3, "n",
 "Zapożyczenie z angielskiego. „lên kem” — grać w grę; „lên” to grać i bawić się.",
 "",
 [("Gram w grę.", "phǒm lên kem khráp", "ผมเล่นเกมครับ"),
  ("Zagramy?", "lên kem kan mǎi khráp", "เล่นเกมกันไหมครับ")],
 ["bawić się", "telefon"], []),

("A2", "sport", "kii-laa", "กีฬา", ST, "Czas wolny", 3, "n",
 "„nák kii-laa” to sportowiec — znów przedrostek „nák”.",
 "",
 [("Lubię sport.", "phǒm châwp kii-laa khráp", "ผมชอบกีฬาครับ"),
  ("Jaki sport pan uprawia?", "lên kii-laa à-rai khráp", "เล่นกีฬาอะไรครับ")],
 ["ćwiczyć", "piłka nożna", "uczeń"], []),

("A2", "piłka nożna", "fút-bawn", "ฟุตบอล", ST, "Czas wolny", 3, "n",
 "Skracane do „bawn”. „tè bawn” to grać w piłkę.",
 "",
 [("Gram w piłkę.", "phǒm tè bawn khráp", "ผมเตะบอลครับ"),
  ("Oglądam mecz.", "phǒm duu bawn khráp", "ผมดูบอลครับ")],
 ["kopać (nogą)", "sport", "oglądać"], []),

("A2", "masaż", "nûat", "นวด", ST, "Czas wolny", 4, "n",
 "„nûat thai” to masaż tajski, „nûat fáo tháo” to masaż stóp. Ceny bardzo przystępne.",
 "",
 [("Chcę masaż tajski.", "phǒm yàak nûat thai khráp", "ผมอยากนวดไทยครับ"),
  ("Za mocno.", "raeng koen pai khráp", "แรงเกินไปครับ")],
 ["stopa", "plecy", "mocny"], []),

("A2", "wycieczka", "thîao", "เที่ยว", ST, "Czas wolny", 5, "n",
 "„pai thîao” to „jechać na wycieczkę, wyjść się zabawić” — jedno z najczęstszych słów w small talku.",
 "",
 [("Jadę na wycieczkę.", "phǒm pai thîao khráp", "ผมไปเที่ยวครับ"),
  ("Dokąd pan jedzie?", "pai thîao thîi nǎi khráp", "ไปเที่ยวที่ไหนครับ")],
 ["podróżować", "wyspa", "urlop"], []),

("A2", "pamiątka", "khǎwng thîi rá-lúek", "ของที่ระลึก", ST, "Czas wolny", 3, "n",
 "„khǎwng” to rzecz. „khǎwng fàak” to prezent przywieziony z podróży — obyczaj bardzo silny.",
 "rzecz do wspominać",
 [("Kupię pamiątkę.", "phǒm jà súe khǎwng thîi rá-lúek khráp", "ผมจะซื้อของที่ระลึกครับ"),
  ("To dla ciebie z podróży.", "khǎwng fàak khráp", "ของฝากครับ")],
 ["prezent", "kupować", "podróżować"], []),

("A2", "zdjęcie grupowe", "thàai rûup rûam", "ถ่ายรูปรวม", ST, "Czas wolny", 2, "n",
 "„rûam” to wspólny — to samo słowo w „phûean rûam ngaan”.",
 "robić zdjęcie wspólny",
 [("Zróbmy wspólne zdjęcie.", "thàai rûup rûam kan mǎi khráp", "ถ่ายรูปรวมกันไหมครับ"),
  ("Czy może pan zrobić nam zdjęcie?", "chûai thàai rûup hâi nòi dâai mǎi khráp", "ช่วยถ่ายรูปให้หน่อยได้ไหมครับ")],
 ["zdjęcie", "aparat", "kolega z pracy"], []),

# ------------------------------------------------------------------ swieta
("A2", "święto", "wan sǎm-khan", "วันสำคัญ", CD, "Święta", 3, "f",
 "„wan yùt râat-chá-kaan” to dzień wolny od pracy urzędów — warto sprawdzać przed wizytą w banku.",
 "dzień ważny",
 [("Jutro jest święto.", "phrûng-níi wan yùt khráp", "พรุ่งนี้วันหยุดครับ"),
  ("Banki są zamknięte.", "thá-naa-khaan pìt khráp", "ธนาคารปิดครับ")],
 ["urlop", "bank", "zamknięty"], []),

("A2", "tajski Nowy Rok", "sǒng-kraan", "สงกรานต์", CD, "Święta", 3, "n",
 "Trzynasty do piętnastego kwietnia. Publiczne oblewanie się wodą — sprzęt elektroniczny warto zabezpieczyć.",
 "",
 [("Songkran jest w kwietniu.", "sǒng-kraan yùu duean mee-sǎa khráp", "สงกรานต์อยู่เดือนเมษาครับ"),
  ("Wszystkiego dobrego na Songkran.", "sùk sǎn wan sǒng-kraan khráp", "สุขสันต์วันสงกรานต์ครับ")],
 ["święto", "woda", "kwiecień"], []),

("A2", "święto Loy Krathong", "loi krà-thong", "ลอยกระทง", CD, "Święta", 2, "n",
 "Listopadowa pełnia księżyca — puszczanie na wodę koszyczków ze świecą.",
 "unosić koszyczek",
 [("Loy Krathong jest w listopadzie.", "loi krà-thong yùu duean phrúes-jì-kaa khráp", "ลอยกระทงอยู่เดือนพฤศจิกาครับ"),
  ("Puszczamy krathong.", "rao pai loi krà-thong khráp", "เราไปลอยกระทงครับ")],
 ["święto", "księżyc", "rzeka"], []),

("A2", "prezent", "khǎwng khwǎn", "ของขวัญ", ST, "Święta", 3, "n",
 "Prezent wręcza się i przyjmuje obiema rękami; otwiera się go zwykle później, nie przy dawcy.",
 "rzecz dar",
 [("To prezent dla pana.", "níi khǎwng khwǎn hâi khun khráp", "นี่ของขวัญให้คุณครับ"),
  ("Dziękuję za prezent.", "khàwp khun sǎm-ràp khǎwng khwǎn khráp", "ขอบคุณสำหรับของขวัญครับ")],
 ["pamiątka", "dawać", "dziękować"], []),

("A2", "przyjęcie", "ngaan líang", "งานเลี้ยง", ST, "Święta", 3, "n",
 "„líang” to czasownik „postawić komuś, ugościć” — kto zaprasza, ten zwykle płaci za wszystkich.",
 "uroczystość gościć",
 [("Idę na przyjęcie.", "phǒm pai ngaan líang khráp", "ผมไปงานเลี้ยงครับ"),
  ("Ja stawiam.", "phǒm líang eeng khráp", "ผมเลี้ยงเองครับ")],
 ["gość", "ślub", "płacić"], []),

("A2", "urodziny", "wan kòoet", "วันเกิด", CD, "Święta", 4, "n",
 "„kòoet” to rodzić się, powstawać. „kòoet à-rai khûen” — co się stało.",
 "dzień rodzić się",
 [("Kiedy ma pan urodziny?", "wan kòoet mûea-rài khráp", "วันเกิดเมื่อไหร่ครับ"),
  ("Dziś są moje urodziny.", "wan níi wan kòoet phǒm khráp", "วันนี้วันเกิดผมครับ")],
 ["szczęście (uczucie)", "prezent", "przyjęcie"], []),

# ------------------------------------------------------------- komunikacja
("A2", "rozmowa telefoniczna", "kaan thoo", "การโทร", ST, "Komunikacja", 3, "n",
 "„thoo” to dzwonić. „thoo klàp” to oddzwonić, „thoo maa” to zadzwonić do mnie.",
 "czynność dzwonić",
 [("Oddzwonię.", "phǒm jà thoo klàp khráp", "ผมจะโทรกลับครับ"),
  ("Proszę do mnie zadzwonić.", "thoo maa hǎa phǒm khráp", "โทรมาหาผมครับ")],
 ["dzwonić", "telefon", "wracać"], []),

("A2", "numer telefonu", "bòe thoo", "เบอร์โทร", ST, "Komunikacja", 4, "p",
 "„bòe” od angielskiego „number”. Wymiana numerów to standardowe zakończenie poznania.",
 "numer dzwonić",
 [("Jaki jest pana numer?", "bòe thoo à-rai khráp", "เบอร์โทรอะไรครับ"),
  ("Podam swój numer.", "phǒm hâi bòe khráp", "ผมให้เบอร์ครับ")],
 ["telefon", "dzwonić", "adres"], []),

("A2", "adres", "thîi yùu", "ที่อยู่", ST, "Komunikacja", 4, "n",
 "Dosłownie „miejsce przebywania”. Warto mieć zapisany po tajsku dla kierowcy.",
 "miejsce być",
 [("Jaki jest adres?", "thîi yùu à-rai khráp", "ที่อยู่อะไรครับ"),
  ("Proszę zapisać adres.", "chûai jòt thîi yùu hâi nòi khráp", "ช่วยจดที่อยู่ให้หน่อยครับ")],
 ["zapisywać", "kierowca", "dom"], []),

("A2", "poczta", "prai-sà-nii", "ไปรษณีย์", ST, "Komunikacja", 3, "f",
 "„sòng prai-sà-nii” to wysłać pocztą. Placówki oznaczone są kolorem żółto-czerwonym.",
 "",
 [("Gdzie jest poczta?", "prai-sà-nii yùu nǎi khráp", "ไปรษณีย์อยู่ไหนครับ"),
  ("Chcę wysłać paczkę.", "phǒm yàak sòng phát-sà-dù khráp", "ผมอยากส่งพัสดุครับ")],
 ["wysyłać", "paczka", "urząd"], []),

("A2", "paczka", "phát-sà-dù", "พัสดุ", ST, "Komunikacja", 3, "f",
 "Odbiór przesyłki wymaga zwykle dokumentu tożsamości.",
 "",
 [("Przyszła paczka.", "phát-sà-dù maa thǔeng láew khráp", "พัสดุมาถึงแล้วครับ"),
  ("Chcę odebrać paczkę.", "phǒm maa ráp phát-sà-dù khráp", "ผมมารับพัสดุครับ")],
 ["poczta", "wysyłać", "pudełko"], []),

("A2", "podpisać się (odbiór)", "sen ráp", "เซ็นรับ", ST, "Komunikacja", 2, "f",
 "„ráp” to odbierać, przyjmować — także „ráp dâai” (dam radę) i „ráp bàt” (przyjmujemy karty).",
 "podpisać odbierać",
 [("Proszę podpisać odbiór.", "sen ráp trong níi khráp", "เซ็นรับตรงนี้ครับ"),
  ("Odebrałem już.", "phǒm ráp láew khráp", "ผมรับแล้วครับ")],
 ["podpis", "paczka", "dokument"], []),

("A2", "tłumaczenie", "kaan plae", "การแปล", ST, "Komunikacja", 3, "n",
 "Znów „kaan” przed czasownikiem. „plae wâa à-rai” — jak to przetłumaczyć.",
 "czynność tłumaczyć",
 [("Potrzebuję tłumaczenia.", "phǒm tâwng kaan kaan plae khráp", "ผมต้องการการแปลครับ"),
  ("Jak to przetłumaczyć?", "plae wâa à-rai khráp", "แปลว่าอะไรครับ")],
 ["tłumaczyć", "język (mowa)", "słownik"], []),

("A2", "akcent (wymowa)", "sǎm niang", "สำเนียง", ST, "Komunikacja", 2, "n",
 "Tajowie chwalą wymowę obcokrajowców bardzo chętnie — komplement „phûut chát” jest częsty.",
 "",
 [("Mam obcy akcent.", "phǒm mii sǎm niang tàang châat khráp", "ผมมีสำเนียงต่างชาติครับ"),
  ("Mówi pan wyraźnie.", "khun phûut chát khráp", "คุณพูดชัดครับ")],
 ["mówić", "język (mowa)", "wyraźny"], []),

("A2", "wymawiać", "àwk sǐang", "ออกเสียง", ST, "Komunikacja", 3, "n",
 "Dosłownie „wypuszczać dźwięk”. „sǐang” to głos, dźwięk i ton.",
 "wychodzić dźwięk",
 [("Jak to się wymawia?", "àwk sǐang yang-ngai khráp", "ออกเสียงยังไงครับ"),
  ("Proszę powtórzyć.", "phûut ìik khráng dâai mǎi khráp", "พูดอีกครั้งได้ไหมครับ")],
 ["mówić", "ton", "powtarzać"], []),

("A2", "ton (w wymowie)", "sǐang wan-ná-yúk", "เสียงวรรณยุกต์", ST, "Komunikacja", 2, "f",
 "Tajski ma pięć tonów: równy, niski, opadający, wysoki i rosnący. Ton zmienia znaczenie słowa całkowicie.",
 "dźwięk znak tonu",
 [("Tajski ma pięć tonów.", "phaa-sǎa thai mii hâa sǐang khráp", "ภาษาไทยมีห้าเสียงครับ"),
  ("Mam problem z tonami.", "phǒm mii pan-hǎa rûeang sǐang khráp", "ผมมีปัญหาเรื่องเสียงครับ")],
 ["wymawiać", "język (mowa)", "problem"], []),

# ------------------------------------------------------------------ pogoda
("A2", "pora deszczowa", "nâa fǒn", "หน้าฝน", PP, "Pory roku", 4, "n",
 "„nâa” tu znaczy „sezon”. Trzy pory: nâa fǒn (deszczowa), nâa nǎao (chłodna), nâa ráwn (gorąca).",
 "sezon deszcz",
 [("Teraz jest pora deszczowa.", "tawn níi nâa fǒn khráp", "ตอนนี้หน้าฝนครับ"),
  ("W porze deszczowej pada codziennie.", "nâa fǒn fǒn tòk thúk wan khráp", "หน้าฝนฝนตกทุกวันครับ")],
 ["deszcz", "pora sucha", "parasol"], []),

("A2", "pora chłodna", "nâa nǎao", "หน้าหนาว", PP, "Pory roku", 3, "n",
 "Od listopada do lutego. Na północy bywa naprawdę zimno nocą — w Bangkoku to raczej ulga.",
 "sezon zimno",
 [("Pora chłodna jest przyjemna.", "nâa nǎao aa-kàat dii khráp", "หน้าหนาวอากาศดีครับ"),
  ("Na północy jest zimno.", "phâak nǔea nǎao khráp", "ภาคเหนือหนาวครับ")],
 ["pora deszczowa", "zimno", "pogoda"], []),

("A2", "pora gorąca", "nâa ráwn", "หน้าร้อน", PP, "Pory roku", 3, "n",
 "Od marca do maja, szczyt upałów w kwietniu — stąd Songkran z wodą właśnie wtedy.",
 "sezon gorąco",
 [("W porze gorącej jest bardzo ciepło.", "nâa ráwn ráwn mâak khráp", "หน้าร้อนร้อนมากครับ"),
  ("Nie znoszę upału.", "phǒm thon ráwn mâi dâai khráp", "ผมทนร้อนไม่ได้ครับ")],
 ["gorąco", "tajski Nowy Rok", "pora chłodna"], []),

("A2", "burza", "phaa-yú", "พายุ", PP, "Pogoda", 3, "n",
 "„phaa-yú fǒn” to burza z deszczem. Komunikaty o burzach dotyczą też promów.",
 "",
 [("Nadchodzi burza.", "phaa-yú kam-lang maa khráp", "พายุกำลังมาครับ"),
  ("Prom odwołany przez burzę.", "ruea yók lôoek phráw phaa-yú khráp", "เรือยกเลิกเพราะพายุครับ")],
 ["deszcz", "prom", "odwoływać"], []),

("A2", "powódź", "nám thûam", "น้ำท่วม", PP, "Pogoda", 3, "n",
 "„thûam” znaczy zalewać. Coroczny problem w porze deszczowej, także w Bangkoku.",
 "woda zalewać",
 [("Ulica jest zalana.", "thà-nǒn nám thûam khráp", "ถนนน้ำท่วมครับ"),
  ("Była powódź.", "nám thûam khráp", "น้ำท่วมครับ")],
 ["deszcz", "ulica", "pora deszczowa"], []),

("A2", "wilgotno", "chúen", "ชื้น", PP, "Pogoda", 3, "n",
 "„aa-kàat chúen” to duszne, wilgotne powietrze — typowe przed deszczem.",
 "",
 [("Jest wilgotno.", "aa-kàat chúen khráp", "อากาศชื้นครับ"),
  ("Ubranie nie chce wyschnąć.", "sûea phâa mâi hâeng khráp", "เสื้อผ้าไม่แห้งครับ")],
 ["mokry", "suchy", "powietrze"], []),

("A2", "wiatr", "lom", "ลม", PP, "Pogoda", 4, "n",
 "„phát lom” to wentylator — dosłownie „dmuchać wiatr”.",
 "",
 [("Wieje wiatr.", "lom raeng khráp", "ลมแรงครับ"),
  ("Nie ma wiatru.", "mâi mii lom khráp", "ไม่มีลมครับ")],
 ["wentylator", "burza", "mocny"], []),

("A2", "prognoza pogody", "phá-yaa-kawn aa-kàat", "พยากรณ์อากาศ", PP, "Pogoda", 2, "f",
 "Słowo z telewizji i aplikacji. W mowie zwykle pyta się wprost: „phrûng-níi fǒn tòk mǎi”.",
 "przepowiadać pogoda",
 [("Sprawdzę prognozę.", "phǒm jà duu phá-yaa-kawn aa-kàat khráp", "ผมจะดูพยากรณ์อากาศครับ"),
  ("Czy jutro będzie padać?", "phrûng-níi fǒn tòk mǎi khráp", "พรุ่งนี้ฝนตกไหมครับ")],
 ["pogoda", "deszcz", "jutro"], []),
]
