# -*- coding: utf-8 -*-
"""Leksyka etapu 5 (B2) — czesc F.

Zakres: zycie osoby mieszkajacej w Tajlandii na stale. Urzad imigracyjny
i wiza, meldunek, prawo jazdy, bank i podatki, dlugoterminowy najem, rachunki,
sasiedzi i wspolnota, szkola dziecka, opieka zdrowotna i ubezpieczenie.

Format jak w lex_b2_core_a.py.
"""

CORE_F = [

# =====================================================================
# WIZA I IMIGRACJA
# =====================================================================
("chciałbym przedłużyć wizę", "phǒm yàak tàw wii-sâa khráp", "ผมอยากต่อวีซ่าครับ",
 "Praca i nauka", "Wiza", "sentence", 5, "f",
 "„tàw” = przedłużyć ważność. Ten sam czasownik dotyczy prawa jazdy i abonamentu.", "",
 ("Chciałbym przedłużyć wizę o kolejny rok.", "phǒm yàak tàw wii-sâa ìik nùeng pii khráp", "ผมอยากต่อวีซ่าอีกหนึ่งปีครับ")),
("kiedy wygasa moja wiza?", "wii-sâa phǒm mòt aa-yú mûea rài khráp", "วีซ่าผมหมดอายุเมื่อไหร่ครับ",
 "Praca i nauka", "Wiza", "sentence", 4, "f", "", "",
 ("Kiedy wygasa moja wiza według pieczątki?", "duu jàak traa prà-táp wii-sâa phǒm mòt aa-yú mûea rài khráp", "ดูจากตราประทับวีซ่าผมหมดอายุเมื่อไหร่ครับ")),
("muszę zgłosić się co dziewięćdziesiąt dni", "tâwng raai-ngaan tua thúk kâo sìp wan khráp", "ต้องรายงานตัวทุกเก้าสิบวันครับ",
 "Praca i nauka", "Wiza", "sentence", 4, "f",
 "„raai-ngaan tua” = zameldować się osobiście. Obowiązek każdego długoterminowego rezydenta.", "raportować ciało",
 ("Muszę zgłosić się co dziewięćdziesiąt dni w imigracyjnym.", "tâwng raai-ngaan tua thúk kâo sìp wan thîi tròot khon khâo mueang khráp", "ต้องรายงานตัวทุกเก้าสิบวันที่ตรวจคนเข้าเมืองครับ")),
("spóźniłem się ze zgłoszeniem", "phǒm raai-ngaan tua cháa khráp", "ผมรายงานตัวช้าครับ",
 "Praca i nauka", "Wiza", "sentence", 3, "f", "", "",
 ("Spóźniłem się ze zgłoszeniem o tydzień, co teraz?", "phǒm raai-ngaan tua cháa nùeng aa-thít tâwng tham yang-ngai khráp", "ผมรายงานตัวช้าหนึ่งอาทิตย์ ต้องทำยังไงครับ")),
("czy grozi mi kara?", "phǒm jà thùuk pràp mǎi khráp", "ผมจะถูกปรับไหมครับ", "Praca i nauka", "Wiza", "sentence", 4, "f",
 "„pràp” = grzywna. Przy przekroczeniu terminu pobytu naliczana jest za każdy dzień.", "",
 ("Czy grozi mi kara za te dni po terminie?", "wan thîi koen maa phǒm jà thùuk pràp mǎi khráp", "วันที่เกินมาผมจะถูกปรับไหมครับ")),
("potrzebuję zaświadczenia o miejscu zamieszkania", "phǒm tâwng-kaan bai rap-rawng thîi phák khráp", "ผมต้องการใบรับรองที่พักครับ",
 "Praca i nauka", "Wiza", "sentence", 3, "f",
 "„bai rap-rawng thîi phák” to dokument potrzebny do prawa jazdy i konta w banku.", "",
 ("Potrzebuję zaświadczenia o miejscu zamieszkania do prawa jazdy.", "phǒm tâwng-kaan bai rap-rawng thîi phák phûea tham bai khàp khìi khráp", "ผมต้องการใบรับรองที่พักเพื่อทำใบขับขี่ครับ")),
("wyjeżdżam i wracam w tym miesiącu", "duean níi phǒm àwk nâwk láew klàp khâo maa khráp", "เดือนนี้ผมออกนอกแล้วกลับเข้ามาครับ",
 "Praca i nauka", "Wiza", "sentence", 3, "n", "", "",
 ("Wyjeżdżam i wracam w tym miesiącu, potrzebuję zgody na powrót.", "duean níi phǒm àwk nâwk láew klàp khâo maa tâwng tham rii-en-thrîi khráp", "เดือนนี้ผมออกนอกแล้วกลับเข้ามา ต้องทำรีเอ็นทรีครับ")),
("czy mogę tu legalnie pracować?", "phǒm tham-ngaan thîi nîi dâai thùuk kòt-mǎai mǎi khráp", "ผมทำงานที่นี่ได้ถูกกฎหมายไหมครับ",
 "Praca i nauka", "Wiza", "sentence", 4, "f", "", "",
 ("Czy mogę tu legalnie pracować z tą wizą?", "wii-sâa bàep níi phǒm tham-ngaan dâai thùuk kòt-mǎai mǎi khráp", "วีซ่าแบบนี้ผมทำงานได้ถูกกฎหมายไหมครับ")),
("kto wystawia pozwolenie na pracę?", "bai à-nú-yâat tham-ngaan àwk hâi thîi nǎi khráp", "ใบอนุญาตทำงานออกให้ที่ไหนครับ",
 "Praca i nauka", "Wiza", "sentence", 3, "f", "", "",
 ("Kto wystawia pozwolenie na pracę — pracodawca czy urząd?", "bai à-nú-yâat tham-ngaan naai jâang rǔe rát àwk hâi khráp", "ใบอนุญาตทำงานนายจ้างหรือรัฐออกให้ครับ")),
("proszę o kolejkę do okienka", "khǎw bàt khiu khráp", "ขอบัตรคิวครับ", "Praca i nauka", "Urząd", "sentence", 4, "n",
 "„bàt khiu” = numerek kolejkowy. W tajskim urzędzie pobiera się go zawsze na wejściu.", "",
 ("Proszę o kolejkę do okienka wizowego.", "khǎw bàt khiu châwng wii-sâa khráp", "ขอบัตรคิวช่องวีซ่าครับ")),
("do której godziny przyjmujecie?", "ráp khâm rǎwng thǔeng kìi moong khráp", "รับคำร้องถึงกี่โมงครับ",
 "Praca i nauka", "Urząd", "sentence", 4, "f", "", "",
 ("Do której godziny przyjmujecie wnioski w piątki?", "wan sùk ráp khâm rǎwng thǔeng kìi moong khráp", "วันศุกร์รับคำร้องถึงกี่โมงครับ")),
("czy jest tu ktoś mówiący po angielsku?", "mii jâo nâa thîi phûut phaa-sǎa ang-krìt mǎi khráp", "มีเจ้าหน้าที่พูดภาษาอังกฤษไหมครับ",
 "Praca i nauka", "Urząd", "sentence", 4, "f", "", "",
 ("Czy jest tu ktoś mówiący po angielsku do trudnych spraw?", "rûeang yâak yâak mii jâo nâa thîi phûut ang-krìt mǎi khráp", "เรื่องยากๆ มีเจ้าหน้าที่พูดอังกฤษไหมครับ")),

# =====================================================================
# BANK, PODATKI, RACHUNKI
# =====================================================================
("chciałbym otworzyć konto", "phǒm yàak pòoet ban-chii khráp", "ผมอยากเปิดบัญชีครับ",
 "Zakupy i pieniądze", "Bank", "sentence", 4, "f", "", "",
 ("Chciałbym otworzyć konto oszczędnościowe.", "phǒm yàak pòoet ban-chii àwm sáp khráp", "ผมอยากเปิดบัญชีออมทรัพย์ครับ")),
("jakie są opłaty miesięczne?", "khâa tham-niam raai duean thâo-rài khráp", "ค่าธรรมเนียมรายเดือนเท่าไหร่ครับ",
 "Zakupy i pieniądze", "Bank", "sentence", 4, "f", "", "",
 ("Jakie są opłaty miesięczne za tę kartę?", "bàt níi khâa tham-niam raai duean thâo-rài khráp", "บัตรนี้ค่าธรรมเนียมรายเดือนเท่าไหร่ครับ")),
("przelew nie doszedł", "ngoen oon yang mâi khâo khráp", "เงินโอนยังไม่เข้าครับ",
 "Zakupy i pieniądze", "Bank", "sentence", 4, "n", "", "",
 ("Przelew nie doszedł, minęły dwa dni.", "ngoen oon yang mâi khâo khráp phàan maa sǎwng wan láew", "เงินโอนยังไม่เข้าครับ ผ่านมาสองวันแล้ว")),
("zablokowano mi kartę", "bàt phǒm thùuk lák khráp", "บัตรผมถูกล็อกครับ", "Zakupy i pieniądze", "Bank", "sentence", 3, "n", "", "",
 ("Zablokowano mi kartę po płatności zagranicznej.", "bàt phǒm thùuk lák lǎng jàak jàai tàang prà-thêet khráp", "บัตรผมถูกล็อกหลังจากจ่ายต่างประเทศครับ")),
("chcę zgłosić podejrzaną transakcję", "phǒm yàak jâeng raai kaan thîi nâa sǒng-sǎi khráp", "ผมอยากแจ้งรายการที่น่าสงสัยครับ",
 "Zakupy i pieniądze", "Bank", "sentence", 3, "f", "", "",
 ("Chcę zgłosić podejrzaną transakcję z wczoraj.", "phǒm yàak jâeng raai kaan nâa sǒng-sǎi mûea waan khráp", "ผมอยากแจ้งรายการน่าสงสัยเมื่อวานครับ")),
("czy muszę płacić tu podatek?", "phǒm tâwng sǐa phaa-sǐi thîi níi mǎi khráp", "ผมต้องเสียภาษีที่นี่ไหมครับ",
 "Praca i nauka", "Podatki", "sentence", 3, "f",
 "„sǐa phaa-sǐi” = płacić podatek, dosłownie „stracić na podatek”. Tak samo mówi się o opłatach.", "",
 ("Czy muszę płacić tu podatek od dochodu z zagranicy?", "raai dâai jàak tàang prà-thêet phǒm tâwng sǐa phaa-sǐi thîi níi mǎi khráp", "รายได้จากต่างประเทศผมต้องเสียภาษีที่นี่ไหมครับ")),
("potrzebuję numeru podatkowego", "phǒm tâwng-kaan lêek prà-jam tua phûu sǐa phaa-sǐi khráp", "ผมต้องการเลขประจำตัวผู้เสียภาษีครับ",
 "Praca i nauka", "Podatki", "sentence", 3, "f", "", "",
 ("Potrzebuję numeru podatkowego do umowy.", "phǒm tâwng-kaan lêek prà-jam tua phûu sǐa phaa-sǐi phûea tham sǎn-yaa khráp", "ผมต้องการเลขประจำตัวผู้เสียภาษีเพื่อทำสัญญาครับ")),
("rachunek za prąd jest wyższy niż zwykle", "khâa fai duean níi phaeng kwàa pòk-kà-tì khráp", "ค่าไฟเดือนนี้แพงกว่าปกติครับ",
 "Dom i codzienność", "Rachunki", "sentence", 4, "n", "", "",
 ("Rachunek za prąd jest wyższy niż zwykle o połowę.", "khâa fai duean níi phaeng kwàa pòk-kà-tì khrûeng nùeng khráp", "ค่าไฟเดือนนี้แพงกว่าปกติครึ่งหนึ่งครับ")),
("gdzie zapłacę rachunek za wodę?", "jàai khâa náam dâai thîi nǎi khráp", "จ่ายค่าน้ำได้ที่ไหนครับ",
 "Dom i codzienność", "Rachunki", "sentence", 4, "n",
 "W Tajlandii rachunki płaci się często w sklepie całodobowym — wystarczy kod kreskowy.", "",
 ("Gdzie zapłacę rachunek za wodę poza bankiem?", "nâwk jàak thá-naa-khaan jàai khâa náam dâai thîi nǎi khráp", "นอกจากธนาคารจ่ายค่าน้ำได้ที่ไหนครับ")),
("chcę ustawić płatność automatyczną", "phǒm yàak tâng jàai àt-tà-noo-mát khráp", "ผมอยากตั้งจ่ายอัตโนมัติครับ",
 "Zakupy i pieniądze", "Rachunki", "sentence", 3, "f", "", "",
 ("Chcę ustawić płatność automatyczną za internet.", "phǒm yàak tâng jàai àt-tà-noo-mát khâa nét khráp", "ผมอยากตั้งจ่ายอัตโนมัติค่าเน็ตครับ")),
("dostałem wezwanie do zapłaty", "phǒm dâai bai jâeng nîi khráp", "ผมได้ใบแจ้งหนี้ครับ",
 "Zakupy i pieniądze", "Rachunki", "sentence", 3, "f", "", "",
 ("Dostałem wezwanie do zapłaty, choć zapłaciłem.", "phǒm dâai bai jâeng nîi thóng thîi jàai pai láew khráp", "ผมได้ใบแจ้งหนี้ทั้งที่จ่ายไปแล้วครับ")),

# =====================================================================
# DLUGOTERMINOWY NAJEM
# =====================================================================
("szukam mieszkania na rok", "phǒm hǎa hâwng châo raai pii khráp", "ผมหาห้องเช่ารายปีครับ",
 "Dom i codzienność", "Najem", "sentence", 4, "n", "", "",
 ("Szukam mieszkania na rok blisko stacji.", "phǒm hǎa hâwng châo raai pii klâi sà-thǎa-nii khráp", "ผมหาห้องเช่ารายปีใกล้สถานีครับ")),
("ile wynosi kaucja?", "khâa mát jam thâo-rài khráp", "ค่ามัดจำเท่าไหร่ครับ", "Dom i codzienność", "Najem", "sentence", 4, "n",
 "„mát jam” = kaucja. Zwykle dwa czynsze plus jeden z góry.", "",
 ("Ile wynosi kaucja i kiedy ją zwracacie?", "khâa mát jam thâo-rài láe khuen mûea rài khráp", "ค่ามัดจำเท่าไหร่และคืนเมื่อไหร่ครับ")),
("czy czynsz obejmuje prąd?", "khâa châo ruam khâa fai mǎi khráp", "ค่าเช่ารวมค่าไฟไหมครับ",
 "Dom i codzienność", "Najem", "sentence", 5, "n", "", "",
 ("Czy czynsz obejmuje prąd i wodę?", "khâa châo ruam khâa fai kàp khâa náam mǎi khráp", "ค่าเช่ารวมค่าไฟกับค่าน้ำไหมครับ")),
("chciałbym przeczytać umowę przed podpisaniem", "khǎw àan sǎn-yaa kàwn sen khráp", "ขออ่านสัญญาก่อนเซ็นครับ",
 "Dom i codzienność", "Najem", "sentence", 4, "f",
 "Zdanie warte zapamiętania w całości. Podpisanie bez czytania jest w Tajlandii wiążące.", "",
 ("Chciałbym przeczytać umowę przed podpisaniem, w spokoju.", "khǎw àan sǎn-yaa kàwn sen khráp khǎw wee-laa nòi", "ขออ่านสัญญาก่อนเซ็นครับ ขอเวลาหน่อย")),
("co się stanie, jeśli wyprowadzę się wcześniej?", "thâa yáai àwk kàwn kam-nòt jà pen yang-ngai khráp", "ถ้าย้ายออกก่อนกำหนดจะเป็นยังไงครับ",
 "Dom i codzienność", "Najem", "sentence", 4, "f", "", "",
 ("Co się stanie z kaucją, jeśli wyprowadzę się wcześniej?", "thâa yáai àwk kàwn kam-nòt khâa mát jam jà pen yang-ngai khráp", "ถ้าย้ายออกก่อนกำหนดค่ามัดจำจะเป็นยังไงครับ")),
("kto płaci za naprawy?", "khâa sâwm khrai àwk khráp", "ค่าซ่อมใครออกครับ", "Dom i codzienność", "Najem", "sentence", 4, "n",
 "„àwk” w kontekście pieniędzy = pokryć koszt. Bardzo częste użycie.", "",
 ("Kto płaci za naprawy klimatyzacji — ja czy właściciel?", "khâa sâwm aae khrai àwk khráp phǒm rǔe jâo khǎwng", "ค่าซ่อมแอร์ใครออกครับ ผมหรือเจ้าของ")),
("chcę przedłużyć umowę najmu", "phǒm yàak tàw sǎn-yaa châo khráp", "ผมอยากต่อสัญญาเช่าครับ",
 "Dom i codzienność", "Najem", "sentence", 4, "f", "", "",
 ("Chcę przedłużyć umowę najmu na tych samych warunkach.", "phǒm yàak tàw sǎn-yaa châo ngûean-khǎi doem khráp", "ผมอยากต่อสัญญาเช่าเงื่อนไขเดิมครับ")),
("czy można negocjować czynsz?", "khâa châo tàw rawng dâai mǎi khráp", "ค่าเช่าต่อรองได้ไหมครับ",
 "Dom i codzienność", "Najem", "sentence", 4, "n",
 "„tàw rawng” = negocjować. Przy najmie długoterminowym w Tajlandii to zupełnie normalne.", "",
 ("Czy można negocjować czynsz przy dwuletniej umowie?", "sǎn-yaa sǎwng pii khâa châo tàw rawng dâai mǎi khráp", "สัญญาสองปีค่าเช่าต่อรองได้ไหมครับ")),
("proszę o protokół zdawczo-odbiorczy", "khǎw bai trùat sà-phâap hâwng khráp", "ขอใบตรวจสภาพห้องครับ",
 "Dom i codzienność", "Najem", "sentence", 3, "f",
 "Spisanie stanu mieszkania chroni kaucję. Zrób to razem z właścicielem i ze zdjęciami.", "",
 ("Proszę o protokół zdawczo-odbiorczy ze zdjęciami.", "khǎw bai trùat sà-phâap hâwng phráwm rûup thàai khráp", "ขอใบตรวจสภาพห้องพร้อมรูปถ่ายครับ")),
("w mieszkaniu jest wilgoć", "nai hâwng chúen mâak khráp", "ในห้องชื้นมากครับ", "Dom i codzienność", "Najem", "sentence", 3, "n", "", "",
 ("W mieszkaniu jest wilgoć i pojawia się pleśń.", "nai hâwng chúen mâak jon khûen raa khráp", "ในห้องชื้นมากจนขึ้นราครับ")),

# =====================================================================
# SASIEDZI I WSPOLNOTA
# =====================================================================
("sąsiedzi hałasują po nocy", "phûean bâan sǐang dang tawn klaang khuen khráp", "เพื่อนบ้านเสียงดังตอนกลางคืนครับ",
 "Dom i codzienność", "Sąsiedzi", "sentence", 4, "n", "", "",
 ("Sąsiedzi hałasują po nocy prawie codziennie.", "phûean bâan sǐang dang tawn klaang khuen kùeap thúk wan khráp", "เพื่อนบ้านเสียงดังตอนกลางคืนเกือบทุกวันครับ")),
("czy mógłby pan ściszyć?", "chûai bao sǐang long nòi dâai mǎi khráp", "ช่วยเบาเสียงลงหน่อยได้ไหมครับ",
 "Dom i codzienność", "Sąsiedzi", "sentence", 4, "n",
 "Zwracaj się bezpośrednio i z uśmiechem. Skarga przez ochronę bez próby rozmowy bywa źle odbierana.", "",
 ("Czy mógłby pan ściszyć po dziesiątej wieczorem?", "lǎng sìi thûm chûai bao sǐang long nòi dâai mǎi khráp", "หลังสี่ทุ่มช่วยเบาเสียงลงหน่อยได้ไหมครับ")),
("zgłoszę to do ochrony", "phǒm jà jâeng yaam khráp", "ผมจะแจ้งยามครับ", "Dom i codzienność", "Sąsiedzi", "sentence", 3, "n", "", "",
 ("Zgłoszę to do ochrony, jeśli się powtórzy.", "thâa pen ìik phǒm jà jâeng yaam khráp", "ถ้าเป็นอีกผมจะแจ้งยามครับ")),
("kto zarządza budynkiem?", "khrai duu-lae aa-khaan khráp", "ใครดูแลอาคารครับ", "Dom i codzienność", "Sąsiedzi", "sentence", 3, "n", "", "",
 ("Kto zarządza budynkiem i gdzie jest biuro?", "khrai duu-lae aa-khaan láe àwf-fít yùu nǎi khráp", "ใครดูแลอาคารและออฟฟิศอยู่ไหนครับ")),
("kiedy jest zebranie wspólnoty?", "prà-chum lûuk bâan mûea rài khráp", "ประชุมลูกบ้านเมื่อไหร่ครับ",
 "Dom i codzienność", "Sąsiedzi", "sentence", 3, "f", "", "",
 ("Kiedy jest zebranie wspólnoty w tym roku?", "pii níi prà-chum lûuk bâan mûea rài khráp", "ปีนี้ประชุมลูกบ้านเมื่อไหร่ครับ")),
("miło mi, wprowadziłem się obok", "yin dii thîi dâai rúu-jàk khráp phǒm yáai maa yùu khâang khâang", "ยินดีที่ได้รู้จักครับ ผมย้ายมาอยู่ข้างๆ",
 "Ludzie i rodzina", "Sąsiedzi", "sentence", 4, "n",
 "Przedstawienie się sąsiadom bardzo ułatwia późniejsze rozmowy o problemach.", "",
 ("Miło mi, wprowadziłem się obok w zeszłym tygodniu.", "yin dii thîi dâai rúu-jàk khráp phǒm phôoeng yáai maa aa-thít thîi láew", "ยินดีที่ได้รู้จักครับ ผมเพิ่งย้ายมาอาทิตย์ที่แล้ว")),
("czy tu jest bezpiecznie wieczorem?", "thǎew níi tawn yen plàwt-phai mǎi khráp", "แถวนี้ตอนเย็นปลอดภัยไหมครับ",
 "Miejsca i orientacja", "Sąsiedzi", "sentence", 3, "n", "", "",
 ("Czy tu jest bezpiecznie wieczorem dla dzieci?", "thǎew níi tawn yen plàwt-phai sǎm-ràp dèk mǎi khráp", "แถวนี้ตอนเย็นปลอดภัยสำหรับเด็กไหมครับ")),
("gdzie wyrzuca się śmieci segregowane?", "thíng khà-yà yâek prà-phêet thîi nǎi khráp", "ทิ้งขยะแยกประเภทที่ไหนครับ",
 "Dom i codzienność", "Sąsiedzi", "sentence", 3, "n", "", "",
 ("Gdzie wyrzuca się śmieci segregowane w tym budynku?", "aa-khaan níi thíng khà-yà yâek prà-phêet thîi nǎi khráp", "อาคารนี้ทิ้งขยะแยกประเภทที่ไหนครับ")),

# =====================================================================
# SZKOLA I DZIECI
# =====================================================================
("chciałbym zapisać dziecko do szkoły", "phǒm yàak sà-màk rian hâi lûuk khráp", "ผมอยากสมัครเรียนให้ลูกครับ",
 "Praca i nauka", "Szkoła", "sentence", 3, "f", "", "",
 ("Chciałbym zapisać dziecko do szkoły od nowego semestru.", "phǒm yàak sà-màk rian hâi lûuk tâng tàae thoem mài khráp", "ผมอยากสมัครเรียนให้ลูกตั้งแต่เทอมใหม่ครับ")),
("jakie dokumenty są potrzebne przy zapisie?", "sà-màk rian tâwng chái èek-kà-sǎan à-rai bâang khráp", "สมัครเรียนต้องใช้เอกสารอะไรบ้างครับ",
 "Praca i nauka", "Szkoła", "sentence", 3, "f", "", "",
 ("Jakie dokumenty są potrzebne przy zapisie obcokrajowca?", "dèk tàang châat sà-màk rian tâwng chái èek-kà-sǎan à-rai bâang khráp", "เด็กต่างชาติสมัครเรียนต้องใช้เอกสารอะไรบ้างครับ")),
("ile wynosi czesne za semestr?", "khâa thoem thâo-rài khráp", "ค่าเทอมเท่าไหร่ครับ", "Praca i nauka", "Szkoła", "sentence", 3, "n", "", "",
 ("Ile wynosi czesne za semestr razem z posiłkami?", "khâa thoem ruam khâa aa-hǎan thâo-rài khráp", "ค่าเทอมรวมค่าอาหารเท่าไหร่ครับ")),
("jak idzie mojemu dziecku?", "lûuk phǒm pen yang-ngai bâang khráp", "ลูกผมเป็นยังไงบ้างครับ",
 "Praca i nauka", "Szkoła", "sentence", 3, "n", "", "",
 ("Jak idzie mojemu dziecku z tajskim?", "lûuk phǒm rîan phaa-sǎa thai pen yang-ngai bâang khráp", "ลูกผมเรียนภาษาไทยเป็นยังไงบ้างครับ")),
("czy mogę porozmawiać z wychowawcą?", "khǎw khui kàp khruu prà-jam chán dâai mǎi khráp", "ขอคุยกับครูประจำชั้นได้ไหมครับ",
 "Praca i nauka", "Szkoła", "sentence", 3, "f", "", "",
 ("Czy mogę porozmawiać z wychowawcą po lekcjach?", "lôek rian láew khǎw khui kàp khruu prà-jam chán dâai mǎi khráp", "เลิกเรียนแล้วขอคุยกับครูประจำชั้นได้ไหมครับ")),
("dziecko jest chore i nie przyjdzie", "lûuk mâi sà-baai jà mâi pai rian khráp", "ลูกไม่สบายจะไม่ไปเรียนครับ",
 "Praca i nauka", "Szkoła", "sentence", 3, "n", "", "",
 ("Dziecko jest chore i nie przyjdzie dziś do szkoły.", "wan níi lûuk mâi sà-baai jà mâi pai rian khráp", "วันนี้ลูกไม่สบายจะไม่ไปเรียนครับ")),

# =====================================================================
# ZDROWIE I UBEZPIECZENIE
# =====================================================================
("czy przyjmujecie moje ubezpieczenie?", "ráp prà-kan khǎwng phǒm mǎi khráp", "รับประกันของผมไหมครับ",
 "Zdrowie", "Ubezpieczenie", "sentence", 4, "f",
 "Zapytaj o to w recepcji przed badaniem, nie po. Rozliczenie po fakcie bywa niemożliwe.", "",
 ("Czy przyjmujecie moje ubezpieczenie zagraniczne?", "ráp prà-kan tàang prà-thêet khǎwng phǒm mǎi khráp", "รับประกันต่างประเทศของผมไหมครับ")),
("czy muszę zapłacić z góry?", "tâwng sǎm-rawng jàai kàwn mǎi khráp", "ต้องสำรองจ่ายก่อนไหมครับ",
 "Zdrowie", "Ubezpieczenie", "sentence", 4, "f",
 "„sǎm-rawng jàai” = zapłacić z własnej kieszeni i odzyskać później. Kluczowe pojęcie przy ubezpieczeniu.", "",
 ("Czy muszę zapłacić z góry i potem się rozliczyć?", "tâwng sǎm-rawng jàai kàwn láew khôi khleem mǎi khráp", "ต้องสำรองจ่ายก่อนแล้วค่อยเคลมไหมครับ")),
("proszę o dokumentację do ubezpieczyciela", "khǎw èek-kà-sǎan sǎm-ràp khleem prà-kan khráp", "ขอเอกสารสำหรับเคลมประกันครับ",
 "Zdrowie", "Ubezpieczenie", "sentence", 3, "f", "", "",
 ("Proszę o dokumentację do ubezpieczyciela z opisem badania.", "khǎw èek-kà-sǎan sǎm-ràp khleem prà-kan phráwm phǒn trùat khráp", "ขอเอกสารสำหรับเคลมประกันพร้อมผลตรวจครับ")),
("chciałbym skierowanie do specjalisty", "khǎw bai sòng tua pai hǎa mǎw chá-phǎw thaang khráp", "ขอใบส่งตัวไปหาหมอเฉพาะทางครับ",
 "Zdrowie", "Lekarz", "sentence", 3, "f", "", "",
 ("Chciałbym skierowanie do specjalisty od kręgosłupa.", "khǎw bai sòng tua pai hǎa mǎw krà-dùuk sǎn lǎng khráp", "ขอใบส่งตัวไปหาหมอกระดูกสันหลังครับ")),
("czy ten lek jest refundowany?", "yaa tua níi prà-kan khrâwp khlum mǎi khráp", "ยาตัวนี้ประกันครอบคลุมไหมครับ",
 "Zdrowie", "Ubezpieczenie", "sentence", 3, "f", "", "",
 ("Czy ten lek jest refundowany, czy płacę sam?", "yaa tua níi prà-kan khrâwp khlum mǎi khráp rǔe jàai eeng", "ยาตัวนี้ประกันครอบคลุมไหมครับ หรือจ่ายเอง")),
("mam badania z zeszłego roku", "phǒm mii phǒn trùat pii thîi láew khráp", "ผมมีผลตรวจปีที่แล้วครับ",
 "Zdrowie", "Lekarz", "sentence", 3, "n", "", "",
 ("Mam badania z zeszłego roku, mogę pokazać.", "phǒm mii phǒn trùat pii thîi láew khǎw hâi duu khráp", "ผมมีผลตรวจปีที่แล้ว ขอให้ดูครับ")),
("od jak dawna to trwa?", "pen maa naan thâo-rài láew khráp", "เป็นมานานเท่าไหร่แล้วครับ",
 "Zdrowie", "Lekarz", "sentence", 4, "f", "", "",
 ("Od jak dawna to trwa i czy się nasila?", "pen maa naan thâo-rài láew láe nàk khûen mǎi khráp", "เป็นมานานเท่าไหร่แล้วและหนักขึ้นไหมครับ")),
("boli mnie przy poruszaniu", "pùat tawn khà-yàp khráp", "ปวดตอนขยับครับ", "Zdrowie", "Lekarz", "sentence", 4, "n",
 "Precyzja opisu bólu przyspiesza diagnozę: kiedy boli, jak boli, jak długo.", "",
 ("Boli mnie przy poruszaniu, w spoczynku prawie wcale.", "pùat tawn khà-yàp khráp tawn yùu chǒoei chǒoei mâi khâwi pùat", "ปวดตอนขยับครับ ตอนอยู่เฉยๆ ไม่ค่อยปวด")),
]
