# -*- coding: utf-8 -*-
"""Leksyka etapu 3 (A2) — czesc C.

Zakres: zdrowie, apteka i lekarz, wyglad i ubrania, dom i mieszkanie.

Format krotki jak w lex_a2_core_a.py.
"""

CORE_C = [

# =====================================================================
# ZDROWIE — objawy
# =====================================================================
("Źle się dziś czuję.", "wan níi phǒm mâi sà-baai khráp", "วันนี้ผมไม่สบายครับ",
 "Zdrowie", "Objawy", "phrase", 5, "n", "„mâi sà-baai” to uniwersalne „jestem chory”.", "",
 ("Od kiedy?", "tâng tàe mûea-rài khráp", "ตั้งแต่เมื่อไหร่ครับ")),
("Boli mnie głowa.", "phǒm pùat hǔa khráp", "ผมปวดหัวครับ",
 "Zdrowie", "Objawy", "phrase", 5, "n", "„pùat” = boleć (ból tępy, ciągły).", "",
 ("Weź coś przeciwbólowego.", "kin yaa kâe pùat khráp", "กินยาแก้ปวดครับ")),
("Boli mnie brzuch.", "phǒm pùat tháwng khráp", "ผมปวดท้องครับ",
 "Zdrowie", "Objawy", "phrase", 5, "n", "", "",
 ("Co jadłeś?", "kin à-rai maa khráp", "กินอะไรมาครับ")),
("Boli mnie gardło.", "phǒm jèp khaw khráp", "ผมเจ็บคอครับ",
 "Zdrowie", "Objawy", "phrase", 4, "n",
 "„jèp” to ból ostry, kłujący — inaczej niż „pùat”.", "jèp = ostry ból",
 ("Pij ciepłą wodę.", "dùem náam ùn ná khráp", "ดื่มน้ำอุ่นนะครับ")),
("Boli mnie ząb.", "phǒm pùat fan khráp", "ผมปวดฟันครับ",
 "Zdrowie", "Objawy", "phrase", 4, "n", "", "",
 ("Trzeba iść do dentysty.", "tâwng pai hǎa mǎw fan khráp", "ต้องไปหาหมอฟันครับ")),
("Boli mnie plecy.", "phǒm pùat lǎng khráp", "ผมปวดหลังครับ",
 "Zdrowie", "Objawy", "phrase", 4, "n", "", "",
 ("Może masaż pomoże.", "nûat àat jà chûai khráp", "นวดอาจจะช่วยครับ")),
("Mam gorączkę.", "phǒm pen khâi khráp", "ผมเป็นไข้ครับ",
 "Zdrowie", "Objawy", "phrase", 5, "n", "„pen” przed chorobą = chorować na coś.", "pen = chorować na",
 ("Zmierzę temperaturę.", "khǎw wát khâi khráp", "ขอวัดไข้ครับ")),
("Mam kaszel.", "phǒm ai khráp", "ผมไอครับ",
 "Zdrowie", "Objawy", "phrase", 4, "n", "", "",
 ("Suchy czy mokry?", "ai hâeng rǔe mii sěem-hà khráp", "ไอแห้งหรือมีเสมหะครับ")),
("Mam katar.", "phǒm náam mûuk lǎi khráp", "ผมน้ำมูกไหลครับ",
 "Zdrowie", "Objawy", "phrase", 4, "n", "", "dosłownie: śluz z nosa płynie",
 ("To pewnie przeziębienie.", "khong pen wàt khráp", "คงเป็นหวัดครับ")),
("Jestem przeziębiony.", "phǒm pen wàt khráp", "ผมเป็นหวัดครับ",
 "Zdrowie", "Objawy", "phrase", 4, "n", "", "",
 ("Odpocznij.", "phák phàwn ná khráp", "พักผ่อนนะครับ")),
("Kręci mi się w głowie.", "phǒm wian hǔa khráp", "ผมเวียนหัวครับ",
 "Zdrowie", "Objawy", "phrase", 4, "n", "", "",
 ("Usiądź na chwilę.", "nâng phák kàwn khráp", "นั่งพักก่อนครับ")),
("Jest mi niedobrze.", "phǒm khlûen sâi khráp", "ผมคลื่นไส้ครับ",
 "Zdrowie", "Objawy", "phrase", 4, "n", "„khlûen sâi” = mdłości.", "",
 ("Chcesz się położyć?", "yàak nawn mǎi khráp", "อยากนอนไหมครับ")),
("Zwymiotowałem.", "phǒm aa-jian khráp", "ผมอาเจียนครับ",
 "Zdrowie", "Objawy", "phrase", 3, "f", "", "",
 ("Ile razy?", "kìi khráng khráp", "กี่ครั้งครับ")),
("Mam biegunkę.", "phǒm tháwng sǐa khráp", "ผมท้องเสียครับ",
 "Zdrowie", "Objawy", "phrase", 4, "n", "Bardzo częsta dolegliwość podróżnych.", "",
 ("Pij dużo wody.", "dùem náam yóe yóe khráp", "ดื่มน้ำเยอะๆ ครับ")),
("Nie mam apetytu.", "phǒm mâi yàak aa-hǎan khráp", "ผมไม่อยากอาหารครับ",
 "Zdrowie", "Objawy", "phrase", 3, "n", "", "",
 ("Od kiedy?", "tâng tàe mûea-rài khráp", "ตั้งแต่เมื่อไหร่ครับ")),
("Nie mogę spać.", "phǒm nawn mâi làp khráp", "ผมนอนไม่หลับครับ",
 "Zdrowie", "Objawy", "phrase", 4, "n", "„làp” = zasnąć.", "",
 ("Od jak dawna?", "pen maa naan rǔe yang khráp", "เป็นมานานหรือยังครับ")),
("Jestem bardzo zmęczony.", "phǒm nùeai mâak khráp", "ผมเหนื่อยมากครับ",
 "Zdrowie", "Objawy", "phrase", 4, "n", "", "",
 ("Musisz odpocząć.", "tâwng phák phàwn khráp", "ต้องพักผ่อนครับ")),
("Skaleczyłem się.", "phǒm mîit bàat khráp", "ผมมีดบาดครับ",
 "Zdrowie", "Urazy", "phrase", 3, "n", "", "dosłownie: nóż zaciął",
 ("Pokaż rękę.", "khǎw duu mue nòi khráp", "ขอดูมือหน่อยครับ")),
("Skręciłem kostkę.", "phǒm khâw tháo phlík khráp", "ผมข้อเท้าพลิกครับ",
 "Zdrowie", "Urazy", "phrase", 3, "n", "", "",
 ("Spuchło?", "buam mǎi khráp", "บวมไหมครับ")),
("Spadłem ze skutera.", "phǒm tòk maw-toe-sai khráp", "ผมตกมอเตอร์ไซค์ครับ",
 "Zdrowie", "Urazy", "phrase", 3, "n", "", "",
 ("Trzeba to opatrzyć.", "tâwng tham phǎe khráp", "ต้องทำแผลครับ")),
("Oparzyłem się słońcem.", "phǒm phǐu mâi dàet khráp", "ผมผิวไหม้แดดครับ",
 "Zdrowie", "Urazy", "phrase", 3, "n", "", "phǐu = skóra",
 ("Posmaruj aloesem.", "thaa waan hǎang jaw-rá-khêe khráp", "ทาว่านหางจระเข้ครับ")),
("Ugryzł mnie owad.", "phǒm doon má-laeng kàt khráp", "ผมโดนแมลงกัดครับ",
 "Zdrowie", "Urazy", "phrase", 3, "n", "„doon” tworzy stronę bierną w mowie potocznej.", "doon = zostać (czymś dotkniętym)",
 ("Swędzi?", "khan mǎi khráp", "คันไหมครับ")),
("Boli mnie od wczoraj.", "pen maa tâng tàe mûea waan khráp", "เป็นมาตั้งแต่เมื่อวานครับ",
 "Zdrowie", "Objawy", "phrase", 4, "n", "", "",
 ("Zbadam.", "khǎw trùat duu khráp", "ขอตรวจดูครับ")),

# ------------------------------------------------- lekarz i apteka
("Muszę iść do lekarza.", "phǒm tâwng pai hǎa mǎw khráp", "ผมต้องไปหาหมอครับ",
 "Zdrowie", "Lekarz", "phrase", 5, "n", "„pai hǎa mǎw” = iść do lekarza.", "",
 ("Zawiozę cię.", "phǒm phaa pai khráp", "ผมพาไปครับ")),
("Chcę się umówić do lekarza.", "phǒm yàak nát phóp mǎw khráp", "ผมอยากนัดพบหมอครับ",
 "Zdrowie", "Lekarz", "phrase", 3, "f", "", "",
 ("Na kiedy?", "wan nǎi khráp", "วันไหนครับ")),
("Czy jest lekarz mówiący po angielsku?", "mii mǎw thîi phûut phaa-sǎa ang-krìt dâai mǎi khráp",
 "มีหมอที่พูดภาษาอังกฤษได้ไหมครับ", "Zdrowie", "Lekarz", "question", 4, "n", "", "",
 ("Jest, na drugim piętrze.", "mii khráp chán sǎwng", "มีครับ ชั้นสอง")),
("Czy to coś poważnego?", "raeng mǎi khráp", "แรงไหมครับ",
 "Zdrowie", "Lekarz", "question", 3, "n", "", "",
 ("Nic groźnego.", "mâi raeng khráp", "ไม่แรงครับ")),
("Ile dni mam brać lekarstwo?", "kin yaa kìi wan khráp", "กินยากี่วันครับ",
 "Zdrowie", "Apteka", "question", 4, "n",
 "Po tajsku lekarstwo się „je” (kin), nie „bierze”.", "",
 ("Pięć dni.", "hâa wan khráp", "ห้าวันครับ")),
("Ile razy dziennie?", "wan lá kìi khráng khráp", "วันละกี่ครั้งครับ",
 "Zdrowie", "Apteka", "question", 4, "n", "„lá” = na, per: wan lá = dziennie.", "lá = na jednostkę",
 ("Trzy razy.", "wan lá sǎam khráng khráp", "วันละสามครั้งครับ")),
("Przed jedzeniem czy po?", "kàwn aa-hǎan rǔe lǎng aa-hǎan khráp", "ก่อนอาหารหรือหลังอาหารครับ",
 "Zdrowie", "Apteka", "question", 4, "n", "", "",
 ("Po jedzeniu.", "lǎng aa-hǎan khráp", "หลังอาหารครับ")),
("Poproszę coś na ból głowy.", "khǎw yaa kâe pùat hǔa khráp", "ขอยาแก้ปวดหัวครับ",
 "Zdrowie", "Apteka", "phrase", 5, "n", "„yaa kâe …” = lek na coś.", "kâe = leczyć, zaradzić",
 ("Dwie tabletki naraz.", "khráng lá sǎwng mét khráp", "ครั้งละสองเม็ดครับ")),
("Poproszę coś na ból brzucha.", "khǎw yaa kâe pùat tháwng khráp", "ขอยาแก้ปวดท้องครับ",
 "Zdrowie", "Apteka", "phrase", 4, "n", "", "",
 ("Proszę bardzo.", "nîi khráp", "นี่ครับ")),
("Poproszę coś na biegunkę.", "khǎw yaa kâe tháwng sǐa khráp", "ขอยาแก้ท้องเสียครับ",
 "Zdrowie", "Apteka", "phrase", 4, "n", "", "",
 ("Dużo pij.", "dùem náam yóe yóe ná khráp", "ดื่มน้ำเยอะๆ นะครับ")),
("Poproszę coś na alergię.", "khǎw yaa kâe pháe khráp", "ขอยาแก้แพ้ครับ",
 "Zdrowie", "Apteka", "phrase", 3, "n", "", "",
 ("Może powodować senność.", "aat jà ngûang nawn khráp", "อาจจะง่วงนอนครับ")),
("Czy potrzebna jest recepta?", "tâwng mii bai sàng yaa mǎi khráp", "ต้องมีใบสั่งยาไหมครับ",
 "Zdrowie", "Apteka", "question", 3, "f", "", "bai sàng yaa = recepta",
 ("Nie trzeba.", "mâi tâwng khráp", "ไม่ต้องครับ")),
("Biorę już inne leki.", "phǒm kin yaa ùen yùu khráp", "ผมกินยาอื่นอยู่ครับ",
 "Zdrowie", "Apteka", "phrase", 3, "n", "", "",
 ("Jakie?", "yaa à-rai khráp", "ยาอะไรครับ")),
("Mam ubezpieczenie.", "phǒm mii prà-kan khráp", "ผมมีประกันครับ",
 "Zdrowie", "Formalności", "phrase", 4, "f", "", "",
 ("Poproszę dokument.", "khǎw èek-kà-sǎan khráp", "ขอเอกสารครับ")),
("Poproszę zaświadczenie dla ubezpieczyciela.", "khǎw bai ráp-rawng phâet khráp", "ขอใบรับรองแพทย์ครับ",
 "Zdrowie", "Formalności", "phrase", 3, "f", "", "bai ráp-rawng phâet = zaświadczenie lekarskie",
 ("Wystawię.", "dǐao àwk hâi khráp", "เดี๋ยวออกให้ครับ")),
("Ile zapłacę za wizytę?", "khâa trùat thâo-rài khráp", "ค่าตรวจเท่าไหร่ครับ",
 "Zdrowie", "Formalności", "question", 3, "n", "", "",
 ("Osiemset batów.", "pàet ráwi bàat khráp", "แปดร้อยบาทครับ")),

# ------------------------------------------------- slownictwo zdrowotne
("dentysta", "mǎw fan", "หมอฟัน", "Zdrowie", "Ludzie", "word", 3, "n", "", "",
 ("Gdzie jest dentysta?", "WHERE")),
("pielęgniarka", "phá-yaa-baan", "พยาบาล", "Zdrowie", "Ludzie", "word", 3, "n", "", "",
 ("Zawołam pielęgniarkę.", "dǐao rîak phá-yaa-baan khráp", "เดี๋ยวเรียกพยาบาลครับ")),
("klinika", "khlí-ník", "คลินิก", "Zdrowie", "Miejsca", "word", 4, "n", "", "",
 ("Gdzie jest klinika?", "WHERE")),
("pogotowie", "rót phá-yaa-baan", "รถพยาบาล", "Zdrowie", "Miejsca", "word", 3, "n", "", "dosłownie: samochód pielęgniarski",
 ("Proszę wezwać pogotowie.", "chûai rîak rót phá-yaa-baan khráp", "ช่วยเรียกรถพยาบาลครับ")),
("tabletka", "yaa mét", "ยาเม็ด", "Zdrowie", "Leki", "word", 4, "n", "", "",
 ("Ile tabletek?", "kìi mét khráp", "กี่เม็ดครับ")),
("syrop", "yaa náam", "ยาน้ำ", "Zdrowie", "Leki", "word", 3, "n", "", "",
 ("Poproszę syrop.", "ORDER")),
("maść", "yaa thaa", "ยาทา", "Zdrowie", "Leki", "word", 3, "n", "", "thaa = smarować",
 ("Poproszę maść.", "ORDER")),
("plaster", "phláas-tôe", "พลาสเตอร์", "Zdrowie", "Leki", "word", 3, "n", "", "",
 ("Czy jest plaster?", "HAVE")),
("bandaż", "phâa phan phǎe", "ผ้าพันแผล", "Zdrowie", "Leki", "word", 2, "n", "", "",
 ("Poproszę bandaż.", "ORDER")),
("antybiotyk", "yaa khâa chúea", "ยาฆ่าเชื้อ", "Zdrowie", "Leki", "word", 3, "f", "", "dosłownie: lek zabijający zarazki",
 ("Czy to antybiotyk?", "ISIT")),
("witaminy", "wí-taa-min", "วิตามิน", "Zdrowie", "Leki", "word", 2, "n", "", "",
 ("Biorę witaminy.", "phǒm kin wí-taa-min khráp", "ผมกินวิตามินครับ")),
("badanie", "kaan trùat", "การตรวจ", "Zdrowie", "Lekarz", "word", 3, "f", "", "",
 ("Kiedy jest badanie?", "kaan trùat mûea-rài khráp", "การตรวจเมื่อไหร่ครับ")),
("wynik badania", "phǒn trùat", "ผลตรวจ", "Zdrowie", "Lekarz", "word", 3, "f", "", "",
 ("Kiedy będzie wynik?", "phǒn trùat àwk mûea-rài khráp", "ผลตรวจออกเมื่อไหร่ครับ")),
("alergia", "kaan pháe", "การแพ้", "Zdrowie", "Alergie", "word", 3, "f", "", "",
 ("Mam alergię.", "phǒm mii kaan pháe khráp", "ผมมีการแพ้ครับ")),
("krew", "lûeat", "เลือด", "Zdrowie", "Ciało", "word", 3, "n", "", "",
 ("Leci krew.", "lûeat àwk khráp", "เลือดออกครับ")),
("temperatura ciała", "ùn-hà-phuum râang-kaai", "อุณหภูมิร่างกาย", "Zdrowie", "Ciało", "word", 2, "f", "", "",
 ("Zmierzę temperaturę.", "khǎw wát ùn-hà-phuum khráp", "ขอวัดอุณหภูมิครับ")),
("rana", "phǎe", "แผล", "Zdrowie", "Urazy", "word", 3, "n", "", "",
 ("Rana jest mała.", "phǎe lék khráp", "แผลเล็กครับ")),
("opuchlizna", "buam", "บวม", "Zdrowie", "Urazy", "word", 3, "n", "", "",
 ("Noga jest spuchnięta.", "khǎa buam khráp", "ขาบวมครับ")),
("swędzenie", "khan", "คัน", "Zdrowie", "Objawy", "word", 3, "n", "", "",
 ("Bardzo mnie swędzi.", "khan mâak khráp", "คันมากครับ")),

# =====================================================================
# WYGLAD I UBRANIA
# =====================================================================
("Czy mogę przymierzyć?", "lawng sài dâai mǎi khráp", "ลองใส่ได้ไหมครับ",
 "Zakupy i pieniądze", "Ubrania", "question", 5, "n", "„lawng” = spróbować.", "",
 ("Przymierzalnia tam.", "hâwng lawng yùu thaang nán khráp", "ห้องลองอยู่ทางนั้นครับ")),
("Czy jest większy rozmiar?", "mii sái yài kwàa mǎi khráp", "มีไซส์ใหญ่กว่าไหมครับ",
 "Zakupy i pieniądze", "Ubrania", "question", 5, "n", "", "",
 ("Zaraz sprawdzę.", "dǐao duu hâi khráp", "เดี๋ยวดูให้ครับ")),
("Czy jest mniejszy rozmiar?", "mii sái lék kwàa mǎi khráp", "มีไซส์เล็กกว่าไหมครับ",
 "Zakupy i pieniądze", "Ubrania", "question", 4, "n", "", "",
 ("Tylko ten rozmiar.", "mii tàe sái níi khráp", "มีแต่ไซส์นี้ครับ")),
("To jest za ciasne.", "kháp koen pai khráp", "คับเกินไปครับ",
 "Zakupy i pieniądze", "Ubrania", "phrase", 4, "n", "„kháp” = ciasny.", "",
 ("Dam większy.", "dǐao ao sái yài maa hâi khráp", "เดี๋ยวเอาไซส์ใหญ่มาให้ครับ")),
("To jest za luźne.", "lǔam koen pai khráp", "หลวมเกินไปครับ",
 "Zakupy i pieniądze", "Ubrania", "phrase", 4, "n", "„lǔam” = luźny.", "",
 ("Mniejszy rozmiar?", "ao sái lék kwàa mǎi khráp", "เอาไซส์เล็กกว่าไหมครับ")),
("W sam raz.", "phaw dii loei khráp", "พอดีเลยครับ",
 "Zakupy i pieniądze", "Ubrania", "phrase", 5, "i", "", "",
 ("Dobrze leży.", "sài láew dii khráp", "ใส่แล้วดีครับ")),
("Czy jest w innym kolorze?", "mii sǐi ùen mǎi khráp", "มีสีอื่นไหมครับ",
 "Zakupy i pieniądze", "Ubrania", "question", 5, "n", "", "",
 ("Jest czarny i biały.", "mii sǐi dam kàp sǐi khǎao khráp", "มีสีดำกับสีขาวครับ")),
("Wolę ciemniejszy kolor.", "phǒm châwp sǐi khêm kwàa khráp", "ผมชอบสีเข้มกว่าครับ",
 "Zakupy i pieniądze", "Ubrania", "phrase", 3, "n", "„khêm” = ciemny, intensywny.", "",
 ("Mam granatowy.", "mii sǐi náam ngoen khráp", "มีสีน้ำเงินครับ")),
("Wolę jaśniejszy kolor.", "phǒm châwp sǐi àwn kwàa khráp", "ผมชอบสีอ่อนกว่าครับ",
 "Zakupy i pieniądze", "Ubrania", "phrase", 3, "n", "„àwn” = jasny, delikatny.", "",
 ("Jest beżowy.", "mii sǐi khrim khráp", "มีสีครีมครับ")),
("Z czego to jest zrobione?", "tham jàak à-rai khráp", "ทำจากอะไรครับ",
 "Zakupy i pieniądze", "Ubrania", "question", 3, "n", "", "jàak = z, od",
 ("Ze stu procent bawełny.", "fâai ráwi poe-sen khráp", "ฝ้ายร้อยเปอร์เซ็นต์ครับ")),
("Czy to się kurczy w praniu?", "sák láew hòt mǎi khráp", "ซักแล้วหดไหมครับ",
 "Zakupy i pieniądze", "Ubrania", "question", 2, "n", "„hòt” = kurczyć się.", "",
 ("Nie kurczy się.", "mâi hòt khráp", "ไม่หดครับ")),
("Wezmę to.", "ao an níi khráp", "เอาอันนี้ครับ",
 "Zakupy i pieniądze", "Ubrania", "phrase", 5, "n", "", "",
 ("Zapakować?", "hàw hâi mǎi khráp", "ห่อให้ไหมครับ")),
("Jeszcze się zastanowię.", "khǎw khít duu kàwn khráp", "ขอคิดดูก่อนครับ",
 "Zakupy i pieniądze", "Ubrania", "phrase", 5, "n",
 "Uprzejmy sposób wyjścia ze sklepu bez zakupu.", "",
 ("Proszę bardzo.", "dâai khráp", "ได้ครับ")),

# ------------------------------------------------- wyglad
("wysoki (o człowieku)", "sǔung", "สูง", "Cechy i opinie", "Wygląd", "word", 4, "n", "", "",
 ("Jest bardzo wysoki.", "VERY")),
("niski (o człowieku)", "tîa", "เตี้ย", "Cechy i opinie", "Wygląd", "word", 4, "n", "", "",
 ("Jest raczej niski.", "khǎo tîa nít nòi khráp", "เขาเตี้ยนิดหน่อยครับ")),
("szczupły", "phǎwm", "ผอม", "Cechy i opinie", "Wygląd", "word", 4, "n", "", "",
 ("Jest szczupła.", "khǎo phǎwm khráp", "เขาผอมครับ")),
("gruby", "ûan", "อ้วน", "Cechy i opinie", "Wygląd", "word", 4, "p",
 "W Tajlandii mówi się o tym swobodniej niż w Polsce, ale nadal warto uważać.", "",
 ("Trochę przytyłem.", "phǒm ûan khûen nít nòi khráp", "ผมอ้วนขึ้นนิดหน่อยครับ")),
("silny", "khǎeng raeng", "แข็งแรง", "Cechy i opinie", "Wygląd", "word", 4, "n",
 "To samo słowo znaczy „zdrowy, w dobrej formie”.", "",
 ("Jest bardzo silny.", "VERY")),
("ładny (o osobie)", "nâa rák", "น่ารัก", "Cechy i opinie", "Wygląd", "word", 5, "i",
 "„nâa rák” znaczy raczej „uroczy” niż „piękny”.", "dosłownie: godny miłości",
 ("Jest bardzo urocza.", "VERY")),
("przystojny", "làw", "หล่อ", "Cechy i opinie", "Wygląd", "word", 4, "i", "", "",
 ("Jest przystojny.", "khǎo làw khráp", "เขาหล่อครับ")),
("piękna", "sǔai", "สวย", "Cechy i opinie", "Wygląd", "word", 5, "n", "", "",
 ("Jest bardzo piękna.", "VERY")),
("włosy", "phǒm", "ผม", "Cechy i opinie", "Wygląd", "word", 4, "n",
 "To samo słowo znaczy „ja” w ustach mężczyzny — decyduje kontekst.", "",
 ("Ma długie włosy.", "khǎo phǒm yaao khráp", "เขาผมยาวครับ")),
("broda", "khrào", "เครา", "Cechy i opinie", "Wygląd", "word", 2, "n", "", "",
 ("Zapuścił brodę.", "khǎo wái khrào khráp", "เขาไว้เคราครับ")),
("okulary", "wâen taa", "แว่นตา", "Cechy i opinie", "Wygląd", "word", 4, "n", "", "",
 ("Noszę okulary.", "phǒm sài wâen taa khráp", "ผมใส่แว่นตาครับ")),
("tatuaż", "ráwi sàk", "รอยสัก", "Cechy i opinie", "Wygląd", "word", 2, "n", "", "",
 ("Ma tatuaż.", "khǎo mii ráwi sàk khráp", "เขามีรอยสักครับ")),

# ------------------------------------------------- ubrania
("koszula", "sûea chóet", "เสื้อเชิ้ต", "Zakupy i pieniądze", "Ubrania", "word", 4, "n", "", "",
 ("Poproszę koszulę.", "ORDER")),
("sukienka", "krà-proong", "กระโปรง", "Zakupy i pieniądze", "Ubrania", "word", 3, "n",
 "Uwaga: „krà-proong” to właściwie spódnica; sukienka to „chút”.", "",
 ("Ta spódnica jest ładna.", "krà-proong túa níi sǔai khráp", "กระโปรงตัวนี้สวยครับ")),
("kurtka", "sûea jáek-két", "เสื้อแจ็คเก็ต", "Zakupy i pieniądze", "Ubrania", "word", 3, "n", "", "",
 ("Czy jest kurtka?", "HAVE")),
("krótkie spodenki", "kaang keeng khǎa sân", "กางเกงขาสั้น", "Zakupy i pieniądze", "Ubrania", "word", 4, "n", "", "",
 ("Wezmę spodenki.", "ao kaang keeng khǎa sân khráp", "เอากางเกงขาสั้นครับ")),
("sandały", "rawng tháo tàe", "รองเท้าแตะ", "Zakupy i pieniądze", "Ubrania", "word", 4, "n", "", "",
 ("Poproszę sandały.", "ORDER")),
("skarpetki", "thǔng tháo", "ถุงเท้า", "Zakupy i pieniądze", "Ubrania", "word", 3, "n", "", "",
 ("Gdzie są skarpetki?", "WHERE")),
("czapka", "mùak", "หมวก", "Zakupy i pieniądze", "Ubrania", "word", 4, "n", "", "",
 ("Poproszę czapkę.", "ORDER")),
("pasek", "khěm khàt", "เข็มขัด", "Zakupy i pieniądze", "Ubrania", "word", 2, "n", "", "",
 ("Czy jest pasek?", "HAVE")),
("plecak", "pêe", "เป้", "Zakupy i pieniądze", "Akcesoria", "word", 4, "n", "", "",
 ("Mój plecak jest ciężki.", "pêe khǎwng phǒm nàk khráp", "เป้ของผมหนักครับ")),
("portfel", "krà-pǎo taang", "กระเป๋าตังค์", "Zakupy i pieniądze", "Akcesoria", "word", 4, "p", "", "",
 ("Zgubiłem portfel.", "phǒm tham krà-pǎo taang hǎai khráp", "ผมทำกระเป๋าตังค์หายครับ")),
("okulary przeciwsłoneczne", "wâen kan dàet", "แว่นกันแดด", "Zakupy i pieniądze", "Akcesoria", "word", 3, "n", "", "",
 ("Czy są okulary przeciwsłoneczne?", "HAVE")),
("rozmiar (odzieży)", "sái", "ไซส์", "Zakupy i pieniądze", "Ubrania", "word", 5, "p", "", "",
 ("Jaki rozmiar?", "sái à-rai khráp", "ไซส์อะไรครับ")),

# =====================================================================
# DOM I MIESZKANIE
# =====================================================================
("Szukam mieszkania do wynajęcia.", "phǒm hǎa hâwng châo yùu khráp", "ผมหาห้องเช่าอยู่ครับ",
 "Dom i codzienność", "Wynajem", "phrase", 4, "n", "Konstrukcja „… yùu” = właśnie to robię.", "",
 ("Na jak długo?", "châo naan thâo-rài khráp", "เช่านานเท่าไหร่ครับ")),
("Ile wynosi czynsz miesięczny?", "khâa châo duean lá thâo-rài khráp", "ค่าเช่าเดือนละเท่าไหร่ครับ",
 "Dom i codzienność", "Wynajem", "question", 4, "n", "", "",
 ("Osiem tysięcy.", "pàet phan khráp", "แปดพันครับ")),
("Czy prąd jest wliczony?", "ruam khâa fai fáa mǎi khráp", "รวมค่าไฟฟ้าไหมครับ",
 "Dom i codzienność", "Wynajem", "question", 4, "n", "", "",
 ("Płaci się osobno.", "jàai yâek khráp", "จ่ายแยกครับ")),
("Czy woda jest wliczona?", "ruam khâa náam mǎi khráp", "รวมค่าน้ำไหมครับ",
 "Dom i codzienność", "Wynajem", "question", 3, "n", "", "",
 ("Woda jest w cenie.", "khâa náam ruam láew khráp", "ค่าน้ำรวมแล้วครับ")),
("Jaka jest kaucja?", "khâa mát jam thâo-rài khráp", "ค่ามัดจำเท่าไหร่ครับ",
 "Dom i codzienność", "Wynajem", "question", 3, "f", "", "",
 ("Dwa czynsze.", "sǎwng duean khráp", "สองเดือนครับ")),
("Czy mieszkanie jest umeblowane?", "mii foe-ní-jôe mǎi khráp", "มีเฟอร์นิเจอร์ไหมครับ",
 "Dom i codzienność", "Wynajem", "question", 3, "n", "", "",
 ("Jest łóżko i szafa.", "mii tiang kàp tûu sûea phâa khráp", "มีเตียงกับตู้เสื้อผ้าครับ")),
("Chciałbym obejrzeć mieszkanie.", "phǒm yàak duu hâwng khráp", "ผมอยากดูห้องครับ",
 "Dom i codzienność", "Wynajem", "phrase", 3, "n", "", "",
 ("Kiedy panu pasuje?", "sà-dùak wan nǎi khráp", "สะดวกวันไหนครับ")),
("Nie działa prąd.", "fai dàp khráp", "ไฟดับครับ",
 "Dom i codzienność", "Awarie", "phrase", 4, "n", "„fai dàp” = zgasło światło, nie ma prądu.", "",
 ("W całym budynku?", "dàp tháng tùek rǔe khráp", "ดับทั้งตึกหรือครับ")),
("Nie ma wody.", "náam mâi lǎi khráp", "น้ำไม่ไหลครับ",
 "Dom i codzienność", "Awarie", "phrase", 4, "n", "„lǎi” = płynąć.", "",
 ("Zgłoszę to.", "dǐao jâeng hâi khráp", "เดี๋ยวแจ้งให้ครับ")),
("Zepsuła się lodówka.", "tûu yen sǐa khráp", "ตู้เย็นเสียครับ",
 "Dom i codzienność", "Awarie", "phrase", 3, "n", "„sǐa” = zepsuty, popsuty.", "",
 ("Wezwę serwis.", "dǐao rîak châang khráp", "เดี๋ยวเรียกช่างครับ")),
("Zepsuła się pralka.", "khrûeang sák phâa sǐa khráp", "เครื่องซักผ้าเสียครับ",
 "Dom i codzienność", "Awarie", "phrase", 3, "n", "", "",
 ("Od kiedy?", "sǐa tâng tàe mûea-rài khráp", "เสียตั้งแต่เมื่อไหร่ครับ")),
("Cieknie kran.", "káwk náam rûa khráp", "ก๊อกน้ำรั่วครับ",
 "Dom i codzienność", "Awarie", "phrase", 3, "n", "", "",
 ("Naprawię jutro.", "phrûng níi jà sâwm hâi khráp", "พรุ่งนี้จะซ่อมให้ครับ")),
("Czy może pan to naprawić?", "chûai sâwm hâi nòi dâai mǎi khráp", "ช่วยซ่อมให้หน่อยได้ไหมครับ",
 "Dom i codzienność", "Awarie", "question", 4, "n", "„sâwm” = naprawiać.", "",
 ("Zaraz przyjdę.", "dǐao maa khráp", "เดี๋ยวมาครับ")),
("Kiedy przyjdzie technik?", "châang jà maa mûea-rài khráp", "ช่างจะมาเมื่อไหร่ครับ",
 "Dom i codzienność", "Awarie", "question", 3, "n", "„châang” = fachowiec, rzemieślnik.", "",
 ("Po południu.", "tawn bàai khráp", "ตอนบ่ายครับ")),
("Muszę wyrzucić śmieci.", "phǒm tâwng thíng khà-yà khráp", "ผมต้องทิ้งขยะครับ",
 "Dom i codzienność", "Obowiązki", "phrase", 3, "n", "„thíng” = wyrzucić.", "",
 ("Kosz jest na dole.", "thǎng khà-yà yùu chán lâang khráp", "ถังขยะอยู่ชั้นล่างครับ")),
("Zrobię pranie.", "phǒm jà sák phâa khráp", "ผมจะซักผ้าครับ",
 "Dom i codzienność", "Obowiązki", "phrase", 3, "n", "", "",
 ("Pralnia jest obok.", "ráan sák phâa yùu khâang khâang khráp", "ร้านซักผ้าอยู่ข้างๆ ครับ")),
("Posprzątam pokój.", "phǒm jà tham khwaam sà-àat hâwng khráp", "ผมจะทำความสะอาดห้องครับ",
 "Dom i codzienność", "Obowiązki", "phrase", 3, "n", "", "",
 ("Pomogę ci.", "phǒm chûai khráp", "ผมช่วยครับ")),
("Ugotuję dziś w domu.", "wan níi phǒm jà tham aa-hǎan thîi bâan khráp", "วันนี้ผมจะทำอาหารที่บ้านครับ",
 "Dom i codzienność", "Obowiązki", "phrase", 3, "n", "", "",
 ("Co ugotujesz?", "tham à-rai khráp", "ทำอะไรครับ")),

# ------------------------------------------------- slownictwo domowe
("mieszkanie do wynajęcia", "hâwng châo", "ห้องเช่า", "Dom i codzienność", "Wynajem", "word", 4, "n", "", "",
 ("Szukam mieszkania.", "phǒm hǎa hâwng châo khráp", "ผมหาห้องเช่าครับ")),
("czynsz", "khâa châo", "ค่าเช่า", "Dom i codzienność", "Wynajem", "word", 4, "n", "", "",
 ("Ile wynosi czynsz?", "HOWMUCH")),
("umowa najmu", "sǎn-yaa châo", "สัญญาเช่า", "Dom i codzienność", "Wynajem", "word", 3, "f", "", "",
 ("Poproszę umowę.", "ORDER")),
("właściciel", "jâo khǎwng", "เจ้าของ", "Dom i codzienność", "Wynajem", "word", 3, "n", "", "",
 ("Gdzie jest właściciel?", "WHERE")),
("mebel", "foe-ní-jôe", "เฟอร์นิเจอร์", "Dom i codzienność", "Wyposażenie", "word", 3, "n", "", "",
 ("Czy są meble?", "HAVE")),
("szafa", "tûu sûea phâa", "ตู้เสื้อผ้า", "Dom i codzienność", "Wyposażenie", "word", 3, "n", "", "",
 ("Gdzie jest szafa?", "WHERE")),
("stół", "tó tham ngaan", "โต๊ะทำงาน", "Dom i codzienność", "Wyposażenie", "word", 3, "n", "", "dosłownie: stół do pracy",
 ("Potrzebuję biurka.", "NEED")),
("krzesło", "kâo-îi", "เก้าอี้", "Dom i codzienność", "Wyposażenie", "word", 4, "n", "", "",
 ("Poproszę krzesło.", "ORDER")),
("kuchenka", "taw", "เตา", "Dom i codzienność", "Wyposażenie", "word", 3, "n", "", "",
 ("Czy jest kuchenka?", "HAVE")),
("mikrofalówka", "mai-khro-wéf", "ไมโครเวฟ", "Dom i codzienność", "Wyposażenie", "word", 3, "n", "", "",
 ("Czy jest mikrofalówka?", "HAVE")),
("odkurzacz", "khrûeang dùut fùn", "เครื่องดูดฝุ่น", "Dom i codzienność", "Wyposażenie", "word", 2, "n", "", "",
 ("Gdzie jest odkurzacz?", "WHERE")),
("kosz na śmieci", "thǎng khà-yà", "ถังขยะ", "Dom i codzienność", "Wyposażenie", "word", 3, "n", "", "",
 ("Gdzie jest kosz?", "WHERE")),
("klucz do mieszkania", "kunjae hâwng", "กุญแจห้อง", "Dom i codzienność", "Wyposażenie", "word", 4, "n", "", "",
 ("Zgubiłem klucz.", "phǒm tham kunjae hǎai khráp", "ผมทำกุญแจหายครับ")),
("sąsiad z góry", "khon chán bon", "คนชั้นบน", "Dom i codzienność", "Sąsiedzi", "word", 2, "p", "", "",
 ("Sąsiad z góry hałasuje.", "khon chán bon sǐang dang khráp", "คนชั้นบนเสียงดังครับ")),
("ochroniarz", "yaam", "ยาม", "Dom i codzienność", "Sąsiedzi", "word", 3, "n",
 "W tajskich budynkach mieszkalnych ochroniarz to pierwsza osoba do pytań.", "",
 ("Zapytam ochroniarza.", "phǒm jà thǎam yaam khráp", "ผมจะถามยามครับ")),
]
