# -*- coding: utf-8 -*-
"""Sesja N — PRACA I NAUKA, CZAS I DATY, LICZBY I LICZENIE.

Praca i nauka miała 1 248 rekordów i 46 haseł — dwadzieścia siedem zdań na
jedno słowo. Ta kategoria najbardziej ucierpiała na budowaniu bazy przez
mnożenie wzorców zdaniowych: zdań przybyło, cegiełek nie.

Krotka: (poziom, polski, fonetyka, pismo, podkategoria, częstość, typ,
         kategoria, uwaga, dosłownie)
"""

PN = "Praca i nauka"
CD = "Czas i daty"
LI = "Liczby i liczenie"

WORK = [

# ============================================================ ZAWODY
("A1", "nauczyciel", "khruu", "ครู", "Zawody", 5, "n", PN,
 "Tytuł, nie tylko zawód — stoi przed imieniem: khruu Nói.", ""),
("A1", "uczeń, student", "nák rian", "นักเรียน", "Zawody", 5, "n", PN,
 "nák- tworzy nazwy osób oddanych czynności: nák rian, nák kii-laa, nák thúrákìt.", "człowiek uczyć się"),
("A2", "student wyższej uczelni", "nák sùek-sǎa", "นักศึกษา", "Zawody", 4, "n", PN,
 "Rozróżnienie jest ostre: nák rian to szkoła, nák sùek-sǎa to uczelnia.", "człowiek studiować"),
("A2", "inżynier", "wít-sà-wá-kawn", "วิศวกร", "Zawody", 3, "n", PN,
 "-kawn to końcówka nazw zawodów technicznych.", ""),
("A2", "prawnik", "thá-naai khwaam", "ทนายความ", "Zawody", 3, "n", PN,
 "khwaam to tu „sprawa sądowa”.", "adwokat sprawa"),
("A2", "księgowy", "nák ban-chii", "นักบัญชี", "Zawody", 3, "n", PN,
 "ban-chii to konto i rachunkowość.", "człowiek rachunek"),
("A2", "sprzedawca", "khon khǎai", "คนขาย", "Zawody", 4, "n", PN,
 "khǎai to sprzedawać. Uwaga na parę: khǎai (sprzedawać) kontra khâi (gorączka).", "człowiek sprzedawać"),
("A2", "urzędnik", "khâa râat-chá-kaan", "ข้าราชการ", "Zawody", 3, "n", PN,
 "Dosłownie „sługa spraw królewskich”.", "sługa sprawy państwowe"),
("A2", "rolnik", "chaao naa", "ชาวนา", "Zawody", 3, "n", PN,
 "chaao- oznacza mieszkańca albo człowieka trudniącego się czymś.", "mieszkaniec pole"),
("A2", "rybak", "chaao prà-mong", "ชาวประมง", "Zawody", 2, "n", PN,
 "", "mieszkaniec rybołówstwo"),
("A2", "przewodnik", "kai", "ไกด์", "Zawody", 3, "n", PN,
 "Zapożyczenie z angielskiego guide.", ""),
("A2", "programista", "prook-kraem-môe", "โปรแกรมเมอร์", "Zawody", 3, "n", PN,
 "", ""),
("A2", "pielęgniarka", "phá-yaa-baan", "พยาบาล", "Zawody", 4, "n", PN,
 "To samo słowo stoi w roong phá-yaa-baan (szpital).", ""),
("A2", "kucharz", "phâw khrua", "พ่อครัว", "Zawody", 3, "n", PN,
 "Dosłownie „ojciec kuchni”; kobieta to mâe khrua.", "ojciec kuchnia"),
("A2", "ochroniarz", "yaam", "ยาม", "Zawody", 3, "n", PN,
 "Także „pora, straż” w znaczeniu odcinka czasu.", ""),
("A2", "szef", "hǔa nâa", "หัวหน้า", "Zawody", 5, "n", PN,
 "Dosłownie „głowa twarz”. Bardzo częste w rozmowie o pracy.", "głowa twarz"),
("A2", "kolega z pracy", "phûean rûam ngaan", "เพื่อนร่วมงาน", "Zawody", 4, "n", PN,
 "rûam to wspólnie, razem.", "przyjaciel wspólnie praca"),
("A2", "podwładny", "lûuk náwng", "ลูกน้อง", "Zawody", 3, "n", PN,
 "Dosłownie „dziecko młodsze” — hierarchia opisana słownictwem rodzinnym.", "dziecko młodszy"),
("A2", "klient", "lûuk kháa", "ลูกค้า", "Zawody", 5, "n", PN,
 "Znów lûuk: „dziecko handlu”.", "dziecko handel"),

# ============================================================ PRACA
("A1", "zawód", "aa-chîip", "อาชีพ", "Praca", 4, "n", PN,
 "Pytanie: tham aa-chîip à-rai.", ""),
("A2", "etat, stanowisko", "tam-nàeng", "ตำแหน่ง", "Praca", 3, "n", PN,
 "Także „położenie, lokalizacja”.", ""),
("A2", "wynagrodzenie", "ngoen duean", "เงินเดือน", "Praca", 4, "n", PN,
 "Dosłownie „pieniądze miesiąca”. Dniówka to khâa raeng.", "pieniądze miesiąc"),
("A2", "premia", "boo-nát", "โบนัส", "Praca", 3, "n", PN,
 "Zwyczajowo wypłacana przed Nowym Rokiem.", ""),
("A2", "nadgodziny", "oo-thii", "โอที", "Praca", 3, "n", PN,
 "Skrót od OT. Bardzo częsty w mowie.", ""),
("A2", "urlop", "wan yùt", "วันหยุด", "Praca", 5, "n", PN,
 "To samo słowo znaczy „dzień wolny” i „święto”.", "dzień zatrzymać"),
("A2", "zwolnienie lekarskie", "laa pùai", "ลาป่วย", "Praca", 3, "n", PN,
 "laa to prosić o wolne; pùai to chorować.", "prosić o wolne chorować"),
("A2", "rozmowa kwalifikacyjna", "sǎm-phâat ngaan", "สัมภาษณ์งาน", "Praca", 3, "n", PN,
 "sǎm-phâat to także wywiad prasowy.", "wywiad praca"),
("A2", "podanie o pracę", "sà-màk ngaan", "สมัครงาน", "Praca", 3, "n", PN,
 "sà-màk to zgłaszać się, zapisywać.", "zgłaszać się praca"),
("A2", "zwolnić kogoś", "lôoi àwk", "เลิกจ้าง", "Praca", 2, "v", PN,
 "Łagodniejsza forma: hâi àwk.", "kończyć zatrudnienie"),
("A2", "rezygnować z pracy", "laa àwk", "ลาออก", "Praca", 3, "v", PN,
 "", "prosić o wolne wychodzić"),
("A2", "awans", "lûean tam-nàeng", "เลื่อนตำแหน่ง", "Praca", 2, "n", PN,
 "lûean to przesuwać — także przesunąć termin.", "przesuwać stanowisko"),
("A2", "spotkanie, zebranie", "prà-chum", "ประชุม", "Praca", 4, "n", PN,
 "hâwng prà-chum — sala konferencyjna.", ""),
("A2", "termin, deadline", "kam-nòt sòng", "กำหนดส่ง", "Praca", 3, "n", PN,
 "kam-nòt to wyznaczać; sòng to wysyłać, oddawać.", "wyznaczony oddanie"),
("A2", "projekt", "khroong kaan", "โครงการ", "Praca", 3, "n", PN,
 "", ""),
("A2", "zadanie", "ngaan", "งาน", "Praca", 5, "n", PN,
 "Jedno z najbardziej wieloznacznych słów: praca, zadanie, impreza, uroczystość.", ""),
("A2", "odpowiedzialność", "khwaam ráp phìt châwp", "ความรับผิดชอบ", "Praca", 3, "n", PN,
 "Dosłownie „przyjmowanie winy i zasługi”.", "stan przyjmować wina zasługa"),
("A2", "doświadczenie", "prà-sòp kaan", "ประสบการณ์", "Praca", 3, "n", PN,
 "", ""),
("A2", "umiejętność", "thák-sà", "ทักษะ", "Praca", 3, "n", PN,
 "", ""),
("A2", "firma", "bàw-rí-sàt", "บริษัท", "Praca", 5, "n", PN,
 "Trzy sylaby; pierwsze dwie nieakcentowane.", ""),
("A2", "fabryka", "roong ngaan", "โรงงาน", "Praca", 3, "n", PN,
 "roong to hala — ten sam przedrostek co w roong rian i roong nǎng.", "hala praca"),
("A2", "oddział, dział", "phà-nàek", "แผนก", "Praca", 3, "n", PN,
 "", ""),
("B1", "umowa", "sǎn-yaa", "สัญญา", "Praca", 3, "n", PN,
 "To samo słowo co „obietnica”.", ""),
("B1", "podatek", "phaa-sǐi", "ภาษี", "Praca", 3, "n", PN,
 "VAT to 7 procent i w restauracjach bywa doliczany osobno.", ""),
("B1", "zysk", "kam-rai", "กำไร", "Praca", 2, "n", PN,
 "", ""),
("B1", "strata", "khàat thun", "ขาดทุน", "Praca", 2, "n", PN,
 "khàat to brakować; thun to kapitał.", "brakować kapitał"),

# ============================================================ NAUKA
("A1", "szkoła podstawowa", "roong rian prà-thǒm", "โรงเรียนประถม", "Nauka", 3, "n", PN,
 "", "szkoła podstawowy"),
("A1", "liceum", "roong rian mát-thá-yǒm", "โรงเรียนมัธยม", "Nauka", 3, "n", PN,
 "", "szkoła średni"),
("A1", "uczelnia, uniwersytet", "má-hǎa wít-thá-yaa-lai", "มหาวิทยาลัย", "Nauka", 4, "n", PN,
 "W mowie skracane do má-hǎa lai.", "wielki uczelnia"),
("A2", "przedmiot (szkolny)", "wí-chaa", "วิชา", "Nauka", 4, "n", PN,
 "", ""),
("A2", "lekcja, zajęcia", "khâap rian", "คาบเรียน", "Nauka", 3, "n", PN,
 "khâap to jednostka lekcyjna.", "jednostka uczyć się"),
("A2", "egzamin", "sàwp", "สอบ", "Nauka", 5, "n", PN,
 "Także czasownik: sàwp phàan — zdać, sàwp tòk — oblać.", ""),
("A2", "zdać egzamin", "sàwp phàan", "สอบผ่าน", "Nauka", 4, "v", PN,
 "phàan to przejść, minąć.", "egzamin przechodzić"),
("A2", "oblać egzamin", "sàwp tòk", "สอบตก", "Nauka", 3, "v", PN,
 "Znów tòk — spadać.", "egzamin spadać"),
("A2", "ocena, stopień", "khá-naen", "คะแนน", "Nauka", 4, "n", PN,
 "Także punkty w grze i w sondażu.", ""),
("A2", "praca domowa", "kaan bâan", "การบ้าน", "Nauka", 4, "n", PN,
 "kaan- tworzy rzeczowniki odczasownikowe.", "czynność dom"),
("A2", "zeszyt", "sà-mùt", "สมุด", "Nauka", 4, "n", PN,
 "To samo słowo stoi w hâwng sà-mùt (biblioteka).", ""),
("A2", "podręcznik", "nǎng-sǔe rian", "หนังสือเรียน", "Nauka", 3, "n", PN,
 "nǎng-sǔe to książka i pismo urzędowe.", "książka uczyć się"),
("A2", "długopis", "pàak-kaa", "ปากกา", "Nauka", 4, "n", PN,
 "Dosłownie „dziób kruka” — od kształtu stalówki.", "usta wrona"),
("A2", "ołówek", "din sǎw", "ดินสอ", "Nauka", 3, "n", PN,
 "Dosłownie „ziemia do pisania”.", "ziemia rysik"),
("A2", "gumka", "yaang lóp", "ยางลบ", "Nauka", 2, "n", PN,
 "lóp to wymazywać, odejmować.", "guma wymazywać"),
("A2", "notatka", "ban-thúek", "บันทึก", "Nauka", 3, "n", PN,
 "Także nagrywać i zapisywać w pamięci urządzenia.", ""),
("A2", "tłumaczyć (język)", "plae", "แปล", "Nauka", 5, "v", PN,
 "plae wâa à-rai — co to znaczy.", ""),
("A2", "tłumaczyć (wyjaśniać)", "à-thí-baai", "อธิบาย", "Nauka", 4, "v", PN,
 "Zupełnie inne słowo niż plae — nie mylić.", ""),
("A2", "powtarzać (materiał)", "thóp thuan", "ทบทวน", "Nauka", 3, "v", PN,
 "", ""),
("A2", "zapamiętać", "jam", "จำ", "Nauka", 5, "v", PN,
 "jam dâi — pamiętam; jam mâi dâi — nie pamiętam.", ""),
("A2", "zapomnieć", "luem", "ลืม", "Nauka", 5, "v", PN,
 "", ""),
("A2", "ćwiczyć", "fùek", "ฝึก", "Nauka", 4, "v", PN,
 "fùek phûut — ćwiczyć mówienie.", ""),
("A2", "błąd", "khâw phìt phlâat", "ข้อผิดพลาด", "Nauka", 3, "n", PN,
 "khâw- tworzy rzeczowniki abstrakcyjne: khâw dii, khâw sǐa.", "punkt błędny chybiony"),
("A2", "poprawny", "thùuk tâwng", "ถูกต้อง", "Nauka", 5, "adj", PN,
 "Uwaga: thùuk samo znaczy też „tani”. Para thùuk tâwng usuwa dwuznaczność.", "poprawny właściwy"),
("B1", "stypendium", "thun kaan sùek-sǎa", "ทุนการศึกษา", "Nauka", 2, "n", PN,
 "thun to kapitał, fundusz.", "fundusz nauka"),
("B1", "dyplom", "prà-kàat-sà-nii-yá-bàt", "ประกาศนียบัตร", "Nauka", 2, "n", PN,
 "Bardzo długi wyraz; w mowie skracany.", ""),

# ============================================================ CZAS
("A1", "chwila", "khrûu", "ครู่", "Odcinki czasu", 4, "n", CD,
 "Uwaga: khrûu (chwila) kontra khruu (nauczyciel) — różni je sam ton.", ""),
("A1", "moment, właśnie teraz", "tawn níi", "ตอนนี้", "Odcinki czasu", 5, "adv", CD,
 "tawn to odcinek czasu — bardzo produktywne: tawn cháo, tawn yen, tawn nán.", "odcinek ten"),
("A2", "wtedy", "tawn nán", "ตอนนั้น", "Odcinki czasu", 4, "adv", CD,
 "", "odcinek tamten"),
("A2", "od razu", "than thii", "ทันที", "Odcinki czasu", 4, "adv", CD,
 "than to zdążyć.", "zdążyć raz"),
("A2", "zdążyć", "than", "ทัน", "Odcinki czasu", 4, "v", CD,
 "mâi than — nie zdążyłem. Bardzo częste.", ""),
("A2", "wcześnie", "cháo", "เช้า", "Odcinki czasu", 5, "adv", CD,
 "To samo słowo co „rano”.", ""),
("A2", "późno", "sǎai", "สาย", "Odcinki czasu", 5, "adj", CD,
 "Uwaga: sǎai to także „linia autobusowa”. maa sǎai — przyjść późno.", ""),
("A2", "punktualnie", "trong wee-laa", "ตรงเวลา", "Odcinki czasu", 4, "adv", CD,
 "trong to prosto, dokładnie.", "dokładnie czas"),
("A2", "wkrótce", "rew rew níi", "เร็วๆนี้", "Odcinki czasu", 4, "adv", CD,
 "Podwojenie rew wzmacnia.", "szybko szybko ten"),
("A2", "kiedyś (w przeszłości)", "mûea kàwn", "เมื่อก่อน", "Odcinki czasu", 4, "adv", CD,
 "", "gdy przedtem"),
("A2", "w przyszłości", "nai à-naa-khót", "ในอนาคต", "Odcinki czasu", 3, "adv", CD,
 "", "w przyszłość"),
("A2", "na razie", "pai kàwn", "ไปก่อน", "Odcinki czasu", 4, "adv", CD,
 "Dosłownie „iść najpierw”. Także formuła pożegnania: pai kàwn ná.", "iść przedtem"),
("A2", "zawsze", "sà-mǒoe", "เสมอ", "Częstotliwość", 5, "adv", CD,
 "", ""),
("A2", "często", "bòi", "บ่อย", "Częstotliwość", 5, "adv", CD,
 "bòi bòi — bardzo często.", ""),
("A2", "czasami", "baang khráng", "บางครั้ง", "Częstotliwość", 5, "adv", CD,
 "khráng to raz, przypadek.", "niektóry raz"),
("A2", "rzadko", "nâan nâan khráng", "นานๆครั้ง", "Częstotliwość", 3, "adv", CD,
 "Dosłownie „raz na długo”.", "długo długo raz"),
("A2", "nigdy", "mâi khooei", "ไม่เคย", "Częstotliwość", 5, "adv", CD,
 "khooei znaczy „mieć w zwyczaju, zdarzyło się kiedyś”.", "nie zdarzyło się"),
("A2", "codziennie", "thúk wan", "ทุกวัน", "Częstotliwość", 5, "adv", CD,
 "thúk to każdy: thúk khon, thúk khráng, thúk pii.", "każdy dzień"),
("A2", "co tydzień", "thúk aa-thít", "ทุกอาทิตย์", "Częstotliwość", 4, "adv", CD,
 "", "każdy tydzień"),
("A2", "raz na jakiś czas", "pen khráng khraao", "เป็นครั้งคราว", "Częstotliwość", 2, "adv", CD,
 "", "być raz okazja"),
("A2", "wiek (stulecie)", "sàt-tà-wát", "ศตวรรษ", "Kalendarz", 2, "n", CD,
 "", ""),
("A2", "dekada", "thót-sà-wát", "ทศวรรษ", "Kalendarz", 2, "n", CD,
 "thót- to dziesięć.", ""),
("A2", "pora roku", "rúe-duu", "ฤดู", "Kalendarz", 3, "n", CD,
 "Termin książkowy; w mowie mówi się nâa fǒn, nâa nǎao, nâa ráwn.", ""),
("A2", "święto", "wan sǎm-khan", "วันสำคัญ", "Kalendarz", 3, "n", CD,
 "sǎm-khan to ważny.", "dzień ważny"),
("A2", "urodziny", "wan kòoet", "วันเกิด", "Kalendarz", 5, "n", CD,
 "kòoet to rodzić się, zdarzyć się.", "dzień urodzić się"),
("A2", "Nowy Rok", "pii mài", "ปีใหม่", "Kalendarz", 4, "n", CD,
 "Tajski Nowy Rok to Songkran w kwietniu, ale świętuje się też pierwszego stycznia.", "rok nowy"),
("A2", "kalendarz", "pà-thí-thin", "ปฏิทิน", "Kalendarz", 3, "n", CD,
 "Rok buddyjski jest o 543 lata wyższy od naszego — na dokumentach zobaczysz 2569.", ""),
("A2", "termin, wyznaczony czas", "kam-nòt", "กำหนด", "Kalendarz", 3, "n", CD,
 "", ""),
("A2", "przełożyć (termin)", "lûean", "เลื่อน", "Kalendarz", 4, "v", CD,
 "Ten sam czasownik co w ban-dai lûean (schody ruchome).", ""),
("A2", "odwołać", "yók lôek", "ยกเลิก", "Kalendarz", 4, "v", CD,
 "yók to podnosić, lôek to kończyć.", "podnosić kończyć"),

# ============================================================ LICZBY
("A2", "połowa", "khrûeng", "ครึ่ง", "Ułamki i ilości", 5, "n", LI,
 "khrûeng chûa-moong — pół godziny.", ""),
("A2", "ćwierć", "sèet nùeng sùan sìi", "เศษหนึ่งส่วนสี่", "Ułamki i ilości", 2, "n", LI,
 "Konstrukcja ułamka: licznik sùan mianownik.", "reszta jeden część cztery"),
("A2", "procent", "poe-sen", "เปอร์เซ็นต์", "Ułamki i ilości", 4, "n", LI,
 "", ""),
("A2", "podwójny", "sǎwng thâo", "สองเท่า", "Ułamki i ilości", 3, "adj", LI,
 "thâo to krotność.", "dwa raz"),
("A2", "para (dwie sztuki)", "khûu", "คู่", "Ułamki i ilości", 4, "n", LI,
 "Klasyfikator butów, skarpet i małżonków.", ""),
("A2", "tuzin", "lǒo", "โหล", "Ułamki i ilości", 2, "n", LI,
 "Z angielskiego dozen. Na targu hurtowym używane.", ""),
("A2", "kilogram", "kì-loo", "กิโล", "Miary", 5, "n", LI,
 "Skrót od kì-loo-kram; ten sam skrót co dla kilometra — rozstrzyga kontekst.", ""),
("A2", "gram", "kram", "กรัม", "Miary", 3, "n", LI,
 "", ""),
("A2", "litr", "lít", "ลิตร", "Miary", 3, "n", LI,
 "", ""),
("A2", "cal", "níu", "นิ้ว", "Miary", 3, "n", LI,
 "To samo słowo znaczy „palec” — miara wzięta z ciała.", ""),
("A2", "waga (ciężar)", "nám-nàk", "น้ำหนัก", "Miary", 4, "n", LI,
 "Dosłownie „woda ciężka”.", "woda ciężki"),
("A2", "wysokość, wzrost", "khwaam sǔung", "ความสูง", "Miary", 3, "n", LI,
 "", "stan wysoki"),
("A2", "szerokość", "khwaam kwâang", "ความกว้าง", "Miary", 2, "n", LI,
 "", "stan szeroki"),
("A2", "długość", "khwaam yaao", "ความยาว", "Miary", 2, "n", LI,
 "", "stan długi"),
("A2", "głębokość", "khwaam lúek", "ความลึก", "Miary", 2, "n", LI,
 "Także o myśli: lúek sûeng.", "stan głęboki"),
("A2", "dodać", "bùak", "บวก", "Działania", 3, "v", LI,
 "Także „plus” w temperaturze.", ""),
("A2", "odjąć", "lóp", "ลบ", "Działania", 3, "v", LI,
 "To samo słowo co „wymazać”.", ""),
("A2", "pomnożyć", "khuun", "คูณ", "Działania", 2, "v", LI,
 "", ""),
("A2", "podzielić", "hǎan", "หาร", "Działania", 2, "v", LI,
 "Także „podzielić rachunek”: hǎan khrûeng.", ""),
("A2", "razem, w sumie", "ruam", "รวม", "Działania", 5, "v", LI,
 "ruam tháng mòt — razem wszystko. Kluczowe przy rachunku.", ""),
("A2", "liczyć", "náp", "นับ", "Działania", 4, "v", LI,
 "Także „uważać za, zaliczać do”.", ""),
("A2", "około, mniej więcej", "prà-maan", "ประมาณ", "Szacowanie", 5, "adv", LI,
 "Bardzo częste w mowie — Taj rzadko podaje liczbę bez tego słowa.", ""),
("A2", "co najmniej", "yàang náwi", "อย่างน้อย", "Szacowanie", 4, "adv", LI,
 "", "sposób mało"),
("A2", "najwyżej", "mâi kooen", "ไม่เกิน", "Szacowanie", 4, "adv", LI,
 "kooen to przekraczać.", "nie przekraczać"),
("A2", "więcej", "mâak kwàa", "มากกว่า", "Szacowanie", 5, "adv", LI,
 "", "dużo niż"),
("A2", "wystarczy", "phaw", "พอ", "Szacowanie", 5, "adj", LI,
 "phaw láew — wystarczy już. Bardzo częste przy nalewaniu.", ""),
("A2", "za mało", "mâi phaw", "ไม่พอ", "Szacowanie", 4, "adj", LI,
 "", "nie wystarczyć"),
("A2", "numer, cyfra", "mǎai lêek", "หมายเลข", "Zapis liczb", 4, "n", LI,
 "W mowie częściej boe — z angielskiego number.", "znak liczba"),
("A2", "pierwszy", "thîi nùeng", "ที่หนึ่ง", "Zapis liczb", 5, "adj", LI,
 "thîi przed liczbą tworzy liczebnik porządkowy.", "miejsce jeden"),
("A2", "ostatni", "sùt tháai", "สุดท้าย", "Zapis liczb", 5, "adj", LI,
 "sùt to kres, tháai to koniec, tył.", "kres koniec"),
]
