# -*- coding: utf-8 -*-
"""Leksyka etapu 4 (B1) — czesc A.

Zakres: naturalna codzienna rozmowa, rozwijanie opinii, zgoda, niezgoda,
uprzejme kontrargumenty, lagodzenie wypowiedzi, zmiana zdania.

Krotka: (polski, fonetyka, tajski, kategoria, podkategoria, typ, freq, rejestr,
         notatka, znaczenie doslowne, przyklad)
Rejestr: n = neutralny, f = formalny, i = nieformalny, p = potoczny
Przyklad: (polski, fonetyka, tajski)
"""

CORE_A = [

# =====================================================================
# ROZWIJANIE OPINII
# =====================================================================
("Moim zdaniem to dobry pomysł.", "nai khwaam-khít phǒm man pen khwaam-khít thîi dii khráp",
 "ในความคิดผมมันเป็นความคิดที่ดีครับ", "Cechy i opinie", "Opinie", "sentence", 4, "n",
 "„nai khwaam-khít phǒm” otwiera opinię bez narzucania jej rozmówcy.", "w mojej myśli",
 ("A jakie jest twoje zdanie?", "khun khít yang-ngai khráp", "คุณคิดยังไงครับ")),
("Jeśli chodzi o mnie, wolę spokojniej.", "sǎm-ràp phǒm phǒm châwp bàep ngîap ngîap mâak-kwàa khráp",
 "สำหรับผมผมชอบแบบเงียบๆ มากกว่าครับ", "Cechy i opinie", "Opinie", "sentence", 3, "n",
 "„sǎm-ràp phǒm” = jeśli o mnie chodzi. Zaznacza, że to tylko twój punkt widzenia.", "",
 ("Ja też tak mam.", "phǒm kâw mǔean kan khráp", "ผมก็เหมือนกันครับ")),
("Szczerze mówiąc, nie bardzo mi się to podoba.", "phûut trong trong ná khráp phǒm mâi khâwi châwp",
 "พูดตรงๆ นะครับ ผมไม่ค่อยชอบ", "Cechy i opinie", "Opinie", "sentence", 4, "n",
 "„phûut trong trong” zapowiada szczerą, ale wciąż uprzejmą uwagę.", "mówiąc prosto",
 ("Powiedz, co ci nie pasuje.", "bàwk maa loei khráp wâa mâi châwp trong nǎi", "บอกมาเลยครับว่าไม่ชอบตรงไหน")),
("Tak naprawdę to zależy od sytuacji.", "thîi jing láew man khûen yùu kàp sà-thǎa-ná-kaan khráp",
 "ที่จริงแล้วมันขึ้นอยู่กับสถานการณ์ครับ", "Gramatyka użytkowa", "Opinie", "sentence", 4, "n",
 "„khûen yùu kàp” = zależeć od. Bardzo częsty zwrot w dyskusji.", "to zależy od sytuacji",
 ("Racja, nie da się powiedzieć na pewno.", "châi khráp bàwk nâe nawn mâi dâai", "ใช่ครับ บอกแน่นอนไม่ได้")),
("Trudno powiedzieć jednoznacznie.", "phûut hâi chát chát yâak khráp", "พูดให้ชัดๆ ยากครับ",
 "Cechy i opinie", "Opinie", "sentence", 3, "n", "", "",
 ("Rozumiem.", "khâo-jai khráp", "เข้าใจครับ")),
("Widzę to trochę inaczej.", "phǒm mawng tàang pai nít nùeng khráp", "ผมมองต่างไปนิดหนึ่งครับ",
 "Cechy i opinie", "Niezgoda", "sentence", 4, "n",
 "„mawng tàang” = patrzeć inaczej. Łagodniejsze niż wprost „nie zgadzam się”.", "patrzę odmiennie",
 ("To powiedz jak.", "bàwk maa sì khráp", "บอกมาสิครับ")),
("Z mojego doświadczenia wygląda to inaczej.", "jàak prà-sòp-kaan phǒm man mâi mǔean yàang nán khráp",
 "จากประสบการณ์ผมมันไม่เหมือนอย่างนั้นครับ", "Cechy i opinie", "Opinie", "sentence", 3, "f",
 "„prà-sòp-kaan” = doświadczenie. Rejestr formalny, dobry w pracy.", "",
 ("Opowiedz.", "lâo hâi fang nòi khráp", "เล่าให้ฟังหน่อยครับ")),
("Nie mam co do tego zdania.", "rûeang níi phǒm mâi mii khwaam-hěn khráp", "เรื่องนี้ผมไม่มีความเห็นครับ",
 "Cechy i opinie", "Opinie", "sentence", 3, "n", "„khwaam-hěn” = opinia, pogląd.", "",
 ("Nie ma sprawy.", "mâi pen rai khráp", "ไม่เป็นไรครับ")),
("Zależy, jak na to spojrzeć.", "láew tàae wâa jà mawng mum nǎi khráp", "แล้วแต่ว่าจะมองมุมไหนครับ",
 "Gramatyka użytkowa", "Opinie", "sentence", 3, "n", "„mum” = kąt, punkt widzenia.", "",
 ("Dobrze powiedziane.", "phûut dâai dii khráp", "พูดได้ดีครับ")),
("Powiem tak: to ma sens.", "phǒm khǎw phûut yàang níi khráp man mii hèet-phǒn",
 "ผมขอพูดอย่างนี้ครับ มันมีเหตุผล", "Cechy i opinie", "Opinie", "sentence", 3, "n",
 "„mii hèet-phǒn” = mieć sens, być uzasadnionym.", "",
 ("Zgoda.", "hěn dûai khráp", "เห็นด้วยครับ")),
("Uważam, że warto spróbować.", "phǒm khít wâa nâa lawng duu khráp", "ผมคิดว่าน่าลองดูครับ",
 "Cechy i opinie", "Opinie", "sentence", 4, "n", "„nâa …” = warto, aż się prosi żeby.", "",
 ("To spróbujmy.", "ngán lawng duu kan khráp", "งั้นลองดูกันครับ")),
("Mam co do tego wątpliwości.", "phǒm yang sǒng-sǎi yùu khráp", "ผมยังสงสัยอยู่ครับ",
 "Cechy i opinie", "Niezgoda", "sentence", 3, "n", "„sǒng-sǎi” = wątpić, ale też: być ciekawym.", "",
 ("Co dokładnie?", "sǒng-sǎi trong nǎi khráp", "สงสัยตรงไหนครับ")),

# =====================================================================
# ZGODA
# =====================================================================
("Całkowicie się zgadzam.", "hěn dûai yàang yîng khráp", "เห็นด้วยอย่างยิ่งครับ",
 "Podstawy i grzeczność", "Zgoda", "phrase", 4, "f",
 "„yàang yîng” to wzmocnienie formalne — na zebraniu tak, w barze nie.", "",
 ("Cieszę się.", "dii jai khráp", "ดีใจครับ")),
("Też tak myślę.", "phǒm kâw khít yàang nán khráp", "ผมก็คิดอย่างนั้นครับ",
 "Podstawy i grzeczność", "Zgoda", "phrase", 5, "n", "", "",
 ("To mamy to samo zdanie.", "ngán khít mǔean kan khráp", "งั้นคิดเหมือนกันครับ")),
("No właśnie.", "nân ná sì khráp", "นั่นน่ะสิครับ", "Small talk", "Reakcje", "phrase", 5, "i",
 "Bardzo naturalne potwierdzenie w rozmowie. W piśmie urzędowym nie występuje.", "",
 ("Dobrze, że rozumiesz.", "dii thîi khâo-jai khráp", "ดีที่เข้าใจครับ")),
("Dokładnie tak.", "châi loei khráp", "ใช่เลยครับ", "Small talk", "Reakcje", "phrase", 5, "n", "", "",
 ("Wiedziałem, że się zgodzisz.", "rúu wâa tâwng hěn dûai khráp", "รู้ว่าต้องเห็นด้วยครับ")),
("Masz rację.", "khun phûut thùuk khráp", "คุณพูดถูกครับ", "Podstawy i grzeczność", "Zgoda", "phrase", 5, "n", "", "",
 ("Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ")),
("Zgadzam się z tobą w tej sprawie.", "rûeang níi phǒm hěn dûai kàp khun khráp", "เรื่องนี้ผมเห็นด้วยกับคุณครับ",
 "Podstawy i grzeczność", "Zgoda", "sentence", 4, "n", "", "",
 ("To dobrze.", "dii khráp", "ดีครับ")),
("Brzmi rozsądnie.", "fang duu mii hèet-phǒn khráp", "ฟังดูมีเหตุผลครับ",
 "Cechy i opinie", "Zgoda", "phrase", 4, "n", "„fang duu” = brzmi, sprawia wrażenie.", "",
 ("To ustalone.", "tòk long taam nán khráp", "ตกลงตามนั้นครับ")),
("Zgadzam się częściowo.", "phǒm hěn dûai baang sùan khráp", "ผมเห็นด้วยบางส่วนครับ",
 "Cechy i opinie", "Zgoda", "phrase", 3, "f", "„baang sùan” = częściowo. Otwiera drogę do kontrargumentu.", "",
 ("A z czym nie?", "sùan nǎi thîi mâi hěn dûai khráp", "ส่วนไหนที่ไม่เห็นด้วยครับ")),
("Rozumiem twój punkt widzenia.", "phǒm khâo-jai mum mawng khǎwng khun khráp", "ผมเข้าใจมุมมองของคุณครับ",
 "Podstawy i grzeczność", "Zgoda", "sentence", 4, "f", "", "",
 ("Dziękuję za wyrozumiałość.", "khàwp-khun thîi khâo-jai khráp", "ขอบคุณที่เข้าใจครับ")),
("Zróbmy tak.", "tham bàep nán loei khráp", "ทำแบบนั้นเลยครับ", "Podstawy i grzeczność", "Zgoda", "phrase", 4, "n", "", "",
 ("Umowa stoi.", "tòk long khráp", "ตกลงครับ")),
("Nie mam nic przeciwko.", "phǒm mâi mii pan-hǎa khráp", "ผมไม่มีปัญหาครับ",
 "Podstawy i grzeczność", "Zgoda", "phrase", 4, "n", "", "nie mam problemu",
 ("To świetnie.", "dii loei khráp", "ดีเลยครับ")),

# =====================================================================
# NIEZGODA I UPRZEJME KONTRARGUMENTY
# =====================================================================
("Zgadzam się, ale jest jeden problem.", "hěn dûai khráp tàae mii yùu rûeang nùeng",
 "เห็นด้วยครับ แต่มีอยู่เรื่องหนึ่ง", "Cechy i opinie", "Niezgoda", "sentence", 4, "n",
 "Tajski schemat uprzejmego sporu: najpierw zgoda, potem „tàae”. Zaczynanie od „mâi” brzmi ostro.", "",
 ("Mów śmiało.", "wâa maa loei khráp", "ว่ามาเลยครับ")),
("Rozumiem, ale nie do końca się zgadzam.", "khâo-jai khráp tàae mâi khâwi hěn dûai thâo-rài",
 "เข้าใจครับ แต่ไม่ค่อยเห็นด้วยเท่าไหร่", "Cechy i opinie", "Niezgoda", "sentence", 4, "n",
 "„mâi khâwi … thâo-rài” osłabia zaprzeczenie — kluczowe dla uprzejmości.", "",
 ("A dlaczego?", "phrááw à-rai khráp", "เพราะอะไรครับ")),
("Może i tak, ale spójrz na to inaczej.", "kâw àat jà châi khráp tàae lawng mawng ìik mum nùeng",
 "ก็อาจจะใช่ครับ แต่ลองมองอีกมุมหนึ่ง", "Cechy i opinie", "Niezgoda", "sentence", 3, "n", "", "",
 ("Zamieniam się w słuch.", "fang yùu khráp", "ฟังอยู่ครับ")),
("Obawiam się, że to się nie uda.", "phǒm klua wâa man jà mâi wôet khráp", "ผมกลัวว่ามันจะไม่เวิร์คครับ",
 "Cechy i opinie", "Niezgoda", "sentence", 3, "p",
 "SLANG: „wôet” to spolszczone angielskie work. NIE używaj w piśmie urzędowym, na rozmowie o pracę ani wobec osób starszych — tam mów „mâi dâi phǒn”.", "",
 ("Czemu tak sądzisz?", "thammai khít yàang nán khráp", "ทำไมคิดอย่างนั้นครับ")),
("Nie jestem przekonany.", "phǒm yang mâi man-jai khráp", "ผมยังไม่มั่นใจครับ",
 "Cechy i opinie", "Niezgoda", "phrase", 4, "n", "„man-jai” = pewny, przekonany.", "",
 ("Co by cię przekonało?", "tâwng tham yang-ngai thǔeng jà man-jai khráp", "ต้องทำยังไงถึงจะมั่นใจครับ")),
("Nie chodzi o to, że jest źle.", "mâi châi wâa man mâi dii ná khráp", "ไม่ใช่ว่ามันไม่ดีนะครับ",
 "Cechy i opinie", "Niezgoda", "sentence", 4, "n",
 "„mâi châi wâa …” = nie chodzi o to, że… Klasyczny wstęp do sprostowania.", "",
 ("To o co?", "láew rûeang à-rai khráp", "แล้วเรื่องอะไรครับ")),
("Przyznaję, że masz trochę racji.", "phǒm yawm ráp wâa khun phûut thùuk baang sùan khráp",
 "ผมยอมรับว่าคุณพูดถูกบางส่วนครับ", "Cechy i opinie", "Niezgoda", "sentence", 3, "f",
 "„yawm ráp” = przyznawać, uznawać.", "",
 ("Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ")),
("Pozwól, że dokończę.", "khǎw phûut hâi jòp kàwn ná khráp", "ขอพูดให้จบก่อนนะครับ",
 "Podstawy i grzeczność", "Rozmowa", "phrase", 3, "n",
 "Uprzejme, ale stanowcze. Bez „khǎw” i „ná” brzmiałoby jak upomnienie.", "",
 ("Przepraszam, mów.", "khǎw-thôot khráp choen khráp", "ขอโทษครับ เชิญครับ")),
("Nie zgadzam się z tym w ogóle.", "phǒm mâi hěn dûai loei khráp", "ผมไม่เห็นด้วยเลยครับ",
 "Cechy i opinie", "Niezgoda", "sentence", 3, "n",
 "„loei” na końcu wzmacnia zaprzeczenie. Używaj świadomie — to mocne zdanie.", "",
 ("W porządku, rozumiem.", "dâai khráp khâo-jai", "ได้ครับ เข้าใจ")),
("Popatrzmy na to z drugiej strony.", "lawng mawng ìik dâan nùeng khráp", "ลองมองอีกด้านหนึ่งครับ",
 "Gramatyka użytkowa", "Dyskusja", "sentence", 3, "n", "", "",
 ("Dobry pomysł.", "khwaam-khít dii khráp", "ความคิดดีครับ")),
("To nie jest takie proste.", "man mâi ngâai khà-nàat nán khráp", "มันไม่ง่ายขนาดนั้นครับ",
 "Cechy i opinie", "Niezgoda", "sentence", 4, "n", "„khà-nàat nán” = aż tak, do tego stopnia.", "",
 ("Wiem.", "rúu khráp", "รู้ครับ")),
("Chyba się nie zrozumieliśmy.", "rao àat jà khâo-jai mâi trong kan khráp", "เราอาจจะเข้าใจไม่ตรงกันครับ",
 "Podstawy i grzeczność", "Rozmowa", "sentence", 3, "n",
 "„khâo-jai mâi trong kan” = rozumieć się rozbieżnie. Ratuje rozmowę bez oskarżania nikogo.", "",
 ("To wyjaśnijmy.", "ngán khui kan mài khráp", "งั้นคุยกันใหม่ครับ")),
("Zmieniłem zdanie.", "phǒm plìan jai láew khráp", "ผมเปลี่ยนใจแล้วครับ",
 "Cechy i opinie", "Opinie", "phrase", 4, "n", "", "",
 ("Nie ma problemu.", "mâi pen rai khráp", "ไม่เป็นไรครับ")),
("Przemyślałem to jeszcze raz.", "phǒm khít duu ìik thii láew khráp", "ผมคิดดูอีกทีแล้วครับ",
 "Cechy i opinie", "Opinie", "phrase", 4, "n", "„ìik thii” = jeszcze raz.", "",
 ("I co?", "láew ngai khráp", "แล้วไงครับ")),
("Przekonałeś mnie.", "khun tham hâi phǒm khâo-jai láew khráp", "คุณทำให้ผมเข้าใจแล้วครับ",
 "Cechy i opinie", "Zgoda", "phrase", 3, "n", "", "sprawiłeś, że zrozumiałem",
 ("Cieszę się.", "dii jai khráp", "ดีใจครับ")),
("Zostańmy przy tym, co ustaliliśmy.", "ao taam thîi tòk long wái ná khráp", "เอาตามที่ตกลงไว้นะครับ",
 "Podstawy i grzeczność", "Zgoda", "sentence", 3, "n", "", "",
 ("Zgoda.", "tòk long khráp", "ตกลงครับ")),

# =====================================================================
# PODTRZYMYWANIE ROZMOWY
# =====================================================================
("A ty co o tym sądzisz?", "láew khun khít yang-ngai khráp", "แล้วคุณคิดยังไงครับ",
 "Small talk", "Rozmowa", "question", 5, "n",
 "Najprostszy sposób oddania głosu. „láew khun …” = a ty…", "",
 ("Zaraz powiem.", "dǐao phǒm bàwk khráp", "เดี๋ยวผมบอกครับ")),
("Możesz powiedzieć coś więcej?", "lâo hâi fang ìik nòi dâai mǎi khráp", "เล่าให้ฟังอีกหน่อยได้ไหมครับ",
 "Small talk", "Rozmowa", "question", 4, "n", "„lâo hâi fang” = opowiedzieć komuś.", "",
 ("Jasne.", "dâai loei khráp", "ได้เลยครับ")),
("Nie chcę ci przerywać, ale…", "mâi yàak khàt jang-wà ná khráp tàae wâa",
 "ไม่อยากขัดจังหวะนะครับ แต่ว่า", "Podstawy i grzeczność", "Rozmowa", "phrase", 3, "f",
 "„khàt jang-wà” = przerywać komuś. Uprzejma wersja wejścia w słowo.", "",
 ("Mów śmiało.", "choen khráp", "เชิญครับ")),
("Wróćmy do tematu.", "klàp maa thîi rûeang doem khráp", "กลับมาที่เรื่องเดิมครับ",
 "Gramatyka użytkowa", "Rozmowa", "phrase", 3, "n", "„rûeang doem” = poprzedni, ten sam temat.", "",
 ("Racja.", "châi khráp", "ใช่ครับ")),
("A propos, chciałem cię o coś zapytać.", "phûut thǔeng láew phǒm yàak thǎam à-rai nòi khráp",
 "พูดถึงแล้ว ผมอยากถามอะไรหน่อยครับ", "Small talk", "Rozmowa", "sentence", 3, "n",
 "„phûut thǔeng láew” = skoro już o tym mowa.", "",
 ("Pytaj.", "thǎam maa loei khráp", "ถามมาเลยครับ")),
("Zmieńmy temat.", "plìan rûeang khui kan thòe khráp", "เปลี่ยนเรื่องคุยกันเถอะครับ",
 "Small talk", "Rozmowa", "phrase", 3, "i", "„thòe” to zachęta „no dalej, zróbmy tak”.", "",
 ("Dobrze.", "dâai khráp", "ได้ครับ")),
("Długo by opowiadać.", "man yaao khráp", "มันยาวครับ", "Small talk", "Rozmowa", "phrase", 3, "p",
 "Potocznie, dosłownie „to jest długie”. Odpowiednik polskiego „to długa historia”.", "to długie",
 ("Mamy czas.", "mii wee-laa khráp", "มีเวลาครับ")),
("Powiem ci to na osobności.", "dǐao khui sǒng tàw sǒng ná khráp", "เดี๋ยวคุยสองต่อสองนะครับ",
 "Ludzie i rodzina", "Rozmowa", "sentence", 2, "n", "„sǒng tàw sǒng” = w cztery oczy.", "dwóch na dwóch",
 ("Dobrze.", "dâai khráp", "ได้ครับ")),
("Zapytam wprost.", "phǒm khǎw thǎam trong trong khráp", "ผมขอถามตรงๆ ครับ",
 "Pytania", "Rozmowa", "phrase", 3, "n", "", "",
 ("Proszę bardzo.", "choen khráp", "เชิญครับ")),
("Nie wiem, czy dobrze rozumiem.", "phǒm mâi nâe-jai wâa khâo-jai thùuk mǎi khráp",
 "ผมไม่แน่ใจว่าเข้าใจถูกไหมครับ", "Pytania", "Rozmowa", "sentence", 4, "n", "", "",
 ("Wyjaśnię jeszcze raz.", "dǐao à-thí-baai mài khráp", "เดี๋ยวอธิบายใหม่ครับ")),
("Czy dobrze cię zrozumiałem?", "phǒm khâo-jai thùuk mǎi khráp", "ผมเข้าใจถูกไหมครับ",
 "Pytania", "Rozmowa", "question", 4, "n", "", "",
 ("Tak, dokładnie.", "châi khráp trong nán loei", "ใช่ครับ ตรงนั้นเลย")),
("Powtórz, proszę, wolniej.", "phûut cháa cháa ìik thii dâai mǎi khráp", "พูดช้าๆ อีกทีได้ไหมครับ",
 "Podstawy i grzeczność", "Rozmowa", "phrase", 5, "n", "", "",
 ("Jasne.", "dâai khráp", "ได้ครับ")),
("Nie usłyszałem ostatniego słowa.", "phǒm mâi dâi yin kham sùt-tháai khráp", "ผมไม่ได้ยินคำสุดท้ายครับ",
 "Podstawy i grzeczność", "Rozmowa", "sentence", 3, "n", "„dâi yin” = usłyszeć, w odróżnieniu od „fang” = słuchać.", "",
 ("Powtórzę.", "phûut mài khráp", "พูดใหม่ครับ")),
("Zaraz, zaraz.", "dǐao dǐao khráp", "เดี๋ยวๆ ครับ", "Small talk", "Reakcje", "phrase", 4, "i",
 "Zatrzymuje rozmówcę, gdy coś się nie zgadza. Grzeczne między znajomymi, nie wobec przełożonego.", "",
 ("Co się stało?", "à-rai rǒe khráp", "อะไรหรือครับ")),
("Mówiąc krótko…", "phûut sân sân khue", "พูดสั้นๆ คือ", "Gramatyka użytkowa", "Rozmowa", "phrase", 4, "n", "", "",
 ("Słucham.", "fang yùu khráp", "ฟังอยู่ครับ")),
("Chodzi mi o to, że…", "thîi phǒm màai thǔeng khue", "ที่ผมหมายถึงคือ",
 "Gramatyka użytkowa", "Rozmowa", "phrase", 4, "n", "„màai thǔeng” = mieć na myśli.", "",
 ("Teraz jasne.", "tawn níi khâo-jai láew khráp", "ตอนนี้เข้าใจแล้วครับ")),
("Źle się wyraziłem.", "phǒm phûut mâi chát khráp", "ผมพูดไม่ชัดครับ",
 "Podstawy i grzeczność", "Rozmowa", "phrase", 3, "n", "", "mówiłem niewyraźnie",
 ("Nie szkodzi.", "mâi pen rai khráp", "ไม่เป็นไรครับ")),
("Chcę to jeszcze doprecyzować.", "phǒm khǎw à-thí-baai phôoem nòi khráp", "ผมขออธิบายเพิ่มหน่อยครับ",
 "Praca i nauka", "Rozmowa", "sentence", 3, "f", "„à-thí-baai” = tłumaczyć, objaśniać.", "",
 ("Proszę.", "choen khráp", "เชิญครับ")),
("Podsumowując…", "sà-rùp láew khue", "สรุปแล้วคือ", "Praca i nauka", "Rozmowa", "phrase", 4, "f",
 "„sà-rùp” = podsumować. Bardzo częste na zebraniach.", "",
 ("Dobrze.", "khráp", "ครับ")),
("Zostawmy to na później.", "khǎw kèp wái khui thii lǎng khráp", "ขอเก็บไว้คุยทีหลังครับ",
 "Praca i nauka", "Rozmowa", "sentence", 3, "n", "", "",
 ("Dobrze.", "dâai khráp", "ได้ครับ")),

# =====================================================================
# LAGODZENIE I DYSTANS
# =====================================================================
("Może się mylę, ale…", "phǒm àat jà khâo-jai phìt ná khráp tàae wâa",
 "ผมอาจจะเข้าใจผิดนะครับ แต่ว่า", "Gramatyka użytkowa", "Opinie", "phrase", 4, "n",
 "Najbezpieczniejszy wstęp do sprzeciwu wobec osoby starszej lub przełożonego.", "",
 ("Mów.", "wâa maa khráp", "ว่ามาครับ")),
("O ile dobrze pamiętam…", "thâo thîi phǒm jam dâai", "เท่าที่ผมจำได้",
 "Gramatyka użytkowa", "Opinie", "phrase", 4, "n", "„thâo thîi …” = o ile, na tyle na ile.", "",
 ("I co pamiętasz?", "jam à-rai dâai bâang khráp", "จำอะไรได้บ้างครับ")),
("O ile mi wiadomo…", "thâo thîi phǒm rúu", "เท่าที่ผมรู้",
 "Gramatyka użytkowa", "Opinie", "phrase", 4, "f", "", "",
 ("Rozumiem.", "khâo-jai khráp", "เข้าใจครับ")),
("Nie chcę nikogo urazić.", "mâi yàak hâi khrai sǐa jai khráp", "ไม่อยากให้ใครเสียใจครับ",
 "Podstawy i grzeczność", "Rozmowa", "sentence", 3, "f", "„sǐa jai” = poczuć się źle, zasmucić się.", "",
 ("Nikt się nie obrazi.", "mâi mii khrai wâa khráp", "ไม่มีใครว่าครับ")),
("Powiedziałbym raczej inaczej.", "phǒm khǎw phûut ìik bàep nùeng khráp", "ผมขอพูดอีกแบบหนึ่งครับ",
 "Cechy i opinie", "Niezgoda", "sentence", 3, "n", "", "",
 ("Śmiało.", "choen khráp", "เชิญครับ")),
("Nie jest to takie oczywiste.", "man mâi chát khà-nàat nán khráp", "มันไม่ชัดขนาดนั้นครับ",
 "Cechy i opinie", "Opinie", "sentence", 3, "n", "", "",
 ("Zgadza się.", "châi khráp", "ใช่ครับ")),
("Pod pewnym względem masz rację.", "baang mum khun kâw phûut thùuk khráp", "บางมุมคุณก็พูดถูกครับ",
 "Cechy i opinie", "Zgoda", "sentence", 3, "n", "", "",
 ("Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ")),
("Wolałbym o tym nie mówić.", "phǒm khǎw mâi phûut rûeang níi ná khráp", "ผมขอไม่พูดเรื่องนี้นะครับ",
 "Podstawy i grzeczność", "Rozmowa", "sentence", 3, "f",
 "Uprzejma odmowa rozmowy. „khǎw mâi …” = poproszę o niezrobienie czegoś.", "",
 ("Rozumiem.", "khâo-jai khráp", "เข้าใจครับ")),
("To dla mnie trudny temat.", "rûeang níi man yâak sǎm-ràp phǒm khráp", "เรื่องนี้มันยากสำหรับผมครับ",
 "Ludzie i rodzina", "Rozmowa", "sentence", 3, "n", "", "",
 ("Przepraszam, że zapytałem.", "khǎw-thôot thîi thǎam khráp", "ขอโทษที่ถามครับ")),
("Nie chcę się wtrącać.", "mâi yàak yûng khráp", "ไม่อยากยุ่งครับ",
 "Ludzie i rodzina", "Rozmowa", "phrase", 3, "n", "„yûng” = mieszać się w coś, ale też: być zajętym.", "",
 ("Nie przeszkadzasz.", "mâi dâi yûng khráp", "ไม่ได้ยุ่งครับ")),
("To zależy od ciebie.", "láew tàae khun khráp", "แล้วแต่คุณครับ",
 "Gramatyka użytkowa", "Opinie", "phrase", 5, "n",
 "„láew tàae” to jedno z najczęstszych zdań w tajskim. Bez niego trudno o naturalną rozmowę.", "",
 ("To ty zdecyduj.", "khun tàt-sǐn jai loei khráp", "คุณตัดสินใจเลยครับ")),
("Zrobię, jak uważasz.", "tham taam thîi khun wâa khráp", "ทำตามที่คุณว่าครับ",
 "Podstawy i grzeczność", "Zgoda", "sentence", 3, "n", "", "",
 ("Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ")),
("Wszystko jedno.", "à-rai kâw dâai khráp", "อะไรก็ได้ครับ",
 "Podstawy i grzeczność", "Rozmowa", "phrase", 5, "n",
 "Uwaga: przy zamawianiu jedzenia dla Taja to realna odpowiedź, nie unik.", "",
 ("Na pewno?", "nâe jai ná khráp", "แน่ใจนะครับ")),
("Nie mam preferencji.", "phǒm mâi mii khwaam tàang khráp", "ผมไม่มีความต่างครับ",
 "Cechy i opinie", "Opinie", "phrase", 2, "f", "", "",
 ("To ja wybiorę.", "ngán phǒm lûeak hâi khráp", "งั้นผมเลือกให้ครับ")),
("Powiedzmy, że tak.", "kâw thǔe wâa châi khráp", "ก็ถือว่าใช่ครับ",
 "Gramatyka użytkowa", "Zgoda", "phrase", 3, "p",
 "„thǔe wâa” = uznajmy, przyjmijmy że. Potoczne, ale nie wulgarne.", "",
 ("Czyli tak.", "ngán kâw châi khráp", "งั้นก็ใช่ครับ")),
]
