# -*- coding: utf-8 -*-
"""Leksyka etapu 4 (B1) — czesc F.

Zakres: podroze po Tajlandii (autobusy nocne, promy, wyspy, targowanie sie
o transport), relacje miedzyludzkie, nieporozumienia i konflikty, przeprosiny,
godzenie sie.

Format jak w lex_b1_core_a.py.
"""

CORE_F = [

# =====================================================================
# PODROZE PO TAJLANDII
# =====================================================================
("Jak najlepiej dostać się na wyspę?", "pai kàw yang-ngai dii thîi sùt khráp",
 "ไปเกาะยังไงดีที่สุดครับ", "Transport", "Podróże", "question", 4, "n",
 "„kàw” = wyspa. Nazwy wysp zaczynają się właśnie tym słowem.", "",
 ("Promem z Surat.", "nâng ruea jàak sù-râat khráp", "นั่งเรือจากสุราษฎร์ครับ")),
("O której odpływa prom?", "ruea àwk kìi moong khráp", "เรือออกกี่โมงครับ",
 "Transport", "Podróże", "question", 4, "n", "„àwk” = odjeżdżać, odpływać.", "",
 ("O ósmej rano.", "pàet moong cháo khráp", "แปดโมงเช้าครับ")),
("Czy jest nocny autobus?", "mii rót fai thîi wîng klaang khuen mǎi khráp",
 "มีรถไฟที่วิ่งกลางคืนไหมครับ", "Transport", "Podróże", "question", 3, "n",
 "„klaang khuen” = w nocy, nocny kurs.", "",
 ("Jest o dwudziestej.", "mii tawn sǎwng thûm khráp", "มีตอนสองทุ่มครับ")),
("Ile godzin trwa podróż?", "chái wee-laa dòoen thaang kìi chûa moong khráp",
 "ใช้เวลาเดินทางกี่ชั่วโมงครับ", "Transport", "Podróże", "question", 4, "n",
 "„dòoen thaang” = podróżować, przemieszczać się.", "",
 ("Około ośmiu.", "prà-maan pàet chûa moong khráp", "ประมาณแปดชั่วโมงครับ")),
("Czy bilet trzeba kupić wcześniej?", "tâwng sǔe tǔa lûang nâa mǎi khráp",
 "ต้องซื้อตั๋วล่วงหน้าไหมครับ", "Transport", "Podróże", "question", 4, "n", "", "",
 ("Lepiej wcześniej.", "sǔe lûang nâa dii kwàa khráp", "ซื้อล่วงหน้าดีกว่าครับ")),
("Czy to jest bezpośredni kurs?", "pai trong rǔe tâwng tàw rót khráp", "ไปตรงหรือต้องต่อรถครับ",
 "Transport", "Podróże", "question", 3, "n", "„tàw rót” = przesiadać się.", "",
 ("Trzeba się przesiąść.", "tâwng tàw rót khráp", "ต้องต่อรถครับ")),
("Gdzie mam się przesiąść?", "tàw rót thîi nǎi khráp", "ต่อรถที่ไหนครับ",
 "Transport", "Podróże", "question", 4, "n", "", "",
 ("W Chumphon.", "thîi chum-phawn khráp", "ที่ชุมพรครับ")),
("Ile kosztuje kurs do centrum?", "khâa rót khâo mueang thâo-rài khráp", "ค่ารถเข้าเมืองเท่าไหร่ครับ",
 "Transport", "Podróże", "question", 4, "n", "„khâo mueang” = do miasta, do centrum.", "",
 ("Trzysta bahtów.", "sǎam ráwi bàat khráp", "สามร้อยบาทครับ")),
("Czy może pan włączyć taksometr?", "kòt mí-tôoe dûai dâai mǎi khráp", "กดมิเตอร์ด้วยได้ไหมครับ",
 "Transport", "Podróże", "question", 4, "n",
 "Prośba o licznik zamiast ceny umownej. Warto ją znać przed wsiadaniem, nie po.", "",
 ("Dobrze.", "dâai khráp", "ได้ครับ")),
("To za drogo, dziękuję.", "phaeng koen pai khráp khàwp-khun", "แพงเกินไปครับ ขอบคุณ",
 "Transport", "Podróże", "sentence", 4, "n",
 "Odejście z uśmiechem i podziękowaniem działa lepiej niż spór o cenę.", "",
 ("To ile pan da?", "hâi thâo-rài khráp", "ให้เท่าไหร่ครับ")),
("Czy da się taniej?", "lót dâai ìik mǎi khráp", "ลดได้อีกไหมครับ",
 "Transport", "Podróże", "question", 4, "n", "", "",
 ("Ostatnia cena.", "raa-khaa sùt-tháai khráp", "ราคาสุดท้ายครับ")),
("Gdzie mogę wynająć skuter?", "châo maw-toe-sai dâai thîi nǎi khráp", "เช่ามอเตอร์ไซค์ได้ที่ไหนครับ",
 "Transport", "Podróże", "question", 4, "n", "", "",
 ("Tu obok.", "trong khâang khâang níi khráp", "ตรงข้างๆ นี้ครับ")),
("Czy potrzebne jest prawo jazdy?", "tâwng chái bai khàp khìi mǎi khráp", "ต้องใช้ใบขับขี่ไหมครับ",
 "Transport", "Podróże", "question", 4, "f",
 "Tak — policja to sprawdza, a brak dokumentu unieważnia ubezpieczenie.", "",
 ("Tak, koniecznie.", "tâwng chái khráp", "ต้องใช้ครับ")),
("Co warto tu zobaczyć?", "thǎew níi mii à-rai nâa duu bâang khráp", "แถวนี้มีอะไรน่าดูบ้างครับ",
 "Miejsca i orientacja", "Podróże", "question", 5, "n", "„thǎew níi” = w tej okolicy.", "",
 ("Wodospad jest niedaleko.", "náam tòk yùu mâi klai khráp", "น้ำตกอยู่ไม่ไกลครับ")),
("Jak długo się tam idzie?", "dòoen pai naan thâo-rài khráp", "เดินไปนานเท่าไหร่ครับ",
 "Miejsca i orientacja", "Podróże", "question", 4, "n", "", "",
 ("Dwadzieścia minut.", "yîi-sìp naa-thii khráp", "ยี่สิบนาทีครับ")),
("Czy jest tam wstęp płatny?", "khâa khâo thâo-rài khráp", "ค่าเข้าเท่าไหร่ครับ",
 "Miejsca i orientacja", "Podróże", "question", 4, "n", "", "",
 ("Sto bahtów.", "nùeng ráwi bàat khráp", "หนึ่งร้อยบาทครับ")),
("Zgubiłem się.", "phǒm lǒng thaang khráp", "ผมหลงทางครับ",
 "Miejsca i orientacja", "Podróże", "sentence", 4, "n", "„lǒng thaang” = zgubić drogę.", "",
 ("Dokąd pan idzie?", "jà pai nǎi khráp", "จะไปไหนครับ")),
("Spóźniłem się na autobus.", "phǒm tòk rót khráp", "ผมตกรถครับ",
 "Transport", "Podróże", "sentence", 3, "n",
 "„tòk rót” dosłownie „spaść z pojazdu” — po polsku „nie zdążyć”. Kalka „phlâat rót” byłaby niezrozumiała.", "spaść z pojazdu",
 ("Następny za godzinę.", "khan tàw pai ìik chûa moong khráp", "คันต่อไปอีกชั่วโมงครับ")),
("Czy ten autobus zatrzymuje się w Hua Hin?", "rót khan níi jàwt hǔa hǐn mǎi khráp",
 "รถคันนี้จอดหัวหินไหมครับ", "Transport", "Podróże", "question", 3, "n", "", "",
 ("Tak, zatrzymuje.", "jàwt khráp", "จอดครับ")),
("Proszę mi powiedzieć, kiedy wysiąść.", "thǔeng láew bàwk dûai ná khráp", "ถึงแล้วบอกด้วยนะครับ",
 "Transport", "Podróże", "sentence", 4, "n", "", "",
 ("Dobrze.", "dâai khráp", "ได้ครับ")),
("W porze deszczowej trudno tam dojechać.", "nâa fǒn pai lam-bàak khráp", "หน้าฝนไปลำบากครับ",
 "Pogoda i przyroda", "Podróże", "sentence", 3, "n",
 "„nâa fǒn” = pora deszczowa. „lam-bàak” = uciążliwy, trudny.", "",
 ("To pojadę zimą.", "ngán pai nâa nǎao khráp", "งั้นไปหน้าหนาวครับ")),
("Wolę podróżować sam.", "phǒm châwp pai khon diao mâak-kwàa khráp", "ผมชอบไปคนเดียวมากกว่าครับ",
 "Transport", "Podróże", "sentence", 3, "n", "", "",
 ("Rozumiem.", "khâo-jai khráp", "เข้าใจครับ")),

# =====================================================================
# RELACJE
# =====================================================================
("Znamy się od dawna.", "rao rúu-jàk kan maa naan láew khráp", "เรารู้จักกันมานานแล้วครับ",
 "Ludzie i rodzina", "Relacje", "sentence", 4, "n", "„rúu-jàk kan” = znać się nawzajem.", "",
 ("To miło.", "dii ná khráp", "ดีนะครับ")),
("Poznaliśmy się w pracy.", "rao jôe kan thîi thîi tham ngaan khráp", "เราเจอกันที่ที่ทำงานครับ",
 "Ludzie i rodzina", "Relacje", "sentence", 3, "n", "", "",
 ("Aha.", "âw khráp", "อ๋อครับ")),
("Dobrze się dogadujemy.", "rao khui kan rúu rûeang khráp", "เราคุยกันรู้เรื่องครับ",
 "Ludzie i rodzina", "Relacje", "sentence", 3, "n",
 "„khui kan rúu rûeang” = rozumieć się w rozmowie. Nie tłumacz tego jako „rozmawiamy dobrze”.", "",
 ("To najważniejsze.", "sǎm-khan thîi sùt khráp", "สำคัญที่สุดครับ")),
("Możesz na mnie liczyć.", "wǎi jai phǒm dâai khráp", "ไว้ใจผมได้ครับ",
 "Ludzie i rodzina", "Relacje", "sentence", 3, "n", "„wǎi jai” = ufać, powierzać zaufanie.", "",
 ("Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ")),
("Zawsze mi pomagał.", "khǎo chûai phǒm mǎa tà-làwt khráp", "เขาช่วยผมมาตลอดครับ",
 "Ludzie i rodzina", "Relacje", "sentence", 3, "n", "„tà-làwt” = przez cały czas, zawsze.", "",
 ("Dobry człowiek.", "khon dii khráp", "คนดีครับ")),
("Jesteśmy tylko znajomymi.", "rao pen khâe khon rúu-jàk khráp", "เราเป็นแค่คนรู้จักครับ",
 "Ludzie i rodzina", "Relacje", "sentence", 3, "n",
 "„khon rúu-jàk” = znajomy. „phûean” to już przyjaciel — Tajowie rozróżniają to wyraźniej niż Polacy.", "",
 ("Rozumiem.", "khâo-jai khráp", "เข้าใจครับ")),
("Straciliśmy kontakt.", "rao khàat kaan tìt tàw kan khráp", "เราขาดการติดต่อกันครับ",
 "Ludzie i rodzina", "Relacje", "sentence", 3, "f", "", "",
 ("Szkoda.", "sǐa daai khráp", "เสียดายครับ")),
("Tęsknię za rodziną.", "phǒm khít thǔeng khrâwp-khrua khráp", "ผมคิดถึงครอบครัวครับ",
 "Ludzie i rodzina", "Relacje", "sentence", 4, "n",
 "„khít thǔeng” = tęsknić. Dosłownie „myśleć aż do” — Tajowie używają tego też przy krótkiej rozłące.", "myśleć aż do",
 ("Kiedy wracasz?", "jà klàp mûea-rài khráp", "จะกลับเมื่อไหร่ครับ")),
("Zależy mi na tej znajomości.", "phǒm hěn khâa khwaam sǎm-phan níi khráp",
 "ผมเห็นค่าความสัมพันธ์นี้ครับ", "Ludzie i rodzina", "Relacje", "sentence", 2, "f",
 "„hěn khâa” = doceniać, widzieć wartość.", "",
 ("Ja też.", "phǒm kâw mǔean kan khráp", "ผมก็เหมือนกันครับ")),

# =====================================================================
# KONFLIKTY I GODZENIE SIE
# =====================================================================
("Chyba się pokłóciliśmy.", "rao khong thá-ló kan khráp", "เราคงทะเลาะกันครับ",
 "Ludzie i rodzina", "Konflikty", "sentence", 3, "n", "„thá-ló” = kłócić się.", "",
 ("Porozmawiajcie.", "khui kan ná khráp", "คุยกันนะครับ")),
("Nie chciałem cię urazić.", "phǒm mâi dâi tâng-jai hâi khun sǐa jai khráp",
 "ผมไม่ได้ตั้งใจให้คุณเสียใจครับ", "Ludzie i rodzina", "Konflikty", "sentence", 3, "n",
 "„mâi dâi tâng-jai” = nie zrobiłem tego celowo. Kluczowe przy przeprosinach.", "",
 ("Wiem.", "rúu khráp", "รู้ครับ")),
("Przepraszam za wczoraj.", "khǎw-thôot rûeang mûea waan khráp", "ขอโทษเรื่องเมื่อวานครับ",
 "Ludzie i rodzina", "Konflikty", "sentence", 4, "n", "", "",
 ("Już nieważne.", "mâi pen rai láew khráp", "ไม่เป็นไรแล้วครับ")),
("Nie miałem tego na myśli.", "phǒm mâi dâi màai khwaam yàang nán khráp",
 "ผมไม่ได้หมายความอย่างนั้นครับ", "Ludzie i rodzina", "Konflikty", "sentence", 3, "n", "", "",
 ("To o co ci chodziło?", "màai thǔeng à-rai khráp", "หมายถึงอะไรครับ")),
("Porozmawiajmy spokojnie.", "khui kan dii dii ná khráp", "คุยกันดีๆ นะครับ",
 "Ludzie i rodzina", "Konflikty", "sentence", 4, "n",
 "„dii dii” po czasowniku = w dobry, spokojny sposób. Bardzo częste przy łagodzeniu sporu.", "",
 ("Dobrze.", "dâai khráp", "ได้ครับ")),
("Nie chcę się kłócić.", "phǒm mâi yàak thá-ló khráp", "ผมไม่อยากทะเลาะครับ",
 "Ludzie i rodzina", "Konflikty", "sentence", 3, "n", "", "",
 ("Ja też nie.", "phǒm kâw mâi yàak khráp", "ผมก็ไม่อยากครับ")),
("Daj mi chwilę do namysłu.", "khǎw wee-laa khít nòi khráp", "ขอเวลาคิดหน่อยครับ",
 "Ludzie i rodzina", "Konflikty", "sentence", 4, "n", "", "",
 ("Nie spiesz się.", "mâi tâwng rîip khráp", "ไม่ต้องรีบครับ")),
("Byłem wtedy zdenerwowany.", "tawn nán phǒm aa-rom sǐa khráp", "ตอนนั้นผมอารมณ์เสียครับ",
 "Ludzie i rodzina", "Konflikty", "sentence", 3, "n", "„aa-rom sǐa” = w złym nastroju, poirytowany.", "",
 ("Rozumiem.", "khâo-jai khráp", "เข้าใจครับ")),
("Zapomnijmy o tym.", "luem rûeang nán pai thòe khráp", "ลืมเรื่องนั้นไปเถอะครับ",
 "Ludzie i rodzina", "Konflikty", "sentence", 3, "i", "", "",
 ("Zgoda.", "dâai khráp", "ได้ครับ")),
("Wybacz mi.", "yòk thôot hâi phǒm dûai khráp", "ยกโทษให้ผมด้วยครับ",
 "Ludzie i rodzina", "Konflikty", "sentence", 2, "f", "„yòk thôot” = wybaczyć. Mocniejsze niż „khǎw-thôot”.", "",
 ("Już dobrze.", "mâi pen rai láew khráp", "ไม่เป็นไรแล้วครับ")),
("To była moja wina.", "pen khwaam phìt khǎwng phǒm khráp", "เป็นความผิดของผมครับ",
 "Ludzie i rodzina", "Konflikty", "sentence", 3, "n", "", "",
 ("Nie tylko twoja.", "mâi châi khǎwng khun khon diao khráp", "ไม่ใช่ของคุณคนเดียวครับ")),
("Możemy zacząć od nowa?", "rôoem mài dâai mǎi khráp", "เริ่มใหม่ได้ไหมครับ",
 "Ludzie i rodzina", "Konflikty", "question", 3, "n", "", "",
 ("Możemy.", "dâai khráp", "ได้ครับ")),
("Potrzebuję trochę przestrzeni.", "phǒm khǎw yùu khon diao sàk phák khráp",
 "ผมขออยู่คนเดียวสักพักครับ", "Ludzie i rodzina", "Konflikty", "sentence", 3, "n",
 "„sàk phák” = przez chwilę, na jakiś czas.", "",
 ("Rozumiem.", "khâo-jai khráp", "เข้าใจครับ")),
("Nie bierz tego do siebie.", "yàa khít mâak ná khráp", "อย่าคิดมากนะครับ",
 "Ludzie i rodzina", "Konflikty", "sentence", 4, "n",
 "„khít mâak” = rozmyślać za dużo, zamartwiać się. Tajowie mówią to zamiast polskiego „nie przejmuj się”.", "nie myśl za dużo",
 ("Postaram się.", "jà phá-yaa-yaam khráp", "จะพยายามครับ")),
("Wyjaśnijmy to sobie.", "maa khîi-jaeng kan hâi chát khráp", "มาชี้แจงกันให้ชัดครับ",
 "Ludzie i rodzina", "Konflikty", "sentence", 3, "f", "„khîi-jaeng” = wyjaśniać, prostować.", "",
 ("Dobrze.", "dâai khráp", "ได้ครับ")),
]
