# -*- coding: utf-8 -*-
"""Sesja N — POGODA I PRZYRODA.

To była najuboższa kategoria bazy: 48 haseł leksykalnych na 61 rekordów.
Dysproporcja nie wynikała z tego, że pogoda jest w rozmowie rzadka — jest
odwrotnie, w Tajlandii to temat otwierający połowę rozmów z nieznajomym.
Wynikała z tego, że wcześniejsze etapy budowały bazę od strony sytuacji
podróżnych, a pogoda nie jest sytuacją, tylko tłem wszystkich pozostałych.

Format krotki:
  (poziom, polski, fonetyka, pismo, podkategoria, częstość, typ, uwaga, dosłownie)
Typy: n rzeczownik, v czasownik, adj przymiotnik, adv przysłówek, w słowo.
"""

CAT = "Pogoda i przyroda"

NATURE = [

# ============================================================ POGODA
("A1", "burza", "phaa-yú", "พายุ", "Pogoda", 4, "n",
 "Słowo obejmuje i burzę z piorunami, i tajfun. O sile mówi się dopiero przymiotnikiem.", ""),
("A1", "grzmot", "fáa ráwng", "ฟ้าร้อง", "Pogoda", 3, "n",
 "Dosłownie „niebo płacze / krzyczy”. Ten sam wzorzec co fáa phàa.", "niebo krzyczeć"),
("A2", "błyskawica", "fáa phàa", "ฟ้าผ่า", "Pogoda", 3, "n",
 "Znaczy raczej „piorun uderzył” niż samo światło błyskawicy.", "niebo rozłupać"),
("A1", "chmura", "mêek", "เมฆ", "Pogoda", 3, "n",
 "Jedna sylaba z tonem opadającym — Polacy skracają ją do zwykłego „mek”.", ""),
("A2", "mgła", "màwk", "หมอก", "Pogoda", 3, "n",
 "Na nizinach rzadka, na północy o poranku codzienna.", ""),
("A2", "rosa", "nám kháang", "น้ำค้าง", "Pogoda", 2, "n",
 "Dosłownie „woda, która została”.", "woda zostawać"),
("A2", "tęcza", "rúng", "รุ้ง", "Pogoda", 2, "n",
 "Pełna forma to „rúng kin náam”, ale w mowie wystarcza samo rúng.", ""),
("A1", "słońce (żar, blask)", "dàet", "แดด", "Pogoda", 5, "n",
 "Uwaga na różnicę: phrá aa-thít to ciało niebieskie, dàet to żar, który z niego leci. W rozmowie o pogodzie zawsze dàet.", ""),
("A1", "jest słonecznie", "dàet àwk", "แดดออก", "Pogoda", 4, "v",
 "Dosłownie „żar wyszedł”. Tajski opisuje pogodę czasownikiem, nie przymiotnikiem.", "żar wychodzić"),
("A2", "zachmurzone niebo", "fáa khrúem", "ฟ้าครึ้ม", "Pogoda", 3, "adj",
 "Zapowiedź deszczu — Taj powie to, zanim spadnie pierwsza kropla.", "niebo pochmurny"),
("A1", "pada deszcz", "fǒn tòk", "ฝนตก", "Pogoda", 5, "v",
 "Najczęstsze zdanie o pogodzie w tajskim. Dosłownie „deszcz spada”.", "deszcz spadać"),
("A2", "przestało padać", "fǒn yùt", "ฝนหยุด", "Pogoda", 3, "v",
 "yùt to zatrzymać się — ten sam czasownik co przy autobusie.", "deszcz zatrzymać się"),
("A2", "wieje wiatr", "lom phát", "ลมพัด", "Pogoda", 3, "v",
 "phát to dmuchać; ten sam wyraz stoi w nazwie wentylatora.", "wiatr dmuchać"),
("A2", "wilgotny", "chúen", "ชื้น", "Pogoda", 4, "adj",
 "Kluczowe słowo w tym klimacie: 35 stopni suchych i 35 wilgotnych to dwie różne rzeczy.", ""),
("A1", "suchy", "hâeng", "แห้ง", "Pogoda", 4, "adj",
 "Także o praniu i o gardle.", ""),
("A2", "wilgotność", "khwaam chúen", "ความชื้น", "Pogoda", 3, "n",
 "khwaam robi rzeczownik z przymiotnika — ten sam wzorzec co khwaam sùk (szczęście).", "stan wilgotny"),
("A2", "temperatura", "ùn-hà-phuum", "อุณหภูมิ", "Pogoda", 3, "n",
 "Wyraz z sanskrytu, cztery sylaby, żadna nieakcentowana poza ostatnią.", ""),
("A2", "stopień (temperatury)", "ong-sǎa", "องศา", "Pogoda", 3, "n",
 "Także stopień kąta. Liczy się bez klasyfikatora: sǎam-sìp ong-sǎa.", ""),
("A2", "prognoza pogody", "phá-yaa-kawn aa-kàat", "พยากรณ์อากาศ", "Pogoda", 3, "n",
 "Formuła z telewizji i z aplikacji — w rozmowie częściej pyta się wprost „fǒn jà tòk mǎi”.", "przewidywać powietrze"),
("A2", "pora deszczowa", "nâa fǒn", "หน้าฝน", "Pogoda", 4, "n",
 "nâa to dosłownie „twarz”, ale w nazwach pór roku znaczy „sezon”. Maj–październik.", "sezon deszcz"),
("A2", "pora chłodna", "nâa nǎao", "หน้าหนาว", "Pogoda", 4, "n",
 "Listopad–luty. „Chłodna” to w Bangkoku 25 stopni — nazwa jest względna.", "sezon zimno"),
("A2", "pora gorąca", "nâa ráwn", "หน้าร้อน", "Pogoda", 4, "n",
 "Marzec–maj, szczyt w kwietniu razem z Songkranem.", "sezon gorąco"),
("B1", "pora sucha", "nâa láeng", "หน้าแล้ง", "Pogoda", 3, "n",
 "Termin rolniczy — mówi się nim o braku wody, nie o wygodzie turysty.", "sezon susza"),
("B1", "powódź", "nám thûam", "น้ำท่วม", "Pogoda", 3, "n",
 "W porze deszczowej temat praktyczny, nie katastroficzny — dotyczy przejezdności ulic.", "woda zalewać"),
("B1", "susza", "phai láeng", "ภัยแล้ง", "Pogoda", 2, "n",
 "phai to klęska, zagrożenie — ten sam wyraz w „phai thammáchâat”.", "klęska susza"),
("B1", "trzęsienie ziemi", "phàen din wǎi", "แผ่นดินไหว", "Pogoda", 2, "n",
 "Dosłownie „płyta ziemi drży”.", "płyta ziemia drżeć"),
("A2", "cień", "ngao", "เงา", "Pogoda", 3, "n",
 "Nagłosowe ng- jest dla Polaka najtrudniejszym dźwiękiem tajskim: to końcówka „bank” postawiona na początku.", ""),
("A2", "wschód słońca", "phrá aa-thít khûen", "พระอาทิตย์ขึ้น", "Pogoda", 3, "n",
 "khûen to wznosić się — ten sam czasownik co przy wsiadaniu do autobusu.", "słońce wznosić się"),
("A2", "zachód słońca", "phrá aa-thít tòk", "พระอาทิตย์ตก", "Pogoda", 3, "n",
 "tòk to spadać — dokładnie ten sam wyraz co w „fǒn tòk”.", "słońce spadać"),
("B1", "świt", "rûng cháo", "รุ่งเช้า", "Pogoda", 2, "n",
 "Bardziej literackie niż „cháo mûet”; w mowie usłyszysz raczej przy opowiadaniu.", "brzask ranek"),
("B1", "zmierzch", "phlóp khâm", "พลบค่ำ", "Pogoda", 2, "n",
 "Krótki — na tej szerokości geograficznej zmrok zapada w kwadrans.", ""),

# ============================================================ NIEBO I ZIEMIA
("A2", "księżyc", "phrá jan", "พระจันทร์", "Niebo i ziemia", 3, "n",
 "phrá to przedrostek czci, ten sam co przy słońcu i przy mnichu.", ""),
("A2", "gwiazda", "daao", "ดาว", "Niebo i ziemia", 3, "n",
 "Także „gwiazda filmowa” — dokładnie ta sama przenośnia co po polsku.", ""),
("B1", "planeta", "daao khráw", "ดาวเคราะห์", "Niebo i ziemia", 2, "n",
 "Dosłownie „gwiazda losu” — nazwa z astrologii, która została w astronomii.", "gwiazda los"),
("B1", "wszechświat", "jàk-krà-waan", "จักรวาล", "Niebo i ziemia", 2, "n",
 "Trzy sylaby, akcent na ostatniej.", ""),
("A2", "Ziemia (planeta)", "lôok", "โลก", "Niebo i ziemia", 4, "n",
 "Także „świat” w sensie ogółu ludzi. Ton opadający.", ""),
("A2", "gleba, ziemia (grunt)", "din", "ดิน", "Niebo i ziemia", 3, "n",
 "Nie mylić z lôok. din to materiał pod nogami.", ""),
("A2", "piasek", "saai", "ทราย", "Niebo i ziemia", 3, "n",
 "Pisownia zaczyna się od znaku czytanego jak s — jeden z wyjątków ortograficznych.", ""),
("A2", "kamień", "hǐn", "หิน", "Niebo i ziemia", 3, "n",
 "Także „skała” w nazwach miejsc, np. Hua Hin — „głowa kamienia”.", ""),
("B1", "jaskinia", "thâm", "ถ้ำ", "Niebo i ziemia", 2, "n",
 "Częste w nazwach atrakcji na południu i północy.", ""),

# ============================================================ WODA
("A2", "wodospad", "nám tòk", "น้ำตก", "Woda", 4, "n",
 "Dosłownie „woda spada” — i jednocześnie nazwa dania mięsnego, bo sok skapuje z rusztu.", "woda spadać"),
("A1", "rzeka", "mâe-nám", "แม่น้ำ", "Woda", 4, "n",
 "Dosłownie „matka wód”. Nazwa Menam to nieporozumienie kartografów: to nie nazwa własna, tylko słowo „rzeka”.", "matka woda"),
("B1", "strumień", "lam-thaan", "ลำธาร", "Woda", 2, "n",
 "Mniejszy niż mâe-nám, w górach.", ""),
("A2", "jezioro", "thá-lee sàap", "ทะเลสาบ", "Woda", 3, "n",
 "Dosłownie „morze słodkie” — tajski buduje jezioro z morza, nie odwrotnie.", "morze słodkowodny"),
("B1", "staw", "sà", "สระ", "Woda", 2, "n",
 "To samo słowo co basen (sà wâai-náam). Jedna sylaba, ton niski.", ""),
("A1", "wyspa", "kàw", "เกาะ", "Woda", 5, "n",
 "Stoi przed nazwą: Kàw Sà-mǔi, Kàw Chaang. Krótka samogłoska i ton niski.", ""),
("A1", "plaża", "chaai hàat", "ชายหาด", "Woda", 4, "n",
 "W mowie często skracane do samego hàat.", "brzeg plaża"),
("A2", "fala", "khlûen", "คลื่น", "Woda", 3, "n",
 "Zbitka khl- na początku — Polacy gubią z niej l.", ""),
("B1", "przypływ", "nám khûen", "น้ำขึ้น", "Woda", 2, "n",
 "Praktyczne przy wynajmie łodzi i przejściu na wyspę.", "woda wznosić się"),
("B1", "odpływ", "nám long", "น้ำลง", "Woda", 2, "n",
 "long to schodzić w dół — ten sam czasownik co przy wysiadaniu z autobusu.", "woda schodzić"),
("A2", "brzeg", "fàng", "ฝั่ง", "Woda", 3, "n",
 "Także „strona” przy przeprawie: fàng níi, fàng nán.", ""),

# ============================================================ UKSZTAŁTOWANIE
("B1", "dolina", "hùp khǎo", "หุบเขา", "Ukształtowanie terenu", 2, "n",
 "khǎo to góra — ten sam wyraz co w phuu khǎo.", "kotlina góra"),
("B1", "wzgórze", "noen khǎo", "เนินเขา", "Ukształtowanie terenu", 2, "n",
 "Mniejsze niż phuu khǎo, większe niż nic.", "pagórek góra"),
("B1", "szczyt góry", "yâwt khǎo", "ยอดเขา", "Ukształtowanie terenu", 2, "n",
 "yâwt to także „czubek” i potocznie „świetny”.", "czubek góra"),
("A2", "pole (ryżowe)", "naa", "นา", "Ukształtowanie terenu", 3, "n",
 "Jedna sylaba, ton średni. Stąd chaao naa — rolnik.", ""),
("A1", "ogród, park", "sǔan", "สวน", "Ukształtowanie terenu", 4, "n",
 "Także sad i plantacja: sǔan klûai — plantacja bananów.", ""),
("B1", "gęsty las", "pàa thúep", "ป่าทึบ", "Ukształtowanie terenu", 2, "n",
 "thúep znaczy gęsty, nieprzenikniony — także o ruchu ulicznym.", "las gęsty"),

# ============================================================ ROŚLINY
("A2", "bambus", "mái phài", "ไม้ไผ่", "Rośliny", 3, "n",
 "Materiał na wszystko: rusztowania, meble, naczynia, jedzenie.", "drewno bambus"),
("B1", "palma", "tôn paam", "ต้นปาล์ม", "Rośliny", 2, "n",
 "tôn to klasyfikator i przedrostek roślin pnących się w górę.", "pień palma"),
("B1", "korzeń", "râak", "ราก", "Rośliny", 2, "n",
 "Także przenośnie: râak thǎan — korzenie, podstawa.", ""),
("B1", "gałąź", "kìng mái", "กิ่งไม้", "Rośliny", 2, "n",
 "", "gałąź drewno"),
("B1", "nasiono, ziarno", "mét", "เมล็ด", "Rośliny", 2, "n",
 "Także klasyfikator drobnych okrągłych rzeczy — tabletek, chili, ziaren.", ""),
("A2", "trawa", "yâa", "หญ้า", "Rośliny", 3, "n",
 "Uwaga na parę minimalną: yâa (trawa) kontra yaa (lek) kontra yàa (nie rób).", ""),
("A2", "roślina", "phûet", "พืช", "Rośliny", 2, "n",
 "Termin ogólny, częstszy w piśmie niż w mowie.", ""),
("A2", "sadzić, uprawiać", "plùuk", "ปลูก", "Rośliny", 3, "v",
 "Także „budować dom” — plùuk bâan. Zbitka pl- bez przydechu.", ""),
("B1", "kwitnąć", "baan", "บาน", "Rośliny", 2, "v",
 "Także o drzwiach: baan prà-tuu to skrzydło drzwi.", ""),

# ============================================================ ZWIERZĘTA
("A1", "zwierzę", "sàt", "สัตว์", "Zwierzęta", 4, "n",
 "Końcowe -t jest niezwolnione: zatrzymujesz język, nie wypuszczasz powietrza.", ""),
("A2", "dzikie zwierzę", "sàt pàa", "สัตว์ป่า", "Zwierzęta", 3, "n",
 "", "zwierzę las"),
("A1", "słoń", "cháang", "ช้าง", "Zwierzęta", 4, "n",
 "Symbol kraju. Uwaga: cháang (słoń) kontra châang (rzemieślnik) różnią się samym tonem.", ""),
("A1", "małpa", "ling", "ลิง", "Zwierzęta", 3, "n",
 "Przy świątyniach traktowana jak zagrożenie dla toreb, nie jak atrakcja.", ""),
("A2", "tygrys", "sǔea", "เสือ", "Zwierzęta", 3, "n",
 "Homofon z „sûea” (koszula) różniący się tonem — klasyczna pułapka.", ""),
("B1", "niedźwiedź", "mǐi", "หมี", "Zwierzęta", 2, "n",
 "Ton rosnący, jak w mǎa (pies).", ""),
("B1", "jeleń", "kwaang", "กวาง", "Zwierzęta", 2, "n",
 "Zbitka kw- czytana jak polskie „kł”.", ""),
("A2", "bawół", "khwaai", "ควาย", "Zwierzęta", 3, "n",
 "Uwaga: potocznie także obelga o kimś tępym. Nie używać żartem.", ""),
("A2", "koń", "máa", "ม้า", "Zwierzęta", 3, "n",
 "Para minimalna z mǎa (pies) i mâa (przyjść, forma potoczna) — trzy tony, trzy znaczenia.", ""),
("B1", "koza", "pháe", "แพะ", "Zwierzęta", 2, "n",
 "Także „kozioł ofiarny” — pháe ráp bàap.", ""),
("B1", "owca", "kàe", "แกะ", "Zwierzęta", 2, "n",
 "To samo brzmienie co „obierać, łuskać”.", ""),
("A2", "kaczka", "pèt", "เป็ด", "Zwierzęta", 3, "n",
 "Uwaga na parę: pèt (kaczka) kontra phèt (ostry). Różnica to sam przydech.", ""),
("A2", "mysz, szczur", "nǔu", "หนู", "Zwierzęta", 3, "n",
 "To samo słowo bywa zaimkiem, którym o sobie mówi dziecko albo młoda kobieta.", ""),
("A2", "wąż", "nguu", "งู", "Zwierzęta", 3, "n",
 "Nagłosowe ng- plus samogłoska długa — najtrudniejsze jednosylabowe słowo tego zestawu.", ""),
("B1", "jaszczurka domowa", "jîng-jòk", "จิ้งจก", "Zwierzęta", 2, "n",
 "Mieszka na ścianie w każdym pokoju i zjada komary. Nie jest problemem.", ""),
("B1", "żaba", "kòp", "กบ", "Zwierzęta", 2, "n",
 "Także danie w kuchni Isanu.", ""),
("B1", "żółw", "tào", "เต่า", "Zwierzęta", 2, "n",
 "Także przenośnie o kimś powolnym.", ""),
("B1", "krokodyl", "jarà-khêe", "จระเข้", "Zwierzęta", 2, "n",
 "", ""),
("A2", "ptak", "nók", "นก", "Zwierzęta", 3, "n",
 "Stoi też w nazwie linii lotniczej — Nok Air.", ""),
("A2", "owad", "má-laeng", "แมลง", "Zwierzęta", 3, "n",
 "Pierwsza sylaba nieakcentowana, w mowie prawie znika: m'laeng.", ""),
("A2", "mrówka", "mót", "มด", "Zwierzęta", 3, "n",
 "Praktyczne słowo: mrówki znajdą każde otwarte jedzenie w kwadrans.", ""),
("B1", "pszczoła", "phûeng", "ผึ้ง", "Zwierzęta", 2, "n",
 "Stąd nám phûeng — miód, dosłownie „woda pszczoły”.", ""),
("B1", "motyl", "phǐi-sûea", "ผีเสื้อ", "Zwierzęta", 2, "n",
 "Dosłownie „duch koszuli” — nazwa niewyjaśniona, ale utrwalona.", "duch koszula"),
("B1", "pająk", "maeng mum", "แมงมุม", "Zwierzęta", 2, "n",
 "", ""),
("A2", "mucha", "má-laeng wan", "แมลงวัน", "Zwierzęta", 3, "n",
 "Dosłownie „owad dnia”.", "owad dzień"),
("B1", "karaluch", "má-laeng sàap", "แมลงสาบ", "Zwierzęta", 2, "n",
 "Słowo, którego lepiej nie potrzebować, ale warto rozumieć w hotelu.", ""),
("A2", "krab", "puu", "ปู", "Zwierzęta", 3, "n",
 "Uwaga: puu (krab) kontra pùu (dziadek) różnią się tonem.", ""),
("A2", "małż, muszla", "hǎwi", "หอย", "Zwierzęta", 3, "n",
 "Zbiorczo o wszystkim, co ma skorupę — od omułków po ślimaki.", ""),
("B1", "rekin", "plaa chà-lǎam", "ปลาฉลาม", "Zwierzęta", 2, "n",
 "plaa to przedrostek wszystkich ryb.", "ryba rekin"),
("B1", "delfin", "plaa loo-maa", "ปลาโลมา", "Zwierzęta", 2, "n",
 "", "ryba delfin"),

# ============================================================ ŚRODOWISKO
("A2", "natura, przyroda", "thammáchâat", "ธรรมชาติ", "Środowisko", 3, "n",
 "Także „naturalny” w opisie produktu.", ""),
("B1", "środowisko", "sìng-wâet-láwm", "สิ่งแวดล้อม", "Środowisko", 3, "n",
 "Dosłownie „rzeczy, które otaczają”.", "rzecz otaczać"),
("B1", "zanieczyszczenie", "mon-lá-phít", "มลพิษ", "Środowisko", 2, "n",
 "Termin urzędowy; w rozmowie częściej mówi się o fùn.", ""),
("A2", "pył, smog", "fùn", "ฝุ่น", "Środowisko", 3, "n",
 "Zimą na północy temat codzienny — PM 2.5 nazywa się po prostu fùn.", ""),
("A1", "śmieci", "khà-yà", "ขยะ", "Środowisko", 4, "n",
 "Obie sylaby z tonem niskim, obie krótkie.", ""),
("B1", "recykling", "rii-sai-khoen", "รีไซเคิล", "Środowisko", 2, "n",
 "Zapożyczenie z angielskiego, przepisane na sylaby tajskie.", ""),
("B1", "energia", "phá-lang-ngaan", "พลังงาน", "Środowisko", 2, "n",
 "Środkowe -ng- i końcowe -ng to ten sam dźwięk w dwóch pozycjach.", ""),
("B1", "klimat", "phuu-mí-aa-kàat", "ภูมิอากาศ", "Środowisko", 2, "n",
 "Nie mylić z aa-kàat (powietrze, pogoda) — phuu-mí- dodaje wymiar długotrwałości.", "teren powietrze"),
("B1", "globalne ocieplenie", "lôok ráwn", "โลกร้อน", "Środowisko", 2, "n",
 "Dosłownie „świat gorący” — krótko i bez terminologii.", "świat gorący"),
("B1", "park narodowy", "ùt-thá-yaan hàeng châat", "อุทยานแห่งชาติ", "Środowisko", 2, "n",
 "Napis na każdej bramce wstępu; warto rozpoznawać ze słuchu.", "park należący naród"),
("B1", "ochrona przyrody", "à-nú-rák thammáchâat", "อนุรักษ์ธรรมชาติ", "Środowisko", 2, "n",
 "à-nú-rák to chronić, zachowywać.", "chronić natura"),
]
