# -*- coding: utf-8 -*-
"""Leksyka etapu 6 — praca, zycie codzienne, wyrazenia potoczne, rejestry.

Trzy bloki:
  1. praca i zycie codzienne — sprawy, ktore zalatwia sie co tydzien,
  2. wyrazenia potoczne BEZPIECZNE — kazde z notatka, gdzie ich nie uzywac,
  3. pary i trojki rejestrowe — ten sam komunikat inaczej ulozony.

Krotka: (poziom, polski, fonetyka, tajski, kategoria, podkategoria, typ,
         freq, rejestr, notatka, znaczenie doslowne, przyklad)
"""

LIFE = [

# =====================================================================
# PRACA — DZIEN POWSZEDNI
# =====================================================================
("A2", "idę do pracy", "pai tham ngaan", "ไปทำงาน", "Praca i nauka", "Codzienność", "phrase", 4, "n",
 "„tham ngaan” to pracować; „ngaan” samo znaczy też przyjęcie i uroczystość.", "iść robić praca",
 ("Wychodzę do pracy o ósmej.", "phǒm pai tham ngaan pàet mohng cháo khráp", "ผมไปทำงานแปดโมงเช้าครับ")),
("A2", "mam dziś wolne", "wan níi phǒm yùt", "วันนี้ผมหยุด", "Praca i nauka", "Codzienność", "phrase", 4, "n",
 "„yùt” znaczy zatrzymać się, ale też „mieć dzień wolny”.", "dzień ten ja zatrzymać",
 ("Dziś mam wolne.", "wan níi phǒm yùt khráp", "วันนี้ผมหยุดครับ")),
("A2", "biorę urlop", "lâa phák ráwn", "ลาพักร้อน", "Praca i nauka", "Urlop", "phrase", 3, "f",
 "„lâa” to formalne wnioskowanie o nieobecność: „lâa pùai” (zwolnienie), „lâa kìt” (sprawy osobiste).", "prosić odpoczynek gorąco",
 ("Biorę urlop w przyszłym tygodniu.", "aa-thít nâa phǒm lâa phák ráwn khráp", "อาทิตย์หน้าผมลาพักร้อนครับ")),
("A2", "jestem na zwolnieniu", "lâa pùai", "ลาป่วย", "Praca i nauka", "Urlop", "phrase", 3, "f",
 "Standardowa formuła w wiadomości do przełożonego.", "prosić chory",
 ("Dziś jestem na zwolnieniu.", "wan níi phǒm lâa pùai khráp", "วันนี้ผมลาป่วยครับ")),
("A2", "spóźnię się", "phǒm jà maa sǎai", "ผมจะมาสาย", "Praca i nauka", "Punktualność", "phrase", 4, "n",
 "Uprzedzenie o spóźnieniu jest w tajskim biurze oczekiwane — milczenie razi bardziej niż spóźnienie.", "ja będę przyjść późno",
 ("Spóźnię się jakieś dziesięć minut.", "phǒm jà maa sǎai prà-maan sìp naa-thii khráp", "ผมจะมาสายประมาณสิบนาทีครับ")),
("B1", "mam dużo pracy", "ngaan yóe", "งานเยอะ", "Praca i nauka", "Obciążenie", "phrase", 4, "n",
 "„yóe” to potoczne „dużo”, częstsze w mowie niż „mâak” przy rzeczownikach.", "praca dużo",
 ("Mam teraz bardzo dużo pracy.", "tawn níi ngaan yóe mâak khráp", "ตอนนี้งานเยอะมากครับ")),
("B1", "termin jest w piątek", "kam-nòt sòng wan sùk", "กำหนดส่งวันศุกร์", "Praca i nauka", "Terminy", "phrase", 3, "f",
 "„kam-nòt sòng” to termin oddania. W mowie skraca się do „dedláai”.", "termin wysłać dzień piątek",
 ("Termin oddania jest w piątek.", "kam-nòt sòng khue wan sùk khráp", "กำหนดส่งคือวันศุกร์ครับ")),
("B1", "zdążę na czas", "sèt than wee-laa", "เสร็จทันเวลา", "Praca i nauka", "Terminy", "phrase", 3, "n",
 "„than wee-laa” = na czas. Bez „than” zdanie mówi tylko, że skończysz.", "skończyć zdążyć czas",
 ("Zdążę to skończyć na czas.", "phǒm sèt than wee-laa nâe nawn khráp", "ผมเสร็จทันเวลาแน่นอนครับ")),
("B1", "potrzebuję więcej czasu", "khǎw wee-laa phôoem", "ขอเวลาเพิ่ม", "Praca i nauka", "Terminy", "phrase", 3, "f",
 "Prośba, nie zawiadomienie. Podaj powód i nową datę, inaczej zabrzmi jak wymówka.", "proszę czas dodać",
 ("Poproszę o dwa dni więcej.", "khǎw wee-laa phôoem ìik sǎwng wan dâai mǎi khráp", "ขอเวลาเพิ่มอีกสองวันได้ไหมครับ")),
("B1", "zajmę się tym", "dǐao phǒm duu hâi", "เดี๋ยวผมดูให้", "Praca i nauka", "Ustalenia", "phrase", 4, "n",
 "„duu hâi” = sprawdzę i zajmę się. Bardzo częsta odpowiedź w biurze i w obsłudze klienta.", "zaraz ja patrzeć dać",
 ("Zajmę się tym, proszę się nie martwić.", "dǐao phǒm duu hâi khráp mâi tâwng kang-won", "เดี๋ยวผมดูให้ครับ ไม่ต้องกังวล")),
("B1", "przekażę to dalej", "jà sòng tàw hâi", "จะส่งต่อให้", "Praca i nauka", "Ustalenia", "phrase", 3, "f",
 "„sòng tàw” to przekazać sprawę innej osobie albo działowi.", "będę wysłać dalej dać",
 ("Przekażę to odpowiedniemu działowi.", "phǒm jà sòng tàw hâi phà-nàek thîi kìao khâwng khráp", "ผมจะส่งต่อให้แผนกที่เกี่ยวข้องครับ")),

# =====================================================================
# ZYCIE CODZIENNE — SPRAWY DO ZALATWIENIA
# =====================================================================
("A2", "zapłacić rachunek", "jàai bin", "จ่ายบิล", "Dom i codzienność", "Rachunki", "phrase", 3, "n",
 "Rachunki za prąd i wodę płaci się w Tajlandii także w sklepach całodobowych.", "płacić rachunek",
 ("Muszę zapłacić rachunek za prąd.", "phǒm tâwng jàai bin khâa fai khráp", "ผมต้องจ่ายบิลค่าไฟครับ")),
("A2", "doładować telefon", "toem ngoen", "เติมเงิน", "Dom i codzienność", "Technika", "phrase", 3, "n",
 "„toem” to dolać, uzupełnić — także „toem náam man” (zatankować).", "dolać pieniądze",
 ("Chcę doładować telefon za sto batów.", "khǎw toem ngoen nùeng ráwi bàat khráp", "ขอเติมเงินหนึ่งร้อยบาทครับ")),
("A2", "zatankować do pełna", "toem tem thǎng", "เติมเต็มถัง", "Transport", "Paliwo", "phrase", 3, "n",
 "Na stacji obsługują cię pracownicy — wystarczy powiedzieć to zdanie przez okno.", "dolać pełny bak",
 ("Proszę do pełna.", "toem tem thǎng khráp", "เติมเต็มถังครับ")),
("A2", "umówić się na wizytę", "nát wee-laa", "นัดเวลา", "Zdrowie", "Formalności", "phrase", 3, "n",
 "„nát” to umówione spotkanie; „mii nát” = mam umówione.", "umówić czas",
 ("Chcę umówić się na wizytę.", "phǒm yàak nát wee-laa khráp", "ผมอยากนัดเวลาครับ")),
("A2", "odwołać spotkanie", "yók lôek nát", "ยกเลิกนัด", "Praca i nauka", "Terminy", "phrase", 3, "n",
 "Odwołanie z wyprzedzeniem i z przeprosinami jest w Tajlandii ważniejsze niż powód.", "odwołać spotkanie",
 ("Muszę odwołać jutrzejsze spotkanie.", "phǒm tâwng yók lôek nát phrûng-níi khráp khǎw-thôot dûai", "ผมต้องยกเลิกนัดพรุ่งนี้ครับ ขอโทษด้วย")),
("B1", "przedłużyć wizę", "tàw wii-sâa", "ต่อวีซ่า", "Praca i nauka", "Urząd", "phrase", 3, "f",
 "„tàw” to przedłużyć. Sprawę załatwia się w biurze imigracyjnym („trùat khon khâo mueang”).", "przedłużyć wiza",
 ("Chcę przedłużyć wizę.", "phǒm yàak tàw wii-sâa khráp", "ผมอยากต่อวีซ่าครับ")),
("B1", "jakie dokumenty są potrzebne?", "tâwng chái èek-kà-sǎan à-rai bâang", "ต้องใช้เอกสารอะไรบ้าง", "Praca i nauka", "Urząd", "question", 4, "f",
 "„bâang” na końcu pytania sygnalizuje, że spodziewasz się kilku odpowiedzi.", "trzeba używać dokument co niektóre",
 ("Jakie dokumenty są potrzebne?", "tâwng chái èek-kà-sǎan à-rai bâang khráp", "ต้องใช้เอกสารอะไรบ้างครับ")),
("B1", "gdzie mam podpisać?", "sen trong nǎi", "เซ็นตรงไหน", "Praca i nauka", "Urząd", "question", 3, "n",
 "„sen” to zapożyczone „sign”. Formalnie: „long laai mue chûe”.", "podpisać miejsce które",
 ("Gdzie mam się podpisać?", "sen trong nǎi khráp", "เซ็นตรงไหนครับ")),
("B1", "czy trzeba zapłacić opłatę?", "mii khâa tham-niam mǎi", "มีค่าธรรมเนียมไหม", "Praca i nauka", "Urząd", "question", 3, "f",
 "„khâa tham-niam” to opłata urzędowa. „khâa …” tworzy nazwy wszystkich opłat.", "mieć opłata urzędowa czy",
 ("Czy jest jakaś opłata?", "mii khâa tham-niam mǎi khráp", "มีค่าธรรมเนียมไหมครับ")),
("B1", "wynajmuję mieszkanie", "phǒm châo hâwng yùu", "ผมเช่าห้องอยู่", "Dom i codzienność", "Mieszkanie", "phrase", 3, "n",
 "W Tajlandii mieszkanie w bloku to zwykle „hâwng” (pokój), nie „bâan”.", "ja wynajmować pokój przebywać",
 ("Wynajmuję tu mieszkanie od roku.", "phǒm châo hâwng yùu thîi nîi maa nùeng pii láew khráp", "ผมเช่าห้องอยู่ที่นี่มาหนึ่งปีแล้วครับ")),
("B1", "kaucja", "ngoen mát jam", "เงินมัดจำ", "Dom i codzienność", "Mieszkanie", "noun", 3, "f",
 "Zwykle dwa czynsze. Warunki zwrotu warto ustalić na piśmie przed wprowadzeniem.", "pieniądze związać zastaw",
 ("Kiedy dostanę zwrot kaucji?", "dâai ngoen mát jam khuen mûea rài khráp", "ได้เงินมัดจำคืนเมื่อไหร่ครับ")),
("B1", "coś się zepsuło w mieszkaniu", "nai hâwng mii à-rai sǐa", "ในห้องมีอะไรเสีย", "Dom i codzienność", "Usterki", "phrase", 3, "n",
 "Zgłoszenie do właściciela albo do recepcji budynku.", "w pokój mieć coś zepsuty",
 ("W pokoju coś się zepsuło.", "nai hâwng mii à-rai sǐa khráp chûai duu hâi nòi", "ในห้องมีอะไรเสียครับ ช่วยดูให้หน่อย")),

# =====================================================================
# WYRAZENIA POTOCZNE — BEZPIECZNE
# =====================================================================
("B1", "spoko, w porządku", "oo-khee loei", "โอเคเลย", "Small talk", "Potoczne", "phrase", 4, "p",
 "POTOCZNE, ale całkowicie bezpieczne — słychać je też w biurze między współpracownikami.", "okej wcale",
 ("Spoko, może być.", "oo-khee loei khráp", "โอเคเลยครับ")),
("B1", "no jasne", "nâe nawn yùu láew", "แน่นอนอยู่แล้ว", "Small talk", "Potoczne", "phrase", 3, "p",
 "POTOCZNE. Potwierdzenie oczywistości. W rozmowie z urzędnikiem lepiej samo „nâe nawn khráp”.", "pewnie być już",
 ("No jasne, że pomogę.", "nâe nawn yùu láew chûai dâai", "แน่นอนอยู่แล้ว ช่วยได้")),
("B1", "super, świetnie", "yîam loei", "เยี่ยมเลย", "Small talk", "Potoczne", "phrase", 3, "p",
 "POTOCZNE, bezpieczne w każdej sytuacji nieurzędowej. Wyraża szczery entuzjazm.", "znakomicie wcale",
 ("Świetnie, dziękuję!", "yîam loei khráp khàwp khun mâak", "เยี่ยมเลยครับ ขอบคุณมาก")),
("B1", "trudna sprawa", "rûeang yài", "เรื่องใหญ่", "Small talk", "Potoczne", "phrase", 3, "p",
 "POTOCZNE. Dosłownie „duża sprawa”. „mâi châi rûeang yài” = nic wielkiego, drobiazg.", "sprawa duża",
 ("To nie jest wielka sprawa.", "mâi châi rûeang yài khráp", "ไม่ใช่เรื่องใหญ่ครับ")),
("B1", "jakoś to będzie", "dǐao kâw dii eeng", "เดี๋ยวก็ดีเอง", "Small talk", "Potoczne", "phrase", 3, "p",
 "POTOCZNE. Tajski odpowiednik pocieszenia „nie martw się, ułoży się”. Wobec kogoś w żałobie zabrzmi lekceważąco.", "zaraz też dobrze samo",
 ("Nie martw się, jakoś to będzie.", "mâi tâwng khrîat dǐao kâw dii eeng", "ไม่ต้องเครียด เดี๋ยวก็ดีเอง")),
("B1", "jestem wykończony", "mòt raeng láew", "หมดแรงแล้ว", "Small talk", "Potoczne", "phrase", 3, "p",
 "POTOCZNE. Dosłownie „skończyła mi się siła”. Bezpieczne wobec znajomych i współpracowników.", "skończyć siła już",
 ("Jestem dziś kompletnie wykończony.", "wan níi mòt raeng láew khráp", "วันนี้หมดแรงแล้วครับ")),
("B1", "nie ma sensu", "mâi mii prà-yòot", "ไม่มีประโยชน์", "Small talk", "Potoczne", "phrase", 3, "n",
 "Ocena sprawy, nie osoby. Powiedziane o czyimś pomyśle brzmi ostro — dodaj „nít nàwi”.", "nie mieć pożytek",
 ("To chyba nie ma sensu.", "khít wâa mâi mii prà-yòot khráp", "คิดว่าไม่มีประโยชน์ครับ")),
("B1", "dawno się nie widzieliśmy", "mâi dâai jooe kan naan", "ไม่ได้เจอกันนาน", "Small talk", "Potoczne", "phrase", 4, "p",
 "POTOCZNE i bardzo ciepłe. Standardowe otwarcie rozmowy po dłuższej przerwie.", "nie móc spotkać razem długo",
 ("Kopę lat! Jak się masz?", "mâi dâai jooe kan naan loei sà-baai dii mǎi", "ไม่ได้เจอกันนานเลย สบายดีไหม")),
("B1", "wpadnij kiedyś", "wâang wâang kâw maa ná", "ว่างๆ ก็มานะ", "Small talk", "Potoczne", "phrase", 3, "p",
 "POTOCZNE. Uprzejmy gest, nie konkretne zaproszenie — tak jak polskie „wpadnij kiedyś”.", "wolny wolny to przyjść",
 ("Wpadnij, jak będziesz miał czas.", "wâang wâang kâw maa ná khráp", "ว่างๆ ก็มานะครับ")),

# =====================================================================
# REJESTRY — TEN SAM KOMUNIKAT INACZEJ
# =====================================================================
("B1", "Proszę chwilę zaczekać. (formalnie)", "khǎw rá-bòp raw sák khrûu ná khráp", "ขอระบบรอสักครู่นะครับ", "Podstawy i grzeczność", "Rejestr", "sentence", 3, "f",
 "REJESTR formalny. Wersja neutralna: „raw sák khrûu ná khráp”. Potoczna: „raw dǐao ná”. Używaj przy kliencie i w urzędzie.", "",
 ("Proszę chwilę zaczekać, sprawdzam.", "khǎw rá-bòp raw sák khrûu ná khráp kam-lang trùat sàwp", "ขอระบบรอสักครู่นะครับ กำลังตรวจสอบ")),
("B1", "Zaraz, chwilkę. (potocznie)", "raw dǐao ná", "รอเดี๋ยวนะ", "Podstawy i grzeczność", "Rejestr", "sentence", 4, "p",
 "REJESTR potoczny. Wersja neutralna: „raw sák khrûu ná khráp”. Formalna: „khǎw rá-bòp raw sák khrûu”. Wobec obcych brzmi zbyt swojsko.", "",
 ("Zaraz, chwilkę, już idę.", "raw dǐao ná maa láew", "รอเดี๋ยวนะ มาแล้ว")),
("B1", "Nie zgadzam się. (formalnie)", "phǒm khǎw mâi hěn dûai khráp", "ผมขอไม่เห็นด้วยครับ", "Cechy i opinie", "Rejestr", "sentence", 3, "f",
 "REJESTR formalny. Neutralnie: „phǒm mâi khâwi hěn dûai khráp”. Potocznie: „mâi ao dûai”. „khǎw” zamienia sprzeciw w prośbę o prawo do innego zdania.", "",
 ("Przy całym szacunku, nie zgadzam się.", "dûai khwaam khaw-róp phǒm khǎw mâi hěn dûai khráp", "ด้วยความเคารพ ผมขอไม่เห็นด้วยครับ")),
("B1", "Nie bardzo się zgadzam. (neutralnie)", "phǒm mâi khâwi hěn dûai", "ผมไม่ค่อยเห็นด้วย", "Cechy i opinie", "Rejestr", "sentence", 4, "n",
 "REJESTR neutralny. Formalnie: „khǎw mâi hěn dûai khráp”. Potocznie: „mâi ao dûai”. „mâi khâwi” osłabia sprzeciw i chroni twarz rozmówcy.", "",
 ("Nie bardzo się z tym zgadzam.", "phǒm mâi khâwi hěn dûai rûeang níi khráp", "ผมไม่ค่อยเห็นด้วยเรื่องนี้ครับ")),
("B1", "Dziękuję za pomoc. (formalnie)", "khàwp phrá khun thîi chûai lǔea khráp", "ขอบพระคุณที่ช่วยเหลือครับ", "Podstawy i grzeczność", "Rejestr", "sentence", 3, "f",
 "REJESTR formalny. Neutralnie: „khàwp khun thîi chûai khráp”. Potocznie: „thǎeng khráp”. Używaj wobec osób starszych i urzędników.", "",
 ("Bardzo dziękuję za okazaną pomoc.", "khàwp phrá khun mâak thîi chûai lǔea khráp", "ขอบพระคุณมากที่ช่วยเหลือครับ")),
("B1", "Dzięki. (potocznie)", "thǎeng khráp", "แต๊งครับ", "Podstawy i grzeczność", "Rejestr", "sentence", 3, "p",
 "REJESTR potoczny, zapożyczone „thanks”. Neutralnie: „khàwp khun khráp”. Formalnie: „khàwp phrá khun khráp”. Wobec starszych zabrzmi lekceważąco.", "",
 ("Dzięki wielkie!", "thǎeng mâak khráp", "แต๊งมากครับ")),
("B1", "Czy mógłbym prosić o…? (formalnie)", "phǒm khǎw rá-bòp nòi dâai mǎi khráp", "ผมขอรบกวนหน่อยได้ไหมครับ", "Podstawy i grzeczność", "Rejestr", "sentence", 3, "f",
 "REJESTR formalny. „rá-bòp” znaczy „kłopotać” — prosisz, uznając, że sprawiasz kłopot. Neutralnie: „chûai … nòi dâai mǎi khráp”. Potocznie: „chûai nòi”.", "ja proszę kłopotać trochę móc czy",
 ("Czy mógłbym prosić o chwilę uwagi?", "phǒm khǎw rá-bòp sák khrûu dâai mǎi khráp", "ผมขอรบกวนสักครู่ได้ไหมครับ")),
("B1", "Pomożesz? (potocznie)", "chûai nòi dâi mǎi", "ช่วยหน่อยได้มั้ย", "Podstawy i grzeczność", "Rejestr", "sentence", 4, "p",
 "REJESTR potoczny — „mǎi” skrócone do „mái/mǎi” bez „khráp”. Neutralnie: „chûai nòi dâai mǎi khráp”. Wobec obcych zawsze dodawaj „khráp/khâ”.", "",
 ("Pomożesz mi na chwilę?", "chûai nòi dâi mǎi", "ช่วยหน่อยได้มั้ย")),
("B1", "Przepraszam za kłopot. (formalnie)", "khǎw-thôot thîi tâwng rá-bòp khráp", "ขอโทษที่ต้องรบกวนครับ", "Podstawy i grzeczność", "Rejestr", "sentence", 3, "f",
 "REJESTR formalny. Neutralnie: „khǎw-thôot thîi rá-bòp khráp”. Potocznie: „thôot ná”. Otwiera prośbę do osoby zajętej.", "",
 ("Przepraszam, że kłopoczę.", "khǎw-thôot thîi tâwng rá-bòp khráp", "ขอโทษที่ต้องรบกวนครับ")),
("B1", "Sorki. (potocznie)", "thôot ná", "โทษนะ", "Podstawy i grzeczność", "Rejestr", "sentence", 4, "p",
 "REJESTR potoczny. Neutralnie: „khǎw-thôot khráp”. Formalnie: „khǎw-thôot dûai khráp”. Przy poważnej przewinie zabrzmi lekceważąco.", "",
 ("Sorki, nie zauważyłem.", "thôot ná mâi hěn loei", "โทษนะ ไม่เห็นเลย")),
]
