# -*- coding: utf-8 -*-
"""Sesja N — partia druga: ciało, ubranie, technika, uzupełnienia kategorii.

Partia pierwsza (pięć modułów) domykała kategorie najuboższe. Ta uzupełnia
pola, które w mowie potocznej wracają stale, a w bazie były reprezentowane
przez pojedyncze hasła: części ciała poza twarzą, ubranie poza koszulą,
telefon i internet, oraz drugi rzut czasowników i przymiotników.

Krotka: (poziom, polski, fonetyka, pismo, podkategoria, częstość, typ,
         kategoria, uwaga, dosłownie)
"""

ZD = "Zdrowie"
DM = "Dom i codzienność"
ZK = "Zakupy i pieniądze"
CZ = "Czasowniki"
CO = "Cechy i opinie"
PN = "Praca i nauka"
ST = "Small talk"
PL = "Miejsca i orientacja"
LR = "Ludzie i rodzina"
PP = "Pogoda i przyroda"
JN = "Jedzenie i napoje"

EXTRA = [

# ============================================================ CIAŁO
("A1", "ciało", "râang kaai", "ร่างกาย", "Ciało", 4, "n", ZD,
 "tua to ciało w mowie potocznej i klasyfikator zwierząt oraz ubrań.", ""),
("A1", "szyja", "khaw", "คอ", "Ciało", 4, "n", ZD,
 "Także gardło — jèp khaw znaczy ból gardła.", ""),
("A1", "ramię, bark", "lài", "ไหล่", "Ciało", 3, "n", ZD,
 "", ""),
("A1", "łokieć", "khâw sàwk", "ข้อศอก", "Ciało", 2, "n", ZD,
 "khâw to staw i punkt.", "staw łokieć"),
("A1", "nadgarstek", "khâw mue", "ข้อมือ", "Ciało", 2, "n", ZD,
 "", "staw ręka"),
("A1", "palec", "níu", "นิ้ว", "Ciało", 4, "n", ZD,
 "To samo słowo co „cal”.", ""),
("A1", "paznokieć", "lép", "เล็บ", "Ciało", 3, "n", ZD,
 "tàt lép — obciąć paznokcie.", ""),
("A1", "kolano", "hǔa khào", "หัวเข่า", "Ciało", 3, "n", ZD,
 "hǔa znów jako „głowa czegoś”.", "głowa kolano"),
("A1", "kostka (u nogi)", "khâw tháo", "ข้อเท้า", "Ciało", 2, "n", ZD,
 "", "staw stopa"),
("A1", "plecy", "lǎng", "หลัง", "Ciało", 4, "n", ZD,
 "To samo słowo znaczy „po, za” w czasie: lǎng aa-hǎan.", ""),
("A1", "klatka piersiowa", "nâa òk", "หน้าอก", "Ciało", 3, "n", ZD,
 "", "przód pierś"),
("A2", "serce (narząd)", "hǔa jai", "หัวใจ", "Ciało", 4, "n", ZD,
 "jai samo to siedziba uczuć; hǔa jai to narząd.", "głowa serce"),
("A2", "żołądek", "krà-phǽ aa-hǎan", "กระเพาะอาหาร", "Ciało", 2, "n", ZD,
 "Potocznie mówi się po prostu tháwng.", "worek jedzenie"),
("A2", "płuca", "pàwt", "ปอด", "Ciało", 2, "n", ZD,
 "", ""),
("A2", "wątroba", "tàp", "ตับ", "Ciało", 2, "n", ZD,
 "Także w menu — tàp mǔu.", ""),
("A2", "kość", "krà-dùuk", "กระดูก", "Ciało", 3, "n", ZD,
 "", ""),
("A2", "mięsień", "klâam núea", "กล้ามเนื้อ", "Ciało", 2, "n", ZD,
 "núea to mięso i miąższ.", "muskuł mięso"),
("A2", "skóra", "phǐu", "ผิว", "Ciało", 3, "n", ZD,
 "phǐu nǎng — cera.", ""),
("A2", "krew", "lûeat", "เลือด", "Ciało", 3, "n", ZD,
 "", ""),
("A2", "mózg", "sà-mǒong", "สมอง", "Ciało", 2, "n", ZD,
 "", ""),
("A2", "oddychać", "hǎai jai", "หายใจ", "Ciało", 3, "v", ZD,
 "Dosłownie „znikać sercem”.", "znikać serce"),

# ============================================================ UBRANIE
("A1", "ubranie", "sûea phâa", "เสื้อผ้า", "Ubranie", 5, "n", ZK,
 "Uwaga: sûea (koszula) kontra sǔea (tygrys) — sam ton.", "koszula tkanina"),
("A1", "spodnie", "kaang keeng", "กางเกง", "Ubranie", 5, "n", ZK,
 "Krótkie: kaang keeng khǎa sân.", ""),
("A1", "spódnica", "krà-prohng", "กระโปรง", "Ubranie", 3, "n", ZK,
 "", ""),
("A1", "sukienka", "chút krà-prohng", "ชุดกระโปรง", "Ubranie", 3, "n", ZK,
 "chút to komplet, zestaw.", "komplet spódnica"),
("A1", "buty", "rawng tháo", "รองเท้า", "Ubranie", 5, "n", ZK,
 "Dosłownie „podkładka pod stopę”. Zdejmuje się je przed wejściem do domu i do świątyni.", "podkładka stopa"),
("A2", "klapki", "rawng tháo tàe", "รองเท้าแตะ", "Ubranie", 5, "n", ZK,
 "Podstawowe obuwie kraju.", "buty dotykać"),
("A2", "skarpetki", "thǔng tháo", "ถุงเท้า", "Ubranie", 3, "n", ZK,
 "thǔng to torba i worek.", "worek stopa"),
("A2", "czapka, kapelusz", "mùak", "หมวก", "Ubranie", 4, "n", ZK,
 "", ""),
("A2", "okulary", "wâen taa", "แว่นตา", "Ubranie", 4, "n", ZK,
 "Przeciwsłoneczne: wâen kan dàet.", "szkło oko"),
("A2", "pasek", "khěm khàt", "เข็มขัด", "Ubranie", 2, "n", ZK,
 "khěm to igła.", "igła zaciskać"),
("A2", "biżuteria", "khrûeang prà-dàp", "เครื่องประดับ", "Ubranie", 2, "n", ZK,
 "", "wyposażenie ozdabiać"),
("A2", "pierścionek", "wǎen", "แหวน", "Ubranie", 2, "n", ZK,
 "", ""),
("A2", "zegarek", "naa-lí-kaa khâw mue", "นาฬิกาข้อมือ", "Ubranie", 3, "n", ZK,
 "", "zegar nadgarstek"),
("A2", "portfel", "krà-pǎo taang", "กระเป๋าตังค์", "Ubranie", 4, "n", ZK,
 "taang to potoczne „pieniądze”.", "torba pieniądze"),
("A2", "plecak", "pêe", "เป้", "Ubranie", 3, "n", ZK,
 "Pełna forma: krà-pǎo pêe.", ""),
("A2", "parasol", "rôm", "ร่ม", "Ubranie", 4, "n", ZK,
 "Także „cień” — nâng nai rôm.", ""),
("A2", "płaszcz przeciwdeszczowy", "sûea kan fǒn", "เสื้อกันฝน", "Ubranie", 3, "n", ZK,
 "kan to chronić przed — ten sam wyraz co w mùak kan náwk.", "koszula chronić deszcz"),
("A2", "sweter, bluza", "sûea kan nǎao", "เสื้อกันหนาว", "Ubranie", 3, "n", ZK,
 "Potrzebny w autobusie nocnym i w każdym centrum handlowym.", "koszula chronić zimno"),

# ============================================================ TECHNIKA
("A1", "telefon komórkowy", "mueu thǔe", "มือถือ", "Technika", 5, "n", DM,
 "Dosłownie „ręka trzyma”.", "ręka trzymać"),
("A2", "ładowarka", "thîi châat", "ที่ชาร์จ", "Technika", 4, "n", DM,
 "", "narzędzie ładować"),
("A2", "bateria", "bàet-tôe-rîi", "แบตเตอรี่", "Technika", 4, "n", DM,
 "W mowie skracane do bàet.", ""),
("A2", "ekran", "nâa jaw", "หน้าจอ", "Technika", 4, "n", DM,
 "", "twarz ekran"),
("A2", "aplikacja", "áep", "แอป", "Technika", 4, "n", DM,
 "", ""),
("A2", "hasło", "rá-hàt phàan", "รหัสผ่าน", "Technika", 4, "n", DM,
 "rá-hàt to kod.", "kod przechodzić"),
("A2", "wi-fi", "waai-faai", "ไวไฟ", "Technika", 5, "n", DM,
 "Pierwsze pytanie w każdej kawiarni.", ""),
("A2", "internet", "in-tooe-nét", "อินเทอร์เน็ต", "Technika", 4, "n", DM,
 "Potocznie: nét.", ""),
("A2", "sygnał, zasięg", "sǎn-yaan", "สัญญาณ", "Technika", 4, "n", DM,
 "mâi mii sǎn-yaan — nie ma zasięgu.", ""),
("A2", "karta SIM", "sim", "ซิม", "Technika", 4, "n", DM,
 "Kupuje się na lotnisku i w każdym markecie.", ""),
("A2", "doładowanie", "toem ngoen", "เติมเงิน", "Technika", 4, "n", DM,
 "toem to dolewać, uzupełniać — także paliwo.", "uzupełniać pieniądze"),
("A2", "wiadomość (SMS)", "khâw khwaam", "ข้อความ", "Technika", 4, "n", DM,
 "", "punkt treść"),
("A2", "zdjęcie", "rûup", "รูป", "Technika", 5, "n", DM,
 "thàai rûup — robić zdjęcie. Także „kształt, postać”.", ""),
("A2", "robić zdjęcie", "thàai rûup", "ถ่ายรูป", "Technika", 5, "v", DM,
 "thàai samo znaczy też „przelać, przenieść”.", "przenosić obraz"),
("A2", "nagrywać", "àt", "อัด", "Technika", 3, "v", DM,
 "Także „naciskać, ubijać”.", ""),
("A2", "wysyłać", "sòng", "ส่ง", "Technika", 5, "v", DM,
 "sòng khâw khwaam, sòng khǎwng, sòng khon klàp bâan.", ""),
("A2", "pobierać (plik)", "doo-loot", "ดาวน์โหลด", "Technika", 3, "v", DM,
 "", ""),
("A2", "wyłączyć (urządzenie)", "pìt khrûeang", "ปิดเครื่อง", "Technika", 4, "v", DM,
 "", "zamykać maszyna"),
("A2", "komputer", "khawm-phíu-tôe", "คอมพิวเตอร์", "Technika", 4, "n", DM,
 "Skracane do khawm.", ""),
("A2", "drukarka", "khrûeang phim", "เครื่องพิมพ์", "Technika", 2, "n", DM,
 "phim to drukować i pisać na klawiaturze.", "maszyna drukować"),

# ============================================================ CZASOWNIKI II
("A2", "budzić się", "tùen", "ตื่น", "Codzienność", 5, "v", CZ,
 "tùen nawn — obudzić się ze snu; tùen tên — być podekscytowanym.", ""),
("A2", "zasypiać", "làp", "หลับ", "Codzienność", 4, "v", CZ,
 "nawn làp — zasnąć. nawn samo to tylko „leżeć”.", ""),
("A2", "śnić", "fǎn", "ฝัน", "Codzienność", 3, "v", CZ,
 "Także rzeczownik „sen”.", ""),
("A2", "siadać", "nâng", "นั่ง", "Codzienność", 5, "v", CZ,
 "Także „jechać czymś”: nâng rót fai.", ""),
("A2", "wstawać", "lúk", "ลุก", "Codzienność", 4, "v", CZ,
 "lúk khûen — podnieść się.", ""),
("A2", "stać", "yuen", "ยืน", "Codzienność", 4, "v", CZ,
 "Uwaga: yuen (stać) kontra yuem (pożyczyć).", ""),
("A2", "leżeć", "nawn", "นอน", "Codzienność", 5, "v", CZ,
 "Także „spać” w mowie codziennej.", ""),
("A2", "nieść, zabierać ze sobą", "aw pai", "เอาไป", "Czynności ogólne", 5, "v", CZ,
 "aw maa — przynieść tutaj. Kierunek koduje pai albo maa.", "brać iść"),
("A2", "przynosić", "aw maa", "เอามา", "Czynności ogólne", 5, "v", CZ,
 "", "brać przychodzić"),
("A2", "dostawać, otrzymywać", "dâi ráp", "ได้รับ", "Czynności ogólne", 4, "v", CZ,
 "", "móc przyjmować"),
("A2", "oddawać, zwracać", "khuen", "คืน", "Czynności ogólne", 4, "v", CZ,
 "Homofon z khuen (noc).", ""),
("A2", "zostawiać", "thíng wái", "ทิ้งไว้", "Czynności ogólne", 3, "v", CZ,
 "wái po czasowniku znaczy „na zapas, na potem”.", "porzucać zostawiać"),
("A2", "chować, przechowywać", "kèp wái", "เก็บไว้", "Czynności ogólne", 4, "v", CZ,
 "", "zbierać zostawiać"),
("A2", "zmieniać zdanie", "plìan jai", "เปลี่ยนใจ", "Czynności ogólne", 3, "v", CZ,
 "", "zmieniać serce"),
("A2", "przyzwyczaić się", "chin", "ชิน", "Czynności ogólne", 3, "v", CZ,
 "chin láew — już przywykłem. Częsta odpowiedź o upale.", ""),
("A2", "unikać", "lìik lîang", "หลีกเลี่ยง", "Czynności ogólne", 2, "v", CZ,
 "", ""),
("A2", "pozwolić komuś", "hâi … tham", "ให้ทำ", "Czynności ogólne", 4, "v", CZ,
 "hâi wprowadza sprawczość: hâi phǒm chûai — pozwól, że pomogę.", "dawać robić"),
("A2", "zmusić", "bang-kháp", "บังคับ", "Czynności ogólne", 2, "v", CZ,
 "Także „sterować” pojazdem.", ""),
("A2", "zapłacić za kogoś", "líang", "เลี้ยง", "Czynności ogólne", 4, "v", CZ,
 "Postawić komuś posiłek. Także karmić i hodować.", ""),
("A2", "zaprosić na posiłek", "líang khâao", "เลี้ยงข้าว", "Czynności ogólne", 3, "v", CZ,
 "Kto zaprasza, ten zwykle płaci za wszystkich.", "karmić ryż"),
("A2", "podziękować i odmówić", "khàwp khun mâi ao", "ขอบคุณไม่เอา", "Czynności ogólne", 3, "v", CZ,
 "Uprzejma odmowa u ulicznego sprzedawcy.", "dziękować nie brać"),
("A2", "pasować (rozmiarem)", "phaw dii", "พอดี", "Czynności ogólne", 5, "adj", CZ,
 "Dosłownie „wystarczająco dobrze”. Także „w sam raz” o czasie.", "wystarczyć dobry"),
("A2", "działać, funkcjonować", "chái dâi", "ใช้ได้", "Czynności ogólne", 5, "v", CZ,
 "Także „ujdzie” jako ocena.", "używać móc"),
("A2", "zależeć od", "láew tàe", "แล้วแต่", "Czynności ogólne", 5, "v", CZ,
 "láew tàe khun — jak wolisz. Bardzo częsta odpowiedź.", "potem ale"),

# ============================================================ PRZYMIOTNIKI II
("A2", "ciężki", "nàk", "หนัก", "Właściwości", 4, "adj", CO,
 "Także o deszczu i o pracy.", ""),
("A2", "lekki", "bao", "เบา", "Właściwości", 4, "adj", CO,
 "Także „cicho” o głośności: bao bao nòi.", ""),
("A2", "czysty", "sà-àat", "สะอาด", "Właściwości", 5, "adj", CO,
 "", ""),
("A2", "brudny", "sòk-kà-pròk", "สกปรก", "Właściwości", 4, "adj", CO,
 "", ""),
("A2", "nowy", "mài", "ใหม่", "Właściwości", 5, "adj", CO,
 "Uwaga na trójkę: mài (nowy), mâi (nie), mǎi (partykuła pytajna).", ""),
("A2", "stary (o rzeczy)", "kào", "เก่า", "Właściwości", 5, "adj", CO,
 "O człowieku: kàe.", ""),
("A2", "zajęty (miejsce)", "mâi wâang", "ไม่ว่าง", "Właściwości", 4, "adj", CO,
 "", "nie wolny"),
("A2", "gotowy", "phráwm", "พร้อม", "Właściwości", 5, "adj", CO,
 "phráwm láew — gotowe. Także „razem z”.", ""),
("A2", "trudny", "yâak", "ยาก", "Ocena", 5, "adj", CO,
 "Uwaga: yâak (trudny) kontra yàak (chcieć) — sam ton.", ""),
("A2", "łatwy", "ngâai", "ง่าย", "Ocena", 5, "adj", CO,
 "Nagłosowe ng-.", ""),
("A2", "ważny", "sǎm-khan", "สำคัญ", "Ocena", 5, "adj", CO,
 "", ""),
("A2", "niepotrzebny", "mâi jam-pen", "ไม่จำเป็น", "Ocena", 4, "adj", CO,
 "jam-pen to konieczny.", "nie konieczny"),
("A2", "konieczny", "jam-pen", "จำเป็น", "Ocena", 4, "adj", CO,
 "", ""),
("A2", "wygodny", "sà-bàai", "สบาย", "Ocena", 5, "adj", CO,
 "Fundament kultury: sà-bàai sà-bàai znaczy „na luzie”.", ""),
("A2", "niewygodny", "mâi sà-dùak", "ไม่สะดวก", "Ocena", 4, "adj", CO,
 "sà-dùak to dogodny — grzeczna formuła odmowy.", "nie dogodny"),
("A2", "dogodny", "sà-dùak", "สะดวก", "Ocena", 4, "adj", CO,
 "", ""),
("A2", "znany, słynny", "mii chûe sǐang", "มีชื่อเสียง", "Ocena", 4, "adj", CO,
 "chûe to imię, sǐang to głos.", "mieć imię głos"),
("A2", "popularny", "níyom", "นิยม", "Ocena", 3, "adj", CO,
 "", ""),
("A2", "drogi (bliski sercu)", "thîi rák", "ที่รัก", "Ocena", 3, "adj", CO,
 "Zwrot do bliskiej osoby.", "który kochać"),
("A2", "wystarczająco dobry", "chái dâi looei", "ใช้ได้เลย", "Ocena", 3, "adj", CO,
 "", "używać móc wcale"),
("A2", "okropny", "yâe mâak", "แย่มาก", "Ocena", 3, "adj", CO,
 "", "zły bardzo"),
("A2", "przepyszny", "à-ràwi mâak", "อร่อยมาก", "Ocena", 5, "adj", CO,
 "Najczęściej wypowiadany komplement w tym kraju.", "smaczny bardzo"),

# ============================================================ UZUPEŁNIENIA
("A2", "kawiarnia", "ráan kaa-fae", "ร้านกาแฟ", "Miejsca publiczne", 5, "n", PL,
 "", "sklep kawa"),
("A2", "bar, knajpa", "ráan lâo", "ร้านเหล้า", "Miejsca publiczne", 3, "n", PL,
 "lâo to alkohol mocny.", "sklep alkohol"),
("A2", "siłownia", "fít-nét", "ฟิตเนส", "Miejsca publiczne", 3, "n", PL,
 "", ""),
("A2", "basen", "sà wâai nám", "สระว่ายน้ำ", "Miejsca publiczne", 4, "n", PL,
 "sà znów jako „staw, zbiornik”.", "staw pływać woda"),
("A2", "toaleta publiczna", "hâwng nám sǎa-thaa-rá-ná", "ห้องน้ำสาธารณะ", "Miejsca publiczne", 4, "n", PL,
 "Bywa płatna — 5 do 10 bahtów.", "toaleta publiczny"),
("A2", "przystanek autobusowy", "pâai rót mee", "ป้ายรถเมล์", "Orientacja", 4, "n", PL,
 "rót mee to autobus miejski.", "znak autobus"),
("A2", "wieś", "mùu bâan", "หมู่บ้าน", "Orientacja", 4, "n", PL,
 "mùu to grupa. Także osiedle w mieście.", "grupa dom"),
("A2", "prowincja", "jang-wàt", "จังหวัด", "Orientacja", 4, "n", PL,
 "Tajlandia ma 77 prowincji.", ""),
("A2", "dzielnica", "khèet", "เขต", "Orientacja", 3, "n", PL,
 "W adresie w Bangkoku obowiązkowy.", ""),
("A2", "granica (państwa)", "chaai daen", "ชายแดน", "Orientacja", 3, "n", PL,
 "", "brzeg granica"),
("A2", "stolica", "mueang lǔang", "เมืองหลวง", "Orientacja", 3, "n", PL,
 "lǔang to główny, królewski.", "miasto główny"),
("A2", "centrum miasta", "nai mueang", "ในเมือง", "Orientacja", 5, "n", PL,
 "Dosłownie „w mieście” — mówi się tak w odróżnieniu od przedmieść.", "w miasto"),
("A2", "przedmieścia", "chaan mueang", "ชานเมือง", "Orientacja", 2, "n", PL,
 "", "obrzeże miasto"),

("A2", "kolega ze szkoły", "phûean rûam hâwng", "เพื่อนร่วมห้อง", "Ludzie", 3, "n", LR,
 "Także współlokator.", "przyjaciel wspólnie pokój"),
("A2", "najlepszy przyjaciel", "phûean sà-nìt", "เพื่อนสนิท", "Ludzie", 4, "n", LR,
 "sà-nìt to bliski, zażyły.", "przyjaciel bliski"),
("A2", "znajomość, relacja", "khwaam sǎm-phan", "ความสัมพันธ์", "Ludzie", 3, "n", LR,
 "", "stan związek"),
("A2", "grupa, ekipa", "klùm", "กลุ่ม", "Ludzie", 4, "n", LR,
 "klùm phûean — paczka znajomych.", ""),
("A2", "tłum", "fǔung chon", "ฝูงชน", "Ludzie", 2, "n", LR,
 "", "stado ludzie"),
("A2", "sąsiedztwo, okolica", "lǽew bâan", "ละแวกบ้าน", "Ludzie", 2, "n", LR,
 "", "okolica dom"),

("A2", "hobby", "ngaan à-dì-rèek", "งานอดิเรก", "Rozmowa", 4, "n", ST,
 "Bardzo częste pytanie przy poznawaniu się.", "zajęcie hobby"),
("A2", "sport", "kii-laa", "กีฬา", "Rozmowa", 4, "n", ST,
 "lên kii-laa — uprawiać sport.", ""),
("A2", "muzyka", "don-trii", "ดนตรี", "Rozmowa", 4, "n", ST,
 "phleeng to piosenka, don-trii to muzyka jako dziedzina.", ""),
("A2", "film", "nǎng", "หนัง", "Rozmowa", 5, "n", ST,
 "To samo słowo znaczy „skóra”.", ""),
("A2", "książka", "nǎng-sǔe", "หนังสือ", "Rozmowa", 5, "n", ST,
 "", ""),
("A2", "gra", "keem", "เกม", "Rozmowa", 4, "n", ST,
 "", ""),
("A2", "podróżować", "thâwng thîao", "ท่องเที่ยว", "Rozmowa", 5, "v", ST,
 "thîao samo znaczy „wybrać się gdzieś dla przyjemności” i jest częstsze.", ""),
("A2", "wybrać się gdzieś", "pai thîao", "ไปเที่ยว", "Rozmowa", 5, "v", ST,
 "Obejmuje i wyjazd, i wieczorne wyjście.", "iść wycieczka"),
("A2", "gotować (hobby)", "tham aa-hǎan", "ทำอาหาร", "Rozmowa", 5, "v", ST,
 "", "robić jedzenie"),
("A2", "ogrodnictwo", "tham sǔan", "ทำสวน", "Rozmowa", 2, "v", ST,
 "", "robić ogród"),
("A2", "wolny czas", "wee-laa wâang", "เวลาว่าง", "Rozmowa", 5, "n", ST,
 "", "czas wolny"),

("A2", "kurs, szkolenie", "khàwt", "คอร์ส", "Nauka", 3, "n", PN,
 "", ""),
("A2", "wykład", "kaan ban-yaai", "การบรรยาย", "Nauka", 2, "n", PN,
 "", "czynność wykładać"),
("A2", "referat, raport", "raai ngaan", "รายงาน", "Nauka", 3, "n", PN,
 "Także „zgłaszać, meldować”.", "pozycja praca"),
("A2", "grupa (zajęciowa)", "hâwng rian", "ห้องเรียน", "Nauka", 4, "n", PN,
 "Także sala lekcyjna.", "pokój uczyć się"),
("A2", "przerwa", "phák brèek", "พักเบรก", "Nauka", 3, "n", PN,
 "", "odpoczynek przerwa"),
("A2", "semestr", "phâak rian", "ภาคเรียน", "Nauka", 2, "n", PN,
 "phâak to część, region.", "część uczyć się"),
("A2", "wiedza", "khwaam rúu", "ความรู้", "Nauka", 4, "n", PN,
 "", "stan wiedzieć"),
("A2", "pomysł", "khwaam khít", "ความคิด", "Nauka", 4, "n", PN,
 "khwaam khít hěn — opinia.", "stan myśleć"),
("A2", "opinia", "khwaam khít hěn", "ความคิดเห็น", "Nauka", 4, "n", PN,
 "", "stan myśleć widzieć"),
("A2", "przykład", "tua yàang", "ตัวอย่าง", "Nauka", 5, "n", PN,
 "chên — na przykład, jako spójnik.", "ciało sposób"),
("A2", "na przykład", "chên", "เช่น", "Nauka", 5, "w", PN,
 "", ""),
("A2", "powód, przyczyna", "sǎa-hèet", "สาเหตุ", "Nauka", 3, "n", PN,
 "", ""),
("A2", "wynik, skutek", "phǒn", "ผล", "Nauka", 4, "n", PN,
 "Także „owoc” — phǒn-lá-mái.", ""),
("A2", "problem", "pan-hǎa", "ปัญหา", "Nauka", 5, "n", PN,
 "mâi mii pan-hǎa — nie ma problemu.", ""),
("A2", "rozwiązanie", "wí-thii kâe pan-hǎa", "วิธีแก้ปัญหา", "Nauka", 3, "n", PN,
 "wí-thii to sposób, metoda.", "sposób naprawiać problem"),
("A2", "sposób, metoda", "wí-thii", "วิธี", "Nauka", 4, "n", PN,
 "", ""),

("A2", "powietrze", "aa-kàat", "อากาศ", "Pogoda", 5, "n", PP,
 "To samo słowo znaczy „pogoda”: aa-kàat dii — ładna pogoda.", ""),
("A2", "duszno", "òp âao", "อบอ้าว", "Pogoda", 3, "adj", PP,
 "Wilgotny upał bez wiatru.", ""),
("A2", "chłodny, przyjemnie zimny", "yen sà-baai", "เย็นสบาย", "Pogoda", 3, "adj", PP,
 "", "zimny wygodny"),
("A2", "upał", "khwaam ráwn", "ความร้อน", "Pogoda", 4, "n", PP,
 "", "stan gorący"),
("A2", "ulewa", "fǒn tòk nàk", "ฝนตกหนัก", "Pogoda", 4, "n", PP,
 "Dosłownie „deszcz pada ciężko”.", "deszcz spadać ciężki"),
("A2", "mżawka", "fǒn prawi", "ฝนปรอย", "Pogoda", 2, "n", PP,
 "", "deszcz mżyć"),

("A2", "owoc", "phǒn-lá-mái", "ผลไม้", "Składniki", 5, "n", JN,
 "", "owoc drewno"),
("A2", "warzywo", "phàk", "ผัก", "Składniki", 5, "n", JN,
 "mang-sà-wí-rát — wegetariański.", ""),
("A2", "mięso", "núea", "เนื้อ", "Składniki", 5, "n", JN,
 "Samo núea znaczy zwykle wołowinę; núea mǔu to wieprzowina.", ""),
("A2", "owoce morza", "aa-hǎan thá-lee", "อาหารทะเล", "Składniki", 5, "n", JN,
 "", "jedzenie morze"),
("A2", "mango", "má-mûang", "มะม่วง", "Składniki", 5, "n", JN,
 "khâao nǐao má-mûang — ryż kleisty z mango.", ""),
("A2", "arbuz", "taeng moo", "แตงโม", "Składniki", 4, "n", JN,
 "", ""),
("A2", "ananas", "sàp-pà-rót", "สับปะรด", "Składniki", 4, "n", JN,
 "", ""),
("A2", "papaja", "má-lá-kaw", "มะละกอ", "Składniki", 4, "n", JN,
 "Główny składnik sôm tam.", ""),
("A2", "durian", "thú-rian", "ทุเรียน", "Składniki", 3, "n", JN,
 "Zakazany w hotelach i w metrze — zapach utrzymuje się dobę.", ""),
("A2", "kokos", "má-phráao", "มะพร้าว", "Składniki", 4, "n", JN,
 "", ""),
("A2", "chleb", "khà-nǒm pang", "ขนมปัง", "Składniki", 4, "n", JN,
 "khà-nǒm to ogólnie słodycz, przekąska.", "przekąska chleb"),
("A2", "ser", "noei khǎeng", "เนยแข็ง", "Składniki", 2, "n", JN,
 "noei to masło.", "masło twardy"),
("A2", "masło", "noei", "เนย", "Składniki", 3, "n", JN,
 "", ""),
("A2", "mleko", "nom", "นม", "Składniki", 4, "n", JN,
 "", ""),
("A2", "jogurt", "yoo-kôet", "โยเกิร์ต", "Składniki", 2, "n", JN,
 "", ""),
]
