# -*- coding: utf-8 -*-
"""Leksyka etapu 4 (B1) — czesc E.

Zakres: wynajem mieszkania, umowa i kaucja, naprawy i usterki, sasiedzi,
technologia: telefon, internet, aplikacje, konta.

Format jak w lex_b1_core_a.py.
"""

CORE_E = [

# =====================================================================
# WYNAJEM MIESZKANIA
# =====================================================================
("Szukam mieszkania do wynajęcia.", "phǒm hǎa hâwng châo khráp", "ผมหาห้องเช่าครับ",
 "Dom i codzienność", "Wynajem", "sentence", 4, "n",
 "„hâwng châo” dosłownie „pokój do wynajęcia” — tak Tajowie mówią też o całych mieszkaniach.", "",
 ("Jaki budżet?", "ngóp prà-maan thâo-rài khráp", "งบประมาณเท่าไหร่ครับ")),
("Ile wynosi czynsz miesięczny?", "khâa châo duean lá thâo-rài khráp", "ค่าเช่าเดือนละเท่าไหร่ครับ",
 "Dom i codzienność", "Wynajem", "question", 5, "n", "„duean lá” = na miesiąc.", "",
 ("Dwanaście tysięcy.", "nùeng mùen sǎwng phan khráp", "หนึ่งหมื่นสองพันครับ")),
("Czy w cenie są media?", "ruam khâa náam khâa fai mǎi khráp", "รวมค่าน้ำค่าไฟไหมครับ",
 "Dom i codzienność", "Wynajem", "question", 4, "n",
 "„khâa náam khâa fai” = woda i prąd. Tajowie wymieniają je zawsze razem.", "",
 ("Osobno.", "jàai yâek khráp", "จ่ายแยกครับ")),
("Jaka jest kaucja?", "khâa mát-jam thâo-rài khráp", "ค่ามัดจำเท่าไหร่ครับ",
 "Dom i codzienność", "Wynajem", "question", 4, "f", "„mát-jam” = kaucja, zadatek.", "",
 ("Za dwa miesiące.", "sǎwng duean khráp", "สองเดือนครับ")),
("Na jak długo jest umowa?", "sǎn-yaa kìi duean khráp", "สัญญากี่เดือนครับ",
 "Dom i codzienność", "Wynajem", "question", 3, "f", "", "",
 ("Na rok.", "nùeng pii khráp", "หนึ่งปีครับ")),
("Czy mogę zobaczyć pokój?", "khǎw duu hâwng nòi dâai mǎi khráp", "ขอดูห้องหน่อยได้ไหมครับ",
 "Dom i codzienność", "Wynajem", "question", 4, "n", "", "",
 ("Proszę za mną.", "choen thaang níi khráp", "เชิญทางนี้ครับ")),
("Czy jest umeblowane?", "mii fəə-ní-jôe hâi mǎi khráp", "มีเฟอร์นิเจอร์ให้ไหมครับ",
 "Dom i codzienność", "Wynajem", "question", 3, "n", "", "",
 ("Wszystko jest.", "mii khróp khráp", "มีครบครับ")),
("Czy można trzymać zwierzęta?", "líang sàt dâai mǎi khráp", "เลี้ยงสัตว์ได้ไหมครับ",
 "Dom i codzienność", "Wynajem", "question", 3, "n", "„líang” = hodować, opiekować się.", "",
 ("Niestety nie.", "mâi dâai khráp", "ไม่ได้ครับ")),
("Kiedy mogę się wprowadzić?", "khâo yùu dâai mûea-rài khráp", "เข้าอยู่ได้เมื่อไหร่ครับ",
 "Dom i codzienność", "Wynajem", "question", 3, "n", "„khâo yùu” = wprowadzić się.", "",
 ("Od pierwszego.", "wan thîi nùeng khráp", "วันที่หนึ่งครับ")),
("Czy czynsz można negocjować?", "lót khâa châo dâai mǎi khráp", "ลดค่าเช่าได้ไหมครับ",
 "Dom i codzienność", "Wynajem", "question", 3, "n", "", "",
 ("Trochę mogę spuścić.", "lót hâi nít nòi dâai khráp", "ลดให้นิดหน่อยได้ครับ")),
("Chciałbym przedłużyć umowę.", "phǒm yàak tàw sǎn-yaa khráp", "ผมอยากต่อสัญญาครับ",
 "Dom i codzienność", "Wynajem", "sentence", 3, "f", "", "",
 ("Bez problemu.", "dâai khráp", "ได้ครับ")),
("Chcę wypowiedzieć umowę.", "phǒm khǎw yók lôek sǎn-yaa khráp", "ผมขอยกเลิกสัญญาครับ",
 "Dom i codzienność", "Wynajem", "sentence", 2, "f", "„yók lôek” = anulować, rozwiązać.", "",
 ("Trzeba miesiąc wcześniej.", "tâwng jâeng lûang nâa nùeng duean khráp", "ต้องแจ้งล่วงหน้าหนึ่งเดือนครับ")),
("Kiedy dostanę kaucję z powrotem?", "dâai khâa mát-jam khǒen mûea-rài khráp",
 "ได้ค่ามัดจำคืนเมื่อไหร่ครับ", "Dom i codzienność", "Wynajem", "question", 3, "f", "", "",
 ("W ciągu miesiąca.", "phaai nai nùeng duean khráp", "ภายในหนึ่งเดือนครับ")),
("Sąsiedzi są bardzo głośni.", "phûean bâan sǐang dang mâak khráp", "เพื่อนบ้านเสียงดังมากครับ",
 "Dom i codzienność", "Sąsiedzi", "sentence", 3, "n", "„phûean bâan” = sąsiad.", "przyjaciel domu",
 ("Porozmawiam z nimi.", "dǐao khui hâi khráp", "เดี๋ยวคุยให้ครับ")),
("Czy można prosić o ciszę po dziesiątej?", "lǎng sìp thûm chûai bao sǐang nòi dâai mǎi khráp",
 "หลังสิบทุ่มช่วยเบาเสียงหน่อยได้ไหมครับ", "Dom i codzienność", "Sąsiedzi", "question", 2, "f",
 "„bao sǐang” = ściszyć. Uprzejma prośba, nie żądanie.", "",
 ("Przepraszamy.", "khǎw-thôot khráp", "ขอโทษครับ")),

# =====================================================================
# NAPRAWY I USTERKI
# =====================================================================
("Klimatyzacja nie działa.", "âae sǐa khráp", "แอร์เสียครับ",
 "Dom i codzienność", "Naprawy", "sentence", 5, "n",
 "„âae” to skrót od air. „sǐa” = zepsuty, nie działa — najczęstsze słowo przy usterkach.", "",
 ("Wyślę technika.", "dǐao hâi châang pai duu khráp", "เดี๋ยวให้ช่างไปดูครับ")),
("Cieknie woda z sufitu.", "náam rûa jàak phee-daan khráp", "น้ำรั่วจากเพดานครับ",
 "Dom i codzienność", "Naprawy", "sentence", 3, "n", "„rûa” = przeciekać, „phee-daan” = sufit.", "",
 ("Sprawdzimy dziś.", "wan níi jà pai duu khráp", "วันนี้จะไปดูครับ")),
("Zatkał się odpływ.", "thâw tan khráp", "ท่อตันครับ",
 "Dom i codzienność", "Naprawy", "sentence", 3, "n", "„tan” = zatkany.", "",
 ("Przyślę hydraulika.", "dǐao hâi châang prà-pàa maa khráp", "เดี๋ยวให้ช่างประปามาครับ")),
("Nie ma ciepłej wody.", "náam ùn mâi maa khráp", "น้ำอุ่นไม่มาครับ",
 "Hotel", "Naprawy", "sentence", 4, "n", "", "",
 ("Sprawdzę bojler.", "dǐao chék khrûeang tham náam ùn khráp", "เดี๋ยวเช็คเครื่องทำน้ำอุ่นครับ")),
("Nie działa gniazdko.", "plák fai chái mâi dâai khráp", "ปลั๊กไฟใช้ไม่ได้ครับ",
 "Dom i codzienność", "Naprawy", "sentence", 3, "n", "", "",
 ("Zaraz obejrzę.", "dǐao maa duu khráp", "เดี๋ยวมาดูครับ")),
("Zamek się zaciął.", "kun-jae tìt khráp", "กุญแจติดครับ",
 "Dom i codzienność", "Naprawy", "sentence", 3, "n", "", "",
 ("Przyjdę z narzędziami.", "dǐao ao khrûeang mue maa khráp", "เดี๋ยวเอาเครื่องมือมาครับ")),
("Czy może pan to naprawić dzisiaj?", "sâwm hâi wan níi dâai mǎi khráp", "ซ่อมให้วันนี้ได้ไหมครับ",
 "Dom i codzienność", "Naprawy", "question", 4, "n", "„sâwm” = naprawiać.", "",
 ("Postaram się.", "jà phá-yaa-yaam khráp", "จะพยายามครับ")),
("Ile będzie kosztować naprawa?", "khâa sâwm thâo-rài khráp", "ค่าซ่อมเท่าไหร่ครับ",
 "Dom i codzienność", "Naprawy", "question", 4, "n", "", "",
 ("Najpierw obejrzę.", "khǎw duu kàwn khráp", "ขอดูก่อนครับ")),
("Czy to jest na gwarancji?", "yang yùu nai prà-kan mǎi khráp", "ยังอยู่ในประกันไหมครับ",
 "Zakupy i pieniądze", "Naprawy", "question", 3, "f", "„prà-kan” = gwarancja, ubezpieczenie.", "",
 ("Proszę o paragon.", "khǎw bai sèt dûai khráp", "ขอใบเสร็จด้วยครับ")),
("Kto pokrywa koszt naprawy?", "khrai àwk khâa sâwm khráp", "ใครออกค่าซ่อมครับ",
 "Dom i codzienność", "Naprawy", "question", 3, "f", "„àwk khâa …” = pokrywać koszt.", "",
 ("Właściciel.", "jâo khǎwng khráp", "เจ้าของครับ")),
("To się zepsuło samo.", "man sǐa eeng khráp", "มันเสียเองครับ",
 "Dom i codzienność", "Naprawy", "sentence", 3, "n",
 "„eeng” po czasowniku = samo z siebie. Ważne przy sporze o kaucję.", "",
 ("Rozumiem.", "khâo-jai khráp", "เข้าใจครับ")),
("Kiedy przyjdzie technik?", "châang jà maa mûea-rài khráp", "ช่างจะมาเมื่อไหร่ครับ",
 "Dom i codzienność", "Naprawy", "question", 4, "n", "„châang” = fachowiec, rzemieślnik.", "",
 ("Po południu.", "tawn bàai khráp", "ตอนบ่ายครับ")),
("Proszę uprzedzić przed przyjściem.", "chûai thoo maa kàwn maa ná khráp", "ช่วยโทรมาก่อนมานะครับ",
 "Dom i codzienność", "Naprawy", "sentence", 3, "n", "", "",
 ("Dobrze.", "dâai khráp", "ได้ครับ")),

# =====================================================================
# TECHNOLOGIA
# =====================================================================
("Nie mam zasięgu.", "mâi mii sǎn-yaan khráp", "ไม่มีสัญญาณครับ",
 "Dom i codzienność", "Technologia", "sentence", 4, "n", "„sǎn-yaan” = sygnał, zasięg.", "",
 ("Spróbuj przy oknie.", "lawng pai trong nâa tàang khráp", "ลองไปตรงหน้าต่างครับ")),
("Internet jest bardzo wolny.", "nét cháa mâak khráp", "เน็ตช้ามากครับ",
 "Dom i codzienność", "Technologia", "sentence", 5, "p",
 "„nét” to potoczny skrót. W umowie z operatorem będzie „in-tôoe-nét”.", "",
 ("Zrestartuj router.", "lawng rii-sét ráo-tôoe khráp", "ลองรีเซ็ตเราเตอร์ครับ")),
("Nie mogę się połączyć z wi-fi.", "tàw wai-fâi mâi dâai khráp", "ต่อไวไฟไม่ได้ครับ",
 "Dom i codzienność", "Technologia", "sentence", 4, "n", "", "",
 ("Podam ci hasło.", "dǐao bàwk phàat-wòet hâi khráp", "เดี๋ยวบอกพาสเวิร์ดให้ครับ")),
("Jakie jest hasło do wi-fi?", "phàat-wòet wai-fâi à-rai khráp", "พาสเวิร์ดไวไฟอะไรครับ",
 "Dom i codzienność", "Technologia", "question", 5, "n", "", "",
 ("Jest na kartce.", "yùu nai bai nán khráp", "อยู่ในใบนั้นครับ")),
("Telefon mi się rozładował.", "bàet-toe-rîi mòt khráp", "แบตเตอรี่หมดครับ",
 "Dom i codzienność", "Technologia", "sentence", 4, "n", "„mòt” = wyczerpać się, skończyć się.", "",
 ("Mam powerbank.", "mii phaao-wôoe-bâeng khráp", "มีพาวเวอร์แบงค์ครับ")),
("Czy mogę naładować telefon?", "khǎw chàat thoo-rá-sàp nòi dâai mǎi khráp",
 "ขอชาร์จโทรศัพท์หน่อยได้ไหมครับ", "Dom i codzienność", "Technologia", "question", 4, "n", "", "",
 ("Gniazdko jest tam.", "plák yùu trong nán khráp", "ปลั๊กอยู่ตรงนั้นครับ")),
("Aplikacja się zawiesza.", "áep khâang khráp", "แอปค้างครับ",
 "Dom i codzienność", "Technologia", "sentence", 3, "p",
 "„khâang” = zawiesić się, zamrozić. Potoczne, ale używane też przez obsługę techniczną.", "",
 ("Zainstaluj od nowa.", "lawng long mài khráp", "ลองลงใหม่ครับ")),
("Zapomniałem hasła.", "phǒm luem phàat-wòet khráp", "ผมลืมพาสเวิร์ดครับ",
 "Dom i codzienność", "Technologia", "sentence", 4, "n", "", "",
 ("Zresetuj przez maila.", "rii-sét phàan ii-meew khráp", "รีเซ็ตผ่านอีเมลครับ")),
("Nie dostałem kodu SMS.", "mâi dâi ráp roo-hàt thaang sáet khráp", "ไม่ได้รับรหัสทางแชทครับ",
 "Dom i codzienność", "Technologia", "sentence", 3, "n", "„roo-hàt” = kod, PIN.", "",
 ("Wyślę ponownie.", "dǐao sòng mài khráp", "เดี๋ยวส่งใหม่ครับ")),
("Chciałbym doładować telefon.", "phǒm yàak toem ngoen mue-thǔe khráp", "ผมอยากเติมเงินมือถือครับ",
 "Dom i codzienność", "Technologia", "sentence", 4, "n",
 "„toem ngoen” = doładować konto. „mue-thǔe” = komórka.", "",
 ("Ile chce pan doładować?", "toem thâo-rài khráp", "เติมเท่าไหร่ครับ")),
("Chcę kupić pakiet internetu.", "phǒm yàak sǔe pháek-kèet nét khráp", "ผมอยากซื้อแพ็คเกจเน็ตครับ",
 "Dom i codzienność", "Technologia", "sentence", 3, "n", "", "",
 ("Na ile dni?", "kìi wan khráp", "กี่วันครับ")),
("Czy mogę zeskanować kod?", "sà-kaen khiw-aa dâai mǎi khráp", "สแกนคิวอาร์ได้ไหมครับ",
 "Dom i codzienność", "Technologia", "question", 4, "n", "", "",
 ("Proszę.", "choen khráp", "เชิญครับ")),
("Prześlij mi to na czacie.", "sòng maa thaang sáet ná khráp", "ส่งมาทางแชทนะครับ",
 "Dom i codzienność", "Technologia", "sentence", 4, "i",
 "W Tajlandii domyślnym komunikatorem jest LINE, nie SMS.", "",
 ("Już wysyłam.", "sòng láew khráp", "ส่งแล้วครับ")),
("Dodaj mnie do grupy.", "chûai ao phǒm khâo klùm dûai khráp", "ช่วยเอาผมเข้ากลุ่มด้วยครับ",
 "Dom i codzienność", "Technologia", "sentence", 3, "i", "", "",
 ("Dodane.", "khâo hâi láew khráp", "เข้าให้แล้วครับ")),
("Nie widzę tej wiadomości.", "phǒm mâi hěn khâw-khwaam níi khráp", "ผมไม่เห็นข้อความนี้ครับ",
 "Dom i codzienność", "Technologia", "sentence", 3, "n", "", "",
 ("Wyślę jeszcze raz.", "dǐao sòng mài khráp", "เดี๋ยวส่งใหม่ครับ")),
("Zrób zrzut ekranu.", "kèp phâap nâa jaw hâi nòi khráp", "เก็บภาพหน้าจอให้หน่อยครับ",
 "Dom i codzienność", "Technologia", "sentence", 3, "n", "„nâa jaw” = ekran.", "twarz ekranu",
 ("Już wysyłam.", "sòng láew khráp", "ส่งแล้วครับ")),
("Konto zostało zablokowane.", "ban-chii thùuk láwk khráp", "บัญชีถูกล็อคครับ",
 "Dom i codzienność", "Technologia", "sentence", 2, "f",
 "„thùuk” tworzy stronę bierną i niesie odcień czegoś niepożądanego.", "",
 ("Skontaktuj się z obsługą.", "tìt tàw fàai bawrikaan khráp", "ติดต่อฝ่ายบริการครับ")),
]
