# -*- coding: utf-8 -*-
"""Sesja F — ZDROWIE: dolegliwosci, leki, apteka, wypadki.

Uwaga systemowa o bolu. Tajski ma dwa slowa: „pùat” to bol tepy,
wewnetrzny (glowa, brzuch, zeby), „jèp” to bol ostry, od rany albo
uderzenia. Konstrukcja jest zawsze ta sama: pùat/jèp + czesc ciala.
Kto zna czesci ciala z tej bazy, zbuduje kazda skarge sam.
"""

ZD = "Zdrowie"

HEALTH = [

# ------------------------------------------------------------ dolegliwosci
("A1", "boleć (tępo)", "pùat", "ปวด", ZD, "Dolegliwości", 5, "n",
 "Ból wewnętrzny i tępy. Zawsze z częścią ciała: pùat hǔa, pùat tháwng, pùat fan.",
 "",
 [("Boli mnie głowa.", "phǒm pùat hǔa khráp", "ผมปวดหัวครับ"),
  ("Boli mnie brzuch.", "phǒm pùat tháwng khráp", "ผมปวดท้องครับ")],
 ["boleć (ostro)", "głowa", "brzuch"], []),

("A1", "boleć (ostro)", "jèp", "เจ็บ", ZD, "Dolegliwości", 5, "n",
 "Ból od rany, skaleczenia, uderzenia. „jèp khaw” to ból gardła — wyjątek od reguły.",
 "",
 [("Boli mnie gardło.", "phǒm jèp khaw khráp", "ผมเจ็บคอครับ"),
  ("Boli, kiedy dotykam.", "tàe láew jèp khráp", "แตะแล้วเจ็บครับ")],
 ["boleć (tępo)", "gardło", "rana"], []),

("A2", "gorączka", "khâi", "ไข้", ZD, "Dolegliwości", 4, "n",
 "„pen khâi” to mieć gorączkę. Uwaga na parę: „khài” to jajko, „khǎi” to odkręcać.",
 "",
 [("Mam gorączkę.", "phǒm pen khâi khráp", "ผมเป็นไข้ครับ"),
  ("Proszę zmierzyć temperaturę.", "chûai wát khâi dûai khráp", "ช่วยวัดไข้ด้วยครับ")],
 ["mierzyć", "chory", "lek"], []),

("A2", "kaszel", "ai", "ไอ", ZD, "Dolegliwości", 4, "n",
 "Bardzo krótkie słowo. „yaa kâe ai” to syrop na kaszel.",
 "",
 [("Mam kaszel.", "phǒm ai khráp", "ผมไอครับ"),
  ("Poproszę coś na kaszel.", "khǎw yaa kâe ai khráp", "ขอยาแก้ไอครับ")],
 ["gardło", "lek", "apteka"], []),

("A2", "katar", "nám mûuk lǎi", "น้ำมูกไหล", ZD, "Dolegliwości", 3, "n",
 "Dosłownie „płynie wydzielina z nosa”. Krócej: „pen wàt” — być przeziębionym.",
 "woda nos płynąć",
 [("Mam katar.", "phǒm nám mûuk lǎi khráp", "ผมน้ำมูกไหลครับ"),
  ("Jestem przeziębiony.", "phǒm pen wàt khráp", "ผมเป็นหวัดครับ")],
 ["nos", "przeziębienie", "lek"], []),

("A2", "przeziębienie", "wàt", "หวัด", ZD, "Dolegliwości", 4, "n",
 "„pen wàt” to najczęstsza skarga w aptece. Klimatyzacja bywa wskazywana jako przyczyna.",
 "",
 [("Jestem przeziębiony.", "phǒm pen wàt khráp", "ผมเป็นหวัดครับ"),
  ("Poproszę lek na przeziębienie.", "khǎw yaa kâe wàt khráp", "ขอยาแก้หวัดครับ")],
 ["katar", "lek", "klimatyzacja"], []),

("A2", "biegunka", "tháwng sǐa", "ท้องเสีย", ZD, "Dolegliwości", 4, "n",
 "Dosłownie „zepsuty brzuch”. Częsta dolegliwość podróżnych — warto znać nazwę leku „yaa kâe tháwng sǐa”.",
 "brzuch zepsuty",
 [("Mam biegunkę.", "phǒm tháwng sǐa khráp", "ผมท้องเสียครับ"),
  ("Poproszę lek na biegunkę.", "khǎw yaa kâe tháwng sǐa khráp", "ขอยาแก้ท้องเสียครับ")],
 ["brzuch", "zepsuty", "apteka"], []),

("A2", "wymiotować", "aa-jian", "อาเจียน", ZD, "Dolegliwości", 3, "f",
 "Forma potoczna: „ûak”. W rozmowie z lekarzem lepsza jest wersja formalna.",
 "",
 [("Wymiotowałem dwa razy.", "phǒm aa-jian sǎwng khráng khráp", "ผมอาเจียนสองครั้งครับ"),
  ("Chce mi się wymiotować.", "phǒm khlûen sâi khráp", "ผมคลื่นไส้ครับ")],
 ["biegunka", "brzuch", "chory"], []),

("A2", "zawroty głowy", "wian hǔa", "เวียนหัว", ZD, "Dolegliwości", 3, "n",
 "„wian” znaczy kręcić się w kółko. To samo słowo w „wong wian” — rondo.",
 "kręcić głowa",
 [("Mam zawroty głowy.", "phǒm wian hǔa khráp", "ผมเวียนหัวครับ"),
  ("Muszę usiąść.", "phǒm tâwng nâng khráp", "ผมต้องนั่งครับ")],
 ["głowa", "boleć (tępo)", "siedzieć"], []),

("A2", "alergia", "pháe", "แพ้", ZD, "Dolegliwości", 4, "n",
 "„pháe” znaczy też „przegrać”. W kontekście jedzenia zawsze rozumiane jako alergia — kluczowe przy zamawianiu.",
 "",
 [("Jestem uczulony na orzeszki.", "phǒm pháe thùa khráp", "ผมแพ้ถั่วครับ"),
  ("Jestem uczulony na owoce morza.", "phǒm pháe aa-hǎan thá-lee khráp", "ผมแพ้อาหารทะเลครับ")],
 ["orzeszki ziemne", "krewetka", "jedzenie"], ["uczulenie"]),

("A2", "wysypka", "phùen", "ผื่น", ZD, "Dolegliwości", 2, "n",
 "„phùen khan” to swędząca wysypka — częste po ukąszeniach owadów.",
 "",
 [("Mam wysypkę.", "phǒm mii phùen khráp", "ผมมีผื่นครับ"),
  ("Swędzi mnie.", "phǒm khan khráp", "ผมคันครับ")],
 ["skóra", "alergia", "komar"], []),

("A2", "swędzieć", "khan", "คัน", ZD, "Dolegliwości", 3, "n",
 "Uwaga: „khan” to również klasyfikator pojazdów — „rót nùeng khan”. Kontekst rozstrzyga.",
 "",
 [("Swędzi mnie noga.", "phǒm khan khǎa khráp", "ผมคันขาครับ"),
  ("Jeden samochód.", "rót nùeng khan khráp", "รถหนึ่งคันครับ")],
 ["wysypka", "skóra", "samochód"], []),

("A2", "oparzenie słoneczne", "phǐu mâi dàet", "ผิวไหม้แดด", ZD, "Dolegliwości", 3, "n",
 "„mâi” tu znaczy „spalony”. Realne ryzyko na plaży przez cały rok.",
 "skóra spalony słońce",
 [("Spaliłem się na słońcu.", "phǒm phǐu mâi dàet khráp", "ผมผิวไหม้แดดครับ"),
  ("Poproszę krem z filtrem.", "khǎw khriim kan dàet khráp", "ขอครีมกันแดดครับ")],
 ["skóra", "słońce", "plaża"], []),

("A2", "skręcić (nogę)", "kháw plìk", "ข้อเท้าพลิก", ZD, "Wypadki", 2, "n",
 "„plìk” znaczy przewrócić na drugą stronę. „kháw tháo” to kostka.",
 "kostka przewracać",
 [("Skręciłem kostkę.", "phǒm kháw tháo plìk khráp", "ผมข้อเท้าพลิกครับ"),
  ("Nie mogę chodzić.", "phǒm doen mâi dâai khráp", "ผมเดินไม่ได้ครับ")],
 ["noga", "stopa", "boleć (ostro)"], []),

("A2", "złamać (kość)", "krà-dùuk hàk", "กระดูกหัก", ZD, "Wypadki", 2, "n",
 "„hàk” to złamać coś podłużnego. Przy szkle używa się „tàek”.",
 "kość łamać",
 [("Chyba mam złamaną rękę.", "khít wâa krà-dùuk mue hàk khráp", "คิดว่ากระดูกมือหักครับ"),
  ("Trzeba zrobić prześwietlenie.", "tâwng èk-sa-ree khráp", "ต้องเอกซเรย์ครับ")],
 ["kość", "ręka (dłoń)", "szpital"], []),

("A2", "skaleczenie", "bàat phlǎe", "บาดแผล", ZD, "Wypadki", 2, "n",
 "„phlǎe” samo znaczy rana. „tham phlǎe” to opatrzyć ranę.",
 "ciąć rana",
 [("Mam skaleczenie.", "phǒm mii bàat phlǎe khráp", "ผมมีบาดแผลครับ"),
  ("Proszę o plaster.", "khǎw pláat-sà-tôoe khráp", "ขอพลาสเตอร์ครับ")],
 ["rana", "krwawić", "plaster"], []),

("A2", "plaster", "pláat-sà-tôoe", "พลาสเตอร์", ZD, "Apteka", 3, "n",
 "Zapożyczenie z angielskiego, rozumiane w każdej aptece.",
 "",
 [("Poproszę plaster.", "khǎw pláat-sà-tôoe khráp", "ขอพลาสเตอร์ครับ"),
  ("Gdzie kupię plastry?", "súe pláat-sà-tôoe dâai thîi nǎi khráp", "ซื้อพลาสเตอร์ได้ที่ไหนครับ")],
 ["skaleczenie", "apteka", "rana"], []),

("A2", "bandaż", "phâa phan phlǎe", "ผ้าพันแผล", ZD, "Apteka", 2, "n",
 "„phan” znaczy owijać. Ten sam czasownik w „phan khaw” — owinąć szyję szalikiem.",
 "tkanina owijać rana",
 [("Poproszę bandaż.", "khǎw phâa phan phlǎe khráp", "ขอผ้าพันแผลครับ"),
  ("Trzeba to zabandażować.", "tâwng phan phlǎe khráp", "ต้องพันแผลครับ")],
 ["plaster", "rana", "apteka"], []),

# ------------------------------------------------------------------ apteka
("A2", "tabletka", "yaa mét", "ยาเม็ด", ZD, "Apteka", 3, "n",
 "„mét” to klasyfikator drobnych okrągłych rzeczy: tabletek, ziarenek, także chili.",
 "lek ziarno",
 [("Dwie tabletki po jedzeniu.", "yaa sǎwng mét lǎng aa-hǎan khráp", "ยาสองเม็ดหลังอาหารครับ"),
  ("Ile tabletek dziennie?", "wan lá kìi mét khráp", "วันละกี่เม็ดครับ")],
 ["lek", "jedzenie", "chili"], []),

("A2", "lek przeciwbólowy", "yaa kâe pùat", "ยาแก้ปวด", ZD, "Apteka", 4, "n",
 "Wzorzec „yaa kâe + dolegliwość” tworzy nazwę każdego leku: yaa kâe ai, yaa kâe wàt, yaa kâe tháwng sǐa.",
 "lek leczyć ból",
 [("Poproszę coś przeciwbólowego.", "khǎw yaa kâe pùat khráp", "ขอยาแก้ปวดครับ"),
  ("Boli mnie głowa, poproszę lek.", "pùat hǔa khǎw yaa nòi khráp", "ปวดหัวขอยาหน่อยครับ")],
 ["lek", "boleć (tępo)", "apteka"], []),

("A2", "antybiotyk", "yaa khâa chúea", "ยาฆ่าเชื้อ", ZD, "Apteka", 2, "f",
 "Dosłownie „lek zabijający zarazki”. W Tajlandii dostępny w aptece łatwiej niż w Europie.",
 "lek zabijać zarazek",
 [("Czy potrzebny jest antybiotyk?", "tâwng chái yaa khâa chúea mǎi khráp", "ต้องใช้ยาฆ่าเชื้อไหมครับ"),
  ("Lekarz przepisał antybiotyk.", "mǎw sàng yaa khâa chúea khráp", "หมอสั่งยาฆ่าเชื้อครับ")],
 ["lek", "lekarz", "apteka"], []),

("A2", "witamina", "wí-taa-min", "วิตามิน", ZD, "Apteka", 2, "n",
 "Zapożyczenie. W aptekach dostępne bez recepty i szeroko reklamowane.",
 "",
 [("Biorę witaminy.", "phǒm kin wí-taa-min khráp", "ผมกินวิตามินครับ"),
  ("Poproszę witaminę C.", "khǎw wí-taa-min sii khráp", "ขอวิตามินซีครับ")],
 ["lek", "apteka", "zdrowy"], []),

("A2", "recepta", "bai sàng yaa", "ใบสั่งยา", ZD, "Apteka", 2, "f",
 "„sàng” to zamawiać, zlecać — to samo słowo co przy zamawianiu jedzenia.",
 "arkusz zlecać lek",
 [("Mam receptę.", "phǒm mii bai sàng yaa khráp", "ผมมีใบสั่งยาครับ"),
  ("Czy potrzebna jest recepta?", "tâwng mii bai sàng yaa mǎi khráp", "ต้องมีใบสั่งยาไหมครับ")],
 ["lek", "lekarz", "apteka"], []),

("A2", "dawka", "khà-nàat yaa", "ขนาดยา", ZD, "Apteka", 2, "f",
 "„khà-nàat” to ten sam „rozmiar” co przy ubraniach — słowo produktywne.",
 "rozmiar lek",
 [("Jaka dawka?", "khà-nàat yaa thâo-rài khráp", "ขนาดยาเท่าไหร่ครับ"),
  ("Jedna tabletka trzy razy dziennie.", "nùeng mét wan lá sǎam khráng khráp", "หนึ่งเม็ดวันละสามครั้งครับ")],
 ["tabletka", "rozmiar", "lek"], []),

("A2", "po jedzeniu", "lǎng aa-hǎan", "หลังอาหาร", ZD, "Apteka", 3, "f",
 "Standardowa instrukcja na opakowaniu, obok „kàwn aa-hǎan” — przed jedzeniem.",
 "po jedzenie",
 [("Brać po jedzeniu.", "kin lǎng aa-hǎan khráp", "กินหลังอาหารครับ"),
  ("Przed jedzeniem czy po?", "kàwn rǔe lǎng aa-hǎan khráp", "ก่อนหรือหลังอาหารครับ")],
 ["tabletka", "jedzenie", "po tym jak"], []),

# ------------------------------------------------------------------ opieka
("A2", "wizyta u lekarza", "pai hǎa mǎw", "ไปหาหมอ", ZD, "Opieka", 4, "n",
 "„hǎa” tu znaczy „udać się do kogoś”, nie „szukać”. Ta sama konstrukcja co „pai hǎa phûean”.",
 "iść do lekarz",
 [("Muszę iść do lekarza.", "phǒm tâwng pai hǎa mǎw khráp", "ผมต้องไปหาหมอครับ"),
  ("Byłem u lekarza.", "phǒm pai hǎa mǎw maa láew khráp", "ผมไปหาหมอมาแล้วครับ")],
 ["lekarz", "szpital", "szukać"], []),

("A2", "klinika", "khli-ník", "คลินิก", ZD, "Opieka", 3, "n",
 "Tańsza i szybsza alternatywa dla szpitala przy drobnych dolegliwościach.",
 "",
 [("W pobliżu jest klinika.", "thǎew níi mii khli-ník khráp", "แถวนี้มีคลินิกครับ"),
  ("Klinika jest otwarta do ósmej.", "khli-ník pòoet thǔeng sǎwng thûm khráp", "คลินิกเปิดถึงสองทุ่มครับ")],
 ["szpital", "lekarz", "otwarty"], []),

("A2", "pogotowie", "rót phá-yaa-baan", "รถพยาบาล", ZD, "Opieka", 3, "n",
 "Numer alarmowy do karetki w Tajlandii to 1669 — warto go zapisać przed podróżą.",
 "pojazd pielęgnować",
 [("Proszę wezwać karetkę.", "chûai rîak rót phá-yaa-baan khráp", "ช่วยเรียกรถพยาบาลครับ"),
  ("To nagły wypadek.", "chùk chǒoen khráp", "ฉุกเฉินครับ")],
 ["szpital", "wypadek", "wołać"], ["karetka"]),

("A2", "nagły wypadek", "chùk chǒoen", "ฉุกเฉิน", ZD, "Opieka", 3, "f",
 "Słowo na tablicach: „hâwng chùk chǒoen” to izba przyjęć.",
 "",
 [("To nagły przypadek.", "pen rûeang chùk chǒoen khráp", "เป็นเรื่องฉุกเฉินครับ"),
  ("Gdzie jest izba przyjęć?", "hâwng chùk chǒoen yùu nǎi khráp", "ห้องฉุกเฉินอยู่ไหนครับ")],
 ["pogotowie", "szpital", "pomagać"], []),

("A2", "ubezpieczenie", "prà-kan", "ประกัน", ZD, "Opieka", 3, "f",
 "„prà-kan sù-khà-phâap” to ubezpieczenie zdrowotne, „prà-kan doen thaang” — podróżne.",
 "",
 [("Mam ubezpieczenie.", "phǒm mii prà-kan khráp", "ผมมีประกันครับ"),
  ("Czy przyjmujecie ubezpieczenie?", "ráp prà-kan mǎi khráp", "รับประกันไหมครับ")],
 ["szpital", "dokument", "płacić"], []),

("A2", "szczepienie", "chìit wák-siin", "ฉีดวัคซีน", ZD, "Opieka", 2, "f",
 "„chìit” znaczy wstrzykiwać — to samo słowo przy zastrzyku.",
 "wstrzykiwać szczepionka",
 [("Byłem szczepiony.", "phǒm chìit wák-siin láew khráp", "ผมฉีดวัคซีนแล้วครับ"),
  ("Gdzie mogę się zaszczepić?", "chìit wák-siin dâai thîi nǎi khráp", "ฉีดวัคซีนได้ที่ไหนครับ")],
 ["zastrzyk", "szpital", "dokument"], []),

("A2", "zastrzyk", "chìit yaa", "ฉีดยา", ZD, "Opieka", 2, "n",
 "Dosłownie „wstrzyknąć lek”. W tajskich klinikach zastrzyk bywa proponowany częściej niż w Europie.",
 "wstrzykiwać lek",
 [("Czy potrzebny jest zastrzyk?", "tâwng chìit yaa mǎi khráp", "ต้องฉีดยาไหมครับ"),
  ("Wolę tabletki.", "phǒm khǎw yaa mét dii kwàa khráp", "ผมขอยาเม็ดดีกว่าครับ")],
 ["szczepienie", "tabletka", "lek"], []),

("A2", "badanie krwi", "trùat lûeat", "ตรวจเลือด", ZD, "Opieka", 2, "f",
 "„trùat” to ten sam czasownik co przy kontroli dokumentów — sprawdzać, badać.",
 "sprawdzać krew",
 [("Trzeba zrobić badanie krwi.", "tâwng trùat lûeat khráp", "ต้องตรวจเลือดครับ"),
  ("Kiedy będą wyniki?", "phǒn àwk mûea-rài khráp", "ผลออกเมื่อไหร่ครับ")],
 ["krew", "sprawdzać", "szpital"], []),

("A2", "zdrowie", "sù-khà-phâap", "สุขภาพ", ZD, "Opieka", 3, "f",
 "„sù-khà-phâap dii” to dobre zdrowie — częste życzenie noworoczne.",
 "",
 [("Dbam o zdrowie.", "phǒm duu lae sù-khà-phâap khráp", "ผมดูแลสุขภาพครับ"),
  ("Życzę zdrowia.", "khǎw hâi sù-khà-phâap khǎeng raeng khráp", "ขอให้สุขภาพแข็งแรงครับ")],
 ["zdrowy", "opiekować się", "silny"], []),

("A2", "odpoczynek (leczniczy)", "phák phàwn", "พักผ่อน", ZD, "Opieka", 3, "n",
 "Typowe zalecenie lekarza: „phák phàwn yóe yóe” — dużo odpoczywać.",
 "odpoczywać rozluźniać",
 [("Proszę odpoczywać.", "phák phàwn yóe yóe khráp", "พักผ่อนเยอะๆครับ"),
  ("Muszę odpocząć.", "phǒm tâwng phák phàwn khráp", "ผมต้องพักผ่อนครับ")],
 ["odpoczywać", "spać", "zmęczony"], []),

("A2", "wyzdrowieć", "hǎai", "หาย", ZD, "Opieka", 4, "n",
 "Uwaga: to samo słowo znaczy „zniknąć, zgubić się”. „hǎai reo reo ná” to życzenie szybkiego powrotu do zdrowia.",
 "",
 [("Już wyzdrowiałem.", "phǒm hǎai láew khráp", "ผมหายแล้วครับ"),
  ("Zdrowiej szybko.", "hǎai reo reo ná khráp", "หายเร็วๆนะครับ")],
 ["chory", "gubić", "zdrowy"], []),

("A2", "ciąża", "tháwng", "ท้อง", ZD, "Opieka", 2, "n",
 "To samo słowo co brzuch. „mii tháwng” albo „tháwng” znaczy być w ciąży.",
 "brzuch",
 [("Jest w ciąży.", "kháo tháwng khráp", "เขาท้องครับ"),
  ("Nie mogę pić, jestem w ciąży.", "chán dùem mâi dâai tháwng yùu khâ", "ฉันดื่มไม่ได้ท้องอยู่ค่ะ")],
 ["brzuch", "dziecko", "szpital"], []),
]
