# -*- coding: utf-8 -*-
"""Sesja F — SWIAT: przyroda, miasto, praca, szkola, sklep.

Uwaga systemowa o nazwach miejsc: „ráan” to przedrostek kazdego lokalu
handlowego (ráan aa-hǎan, ráan kaa-fae, ráan yaa), a „thîi” tworzy nazwy
miejsc funkcyjnych (thîi jàwt rót — parking). Znajomosc tych dwoch
przedrostkow pozwala rozpoznac dziesiatki szyldow bez uczenia sie ich
pojedynczo.
"""

PP = "Pogoda i przyroda"
MO = "Miejsca i orientacja"
PN = "Praca i nauka"
ZP = "Zakupy i pieniądze"

WORLD = [

# ============================================================ PRZYRODA
("A1", "drzewo", "tôn mái", "ต้นไม้", PP, "Przyroda", 4, "n",
 "„tôn” to klasyfikator roślin i zarazem słowo „pień, początek”. „tôn” pojawia się też w „tôn duean” — początek miesiąca.",
 "pień drewno",
 [("Pod drzewem jest cień.", "tâai tôn mái mii rôm khráp", "ใต้ต้นไม้มีร่มครับ"),
  ("To duże drzewo.", "tôn mái yài khráp", "ต้นไม้ใหญ่ครับ")],
 ["liść", "kwiat", "ogród"], []),

("A2", "liść", "bai mái", "ใบไม้", PP, "Przyroda", 3, "n",
 "„bai” to klasyfikator rzeczy płaskich i cienkich: liści, kartek, biletów, talerzy.",
 "arkusz drewno",
 [("Liście opadają.", "bai mái rûang khráp", "ใบไม้ร่วงครับ"),
  ("Podaj mi liść bananowca.", "khǎw bai tawng nòi khráp", "ขอใบตองหน่อยครับ")],
 ["drzewo", "kwiat", "spadać"], []),

("A1", "kwiat", "dàwk mái", "ดอกไม้", PP, "Przyroda", 4, "n",
 "„dàwk” to klasyfikator kwiatów. Girlandy „phuang maa-lai” to codzienny element życia religijnego.",
 "kwiat drewno",
 [("Kupiłem kwiaty.", "phǒm súe dàwk mái khráp", "ผมซื้อดอกไม้ครับ"),
  ("Kwiaty ładnie pachną.", "dàwk mái hǎwm khráp", "ดอกไม้หอมครับ")],
 ["drzewo", "ogród", "pachnący"], []),

("A2", "trawa", "yâa", "หญ้า", PP, "Przyroda", 2, "n",
 "Ton opadający. Nie mylić z „yaa” (lek) ani „yàa” (nie rób).",
 "",
 [("Proszę nie chodzić po trawie.", "yàa doen bon yâa khráp", "อย่าเดินบนหญ้าครับ"),
  ("Trawa jest zielona.", "yâa sǐi khǐao khráp", "หญ้าสีเขียวครับ")],
 ["ogród", "zielony", "park"], []),

("A2", "kamień", "hǐn", "หิน", PP, "Przyroda", 2, "n",
 "„nám khǎeng” to lód, ale „hǐn” to skała. Uwaga na plażach: „hàat hǐn” to plaża kamienista.",
 "",
 [("Plaża jest kamienista.", "hàat pen hǐn khráp", "หาดเป็นหินครับ"),
  ("Uważaj na kamienie.", "rá-wang hǐn khráp", "ระวังหินครับ")],
 ["plaża", "góra", "piasek"], ["skała"]),

("A2", "piasek", "saai", "ทราย", PP, "Przyroda", 3, "n",
 "Uwaga: „sǎai” z tonem rosnącym znaczy „późny ranek” i „linia”. Ton zmienia sens całkowicie.",
 "",
 [("Piasek jest gorący.", "saai ráwn khráp", "ทรายร้อนครับ"),
  ("Biały piasek.", "saai khǎao khráp", "ทรายขาวครับ")],
 ["plaża", "morze", "gorący"], []),

("A2", "fala", "khlûen", "คลื่น", PP, "Przyroda", 3, "n",
 "„khlûen yài” — duże fale. Ważne przy sprawdzaniu, czy prom popłynie.",
 "",
 [("Fale są dziś duże.", "wan níi khlûen yài khráp", "วันนี้คลื่นใหญ่ครับ"),
  ("Prom nie płynie przez fale.", "ruea mâi àwk phráw khlûen khráp", "เรือไม่ออกเพราะคลื่นครับ")],
 ["morze", "plaża", "łódź"], []),

("A2", "rzeka", "mâe nám", "แม่น้ำ", PP, "Przyroda", 3, "n",
 "Dosłownie „matka wody”. „mâe” tworzy też „mâe khrua” — kucharka, gospodyni kuchni.",
 "matka woda",
 [("Rzeka jest szeroka.", "mâe nám kwâang khráp", "แม่น้ำกว้างครับ"),
  ("Popłyniemy łodzią po rzece.", "rao jà nâng ruea nai mâe nám khráp", "เราจะนั่งเรือในแม่น้ำครับ")],
 ["morze", "łódź", "szeroki"], []),

("A2", "wyspa", "kàw", "เกาะ", PP, "Przyroda", 4, "n",
 "Poprzedza nazwy wysp: Kàw Sà-mǔi, Kàw Chaang. Rozpoznanie tego słowa ułatwia czytanie rozkładów promów.",
 "",
 [("Jedziemy na wyspę.", "rao pai kàw khráp", "เราไปเกาะครับ"),
  ("Ta wyspa jest spokojna.", "kàw níi sà-ngòp khráp", "เกาะนี้สงบครับ")],
 ["morze", "łódź", "plaża"], []),

("A2", "las", "pàa", "ป่า", PP, "Przyroda", 3, "n",
 "„pàa” w nazwach parków narodowych. Uwaga na parę: „pàa” (las) i „pâa” (ciotka).",
 "",
 [("W lesie są słonie.", "nai pàa mii cháang khráp", "ในป่ามีช้างครับ"),
  ("Idziemy na spacer do lasu.", "rao pai doen pàa khráp", "เราไปเดินป่าครับ")],
 ["góra", "drzewo", "słoń"], []),

("A2", "wodospad", "nám tòk", "น้ำตก", PP, "Przyroda", 3, "n",
 "Dosłownie „woda spada”. Ostrożnie w porze deszczowej — bywają zamykane.",
 "woda spadać",
 [("Chcę zobaczyć wodospad.", "phǒm yàak duu nám tòk khráp", "ผมอยากดูน้ำตกครับ"),
  ("Wodospad jest zamknięty.", "nám tòk pìt khráp", "น้ำตกปิดครับ")],
 ["rzeka", "las", "spadać"], []),

("A2", "gwiazda", "daao", "ดาว", PP, "Przyroda", 2, "n",
 "To samo słowo o gwieździe filmowej i o ocenie w gwiazdkach: „roong raem hâa daao”.",
 "",
 [("Dziś widać gwiazdy.", "khuen níi hěn daao khráp", "คืนนี้เห็นดาวครับ"),
  ("Hotel pięciogwiazdkowy.", "roong raem hâa daao khráp", "โรงแรมห้าดาวครับ")],
 ["księżyc", "niebo", "noc"], []),

("A2", "księżyc", "phrá jan", "พระจันทร์", PP, "Przyroda", 2, "n",
 "„phrá” to przedrostek honoryfikatywny — używany wobec mnichów, króla i ciał niebieskich.",
 "święty księżyc",
 [("Dziś jest pełnia.", "khuen níi phrá jan tem duang khráp", "คืนนี้พระจันทร์เต็มดวงครับ"),
  ("Księżyc jest jasny.", "phrá jan sà-wàang khráp", "พระจันทร์สว่างครับ")],
 ["gwiazda", "słońce", "noc"], []),

("A2", "cień", "rôm", "ร่ม", PP, "Przyroda", 3, "n",
 "To samo słowo znaczy „parasol”. W tym klimacie jedno i drugie ratuje sytuację.",
 "",
 [("Usiądźmy w cieniu.", "pai nâng nai rôm khráp", "ไปนั่งในร่มครับ"),
  ("Weź parasol.", "ao rôm pai dûai khráp", "เอาร่มไปด้วยครับ")],
 ["słońce", "drzewo", "deszcz"], ["parasol"]),

("A2", "powietrze", "aa-kàat", "อากาศ", PP, "Przyroda", 4, "n",
 "To samo słowo znaczy „pogoda”: „aa-kàat dii” to zarazem ładna pogoda i dobre powietrze.",
 "",
 [("Powietrze jest złe.", "aa-kàat mâi dii khráp", "อากาศไม่ดีครับ"),
  ("Dziś jest ładna pogoda.", "wan níi aa-kàat dii khráp", "วันนี้อากาศดีครับ")],
 ["pogoda", "zanieczyszczenie", "oddychać"], []),

("A2", "zanieczyszczenie", "mon-lá-phít", "มลพิษ", PP, "Przyroda", 3, "f",
 "W sezonie smogowym w Chiang Mai i Bangkoku codzienny temat rozmów. Potocznie mówi się „fùn” — pył.",
 "",
 [("Zanieczyszczenie jest wysokie.", "mon-lá-phít sǔung khráp", "มลพิษสูงครับ"),
  ("Dużo pyłu w powietrzu.", "fùn yóe khráp", "ฝุ่นเยอะครับ")],
 ["powietrze", "maseczka", "pogoda"], ["smog"]),

# ============================================================ MIASTO
("A2", "chodnik", "thaang tháo", "ทางเท้า", MO, "Miasto", 3, "n",
 "Dosłownie „droga stóp”. W praktyce często zajęty przez stragany — stąd częste zejście na jezdnię.",
 "droga stopa",
 [("Chodnik jest zastawiony.", "thaang tháo mii khǎwng waang khráp", "ทางเท้ามีของวางครับ"),
  ("Proszę iść chodnikiem.", "doen bon thaang tháo khráp", "เดินบนทางเท้าครับ")],
 ["ulica", "przejście dla pieszych", "chodzić"], []),

("A2", "przejście dla pieszych", "thaang máa laai", "ทางม้าลาย", MO, "Miasto", 3, "n",
 "Dosłownie „droga w zebrę”. Uwaga: kierowcy rzadko zatrzymują się z własnej woli.",
 "droga zebra",
 [("Gdzie jest przejście?", "thaang máa laai yùu nǎi khráp", "ทางม้าลายอยู่ไหนครับ"),
  ("Przejdź po pasach.", "khâam thaang máa laai khráp", "ข้ามทางม้าลายครับ")],
 ["chodnik", "przechodzić", "ulica"], ["pasy"]),

("A2", "most", "sà-phaan", "สะพาน", MO, "Miasto", 3, "n",
 "„sà-phaan looi” to kładka nad ulicą — częsty sposób przejścia w Bangkoku.",
 "",
 [("Idź przez most.", "khâam sà-phaan khráp", "ข้ามสะพานครับ"),
  ("Za mostem jest targ.", "loei sà-phaan pai mii tà-làat khráp", "เลยสะพานไปมีตลาดครับ")],
 ["rzeka", "przechodzić", "ulica"], []),

("A2", "latarnia uliczna", "sǎo fai", "เสาไฟ", MO, "Miasto", 2, "n",
 "„sǎo” to słup. Przydatne przy opisywaniu miejsca kierowcy taksówki.",
 "słup światło",
 [("Zatrzymaj się przy latarni.", "jàwt trong sǎo fai khráp", "จอดตรงเสาไฟครับ"),
  ("Latarnia nie świeci.", "sǎo fai mâi tìt khráp", "เสาไฟไม่ติดครับ")],
 ["ulica", "światło", "zatrzymać"], []),

("A2", "śmietnik uliczny", "thǎng khà-yà sǎa-thaa-rá-ná", "ถังขยะสาธารณะ", MO, "Miasto", 2, "n",
 "„sǎa-thaa-rá-ná” znaczy publiczny — to samo słowo w „sǔan sǎa-thaa-rá-ná” (park publiczny).",
 "kosz śmieci publiczny",
 [("Gdzie jest kosz?", "thǎng khà-yà yùu nǎi khráp", "ถังขยะอยู่ไหนครับ"),
  ("Proszę nie śmiecić.", "yàa thíng khà-yà khráp", "อย่าทิ้งขยะครับ")],
 ["kosz na śmieci", "wyrzucić"], []),

("A2", "plac", "laan", "ลาน", MO, "Miasto", 2, "n",
 "„laan jàwt rót” to plac parkingowy. Samo „laan” to otwarta utwardzona przestrzeń.",
 "",
 [("Spotkamy się na placu.", "jooe kan thîi laan khráp", "เจอกันที่ลานครับ"),
  ("Parking jest z tyłu.", "laan jàwt rót yùu khâang lǎng khráp", "ลานจอดรถอยู่ข้างหลังครับ")],
 ["parking", "spotykać się"], []),

("A2", "parking", "thîi jàwt rót", "ที่จอดรถ", MO, "Miasto", 3, "n",
 "Dosłownie „miejsce zatrzymania pojazdu”. Przedrostek „thîi” tworzy dziesiątki nazw miejsc.",
 "miejsce zatrzymać pojazd",
 [("Gdzie jest parking?", "thîi jàwt rót yùu nǎi khráp", "ที่จอดรถอยู่ไหนครับ"),
  ("Parking jest pełny.", "thîi jàwt rót tem khráp", "ที่จอดรถเต็มครับ")],
 ["plac", "samochód", "zatrzymać"], []),

("A2", "urząd", "sǎm-nák ngaan", "สำนักงาน", PN, "Miasto", 3, "f",
 "„sǎm-nák ngaan trùat khon khâo mueang” to biuro imigracyjne — najczęściej odwiedzany urząd przez obcokrajowców.",
 "biuro praca",
 [("Idę do urzędu.", "phǒm pai sǎm-nák ngaan khráp", "ผมไปสำนักงานครับ"),
  ("Urząd jest zamknięty.", "sǎm-nák ngaan pìt khráp", "สำนักงานปิดครับ")],
 ["biuro", "dokument", "wiza"], []),

("A2", "świątynia", "wát", "วัด", MO, "Miasto", 4, "n",
 "Poprzedza nazwy: Wát Phoo, Wát Aroon. Zasada wejścia: zakryte ramiona i kolana, buty zdjęte.",
 "",
 [("Idziemy do świątyni.", "rao pai wát khráp", "เราไปวัดครับ"),
  ("Do świątyni trzeba się odpowiednio ubrać.", "khâo wát tâwng tàeng tua sù-phâap khráp", "เข้าวัดต้องแต่งตัวสุภาพครับ")],
 ["mnich", "spódnica", "buty"], []),

("A2", "mnich", "phrá", "พระ", MO, "Miasto", 3, "f",
 "Ważna zasada: kobieta nie dotyka mnicha ani nie podaje mu rzeczy bezpośrednio do ręki.",
 "",
 [("Mnisi zbierają jałmużnę rano.", "phrá bìn-thá-bàat tawn cháo khráp", "พระบิณฑบาตตอนเช้าครับ"),
  ("Kobiety nie dotykają mnichów.", "phûu yǐng mâi tàe tûa phrá khráp", "ผู้หญิงไม่แตะต้องพระครับ")],
 ["świątynia", "kobieta", "rano"], []),

("A2", "posterunek policji", "sà-thǎa-nii tam-rùat", "สถานีตำรวจ", MO, "Miasto", 3, "f",
 "„sà-thǎa-nii” to stacja — także kolejowa i autobusowa. Potocznie „roong phák”.",
 "stacja policja",
 [("Gdzie jest posterunek policji?", "sà-thǎa-nii tam-rùat yùu nǎi khráp", "สถานีตำรวจอยู่ไหนครับ"),
  ("Muszę zgłosić kradzież.", "phǒm tâwng jâeng khwaam khráp", "ผมต้องแจ้งความครับ")],
 ["policja", "kraść", "zgłaszać"], []),

# ============================================================ PRACA
("A2", "biuro", "áwf-fít", "ออฟฟิศ", PN, "Praca", 4, "n",
 "Zapożyczenie z angielskiego, częstsze w mowie potocznej niż formalne „sǎm-nák ngaan”.",
 "",
 [("Jestem w biurze.", "phǒm yùu thîi áwf-fít khráp", "ผมอยู่ที่ออฟฟิศครับ"),
  ("Biuro jest blisko domu.", "áwf-fít yùu klâi bâan khráp", "ออฟฟิศอยู่ใกล้บ้านครับ")],
 ["urząd", "praca", "kolega"], []),

("A2", "szef", "hǔa-nâa", "หัวหน้า", PN, "Praca", 4, "n",
 "Dosłownie „głowa i twarz”. Potocznie mówi się też „jâo naai”.",
 "głowa twarz",
 [("Mój szef jest surowy.", "hǔa-nâa phǒm dù khráp", "หัวหน้าผมดุครับ"),
  ("Muszę zapytać szefa.", "phǒm tâwng thǎam hǔa-nâa kàwn khráp", "ผมต้องถามหัวหน้าก่อนครับ")],
 ["praca", "kolega", "pytać"], []),

("A2", "kolega z pracy", "phûean rûam ngaan", "เพื่อนร่วมงาน", PN, "Praca", 3, "n",
 "„rûam” znaczy wspólny, razem. „rûam thaang” — po drodze razem.",
 "przyjaciel wspólny praca",
 [("To mój kolega z pracy.", "níi phûean rûam ngaan phǒm khráp", "นี่เพื่อนร่วมงานผมครับ"),
  ("Koledzy są mili.", "phûean rûam ngaan jai dii khráp", "เพื่อนร่วมงานใจดีครับ")],
 ["szef", "praca", "przyjaciel"], []),

("A2", "spotkanie", "prà-chum", "ประชุม", PN, "Praca", 4, "f",
 "„khâo prà-chum” — wejść na spotkanie, czyli mieć zebranie. Częste jako powód odmowy.",
 "",
 [("Mam spotkanie o drugiej.", "phǒm mii prà-chum bàai sǎwng khráp", "ผมมีประชุมบ่ายสองครับ"),
  ("Spotkanie zostało przełożone.", "prà-chum lûean khráp", "ประชุมเลื่อนครับ")],
 ["biuro", "szef", "przekładać"], ["zebranie"]),

("A2", "wynagrodzenie", "ngoen duean", "เงินเดือน", PN, "Praca", 3, "n",
 "Dosłownie „pieniądze miesięczne”. Pensję wypłaca się zwykle pod koniec miesiąca.",
 "pieniądze miesiąc",
 [("Pensja przychodzi na koniec miesiąca.", "ngoen duean àwk sîn duean khráp", "เงินเดือนออกสิ้นเดือนครับ"),
  ("Wynagrodzenie jest niskie.", "ngoen duean nói khráp", "เงินเดือนน้อยครับ")],
 ["pieniądze", "praca", "bank"], ["pensja"]),

("A2", "urlop", "wan yùt", "วันหยุด", PN, "Praca", 4, "n",
 "To samo słowo znaczy „dzień wolny” i „święto”. „laa phák ráwn” to konkretnie urlop wypoczynkowy.",
 "dzień zatrzymać",
 [("Jutro mam wolne.", "phrûng-níi phǒm yùt khráp", "พรุ่งนี้ผมหยุดครับ"),
  ("Biorę urlop w przyszłym tygodniu.", "phǒm jà laa phák aa-thít nâa khráp", "ผมจะลาพักอาทิตย์หน้าครับ")],
 ["święto", "praca", "odpoczywać"], ["dzień wolny"]),

("A2", "nadgodziny", "oo-thii", "โอที", PN, "Praca", 2, "p",
 "Skrót od angielskiego OT. W rozmowie o pracy fizycznej słowo bardzo częste.",
 "",
 [("Dziś mam nadgodziny.", "wan níi phǒm tham oo-thii khráp", "วันนี้ผมทำโอทีครับ"),
  ("Nadgodziny są płatne dodatkowo.", "oo-thii dâai ngoen phôoem khráp", "โอทีได้เงินเพิ่มครับ")],
 ["praca", "wynagrodzenie"], []),

# ============================================================ SZKOLA
("A2", "uczeń", "nák rian", "นักเรียน", PN, "Szkoła", 4, "n",
 "„nák” tworzy nazwy zawodów i ról: nák thúrá-kìt (biznesmen), nák dontrii (muzyk), nák kii-laa (sportowiec).",
 "specjalista uczyć się",
 [("Jestem uczniem.", "phǒm pen nák rian khráp", "ผมเป็นนักเรียนครับ"),
  ("Uczniowie noszą mundurki.", "nák rian sài chút nák rian khráp", "นักเรียนใส่ชุดนักเรียนครับ")],
 ["nauczyciel", "szkoła", "uczyć się"], []),

("A2", "student", "nák sùek-sǎa", "นักศึกษา", PN, "Szkoła", 3, "f",
 "Rozróżnienie ważne: „nák rian” to uczeń szkoły, „nák sùek-sǎa” to student uczelni.",
 "specjalista studiować",
 [("Jestem studentem.", "phǒm pen nák sùek-sǎa khráp", "ผมเป็นนักศึกษาครับ"),
  ("Studenci mają zniżkę.", "nák sùek-sǎa lót raa-khaa khráp", "นักศึกษาลดราคาครับ")],
 ["uczeń", "uniwersytet", "zniżka"], []),

("A2", "uniwersytet", "má-hǎa-wít-thá-yaa-lai", "มหาวิทยาลัย", PN, "Szkoła", 3, "f",
 "Długie słowo, w mowie skracane do „má-hǎa-lai”. „má-hǎa” znaczy wielki.",
 "wielki wiedza miejsce",
 [("Studiuję na uniwersytecie.", "phǒm rian thîi má-hǎa-lai khráp", "ผมเรียนที่มหาลัยครับ"),
  ("Uniwersytet jest w mieście.", "má-hǎa-lai yùu nai mueang khráp", "มหาลัยอยู่ในเมืองครับ")],
 ["student", "szkoła", "uczyć się"], []),

("A2", "lekcja", "bòt rian", "บทเรียน", PN, "Szkoła", 3, "n",
 "„bòt” to rozdział. „bòt thîi nùeng” — lekcja pierwsza.",
 "rozdział uczyć się",
 [("Dzisiejsza lekcja jest trudna.", "bòt rian wan níi yâak khráp", "บทเรียนวันนี้ยากครับ"),
  ("Lekcja trzecia.", "bòt thîi sǎam khráp", "บทที่สามครับ")],
 ["uczyć się", "nauczyciel", "trudny"], []),

("A2", "zadanie domowe", "kaan bâan", "การบ้าน", PN, "Szkoła", 3, "n",
 "„kaan” tworzy rzeczowniki odczasownikowe: kaan ngaan (praca), kaan doen thaang (podróżowanie).",
 "czynność dom",
 [("Mam zadanie domowe.", "phǒm mii kaan bâan khráp", "ผมมีการบ้านครับ"),
  ("Odrobiłem zadanie.", "phǒm tham kaan bâan sèt láew khráp", "ผมทำการบ้านเสร็จแล้วครับ")],
 ["lekcja", "uczyć się", "kończyć"], []),

("A2", "zeszyt", "sà-mùt", "สมุด", PN, "Szkoła", 3, "n",
 "„sà-mùt ban-chii” to książeczka bankowa — to samo słowo.",
 "",
 [("Poproszę zeszyt.", "khǎw sà-mùt khráp", "ขอสมุดครับ"),
  ("Zapiszę to w zeszycie.", "phǒm jà jòt nai sà-mùt khráp", "ผมจะจดในสมุดครับ")],
 ["długopis", "notować", "papier"], []),

("A2", "długopis", "pàak-kaa", "ปากกา", PN, "Szkoła", 3, "n",
 "Zawiera „pàak” — usta, dziób. Dosłownie „dziób wrony”, od dawnych piór.",
 "dziób wrona",
 [("Czy mogę pożyczyć długopis?", "khǎw yuem pàak-kaa nòi khráp", "ขอยืมปากกาหน่อยครับ"),
  ("Nie mam długopisu.", "phǒm mâi mii pàak-kaa khráp", "ผมไม่มีปากกาครับ")],
 ["zeszyt", "pisać", "ołówek"], []),

("A2", "ołówek", "din-sǎw", "ดินสอ", PN, "Szkoła", 2, "n",
 "„din” to ziemia, glina. Nie mylić z „dâi” ani „dii”.",
 "",
 [("Poproszę ołówek.", "khǎw din-sǎw khráp", "ขอดินสอครับ"),
  ("Napisz ołówkiem.", "khǐan dûai din-sǎw khráp", "เขียนด้วยดินสอครับ")],
 ["długopis", "zeszyt", "pisać"], []),

("A2", "słownik", "phót-jà-naa-nú-krom", "พจนานุกรม", PN, "Szkoła", 2, "f",
 "Słowo długie i formalne — w mowie częściej „dík” od angielskiego „dictionary”.",
 "",
 [("Sprawdzam w słowniku.", "phǒm pòoet dík duu khráp", "ผมเปิดดิกดูครับ"),
  ("Masz słownik?", "mii dík mǎi khráp", "มีดิกไหมครับ")],
 ["słowo", "uczyć się", "tłumaczyć"], []),

("A2", "egzamin", "kaan sàwp", "การสอบ", PN, "Szkoła", 3, "n",
 "„sàwp phàan” to zdać, „sàwp tòk” to oblać — dosłownie „egzamin spadł”.",
 "czynność egzaminować",
 [("Jutro mam egzamin.", "phrûng-níi phǒm mii sàwp khráp", "พรุ่งนี้ผมมีสอบครับ"),
  ("Zdałem egzamin.", "phǒm sàwp phàan láew khráp", "ผมสอบผ่านแล้วครับ")],
 ["uczyć się", "zdawać egzamin", "trudny"], []),

# ============================================================ SKLEP
("A2", "targ", "tà-làat", "ตลาด", ZP, "Sklep", 5, "n",
 "„tà-làat nát” to targ okresowy, „tà-làat nám” to targ na wodzie. Na targu ceny są negocjowalne, w sklepie sieciowym nie.",
 "",
 [("Idę na targ.", "phǒm pai tà-làat khráp", "ผมไปตลาดครับ"),
  ("Na targu jest taniej.", "thîi tà-làat thùuk kwàa khráp", "ที่ตลาดถูกกว่าครับ")],
 ["sklep", "targować się", "tani"], []),

("A2", "sklep spożywczy", "ráan cham", "ร้านชำ", ZP, "Sklep", 3, "n",
 "Mały sklepik osiedlowy. „ráan sà-dùak sûe” to sklep całodobowy typu 7-Eleven.",
 "sklep towary",
 [("Kupię w sklepiku.", "phǒm súe thîi ráan cham khráp", "ผมซื้อที่ร้านชำครับ"),
  ("Sklep całodobowy jest na rogu.", "ráan sà-dùak sûe yùu hǔa mum khráp", "ร้านสะดวกซื้ออยู่หัวมุมครับ")],
 ["sklep", "targ", "kupować"], []),

("A2", "kasa", "khaao-tôoe", "เคาน์เตอร์", ZP, "Sklep", 3, "n",
 "Zapożyczenie „counter”. „jàai thîi khaao-tôoe” — płaci się przy ladzie.",
 "",
 [("Proszę zapłacić przy kasie.", "jàai thîi khaao-tôoe khráp", "จ่ายที่เคาน์เตอร์ครับ"),
  ("Przy kasie jest kolejka.", "thîi khaao-tôoe khon yóe khráp", "ที่เคาน์เตอร์คนเยอะครับ")],
 ["płacić", "kolejka", "paragon"], ["lada"]),

("A2", "paragon", "bai sèt", "ใบเสร็จ", ZP, "Sklep", 3, "n",
 "„bai” to klasyfikator kartek. „bai sèt ráp ngoen” to pełna forma.",
 "arkusz zakończony",
 [("Poproszę paragon.", "khǎw bai sèt khráp", "ขอใบเสร็จครับ"),
  ("Zgubiłem paragon.", "phǒm tham bai sèt hǎai khráp", "ผมทำใบเสร็จหายครับ")],
 ["płacić", "kasa", "zwrot"], []),

("A2", "kolejka", "khiu", "คิว", ZP, "Sklep", 3, "n",
 "Zapożyczenie „queue”. „tàw khiu” — stanąć w kolejce, „jawng khiu” — zarezerwować miejsce w kolejce.",
 "",
 [("Proszę stanąć w kolejce.", "tàw khiu khráp", "ต่อคิวครับ"),
  ("Kolejka jest długa.", "khiu yaao khráp", "คิวยาวครับ")],
 ["kasa", "czekać", "długi"], []),

("A2", "wyprzedaż", "lót raa-khaa", "ลดราคา", ZP, "Sklep", 4, "n",
 "Dosłownie „obniżyć cenę”. Na szyldach częste „sêel” od angielskiego „sale”.",
 "zmniejszać cena",
 [("Jest wyprzedaż.", "kam-lang lót raa-khaa khráp", "กำลังลดราคาครับ"),
  ("Czy będzie zniżka?", "lót raa-khaa dâai mǎi khráp", "ลดราคาได้ไหมครับ")],
 ["cena", "tani", "targować się"], ["zniżka"]),

("A2", "reklamówka", "thǔng", "ถุง", ZP, "Sklep", 4, "n",
 "Samo „thǔng” wystarcza w sklepie. Od 2020 roku darmowych reklamówek zwykle nie ma.",
 "",
 [("Nie potrzebuję reklamówki.", "mâi ao thǔng khráp", "ไม่เอาถุงครับ"),
  ("Poproszę reklamówkę.", "khǎw thǔng nòi khráp", "ขอถุงหน่อยครับ")],
 ["plastik", "torebka", "kupować"], []),

("A2", "zwrot towaru", "khuen sǐn kháa", "คืนสินค้า", ZP, "Sklep", 2, "f",
 "„khuen” znaczy zwracać — to samo słowo w „khuen ngoen” (zwrot pieniędzy).",
 "zwracać towar",
 [("Czy mogę zwrócić towar?", "khuen sǐn kháa dâai mǎi khráp", "คืนสินค้าได้ไหมครับ"),
  ("Proszę o zwrot pieniędzy.", "khǎw khuen ngoen khráp", "ขอคืนเงินครับ")],
 ["paragon", "zwracać", "wymieniać"], []),
]
