# -*- coding: utf-8 -*-
"""Leksyka etapu 6 — zwroty podrozne i zwroty uzywane w uslugach.

Zakres: lotnisko i przyloty, dworzec i bilety, taksowka i wynajem, hotel
w praktyce, restauracja poza zamawianiem, sklep i targ, fryzjer, pralnia,
warsztat, poczta, bank przy okienku.

Krotka: (poziom, polski, fonetyka, tajski, kategoria, podkategoria, typ,
         freq, rejestr, notatka, znaczenie doslowne, przyklad)
"""

TRAVEL = [

# =====================================================================
# LOTNISKO, DWORZEC, BILETY
# =====================================================================
("A2", "bilet w jedną stronę", "tǔa thîao diao", "ตั๋วเที่ยวเดียว", "Transport", "Bilety", "noun", 4, "n",
 "„thîao” to jeden przejazd albo wycieczka. Bilet powrotny to „tǔa pai klàp”.", "bilet podróż jedna",
 ("Poproszę bilet w jedną stronę.", "khǎw tǔa thîao diao nùeng bai khráp", "ขอตั๋วเที่ยวเดียวหนึ่งใบครับ")),
("A2", "bilet powrotny", "tǔa pai klàp", "ตั๋วไปกลับ", "Transport", "Bilety", "noun", 4, "n",
 "Dosłownie „bilet iść wrócić”. Tajski opisuje trasę, nie typ biletu.", "bilet iść wrócić",
 ("Poproszę bilet powrotny na jutro.", "khǎw tǔa pai klàp sǎm-ràp phrûng-níi khráp", "ขอตั๋วไปกลับสำหรับพรุ่งนี้ครับ")),
("A2", "o której odjeżdża?", "àwk kìi mohng", "ออกกี่โมง", "Transport", "Rozkład", "question", 5, "n",
 "„àwk” = wyruszać, „thǔeng” = przyjeżdżać. Ta para wystarczy do całego rozkładu.", "wyjechać ile godzina",
 ("O której odjeżdża autobus?", "rót àwk kìi mohng khráp", "รถออกกี่โมงครับ")),
("A2", "o której przyjeżdża?", "thǔeng kìi mohng", "ถึงกี่โมง", "Transport", "Rozkład", "question", 5, "n",
 "„thǔeng” dotyczy dotarcia do celu — także w zdaniu „maa thǔeng láew” (już dotarłem).", "dojść ile godzina",
 ("O której będziemy na miejscu?", "thǔeng kìi mohng khráp", "ถึงกี่โมงครับ")),
("A2", "ile trwa podróż?", "chái wee-laa kìi chûa-mohng", "ใช้เวลากี่ชั่วโมง", "Transport", "Rozkład", "question", 4, "n",
 "„chái wee-laa” dosłownie „używać czasu” — standardowe pytanie o czas trwania.", "używać czas ile godzin",
 ("Ile trwa jazda do Ayutthai?", "pai à-yút-thá-yaa chái wee-laa kìi chûa-mohng khráp", "ไปอยุธยาใช้เวลากี่ชั่วโมงครับ")),
("A2", "z którego peronu?", "chaan chá-laa nǎi", "ชานชาลาไหน", "Transport", "Dworzec", "question", 3, "f",
 "Na dworcu kolejowym. Na dworcu autobusowym pyta się o „châwng” (stanowisko).", "peron który",
 ("Z którego peronu odjeżdża?", "àwk chaan chá-laa nǎi khráp", "ออกชานชาลาไหนครับ")),
("A2", "gdzie odbiór bagażu?", "ráp krà-pǎo thîi nǎi", "รับกระเป๋าที่ไหน", "Transport", "Lotnisko", "question", 3, "n",
 "„ráp krà-pǎo” to odbiór walizek z taśmy.", "odebrać walizka gdzie",
 ("Gdzie odbiera się bagaż?", "ráp krà-pǎo thîi nǎi khráp", "รับกระเป๋าที่ไหนครับ")),
("A2", "mój bagaż nie dotarł", "krà-pǎo phǒm mâi maa", "กระเป๋าผมไม่มา", "Awarie i pomoc", "Lotnisko", "phrase", 3, "n",
 "Zdanie otwierające zgłoszenie w biurze bagażu. Potem podaj numer lotu.", "walizka moja nie przyjść",
 ("Moja walizka nie przyleciała.", "krà-pǎo phǒm mâi maa kàp thîao bin khráp", "กระเป๋าผมไม่มากับเที่ยวบินครับ")),
("A2", "gdzie jest wyjście?", "thaang àwk yùu thîi nǎi", "ทางออกอยู่ที่ไหน", "Miejsca i orientacja", "Orientacja", "question", 4, "n",
 "„thaang àwk” to wyjście, „thaang khâo” wejście. Widnieje na wszystkich tablicach.", "droga wyjść być gdzie",
 ("Gdzie jest wyjście?", "thaang àwk yùu thîi nǎi khráp", "ทางออกอยู่ที่ไหนครับ")),
("B1", "przesiadka", "tàw rót", "ต่อรถ", "Transport", "Trasa", "phrase", 3, "n",
 "„tàw” = kontynuować. Przesiadka na samolot to „tàw khrûeang”.", "kontynuować pojazd",
 ("Muszę się przesiąść w Chiang Mai.", "phǒm tâwng tàw rót thîi chiang mài khráp", "ผมต้องต่อรถที่เชียงใหม่ครับ")),

# =====================================================================
# TAKSOWKA I WYNAJEM
# =====================================================================
("A2", "proszę włączyć taksometr", "kòt mí-tôoe dûai khráp", "กดมิเตอร์ด้วยครับ", "Transport", "Taksówka", "phrase", 5, "n",
 "Kluczowe zdanie w Bangkoku. Powiedziane od razu przy wsiadaniu oszczędza negocjacji.", "nacisnąć taksometr też",
 ("Proszę włączyć licznik.", "kòt mí-tôoe dûai ná khráp", "กดมิเตอร์ด้วยนะครับ")),
("A2", "ile będzie kosztować?", "thâo rài khráp", "เท่าไหร่ครับ", "Zakupy i pieniądze", "Cena", "question", 5, "n",
 "Najkrótsze pytanie o cenę. Zawsze z „khráp/khâ”.", "ile",
 ("Ile to będzie kosztować?", "pai thǔeng thîi nân thâo rài khráp", "ไปถึงที่นั่นเท่าไหร่ครับ")),
("A2", "proszę tu skręcić w lewo", "líao sáai trong níi", "เลี้ยวซ้ายตรงนี้", "Transport", "Kierunki", "phrase", 4, "n",
 "„líao sáai / khwǎa” to skręt w lewo i prawo — dwa słowa wystarczą do nawigacji.", "skręcić lewo tutaj",
 ("Proszę skręcić tu w lewo.", "líao sáai trong níi khráp", "เลี้ยวซ้ายตรงนี้ครับ")),
("A2", "proszę jechać prosto", "trong pai", "ตรงไป", "Transport", "Kierunki", "phrase", 4, "n",
 "„trong pai rûeai rûeai” = cały czas prosto.", "prosto iść",
 ("Proszę jechać cały czas prosto.", "trong pai rûeai rûeai khráp", "ตรงไปเรื่อยๆ ครับ")),
("A2", "wynająć skuter", "châo rót maw-tôoe-sai", "เช่ารถมอเตอร์ไซค์", "Transport", "Wynajem", "phrase", 4, "n",
 "„châo” dotyczy wynajmu wszystkiego: pokoju, samochodu, roweru.", "wynająć pojazd motocykl",
 ("Chciałbym wynająć skuter na dzień.", "khǎw châo rót maw-tôoe-sai nùeng wan khráp", "ขอเช่ารถมอเตอร์ไซค์หนึ่งวันครับ")),
("B1", "czy w cenie jest ubezpieczenie?", "ruam prà-kan mǎi", "รวมประกันไหม", "Transport", "Wynajem", "question", 3, "n",
 "„ruam” = wliczone. Pytanie warte zadania przed każdym podpisem.", "wliczyć ubezpieczenie czy",
 ("Czy ubezpieczenie jest wliczone?", "raa-khaa níi ruam prà-kan mǎi khráp", "ราคานี้รวมประกันไหมครับ")),
("B1", "potrzebuję kasku", "khǎw mùak kan náwk", "ขอหมวกกันน็อค", "Transport", "Wynajem", "phrase", 3, "n",
 "W Tajlandii kask jest obowiązkowy także dla pasażera; policja to kontroluje.", "proszę czapka chronić uderzenie",
 ("Poproszę dwa kaski.", "khǎw mùak kan náwk sǎwng bai khráp", "ขอหมวกกันน็อคสองใบครับ")),

# =====================================================================
# HOTEL W PRAKTYCE
# =====================================================================
("A2", "o której jest wymeldowanie?", "chék-áo kìi mohng", "เช็คเอาท์กี่โมง", "Hotel", "Doba hotelowa", "question", 4, "n",
 "Zapożyczenia „chék-in / chék-áo” są w Tajlandii powszechne także poza turystyką.", "wymeldować ile godzina",
 ("O której trzeba się wymeldować?", "chék-áo kìi mohng khráp", "เช็คเอาท์กี่โมงครับ")),
("A2", "czy mogę zostawić bagaż?", "fàak krà-pǎo dâai mǎi", "ฝากกระเป๋าได้ไหม", "Hotel", "Bagaż", "question", 4, "n",
 "„fàak” to powierzyć na przechowanie — hotele robią to zwykle bez opłaty.", "powierzyć walizka móc czy",
 ("Czy mogę zostawić bagaż do wieczora?", "fàak krà-pǎo thǔeng tawn yen dâai mǎi khráp", "ฝากกระเป๋าถึงตอนเย็นได้ไหมครับ")),
("A2", "poproszę o późniejsze wymeldowanie", "khǎw chék-áo sǎai nòi", "ขอเช็คเอาท์สายหน่อย", "Hotel", "Doba hotelowa", "phrase", 3, "n",
 "„sǎai” znaczy „późno” o porze dnia; „cháa” to „powoli”.", "proszę wymeldować późno trochę",
 ("Czy mogę wymeldować się później?", "khǎw chék-áo sǎai nòi dâai mǎi khráp", "ขอเช็คเอาท์สายหน่อยได้ไหมครับ")),
("A2", "nie ma ciepłej wody", "mâi mii náam ùn", "ไม่มีน้ำอุ่น", "Hotel", "Reklamacje", "phrase", 4, "n",
 "„náam ùn” to woda ciepła; „náam ráwn” to wrzątek.", "nie mieć woda ciepła",
 ("W pokoju nie ma ciepłej wody.", "nai hâwng mâi mii náam ùn khráp", "ในห้องไม่มีน้ำอุ่นครับ")),
("A2", "proszę o dodatkowy ręcznik", "khǎw phâa chét tua phôoem", "ขอผ้าเช็ดตัวเพิ่ม", "Hotel", "Pokój", "phrase", 3, "n",
 "„phôoem” = więcej, dodatkowo. Działa z każdą prośbą o dokładkę.", "proszę ręcznik dodać",
 ("Poproszę jeszcze jeden ręcznik.", "khǎw phâa chét tua phôoem ìik phǔen khráp", "ขอผ้าเช็ดตัวเพิ่มอีกผืนครับ")),
("B1", "czy można zmienić pokój?", "plìan hâwng dâai mǎi", "เปลี่ยนห้องได้ไหม", "Hotel", "Reklamacje", "question", 3, "n",
 "Prośba, nie żądanie — dodaj powód, żeby nie zabrzmieć roszczeniowo.", "zmienić pokój móc czy",
 ("Czy można zmienić pokój na cichszy?", "plìan hâwng pen hâwng thîi ngîap kwàa dâai mǎi khráp", "เปลี่ยนห้องเป็นห้องที่เงียบกว่าได้ไหมครับ")),
("B1", "czy śniadanie jest wliczone?", "ruam aa-hǎan cháo mǎi", "รวมอาหารเช้าไหม", "Hotel", "Doba hotelowa", "question", 4, "n",
 "Pytanie warte zadania przy meldowaniu — ceny często podaje się bez śniadania.", "wliczyć jedzenie rano czy",
 ("Czy w cenie jest śniadanie?", "raa-khaa níi ruam aa-hǎan cháo mǎi khráp", "ราคานี้รวมอาหารเช้าไหมครับ")),

# =====================================================================
# RESTAURACJA POZA ZAMAWIANIEM
# =====================================================================
("A2", "na wynos", "sài thǔng", "ใส่ถุง", "Restauracja", "Na wynos", "phrase", 5, "n",
 "Dosłownie „włożyć do torby”. Bardziej naturalne niż kalka „tèek à-wee”.", "włożyć torba",
 ("Poproszę na wynos.", "sài thǔng dûai khráp", "ใส่ถุงด้วยครับ")),
("A2", "na miejscu", "kin thîi nîi", "กินที่นี่", "Restauracja", "Na wynos", "phrase", 4, "n",
 "Odpowiedź na standardowe pytanie sprzedawcy „thîi nîi rǔe klàp bâan”.", "jeść tutaj",
 ("Zjem na miejscu.", "kin thîi nîi khráp", "กินที่นี่ครับ")),
("A2", "bez lodu", "mâi sài náam khǎeng", "ไม่ใส่น้ำแข็ง", "Restauracja", "Napoje", "phrase", 4, "n",
 "„mâi sài …” to uniwersalna formuła wykluczania składników.", "nie włożyć woda twarda",
 ("Poproszę bez lodu.", "mâi sài náam khǎeng khráp", "ไม่ใส่น้ำแข็งครับ")),
("A2", "bez cukru", "mâi sài náam-taan", "ไม่ใส่น้ำตาล", "Restauracja", "Napoje", "phrase", 4, "n",
 "W Tajlandii napoje domyślnie są słodzone — bez tego zdania dostaniesz cukier.", "nie włożyć cukier",
 ("Poproszę bez cukru.", "mâi sài náam-taan khráp", "ไม่ใส่น้ำตาลครับ")),
("A2", "jestem uczulony na orzeszki", "phǒm pháe thùa", "ผมแพ้ถั่ว", "Zdrowie", "Alergie", "phrase", 4, "n",
 "„pháe” to alergia. Zdanie ratuje zdrowie — warto je umieć bez namysłu.", "ja alergia orzech",
 ("Jestem uczulony na orzeszki ziemne.", "phǒm pháe thùa lí-sǒng khráp", "ผมแพ้ถั่วลิสงครับ")),
("A2", "nie jem mięsa", "phǒm mâi kin núea sàt", "ผมไม่กินเนื้อสัตว์", "Restauracja", "Dieta", "phrase", 4, "n",
 "„núea sàt” obejmuje wszystkie mięsa. Sam „núea” to zwykle wołowina.", "ja nie jeść mięso zwierzę",
 ("Nie jem mięsa, poproszę coś warzywnego.", "phǒm mâi kin núea sàt khǎw à-rai thîi pen phàk khráp", "ผมไม่กินเนื้อสัตว์ ขออะไรที่เป็นผักครับ")),
("A2", "poproszę rachunek", "khǎw bin", "ขอบิล", "Restauracja", "Płatność", "phrase", 5, "n",
 "„khǎw bin” albo „chék bin” — oba są zrozumiałe wszędzie.", "proszę rachunek",
 ("Poproszę rachunek.", "khǎw bin dûai khráp", "ขอบิลด้วยครับ")),
("A2", "czy można płacić kartą?", "jàai bàt dâai mǎi", "จ่ายบัตรได้ไหม", "Zakupy i pieniądze", "Płatności", "question", 4, "n",
 "Na targach i w małych barach zwykle nie — warto zapytać zawczasu.", "płacić karta móc czy",
 ("Czy przyjmujecie karty?", "thîi nîi jàai bàt dâai mǎi khráp", "ที่นี่จ่ายบัตรได้ไหมครับ")),
("B1", "to nie jest to, co zamawiałem", "mâi châi thîi phǒm sàng khráp", "ไม่ใช่ที่ผมสั่งครับ", "Restauracja", "Reklamacje", "phrase", 3, "n",
 "Spokojne stwierdzenie faktu. Podniesiony głos w Tajlandii szkodzi sprawie.", "nie jest co ja zamówić",
 ("Chyba to nie moje zamówienie.", "an níi mâi châi thîi phǒm sàng ná khráp", "อันนี้ไม่ใช่ที่ผมสั่งนะครับ")),
("B1", "rachunek chyba się nie zgadza", "bin nâa jà mâi thùuk", "บิลน่าจะไม่ถูก", "Restauracja", "Reklamacje", "phrase", 3, "n",
 "„nâa jà” łagodzi zarzut do przypuszczenia — kluczowe dla zachowania twarzy obu stron.", "rachunek pewnie nie poprawny",
 ("Rachunek chyba się nie zgadza.", "bin nâa jà mâi thùuk ná khráp chûai chék hâi nòi", "บิลน่าจะไม่ถูกนะครับ ช่วยเช็คให้หน่อย")),

# =====================================================================
# SKLEP I TARG
# =====================================================================
("A2", "tylko oglądam", "duu chǒoei chǒoei", "ดูเฉยๆ", "Zakupy i pieniądze", "W sklepie", "phrase", 4, "n",
 "Uprzejma odpowiedź sprzedawcy, gdy nie chcesz kupować. Nie brzmi odpychająco.", "patrzeć tylko",
 ("Dziękuję, tylko oglądam.", "khàwp khun khráp duu chǒoei chǒoei khráp", "ขอบคุณครับ ดูเฉยๆ ครับ")),
("A2", "czy jest większy rozmiar?", "mii sái yài kwàa mǎi", "มีไซส์ใหญ่กว่าไหม", "Zakupy i pieniądze", "Ubrania", "question", 4, "n",
 "„sái” to zapożyczone „size”; używa się go powszechnie.", "mieć rozmiar duży niż czy",
 ("Czy jest większy rozmiar?", "mii sái yài kwàa níi mǎi khráp", "มีไซส์ใหญ่กว่านี้ไหมครับ")),
("A2", "czy jest w innym kolorze?", "mii sǐi ùen mǎi", "มีสีอื่นไหม", "Zakupy i pieniądze", "Ubrania", "question", 3, "n",
 "„ùen” = inny. Działa z każdym rzeczownikiem: „bàep ùen”, „wan ùen”.", "mieć kolor inny czy",
 ("Czy jest w innym kolorze?", "mii sǐi ùen mǎi khráp", "มีสีอื่นไหมครับ")),
("A2", "trochę taniej, proszę", "lót nòi dâai mǎi", "ลดหน่อยได้ไหม", "Zakupy i pieniądze", "Targowanie", "phrase", 4, "i",
 "Na targu tak — w sklepie z cenami stałymi ta prośba wprawia sprzedawcę w zakłopotanie.", "obniżyć trochę móc czy",
 ("Da się trochę taniej?", "lót nòi dâai mǎi khráp", "ลดหน่อยได้ไหมครับ")),
("A2", "wezmę to", "ao an níi", "เอาอันนี้", "Zakupy i pieniądze", "W sklepie", "phrase", 5, "n",
 "„an” to uniwersalny klasyfikator dla drobnych przedmiotów.", "wziąć sztuka ta",
 ("Wezmę ten.", "ao an níi khráp", "เอาอันนี้ครับ")),
("A2", "poproszę paragon", "khǎw bai sèt", "ขอใบเสร็จ", "Zakupy i pieniądze", "Płatności", "phrase", 3, "n",
 "Potrzebny przy zwrocie i przy rozliczeniu firmowym.", "proszę arkusz skończony",
 ("Poproszę paragon.", "khǎw bai sèt dûai khráp", "ขอใบเสร็จด้วยครับ")),
("B1", "czy mogę to zwrócić?", "khuen khǎwng dâai mǎi", "คืนของได้ไหม", "Zakupy i pieniądze", "Reklamacje", "question", 3, "n",
 "Zwroty w Tajlandii bywają trudniejsze niż w Europie — zapytaj przed zakupem.", "zwrócić rzecz móc czy",
 ("Czy mogę to zwrócić w ciągu tygodnia?", "khuen khǎwng phaai nai nùeng aa-thít dâai mǎi khráp", "คืนของภายในหนึ่งอาทิตย์ได้ไหมครับ")),

# =====================================================================
# USLUGI: FRYZJER, PRALNIA, WARSZTAT, POCZTA
# =====================================================================
("A2", "proszę tylko podciąć", "tàt sân nòi diao", "ตัดสั้นนิดเดียว", "Praca i nauka", "Usługi", "phrase", 3, "n",
 "U fryzjera to zdanie ratuje przed nieoczekiwaną fryzurą.", "ciąć krótko odrobinę",
 ("Proszę tylko lekko podciąć.", "tàt sân nòi diao phaw ná khráp", "ตัดสั้นนิดเดียวพอนะครับ")),
("A2", "ile kosztuje pranie?", "sák phâa khít yang-ngai", "ซักผ้าคิดยังไง", "Praca i nauka", "Usługi", "question", 3, "n",
 "W pralniach liczy się zwykle za kilogram — „kì-loo lá thâo rài”.", "prać tkanina liczyć jak",
 ("Jak liczycie za pranie?", "sák phâa khít yang-ngai khráp", "ซักผ้าคิดยังไงครับ")),
("A2", "na kiedy będzie gotowe?", "sèt mûea rài", "เสร็จเมื่อไหร่", "Praca i nauka", "Usługi", "question", 4, "n",
 "Uniwersalne pytanie: pralnia, warsztat, krawiec, naprawa telefonu.", "skończyć kiedy",
 ("Na kiedy będzie gotowe?", "sèt mûea rài khráp", "เสร็จเมื่อไหร่ครับ")),
("B1", "czy da się to naprawić?", "sâwm dâai mǎi", "ซ่อมได้ไหม", "Awarie i pomoc", "Naprawy", "question", 3, "n",
 "„sâwm” brzmi identycznie jak „sâwm” (widelec), ale to inne słowo — rozróżnia je kontekst.", "naprawić móc czy",
 ("Czy da się to naprawić?", "an níi sâwm dâai mǎi khráp", "อันนี้ซ่อมได้ไหมครับ")),
("B1", "ile potrwa naprawa?", "sâwm chái wee-laa naan mǎi", "ซ่อมใช้เวลานานไหม", "Awarie i pomoc", "Naprawy", "question", 3, "n",
 "„naan mǎi” pyta o długość trwania, nie o konkretną godzinę.", "naprawić używać czas długo czy",
 ("Długo to potrwa?", "sâwm chái wee-laa naan mǎi khráp", "ซ่อมใช้เวลานานไหมครับ")),
("B1", "chcę wysłać paczkę do Polski", "sòng phát-sà-dù pai poo-laen", "ส่งพัสดุไปโปแลนด์", "Praca i nauka", "Poczta", "phrase", 3, "n",
 "„phát-sà-dù” to paczka pocztowa; list to „jòt-mǎai”.", "wysłać paczka iść Polska",
 ("Chcę wysłać paczkę do Polski.", "phǒm yàak sòng phát-sà-dù pai poo-laen khráp", "ผมอยากส่งพัสดุไปโปแลนด์ครับ")),
("B1", "ile to zajmie dni?", "kìi wan thǔeng", "กี่วันถึง", "Praca i nauka", "Poczta", "question", 3, "n",
 "Krótsze i naturalniejsze niż pełne zdanie z „chái wee-laa”.", "ile dni dojść",
 ("Ile dni idzie przesyłka?", "kìi wan thǔeng khráp", "กี่วันถึงครับ")),
("B1", "chcę wymienić pieniądze", "lâek ngoen", "แลกเงิน", "Zakupy i pieniądze", "Bank", "phrase", 4, "n",
 "„lâek” to wymienić jedno na drugie — także rozmienić banknot.", "wymienić pieniądze",
 ("Gdzie mogę wymienić pieniądze?", "lâek ngoen dâai thîi nǎi khráp", "แลกเงินได้ที่ไหนครับ")),
("B1", "jaki jest kurs?", "àt-traa lâek plìan thâo rài", "อัตราแลกเปลี่ยนเท่าไหร่", "Zakupy i pieniądze", "Bank", "question", 3, "f",
 "Formalne, ale w kantorze zrozumiałe wszędzie.", "stawka wymiana ile",
 ("Jaki jest dziś kurs?", "wan níi àt-traa lâek plìan thâo rài khráp", "วันนี้อัตราแลกเปลี่ยนเท่าไหร่ครับ")),
("B1", "proszę o drobne", "khǎw ngoen yâwi", "ขอเงินย่อย", "Zakupy i pieniądze", "Bank", "phrase", 3, "n",
 "Drobne są w Tajlandii bardzo przydatne — taksówkarze rzadko mają wydać z tysiąca.", "proszę pieniądze drobne",
 ("Poproszę drobne banknoty.", "khǎw ngoen yâwi dûai khráp", "ขอเงินย่อยด้วยครับ")),
]
