# -*- coding: utf-8 -*-
"""Sesja N, partia czwarta — UCZUCIA, CHARAKTER, POJĘCIA ABSTRAKCYJNE.

Baza opisywała stany ciała (zmęczony, głodny, chory) znacznie lepiej niż
stany umysłu. Tymczasem w tajskim to właśnie ta warstwa ma najgęstszą
strukturę: dziesiątki wyrażeń budowanych na rdzeniu „jai” (serce), z których
każde znaczy co innego, a żadnego nie da się zgadnąć ze składników.

Rodzina „jai” jest tu potraktowana jako całość, bo tylko jako całość ma sens:
jai dii to życzliwy, jai ráwn niecierpliwy, jai yen opanowany, sǐa jai
zasmucony, dii jai ucieszony, tòk jai przestraszony, nói jai urażony,
tâng jai skupiony. Kto zna sam wyraz „jai”, nie odgadnie żadnego z nich.

Krotka: (poziom, polski, fonetyka, pismo, podkategoria, częstość, typ,
         kategoria, uwaga, dosłownie)
"""

CO = "Cechy i opinie"
ST = "Small talk"
LR = "Ludzie i rodzina"
PN = "Praca i nauka"
ZD = "Zdrowie"

MIND = [

# ============================================================ RODZINA "JAI"
("A2", "ucieszony, zadowolony", "dii jai", "ดีใจ", "Uczucia", 5, "adj", CO,
 "Dosłownie „dobre serce” — ale znaczy „cieszę się”, nie „jestem życzliwy”. Tym drugim jest jai dii, z odwróconym szykiem.", "dobry serce"),
("A2", "zasmucony", "sǐa jai", "เสียใจ", "Uczucia", 5, "adj", CO,
 "Dosłownie „zepsute serce”. Także formuła kondolencji.", "psuć serce"),
("A2", "urażony, dotknięty", "nói jai", "น้อยใจ", "Uczucia", 4, "adj", CO,
 "Dosłownie „mało serca”. Uczucie bez dobrego polskiego odpowiednika: żal do kogoś, że o nas nie pomyślał.", "mało serce"),
("A2", "skupiony, uważny", "tâng jai", "ตั้งใจ", "Uczucia", 5, "adj", CO,
 "Także „zamierzać, robić celowo”: tâng jai tham.", "ustanawiać serce"),
("A2", "szczery, otwarty", "jai jing", "ใจจริง", "Uczucia", 3, "adj", CO,
 "", "serce prawdziwy"),
("A2", "odważny", "jai klâa", "ใจกล้า", "Uczucia", 3, "adj", CO,
 "klâa to śmiały.", "serce śmiały"),
("A2", "tchórzliwy", "jai sǐa", "ใจเสีย", "Uczucia", 2, "adj", CO,
 "Uwaga na szyk: jai sǐa to stracić odwagę, sǐa jai to zasmucić się.", "serce psuć"),
("A2", "wielkoduszny, gotów wydać", "jai kwâang", "ใจกว้าง", "Uczucia", 3, "adj", CO,
 "Dosłownie „szerokie serce”.", "serce szeroki"),
("A2", "małostkowy", "jai khâep", "ใจแคบ", "Uczucia", 2, "adj", CO,
 "khâep to wąski.", "serce wąski"),
("A2", "twardy, bezlitosny", "jai dam", "ใจดำ", "Uczucia", 2, "adj", CO,
 "Dosłownie „czarne serce”.", "serce czarny"),
("A2", "miękkiego serca, ustępliwy", "jai àwn", "ใจอ่อน", "Uczucia", 3, "adj", CO,
 "àwn to miękki, słaby.", "serce miękki"),
("A2", "roztargniony", "jai lawi", "ใจลอย", "Uczucia", 3, "adj", CO,
 "Dosłownie „serce unosi się”.", "serce unosić się"),
("A2", "spieszący się, niecierpliwy w działaniu", "jai rew", "ใจเร็ว", "Uczucia", 2, "adj", CO,
 "", "serce szybki"),
("A2", "ulżyło mi", "baw jai", "เบาใจ", "Uczucia", 3, "adj", CO,
 "bao to lekki.", "lekki serce"),
("A2", "przygnębiony", "nàk jai", "หนักใจ", "Uczucia", 3, "adj", CO,
 "Dosłownie „ciężkie serce” — o zmartwieniu, nie o smutku.", "ciężki serce"),
("A2", "zainteresowany", "sǒn jai", "สนใจ", "Uczucia", 5, "v", CO,
 "Dosłownie „nawlekać serce”.", "nawlekać serce"),
("A2", "zrozumieć opacznie", "khâo jai phìt", "เข้าใจผิด", "Uczucia", 4, "v", CO,
 "Bardzo przydatne przy nieporozumieniu.", "wchodzić serce błędny"),
("A2", "dogadzać komuś, ustępować", "taam jai", "ตามใจ", "Uczucia", 3, "v", CO,
 "Samo „taam jai” znaczy też „rób, jak chcesz”.", "podążać serce"),
("A2", "zapamiętać, wziąć do siebie", "jam jai", "จำใจ", "Uczucia", 2, "v", CO,
 "Znaczy „robić coś wbrew sobie” — nie „zapamiętać”. Pułapka dla uczącego się.", "pamiętać serce"),

# ============================================================ UCZUCIA
("A2", "radość", "khwaam sùk", "ความสุข", "Uczucia", 5, "n", ST,
 "sùk to szczęście jako stan. Życzenie: khǎw hâi mii khwaam sùk.", "stan szczęście"),
("A2", "smutek", "khwaam sâo", "ความเศร้า", "Uczucia", 3, "n", ST,
 "sâo to smutny.", "stan smutny"),
("A2", "strach", "khwaam klua", "ความกลัว", "Uczucia", 4, "n", ST,
 "klua to bać się — bardzo częsty czasownik.", "stan bać się"),
("A2", "bać się", "klua", "กลัว", "Uczucia", 5, "v", ST,
 "klua mâak — bardzo się boję. Zbitka kl- bez przydechu.", ""),
("A2", "złość, gniew", "khwaam kròot", "ความโกรธ", "Uczucia", 3, "n", ST,
 "", "stan zły"),
("A2", "ulga", "khwaam lòng", "ความโล่ง", "Uczucia", 2, "n", ST,
 "lòng to przestronny, wolny od ciężaru.", "stan przestronny"),
("A2", "nadzieja", "khwaam wǎng", "ความหวัง", "Uczucia", 4, "n", ST,
 "", "stan mieć nadzieję"),
("A2", "tęsknota", "khwaam khít thǔeng", "ความคิดถึง", "Uczucia", 3, "n", ST,
 "", "stan myśleć aż do"),
("A2", "miłość", "khwaam rák", "ความรัก", "Uczucia", 4, "n", ST,
 "", "stan kochać"),
("A2", "nienawiść", "khwaam klìat", "ความเกลียด", "Uczucia", 2, "n", ST,
 "klìat to nienawidzić.", "stan nienawidzić"),
("A2", "nienawidzić, nie znosić", "klìat", "เกลียด", "Uczucia", 3, "v", ST,
 "Mocne słowo — o jedzeniu raczej mâi châwp.", ""),
("A2", "zazdrość", "khwaam ìt-chǎa", "ความอิจฉา", "Uczucia", 2, "n", ST,
 "O zazdrość w związku: hǔeng.", "stan zazdrościć"),
("A2", "zazdrosny (w związku)", "hǔeng", "หึง", "Uczucia", 3, "adj", ST,
 "Osobne słowo od ìt-chǎa — tajski rozróżnia te dwie zazdrości.", ""),
("A2", "wstyd", "khwaam aai", "ความอาย", "Uczucia", 3, "n", ST,
 "", "stan wstydzić się"),
("A2", "duma", "khwaam phuum jai", "ความภูมิใจ", "Uczucia", 3, "n", ST,
 "Znów jai — „grunt serca”.", "stan dumny"),
("A2", "cierpliwość", "khwaam òt thon", "ความอดทน", "Uczucia", 3, "n", ST,
 "òt thon to wytrzymywać, znosić — także o upale i o pracy.", "stan wytrzymywać"),
("A2", "wytrzymać, znieść", "òt thon", "อดทน", "Uczucia", 4, "v", ST,
 "", ""),
("A2", "cierpieć", "thúk", "ทุกข์", "Uczucia", 2, "v", ST,
 "Przeciwieństwo sùk. Uwaga: homofon z thúk (każdy), pisanym inaczej.", ""),
("A2", "współczuć, litować się", "sǒng-sǎan", "สงสาร", "Uczucia", 4, "v", ST,
 "Bardzo częste — także o zwierzęciu i o obcym człowieku.", ""),
("A2", "żałować", "sǐa daai", "เสียดาย", "Uczucia", 4, "v", ST,
 "O zmarnowanej okazji albo rzeczy. „Szkoda!” jako wykrzyknik.", "tracić szkoda"),
("A2", "cieszyć się z czegoś", "dii jai thîi", "ดีใจที่", "Uczucia", 4, "v", ST,
 "thîi wprowadza powód.", "cieszyć się że"),
("A2", "znudzić się czymś", "bùea", "เบื่อ", "Uczucia", 4, "v", ST,
 "bùea aa-hǎan — znudziło mi się to jedzenie. Także „mieć dość”.", ""),
("A2", "zaskoczyć się, zdziwić", "plàek jai", "แปลกใจ", "Uczucia", 3, "v", ST,
 "", "dziwny serce"),

# ============================================================ CHARAKTER
("A2", "uprzejmy, dobrze wychowany", "rîap ráwi", "เรียบร้อย", "Charakter", 4, "adj", CO,
 "Także „w porządku, gotowe” o sprawie. Komplement wobec kobiety.", "gładki porządny"),
("A2", "nieuczciwy", "mâi sûe sàt", "ไม่ซื่อสัตย์", "Charakter", 2, "adj", CO,
 "sûe to prosty, prawy.", "nie uczciwy"),
("A2", "uczciwy, prawy", "sûe sàt", "ซื่อสัตย์", "Charakter", 3, "adj", CO,
 "", ""),
("A2", "wierny, lojalny", "jong rák phák dii", "จงรักภักดี", "Charakter", 2, "adj", CO,
 "Formuła głównie o lojalności wobec kraju i monarchii.", "oddany kochać wierny"),
("A2", "odpowiedzialny", "mii khwaam ráp phìt châwp", "มีความรับผิดชอบ", "Charakter", 3, "adj", CO,
 "", "mieć odpowiedzialność"),
("A2", "punktualny", "trong tàw wee-laa", "ตรงต่อเวลา", "Charakter", 3, "adj", CO,
 "", "prosty wobec czas"),
("A2", "ambitny", "mii khwaam tâng jai sǔung", "มีความตั้งใจสูง", "Charakter", 2, "adj", CO,
 "", "mieć determinacja wysoki"),
("A2", "skromny", "thàwm tua", "ถ่อมตัว", "Charakter", 3, "adj", CO,
 "Cecha ceniona wyżej niż pewność siebie.", "uniżać ciało"),
("A2", "pewny siebie", "mân jai", "มั่นใจ", "Charakter", 4, "adj", CO,
 "mân to pewny, stabilny. Także „jestem pewien”.", "pewny serce"),
("A2", "niepewny, niezdecydowany", "mâi nâe jai", "ไม่แน่ใจ", "Charakter", 5, "adj", CO,
 "Bardzo częsta odpowiedź — łagodniejsza niż „nie wiem”.", "nie pewny serce"),
("A2", "wesoły, pogodny", "râa rooeng", "ร่าเริง", "Charakter", 3, "adj", CO,
 "", ""),
("A2", "poważny (o człowieku)", "jing jang", "จริงจัง", "Charakter", 3, "adj", CO,
 "", "prawdziwy mocno"),
("A2", "uparty", "dûe", "ดื้อ", "Charakter", 3, "adj", CO,
 "Częste o dzieciach i o sobie samym z przekąsem.", ""),
("A2", "gadatliwy", "phûut mâak", "พูดมาก", "Charakter", 4, "adj", CO,
 "Bywa zarzutem: „phûut mâak!” znaczy „za dużo gadasz”.", "mówić dużo"),
("A2", "cichy, małomówny", "phûut náwi", "พูดน้อย", "Charakter", 3, "adj", CO,
 "", "mówić mało"),
("A2", "towarzyski", "khâo kàp khon ngâai", "เข้ากับคนง่าย", "Charakter", 2, "adj", CO,
 "Dosłownie „łatwo wchodzi z ludźmi”.", "wchodzić z człowiek łatwy"),
("A2", "zabawny (o osobie)", "khon tà-lòk", "คนตลก", "Charakter", 3, "n", LR,
 "", "człowiek zabawny"),
("A2", "zdolny, kompetentny", "kèng", "เก่ง", "Charakter", 5, "adj", CO,
 "Najczęstsza pochwała: „kèng mâak!” — świetnie ci idzie.", ""),
("A2", "niezdarny", "sûm sâam", "ซุ่มซ่าม", "Charakter", 2, "adj", CO,
 "", ""),
("A2", "dokładny, staranny", "lá-ìat", "ละเอียด", "Charakter", 3, "adj", CO,
 "Także „drobno pokrojony” i „szczegółowy”.", ""),
("A2", "niedbały", "sà-phrâo", "สะเพร่า", "Charakter", 2, "adj", CO,
 "", ""),

# ============================================================ POJĘCIA
("B1", "prawda", "khwaam jing", "ความจริง", "Pojęcia", 4, "n", PN,
 "khwaam jing khue — prawda jest taka, że.", "stan prawdziwy"),
("B1", "kłamstwo", "kham koo-hòk", "คำโกหก", "Pojęcia", 3, "n", PN,
 "koo-hòk to kłamać.", "słowo kłamać"),
("B1", "kłamać", "koo-hòk", "โกหก", "Pojęcia", 3, "v", PN,
 "", ""),
("B1", "tajemnica", "khwaam láp", "ความลับ", "Pojęcia", 3, "n", PN,
 "láp to tajny.", "stan tajny"),
("B1", "cel", "pâo mǎai", "เป้าหมาย", "Pojęcia", 3, "n", PN,
 "pâo to tarcza.", "tarcza znak"),
("B1", "przyszłość", "à-naa-khót", "อนาคต", "Pojęcia", 3, "n", PN,
 "", ""),
("B1", "przeszłość", "à-dìit", "อดีต", "Pojęcia", 3, "n", PN,
 "Także „były”: à-dìit naa-yók.", ""),
("B1", "teraźniejszość", "pàt-jù-ban", "ปัจจุบัน", "Pojęcia", 3, "n", PN,
 "Także „obecnie” jako przysłówek.", ""),
("B1", "szansa, okazja", "oo-kàat", "โอกาส", "Pojęcia", 4, "n", PN,
 "mii oo-kàat — mieć okazję. Bardzo częste.", ""),
("B1", "wybór, możliwość", "thaang lûeak", "ทางเลือก", "Pojęcia", 3, "n", PN,
 "", "droga wybierać"),
("B1", "warunek", "ngûean khǎi", "เงื่อนไข", "Pojęcia", 3, "n", PN,
 "", ""),
("B1", "skutek uboczny", "phǒn kháang khiang", "ผลข้างเคียง", "Pojęcia", 2, "n", ZD,
 "Termin z ulotek lekowych.", "skutek strona boczny"),
("B1", "zaleta", "khâw dii", "ข้อดี", "Pojęcia", 4, "n", PN,
 "khâw- tworzy pary: khâw dii i khâw sǐa.", "punkt dobry"),
("B1", "wada", "khâw sǐa", "ข้อเสีย", "Pojęcia", 4, "n", PN,
 "", "punkt zły"),
("B1", "zmiana", "kaan plìan plaeng", "การเปลี่ยนแปลง", "Pojęcia", 3, "n", PN,
 "", "czynność zmieniać przekształcać"),
("B1", "rozwój, postęp", "kaan phát-thá-naa", "การพัฒนา", "Pojęcia", 3, "n", PN,
 "Słowo obecne w każdym oficjalnym komunikacie.", "czynność rozwijać"),
("B1", "doświadczyć, przeżyć", "prà-sòp", "ประสบ", "Pojęcia", 2, "v", PN,
 "prà-sòp kaan — doświadczenie.", ""),
("B1", "zależność, związek", "khwaam kìao khâwng", "ความเกี่ยวข้อง", "Pojęcia", 2, "n", PN,
 "", "stan dotyczyć"),
("B1", "przyczyna i skutek", "hèet lǽ phǒn", "เหตุและผล", "Pojęcia", 2, "n", PN,
 "hèet to powód, przyczyna.", "przyczyna i skutek"),
("B1", "znaczyć, mieć sens", "mii hèet phǒn", "มีเหตุผล", "Pojęcia", 3, "adj", PN,
 "Także „rozsądny” o człowieku.", "mieć przyczyna skutek"),
("B1", "bez sensu", "mâi mii hèet phǒn", "ไม่มีเหตุผล", "Pojęcia", 3, "adj", PN,
 "", "nie mieć przyczyna skutek"),
("B1", "poziom, stopień", "rá-dàp", "ระดับ", "Pojęcia", 4, "n", PN,
 "rá-dàp phaa-sǎa — poziom językowy.", ""),
("B1", "jakość a ilość", "prì-maan", "ปริมาณ", "Pojęcia", 3, "n", PN,
 "prì-maan to ilość; khun-ná-phâap to jakość.", ""),
("B1", "wartość", "khun-ná-khâa", "คุณค่า", "Pojęcia", 2, "n", PN,
 "Nie mylić z raa-khaa (cena).", ""),
("B1", "wpływać na coś", "mii phǒn tàw", "มีผลต่อ", "Pojęcia", 3, "v", PN,
 "", "mieć skutek wobec"),
("B1", "zależy to od", "khûen yùu kàp", "ขึ้นอยู่กับ", "Pojęcia", 4, "v", PN,
 "Dosłownie „wznosi się przy”.", "wznosić się przy"),
]
