# -*- coding: utf-8 -*-
"""Sesja N, partia szósta — WYRÓWNANIE ROZKŁADU.

Po pięciu partiach rozkład nowego materiału sam zaczął się przechylać: Praca
i nauka dostała 123 hasła, Restauracja 9. To jest dokładnie ten błąd, który
ta sesja miała naprawić — kategoria z 1 248 rekordami rosła najszybciej.

Ta partia jest więc dobrana odwrotnie do wygody pisania: celowo nie zawiera
ANI JEDNEGO hasła z kategorii Praca i nauka, Cechy i opinie ani Gramatyka
użytkowa. Idzie wyłącznie tam, gdzie po pięciu partiach wciąż było najciaśniej:
Restauracja, Hotel, Transport, Czas i daty, Zdrowie, Pytania, Podstawy,
Liczby, Jedzenie.

Krotka: (poziom, polski, fonetyka, pismo, podkategoria, częstość, typ,
         kategoria, uwaga, dosłownie)
"""

RE = "Restauracja"
HO = "Hotel"
TR = "Transport"
CD = "Czas i daty"
ZD = "Zdrowie"
PY = "Pytania"
PG = "Podstawy i grzeczność"
LI = "Liczby i liczenie"
JN = "Jedzenie i napoje"
PL = "Miejsca i orientacja"
AW = "Awarie i pomoc"

BALANCE = [

# ============================================================ RESTAURACJA
("A2", "obsługa (personel)", "kaan bàw-rí-kaan", "การบริการ", "Obsługa", 4, "n", RE,
 "bàw-rí-kaan to usługa. Napiwek zwykle nieobowiązkowy, bo doliczany bywa service charge.", "czynność usługa"),
("A2", "zamówienie", "aw-dôe", "ออร์เดอร์", "Zamawianie", 4, "n", RE,
 "Zapożyczenie; formalnie raai kaan sàng.", ""),
("A2", "kolejka (do stolika)", "khiu", "คิว", "Obsługa", 4, "n", RE,
 "Z angielskiego queue. Także kolejka w banku i na poczcie.", ""),
("A2", "bufet, szwedzki stół", "buf-fêe", "บุฟเฟ่ต์", "Zamawianie", 3, "n", RE,
 "Bardzo popularna formuła, zwłaszcza przy grillu mǔu krà-thá.", ""),
("A2", "grill przy stole", "mǔu krà-thá", "หมูกระทะ", "Potrawy", 3, "n", RE,
 "Dosłownie „wieprzowina z patelni”. Wieczorna instytucja towarzyska.", "wieprzowina patelnia"),
("A2", "danie dnia", "meun prà-jam wan", "เมนูประจำวัน", "Zamawianie", 3, "n", RE,
 "prà-jam to stały, regularny.", "menu stały dzień"),
("A2", "dokładka ryżu", "phôoem khâao", "เพิ่มข้าว", "Zamawianie", 4, "v", RE,
 "W wielu barach darmowa — wystarczy poprosić.", "dodawać ryż"),
("A2", "doprawić", "prung rót", "ปรุงรส", "Zamawianie", 3, "v", RE,
 "Na stole zwykle stoi zestaw czterech przypraw do samodzielnego doprawiania.", "przyrządzać smak"),
("A2", "dolać, dopełnić", "toem", "เติม", "Zamawianie", 4, "v", RE,
 "Ten sam czasownik co przy doładowaniu telefonu i tankowaniu.", ""),
("A2", "kubek", "kâew nám", "แก้วน้ำ", "Nakrycie", 4, "n", RE,
 "", "szklanka woda"),
("A2", "dzbanek", "yùeak", "เหยือก", "Nakrycie", 2, "n", RE,
 "", ""),
("A2", "taca", "thàat", "ถาด", "Nakrycie", 3, "n", RE,
 "W barach samoobsługowych podstawowe naczynie.", ""),
("A2", "obrus", "phâa puu tó", "ผ้าปูโต๊ะ", "Nakrycie", 2, "n", RE,
 "Znów puu — rozkładać.", "tkanina rozkładać stół"),
("A2", "popielniczka", "thîi khìa bù-rìi", "ที่เขี่ยบุหรี่", "Nakrycie", 2, "n", RE,
 "Palenie w lokalach zamkniętych zakazane.", "narzędzie strząsać papieros"),
("A2", "stolik na zewnątrz", "tó khâang nâwk", "โต๊ะข้างนอก", "Obsługa", 3, "n", RE,
 "", "stół strona zewnątrz"),
("A2", "sala z klimatyzacją", "hâwng ae", "ห้องแอร์", "Obsługa", 4, "n", RE,
 "Realna różnica w cenie i w komforcie.", "pokój klimatyzacja"),
("A2", "zapakować resztki", "hàw klàp bâan", "ห่อกลับบ้าน", "Płacenie", 3, "v", RE,
 "Naturalne i oczekiwane — nikogo nie dziwi.", "pakować wracać dom"),
("A2", "opłata serwisowa", "khâa bàw-rí-kaan", "ค่าบริการ", "Płacenie", 3, "n", RE,
 "Zwykle 10 procent, w lokalach hotelowych doliczana automatycznie.", "opłata usługa"),
("A2", "podzielić rachunek", "hǎan khrûeng", "หารครึ่ง", "Płacenie", 3, "v", RE,
 "hǎan to dzielić — działanie matematyczne użyte dosłownie.", "dzielić połowa"),

# ============================================================ HOTEL
("A2", "pokój rodzinny", "hâwng khrâwp khrua", "ห้องครอบครัว", "Rodzaje pokoi", 3, "n", HO,
 "khrâwp khrua to rodzina jako gospodarstwo domowe.", "pokój rodzina"),
("A2", "rodzina (gospodarstwo)", "khrâwp khrua", "ครอบครัว", "Rodzaje pokoi", 5, "n", HO,
 "Szersze niż phâw mâe — obejmuje wszystkich pod jednym dachem.", ""),
("A2", "dostawka (łóżko)", "tiang sòoem", "เตียงเสริม", "Wyposażenie", 2, "n", HO,
 "sòoem to dokładać, wzmacniać.", "łóżko dodatkowy"),
("A2", "budzenie na telefon", "bàw-rí-kaan plùk", "บริการปลุก", "Obsługa", 2, "n", HO,
 "plùk to budzić kogoś — inne słowo niż tùen (budzić się).", "usługa budzić"),
("A2", "nie przeszkadzać", "hâam róp-kuan", "ห้ามรบกวน", "Obsługa", 3, "w", HO,
 "Napis na zawieszce. hâam to zakaz.", "zakaz przeszkadzać"),
("A2", "zapasowy klucz", "kun-jae sǎm-rawng", "กุญแจสำรอง", "Wyposażenie", 2, "n", HO,
 "sǎm-rawng to zapasowy, rezerwowy.", "klucz zapasowy"),
("A2", "wymiana ręczników", "plìan phâa chét tua", "เปลี่ยนผ้าเช็ดตัว", "Obsługa", 2, "v", HO,
 "", "zmieniać ręcznik"),
("A2", "hałas z sąsiedniego pokoju", "sǐang jàak hâwng khâang", "เสียงจากห้องข้าง", "Obsługa", 2, "n", HO,
 "jàak to „z, od”.", "dźwięk z pokój obok"),
("A2", "przedłużyć pobyt", "tàw hâwng", "ต่อห้อง", "Rezerwacja", 3, "v", HO,
 "Znów tàw — przedłużać. Ten sam czasownik co przy wizie.", "przedłużać pokój"),
("A2", "wcześniejsze zameldowanie", "khâo hâwng kàwn wee-laa", "เข้าห้องก่อนเวลา", "Rezerwacja", 3, "n", HO,
 "Bywa płatne, warto zapytać z góry.", "wchodzić pokój przed czas"),
("A2", "widok na ogród", "wiu sǔan", "วิวสวน", "Rodzaje pokoi", 2, "n", HO,
 "", "widok ogród"),
("A2", "pensjonat, kwatera", "kèt háo", "เกสต์เฮาส์", "Rodzaje pokoi", 4, "n", HO,
 "Tańsza i częstsza forma noclegu niż roong raem.", ""),
("A2", "hostel", "hàw-sà-teew", "ฮอสเทล", "Rodzaje pokoi", 3, "n", HO,
 "", ""),
("A2", "pokój wieloosobowy", "hâwng ruam", "ห้องรวม", "Rodzaje pokoi", 3, "n", HO,
 "Znów ruam — wspólny, łączony.", "pokój wspólny"),
("A2", "cisza nocna", "wee-laa ngîap", "เวลาเงียบ", "Obsługa", 2, "n", HO,
 "", "czas cichy"),

# ============================================================ TRANSPORT
("A2", "miejsce siedzące", "thîi nâng", "ที่นั่ง", "Podróż", 5, "n", TR,
 "Znów thîi — miejsce.", "miejsce siedzieć"),
("A2", "miejsce przy oknie", "thîi nâng rim nâa tàang", "ที่นั่งริมหน้าต่าง", "Podróż", 3, "n", TR,
 "rim to skraj, brzeg.", "miejsce skraj okno"),
("A2", "miejsce przy przejściu", "thîi nâng rim thaang doen", "ที่นั่งริมทางเดิน", "Podróż", 2, "n", TR,
 "", "miejsce skraj korytarz"),
("A2", "klasa (w pociągu)", "chán", "ชั้น", "Podróż", 4, "n", TR,
 "Ten sam wyraz co piętro: chán nùeng, chán sǎwng, chán sǎam.", ""),
("A2", "wagon sypialny", "tûu nawn", "ตู้นอน", "Podróż", 3, "n", TR,
 "Znów tûu — szafa, przedział.", "przedział spać"),
("A2", "pociąg nocny", "rót fai klaang khuen", "รถไฟกลางคืน", "Podróż", 3, "n", TR,
 "Wygodniejszy i tańszy niż samolot na długich trasach.", "pociąg środek noc"),
("A2", "odwołany", "yók lôek láew", "ยกเลิกแล้ว", "Podróż", 3, "adj", TR,
 "", "odwołać już"),
("A2", "opóźniony (o kursie)", "lâa cháa", "ล่าช้า", "Podróż", 3, "adj", TR,
 "cháa samo to powolny.", "opóźniony powolny"),
("A2", "połączenie (przesiadkowe)", "thîao tàw", "เที่ยวต่อ", "Podróż", 3, "n", TR,
 "thîao to kurs, przejazd.", "kurs łączyć"),
("A2", "kurs, przejazd", "thîao", "เที่ยว", "Podróż", 5, "n", TR,
 "To samo słowo znaczy „wybrać się gdzieś”. thîao diao — w jedną stronę.", ""),
("A2", "bagażnik", "thái rót", "ท้ายรถ", "Pojazdy", 2, "n", TR,
 "thái to tył, koniec.", "tył pojazd"),
("A2", "hamulec", "brèek", "เบรก", "Pojazdy", 3, "n", TR,
 "Także czasownik „hamować”.", ""),
("A2", "kierownica", "phuang maa-lai", "พวงมาลัย", "Pojazdy", 2, "n", TR,
 "Dosłownie „wieniec kwiatów” — od kształtu.", "wieniec girlanda"),
("A2", "klakson", "trae", "แตร", "Pojazdy", 3, "n", TR,
 "Używany częściej jako sygnał „jestem tu”, nie jako wyraz złości.", ""),
("A2", "lusterko", "krà-jòk mawng lǎng", "กระจกมองหลัง", "Pojazdy", 2, "n", TR,
 "mawng to patrzeć.", "szkło patrzeć tył"),
("A2", "wypożyczyć skuter", "châo maw-tôe-sai", "เช่ามอเตอร์ไซค์", "Podróż", 4, "v", TR,
 "Wymaga międzynarodowego prawa jazdy; kontrole są częste.", "wynajmować skuter"),
("A2", "zatankować do pełna", "toem tem thǎng", "เติมเต็มถัง", "Podróż", 3, "v", TR,
 "", "dolewać pełny zbiornik"),
("A2", "opłata za przejazd", "khâa doi-sǎan", "ค่าโดยสาร", "Podróż", 4, "n", TR,
 "", "opłata podróżowanie"),
("A2", "włączyć taksometr", "kòt mí-tôe", "กดมิเตอร์", "Podróż", 4, "v", TR,
 "Zdanie do zapamiętania: kierowcy chętnie proponują cenę z ręki, zwykle wyższą.", "naciskać licznik"),
("A2", "licznik, taksometr", "mí-tôe", "มิเตอร์", "Podróż", 4, "n", TR,
 "Także licznik prądu i wody.", ""),

# ============================================================ CZAS
("A2", "doba (24 godziny)", "yîi sìp sìi chûa-moong", "ยี่สิบสี่ชั่วโมง", "Odcinki czasu", 3, "n", CD,
 "Uwaga na liczebnik: dwadzieścia to yîi sìp, nie sǎwng sìp.", "dwadzieścia cztery godzina"),
("A2", "przed chwilą", "mûea kîi", "เมื่อกี้", "Odcinki czasu", 4, "adv", CD,
 "Bardzo częste w mowie potocznej.", "gdy przed chwilą"),
("A2", "w międzyczasie", "nai rá-wàang níi", "ในระหว่างนี้", "Odcinki czasu", 3, "adv", CD,
 "", "w podczas ten"),
("A2", "tymczasowo", "chûa khraao", "ชั่วคราว", "Odcinki czasu", 3, "adv", CD,
 "chûa to okres — ten sam człon co w chûa-moong.", "okres okazja"),
("A2", "na stałe", "thǎa-wawn", "ถาวร", "Odcinki czasu", 3, "adj", CD,
 "Przeciwieństwo chûa khraao.", ""),
("A2", "okres, etap", "chûang", "ช่วง", "Odcinki czasu", 4, "n", CD,
 "chûang níi — w tym okresie, ostatnio. Bardzo częste.", ""),
("A2", "ostatnio, w tym czasie", "chûang níi", "ช่วงนี้", "Odcinki czasu", 5, "adv", CD,
 "Otwiera połowę rozmów: „chûang níi pen yang ngai”.", "okres ten"),
("A2", "roczny", "raai pii", "รายปี", "Kalendarz", 2, "adj", CD,
 "raai- tworzy przymiotniki okresowości: raai wan, raai duean, raai pii.", "pozycja rok"),
("A2", "miesięczny", "raai duean", "รายเดือน", "Kalendarz", 3, "adj", CD,
 "", "pozycja miesiąc"),
("A2", "dzienny", "raai wan", "รายวัน", "Kalendarz", 3, "adj", CD,
 "", "pozycja dzień"),
("A2", "nocny", "klaang khuen", "กลางคืน", "Kalendarz", 4, "adj", CD,
 "klaang to środek — klaang wan to dzień, klaang khuen noc.", "środek noc"),
("A2", "poranny", "tawn cháo", "ตอนเช้า", "Kalendarz", 5, "adj", CD,
 "", "odcinek rano"),
("A2", "termin ważności", "wan mòt aa-yú", "วันหมดอายุ", "Kalendarz", 3, "n", CD,
 "aa-yú to wiek. Napis na każdym opakowaniu.", "dzień wyczerpać wiek"),
("A2", "rocznica", "wan khróp râwp", "วันครบรอบ", "Kalendarz", 2, "n", CD,
 "khróp to pełny komplet, râwp to obieg.", "dzień pełny obieg"),
("A2", "długi weekend", "wan yùt yaao", "วันหยุดยาว", "Kalendarz", 3, "n", CD,
 "Kraj ma ich sporo — warto sprawdzać przed podróżą.", "dzień wolny długi"),

# ============================================================ ZDROWIE
("A2", "termometr", "prà-ràwt wát khâi", "ปรอทวัดไข้", "Sprzęt", 2, "n", ZD,
 "wát to mierzyć.", "rtęć mierzyć gorączka"),
("A2", "gips", "fùeak", "เฝือก", "Sprzęt", 2, "n", ZD,
 "", ""),
("A2", "kule (do chodzenia)", "mái tháo", "ไม้เท้า", "Sprzęt", 2, "n", ZD,
 "Także laska.", "drewno stopa"),
("A2", "wózek inwalidzki", "rót khěn", "รถเข็น", "Sprzęt", 2, "n", ZD,
 "khěn to pchać. To samo słowo znaczy wózek sklepowy.", "pojazd pchać"),
("A2", "soczewki kontaktowe", "khawn-thǽk lehn", "คอนแทคเลนส์", "Sprzęt", 2, "n", ZD,
 "", ""),
("A2", "suplement diety", "aa-hǎan sòoem", "อาหารเสริม", "Leczenie", 3, "n", ZD,
 "sòoem to uzupełniać.", "jedzenie uzupełniać"),
("A2", "odporność", "phuum khúm kan", "ภูมิคุ้มกัน", "Leczenie", 2, "n", ZD,
 "khúm kan to osłaniać.", "grunt osłaniać"),
("A2", "bezsenność", "nawn mâi làp", "นอนไม่หลับ", "Objawy", 3, "n", ZD,
 "Dosłownie „leżeć i nie zasnąć”.", "leżeć nie zasypiać"),
("A2", "stres", "khwaam khrîat", "ความเครียด", "Objawy", 4, "n", ZD,
 "khrîat to napięty, zestresowany.", "stan napięty"),
("A2", "depresja", "rôok súem sâo", "โรคซึมเศร้า", "Objawy", 2, "n", ZD,
 "Znów rôok jako jednostka chorobowa.", "choroba przygnębiony smutny"),
("A2", "terapia, leczenie", "kaan ráksǎa", "การรักษา", "Leczenie", 3, "n", ZD,
 "ráksǎa to leczyć i chronić — to samo słowo co w ráksǎa nâa.", "czynność leczyć"),
("A2", "rehabilitacja", "kaai-yá-phâap bam-bàt", "กายภาพบำบัด", "Leczenie", 2, "n", ZD,
 "", "ciało terapia"),
("A2", "dieta (jadłospis leczniczy)", "aa-hǎan khûap khum", "อาหารควบคุม", "Leczenie", 2, "n", ZD,
 "", "jedzenie kontrolować"),
("A2", "nietolerancja pokarmowa", "phǽe aa-hǎan", "แพ้อาหาร", "Objawy", 4, "n", ZD,
 "Ten sam czasownik phǽe co przy alergii.", "uczulony jedzenie"),
("A2", "grupa krwi", "klùm lûeat", "กลุ่มเลือด", "Leczenie", 2, "n", ZD,
 "Warto mieć zapisaną.", "grupa krew"),
("A2", "oddział szpitalny", "waat", "วอร์ด", "Placówki", 2, "n", ZD,
 "", ""),
("A2", "skierowanie", "bai sòng tùua", "ใบส่งตัว", "Placówki", 2, "n", ZD,
 "", "arkusz wysyłać osoba"),

# ============================================================ PYTANIA
("A2", "ile razy?", "kìi khráng", "กี่ครั้ง", "Struktury pytające", 4, "w", PY,
 "Znów kìi z klasyfikatorem.", "ile raz"),
("A2", "który raz z kolei?", "khráng thîi thâo rai", "ครั้งที่เท่าไร", "Struktury pytające", 2, "w", PY,
 "", "raz który ile"),
("A2", "jak to się nazywa?", "rîak wâa à-rai", "เรียกว่าอะไร", "Struktury pytające", 5, "w", PY,
 "Najużyteczniejsze pytanie dla uczącego się języka.", "nazywać że co"),
("A2", "gdzie dokładnie?", "trong nǎi", "ตรงไหน", "Struktury pytające", 4, "w", PY,
 "trong to dokładnie, wprost — węższe niż thîi nǎi.", "dokładnie który"),
("A2", "do kiedy?", "thǔeng mûea rai", "ถึงเมื่อไร", "Struktury pytające", 3, "w", PY,
 "", "aż do kiedy"),
("A2", "od kiedy?", "tâng tàe mûea rai", "ตั้งแต่เมื่อไร", "Struktury pytające", 3, "w", PY,
 "", "od kiedy"),
("A2", "z kim?", "kàp khrai", "กับใคร", "Struktury pytające", 4, "w", PY,
 "", "z kto"),
("A2", "dla kogo?", "sǎm-ràp khrai", "สำหรับใคร", "Struktury pytające", 3, "w", PY,
 "", "dla kto"),
("A2", "czym? (środkiem)", "doi sǎan à-rai", "โดยสารอะไร", "Struktury pytające", 3, "w", PY,
 "Pytanie o środek transportu.", "podróżować co"),
("A2", "ile kosztuje razem?", "tháng mòt thâo rai", "ทั้งหมดเท่าไร", "Struktury pytające", 5, "w", PY,
 "Zdanie kończące każdą transakcję.", "wszystko ile"),
("A2", "co jeszcze?", "mii à-rai ìik", "มีอะไรอีก", "Struktury pytające", 4, "w", PY,
 "", "mieć co jeszcze"),
("A2", "dlaczego nie?", "tham-mai mâi", "ทำไมไม่", "Struktury pytające", 3, "w", PY,
 "", "dlaczego nie"),

# ============================================================ GRZECZNOŚĆ
("A1", "dobranoc", "raa-trii sà-wàt", "ราตรีสวัสดิ์", "Zwroty grzecznościowe", 4, "w", PG,
 "Formalne. W mowie częściej „fǎn dii” — śpij dobrze.", "noc pomyślność"),
("A1", "śpij dobrze", "fǎn dii", "ฝันดี", "Zwroty grzecznościowe", 4, "w", PG,
 "Dosłownie „dobrych snów”.", "śnić dobry"),
("A1", "miłego dnia", "khǎw hâi pen wan thîi dii", "ขอให้เป็นวันที่ดี", "Zwroty grzecznościowe", 3, "w", PG,
 "Konstrukcja życzeń: khǎw hâi plus treść.", "prosić żeby być dzień dobry"),
("A1", "smacznego", "thaan hâi à-ràwi", "ทานให้อร่อย", "Zwroty grzecznościowe", 4, "w", PG,
 "Nie ma jednego utrwalonego zwrotu — ten jest najbliższy.", "jeść żeby smaczny"),
("A1", "na zdrowie (toast)", "chon kâew", "ชนแก้ว", "Zwroty grzecznościowe", 3, "w", PG,
 "Dosłownie „stuknąć szklankami”. Popularne też angielskie „chai yo”.", "uderzać szklanka"),
("A1", "dawno się nie widzieliśmy", "mâi dâi jooe kan naan", "ไม่ได้เจอกันนาน", "Zwroty grzecznościowe", 4, "w", PG,
 "", "nie móc spotkać nawzajem długo"),
("A1", "co słychać?", "pen yang ngai bâang", "เป็นยังไงบ้าง", "Zwroty grzecznościowe", 5, "w", PG,
 "bâang zmiękcza pytanie do „jakoś tam”.", "być jak trochę"),
("A1", "wszystkiego najlepszego", "sùk sǎn wan kòoet", "สุขสันต์วันเกิด", "Zwroty grzecznościowe", 3, "w", PG,
 "sùk sǎn to radosny — także przy innych świętach.", "radosny dzień urodzenia"),
("A1", "przepraszam za spóźnienie", "khǎw thôot thîi maa sǎai", "ขอโทษที่มาสาย", "Zwroty grzecznościowe", 4, "w", PG,
 "thîi wprowadza powód przeprosin.", "przepraszać że przyjść późno"),
("A1", "proszę usiąść", "chooen nâng", "เชิญนั่ง", "Zwroty grzecznościowe", 4, "w", PG,
 "chooen to zapraszający gest i słowo.", "zapraszać siedzieć"),
("A1", "proszę wejść", "chooen khâo maa", "เชิญเข้ามา", "Zwroty grzecznościowe", 4, "w", PG,
 "", "zapraszać wchodzić"),
("A1", "poczekaj chwilę", "raw sák khrûu", "รอสักครู่", "Zwroty grzecznościowe", 5, "w", PG,
 "sák łagodzi — „no, chwilkę”.", "czekać około chwila"),
("A1", "nie ma za co", "mâi tâwng khàwp khun", "ไม่ต้องขอบคุณ", "Zwroty grzecznościowe", 3, "w", PG,
 "Częściej odpowiada się po prostu „mâi pen rai”.", "nie trzeba dziękować"),

# ============================================================ LICZBY
("A2", "suma, łącznie", "yâwt ruam", "ยอดรวม", "Działania", 4, "n", LI,
 "yâwt to szczyt, saldo, kwota.", "kwota razem"),
("A2", "średnia", "chà-lìa", "เฉลี่ย", "Działania", 3, "n", LI,
 "Także czasownik „uśredniać, podzielić po równo”.", ""),
("A2", "maksimum", "sǔung sùt", "สูงสุด", "Szacowanie", 3, "n", LI,
 "sùt tworzy stopień najwyższy.", "wysoki kres"),
("A2", "minimum", "tàm sùt", "ต่ำสุด", "Szacowanie", 3, "n", LI,
 "tàm to niski.", "niski kres"),
("A2", "wykres", "kraaf", "กราฟ", "Zapis liczb", 2, "n", LI,
 "", ""),
("A2", "tabela", "taa-raang", "ตาราง", "Zapis liczb", 3, "n", LI,
 "Także „metr kwadratowy”: taa-raang mét.", ""),
("A2", "statystyka", "sà-thì-tì", "สถิติ", "Zapis liczb", 2, "n", LI,
 "Także „rekord” w sporcie.", ""),
("A2", "podwoić", "phôoem pen sǎwng thâo", "เพิ่มเป็นสองเท่า", "Działania", 2, "v", LI,
 "", "zwiększać być dwa raz"),
("A2", "zaokrąglić", "plùuk sèet", "ปัดเศษ", "Działania", 2, "v", LI,
 "sèet to reszta, ułamek.", "strząsać reszta"),
("A2", "reszta z dzielenia, drobna końcówka", "sèet", "เศษ", "Działania", 3, "n", LI,
 "Także „resztki, odpadki”.", ""),
("A2", "sztuka, egzemplarz", "chín", "ชิ้น", "Zapis liczb", 4, "n", LI,
 "Klasyfikator kawałków: mięsa, ciasta, ubrania.", ""),
("A2", "komplet, zestaw", "chút", "ชุด", "Zapis liczb", 4, "n", LI,
 "Także strój i garnitur.", ""),

# ============================================================ JEDZENIE
("A2", "guawa", "fà-ràng", "ฝรั่ง", "Składniki", 4, "n", JN,
 "Uwaga: to samo słowo oznacza białego cudzoziemca. Żart o tym zna każdy sprzedawca owoców.", ""),
("A2", "rambutan", "ngáw", "เงาะ", "Składniki", 3, "n", JN,
 "Nagłosowe ng- plus ton wysoki.", ""),
("A2", "mangostan", "mang-khút", "มังคุด", "Składniki", 3, "n", JN,
 "Nazywany królową owoców, w parze z durianem jako królem.", ""),
("A2", "longan", "lam yai", "ลำไย", "Składniki", 3, "n", JN,
 "Specjalność północy.", ""),
("A2", "smoczy owoc", "kâew mang-kawn", "แก้วมังกร", "Składniki", 3, "n", JN,
 "mang-kawn to smok.", "kryształ smok"),
("A2", "pomelo", "sôm oo", "ส้มโอ", "Składniki", 3, "n", JN,
 "Znów sôm — rodzina owoców cytrusowych.", "cytrus pomelo"),
("A2", "tamaryndowiec", "má-khǎam", "มะขาม", "Składniki", 3, "n", JN,
 "Kwaśny składnik pad thaia i wielu sosów.", ""),
("A2", "marakuja", "sǎo-wá-rót", "เสาวรส", "Składniki", 2, "n", JN,
 "", ""),
("A2", "cytryna", "má-naao lǔeang", "มะนาวเหลือง", "Składniki", 2, "n", JN,
 "W kuchni używa się limonki; cytryna jest rzadka.", "limonka żółty"),
("A2", "brokuł", "bràwk-khoo-lîi", "บรอกโคลี", "Składniki", 2, "n", JN,
 "", ""),
("A2", "kalafior", "dàwk kà-làm", "ดอกกะหล่ำ", "Składniki", 2, "n", JN,
 "kà-làm to kapusta; dàwk to kwiat.", "kwiat kapusta"),
("A2", "fasola, groch", "thùa", "ถั่ว", "Składniki", 4, "n", JN,
 "Zbiorczo o wszystkich strączkach i orzechach.", ""),
("A2", "kurkuma", "khà-mîn", "ขมิ้น", "Składniki", 2, "n", JN,
 "Podstawa curry południa.", ""),
("A2", "cynamon", "òp chooei", "อบเชย", "Składniki", 2, "n", JN,
 "", ""),
("A2", "anyż gwiazdkowaty", "pòi kák", "โป๊ยกั๊ก", "Składniki", 2, "n", JN,
 "Z chińskiego „osiem rogów”.", ""),
("A2", "pieprz", "phrík thai", "พริกไทย", "Składniki", 4, "n", JN,
 "Dosłownie „chili tajskie” — mimo nazwy to zwykły pieprz.", "chili tajski"),
("A2", "makaron pszenny", "bà-mìi", "บะหมี่", "Potrawy", 4, "n", JN,
 "Żółty, w odróżnieniu od ryżowego kǔai-tǐao.", ""),
("A2", "makaron błyskawiczny", "maa-maa", "มาม่า", "Potrawy", 4, "n", JN,
 "Nazwa marki, która stała się nazwą kategorii — jak adidasy.", ""),
("A2", "sałatka mięsna po lasku", "lâap", "ลาบ", "Potrawy", 3, "n", JN,
 "Kuchnia Isanu; bardzo ostra, jedzona z ryżem kleistym.", ""),
("A2", "zupa kwaśna", "kaeng sôm", "แกงส้ม", "Potrawy", 3, "n", JN,
 "Mimo nazwy nie zawiera pomarańczy — sôm znaczy tu „kwaśny”.", "curry kwaśny"),
("A2", "jajko na twardo", "khài tôm", "ไข่ต้ม", "Potrawy", 3, "n", JN,
 "Znów tôm — gotować w wodzie.", "jajko gotować"),
("A2", "smażone warzywa", "phàt phàk", "ผัดผัก", "Potrawy", 4, "n", JN,
 "Najprostsze danie jarskie do zamówienia.", "smażyć warzywo"),

# ============================================================ MIEJSCA I AWARIE
("A2", "punkt informacyjny", "sǔun khâw muun", "ศูนย์ข้อมูล", "Miejsca publiczne", 3, "n", PL,
 "sǔun to centrum i zero.", "centrum informacja"),
("A2", "informacja, dane", "khâw muun", "ข้อมูล", "Miejsca publiczne", 4, "n", PL,
 "", "punkt podstawa"),
("A2", "centrum (ośrodek)", "sǔun", "ศูนย์", "Miejsca publiczne", 4, "n", PL,
 "Uwaga: to samo słowo znaczy „zero”.", ""),
("A2", "wypożyczalnia rowerów", "ráan châo jàk-krà-yaan", "ร้านเช่าจักรยาน", "Miejsca publiczne", 2, "n", PL,
 "", "sklep wynajem rower"),
("A2", "biuro podróży", "bàw-rí-sàt thûa", "บริษัททัวร์", "Miejsca publiczne", 3, "n", PL,
 "", "firma wycieczka"),
("A2", "punkt widokowy", "jùt chom wiu", "จุดชมวิว", "Miejsca publiczne", 3, "n", PL,
 "jùt to punkt; chom to podziwiać.", "punkt podziwiać widok"),
("A2", "punkt, miejsce (na mapie)", "jùt", "จุด", "Orientacja", 4, "n", PL,
 "Także kropka i przecinek dziesiętny.", ""),
("A2", "wejście dla niepełnosprawnych", "thaang khâo phûu phí-kaan", "ทางเข้าผู้พิการ", "Orientacja", 2, "n", PL,
 "", "wejście osoba niepełnosprawny"),
("A2", "zgubiony bagaż", "krà-pǎo hǎai", "กระเป๋าหาย", "Sytuacje", 3, "n", AW,
 "Znów hǎai — zniknąć.", "torba zniknąć"),
("A2", "biuro rzeczy znalezionych", "sǔun khǎwng hǎai", "ศูนย์ของหาย", "Sytuacje", 2, "n", AW,
 "", "centrum rzecz zgubiony"),
("A2", "numer alarmowy", "boe chùk chǒoen", "เบอร์ฉุกเฉิน", "Reakcja", 4, "n", AW,
 "chùk chǒoen to nagły wypadek. Pogotowie 1669, policja turystyczna 1155.", "numer nagły"),
("A2", "nagły wypadek", "chùk chǒoen", "ฉุกเฉิน", "Reakcja", 4, "n", AW,
 "Napis nad wejściem na izbę przyjęć.", ""),
("A2", "pomoc drogowa", "rót yók", "รถยก", "Reakcja", 2, "n", AW,
 "Znów yók — podnosić.", "pojazd podnosić"),
("A2", "ubezpieczenie podróżne", "prà-kan kaan doen thaang", "ประกันการเดินทาง", "Reakcja", 3, "n", AW,
 "Bez niego leczenie w szpitalu prywatnym bywa bardzo kosztowne.", "ubezpieczenie podróż"),
("A2", "zablokowany zamek", "kun-jae tìt", "กุญแจติด", "Sytuacje", 2, "n", AW,
 "Znów tìt — utknąć.", "klucz utknąć"),
("A2", "brak wody", "nám mâi lǎi", "น้ำไม่ไหล", "Sytuacje", 3, "n", AW,
 "lǎi to płynąć.", "woda nie płynąć"),
("A2", "płynąć, ciec", "lǎi", "ไหล", "Sytuacje", 3, "v", AW,
 "O wodzie, prądzie i ruchu ulicznym.", ""),
]
