# -*- coding: utf-8 -*-
"""Leksyka etapu 6 — zdrowie i bezpieczenstwo.

Uklad jest sekwencyjny, tak jak w etapie 5: rekordy daja sie zlozyc w rozmowe.
Najpierw objaw, potem czas trwania i nasilenie, potem apteka, potem sytuacja
nagla i wezwanie pomocy, na koncu bezpieczenstwo codzienne.

Krotka: (poziom, polski, fonetyka, tajski, kategoria, podkategoria, typ,
         freq, rejestr, notatka, znaczenie doslowne, przyklad)
"""

SAFETY = [

# =====================================================================
# OBJAWY
# =====================================================================
("A2", "boli mnie głowa", "pùat hǔa", "ปวดหัว", "Zdrowie", "Objawy", "phrase", 5, "n",
 "„pùat” to ból tępy, ciągły. Ból ostry, kłujący to „jèp”.", "boleć głowa",
 ("Od rana boli mnie głowa.", "pùat hǔa tâng tàe cháo khráp", "ปวดหัวตั้งแต่เช้าครับ")),
("A2", "boli mnie brzuch", "pùat tháwng", "ปวดท้อง", "Zdrowie", "Objawy", "phrase", 5, "n",
 "Najczęstsza dolegliwość turysty w Tajlandii. Warto umieć bez zastanowienia.", "boleć brzuch",
 ("Boli mnie brzuch od wczoraj.", "pùat tháwng tâng tàe mûea waan khráp", "ปวดท้องตั้งแต่เมื่อวานครับ")),
("A2", "boli mnie gardło", "jèp khaw", "เจ็บคอ", "Zdrowie", "Objawy", "phrase", 4, "n",
 "Tu używa się „jèp”, nie „pùat” — ból gardła jest ostry.", "boleć gardło",
 ("Boli mnie gardło i mam kaszel.", "jèp khaw láe ai dûai khráp", "เจ็บคอและไอด้วยครับ")),
("A2", "mam gorączkę", "pen khâi", "เป็นไข้", "Zdrowie", "Objawy", "phrase", 5, "n",
 "„pen” tworzy nazwy chorób: „pen wàt” (przeziębienie), „pen khâi” (gorączka).", "być gorączka",
 ("Mam gorączkę od dwóch dni.", "pen khâi maa sǎwng wan láew khráp", "เป็นไข้มาสองวันแล้วครับ")),
("A2", "jestem przeziębiony", "pen wàt", "เป็นหวัด", "Zdrowie", "Objawy", "phrase", 4, "n",
 "Lekka infekcja. Grypa to „khâi wàt yài”.", "być przeziębienie",
 ("Jestem przeziębiony.", "phǒm pen wàt khráp", "ผมเป็นหวัดครับ")),
("A2", "mam kaszel", "ai", "ไอ", "Zdrowie", "Objawy", "verb", 4, "n",
 "Jedno krótkie słowo. W aptece wystarczy powiedzieć „ai” i wskazać gardło.", "",
 ("Kaszlę już od tygodnia.", "phǒm ai maa nùeng aa-thít láew khráp", "ผมไอมาหนึ่งอาทิตย์แล้วครับ")),
("A2", "mam katar", "náam mûuk lǎi", "น้ำมูกไหล", "Zdrowie", "Objawy", "phrase", 3, "n",
 "Dosłownie „płynie wydzielina z nosa”. Tajski opisuje objaw, nie nazywa go.", "woda nos płynąć",
 ("Mam katar i boli mnie głowa.", "náam mûuk lǎi láe pùat hǔa khráp", "น้ำมูกไหลและปวดหัวครับ")),
("A2", "mam biegunkę", "tháwng sǐa", "ท้องเสีย", "Zdrowie", "Objawy", "phrase", 4, "n",
 "Dosłownie „zepsuty brzuch”. Powszechne i całkowicie neutralne słowo.", "brzuch zepsuty",
 ("Mam biegunkę od wczoraj.", "tháwng sǐa tâng tàe mûea waan khráp", "ท้องเสียตั้งแต่เมื่อวานครับ")),
("A2", "mdli mnie", "khlûen sâi", "คลื่นไส้", "Zdrowie", "Objawy", "phrase", 3, "n",
 "Dosłownie „fale w jelitach”. Standardowe słowo także w gabinecie lekarskim.", "fala jelito",
 ("Mdli mnie od rana.", "phǒm khlûen sâi tâng tàe cháo khráp", "ผมคลื่นไส้ตั้งแต่เช้าครับ")),
("A2", "kręci mi się w głowie", "wian hǔa", "เวียนหัว", "Zdrowie", "Objawy", "phrase", 3, "n",
 "Objaw ważny przy udarze cieplnym — częstym u przyjezdnych.", "kręcić głowa",
 ("Kręci mi się w głowie.", "phǒm wian hǔa khráp", "ผมเวียนหัวครับ")),
("B1", "boli mnie tutaj", "jèp trong níi", "เจ็บตรงนี้", "Zdrowie", "Wywiad lekarski", "phrase", 4, "n",
 "Najskuteczniejsze zdanie u lekarza: wskazujesz palcem i mówisz to.", "boleć tutaj",
 ("Boli mnie dokładnie tutaj.", "jèp trong níi khráp", "เจ็บตรงนี้ครับ")),
("B1", "boli od trzech dni", "pen maa sǎam wan láew", "เป็นมาสามวันแล้ว", "Zdrowie", "Wywiad lekarski", "phrase", 4, "n",
 "„pen maa … láew” to standardowa odpowiedź na pytanie lekarza o czas trwania.", "być przyjść trzy dni już",
 ("Trwa to już trzy dni.", "pen maa sǎam wan láew khráp", "เป็นมาสามวันแล้วครับ")),
("B1", "ból jest silny", "pùat mâak", "ปวดมาก", "Zdrowie", "Wywiad lekarski", "phrase", 4, "n",
 "Skala jest w Tajlandii rzadko używana; wystarczy „nít nàwi / mâak / mâak mâak”.", "boleć bardzo",
 ("Ból jest bardzo silny.", "pùat mâak khráp thon mâi wǎai", "ปวดมากครับ ทนไม่ไหว")),
("B1", "objawy się nasilają", "aa-kaan nàk khûen", "อาการหนักขึ้น", "Zdrowie", "Wywiad lekarski", "phrase", 3, "f",
 "„aa-kaan” to objawy albo stan chorego — słowo obecne w każdej rozmowie z lekarzem.", "objaw ciężko wzrastać",
 ("Objawy się nasilają.", "aa-kaan nàk khûen khráp", "อาการหนักขึ้นครับ")),

# =====================================================================
# APTEKA I LECZENIE
# =====================================================================
("A2", "lek przeciwbólowy", "yaa kâe pùat", "ยาแก้ปวด", "Zdrowie", "Apteka", "noun", 4, "n",
 "„yaa kâe …” to schemat nazw leków: kâe pùat, kâe ai, kâe pháe.", "lek leczyć ból",
 ("Poproszę coś przeciwbólowego.", "khǎw yaa kâe pùat khráp", "ขอยาแก้ปวดครับ")),
("A2", "lek na kaszel", "yaa kâe ai", "ยาแก้ไอ", "Zdrowie", "Apteka", "noun", 3, "n",
 "Ten sam schemat co „yaa kâe pùat”. W aptece wystarczy nazwa objawu.", "lek leczyć kaszel",
 ("Poproszę syrop na kaszel.", "khǎw yaa kâe ai khráp", "ขอยาแก้ไอครับ")),
("A2", "lek na alergię", "yaa kâe pháe", "ยาแก้แพ้", "Zdrowie", "Apteka", "noun", 3, "n",
 "Przydaje się po ukąszeniach owadów, częstych w porze deszczowej.", "lek leczyć alergia",
 ("Poproszę lek na alergię.", "khǎw yaa kâe pháe khráp", "ขอยาแก้แพ้ครับ")),
("A2", "ile razy dziennie?", "wan lá kìi khráng", "วันละกี่ครั้ง", "Zdrowie", "Apteka", "question", 4, "n",
 "„lá” tworzy stawkę na jednostkę: „wan lá”, „khon lá”, „chín lá”.", "dzień na ile razy",
 ("Ile razy dziennie to brać?", "kin wan lá kìi khráng khráp", "กินวันละกี่ครั้งครับ")),
("A2", "przed jedzeniem czy po?", "kàwn aa-hǎan rǔe lǎng aa-hǎan", "ก่อนอาหารหรือหลังอาหาร", "Zdrowie", "Apteka", "question", 3, "n",
 "Informacja standardowo podawana na tajskich opakowaniach leków.", "przed jedzenie czy po jedzenie",
 ("Brać przed jedzeniem czy po?", "kin kàwn aa-hǎan rǔe lǎng aa-hǎan khráp", "กินก่อนอาหารหรือหลังอาหารครับ")),
("B1", "jestem uczulony na ten lek", "phǒm pháe yaa níi", "ผมแพ้ยานี้", "Zdrowie", "Alergie", "phrase", 4, "n",
 "Zdanie o znaczeniu ratunkowym. Warto mieć je też zapisane na kartce w portfelu.", "ja alergia lek ten",
 ("Jestem uczulony na penicylinę.", "phǒm pháe yaa pheen-ni-sin-lin khráp", "ผมแพ้ยาเพนนิซิลลินครับ")),
("B1", "biorę leki na stałe", "phǒm kin yaa prà-jam", "ผมกินยาประจำ", "Zdrowie", "Wywiad lekarski", "phrase", 3, "n",
 "„prà-jam” = regularnie, na stałe. Ważne przy każdej wizycie.", "ja jeść lek regularnie",
 ("Biorę leki na stałe na nadciśnienie.", "phǒm kin yaa khwaam dan lôhit sǔung prà-jam khráp", "ผมกินยาความดันโลหิตสูงประจำครับ")),
("B1", "potrzebuję zaświadczenia lekarskiego", "khǎw bai ráp-rawng phâet", "ขอใบรับรองแพทย์", "Zdrowie", "Formalności", "phrase", 3, "f",
 "Potrzebne do ubezpieczenia i do zwolnienia z pracy.", "proszę arkusz poświadczenie lekarz",
 ("Poproszę zaświadczenie lekarskie.", "khǎw bai ráp-rawng phâet dûai khráp", "ขอใบรับรองแพทย์ด้วยครับ")),
("B1", "mam ubezpieczenie podróżne", "phǒm mii prà-kan kaan doen thaang", "ผมมีประกันการเดินทาง", "Zdrowie", "Formalności", "phrase", 3, "f",
 "Powiedz to w rejestracji od razu — zmienia sposób rozliczenia wizyty.", "ja mieć ubezpieczenie podróż",
 ("Mam ubezpieczenie podróżne.", "phǒm mii prà-kan kaan doen thaang khráp", "ผมมีประกันการเดินทางครับ")),

# =====================================================================
# SYTUACJA NAGLA
# =====================================================================
("A1", "na pomoc!", "chûai dûai", "ช่วยด้วย", "Awarie i pomoc", "Alarm", "phrase", 5, "n",
 "Krzyk o pomoc. Jedyne zdanie z tej listy, którego uczy się na pamięć od pierwszego dnia.", "pomóc też",
 ("Na pomoc! Wypadek!", "chûai dûai mii ù-bàt-tì-hèet", "ช่วยด้วย มีอุบัติเหตุ")),
("A2", "proszę wezwać karetkę", "rîak rót phá-yaa-baan", "เรียกรถพยาบาล", "Awarie i pomoc", "Alarm", "phrase", 4, "n",
 "„rîak” to wezwać. Numer alarmowy pogotowia w Tajlandii to 1669.", "wołać pojazd szpital",
 ("Proszę wezwać karetkę!", "chûai rîak rót phá-yaa-baan dûai khráp", "ช่วยเรียกรถพยาบาลด้วยครับ")),
("A2", "proszę wezwać policję", "rîak tam-rùat", "เรียกตำรวจ", "Awarie i pomoc", "Alarm", "phrase", 4, "n",
 "Policja turystyczna ma osobny numer 1155 i mówi po angielsku.", "wołać policja",
 ("Proszę wezwać policję.", "chûai rîak tam-rùat dûai khráp", "ช่วยเรียกตำรวจด้วยครับ")),
("B1", "wydarzył się wypadek", "mii ù-bàt-tì-hèet", "มีอุบัติเหตุ", "Awarie i pomoc", "Wypadek", "phrase", 4, "n",
 "Pierwsze zdanie rozmowy z dyspozytorem: co się stało.", "mieć wypadek",
 ("Wydarzył się wypadek samochodowy.", "mii ù-bàt-tì-hèet rót chon khráp", "มีอุบัติเหตุรถชนครับ")),
("B1", "są ranni", "mii khon jèp", "มีคนเจ็บ", "Awarie i pomoc", "Wypadek", "phrase", 4, "n",
 "Drugie zdanie: czy ktoś ucierpiał. Dyspozytor pyta o to natychmiast.", "mieć osoba ranny",
 ("Są dwie osoby ranne.", "mii khon jèp sǎwng khon khráp", "มีคนเจ็บสองคนครับ")),
("B1", "on jest przytomny", "khǎo yang rúu-sùek tua", "เขายังรู้สึกตัว", "Awarie i pomoc", "Wypadek", "phrase", 3, "f",
 "„rúu-sùek tua” to być przytomnym. Kluczowa informacja dla dyspozytora.", "on jeszcze czuć ciało",
 ("Jest przytomny, ale krwawi.", "khǎo yang rúu-sùek tua tàe lûeat àwk khráp", "เขายังรู้สึกตัวแต่เลือดออกครับ")),
("B1", "on jest nieprzytomny", "khǎo mâi rúu-sùek tua", "เขาไม่รู้สึกตัว", "Awarie i pomoc", "Wypadek", "phrase", 3, "f",
 "Ta informacja podnosi priorytet wezwania. Podaj ją od razu.", "on nie czuć ciało",
 ("Jest nieprzytomny, proszę szybko!", "khǎo mâi rúu-sùek tua rîip nòi khráp", "เขาไม่รู้สึกตัว รีบหน่อยครับ")),
("B1", "jesteśmy koło…", "raw yùu klâi", "เราอยู่ใกล้", "Awarie i pomoc", "Lokalizacja", "phrase", 4, "n",
 "Bez punktu odniesienia dyspozytor nie znajdzie miejsca. Podawaj sklep, świątynię albo stację.", "my być blisko",
 ("Jesteśmy koło stacji metra.", "raw yùu klâi sà-thǎa-nii rót fai fáa khráp", "เราอยู่ใกล้สถานีรถไฟฟ้าครับ")),
("B1", "nie wiem, gdzie jestem", "phǒm mâi rúu wâa yùu thîi nǎi", "ผมไม่รู้ว่าอยู่ที่ไหน", "Awarie i pomoc", "Lokalizacja", "phrase", 3, "n",
 "Powiedz to od razu — dyspozytor przejdzie wtedy na pytania o punkty orientacyjne.", "ja nie wiedzieć że być gdzie",
 ("Nie wiem, gdzie dokładnie jestem.", "phǒm mâi rúu wâa yùu thîi nǎi nâe khráp", "ผมไม่รู้ว่าอยู่ที่ไหนแน่ครับ")),
("B1", "okradziono mnie", "phǒm thùuk khà-mooi", "ผมถูกขโมย", "Awarie i pomoc", "Kradzież", "phrase", 3, "n",
 "„thùuk” tworzy stronę bierną o wydźwięku niekorzystnym dla mówiącego.", "ja zostać okradziony",
 ("Okradziono mnie w autobusie.", "phǒm thùuk khà-mooi bon rót mee khráp", "ผมถูกขโมยบนรถเมล์ครับ")),
("B1", "chcę skontaktować się z ambasadą", "khǎw tìt tàw sà-thǎan-thûut", "ขอติดต่อสถานทูต", "Awarie i pomoc", "Ambasada", "phrase", 3, "f",
 "Zdanie potrzebne przy utracie paszportu i przy zatrzymaniu przez policję.", "proszę kontakt ambasada",
 ("Chcę skontaktować się z ambasadą Polski.", "khǎw tìt tàw sà-thǎan-thûut poo-laen khráp", "ขอติดต่อสถานทูตโปแลนด์ครับ")),

# =====================================================================
# BEZPIECZENSTWO CODZIENNE
# =====================================================================
("A2", "uwaga!", "rá-wang", "ระวัง", "Awarie i pomoc", "Ostrzeżenia", "phrase", 5, "n",
 "Ostrzeżenie krótkie i natychmiastowe. Na tabliczkach: „rá-wang lûen” (uwaga, ślisko).", "",
 ("Uwaga, ślisko!", "rá-wang lûen ná khráp", "ระวังลื่นนะครับ")),
("A2", "czy tu jest bezpiecznie?", "trong níi plàwt phai mǎi", "ตรงนี้ปลอดภัยไหม", "Awarie i pomoc", "Bezpieczeństwo", "question", 3, "n",
 "„plàwt phai” = wolny od niebezpieczeństwa. Pytanie warte zadania wieczorem w nieznanej okolicy.", "tutaj wolny niebezpieczeństwo czy",
 ("Czy wieczorem jest tu bezpiecznie?", "tawn khâm trong níi plàwt phai mǎi khráp", "ตอนค่ำตรงนี้ปลอดภัยไหมครับ")),
("A2", "czy tę wodę można pić?", "náam níi dùem dâai mǎi", "น้ำนี้ดื่มได้ไหม", "Zdrowie", "Bezpieczeństwo", "question", 3, "n",
 "Woda z kranu w Tajlandii nie nadaje się do picia; pytanie ma sens także w hotelu.", "woda ta pić móc czy",
 ("Czy tę wodę można pić?", "náam níi dùem dâai mǎi khráp", "น้ำนี้ดื่มได้ไหมครับ")),
("A2", "proszę tego nie dotykać", "yàa tàe tâwng", "อย่าแตะต้อง", "Awarie i pomoc", "Ostrzeżenia", "phrase", 2, "f",
 "„yàa” to zakaz. Wobec dorosłych brzmi mocno — łagodzi je „ná khráp”.", "nie dotykać",
 ("Proszę tego nie dotykać.", "yàa tàe tâwng ná khráp an-tà-raai", "อย่าแตะต้องนะครับ อันตราย")),
("B1", "to jest niebezpieczne", "an-tà-raai", "อันตราย", "Awarie i pomoc", "Ostrzeżenia", "adjective", 4, "n",
 "Widnieje na wszystkich tablicach ostrzegawczych. Warto rozpoznawać ze słuchu.", "",
 ("To miejsce jest niebezpieczne.", "trong nán an-tà-raai khráp", "ตรงนั้นอันตรายครับ")),
("B1", "zgubiłem się", "phǒm lǒng thaang", "ผมหลงทาง", "Awarie i pomoc", "Orientacja", "phrase", 4, "n",
 "„lǒng” to zabłądzić. Zdanie otwiera prośbę o pomoc w nawigacji.", "ja zabłądzić droga",
 ("Zgubiłem się, jak dojść do stacji?", "phǒm lǒng thaang khráp pai sà-thǎa-nii yang-ngai", "ผมหลงทางครับ ไปสถานียังไง")),
("A2", "palić papierosy", "sùup bù-rìi", "สูบบุหรี่", "Zdrowie", "Używki", "verb", 3, "n",
 "„sùup” znaczy „ssać, wciągać”. Palenie w miejscach publicznych jest w Tajlandii karane mandatem — tabliczki mówią „hâam sùup bù-rìi”.", "wciągać papieros",
 ("Gdzie można zapalić?", "sùup bù-rìi dâai thîi nǎi khráp", "สูบบุหรี่ได้ที่ไหนครับ")),
("B1", "proszę mnie tu poczekać", "raw phǒm trong níi ná", "รอผมตรงนี้นะ", "Awarie i pomoc", "Bezpieczeństwo", "phrase", 3, "i",
 "Przydatne, gdy podróżujesz z dzieckiem albo z kimś, kto nie zna okolicy.", "czekać ja tutaj",
 ("Poczekaj tu na mnie, zaraz wracam.", "raw phǒm trong níi ná dǐao klàp maa", "รอผมตรงนี้นะ เดี๋ยวกลับมา")),
]
