# -*- coding: utf-8 -*-
"""Sesja N — TRANSPORT, MIEJSCA I ORIENTACJA, HOTEL.

Trzy kategorie o tej samej wadzie: dużo gotowych zwrotów, mało haseł.
Transport miał 202 rekordy przy 43 hasłach, Miejsca 374 przy 46, Hotel 189
przy 26. Uczący się dostawał zdanie „Gdzie jest przystanek autobusowy?”
w całości, ale nie miał czym go przebudować, gdy chodziło o dworzec, pomost
albo bramkę.
"""

TR = "Transport"
PL = "Miejsca i orientacja"
HO = "Hotel"

MOVE = [

# ============================================================ TRANSPORT: POJAZDY
("A1", "pojazd, wóz", "yaan phaa-hà-ná", "ยานพาหนะ", "Pojazdy", 2, "n", TR,
 "Termin urzędowy z formularzy i znaków. W mowie mówi się po prostu rót.", ""),
("A1", "minibus", "rót tûu", "รถตู้", "Pojazdy", 4, "n", TR,
 "Dosłownie „pojazd szafa”. Podstawowy transport międzymiastowy na krótkich trasach.", "pojazd szafa"),
("A1", "autobus piętrowy", "rót sǎwng chán", "รถสองชั้น", "Pojazdy", 3, "n", TR,
 "Na trasach nocnych. chán to piętro i warstwa.", "pojazd dwa piętro"),
("A2", "autobus z klimatyzacją", "rót ae", "รถแอร์", "Pojazdy", 4, "n", TR,
 "Różnica w cenie biletu wobec rót thammádaa bywa dwukrotna.", "pojazd klimatyzacja"),
("A2", "autobus zwykły (bez klimatyzacji)", "rót thammádaa", "รถธรรมดา", "Pojazdy", 3, "n", TR,
 "thammádaa to „zwykły, normalny” — także o człowieku i o dniu.", "pojazd zwykły"),
("A1", "ciężarówka", "rót bantúk", "รถบรรทุก", "Pojazdy", 3, "n", TR,
 "bantúk to ładować, przewozić.", "pojazd ładować"),
("A2", "furgonetka z ławkami", "sǎwng thǎew", "สองแถว", "Pojazdy", 4, "n", TR,
 "Dosłownie „dwa rzędy”. Na prowincji to podstawowy transport miejski — wsiadasz z tyłu, płacisz przy wysiadaniu.", "dwa rząd"),
("A1", "rower", "jàk-krà-yaan", "จักรยาน", "Pojazdy", 3, "n", TR,
 "Trzy sylaby; pierwsze dwie nieakcentowane i w mowie zlewają się.", ""),
("A2", "łódź długoogonowa", "ruea hǎang yaao", "เรือหางยาว", "Pojazdy", 3, "n", TR,
 "Charakterystyczna łódź z silnikiem samochodowym na długim wale.", "łódź ogon długi"),
("A2", "prom", "ruea khâam fâak", "เรือข้ามฟาก", "Pojazdy", 3, "n", TR,
 "khâam to przechodzić w poprzek — ten sam czasownik co przy przechodzeniu przez ulicę.", "łódź przekraczać brzeg"),
("A2", "łódź motorowa", "ruea rew", "เรือเร็ว", "Pojazdy", 3, "n", TR,
 "Na wyspy. rew to szybki.", "łódź szybki"),
("A2", "kolejka nadziemna", "rót fai fáa", "รถไฟฟ้า", "Pojazdy", 4, "n", TR,
 "W Bangkoku BTS. Dosłownie „pojazd ognia niebieskiego” — czyli elektryczny.", "pojazd ogień elektryczność"),
("A2", "metro", "rót fai tâi din", "รถไฟใต้ดิน", "Pojazdy", 4, "n", TR,
 "MRT. tâi to pod.", "pojazd ogień pod ziemia"),

# ============================================================ TRANSPORT: PODRÓŻ
("A1", "kierowca", "khon khàp", "คนขับ", "Podróż", 4, "n", TR,
 "khàp to prowadzić pojazd. Zwrot do kierowcy taksówki: phîi khàp.", "człowiek prowadzić"),
("A2", "pasażer", "phûu doi-sǎan", "ผู้โดยสาร", "Podróż", 3, "n", TR,
 "phûu- tworzy nazwy osób od czynności, jak polskie -ciel.", "osoba podróżować"),
("A2", "konduktor, obsługa", "krà-pǎo rót", "กระเป๋ารถ", "Podróż", 2, "n", TR,
 "Dosłownie „torba pojazdu” — od torby na bilety i drobne.", "torba pojazd"),
("A1", "peron", "chaan chaa-laa", "ชานชาลา", "Podróż", 3, "n", TR,
 "Słowo z dworcowych zapowiedzi.", ""),
("A1", "tor, szyna", "raang", "ราง", "Podróż", 2, "n", TR,
 "Także rynna i rowek.", ""),
("A2", "pomost, przystań", "thâa ruea", "ท่าเรือ", "Podróż", 4, "n", TR,
 "thâa to przystań, port. Stąd nazwy przystanków łodzi w Bangkoku.", "przystań łódź"),
("A2", "bramka (na lotnisku)", "prà-tuu khûen khrûeang", "ประตูขึ้นเครื่อง", "Podróż", 3, "n", TR,
 "Dosłownie „drzwi wejścia na maszynę”.", "drzwi wsiadać maszyna"),
("A2", "odprawa", "chék-in", "เช็คอิน", "Podróż", 4, "n", TR,
 "Zapożyczenie; działa też jako czasownik.", ""),
("A2", "bagaż podręczny", "krà-pǎo thǔe khûen khrûeang", "กระเป๋าถือขึ้นเครื่อง", "Podróż", 3, "n", TR,
 "thǔe to trzymać w ręce.", "torba trzymać wsiadać maszyna"),
("A2", "odbiór bagażu", "ráp krà-pǎo", "รับกระเป๋า", "Podróż", 3, "n", TR,
 "ráp to odbierać, przyjmować — bardzo produktywny czasownik.", "odbierać torba"),
("A2", "kontrola paszportowa", "tùuat nǎng-sǔe doen thaang", "ตรวจหนังสือเดินทาง", "Podróż", 3, "n", TR,
 "tùuat to sprawdzać, badać — także w gabinecie lekarskim.", "sprawdzać paszport"),
("A2", "cło", "sǔn-lá-kaa-kawn", "ศุลกากร", "Podróż", 2, "n", TR,
 "Napis nad przejściem; warto rozpoznać ze słuchu w zapowiedzi.", ""),
("A2", "wiza", "wii-sâa", "วีซ่า", "Podróż", 4, "n", TR,
 "Temat praktyczny przy każdym dłuższym pobycie.", ""),
("B1", "przedłużenie wizy", "tàw wii-sâa", "ต่อวีซ่า", "Podróż", 3, "n", TR,
 "tàw to przedłużać i łączyć — także o przesiadce.", "przedłużać wiza"),
("A2", "przesiadka", "tàw rót", "ต่อรถ", "Podróż", 3, "n", TR,
 "Ten sam czasownik tàw. O locie: tàw khrûeang.", "łączyć pojazd"),
("A2", "trasa, linia", "sǎai", "สาย", "Podróż", 4, "n", TR,
 "Numer linii autobusowej: sǎai sìp-hâa. Także „sznurek” i „spóźniony”.", ""),
("A2", "kierunek", "thít thaang", "ทิศทาง", "Podróż", 3, "n", TR,
 "thít to strona świata, thaang to droga.", "strona świata droga"),
("A2", "odjazd", "àwk doen thaang", "ออกเดินทาง", "Podróż", 3, "n", TR,
 "àwk to wychodzić — punkt wyjścia większości zwrotów o ruchu.", "wychodzić podróżować"),
("A2", "przyjazd", "thǔeng", "ถึง", "Podróż", 5, "v", TR,
 "Bardzo częsty czasownik: dojechać, dotrzeć, dojść. Także „aż do”.", ""),
("A2", "wsiadać", "khûen rót", "ขึ้นรถ", "Podróż", 5, "v", TR,
 "Tajski mówi „wznieść się na pojazd”, niezależnie od tego, czy się wchodzi w górę.", "wznosić się pojazd"),
("A2", "wysiadać", "long rót", "ลงรถ", "Podróż", 5, "v", TR,
 "Symetria: khûen w górę, long w dół.", "schodzić pojazd"),
("A2", "spóźnić się (na coś)", "tòk rót", "ตกรถ", "Podróż", 3, "v", TR,
 "Dosłownie „spaść z pojazdu” — czyli nie zdążyć.", "spaść pojazd"),
("B1", "korek uliczny", "rót tìt", "รถติด", "Podróż", 5, "n", TR,
 "tìt to utknąć, przykleić się. W Bangkoku najczęstsze wytłumaczenie spóźnienia.", "pojazd utknąć"),
("B1", "objazd", "thaang bìang", "ทางเบี่ยง", "Podróż", 2, "n", TR,
 "Napis na drodze przy remoncie.", "droga zbaczać"),
("B1", "prawo jazdy", "bai khàp khìi", "ใบขับขี่", "Podróż", 3, "n", TR,
 "bai to arkusz i klasyfikator rzeczy płaskich.", "arkusz prowadzić jeździć"),
("B1", "kask", "mùak kan náwk", "หมวกกันน็อก", "Podróż", 3, "n", TR,
 "Dosłownie „czapka chroniąca przed uderzeniem”. Obowiązkowy i kontrolowany.", "czapka chronić uderzenie"),
("B1", "pas bezpieczeństwa", "khěm khàt ní-rá-phai", "เข็มขัดนิรภัย", "Podróż", 2, "n", TR,
 "khěm khàt to zwykły pasek do spodni.", "pasek bezpieczeństwo"),
("B1", "opłata drogowa", "khâa thaang dùan", "ค่าทางด่วน", "Podróż", 2, "n", TR,
 "thaang dùan to droga ekspresowa.", "opłata droga szybki"),
("A2", "stacja benzynowa", "pám nám man", "ปั๊มน้ำมัน", "Podróż", 3, "n", TR,
 "nám man to dosłownie „woda tłusta” — paliwo i olej jadalny to to samo słowo.", "pompa paliwo"),
("A2", "paliwo, olej", "nám man", "น้ำมัน", "Podróż", 4, "n", TR,
 "W restauracji ten sam wyraz znaczy olej do smażenia.", "woda tłuszcz"),
("B1", "opona", "yaang rót", "ยางรถ", "Podróż", 2, "n", TR,
 "yaang to guma i drzewo kauczukowe.", "guma pojazd"),

# ============================================================ MIEJSCA
("A1", "budynek", "aa-khaan", "อาคาร", "Budynki", 3, "n", PL,
 "Słowo z tablic informacyjnych: aa-khaan A, aa-khaan B.", ""),
("A1", "wieżowiec", "tùek sǔung", "ตึกสูง", "Budynki", 3, "n", PL,
 "tùek to budynek murowany, w odróżnieniu od drewnianego bâan.", "budynek wysoki"),
("A1", "piętro", "chán", "ชั้น", "Budynki", 5, "n", PL,
 "Też półka, warstwa i klasa szkolna. Bardzo produktywne słowo.", ""),
("A1", "parter", "chán nùeng", "ชั้นหนึ่ง", "Budynki", 4, "n", PL,
 "Uwaga: tajskie „pierwsze piętro” to polski parter — liczenie idzie od poziomu ulicy.", "piętro jeden"),
("A2", "winda", "líp", "ลิฟต์", "Budynki", 4, "n", PL,
 "Zapożyczenie z angielskiego lift.", ""),
("A2", "schody ruchome", "ban-dai lûean", "บันไดเลื่อน", "Budynki", 3, "n", PL,
 "lûean to przesuwać się, ślizgać.", "schody przesuwać się"),
("A2", "wejście", "thaang khâo", "ทางเข้า", "Budynki", 4, "n", PL,
 "thaang to droga i sposób; z khâo i àwk tworzy parę wejście–wyjście.", "droga wchodzić"),
("A2", "wyjście", "thaang àwk", "ทางออก", "Budynki", 4, "n", PL,
 "Także „wyjście z sytuacji” — dokładnie ta sama przenośnia co po polsku.", "droga wychodzić"),
("A2", "wyjście awaryjne", "thaang nǐi fai", "ทางหนีไฟ", "Budynki", 2, "n", PL,
 "nǐi to uciekać.", "droga uciekać ogień"),
("A1", "korytarz", "thaang doen", "ทางเดิน", "Budynki", 3, "n", PL,
 "", "droga chodzić"),
("A2", "róg (ulicy)", "hǔa mum", "หัวมุม", "Orientacja", 4, "n", PL,
 "hǔa to głowa i czoło czegoś; mum to kąt.", "głowa kąt"),
("A1", "skrzyżowanie", "sìi yâek", "สี่แยก", "Orientacja", 4, "n", PL,
 "Dosłownie „cztery rozgałęzienia”. Trójkątne to sǎam yâek.", "cztery rozgałęzienie"),
("A2", "rondo", "wong wian", "วงเวียน", "Orientacja", 3, "n", PL,
 "Dosłownie „koło obrotowe”.", "koło krążyć"),
("A1", "przejście dla pieszych", "thaang máa laai", "ทางม้าลาย", "Orientacja", 3, "n", PL,
 "Dosłownie „droga zebry” — máa laai to zebra, czyli „koń w paski”.", "droga zebra"),
("A2", "chodnik", "thaang tháo", "ทางเท้า", "Orientacja", 3, "n", PL,
 "tháo to stopa.", "droga stopa"),
("A2", "most", "sà-phaan", "สะพาน", "Orientacja", 4, "n", PL,
 "Także kładka nad ulicą — sà-phaan lawi.", ""),
("A2", "kładka dla pieszych", "sà-phaan lawi", "สะพานลอย", "Orientacja", 3, "n", PL,
 "lawi to unosić się, pływać w powietrzu.", "most unosić się"),
("A1", "aleja, główna ulica", "thà-nǒn yài", "ถนนใหญ่", "Orientacja", 4, "n", PL,
 "W adresie stoi przed nazwą.", "ulica duży"),
("A2", "kilometr", "kì-loo-mét", "กิโลเมตร", "Orientacja", 3, "n", PL,
 "W mowie skracane do samego kì-loo — tak samo jak kilogram.", ""),
("A2", "metr", "mét", "เมตร", "Orientacja", 3, "n", PL,
 "", ""),
("A2", "odległość", "rá-yá thaang", "ระยะทาง", "Orientacja", 3, "n", PL,
 "rá-yá to odstęp — także w czasie.", "odstęp droga"),
("A2", "północ (strona świata)", "nǔea", "เหนือ", "Orientacja", 3, "n", PL,
 "Także „powyżej, ponad”. Region północny to phâak nǔea.", ""),
("A2", "południe (strona świata)", "tâi", "ใต้", "Orientacja", 3, "n", PL,
 "Także „pod”. Region południowy to phâak tâi.", ""),
("A2", "wschód", "tà-wan àwk", "ตะวันออก", "Orientacja", 3, "n", PL,
 "Dosłownie „słońce wychodzi”.", "słońce wychodzić"),
("A2", "zachód", "tà-wan tòk", "ตะวันตก", "Orientacja", 3, "n", PL,
 "Dosłownie „słońce spada”. Stąd „khon tà-wan tòk” — człowiek Zachodu.", "słońce spadać"),
("A2", "przeciwna strona", "fàng trong khâam", "ฝั่งตรงข้าม", "Orientacja", 3, "n", PL,
 "trong khâam to naprzeciwko.", "brzeg naprzeciw"),
("A2", "obok, przy", "khâang khâang", "ข้างๆ", "Orientacja", 4, "adv", PL,
 "Podwojenie khâang osłabia znaczenie do „gdzieś obok”.", "strona strona"),
("A2", "wewnątrz", "khâang nai", "ข้างใน", "Orientacja", 4, "adv", PL,
 "", "strona wewnątrz"),
("A2", "na zewnątrz", "khâang nâwk", "ข้างนอก", "Orientacja", 4, "adv", PL,
 "", "strona zewnątrz"),
("A2", "na wprost, prosto", "trong pai", "ตรงไป", "Orientacja", 5, "adv", PL,
 "Pierwsza odpowiedź na pytanie o drogę.", "prosto iść"),
("A2", "z powrotem", "klàp", "กลับ", "Orientacja", 5, "v", PL,
 "Wracać i odwracać. klàp bâan — wrócić do domu.", ""),
("B1", "gubić się", "lǒng thaang", "หลงทาง", "Orientacja", 3, "v", PL,
 "lǒng samo znaczy też zauroczyć się.", "zabłądzić droga"),
("A2", "mapa", "phǎen thîi", "แผนที่", "Orientacja", 4, "n", PL,
 "phǎen to arkusz, płyta.", "arkusz miejsce"),
("A2", "znak, tablica", "pâai", "ป้าย", "Orientacja", 4, "n", PL,
 "Także przystanek autobusowy: pâai rót mee.", ""),

# ============================================================ MIEJSCA PUBLICZNE
("A1", "targ nocny", "tà-làat klaang khuen", "ตลาดกลางคืน", "Miejsca publiczne", 4, "n", PL,
 "", "targ środek noc"),
("A1", "targ pływający", "tà-làat nám", "ตลาดน้ำ", "Miejsca publiczne", 3, "n", PL,
 "", "targ woda"),
("A2", "centrum handlowe", "hâang", "ห้าง", "Miejsca publiczne", 4, "n", PL,
 "Pełna forma hâang sàp-phá-sǐn-kháa, ale nikt tak nie mówi.", ""),
("A2", "sklep całodobowy", "ráan sà-dùak séu", "ร้านสะดวกซื้อ", "Miejsca publiczne", 3, "n", PL,
 "Dosłownie „sklep wygodnego kupowania”.", "sklep wygodny kupować"),
("A1", "świątynia buddyjska", "wát", "วัด", "Miejsca publiczne", 5, "n", PL,
 "Stoi przed nazwą: Wát Phoo. Także „mierzyć” jako czasownik.", ""),
("A2", "muzeum", "phí-phít-thá-phan", "พิพิธภัณฑ์", "Miejsca publiczne", 3, "n", PL,
 "Cztery sylaby; w mowie pierwsze trzy są ledwie zaznaczone.", ""),
("A2", "pałac", "wang", "วัง", "Miejsca publiczne", 3, "n", PL,
 "Wielki Pałac to Phrá Bà-rom-má-hǎa-râat-chá-wang.", ""),
("A2", "biblioteka", "hâwng sà-mùt", "ห้องสมุด", "Miejsca publiczne", 3, "n", PL,
 "hâwng to pokój — bardzo produktywny przedrostek nazw pomieszczeń.", "pokój księga"),
("A2", "kino", "roong nǎng", "โรงหนัง", "Miejsca publiczne", 4, "n", PL,
 "roong to hala, zakład; nǎng to skóra i film.", "hala film"),
("A2", "teatr", "roong lá-khawn", "โรงละคร", "Miejsca publiczne", 2, "n", PL,
 "lá-khawn to też serial telewizyjny.", "hala przedstawienie"),
("A2", "stadion", "sà-nǎam kii-laa", "สนามกีฬา", "Miejsca publiczne", 3, "n", PL,
 "sà-nǎam to plac, boisko, pole — także sà-nǎam bin (lotnisko).", "plac sport"),
("A2", "plac zabaw", "sà-nǎam dèk lên", "สนามเด็กเล่น", "Miejsca publiczne", 2, "n", PL,
 "", "plac dziecko bawić się"),
("A2", "posterunek policji", "sà-thǎa-nii tam-rùat", "สถานีตำรวจ", "Miejsca publiczne", 4, "n", PL,
 "sà-thǎa-nii to stacja — także kolejowa i telewizyjna.", "stacja policja"),
("A2", "urząd, biuro", "sǎm-nák ngaan", "สำนักงาน", "Miejsca publiczne", 3, "n", PL,
 "", "siedziba praca"),
("A2", "ambasada", "sà-thǎan thûut", "สถานทูต", "Miejsca publiczne", 3, "n", PL,
 "Praktyczne przy zgubionym paszporcie.", "siedziba poseł"),
("A2", "poczta", "prai-sà-nii", "ไปรษณีย์", "Miejsca publiczne", 3, "n", PL,
 "", ""),
("A2", "kantor", "thîi lâek ngoen", "ที่แลกเงิน", "Miejsca publiczne", 4, "n", PL,
 "lâek to wymieniać.", "miejsce wymieniać pieniądze"),
("A2", "pralnia", "ráan sák phâa", "ร้านซักผ้า", "Miejsca publiczne", 3, "n", PL,
 "sák to prać, phâa to tkanina.", "sklep prać tkanina"),
("A2", "fryzjer", "ráan tàt phǒm", "ร้านตัดผม", "Miejsca publiczne", 3, "n", PL,
 "Uwaga: phǒm to tu „włosy”, nie zaimek „ja”. Ten sam zapis, inne słowo.", "sklep ciąć włosy"),
("A2", "salon masażu", "ráan nûat", "ร้านนวด", "Miejsca publiczne", 4, "n", PL,
 "nûat to masować i masaż.", "sklep masaż"),
("A2", "warsztat samochodowy", "ùu sâwm rót", "อู่ซ่อมรถ", "Miejsca publiczne", 2, "n", PL,
 "sâwm to naprawiać — homofon z sâwm (widelec) różniący się tylko pisownią.", "warsztat naprawiać pojazd"),
("A2", "wypożyczalnia", "ráan hâi châo", "ร้านให้เช่า", "Miejsca publiczne", 3, "n", PL,
 "châo to wynajmować — z perspektywy najemcy.", "sklep dawać wynajem"),

# ============================================================ HOTEL
("A1", "recepcja", "phà-nàek tâwn ráp", "แผนกต้อนรับ", "Obsługa", 4, "n", HO,
 "tâwn ráp to witać, przyjmować gości.", "dział witać"),
("A1", "hol, lobby", "láwp-bîi", "ล็อบบี้", "Obsługa", 3, "n", HO,
 "", ""),
("A2", "pokój jednoosobowy", "hâwng dìao", "ห้องเดี่ยว", "Rodzaje pokoi", 4, "n", HO,
 "dìao to pojedynczy, samotny — także „chwila” w khrûu dìao.", "pokój pojedynczy"),
("A2", "pokój dwuosobowy", "hâwng khûu", "ห้องคู่", "Rodzaje pokoi", 4, "n", HO,
 "khûu to para — także o małżonkach i o butach.", "pokój para"),
("A2", "pokój z dwoma łóżkami", "hâwng tiang khûu", "ห้องเตียงคู่", "Rodzaje pokoi", 3, "n", HO,
 "", "pokój łóżko para"),
("A2", "pokój z widokiem na morze", "hâwng wiu thá-lee", "ห้องวิวทะเล", "Rodzaje pokoi", 3, "n", HO,
 "wiu to zapożyczone „view”.", "pokój widok morze"),
("A2", "pokój z balkonem", "hâwng mii rá-biang", "ห้องมีระเบียง", "Rodzaje pokoi", 3, "n", HO,
 "", "pokój mieć balkon"),
("A2", "balkon", "rá-biang", "ระเบียง", "Wyposażenie", 3, "n", HO,
 "Także taras i weranda.", ""),
("A1", "klucz do pokoju", "kun-jae hâwng", "กุญแจห้อง", "Wyposażenie", 4, "n", HO,
 "kun-jae to klucz i zamek.", "klucz pokój"),
("A2", "karta do pokoju", "khâat hâwng", "การ์ดห้อง", "Wyposażenie", 3, "n", HO,
 "", "karta pokój"),
("A2", "sejf", "tûu sêep", "ตู้เซฟ", "Wyposażenie", 3, "n", HO,
 "tûu to szafa — także w rót tûu (minibus) i tûu yen (lodówka).", "szafa sejf"),
("A2", "lodówka", "tûu yen", "ตู้เย็น", "Wyposażenie", 4, "n", HO,
 "Dosłownie „szafa zimna”.", "szafa zimny"),
("A2", "czajnik", "kaa tôm nám", "กาต้มน้ำ", "Wyposażenie", 3, "n", HO,
 "tôm to gotować w wodzie — ten sam czasownik co w tôm yam.", "dzbanek gotować woda"),
("A2", "ręcznik", "phâa chét tua", "ผ้าเช็ดตัว", "Wyposażenie", 4, "n", HO,
 "chét to wycierać, tua to ciało.", "tkanina wycierać ciało"),
("A2", "poduszka", "mǎwn", "หมอน", "Wyposażenie", 4, "n", HO,
 "Uwaga na parę: mǎwn (poduszka) kontra màwn (koc).", ""),
("A2", "koc", "phâa hòm", "ผ้าห่ม", "Wyposażenie", 3, "n", HO,
 "hòm to okrywać się.", "tkanina okrywać"),
("A2", "prześcieradło", "phâa puu thîi nawn", "ผ้าปูที่นอน", "Wyposażenie", 2, "n", HO,
 "puu to rozkładać.", "tkanina rozkładać łóżko"),
("A2", "zasłony", "phâa mâan", "ผ้าม่าน", "Wyposażenie", 2, "n", HO,
 "", "tkanina zasłona"),
("A2", "suszarka do włosów", "thîi pào phǒm", "ที่เป่าผม", "Wyposażenie", 2, "n", HO,
 "pào to dmuchać. thîi- tworzy nazwy narzędzi.", "narzędzie dmuchać włosy"),
("A2", "mydło", "sà-bùu", "สบู่", "Wyposażenie", 3, "n", HO,
 "", ""),
("A2", "papier toaletowy", "krà-dàat cham-rá", "กระดาษชำระ", "Wyposażenie", 3, "n", HO,
 "W mowie częściej po prostu thít-chûu.", "papier oczyszczać"),
("A2", "gniazdko elektryczne", "plák fai", "ปลั๊กไฟ", "Wyposażenie", 3, "n", HO,
 "Napięcie 220 V, wtyczki płaskie i okrągłe w jednym gnieździe.", "wtyczka prąd"),
("A2", "przejściówka", "hǔa plaeng", "หัวแปลง", "Wyposażenie", 2, "n", HO,
 "plaeng to przekształcać, zamieniać.", "głowica przekształcać"),
("A2", "śniadanie w cenie", "ruam aa-hǎan cháo", "รวมอาหารเช้า", "Rezerwacja", 4, "n", HO,
 "ruam to obejmować, wliczać — kluczowe słowo przy pytaniu o cenę.", "obejmować jedzenie rano"),
("A2", "doba hotelowa", "khuen", "คืน", "Rezerwacja", 5, "n", HO,
 "Liczy się nocami, nie dniami: sǎam khuen — trzy noce.", ""),
("A2", "zameldowanie", "wee-laa khâo phák", "เวลาเข้าพัก", "Rezerwacja", 3, "n", HO,
 "phák to odpoczywać, mieszkać tymczasowo.", "czas wchodzić mieszkać"),
("A2", "wymeldowanie", "wee-laa khuen hâwng", "เวลาคืนห้อง", "Rezerwacja", 3, "n", HO,
 "Uwaga: khuen to tu „zwracać”, homofon z khuen (noc). Rozstrzyga kontekst.", "czas zwracać pokój"),
("A2", "kaucja", "ngoen mát jam", "เงินมัดจำ", "Rezerwacja", 3, "n", HO,
 "Zwykle pobierana przy wynajmie skutera i pokoju na dłużej.", "pieniądze zastaw"),
("A2", "potwierdzenie rezerwacji", "bai yuen yan kaan jawng", "ใบยืนยันการจอง", "Rezerwacja", 3, "n", HO,
 "yuen yan to potwierdzać, jawng to rezerwować.", "arkusz potwierdzać rezerwacja"),
("B1", "wolny pokój", "hâwng wâang", "ห้องว่าง", "Rezerwacja", 4, "n", HO,
 "wâang to pusty i wolny — także o czasie: wee-laa wâang.", "pokój wolny"),
("B1", "brak wolnych miejsc", "tem", "เต็ม", "Rezerwacja", 4, "adj", HO,
 "Jedno słowo załatwia „pełny, zajęty, komplet”.", ""),
("B1", "sprzątanie pokoju", "tham khwaam sà-àat hâwng", "ทำความสะอาดห้อง", "Obsługa", 3, "n", HO,
 "sà-àat to czysty; tham khwaam sà-àat to dosłownie „robić czystość”.", "robić czystość pokój"),
("B1", "obsługa pokojowa", "ruum soe-wít", "รูมเซอร์วิส", "Obsługa", 2, "n", HO,
 "", ""),
("B1", "napiwek", "thíp", "ทิป", "Obsługa", 3, "n", HO,
 "Nieobowiązkowy, ale przyjęty w hotelach i masażu.", ""),
]
