# -*- coding: utf-8 -*-
"""Leksyka etapu 4 (B1) — czesc G.

Zakres: zdrowie na poziomie B1 — dokladniejszy opis objawow, czas trwania,
nasilenie, wywiad lekarski, apteka, badania, szpital.

UWAGA: to material jezykowy, nie porada medyczna. Rekordy ucza opisywac
objawy, a nie diagnozowac ani leczyc.

Format jak w lex_b1_core_a.py.
"""

CORE_G = [

# =====================================================================
# OPIS OBJAWOW
# =====================================================================
("Źle się czuję od wczoraj.", "phǒm mâi sà-baai tâng tàae mûea waan khráp",
 "ผมไม่สบายตั้งแต่เมื่อวานครับ", "Zdrowie", "Objawy", "sentence", 5, "n",
 "„mâi sà-baai” obejmuje całe spektrum: od przeziębienia po gorszy nastrój.", "",
 ("Co konkretnie dolega?", "pen à-rai khráp", "เป็นอะไรครับ")),
("Boli mnie tutaj.", "jèp trong níi khráp", "เจ็บตรงนี้ครับ",
 "Zdrowie", "Objawy", "sentence", 5, "n",
 "„jèp” to ból ostry, punktowy. „pùat” to ból tępy, pulsujący — lekarz o to zapyta.", "",
 ("Od jak dawna?", "pen maa naan thâo-rài khráp", "เป็นมานานเท่าไหร่ครับ")),
("To tępy ból.", "man pùat tûue tûue khráp", "มันปวดตื้อๆ ครับ",
 "Zdrowie", "Objawy", "sentence", 3, "n", "„pùat tûue” = ból tępy, głuchy.", "",
 ("Rozumiem.", "khâo-jai khráp", "เข้าใจครับ")),
("Ból przychodzi falami.", "man pùat pen phák pen khraao khráp", "มันปวดเป็นพักเป็นคราวครับ",
 "Zdrowie", "Objawy", "sentence", 3, "n", "„pen phák pen khraao” = z przerwami, napadowo.", "",
 ("Jak często?", "bàwi khâe nǎi khráp", "บ่อยแค่ไหนครับ")),
("Boli, kiedy się poruszam.", "khà-yàp láew jèp khráp", "ขยับแล้วเจ็บครับ",
 "Zdrowie", "Objawy", "sentence", 3, "n", "„khà-yàp” = poruszać się, ruszać częścią ciała.", "",
 ("Proszę pokazać gdzie.", "chíi hâi duu nòi khráp", "ชี้ให้ดูหน่อยครับ")),
("Ból promieniuje do pleców.", "pùat râao pai thîi lǎng khráp", "ปวดร้าวไปที่หลังครับ",
 "Zdrowie", "Objawy", "sentence", 2, "f", "„râao” = promieniować, rozchodzić się.", "",
 ("Zbadam pana.", "khǎw trùat dûai khráp", "ขอตรวจด้วยครับ")),
("Mam gorączkę od dwóch dni.", "phǒm mii khâi maa sǎwng wan láew khráp", "ผมมีไข้มาสองวันแล้วครับ",
 "Zdrowie", "Objawy", "sentence", 4, "n", "„khâi” = gorączka.", "",
 ("Ile stopni?", "kìi ong-sǎa khráp", "กี่องศาครับ")),
("Gorączka wraca wieczorem.", "khâi khûen tawn yen thúk wan khráp", "ไข้ขึ้นตอนเย็นทุกวันครับ",
 "Zdrowie", "Objawy", "sentence", 3, "n", "", "",
 ("Trzeba zrobić badanie.", "tâwng trùat lûeat khráp", "ต้องตรวจเลือดครับ")),
("Mam dreszcze.", "phǒm nǎao sàn khráp", "ผมหนาวสั่นครับ",
 "Zdrowie", "Objawy", "sentence", 3, "n", "„nǎao sàn” = trząść się z zimna.", "",
 ("Proszę się położyć.", "nawn phák kàwn khráp", "นอนพักก่อนครับ")),
("Nie mam apetytu.", "phǒm mâi yàak aa-hǎan khráp", "ผมไม่อยากอาหารครับ",
 "Zdrowie", "Objawy", "sentence", 3, "n", "", "",
 ("Od kiedy?", "tâng tàae mûea-rài khráp", "ตั้งแต่เมื่อไหร่ครับ")),
("Kręci mi się w głowie.", "phǒm wian hǔa khráp", "ผมเวียนหัวครับ",
 "Zdrowie", "Objawy", "sentence", 4, "n", "„wian hǔa” = zawroty głowy.", "",
 ("Proszę usiąść.", "nâng long kàwn khráp", "นั่งลงก่อนครับ")),
("Mam mdłości.", "phǒm khlûen sâi khráp", "ผมคลื่นไส้ครับ",
 "Zdrowie", "Objawy", "sentence", 3, "n", "", "",
 ("Wymiotował pan?", "aa-jian mǎi khráp", "อาเจียนไหมครับ")),
("Nie mogę spać.", "phǒm nawn mâi làp khráp", "ผมนอนไม่หลับครับ",
 "Zdrowie", "Objawy", "sentence", 4, "n",
 "„nawn” = kłaść się, „làp” = zasnąć. Tajski rozdziela te dwa etapy.", "",
 ("Od dawna?", "pen maa naan mǎi khráp", "เป็นมานานไหมครับ")),
("Jestem ciągle zmęczony.", "phǒm nùeai tà-làwt wee-laa khráp", "ผมเหนื่อยตลอดเวลาครับ",
 "Zdrowie", "Objawy", "sentence", 3, "n", "", "",
 ("Trzeba to sprawdzić.", "tâwng trùat duu khráp", "ต้องตรวจดูครับ")),
("Mam wysypkę na skórze.", "phǒm mii phùen thîi phǐu khráp", "ผมมีผื่นที่ผิวครับ",
 "Zdrowie", "Objawy", "sentence", 3, "n", "„phùen” = wysypka, „phǐu” = skóra.", "",
 ("Swędzi?", "khan mǎi khráp", "คันไหมครับ")),
("Spuchła mi noga.", "khǎa phǒm buam khráp", "ขาผมบวมครับ",
 "Zdrowie", "Objawy", "sentence", 3, "n", "„buam” = opuchnięty.", "",
 ("Proszę pokazać.", "khǎw duu nòi khráp", "ขอดูหน่อยครับ")),
("Trudno mi oddychać.", "hǎai jai mâi khâwi àwk khráp", "หายใจไม่ค่อยออกครับ",
 "Zdrowie", "Objawy", "sentence", 2, "n",
 "To objaw pilny. Jeśli nasila się nagle, jedź na izbę przyjęć, nie do apteki.", "",
 ("Idziemy do lekarza teraz.", "pai hǎa mǎw dǐao níi khráp", "ไปหาหมอเดี๋ยวนี้ครับ")),
("Mam biegunkę od rana.", "phǒm tháwng sǐa tâng tàae cháo khráp", "ผมท้องเสียตั้งแต่เช้าครับ",
 "Zdrowie", "Objawy", "sentence", 4, "n", "„tháwng sǐa” = rozstrój żołądka.", "",
 ("Pij dużo wody.", "dùem náam yóe yóe ná khráp", "ดื่มน้ำเยอะๆ นะครับ")),
("Chyba coś mi zaszkodziło.", "khong phǎe aa-hǎan khráp", "คงแพ้อาหารครับ",
 "Zdrowie", "Objawy", "sentence", 3, "n", "„phǎe” = uczulenie, ale też: nietolerancja.", "",
 ("Co pan jadł?", "kin à-rai maa khráp", "กินอะไรมาครับ")),
("Objawy się nasilają.", "aa-kaan nàk khûen khráp", "อาการหนักขึ้นครับ",
 "Zdrowie", "Objawy", "sentence", 3, "f", "„aa-kaan” = objawy, stan chorobowy.", "",
 ("Chodźmy do szpitala.", "pai roong-phá-yaa-baan khráp", "ไปโรงพยาบาลครับ")),
("Trochę mi się poprawiło.", "aa-kaan dii khûen nòi nùeng khráp", "อาการดีขึ้นหน่อยหนึ่งครับ",
 "Zdrowie", "Objawy", "sentence", 3, "n", "", "",
 ("To dobrze.", "dii khráp", "ดีครับ")),

# =====================================================================
# U LEKARZA
# =====================================================================
("Chciałbym się umówić do lekarza.", "phǒm yàak nát phóp mǎw khráp", "ผมอยากนัดพบหมอครับ",
 "Zdrowie", "Lekarz", "sentence", 4, "f", "„nát phóp” = umówić wizytę.", "",
 ("Kiedy panu pasuje?", "sà-dùak wan nǎi khráp", "สะดวกวันไหนครับ")),
("Czy jest lekarz mówiący po angielsku?", "mii mǎw thîi phûut ang-krìt dâai mǎi khráp",
 "มีหมอที่พูดอังกฤษได้ไหมครับ", "Zdrowie", "Lekarz", "question", 4, "n", "", "",
 ("Jest, chwileczkę.", "mii khráp raw sàk khrûu", "มีครับ รอสักครู่")),
("Biorę leki na nadciśnienie.", "phǒm kin yaa khwaam dan lôhìt khráp", "ผมกินยาความดันโลหิตครับ",
 "Zdrowie", "Lekarz", "sentence", 2, "f", "„khwaam dan lôhìt” = ciśnienie krwi.", "",
 ("Jaką dawkę?", "khà-nàat thâo-rài khráp", "ขนาดเท่าไหร่ครับ")),
("Jestem uczulony na antybiotyki.", "phǒm phǎe yaa pà-tì-chii-wá-ná khráp", "ผมแพ้ยาปฏิชีวนะครับ",
 "Zdrowie", "Lekarz", "sentence", 3, "f",
 "To zdanie warto umieć powiedzieć bezbłędnie. Zapisz je też na kartce w portfelu.", "",
 ("Zanotuję.", "dǐao bantúek wái khráp", "เดี๋ยวบันทึกไว้ครับ")),
("Nie choruję przewlekle.", "phǒm mâi mii rôhk prà-jam tua khráp", "ผมไม่มีโรคประจำตัวครับ",
 "Zdrowie", "Lekarz", "sentence", 3, "f", "„rôhk prà-jam tua” = choroba przewlekła.", "",
 ("To dobrze.", "dii khráp", "ดีครับ")),
("Czy muszę zrobić badania?", "tâwng trùat à-rai bâang mǎi khráp", "ต้องตรวจอะไรบ้างไหมครับ",
 "Zdrowie", "Lekarz", "question", 3, "f", "", "",
 ("Badanie krwi.", "trùat lûeat khráp", "ตรวจเลือดครับ")),
("Kiedy będą wyniki?", "phǒn trùat àwk mûea-rài khráp", "ผลตรวจออกเมื่อไหร่ครับ",
 "Zdrowie", "Lekarz", "question", 3, "f", "„phǒn trùat” = wynik badania.", "",
 ("Jutro po południu.", "phrûng níi bàai khráp", "พรุ่งนี้บ่ายครับ")),
("Czy to coś poważnego?", "man nàk mǎi khráp", "มันหนักไหมครับ",
 "Zdrowie", "Lekarz", "question", 4, "n", "", "",
 ("Nie, spokojnie.", "mâi nàk khráp sà-baai jai dâai", "ไม่หนักครับ สบายใจได้")),
("Ile dni mam brać ten lek?", "kin yaa níi kìi wan khráp", "กินยานี้กี่วันครับ",
 "Zdrowie", "Apteka", "question", 4, "n",
 "W tajskim leki się „je” (kin yaa), nie „bierze”. Kalka z polskiego brzmiałaby dziwnie.", "",
 ("Przez pięć dni.", "hâa wan khráp", "ห้าวันครับ")),
("Przed jedzeniem czy po?", "kàwn aa-hǎan rǔe lǎng aa-hǎan khráp", "ก่อนอาหารหรือหลังอาหารครับ",
 "Zdrowie", "Apteka", "question", 4, "n", "", "",
 ("Po jedzeniu.", "lǎng aa-hǎan khráp", "หลังอาหารครับ")),
("Czy ten lek daje senność?", "yaa níi tham hâi ngûang mǎi khráp", "ยานี้ทำให้ง่วงไหมครับ",
 "Zdrowie", "Apteka", "question", 3, "n", "", "",
 ("Trochę tak.", "ngûang nít nòi khráp", "ง่วงนิดหน่อยครับ")),
("Czy mogę prowadzić po tym leku?", "kin yaa níi láew khàp rót dâai mǎi khráp",
 "กินยานี้แล้วขับรถได้ไหมครับ", "Zdrowie", "Apteka", "question", 3, "n", "", "",
 ("Lepiej nie.", "mâi khuan khráp", "ไม่ควรครับ")),
("Czy potrzebna jest recepta?", "tâwng chái bai sàng yaa mǎi khráp", "ต้องใช้ใบสั่งยาไหมครับ",
 "Zdrowie", "Apteka", "question", 3, "f", "„bai sàng yaa” = recepta.", "",
 ("Nie trzeba.", "mâi tâwng khráp", "ไม่ต้องครับ")),
("Mam ubezpieczenie podróżne.", "phǒm mii prà-kan kaan dòoen thaang khráp",
 "ผมมีประกันการเดินทางครับ", "Zdrowie", "Lekarz", "sentence", 3, "f", "", "",
 ("Proszę o polisę.", "khǎw èek-kà-sǎan prà-kan dûai khráp", "ขอเอกสารประกันด้วยครับ")),
("Czy szpital wystawi zaświadczenie?", "roong-phá-yaa-baan àwk bai ráp-rawng dâai mǎi khráp",
 "โรงพยาบาลออกใบรับรองได้ไหมครับ", "Zdrowie", "Lekarz", "question", 2, "f", "", "",
 ("Tak, przy kasie.", "dâai khráp thîi kaao-nôoe", "ได้ครับ ที่เคาน์เตอร์")),
("Muszę iść na izbę przyjęć.", "phǒm tâwng pai hâwng chùk-chǒoen khráp", "ผมต้องไปห้องฉุกเฉินครับ",
 "Zdrowie", "Lekarz", "sentence", 3, "f", "„chùk-chǒoen” = nagły wypadek.", "",
 ("Zawiozę pana.", "dǐao phaa pai khráp", "เดี๋ยวพาไปครับ")),
("Proszę wezwać pogotowie.", "chûai rîak rót phá-yaa-baan dûai khráp", "ช่วยเรียกรถพยาบาลด้วยครับ",
 "Zdrowie", "Lekarz", "sentence", 2, "f",
 "Numer alarmowy do pogotowia w Tajlandii to 1669.", "",
 ("Już dzwonię.", "thoo láew khráp", "โทรแล้วครับ")),
("Odpoczywam i piję dużo wody.", "phǒm phák láew dùem náam yóe khráp", "ผมพักแล้วดื่มน้ำเยอะครับ",
 "Zdrowie", "Objawy", "sentence", 3, "n", "", "",
 ("Bardzo dobrze.", "dii mâak khráp", "ดีมากครับ")),
("Wracam do zdrowia.", "phǒm khôi hǎai láew khráp", "ผมค่อยหายแล้วครับ",
 "Zdrowie", "Objawy", "sentence", 3, "n", "„hǎai” = wyzdrowieć, ustąpić.", "",
 ("Cieszę się.", "dii jai dûai khráp", "ดีใจด้วยครับ")),
]
