# -*- coding: utf-8 -*-
"""Leksyka etapu 2 — domkniecie poziomu A1.

Rekord rdzenny (lista CORE2S), krotka:
    (pl, ph, th, kategoria, podkategoria, typ, frequency, notatka, literal, przyklad)

Przyklad ma dwie dozwolone postacie:
    ("Polskie zdanie.", "NAZWA_WZORCA")        -> tajska strona z PAT w stage2.py
    ("Polskie zdanie.", "fonetyka", "tajski")  -> wpisana recznie

Polska strona przykladu ZAWSZE jest pisana recznie i odmieniona — dlatego
nie powstaja artefakty w rodzaju „Chcialbym woda".
"""

CORE2S = [

# =====================================================================
# POGODA I PRZYRODA
# =====================================================================
("pogoda", "aa-kàat", "อากาศ", "Pogoda i przyroda", "Pogoda", "word", 5,
 "To samo słowo znaczy też „powietrze”.", "",
 ("Jaka jest dziś pogoda?", "wan níi aa-kàat pen yang-ngai khráp", "วันนี้อากาศเป็นยังไงครับ")),
("deszcz", "fǒn", "ฝน", "Pogoda i przyroda", "Pogoda", "word", 5,
 "Samo „fǒn” to deszcz; „fǒn tòk” znaczy „pada”.", "",
 ("Wygląda na to, że będzie deszcz.", "thâa thaang fǒn jà tòk", "ท่าทางฝนจะตก")),
("burza", "phaa-yú", "พายุ", "Pogoda i przyroda", "Pogoda", "word", 3, "", "",
 ("Nadciąga burza.", "phaa-yú kamlang maa", "พายุกำลังมา")),
("wiatr", "lom", "ลม", "Pogoda i przyroda", "Pogoda", "word", 4, "", "",
 ("Wieje mocny wiatr.", "lom raeng mâak", "ลมแรงมาก")),
("chmura", "mêek", "เมฆ", "Pogoda i przyroda", "Pogoda", "word", 3, "", "",
 ("Dziś jest pochmurno.", "wan níi mii mêek mâak", "วันนี้มีเมฆมาก")),
("słońce", "phrá aa-thít", "พระอาทิตย์", "Pogoda i przyroda", "Przyroda", "word", 4, "", "",
 ("Słońce już zaszło.", "phrá aa-thít tòk din láew", "พระอาทิตย์ตกดินแล้ว")),
("ostre słońce", "dàet", "แดด", "Pogoda i przyroda", "Pogoda", "word", 4,
 "„dàet” to konkretnie żar słoneczny, nie sama gwiazda.", "",
 ("Dziś mocno praży.", "wan níi dàet ráwn mâak", "วันนี้แดดร้อนมาก")),
("niebo", "fáa", "ฟ้า", "Pogoda i przyroda", "Przyroda", "word", 3, "", "",
 ("Niebo jest dziś czyste.", "wan níi fáa sǎi", "วันนี้ฟ้าใส")),
("parasol", "rôm", "ร่ม", "Pogoda i przyroda", "Pogoda", "word", 4,
 "To samo słowo znaczy „cień”.", "",
 ("Wziąłeś parasol?", "ao rôm maa mǎi khráp", "เอาร่มมาไหมครับ")),
("pora deszczowa", "nâa fǒn", "หน้าฝน", "Pogoda i przyroda", "Pogoda", "word", 4,
 "Trwa mniej więcej od maja do października.", "nâa = pora, sezon",
 ("Teraz jest pora deszczowa.", "tawn níi pen nâa fǒn", "ตอนนี้เป็นหน้าฝน")),
("pora sucha", "nâa láeng", "หน้าแล้ง", "Pogoda i przyroda", "Pogoda", "word", 3, "", "",
 ("W porze suchej jest bardzo gorąco.", "nâa láeng ráwn mâak", "หน้าแล้งร้อนมาก")),
("parno, duszno", "òp-âao", "อบอ้าว", "Pogoda i przyroda", "Pogoda", "word", 3, "", "",
 ("Dziś jest strasznie duszno.", "wan níi òp-âao mâak", "วันนี้อบอ้าวมาก")),
("wilgotno", "chúen", "ชื้น", "Pogoda i przyroda", "Pogoda", "word", 3, "", "",
 ("W pokoju jest wilgotno.", "nai hâwng chúen", "ในห้องชื้น")),
("mokry", "pìak", "เปียก", "Pogoda i przyroda", "Pogoda", "word", 3, "", "",
 ("Cały przemokłem.", "phǒm pìak mòt loei", "ผมเปียกหมดเลย")),
("suchy", "hâeng", "แห้ง", "Pogoda i przyroda", "Pogoda", "word", 3, "", "",
 ("Pranie jest już suche.", "phâa hâeng láew", "ผ้าแห้งแล้ว")),
("temperatura", "ùn-hà-phuum", "อุณหภูมิ", "Pogoda i przyroda", "Pogoda", "word", 3, "", "",
 ("Jaka jest dziś temperatura?", "wan níi ùn-hà-phuum thâo-rài khráp", "วันนี้อุณหภูมิเท่าไหร่ครับ")),
("drzewo", "tôn máai", "ต้นไม้", "Pogoda i przyroda", "Przyroda", "word", 3, "", "",
 ("Usiądźmy pod drzewem.", "nâng tâi tôn máai kan", "นั่งใต้ต้นไม้กัน")),
("kwiat", "dàwk máai", "ดอกไม้", "Pogoda i przyroda", "Przyroda", "word", 3, "", "",
 ("Te kwiaty pięknie pachną.", "dàwk máai hǎwm mâak", "ดอกไม้หอมมาก")),
("rzeka", "mâe náam", "แม่น้ำ", "Pogoda i przyroda", "Przyroda", "word", 3, "", "mâe = matka; náam = woda",
 ("Nad rzeką jest chłodniej.", "thîi mâe náam yen kwàa", "ที่แม่น้ำเย็นกว่า")),
("wodospad", "náam tòk", "น้ำตก", "Pogoda i przyroda", "Przyroda", "word", 3, "", "",
 ("Chcę zobaczyć wodospad.", "phǒm yàak pai duu náam tòk", "ผมอยากไปดูน้ำตก")),
("las", "pàa", "ป่า", "Pogoda i przyroda", "Przyroda", "word", 3, "", "",
 ("W lesie jest dużo komarów.", "nai pàa mii yung yə\u0301ə", "ในป่ามียุงเยอะ")),
("komar", "yung", "ยุง", "Pogoda i przyroda", "Zwierzęta", "word", 4, "", "",
 ("Ugryzł mnie komar.", "yung kàt khráp", "ยุงกัดครับ")),
("pies", "mǎa", "หมา", "Pogoda i przyroda", "Zwierzęta", "word", 4,
 "Uprzejmiej: „sù-nák”. „mǎa” jest potoczne, ale słyszy się je najczęściej.", "",
 ("Ten pies jest przyjazny.", "mǎa tua níi jai dii", "หมาตัวนี้ใจดี")),
("kot", "maew", "แมว", "Pogoda i przyroda", "Zwierzęta", "word", 3, "", "",
 ("Mam w domu kota.", "thîi bâan mii maew", "ที่บ้านมีแมว")),
("słoń", "cháang", "ช้าง", "Pogoda i przyroda", "Zwierzęta", "word", 3, "", "",
 ("Gdzie można zobaczyć słonie?", "duu cháang dâai thîi nǎi khráp", "ดูช้างได้ที่ไหนครับ")),
("małpa", "ling", "ลิง", "Pogoda i przyroda", "Zwierzęta", "word", 3, "", "",
 ("Uważaj na małpy.", "rá-wang ling ná khráp", "ระวังลิงนะครับ")),
("ptak", "nók", "นก", "Pogoda i przyroda", "Zwierzęta", "word", 2, "", "",
 ("Rano słychać ptaki.", "tawn cháo mii sǐang nók", "ตอนเช้ามีเสียงนก")),
("wąż", "nguu", "งู", "Pogoda i przyroda", "Zwierzęta", "word", 2, "", "",
 ("Boję się węży.", "phǒm klua nguu", "ผมกลัวงู")),
("Dziś jest bardzo gorąco.", "wan níi ráwn mâak", "วันนี้ร้อนมาก",
 "Pogoda i przyroda", "Pogoda", "sentence", 5, "Zdanie, które usłyszysz codziennie.", "",
 ("Rzeczywiście, bardzo gorąco.", "ráwn mâak jing jing khráp", "ร้อนมากจริงๆ ครับ")),
("Pada mocno.", "fǒn tòk nàk", "ฝนตกหนัก", "Pogoda i przyroda", "Pogoda", "sentence", 4, "", "nàk = ciężko, mocno",
 ("Weź parasol.", "ao rôm pai dûai khráp", "เอาร่มไปด้วยครับ")),
("Deszcz już przestał.", "fǒn yùt láew", "ฝนหยุดแล้ว", "Pogoda i przyroda", "Pogoda", "sentence", 4, "", "yùt = zatrzymać się",
 ("To możemy już iść.", "pai kan dâai láew khráp", "ไปกันได้แล้วครับ")),
("Czy jutro będzie padać?", "phrûng níi fǒn jà tòk mǎi khráp", "พรุ่งนี้ฝนจะตกไหมครับ",
 "Pogoda i przyroda", "Pogoda", "question", 4, "", "",
 ("Chyba tak.", "khít wâa tòk khráp", "คิดว่าตกครับ")),
("Poczekam, aż przestanie padać.", "phǒm jà raw hâi fǒn yùt kàwn", "ผมจะรอให้ฝนหยุดก่อน",
 "Pogoda i przyroda", "Pogoda", "sentence", 3, "", "kàwn = najpierw, zanim",
 ("Dobrze, poczekajmy.", "raw kan kàwn khráp", "รอกันก่อนครับ")),
("Zrobiło się chłodniej.", "aa-kàat yen long láew", "อากาศเย็นลงแล้ว",
 "Pogoda i przyroda", "Pogoda", "sentence", 3, "", "long = w dół (spadek)",
 ("Wieczorem jest przyjemnie.", "tawn yen sà-baai khráp", "ตอนเย็นสบายครับ")),
("Dziś jest słonecznie.", "wan níi dàet àwk", "วันนี้แดดออก", "Pogoda i przyroda", "Pogoda", "sentence", 4, "", "àwk = wyjść, pojawić się",
 ("Idziemy na plażę.", "pai tha-lee kan khráp", "ไปทะเลกันครับ")),

# =====================================================================
# PYTANIA
# =====================================================================
("Jak długo?", "naan thâo-rài khráp", "นานเท่าไหร่ครับ", "Pytania", "Słowa pytające", "question", 5, "", "naan = długo (o czasie)",
 ("Jakieś dwie godziny.", "pramaan sǎwng chûa-moong khráp", "ประมาณสองชั่วโมงครับ")),
("Jak daleko?", "klai thâo-rài khráp", "ไกลเท่าไหร่ครับ", "Pytania", "Słowa pytające", "question", 5,
 "Uwaga: „klai” (daleko) i „klâi” (blisko) różni wyłącznie ton.", "",
 ("Około dwóch kilometrów.", "pramaan sǎwng kì-loo khráp", "ประมาณสองกิโลครับ")),
("Jak często?", "bòi khâe nǎi khráp", "บ่อยแค่ไหนครับ", "Pytania", "Słowa pytające", "question", 3, "", "khâe nǎi = w jakim stopniu",
 ("Mniej więcej raz w tygodniu.", "pramaan aa-thít lá khráng khráp", "ประมาณอาทิตย์ละครั้งครับ")),
("O której godzinie?", "kìi moong khráp", "กี่โมงครับ", "Pytania", "Słowa pytające", "question", 5, "", "",
 ("O ósmej rano.", "pàet moong cháo khráp", "แปดโมงเช้าครับ")),
("Ile masz lat?", "aa-yú thâo-rài khráp", "อายุเท่าไหร่ครับ", "Pytania", "Słowa pytające", "question", 4,
 "Pytanie o wiek nie jest w Tajlandii nietaktem.", "",
 ("Mam trzydzieści lat.", "phǒm aa-yú sǎam-sìp pii khráp", "ผมอายุสามสิบปีครับ")),
("Z kim?", "kàp khrai khráp", "กับใครครับ", "Pytania", "Słowa pytające", "question", 3, "", "",
 ("Z przyjacielem.", "kàp phûean khráp", "กับเพื่อนครับ")),
("Dla kogo?", "sǎmràp khrai khráp", "สำหรับใครครับ", "Pytania", "Słowa pytające", "question", 3, "", "",
 ("Dla mnie.", "sǎmràp phǒm khráp", "สำหรับผมครับ")),
("Czyje to jest?", "khǎwng khrai khráp", "ของใครครับ", "Pytania", "Słowa pytające", "question", 3, "", "khǎwng = rzecz, własność",
 ("To moje.", "khǎwng phǒm khráp", "ของผมครับ")),
("Dokąd idziesz?", "pai nǎi khráp", "ไปไหนครับ", "Pytania", "Słowa pytające", "question", 5,
 "Częściej jest to zwykłe powitanie niż realne pytanie. Wystarczy odpowiedzieć ogólnikowo.", "",
 ("Tak sobie, kawałek dalej.", "pai thǎew níi khráp", "ไปแถวนี้ครับ")),
("Co robisz?", "tham à-rai yùu khráp", "ทำอะไรอยู่ครับ", "Pytania", "Słowa pytające", "question", 4, "", "yùu na końcu = właśnie teraz",
 ("Nic szczególnego.", "mâi dâai tham à-rai khráp", "ไม่ได้ทำอะไรครับ")),
("Naprawdę?", "jing rǔe khráp", "จริงเหรอครับ", "Pytania", "Reakcje", "question", 4, "", "",
 ("Naprawdę.", "jing jing khráp", "จริงๆ ครับ")),
("Który z nich?", "an nǎi khráp", "อันไหนครับ", "Pytania", "Słowa pytające", "question", 4, "", "an = uniwersalny klasyfikator",
 ("Ten tutaj.", "an níi khráp", "อันนี้ครับ")),
("Gdzie dokładnie?", "trong nǎi khráp", "ตรงไหนครับ", "Pytania", "Słowa pytające", "question", 4, "", "trong = dokładnie w tym miejscu",
 ("O, tam.", "trong nán khráp", "ตรงนั้นครับ")),
("Ile to razem?", "tháng mòt thâo-rài khráp", "ทั้งหมดเท่าไหร่ครับ", "Pytania", "Słowa pytające", "question", 5, "", "tháng mòt = w sumie",
 ("Razem dwieście bahtów.", "tháng mòt sǎwng ráwi bàat khráp", "ทั้งหมดสองร้อยบาทครับ")),
("Jak się tego używa?", "chái yang-ngai khráp", "ใช้ยังไงครับ", "Pytania", "Słowa pytające", "question", 3, "", "",
 ("Pokażę ci.", "dǐao tham hâi duu khráp", "เดี๋ยวทำให้ดูครับ")),
("Co się stało?", "pen à-rai khráp", "เป็นอะไรครับ", "Pytania", "Reakcje", "question", 4,
 "Tego samego zwrotu używa się, pytając kogoś, czy nic mu nie jest.", "",
 ("Nic mi nie jest.", "mâi pen rai khráp", "ไม่เป็นไรครับ")),
("Kiedy przyjedzie?", "jà maa mûea-rài khráp", "จะมาเมื่อไหร่ครับ", "Pytania", "Słowa pytające", "question", 4, "", "",
 ("Za dziesięć minut.", "ìik sìp naa-thii khráp", "อีกสิบนาทีครับ")),
]

CORE2S += [

# =====================================================================
# LUDZIE I RODZINA
# =====================================================================
("rodzice", "phâw mâe", "พ่อแม่", "Ludzie i rodzina", "Rodzina", "word", 4, "", "dosłownie: ojciec-matka",
 ("Moi rodzice mieszkają w Polsce.", "phâw mâe yùu thîi poo-laen", "พ่อแม่อยู่ที่โปแลนด์")),
("babcia", "yâai", "ยาย", "Ludzie i rodzina", "Rodzina", "word", 3,
 "„yâai” to mama mamy. Mama taty to „yâa”.", "",
 ("To jest moja babcia.", "nîi yâai khǎwng phǒm khráp", "นี่ยายของผมครับ")),
("dziadek", "taa", "ตา", "Ludzie i rodzina", "Rodzina", "word", 3,
 "„taa” to tata mamy. Tata taty to „pùu”.", "",
 ("Mój dziadek ma osiemdziesiąt lat.", "taa aa-yú pàet-sìp pii", "ตาอายุแปดสิบปี")),
("wnuk, wnuczka", "lǎan", "หลาน", "Ludzie i rodzina", "Rodzina", "word", 3,
 "Tym samym słowem określa się siostrzeńca i bratanka.", "",
 ("Mam dwoje wnuków.", "mii lǎan sǎwng khon", "มีหลานสองคน")),
("wujek", "lung", "ลุง", "Ludzie i rodzina", "Rodzina", "word", 3,
 "Starszy brat rodzica. Tak zwraca się też uprzejmie do starszego mężczyzny.", "",
 ("To mój wujek.", "nîi lung khǎwng phǒm khráp", "นี่ลุงของผมครับ")),
("ciocia", "pâa", "ป้า", "Ludzie i rodzina", "Rodzina", "word", 3,
 "Starsza siostra rodzica. Uprzejme zwrócenie się do starszej kobiety, np. na targu.", "",
 ("Ciociu, poproszę dwie sztuki.", "pâa khǎw sǎwng an khráp", "ป้า ขอสองอันครับ")),
("ciocia, wujek (młodsi od rodzica)", "náa", "น้า", "Ludzie i rodzina", "Rodzina", "word", 3,
 "Młodsze rodzeństwo mamy — bez rozróżnienia płci.", "",
 ("Moja ciocia mieszka w Bangkoku.", "náa yùu krung-thêep", "น้าอยู่กรุงเทพ")),
("rodzeństwo", "phîi náwng", "พี่น้อง", "Ludzie i rodzina", "Rodzina", "word", 3, "", "dosłownie: starsi-młodsi",
 ("Masz rodzeństwo?", "mii phîi náwng mǎi khráp", "มีพี่น้องไหมครับ")),
("sąsiad", "phûean bâan", "เพื่อนบ้าน", "Ludzie i rodzina", "Relacje", "word", 3, "", "dosłownie: przyjaciel domu",
 ("Mój sąsiad jest bardzo miły.", "phûean bâan jai dii mâak", "เพื่อนบ้านใจดีมาก")),
("kolega z pracy", "phûean rûam ngaan", "เพื่อนร่วมงาน", "Ludzie i rodzina", "Relacje", "word", 3, "", "",
 ("Idę z kolegami z pracy.", "pai kàp phûean rûam ngaan", "ไปกับเพื่อนร่วมงาน")),
("szef", "jâo naai", "เจ้านาย", "Ludzie i rodzina", "Relacje", "word", 3, "", "",
 ("Mój szef jest dziś nieobecny.", "jâo naai mâi yùu wan níi", "เจ้านายไม่อยู่วันนี้")),
("wiek", "aa-yú", "อายุ", "Ludzie i rodzina", "Dane osobowe", "word", 4, "", "",
 ("Ile masz lat?", "aa-yú thâo-rài khráp", "อายุเท่าไหร่ครับ")),
("Mam trzydzieści lat.", "phǒm aa-yú sǎam-sìp pii", "ผมอายุสามสิบปี",
 "Ludzie i rodzina", "Dane osobowe", "sentence", 4, "Wystarczy podmienić liczbę.", "pii = rok, lata",
 ("A ile ty masz lat?", "láew khun aa-yú thâo-rài khráp", "แล้วคุณอายุเท่าไหร่ครับ")),
("Jestem żonaty.", "phǒm tàeng ngaan láew", "ผมแต่งงานแล้ว",
 "Ludzie i rodzina", "Relacje", "sentence", 3, "Kobieta powie „chǎn tàeng ngaan láew”.", "tàeng ngaan = brać ślub",
 ("Od pięciu lat.", "hâa pii láew khráp", "ห้าปีแล้วครับ")),
("Jestem singlem.", "phǒm pen sòot", "ผมเป็นโสด", "Ludzie i rodzina", "Relacje", "sentence", 3, "", "sòot = stanu wolnego",
 ("Ja też.", "phǒm kâw mǔean kan khráp", "ผมก็เหมือนกันครับ")),
("Mam dwoje dzieci.", "phǒm mii lûuk sǎwng khon", "ผมมีลูกสองคน",
 "Ludzie i rodzina", "Rodzina", "sentence", 4, "", "khon = klasyfikator dla ludzi",
 ("Chłopiec i dziewczynka.", "phûu chaai khon nùeng phûu yǐng khon nùeng", "ผู้ชายคนหนึ่ง ผู้หญิงคนหนึ่ง")),
("Nie mam dzieci.", "phǒm mâi mii lûuk", "ผมไม่มีลูก", "Ludzie i rodzina", "Rodzina", "sentence", 3, "", "",
 ("Jeszcze nie.", "yang mâi mii khráp", "ยังไม่มีครับ")),
("Mieszkam sam.", "phǒm yùu khon diao", "ผมอยู่คนเดียว", "Ludzie i rodzina", "Relacje", "sentence", 3, "", "khon diao = sam, w pojedynkę",
 ("Nie nudzi ci się?", "ngǎo mǎi khráp", "เหงาไหมครับ")),

# =====================================================================
# SMALL TALK
# =====================================================================
("Czym się zajmujesz?", "tham ngaan à-rai khráp", "ทำงานอะไรครับ", "Small talk", "Poznawanie ludzi", "question", 4, "", "",
 ("Pracuję w biurze.", "phǒm tham ngaan thîi áwf-fít khráp", "ผมทำงานที่ออฟฟิศครับ")),
("Pracuję w biurze.", "phǒm tham ngaan thîi áwf-fít", "ผมทำงานที่ออฟฟิศ", "Small talk", "Poznawanie ludzi", "sentence", 3, "", "",
 ("A ty?", "láew khun lâ khráp", "แล้วคุณล่ะครับ")),
("Jestem tu służbowo.", "phǒm maa tham ngaan khráp", "ผมมาทำงานครับ", "Small talk", "Poznawanie ludzi", "sentence", 3, "", "",
 ("Na jak długo?", "maa naan thâo-rài khráp", "มานานเท่าไหร่ครับ")),
("Jak długo już tu jesteś?", "yùu thîi nîi naan thâo-rài láew khráp", "อยู่ที่นี่นานเท่าไหร่แล้วครับ",
 "Small talk", "Poznawanie ludzi", "question", 3, "", "",
 ("Od tygodnia.", "nùeng aa-thít láew khráp", "หนึ่งอาทิตย์แล้วครับ")),
("Jestem tu od tygodnia.", "phǒm yùu thîi nîi nùeng aa-thít láew", "ผมอยู่ที่นี่หนึ่งอาทิตย์แล้ว",
 "Small talk", "Poznawanie ludzi", "sentence", 3, "", "láew = już (stan trwa)",
 ("I jak ci się podoba?", "châwp mǎi khráp", "ชอบไหมครับ")),
("Zostaję dwa tygodnie.", "phǒm jà yùu sǎwng aa-thít", "ผมจะอยู่สองอาทิตย์",
 "Small talk", "Poznawanie ludzi", "sentence", 3, "", "",
 ("To jeszcze sporo czasu.", "yang mii weelaa ìik yə\u0301ə khráp", "ยังมีเวลาอีกเยอะครับ")),
("Bardzo lubię Tajlandię.", "phǒm châwp mueang thai mâak", "ผมชอบเมืองไทยมาก",
 "Small talk", "Poznawanie ludzi", "sentence", 4, "„mueang thai” to potoczna, cieplejsza nazwa kraju.", "",
 ("Co lubisz najbardziej?", "châwp à-rai thîi sùt khráp", "ชอบอะไรที่สุดครับ")),
("Jedzenie tutaj jest pyszne.", "aa-hǎan thîi nîi à-ròi mâak", "อาหารที่นี่อร่อยมาก",
 "Small talk", "Reakcje", "sentence", 4, "Komplement, który zawsze działa.", "",
 ("Dziękuję bardzo.", "khàwp-khun mâak khráp", "ขอบคุณมากครับ")),
("Uczę się tajskiego.", "phǒm kamlang rian phaa-sǎa thai", "ผมกำลังเรียนภาษาไทย",
 "Small talk", "Poznawanie ludzi", "sentence", 4, "", "kamlang = właśnie teraz (czynność w toku)",
 ("Mówisz bardzo dobrze.", "phûut dâai dii mâak khráp", "พูดได้ดีมากครับ")),
("Rozumiem tylko trochę.", "phǒm khâo jai nít nòi", "ผมเข้าใจนิดหน่อย",
 "Small talk", "Poznawanie ludzi", "sentence", 4, "", "khâo jai = rozumieć",
 ("Będę mówić wolniej.", "jà phûut cháa cháa khráp", "จะพูดช้าๆ ครับ")),
("Miło było cię poznać.", "dii jai thîi dâai rúu-jàk khráp", "ดีใจที่ได้รู้จักครับ",
 "Small talk", "Pożegnania", "phrase", 4, "", "dii jai = cieszyć się",
 ("Mnie również.", "chên kan khráp", "เช่นกันครับ")),
("Powodzenia!", "chôok dii", "โชคดี", "Small talk", "Pożegnania", "phrase", 4,
 "Mówi się to również zamiast „do widzenia”.", "dosłownie: dobry los",
 ("Dziękuję, nawzajem.", "khàwp-khun khráp chên kan", "ขอบคุณครับ เช่นกัน")),
("Uważaj na siebie.", "duu lae tua eeng dûai ná khráp", "ดูแลตัวเองด้วยนะครับ",
 "Small talk", "Pożegnania", "phrase", 3, "", "duu lae = dbać, opiekować się",
 ("Ty też.", "khun kâw dûai ná khráp", "คุณก็ด้วยนะครับ")),
("Gratulacje!", "yin dii dûai khráp", "ยินดีด้วยครับ", "Small talk", "Reakcje", "phrase", 3, "", "",
 ("Dziękuję bardzo.", "khàwp-khun mâak khráp", "ขอบคุณมากครับ")),
("Wszystkiego najlepszego!", "sùk sǎn wan kə\u0300ət", "สุขสันต์วันเกิด", "Small talk", "Reakcje", "phrase", 3,
 "Życzenia urodzinowe.", "wan kə\u0300ət = dzień narodzin",
 ("Dziękuję, jesteś kochany.", "khàwp-khun ná khráp jai dii jang", "ขอบคุณนะครับ ใจดีจัง")),
("Dobranoc.", "raa-trii sà-wàt", "ราตรีสวัสดิ์", "Small talk", "Pożegnania", "phrase", 4,
 "Forma nieco oficjalna; na co dzień częściej mówi się „fǎn dii”.", "",
 ("Dobranoc, śpij dobrze.", "raa-trii sà-wàt fǎn dii khráp", "ราตรีสวัสดิ์ ฝันดีครับ")),
("Śpij dobrze.", "fǎn dii", "ฝันดี", "Small talk", "Pożegnania", "phrase", 4, "", "dosłownie: dobrych snów",
 ("Ty też śpij dobrze.", "fǎn dii chên kan khráp", "ฝันดีเช่นกันครับ")),
("Miłego dnia!", "khǎw hâi pen wan thîi dii ná khráp", "ขอให้เป็นวันที่ดีนะครับ",
 "Small talk", "Pożegnania", "phrase", 3, "", "khǎw hâi = życzę, oby",
 ("Dziękuję, nawzajem.", "khàwp-khun khráp chên kan", "ขอบคุณครับ เช่นกัน")),
("Smacznego!", "thaan hâi à-ròi ná khráp", "ทานให้อร่อยนะครับ", "Small talk", "Reakcje", "phrase", 3,
 "„thaan” to uprzejmiejsza wersja „kin” (jeść).", "",
 ("Dziękuję, zjedzmy razem.", "khàwp-khun khráp kin dûai kan", "ขอบคุณครับ กินด้วยกัน")),
("Na zdrowie!", "chon kâew", "ชนแก้ว", "Small talk", "Reakcje", "phrase", 3, "Toast przy stukaniu się kieliszkami.", "dosłownie: stuknąć szklankami",
 ("Na zdrowie!", "chon kâew khráp", "ชนแก้วครับ")),
("Cała przyjemność po mojej stronie.", "yin dii khráp", "ยินดีครับ", "Small talk", "Zwroty grzecznościowe", "phrase", 3, "", "",
 ("Dziękuję za pomoc.", "khàwp-khun thîi chûai khráp", "ขอบคุณที่ช่วยครับ")),
("Dziękuję za pomoc.", "khàwp-khun thîi chûai khráp", "ขอบคุณที่ช่วยครับ",
 "Podstawy i grzeczność", "Zwroty grzecznościowe", "phrase", 4, "", "",
 ("Drobiazg.", "mâi pen rai khráp", "ไม่เป็นไรครับ")),
("Przepraszam, że przeszkadzam.", "khǎw thôot thîi róp-kuan khráp", "ขอโทษที่รบกวนครับ",
 "Podstawy i grzeczność", "Zwroty grzecznościowe", "phrase", 4, "", "róp-kuan = zawracać głowę",
 ("Nie ma sprawy, słucham.", "mâi pen rai khráp wâa yang-ngai", "ไม่เป็นไรครับ ว่ายังไง")),
("Przepraszam, przejdę.", "khǎw thaang nòi khráp", "ขอทางหน่อยครับ",
 "Podstawy i grzeczność", "Zwroty grzecznościowe", "phrase", 5, "Niezbędne w tłumie i w metrze.", "thaang = droga, przejście",
 ("Proszę bardzo.", "chəən khráp", "เชิญครับ")),
("Proszę usiąść.", "chəən nâng khráp", "เชิญนั่งครับ", "Podstawy i grzeczność", "Zwroty grzecznościowe", "phrase", 4, "", "chəən = zapraszam, proszę bardzo",
 ("Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ")),
("Poczekaj chwilę, proszę.", "raw sàk khrûu ná khráp", "รอสักครู่นะครับ",
 "Podstawy i grzeczność", "Zwroty grzecznościowe", "phrase", 5, "", "sàk khrûu = momencik",
 ("Dobrze, poczekam.", "dâai khráp phǒm raw", "ได้ครับ ผมรอ")),
("Nie ma pośpiechu.", "mâi tâwng rîip khráp", "ไม่ต้องรีบครับ", "Podstawy i grzeczność", "Zwroty grzecznościowe", "phrase", 4, "", "rîip = spieszyć się",
 ("Dziękuję za wyrozumiałość.", "khàwp-khun khráp", "ขอบคุณครับ")),
("Jak wolisz.", "láew tàe khun khráp", "แล้วแต่คุณครับ", "Podstawy i grzeczność", "Zwroty grzecznościowe", "phrase", 4,
 "Bardzo częsta, uprzejma odpowiedź przy wyborze.", "",
 ("To zróbmy tak.", "ngán ao yàang níi khráp", "งั้นเอาอย่างนี้ครับ")),
("Zgadzam się.", "hěn dûai khráp", "เห็นด้วยครับ", "Podstawy i grzeczność", "Reakcje", "phrase", 3, "", "hěn dûai = być tego samego zdania",
 ("To się umówmy.", "tòk long khráp", "ตกลงครับ")),
("Umowa stoi.", "tòk long khráp", "ตกลงครับ", "Podstawy i grzeczność", "Reakcje", "phrase", 4, "", "tòk long = zgoda, ustalone",
 ("Świetnie.", "dii mâak khráp", "ดีมากครับ")),
]

CORE2S += [

# =====================================================================
# CZAS I DATY — MIESIĄCE
# =====================================================================
("styczeń", "má-kà-raa-khom", "มกราคม", "Czas i daty", "Miesiące", "word", 3,
 "Nazwy miesięcy zakończone na „-khom” mają 31 dni, na „-yon” — 30.", "",
 ("Przyjeżdżam w styczniu.", "MONTH")),
("luty", "kum-phaa-phan", "กุมภาพันธ์", "Czas i daty", "Miesiące", "word", 3, "", "",
 ("Przyjeżdżam w lutym.", "MONTH")),
("marzec", "mii-naa-khom", "มีนาคม", "Czas i daty", "Miesiące", "word", 3, "", "",
 ("Przyjeżdżam w marcu.", "MONTH")),
("kwiecień", "mee-sǎa-yon", "เมษายน", "Czas i daty", "Miesiące", "word", 3,
 "W kwietniu wypada Songkran — tajski Nowy Rok.", "",
 ("Przyjeżdżam w kwietniu.", "MONTH")),
("maj", "phrúet-sà-phaa-khom", "พฤษภาคม", "Czas i daty", "Miesiące", "word", 3, "", "",
 ("Przyjeżdżam w maju.", "MONTH")),
("czerwiec", "mí-thù-naa-yon", "มิถุนายน", "Czas i daty", "Miesiące", "word", 3, "", "",
 ("Przyjeżdżam w czerwcu.", "MONTH")),
("lipiec", "kà-rá-kà-daa-khom", "กรกฎาคม", "Czas i daty", "Miesiące", "word", 3, "", "",
 ("Przyjeżdżam w lipcu.", "MONTH")),
("sierpień", "sǐng-hǎa-khom", "สิงหาคม", "Czas i daty", "Miesiące", "word", 3, "", "",
 ("Przyjeżdżam w sierpniu.", "MONTH")),
("wrzesień", "kan-yaa-yon", "กันยายน", "Czas i daty", "Miesiące", "word", 3, "", "",
 ("Przyjeżdżam we wrześniu.", "MONTH")),
("październik", "tù-laa-khom", "ตุลาคม", "Czas i daty", "Miesiące", "word", 3, "", "",
 ("Przyjeżdżam w październiku.", "MONTH")),
("listopad", "phrúet-sà-jì-kaa-yon", "พฤศจิกายน", "Czas i daty", "Miesiące", "word", 3, "", "",
 ("Przyjeżdżam w listopadzie.", "MONTH")),
("grudzień", "than-waa-khom", "ธันวาคม", "Czas i daty", "Miesiące", "word", 3, "", "",
 ("Przyjeżdżam w grudniu.", "MONTH")),

# =====================================================================
# CZAS I DATY — WYRAŻENIA
# =====================================================================
("pojutrze", "má-ruen níi", "มะรืนนี้", "Czas i daty", "Dni", "word", 3, "", "",
 ("Wracam pojutrze.", "phǒm klàp má-ruen níi", "ผมกลับมะรืนนี้")),
("przedwczoraj", "mûea waan suen", "เมื่อวานซืน", "Czas i daty", "Dni", "word", 2, "", "",
 ("Przyjechałem przedwczoraj.", "phǒm maa thǔeng mûea waan suen", "ผมมาถึงเมื่อวานซืน")),
("weekend", "sǎo aa-thít", "เสาร์อาทิตย์", "Czas i daty", "Dni tygodnia", "word", 4, "", "dosłownie: sobota-niedziela",
 ("W weekend jest tłoczno.", "sǎo aa-thít khon yə\u0301ə", "เสาร์อาทิตย์คนเยอะ")),
("w przyszłym tygodniu", "aa-thít nâa", "อาทิตย์หน้า", "Czas i daty", "Rozkład", "word", 4, "", "nâa = następny",
 ("Do zobaczenia w przyszłym tygodniu.", "jəə kan aa-thít nâa khráp", "เจอกันอาทิตย์หน้าครับ")),
("w zeszłym tygodniu", "aa-thít thîi láew", "อาทิตย์ที่แล้ว", "Czas i daty", "Rozkład", "word", 3, "", "thîi láew = miniony",
 ("Byłem tam w zeszłym tygodniu.", "phǒm pai maa aa-thít thîi láew", "ผมไปมาอาทิตย์ที่แล้ว")),
("w przyszłym miesiącu", "duean nâa", "เดือนหน้า", "Czas i daty", "Rozkład", "word", 3, "", "",
 ("Wracam do domu w przyszłym miesiącu.", "phǒm jà klàp bâan duean nâa", "ผมจะกลับบ้านเดือนหน้า")),
("w zeszłym miesiącu", "duean thîi láew", "เดือนที่แล้ว", "Czas i daty", "Rozkład", "word", 3, "", "",
 ("Zacząłem uczyć się w zeszłym miesiącu.", "phǒm rôem rian duean thîi láew", "ผมเริ่มเรียนเดือนที่แล้ว")),
("w tym roku", "pii níi", "ปีนี้", "Czas i daty", "Rozkład", "word", 4, "", "",
 ("W tym roku jest goręcej.", "pii níi ráwn kwàa", "ปีนี้ร้อนกว่า")),
("w przyszłym roku", "pii nâa", "ปีหน้า", "Czas i daty", "Rozkład", "word", 3, "", "",
 ("Przyjadę znowu w przyszłym roku.", "pii nâa jà maa ìik khráp", "ปีหน้าจะมาอีกครับ")),
("w zeszłym roku", "pii thîi láew", "ปีที่แล้ว", "Czas i daty", "Rozkład", "word", 3, "", "",
 ("Byłem tu w zeszłym roku.", "phǒm maa thîi nîi pii thîi láew", "ผมมาที่นี่ปีที่แล้ว")),
("dziś rano", "cháo níi", "เช้านี้", "Czas i daty", "Pory dnia", "word", 4, "", "",
 ("Dziś rano padało.", "cháo níi fǒn tòk", "เช้านี้ฝนตก")),
("dziś wieczorem", "yen níi", "เย็นนี้", "Czas i daty", "Pory dnia", "word", 4, "", "",
 ("Co robisz dziś wieczorem?", "yen níi tham à-rai khráp", "เย็นนี้ทำอะไรครับ")),
("dziś w nocy", "khuen níi", "คืนนี้", "Czas i daty", "Pory dnia", "word", 4, "", "",
 ("Dziś w nocy zostaję w hotelu.", "khuen níi phák thîi roong raem", "คืนนี้พักที่โรงแรม")),
("codziennie", "thúk wan", "ทุกวัน", "Czas i daty", "Rozkład", "word", 4, "", "thúk = każdy",
 ("Ćwiczę codziennie.", "phǒm áwk kamlang kaai thúk wan", "ผมออกกำลังกายทุกวัน")),
("zawsze", "tà-làwt", "ตลอด", "Czas i daty", "Rozkład", "word", 3, "", "",
 ("Tu zawsze jest tłoczno.", "thîi nîi khon yə\u0301ə tà-làwt", "ที่นี่คนเยอะตลอด")),
("nigdy (nie zdarzyło się)", "mâi khəəi", "ไม่เคย", "Czas i daty", "Rozkład", "word", 4,
 "„khəəi” to doświadczenie życiowe: „nigdy jeszcze nie…”.", "",
 ("Nigdy tego nie jadłem.", "phǒm mâi khəəi kin khráp", "ผมไม่เคยกินครับ")),
("czasami", "baang khráng", "บางครั้ง", "Czas i daty", "Rozkład", "word", 3, "", "",
 ("Czasami chodzę tam pieszo.", "baang khráng phǒm dəən pai", "บางครั้งผมเดินไป")),
("często", "bòi", "บ่อย", "Czas i daty", "Rozkład", "word", 4, "", "",
 ("Często tu bywasz?", "maa bòi mǎi khráp", "มาบ่อยไหมครับ")),
("rzadko", "naan naan thii", "นานๆ ที", "Czas i daty", "Rozkład", "word", 3, "", "",
 ("Rzadko piję kawę.", "phǒm dùem kaa-fae naan naan thii", "ผมดื่มกาแฟนานๆ ที")),
("jeszcze raz", "ìik khráng", "อีกครั้ง", "Czas i daty", "Rozkład", "word", 4, "", "ìik = jeszcze, dodatkowo",
 ("Powiedz to jeszcze raz.", "phûut ìik khráng dâai mǎi khráp", "พูดอีกครั้งได้ไหมครับ")),
("za chwilę", "dǐao", "เดี๋ยว", "Czas i daty", "Rozkład", "word", 5,
 "Bardzo częste słowo — zapowiada, że coś nastąpi za moment.", "",
 ("Za chwilę wracam.", "dǐao maa khráp", "เดี๋ยวมาครับ")),
("przed (czymś)", "kàwn", "ก่อน", "Czas i daty", "Rozkład", "word", 4, "", "",
 ("Zjedzmy przed wyjściem.", "kin kàwn pai khráp", "กินก่อนไปครับ")),
("po (czymś)", "lǎng", "หลัง", "Czas i daty", "Rozkład", "word", 4, "", "",
 ("Spotkajmy się po pracy.", "jəə kan lǎng lôek ngaan khráp", "เจอกันหลังเลิกงานครับ")),
("spóźniony", "sǎai", "สาย", "Czas i daty", "Rozkład", "word", 4, "", "",
 ("Przepraszam za spóźnienie.", "khǎw thôot thîi maa sǎai khráp", "ขอโทษที่มาสายครับ")),
("pół godziny", "khrûeng chûa-moong", "ครึ่งชั่วโมง", "Czas i daty", "Jednostki", "word", 4, "", "khrûeng = połowa",
 ("Zajmie to pół godziny.", "chái weelaa khrûeng chûa-moong", "ใช้เวลาครึ่งชั่วโมง")),
("data", "wan thîi", "วันที่", "Czas i daty", "Dni", "word", 3, "", "",
 ("Którego dziś mamy?", "wan níi wan thîi thâo-rài khráp", "วันนี้วันที่เท่าไหร่ครับ")),
("Jest południe.", "thîang wan", "เที่ยงวัน", "Czas i daty", "Pory dnia", "sentence", 3, "", "",
 ("To pora obiadu.", "thǔeng weelaa aa-hǎan klaang wan", "ถึงเวลาอาหารกลางวัน")),
("Jest północ.", "thîang khuen", "เที่ยงคืน", "Czas i daty", "Pory dnia", "sentence", 3, "", "",
 ("Już bardzo późno.", "dùek mâak láew khráp", "ดึกมากแล้วครับ")),
("O której otwierają?", "pə\u0300ət kìi moong khráp", "เปิดกี่โมงครับ", "Czas i daty", "Rozkład", "question", 5, "", "pə\u0300ət = otwierać",
 ("O dziewiątej rano.", "kâo moong cháo khráp", "เก้าโมงเช้าครับ")),
("O której zamykają?", "pìt kìi moong khráp", "ปิดกี่โมงครับ", "Czas i daty", "Rozkład", "question", 5, "", "pìt = zamykać",
 ("O dwudziestej drugiej.", "sìi thûm khráp", "สี่ทุ่มครับ")),
("Ile to potrwa?", "chái weelaa naan thâo-rài khráp", "ใช้เวลานานเท่าไหร่ครับ",
 "Czas i daty", "Rozkład", "question", 4, "", "chái weelaa = zajmować czas",
 ("Jakieś dwadzieścia minut.", "pramaan yîi-sìp naa-thii khráp", "ประมาณยี่สิบนาทีครับ")),
("Za pięć minut.", "ìik hâa naa-thii", "อีกห้านาที", "Czas i daty", "Rozkład", "sentence", 4, "", "",
 ("Dobrze, czekam.", "dâai khráp phǒm raw yùu", "ได้ครับ ผมรออยู่")),
("Jestem już spóźniony.", "phǒm sǎai láew khráp", "ผมสายแล้วครับ", "Czas i daty", "Rozkład", "sentence", 3, "", "",
 ("To pospieszmy się.", "rîip nòi khráp", "รีบหน่อยครับ")),

# =====================================================================
# LICZBY I LICZENIE
# =====================================================================
("dwanaście", "sìp sǎwng", "สิบสอง", "Liczby i liczenie", "Liczebniki", "word", 4, "", "", ("Dwanaście bahtów.", "NUMBAHT")),
("trzynaście", "sìp sǎam", "สิบสาม", "Liczby i liczenie", "Liczebniki", "word", 3, "", "", ("Trzynaście bahtów.", "NUMBAHT")),
("czternaście", "sìp sìi", "สิบสี่", "Liczby i liczenie", "Liczebniki", "word", 3, "", "", ("Czternaście bahtów.", "NUMBAHT")),
("piętnaście", "sìp hâa", "สิบห้า", "Liczby i liczenie", "Liczebniki", "word", 4, "", "", ("Piętnaście bahtów.", "NUMBAHT")),
("szesnaście", "sìp hòk", "สิบหก", "Liczby i liczenie", "Liczebniki", "word", 3, "", "", ("Szesnaście bahtów.", "NUMBAHT")),
("siedemnaście", "sìp jèt", "สิบเจ็ด", "Liczby i liczenie", "Liczebniki", "word", 3, "", "", ("Siedemnaście bahtów.", "NUMBAHT")),
("osiemnaście", "sìp pàet", "สิบแปด", "Liczby i liczenie", "Liczebniki", "word", 3, "", "", ("Osiemnaście bahtów.", "NUMBAHT")),
("dziewiętnaście", "sìp kâo", "สิบเก้า", "Liczby i liczenie", "Liczebniki", "word", 3, "", "", ("Dziewiętnaście bahtów.", "NUMBAHT")),
("dwadzieścia pięć", "yîi-sìp hâa", "ยี่สิบห้า", "Liczby i liczenie", "Liczebniki", "word", 3,
 "Uwaga: dwadzieścia to „yîi-sìp”, nie „sǎwng sìp”.", "", ("Dwadzieścia pięć bahtów.", "NUMBAHT")),
("sześćdziesiąt", "hòk-sìp", "หกสิบ", "Liczby i liczenie", "Liczebniki", "word", 3, "", "", ("Sześćdziesiąt bahtów.", "NUMBAHT")),
("siedemdziesiąt", "jèt-sìp", "เจ็ดสิบ", "Liczby i liczenie", "Liczebniki", "word", 3, "", "", ("Siedemdziesiąt bahtów.", "NUMBAHT")),
("osiemdziesiąt", "pàet-sìp", "แปดสิบ", "Liczby i liczenie", "Liczebniki", "word", 3, "", "", ("Osiemdziesiąt bahtów.", "NUMBAHT")),
("dziewięćdziesiąt", "kâo-sìp", "เก้าสิบ", "Liczby i liczenie", "Liczebniki", "word", 3, "", "", ("Dziewięćdziesiąt bahtów.", "NUMBAHT")),
("trzysta", "sǎam ráwi", "สามร้อย", "Liczby i liczenie", "Liczebniki", "word", 4, "", "", ("Trzysta bahtów.", "NUMBAHT")),
("połowa", "khrûeng", "ครึ่ง", "Liczby i liczenie", "Ilość", "word", 4, "", "",
 ("Poproszę pół porcji.", "khǎw khrûeng thîi khráp", "ขอครึ่งที่ครับ")),
("pierwszy", "thîi nùeng", "ที่หนึ่ง", "Liczby i liczenie", "Określenia", "word", 3, "", "",
 ("To mój pierwszy raz.", "pen khráng râek khǎwng phǒm", "เป็นครั้งแรกของผม")),
("drugi", "thîi sǎwng", "ที่สอง", "Liczby i liczenie", "Określenia", "word", 3, "", "",
 ("Druga ulica w prawo.", "sǎwi thîi sǎwng thaang khwǎa", "ซอยที่สองทางขวา")),
("kilka", "sǎwng sǎam", "สองสาม", "Liczby i liczenie", "Ilość", "word", 3,
 "Tajowie mówią dosłownie „dwa trzy”, gdy mają na myśli „kilka”.", "",
 ("Zostanę kilka dni.", "phǒm jà yùu sǎwng sǎam wan", "ผมจะอยู่สองสามวัน")),
("razem, w sumie", "tháng mòt", "ทั้งหมด", "Liczby i liczenie", "Ilość", "word", 5, "", "",
 ("Ile razem?", "tháng mòt thâo-rài khráp", "ทั้งหมดเท่าไหร่ครับ")),
("około", "pramaan", "ประมาณ", "Liczby i liczenie", "Określenia", "word", 4, "", "",
 ("Około stu bahtów.", "pramaan nùeng ráwi bàat", "ประมาณหนึ่งร้อยบาท")),
]

CORE2S += [

# =====================================================================
# ZAKUPY I PIENIĄDZE
# =====================================================================
("moneta", "rǐan", "เหรียญ", "Zakupy i pieniądze", "Płatności", "word", 3, "", "",
 ("Mam same monety.", "phǒm mii tàe rǐan khráp", "ผมมีแต่เหรียญครับ")),
("banknot", "thá-ná-bàt", "ธนบัตร", "Zakupy i pieniądze", "Płatności", "word", 3, "", "",
 ("Mam tylko duży banknot.", "phǒm mii tàe bai yài khráp", "ผมมีแต่ใบใหญ่ครับ")),
("kantor", "râan lâek ngoen", "ร้านแลกเงิน", "Zakupy i pieniądze", "Płatności", "word", 4, "", "lâek = wymieniać",
 ("Gdzie jest najbliższy kantor?", "WHERE")),
("kurs wymiany", "àt-traa lâek plìan", "อัตราแลกเปลี่ยน", "Zakupy i pieniądze", "Płatności", "word", 3, "", "",
 ("Jaki jest dziś kurs?", "wan níi àt-traa thâo-rài khráp", "วันนี้อัตราเท่าไหร่ครับ")),
("opłata", "khâa tham-niam", "ค่าธรรมเนียม", "Zakupy i pieniądze", "Płatności", "word", 3, "", "khâa = koszt, opłata za coś",
 ("Czy jest jakaś opłata?", "mii khâa tham-niam mǎi khráp", "มีค่าธรรมเนียมไหมครับ")),
("kaucja", "ngoen mát-jam", "เงินมัดจำ", "Zakupy i pieniądze", "Płatności", "word", 3,
 "Przy wynajmie skutera zwykle zostawia się kaucję zamiast paszportu.", "",
 ("Ile wynosi kaucja?", "ngoen mát-jam thâo-rài khráp", "เงินมัดจำเท่าไหร่ครับ")),
("za darmo", "frii", "ฟรี", "Zakupy i pieniądze", "Cena", "word", 4, "Zapożyczenie z angielskiego, w powszechnym użyciu.", "",
 ("Czy to jest za darmo?", "an níi frii mǎi khráp", "อันนี้ฟรีไหมครับ")),
("napiwek", "thíp", "ทิป", "Zakupy i pieniądze", "Płatności", "word", 3,
 "Napiwek nie jest obowiązkowy, ale mile widziany w restauracjach.", "",
 ("Reszty nie trzeba.", "mâi tâwng thawn khráp", "ไม่ต้องทอนครับ")),
("torba na zakupy", "thǔng", "ถุง", "Zakupy i pieniądze", "Zakupy", "word", 4, "", "",
 ("Poproszę torbę.", "ORDER")),
("Czy mogę zapłacić kartą?", "jàai bàt dâai mǎi khráp", "จ่ายบัตรได้ไหมครับ",
 "Zakupy i pieniądze", "Płatności", "question", 5, "Na targach i w małych sklepach zwykle nie.", "",
 ("Przepraszam, tylko gotówka.", "khǎw thôot khráp ngoen sòt thâo nán", "ขอโทษครับ เงินสดเท่านั้น")),
("Czy da się taniej?", "lót nòi dâai mǎi khráp", "ลดหน่อยได้ไหมครับ",
 "Zakupy i pieniądze", "Targowanie", "question", 5,
 "Targowanie z uśmiechem działa; podniesiony głos zamyka rozmowę.", "lót = obniżyć",
 ("Dobrze, dwadzieścia bahtów taniej.", "lót hâi yîi-sìp bàat khráp", "ลดให้ยี่สิบบาทครับ")),
("To dla mnie za drogo.", "phaeng pai sǎmràp phǒm khráp", "แพงไปสำหรับผมครับ",
 "Zakupy i pieniądze", "Targowanie", "sentence", 4, "", "",
 ("To ile pan da?", "hâi thâo-rài khráp", "ให้เท่าไหร่ครับ")),
("Wezmę to.", "ao an níi khráp", "เอาอันนี้ครับ", "Zakupy i pieniądze", "Zakup", "sentence", 5, "", "ao = brać, chcieć",
 ("Coś jeszcze?", "ao à-rai ìik mǎi khráp", "เอาอะไรอีกไหมครับ")),
("Tylko oglądam.", "duu chə\u030cəi chə\u030cəi khráp", "ดูเฉยๆ ครับ",
 "Zakupy i pieniądze", "Zakup", "sentence", 4, "Uprzejmy sposób odmowy sprzedawcy.", "",
 ("Proszę bardzo, niech pan patrzy.", "chəən duu dâai khráp", "เชิญดูได้ครับ")),
("Gdzie mogę wymienić pieniądze?", "lâek ngoen dâai thîi nǎi khráp", "แลกเงินได้ที่ไหนครับ",
 "Zakupy i pieniądze", "Płatności", "question", 4, "", "",
 ("W kantorze przy wejściu.", "thîi râan lâek ngoen trong thaang khâo khráp", "ที่ร้านแลกเงินตรงทางเข้าครับ")),
("Ile kosztuje jedna sztuka?", "an lá thâo-rài khráp", "อันละเท่าไหร่ครับ",
 "Zakupy i pieniądze", "Cena", "question", 5, "", "lá = za sztukę",
 ("Dwadzieścia bahtów za sztukę.", "an lá yîi-sìp bàat khráp", "อันละยี่สิบบาทครับ")),
("Poproszę paragon.", "khǎw bai sèt dûai khráp", "ขอใบเสร็จด้วยครับ",
 "Zakupy i pieniądze", "Płatności", "phrase", 4, "", "bai sèt = paragon",
 ("Proszę bardzo.", "nîi khráp", "นี่ครับ")),
("Czy mogę to przymierzyć?", "lawng sài dâai mǎi khráp", "ลองใส่ได้ไหมครับ",
 "Zakupy i pieniądze", "Ubrania", "question", 4, "", "lawng = spróbować; sài = założyć",
 ("Przymierzalnia jest tam.", "hâwng lawng yùu thaang nán khráp", "ห้องลองอยู่ทางนั้นครับ")),
("Czy jest większy rozmiar?", "mii sái yài kwàa mǎi khráp", "มีไซส์ใหญ่กว่าไหมครับ",
 "Zakupy i pieniądze", "Ubrania", "question", 4, "", "kwàa = bardziej (stopień wyższy)",
 ("Zaraz sprawdzę.", "dǐao duu hâi khráp", "เดี๋ยวดูให้ครับ")),

# =====================================================================
# ZDROWIE
# =====================================================================
("ból zęba", "pùat fan", "ปวดฟัน", "Zdrowie", "Objawy", "word", 3, "", "pùat = tępy, ciągły ból",
 ("Boli mnie ząb.", "phǒm pùat fan khráp", "ผมปวดฟันครับ")),
("kaszel", "ai", "ไอ", "Zdrowie", "Objawy", "word", 3, "", "",
 ("Kaszlę od trzech dni.", "phǒm ai maa sǎam wan láew", "ผมไอมาสามวันแล้ว")),
("katar", "náam mûuk lǎi", "น้ำมูกไหล", "Zdrowie", "Objawy", "word", 3, "", "dosłownie: cieknie z nosa",
 ("Mam katar.", "phǒm náam mûuk lǎi khráp", "ผมน้ำมูกไหลครับ")),
("przeziębienie", "pen wàt", "เป็นหวัด", "Zdrowie", "Objawy", "word", 4, "", "pen = mieć (chorobę)",
 ("Chyba się przeziębiłem.", "phǒm khít wâa pen wàt khráp", "ผมคิดว่าเป็นหวัดครับ")),
("wymiotować", "aa-jian", "อาเจียน", "Zdrowie", "Objawy", "word", 3, "", "",
 ("Wymiotowałem w nocy.", "phǒm aa-jian tawn khuen khráp", "ผมอาเจียนตอนคืนครับ")),
("oparzenie słoneczne", "phǐu mâi dàet", "ผิวไหม้แดด", "Zdrowie", "Objawy", "word", 3, "", "phǐu = skóra",
 ("Spiekłem się na słońcu.", "phǐu phǒm mâi dàet khráp", "ผิวผมไหม้แดดครับ")),
("ukąszenie owada", "malaeng kàt", "แมลงกัด", "Zdrowie", "Objawy", "word", 3, "", "kàt = gryźć",
 ("Coś mnie ugryzło.", "mii à-rai kàt phǒm khráp", "มีอะไรกัดผมครับ")),
("bandaż", "phâa phan phlǎe", "ผ้าพันแผล", "Zdrowie", "Apteka", "word", 3, "", "phlǎe = rana",
 ("Poproszę bandaż.", "ORDER")),
("dentysta", "mǎw fan", "หมอฟัน", "Zdrowie", "Ludzie", "word", 3, "", "mǎw = lekarz",
 ("Gdzie jest dentysta?", "WHERE")),
("Źle się czuję.", "phǒm mâi sà-baai khráp", "ผมไม่สบายครับ", "Zdrowie", "Objawy", "sentence", 5,
 "Uniwersalne zdanie na każdą niedyspozycję.", "sà-baai = dobrze się mieć",
 ("Co ci dolega?", "pen à-rai khráp", "เป็นอะไรครับ")),
("Boli mnie tutaj.", "pùat trong níi khráp", "ปวดตรงนี้ครับ", "Zdrowie", "Objawy", "sentence", 5,
 "Wystarczy wskazać palcem.", "",
 ("Od kiedy?", "tâng tàe mûea-rài khráp", "ตั้งแต่เมื่อไหร่ครับ")),
("Od wczoraj.", "tâng tàe mûea waan khráp", "ตั้งแต่เมื่อวานครับ", "Zdrowie", "Objawy", "sentence", 4, "", "tâng tàe = od (jakiegoś momentu)",
 ("To zbadam pana.", "khǎw trùat duu nòi khráp", "ขอตรวจดูหน่อยครับ")),
("Potrzebuję lekarza.", "phǒm tâwng kaan mǎw khráp", "ผมต้องการหมอครับ", "Zdrowie", "Nagłe wypadki", "sentence", 5, "", "tâwng kaan = potrzebować",
 ("Zaraz kogoś wezwę.", "dǐao rîak hâi khráp", "เดี๋ยวเรียกให้ครับ")),
("Proszę mnie zawieźć do szpitala.", "phaa pai roong phá-yaa-baan nòi khráp", "พาไปโรงพยาบาลหน่อยครับ",
 "Zdrowie", "Nagłe wypadki", "phrase", 4, "", "phaa pai = zaprowadzić, zawieźć",
 ("Proszę wsiadać.", "khûen rót loei khráp", "ขึ้นรถเลยครับ")),
("Mam alergię na orzeszki.", "phǒm pháe thùa khráp", "ผมแพ้ถั่วครับ", "Zdrowie", "Dieta", "sentence", 4,
 "Bardzo ważne zdanie: orzeszki są w wielu tajskich daniach.", "pháe = mieć uczulenie",
 ("Zaznaczę to w kuchni.", "dǐao bàwk khrua hâi khráp", "เดี๋ยวบอกครัวให้ครับ")),
("Nie mogę jeść ostrego.", "phǒm kin phèt mâi dâai khráp", "ผมกินเผ็ดไม่ได้ครับ",
 "Zdrowie", "Dieta", "sentence", 5, "", "",
 ("Zrobię łagodnie.", "jà tham mâi phèt khráp", "จะทำไม่เผ็ดครับ")),
("Czuję się już lepiej.", "dii khûen láew khráp", "ดีขึ้นแล้วครับ", "Zdrowie", "Samopoczucie", "sentence", 4, "", "khûen = w górę (poprawa)",
 ("To dobrze.", "dii láew khráp", "ดีแล้วครับ")),
("Kręci mi się w głowie.", "phǒm wian hǔa khráp", "ผมเวียนหัวครับ", "Zdrowie", "Objawy", "sentence", 4, "", "hǔa = głowa",
 ("Proszę usiąść.", "nâng phák kàwn khráp", "นั่งพักก่อนครับ")),

# =====================================================================
# EMOCJE
# =====================================================================
("zły, wściekły", "kròot", "โกรธ", "Cechy i opinie", "Emocje", "word", 3, "", "",
 ("Nie gniewaj się.", "yàa kròot ná khráp", "อย่าโกรธนะครับ")),
("zaskoczony", "tòk jai", "ตกใจ", "Cechy i opinie", "Emocje", "word", 3, "", "dosłownie: serce spada",
 ("Ale mnie zaskoczyłeś.", "tòk jai loei khráp", "ตกใจเลยครับ")),
("spokojny, opanowany", "jai yen", "ใจเย็น", "Cechy i opinie", "Emocje", "word", 4,
 "Komplement: „jai yen” to ktoś, kto się nie unosi.", "dosłownie: chłodne serce",
 ("Spokojnie, bez nerwów.", "jai yen yen khráp", "ใจเย็นๆ ครับ")),
("dumny", "phuum jai", "ภูมิใจ", "Cechy i opinie", "Emocje", "word", 3, "", "",
 ("Jestem z ciebie dumny.", "phǒm phuum jai nai tua khun khráp", "ผมภูมิใจในตัวคุณครับ")),
("rozczarowany", "phìt wǎng", "ผิดหวัง", "Cechy i opinie", "Emocje", "word", 3, "", "",
 ("Trochę się zawiodłem.", "phǒm phìt wǎng nít nòi khráp", "ผมผิดหวังนิดหน่อยครับ")),
("samotny", "ngǎo", "เหงา", "Cechy i opinie", "Emocje", "word", 3, "", "",
 ("Czasem czuję się samotny.", "baang khráng phǒm ngǎo khráp", "บางครั้งผมเหงาครับ")),
("zadowolony", "phaw jai", "พอใจ", "Cechy i opinie", "Emocje", "word", 3, "", "phaw = wystarczająco",
 ("Jestem zadowolony.", "phǒm phaw jai khráp", "ผมพอใจครับ")),
("zestresowany", "khrîat", "เครียด", "Cechy i opinie", "Emocje", "word", 3, "", "",
 ("Nie stresuj się.", "yàa khrîat ná khráp", "อย่าเครียดนะครับ")),
("zawstydzony, nieśmiały", "aai", "อาย", "Cechy i opinie", "Emocje", "word", 3, "", "",
 ("Trochę się wstydzę.", "phǒm aai nít nòi khráp", "ผมอายนิดหน่อยครับ")),
("tęsknić", "khít thǔeng", "คิดถึง", "Cechy i opinie", "Emocje", "word", 4,
 "Mówi się to również do przyjaciół, nie tylko w związku.", "dosłownie: myśleć aż do kogoś",
 ("Tęsknię za tobą.", "phǒm khít thǔeng khun khráp", "ผมคิดถึงคุณครับ")),
("Nie martw się.", "mâi tâwng kang-won khráp", "ไม่ต้องกังวลครับ", "Cechy i opinie", "Emocje", "phrase", 4, "", "",
 ("Dziękuję, już mi lepiej.", "khàwp-khun khráp dii khûen láew", "ขอบคุณครับ ดีขึ้นแล้ว")),
("Cieszę się.", "dii jai khráp", "ดีใจครับ", "Cechy i opinie", "Emocje", "phrase", 4, "", "dii jai = dobre serce, radość",
 ("Ja też się cieszę.", "phǒm kâw dii jai khráp", "ผมก็ดีใจครับ")),
("Przykro mi.", "sǐa jai dûai khráp", "เสียใจด้วยครับ", "Cechy i opinie", "Emocje", "phrase", 4,
 "Wyraz współczucia, nie przeprosin.", "sǐa jai = smutek, żal",
 ("Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ")),
]

CORE2S += [

# =====================================================================
# DOM I CODZIENNOŚĆ
# =====================================================================
("kuchnia", "hâwng khrua", "ห้องครัว", "Dom i codzienność", "Mieszkanie", "word", 3, "", "hâwng = pokój",
 ("Gdzie jest kuchnia?", "WHERE")),
("sypialnia", "hâwng nawn", "ห้องนอน", "Dom i codzienność", "Mieszkanie", "word", 3, "", "nawn = spać, leżeć",
 ("Sypialnia jest na górze.", "hâwng nawn yùu chán bon", "ห้องนอนอยู่ชั้นบน")),
("salon", "hâwng nâng lên", "ห้องนั่งเล่น", "Dom i codzienność", "Mieszkanie", "word", 3, "", "dosłownie: pokój do siedzenia i zabawy",
 ("Poczekajmy w salonie.", "raw thîi hâwng nâng lên khráp", "รอที่ห้องนั่งเล่นครับ")),
("lodówka", "tûu yen", "ตู้เย็น", "Dom i codzienność", "Wyposażenie", "word", 4, "", "tûu = szafka; yen = chłodny",
 ("Czy w pokoju jest lodówka?", "nai hâwng mii tûu yen mǎi khráp", "ในห้องมีตู้เย็นไหมครับ")),
("pralka", "khrûeang sák phâa", "เครื่องซักผ้า", "Dom i codzienność", "Wyposażenie", "word", 3, "", "khrûeang = maszyna",
 ("Gdzie jest pralka?", "WHERE")),
("czajnik", "kaa náam ráwn", "กาน้ำร้อน", "Dom i codzienność", "Wyposażenie", "word", 3, "", "",
 ("Czy jest czajnik?", "HAVE")),
("śmieci", "khà-yà", "ขยะ", "Dom i codzienność", "Mieszkanie", "word", 3, "", "",
 ("Gdzie wyrzucić śmieci?", "thíng khà-yà thîi nǎi khráp", "ทิ้งขยะที่ไหนครับ")),
("piętro", "chán", "ชั้น", "Dom i codzienność", "Mieszkanie", "word", 4,
 "Tego samego słowa używa się o półce i o klasie w szkole.", "",
 ("Które piętro?", "chán nǎi khráp", "ชั้นไหนครับ")),
("myć zęby", "praeng fan", "แปรงฟัน", "Dom i codzienność", "Codzienne", "word", 3, "", "",
 ("Myję zęby rano i wieczorem.", "phǒm praeng fan cháo lae yen", "ผมแปรงฟันเช้าและเย็น")),
("ubierać się", "tàeng tua", "แต่งตัว", "Dom i codzienność", "Codzienne", "word", 3, "", "",
 ("Zaraz się ubiorę.", "dǐao tàeng tua kàwn khráp", "เดี๋ยวแต่งตัวก่อนครับ")),
("sprzątać", "tham khwaam sà-àat", "ทำความสะอาด", "Dom i codzienność", "Codzienne", "word", 3, "", "sà-àat = czysty",
 ("Kiedy sprzątają pokój?", "tham khwaam sà-àat hâwng tawn nǎi khráp", "ทำความสะอาดห้องตอนไหนครับ")),
("naprawiać", "sâwm", "ซ่อม", "Dom i codzienność", "Codzienne", "word", 3, "", "",
 ("Czy da się to naprawić?", "sâwm dâai mǎi khráp", "ซ่อมได้ไหมครับ")),
("Idę spać.", "phǒm jà pai nawn khráp", "ผมจะไปนอนครับ", "Dom i codzienność", "Codzienne", "sentence", 4, "", "",
 ("Dobranoc, śpij dobrze.", "fǎn dii khráp", "ฝันดีครับ")),
("Dopiero wstałem.", "phǒm phôeng tùen khráp", "ผมเพิ่งตื่นครับ", "Dom i codzienność", "Codzienne", "sentence", 3, "", "phôeng = dopiero co",
 ("To zjedzmy śniadanie.", "pai kin khâao cháo kan khráp", "ไปกินข้าวเช้ากันครับ")),
("Muszę iść do pracy.", "phǒm tâwng pai tham ngaan khráp", "ผมต้องไปทำงานครับ",
 "Dom i codzienność", "Codzienne", "sentence", 4, "", "",
 ("To do zobaczenia wieczorem.", "yen níi jəə kan khráp", "เย็นนี้เจอกันครับ")),
("Wracam do domu.", "phǒm klàp bâan khráp", "ผมกลับบ้านครับ", "Dom i codzienność", "Codzienne", "sentence", 4, "", "",
 ("Uważaj na siebie.", "duu lae tua eeng ná khráp", "ดูแลตัวเองนะครับ")),
("Idę zrobić zakupy.", "phǒm pai súe khǎwng khráp", "ผมไปซื้อของครับ", "Dom i codzienność", "Codzienne", "sentence", 4, "", "súe khǎwng = kupować rzeczy",
 ("Kupisz mi wodę?", "súe náam hâi nòi dâai mǎi khráp", "ซื้อน้ำให้หน่อยได้ไหมครับ")),
("Ładuję telefon.", "phǒm chárt mue-thǔe khráp", "ผมชาร์จมือถือครับ", "Dom i codzienność", "Codzienne", "sentence", 3, "", "mue-thǔe = telefon komórkowy",
 ("Gdzie jest gniazdko?", "plák fai yùu thîi nǎi khráp", "ปลั๊กไฟอยู่ที่ไหนครับ")),
("Zaraz wracam.", "dǐao maa khráp", "เดี๋ยวมาครับ", "Dom i codzienność", "Codzienne", "phrase", 5,
 "Bardzo częsty zwrot — dosłownie „za moment przyjdę”.", "",
 ("Dobrze, poczekam.", "dâai khráp phǒm raw yùu", "ได้ครับ ผมรออยู่")),

# =====================================================================
# HOTEL
# =====================================================================
("poduszka", "mǎwn", "หมอน", "Hotel", "Wyposażenie", "word", 4, "", "",
 ("Poproszę jeszcze jedną poduszkę.", "khǎw mǎwn ìik bai khráp", "ขอหมอนอีกใบครับ")),
("koc", "phâa hòm", "ผ้าห่ม", "Hotel", "Wyposażenie", "word", 4, "", "phâa = tkanina",
 ("Poproszę koc.", "ORDER")),
("pościel", "phâa puu thîi nawn", "ผ้าปูที่นอน", "Hotel", "Wyposażenie", "word", 3, "", "",
 ("Czy można zmienić pościel?", "plìan phâa puu thîi nawn dâai mǎi khráp", "เปลี่ยนผ้าปูที่นอนได้ไหมครับ")),
("basen", "sà wâai náam", "สระว่ายน้ำ", "Hotel", "Wyposażenie", "word", 4, "", "wâai náam = pływać",
 ("Do której czynny jest basen?", "sà wâai náam pìt kìi moong khráp", "สระว่ายน้ำปิดกี่โมงครับ")),
("zameldowanie", "chék in", "เช็คอิน", "Hotel", "Recepcja", "word", 4, "Zapożyczenie z angielskiego.", "",
 ("O której jest zameldowanie?", "chék in kìi moong khráp", "เช็คอินกี่โมงครับ")),
("wymeldowanie", "chék áo", "เช็คเอาท์", "Hotel", "Recepcja", "word", 4, "", "",
 ("O której muszę się wymeldować?", "chék áo kìi moong khráp", "เช็คเอาท์กี่โมงครับ")),
("przechowalnia bagażu", "fàak krà-pǎo", "ฝากกระเป๋า", "Hotel", "Recepcja", "word", 4, "", "fàak = zostawić na przechowanie",
 ("Czy mogę zostawić bagaż?", "fàak krà-pǎo dâai mǎi khráp", "ฝากกระเป๋าได้ไหมครับ")),
("Czy jest wolny pokój?", "mii hâwng wâang mǎi khráp", "มีห้องว่างไหมครับ",
 "Hotel", "Recepcja", "question", 5, "", "wâang = wolny, dostępny",
 ("Tak, jeden został.", "mii khráp lǔea hâwng diao", "มีครับ เหลือห้องเดียว")),
("Zostanę jeszcze jedną noc.", "phǒm jà phák tàw ìik nùeng khuen khráp", "ผมจะพักต่ออีกหนึ่งคืนครับ",
 "Hotel", "Recepcja", "sentence", 4, "", "phák tàw = przedłużyć pobyt",
 ("Dobrze, zaraz to zapiszę.", "dâai khráp dǐao jòt hâi", "ได้ครับ เดี๋ยวจดให้")),
("Klimatyzacja jest za zimna.", "ae yen pai nòi khráp", "แอร์เย็นไปหน่อยครับ",
 "Hotel", "Problemy", "sentence", 3, "", "",
 ("Zaraz przykręcę.", "dǐao pràp hâi khráp", "เดี๋ยวปรับให้ครับ")),
("Nie ma gorącej wody.", "mâi mii náam ráwn khráp", "ไม่มีน้ำร้อนครับ", "Hotel", "Problemy", "sentence", 4, "", "",
 ("Przepraszamy, sprawdzimy to.", "khǎw thôot khráp dǐao pai duu hâi", "ขอโทษครับ เดี๋ยวไปดูให้")),
("Poproszę o budzenie o siódmej.", "chûai plùk tawn jèt moong dûai khráp", "ช่วยปลุกตอนเจ็ดโมงด้วยครับ",
 "Hotel", "Recepcja", "phrase", 3, "", "plùk = budzić",
 ("Dobrze, zadzwonimy.", "dâai khráp jà thoo pai", "ได้ครับ จะโทรไป")),

# =====================================================================
# TRANSPORT I DROGA
# =====================================================================
("przystanek autobusowy", "pâai rót mee", "ป้ายรถเมล์", "Transport", "Pojazdy", "word", 4, "", "pâai = tabliczka, znak",
 ("Gdzie jest przystanek autobusowy?", "WHERE")),
("stacja benzynowa", "pâm náam man", "ปั๊มน้ำมัน", "Transport", "Pojazdy", "word", 3, "", "náam man = paliwo, olej",
 ("Czy w pobliżu jest stacja benzynowa?", "thǎew níi mii pâm náam man mǎi khráp", "แถวนี้มีปั๊มน้ำมันไหมครับ")),
("korek uliczny", "rót tìt", "รถติด", "Transport", "Podróż", "word", 5,
 "W Bangkoku usłyszysz to słowo codziennie.", "dosłownie: samochody się kleją",
 ("Jest straszny korek.", "rót tìt mâak khráp", "รถติดมากครับ")),
("opóźnienie", "cháa kwàa kam-nòt", "ช้ากว่ากำหนด", "Transport", "Podróż", "word", 3, "", "",
 ("Pociąg ma opóźnienie.", "rót fai cháa kwàa kam-nòt khráp", "รถไฟช้ากว่ากำหนดครับ")),
("prom", "ruea khâam fâak", "เรือข้ามฟาก", "Transport", "Pojazdy", "word", 3, "", "khâam = przeprawiać się",
 ("O której odpływa prom?", "ruea àwk kìi moong khráp", "เรือออกกี่โมงครับ")),
("na rogu", "trong hǔa mum", "ตรงหัวมุม", "Miejsca i orientacja", "Kierunki", "word", 4, "", "hǔa mum = narożnik",
 ("Sklep jest na rogu.", "ráan yùu trong hǔa mum khráp", "ร้านอยู่ตรงหัวมุมครับ")),
("między", "rá-wàang", "ระหว่าง", "Miejsca i orientacja", "Kierunki", "word", 3, "", "",
 ("To jest między bankiem a apteką.", "yùu rá-wàang thá-naa-khaan kàp ráan yaa", "อยู่ระหว่างธนาคารกับร้านยา")),
("Proszę jechać prosto.", "trong pai khráp", "ตรงไปครับ", "Miejsca i orientacja", "Wskazówki", "phrase", 5, "", "",
 ("Jak daleko?", "klai thâo-rài khráp", "ไกลเท่าไหร่ครับ")),
("Proszę skręcić w lewo.", "líao sáai khráp", "เลี้ยวซ้ายครับ", "Miejsca i orientacja", "Wskazówki", "phrase", 5, "", "líao = skręcać",
 ("Tutaj?", "trong níi rǔe khráp", "ตรงนี้เหรอครับ")),
("Proszę skręcić w prawo.", "líao khwǎa khráp", "เลี้ยวขวาครับ", "Miejsca i orientacja", "Wskazówki", "phrase", 5, "", "",
 ("Dobrze, rozumiem.", "khâo jai láew khráp", "เข้าใจแล้วครับ")),
("Proszę zatrzymać się tutaj.", "jàwt trong níi khráp", "จอดตรงนี้ครับ", "Transport", "Taxi", "phrase", 5, "", "jàwt = zaparkować, zatrzymać",
 ("Dobrze.", "dâai khráp", "ได้ครับ")),
("Zgubiłem się.", "phǒm lǒng thaang khráp", "ผมหลงทางครับ", "Miejsca i orientacja", "Orientacja", "sentence", 4, "", "lǒng = zgubić drogę",
 ("Dokąd chce pan dojść?", "jà pai nǎi khráp", "จะไปไหนครับ")),
("Czy to daleko stąd?", "klai jàak thîi nîi mǎi khráp", "ไกลจากที่นี่ไหมครับ",
 "Miejsca i orientacja", "Orientacja", "question", 4, "", "jàak = od",
 ("Niedaleko, pięć minut.", "mâi klai hâa naa-thii khráp", "ไม่ไกล ห้านาทีครับ")),
("Czy mogę dojść tam pieszo?", "dəən pai dâai mǎi khráp", "เดินไปได้ไหมครับ",
 "Miejsca i orientacja", "Orientacja", "question", 4, "", "dəən = iść pieszo",
 ("Da się, ale jest gorąco.", "dəən dâai tàe ráwn ná khráp", "เดินได้ แต่ร้อนนะครับ")),
("Proszę pokazać na mapie.", "chûai chíi nai phǎen thîi nòi khráp", "ช่วยชี้ในแผนที่หน่อยครับ",
 "Miejsca i orientacja", "Orientacja", "phrase", 4, "", "chíi = wskazywać palcem",
 ("Jesteśmy tutaj.", "raw yùu trong níi khráp", "เราอยู่ตรงนี้ครับ")),
]

CORE2S += [

# =====================================================================
# CZASOWNIKI PODSTAWOWE
# =====================================================================
("rozmawiać", "khui", "คุย", "Czasowniki", "Podstawowe", "word", 4, "", "",
 ("Porozmawiajmy później.", "dǐao khui kan khráp", "เดี๋ยวคุยกันครับ")),
("śpiewać", "ráwng phleeng", "ร้องเพลง", "Czasowniki", "Rozrywka", "word", 3, "", "phleeng = piosenka",
 ("Lubisz śpiewać?", "châwp ráwng phleeng mǎi khráp", "ชอบร้องเพลงไหมครับ")),
("tańczyć", "tên", "เต้น", "Czasowniki", "Rozrywka", "word", 3, "", "",
 ("Chodźmy potańczyć.", "pai tên kan khráp", "ไปเต้นกันครับ")),
("zaczynać", "rôem", "เริ่ม", "Czasowniki", "Podstawowe", "word", 4, "", "",
 ("O której się zaczyna?", "rôem kìi moong khráp", "เริ่มกี่โมงครับ")),
("kończyć się", "sèt", "เสร็จ", "Czasowniki", "Podstawowe", "word", 4, "", "",
 ("Już skończyłem.", "sèt láew khráp", "เสร็จแล้วครับ")),
("potrzebować", "tâwng kaan", "ต้องการ", "Czasowniki", "Modalne", "word", 4,
 "Forma nieco oficjalna; w mowie potocznej częściej „yàak dâai”.", "",
 ("Czego pan potrzebuje?", "tâwng kaan à-rai khráp", "ต้องการอะไรครับ")),
("dostać", "dâai ráp", "ได้รับ", "Czasowniki", "Podstawowe", "word", 3, "", "",
 ("Dostałem wiadomość.", "phǒm dâai ráp khâw khwaam láew", "ผมได้รับข้อความแล้ว")),
("pożyczyć", "yuem", "ยืม", "Czasowniki", "Podstawowe", "word", 3, "", "",
 ("Czy mogę pożyczyć długopis?", "khǎw yuem pàak-kaa nòi dâai mǎi khráp", "ขอยืมปากกาหน่อยได้ไหมครับ")),
("pokazać", "hâi duu", "ให้ดู", "Czasowniki", "Podstawowe", "word", 4, "", "hâi = dać; duu = patrzeć",
 ("Pokaż mi, proszę.", "khǎw duu nòi khráp", "ขอดูหน่อยครับ")),
("wybierać", "lûeak", "เลือก", "Czasowniki", "Podstawowe", "word", 3, "", "",
 ("Wybierz, co chcesz.", "lûeak dâai loei khráp", "เลือกได้เลยครับ")),
("podpisać", "sen chûe", "เซ็นชื่อ", "Czasowniki", "Formalności", "word", 3, "", "chûe = imię",
 ("Proszę podpisać tutaj.", "sen chûe trong níi khráp", "เซ็นชื่อตรงนี้ครับ")),
("wypełnić formularz", "kràwk fawm", "กรอกฟอร์ม", "Czasowniki", "Formalności", "word", 3, "", "",
 ("Proszę wypełnić formularz.", "kràwk fawm nòi khráp", "กรอกฟอร์มหน่อยครับ")),
("zgubić", "tham hǎai", "ทำหาย", "Czasowniki", "Podstawowe", "word", 4, "", "dosłownie: sprawić, że zniknęło",
 ("Zgubiłem klucz.", "phǒm tham kun-jae hǎai khráp", "ผมทำกุญแจหายครับ")),
("znaleźć", "hǎa jəə", "หาเจอ", "Czasowniki", "Podstawowe", "word", 4, "", "hǎa = szukać; jəə = natrafić",
 ("Znalazłem.", "hǎa jəə láew khráp", "หาเจอแล้วครับ")),
("zapraszać", "chuan", "ชวน", "Czasowniki", "Podstawowe", "word", 3, "", "",
 ("Zapraszam cię na kolację.", "phǒm chuan khun pai kin khâao yen khráp", "ผมชวนคุณไปกินข้าวเย็นครับ")),
("pakować się", "jàt krà-pǎo", "จัดกระเป๋า", "Czasowniki", "Podróż", "word", 3, "", "krà-pǎo = torba, walizka",
 ("Muszę się spakować.", "phǒm tâwng jàt krà-pǎo khráp", "ผมต้องจัดกระเป๋าครับ")),
("czuć się", "rúu-sùek", "รู้สึก", "Czasowniki", "Podstawowe", "word", 4, "", "",
 ("Jak się czujesz?", "rúu-sùek yang-ngai bâang khráp", "รู้สึกยังไงบ้างครับ")),
("używać", "chái", "ใช้", "Czasowniki", "Podstawowe", "word", 5, "", "",
 ("Czy mogę tego użyć?", "chái dâai mǎi khráp", "ใช้ได้ไหมครับ")),
("odpocząć", "phák phàwn", "พักผ่อน", "Czasowniki", "Podstawowe", "word", 4, "", "",
 ("Odpocznij trochę.", "phák phàwn nòi ná khráp", "พักผ่อนหน่อยนะครับ")),
("wstawać", "tùen nawn", "ตื่นนอน", "Czasowniki", "Codzienne", "word", 4, "", "tùen = obudzić się",
 ("Wstaję o szóstej.", "phǒm tùen nawn hòk moong khráp", "ผมตื่นนอนหกโมงครับ")),
("wysiąść", "long", "ลง", "Czasowniki", "Ruch", "word", 4,
 "„long” znaczy też „w dół”. W autobusie: „long thîi nǎi” — gdzie wysiąść.", "",
 ("Gdzie mam wysiąść?", "long thîi nǎi khráp", "ลงที่ไหนครับ")),
("przesiadać się", "plìan rót", "เปลี่ยนรถ", "Czasowniki", "Ruch", "word", 3, "", "plìan = zmieniać",
 ("Czy muszę się przesiadać?", "tâwng plìan rót mǎi khráp", "ต้องเปลี่ยนรถไหมครับ")),

# =====================================================================
# CECHY I OPINIE — PRZYMIOTNIKI
# =====================================================================
("długi", "yaao", "ยาว", "Cechy i opinie", "Rozmiar", "word", 4, "", "", ("To jest za długie.", "TOOMUCH")),
("krótki", "sân", "สั้น", "Cechy i opinie", "Rozmiar", "word", 4, "", "", ("To jest za krótkie.", "TOOMUCH")),
("wysoki", "sǔung", "สูง", "Cechy i opinie", "Rozmiar", "word", 4, "", "", ("Jest bardzo wysoki.", "VERY")),
("niski (wzrost)", "tîa", "เตี้ย", "Cechy i opinie", "Rozmiar", "word", 3, "", "", ("Jestem raczej niski.", "phǒm tîa nít nòi khráp", "ผมเตี้ยนิดหน่อยครับ")),
("gruby", "ûan", "อ้วน", "Cechy i opinie", "Wygląd", "word", 3,
 "W Tajlandii nie jest to zniewaga, tylko neutralny opis.", "", ("Trochę przytyłem.", "phǒm ûan khûen nít nòi khráp", "ผมอ้วนขึ้นนิดหน่อยครับ")),
("chudy", "phǎwm", "ผอม", "Cechy i opinie", "Wygląd", "word", 3, "", "", ("Jest bardzo szczupły.", "VERY")),
("ciężki", "nàk", "หนัก", "Cechy i opinie", "Stan", "word", 4, "", "", ("Ta walizka jest ciężka.", "krà-pǎo bai níi nàk khráp", "กระเป๋าใบนี้หนักครับ")),
("lekki", "bao", "เบา", "Cechy i opinie", "Stan", "word", 4, "", "", ("Torba jest lekka.", "krà-pǎo bao khráp", "กระเป๋าเบาครับ")),
("silny, mocny", "khǎeng raeng", "แข็งแรง", "Cechy i opinie", "Stan", "word", 3, "", "", ("Jesteś bardzo silny.", "VERY")),
("słaby", "àwn ae", "อ่อนแอ", "Cechy i opinie", "Stan", "word", 2, "", "", ("Czuję się słabo.", "phǒm rúu-sùek àwn ae khráp", "ผมรู้สึกอ่อนแอครับ")),
("interesujący", "nâa sǒn jai", "น่าสนใจ", "Cechy i opinie", "Ocena", "word", 4, "", "nâa = wart tego, by…",
 ("To bardzo interesujące.", "VERY")),
("nudny", "nâa bùea", "น่าเบื่อ", "Cechy i opinie", "Ocena", "word", 3, "", "", ("To trochę nudne.", "ABIT")),
("ważny", "sǎm-khan", "สำคัญ", "Cechy i opinie", "Ocena", "word", 4, "", "", ("To bardzo ważne.", "VERY")),
("taki sam", "mǔean kan", "เหมือนกัน", "Cechy i opinie", "Ocena", "word", 5,
 "Używa się też w znaczeniu „ja też”.", "", ("Są takie same.", "mǔean kan khráp", "เหมือนกันครับ")),
("inny", "an ùen", "อันอื่น", "Cechy i opinie", "Ocena", "word", 4, "", "an = sztuka, rzecz",
 ("Czy jest jakiś inny?", "HAVE")),
("wygodny", "sà-baai", "สบาย", "Cechy i opinie", "Stan", "word", 5,
 "Kluczowe tajskie słowo: wygoda, spokój, dobre samopoczucie.", "",
 ("Tutaj jest bardzo przyjemnie.", "VERY")),
("pusty", "wâang plào", "ว่างเปล่า", "Cechy i opinie", "Stan", "word", 3, "", "", ("Butelka jest pusta.", "khùat wâang plào khráp", "ขวดว่างเปล่าครับ")),
("miękki", "nûm", "นุ่ม", "Cechy i opinie", "Stan", "word", 3, "", "", ("Łóżko jest miękkie.", "tiang nûm khráp", "เตียงนุ่มครับ")),
("twardy", "khǎeng", "แข็ง", "Cechy i opinie", "Stan", "word", 3, "", "", ("To jest za twarde.", "TOOMUCH")),
("jasny", "sà-wàang", "สว่าง", "Cechy i opinie", "Stan", "word", 3, "", "", ("W pokoju jest jasno.", "nai hâwng sà-wàang khráp", "ในห้องสว่างครับ")),
("ciemny", "mûet", "มืด", "Cechy i opinie", "Stan", "word", 3, "", "", ("Robi się ciemno.", "mûet láew khráp", "มืดแล้วครับ")),
("głęboki", "lúek", "ลึก", "Cechy i opinie", "Rozmiar", "word", 2, "", "", ("Czy tu jest głęboko?", "ISIT")),
("prawdziwy", "jing", "จริง", "Cechy i opinie", "Ocena", "word", 4, "", "", ("To prawda.", "jing khráp", "จริงครับ")),
("świeży", "sòt", "สด", "Cechy i opinie", "Smak", "word", 4, "", "", ("Czy to jest świeże?", "ISIT")),
("dojrzały", "sùk", "สุก", "Cechy i opinie", "Smak", "word", 3,
 "To samo słowo znaczy „ugotowany, wysmażony”.", "", ("Czy to jest dojrzałe?", "ISIT")),
("surowy", "dìp", "ดิบ", "Cechy i opinie", "Smak", "word", 3, "", "", ("Wolę nie jeść surowego.", "phǒm mâi kin khǎwng dìp khráp", "ผมไม่กินของดิบครับ")),
("cudowny, wspaniały", "yîam", "เยี่ยม", "Cechy i opinie", "Ocena", "word", 3, "", "",
 ("Wspaniale!", "yîam mâak khráp", "เยี่ยมมากครับ")),
("dziwny", "plàek", "แปลก", "Cechy i opinie", "Ocena", "word", 3, "", "",
 ("To trochę dziwne.", "ABIT")),
("uważny, ostrożny", "rá-wang", "ระวัง", "Cechy i opinie", "Stan", "word", 4,
 "Najczęściej słychać to jako ostrzeżenie: „uważaj!”.", "",
 ("Uważaj na siebie.", "rá-wang dûai ná khráp", "ระวังด้วยนะครับ")),

# =====================================================================
# RESTAURACJA I JEDZENIE — UZUPEŁNIENIE
# =====================================================================
("słomka", "làwt", "หลอด", "Restauracja", "Zastawa", "word", 3, "", "", ("Poproszę słomkę.", "ORDER")),
("miska", "chaam", "ชาม", "Restauracja", "Zastawa", "word", 3, "", "", ("Poproszę miskę.", "ORDER")),
("kubek", "kâew", "แก้ว", "Restauracja", "Zastawa", "word", 4,
 "„kâew” to zarówno szklanka, jak i klasyfikator napojów.", "", ("Poproszę kubek.", "ORDER")),
("stolik", "tó", "โต๊ะ", "Restauracja", "Obsługa", "word", 4, "", "",
 ("Czy jest wolny stolik?", "mii tó wâang mǎi khráp", "มีโต๊ะว่างไหมครับ")),
("rezerwacja", "kaan jawng", "การจอง", "Restauracja", "Obsługa", "word", 3, "", "jawng = rezerwować",
 ("Mam rezerwację.", "phǒm jawng wái láew khráp", "ผมจองไว้แล้วครับ")),
("Poproszę mniej ostro.", "khǎw phèt náwi náwi khráp", "ขอเผ็ดน้อยๆ ครับ",
 "Restauracja", "Zamówienie", "phrase", 5,
 "„mâi phèt” to całkiem bez ostrości; „phèt náwi náwi” to łagodnie.", "náwi = mało",
 ("Dobrze, będzie łagodnie.", "dâai khráp mâi phèt mâak", "ได้ครับ ไม่เผ็ดมาก")),
("Poproszę bez cukru.", "khǎw mâi sài náam-taan khráp", "ขอไม่ใส่น้ำตาลครับ",
 "Restauracja", "Zamówienie", "phrase", 5,
 "Tajskie napoje domyślnie są bardzo słodkie.", "",
 ("Bez cukru, dobrze.", "mâi sài náam-taan ná khráp", "ไม่ใส่น้ำตาลนะครับ")),
("Poproszę bez lodu.", "khǎw mâi sài nám khǎeng khráp", "ขอไม่ใส่น้ำแข็งครับ",
 "Restauracja", "Zamówienie", "phrase", 4, "", "nám khǎeng = lód",
 ("Dobrze.", "dâai khráp", "ได้ครับ")),
("Jestem wegetarianinem.", "phǒm kin jee khráp", "ผมกินเจครับ",
 "Restauracja", "Dieta", "sentence", 4,
 "„kin jee” to ścisła dieta bezmięsna, znana w całym kraju.", "",
 ("To zrobię z tofu.", "ngán sài tâo-hûu ná khráp", "งั้นใส่เต้าหู้นะครับ")),
("Nie jem mięsa.", "phǒm mâi kin núea sàt khráp", "ผมไม่กินเนื้อสัตว์ครับ",
 "Restauracja", "Dieta", "sentence", 4, "", "núea sàt = mięso zwierzęce",
 ("Warzywa mogą być?", "phàk dâai mǎi khráp", "ผักได้ไหมครับ")),
("Poproszę to na wynos.", "khǎw sài thǔng klàp bâan khráp", "ขอใส่ถุงกลับบ้านครับ",
 "Restauracja", "Zamówienie", "phrase", 5, "", "",
 ("Chwileczkę.", "sàk khrûu ná khráp", "สักครู่นะครับ")),
("Było bardzo smacznie.", "à-ròi mâak khráp", "อร่อยมากครับ", "Restauracja", "Reakcje", "phrase", 5,
 "Najlepszy komplement dla kucharza.", "",
 ("Dziękuję, zapraszamy ponownie.", "khàwp-khun khráp maa mài ná khráp", "ขอบคุณครับ มาใหม่นะครับ")),
]


# =====================================================================
# WZORCE ZDANIOWE Z BIAŁĄ LISTĄ
# ---------------------------------------------------------------------
# Zasada: żadnego iloczynu kartezjańskiego. Każdy wzorzec ma zamkniętą
# listę słów, dla których wynik brzmi naturalnie PO POLSKU, a polska
# strona rekordu jest wpisana ręcznie — nie sklejana z kawałków.
# Element listy: (polski rekord, hasło bazowe z CORE2S, polski przykład)
# =====================================================================

TEMPLATES2 = [

 dict(key="VERY", ty="collocation", cat="Cechy i opinie", sub="Określenia",
      ph="{ph} mâak", th="{th}มาก",
      lit="mâak = bardzo; w tajskim stoi ZAWSZE po przymiotniku",
      note="Szyk odwrotny niż w polskim: najpierw cecha, potem „mâak”.",
      ex_ph="nîi {ph} mâak khráp", ex_th="นี่{th}มากครับ",
      items=[
        ("bardzo długi", "długi", "To jest bardzo długie."),
        ("bardzo krótki", "krótki", "To jest bardzo krótkie."),
        ("bardzo wysoki", "wysoki", "To jest bardzo wysokie."),
        ("bardzo ciężki", "ciężki", "To jest bardzo ciężkie."),
        ("bardzo lekki", "lekki", "To jest bardzo lekkie."),
        ("bardzo interesujący", "interesujący", "To jest bardzo interesujące."),
        ("bardzo nudny", "nudny", "To jest bardzo nudne."),
        ("bardzo ważny", "ważny", "To jest bardzo ważne."),
        ("bardzo wygodny", "wygodny", "To jest bardzo wygodne."),
        ("bardzo miękki", "miękki", "To jest bardzo miękkie."),
        ("bardzo twardy", "twardy", "To jest bardzo twarde."),
        ("bardzo świeży", "świeży", "To jest bardzo świeże."),
      ]),

 dict(key="TOO", ty="collocation", cat="Cechy i opinie", sub="Określenia",
      ph="{ph} pai", th="{th}ไป",
      lit="… pai = za bardzo, ponad miarę",
      note="Grzeczna forma narzekania — używana przy targowaniu i w sklepie.",
      ex_ph="{ph} pai sǎmràp phǒm khráp", ex_th="{th}ไปสำหรับผมครับ",
      items=[
        ("za długi", "długi", "Dla mnie za długie."),
        ("za krótki", "krótki", "Dla mnie za krótkie."),
        ("za ciężki", "ciężki", "Dla mnie za ciężkie."),
        ("za twardy", "twardy", "Dla mnie za twarde."),
        ("za jasny", "jasny", "Dla mnie za jasne."),
        ("za ciemny", "ciemny", "Dla mnie za ciemne."),
      ]),

 dict(key="ISIT", ty="question", cat="Cechy i opinie", sub="Ocena",
      ph="{ph} mǎi khráp", th="{th}ไหมครับ",
      lit="mǎi = partykuła pytajna na końcu zdania",
      note="Pytanie o cechę: sam przymiotnik plus „mǎi”. Bez czasownika „być”.",
      ex_ph="nít nòi khráp", ex_th="นิดหน่อยครับ",
      items=[
        ("Czy to jest świeże?", "świeży", "Trochę."),
        ("Czy to jest dojrzałe?", "dojrzały", "Trochę."),
        ("Czy to jest ciężkie?", "ciężki", "Trochę."),
        ("Czy to jest twarde?", "twardy", "Trochę."),
        ("Czy to jest interesujące?", "interesujący", "Trochę."),
        ("Czy to ważne?", "ważny", "Trochę."),
        ("Czy to prawda?", "prawdziwy", "Trochę."),
      ]),

 dict(key="WANTV", ty="sentence", cat="Czasowniki", sub="Modalne",
      ph="phǒm yàak {ph}", th="ผมอยาก{th}",
      lit="yàak + czasownik = chcieć coś zrobić",
      note="Kobieta powie „chǎn yàak…”.",
      ex_ph="dâai loei khráp", ex_th="ได้เลยครับ",
      items=[
        ("Chcę odpocząć.", "odpocząć", "Jasne, proszę bardzo."),
        ("Chcę porozmawiać.", "rozmawiać", "Jasne, proszę bardzo."),
        ("Chcę zaśpiewać.", "śpiewać", "Jasne, proszę bardzo."),
        ("Chcę potańczyć.", "tańczyć", "Jasne, proszę bardzo."),
      ]),

 dict(key="CANI", ty="question", cat="Czasowniki", sub="Modalne",
      ph="{ph} dâai mǎi khráp", th="{th}ได้ไหมครับ",
      lit="dâai mǎi = czy można",
      note="Najprostszy sposób proszenia o pozwolenie.",
      ex_ph="dâai khráp chəən loei", ex_th="ได้ครับ เชิญเลย",
      items=[
        ("Czy mogę pożyczyć?", "pożyczyć", "Można, proszę bardzo."),
        ("Czy mogę wybrać?", "wybierać", "Można, proszę bardzo."),
        ("Czy mogę tego użyć?", "używać", "Można, proszę bardzo."),
        ("Czy może pan pokazać?", "pokazać", "Można, proszę bardzo."),
      ]),

 dict(key="MUST", ty="sentence", cat="Czasowniki", sub="Modalne",
      ph="phǒm tâwng {ph}", th="ผมต้อง{th}",
      lit="tâwng = musieć",
      note="",
      ex_ph="tâwng tham tawn nǎi khráp", ex_th="ต้องทำตอนไหนครับ",
      items=[
        ("Muszę się spakować.", "pakować się", "Kiedy trzeba to zrobić?"),
        ("Muszę wcześnie wstać.", "wstawać", "Kiedy trzeba to zrobić?"),
        ("Muszę się przesiąść.", "przesiadać się", "Kiedy trzeba to zrobić?"),
        ("Muszę podpisać.", "podpisać", "Kiedy trzeba to zrobić?"),
        ("Muszę wypełnić formularz.", "wypełnić formularz", "Kiedy trzeba to zrobić?"),
      ]),

 dict(key="NOTYET", ty="sentence", cat="Czasowniki", sub="Modalne",
      ph="yang mâi dâai {ph}", th="ยังไม่ได้{th}",
      lit="yang mâi dâai = jeszcze tego nie zrobiłem",
      note="Konstrukcja o czynności, która wciąż czeka na wykonanie.",
      ex_ph="dǐao tham khráp", ex_th="เดี๋ยวทำครับ",
      items=[
        ("Jeszcze się nie spakowałem.", "pakować się", "Zaraz to zrobię."),
        ("Jeszcze nie podpisałem.", "podpisać", "Zaraz to zrobię."),
        ("Jeszcze nie wybrałem.", "wybierać", "Zaraz to zrobię."),
        ("Jeszcze nie zacząłem.", "zaczynać", "Zaraz to zrobię."),
      ]),

 dict(key="LIKEV", ty="sentence", cat="Czasowniki", sub="Rozrywka",
      ph="phǒm châwp {ph}", th="ผมชอบ{th}",
      lit="châwp = lubić",
      note="",
      ex_ph="phǒm kâw châwp mǔean kan", ex_th="ผมก็ชอบเหมือนกัน",
      items=[
        ("Lubię śpiewać.", "śpiewać", "Ja też to lubię."),
        ("Lubię tańczyć.", "tańczyć", "Ja też to lubię."),
        ("Lubię rozmawiać.", "rozmawiać", "Ja też to lubię."),
        ("Lubię odpoczywać.", "odpocząć", "Ja też to lubię."),
      ]),
]
