# -*- coding: utf-8 -*-
"""Sesja F — DOM: pomieszczenia, wyposazenie, lazienka.

Uwaga o klasyfikatorach: przy liczeniu rzeczy tajski wymaga klasyfikatora
(„tó sǎwng tua” — dwa stoly). W notatkach przy czesci hasel podany jest
wlasciwy klasyfikator, bo bez niego zdanie z liczba brzmi niepoprawnie.
"""

CD = "Dom i codzienność"

HOUSE = [

# ============================================================ POMIESZCZENIA
("A1", "podłoga", "phúen", "พื้น", CD, "Wnętrze", 4, "n",
 "To samo słowo znaczy „powierzchnia, teren, tło”. W Tajlandii siada się na podłodze często — jest to przestrzeń czysta.",
 "",
 [("Podłoga jest mokra.", "phúen pìak khráp", "พื้นเปียกครับ"),
  ("Proszę usiąść na podłodze.", "nâng bon phúen dâai khráp", "นั่งบนพื้นได้ครับ")],
 ["ściana", "sufit", "zamiatać"], []),

("A2", "ściana", "fǎa", "ฝา", CD, "Wnętrze", 3, "n",
 "Ton rosnący. Uwaga: „fáa” z tonem wysokim to niebo — te dwa słowa różni tylko ton.",
 "",
 [("Na ścianie jest jaszczurka.", "thîi fǎa mii jîng-jòk khráp", "ที่ฝามีจิ้งจกครับ"),
  ("Ściana jest brudna.", "fǎa sòk-kà-pròk khráp", "ฝาสกปรกครับ")],
 ["podłoga", "sufit", "niebieski"], []),

("A2", "sufit", "phé-daan", "เพดาน", CD, "Wnętrze", 3, "n",
 "Przydatne przy zgłaszaniu przecieku w wynajmowanym mieszkaniu.",
 "",
 [("Sufit przecieka.", "phé-daan rûa khráp", "เพดานรั่วครับ"),
  ("Wentylator jest na suficie.", "phát lom yùu thîi phé-daan khráp", "พัดลมอยู่ที่เพดานครับ")],
 ["podłoga", "ściana", "wentylator"], []),

("A2", "dach", "lǎng-khaa", "หลังคา", CD, "Wnętrze", 3, "n",
 "Zawiera „lǎng” (plecy, tył) — dosłownie „plecy domu”.",
 "",
 [("Dach przecieka.", "lǎng-khaa rûa khráp", "หลังคารั่วครับ"),
  ("Na dachu jest taras.", "bon lǎng-khaa mii dàat fáa khráp", "บนหลังคามีดาดฟ้าครับ")],
 ["sufit", "deszcz"], []),

("A2", "schody", "ban-dai", "บันได", CD, "Wnętrze", 4, "n",
 "To samo słowo oznacza drabinę. Częste na tabliczkach: „rá-wang ban-dai”.",
 "",
 [("Uważaj na schodach.", "rá-wang ban-dai khráp", "ระวังบันไดครับ"),
  ("Mieszkam na górze, po schodach.", "phǒm yùu khâang bon khûen ban-dai khráp", "ผมอยู่ข้างบนขึ้นบันไดครับ")],
 ["winda", "piętro", "wchodzić na górę"], ["drabina"]),

("A2", "łazienka", "hâwng-nám", "ห้องน้ำ", CD, "Wnętrze", 5, "n",
 "Dosłownie „pokój wodny”. To samo słowo oznacza toaletę publiczną — pytanie „hâwng-nám yùu nǎi khráp” jest jednym z najważniejszych w podróży.",
 "pokój woda",
 [("Gdzie jest łazienka?", "hâwng-nám yùu nǎi khráp", "ห้องน้ำอยู่ไหนครับ"),
  ("Łazienka jest zajęta.", "hâwng-nám mâi wâang khráp", "ห้องน้ำไม่ว่างครับ")],
 ["toaleta", "prysznic", "pokój"], []),

("A2", "korytarz", "thaang doen", "ทางเดิน", CD, "Wnętrze", 3, "n",
 "Dosłownie „droga do chodzenia”. „thaang” to bardzo produktywne słowo: thaang àwk (wyjście), thaang khâo (wejście).",
 "droga chodzić",
 [("Pokój jest na końcu korytarza.", "hâwng yùu sùt thaang doen khráp", "ห้องอยู่สุดทางเดินครับ"),
  ("Proszę nie zastawiać korytarza.", "yàa waang khǎwng nai thaang doen khráp", "อย่าวางของในทางเดินครับ")],
 ["wejście", "wyjście", "chodzić"], []),

("A2", "ogród", "sǔan", "สวน", CD, "Wnętrze", 3, "n",
 "To samo słowo znaczy „park” — „sǔan sà-thǎa-rá-ná” to park publiczny.",
 "",
 [("Za domem jest ogród.", "lǎng bâan mii sǔan khráp", "หลังบ้านมีสวนครับ"),
  ("Idziemy do parku.", "rao pai sǔan khráp", "เราไปสวนครับ")],
 ["park", "drzewo", "kwiat"], []),

("A2", "brama", "prà-tuu rúa", "ประตูรั้ว", CD, "Wnętrze", 2, "n",
 "„prà-tuu” to drzwi, „rúa” to płot. Razem: brama w ogrodzeniu.",
 "drzwi płot",
 [("Brama jest zamknięta.", "prà-tuu rúa pìt yùu khráp", "ประตูรั้วปิดอยู่ครับ"),
  ("Proszę zamknąć bramę.", "chûai pìt prà-tuu rúa dûai khráp", "ช่วยปิดประตูรั้วด้วยครับ")],
 ["drzwi", "zamek (w drzwiach)"], []),

# ============================================================ WYPOSAZENIE
("A2", "zamek (w drzwiach)", "kun-jae lák", "กุญแจล็อค", CD, "Wyposażenie", 3, "n",
 "„kun-jae” to zarazem klucz i zamek. Przy problemie z zamkiem w hotelu: „kun-jae sǐa khráp”.",
 "klucz blokada",
 [("Zamek się zaciął.", "kun-jae sǐa khráp", "กุญแจเสียครับ"),
  ("Nie mogę otworzyć zamka.", "phǒm pòoet kun-jae mâi dâai khráp", "ผมเปิดกุญแจไม่ได้ครับ")],
 ["klucz", "drzwi", "psuć się"], []),

("A2", "dzwonek do drzwi", "krà-dìng prà-tuu", "กระดิ่งประตู", CD, "Wyposażenie", 2, "n",
 "Rzadszy niż w Europie — w wielu domach po prostu się woła.",
 "dzwonek drzwi",
 [("Dzwonek nie działa.", "krà-dìng prà-tuu sǐa khráp", "กระดิ่งประตูเสียครับ"),
  ("Ktoś dzwoni do drzwi.", "mii khon kòt krà-dìng khráp", "มีคนกดกระดิ่งครับ")],
 ["drzwi", "psuć się"], []),

("A2", "zasłona", "phâa mâan", "ผ้าม่าน", CD, "Wyposażenie", 3, "n",
 "„phâa” to tkanina i zaczyna wiele nazw: phâa chét tua (ręcznik), phâa hòm (koc).",
 "tkanina zasłona",
 [("Proszę zasunąć zasłony.", "chûai pìt phâa mâan dûai khráp", "ช่วยปิดผ้าม่านด้วยครับ"),
  ("Zasłony są brudne.", "phâa mâan sòk-kà-pròk khráp", "ผ้าม่านสกปรกครับ")],
 ["okno", "koc", "światło"], []),

("A2", "koc", "phâa hòm", "ผ้าห่ม", CD, "Wyposażenie", 4, "n",
 "W hotelu z mocną klimatyzacją prośba o dodatkowy koc jest bardzo praktyczna.",
 "tkanina przykrywać",
 [("Poproszę jeszcze jeden koc.", "khǎw phâa hòm ìik phǔen khráp", "ขอผ้าห่มอีกผืนครับ"),
  ("Koc jest cienki.", "phâa hòm baang khráp", "ผ้าห่มบางครับ")],
 ["poduszka", "łóżko", "cienki"], []),

("A2", "prześcieradło", "phâa puu thîi nawn", "ผ้าปูที่นอน", CD, "Wyposażenie", 3, "n",
 "Dosłownie „tkanina rozłożona na spanie”. Przydatne przy prośbie o zmianę pościeli.",
 "tkanina rozłożyć spanie",
 [("Proszę zmienić prześcieradło.", "chûai plìan phâa puu thîi nawn khráp", "ช่วยเปลี่ยนผ้าปูที่นอนครับ"),
  ("Prześcieradło jest zabrudzone.", "phâa puu thîi nawn pûean khráp", "ผ้าปูที่นอนเปื้อนครับ")],
 ["koc", "pościel", "łóżko"], []),

("A2", "materac", "thîi nawn", "ที่นอน", CD, "Wyposażenie", 3, "n",
 "Dosłownie „miejsce do spania”. W tańszych pokojach bywa twardy — stąd częsta skarga „thîi nawn khǎeng”.",
 "miejsce spanie",
 [("Materac jest za twardy.", "thîi nawn khǎeng koen pai khráp", "ที่นอนแข็งเกินไปครับ"),
  ("Materac jest wygodny.", "thîi nawn nûm sà-baai khráp", "ที่นอนนุ่มสบายครับ")],
 ["łóżko", "poduszka", "miękki"], []),

("A2", "kanapa", "soo-faa", "โซฟา", CD, "Wyposażenie", 3, "n",
 "Zapożyczenie z angielskiego. Klasyfikator: „tua”, ten sam co przy krześle.",
 "",
 [("Kanapa jest wygodna.", "soo-faa nâng sà-baai khráp", "โซฟานั่งสบายครับ"),
  ("Usiądź na kanapie.", "nâng bon soo-faa khráp", "นั่งบนโซฟาครับ")],
 ["krzesło", "salon", "siedzieć"], []),

("A2", "półka", "chán waang khǎwng", "ชั้นวางของ", CD, "Wyposażenie", 3, "n",
 "„chán” znaczy zarówno półkę, jak i piętro. Kontekst rozstrzyga.",
 "poziom kłaść rzeczy",
 [("Połóż to na półce.", "waang bon chán khráp", "วางบนชั้นครับ"),
  ("Półka jest pełna.", "chán tem láew khráp", "ชั้นเต็มแล้วครับ")],
 ["szafa", "kłaść", "piętro"], []),

("A2", "szuflada", "lín chák", "ลิ้นชัก", CD, "Wyposażenie", 3, "n",
 "Zawiera „lín” — język. Dosłownie „wysuwany język”.",
 "język wysuwać",
 [("Klucze są w szufladzie.", "kun-jae yùu nai lín chák khráp", "กุญแจอยู่ในลิ้นชักครับ"),
  ("Szuflada się nie otwiera.", "lín chák pòoet mâi dâai khráp", "ลิ้นชักเปิดไม่ได้ครับ")],
 ["szafa", "półka", "klucz"], []),

("A2", "lustro", "krà-jòk ngao", "กระจกเงา", CD, "Wyposażenie", 3, "n",
 "Samo „krà-jòk” to szkło i szyba. „ngao” znaczy cień, odbicie.",
 "szkło odbicie",
 [("W łazience jest lustro.", "nai hâwng-nám mii krà-jòk khráp", "ในห้องน้ำมีกระจกครับ"),
  ("Lustro jest brudne.", "krà-jòk sòk-kà-pròk khráp", "กระจกสกปรกครับ")],
 ["łazienka", "okno"], []),

("A2", "żarówka", "làwt fai", "หลอดไฟ", CD, "Wyposażenie", 3, "n",
 "„fai” to ogień, światło i prąd zarazem. „làwt” to rurka.",
 "rurka światło",
 [("Żarówka się przepaliła.", "làwt fai khàat khráp", "หลอดไฟขาดครับ"),
  ("Proszę wymienić żarówkę.", "chûai plìan làwt fai dûai khráp", "ช่วยเปลี่ยนหลอดไฟด้วยครับ")],
 ["światło", "gniazdko", "psuć się"], []),

("A2", "włącznik", "sà-wít fai", "สวิตช์ไฟ", CD, "Wyposażenie", 3, "n",
 "Zapożyczenie z angielskiego plus „fai”. Praktyczne w nieznanym pokoju.",
 "przełącznik światło",
 [("Gdzie jest włącznik?", "sà-wít fai yùu nǎi khráp", "สวิตช์ไฟอยู่ไหนครับ"),
  ("Włącznik nie działa.", "sà-wít fai sǐa khráp", "สวิตช์ไฟเสียครับ")],
 ["światło", "żarówka", "gniazdko"], []),

("A2", "kran", "káwk nám", "ก๊อกน้ำ", CD, "Wyposażenie", 4, "n",
 "„nám” to woda. Częste przy zgłaszaniu usterki w wynajmowanym mieszkaniu.",
 "kurek woda",
 [("Kran cieknie.", "káwk nám rûa khráp", "ก๊อกน้ำรั่วครับ"),
  ("Nie ma wody z kranu.", "nám mâi lǎi khráp", "น้ำไม่ไหลครับ")],
 ["umywalka", "łazienka", "woda"], []),

("A2", "umywalka", "àang láang nâa", "อ่างล้างหน้า", CD, "Wyposażenie", 3, "n",
 "Dosłownie „miska do mycia twarzy”. „àang láang jaan” to zlewozmywak.",
 "miska myć twarz",
 [("Umywalka jest zatkana.", "àang láang nâa tan khráp", "อ่างล้างหน้าตันครับ"),
  ("Zlew jest zatkany.", "àang láang jaan tan khráp", "อ่างล้างจานตันครับ")],
 ["kran", "łazienka", "twarz"], ["zlew"]),

("A2", "papier toaletowy", "krà-dàat cham-rá", "กระดาษชำระ", CD, "Łazienka", 4, "n",
 "„krà-dàat” to papier. W wielu miejscach papieru nie ma w kabinie, tylko przy wejściu.",
 "papier oczyszczający",
 [("Nie ma papieru toaletowego.", "mâi mii krà-dàat cham-rá khráp", "ไม่มีกระดาษชำระครับ"),
  ("Poproszę papier toaletowy.", "khǎw krà-dàat cham-rá khráp", "ขอกระดาษชำระครับ")],
 ["toaleta", "łazienka"], []),

("A2", "szczoteczka do zębów", "praeng sǐi fan", "แปรงสีฟัน", CD, "Łazienka", 3, "n",
 "Zawiera „sǐi” — to samo słowo co kolor, tu w znaczeniu „szorować”.",
 "szczotka szorować zęby",
 [("Zapomniałem szczoteczki.", "phǒm luem praeng sǐi fan khráp", "ผมลืมแปรงสีฟันครับ"),
  ("Poproszę szczoteczkę do zębów.", "khǎw praeng sǐi fan khráp", "ขอแปรงสีฟันครับ")],
 ["myć zęby", "ząb", "pasta do zębów"], []),

("A2", "pasta do zębów", "yaa sǐi fan", "ยาสีฟัน", CD, "Łazienka", 3, "n",
 "„yaa” znaczy lek — dosłownie „lek do szorowania zębów”.",
 "lek szorować zęby",
 [("Skończyła się pasta.", "yaa sǐi fan mòt khráp", "ยาสีฟันหมดครับ"),
  ("Gdzie jest pasta do zębów?", "yaa sǐi fan yùu nǎi khráp", "ยาสีฟันอยู่ไหนครับ")],
 ["szczoteczka do zębów", "myć zęby", "lek"], []),

("A2", "szampon", "yaa sà phǒm", "ยาสระผม", CD, "Łazienka", 3, "n",
 "Znów „yaa”. „sà phǒm” to myć włosy.",
 "lek myć włosy",
 [("Poproszę szampon.", "khǎw yaa sà phǒm khráp", "ขอยาสระผมครับ"),
  ("Nie ma szamponu.", "mâi mii yaa sà phǒm khráp", "ไม่มียาสระผมครับ")],
 ["mydło", "włosy", "brać prysznic"], []),

("A2", "kosz na śmieci", "thǎng khà-yà", "ถังขยะ", CD, "Sprzątanie", 3, "n",
 "„thǎng” to zbiornik, wiadro. „khà-yà” to śmieci.",
 "wiadro śmieci",
 [("Gdzie jest kosz na śmieci?", "thǎng khà-yà yùu nǎi khráp", "ถังขยะอยู่ไหนครับ"),
  ("Kosz jest pełny.", "thǎng khà-yà tem láew khráp", "ถังขยะเต็มแล้วครับ")],
 ["śmieci", "wyrzucić", "sprzątać"], []),

("A2", "miotła", "mái kwàat", "ไม้กวาด", CD, "Sprzątanie", 3, "n",
 "„mái” znaczy drewno i przedrostkuje wiele narzędzi.",
 "drewno zamiatać",
 [("Gdzie jest miotła?", "mái kwàat yùu nǎi khráp", "ไม้กวาดอยู่ไหนครับ"),
  ("Poproszę miotłę.", "khǎw mái kwàat nòi khráp", "ขอไม้กวาดหน่อยครับ")],
 ["zamiatać", "sprzątać", "podłoga"], []),

("A2", "detergent", "nám yaa láang jaan", "น้ำยาล้างจาน", CD, "Sprzątanie", 3, "n",
 "Dosłownie „płyn do mycia talerzy”. „nám yaa” to ogólnie płyn chemiczny.",
 "płyn myć talerz",
 [("Skończył się płyn do naczyń.", "nám yaa láang jaan mòt khráp", "น้ำยาล้างจานหมดครับ"),
  ("Poproszę płyn do naczyń.", "khǎw nám yaa láang jaan khráp", "ขอน้ำยาล้างจานครับ")],
 ["zmywać naczynia", "mydło", "talerz"], []),

("A2", "proszek do prania", "phǒng sák fàwk", "ผงซักฟอก", CD, "Sprzątanie", 3, "n",
 "„phǒng” to proszek. Nie mylić z „phǒm” (włosy, ja).",
 "proszek prać",
 [("Poproszę proszek do prania.", "khǎw phǒng sák fàwk khráp", "ขอผงซักฟอกครับ"),
  ("Skończył się proszek.", "phǒng sák fàwk mòt khráp", "ผงซักฟอกหมดครับ")],
 ["prać", "pralka", "pralnia"], []),

("A2", "garnek", "mâw", "หม้อ", CD, "Kuchnia", 3, "n",
 "Ton rosnący. Uwaga: „mǎw” z innym tonem to lekarz — ćwicz różnicę.",
 "",
 [("Zupa jest w garnku.", "súp yùu nai mâw khráp", "ซุปอยู่ในหม้อครับ"),
  ("Poproszę duży garnek.", "khǎw mâw yài khráp", "ขอหม้อใหญ่ครับ")],
 ["patelnia", "gotować w wodzie", "kuchnia"], []),

("A2", "patelnia", "krà-thá", "กระทะ", CD, "Kuchnia", 3, "n",
 "Podstawowe narzędzie kuchni tajskiej — większość dań to „phàt”, czyli smażenie na patelni.",
 "",
 [("Smażę na patelni.", "phǒm phàt nai krà-thá khráp", "ผมผัดในกระทะครับ"),
  ("Patelnia jest gorąca.", "krà-thá ráwn khráp", "กระทะร้อนครับ")],
 ["garnek", "smażyć na patelni", "kuchnia"], []),

("A2", "miska", "chaam", "ชาม", CD, "Kuchnia", 4, "n",
 "Makaron i zupę podaje się w misce, nie na talerzu. Klasyfikator przy zamawianiu: „bà-mìi nùeng chaam”.",
 "",
 [("Poproszę miskę makaronu.", "khǎw bà-mìi nùeng chaam khráp", "ขอบะหมี่หนึ่งชามครับ"),
  ("Miska jest gorąca.", "chaam ráwn khráp", "ชามร้อนครับ")],
 ["talerz", "zupa", "makaron"], []),

("A2", "pudełko", "klàwng", "กล่อง", CD, "Wyposażenie", 4, "n",
 "Także klasyfikator: „khâao nùeng klàwng” to jedna porcja na wynos.",
 "",
 [("Poproszę na wynos.", "khǎw sài klàwng khráp", "ขอใส่กล่องครับ"),
  ("Co jest w tym pudełku?", "nai klàwng mii à-rai khráp", "ในกล่องมีอะไรครับ")],
 ["torba", "wkładać"], []),

("A2", "wiadro", "thǎng", "ถัง", CD, "Wyposażenie", 3, "n",
 "Także zbiornik na wodę i gaz: „thǎng kàet” to butla gazowa.",
 "",
 [("Poproszę wiadro wody.", "khǎw thǎng nám khráp", "ขอถังน้ำครับ"),
  ("Butla gazowa jest pusta.", "thǎng kàet mòt khráp", "ถังแก๊สหมดครับ")],
 ["kosz na śmieci", "woda"], []),

("A2", "przewód", "sǎai fai", "สายไฟ", CD, "Wyposażenie", 3, "n",
 "„sǎai” to linia, przewód, także trasa autobusu. „sǎai fai” to kabel elektryczny.",
 "linia prąd",
 [("Przewód jest uszkodzony.", "sǎai fai khàat khráp", "สายไฟขาดครับ"),
  ("Gdzie jest kabel?", "sǎai fai yùu nǎi khráp", "สายไฟอยู่ไหนครับ")],
 ["gniazdko", "ładowarka", "prąd"], ["kabel"]),

("A2", "prąd", "fai fáa", "ไฟฟ้า", CD, "Wyposażenie", 4, "n",
 "Dosłownie „ogień nieba”. Przy awarii: „fai dàp” — nie ma prądu.",
 "ogień niebo",
 [("Nie ma prądu.", "fai dàp khráp", "ไฟดับครับ"),
  ("Rachunek za prąd.", "bin khâa fai fáa khráp", "บิลค่าไฟฟ้าครับ")],
 ["światło", "przewód", "rachunek"], []),

("A2", "sprzątanie", "tham khwaam sà-àat", "ทำความสะอาด", CD, "Sprzątanie", 4, "n",
 "Dosłownie „robić czystość”. „sà-àat” to czysty.",
 "robić czystość",
 [("Sprzątam pokój.", "phǒm tham khwaam sà-àat hâwng khráp", "ผมทำความสะอาดห้องครับ"),
  ("Kiedy sprzątacie pokój?", "tham khwaam sà-àat hâwng mûea-rài khráp", "ทำความสะอาดห้องเมื่อไหร่ครับ")],
 ["sprzątać", "sprzątaczka", "czysty"], []),

("A2", "wynajmować (mieszkanie)", "châo", "เช่า", CD, "Mieszkanie", 4, "n",
 "Uwaga: „châo” to wynajmować od kogoś, „hâi châo” to wynajmować komuś. Różnica ważna przy czytaniu ogłoszeń.",
 "",
 [("Wynajmuję mieszkanie.", "phǒm châo hâwng khráp", "ผมเช่าห้องครับ"),
  ("Ile wynosi czynsz?", "khâa châo thâo-rài khráp", "ค่าเช่าเท่าไหร่ครับ")],
 ["czynsz", "kaucja", "umowa"], []),

("A2", "przeprowadzać się", "yáai bâan", "ย้ายบ้าน", CD, "Mieszkanie", 3, "n",
 "„yáai” samo znaczy przenosić. „yáai ngaan” — zmienić pracę.",
 "przenosić dom",
 [("Przeprowadzam się w przyszłym miesiącu.", "phǒm jà yáai bâan duean nâa khráp", "ผมจะย้ายบ้านเดือนหน้าครับ"),
  ("Przeprowadziłem się niedawno.", "phǒm phôoeng yáai bâan khráp", "ผมเพิ่งย้ายบ้านครับ")],
 ["wynajmować (mieszkanie)", "dom"], []),

("A2", "sąsiedztwo", "thǎew bâan", "แถวบ้าน", CD, "Mieszkanie", 4, "n",
 "„thǎew” znaczy „okolica, w pobliżu”. „thǎew níi” — tu w okolicy, bardzo częste przy pytaniu o drogę.",
 "okolica dom",
 [("Czy w okolicy jest apteka?", "thǎew níi mii ráan yaa mǎi khráp", "แถวนี้มีร้านยาไหมครับ"),
  ("Mieszkam w tej okolicy.", "phǒm yùu thǎew níi khráp", "ผมอยู่แถวนี้ครับ")],
 ["sąsiad", "apteka", "blisko"], ["okolica"]),
]
