# -*- coding: utf-8 -*-
"""Rdzenna baza leksykalna Thai All-in-One.
Krotka: (polski, fonetyka, pismo tajskie [tylko TTS], kategoria, podkategoria,
         czesc mowy, flagi, extra, survival, frekwencja 1-5)
flagi: order (mozna zamowic), buy (mozna kupic), place, vehicle, verb, adj,
       thing, person, time, num, phrase, particle, food, drink
extra: dla rzeczownikow = klasyfikator (fonetyka|tajski|polski opis),
       dla przymiotnikow = forma nijaka, dla czasownikow = ""
"""

CORE = [
# ---------------------------------------------------------------- PODSTAWY
("cześć / dzień dobry", "sawàt-dii", "สวัสดี", "Podstawy i grzeczność", "Powitania", "phrase", "phrase", "", 1, 5),
("dziękuję", "khàwp-khun", "ขอบคุณ", "Podstawy i grzeczność", "Zwroty grzecznościowe", "phrase", "phrase", "", 1, 5),
("dziękuję bardzo", "khàwp-khun mâak", "ขอบคุณมาก", "Podstawy i grzeczność", "Zwroty grzecznościowe", "phrase", "phrase", "", 1, 5),
("przepraszam", "khǎw-thôot", "ขอโทษ", "Podstawy i grzeczność", "Zwroty grzecznościowe", "phrase", "phrase", "", 1, 5),
("nie ma sprawy", "mâi pen rai", "ไม่เป็นไร", "Podstawy i grzeczność", "Zwroty grzecznościowe", "phrase", "phrase", "", 1, 5),
("tak", "châi", "ใช่", "Podstawy i grzeczność", "Tak i nie", "phrase", "phrase", "", 1, 5),
("nie", "mâi châi", "ไม่ใช่", "Podstawy i grzeczność", "Tak i nie", "phrase", "phrase", "", 1, 5),
("nie (przeczenie czasownika)", "mâi", "ไม่", "Podstawy i grzeczność", "Tak i nie", "particle", "particle", "", 1, 5),
("można / da się", "dâai", "ได้", "Podstawy i grzeczność", "Tak i nie", "verb", "particle", "", 1, 5),
("nie można", "mâi dâai", "ไม่ได้", "Podstawy i grzeczność", "Tak i nie", "phrase", "phrase", "", 1, 5),
("proszę (zapraszam)", "chəən", "เชิญ", "Podstawy i grzeczność", "Zwroty grzecznościowe", "phrase", "phrase", "", 1, 4),
("proszę (formalnie)", "karúnaa", "กรุณา", "Podstawy i grzeczność", "Zwroty grzecznościowe", "phrase", "phrase", "", 1, 3),
("do widzenia", "laa kàwn", "ลาก่อน", "Podstawy i grzeczność", "Pożegnania", "phrase", "phrase", "", 1, 4),
("do zobaczenia", "jəə kan mài", "เจอกันใหม่", "Podstawy i grzeczność", "Pożegnania", "phrase", "phrase", "", 1, 4),
("miło mi cię poznać", "yin-dii thîi dâai rúu-jàk", "ยินดีที่ได้รู้จัก", "Small talk", "Poznawanie ludzi", "phrase", "phrase", "", 1, 4),
("jak się masz?", "sabaai-dii mǎi", "สบายดีไหม", "Small talk", "Poznawanie ludzi", "phrase", "phrase", "", 1, 5),
("mam się dobrze", "sabaai-dii", "สบายดี", "Small talk", "Poznawanie ludzi", "phrase", "phrase", "", 1, 5),
("partykuła grzecznościowa (mężczyzna)", "khráp", "ครับ", "Podstawy i grzeczność", "Partykuły", "particle", "particle", "", 1, 5),
("partykuła grzecznościowa (kobieta)", "khâ", "ค่ะ", "Podstawy i grzeczność", "Partykuły", "particle", "particle", "", 1, 5),
("ja (mężczyzna)", "phǒm", "ผม", "Podstawy i grzeczność", "Zaimki", "pronoun", "person", "", 1, 5),
("ja (kobieta)", "chǎn", "ฉัน", "Podstawy i grzeczność", "Zaimki", "pronoun", "person", "", 1, 5),
("ty", "khun", "คุณ", "Podstawy i grzeczność", "Zaimki", "pronoun", "person", "", 1, 5),
("on / ona", "kháw", "เขา", "Podstawy i grzeczność", "Zaimki", "pronoun", "person", "", 1, 4),
("my", "rao", "เรา", "Podstawy i grzeczność", "Zaimki", "pronoun", "person", "", 1, 4),
("oni", "phûak-kháw", "พวกเขา", "Podstawy i grzeczność", "Zaimki", "pronoun", "person", "", 0, 3),
("pomocy!", "chûai dûai", "ช่วยด้วย", "Awarie i pomoc", "Nagłe wypadki", "phrase", "phrase", "", 1, 5),
("uwaga!", "rawang", "ระวัง", "Awarie i pomoc", "Nagłe wypadki", "phrase", "phrase", "", 1, 4),
("chwileczkę", "raw sàk khrûu", "รอสักครู่", "Podstawy i grzeczność", "Zwroty grzecznościowe", "phrase", "phrase", "", 1, 4),
("nie rozumiem", "mâi khâo-jai", "ไม่เข้าใจ", "Podstawy i grzeczność", "Komunikacja", "phrase", "phrase", "", 1, 5),
("rozumiem", "khâo-jai láew", "เข้าใจแล้ว", "Podstawy i grzeczność", "Komunikacja", "phrase", "phrase", "", 1, 5),
("nie wiem", "mâi rúu", "ไม่รู้", "Podstawy i grzeczność", "Komunikacja", "phrase", "phrase", "", 1, 5),

# ------------------------------------------------------- JEDZENIE I NAPOJE
("woda", "náam", "น้ำ", "Jedzenie i napoje", "Napoje", "noun", "order,buy,drink", "khùat|ขวด|butelka", 1, 5),
("woda butelkowana", "náam plào", "น้ำเปล่า", "Jedzenie i napoje", "Napoje", "noun", "order,buy,drink", "khùat|ขวด|butelka", 1, 5),
("lód", "náam khǎeng", "น้ำแข็ง", "Jedzenie i napoje", "Napoje", "noun", "order,drink", "thǔng|ถุง|torebka", 1, 5),
("sok pomarańczowy", "náam sôm", "น้ำส้ม", "Jedzenie i napoje", "Napoje", "noun", "order,buy,drink", "kâew|แก้ว|szklanka", 1, 4),
("woda kokosowa", "náam maphráaw", "น้ำมะพร้าว", "Jedzenie i napoje", "Napoje", "noun", "order,buy,drink", "lûuk|ลูก|sztuka", 1, 4),
("kawa", "kaa-fae", "กาแฟ", "Jedzenie i napoje", "Napoje", "noun", "order,buy,drink", "kâew|แก้ว|szklanka", 1, 5),
("kawa mrożona", "kaa-fae yen", "กาแฟเย็น", "Jedzenie i napoje", "Napoje", "noun", "order,buy,drink", "kâew|แก้ว|szklanka", 1, 5),
("herbata", "chaa", "ชา", "Jedzenie i napoje", "Napoje", "noun", "order,buy,drink", "kâew|แก้ว|szklanka", 1, 4),
("herbata mrożona", "chaa yen", "ชาเย็น", "Jedzenie i napoje", "Napoje", "noun", "order,buy,drink", "kâew|แก้ว|szklanka", 1, 4),
("mleko", "nom", "นม", "Jedzenie i napoje", "Napoje", "noun", "order,buy,drink", "khùat|ขวด|butelka", 0, 4),
("piwo", "bia", "เบียร์", "Jedzenie i napoje", "Napoje", "noun", "order,buy,drink", "khùat|ขวด|butelka", 1, 5),
("alkohol", "lâo", "เหล้า", "Jedzenie i napoje", "Napoje", "noun", "order,buy,drink", "khùat|ขวด|butelka", 0, 3),
("wino", "wai", "ไวน์", "Jedzenie i napoje", "Napoje", "noun", "order,buy,drink", "kâew|แก้ว|kieliszek", 0, 3),
("woda gazowana", "soo-daa", "โซดา", "Jedzenie i napoje", "Napoje", "noun", "order,buy,drink", "khùat|ขวด|butelka", 0, 3),
("ryż", "khâaw", "ข้าว", "Jedzenie i napoje", "Dania główne", "noun", "order,buy,food", "jaan|จาน|talerz", 1, 5),
("ryż smażony", "khâaw phàt", "ข้าวผัด", "Jedzenie i napoje", "Dania główne", "noun", "order,buy,food", "jaan|จาน|talerz", 1, 5),
("ryż kleisty", "khâaw nǐaw", "ข้าวเหนียว", "Jedzenie i napoje", "Dania główne", "noun", "order,buy,food", "thǔng|ถุง|porcja", 1, 4),
("makaron ryżowy w rosole", "kǔai-tǐaw", "ก๋วยเตี๋ยว", "Jedzenie i napoje", "Dania główne", "noun", "order,buy,food", "chaam|ชาม|miska", 1, 5),
("pad thai", "phàt thai", "ผัดไทย", "Jedzenie i napoje", "Dania główne", "noun", "order,buy,food", "jaan|จาน|talerz", 1, 5),
("zupa tom yam z krewetkami", "tôm yam kûng", "ต้มยำกุ้ง", "Jedzenie i napoje", "Dania główne", "noun", "order,buy,food", "chaam|ชาม|miska", 1, 4),
("sałatka z zielonej papai", "sôm tam", "ส้มตำ", "Jedzenie i napoje", "Dania główne", "noun", "order,buy,food", "jaan|จาน|talerz", 1, 5),
("zielone curry", "kaeng khǐaw wǎan", "แกงเขียวหวาน", "Jedzenie i napoje", "Dania główne", "noun", "order,buy,food", "jaan|จาน|talerz", 0, 4),
("kurczak", "kài", "ไก่", "Jedzenie i napoje", "Mięso i ryby", "noun", "order,buy,food", "tua|ตัว|sztuka", 1, 5),
("wieprzowina", "mǔu", "หมู", "Jedzenie i napoje", "Mięso i ryby", "noun", "order,buy,food", "jaan|จาน|porcja", 1, 5),
("wołowina", "núea", "เนื้อ", "Jedzenie i napoje", "Mięso i ryby", "noun", "order,buy,food", "jaan|จาน|porcja", 1, 4),
("ryba", "plaa", "ปลา", "Jedzenie i napoje", "Mięso i ryby", "noun", "order,buy,food", "tua|ตัว|sztuka", 1, 4),
("krewetki", "kûng", "กุ้ง", "Jedzenie i napoje", "Mięso i ryby", "noun", "order,buy,food", "tua|ตัว|sztuka", 1, 4),
("krab", "puu", "ปู", "Jedzenie i napoje", "Mięso i ryby", "noun", "order,buy,food", "tua|ตัว|sztuka", 0, 3),
("kalmary", "plaa mùek", "ปลาหมึก", "Jedzenie i napoje", "Mięso i ryby", "noun", "order,buy,food", "tua|ตัว|sztuka", 0, 3),
("jajko", "khài", "ไข่", "Jedzenie i napoje", "Produkty", "noun", "order,buy,food", "fawng|ฟอง|sztuka", 1, 5),
("warzywa", "phàk", "ผัก", "Jedzenie i napoje", "Produkty", "noun", "order,buy,food", "jaan|จาน|porcja", 1, 4),
("owoce", "phǒn-la-máai", "ผลไม้", "Jedzenie i napoje", "Owoce", "noun", "order,buy,food", "jaan|จาน|porcja", 1, 4),
("mango", "mamûang", "มะม่วง", "Jedzenie i napoje", "Owoce", "noun", "order,buy,food", "lûuk|ลูก|sztuka", 1, 4),
("banan", "klûai", "กล้วย", "Jedzenie i napoje", "Owoce", "noun", "order,buy,food", "lûuk|ลูก|sztuka", 1, 4),
("ananas", "sàp-parót", "สับปะรด", "Jedzenie i napoje", "Owoce", "noun", "order,buy,food", "lûuk|ลูก|sztuka", 0, 3),
("arbuz", "taeng-moo", "แตงโม", "Jedzenie i napoje", "Owoce", "noun", "order,buy,food", "lûuk|ลูก|sztuka", 0, 3),
("pomarańcza", "sôm", "ส้ม", "Jedzenie i napoje", "Owoce", "noun", "order,buy,food", "lûuk|ลูก|sztuka", 0, 4),
("papaja", "malakaw", "มะละกอ", "Jedzenie i napoje", "Owoce", "noun", "order,buy,food", "lûuk|ลูก|sztuka", 0, 3),
("kokos", "maphráaw", "มะพร้าว", "Jedzenie i napoje", "Owoce", "noun", "order,buy,food", "lûuk|ลูก|sztuka", 0, 3),
("słodycze / przekąska", "khanǒm", "ขนม", "Jedzenie i napoje", "Produkty", "noun", "order,buy,food", "chín|ชิ้น|kawałek", 0, 4),
("chleb", "khanǒm pang", "ขนมปัง", "Jedzenie i napoje", "Produkty", "noun", "order,buy,food", "phàen|แผ่น|kromka", 0, 4),
("ryż kleisty z mango", "khâaw nǐaw mamûang", "ข้าวเหนียวมะม่วง", "Jedzenie i napoje", "Desery", "noun", "order,buy,food", "jaan|จาน|porcja", 0, 4),
("lody", "ai-sakhriim", "ไอศกรีม", "Jedzenie i napoje", "Desery", "noun", "order,buy,food", "thûai|ถ้วย|kubek", 0, 3),
("papryczka chili", "phrík", "พริก", "Jedzenie i napoje", "Przyprawy", "noun", "order,buy,food", "mét|เม็ด|sztuka", 1, 5),
("cukier", "náam-taan", "น้ำตาล", "Jedzenie i napoje", "Przyprawy", "noun", "order,buy,food", "cháwn|ช้อน|łyżka", 1, 4),
("sól", "kluea", "เกลือ", "Jedzenie i napoje", "Przyprawy", "noun", "order,buy,food", "cháwn|ช้อน|łyżka", 0, 3),
("sos rybny", "náam plaa", "น้ำปลา", "Jedzenie i napoje", "Przyprawy", "noun", "order,buy,food", "khùat|ขวด|butelka", 0, 3),
("orzeszki ziemne", "thùa", "ถั่ว", "Jedzenie i napoje", "Przyprawy", "noun", "order,buy,food", "thǔng|ถุง|torebka", 1, 4),
("zupa", "súp", "ซุป", "Jedzenie i napoje", "Dania główne", "noun", "order,buy,food", "chaam|ชาม|miska", 0, 3),
("sałatka", "salàt", "สลัด", "Jedzenie i napoje", "Dania główne", "noun", "order,buy,food", "jaan|จาน|talerz", 0, 3),
("jedzenie", "aa-hǎan", "อาหาร", "Jedzenie i napoje", "Ogólne", "noun", "order,buy,food", "jaan|จาน|danie", 1, 5),
("śniadanie", "aa-hǎan cháo", "อาหารเช้า", "Jedzenie i napoje", "Posiłki", "noun", "order,food", "múue|มื้อ|posiłek", 1, 4),
("obiad", "aa-hǎan klaang-wan", "อาหารกลางวัน", "Jedzenie i napoje", "Posiłki", "noun", "order,food", "múue|มื้อ|posiłek", 1, 4),
("kolacja", "aa-hǎan yen", "อาหารเย็น", "Jedzenie i napoje", "Posiłki", "noun", "order,food", "múue|มื้อ|posiłek", 1, 4),
("jedzenie wegetariańskie", "aa-hǎan mang-sawírát", "อาหารมังสวิรัติ", "Jedzenie i napoje", "Dieta", "noun", "order,food", "jaan|จาน|danie", 1, 4),
("menu", "mee-nuu", "เมนู", "Restauracja", "Obsługa", "noun", "thing", "an|อัน|sztuka", 1, 5),
("łyżka", "cháwn", "ช้อน", "Restauracja", "Sztućce", "noun", "thing,buy", "an|อัน|sztuka", 1, 4),
("widelec", "sâwm", "ส้อม", "Restauracja", "Sztućce", "noun", "thing,buy", "an|อัน|sztuka", 1, 4),
("pałeczki", "takìap", "ตะเกียบ", "Restauracja", "Sztućce", "noun", "thing,buy", "khûu|คู่|para", 0, 3),
("nóż", "mîit", "มีด", "Restauracja", "Sztućce", "noun", "thing,buy", "lêm|เล่ม|sztuka", 0, 3),
("talerz", "jaan", "จาน", "Restauracja", "Zastawa", "noun", "thing,buy", "bai|ใบ|sztuka", 0, 3),
("szklanka", "kâew", "แก้ว", "Restauracja", "Zastawa", "noun", "thing,buy", "bai|ใบ|sztuka", 0, 4),
("serwetka", "kradàat chét paak", "กระดาษเช็ดปาก", "Restauracja", "Zastawa", "noun", "thing", "phàen|แผ่น|sztuka", 0, 3),
("rachunek", "bin", "บิล", "Restauracja", "Płatność", "noun", "thing", "bai|ใบ|sztuka", 1, 5),
("na wynos", "sài thǔng", "ใส่ถุง", "Restauracja", "Zamówienie", "phrase", "phrase", "", 1, 5),
("na miejscu", "kin thîi nîi", "กินที่นี่", "Restauracja", "Zamówienie", "phrase", "phrase", "", 1, 4),

# --------------------------------------------------------------- MIEJSCA
("toaleta", "hâwng náam", "ห้องน้ำ", "Miejsca i orientacja", "Obiekty", "noun", "place", "hâwng|ห้อง|pomieszczenie", 1, 5),
("hotel", "roong raem", "โรงแรม", "Hotel", "Obiekty", "noun", "place", "hàeng|แห่ง|obiekt", 1, 5),
("restauracja", "ráan aa-hǎan", "ร้านอาหาร", "Restauracja", "Obiekty", "noun", "place", "ráan|ร้าน|lokal", 1, 5),
("kawiarnia", "ráan kaa-fae", "ร้านกาแฟ", "Miejsca i orientacja", "Obiekty", "noun", "place", "ráan|ร้าน|lokal", 1, 4),
("targ", "talàat", "ตลาด", "Zakupy i pieniądze", "Obiekty", "noun", "place", "hàeng|แห่ง|obiekt", 1, 5),
("bazar nocny", "talàat klaang khuen", "ตลาดกลางคืน", "Zakupy i pieniądze", "Obiekty", "noun", "place", "hàeng|แห่ง|obiekt", 1, 4),
("centrum handlowe", "hâang", "ห้าง", "Zakupy i pieniądze", "Obiekty", "noun", "place", "hàeng|แห่ง|obiekt", 1, 4),
("sklep całodobowy", "ráan sadùak súe", "ร้านสะดวกซื้อ", "Zakupy i pieniądze", "Obiekty", "noun", "place", "ráan|ร้าน|sklep", 1, 4),
("supermarket", "suu-pəə-maa-két", "ซูเปอร์มาร์เก็ต", "Zakupy i pieniądze", "Obiekty", "noun", "place", "hàeng|แห่ง|obiekt", 0, 3),
("bank", "thanaakhaan", "ธนาคาร", "Zakupy i pieniądze", "Obiekty", "noun", "place", "hàeng|แห่ง|obiekt", 1, 4),
("bankomat", "tûu ee-thii-em", "ตู้เอทีเอ็ม", "Zakupy i pieniądze", "Obiekty", "noun", "place", "tûu|ตู้|automat", 1, 5),
("szpital", "roong phayaabaan", "โรงพยาบาล", "Zdrowie", "Obiekty", "noun", "place", "hàeng|แห่ง|obiekt", 1, 5),
("klinika", "khlii-ník", "คลินิก", "Zdrowie", "Obiekty", "noun", "place", "hàeng|แห่ง|obiekt", 1, 4),
("apteka", "ráan khǎai yaa", "ร้านขายยา", "Zdrowie", "Obiekty", "noun", "place", "ráan|ร้าน|lokal", 1, 5),
("komisariat policji", "sathǎanii tamrùat", "สถานีตำรวจ", "Awarie i pomoc", "Obiekty", "noun", "place", "hàeng|แห่ง|obiekt", 1, 4),
("lotnisko", "sanǎam bin", "สนามบิน", "Transport", "Obiekty", "noun", "place", "hàeng|แห่ง|obiekt", 1, 5),
("dworzec kolejowy", "sathǎanii rót fai", "สถานีรถไฟ", "Transport", "Obiekty", "noun", "place", "hàeng|แห่ง|obiekt", 1, 4),
("dworzec autobusowy", "sathǎanii khǒn sòng", "สถานีขนส่ง", "Transport", "Obiekty", "noun", "place", "hàeng|แห่ง|obiekt", 1, 4),
("przystań / port", "thâa ruea", "ท่าเรือ", "Transport", "Obiekty", "noun", "place", "hàeng|แห่ง|obiekt", 0, 3),
("świątynia", "wát", "วัด", "Miejsca i orientacja", "Turystyka", "noun", "place", "hàeng|แห่ง|obiekt", 1, 4),
("plaża", "chaai hàat", "ชายหาด", "Miejsca i orientacja", "Turystyka", "noun", "place", "hàeng|แห่ง|obiekt", 1, 4),
("morze", "thalee", "ทะเล", "Miejsca i orientacja", "Przyroda", "noun", "place", "hàeng|แห่ง|obiekt", 0, 4),
("góra", "phuu khǎo", "ภูเขา", "Miejsca i orientacja", "Przyroda", "noun", "place", "lûuk|ลูก|sztuka", 0, 3),
("wyspa", "kàw", "เกาะ", "Miejsca i orientacja", "Przyroda", "noun", "place", "kàw|เกาะ|wyspa", 1, 4),
("park", "sǔan sǎathaaraná", "สวนสาธารณะ", "Miejsca i orientacja", "Turystyka", "noun", "place", "hàeng|แห่ง|obiekt", 0, 3),
("salon masażu", "ráan nûat", "ร้านนวด", "Miejsca i orientacja", "Usługi", "noun", "place", "ráan|ร้าน|lokal", 1, 4),
("szkoła", "roong rian", "โรงเรียน", "Praca i nauka", "Obiekty", "noun", "place", "hàeng|แห่ง|obiekt", 0, 3),
("uniwersytet", "mahǎawítthayaalai", "มหาวิทยาลัย", "Praca i nauka", "Obiekty", "noun", "place", "hàeng|แห่ง|obiekt", 0, 3),
("biuro", "áwf-fít", "ออฟฟิศ", "Praca i nauka", "Obiekty", "noun", "place", "hàeng|แห่ง|obiekt", 0, 3),
("dom", "bâan", "บ้าน", "Dom i codzienność", "Mieszkanie", "noun", "place", "lǎng|หลัง|budynek", 1, 5),
("pokój", "hâwng", "ห้อง", "Hotel", "Mieszkanie", "noun", "place,buy", "hâwng|ห้อง|pokój", 1, 5),
("winda", "líf", "ลิฟต์", "Hotel", "Obiekty", "noun", "place", "tua|ตัว|sztuka", 0, 3),
("wyjście", "thaang àwk", "ทางออก", "Miejsca i orientacja", "Orientacja", "noun", "place", "thaang|ทาง|przejście", 1, 4),
("wejście", "thaang khâo", "ทางเข้า", "Miejsca i orientacja", "Orientacja", "noun", "place", "thaang|ทาง|przejście", 0, 3),
("ambasada", "sathǎan thûut", "สถานทูต", "Awarie i pomoc", "Obiekty", "noun", "place", "hàeng|แห่ง|obiekt", 1, 3),
("poczta", "praisanii", "ไปรษณีย์", "Miejsca i orientacja", "Usługi", "noun", "place", "hàeng|แห่ง|obiekt", 0, 3),
("pralnia", "ráan sák rîit", "ร้านซักรีด", "Miejsca i orientacja", "Usługi", "noun", "place", "ráan|ร้าน|lokal", 0, 3),
("siedem-jedenaście (sklep)", "see-wên", "เซเว่น", "Zakupy i pieniądze", "Obiekty", "noun", "place", "ráan|ร้าน|sklep", 1, 5),

# ------------------------------------------------------------- TRANSPORT
("samochód", "rót", "รถ", "Transport", "Pojazdy", "noun", "vehicle,buy", "khan|คัน|sztuka", 1, 5),
("taksówka", "tháek-sîi", "แท็กซี่", "Transport", "Pojazdy", "noun", "vehicle", "khan|คัน|sztuka", 1, 5),
("motocykl", "maw-tôe-sai", "มอเตอร์ไซค์", "Transport", "Pojazdy", "noun", "vehicle,buy", "khan|คัน|sztuka", 1, 5),
("tuk-tuk", "túk túk", "ตุ๊กตุ๊ก", "Transport", "Pojazdy", "noun", "vehicle", "khan|คัน|sztuka", 1, 4),
("minibus", "rót tûu", "รถตู้", "Transport", "Pojazdy", "noun", "vehicle", "khan|คัน|sztuka", 1, 4),
("autobus", "rót bát", "รถบัส", "Transport", "Pojazdy", "noun", "vehicle", "khan|คัน|sztuka", 1, 4),
("autobus miejski", "rót mee", "รถเมล์", "Transport", "Pojazdy", "noun", "vehicle", "khan|คัน|sztuka", 0, 4),
("pociąg", "rót fai", "รถไฟ", "Transport", "Pojazdy", "noun", "vehicle", "khabuan|ขบวน|skład", 1, 4),
("metro naziemne", "rót fai fáa", "รถไฟฟ้า", "Transport", "Pojazdy", "noun", "vehicle", "khabuan|ขบวน|skład", 1, 4),
("łódź", "ruea", "เรือ", "Transport", "Pojazdy", "noun", "vehicle", "lam|ลำ|sztuka", 1, 4),
("samolot", "khrûeang bin", "เครื่องบิน", "Transport", "Pojazdy", "noun", "vehicle", "lam|ลำ|sztuka", 1, 4),
("rower", "jàkkrayaan", "จักรยาน", "Transport", "Pojazdy", "noun", "vehicle,buy", "khan|คัน|sztuka", 0, 3),
("bilet", "tǔa", "ตั๋ว", "Transport", "Podróż", "noun", "thing,buy", "bai|ใบ|sztuka", 1, 5),
("walizka", "krapǎo dəən thaang", "กระเป๋าเดินทาง", "Transport", "Podróż", "noun", "thing,buy", "bai|ใบ|sztuka", 1, 4),
("paszport", "nǎng-sǔe dəən thaang", "หนังสือเดินทาง", "Transport", "Podróż", "noun", "thing", "lêm|เล่ม|sztuka", 1, 4),
("wiza", "wii-sâa", "วีซ่า", "Transport", "Podróż", "noun", "thing", "bai|ใบ|sztuka", 1, 3),
("mapa", "phǎen thîi", "แผนที่", "Miejsca i orientacja", "Orientacja", "noun", "thing,buy", "bai|ใบ|sztuka", 0, 3),
("ulica", "thanǒn", "ถนน", "Miejsca i orientacja", "Orientacja", "noun", "place", "sǎai|สาย|ulica", 1, 4),
("uliczka boczna", "soi", "ซอย", "Miejsca i orientacja", "Orientacja", "noun", "place", "soi|ซอย|uliczka", 1, 5),
("most", "saphaan", "สะพาน", "Miejsca i orientacja", "Orientacja", "noun", "place", "saphaan|สะพาน|most", 0, 3),
("skrzyżowanie", "sìi yâek", "สี่แยก", "Miejsca i orientacja", "Orientacja", "noun", "place", "yâek|แยก|skrzyżowanie", 1, 4),
("kask", "mùak kan nók", "หมวกกันน็อค", "Transport", "Wyposażenie", "noun", "thing,buy", "bai|ใบ|sztuka", 1, 3),
("benzyna", "náam man", "น้ำมัน", "Transport", "Wyposażenie", "noun", "thing,buy", "lít|ลิตร|litr", 1, 4),
("prawo jazdy", "bai khàp khìi", "ใบขับขี่", "Transport", "Podróż", "noun", "thing", "bai|ใบ|sztuka", 0, 3),
]
