# -*- coding: utf-8 -*-
"""Dialogi etapu 3 (A2) — czesc A: restauracja, hotel, transport, spotkania.

Krotka: (tytul, sytuacja, poziom, rola A, rola B, kwestie, notatka)
Kwestia: (rola, polski, fonetyka, tajski)
"""

DIALOGUES_A2_A = [

("Rezerwacja stolika przez telefon", "Restauracja", "A2", "Gość", "Restauracja", [
 ("B", "Dzień dobry, restauracja Baan Suan.", "sawàt-dii khráp ráan baan sǔan khráp", "สวัสดีครับ ร้านบ้านสวนครับ"),
 ("A", "Dzień dobry, chciałbym zarezerwować stolik.", "sawàt-dii khráp phǒm yàak jawng tó khráp", "สวัสดีครับ ผมอยากจองโต๊ะครับ"),
 ("B", "Na kiedy i dla ilu osób?", "wan nǎi láe kìi khon khráp", "วันไหนและกี่คนครับ"),
 ("A", "Na jutro wieczorem, cztery osoby.", "phrûng níi tawn yen sìi khon khráp", "พรุ่งนี้ตอนเย็นสี่คนครับ"),
 ("B", "O której godzinie?", "kìi moong khráp", "กี่โมงครับ"),
 ("A", "O siódmej. Pasuje?", "nùeng thûm dâai mǎi khráp", "หนึ่งทุ่มได้ไหมครับ"),
 ("B", "Może być. Wewnątrz czy na zewnątrz?", "dâai khráp khâang nai rǔe khâang nâwk khráp", "ได้ครับ ข้างในหรือข้างนอกครับ"),
 ("A", "Wolimy stolik na zewnątrz.", "raw châwp tó khâang nâwk mâak-kwàa khráp", "เราชอบโต๊ะข้างนอกมากกว่าครับ"),
 ("B", "Poproszę nazwisko i numer telefonu.", "khǎw chûe kàp boe thoo khráp", "ขอชื่อกับเบอร์โทรครับ"),
 ("A", "Kowalski. Numer podam teraz.", "kow-waan-sà-kîi khráp dǐao bàwk boe khráp", "โควาลสกีครับ เดี๋ยวบอกเบอร์ครับ"),
 ("B", "Zarezerwowane. Do zobaczenia jutro.", "jawng hâi láew khráp phrûng níi jôe kan khráp", "จองให้แล้วครับ พรุ่งนี้เจอกันครับ"),
 ("A", "Dziękuję bardzo.", "khàwp-khun mâak khráp", "ขอบคุณมากครับ"),
], "„jawng” to rezerwacja stolika, hotelu i biletu. „thûm” liczy godziny wieczorne: nùeng thûm = 19:00."),

("Zamawianie z preferencjami", "Restauracja", "A2", "Gość", "Kelner", [
 ("B", "Są państwo gotowi zamówić?", "phráwm sàng rǔe yang khráp", "พร้อมสั่งหรือยังครับ"),
 ("A", "Tak. Co pan poleca?", "phráwm khráp náe-nam à-rai dii khráp", "พร้อมครับ แนะนำอะไรดีครับ"),
 ("B", "Dziś polecam rybę na parze.", "wan níi náe-nam plaa nûeng khráp", "วันนี้แนะนำปลานึ่งครับ"),
 ("A", "Czy to danie jest ostre?", "aa-hǎan níi phèt mǎi khráp", "อาหารนี้เผ็ดไหมครับ"),
 ("B", "Trochę ostre.", "phèt nít nòi khráp", "เผ็ดนิดหน่อยครับ"),
 ("A", "Proszę bardzo mało ostre.", "khǎw phèt nói mâak khráp", "ขอเผ็ดน้อยมากครับ"),
 ("B", "Dobrze. Coś do picia?", "dâai khráp ráp khrûeang dùem à-rai khráp", "ได้ครับ รับเครื่องดื่มอะไรครับ"),
 ("A", "Wodę bez lodu poproszę.", "khǎw náam mâi sài náam khǎeng khráp", "ขอน้ำไม่ใส่น้ำแข็งครับ"),
 ("B", "Jeszcze coś?", "ráp à-rai ìik mǎi khráp", "รับอะไรอีกไหมครับ"),
 ("A", "Mam uczulenie na owoce morza — proszę uważać.", "phǒm pháe aa-hǎan thá-lee khráp chûai rá-wang dûai", "ผมแพ้อาหารทะเลครับ ช่วยระวังด้วย"),
 ("B", "Powiem kucharzowi.", "jà bàwk phâw khrua khráp", "จะบอกพ่อครัวครับ"),
 ("A", "Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ"),
], "„phèt nói” to słabo ostre, a „mâi phèt” — wcale. Przy alergii zawsze mów „phǎe” plus nazwa produktu."),

("Reklamacja w restauracji", "Restauracja", "A2", "Gość", "Kelner", [
 ("A", "Przepraszam, to nie jest to, co zamawiałem.", "khǎw-thôot khráp nîi mâi châi thîi phǒm sàng", "ขอโทษครับ นี่ไม่ใช่ที่ผมสั่ง"),
 ("B", "Bardzo przepraszam. Co pan zamawiał?", "khǎw-thôot jing jing khráp sàng à-rai khráp", "ขอโทษจริงๆ ครับ สั่งอะไรครับ"),
 ("A", "Kurczaka grillowanego, nie smażonego.", "kài yâang mâi châi kài thâwt khráp", "ไก่ย่าง ไม่ใช่ไก่ทอดครับ"),
 ("B", "Sprawdzę zamówienie.", "khǎw chék raai-kaan khráp", "ขอเช็ครายการครับ"),
 ("A", "I danie jest zimne.", "láew aa-hǎan kâw yen dûai khráp", "แล้วอาหารก็เย็นด้วยครับ"),
 ("B", "Podgrzejemy i wymienimy.", "dǐao ùn láew plìan hâi mài khráp", "เดี๋ยวอุ่นแล้วเปลี่ยนให้ใหม่ครับ"),
 ("A", "Jak długo trzeba czekać?", "tâwng raw naan thâo-rài khráp", "ต้องรอนานเท่าไหร่ครับ"),
 ("B", "Około dziesięciu minut.", "prà-maan sìp naa-thii khráp", "ประมาณสิบนาทีครับ"),
 ("A", "Dobrze, poczekamy.", "dâai khráp raw dâai", "ได้ครับ รอได้"),
 ("B", "Przepraszam za opóźnienie.", "khǎw-thôot thîi cháa khráp", "ขอโทษที่ช้าครับ"),
 ("A", "Nic się nie stało.", "mâi pen rai khráp", "ไม่เป็นไรครับ"),
], "„mâi châi thîi phǒm sàng” to uprzejma reklamacja: mówimy o zamówieniu, nie o winie kelnera."),

("Płacenie i dzielenie rachunku", "Restauracja", "A2", "Gość", "Kelner", [
 ("A", "Poproszę rachunek.", "chék bin dûai khráp", "เช็คบิลด้วยครับ"),
 ("B", "Razem osiemset batów.", "tháng mòt pàet ráwi bàat khráp", "ทั้งหมดแปดร้อยบาทครับ"),
 ("A", "Chyba jest błąd w rachunku.", "bin nâa jà phìt khráp", "บิลน่าจะผิดครับ"),
 ("B", "Zaraz sprawdzę.", "dǐao chék hâi khráp", "เดี๋ยวเช็คให้ครับ"),
 ("A", "Nie zamawialiśmy piwa.", "raw mâi dâi sàng bia khráp", "เราไม่ได้สั่งเบียร์ครับ"),
 ("B", "Ma pan rację, poprawię.", "thùuk tâwng khráp dǐao kâe hâi", "ถูกต้องครับ เดี๋ยวแก้ให้"),
 ("A", "Czy w rachunku jest serwis?", "ruam khâa bawrí-kaan láew rǔe yang khráp", "รวมค่าบริการแล้วหรือยังครับ"),
 ("B", "Tak, dziesięć procent.", "ruam láew khráp sìp poe-sen", "รวมแล้วครับ สิบเปอร์เซ็นต์"),
 ("A", "Płacimy osobno.", "jàai yâek kan khráp", "จ่ายแยกกันครับ"),
 ("B", "Rozpiszę rachunek.", "dǐao yâek bin hâi khráp", "เดี๋ยวแยกบิลให้ครับ"),
 ("A", "Czy mogę zapłacić kartą?", "jàai dûai bàt dâai mǎi khráp", "จ่ายด้วยบัตรได้ไหมครับ"),
 ("B", "Można. Proszę tutaj.", "dâai khráp choen thaang níi", "ได้ครับ เชิญทางนี้"),
], "„chék bin” to najczęstsza forma prośby o rachunek. „yâek bin” — rozdzielić rachunek na osoby."),

("Wcześniejsze zameldowanie", "Hotel", "A2", "Gość", "Recepcja", [
 ("A", "Dzień dobry, mam rezerwację.", "sawàt-dii khráp phǒm jawng wái láew khráp", "สวัสดีครับ ผมจองไว้แล้วครับ"),
 ("B", "Poproszę nazwisko i paszport.", "khǎw chûe kàp phaas-pàwt khráp", "ขอชื่อกับพาสปอร์ตครับ"),
 ("A", "Proszę. Rezerwowałem przez internet.", "nîi khráp phǒm jawng phàan in-təə-nét khráp", "นี่ครับ ผมจองผ่านอินเทอร์เน็ตครับ"),
 ("B", "Widzę rezerwację. Pokój na dwie noce.", "jôe láew khráp hâwng sǎwng khuen", "เจอแล้วครับ ห้องสองคืน"),
 ("A", "Czy mogę zameldować się wcześniej?", "chék-in kàwn wee-laa dâai mǎi khráp", "เช็คอินก่อนเวลาได้ไหมครับ"),
 ("B", "Pokój będzie gotowy o dwunastej.", "hâwng phráwm tawn thîang khráp", "ห้องพร้อมตอนเที่ยงครับ"),
 ("A", "Czy mogę zostawić bagaż?", "khǎw fàak krà-pǎo wái dâai mǎi khráp", "ขอฝากกระเป๋าไว้ได้ไหมครับ"),
 ("B", "Oczywiście, tutaj z boku.", "dâai khráp wái trong níi", "ได้ครับ ไว้ตรงนี้"),
 ("A", "Poproszę cichy pokój.", "khǎw hâwng thîi ngîap nòi khráp", "ขอห้องที่เงียบหน่อยครับ"),
 ("B", "Damy pokój od podwórza.", "jà hâi hâwng dâan lǎng khráp", "จะให้ห้องด้านหลังครับ"),
 ("A", "Świetnie, dziękuję.", "dii mâak khráp khàwp-khun", "ดีมากครับ ขอบคุณ"),
], "„fàak … wái” znaczy zostawić coś pod opieką. Nie mylić z „thíng”, czyli wyrzucić."),

("Problem z pokojem", "Hotel", "A2", "Gość", "Recepcja", [
 ("A", "Dzień dobry, mam problem w pokoju.", "sawàt-dii khráp phǒm mii panhǎa nai hâwng khráp", "สวัสดีครับ ผมมีปัญหาในห้องครับ"),
 ("B", "Co się stało?", "koet à-rai khûen khráp", "เกิดอะไรขึ้นครับ"),
 ("A", "Nie ma ciepłej wody.", "mâi mii náam ùn khráp", "ไม่มีน้ำอุ่นครับ"),
 ("B", "Od kiedy?", "tâng tàe mûea-rài khráp", "ตั้งแต่เมื่อไหร่ครับ"),
 ("A", "Od wczoraj wieczorem.", "tâng tàe mûea khuen níi khráp", "ตั้งแต่เมื่อคืนนี้ครับ"),
 ("B", "Przepraszam, wyślę technika.", "khǎw-thôot khráp jà sòng châang pai", "ขอโทษครับ จะส่งช่างไป"),
 ("A", "Klimatyzacja też hałasuje.", "ae kâw sǐang dang dûai khráp", "แอร์ก็เสียงดังด้วยครับ"),
 ("B", "Sprawdzimy jedno i drugie.", "dǐao chék hâi tháng sǎwng yàang khráp", "เดี๋ยวเช็คให้ทั้งสองอย่างครับ"),
 ("A", "Czy można zmienić pokój?", "plìan hâwng dâai mǎi khráp", "เปลี่ยนห้องได้ไหมครับ"),
 ("B", "Sprawdzę wolne pokoje.", "khǎw chék hâwng wâang khráp", "ขอเช็คห้องว่างครับ"),
 ("A", "Byłbym wdzięczny.", "khàwp-khun mâak khráp", "ขอบคุณมากครับ"),
 ("B", "Zadzwonię do pokoju za chwilę.", "dǐao thoo khûen hâwng khráp", "เดี๋ยวโทรขึ้นห้องครับ"),
], "„sǐang dang” to głośny dźwięk. „châang” to fachowiec — od hydraulika po elektryka."),

("Późne wymeldowanie", "Hotel", "A2", "Gość", "Recepcja", [
 ("A", "Chciałbym wymeldować się później.", "phǒm yàak chék-áo cháa kwàa khráp", "ผมอยากเช็คเอาท์ช้ากว่าครับ"),
 ("B", "Do której godziny?", "thǔeng kìi moong khráp", "ถึงกี่โมงครับ"),
 ("A", "Do trzeciej po południu.", "thǔeng bàai sǎam khráp", "ถึงบ่ายสามครับ"),
 ("B", "Do drugiej bez dopłaty.", "thǔeng bàai sǎwng mâi mii khâa chái jàai khráp", "ถึงบ่ายสองไม่มีค่าใช้จ่ายครับ"),
 ("A", "A po drugiej ile?", "lǎng bàai sǎwng thâo-rài khráp", "หลังบ่ายสองเท่าไหร่ครับ"),
 ("B", "Trzysta batów.", "sǎam ráwi bàat khráp", "สามร้อยบาทครับ"),
 ("A", "To dla mnie za drogo.", "phaeng koen pai sǎm-ràp phǒm khráp", "แพงเกินไปสำหรับผมครับ"),
 ("B", "Może pan zostawić bagaż za darmo.", "fàak krà-pǎo wái frii dâai khráp", "ฝากกระเป๋าไว้ฟรีได้ครับ"),
 ("A", "Świetnie, tak zrobię.", "dii khráp ao yàang nán", "ดีครับ เอาอย่างนั้น"),
 ("B", "Wymeldowanie o dwunastej.", "chék-áo thîang khráp", "เช็คเอาท์เที่ยงครับ"),
 ("A", "Rozumiem, dziękuję.", "khâo-jai láew khráp khàwp-khun", "เข้าใจแล้วครับ ขอบคุณ"),
], "„khâa chái jàai” to opłata dodatkowa. „frii” — zapożyczenie z angielskiego, całkowicie naturalne."),

("Taksówka z taksometrem", "Transport", "A2", "Pasażer", "Kierowca", [
 ("A", "Dzień dobry, jedzie pan do centrum?", "sawàt-dii khráp pai nai mueang mǎi khráp", "สวัสดีครับ ไปในเมืองไหมครับ"),
 ("B", "Jadę. Trzysta batów.", "pai khráp sǎam ráwi bàat", "ไปครับ สามร้อยบาท"),
 ("A", "Proszę włączyć taksometr.", "chûai pòet mí-tôe dûai khráp", "ช่วยเปิดมิเตอร์ด้วยครับ"),
 ("B", "Teraz jest duży korek.", "tawn níi rót tìt mâak khráp", "ตอนนี้รถติดมากครับ"),
 ("A", "Bez taksometru nie jadę.", "mâi pòet mí-tôe phǒm mâi pai khráp", "ไม่เปิดมิเตอร์ผมไม่ไปครับ"),
 ("B", "Dobrze, włączam.", "dâai khráp pòet hâi", "ได้ครับ เปิดให้"),
 ("A", "Dziękuję. Czy jedziemy autostradą?", "khàwp-khun khráp khûen thaang dùan mǎi khráp", "ขอบคุณครับ ขึ้นทางด่วนไหมครับ"),
 ("B", "Autostradą jest szybciej.", "thaang dùan reo kwàa khráp", "ทางด่วนเร็วกว่าครับ"),
 ("A", "To jedźmy. Ja płacę za przejazd.", "ngán pai thaang dùan khráp phǒm jàai khâa thaang eeng", "งั้นไปทางด่วนครับ ผมจ่ายค่าทางเอง"),
 ("B", "Dobrze.", "dâai khráp", "ได้ครับ"),
 ("A", "Proszę zatrzymać się za rogiem.", "jàwt loei hǔa mum khráp", "จอดเลยหัวมุมครับ"),
 ("B", "Dobrze, tutaj.", "dâai khráp trong níi", "ได้ครับ ตรงนี้"),
], "Taksometr to „mí-tôe”. Bez niego kierowca poda cenę z sufitu — to najważniejszy zwrot podróżnika."),

("Pytanie o autobus", "Transport", "A2", "Pasażer", "Przechodzień", [
 ("A", "Przepraszam, czy ten autobus jedzie na dworzec?", "khǎw-thôot khráp rót khan níi pai sà-thǎa-nii mǎi khráp", "ขอโทษครับ รถคันนี้ไปสถานีไหมครับ"),
 ("B", "Nie, trzeba się przesiąść.", "mâi pai khráp tâwng plìan rót", "ไม่ไปครับ ต้องเปลี่ยนรถ"),
 ("A", "Gdzie mam wysiąść?", "phǒm khuan long thîi nǎi khráp", "ผมควรลงที่ไหนครับ"),
 ("B", "Na trzecim przystanku.", "long pâai thîi sǎam khráp", "ลงป้ายที่สามครับ"),
 ("A", "Ile przystanków jeszcze?", "ìik kìi pâai khráp", "อีกกี่ป้ายครับ"),
 ("B", "Jeszcze trzy.", "ìik sǎam pâai khráp", "อีกสามป้ายครับ"),
 ("A", "Proszę mi powiedzieć, gdzie wysiąść.", "chûai bàwk dûai wâa long thîi nǎi khráp", "ช่วยบอกด้วยว่าลงที่ไหนครับ"),
 ("B", "Powiem ci.", "dǐao bàwk khráp", "เดี๋ยวบอกครับ"),
 ("A", "Jak długo stąd na dworzec?", "pai sà-thǎa-nii chái wee-laa naan thâo-rài khráp", "ไปสถานีใช้เวลานานเท่าไหร่ครับ"),
 ("B", "Jakieś dwadzieścia minut.", "prà-maan yîi-sìp naa-thii khráp", "ประมาณยี่สิบนาทีครับ"),
 ("A", "Dziękuję bardzo.", "khàwp-khun mâak khráp", "ขอบคุณมากครับ"),
], "„khan” to słowo miarowe do pojazdów, „pâai” — do przystanków. Bez nich zdanie brzmi niepełnie."),

("Wynajem skutera na dzień", "Transport", "A2", "Turysta", "Wypożyczalnia", [
 ("A", "Chciałbym wynająć skuter na jeden dzień.", "phǒm khǎw châo maw-toe-sai nùeng wan khráp", "ผมขอเช่ามอเตอร์ไซค์หนึ่งวันครับ"),
 ("B", "Poproszę paszport.", "khǎw phaas-pàwt khráp", "ขอพาสปอร์ตครับ"),
 ("A", "Ile kosztuje na dzień?", "châo wan lá thâo-rài khráp", "เช่าวันละเท่าไหร่ครับ"),
 ("B", "Dwieście pięćdziesiąt batów.", "sǎwng ráwi hâa sìp bàat khráp", "สองร้อยห้าสิบบาทครับ"),
 ("A", "Czy kask jest w cenie?", "mùak kan náwk ruam mǎi khráp", "หมวกกันน็อกรวมไหมครับ"),
 ("B", "Tak, dwa kaski.", "ruam khráp sǎwng bai", "รวมครับ สองใบ"),
 ("A", "Ile kosztuje paliwo?", "khâa náam man thâo-rài khráp", "ค่าน้ำมันเท่าไหร่ครับ"),
 ("B", "Pełny bak sto batów.", "tem thǎng ráwi nùeng khráp", "เต็มถังร้อยหนึ่งครับ"),
 ("A", "Chcę spróbować poprowadzić.", "khǎw lawng khàp duu nòi khráp", "ขอลองขับดูหน่อยครับ"),
 ("B", "Proszę bardzo, ostrożnie.", "choen khráp khàp rá-wang ná", "เชิญครับ ขับระวังนะ"),
 ("A", "Gdzie mogę zaparkować wieczorem?", "tawn yen jàwt rót dâai thîi nǎi khráp", "ตอนเย็นจอดรถได้ที่ไหนครับ"),
 ("B", "Za budynkiem.", "dâan lǎng tùek khráp", "ด้านหลังตึกครับ"),
], "„châo” to wynająć od kogoś. „bai” liczy kaski, kartki i dokumenty."),

("Ustalanie terminu spotkania", "Czas i daty", "A2", "Znajomy", "Znajoma", [
 ("A", "Spotkajmy się w tym tygodniu.", "aa-thít níi jôe kan ná khráp", "อาทิตย์นี้เจอกันนะครับ"),
 ("B", "Który dzień ci pasuje?", "wan nǎi sà-dùak khráp", "วันไหนสะดวกครับ"),
 ("A", "W sobotę jestem wolny cały dzień.", "wan sǎo phǒm wâang tháng wan khráp", "วันเสาร์ผมว่างทั้งวันครับ"),
 ("B", "Ja mam rano pracę.", "tawn cháo phǒm mii ngaan khráp", "ตอนเช้าผมมีงานครับ"),
 ("A", "To może po południu?", "ngán tawn bàai dâai mǎi khráp", "งั้นตอนบ่ายได้ไหมครับ"),
 ("B", "Pasuje. O czwartej?", "dâai khráp sìi moong yen mǎi khráp", "ได้ครับ สี่โมงเย็นไหมครับ"),
 ("A", "Może być trochę później?", "cháa kwàa nít nòi dâai mǎi khráp", "ช้ากว่านิดหน่อยได้ไหมครับ"),
 ("B", "To o piątej.", "ngán hâa moong yen khráp", "งั้นห้าโมงเย็นครับ"),
 ("A", "Gdzie się spotkamy?", "jôe kan thîi nǎi dii khráp", "เจอกันที่ไหนดีครับ"),
 ("B", "Przed wejściem do centrum handlowego.", "nâa thaang khâo hâang khráp", "หน้าทางเข้าห้างครับ"),
 ("A", "Będę punktualnie.", "phǒm jà maa trong wee-laa khráp", "ผมจะมาตรงเวลาครับ"),
 ("B", "Potwierdzę wieczorem.", "dǐao yuen-yan tawn yen khráp", "เดี๋ยวยืนยันตอนเย็นครับ"),
], "„sà-dùak” znaczy „dogodny”. Pytanie „wan nǎi sà-dùak” brzmi uprzejmiej niż „kiedy możesz”."),

("Przekładanie spotkania", "Czas i daty", "A2", "Znajomy", "Znajoma", [
 ("A", "Przepraszam, muszę przełożyć spotkanie.", "khǎw-thôot khráp phǒm tâwng lûean nát", "ขอโทษครับ ผมต้องเลื่อนนัด"),
 ("B", "Coś się stało?", "koet à-rai khûen rǔe plào khráp", "เกิดอะไรขึ้นหรือเปล่าครับ"),
 ("A", "Mam dziś dużo pracy.", "wan níi ngaan yóe khráp", "วันนี้งานเยอะครับ"),
 ("B", "Rozumiem. Na kiedy?", "khâo-jai khráp lûean pen wan nǎi khráp", "เข้าใจครับ เลื่อนเป็นวันไหนครับ"),
 ("A", "Może w przyszłym tygodniu?", "aa-thít nâa dâai mǎi khráp", "อาทิตย์หน้าได้ไหมครับ"),
 ("B", "Pasuje mi.", "dâai khráp", "ได้ครับ"),
 ("A", "Bardzo mi przykro.", "khǎw-thôot jing jing khráp", "ขอโทษจริงๆ ครับ"),
 ("B", "Nie ma sprawy.", "mâi pen rai khráp", "ไม่เป็นไรครับ"),
 ("A", "Następnym razem ja stawiam.", "khráng nâa phǒm líang eeng khráp", "ครั้งหน้าผมเลี้ยงเองครับ"),
 ("B", "Umowa stoi.", "tòk long khráp", "ตกลงครับ"),
], "„lûean nát” to przełożyć umówione spotkanie; „yók-lôek” — odwołać całkiem."),

("Spóźnienie", "Czas i daty", "A2", "Spóźniony", "Czekający", [
 ("A", "Spóźnię się dziesięć minut.", "phǒm jà cháa sìp naa-thii khráp", "ผมจะช้าสิบนาทีครับ"),
 ("B", "Nie ma problemu, poczekam.", "mâi mii panhǎa khráp phǒm raw dâai", "ไม่มีปัญหาครับ ผมรอได้"),
 ("A", "Jest duży korek.", "rót tìt mâak khráp", "รถติดมากครับ"),
 ("B", "Gdzie teraz jesteś?", "tawn níi yùu thîi nǎi khráp", "ตอนนี้อยู่ที่ไหนครับ"),
 ("A", "Właśnie przejeżdżam przez most.", "kamlang khâam sà-phaan khráp", "กำลังข้ามสะพานครับ"),
 ("B", "To już blisko.", "ngán klâi láew khráp", "งั้นใกล้แล้วครับ"),
 ("A", "Przepraszam za spóźnienie.", "khǎw-thôot thîi maa cháa khráp", "ขอโทษที่มาช้าครับ"),
 ("B", "Nic się nie stało, siadaj.", "mâi pen rai khráp nâng loei", "ไม่เป็นไรครับ นั่งเลย"),
 ("A", "Dziękuję za cierpliwość.", "khàwp-khun thîi raw khráp", "ขอบคุณที่รอครับ"),
], "„kamlang … yùu” opisuje czynność w toku; tutaj skrócone do samego „kamlang”."),

("Pytanie o widok i pokój", "Hotel", "A2", "Gość", "Recepcja", [
 ("A", "Czy mogę zobaczyć pokój przed decyzją?", "khǎw duu hâwng kàwn dâai mǎi khráp", "ขอดูห้องก่อนได้ไหมครับ"),
 ("B", "Zapraszam, chodźmy.", "choen khráp pai duu kan", "เชิญครับ ไปดูกัน"),
 ("A", "Czy pokój ma balkon?", "hâwng mii rá-biang mǎi khráp", "ห้องมีระเบียงไหมครับ"),
 ("B", "Ma mały balkon.", "mii rá-biang lék khráp", "มีระเบียงเล็กครับ"),
 ("A", "Poproszę pokój z widokiem na morze.", "khǎw hâwng wiu thá-lee khráp", "ขอห้องวิวทะเลครับ"),
 ("B", "Dopłata pięćset batów.", "phôoem hâa ráwi bàat khráp", "เพิ่มห้าร้อยบาทครับ"),
 ("A", "Drożej, niż myślałem.", "phaeng kwàa thîi khít wái khráp", "แพงกว่าที่คิดไว้ครับ"),
 ("B", "Mamy też pokój na wyższym piętrze.", "mii hâwng chán sǔung dûai khráp", "มีห้องชั้นสูงด้วยครับ"),
 ("A", "Ten pokój mi nie odpowiada.", "hâwng níi mâi khâwi thùuk jai khráp", "ห้องนี้ไม่ค่อยถูกใจครับ"),
 ("B", "Pokażę inny.", "dǐao hâi duu hâwng ùen khráp", "เดี๋ยวให้ดูห้องอื่นครับ"),
 ("A", "Dziękuję za cierpliwość.", "khàwp-khun thîi jai yen khráp", "ขอบคุณที่ใจเย็นครับ"),
], "„thùuk jai” = przypaść do gustu. „mâi khâwi thùuk jai” to uprzejma odmowa bez krytyki."),

("Zamawianie do pokoju", "Hotel", "A2", "Gość", "Obsługa", [
 ("A", "Czy mogę zamówić coś do pokoju?", "sàng aa-hǎan khûen hâwng dâai mǎi khráp", "สั่งอาหารขึ้นห้องได้ไหมครับ"),
 ("B", "Można do dwudziestej drugiej.", "dâai thǔeng sǎwng thûm khráp", "ได้ถึงสองทุ่มครับ"),
 ("A", "Poproszę zupę i ryż.", "khǎw tôm yam kàp khâao khráp", "ขอต้มยำกับข้าวครับ"),
 ("B", "Ostre czy łagodne?", "phèt rǔe mâi phèt khráp", "เผ็ดหรือไม่เผ็ดครับ"),
 ("A", "Bardzo mało ostre.", "phèt nói mâak khráp", "เผ็ดน้อยมากครับ"),
 ("B", "Coś do picia?", "ráp khrûeang dùem mǎi khráp", "รับเครื่องดื่มไหมครับ"),
 ("A", "Poproszę jeszcze jedną wodę.", "khǎw náam ìik khùat khráp", "ขอน้ำอีกขวดครับ"),
 ("B", "Numer pokoju?", "hâwng boe à-rai khráp", "ห้องเบอร์อะไรครับ"),
 ("A", "Pokój czterysta dwa.", "hâwng sìi sǔun sǎwng khráp", "ห้องสี่ศูนย์สองครับ"),
 ("B", "Za dwadzieścia minut.", "ìik yîi-sìp naa-thii khráp", "อีกยี่สิบนาทีครับ"),
 ("A", "Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ"),
], "„khùat” liczy butelki. Przy zamówieniu do pokoju zawsze podaj „hâwng boe …”."),

("Pranie w hotelu", "Hotel", "A2", "Gość", "Obsługa", [
 ("A", "Poproszę o pranie.", "khǎw sák phâa khráp", "ขอซักผ้าครับ"),
 ("B", "Ile sztuk?", "kìi chín khráp", "กี่ชิ้นครับ"),
 ("A", "Pięć koszulek i dwie pary spodni.", "sûea hâa túa kàp kaang keeng sǎwng túa khráp", "เสื้อห้าตัวกับกางเกงสองตัวครับ"),
 ("B", "Ile wynosi opłata za pranie?", "khâa sák phâa khít yang-ngai khráp", "ค่าซักผ้าคิดยังไงครับ"),
 ("A", "Właśnie o to pytam.", "phǒm kâw yàak thǎam mǔean kan khráp", "ผมก็อยากถามเหมือนกันครับ"),
 ("B", "Czterdzieści batów za sztukę.", "chín lá sìi sìp bàat khráp", "ชิ้นละสี่สิบบาทครับ"),
 ("A", "Kiedy będzie gotowe?", "sèt mûea-rài khráp", "เสร็จเมื่อไหร่ครับ"),
 ("B", "Jutro rano.", "phrûng níi cháo khráp", "พรุ่งนี้เช้าครับ"),
 ("A", "Proszę nie prać tego osobno.", "chûai yàa sák yâek khráp", "ช่วยอย่าซักแยกครับ"),
 ("B", "Dobrze, zanotuję.", "dâai khráp jà jòt wái", "ได้ครับ จะจดไว้"),
], "„túa” liczy ubrania, „chín” — sztuki dowolnego rodzaju. Oba są tu poprawne."),

("Kupowanie biletu na pociąg", "Transport", "A2", "Podróżny", "Kasjer", [
 ("A", "Poproszę bilet do Ayutthayi.", "khǎw tǔa pai à-yút-thá-yaa khráp", "ขอตั๋วไปอยุธยาครับ"),
 ("B", "W jedną stronę czy powrotny?", "thîao diao rǔe pai klàp khráp", "เที่ยวเดียวหรือไปกลับครับ"),
 ("A", "Poproszę bilet powrotny.", "khǎw tǔa pai klàp khráp", "ขอตั๋วไปกลับครับ"),
 ("B", "Na kiedy powrót?", "klàp wan nǎi khráp", "กลับวันไหนครับ"),
 ("A", "W niedzielę wieczorem.", "wan aa-thít tawn yen khráp", "วันอาทิตย์ตอนเย็นครับ"),
 ("B", "Osiemset batów razem.", "tháng mòt pàet ráwi bàat khráp", "ทั้งหมดแปดร้อยบาทครับ"),
 ("A", "O której odjeżdża?", "àwk kìi moong khráp", "ออกกี่โมงครับ"),
 ("B", "Za czterdzieści minut.", "ìik sìi sìp naa-thii khráp", "อีกสี่สิบนาทีครับ"),
 ("A", "Który peron?", "chaan chaa-laa nǎi khráp", "ชานชาลาไหนครับ"),
 ("B", "Peron drugi.", "chaan chaa-laa thîi sǎwng khráp", "ชานชาลาที่สองครับ"),
 ("A", "Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ"),
], "„thîao diao” to jeden kurs, „pai klàp” — tam i z powrotem."),

("Zgubiona torba w taksówce", "Awarie i pomoc", "A2", "Turysta", "Recepcja", [
 ("A", "Mam problem. Zostawiłem torbę w taksówce.", "phǒm mii panhǎa khráp luem krà-pǎo wái nai tháek-sîi", "ผมมีปัญหาครับ ลืมกระเป๋าไว้ในแท็กซี่"),
 ("B", "Ma pan paragon z taksówki?", "mii bai sèt tháek-sîi mǎi khráp", "มีใบเสร็จแท็กซี่ไหมครับ"),
 ("A", "Tak, mam.", "mii khráp", "มีครับ"),
 ("B", "To dobrze, zadzwonimy.", "dii khráp dǐao thoo hǎa hâi", "ดีครับ เดี๋ยวโทรหาให้"),
 ("A", "Co było w środku?", "nai krà-pǎo mii à-rai bâang khráp", "ในกระเป๋ามีอะไรบ้างครับ"),
 ("B", "Paszport i ładowarka.", "phaas-pàwt kàp thîi chaat khráp", "พาสปอร์ตกับที่ชาร์จครับ"),
 ("A", "To pilne.", "rûeang dùan khráp", "เรื่องด่วนครับ"),
 ("B", "Rozumiem, dzwonię teraz.", "khâo-jai khráp thoo loei", "เข้าใจครับ โทรเลย"),
 ("A", "Czy powinienem iść na policję?", "phǒm khuan pai jâeng khwaam mǎi khráp", "ผมควรไปแจ้งความไหมครับ"),
 ("B", "Najpierw poczekajmy na odpowiedź.", "raw kham tàwp kàwn khráp", "รอคำตอบก่อนครับ"),
 ("A", "Dobrze, dziękuję za pomoc.", "dâai khráp khàwp-khun thîi chûai", "ได้ครับ ขอบคุณที่ช่วย"),
], "Uwaga: role są tu odwrócone w kwestii o zawartości — recepcjonista pyta, gość odpowiada. „jâeng khwaam” to zgłoszenie na policji."),

("Zmiana zamówienia", "Restauracja", "A2", "Gość", "Kelner", [
 ("A", "Przepraszam, czy mogę zmienić zamówienie?", "khǎw-thôot khráp khǎw plìan raai-kaan dâai mǎi", "ขอโทษครับ ขอเปลี่ยนรายการได้ไหม"),
 ("B", "Jeszcze nie zaczęliśmy gotować.", "yang mâi dâi tham khráp", "ยังไม่ได้ทำครับ"),
 ("A", "To dobrze. Anuluję jedno danie.", "dii khráp khǎw yók-lôek nùeng yàang", "ดีครับ ขอยกเลิกหนึ่งอย่าง"),
 ("B", "Które danie?", "yàang nǎi khráp", "อย่างไหนครับ"),
 ("A", "Zupę. Zamiast tego poproszę sałatkę.", "tôm yam khráp khǎw sà-làt thaen", "ต้มยำครับ ขอสลัดแทน"),
 ("B", "Dobrze. Coś jeszcze?", "dâai khráp ráp à-rai ìik mǎi", "ได้ครับ รับอะไรอีกไหม"),
 ("A", "Poproszę o wszystko naraz.", "khǎw sèt phráwm kan khráp", "ขอเสร็จพร้อมกันครับ"),
 ("B", "Podamy razem.", "sèet phráwm kan khráp", "เสิร์ฟพร้อมกันครับ"),
 ("A", "Dziękuję za wyrozumiałość.", "khàwp-khun mâak khráp", "ขอบคุณมากครับ"),
], "„thaen” znaczy „zamiast”. „phráwm kan” — jednocześnie, razem."),

("Pytanie o drogę pieszo", "Miejsca i orientacja", "A2", "Turysta", "Przechodzień", [
 ("A", "Przepraszam, zgubiłem się.", "khǎw-thôot khráp phǒm lǒng thaang", "ขอโทษครับ ผมหลงทาง"),
 ("B", "Dokąd chcesz dojść?", "jà pai nǎi khráp", "จะไปไหนครับ"),
 ("A", "Nie mogę znaleźć mojego hotelu.", "phǒm hǎa roong-raem mâi jôe khráp", "ผมหาโรงแรมไม่เจอครับ"),
 ("B", "Jak się nazywa?", "chûe à-rai khráp", "ชื่ออะไรครับ"),
 ("A", "Baan Rim Nam. Mam mapę.", "baan rim náam khráp phǒm mii phǎen thîi", "บ้านริมน้ำครับ ผมมีแผนที่"),
 ("B", "Aha, znam. Idź prosto.", "âw rúu-jàk khráp trong pai", "อ๋อ รู้จักครับ ตรงไป"),
 ("A", "A potem?", "láew ngai tàw khráp", "แล้วไงต่อครับ"),
 ("B", "Na skrzyżowaniu skręć w lewo.", "thǔeng sìi yâek líao sáai khráp", "ถึงสี่แยกเลี้ยวซ้ายครับ"),
 ("A", "Jak długo stąd do hotelu?", "pai roong-raem chái wee-laa naan thâo-rài khráp", "ไปโรงแรมใช้เวลานานเท่าไหร่ครับ"),
 ("B", "Pieszo jakieś dziesięć minut.", "doen prà-maan sìp naa-thii khráp", "เดินประมาณสิบนาทีครับ"),
 ("A", "Proszę mówić wolniej.", "chûai phûut cháa cháa nòi khráp", "ช่วยพูดช้าๆ หน่อยครับ"),
 ("B", "Prosto, potem w lewo.", "trong pai láew líao sáai khráp", "ตรงไป แล้วเลี้ยวซ้ายครับ"),
], "„sìi yâek” to skrzyżowanie czterech dróg. „lǒng thaang” — zgubić drogę."),
]
