# -*- coding: utf-8 -*-
"""Wzorce zdaniowe etapu 5 (B2) — czesc E: konstrukcje rzeczownikowe, druga seria.

Zakres: braki i niedobory, przygotowanie na spotkanie, zwiazek przyczynowy,
weryfikacja przed decyzja, waga sprawy, zakres ubezpieczenia i gwarancji,
wzrost kosztow, przekazanie sprawy dalej.

Pozycja: (polskie haslo rekordu, polskie haslo bazowe, polski przyklad)
"""

TPL_E = [

# =====================================================================
# tawn nii raw yang khaat … yuu — brak, niedobor
# =====================================================================
dict(key="KHAATYUU", ty="sentence", cat="Praca i nauka", sub="Braki", reg="n",
     ph="tawn níi raw yang khàat {ph} yùu khráp", th="ตอนนี้เรายังขาด{th}อยู่ครับ",
     lit="khàat = brakować, być niekompletnym",
     note="„khàat” mówi o brakującym elemencie kompletu, „mâi mii” o całkowitym braku. Przy dokumentach urzędnik użyje właśnie „khàat”.",
     ex_ph="raw khàat {ph} yùu ìik thâo rài khráp", ex_th="เราขาด{th}อยู่อีกเท่าไหร่ครับ",
     items=[
       ("Wciąż brakuje nam dokumentów.", "dokument", "Ilu dokumentów jeszcze brakuje?"),
       ("Wciąż brakuje nam podpisu.", "podpis", "Ilu podpisów jeszcze brakuje?"),
       ("Wciąż brakuje nam umowy.", "umowa", "Czego brakuje w umowie?"),
       ("Wciąż brakuje nam paragonu.", "paragon", "Ilu paragonów jeszcze brakuje?"),
       ("Wciąż brakuje nam pieniędzy.", "pieniądze", "Ile pieniędzy jeszcze brakuje?"),
       ("Wciąż brakuje nam gotówki.", "gotówka", "Ile gotówki jeszcze brakuje?"),
       ("Wciąż brakuje nam reszty.", "reszta", "Ile reszty jeszcze brakuje?"),
       ("Wciąż brakuje nam ubezpieczenia.", "ubezpieczenie", "Czego brakuje w ubezpieczeniu?"),
       ("Wciąż brakuje nam wyniku badania.", "wynik badania", "Ilu wyników jeszcze brakuje?"),
       ("Wciąż brakuje nam leków.", "lek", "Ilu leków jeszcze brakuje?"),
       ("Wciąż brakuje nam ludzi do pracy.", "praca", "Ilu ludzi jeszcze brakuje?"),
       ("Wciąż brakuje nam klientów.", "klient", "Ilu klientów jeszcze brakuje?"),
       ("Wciąż brakuje nam zasięgu.", "zasięg", "Gdzie tu w ogóle jest zasięg?"),
       ("Wciąż brakuje nam internetu.", "internet", "Kiedy będzie internet?"),
       ("Wciąż brakuje nam hasła do sieci.", "hasło", "Gdzie znajdę hasło?"),
       ("Wciąż brakuje nam ładowarki.", "ładowarka", "Czy ktoś ma ładowarkę?"),
       ("Wciąż brakuje nam ręczników.", "ręcznik", "Ilu ręczników jeszcze brakuje?"),
       ("Wciąż brakuje nam pościeli.", "pościel", "Ilu kompletów pościeli brakuje?"),
       ("Wciąż brakuje nam kluczy.", "klucz", "Ilu kluczy jeszcze brakuje?"),
       ("Wciąż brakuje nam mebli.", "mebel", "Ilu mebli jeszcze brakuje?"),
       ("Wciąż brakuje nam krzeseł.", "krzesło", "Ilu krzeseł jeszcze brakuje?"),
       ("Wciąż brakuje nam wody.", "woda", "Ile wody jeszcze brakuje?"),
       ("Wciąż brakuje nam ryżu.", "ryż", "Ile ryżu jeszcze brakuje?"),
       ("Wciąż brakuje nam warzyw.", "warzywa", "Ile warzyw jeszcze brakuje?"),
       ("Wciąż brakuje nam jedzenia dla wszystkich.", "jedzenie", "Ile jedzenia jeszcze brakuje?"),
       ("Wciąż brakuje nam czasu.", "praca", "Ile czasu jeszcze brakuje na tę pracę?"),
       ("Wciąż brakuje nam biletów.", "bilet", "Ilu biletów jeszcze brakuje?"),
       ("Wciąż brakuje nam paliwa.", "benzyna", "Ile paliwa jeszcze brakuje?"),
       ("Wciąż brakuje nam kasków.", "kask", "Ilu kasków jeszcze brakuje?"),
       ("Wciąż brakuje nam kierowcy.", "kierowca", "Kiedy będzie kierowca?"),
       ("Wciąż brakuje nam przewodnika.", "przewodnik (osoba)", "Kiedy będzie przewodnik?"),
       ("Wciąż brakuje nam mapy okolicy.", "mapa", "Gdzie dostanę mapę?"),
       ("Wciąż brakuje nam wizytówek.", "wizytówka", "Ilu wizytówek jeszcze brakuje?"),
       ("Wciąż brakuje nam numeru telefonu do nich.", "numer telefonu", "Gdzie znajdę ich numer?"),
       ("Wciąż brakuje nam informacji o projekcie.", "projekt", "Czego brakuje w projekcie?"),
       ("Wciąż brakuje nam zgody właściciela.", "właściciel", "Kiedy będzie zgoda właściciela?"),
     ]),

# =====================================================================
# chuai triam … maa duai — przygotowanie
# =====================================================================
dict(key="TRIAMMAA", ty="sentence", cat="Praca i nauka", sub="Przygotowanie", reg="f",
     ph="chûai triam {ph} maa dûai ná khráp", th="ช่วยเตรียม{th}มาด้วยนะครับ",
     lit="triam … maa = przygotować i przynieść ze sobą",
     note="„maa” dodaje kierunek: masz to ze sobą przynieść, nie tylko przygotować w domu. Ta różnica bywa kluczowa w urzędzie.",
     ex_ph="tâwng triam {ph} maa dûai mǎi khráp", ex_th="ต้องเตรียม{th}มาด้วยไหมครับ",
     items=[
       ("Proszę przygotować i przynieść dokumenty.", "dokument", "Czy trzeba przynieść dokumenty?"),
       ("Proszę przygotować i przynieść paszport.", "paszport", "Czy trzeba przynieść paszport?"),
       ("Proszę przygotować i przynieść wizę.", "wiza", "Czy trzeba przynieść wizę?"),
       ("Proszę przygotować i przynieść umowę.", "umowa", "Czy trzeba przynieść umowę?"),
       ("Proszę przygotować i przynieść umowę najmu.", "umowa najmu", "Czy trzeba przynieść umowę najmu?"),
       ("Proszę przygotować i przynieść paragon.", "paragon", "Czy trzeba przynieść paragon?"),
       ("Proszę przygotować i przynieść gotówkę.", "gotówka", "Czy trzeba przynieść gotówkę?"),
       ("Proszę przygotować i przynieść kartę kredytową.", "karta kredytowa", "Czy trzeba przynieść kartę?"),
       ("Proszę przygotować i przynieść ubezpieczenie.", "ubezpieczenie", "Czy trzeba przynieść ubezpieczenie?"),
       ("Proszę przygotować i przynieść wyniki badań.", "wynik badania", "Czy trzeba przynieść wyniki?"),
       ("Proszę przygotować i przynieść leki.", "lek", "Czy trzeba przynieść leki?"),
       ("Proszę przygotować i przynieść prawo jazdy.", "prawo jazdy", "Czy trzeba przynieść prawo jazdy?"),
       ("Proszę przygotować i przynieść bilet.", "bilet", "Czy trzeba przynieść bilet?"),
       ("Proszę przygotować i przynieść wizytówkę.", "wizytówka", "Czy trzeba przynieść wizytówkę?"),
       ("Proszę przygotować i przynieść telefon.", "telefon", "Czy trzeba przynieść telefon?"),
       ("Proszę przygotować i przynieść ładowarkę.", "ładowarka", "Czy trzeba przynieść ładowarkę?"),
       ("Proszę przygotować i przynieść powerbank.", "powerbank", "Czy trzeba przynieść powerbank?"),
       ("Proszę przygotować i przynieść przejściówkę.", "przejściówka", "Czy trzeba przynieść przejściówkę?"),
       ("Proszę przygotować i przynieść mapę.", "mapa", "Czy trzeba przynieść mapę?"),
       ("Proszę przygotować i przynieść kask.", "kask", "Czy trzeba przynieść kask?"),
       ("Proszę przygotować i przynieść walizkę.", "walizka", "Czy trzeba przynieść walizkę?"),
       ("Proszę przygotować i przynieść plecak.", "plecak", "Czy trzeba przynieść plecak?"),
       ("Proszę przygotować i przynieść torbę.", "torba", "Czy trzeba przynieść torbę?"),
       ("Proszę przygotować i przynieść parasol na słońce i krem.", "krem z filtrem", "Czy trzeba przynieść krem?"),
       ("Proszę przygotować i przynieść wodę.", "woda", "Czy trzeba przynieść wodę?"),
       ("Proszę przygotować i przynieść jedzenie.", "jedzenie", "Czy trzeba przynieść jedzenie?"),
       ("Proszę przygotować i przynieść ręcznik.", "ręcznik", "Czy trzeba przynieść ręcznik?"),
       ("Proszę przygotować i przynieść klucz.", "klucz", "Czy trzeba przynieść klucz?"),
       ("Proszę przygotować i przynieść kaucję.", "kaucja", "Czy trzeba przynieść kaucję?"),
       ("Proszę przygotować i przynieść zdjęcie do dokumentów.", "podpis", "Czy trzeba mieć własny podpis na kopiach?"),
       ("Proszę przygotować i przynieść dane konta.", "konto", "Czy trzeba przynieść dane konta?"),
       ("Proszę przygotować i przynieść potwierdzenie przelewu.", "przelew", "Czy trzeba przynieść potwierdzenie?"),
       ("Proszę przygotować i przynieść kod QR do płatności.", "kod QR", "Czy trzeba mieć kod QR?"),
       ("Proszę przygotować i przynieść dokumenty firmy.", "firma", "Czy trzeba przynieść dokumenty firmy?"),
       ("Proszę przygotować i przynieść materiały na zebranie.", "zebranie", "Czy trzeba przynieść materiały?"),
       ("Proszę przygotować i przynieść opis projektu.", "projekt", "Czy trzeba przynieść opis projektu?"),
     ]),

# =====================================================================
# … kiao khawng kap rueang nii doi trong — zwiazek przyczynowy
# =====================================================================
dict(key="KIAOKHAWNG", ty="sentence", cat="Praca i nauka", sub="Argumentacja", reg="f",
     ph="{ph} kìao khâwng kàp rûeang níi doi trong khráp", th="{th}เกี่ยวข้องกับเรื่องนี้โดยตรงครับ",
     lit="kìao khâwng doi trong = związany bezpośrednio",
     note="Zwrot z języka raportów i pism urzędowych. Wskazuje, że coś jest istotne dla sprawy, a nie tylko z nią sąsiaduje.",
     ex_ph="{ph} kìao khâwng kàp rûeang níi yang-ngai khráp", ex_th="{th}เกี่ยวข้องกับเรื่องนี้ยังไงครับ",
     items=[
       ("Umowa ma z tym bezpośredni związek.", "umowa", "Jaki związek ma z tym umowa?"),
       ("Kaucja ma z tym bezpośredni związek.", "kaucja", "Jaki związek ma z tym kaucja?"),
       ("Cena ma z tym bezpośredni związek.", "cena", "Jaki związek ma z tym cena?"),
       ("Opłata ma z tym bezpośredni związek.", "opłata", "Jaki związek ma z tym opłata?"),
       ("Przelew ma z tym bezpośredni związek.", "przelew", "Jaki związek ma z tym przelew?"),
       ("Konto ma z tym bezpośredni związek.", "konto", "Jaki związek ma z tym konto?"),
       ("Ubezpieczenie ma z tym bezpośredni związek.", "ubezpieczenie", "Jaki związek ma z tym ubezpieczenie?"),
       ("Wiza ma z tym bezpośredni związek.", "wiza", "Jaki związek ma z tym wiza?"),
       ("Paszport ma z tym bezpośredni związek.", "paszport", "Jaki związek ma z tym paszport?"),
       ("Prawo jazdy ma z tym bezpośredni związek.", "prawo jazdy", "Jaki związek ma z tym prawo jazdy?"),
       ("Ten dokument ma z tym bezpośredni związek.", "dokument", "Jaki związek ma z tym ten dokument?"),
       ("Podpis ma z tym bezpośredni związek.", "podpis", "Jaki związek ma z tym podpis?"),
       ("Klient ma z tym bezpośredni związek.", "klient", "Jaki związek ma z tym klient?"),
       ("Projekt ma z tym bezpośredni związek.", "projekt", "Jaki związek ma z tym projekt?"),
       ("Firma ma z tym bezpośredni związek.", "firma", "Jaki związek ma z tym firma?"),
       ("Zebranie ma z tym bezpośredni związek.", "zebranie", "Jaki związek ma z tym zebranie?"),
       ("Pensja ma z tym bezpośredni związek.", "pensja", "Jaki związek ma z tym pensja?"),
       ("Nadgodziny mają z tym bezpośredni związek.", "nadgodziny", "Jaki związek mają z tym nadgodziny?"),
       ("Urlop ma z tym bezpośredni związek.", "urlop", "Jaki związek ma z tym urlop?"),
       ("Czynsz ma z tym bezpośredni związek.", "czynsz", "Jaki związek ma z tym czynsz?"),
       ("Właściciel ma z tym bezpośredni związek.", "właściciel", "Jaki związek ma z tym właściciel?"),
       ("Sąsiad z góry ma z tym bezpośredni związek.", "sąsiad z góry", "Jaki związek ma z tym sąsiad?"),
       ("Ochroniarz ma z tym bezpośredni związek.", "ochroniarz", "Jaki związek ma z tym ochroniarz?"),
       ("Korki mają z tym bezpośredni związek.", "korek uliczny", "Jaki związek mają z tym korki?"),
       ("Opóźnienie ma z tym bezpośredni związek.", "opóźnienie", "Jaki związek ma z tym opóźnienie?"),
       ("Kierowca ma z tym bezpośredni związek.", "kierowca", "Jaki związek ma z tym kierowca?"),
       ("Rozkład jazdy ma z tym bezpośredni związek.", "rozkład jazdy", "Jaki związek ma z tym rozkład?"),
       ("Alergia ma z tym bezpośredni związek.", "alergia", "Jaki związek ma z tym alergia?"),
       ("Wynik badania ma z tym bezpośredni związek.", "wynik badania", "Jaki związek ma z tym wynik?"),
       ("Lek ma z tym bezpośredni związek.", "lek", "Jaki związek ma z tym lek?"),
       ("Lekarz ma z tym bezpośredni związek.", "lekarz", "Jaki związek ma z tym lekarz?"),
       ("Szkoła ma z tym bezpośredni związek.", "szkoła", "Jaki związek ma z tym szkoła?"),
       ("Internet ma z tym bezpośredni związek.", "internet", "Jaki związek ma z tym internet?"),
       ("Aplikacja ma z tym bezpośredni związek.", "aplikacja", "Jaki związek ma z tym aplikacja?"),
       ("Zasięg ma z tym bezpośredni związek.", "zasięg", "Jaki związek ma z tym zasięg?"),
       ("Ten problem ma z tym bezpośredni związek.", "problem", "Jaki związek ma z tym ten problem?"),
     ]),

# =====================================================================
# khaw truat sawp … kawn — weryfikacja przed decyzja
# =====================================================================
dict(key="TRUATSAWP", ty="sentence", cat="Praca i nauka", sub="Weryfikacja", reg="f",
     ph="khǎw trùat sàwp {ph} kàwn dâai mǎi khráp", th="ขอตรวจสอบ{th}ก่อนได้ไหมครับ",
     lit="trùat sàwp = sprawdzić, zweryfikować urzędowo",
     note="„trùat sàwp” to sprawdzenie formalne, mocniejsze niż potoczne „chék”. W banku i urzędzie użyj tego słowa.",
     ex_ph="trùat sàwp {ph} chái wee-laa naan mǎi khráp", ex_th="ตรวจสอบ{th}ใช้เวลานานไหมครับ",
     items=[
       ("Czy mogę najpierw sprawdzić umowę?", "umowa", "Czy sprawdzanie umowy długo trwa?"),
       ("Czy mogę najpierw sprawdzić rachunek?", "rachunek", "Czy sprawdzanie rachunku długo trwa?"),
       ("Czy mogę najpierw sprawdzić cenę?", "cena", "Czy sprawdzanie ceny długo trwa?"),
       ("Czy mogę najpierw sprawdzić opłatę?", "opłata", "Czy sprawdzanie opłaty długo trwa?"),
       ("Czy mogę najpierw sprawdzić przelew?", "przelew", "Czy sprawdzanie przelewu długo trwa?"),
       ("Czy mogę najpierw sprawdzić konto?", "konto", "Czy sprawdzanie konta długo trwa?"),
       ("Czy mogę najpierw sprawdzić dokumenty?", "dokument", "Czy sprawdzanie dokumentów długo trwa?"),
       ("Czy mogę najpierw sprawdzić paszport?", "paszport", "Czy sprawdzanie paszportu długo trwa?"),
       ("Czy mogę najpierw sprawdzić wizę?", "wiza", "Czy sprawdzanie wizy długo trwa?"),
       ("Czy mogę najpierw sprawdzić ubezpieczenie?", "ubezpieczenie", "Czy sprawdzanie ubezpieczenia długo trwa?"),
       ("Czy mogę najpierw sprawdzić wynik badania?", "wynik badania", "Czy sprawdzanie wyniku długo trwa?"),
       ("Czy mogę najpierw sprawdzić pokój?", "pokój", "Czy oględziny pokoju długo trwają?"),
       ("Czy mogę najpierw sprawdzić klimatyzację?", "klimatyzacja", "Czy sprawdzanie klimatyzacji długo trwa?"),
       ("Czy mogę najpierw sprawdzić lodówkę?", "lodówka", "Czy sprawdzanie lodówki długo trwa?"),
       ("Czy mogę najpierw sprawdzić pralkę?", "pralka", "Czy sprawdzanie pralki długo trwa?"),
       ("Czy mogę najpierw sprawdzić router?", "router", "Czy sprawdzanie routera długo trwa?"),
       ("Czy mogę najpierw sprawdzić internet?", "internet", "Czy sprawdzanie internetu długo trwa?"),
       ("Czy mogę najpierw sprawdzić gniazdka?", "gniazdko", "Czy sprawdzanie gniazdek długo trwa?"),
       ("Czy mogę najpierw sprawdzić okna?", "okno", "Czy sprawdzanie okien długo trwa?"),
       ("Czy mogę najpierw sprawdzić drzwi?", "drzwi", "Czy sprawdzanie drzwi długo trwa?"),
       ("Czy mogę najpierw sprawdzić zamek w drzwiach?", "klucz do mieszkania", "Czy sprawdzanie zamka długo trwa?"),
       ("Czy mogę najpierw sprawdzić samochód?", "samochód", "Czy sprawdzanie samochodu długo trwa?"),
       ("Czy mogę najpierw sprawdzić motocykl?", "motocykl", "Czy sprawdzanie motocykla długo trwa?"),
       ("Czy mogę najpierw sprawdzić kask?", "kask", "Czy sprawdzanie kasku długo trwa?"),
       ("Czy mogę najpierw sprawdzić bilet?", "bilet", "Czy sprawdzanie biletu długo trwa?"),
       ("Czy mogę najpierw sprawdzić rozkład jazdy?", "rozkład jazdy", "Czy sprawdzanie rozkładu długo trwa?"),
       ("Czy mogę najpierw sprawdzić bagaż?", "walizka", "Czy sprawdzanie bagażu długo trwa?"),
       ("Czy mogę najpierw sprawdzić towar?", "rozmiar", "Czy sprawdzanie rozmiaru długo trwa?"),
       ("Czy mogę najpierw sprawdzić kolor?", "kolor", "Czy dobieranie koloru długo trwa?"),
       ("Czy mogę najpierw sprawdzić kurs wymiany?", "kurs wymiany", "Czy sprawdzanie kursu długo trwa?"),
       ("Czy mogę najpierw sprawdzić menu?", "menu", "Czy przejrzenie menu długo trwa?"),
       ("Czy mogę najpierw sprawdzić stolik?", "stolik", "Czy przygotowanie stolika długo trwa?"),
       ("Czy mogę najpierw sprawdzić aplikację?", "aplikacja", "Czy sprawdzanie aplikacji długo trwa?"),
       ("Czy mogę najpierw sprawdzić hasło?", "hasło", "Czy resetowanie hasła długo trwa?"),
       ("Czy mogę najpierw sprawdzić dane firmy?", "firma", "Czy weryfikacja firmy długo trwa?"),
       ("Czy mogę najpierw sprawdzić zgłoszony problem?", "problem", "Czy diagnoza problemu długo trwa?"),
     ]),

# =====================================================================
# … khrang nii sam-khan pen phi-seet — waga sprawy
# =====================================================================
dict(key="PHISEET", ty="sentence", cat="Praca i nauka", sub="Priorytety", reg="f",
     ph="{ph} khráng níi sǎm-khan pen phí-sèet khráp", th="{th}ครั้งนี้สำคัญเป็นพิเศษครับ",
     lit="pen phí-sèet = w sposób szczególny",
     note="„pen phí-sèet” podnosi wagę bez podnoszenia głosu. Bardzo przydatne przy delegowaniu zadań.",
     ex_ph="thammai {ph} khráng níi thǔeng sǎm-khan pen phí-sèet khráp", ex_th="ทำไม{th}ครั้งนี้ถึงสำคัญเป็นพิเศษครับ",
     items=[
       ("Tym razem zebranie jest szczególnie ważne.", "zebranie", "Dlaczego to zebranie jest szczególnie ważne?"),
       ("Tym razem projekt jest szczególnie ważny.", "projekt", "Dlaczego ten projekt jest szczególnie ważny?"),
       ("Tym razem klient jest szczególnie ważny.", "klient", "Dlaczego ten klient jest szczególnie ważny?"),
       ("Tym razem umowa jest szczególnie ważna.", "umowa", "Dlaczego ta umowa jest szczególnie ważna?"),
       ("Tym razem dokument jest szczególnie ważny.", "dokument", "Dlaczego ten dokument jest szczególnie ważny?"),
       ("Tym razem podpis jest szczególnie ważny.", "podpis", "Dlaczego ten podpis jest szczególnie ważny?"),
       ("Tym razem współpraca jest szczególnie ważna.", "współpraca", "Dlaczego ta współpraca jest ważna?"),
       ("Tym razem badanie jest szczególnie ważne.", "badanie", "Dlaczego to badanie jest szczególnie ważne?"),
       ("Tym razem wynik badania jest szczególnie ważny.", "wynik badania", "Dlaczego ten wynik jest ważny?"),
       ("Tym razem wizyta u lekarza jest szczególnie ważna.", "lekarz", "Dlaczego ta wizyta jest ważna?"),
       ("Tym razem ubezpieczenie jest szczególnie ważne.", "ubezpieczenie", "Dlaczego to ubezpieczenie jest ważne?"),
       ("Tym razem wiza jest szczególnie ważna.", "wiza", "Dlaczego ta wiza jest szczególnie ważna?"),
       ("Tym razem paszport jest szczególnie ważny.", "paszport", "Dlaczego ten paszport jest ważny?"),
       ("Tym razem przelew jest szczególnie ważny.", "przelew", "Dlaczego ten przelew jest ważny?"),
       ("Tym razem kaucja jest szczególnie ważna.", "kaucja", "Dlaczego ta kaucja jest ważna?"),
       ("Tym razem cena jest szczególnie ważna.", "cena", "Dlaczego ta cena jest ważna?"),
       ("Tym razem rachunek jest szczególnie ważny.", "rachunek", "Dlaczego ten rachunek jest ważny?"),
       ("Tym razem paragon jest szczególnie ważny.", "paragon", "Dlaczego ten paragon jest ważny?"),
       ("Tym razem umowa najmu jest szczególnie ważna.", "umowa najmu", "Dlaczego ta umowa najmu jest ważna?"),
       ("Tym razem termin jest szczególnie ważny.", "rozkład jazdy", "Dlaczego ten rozkład jest ważny?"),
       ("Tym razem bilet jest szczególnie ważny.", "bilet", "Dlaczego ten bilet jest ważny?"),
       ("Tym razem bagaż jest szczególnie ważny.", "walizka", "Dlaczego ten bagaż jest ważny?"),
       ("Tym razem wycieczka jest szczególnie ważna.", "wycieczka", "Dlaczego ta wycieczka jest ważna?"),
       ("Tym razem szkoła jest szczególnie ważna.", "szkoła", "Dlaczego ta szkoła jest ważna?"),
       ("Tym razem praca jest szczególnie ważna.", "praca", "Dlaczego ta praca jest ważna?"),
       ("Tym razem pensja jest szczególnie ważna.", "pensja", "Dlaczego ta pensja jest ważna?"),
       ("Tym razem urlop jest szczególnie ważny.", "urlop", "Dlaczego ten urlop jest ważny?"),
       ("Tym razem firma jest szczególnie ważna.", "firma", "Dlaczego ta firma jest ważna?"),
       ("Tym razem konto jest szczególnie ważne.", "konto", "Dlaczego to konto jest ważne?"),
       ("Tym razem hasło jest szczególnie ważne.", "hasło", "Dlaczego to hasło jest ważne?"),
       ("Tym razem aplikacja jest szczególnie ważna.", "aplikacja", "Dlaczego ta aplikacja jest ważna?"),
       ("Tym razem wizytówka jest szczególnie ważna.", "wizytówka", "Dlaczego ta wizytówka jest ważna?"),
       ("Tym razem numer telefonu jest szczególnie ważny.", "numer telefonu", "Dlaczego ten numer jest ważny?"),
       ("Tym razem pokój jest szczególnie ważny.", "pokój", "Dlaczego ten pokój jest ważny?"),
       ("Tym razem ten problem jest szczególnie ważny.", "problem", "Dlaczego ten problem jest ważny?"),
       ("Tym razem opóźnienie jest szczególnie ważne.", "opóźnienie", "Dlaczego to opóźnienie jest ważne?"),
     ]),

# =====================================================================
# pra-kan mai khrawp khlum … — zakres ubezpieczenia
# =====================================================================
dict(key="KHRAWPKHLUM", ty="sentence", cat="Zakupy i pieniądze", sub="Ubezpieczenie", reg="f",
     ph="prà-kan mâi khrâwp khlum {ph} khráp", th="ประกันไม่ครอบคลุม{th}ครับ",
     lit="khrâwp khlum = obejmować, pokrywać zakresem",
     note="Zdanie, które usłyszysz w klinice i przy reklamacji. Warto znać je biernie, zanim usłyszy się je w kryzysie.",
     ex_ph="prà-kan khrâwp khlum {ph} dûai mǎi khráp", ex_th="ประกันครอบคลุม{th}ด้วยไหมครับ",
     items=[
       ("Ubezpieczenie nie obejmuje leków.", "lek", "Czy ubezpieczenie obejmuje też leki?"),
       ("Ubezpieczenie nie obejmuje antybiotyku.", "antybiotyk", "Czy ubezpieczenie obejmuje antybiotyk?"),
       ("Ubezpieczenie nie obejmuje badania.", "badanie", "Czy ubezpieczenie obejmuje badanie?"),
       ("Ubezpieczenie nie obejmuje dentysty.", "dentysta", "Czy ubezpieczenie obejmuje dentystę?"),
       ("Ubezpieczenie nie obejmuje kliniki prywatnej.", "klinika", "Czy ubezpieczenie obejmuje tę klinikę?"),
       ("Ubezpieczenie nie obejmuje szpitala prywatnego.", "szpital", "Czy ubezpieczenie obejmuje ten szpital?"),
       ("Ubezpieczenie nie obejmuje pogotowia.", "pogotowie", "Czy ubezpieczenie obejmuje pogotowie?"),
       ("Ubezpieczenie nie obejmuje witamin.", "witaminy", "Czy ubezpieczenie obejmuje witaminy?"),
       ("Ubezpieczenie nie obejmuje maści.", "maść", "Czy ubezpieczenie obejmuje maść?"),
       ("Ubezpieczenie nie obejmuje bandaży.", "bandaż", "Czy ubezpieczenie obejmuje bandaże?"),
       ("Ubezpieczenie nie obejmuje leczenia rany.", "rana", "Czy ubezpieczenie obejmuje opatrunek rany?"),
       ("Ubezpieczenie nie obejmuje oparzenia słonecznego.", "oparzenie słoneczne", "Czy ubezpieczenie obejmuje oparzenie?"),
       ("Ubezpieczenie nie obejmuje ukąszeń owadów.", "ukąszenie owada", "Czy ubezpieczenie obejmuje ukąszenia?"),
       ("Ubezpieczenie nie obejmuje alergii.", "alergia", "Czy ubezpieczenie obejmuje alergię?"),
       ("Ubezpieczenie nie obejmuje motocykla.", "motocykl", "Czy ubezpieczenie obejmuje motocykl?"),
       ("Ubezpieczenie nie obejmuje samochodu.", "samochód", "Czy ubezpieczenie obejmuje samochód?"),
       ("Ubezpieczenie nie obejmuje bagażu.", "walizka", "Czy ubezpieczenie obejmuje bagaż?"),
       ("Ubezpieczenie nie obejmuje telefonu.", "telefon", "Czy ubezpieczenie obejmuje telefon?"),
       ("Ubezpieczenie nie obejmuje sprzętu w mieszkaniu.", "mebel", "Czy ubezpieczenie obejmuje meble?"),
       ("Ubezpieczenie nie obejmuje pralki.", "pralka", "Czy ubezpieczenie obejmuje pralkę?"),
       ("Ubezpieczenie nie obejmuje lodówki.", "lodówka", "Czy ubezpieczenie obejmuje lodówkę?"),
       ("Ubezpieczenie nie obejmuje klimatyzacji.", "klimatyzacja", "Czy ubezpieczenie obejmuje klimatyzację?"),
       ("Ubezpieczenie nie obejmuje kosztów opóźnienia.", "opóźnienie", "Czy ubezpieczenie obejmuje opóźnienie?"),
       ("Ubezpieczenie nie obejmuje biletu.", "bilet", "Czy ubezpieczenie obejmuje bilet?"),
       ("Ubezpieczenie nie obejmuje wycieczki.", "wycieczka", "Czy ubezpieczenie obejmuje wycieczkę?"),
       ("Ubezpieczenie nie obejmuje pokoju w hotelu.", "pokój", "Czy ubezpieczenie obejmuje hotel?"),
       ("Ubezpieczenie nie obejmuje kaucji.", "kaucja", "Czy ubezpieczenie obejmuje kaucję?"),
       ("Ubezpieczenie nie obejmuje czynszu.", "czynsz", "Czy ubezpieczenie obejmuje czynsz?"),
       ("Ubezpieczenie nie obejmuje opłat dodatkowych.", "opłata", "Czy ubezpieczenie obejmuje opłaty?"),
       ("Ubezpieczenie nie obejmuje utraty gotówki.", "gotówka", "Czy ubezpieczenie obejmuje gotówkę?"),
       ("Ubezpieczenie nie obejmuje karty kredytowej.", "karta kredytowa", "Czy ubezpieczenie obejmuje kartę?"),
       ("Ubezpieczenie nie obejmuje paszportu.", "paszport", "Czy ubezpieczenie obejmuje paszport?"),
       ("Ubezpieczenie nie obejmuje kosztów prawnika przy problemie.", "problem", "Czy ubezpieczenie obejmuje pomoc prawną?"),
       ("Ubezpieczenie nie obejmuje kasku.", "kask", "Czy ubezpieczenie obejmuje kask?"),
       ("Ubezpieczenie nie obejmuje okularów.", "okulary", "Czy ubezpieczenie obejmuje okulary?"),
       ("Ubezpieczenie nie obejmuje roweru.", "rower", "Czy ubezpieczenie obejmuje rower?"),
     ]),

# =====================================================================
# khaa … khuen jaak pii thii laew — wzrost kosztow
# =====================================================================
dict(key="KHAAKHUEN", ty="sentence", cat="Zakupy i pieniądze", sub="Koszty", reg="n",
     ph="khâa {ph} khûen jàak pii thîi láew khráp", th="ค่า{th}ขึ้นจากปีที่แล้วครับ",
     lit="khâa … = opłata za …; khûen = wzrosnąć",
     note="„khâa” tworzy nazwę opłaty z niemal każdego rzeczownika. To jeden z najbardziej produktywnych przedrostków w tajskim.",
     ex_ph="khâa {ph} khûen thâo rài jàak pii thîi láew khráp", ex_th="ค่า{th}ขึ้นเท่าไหร่จากปีที่แล้วครับ",
     items=[
       ("Opłata za wynajem wzrosła od zeszłego roku.", "mieszkanie do wynajęcia", "O ile wzrosła opłata za wynajem?"),
       ("Opłata za pokój wzrosła od zeszłego roku.", "pokój", "O ile wzrosła opłata za pokój?"),
       ("Opłata za internet wzrosła od zeszłego roku.", "internet", "O ile wzrosła opłata za internet?"),
       ("Opłata za telefon wzrosła od zeszłego roku.", "telefon", "O ile wzrosła opłata za telefon?"),
       ("Opłata za wodę wzrosła od zeszłego roku.", "woda", "O ile wzrosła opłata za wodę?"),
       ("Opłata za prąd wzrosła od zeszłego roku.", "światło", "O ile wzrosła opłata za prąd?"),
       ("Opłata za benzynę wzrosła od zeszłego roku.", "benzyna", "O ile wzrosła cena benzyny?"),
       ("Opłata za taksówkę wzrosła od zeszłego roku.", "taksówka", "O ile wzrosła opłata za taksówkę?"),
       ("Opłata za autobus wzrosła od zeszłego roku.", "autobus", "O ile wzrosła opłata za autobus?"),
       ("Opłata za pociąg wzrosła od zeszłego roku.", "pociąg", "O ile wzrosła opłata za pociąg?"),
       ("Opłata za bilet wzrosła od zeszłego roku.", "bilet", "O ile wzrosła cena biletu?"),
       ("Opłata za przelew wzrosła od zeszłego roku.", "przelew", "O ile wzrosła opłata za przelew?"),
       ("Opłata za konto wzrosła od zeszłego roku.", "konto", "O ile wzrosła opłata za konto?"),
       ("Opłata za kartę kredytową wzrosła od zeszłego roku.", "karta kredytowa", "O ile wzrosła opłata za kartę?"),
       ("Opłata za ubezpieczenie wzrosła od zeszłego roku.", "ubezpieczenie", "O ile wzrosła składka?"),
       ("Opłata za leki wzrosła od zeszłego roku.", "lek", "O ile wzrosła cena leków?"),
       ("Opłata za badanie wzrosła od zeszłego roku.", "badanie", "O ile wzrosła cena badania?"),
       ("Opłata za dentystę wzrosła od zeszłego roku.", "dentysta", "O ile wzrosła cena u dentysty?"),
       ("Opłata za szkołę wzrosła od zeszłego roku.", "szkoła", "O ile wzrosło czesne?"),
       ("Opłata za uniwersytet wzrosła od zeszłego roku.", "uniwersytet", "O ile wzrosło czesne na uczelni?"),
       ("Opłata za wizę wzrosła od zeszłego roku.", "wiza", "O ile wzrosła opłata wizowa?"),
       ("Opłata za paszport wzrosła od zeszłego roku.", "paszport", "O ile wzrosła opłata za paszport?"),
       ("Opłata za prawo jazdy wzrosła od zeszłego roku.", "prawo jazdy", "O ile wzrosła opłata za prawo jazdy?"),
       ("Opłata za wycieczkę wzrosła od zeszłego roku.", "wycieczka", "O ile wzrosła cena wycieczki?"),
       ("Opłata za hotel wzrosła od zeszłego roku.", "hotel", "O ile wzrosła cena hotelu?"),
       ("Opłata za jedzenie wzrosła od zeszłego roku.", "jedzenie", "O ile wzrosły ceny jedzenia?"),
       ("Opłata za kawę wzrosła od zeszłego roku.", "kawa", "O ile wzrosła cena kawy?"),
       ("Opłata za ryż wzrosła od zeszłego roku.", "ryż", "O ile wzrosła cena ryżu?"),
       ("Opłata za śniadanie wzrosła od zeszłego roku.", "śniadanie", "O ile wzrosła cena śniadania?"),
       ("Opłata za pranie wzrosła od zeszłego roku.", "pralnia", "O ile wzrosła cena prania?"),
       ("Opłata za sprzątanie wzrosła od zeszłego roku.", "sprzątaczka", "O ile wzrosła opłata za sprzątanie?"),
       ("Opłata za ochronę wzrosła od zeszłego roku.", "ochroniarz", "O ile wzrosła opłata za ochronę?"),
       ("Opłata za siłownię wzrosła od zeszłego roku.", "siłownia", "O ile wzrosła opłata za siłownię?"),
       ("Opłata za basen wzrosła od zeszłego roku.", "basen", "O ile wzrosła opłata za basen?"),
       ("Opłata za masaż wzrosła od zeszłego roku.", "masaż", "O ile wzrosła cena masażu?"),
       ("Opłata za naprawy wzrosła od zeszłego roku.", "problem", "O ile wzrosły koszty napraw?"),
     ]),

# =====================================================================
# rueang … khaw song taw hai phanaek thii kiao khawng — przekazanie sprawy
# =====================================================================
dict(key="SONGTAW", ty="sentence", cat="Praca i nauka", sub="Procedury", reg="f",
     ph="rûeang {ph} khǎw sòng tàw hâi phà-nàek thîi kìao khâwng khráp", th="เรื่อง{th}ขอส่งต่อให้แผนกที่เกี่ยวข้องครับ",
     lit="phà-nàek thîi kìao khâwng = właściwy dział",
     note="Standardowa formuła przekierowania w firmie i urzędzie. Zapamiętaj ją także biernie — usłyszysz ją bardzo często.",
     ex_ph="rûeang {ph} sòng tàw hâi phà-nàek nǎi khráp", ex_th="เรื่อง{th}ส่งต่อให้แผนกไหนครับ",
     items=[
       ("Sprawę umowy przekażę do właściwego działu.", "umowa", "Do którego działu trafia sprawa umowy?"),
       ("Sprawę rachunku przekażę do właściwego działu.", "rachunek", "Do którego działu trafia sprawa rachunku?"),
       ("Sprawę przelewu przekażę do właściwego działu.", "przelew", "Do którego działu trafia przelew?"),
       ("Sprawę konta przekażę do właściwego działu.", "konto", "Do którego działu trafia sprawa konta?"),
       ("Sprawę opłaty przekażę do właściwego działu.", "opłata", "Do którego działu trafia sprawa opłaty?"),
       ("Sprawę kaucji przekażę do właściwego działu.", "kaucja", "Do którego działu trafia sprawa kaucji?"),
       ("Sprawę czynszu przekażę do właściwego działu.", "czynsz", "Do którego działu trafia sprawa czynszu?"),
       ("Sprawę pensji przekażę do właściwego działu.", "pensja", "Do którego działu trafia sprawa pensji?"),
       ("Sprawę nadgodzin przekażę do właściwego działu.", "nadgodziny", "Do którego działu trafiają nadgodziny?"),
       ("Sprawę urlopu przekażę do właściwego działu.", "urlop", "Do którego działu trafia sprawa urlopu?"),
       ("Sprawę dokumentów przekażę do właściwego działu.", "dokument", "Do którego działu trafiają dokumenty?"),
       ("Sprawę wizy przekażę do właściwego działu.", "wiza", "Do którego działu trafia sprawa wizy?"),
       ("Sprawę ubezpieczenia przekażę do właściwego działu.", "ubezpieczenie", "Do którego działu trafia ubezpieczenie?"),
       ("Sprawę klienta przekażę do właściwego działu.", "klient", "Do którego działu trafia sprawa klienta?"),
       ("Sprawę projektu przekażę do właściwego działu.", "projekt", "Do którego działu trafia projekt?"),
       ("Sprawę współpracy przekażę do właściwego działu.", "współpraca", "Do którego działu trafia współpraca?"),
       ("Sprawę zebrania przekażę do właściwego działu.", "zebranie", "Do którego działu trafia zebranie?"),
       ("Sprawę internetu przekażę do właściwego działu.", "internet", "Do którego działu trafia internet?"),
       ("Sprawę routera przekażę do właściwego działu.", "router", "Do którego działu trafia router?"),
       ("Sprawę aplikacji przekażę do właściwego działu.", "aplikacja", "Do którego działu trafia aplikacja?"),
       ("Sprawę zasięgu przekażę do właściwego działu.", "zasięg", "Do którego działu trafia sprawa zasięgu?"),
       ("Sprawę klimatyzacji przekażę do właściwego działu.", "klimatyzacja", "Do którego działu trafia klimatyzacja?"),
       ("Sprawę windy przekażę do właściwego działu.", "winda", "Do którego działu trafia sprawa windy?"),
       ("Sprawę pralki przekażę do właściwego działu.", "pralka", "Do którego działu trafia sprawa pralki?"),
       ("Sprawę lodówki przekażę do właściwego działu.", "lodówka", "Do którego działu trafia sprawa lodówki?"),
       ("Sprawę śmieci przekażę do właściwego działu.", "śmieci", "Do którego działu trafia sprawa śmieci?"),
       ("Sprawę ochrony przekażę do właściwego działu.", "ochroniarz", "Do którego działu trafia sprawa ochrony?"),
       ("Sprawę sąsiada z góry przekażę do właściwego działu.", "sąsiad z góry", "Do którego działu trafia ta skarga?"),
       ("Sprawę bagażu przekażę do właściwego działu.", "walizka", "Do którego działu trafia sprawa bagażu?"),
       ("Sprawę biletu przekażę do właściwego działu.", "bilet", "Do którego działu trafia sprawa biletu?"),
       ("Sprawę opóźnienia przekażę do właściwego działu.", "opóźnienie", "Do którego działu trafia opóźnienie?"),
       ("Sprawę wyniku badania przekażę do właściwego działu.", "wynik badania", "Do którego działu trafia wynik?"),
       ("Sprawę leków przekażę do właściwego działu.", "lek", "Do którego działu trafia sprawa leków?"),
       ("Sprawę szkoły przekażę do właściwego działu.", "szkoła", "Do którego działu trafia sprawa szkoły?"),
       ("Sprawę zgłoszonego problemu przekażę do właściwego działu.", "problem", "Do którego działu trafia to zgłoszenie?"),
       ("Sprawę reklamacji ceny przekażę do właściwego działu.", "cena", "Do którego działu trafia sprawa ceny?"),
     ]),
]
