# -*- coding: utf-8 -*-
"""Sesja F — CZASOWNIKI, czesc I: ruch, rece i przedmioty, dzien codzienny,
kuchnia.

Wszystkie hasla w formie podstawowej. Tajski czasownik sie nie odmienia, wiec
haslo slownikowe jest zarazem forma uzywana w zdaniu — to ulatwienie, ktore
warto pokazac uczacemu sie wprost.
"""

CV = "Czasowniki"
CD = "Dom i codzienność"
CF = "Jedzenie i napoje"
CT = "Transport"

VERBS_A = [

# ==================================================================== RUCH
("A1", "iść", "pai", "ไป", CV, "Ruch", 5, "n",
 "Jeden z najczęstszych czasowników tajskich. Wchodzi w setki złożeń jako wskaźnik kierunku „od mówiącego”: „ao pai” (zabrać), „doen pai” (pójść pieszo).",
 "",
 [("Idę do domu.", "phǒm pai bâan khráp", "ผมไปบ้านครับ"),
  ("Dokąd idziesz?", "khun pai nǎi khráp", "คุณไปไหนครับ"),
  ("Idziemy razem.", "rao pai dûai kan khráp", "เราไปด้วยกันครับ")],
 ["przyjść", "chodzić", "wracać"], []),

("A1", "przyjść", "maa", "มา", CV, "Ruch", 5, "n",
 "Para do „pai”. „maa” to kierunek w stronę mówiącego. Ta para działa w tajskim jak dwa bieguny i dokleja się do innych czasowników.",
 "",
 [("Przyjdź tutaj.", "maa thîi nîi khráp", "มาที่นี่ครับ"),
  ("Kiedy przyjdziesz?", "khun jà maa mûea-rài khráp", "คุณจะมาเมื่อไหร่ครับ"),
  ("Przyszedłem wczoraj.", "phǒm maa mûea-waan khráp", "ผมมาเมื่อวานครับ")],
 ["iść", "wracać"], []),

("A1", "chodzić", "doen", "เดิน", CV, "Ruch", 5, "n",
 "Konkretnie: poruszać się pieszo. „doen pai” to pójść na piechotę, w odróżnieniu od „pai” bez określenia sposobu.",
 "",
 [("Chodzę pieszo do pracy.", "phǒm doen pai tham ngaan khráp", "ผมเดินไปทำงานครับ"),
  ("Idźmy powoli.", "doen cháa cháa ná khráp", "เดินช้าๆนะครับ"),
  ("Daleko się idzie?", "doen klai mǎi khráp", "เดินไกลไหมครับ")],
 ["iść", "biegać", "zatrzymać się"], []),

("A2", "wchodzić na górę", "khûen", "ขึ้น", CV, "Ruch", 5, "n",
 "Znaczy „w górę” i tym samym czasownikiem wsiada się do pojazdu: „khûen rót”. Para do „long”.",
 "",
 [("Wchodzę na górę.", "phǒm khûen khâang bon khráp", "ผมขึ้นข้างบนครับ"),
  ("Wsiadaj do samochodu.", "khûen rót khráp", "ขึ้นรถครับ"),
  ("Ceny idą w górę.", "raa-khaa khûen khráp", "ราคาขึ้นครับ")],
 ["schodzić", "piętro"], []),

("A2", "schodzić", "long", "ลง", CV, "Ruch", 5, "n",
 "Para do „khûen”. Tym samym słowem wysiada się z pojazdu i tak samo mówi się o spadku ceny czy temperatury.",
 "",
 [("Schodzę na dół.", "phǒm long khâang lâang khráp", "ผมลงข้างล่างครับ"),
  ("Wysiadam tutaj.", "phǒm long thîi nîi khráp", "ผมลงที่นี่ครับ"),
  ("Deszcz pada.", "fǒn tòk long maa khráp", "ฝนตกลงมาครับ")],
 ["wchodzić na górę", "wysiadać"], []),

("A2", "przechodzić (przez)", "khâam", "ข้าม", CV, "Ruch", 4, "n",
 "O ulicy, moście, rzece. Ton opadający, samogłoska długa.",
 "",
 [("Przejdź przez ulicę.", "khâam thà-nǒn khráp", "ข้ามถนนครับ"),
  ("Uważaj, przechodząc.", "rá-wang tawn khâam ná khráp", "ระวังตอนข้ามนะครับ")],
 ["ulica", "most", "uważać"], []),

("A1", "zatrzymać się", "yùt", "หยุด", CV, "Ruch", 5, "n",
 "Jedno słowo, którym zatrzymasz taksówkę. Ton niski, końcowe „t” niezwolnione.",
 "",
 [("Proszę się tu zatrzymać.", "yùt thîi nîi khráp", "หยุดที่นี่ครับ"),
  ("Deszcz przestał padać.", "fǒn yùt tòk láew khráp", "ฝนหยุดตกแล้วครับ")],
 ["chodzić", "taksówka"], []),

("A2", "dotrzeć", "thǔeng", "ถึง", CV, "Ruch", 5, "n",
 "Znaczy zarówno „dotrzeć”, jak i „aż do”. W rozkładach jazdy oznacza godzinę przyjazdu.",
 "",
 [("Kiedy dotrzemy?", "rao jà thǔeng mûea-rài khráp", "เราจะถึงเมื่อไหร่ครับ"),
  ("Już dotarłem.", "phǒm thǔeng láew khráp", "ผมถึงแล้วครับ")],
 ["przyjść", "stacja"], ["przyjechać"]),

("A2", "wyruszyć", "àwk doen thaang", "ออกเดินทาง", CV, "Ruch", 4, "n",
 "Dosłownie „wyjść w drogę”. Samo „àwk” znaczy wyjść i tak mówi się o odjeździe autobusu.",
 "wyjść iść droga",
 [("Wyruszamy jutro.", "rao jà àwk doen thaang phrûng-níi khráp", "เราจะออกเดินทางพรุ่งนี้ครับ"),
  ("O której odjeżdża autobus?", "rót àwk kìi mohng khráp", "รถออกกี่โมงครับ")],
 ["dotrzeć", "podróżować"], []),

("A2", "podróżować", "thâwng-thîao", "ท่องเที่ยว", CV, "Ruch", 4, "n",
 "O zwiedzaniu dla przyjemności. O przemieszczaniu się w ogóle mówi się „doen thaang”.",
 "",
 [("Lubię podróżować.", "phǒm châwp thâwng-thîao khráp", "ผมชอบท่องเที่ยวครับ"),
  ("Podróżuję sam.", "phǒm thâwng-thîao khon diao khráp", "ผมท่องเที่ยวคนเดียวครับ")],
 ["wyruszyć", "wycieczka"], []),

("A2", "prowadzić (pojazd)", "khàp", "ขับ", CT, "Ruch", 4, "n",
 "O samochodzie i motocyklu. „khàp rót” to prowadzić auto, „khàp mawtoesai” — skuter.",
 "",
 [("Nie umiem prowadzić.", "phǒm khàp rót mâi pen khráp", "ผมขับรถไม่เป็นครับ"),
  ("Prowadź ostrożnie.", "khàp rót rá-wang ná khráp", "ขับรถระวังนะครับ")],
 ["samochód", "motocykl"], []),

("A2", "iść za kimś", "taam", "ตาม", CV, "Ruch", 4, "n",
 "Znaczy też „według” i „szukać kogoś”. „taam maa” to chodź za mną.",
 "",
 [("Proszę iść za mną.", "taam phǒm maa khráp", "ตามผมมาครับ"),
  ("Idę za tobą.", "phǒm taam khun pai khráp", "ผมตามคุณไปครับ")],
 ["iść", "chodzić"], []),

("A2", "uciekać", "nǐi", "หนี", CV, "Ruch", 3, "n",
 "Ton rosnący, samogłoska długa. Przydatne przy zgłaszaniu kradzieży.",
 "",
 [("Złodziej uciekł.", "khà-mooi nǐi pai láew khráp", "ขโมยหนีไปแล้วครับ"),
  ("Pies uciekł.", "mǎa nǐi pai khráp", "หมาหนีไปครับ")],
 ["kradzież", "biegać"], []),

("A2", "spaść", "tòk", "ตก", CV, "Ruch", 4, "n",
 "Bardzo szeroki zakres: spada deszcz, spada cena, można też „tòk rót” — spóźnić się na autobus, dosłownie „spaść z pojazdu”.",
 "",
 [("Telefon mi spadł.", "thoo-rá-sàp phǒm tòk khráp", "โทรศัพท์ผมตกครับ"),
  ("Spóźniłem się na autobus.", "phǒm tòk rót khráp", "ผมตกรถครับ")],
 ["schodzić", "deszcz"], []),

("A2", "wstać (z miejsca)", "lúk", "ลุก", CV, "Ruch", 3, "n",
 "Podnieść się z siedzenia albo z łóżka. Nie mylić z „tùen” (obudzić się).",
 "",
 [("Proszę wstać.", "chûai lúk khûen nòi khráp", "ช่วยลุกขึ้นหน่อยครับ"),
  ("Wstałem i wyszedłem.", "phǒm lúk láew àwk pai khráp", "ผมลุกแล้วออกไปครับ")],
 ["budzić się", "siedzieć"], []),

# ================================================== RECE I PRZEDMIOTY
("A1", "kłaść", "waang", "วาง", CV, "Czynności", 4, "n",
 "Odłożyć coś na powierzchnię. „waang wái” znaczy zostawić coś na miejscu.",
 "",
 [("Połóż to na stole.", "waang bon tó khráp", "วางบนโต๊ะครับ"),
  ("Gdzie mam to położyć?", "waang thîi nǎi dii khráp", "วางที่ไหนดีครับ")],
 ["brać", "podnieść", "stół"], []),

("A2", "podnieść", "yók", "ยก", CV, "Czynności", 4, "n",
 "O ciężarze. „yók hâi” znaczy też „ustąpić, oddać komuś”.",
 "",
 [("To jest za ciężkie, nie podniosę.", "nàk koen pai yók mâi wǎi khráp", "หนักเกินไปยกไม่ไหวครับ"),
  ("Pomożesz mi podnieść?", "chûai yók nòi dâai mǎi khráp", "ช่วยยกหน่อยได้ไหมครับ")],
 ["kłaść", "ciężki", "nieść"], []),

("A2", "nieść", "thǔe", "ถือ", CV, "Czynności", 4, "n",
 "Trzymać coś w ręku i przenosić. „thǔe krà-pǎo” — nieść torbę.",
 "",
 [("Poniosę twoją torbę.", "phǒm thǔe krà-pǎo hâi khráp", "ผมถือกระเป๋าให้ครับ"),
  ("Nie mogę tego nieść.", "phǒm thǔe mâi wǎi khráp", "ผมถือไม่ไหวครับ")],
 ["podnieść", "torba", "ręka (dłoń)"], ["trzymać"]),

("A2", "ciągnąć", "dueng", "ดึง", CV, "Czynności", 3, "n",
 "Na drzwiach obok „phlàk”. Warto znać oba, bo napisy bywają tylko po tajsku.",
 "",
 [("Ciągnij drzwi.", "dueng prà-tuu khráp", "ดึงประตูครับ"),
  ("Nie ciągnij tak mocno.", "yàa dueng raeng khráp", "อย่าดึงแรงครับ")],
 ["pchać", "drzwi"], []),

("A2", "pchać", "phlàk", "ผลัก", CV, "Czynności", 3, "n",
 "Para do „dueng”. Zbitka „phl” jest dla Polaka trudna — ćwicz osobno.",
 "",
 [("Pchnij drzwi.", "phlàk prà-tuu khráp", "ผลักประตูครับ"),
  ("Ktoś mnie popchnął.", "mii khon phlàk phǒm khráp", "มีคนผลักผมครับ")],
 ["ciągnąć", "drzwi"], []),

("A2", "łapać", "jàp", "จับ", CV, "Czynności", 4, "n",
 "Znaczy też „trzymać” i „aresztować” — „tam-rùat jàp” to policja kogoś zatrzymała.",
 "",
 [("Złap to.", "jàp wái khráp", "จับไว้ครับ"),
  ("Policja złapała złodzieja.", "tam-rùat jàp khà-mooi dâai láew khráp", "ตำรวจจับขโมยได้แล้วครับ")],
 ["nieść", "policjant"], []),

("A2", "rzucać", "khwâang", "ขว้าง", CV, "Czynności", 2, "n",
 "O rzucaniu przedmiotem. Wyrzucić śmieci to jednak „thíng”.",
 "",
 [("Nie rzucaj tym.", "yàa khwâang khráp", "อย่าขว้างครับ"),
  ("Rzucił piłkę.", "kháo khwâang lûuk bawn khráp", "เขาขว้างลูกบอลครับ")],
 ["wyrzucić", "łapać"], []),

("A2", "wyrzucić", "thíng", "ทิ้ง", CV, "Czynności", 4, "n",
 "O śmieciach, ale też o porzuceniu czegoś lub kogoś. Ton wysoki.",
 "",
 [("Wyrzuć to.", "thíng pai khráp", "ทิ้งไปครับ"),
  ("Gdzie wyrzucić śmieci?", "thíng khà-yà thîi nǎi khráp", "ทิ้งขยะที่ไหนครับ")],
 ["śmieci", "rzucać"], []),

("A2", "wkładać", "sài", "ใส่", CV, "Czynności", 5, "n",
 "Jeden z najbardziej uniwersalnych czasowników. Znaczy „włożyć”, ale też „dodać składnik” i „mieć na sobie ubranie”. Zdanie „mâi sài phrík” to właśnie ten czasownik.",
 "",
 [("Poproszę bez chili.", "mâi sài phrík khráp", "ไม่ใส่พริกครับ"),
  ("Włóż to do torby.", "sài nai krà-pǎo khráp", "ใส่ในกระเป๋าครับ"),
  ("Mam na sobie czarną koszulę.", "phǒm sài sûea sǐi dam khráp", "ผมใส่เสื้อสีดำครับ")],
 ["zdejmować", "wyjmować", "koszula"], []),

("A2", "wyjmować", "ao àwk", "เอาออก", CV, "Czynności", 4, "n",
 "Dosłownie „wziąć na zewnątrz”. Tajski składa czasowniki tam, gdzie polski ma przedrostki.",
 "wziąć wyjść",
 [("Wyjmij to, proszę.", "chûai ao àwk nòi khráp", "ช่วยเอาออกหน่อยครับ"),
  ("Poproszę wyjąć lód.", "chûai ao nám khǎeng àwk khráp", "ช่วยเอาน้ำแข็งออกครับ")],
 ["wkładać", "zdejmować"], []),

("A2", "zdejmować", "thàwt", "ถอด", CD, "Czynności", 4, "n",
 "O butach, ubraniu, okularach. Przy wejściu do domu i świątyni usłyszysz „thàwt rawng-tháo”.",
 "",
 [("Proszę zdjąć buty.", "kà-rú-naa thàwt rawng-tháo khráp", "กรุณาถอดรองเท้าครับ"),
  ("Zdejmij kurtkę.", "thàwt sûea nâwk khráp", "ถอดเสื้อนอกครับ")],
 ["wkładać", "buty", "świątynia"], []),

("A2", "ubierać się", "tàeng tua", "แต่งตัว", CD, "Czynności", 4, "n",
 "Dosłownie „ozdobić ciało”. O samym wkładaniu konkretnej rzeczy mówi się „sài”.",
 "ozdobić ciało",
 [("Ubieram się.", "phǒm kam-lang tàeng tua khráp", "ผมกำลังแต่งตัวครับ"),
  ("Ubierz się ładnie.", "tàeng tua sǔai sǔai ná khráp", "แต่งตัวสวยๆนะครับ")],
 ["wkładać", "koszula", "sukienka"], []),

("A2", "wieszać", "khwǎen", "แขวน", CD, "Czynności", 3, "n",
 "O ubraniu na wieszaku i o obrazie na ścianie. Ton rosnący.",
 "",
 [("Powieś to w szafie.", "khwǎen wái nai tûu khráp", "แขวนไว้ในตู้ครับ"),
  ("Gdzie mogę powiesić ręcznik?", "khwǎen phâa chét tua thîi nǎi khráp", "แขวนผ้าเช็ดตัวที่ไหนครับ")],
 ["szafa", "ręcznik", "kłaść"], []),

("A2", "wiązać", "phùuk", "ผูก", CV, "Czynności", 3, "n",
 "O sznurku, sznurowadle, ale też o wiązaniu umowy: „phùuk phan” znaczy „zobowiązywać”.",
 "",
 [("Zawiąż to mocno.", "phùuk hâi nâen khráp", "ผูกให้แน่นครับ"),
  ("Nie umiem zawiązać.", "phǒm phùuk mâi pen khráp", "ผมผูกไม่เป็นครับ")],
 ["ciągnąć", "buty"], []),

("A2", "ciąć", "tàt", "ตัด", CV, "Czynności", 4, "n",
 "Uniwersalne: ciąć papier, obciąć włosy, obciąć cenę. „tàt raa-khaa” to obniżka.",
 "",
 [("Chcę obciąć włosy.", "phǒm yàak tàt phǒm khráp", "ผมอยากตัดผมครับ"),
  ("Proszę to przeciąć na pół.", "tàt khrûeng nùeng khráp", "ตัดครึ่งหนึ่งครับ")],
 ["kroić", "włosy", "nóż"], []),

("A2", "kroić", "hàn", "หั่น", CF, "Kuchnia", 3, "n",
 "Konkretnie o jedzeniu. Warzywa i mięso się „hàn”, włosy się „tàt”.",
 "",
 [("Pokrój warzywa.", "hàn phàk khráp", "หั่นผักครับ"),
  ("Pokrojone drobno.", "hàn lék lék khráp", "หั่นเล็กๆครับ")],
 ["ciąć", "warzywo", "nóż"], []),

("A2", "wycierać", "chét", "เช็ด", CD, "Sprzątanie", 4, "n",
 "„phâa chét tua” to ręcznik, dosłownie „ściereczka do wycierania ciała”.",
 "",
 [("Wytrzyj stół.", "chét tó khráp", "เช็ดโต๊ะครับ"),
  ("Wytrzyj ręce.", "chét mue khráp", "เช็ดมือครับ")],
 ["ręcznik", "sprzątać", "myć"], []),

("A2", "zamiatać", "kwàat", "กวาด", CD, "Sprzątanie", 3, "n",
 "O podłodze. „mái kwàat” to miotła.",
 "",
 [("Zamiatam podłogę.", "phǒm kwàat phúen khráp", "ผมกวาดพื้นครับ"),
  ("Trzeba tu zamieść.", "tâwng kwàat thîi nîi khráp", "ต้องกวาดที่นี่ครับ")],
 ["sprzątać", "wycierać", "podłoga"], []),

("A2", "pakować", "pák", "แพ็ค", CV, "Czynności", 3, "n",
 "Zapożyczenie z angielskiego, używane o walizce i o paczce. Tradycyjnie mówi się też „kèp khǎwng”.",
 "",
 [("Pakuję walizkę.", "phǒm pák krà-pǎo khráp", "ผมแพ็คกระเป๋าครับ"),
  ("Poproszę zapakować na wynos.", "chûai pák klàp bâan khráp", "ช่วยแพ็คกลับบ้านครับ")],
 ["walizka", "wkładać"], []),

("A2", "psuć się", "sǐa", "เสีย", CV, "Czynności", 5, "n",
 "Bardzo szeroki zakres: zepsuty sprzęt, zepsute jedzenie, „sǐa jai” — być smutnym, „sǐa ngoen” — wydać pieniądze.",
 "",
 [("Klimatyzacja się zepsuła.", "aae sǐa khráp", "แอร์เสียครับ"),
  ("To jedzenie się zepsuło.", "aa-hǎan níi sǐa láew khráp", "อาหารนี้เสียแล้วครับ")],
 ["naprawiać", "zepsuty"], []),

("A2", "łamać", "hàk", "หัก", CV, "Czynności", 3, "n",
 "O kości, gałęzi, ale też o potrąceniu z pensji: „hàk ngoen”.",
 "",
 [("Złamałem rękę.", "khǎen phǒm hàk khráp", "แขนผมหักครับ"),
  ("Krzesło się złamało.", "kâo-îi hàk khráp", "เก้าอี้หักครับ")],
 ["kość", "psuć się", "rozbić"], []),

("A2", "rozbić", "tham tàek", "ทำแตก", CV, "Czynności", 3, "n",
 "Dosłownie „zrobić, że pęknie”. Konstrukcja „tham + skutek” jest w tajskim bardzo produktywna: „tham hǎai” — zgubić, „tham hòk” — rozlać.",
 "zrobić pęknąć",
 [("Przepraszam, stłukłem szklankę.", "khǎw thôot khráp phǒm tham kâew tàek", "ขอโทษครับผมทำแก้วแตก"),
  ("Uważaj, żeby nie rozbić.", "rá-wang yàa tham tàek ná khráp", "ระวังอย่าทำแตกนะครับ")],
 ["łamać", "psuć się", "szklanka"], []),

("A2", "rozlać", "tham hòk", "ทำหก", CV, "Czynności", 3, "n",
 "Ta sama konstrukcja „tham + skutek”. Przydaje się przy przepraszaniu w restauracji.",
 "zrobić rozlać",
 [("Rozlałem wodę.", "phǒm tham nám hòk khráp", "ผมทำน้ำหกครับ"),
  ("Uważaj, żeby nie rozlać.", "rá-wang yàa tham hòk ná khráp", "ระวังอย่าทำหกนะครับ")],
 ["rozbić", "woda"], []),

# ============================================================ DZIEN CODZIENNY
("A1", "budzić się", "tùen", "ตื่น", CD, "Codzienność", 5, "n",
 "„tùen nawn” to pełna forma. Uwaga: to samo słowo znaczy „być podekscytowanym” w „tùen tên”.",
 "",
 [("Budzę się o szóstej.", "phǒm tùen hòk mohng cháo khráp", "ผมตื่นหกโมงเช้าครับ"),
  ("Obudź mnie o siódmej.", "plùk phǒm jèt mohng khráp", "ปลุกผมเจ็ดโมงครับ")],
 ["zasypiać", "wstawać", "rano"], []),

("A2", "zasypiać", "làp", "หลับ", CD, "Codzienność", 4, "n",
 "„nawn làp” to zasnąć. Samo „nawn” znaczy leżeć albo iść spać, niekoniecznie zasnąć.",
 "",
 [("Nie mogę zasnąć.", "phǒm nawn mâi làp khráp", "ผมนอนไม่หลับครับ"),
  ("Zasnąłem w autobusie.", "phǒm làp bon rót khráp", "ผมหลับบนรถครับ")],
 ["budzić się", "spać", "łóżko"], []),

("A2", "brać prysznic", "àap nám", "อาบน้ำ", CD, "Codzienność", 5, "n",
 "Dosłownie „kąpać wodą”. W tajskim klimacie czynność wykonywana zwykle dwa razy dziennie — pytanie „àap nám rúe yang” jest zwykłą uprzejmością.",
 "kąpać woda",
 [("Biorę prysznic.", "phǒm kam-lang àap nám khráp", "ผมกำลังอาบน้ำครับ"),
  ("Wezmę prysznic i wychodzę.", "àap nám sèt láew pai khráp", "อาบน้ำเสร็จแล้วไปครับ")],
 ["myć", "prysznic", "ręcznik"], ["kąpać się"]),

("A2", "myć zęby", "praeng fan", "แปรงฟัน", CD, "Codzienność", 4, "n",
 "„praeng” to zarazem szczotka i czynność szczotkowania.",
 "szczotkować zęby",
 [("Myję zęby rano i wieczorem.", "phǒm praeng fan cháo yen khráp", "ผมแปรงฟันเช้าเย็นครับ"),
  ("Zapomniałem szczoteczki.", "phǒm luem praeng sǐi fan khráp", "ผมลืมแปรงสีฟันครับ")],
 ["ząb", "brać prysznic"], []),

("A2", "czesać się", "wǐi phǒm", "หวีผม", CD, "Codzienność", 2, "n",
 "„wǐi” to grzebień i czynność zarazem — jak „praeng” przy zębach.",
 "grzebień włosy",
 [("Czeszę się.", "phǒm wǐi phǒm khráp", "ผมหวีผมครับ"),
  ("Masz grzebień?", "mii wǐi mǎi khráp", "มีหวีไหมครับ")],
 ["włosy", "ubierać się"], []),

("A2", "golić się", "kon nùat", "โกนหนวด", CD, "Codzienność", 2, "n",
 "„nùat” to wąsy i zarost. Nie mylić z „nûat” (masaż) — różni je ton.",
 "golić zarost",
 [("Golę się codziennie.", "phǒm kon nùat thúk wan khráp", "ผมโกนหนวดทุกวันครับ"),
  ("Zapomniałem maszynki.", "phǒm luem mîit kon nùat khráp", "ผมลืมมีดโกนหนวดครับ")],
 ["broda", "ubierać się"], []),

("A2", "ćwiczyć (sport)", "àwk kam-lang kaai", "ออกกำลังกาย", CD, "Codzienność", 4, "n",
 "Dosłownie „wydawać siłę ciała”. Cztery sylaby, ale to jedyne naturalne określenie aktywności fizycznej.",
 "wydawać siła ciało",
 [("Ćwiczę codziennie.", "phǒm àwk kam-lang kaai thúk wan khráp", "ผมออกกำลังกายทุกวันครับ"),
  ("Powinieneś więcej ćwiczyć.", "khun khuan àwk kam-lang kaai bàwi bàwi khráp", "คุณควรออกกำลังกายบ่อยๆครับ")],
 ["siłownia", "biegać", "mięsień"], []),

("A2", "prasować", "rîit phâa", "รีดผ้า", CD, "Sprzątanie", 3, "n",
 "„phâa” to tkanina i ubranie. W hotelu „rîit phâa” to usługa prasowania.",
 "prasować tkanina",
 [("Czy prasujecie ubrania?", "mii bawn-rí-kaan rîit phâa mǎi khráp", "มีบริการรีดผ้าไหมครับ"),
  ("Muszę wyprasować koszulę.", "phǒm tâwng rîit sûea khráp", "ผมต้องรีดเสื้อครับ")],
 ["prać", "pralnia", "koszula"], []),

# =================================================================== KUCHNIA
("A1", "smażyć na patelni", "phàt", "ผัด", CF, "Sposoby przyrządzania", 5, "n",
 "Kluczowe słowo w karcie dań: „phàt thai”, „phàt krà-phao”, „phàt phàk”. Oznacza szybkie smażenie z mieszaniem.",
 "",
 [("Poproszę smażony ryż.", "khǎw khâao phàt khráp", "ขอข้าวผัดครับ"),
  ("Poproszę smażone warzywa.", "khǎw phàk phàt khráp", "ขอผัดผักครับ")],
 ["smażyć na głębokim", "grillować", "warzywo"], []),

("A1", "smażyć na głębokim", "thâwt", "ทอด", CF, "Sposoby przyrządzania", 5, "n",
 "W głębokim oleju. „kài thâwt” to smażony kurczak, „mǔu thâwt” — wieprzowina.",
 "",
 [("Poproszę smażonego kurczaka.", "khǎw kài thâwt khráp", "ขอไก่ทอดครับ"),
  ("Poproszę frytki.", "khǎw man fà-ràng thâwt khráp", "ขอมันฝรั่งทอดครับ")],
 ["smażyć na patelni", "ziemniak", "kurczak"], []),

("A1", "grillować", "yâang", "ย่าง", CF, "Sposoby przyrządzania", 5, "n",
 "Nad węglem. Standard ulicznego jedzenia: „mǔu yâang”, „kài yâang”.",
 "",
 [("Poproszę grillowaną wieprzowinę.", "khǎw mǔu yâang khráp", "ขอหมูย่างครับ"),
  ("Grillowana ryba jest dobra.", "plaa yâang à-ròi khráp", "ปลาย่างอร่อยครับ")],
 ["smażyć na głębokim", "ryba", "świnia"], []),

("A1", "gotować w wodzie", "tôm", "ต้ม", CF, "Sposoby przyrządzania", 5, "n",
 "Stąd nazwa „tôm yam” — dosłownie „gotowana sałatka”. Ton opadający.",
 "",
 [("Poproszę gotowane jajko.", "khǎw khài tôm khráp", "ขอไข่ต้มครับ"),
  ("Ta zupa jest gotowana długo.", "súp níi tôm naan khráp", "ซุปนี้ต้มนานครับ")],
 ["gotować na parze", "zupa", "jajko"], []),

("A2", "gotować na parze", "nûeng", "นึ่ง", CF, "Sposoby przyrządzania", 4, "n",
 "Najzdrowszy sposób i dobre słowo dla kogoś na diecie: „plaa nûeng” to ryba na parze.",
 "",
 [("Poproszę rybę na parze.", "khǎw plaa nûeng khráp", "ขอปลานึ่งครับ"),
  ("Wolę gotowane na parze.", "phǒm châwp bàep nûeng kwàa khráp", "ผมชอบแบบนึ่งกว่าครับ")],
 ["gotować w wodzie", "ryba", "dynia"], []),

("A2", "piec", "òp", "อบ", CF, "Sposoby przyrządzania", 3, "n",
 "W piekarniku. Rzadsze w kuchni tajskiej, ale obecne w piekarniach i pizzeriach.",
 "",
 [("Poproszę pieczonego kurczaka.", "khǎw kài òp khráp", "ขอไก่อบครับ"),
  ("Ten chleb jest świeżo pieczony.", "khà-nǒm pang òp mài khráp", "ขนมปังอบใหม่ครับ")],
 ["grillować", "chleb"], []),

("A2", "mieszać (łyżką)", "khon", "คน", CF, "Kuchnia", 3, "n",
 "Uwaga na homonim: „khon” z tym samym zapisem znaczy też „człowiek”. Kontekst rozstrzyga.",
 "",
 [("Wymieszaj dobrze.", "khon hâi khâo kan khráp", "คนให้เข้ากันครับ"),
  ("Mieszaj powoli.", "khon cháa cháa khráp", "คนช้าๆครับ")],
 ["nalewać", "łyżka"], []),

("A2", "nalewać", "rin", "ริน", CF, "Kuchnia", 3, "n",
 "O napoju. Prosta sylaba z tonem średnim.",
 "",
 [("Naleję ci wody.", "phǒm rin nám hâi khráp", "ผมรินน้ำให้ครับ"),
  ("Nalej mniej, proszę.", "rin nói nòi khráp", "รินน้อยหน่อยครับ")],
 ["mieszać (łyżką)", "woda", "szklanka"], []),

("A2", "obierać", "pàwk", "ปอก", CF, "Kuchnia", 3, "n",
 "O owocach i warzywach. Na targu usłyszysz pytanie „pàwk hâi mǎi” — obrać panu?",
 "",
 [("Proszę obrać.", "pàwk hâi nòi khráp", "ปอกให้หน่อยครับ"),
  ("Obieram mango.", "phǒm pàwk má-mûang khráp", "ผมปอกมะม่วงครับ")],
 ["kroić", "mango", "nóż"], []),

("A2", "podgrzewać", "ûn", "อุ่น", CF, "Kuchnia", 3, "n",
 "To samo słowo znaczy „letni, ciepławy”. „ûn aa-hǎan” to odgrzać jedzenie.",
 "",
 [("Proszę podgrzać.", "chûai ûn hâi nòi khráp", "ช่วยอุ่นให้หน่อยครับ"),
  ("Jedzenie jest ledwo ciepłe.", "aa-hǎan ûn ûn khráp", "อาหารอุ่นๆครับ")],
 ["zamrażać", "gorący"], []),

("A2", "zamrażać", "châe khǎeng", "แช่แข็ง", CF, "Kuchnia", 3, "n",
 "„châe” znaczy moczyć, zanurzać; „khǎeng” — twardy. Razem: zamrozić.",
 "moczyć twardy",
 [("Włóż to do zamrażarki.", "sài châwng châe khǎeng khráp", "ใส่ช่องแช่แข็งครับ"),
  ("To jest mrożone.", "an níi châe khǎeng khráp", "อันนี้แช่แข็งครับ")],
 ["podgrzewać", "lodówka", "lód"], []),

("A2", "próbować (smakować)", "chim", "ชิม", CF, "Kuchnia", 4, "n",
 "Tylko o smaku. Próbować w znaczeniu „usiłować” to „lawng”.",
 "",
 [("Chce pan spróbować?", "lawng chim mǎi khráp", "ลองชิมไหมครับ"),
  ("Spróbowałem, jest dobre.", "phǒm chim láew à-ròi khráp", "ผมชิมแล้วอร่อยครับ")],
 ["smak", "smaczny"], []),

("A2", "zmywać naczynia", "láang jaan", "ล้างจาน", CD, "Sprzątanie", 3, "n",
 "„láang” to myć wodą — także ręce, warzywa i samochód.",
 "myć talerz",
 [("Zmywam naczynia.", "phǒm láang jaan khráp", "ผมล้างจานครับ"),
  ("Kto zmywa dzisiaj?", "wan-níi khrai láang jaan khráp", "วันนี้ใครล้างจานครับ")],
 ["talerz", "myć", "sprzątać"], []),

("A2", "karmić", "líang", "เลี้ยง", CV, "Czynności", 3, "n",
 "Znaczy też „wychowywać dziecko” i „postawić komuś posiłek” — „phǒm líang” to „ja stawiam”.",
 "",
 [("Ja stawiam.", "wan-níi phǒm líang khráp", "วันนี้ผมเลี้ยงครับ"),
  ("Karmię psa.", "phǒm líang mǎa khráp", "ผมเลี้ยงหมาครับ")],
 ["płacić", "pies", "dziecko"], []),
]
