# -*- coding: utf-8 -*-
"""Sesja F — CZESCI CIALA. System zamkniety.

Kazda czesc ciala jest powiazana z dolegliwoscia, bo w tej roli uczacy sie jej
naprawde potrzebuje. Tajska konstrukcja bolu: „pùat” + czesc ciala, bez zaimka
dzierzawczego — „pùat hǔa”, nie „boli moja glowa”.
"""

CAT = "Zdrowie"
SUB = "Części ciała"

BODY = [

("A1", "głowa", "hǔa", "หัว", CAT, SUB, 5, "n",
 "Ton rosnący. Uwaga kulturowa: głowa jest w Tajlandii częścią najbardziej szanowaną — nie dotyka się cudzej głowy, nawet dziecka.",
 "",
 [("Boli mnie głowa.", "pùat hǔa khráp", "ปวดหัวครับ"),
  ("Proszę nie dotykać jej głowy.", "kà-rú-naa yàa tàe hǔa khǎo khráp", "กรุณาอย่าแตะหัวเขาครับ"),
  ("Uderzyłem się w głowę.", "phǒm hǔa chon khráp", "ผมหัวชนครับ")],
 ["włosy", "twarz", "ból"], []),

("A1", "oko", "taa", "ตา", CAT, SUB, 5, "n",
 "Krótkie, proste słowo. To samo „taa” znaczy też „dziadek ze strony matki” — kontekst rozstrzyga.",
 "",
 [("Bolą mnie oczy.", "pùat taa khráp", "ปวดตาครับ"),
  ("Mam coś w oku.", "mii à-rai khâo taa khráp", "มีอะไรเข้าตาครับ"),
  ("Zamknij oczy.", "làp taa sí", "หลับตาสิ")],
 ["ucho", "nos", "okulary"], ["oczy"]),

("A1", "ucho", "hǔu", "หู", CAT, SUB, 4, "n",
 "Samogłoska długa i ton rosnący. Nie skracaj — „hǔ” z krótkim „u” nie brzmi jak słowo.",
 "",
 [("Boli mnie ucho.", "pùat hǔu khráp", "ปวดหูครับ"),
  ("Nie słyszę na to ucho.", "hǔu khâang níi mâi dâai yin khráp", "หูข้างนี้ไม่ได้ยินครับ")],
 ["oko", "nos", "słyszeć"], ["uszy"]),

("A1", "nos", "jà-mùuk", "จมูก", CAT, SUB, 4, "n",
 "„j” czytaj jak polskie „dź”. Drugą sylabę wymawiaj długo, końcowe „k” niezwolnione.",
 "",
 [("Mam katar.", "nám mûuk lǎi khráp", "น้ำมูกไหลครับ"),
  ("Mam zatkany nos.", "jà-mùuk tan khráp", "จมูกตันครับ")],
 ["oko", "ucho", "katar"], []),

("A1", "usta", "pàak", "ปาก", CAT, SUB, 4, "n",
 "„p” bez przydechu — to nie „ph”. Ton niski, samogłoska długa.",
 "",
 [("Otwórz usta.", "âa pàak khráp", "อ้าปากครับ"),
  ("Mam ranę w ustach.", "mii phlǎe nai pàak khráp", "มีแผลในปากครับ")],
 ["ząb", "język", "gardło"], []),

("A1", "ząb", "fan", "ฟัน", CAT, SUB, 4, "n",
 "Ton średni, krótko. „mǎw fan” to dentysta — dosłownie „lekarz od zębów”.",
 "",
 [("Boli mnie ząb.", "pùat fan khráp", "ปวดฟันครับ"),
  ("Muszę iść do dentysty.", "phǒm tâwng pai hǎa mǎw fan khráp", "ผมต้องไปหาหมอฟันครับ"),
  ("Myję zęby.", "phǒm praeng fan khráp", "ผมแปรงฟันครับ")],
 ["usta", "ból", "lekarz"], ["zęby"]),

("A2", "język (w ustach)", "lín", "ลิ้น", CAT, SUB, 3, "n",
 "Uwaga: to inne słowo niż język w znaczeniu mowy — ten drugi to „phaa-sǎa”.",
 "",
 [("Poparzyłem sobie język.", "lín phǒm lûak khráp", "ลิ้นผมลวกครับ"),
  ("To jest ostre na języku.", "phèt lín khráp", "เผ็ดลิ้นครับ")],
 ["usta", "ząb", "ostry"], []),

("A1", "szyja", "khaw", "คอ", CAT, SUB, 4, "n",
 "To samo słowo oznacza gardło. Rozróżnienie robi kontekst albo czasownik: „pùat khaw” to raczej ból gardła.",
 "",
 [("Boli mnie szyja.", "pùat khaw khráp", "ปวดคอครับ"),
  ("Nie mogę obrócić szyi.", "phǒm mǔn khaw mâi dâai khráp", "ผมหมุนคอไม่ได้ครับ")],
 ["gardło", "ramię", "plecy"], []),

("A1", "gardło", "lam-khaw", "ลำคอ", CAT, SUB, 4, "n",
 "Wersja jednoznaczna, gdy chcesz odróżnić gardło od szyi. W rozmowie z lekarzem wystarczy jednak „jèp khaw”.",
 "",
 [("Boli mnie gardło.", "jèp khaw khráp", "เจ็บคอครับ"),
  ("Mam ból gardła od wczoraj.", "jèp khaw tâng-tàe mûea-waan khráp", "เจ็บคอตั้งแต่เมื่อวานครับ")],
 ["szyja", "kaszel", "przeziębienie"], []),

("A2", "ramię (bark)", "làai", "ไหล่", CAT, SUB, 3, "n",
 "Bark, nie cała ręka. Częste przy bólu po noszeniu plecaka.",
 "",
 [("Boli mnie bark.", "pùat làai khráp", "ปวดไหล่ครับ"),
  ("Prawy bark boli bardziej.", "làai khwǎa pùat kwàa khráp", "ไหล่ขวาปวดกว่าครับ")],
 ["ręka (dłoń)", "szyja", "plecy"], ["bark"]),

("A1", "ręka (dłoń)", "mue", "มือ", CAT, SUB, 5, "n",
 "„ue” to samogłoska bliska polskiemu „y”. Tym słowem obejmuje się dłoń, a często całą rękę w mowie potocznej.",
 "",
 [("Umyj ręce.", "láang mue khráp", "ล้างมือครับ"),
  ("Skaleczyłem się w rękę.", "phǒm bàat mue khráp", "ผมบาดมือครับ"),
  ("Podaj mi rękę.", "yûen mue maa khráp", "ยื่นมือมาครับ")],
 ["palec", "ramię (przedramię)", "myć"], ["dłoń"]),

("A2", "ramię (przedramię)", "khǎen", "แขน", CAT, SUB, 4, "n",
 "Ręka od barku do nadgarstka. Odróżnij od „mue” — po tajsku to dwa różne słowa, po polsku często jedno.",
 "",
 [("Boli mnie ręka.", "pùat khǎen khráp", "ปวดแขนครับ"),
  ("Złamałem rękę.", "khǎen phǒm hàk khráp", "แขนผมหักครับ")],
 ["ręka (dłoń)", "ramię (bark)", "kość"], ["ramię"]),

("A2", "palec", "níu", "นิ้ว", CAT, SUB, 4, "n",
 "To samo słowo znaczy „cal” jako miara. Dotyczy palców rąk i stóp.",
 "",
 [("Skaleczyłem się w palec.", "phǒm bàat níu khráp", "ผมบาดนิ้วครับ"),
  ("Ten pierścionek nie pasuje na mój palec.", "wǎen mâi phaw dii kàp níu phǒm khráp", "แหวนไม่พอดีกับนิ้วผมครับ")],
 ["ręka (dłoń)", "stopa", "paznokieć"], []),

("A2", "paznokieć", "lép", "เล็บ", CAT, SUB, 3, "n",
 "Krótka samogłoska, końcowe „p” niezwolnione. Salon paznokciowy to „ráan tham lép”.",
 "",
 [("Chciałbym obciąć paznokcie.", "phǒm yàak tàt lép khráp", "ผมอยากตัดเล็บครับ"),
  ("Ona maluje paznokcie.", "kháo thaa lép khâ", "เขาทาเล็บค่ะ")],
 ["palec", "ręka (dłoń)"], []),

("A1", "noga", "khǎa", "ขา", CAT, SUB, 5, "n",
 "Ton rosnący, samogłoska długa. Uwaga kulturowa: nie wskazuje się nogą i nie kieruje stopy w stronę człowieka ani wizerunku Buddy.",
 "",
 [("Bolą mnie nogi.", "pùat khǎa khráp", "ปวดขาครับ"),
  ("Skręciłem nogę.", "khǎa phǒm phlík khráp", "ขาผมพลิกครับ")],
 ["stopa", "kolano", "chodzić"], ["nogi"]),

("A1", "stopa", "tháo", "เท้า", CAT, SUB, 4, "n",
 "„th” to „t” z przydechem, „ao” czytaj jak „au”. Stopa to część ciała uważana za najniższą także symbolicznie.",
 "",
 [("Bolą mnie stopy.", "pùat tháo khráp", "ปวดเท้าครับ"),
  ("Proszę zdjąć buty.", "kà-rú-naa thàwt rawng-tháo khráp", "กรุณาถอดรองเท้าครับ")],
 ["noga", "kolano", "but"], []),

("A2", "kolano", "hǔa khào", "หัวเข่า", CAT, SUB, 3, "n",
 "Dosłownie „głowa kolana”. Częste przy zgłaszaniu urazu po wypadku na skuterze.",
 "głowa kolana",
 [("Boli mnie kolano.", "pùat hǔa khào khráp", "ปวดหัวเข่าครับ"),
  ("Rozbiłem kolano.", "hǔa khào tàek khráp", "หัวเข่าแตกครับ")],
 ["noga", "stopa", "rana"], []),

("A1", "plecy", "lǎng", "หลัง", CAT, SUB, 4, "n",
 "To samo słowo znaczy „za, po” — „lǎng aa-hǎan” to po posiłku. Ton rosnący.",
 "",
 [("Bolą mnie plecy.", "pùat lǎng khráp", "ปวดหลังครับ"),
  ("Boli mnie dolna część pleców.", "pùat lǎng thâwn lâang khráp", "ปวดหลังท่อนล่างครับ")],
 ["szyja", "ramię (bark)", "masaż"], []),

("A1", "brzuch", "tháwng", "ท้อง", CAT, SUB, 5, "n",
 "„pùat tháwng” to jedna z najczęstszych skarg turysty. To samo słowo w innym kontekście znaczy „być w ciąży”.",
 "",
 [("Boli mnie brzuch.", "pùat tháwng khráp", "ปวดท้องครับ"),
  ("Mam rozstrój żołądka.", "tháwng sǐa khráp", "ท้องเสียครับ"),
  ("Boli mnie brzuch od wczoraj.", "pùat tháwng tâng-tàe mûea-waan khráp", "ปวดท้องตั้งแต่เมื่อวานครับ")],
 ["serce", "biegunka", "ból"], ["żołądek"]),

("A2", "serce", "hǔa jai", "หัวใจ", CAT, SUB, 4, "n",
 "Dosłownie „głowa serca”. Samo „jai” to serce w znaczeniu przenośnym i wchodzi w dziesiątki wyrażeń: „jai dii” (dobry), „jai yen” (spokojny).",
 "głowa serca",
 [("Mam problem z sercem.", "phǒm mii pan-hǎa hǔa jai khráp", "ผมมีปัญหาหัวใจครับ"),
  ("Serce bije szybko.", "hǔa jai tên reo khráp", "หัวใจเต้นเร็วครับ")],
 ["brzuch", "krew", "lekarz"], []),

("A2", "skóra", "phǐu nǎng", "ผิวหนัง", CAT, SUB, 3, "n",
 "„phǐu” to sama powierzchnia skóry i tego słowa użyjesz przy kosmetykach; „nǎng” to skóra jako materia, także skóra wyprawiona.",
 "",
 [("Mam wysypkę na skórze.", "mii phùen thîi phǐu nǎng khráp", "มีผื่นที่ผิวหนังครับ"),
  ("Moja skóra jest sucha.", "phǐu phǒm hâeng khráp", "ผิวผมแห้งครับ")],
 ["wysypka", "słońce"], []),

("A2", "kość", "krà-dùuk", "กระดูก", CAT, SUB, 3, "n",
 "Potrzebne przy zgłaszaniu złamania. Samogłoska w drugiej sylabie długa, końcowe „k” niezwolnione.",
 "",
 [("Chyba złamałem kość.", "phǒm khít wâa krà-dùuk hàk khráp", "ผมคิดว่ากระดูกหักครับ"),
  ("Potrzebuję prześwietlenia.", "phǒm tâwng èks-ree khráp", "ผมต้องเอกซเรย์ครับ")],
 ["ramię (przedramię)", "kolano", "złamać"], []),

("A2", "mięsień", "klâam núea", "กล้ามเนื้อ", CAT, SUB, 3, "n",
 "Przydatne po siłowni i przy masażu — „pùat klâam núea” to zakwasy.",
 "",
 [("Mam zakwasy.", "pùat klâam núea khráp", "ปวดกล้ามเนื้อครับ"),
  ("Naciągnąłem mięsień.", "klâam núea phlèet khráp", "กล้ามเนื้อเพล็ดครับ")],
 ["kość", "masaż", "plecy"], []),

("A2", "twarz", "nâa", "หน้า", CAT, SUB, 4, "n",
 "To samo słowo znaczy „przód” i „następny”: „nâa ráan” to front sklepu, „aa-thít nâa” to przyszły tydzień. Kontekst rozstrzyga.",
 "",
 [("Umyj twarz.", "láang nâa khráp", "ล้างหน้าครับ"),
  ("Jesteś blady.", "khun nâa sìit khráp", "คุณหน้าซีดครับ")],
 ["głowa", "oko", "nos"], []),

("A2", "włosy", "phǒm", "ผม", CAT, SUB, 4, "n",
 "To samo słowo, którym mężczyzna mówi o sobie „ja”. Zdanie „phǒm tàt phǒm” znaczy „obciąłem włosy” i nie jest pomyłką.",
 "",
 [("Chciałbym obciąć włosy.", "phǒm yàak tàt phǒm khráp", "ผมอยากตัดผมครับ"),
  ("Moje włosy są długie.", "phǒm phǒm yaao khráp", "ผมผมยาวครับ")],
 ["głowa", "fryzjer"], []),

("A2", "krwawić", "lûeat àwk", "เลือดออก", CAT, SUB, 3, "n",
 "Dosłownie „krew wychodzi”. Konstrukcja tajska używa czasownika ruchu tam, gdzie polski ma osobny wyraz.",
 "krew wychodzić",
 [("Krwawi mi z nosa.", "lûeat àwk jà-mùuk khráp", "เลือดออกจมูกครับ"),
  ("Rana krwawi.", "phlǎe lûeat àwk khráp", "แผลเลือดออกครับ")],
 ["rana", "skóra"], []),

("A2", "rana", "phlǎe", "แผล", CAT, SUB, 3, "n",
 "Jedna sylaba z tonem rosnącym i zbitką „phl” — ćwicz powoli. Potrzebne w aptece.",
 "",
 [("Mam ranę na nodze.", "mii phlǎe thîi khǎa khráp", "มีแผลที่ขาครับ"),
  ("Poproszę plaster na ranę.", "khǎw pláas-tôoe pìt phlǎe khráp", "ขอพลาสเตอร์ปิดแผลครับ")],
 ["krwawić", "kolano", "skóra"], []),

("A2", "oddychać", "hǎai jai", "หายใจ", "Czasowniki", SUB, 3, "n",
 "Dosłownie „ginie serce”. Przy problemach z oddychaniem: „hǎai jai mâi àwk” — nie mogę złapać tchu.",
 "znikać serce",
 [("Nie mogę złapać tchu.", "hǎai jai mâi àwk khráp", "หายใจไม่ออกครับ"),
  ("Proszę oddychać głęboko.", "hǎai jai lúek lúek khráp", "หายใจลึกๆครับ")],
 ["serce", "gardło"], []),
]
