# -*- coding: utf-8 -*-
"""Sesja N — LUDZIE I RODZINA, SMALL TALK, PODSTAWY I GRZECZNOŚĆ, PYTANIA.

Cztery kategorie, w których baza miała najgorszy stosunek haseł do rekordów:
Pytania 11 haseł na 429 rekordów, Podstawy 28 na 521, Small talk 30 na 525.
Uczący się miał setki gotowych pytań i jedenaście cegiełek do zbudowania
własnego. Ta partia odwraca proporcję.

Krotka: (poziom, polski, fonetyka, pismo, podkategoria, częstość, typ,
         kategoria, uwaga, dosłownie)
"""

LR = "Ludzie i rodzina"
ST = "Small talk"
PG = "Podstawy i grzeczność"
PY = "Pytania"

PEOPLE = [

# ============================================================ RODZINA
("A1", "rodzice", "phâw mâe", "พ่อแม่", "Rodzina", 5, "n", LR,
 "Tajski składa rodziców z ojca i matki — nie ma osobnego wyrazu.", "ojciec matka"),
("A1", "dziecko (potomek)", "lûuk", "ลูก", "Rodzina", 5, "n", LR,
 "Uwaga na różnicę: lûuk to własne dziecko, dèk to dziecko jako mały człowiek.", ""),
("A1", "syn", "lûuk chaai", "ลูกชาย", "Rodzina", 4, "n", LR,
 "chaai to męski — ta sama końcówka co w phûu chaai.", "dziecko mężczyzna"),
("A1", "córka", "lûuk sǎao", "ลูกสาว", "Rodzina", 4, "n", LR,
 "sǎao to młoda kobieta.", "dziecko dziewczyna"),
("A1", "starszy brat lub siostra", "phîi", "พี่", "Rodzina", 5, "n", LR,
 "Kluczowe słowo kultury: używa się go też do obcych trochę starszych od nas. Grzeczniej niż khun.", ""),
("A1", "młodszy brat lub siostra", "náwng", "น้อง", "Rodzina", 5, "n", LR,
 "Tak zwraca się do kelnera i do sprzedawcy młodszego od nas.", ""),
("A1", "starszy brat", "phîi chaai", "พี่ชาย", "Rodzina", 4, "n", LR,
 "Tajski koduje kolejność urodzenia, nie samą płeć — inaczej niż polski.", "starszy mężczyzna"),
("A1", "starsza siostra", "phîi sǎao", "พี่สาว", "Rodzina", 4, "n", LR,
 "", "starszy dziewczyna"),
("A1", "młodszy brat", "náwng chaai", "น้องชาย", "Rodzina", 4, "n", LR,
 "", "młodszy mężczyzna"),
("A1", "młodsza siostra", "náwng sǎao", "น้องสาว", "Rodzina", 4, "n", LR,
 "", "młodszy dziewczyna"),
("A2", "wnuk, wnuczka", "lǎan", "หลาน", "Rodzina", 3, "n", LR,
 "To samo słowo znaczy też siostrzeniec i bratanek — pokrewieństwo w dół, bez różnicowania.", ""),
("A2", "teść, teściowa", "phâw taa", "พ่อตา", "Rodzina", 2, "n", LR,
 "Dosłownie „ojciec oka” — od strony żony. Teściowa to mâe yaai.", "ojciec oko"),
("A2", "zięć, synowa", "lûuk khǒoei", "ลูกเขย", "Rodzina", 2, "n", LR,
 "Synowa to lûuk sà-phái.", "dziecko zięć"),
("A2", "krewny", "yâat", "ญาติ", "Rodzina", 3, "n", LR,
 "phîi náwng yâat to szeroko rozumiana rodzina.", ""),
("A2", "małżeństwo, ślub", "tàeng ngaan", "แต่งงาน", "Rodzina", 4, "n", LR,
 "Dosłownie „ozdobić uroczystość”. Działa też jako czasownik.", "ozdabiać uroczystość"),
("A2", "rozwód", "yàa", "หย่า", "Rodzina", 2, "n", LR,
 "Uwaga na trójkę: yàa (rozwód), yaa (lek), yâa (trawa).", ""),
("A2", "ciąża", "tâng khan", "ตั้งครรภ์", "Rodzina", 2, "n", LR,
 "Potocznie mówi się mii tháwng — „mieć brzuch”.", "ustanawiać płód"),
("B1", "wychowywać", "líang duu", "เลี้ยงดู", "Rodzina", 2, "v", LR,
 "líang samo znaczy też karmić i postawić komuś jedzenie.", "karmić patrzeć"),
("B1", "adoptować", "ráp líang", "รับเลี้ยง", "Rodzina", 2, "v", LR,
 "", "przyjmować wychowywać"),

# ============================================================ LUDZIE
("A1", "mężczyzna", "phûu chaai", "ผู้ชาย", "Ludzie", 5, "n", LR,
 "phûu- to przedrostek osoby; z chaai daje mężczyznę, z yǐng kobietę.", "osoba męski"),
("A1", "kobieta", "phûu yǐng", "ผู้หญิง", "Ludzie", 5, "n", LR,
 "", "osoba żeński"),
("A1", "chłopiec", "dèk phûu chaai", "เด็กผู้ชาย", "Ludzie", 3, "n", LR,
 "", "dziecko osoba męski"),
("A1", "dziewczynka", "dèk phûu yǐng", "เด็กผู้หญิง", "Ludzie", 3, "n", LR,
 "", "dziecko osoba żeński"),
("A2", "nastolatek", "wai rûn", "วัยรุ่น", "Ludzie", 3, "n", LR,
 "wai to wiek jako etap życia.", "wiek pokolenie"),
("A2", "dorosły", "phûu yài", "ผู้ใหญ่", "Ludzie", 4, "n", LR,
 "Także „osoba ważna, zwierzchnik” — znaczenie zależy od kontekstu.", "osoba duży"),
("A2", "osoba starsza", "phûu sǔung aa-yú", "ผู้สูงอายุ", "Ludzie", 3, "n", LR,
 "Forma grzeczna; khon kàe jest neutralna, ale bywa odebrana szorstko.", "osoba wysoki wiek"),
("A2", "sąsiad", "phûean bâan", "เพื่อนบ้าน", "Ludzie", 3, "n", LR,
 "phûean to przyjaciel, kolega.", "przyjaciel dom"),
("A2", "znajomy", "khon rúu-jàk", "คนรู้จัก", "Ludzie", 3, "n", LR,
 "rúu-jàk to znać kogoś — inne słowo niż rúu (wiedzieć).", "człowiek znać"),
("A2", "obcy, nieznajomy", "khon plàek nâa", "คนแปลกหน้า", "Ludzie", 2, "n", LR,
 "Dosłownie „człowiek o dziwnej twarzy”.", "człowiek dziwny twarz"),
("A2", "gość", "khàek", "แขก", "Ludzie", 4, "n", LR,
 "Także mieszkaniec Azji Południowej — znaczenie historyczne, dziś bywa odbierane jako niegrzeczne.", ""),
("A2", "gospodarz", "jâo bâan", "เจ้าบ้าน", "Ludzie", 2, "n", LR,
 "jâo to właściciel, pan czegoś.", "pan dom"),
("A2", "właściciel", "jâo khǎwng", "เจ้าของ", "Ludzie", 4, "n", LR,
 "", "pan rzecz"),
("A2", "cudzoziemiec", "chaao tàang châat", "ชาวต่างชาติ", "Ludzie", 3, "n", LR,
 "Neutralne. fà-ràng dotyczy tylko białych i jest potoczne.", "mieszkaniec obcy naród"),
("A2", "Tajowie, Tajka, Taj", "khon thai", "คนไทย", "Ludzie", 5, "n", LR,
 "Wzorzec khon + nazwa kraju działa dla każdej narodowości: khon pohlaen.", "człowiek Tajlandia"),
("A2", "Polak, Polka", "khon pohlaen", "คนโปแลนด์", "Ludzie", 4, "n", LR,
 "Zapożyczenie z angielskiego Poland.", "człowiek Polska"),
("A2", "mnich", "phrá", "พระ", "Ludzie", 4, "n", LR,
 "Kobieta nie powinna podawać mnichowi rzeczy do ręki ani go dotykać — kładzie przedmiot obok.", ""),
("A2", "para (dwoje ludzi)", "khûu rák", "คู่รัก", "Ludzie", 3, "n", LR,
 "rák to kochać.", "para kochać"),
("A2", "przyjaciółka, dziewczyna", "faen", "แฟน", "Ludzie", 5, "n", LR,
 "Jedno słowo na chłopaka i dziewczynę, bez różnicowania płci. Z angielskiego fan.", ""),
("B1", "samotny, singiel", "sòot", "โสด", "Ludzie", 3, "adj", LR,
 "Odpowiedź na bardzo częste pytanie „mii faen rǔe yang”.", ""),

# ============================================================ SMALL TALK
("A1", "rozmawiać, gawędzić", "khui", "คุย", "Rozmowa", 5, "v", ST,
 "Lżejsze niż phûut — mówi się o rozmowie dla przyjemności.", ""),
("A2", "opowiadać", "lâo", "เล่า", "Rozmowa", 4, "v", ST,
 "lâo rûeang — opowiadać historię.", ""),
("A2", "historia, sprawa", "rûeang", "เรื่อง", "Rozmowa", 5, "n", ST,
 "Bardzo produktywne: temat, sprawa, film, kłopot. rûeang à-rai — o co chodzi.", ""),
("A2", "temat", "hǔa khâw", "หัวข้อ", "Rozmowa", 3, "n", ST,
 "", "głowa punkt"),
("A2", "żart", "múk", "มุก", "Rozmowa", 3, "n", ST,
 "lên múk — żartować. Dosłownie „perła”.", ""),
("A2", "śmiać się", "hǔa ráw", "หัวเราะ", "Rozmowa", 4, "v", ST,
 "", ""),
("A2", "uśmiechać się", "yím", "ยิ้ม", "Rozmowa", 4, "v", ST,
 "Kraj bywa nazywany „krajem uśmiechu” — ale uśmiech bywa też sygnałem zakłopotania.", ""),
("A2", "żartować", "phûut lên", "พูดเล่น", "Rozmowa", 4, "v", ST,
 "Dosłownie „mówić na zabawę”. Ratuje sytuację po nieudanym żarcie.", "mówić bawić się"),
("A2", "mówić poważnie", "phûut jing", "พูดจริง", "Rozmowa", 3, "v", ST,
 "jing to prawdziwy, naprawdę.", "mówić prawdziwy"),
("A2", "zgadzać się", "hěn dûai", "เห็นด้วย", "Rozmowa", 5, "v", ST,
 "Dosłownie „widzieć razem z”. Zaprzeczenie: mâi hěn dûai.", "widzieć razem"),
("A2", "nie zgadzać się", "mâi hěn dûai", "ไม่เห็นด้วย", "Rozmowa", 4, "v", ST,
 "Wyrażana łagodniej niż po polsku — często poprzedzona uśmiechem.", "nie widzieć razem"),
("A2", "wątpić", "sǒng-sǎi", "สงสัย", "Rozmowa", 4, "v", ST,
 "Także „zastanawiać się, mieć pytanie”: mii à-rai sǒng-sǎi mǎi.", ""),
("A2", "przypuszczać", "khâat wâa", "คาดว่า", "Rozmowa", 3, "v", ST,
 "wâa wprowadza treść myśli — jak polskie „że”.", "szacować że"),
("A2", "obiecywać", "sǎn-yaa", "สัญญา", "Rozmowa", 3, "v", ST,
 "Także rzeczownik: umowa, kontrakt.", ""),
("A2", "zapraszać", "chuan", "ชวน", "Rozmowa", 4, "v", ST,
 "Lżejsze niż chəən; chuan to namówić kogoś, żeby poszedł z nami.", ""),
("A2", "odmawiać", "pà-tì-sèet", "ปฏิเสธ", "Rozmowa", 3, "v", ST,
 "Formalne. W rozmowie odmawia się raczej okrężnie, przez „mâi sà-dùak”.", ""),
("A2", "chwalić", "chom", "ชม", "Rozmowa", 3, "v", ST,
 "Także „oglądać, podziwiać”: chom wiu.", ""),
("A2", "narzekać", "bòn", "บ่น", "Rozmowa", 3, "v", ST,
 "Krótkie i bardzo częste w mowie potocznej.", ""),
("A2", "plotkować", "nin-thaa", "นินทา", "Rozmowa", 2, "v", ST,
 "", ""),
("A2", "przerywać komuś", "phûut sâek", "พูดแทรก", "Rozmowa", 2, "v", ST,
 "sâek to wcisnąć się między.", "mówić wciskać się"),
("A2", "milczeć", "ngîap", "เงียบ", "Rozmowa", 4, "adj", ST,
 "Także „cichy” o miejscu. Nagłosowe ng-.", ""),
("A2", "hałaśliwy", "sǐang dang", "เสียงดัง", "Rozmowa", 4, "adj", ST,
 "dang to głośny i słynny.", "dźwięk głośny"),
("A2", "nudny", "nâa bùea", "น่าเบื่อ", "Opinie", 4, "adj", ST,
 "nâa- przed czasownikiem znaczy „wart tego, żeby”: nâa bùea to „wart znudzenia”.", "wart nudzić"),
("A2", "ciekawy, interesujący", "nâa sǒn-jai", "น่าสนใจ", "Opinie", 5, "adj", ST,
 "sǒn-jai to interesować się — dosłownie „nawlekać serce”.", "wart interesować"),
("A2", "zabawny", "tà-lòk", "ตลก", "Opinie", 4, "adj", ST,
 "Także rzeczownik: komik.", ""),
("A2", "dziwny", "plàek", "แปลก", "Opinie", 4, "adj", ST,
 "Bez negatywnego zabarwienia — po prostu nietypowy.", ""),
("A2", "zwyczajny", "thammádaa", "ธรรมดา", "Opinie", 4, "adj", ST,
 "Bardzo częsta odpowiedź na „jak leci” — znaczy „po staremu”.", ""),
("A2", "przyjemny, miły", "nâa rák", "น่ารัก", "Opinie", 5, "adj", ST,
 "Dosłownie „wart kochania”. Używane szeroko: o ludziach, rzeczach i pomysłach.", "wart kochać"),
("A2", "zajęty", "yûng", "ยุ่ง", "Opinie", 4, "adj", ST,
 "Także „zabałaganiony” i „wtrącać się”: yûng rûeang khon ùen.", ""),
("A2", "wolny (mający czas)", "wâang", "ว่าง", "Opinie", 5, "adj", ST,
 "Ten sam wyraz co „pusty” o pokoju.", ""),
("A2", "zmęczony", "nùeai", "เหนื่อย", "Opinie", 5, "adj", ST,
 "O zmęczeniu fizycznym; senność to ngûang nawn.", ""),
("A2", "senny", "ngûang nawn", "ง่วงนอน", "Opinie", 4, "adj", ST,
 "", "senny spać"),
("A2", "podekscytowany", "tùen tên", "ตื่นเต้น", "Opinie", 3, "adj", ST,
 "tùen to obudzić się; podwojenie daje pobudzenie.", "budzić się napięty"),
("A2", "zaskoczony", "tòk jai", "ตกใจ", "Opinie", 4, "adj", ST,
 "Dosłownie „serce spadło” — cała rodzina uczuć jest w tajskim budowana na jai.", "spaść serce"),
("A2", "wzruszony", "prà-tháp jai", "ประทับใจ", "Opinie", 3, "adj", ST,
 "Dosłownie „odcisnąć się na sercu”.", "odciskać serce"),
("A2", "rozczarowany", "phìt wǎng", "ผิดหวัง", "Opinie", 3, "adj", ST,
 "phìt to błędny, wǎng to nadzieja.", "błędny nadzieja"),
("A2", "zawstydzony", "aai", "อาย", "Opinie", 4, "adj", ST,
 "Kluczowe pojęcie kulturowe — utrata twarzy to sǐa nâa.", ""),
("A2", "zdenerwowany", "kròot", "โกรธ", "Opinie", 4, "adj", ST,
 "Okazywanie złości publicznie jest źle widziane i skuteczne odwrotnie do zamiaru.", ""),
("A2", "spokojny", "jai yen", "ใจเย็น", "Opinie", 5, "adj", ST,
 "Dosłownie „zimne serce”. Największy komplement w tej kulturze; jai ráwn to przeciwieństwo.", "serce zimny"),
("A2", "niecierpliwy", "jai ráwn", "ใจร้อน", "Opinie", 4, "adj", ST,
 "Dosłownie „gorące serce” — zarzut, nie opis temperamentu.", "serce gorący"),
("A2", "hojny", "jai dii", "ใจดี", "Opinie", 5, "adj", ST,
 "Dosłownie „dobre serce” — znaczy raczej „życzliwy” niż „szczodry”.", "serce dobry"),
("B1", "wdzięczny", "sǔeng jai", "ซึ้งใจ", "Opinie", 2, "adj", ST,
 "", "przenikać serce"),
("B1", "tęsknić", "khít thǔeng", "คิดถึง", "Opinie", 5, "v", ST,
 "Dosłownie „myśleć aż do”. Mówi się to znacznie swobodniej niż po polsku — także do znajomych.", "myśleć aż do"),

# ============================================================ GRZECZNOŚĆ
("A1", "przepraszać (kogoś)", "khǎw thôot", "ขอโทษ", "Zwroty grzecznościowe", 5, "v", PG,
 "Ten sam zwrot zaczyna pytanie do obcej osoby — jak polskie „przepraszam pana”.", "prosić kara"),
("A1", "wybaczać", "hâi à-phai", "ให้อภัย", "Zwroty grzecznościowe", 3, "v", PG,
 "", "dawać wybaczenie"),
("A2", "nie ma sprawy", "mâi pen rai", "ไม่เป็นไร", "Zwroty grzecznościowe", 5, "w", PG,
 "Najbardziej tajski zwrot w całym języku: odpowiedź na przeprosiny, na podziękowania i na drobne niepowodzenie.", "nie być co"),
("A2", "proszę bardzo (podając)", "nîi khráp", "นี่ครับ", "Zwroty grzecznościowe", 4, "w", PG,
 "Wypowiadane przy wręczaniu.", "to"),
("A2", "chwileczkę", "sák khrûu", "สักครู่", "Zwroty grzecznościowe", 4, "w", PG,
 "Grzeczniejsze niż raw sàk-khrûu. Także rawsàk pai kàwn.", "około chwila"),
("A2", "z przyjemnością", "yin dii", "ยินดี", "Zwroty grzecznościowe", 4, "w", PG,
 "Także „gratuluję” i „miło mi” przy poznaniu.", "cieszyć się dobry"),
("A2", "gratuluję", "yin dii dûai", "ยินดีด้วย", "Zwroty grzecznościowe", 3, "w", PG,
 "", "cieszyć się razem"),
("A2", "powodzenia", "chôok dii", "โชคดี", "Zwroty grzecznościowe", 4, "w", PG,
 "Także pożegnanie — bliskie polskiemu „trzymaj się”.", "szczęście dobry"),
("A2", "uważaj na siebie", "duu lae tua eeng", "ดูแลตัวเอง", "Zwroty grzecznościowe", 3, "w", PG,
 "tua eeng to „sam siebie”.", "opiekować się siebie"),
("A2", "przeszkadzać", "róp-kuan", "รบกวน", "Zwroty grzecznościowe", 4, "v", PG,
 "Zaczyna grzeczną prośbę: „khǎw róp-kuan nòi” — czy mogę zawracać głowę.", ""),
("A2", "pozwolić", "à-nú-yâat", "อนุญาต", "Zwroty grzecznościowe", 3, "v", PG,
 "Formalne; w rozmowie wystarczy „dâi mǎi”.", ""),
("A2", "zabronione", "hâam", "ห้าม", "Zwroty grzecznościowe", 4, "v", PG,
 "Pierwsze słowo na znakach zakazu.", ""),
("A2", "szanować", "khao-róp", "เคารพ", "Zwroty grzecznościowe", 3, "v", PG,
 "Kluczowe w kontakcie z osobami starszymi i z instytucjami.", ""),
("A2", "kłaniać się (wai)", "wâi", "ไหว้", "Zwroty grzecznościowe", 4, "v", PG,
 "Gest złożonych dłoni. Zasada: młodszy zaczyna, starszy odpowiada. Nie kłaniamy się dzieciom ani obsłudze.", ""),
("A2", "grzeczny", "sù-phâap", "สุภาพ", "Zwroty grzecznościowe", 4, "adj", PG,
 "sù-phâap bù-rùt to pan, sù-phâap sà-trii to pani — napisy na toaletach.", ""),
("A2", "niegrzeczny", "mâi sù-phâap", "ไม่สุภาพ", "Zwroty grzecznościowe", 3, "adj", PG,
 "", "nie grzeczny"),
("B1", "stracić twarz", "sǐa nâa", "เสียหน้า", "Zwroty grzecznościowe", 3, "v", PG,
 "Pojęcie porządkujące większość zachowań grzecznościowych. Publiczna krytyka to jej odebranie.", "tracić twarz"),
("B1", "zachować twarz", "ráksǎa nâa", "รักษาหน้า", "Zwroty grzecznościowe", 2, "v", PG,
 "ráksǎa to chronić, leczyć, utrzymywać.", "chronić twarz"),
("B1", "okazać wdzięczność", "sà-daeng khwaam kà-tan-yuu", "แสดงความกตัญญู", "Zwroty grzecznościowe", 2, "v", PG,
 "kà-tan-yuu to wdzięczność wobec rodziców i nauczycieli — pojęcie mocniejsze niż polskie.", "okazywać wdzięczność"),

# ============================================================ PYTANIA
("A1", "jak? (w jaki sposób)", "yàang rai", "อย่างไร", "Słowa pytające", 4, "w", PY,
 "W mowie skracane do yang ngai. Forma pełna jest książkowa.", "sposób jaki"),
("A1", "jak? (potocznie)", "yang ngai", "ยังไง", "Słowa pytające", 5, "w", PY,
 "To samo co yàang rai, ale tak się faktycznie mówi.", ""),
("A1", "dlaczego?", "tham-mai", "ทำไม", "Słowa pytające", 5, "w", PY,
 "Stoi na początku albo na końcu zdania — obie pozycje poprawne.", ""),
("A1", "kiedy?", "mûea rai", "เมื่อไร", "Słowa pytające", 5, "w", PY,
 "O przyszłości i o przeszłości tak samo — tajski nie odmienia.", "gdy jaki"),
("A1", "kto?", "khrai", "ใคร", "Słowa pytające", 5, "w", PY,
 "Jedna sylaba. Uwaga: to samo słowo znaczy „ktoś” w zdaniu twierdzącym.", ""),
("A1", "czyj?", "khǎwng khrai", "ของใคร", "Słowa pytające", 4, "w", PY,
 "khǎwng to „rzecz” i wskaźnik przynależności.", "rzecz kto"),
("A1", "ile? (o liczbie)", "kìi", "กี่", "Słowa pytające", 5, "w", PY,
 "Zawsze z klasyfikatorem: kìi khon, kìi bai, kìi khuen.", ""),
("A1", "ile? (o cenie)", "thâo rai", "เท่าไร", "Słowa pytające", 5, "w", PY,
 "thâo to „równy, tyle co”.", "równy jaki"),
("A2", "który z nich?", "an nǎi", "อันไหน", "Słowa pytające", 4, "w", PY,
 "an to uniwersalny klasyfikator rzeczy bez własnego klasyfikatora.", "sztuka który"),
("A2", "gdzieś", "thîi nǎi sák thîi", "ที่ไหนสักที่", "Słowa pytające", 2, "w", PY,
 "sák osłabia pytanie do nieokreśloności.", "miejsce który około miejsce"),
("A2", "czy już…?", "rǔe yang", "หรือยัง", "Struktury pytające", 5, "w", PY,
 "Pyta o dokonanie: „kin khâao rǔe yang” — jadłeś już? Odpowiedź: láew albo yang.", "czy jeszcze"),
("A2", "jeszcze nie", "yang", "ยัง", "Struktury pytające", 5, "adv", PY,
 "Samo yang wystarcza za pełną odpowiedź.", ""),
("A2", "czy prawda?", "châi mǎi", "ใช่ไหม", "Struktury pytające", 5, "w", PY,
 "Domyka zdanie, którego jesteśmy prawie pewni — jak polskie „prawda?”.", "tak czy"),
("A2", "czy nie…?", "mâi … rǔe", "ไม่…หรือ", "Struktury pytające", 3, "w", PY,
 "Pytanie z niedowierzaniem.", "nie czy"),
("A2", "czy może…?", "…dâi mǎi", "ได้ไหม", "Struktury pytające", 5, "w", PY,
 "Najważniejsza konstrukcja prośby w całym języku: czasownik plus dâi mǎi.", "móc czy"),
("A2", "albo, czy (w wyborze)", "rǔe", "หรือ", "Struktury pytające", 5, "w", PY,
 "Łączy dwie opcje: chaa rǔe kaa-fae.", ""),
("B1", "co się stało?", "kòoet à-rai khûen", "เกิดอะไรขึ้น", "Struktury pytające", 3, "w", PY,
 "kòoet to rodzić się, zdarzyć się.", "zdarzyć się co wznosić"),
("B1", "po co?", "phûea à-rai", "เพื่ออะไร", "Struktury pytające", 3, "w", PY,
 "phûea to „dla, w celu”.", "dla co"),
("B1", "jak długo?", "naan thâo rai", "นานเท่าไร", "Struktury pytające", 4, "w", PY,
 "naan to długo w czasie.", "długo ile"),
("B1", "jak często?", "bòi khâe nǎi", "บ่อยแค่ไหน", "Struktury pytające", 3, "w", PY,
 "bòi to często; khâe nǎi to „w jakim stopniu”.", "często stopień jaki"),
("B1", "jak daleko?", "klai khâe nǎi", "ไกลแค่ไหน", "Struktury pytające", 4, "w", PY,
 "Uwaga na parę minimalną: klai (daleko) kontra klâi (blisko) — różni je sam ton.", "daleko stopień jaki"),
]
