# -*- coding: utf-8 -*-
"""Sesja F — PODROZ I PIENIADZE: transport, bilety, bank, platnosci.

Uwaga systemowa o pojazdach: „rót” to kazdy pojazd kolowy, a rodzaj
dopowiada drugi czlon — rót mee (autobus miejski), rót tuu (minibus),
rót fai (pociag, doslownie „pojazd ognia”), rót khěn (wozek). Znajac
„rót”, rozpoznaje sie kilkanascie nazw srodkow transportu naraz.
"""

TR = "Transport"
ZP = "Zakupy i pieniądze"

TRAVEL = [

# ---------------------------------------------------------------- pojazdy
("A2", "minibus", "rót tuu", "รถตู้", TR, "Pojazdy", 4, "n",
 "„tuu” to szafa, skrzynia. Główny środek transportu między miastami — tańszy i szybszy niż autobus.",
 "pojazd skrzynia",
 [("Jadę minibusem.", "phǒm nâng rót tuu khráp", "ผมนั่งรถตู้ครับ"),
  ("Gdzie odjeżdża minibus?", "rót tuu àwk thîi nǎi khráp", "รถตู้ออกที่ไหนครับ")],
 ["autobus", "pociąg", "dworzec"], []),

("A2", "pociąg", "rót fai", "รถไฟ", TR, "Pojazdy", 4, "n",
 "Dosłownie „pojazd ognia”. „rót fai fáa” to kolej naziemna BTS w Bangkoku.",
 "pojazd ogień",
 [("Jadę pociągiem.", "phǒm nâng rót fai khráp", "ผมนั่งรถไฟครับ"),
  ("Pociąg jest spóźniony.", "rót fai maa cháa khráp", "รถไฟมาช้าครับ")],
 ["dworzec", "bilet", "spóźnić się"], []),

("A2", "metro", "rót fai tâi din", "รถไฟใต้ดิน", TR, "Pojazdy", 3, "n",
 "Dosłownie „pociąg pod ziemią” — MRT. Naziemne BTS to „rót fai fáa”.",
 "pociąg pod ziemia",
 [("Pojadę metrem.", "phǒm jà nâng rót fai tâi din khráp", "ผมจะนั่งรถไฟใต้ดินครับ"),
  ("Gdzie jest stacja metra?", "sà-thǎa-nii rót fai tâi din yùu nǎi khráp", "สถานีรถไฟใต้ดินอยู่ไหนครับ")],
 ["pociąg", "stacja", "bilet"], []),

("A2", "prom", "ruea khâam fâak", "เรือข้ามฟาก", TR, "Pojazdy", 3, "n",
 "„khâam fâak” to przeprawa na drugi brzeg. Codzienny transport w Bangkoku i na wyspy.",
 "łódź przechodzić brzeg",
 [("O której odpływa prom?", "ruea àwk kìi moong khráp", "เรือออกกี่โมงครับ"),
  ("Prom nie płynie.", "ruea mâi àwk khráp", "เรือไม่ออกครับ")],
 ["łódź", "wyspa", "fala"], []),

("A2", "motocykl-taksówka", "win maw-toe-sai", "วินมอเตอร์ไซค์", TR, "Pojazdy", 4, "p",
 "Kierowcy w pomarańczowych kamizelkach czekają na rogu ulicy. Najszybszy sposób na krótki dystans w korku.",
 "postój motocykl",
 [("Pojadę motocyklem.", "phǒm nâng win khráp", "ผมนั่งวินครับ"),
  ("Ile do końca ulicy?", "sùt sawi thâo-rài khráp", "สุดซอยเท่าไหร่ครับ")],
 ["motocykl", "kask", "taksówka"], []),

("A2", "trójkołowiec", "túk túk", "ตุ๊กตุ๊ก", TR, "Pojazdy", 3, "p",
 "Cenę zawsze ustala się przed wsiadaniem — nie ma taksometru.",
 "",
 [("Ile do świątyni?", "pai wát thâo-rài khráp", "ไปวัดเท่าไหร่ครับ"),
  ("Za drogo, sto batów.", "phaeng pai nùeng ráwi bàat dâai mǎi khráp", "แพงไปหนึ่งร้อยบาทได้ไหมครับ")],
 ["taksówka", "targować się", "cena"], ["tuk tuk"]),

("A2", "wypożyczać (pojazd)", "châo rót", "เช่ารถ", TR, "Podróż", 3, "n",
 "Ten sam czasownik co przy wynajmie mieszkania. Zwykle wymagany jest paszport jako zastaw.",
 "wynajmować pojazd",
 [("Chcę wypożyczyć motocykl.", "phǒm yàak châo maw-toe-sai khráp", "ผมอยากเช่ามอเตอร์ไซค์ครับ"),
  ("Ile za dzień?", "wan lá thâo-rài khráp", "วันละเท่าไหร่ครับ")],
 ["wynajmować (mieszkanie)", "motocykl", "paszport"], []),

("A2", "prawo jazdy", "bai khàp khìi", "ใบขับขี่", TR, "Podróż", 3, "f",
 "Policja kontroluje je regularnie przy wypożyczonych motocyklach. Wymagane jest międzynarodowe.",
 "arkusz prowadzić jeździć",
 [("Mam prawo jazdy.", "phǒm mii bai khàp khìi khráp", "ผมมีใบขับขี่ครับ"),
  ("Proszę o prawo jazdy.", "khǎw duu bai khàp khìi khráp", "ขอดูใบขับขี่ครับ")],
 ["prowadzić", "policja", "dokument"], []),

("A2", "korek uliczny", "rót tìt", "รถติด", TR, "Podróż", 4, "n",
 "Dosłownie „pojazdy przyklejone”. Najczęstsze wyjaśnienie spóźnienia w Bangkoku.",
 "pojazd przyklejony",
 [("Jest korek.", "rót tìt khráp", "รถติดครับ"),
  ("Spóźnię się przez korek.", "phǒm jà cháa phráw rót tìt khráp", "ผมจะช้าเพราะรถติดครับ")],
 ["spóźnić się", "ulica", "ponieważ"], []),

("A2", "bilet powrotny", "tǔa pai klàp", "ตั๋วไปกลับ", TR, "Podróż", 3, "n",
 "„pai klàp” to „tam i z powrotem”. Bilet w jedną stronę to „tǔa thîao diao”.",
 "bilet iść wracać",
 [("Poproszę bilet powrotny.", "khǎw tǔa pai klàp khráp", "ขอตั๋วไปกลับครับ"),
  ("W jedną stronę, proszę.", "tǔa thîao diao khráp", "ตั๋วเที่ยวเดียวครับ")],
 ["bilet", "wracać", "podróżować"], []),

("A2", "peron", "chaan chaa-laa", "ชานชาลา", TR, "Podróż", 2, "f",
 "Słowo formalne, spotykane na dworcach kolejowych i w komunikatach.",
 "",
 [("Z którego peronu?", "chaan chaa-laa nǎi khráp", "ชานชาลาไหนครับ"),
  ("Peron numer trzy.", "chaan chaa-laa thîi sǎam khráp", "ชานชาลาที่สามครับ")],
 ["pociąg", "dworzec", "trzeci"], []),

("A2", "bagaż", "sǎm-phaa", "สัมภาระ", TR, "Podróż", 3, "f",
 "Formalne, używane na lotnisku. Potocznie mówi się po prostu „krà-pǎo”.",
 "",
 [("Gdzie odbiór bagażu?", "ráp sǎm-phaa thîi nǎi khráp", "รับสัมภาระที่ไหนครับ"),
  ("Zgubiono mój bagaż.", "krà-pǎo phǒm hǎai khráp", "กระเป๋าผมหายครับ")],
 ["torebka", "lotnisko", "gubić"], []),

("A2", "opóźnienie", "lâa cháa", "ล่าช้า", TR, "Podróż", 3, "f",
 "Słowo z komunikatów lotniskowych i kolejowych. Potocznie: „maa cháa”.",
 "opóźniony wolny",
 [("Lot jest opóźniony.", "thîao bin lâa cháa khráp", "เที่ยวบินล่าช้าครับ"),
  ("O ile opóźniony?", "cháa kìi chûa-moong khráp", "ช้ากี่ชั่วโมงครับ")],
 ["samolot", "spóźnić się", "wolno"], []),

("A2", "odprawa", "chék-in", "เช็คอิน", TR, "Podróż", 3, "n",
 "Zapożyczenie z angielskiego, stosowane i na lotnisku, i w hotelu.",
 "",
 [("Gdzie jest odprawa?", "chék-in thîi nǎi khráp", "เช็คอินที่ไหนครับ"),
  ("O której odprawa w hotelu?", "chék-in kìi moong khráp", "เช็คอินกี่โมงครับ")],
 ["lotnisko", "hotel", "bagaż"], []),

("A2", "wiza", "wii-sâa", "วีซ่า", TR, "Podróż", 4, "f",
 "„tàw wii-sâa” to przedłużyć wizę — sprawa załatwiana w biurze imigracyjnym.",
 "",
 [("Muszę przedłużyć wizę.", "phǒm tâwng tàw wii-sâa khráp", "ผมต้องต่อวีซ่าครับ"),
  ("Wiza kończy się w przyszłym miesiącu.", "wii-sâa mòt duean nâa khráp", "วีซ่าหมดเดือนหน้าครับ")],
 ["paszport", "urząd", "dokument"], []),

("A2", "granica", "chaai daen", "ชายแดน", TR, "Podróż", 2, "f",
 "„pai chaai daen” to wyjazd na granicę w celu odnowienia wizy — praktyka znana jako border run.",
 "brzeg terytorium",
 [("Jadę na granicę.", "phǒm pai chaai daen khráp", "ผมไปชายแดนครับ"),
  ("Granica jest zamknięta.", "chaai daen pìt khráp", "ชายแดนปิดครับ")],
 ["wiza", "kraj", "zamknięty"], []),

# ----------------------------------------------------------------- pieniadze
("A2", "gotówka", "ngoen sòt", "เงินสด", ZP, "Pieniądze", 4, "n",
 "„sòt” to to samo „świeży” co przy jedzeniu. Wiele straganów przyjmuje wyłącznie gotówkę.",
 "pieniądze świeży",
 [("Płacę gotówką.", "phǒm jàai ngoen sòt khráp", "ผมจ่ายเงินสดครับ"),
  ("Tylko gotówka.", "ráp tàe ngoen sòt khráp", "รับแต่เงินสดครับ")],
 ["karta", "płacić", "świeży"], []),

("A2", "karta płatnicza", "bàt khree-dìt", "บัตรเครดิต", ZP, "Pieniądze", 4, "n",
 "„bàt” to każda karta: bàt prà-jam tua (dowód), bàt thoo-rá-sàp (karta telefoniczna).",
 "karta kredyt",
 [("Czy mogę zapłacić kartą?", "jàai bàt dâai mǎi khráp", "จ่ายบัตรได้ไหมครับ"),
  ("Karta nie działa.", "bàt chái mâi dâai khráp", "บัตรใช้ไม่ได้ครับ")],
 ["gotówka", "płacić", "bank"], ["karta"]),

("A2", "bankomat", "tûu ee-thii-em", "ตู้เอทีเอ็ม", ZP, "Pieniądze", 4, "n",
 "„tûu” to szafka, automat: tûu yen (lodówka), tûu nám (automat z wodą).",
 "szafka bankomat",
 [("Gdzie jest bankomat?", "tûu ee-thii-em yùu nǎi khráp", "ตู้เอทีเอ็มอยู่ไหนครับ"),
  ("Bankomat nie działa.", "tûu ee-thii-em sǐa khráp", "ตู้เอทีเอ็มเสียครับ")],
 ["bank", "pieniądze", "wypłacać"], []),

("A2", "wypłacać (pieniądze)", "thǎwn ngoen", "ถอนเงิน", ZP, "Pieniądze", 3, "n",
 "„thǎwn” znaczy też wycofać. „fàak ngoen” to wpłacić na konto.",
 "wycofać pieniądze",
 [("Chcę wypłacić pieniądze.", "phǒm yàak thǎwn ngoen khráp", "ผมอยากถอนเงินครับ"),
  ("Wpłacę na konto.", "phǒm jà fàak ngoen khráp", "ผมจะฝากเงินครับ")],
 ["bankomat", "bank", "konto"], []),

("A2", "konto bankowe", "ban-chii thá-naa-khaan", "บัญชีธนาคาร", ZP, "Pieniądze", 3, "f",
 "„pòoet ban-chii” to założyć konto — wymaga dokumentu pobytowego.",
 "konto bank",
 [("Chcę założyć konto.", "phǒm yàak pòoet ban-chii khráp", "ผมอยากเปิดบัญชีครับ"),
  ("Jaki numer konta?", "lêek ban-chii à-rai khráp", "เลขบัญชีอะไรครับ")],
 ["bank", "dokument", "wypłacać (pieniądze)"], []),

("A2", "przelew", "oon ngoen", "โอนเงิน", ZP, "Pieniądze", 4, "n",
 "Przelew przez aplikację po numerze telefonu to w Tajlandii standard — częstszy niż karta.",
 "przelewać pieniądze",
 [("Zrobię przelew.", "phǒm jà oon ngoen khráp", "ผมจะโอนเงินครับ"),
  ("Czy mogę przelać?", "oon dâai mǎi khráp", "โอนได้ไหมครับ")],
 ["konto bankowe", "aplikacja", "płacić"], []),

("A2", "reszta", "ngoen thawn", "เงินทอน", ZP, "Pieniądze", 4, "n",
 "„thawn” to wydawać resztę. Uwaga: przy dużym banknocie sprzedawca często nie ma jak wydać.",
 "pieniądze wydawać",
 [("Poproszę resztę.", "khǎw ngoen thawn khráp", "ขอเงินทอนครับ"),
  ("Nie mam wydać.", "mâi mii ngoen thawn khráp", "ไม่มีเงินทอนครับ")],
 ["płacić", "banknot", "drobne"], []),

("A2", "drobne", "sèet sà-taang", "เศษสตางค์", ZP, "Pieniądze", 3, "n",
 "„sà-taang” to setna część bata. W praktyce liczy się monety od jednego bata.",
 "reszta satang",
 [("Mam drobne.", "phǒm mii sèet sà-taang khráp", "ผมมีเศษสตางค์ครับ"),
  ("Czy ma pan drobne?", "mii sèet mǎi khráp", "มีเศษไหมครับ")],
 ["moneta", "reszta", "banknot"], []),

("A2", "banknot", "thá-ná-bàt", "ธนบัตร", ZP, "Pieniądze", 3, "f",
 "Uwaga kulturowa: na banknocie jest wizerunek króla — nie należy na nim stawać ani go niszczyć.",
 "",
 [("Poproszę mniejszy banknot.", "khǎw bai lék kwàa dâai mǎi khráp", "ขอใบเล็กกว่าได้ไหมครับ"),
  ("Mam tylko tysiąc.", "phǒm mii tàe bai lá phan khráp", "ผมมีแต่ใบละพันครับ")],
 ["moneta", "reszta", "tysiąc"], []),

("A2", "moneta", "rǐan", "เหรียญ", ZP, "Pieniądze", 3, "n",
 "„rǐan” to także medal. Monety bat mają nominały 1, 2, 5 i 10.",
 "",
 [("Poproszę monety.", "khǎw rǐan khráp", "ขอเหรียญครับ"),
  ("Automat przyjmuje tylko monety.", "tûu ráp tàe rǐan khráp", "ตู้รับแต่เหรียญครับ")],
 ["banknot", "drobne", "bankomat"], []),

("A2", "kantor", "ráan lâek ngoen", "ร้านแลกเงิน", ZP, "Pieniądze", 3, "n",
 "Kursy w kantorach w mieście są wyraźnie lepsze niż na lotnisku.",
 "sklep wymieniać pieniądze",
 [("Gdzie jest kantor?", "ráan lâek ngoen yùu nǎi khráp", "ร้านแลกเงินอยู่ไหนครับ"),
  ("Jaki kurs?", "àt-traa lâek plìan thâo-rài khráp", "อัตราแลกเปลี่ยนเท่าไหร่ครับ")],
 ["wymieniać", "pieniądze", "bank"], []),

("A2", "opłata", "khâa tham niam", "ค่าธรรมเนียม", ZP, "Pieniądze", 3, "f",
 "„khâa” to przedrostek wszystkich opłat: khâa nám (za wodę), khâa fai (za prąd), khâa châo (czynsz).",
 "koszt opłata",
 [("Czy jest opłata?", "mii khâa tham niam mǎi khráp", "มีค่าธรรมเนียมไหมครับ"),
  ("Opłata wynosi trzydzieści batów.", "khâa tham niam sǎam-sìp bàat khráp", "ค่าธรรมเนียมสามสิบบาทครับ")],
 ["cena", "płacić", "prąd"], []),

("A2", "kaucja", "ngoen mát jam", "เงินมัดจำ", ZP, "Pieniądze", 2, "f",
 "Wymagana przy wynajmie mieszkania i motocykla. Zwykle równowartość jednego lub dwóch czynszów.",
 "pieniądze wiązać zatrzymać",
 [("Ile wynosi kaucja?", "ngoen mát jam thâo-rài khráp", "เงินมัดจำเท่าไหร่ครับ"),
  ("Kaucja jest zwrotna.", "ngoen mát jam khuen dâai khráp", "เงินมัดจำคืนได้ครับ")],
 ["wynajmować (mieszkanie)", "umowa", "oddawać"], []),

("A2", "rachunek za media", "bin khâa nám khâa fai", "บิลค่าน้ำค่าไฟ", ZP, "Pieniądze", 2, "n",
 "Płacone zwykle w sklepie całodobowym — wygodniejsze niż w banku.",
 "rachunek koszt woda koszt prąd",
 [("Muszę zapłacić rachunki.", "phǒm tâwng jàai bin khráp", "ผมต้องจ่ายบิลครับ"),
  ("Płacę w sklepie.", "phǒm jàai thîi ráan sà-dùak sûe khráp", "ผมจ่ายที่ร้านสะดวกซื้อครับ")],
 ["prąd", "woda", "płacić"], []),

("A2", "oszczędzać (pieniądze)", "kèp ngoen", "เก็บเงิน", ZP, "Pieniądze", 3, "n",
 "Ten sam „kèp” co „schować, pozbierać” — pieniądze się odkłada, czyli chowa.",
 "chować pieniądze",
 [("Oszczędzam na podróż.", "phǒm kèp ngoen pai thîao khráp", "ผมเก็บเงินไปเที่ยวครับ"),
  ("Trzeba oszczędzać.", "tâwng kèp ngoen khráp", "ต้องเก็บเงินครับ")],
 ["podnosić z ziemi", "pieniądze", "podróżować"], []),

("A2", "drogi (kosztowny)", "phaeng", "แพง", ZP, "Pieniądze", 5, "n",
 "„phaeng pai” to „za drogo” — otwarcie negocjacji na targu. W sklepie sieciowym nie negocjuje się.",
 "",
 [("Za drogo.", "phaeng pai khráp", "แพงไปครับ"),
  ("Czy może być taniej?", "lót dâai mǎi khráp", "ลดได้ไหมครับ")],
 ["tani", "targować się", "cena"], []),
]
