# -*- coding: utf-8 -*-
"""Wzorce zdaniowe etapu 3 (A2) — czesc C: konstrukcje rzeczownikowe.

Biale listy dobrane pod konstrukcje: wzorzec „… sie zepsul" obejmuje wylacznie
urzadzenia, wzorzec „Zostawilem … w pokoju" — rzeczy przenosne, a wzorzec
„Jak dlugo stad do …" — miejsca.

Pozycja: (polskie haslo rekordu, polskie haslo bazowe, polski przyklad)
"""

TPL_C = [

# =====================================================================
# haa … yuu — „szukam"
# =====================================================================
dict(key="HAAYUU", ty="sentence", cat="Awarie i pomoc", sub="Poszukiwanie", reg="n",
     ph="phǒm hǎa {ph} yùu khráp", th="ผมหา{th}อยู่ครับ",
     lit="hǎa … yùu = jestem w trakcie szukania",
     note="Klamra „… yùu” pokazuje, że czynność właśnie trwa — dlatego brzmi to jak prośba o pomoc.",
     ex_ph="hǎa {ph} yùu rǔe khráp", ex_th="หา{th}อยู่หรือครับ",
     items=[
       ("Szukam ręcznika.", "ręcznik", "Szukasz ręcznika?"),
       ("Szukam koca.", "koc", "Szukasz koca?"),
       ("Szukam poduszki.", "poduszka", "Szukasz poduszki?"),
       ("Szukam klucza.", "klucz", "Szukasz klucza?"),
       ("Szukam mydła.", "mydło", "Szukasz mydła?"),
       ("Szukam papieru toaletowego.", "papier toaletowy", "Szukasz papieru toaletowego?"),
       ("Szukam ładowarki.", "ładowarka", "Szukasz ładowarki?"),
       ("Szukam karty SIM.", "karta SIM", "Szukasz karty SIM?"),
       ("Szukam telefonu.", "telefon", "Szukasz telefonu?"),
       ("Szukam walizki.", "walizka", "Szukasz walizki?"),
       ("Szukam torby.", "torba", "Szukasz torby?"),
       ("Szukam mapy.", "mapa", "Szukasz mapy?"),
       ("Szukam karty dań.", "menu", "Szukasz karty dań?"),
       ("Szukam paragonu.", "paragon", "Szukasz paragonu?"),
       ("Szukam bankomatu.", "bankomat", "Szukasz bankomatu?"),
       ("Szukam kantoru.", "kantor", "Szukasz kantoru?"),
       ("Szukam apteki.", "apteka", "Szukasz apteki?"),
       ("Szukam lekarstwa.", "lek", "Szukasz lekarstwa?"),
       ("Szukam plastra.", "plaster", "Szukasz plastra?"),
       ("Szukam butów.", "buty", "Szukasz butów?"),
       ("Szukam koszulki.", "koszulka", "Szukasz koszulki?"),
       ("Szukam spodni.", "spodnie", "Szukasz spodni?"),
       ("Szukam kapelusza.", "kapelusz", "Szukasz kapelusza?"),
       ("Szukam kremu z filtrem.", "krem z filtrem", "Szukasz kremu z filtrem?"),
       ("Szukam pamiątki.", "pamiątka", "Szukasz pamiątki?"),
       ("Szukam biletu.", "bilet", "Szukasz biletu?"),
       ("Szukam paszportu.", "paszport", "Szukasz paszportu?"),
       ("Szukam kasku.", "kask", "Szukasz kasku?"),
       ("Szukam toalety.", "toaleta", "Szukasz toalety?"),
       ("Szukam pralni.", "pralnia", "Szukasz pralni?"),
     ]),

# =====================================================================
# tawng-kaan — „potrzebuje"
# =====================================================================
dict(key="TAWNGKAAN", ty="sentence", cat="Awarie i pomoc", sub="Prośby", reg="f",
     ph="phǒm tâwng-kaan {ph} khráp", th="ผมต้องการ{th}ครับ",
     lit="tâwng-kaan = potrzebować (oficjalnie)",
     note="Ton urzędowy. W rozmowie na targu naturalniejsze jest „khǎw … nòi”.",
     ex_ph="tâwng-kaan {ph} kìi an khráp", ex_th="ต้องการ{th}กี่อันครับ",
     items=[
       ("Potrzebuję ręcznika.", "ręcznik", "Ile ręczników pan potrzebuje?"),
       ("Potrzebuję koca.", "koc", "Ile koców pan potrzebuje?"),
       ("Potrzebuję poduszki.", "poduszka", "Ile poduszek pan potrzebuje?"),
       ("Potrzebuję pościeli.", "pościel", "Ile kompletów pan potrzebuje?"),
       ("Potrzebuję klucza.", "klucz", "Ile kluczy pan potrzebuje?"),
       ("Potrzebuję mydła.", "mydło", "Ile mydeł pan potrzebuje?"),
       ("Potrzebuję ładowarki.", "ładowarka", "Ile ładowarek pan potrzebuje?"),
       ("Potrzebuję karty SIM.", "karta SIM", "Ile kart pan potrzebuje?"),
       ("Potrzebuję mapy.", "mapa", "Ile map pan potrzebuje?"),
       ("Potrzebuję talerza.", "talerz", "Ile talerzy pan potrzebuje?"),
       ("Potrzebuję szklanki.", "szklanka", "Ile szklanek pan potrzebuje?"),
       ("Potrzebuję łyżki.", "łyżka", "Ile łyżek pan potrzebuje?"),
       ("Potrzebuję widelca.", "widelec", "Ile widelców pan potrzebuje?"),
       ("Potrzebuję noża.", "nóż", "Ile noży pan potrzebuje?"),
       ("Potrzebuję serwetki.", "serwetka", "Ile serwetek pan potrzebuje?"),
       ("Potrzebuję paragonu.", "paragon", "Ile paragonów pan potrzebuje?"),
       ("Potrzebuję lekarstwa.", "lek", "Ile opakowań pan potrzebuje?"),
       ("Potrzebuję leku przeciwbólowego.", "lek przeciwbólowy", "Ile opakowań pan potrzebuje?"),
       ("Potrzebuję plastra.", "plaster", "Ile plastrów pan potrzebuje?"),
       ("Potrzebuję bandaża.", "bandaż", "Ile bandaży pan potrzebuje?"),
       ("Potrzebuję ubezpieczenia.", "ubezpieczenie", "Na ile dni pan potrzebuje?"),
       ("Potrzebuję biletu.", "bilet", "Ile biletów pan potrzebuje?"),
       ("Potrzebuję wizy.", "wiza", "Na ile dni pan potrzebuje?"),
       ("Potrzebuję kasku.", "kask", "Ile kasków pan potrzebuje?"),
       ("Potrzebuję torby na zakupy.", "torba na zakupy", "Ile toreb pan potrzebuje?"),
     ]),

# =====================================================================
# haa … mai joe — „nie moge znalezc"
# =====================================================================
dict(key="HAAMAIJOE", ty="sentence", cat="Awarie i pomoc", sub="Problemy", reg="n",
     ph="phǒm hǎa {ph} mâi jôe khráp", th="ผมหา{th}ไม่เจอครับ",
     lit="hǎa … mâi jôe = szukam i nie znajduję",
     note="„jôe” znaczy „natknąć się”. Konstrukcja opisuje wynik, nie samą czynność.",
     ex_ph="hǎa {ph} mâi jôe rǔe khráp", ex_th="หา{th}ไม่เจอหรือครับ",
     items=[
       ("Nie mogę znaleźć klucza.", "klucz", "Nie możesz znaleźć klucza?"),
       ("Nie mogę znaleźć telefonu.", "telefon", "Nie możesz znaleźć telefonu?"),
       ("Nie mogę znaleźć ładowarki.", "ładowarka", "Nie możesz znaleźć ładowarki?"),
       ("Nie mogę znaleźć paszportu.", "paszport", "Nie możesz znaleźć paszportu?"),
       ("Nie mogę znaleźć biletu.", "bilet", "Nie możesz znaleźć biletu?"),
       ("Nie mogę znaleźć torby.", "torba", "Nie możesz znaleźć torby?"),
       ("Nie mogę znaleźć walizki.", "walizka", "Nie możesz znaleźć walizki?"),
       ("Nie mogę znaleźć mapy.", "mapa", "Nie możesz znaleźć mapy?"),
       ("Nie mogę znaleźć paragonu.", "paragon", "Nie możesz znaleźć paragonu?"),
       ("Nie mogę znaleźć karty SIM.", "karta SIM", "Nie możesz znaleźć karty SIM?"),
       ("Nie mogę znaleźć okularów przeciwsłonecznych.", "okulary przeciwsłoneczne", "Nie możesz znaleźć okularów?"),
       ("Nie mogę znaleźć butów.", "buty", "Nie możesz znaleźć butów?"),
       ("Nie mogę znaleźć kapelusza.", "kapelusz", "Nie możesz znaleźć kapelusza?"),
       ("Nie mogę znaleźć hotelu.", "hotel", "Nie możesz znaleźć hotelu?"),
       ("Nie mogę znaleźć przystanku.", "przystanek autobusowy", "Nie możesz znaleźć przystanku?"),
       ("Nie mogę znaleźć bankomatu.", "bankomat", "Nie możesz znaleźć bankomatu?"),
       ("Nie mogę znaleźć toalety.", "toaleta", "Nie możesz znaleźć toalety?"),
       ("Nie mogę znaleźć wyjścia.", "wyjście", "Nie możesz znaleźć wyjścia?"),
       ("Nie mogę znaleźć wejścia.", "wejście", "Nie możesz znaleźć wejścia?"),
       ("Nie mogę znaleźć windy.", "winda", "Nie możesz znaleźć windy?"),
     ]),

# =====================================================================
# tham … haai — „zgubilem"
# =====================================================================
dict(key="THAMHAAI", ty="sentence", cat="Awarie i pomoc", sub="Problemy", reg="n",
     ph="phǒm tham {ph} hǎai khráp", th="ผมทำ{th}หายครับ",
     lit="tham … hǎai = spowodować zniknięcie, czyli zgubić",
     note="Rzeczownik stoi w środku konstrukcji, nie na końcu. To stały schemat tajskiego.",
     ex_ph="tham {ph} hǎai thîi nǎi khráp", ex_th="ทำ{th}หายที่ไหนครับ",
     items=[
       ("Zgubiłem klucz.", "klucz", "Gdzie zgubiłeś klucz?"),
       ("Zgubiłem bilet.", "bilet", "Gdzie zgubiłeś bilet?"),
       ("Zgubiłem torbę.", "torba", "Gdzie zgubiłeś torbę?"),
       ("Zgubiłem walizkę.", "walizka", "Gdzie zgubiłeś walizkę?"),
       ("Zgubiłem ładowarkę.", "ładowarka", "Gdzie zgubiłeś ładowarkę?"),
       ("Zgubiłem kartę SIM.", "karta SIM", "Gdzie zgubiłeś kartę SIM?"),
       ("Zgubiłem kartę kredytową.", "karta kredytowa", "Gdzie zgubiłeś kartę?"),
       ("Zgubiłem okulary przeciwsłoneczne.", "okulary przeciwsłoneczne", "Gdzie zgubiłeś okulary?"),
       ("Zgubiłem kapelusz.", "kapelusz", "Gdzie zgubiłeś kapelusz?"),
       ("Zgubiłem paragon.", "paragon", "Gdzie zgubiłeś paragon?"),
       ("Zgubiłem mapę.", "mapa", "Gdzie zgubiłeś mapę?"),
       ("Zgubiłem prawo jazdy.", "prawo jazdy", "Gdzie zgubiłeś prawo jazdy?"),
       ("Zgubiłem kask.", "kask", "Gdzie zgubiłeś kask?"),
       ("Zgubiłem buty.", "buty", "Gdzie zgubiłeś buty?"),
       ("Zgubiłem pamiątkę.", "pamiątka", "Gdzie zgubiłeś pamiątkę?"),
       ("Zgubiłem lekarstwo.", "lek", "Gdzie zgubiłeś lekarstwo?"),
     ]),

# =====================================================================
# luem … wai nai hawng — „zostawilem w pokoju"
# =====================================================================
dict(key="LUEMWAI", ty="sentence", cat="Hotel", sub="Problemy", reg="n",
     ph="phǒm luem {ph} wái nai hâwng khráp", th="ผมลืม{th}ไว้ในห้องครับ",
     lit="luem … wái = zostawić coś przez zapomnienie",
     note="„wái” dodaje sens „i tam to leży”. Bez niego zdanie znaczy tylko „zapomniałem”.",
     ex_ph="luem {ph} wái nai hâwng rǔe khráp", ex_th="ลืม{th}ไว้ในห้องหรือครับ",
     items=[
       ("Zostawiłem klucz w pokoju.", "klucz", "Zostawiłeś klucz w pokoju?"),
       ("Zostawiłem telefon w pokoju.", "telefon", "Zostawiłeś telefon w pokoju?"),
       ("Zostawiłem ładowarkę w pokoju.", "ładowarka", "Zostawiłeś ładowarkę w pokoju?"),
       ("Zostawiłem paszport w pokoju.", "paszport", "Zostawiłeś paszport w pokoju?"),
       ("Zostawiłem torbę w pokoju.", "torba", "Zostawiłeś torbę w pokoju?"),
       ("Zostawiłem walizkę w pokoju.", "walizka", "Zostawiłeś walizkę w pokoju?"),
       ("Zostawiłem lekarstwo w pokoju.", "lek", "Zostawiłeś lekarstwo w pokoju?"),
       ("Zostawiłem okulary przeciwsłoneczne w pokoju.", "okulary przeciwsłoneczne", "Zostawiłeś okulary w pokoju?"),
       ("Zostawiłem buty w pokoju.", "buty", "Zostawiłeś buty w pokoju?"),
       ("Zostawiłem kapelusz w pokoju.", "kapelusz", "Zostawiłeś kapelusz w pokoju?"),
       ("Zostawiłem ręcznik w pokoju.", "ręcznik", "Zostawiłeś ręcznik w pokoju?"),
       ("Zostawiłem bilet w pokoju.", "bilet", "Zostawiłeś bilet w pokoju?"),
       ("Zostawiłem mapę w pokoju.", "mapa", "Zostawiłeś mapę w pokoju?"),
       ("Zostawiłem kask w pokoju.", "kask", "Zostawiłeś kask w pokoju?"),
       ("Zostawiłem krem z filtrem w pokoju.", "krem z filtrem", "Zostawiłeś krem w pokoju?"),
       ("Zostawiłem pamiątkę w pokoju.", "pamiątka", "Zostawiłeś pamiątkę w pokoju?"),
     ]),

# =====================================================================
# luem ao … maa — „zapomnialem wziac"
# =====================================================================
dict(key="LUEMAO", ty="sentence", cat="Awarie i pomoc", sub="Problemy", reg="n",
     ph="phǒm luem ao {ph} maa khráp", th="ผมลืมเอา{th}มาครับ",
     lit="luem ao … maa = zapomniałem to ze sobą zabrać",
     note="„ao … maa” = wziąć coś ze sobą w tę stronę. „ao … pai” to zabrać w tamtą.",
     ex_ph="luem ao {ph} maa rǔe khráp", ex_th="ลืมเอา{th}มาหรือครับ",
     items=[
       ("Zapomniałem wziąć klucz.", "klucz", "Zapomniałeś wziąć klucz?"),
       ("Zapomniałem wziąć telefon.", "telefon", "Zapomniałeś wziąć telefon?"),
       ("Zapomniałem wziąć ładowarkę.", "ładowarka", "Zapomniałeś wziąć ładowarkę?"),
       ("Zapomniałem wziąć paszport.", "paszport", "Zapomniałeś wziąć paszport?"),
       ("Zapomniałem wziąć bilet.", "bilet", "Zapomniałeś wziąć bilet?"),
       ("Zapomniałem wziąć pieniądze.", "pieniądze", "Zapomniałeś wziąć pieniądze?"),
       ("Zapomniałem wziąć kartę kredytową.", "karta kredytowa", "Zapomniałeś wziąć kartę?"),
       ("Zapomniałem wziąć mapę.", "mapa", "Zapomniałeś wziąć mapę?"),
       ("Zapomniałem wziąć lekarstwo.", "lek", "Zapomniałeś wziąć lekarstwo?"),
       ("Zapomniałem wziąć krem z filtrem.", "krem z filtrem", "Zapomniałeś wziąć krem?"),
       ("Zapomniałem wziąć kapelusz.", "kapelusz", "Zapomniałeś wziąć kapelusz?"),
       ("Zapomniałem wziąć okulary przeciwsłoneczne.", "okulary przeciwsłoneczne", "Zapomniałeś wziąć okulary?"),
       ("Zapomniałem wziąć torbę na zakupy.", "torba na zakupy", "Zapomniałeś wziąć torbę?"),
       ("Zapomniałem wziąć prawo jazdy.", "prawo jazdy", "Zapomniałeś wziąć prawo jazdy?"),
       ("Zapomniałem wziąć kask.", "kask", "Zapomniałeś wziąć kask?"),
       ("Zapomniałem wziąć ręcznik.", "ręcznik", "Zapomniałeś wziąć ręcznik?"),
     ]),

# =====================================================================
# mii … laew — „mam juz"
# =====================================================================
dict(key="MIILAEW", ty="sentence", cat="Gramatyka użytkowa", sub="Posiadanie", reg="n",
     ph="phǒm mii {ph} láew khráp", th="ผมมี{th}แล้วครับ",
     lit="mii … láew = już to mam",
     note="Uprzejmy sposób odmowy sprzedawcy: nie odmawiamy, tylko stwierdzamy fakt.",
     ex_ph="mii {ph} láew rǔe khráp", ex_th="มี{th}แล้วหรือครับ",
     items=[
       ("Mam już bilet.", "bilet", "Masz już bilet?"),
       ("Mam już mapę.", "mapa", "Masz już mapę?"),
       ("Mam już kartę SIM.", "karta SIM", "Masz już kartę SIM?"),
       ("Mam już ładowarkę.", "ładowarka", "Masz już ładowarkę?"),
       ("Mam już ubezpieczenie.", "ubezpieczenie", "Masz już ubezpieczenie?"),
       ("Mam już wizę.", "wiza", "Masz już wizę?"),
       ("Mam już prawo jazdy.", "prawo jazdy", "Masz już prawo jazdy?"),
       ("Mam już kask.", "kask", "Masz już kask?"),
       ("Mam już ręcznik.", "ręcznik", "Masz już ręcznik?"),
       ("Mam już krem z filtrem.", "krem z filtrem", "Masz już krem z filtrem?"),
       ("Mam już torbę na zakupy.", "torba na zakupy", "Masz już torbę?"),
       ("Mam już lekarstwo.", "lek", "Masz już lekarstwo?"),
       ("Mam już plaster.", "plaster", "Masz już plaster?"),
       ("Mam już kapelusz.", "kapelusz", "Masz już kapelusz?"),
       ("Mam już okulary przeciwsłoneczne.", "okulary przeciwsłoneczne", "Masz już okulary?"),
       ("Mam już paragon.", "paragon", "Masz już paragon?"),
       ("Mam już pamiątkę.", "pamiątka", "Masz już pamiątkę?"),
       ("Mam już rower.", "rower", "Masz już rower?"),
     ]),

# =====================================================================
# chuai ao … maa hai noi — „prosze przyniesc"
# =====================================================================
dict(key="AOMAAHAI", ty="phrase", cat="Hotel", sub="Obsługa", reg="n",
     ph="chûai ao {ph} maa hâi nòi khráp", th="ช่วยเอา{th}มาให้หน่อยครับ",
     lit="ao … maa hâi = przynieś to dla mnie",
     note="Najczęstsza prośba w hotelu i restauracji. „hâi” wskazuje, komu przysługa służy.",
     ex_ph="ao {ph} maa hâi kìi an khráp", ex_th="เอา{th}มาให้กี่อันครับ",
     items=[
       ("Proszę przynieść ręcznik.", "ręcznik", "Ile ręczników przynieść?"),
       ("Proszę przynieść koc.", "koc", "Ile koców przynieść?"),
       ("Proszę przynieść poduszkę.", "poduszka", "Ile poduszek przynieść?"),
       ("Proszę przynieść pościel.", "pościel", "Ile kompletów przynieść?"),
       ("Proszę przynieść mydło.", "mydło", "Ile mydeł przynieść?"),
       ("Proszę przynieść papier toaletowy.", "papier toaletowy", "Ile rolek przynieść?"),
       ("Proszę przynieść talerz.", "talerz", "Ile talerzy przynieść?"),
       ("Proszę przynieść szklankę.", "szklanka", "Ile szklanek przynieść?"),
       ("Proszę przynieść kubek.", "kubek", "Ile kubków przynieść?"),
       ("Proszę przynieść łyżkę.", "łyżka", "Ile łyżek przynieść?"),
       ("Proszę przynieść widelec.", "widelec", "Ile widelców przynieść?"),
       ("Proszę przynieść nóż.", "nóż", "Ile noży przynieść?"),
       ("Proszę przynieść serwetkę.", "serwetka", "Ile serwetek przynieść?"),
       ("Proszę przynieść pałeczki.", "pałeczki", "Ile par przynieść?"),
       ("Proszę przynieść kartę dań.", "menu", "Ile kart przynieść?"),
       ("Proszę przynieść rachunek.", "rachunek", "Jeden rachunek czy dwa?"),
       ("Proszę przynieść czajnik.", "czajnik", "Ile czajników przynieść?"),
       ("Proszę przynieść lekarstwo.", "lek", "Ile opakowań przynieść?"),
     ]),

# =====================================================================
# khaw … iik an nueng — „prosze jeszcze jeden"
# =====================================================================
dict(key="KHAWIIK", ty="phrase", cat="Restauracja", sub="Zamawianie", reg="n",
     ph="khǎw {ph} ìik an nùeng khráp", th="ขอ{th}อีกอันหนึ่งครับ",
     lit="ìik an nùeng = jeszcze jedna sztuka",
     note="„an” to zapasowe słowo miarowe. Do butelek użyj „khùat”, do talerzy „jaan”.",
     ex_ph="ao {ph} ìik kìi an khráp", ex_th="เอา{th}อีกกี่อันครับ",
     items=[
       ("Poproszę jeszcze jeden ręcznik.", "ręcznik", "Ile jeszcze ręczników?"),
       ("Poproszę jeszcze jedną poduszkę.", "poduszka", "Ile jeszcze poduszek?"),
       ("Poproszę jeszcze jeden koc.", "koc", "Ile jeszcze koców?"),
       ("Poproszę jeszcze jeden talerz.", "talerz", "Ile jeszcze talerzy?"),
       ("Poproszę jeszcze jedną szklankę.", "szklanka", "Ile jeszcze szklanek?"),
       ("Poproszę jeszcze jeden kubek.", "kubek", "Ile jeszcze kubków?"),
       ("Poproszę jeszcze jedną łyżkę.", "łyżka", "Ile jeszcze łyżek?"),
       ("Poproszę jeszcze jeden widelec.", "widelec", "Ile jeszcze widelców?"),
       ("Poproszę jeszcze jeden nóż.", "nóż", "Ile jeszcze noży?"),
       ("Poproszę jeszcze jedną serwetkę.", "serwetka", "Ile jeszcze serwetek?"),
       ("Poproszę jeszcze jedną kartę dań.", "menu", "Ile jeszcze kart?"),
       ("Poproszę jeszcze jeden klucz.", "klucz", "Ile jeszcze kluczy?"),
       ("Poproszę jeszcze jedno mydło.", "mydło", "Ile jeszcze mydeł?"),
       ("Poproszę jeszcze jeden bilet.", "bilet", "Ile jeszcze biletów?"),
       ("Poproszę jeszcze jedną torbę.", "torba", "Ile jeszcze toreb?"),
       ("Poproszę jeszcze jeden plaster.", "plaster", "Ile jeszcze plastrów?"),
     ]),

# =====================================================================
# khaw plian — „czy moge wymienic"
# =====================================================================
dict(key="PLIANIT", ty="question", cat="Zakupy i pieniądze", sub="Reklamacje", reg="n",
     ph="khǎw plìan {ph} dâai mǎi khráp", th="ขอเปลี่ยน{th}ได้ไหมครับ",
     lit="khǎw plìan … = proszę o wymianę",
     note="„plìan” to wymiana na inny egzemplarz; zwrot pieniędzy to „khuen ngoen”.",
     ex_ph="plìan {ph} mài hâi khráp", ex_th="เปลี่ยน{th}ใหม่ให้ครับ",
     items=[
       ("Czy mogę wymienić ręcznik?", "ręcznik", "Wymienię ręcznik na nowy."),
       ("Czy mogę wymienić poduszkę?", "poduszka", "Wymienię poduszkę na nową."),
       ("Czy mogę wymienić pościel?", "pościel", "Wymienię pościel na nową."),
       ("Czy mogę wymienić klucz?", "klucz", "Wymienię klucz na nowy."),
       ("Czy mogę wymienić koszulkę?", "koszulka", "Wymienię koszulkę na nową."),
       ("Czy mogę wymienić spodnie?", "spodnie", "Wymienię spodnie na nowe."),
       ("Czy mogę wymienić buty?", "buty", "Wymienię buty na nowe."),
       ("Czy mogę wymienić kapelusz?", "kapelusz", "Wymienię kapelusz na nowy."),
       ("Czy mogę wymienić bilet?", "bilet", "Wymienię bilet na nowy."),
       ("Czy mogę wymienić kartę SIM?", "karta SIM", "Wymienię kartę na nową."),
       ("Czy mogę wymienić ładowarkę?", "ładowarka", "Wymienię ładowarkę na nową."),
       ("Czy mogę wymienić talerz?", "talerz", "Wymienię talerz na nowy."),
       ("Czy mogę wymienić szklankę?", "szklanka", "Wymienię szklankę na nową."),
       ("Czy mogę wymienić kask?", "kask", "Wymienię kask na nowy."),
       ("Czy mogę wymienić pokój?", "pokój", "Wymienię pokój na inny."),
       ("Czy mogę wymienić banknot?", "banknot", "Wymienię banknot na inny."),
     ]),

# =====================================================================
# khaw faak … wai — „czy moge zostawic na przechowanie"
# =====================================================================
dict(key="FAAKWAI", ty="question", cat="Hotel", sub="Obsługa", reg="n",
     ph="khǎw fàak {ph} wái dâai mǎi khráp", th="ขอฝาก{th}ไว้ได้ไหมครับ",
     lit="fàak … wái = zostawić coś pod czyjąś opieką",
     note="„fàak” zakłada, że ktoś tego przypilnuje — inaczej niż „thíng”, czyli porzucić.",
     ex_ph="fàak {ph} wái kìi wan khráp", ex_th="ฝาก{th}ไว้กี่วันครับ",
     items=[
       ("Czy mogę zostawić walizkę?", "walizka", "Na ile dni zostawić walizkę?"),
       ("Czy mogę zostawić torbę?", "torba", "Na ile dni zostawić torbę?"),
       ("Czy mogę zostawić klucz?", "klucz", "Na ile dni zostawić klucz?"),
       ("Czy mogę zostawić paszport?", "paszport", "Na ile dni zostawić paszport?"),
       ("Czy mogę zostawić rower?", "rower", "Na ile dni zostawić rower?"),
       ("Czy mogę zostawić motocykl?", "motocykl", "Na ile dni zostawić motocykl?"),
       ("Czy mogę zostawić kask?", "kask", "Na ile dni zostawić kask?"),
       ("Czy mogę zostawić pieniądze w depozycie?", "pieniądze", "Na ile dni zostawić pieniądze?"),
       ("Czy mogę zostawić lekarstwo?", "lek", "Na ile dni zostawić lekarstwo?"),
       ("Czy mogę zostawić pamiątkę?", "pamiątka", "Na ile dni zostawić pamiątkę?"),
       ("Czy mogę zostawić buty?", "buty", "Na ile dni zostawić buty?"),
       ("Czy mogę zostawić kapelusz?", "kapelusz", "Na ile dni zostawić kapelusz?"),
     ]),

# =====================================================================
# chai … dai mai — „czy moge uzyc"
# =====================================================================
dict(key="CHAIDAIMAI", ty="question", cat="Pytania", sub="Prośby", reg="n",
     ph="chái {ph} dâai mǎi khráp", th="ใช้{th}ได้ไหมครับ",
     lit="chái … dâai mǎi = czy wolno tego użyć",
     note="Pyta o pozwolenie, nie o sprawność. O sprawność pytamy „… chái dâai mǎi”.",
     ex_ph="chái {ph} dâai loei khráp", ex_th="ใช้{th}ได้เลยครับ",
     items=[
       ("Czy mogę użyć klimatyzacji?", "klimatyzacja", "Można korzystać z klimatyzacji."),
       ("Czy mogę użyć wentylatora?", "wentylator", "Można korzystać z wentylatora."),
       ("Czy mogę użyć prysznica?", "prysznic", "Można korzystać z prysznica."),
       ("Czy mogę użyć windy?", "winda", "Można korzystać z windy."),
       ("Czy mogę użyć basenu?", "basen", "Można korzystać z basenu."),
       ("Czy mogę użyć lodówki?", "lodówka", "Można korzystać z lodówki."),
       ("Czy mogę użyć pralki?", "pralka", "Można korzystać z pralki."),
       ("Czy mogę użyć czajnika?", "czajnik", "Można korzystać z czajnika."),
       ("Czy mogę użyć kuchni?", "kuchnia", "Można korzystać z kuchni."),
       ("Czy mogę użyć internetu?", "internet", "Można korzystać z internetu."),
       ("Czy mogę użyć wi-fi?", "wi-fi", "Można korzystać z wi-fi."),
       ("Czy mogę użyć telefonu?", "telefon", "Można korzystać z telefonu."),
       ("Czy mogę użyć ładowarki?", "ładowarka", "Można korzystać z ładowarki."),
       ("Czy mogę użyć karty kredytowej?", "karta kredytowa", "Można płacić kartą."),
       ("Czy mogę użyć toalety?", "toaleta", "Można korzystać z toalety."),
       ("Czy mogę użyć roweru?", "rower", "Można korzystać z roweru."),
     ]),

# =====================================================================
# … sia — „zepsul sie"
# =====================================================================
dict(key="SIABROKEN", ty="sentence", cat="Awarie i pomoc", sub="Awarie", reg="n",
     ph="{ph} sǐa khráp", th="{th}เสียครับ",
     lit="sǐa = zepsuty, niesprawny",
     note="„sǐa” dotyczy urządzeń. O jedzeniu powiemy „sǐa” w sensie „zepsute, nieświeże”.",
     ex_ph="{ph} sǐa tâng tàe mûea-rài khráp", ex_th="{th}เสียตั้งแต่เมื่อไหร่ครับ",
     items=[
       ("Klimatyzacja się zepsuła.", "klimatyzacja", "Od kiedy klimatyzacja jest zepsuta?"),
       ("Wentylator się zepsuł.", "wentylator", "Od kiedy wentylator jest zepsuty?"),
       ("Winda się zepsuła.", "winda", "Od kiedy winda jest zepsuta?"),
       ("Prysznic się zepsuł.", "prysznic", "Od kiedy prysznic jest zepsuty?"),
       ("Lodówka się zepsuła.", "lodówka", "Od kiedy lodówka jest zepsuta?"),
       ("Pralka się zepsuła.", "pralka", "Od kiedy pralka jest zepsuta?"),
       ("Czajnik się zepsuł.", "czajnik", "Od kiedy czajnik jest zepsuty?"),
       ("Telefon się zepsuł.", "telefon", "Od kiedy telefon jest zepsuty?"),
       ("Ładowarka się zepsuła.", "ładowarka", "Od kiedy ładowarka jest zepsuta?"),
       ("Zamek w drzwiach się zepsuł.", "drzwi", "Od kiedy drzwi są zepsute?"),
       ("Okno się zepsuło.", "okno", "Od kiedy okno jest zepsute?"),
       ("Światło się zepsuło.", "światło", "Od kiedy światło jest zepsute?"),
       ("Motocykl się zepsuł.", "motocykl", "Od kiedy motocykl jest zepsuty?"),
       ("Rower się zepsuł.", "rower", "Od kiedy rower jest zepsuty?"),
       ("Samochód się zepsuł.", "samochód", "Od kiedy samochód jest zepsuty?"),
     ]),

# =====================================================================
# … chai mai dai — „nie dziala"
# =====================================================================
dict(key="CHAIMAIDAI", ty="sentence", cat="Awarie i pomoc", sub="Awarie", reg="n",
     ph="{ph} chái mâi dâai khráp", th="{th}ใช้ไม่ได้ครับ",
     lit="chái mâi dâai = nie da się tego użyć",
     note="Różnica wobec „sǐa”: tu nie orzekamy, że sprzęt jest zepsuty — tylko że nie działa.",
     ex_ph="{ph} chái mâi dâai rǔe khráp", ex_th="{th}ใช้ไม่ได้หรือครับ",
     items=[
       ("Klimatyzacja nie działa.", "klimatyzacja", "Klimatyzacja nie działa?"),
       ("Winda nie działa.", "winda", "Winda nie działa?"),
       ("Prysznic nie działa.", "prysznic", "Prysznic nie działa?"),
       ("Lodówka nie działa.", "lodówka", "Lodówka nie działa?"),
       ("Czajnik nie działa.", "czajnik", "Czajnik nie działa?"),
       ("Telefon nie działa.", "telefon", "Telefon nie działa?"),
       ("Ładowarka nie działa.", "ładowarka", "Ładowarka nie działa?"),
       ("Karta SIM nie działa.", "karta SIM", "Karta SIM nie działa?"),
       ("Hasło nie działa.", "hasło", "Hasło nie działa?"),
       ("Wi-fi nie działa.", "wi-fi", "Wi-fi nie działa?"),
       ("Internet nie działa.", "internet", "Internet nie działa?"),
       ("Klucz nie działa.", "klucz", "Klucz nie działa?"),
       ("Bankomat nie działa.", "bankomat", "Bankomat nie działa?"),
       ("Karta kredytowa nie działa.", "karta kredytowa", "Karta nie działa?"),
       ("Światło nie działa.", "światło", "Światło nie działa?"),
     ]),

# =====================================================================
# thii nii mai mii — „nie ma tutaj"
# =====================================================================
dict(key="MAIMIITHII", ty="sentence", cat="Awarie i pomoc", sub="Problemy", reg="n",
     ph="thîi nîi mâi mii {ph} khráp", th="ที่นี่ไม่มี{th}ครับ",
     lit="thîi nîi mâi mii = tutaj tego nie ma",
     note="Zdanie bez czasownika „być” — tajski używa „mii”, czyli „mieć/istnieć”.",
     ex_ph="thîi nîi mii {ph} mǎi khráp", ex_th="ที่นี่มี{th}ไหมครับ",
     items=[
       ("Nie ma tu ręcznika.", "ręcznik", "Czy jest tu ręcznik?"),
       ("Nie ma tu koca.", "koc", "Czy jest tu koc?"),
       ("Nie ma tu poduszki.", "poduszka", "Czy jest tu poduszka?"),
       ("Nie ma tu mydła.", "mydło", "Czy jest tu mydło?"),
       ("Nie ma tu papieru toaletowego.", "papier toaletowy", "Czy jest tu papier toaletowy?"),
       ("Nie ma tu gorącej wody.", "gorąca woda", "Czy jest tu gorąca woda?"),
       ("Nie ma tu klimatyzacji.", "klimatyzacja", "Czy jest tu klimatyzacja?"),
       ("Nie ma tu wentylatora.", "wentylator", "Czy jest tu wentylator?"),
       ("Nie ma tu windy.", "winda", "Czy jest tu winda?"),
       ("Nie ma tu wi-fi.", "wi-fi", "Czy jest tu wi-fi?"),
       ("Nie ma tu bankomatu.", "bankomat", "Czy jest tu bankomat?"),
       ("Nie ma tu toalety.", "toaleta", "Czy jest tu toaleta?"),
       ("Nie ma tu menu.", "menu", "Czy jest tu karta dań?"),
       ("Nie ma tu widelca.", "widelec", "Czy jest tu widelec?"),
       ("Nie ma tu serwetki.", "serwetka", "Czy jest tu serwetka?"),
       ("Nie ma tu apteki.", "apteka", "Czy jest tu apteka?"),
       ("Nie ma tu lekarza.", "lekarz", "Czy jest tu lekarz?"),
       ("Nie ma tu mapy.", "mapa", "Czy jest tu mapa?"),
     ]),

# =====================================================================
# nii mai chai … khawng phom — „to nie moje"
# =====================================================================
dict(key="MAICHAIKHAWNG", ty="sentence", cat="Gramatyka użytkowa", sub="Posiadanie", reg="n",
     ph="nîi mâi châi {ph} khǎwng phǒm khráp", th="นี่ไม่ใช่{th}ของผมครับ",
     lit="khǎwng = należący do",
     note="„khǎwng phǒm” zawsze idzie po rzeczowniku: „torba moja”, nie „moja torba”.",
     ex_ph="nîi {ph} khǎwng khrai khráp", ex_th="นี่{th}ของใครครับ",
     items=[
       ("To nie jest moja torba.", "torba", "Czyja to torba?"),
       ("To nie jest moja walizka.", "walizka", "Czyja to walizka?"),
       ("To nie jest mój klucz.", "klucz", "Czyj to klucz?"),
       ("To nie jest mój telefon.", "telefon", "Czyj to telefon?"),
       ("To nie jest moja ładowarka.", "ładowarka", "Czyja to ładowarka?"),
       ("To nie jest mój paszport.", "paszport", "Czyj to paszport?"),
       ("To nie jest mój bilet.", "bilet", "Czyj to bilet?"),
       ("To nie jest mój rachunek.", "rachunek", "Czyj to rachunek?"),
       ("To nie jest mój paragon.", "paragon", "Czyj to paragon?"),
       ("To nie są moje buty.", "buty", "Czyje to buty?"),
       ("To nie jest mój kapelusz.", "kapelusz", "Czyj to kapelusz?"),
       ("To nie jest mój kask.", "kask", "Czyj to kask?"),
       ("To nie jest mój rower.", "rower", "Czyj to rower?"),
       ("To nie jest mój pokój.", "pokój", "Czyj to pokój?"),
     ]),

# =====================================================================
# chao … dai thii nai — „gdzie moge wypozyczyc"
# =====================================================================
dict(key="CHAOTHIINAI", ty="question", cat="Pytania", sub="Wynajem", reg="n",
     ph="châo {ph} dâai thîi nǎi khráp", th="เช่า{th}ได้ที่ไหนครับ",
     lit="châo = wynajmować, wypożyczać",
     note="„châo” to brać w najem; wynajmować komuś to „hâi châo”.",
     ex_ph="châo {ph} wan lá thâo-rài khráp", ex_th="เช่า{th}วันละเท่าไหร่ครับ",
     items=[
       ("Gdzie mogę wypożyczyć rower?", "rower", "Ile kosztuje rower na dzień?"),
       ("Gdzie mogę wypożyczyć motocykl?", "motocykl", "Ile kosztuje motocykl na dzień?"),
       ("Gdzie mogę wypożyczyć samochód?", "samochód", "Ile kosztuje samochód na dzień?"),
       ("Gdzie mogę wypożyczyć kask?", "kask", "Ile kosztuje kask na dzień?"),
       ("Gdzie mogę wypożyczyć łódź?", "łódź", "Ile kosztuje łódź na dzień?"),
       ("Gdzie mogę wynająć pokój?", "pokój", "Ile kosztuje pokój na dzień?"),
       ("Gdzie mogę wypożyczyć telefon?", "telefon", "Ile kosztuje telefon na dzień?"),
       ("Gdzie mogę wypożyczyć parasol?", "parasol", "Ile kosztuje parasol na dzień?"),
     ]),

# =====================================================================
# pai … chai wee-laa naan thao-rai — „jak dlugo stad do"
# =====================================================================
dict(key="NAANTHAORAI", ty="question", cat="Pytania", sub="Odległość", reg="n",
     ph="pai {ph} chái wee-laa naan thâo-rài khráp", th="ไป{th}ใช้เวลานานเท่าไหร่ครับ",
     lit="chái wee-laa = zajmuje czasu",
     note="Pytanie o czas przejazdu, nie o odległość w kilometrach.",
     ex_ph="pai {ph} chái wee-laa kìi naa-thii khráp", ex_th="ไป{th}ใช้เวลากี่นาทีครับ",
     items=[
       ("Jak długo stąd na lotnisko?", "lotnisko", "Ile minut stąd na lotnisko?"),
       ("Jak długo stąd na dworzec kolejowy?", "dworzec kolejowy", "Ile minut stąd na dworzec?"),
       ("Jak długo stąd na dworzec autobusowy?", "dworzec autobusowy", "Ile minut stąd na dworzec?"),
       ("Jak długo stąd do hotelu?", "hotel", "Ile minut stąd do hotelu?"),
       ("Jak długo stąd na plażę?", "plaża", "Ile minut stąd na plażę?"),
       ("Jak długo stąd na targ?", "targ", "Ile minut stąd na targ?"),
       ("Jak długo stąd do centrum handlowego?", "centrum handlowe", "Ile minut stąd do centrum?"),
       ("Jak długo stąd do szpitala?", "szpital", "Ile minut stąd do szpitala?"),
       ("Jak długo stąd do apteki?", "apteka", "Ile minut stąd do apteki?"),
       ("Jak długo stąd do banku?", "bank", "Ile minut stąd do banku?"),
       ("Jak długo stąd do świątyni?", "świątynia", "Ile minut stąd do świątyni?"),
       ("Jak długo stąd do parku?", "park", "Ile minut stąd do parku?"),
       ("Jak długo stąd na pocztę?", "poczta", "Ile minut stąd na pocztę?"),
       ("Jak długo stąd do restauracji?", "restauracja", "Ile minut stąd do restauracji?"),
       ("Jak długo stąd na stację benzynową?", "stacja benzynowa", "Ile minut stąd na stację?"),
       ("Jak długo stąd do kawiarni?", "kawiarnia", "Ile minut stąd do kawiarni?"),
       ("Jak długo stąd do salonu masażu?", "salon masażu", "Ile minut stąd do masażu?"),
       ("Jak długo stąd na wyspę?", "wyspa", "Ile minut stąd na wyspę?"),
     ]),

# =====================================================================
# kamlang ja pai — „wlasnie ide do"
# =====================================================================
dict(key="KAMLANGPAI", ty="sentence", cat="Miejsca i orientacja", sub="Ruch", reg="n",
     ph="phǒm kamlang jà pai {ph} khráp", th="ผมกำลังจะไป{th}ครับ",
     lit="kamlang jà pai = właśnie się tam wybieram",
     note="Różnica wobec „phǒm jà pai”: tu wychodzimy w tej chwili, nie kiedyś.",
     ex_ph="kamlang jà pai {ph} rǔe khráp", ex_th="กำลังจะไป{th}หรือครับ",
     items=[
       ("Właśnie idę na targ.", "targ", "Właśnie idziesz na targ?"),
       ("Właśnie idę do apteki.", "apteka", "Właśnie idziesz do apteki?"),
       ("Właśnie idę do banku.", "bank", "Właśnie idziesz do banku?"),
       ("Właśnie idę na pocztę.", "poczta", "Właśnie idziesz na pocztę?"),
       ("Właśnie idę do pralni.", "pralnia", "Właśnie idziesz do pralni?"),
       ("Właśnie idę do supermarketu.", "supermarket", "Właśnie idziesz do supermarketu?"),
       ("Właśnie idę do centrum handlowego.", "centrum handlowe", "Właśnie idziesz do centrum?"),
       ("Właśnie idę na plażę.", "plaża", "Właśnie idziesz na plażę?"),
       ("Właśnie idę do parku.", "park", "Właśnie idziesz do parku?"),
       ("Właśnie idę do świątyni.", "świątynia", "Właśnie idziesz do świątyni?"),
       ("Właśnie idę do szpitala.", "szpital", "Właśnie idziesz do szpitala?"),
       ("Właśnie idę do kawiarni.", "kawiarnia", "Właśnie idziesz do kawiarni?"),
       ("Właśnie idę do restauracji.", "restauracja", "Właśnie idziesz do restauracji?"),
       ("Właśnie idę na masaż.", "salon masażu", "Właśnie idziesz na masaż?"),
       ("Właśnie idę na dworzec autobusowy.", "dworzec autobusowy", "Właśnie idziesz na dworzec?"),
       ("Właśnie idę na lotnisko.", "lotnisko", "Właśnie idziesz na lotnisko?"),
       ("Właśnie idę na bazar nocny.", "bazar nocny", "Właśnie idziesz na bazar?"),
       ("Właśnie idę do hotelu.", "hotel", "Właśnie idziesz do hotelu?"),
     ]),

# =====================================================================
# ao … mai — „chcesz…?"
# =====================================================================
dict(key="AOMAI", ty="question", cat="Pytania", sub="Propozycje", reg="i",
     ph="ao {ph} mǎi khráp", th="เอา{th}ไหมครับ",
     lit="ao = brać, chcieć dostać",
     note="„ao” jest krótsze i swobodniejsze niż „tâwng-kaan”. Odmowa to „mâi ao”.",
     ex_ph="ao {ph} mǎi khráp mii yùu", ex_th="เอา{th}ไหมครับ มีอยู่",
     items=[
       ("Chcesz ręcznik?", "ręcznik", "Chcesz ręcznik? Mam."),
       ("Chcesz koc?", "koc", "Chcesz koc? Mam."),
       ("Chcesz poduszkę?", "poduszka", "Chcesz poduszkę? Mam."),
       ("Chcesz mapę?", "mapa", "Chcesz mapę? Mam."),
       ("Chcesz kartę dań?", "menu", "Chcesz kartę dań? Mam."),
       ("Chcesz torbę?", "torba", "Chcesz torbę? Mam."),
       ("Chcesz torbę na zakupy?", "torba na zakupy", "Chcesz torbę na zakupy? Mam."),
       ("Chcesz serwetkę?", "serwetka", "Chcesz serwetkę? Mam."),
       ("Chcesz łyżkę?", "łyżka", "Chcesz łyżkę? Mam."),
       ("Chcesz widelec?", "widelec", "Chcesz widelec? Mam."),
       ("Chcesz pałeczki?", "pałeczki", "Chcesz pałeczki? Mam."),
       ("Chcesz lekarstwo?", "lek", "Chcesz lekarstwo? Mam."),
       ("Chcesz plaster?", "plaster", "Chcesz plaster? Mam."),
       ("Chcesz krem z filtrem?", "krem z filtrem", "Chcesz krem z filtrem? Mam."),
       ("Chcesz kapelusz?", "kapelusz", "Chcesz kapelusz? Mam."),
       ("Chcesz kask?", "kask", "Chcesz kask? Mam."),
       ("Chcesz paragon?", "paragon", "Chcesz paragon? Mam."),
       ("Chcesz pamiątkę?", "pamiątka", "Chcesz pamiątkę? Mam."),
     ]),

# =====================================================================
# khaa … thao-rai — „ile wynosi oplata za"
# =====================================================================
dict(key="KHAATHAORAI", ty="question", cat="Zakupy i pieniądze", sub="Ceny", reg="n",
     ph="khâa {ph} thâo-rài khráp", th="ค่า{th}เท่าไหร่ครับ",
     lit="khâa + rzeczownik = opłata za coś",
     note="„khâa” tworzy nazwy opłat: khâa rót, khâa hâwng, khâa aa-hǎan.",
     ex_ph="khâa {ph} khít yang-ngai khráp", ex_th="ค่า{th}คิดยังไงครับ",
     items=[
       ("Ile wynosi opłata za pokój?", "pokój", "Jak liczycie opłatę za pokój?"),
       ("Ile wynosi opłata za taksówkę?", "taksówka", "Jak liczycie opłatę za taksówkę?"),
       ("Ile wynosi opłata za autobus?", "autobus", "Jak liczycie opłatę za autobus?"),
       ("Ile wynosi opłata za pociąg?", "pociąg", "Jak liczycie opłatę za pociąg?"),
       ("Ile wynosi opłata za motocykl?", "motocykl", "Jak liczycie opłatę za motocykl?"),
       ("Ile wynosi opłata za rower?", "rower", "Jak liczycie opłatę za rower?"),
       ("Ile wynosi opłata za bilet?", "bilet", "Jak liczycie opłatę za bilet?"),
       ("Ile wynosi opłata za wizę?", "wiza", "Jak liczycie opłatę za wizę?"),
       ("Ile wynosi opłata za internet?", "internet", "Jak liczycie opłatę za internet?"),
       ("Ile wynosi opłata za telefon?", "telefon", "Jak liczycie opłatę za telefon?"),
       ("Ile wynosi opłata za lekarza?", "lekarz", "Jak liczycie opłatę za wizytę?"),
       ("Ile wynosi opłata za ubezpieczenie?", "ubezpieczenie", "Jak liczycie opłatę za ubezpieczenie?"),
       ("Ile wynosi opłata za masaż?", "salon masażu", "Jak liczycie opłatę za masaż?"),
       ("Ile wynosi opłata za pralnię?", "pralnia", "Jak liczycie opłatę za pranie?"),
       ("Ile wynosi opłata za przechowalnię bagażu?", "przechowalnia bagażu", "Jak liczycie opłatę za bagaż?"),
     ]),
]
