# -*- coding: utf-8 -*-
"""Leksyka etapu 4 (B1) — wyrazenia laczace i rejestr.

Zakres: spojniki i wyrazenia spajajace dluzsza wypowiedz, oraz pary
formalne/potoczne tego samego znaczenia. Poziom B1 rozni sie od A2 wlasnie
tym, ze uczacy sie przestaje mowic pojedynczymi zdaniami.

Format jak w lex_b1_core_a.py.
"""

CORE_CONNECT = [

# =====================================================================
# LACZENIE MYSLI
# =====================================================================
("poza tym", "nâwk jàak níi", "นอกจากนี้", "Gramatyka użytkowa", "Spójniki", "word", 4, "f",
 "Rejestr pisany i oficjalny. W rozmowie częściej „láew kâw”.", "",
 ("Poza tym jest za drogo.", "nâwk jàak níi yang phaeng ìik khráp", "นอกจากนี้ยังแพงอีกครับ")),
("a poza tym", "láew kâw", "แล้วก็", "Gramatyka użytkowa", "Spójniki", "word", 5, "p",
 "Potoczny odpowiednik „nâwk jàak níi”. Tym Tajowie sklejają wyliczenia w mowie.", "",
 ("A poza tym jestem zmęczony.", "láew kâw phǒm kâw nùeai khráp", "แล้วก็ผมก็เหนื่อยครับ")),
("dlatego właśnie", "phráw chà-nán", "เพราะฉะนั้น", "Gramatyka użytkowa", "Spójniki", "word", 4, "f",
 "Wprowadza wniosek. Mocniejsze i bardziej oficjalne niż „kâw loei”.", "",
 ("Dlatego właśnie nie pojechałem.", "phráw chà-nán phǒm loei mâi pai khráp", "เพราะฉะนั้นผมเลยไม่ไปครับ")),
("i dlatego", "kâw loei", "ก็เลย", "Gramatyka użytkowa", "Spójniki", "word", 5, "n",
 "Najczęstszy sposób łączenia przyczyny ze skutkiem w mowie codziennej.", "",
 ("I dlatego wróciłem.", "kâw loei klàp maa khráp", "ก็เลยกลับมาครับ")),
("mimo to", "thǔeng yàang nán", "ถึงอย่างนั้น", "Gramatyka użytkowa", "Spójniki", "word", 3, "f", "", "",
 ("Mimo to spróbowałem.", "thǔeng yàang nán phǒm kâw lawng khráp", "ถึงอย่างนั้นผมก็ลองครับ")),
("jednakże", "yàang rai kâw taam", "อย่างไรก็ตาม", "Gramatyka użytkowa", "Spójniki", "word", 2, "f",
 "Wyłącznie rejestr pisany i oficjalny. W rozmowie zabrzmi jak czytanie z kartki.", "",
 ("Jednakże sytuacja się zmieniła.", "yàang rai kâw taam sà-thǎa-ná-kaan plìan pai khráp",
  "อย่างไรก็ตามสถานการณ์เปลี่ยนไปครับ")),
("tak czy inaczej", "yang-ngai kâw taam", "ยังไงก็ตาม", "Gramatyka użytkowa", "Spójniki", "word", 4, "n",
 "Mówiony odpowiednik „yàang rai kâw taam”.", "",
 ("Tak czy inaczej idę.", "yang-ngai kâw taam phǒm kâw pai khráp", "ยังไงก็ตามผมก็ไปครับ")),
("na przykład taki", "yók tua yàang chên", "ยกตัวอย่างเช่น", "Gramatyka użytkowa", "Spójniki", "phrase", 3, "f",
 "„yók tua yàang” = podać przykład.", "",
 ("Na przykład taki przypadek.", "yók tua yàang chên kaw-ra-nii níi khráp", "ยกตัวอย่างเช่นกรณีนี้ครับ")),
("czyli inaczej mówiąc", "rǔe kâw khue", "หรือก็คือ", "Gramatyka użytkowa", "Spójniki", "phrase", 3, "n", "", "",
 ("Czyli inaczej mówiąc, nie ma.", "rǔe kâw khue mâi mii khráp", "หรือก็คือไม่มีครับ")),
("w dodatku", "yîng pai kwàa nán", "ยิ่งไปกว่านั้น", "Gramatyka użytkowa", "Spójniki", "phrase", 2, "f", "", "",
 ("W dodatku było późno.", "yîng pai kwàa nán man dùek láew khráp", "ยิ่งไปกว่านั้นมันดึกแล้วครับ")),
("z drugiej strony", "nai thaang klàp kan", "ในทางกลับกัน", "Gramatyka użytkowa", "Spójniki", "phrase", 3, "f", "", "",
 ("Z drugiej strony to tanie.", "nai thaang klàp kan man kâw thùuk khráp", "ในทางกลับกันมันก็ถูกครับ")),
("na szczęście", "chôhk dii thîi", "โชคดีที่", "Gramatyka użytkowa", "Spójniki", "phrase", 4, "n", "", "",
 ("Na szczęście nic się nie stało.", "chôhk dii thîi mâi mii à-rai khráp", "โชคดีที่ไม่มีอะไรครับ")),
("niestety", "nâa sǐa daai thîi", "น่าเสียดายที่", "Gramatyka użytkowa", "Spójniki", "phrase", 4, "n", "", "",
 ("Niestety nie zdążyłem.", "nâa sǐa daai thîi phǒm maa mâi than khráp", "น่าเสียดายที่ผมมาไม่ทันครับ")),
("prawdę mówiąc", "thîi jing láew", "ที่จริงแล้ว", "Gramatyka użytkowa", "Spójniki", "phrase", 4, "n", "", "",
 ("Prawdę mówiąc, zapomniałem.", "thîi jing láew phǒm luem khráp", "ที่จริงแล้วผมลืมครับ")),
("przede wszystkim", "kàwn ùen", "ก่อนอื่น", "Gramatyka użytkowa", "Spójniki", "phrase", 3, "f", "", "",
 ("Przede wszystkim dziękuję.", "kàwn ùen khàwp-khun khráp", "ก่อนอื่นขอบคุณครับ")),
("wreszcie", "nai thîi sùt", "ในที่สุด", "Gramatyka użytkowa", "Spójniki", "phrase", 3, "n", "", "",
 ("Wreszcie się udało.", "nai thîi sùt kâw sǎm-rèt khráp", "ในที่สุดก็สำเร็จครับ")),
("mniej więcej tak", "prà-maan níi", "ประมาณนี้", "Gramatyka użytkowa", "Spójniki", "phrase", 4, "n", "", "",
 ("Mniej więcej tak to wygląda.", "kâw prà-maan níi khráp", "ก็ประมาณนี้ครับ")),
("według mnie", "tâam khwaam-khít phǒm", "ตามความคิดผม", "Gramatyka użytkowa", "Spójniki", "phrase", 4, "n", "", "",
 ("Według mnie warto.", "tâam khwaam-khít phǒm man khúm khráp", "ตามความคิดผมมันคุ้มครับ")),
("jak wiadomo", "taam thîi rúu kan", "ตามที่รู้กัน", "Gramatyka użytkowa", "Spójniki", "phrase", 2, "f", "", "",
 ("Jak wiadomo, jest drogo.", "taam thîi rúu kan man phaeng khráp", "ตามที่รู้กันมันแพงครับ")),
("o ile pamiętam", "thâo thîi jam dâai", "เท่าที่จำได้", "Gramatyka użytkowa", "Spójniki", "phrase", 3, "n", "", "",
 ("O ile pamiętam, było zamknięte.", "thâo thîi jam dâai man pìt khráp", "เท่าที่จำได้มันปิดครับ")),
("zanim o tym powiem", "kàwn thîi jà bàwk", "ก่อนที่จะบอก", "Gramatyka użytkowa", "Spójniki", "phrase", 2, "n", "", "",
 ("Zanim o tym powiem, usiądźmy.", "kàwn thîi jà bàwk nâng kàwn khráp", "ก่อนที่จะบอกนั่งก่อนครับ")),
("skoro tak", "nai mûea thîi", "ในเมื่อ", "Gramatyka użytkowa", "Spójniki", "phrase", 3, "f", "", "",
 ("Skoro tak, to idźmy.", "nai mûea thîi pen yàang nán pai kan khráp", "ในเมื่อเป็นอย่างนั้นไปกันครับ")),
("w takim razie", "thâa yàang nán", "ถ้าอย่างนั้น", "Gramatyka użytkowa", "Spójniki", "phrase", 4, "n", "", "",
 ("W takim razie poczekam.", "thâa yàang nán phǒm raw khráp", "ถ้าอย่างนั้นผมรอครับ")),
("choćby dlatego, że", "kâw phráw wâa", "ก็เพราะว่า", "Gramatyka użytkowa", "Spójniki", "phrase", 3, "n", "", "",
 ("Choćby dlatego, że jest drogo.", "kâw phráw wâa man phaeng khráp", "ก็เพราะว่ามันแพงครับ")),
("dopóki nie", "jon kwàa jà", "จนกว่าจะ", "Gramatyka użytkowa", "Spójniki", "phrase", 3, "n",
 "„jon kwàa jà …” = dopóki nie nastąpi… Po tajsku nie ma tu przeczenia — kalka z polskiego byłaby błędem.", "",
 ("Poczekam, dopóki nie wróci.", "phǒm raw jon kwàa khǎo jà klàp khráp", "ผมรอจนกว่าเขาจะกลับครับ")),
("od czasu, gdy", "tâng tàae thîi", "ตั้งแต่ที่", "Gramatyka użytkowa", "Spójniki", "phrase", 3, "n", "", "",
 ("Od czasu, gdy tu mieszkam.", "tâng tàae thîi phǒm yáai maa yùu khráp", "ตั้งแต่ที่ผมย้ายมาอยู่ครับ")),
("za każdym razem, gdy", "thúk khráng thîi", "ทุกครั้งที่", "Gramatyka użytkowa", "Spójniki", "phrase", 3, "n", "", "",
 ("Za każdym razem, gdy pada.", "thúk khráng thîi fǒn tòk khráp", "ทุกครั้งที่ฝนตกครับ")),
("nie tylko, ale i", "mâi châi khâe … tàae yang", "ไม่ใช่แค่ แต่ยัง",
 "Gramatyka użytkowa", "Spójniki", "phrase", 2, "f", "Konstrukcja dwuczłonowa, typowa dla wypowiedzi na zebraniu.", "",
 ("Nie tylko tanio, ale i szybko.", "mâi châi khâe thùuk tàae yang reo dûai khráp",
  "ไม่ใช่แค่ถูกแต่ยังเร็วด้วยครับ")),
("im dłużej, tym gorzej", "yîng naan yîng yâe", "ยิ่งนานยิ่งแย่",
 "Gramatyka użytkowa", "Spójniki", "phrase", 3, "n", "Konstrukcja „yîng … yîng …” = im…, tym…", "",
 ("Im dłużej czekam, tym gorzej.", "yîng raw yîng yâe khráp", "ยิ่งรอยิ่งแย่ครับ")),

# =====================================================================
# REJESTR: PARY FORMALNE I POTOCZNE
# =====================================================================
("jeść (oficjalnie)", "ráp-prà-thaan", "รับประทาน", "Jedzenie i napoje", "Rejestr", "word", 2, "f",
 "Wersja oficjalna. Na tablicach i w menu restauracji hotelowych. W domu nikt tak nie mówi.", "",
 ("Zapraszam do stołu.", "choen ráp-prà-thaan khráp", "เชิญรับประทานครับ")),
("jeść (potocznie)", "dàek", "แดก", "Jedzenie i napoje", "Rejestr", "word", 1, "p",
 "SLANG WULGARNY. NIE używaj nigdy wobec obcych, starszych, w pracy ani w restauracji — to obraźliwe. "
 "Rekord jest tu po to, żebyś rozpoznał to słowo, gdy je usłyszysz, a nie po to, żeby go używać.", "",
 ("Nie mów tak przy stole.", "yàa phûut yàang nán ná khráp", "อย่าพูดอย่างนั้นนะครับ")),
("iść (oficjalnie)", "dòoen thaang pai", "เดินทางไป", "Transport", "Rejestr", "phrase", 3, "f", "", "",
 ("Wyruszam jutro.", "phǒm dòoen thaang pai phrûng níi khráp", "ผมเดินทางไปพรุ่งนี้ครับ")),
("głowa (oficjalnie)", "sǐi-sà", "ศีรษะ", "Zdrowie", "Rejestr", "word", 2, "f",
 "Słowo z rejestru medycznego i pisanego. W rozmowie z lekarzem wystarczy „hǔa”.", "",
 ("Boli mnie głowa.", "pùat sǐi-sà khráp", "ปวดศีรษะครับ")),
("żona (oficjalnie)", "phan-rá-yaa", "ภรรยา", "Ludzie i rodzina", "Rejestr", "word", 3, "f",
 "Formalnie. Potocznie: „mia”, ale to słowo bywa odbierane jako lekceważące.", "",
 ("To moja żona.", "nîi phan-rá-yaa phǒm khráp", "นี่ภรรยาผมครับ")),
("mąż (oficjalnie)", "sǎa-mii", "สามี", "Ludzie i rodzina", "Rejestr", "word", 3, "f", "", "",
 ("To mój mąż.", "nîi sǎa-mii chǎn khâ", "นี่สามีฉันค่ะ")),
("dziecko (oficjalnie)", "bùt", "บุตร", "Ludzie i rodzina", "Rejestr", "word", 2, "f",
 "Wyłącznie w dokumentach. W rozmowie zawsze „lûuk”.", "",
 ("Mam dwoje dzieci.", "phǒm mii bùt sǎwng khon khráp", "ผมมีบุตรสองคนครับ")),
("bardzo (oficjalnie)", "pen yàang yîng", "เป็นอย่างยิ่ง", "Cechy i opinie", "Rejestr", "phrase", 2, "f", "", "",
 ("Bardzo dziękuję.", "khàwp-khun pen yàang yîng khráp", "ขอบคุณเป็นอย่างยิ่งครับ")),
("bardzo (potocznie)", "sùt sùt", "สุดๆ", "Cechy i opinie", "Rejestr", "phrase", 3, "p",
 "Wzmocnienie młodzieżowe. W piśmie służbowym nie występuje.", "",
 ("Naprawdę bardzo dobre.", "dii sùt sùt loei", "ดีสุดๆ เลย")),
("dużo (potocznie)", "yóe yáe", "เยอะแยะ", "Liczby i liczenie", "Rejestr", "phrase", 3, "p", "", "",
 ("Jest tego mnóstwo.", "mii yóe yáe loei khráp", "มีเยอะแยะเลยครับ")),
("pieniądze (potocznie)", "tang", "ตังค์", "Zakupy i pieniądze", "Rejestr", "word", 4, "p",
 "Potoczny skrót od „sà-taang”. Swobodne, ale nieobraźliwe — w banku jednak mów „ngoen”.", "",
 ("Nie mam przy sobie pieniędzy.", "mâi mii tang tìt tua khráp", "ไม่มีตังค์ติดตัวครับ")),
("bardzo drogo (potocznie)", "phaeng wôoe", "แพงเวอร์", "Zakupy i pieniądze", "Rejestr", "phrase", 3, "p",
 "SLANG: „wôoe” od angielskiego over. NIE używaj wobec sprzedawcy — zabrzmi jak zarzut.", "",
 ("Strasznie drogo.", "phaeng wôoe loei", "แพงเวอร์เลย")),
("ładna (potocznie)", "sǔai wêr", "สวยเว่อร์", "Cechy i opinie", "Rejestr", "phrase", 2, "p",
 "SLANG towarzyski. NIE mów tak do nieznajomej osoby ani w pracy — bywa odbierane jako zaczepka.", "",
 ("Naprawdę ładnie.", "sǔai wêr loei", "สวยเว่อร์เลย")),
("dobrze (potocznie)", "oo-khee", "โอเค", "Podstawy i grzeczność", "Rejestr", "word", 5, "p",
 "Angielskie OK weszło do tajskiego na stałe. W piśmie urzędowym używaj „tòk long”.", "",
 ("Dobra, zgoda.", "oo-khee khráp", "โอเคครับ")),
("proszę (oficjalnie)", "krù-naa", "กรุณา", "Podstawy i grzeczność", "Rejestr", "word", 3, "f",
 "Na tablicach, w komunikatach i pismach. W rozmowie brzmi sztywno — użyj „chûai … nòi”.", "",
 ("Proszę zaczekać.", "krù-naa raw sàk khrûu khráp", "กรุณารอสักครู่ครับ")),
("przepraszam (oficjalnie)", "khǎw à-phai", "ขออภัย", "Podstawy i grzeczność", "Rejestr", "phrase", 3, "f",
 "Formalne przeprosiny — w ogłoszeniach i pismach. Na co dzień „khǎw-thôot”.", "",
 ("Przepraszamy za utrudnienia.", "khǎw à-phai nai khwaam mâi sà-dùak khráp",
  "ขออภัยในความไม่สะดวกครับ")),
("informować (oficjalnie)", "jâeng hâi sâap", "แจ้งให้ทราบ", "Praca i nauka", "Rejestr", "phrase", 2, "f", "", "",
 ("Informujemy uprzejmie.", "khǎw jâeng hâi sâap khráp", "ขอแจ้งให้ทราบครับ")),
("wiedzieć (oficjalnie)", "sâap", "ทราบ", "Praca i nauka", "Rejestr", "word", 3, "f",
 "Formalny odpowiednik „rúu”. W rozmowie z urzędnikiem robi dobre wrażenie.", "",
 ("Nie mam takiej wiedzy.", "phǒm mâi sâap khráp", "ผมไม่ทราบครับ")),
("dom (oficjalnie)", "thîi phák aa-sǎi", "ที่พักอาศัย", "Dom i codzienność", "Rejestr", "phrase", 2, "f", "", "",
 ("Adres zamieszkania.", "thîi phák aa-sǎi khráp", "ที่พักอาศัยครับ")),
("kolega (potocznie)", "phûean sà-nít", "เพื่อนสนิท", "Ludzie i rodzina", "Rejestr", "phrase", 4, "i",
 "„sà-nít” = bliski, zżyty. To już przyjaciel, nie znajomy.", "",
 ("To mój bliski kolega.", "khǎo pen phûean sà-nít phǒm khráp", "เขาเป็นเพื่อนสนิทผมครับ")),
("kumpel (potocznie)", "kler", "เกลอ", "Ludzie i rodzina", "Rejestr", "word", 1, "p",
 "Bardzo swobodne, regionalne. NIE używaj wobec osoby, której nie znasz dobrze.", "",
 ("Znamy się od dzieciństwa.", "rúu-jàk kan tâng tàae dèk khráp", "รู้จักกันตั้งแต่เด็กครับ")),
("no i", "kâw", "ก็", "Gramatyka użytkowa", "Rejestr", "word", 5, "p",
 "Najbardziej uniwersalne słowo tajskiej mowy potocznej. Łagodzi, łączy i wypełnia pauzę.", "",
 ("No i poszedłem.", "kâw pai khráp", "ก็ไปครับ")),
("no bo", "kâw phráw", "ก็เพราะ", "Gramatyka użytkowa", "Rejestr", "phrase", 4, "p", "", "",
 ("No bo było zamknięte.", "kâw phráw man pìt khráp", "ก็เพราะมันปิดครับ")),
("właściwie to", "jing jing láew", "จริงๆ แล้ว", "Gramatyka użytkowa", "Rejestr", "phrase", 4, "n", "", "",
 ("Właściwie to nie wiem.", "jing jing láew phǒm mâi rúu khráp", "จริงๆ แล้วผมไม่รู้ครับ")),
("że tak powiem", "phûut dâai wâa", "พูดได้ว่า", "Gramatyka użytkowa", "Rejestr", "phrase", 3, "n", "", "",
 ("Że tak powiem, było ciężko.", "phûut dâai wâa man nàk khráp", "พูดได้ว่ามันหนักครับ")),
("mówiąc wprost", "phûut ngâai ngâai", "พูดง่ายๆ", "Gramatyka użytkowa", "Rejestr", "phrase", 4, "n", "", "",
 ("Mówiąc wprost, nie ma.", "phûut ngâai ngâai khue mâi mii khráp", "พูดง่ายๆ คือไม่มีครับ")),
("jeśli mogę tak powiedzieć", "thâa jà hâi phûut", "ถ้าจะให้พูด", "Gramatyka użytkowa", "Rejestr", "phrase", 2, "f", "", "",
 ("Jeśli mogę tak powiedzieć, to za mało.", "thâa jà hâi phûut man yang mâi phaw khráp",
  "ถ้าจะให้พูดมันยังไม่พอครับ")),
("z całym szacunkiem", "dûai khwaam khaw-róp", "ด้วยความเคารพ", "Podstawy i grzeczność", "Rejestr", "phrase", 2, "f",
 "Wstęp do sprzeciwu wobec osoby wyższej rangą. Bez niego uwaga zabrzmi jak zuchwalstwo.", "",
 ("Z całym szacunkiem, nie zgadzam się.", "dûai khwaam khaw-róp phǒm mâi hěn dûai khráp",
  "ด้วยความเคารพผมไม่เห็นด้วยครับ")),
("pozwolę sobie zauważyć", "khǎw rian hâi sâap", "ขอเรียนให้ทราบ", "Praca i nauka", "Rejestr", "phrase", 2, "f",
 "„rian” w tym znaczeniu = zwracać się z szacunkiem do wyżej postawionej osoby.", "",
 ("Pozwolę sobie zauważyć, że jest błąd.", "khǎw rian hâi sâap wâa mii khwaam phìt phlâat khráp",
  "ขอเรียนให้ทราบว่ามีความผิดพลาดครับ")),
("uprzejmie proszę", "khǎw khwaam kà-rú-naa", "ขอความกรุณา", "Podstawy i grzeczność", "Rejestr", "phrase", 2, "f", "", "",
 ("Uprzejmie proszę o pomoc.", "khǎw khwaam kà-rú-naa chûai dûai khráp", "ขอความกรุณาช่วยด้วยครับ")),
]
