# -*- coding: utf-8 -*-
"""Leksyka etapu 5 (B2) — czesc D.

Zakres: rozwiazywanie konfliktow i naturalne wyrazanie emocji. Zglaszanie
niezadowolenia, przeprosiny o roznej sile, przyjmowanie przeprosin, studzenie
sporu, stawianie granic, emocje pozytywne i trudne.

Format jak w lex_b2_core_a.py.
"""

CORE_D = [

# =====================================================================
# ZGLASZANIE NIEZADOWOLENIA
# =====================================================================
("muszę ci coś powiedzieć wprost", "mii rûeang tâwng bàwk trong trong khráp", "มีเรื่องต้องบอกตรงๆ ครับ",
 "Praca i nauka", "Konflikt", "sentence", 4, "n",
 "Zapowiedź trudnej rozmowy. W Tajlandii uprzedzenie o niej samo w sobie jest formą szacunku.", "",
 ("Muszę ci coś powiedzieć wprost, bo długo czekałem.", "mii rûeang tâwng bàwk trong trong khráp phráw phǒm raw maa naan", "มีเรื่องต้องบอกตรงๆ ครับ เพราะผมรอมานาน")),
("czuję się z tym niekomfortowo", "phǒm rúu-sùek mâi sà-baai jai khráp", "ผมรู้สึกไม่สบายใจครับ",
 "Cechy i opinie", "Konflikt", "sentence", 5, "n",
 "Standardowy tajski sposób zgłaszania problemu emocjonalnego. Mówisz o sobie, nie oskarżasz.", "",
 ("Czuję się z tym niekomfortowo od kilku dni.", "phǒm rúu-sùek mâi sà-baai jai maa lǎai wan láew khráp", "ผมรู้สึกไม่สบายใจมาหลายวันแล้วครับ")),
("to mnie zabolało", "man tham hâi phǒm sǐa jai khráp", "มันทำให้ผมเสียใจครับ",
 "Cechy i opinie", "Konflikt", "sentence", 4, "n", "psuje serce", "",
 ("To mnie zabolało, choć wiem, że nie chciałeś.", "man tham hâi phǒm sǐa jai khráp thǔeng jà rúu wâa mâi tâng-jai", "มันทำให้ผมเสียใจครับ ถึงจะรู้ว่าไม่ตั้งใจ")),
("poczułem się pominięty", "phǒm rúu-sùek thùuk mawng khâam khráp", "ผมรู้สึกถูกมองข้ามครับ",
 "Praca i nauka", "Konflikt", "sentence", 3, "n", "być przeoczonym wzrokiem", "",
 ("Poczułem się pominięty przy tej decyzji.", "kaan tàt-sǐn jai khráng níi phǒm rúu-sùek thùuk mawng khâam khráp", "การตัดสินใจครั้งนี้ผมรู้สึกถูกมองข้ามครับ")),
("nie tak się umawialiśmy", "man mâi trong kàp thîi tòk long wái khráp", "มันไม่ตรงกับที่ตกลงไว้ครับ",
 "Praca i nauka", "Konflikt", "sentence", 4, "n",
 "Odwołanie się do ustalenia zamiast do winy. Najskuteczniejsze zdanie przy reklamacji.", "",
 ("Nie tak się umawialiśmy co do ceny.", "rûeang raa-khaa man mâi trong kàp thîi tòk long wái khráp", "เรื่องราคามันไม่ตรงกับที่ตกลงไว้ครับ")),
("proszę mnie zrozumieć", "chûai khâo-jai phǒm nòi ná khráp", "ช่วยเข้าใจผมหน่อยนะครับ",
 "Podstawy i grzeczność", "Konflikt", "sentence", 4, "n", "", "",
 ("Proszę mnie zrozumieć, czekam już trzeci tydzień.", "chûai khâo-jai phǒm nòi ná khráp phǒm raw maa sǎam aa-thít láew", "ช่วยเข้าใจผมหน่อยนะครับ ผมรอมาสามอาทิตย์แล้ว")),
("to się powtarza za często", "man kòet khûen bàwi koen pai khráp", "มันเกิดขึ้นบ่อยเกินไปครับ",
 "Praca i nauka", "Konflikt", "sentence", 3, "n", "", "",
 ("To się powtarza za często, żeby to ignorować.", "man kòet khûen bàwi koen jà plòi phàan khráp", "มันเกิดขึ้นบ่อยเกินจะปล่อยผ่านครับ")),
("chciałbym, żeby to się zmieniło", "yàak hâi man dii khûen khráp", "อยากให้มันดีขึ้นครับ",
 "Praca i nauka", "Konflikt", "sentence", 4, "n", "", "",
 ("Chciałbym, żeby to się zmieniło od przyszłego miesiąca.", "yàak hâi man dii khûen tâng tàae duean nâa khráp", "อยากให้มันดีขึ้นตั้งแต่เดือนหน้าครับ")),
("mówię to raz, bez awantury", "phǒm bàwk khráng diao mâi mii dràa-mâa khráp", "ผมบอกครั้งเดียว ไม่มีดราม่าครับ",
 "Praca i nauka", "Konflikt", "sentence", 3, "p",
 "SLANG. „dràa-mâa” to zapożyczone „drama”. W piśmie i wobec urzędu użyj „mâi yàak hâi pen rûeang yài”.", "",
 ("Mówię to raz, bez awantury, i wracamy do pracy.", "phǒm bàwk khráng diao mâi mii dràa-mâa khráp láew tham-ngaan tàw", "ผมบอกครั้งเดียว ไม่มีดราม่าครับ แล้วทำงานต่อ")),

# =====================================================================
# PRZEPROSINY O ROZNEJ SILE
# =====================================================================
("sorki", "khǎw-thôot náe", "ขอโทษแหน่", "Podstawy i grzeczność", "Przeprosiny", "phrase", 4, "p",
 "SLANG. Wersja koleżeńska, między rówieśnikami. Wobec starszego, klienta i urzędnika brzmi lekceważąco.", "",
 ("Sorki, zapomniałem oddzwonić.", "khǎw-thôot náe luem thoo klàp", "ขอโทษแหน่ ลืมโทรกลับ")),
("przepraszam za kłopot", "khǎw-thôot thîi tham hâi yûng yâak khráp", "ขอโทษที่ทำให้ยุ่งยากครับ",
 "Podstawy i grzeczność", "Przeprosiny", "sentence", 5, "n", "", "",
 ("Przepraszam za kłopot, poprawię to dzisiaj.", "khǎw-thôot thîi tham hâi yûng yâak khráp dǐao kâe hâi wan níi", "ขอโทษที่ทำให้ยุ่งยากครับ เดี๋ยวแก้ให้วันนี้")),
("przepraszam, to moja wina", "khǎw-thôot khráp pen khwaam phìt khǎwng phǒm", "ขอโทษครับ เป็นความผิดของผม",
 "Podstawy i grzeczność", "Przeprosiny", "sentence", 4, "n",
 "Wzięcie winy wprost. W tajskiej pracy dobrze widziane, o ile następuje po nim naprawa.", "",
 ("Przepraszam, to moja wina, źle policzyłem.", "khǎw-thôot khráp pen khwaam phìt khǎwng phǒm phǒm khít phìt", "ขอโทษครับ เป็นความผิดของผม ผมคิดผิด")),
("bardzo mi przykro z tego powodu", "phǒm sǐa jai kàp rûeang níi mâak khráp", "ผมเสียใจกับเรื่องนี้มากครับ",
 "Podstawy i grzeczność", "Przeprosiny", "sentence", 4, "f", "", "",
 ("Bardzo mi przykro z tego powodu, naprawimy to.", "phǒm sǐa jai kàp rûeang níi mâak khráp dǐao kâe khǎi hâi", "ผมเสียใจกับเรื่องนี้มากครับ เดี๋ยวแก้ไขให้")),
("proszę o wybaczenie", "khǎw à-phai jàak jai jing khráp", "ขออภัยจากใจจริงครับ",
 "Podstawy i grzeczność", "Przeprosiny", "sentence", 3, "f",
 "Najwyższy rejestr przeprosin. Wobec drobiazgu wypadnie teatralnie.", "z prawdziwego serca",
 ("Proszę o wybaczenie, to nie powinno się zdarzyć.", "khǎw à-phai jàak jai jing khráp man mâi khuan kòet khûen", "ขออภัยจากใจจริงครับ มันไม่ควรเกิดขึ้น")),
("obiecuję, że to się nie powtórzy", "phǒm sǎn-yaa wâa jà mâi hâi kòet ìik khráp", "ผมสัญญาว่าจะไม่ให้เกิดอีกครับ",
 "Praca i nauka", "Przeprosiny", "sentence", 4, "f", "", "",
 ("Obiecuję, że to się nie powtórzy w tym kwartale.", "phǒm sǎn-yaa wâa jà mâi hâi kòet ìik nai khwaa-tôoe níi khráp", "ผมสัญญาว่าจะไม่ให้เกิดอีกในควอเตอร์นี้ครับ")),
("weźmy to na siebie i naprawmy", "ráp phìt châwp láew kâe pai dûai kan khráp", "รับผิดชอบแล้วแก้ไปด้วยกันครับ",
 "Praca i nauka", "Przeprosiny", "sentence", 3, "n", "", "",
 ("Weźmy to na siebie i naprawmy, zamiast szukać winnych.", "ráp phìt châwp láew kâe pai dûai kan khráp yàa mûa hǎa khon phìt", "รับผิดชอบแล้วแก้ไปด้วยกันครับ อย่ามัวหาคนผิด")),
("jak mogę to wynagrodzić?", "hâi phǒm chót chôei yang-ngai dii khráp", "ให้ผมชดเชยยังไงดีครับ",
 "Praca i nauka", "Przeprosiny", "sentence", 3, "f",
 "„chót chôei” = zrekompensować. Słowo z języka reklamacji i ubezpieczeń.", "",
 ("Jak mogę to wynagrodzić, żeby było uczciwie?", "hâi phǒm chót chôei yang-ngai thǔeng jà pen tham khráp", "ให้ผมชดเชยยังไงถึงจะเป็นธรรมครับ")),

# =====================================================================
# PRZYJMOWANIE PRZEPROSIN I GODZENIE SIE
# =====================================================================
("nie gniewam się", "phǒm mâi dâai kròot khráp", "ผมไม่ได้โกรธครับ", "Cechy i opinie", "Godzenie", "sentence", 5, "n", "", "",
 ("Nie gniewam się, chciałem tylko wyjaśnić.", "phǒm mâi dâai kròot khráp khâe yàak khui hâi chát", "ผมไม่ได้โกรธครับ แค่อยากคุยให้ชัด")),
("już zapomniałem o sprawie", "rûeang nán phàan pai láew khráp", "เรื่องนั้นผ่านไปแล้วครับ",
 "Cechy i opinie", "Godzenie", "sentence", 4, "n", "", "",
 ("Już zapomniałem o sprawie, idziemy dalej.", "rûeang nán phàan pai láew khráp pai tàw dii kwàa", "เรื่องนั้นผ่านไปแล้วครับ ไปต่อดีกว่า")),
("nie mam do ciebie żalu", "phǒm mâi dâai thǔe sǎa khráp", "ผมไม่ได้ถือสาครับ", "Cechy i opinie", "Godzenie", "sentence", 4, "n", "", "",
 ("Nie mam do ciebie żalu, każdemu się zdarza.", "phǒm mâi dâai thǔe sǎa khráp khrai kâw phìt dâai", "ผมไม่ได้ถือสาครับ ใครก็ผิดได้")),
("zacznijmy od nowa", "rôoem mài kan ná khráp", "เริ่มใหม่กันนะครับ", "Cechy i opinie", "Godzenie", "sentence", 4, "n", "", "",
 ("Zacznijmy od nowa, tym razem z jasnymi zasadami.", "rôoem mài kan ná khráp khráng níi tòk long kót hâi chát", "เริ่มใหม่กันนะครับ ครั้งนี้ตกลงกฎให้ชัด")),
("dobrze, że o tym powiedziałeś", "dii láew thîi bàwk khráp", "ดีแล้วที่บอกครับ", "Cechy i opinie", "Godzenie", "sentence", 4, "n",
 "Nagradza rozmówcę za odwagę zgłoszenia problemu. Bardzo skuteczne w zespole.", "",
 ("Dobrze, że o tym powiedziałeś, nie wiedziałem.", "dii láew thîi bàwk khráp phǒm mâi rúu maa kàwn", "ดีแล้วที่บอกครับ ผมไม่รู้มาก่อน")),
("chodźmy na kawę i pogadajmy", "pai kin kaa-fae láew khui kan dii kwàa khráp", "ไปกินกาแฟแล้วคุยกันดีกว่าครับ",
 "Small talk", "Godzenie", "sentence", 4, "i",
 "Przeniesienie konfliktu poza biurko to bardzo tajski sposób na jego rozbrojenie.", "",
 ("Chodźmy na kawę i pogadajmy spokojnie.", "pai kin kaa-fae láew khui kan jai yen yen khráp", "ไปกินกาแฟแล้วคุยกันใจเย็นๆ ครับ")),
("wyjaśnijmy to teraz, żeby nie zostało", "khui hâi jòp tawn níi loei ná khráp", "คุยให้จบตอนนี้เลยนะครับ",
 "Praca i nauka", "Godzenie", "sentence", 4, "n", "", "",
 ("Wyjaśnijmy to teraz, żeby nie zostało na później.", "khui hâi jòp tawn níi loei ná khráp jà dâai mâi khâang khaa", "คุยให้จบตอนนี้เลยนะครับ จะได้ไม่ค้างคา")),
("ważniejsza jest dla mnie relacja", "khwaam sǎm-phan sǎm-khan kwàa khráp", "ความสัมพันธ์สำคัญกว่าครับ",
 "Ludzie i rodzina", "Godzenie", "sentence", 3, "n", "", "",
 ("Ważniejsza jest dla mnie relacja niż ta kwota.", "khwaam sǎm-phan sǎm-khan kwàa ngoen jam-nuan níi khráp", "ความสัมพันธ์สำคัญกว่าเงินจำนวนนี้ครับ")),
("uścisnąłbym rękę i zamknął temat", "jàp mue kan láew jòp rûeang khráp", "จับมือกันแล้วจบเรื่องครับ",
 "Ludzie i rodzina", "Godzenie", "sentence", 3, "i", "", "",
 ("Uścisnąłbym rękę i zamknął temat na dobre.", "jàp mue kan láew jòp rûeang pai loei khráp", "จับมือกันแล้วจบเรื่องไปเลยครับ")),

# =====================================================================
# STUDZENIE SPORU
# =====================================================================
("nie podnośmy głosu", "yàa sǐang dang kan loei khráp", "อย่าเสียงดังกันเลยครับ",
 "Podstawy i grzeczność", "Konflikt", "sentence", 4, "n",
 "Podniesiony głos w Tajlandii kompromituje mówiącego, nie adresata. Warto to wiedzieć zawczasu.", "",
 ("Nie podnośmy głosu, ludzie patrzą.", "yàa sǐang dang kan loei khráp khon mawng yùu", "อย่าเสียงดังกันเลยครับ คนมองอยู่")),
("zachowajmy spokój", "jai yen yen wái kàwn ná khráp", "ใจเย็นๆ ไว้ก่อนนะครับ",
 "Podstawy i grzeczność", "Konflikt", "sentence", 5, "n", "", "",
 ("Zachowajmy spokój, krzykiem tego nie rozwiążemy.", "jai yen yen wái kàwn ná khráp sǐang dang kâw mâi chûai", "ใจเย็นๆ ไว้ก่อนนะครับ เสียงดังก็ไม่ช่วย")),
("to nie miejsce na taką rozmowę", "thîi nîi mâi mò jà khui rûeang níi khráp", "ที่นี่ไม่เหมาะจะคุยเรื่องนี้ครับ",
 "Praca i nauka", "Konflikt", "sentence", 3, "n", "", "",
 ("To nie miejsce na taką rozmowę, wejdźmy do środka.", "thîi nîi mâi mò jà khui rûeang níi khráp khâo khâang nai kan kàwn", "ที่นี่ไม่เหมาะจะคุยเรื่องนี้ครับ เข้าข้างในกันก่อน")),
("odłóżmy to do jutra", "phák rûeang níi wái phrûng-níi ná khráp", "พักเรื่องนี้ไว้พรุ่งนี้นะครับ",
 "Praca i nauka", "Konflikt", "sentence", 3, "n", "", "",
 ("Odłóżmy to do jutra, obaj jesteśmy zmęczeni.", "phák rûeang níi wái phrûng-níi ná khráp raw sǎwng khon kâw nùeai", "พักเรื่องนี้ไว้พรุ่งนี้นะครับ เราสองคนก็เหนื่อย")),
("nie chcę się kłócić", "phǒm mâi yàak thá-ló kan khráp", "ผมไม่อยากทะเลาะกันครับ",
 "Ludzie i rodzina", "Konflikt", "sentence", 4, "n", "", "",
 ("Nie chcę się kłócić, chcę to po prostu poukładać.", "phǒm mâi yàak thá-ló kan khráp khâe yàak hâi man riap ráwi", "ผมไม่อยากทะเลาะกันครับ แค่อยากให้มันเรียบร้อย")),
("obaj mamy trochę racji", "raw kâw thùuk kan khon lá khrûeng khráp", "เราก็ถูกกันคนละครึ่งครับ",
 "Cechy i opinie", "Konflikt", "sentence", 3, "n", "", "",
 ("Obaj mamy trochę racji, więc się dogadajmy.", "raw kâw thùuk kan khon lá khrûeng khráp maa tòk long kan", "เราก็ถูกกันคนละครึ่งครับ มาตกลงกัน")),
("zostawmy emocje na boku", "ao aa-rom àwk pai kàwn khráp", "เอาอารมณ์ออกไปก่อนครับ",
 "Praca i nauka", "Konflikt", "sentence", 3, "n", "", "",
 ("Zostawmy emocje na boku i spójrzmy na fakty.", "ao aa-rom àwk pai kàwn khráp duu khâw thét jing dii kwàa", "เอาอารมณ์ออกไปก่อนครับ ดูข้อเท็จจริงดีกว่า")),
("nie o to nam chodzi", "raw mâi dâai jà ao chá-ná kan khráp", "เราไม่ได้จะเอาชนะกันครับ",
 "Praca i nauka", "Konflikt", "sentence", 3, "n", "wygrać nad sobą nawzajem", "",
 ("Nie o to nam chodzi, żeby wygrać spór.", "raw mâi dâai jà ao chá-ná kan khráp", "เราไม่ได้จะเอาชนะกันครับ")),

# =====================================================================
# STAWIANIE GRANIC
# =====================================================================
("to przekracza moje możliwości", "man koen kam-lang phǒm khráp", "มันเกินกำลังผมครับ",
 "Praca i nauka", "Granice", "sentence", 4, "n", "przekracza moją siłę", "",
 ("To przekracza moje możliwości czasowe w tym miesiącu.", "duean níi man koen kam-lang phǒm khráp", "เดือนนี้มันเกินกำลังผมครับ")),
("mam już pełne ręce roboty", "ngaan phǒm nâen mâak láew khráp", "งานผมแน่นมากแล้วครับ",
 "Praca i nauka", "Granice", "sentence", 4, "n", "", "",
 ("Mam już pełne ręce roboty do końca tygodnia.", "ngaan phǒm nâen thǔeng sîn aa-thít láew khráp", "งานผมแน่นถึงสิ้นอาทิตย์แล้วครับ")),
("potrzebuję jasnych zasad", "khǎw kót thîi chát-jeen khráp", "ขอกฎที่ชัดเจนครับ", "Praca i nauka", "Granice", "sentence", 3, "n", "", "",
 ("Potrzebuję jasnych zasad, żeby uniknąć nieporozumień.", "khǎw kót thîi chát-jeen khráp jà dâai mâi khâo-jai phìt", "ขอกฎที่ชัดเจนครับ จะได้ไม่เข้าใจผิด")),
("proszę nie dzwonić po dwudziestej", "chûai yàa thoo lǎng sǎwng thûm ná khráp", "ช่วยอย่าโทรหลังสองทุ่มนะครับ",
 "Praca i nauka", "Granice", "sentence", 3, "n",
 "„sǎwng thûm” to 20:00. Tajski liczy godziny wieczorne osobno, warto to opanować.", "",
 ("Proszę nie dzwonić po dwudziestej, chyba że to pilne.", "chûai yàa thoo lǎng sǎwng thûm ná khráp yók wén rûeang dùan", "ช่วยอย่าโทรหลังสองทุ่มนะครับ ยกเว้นเรื่องด่วน")),
("to sprawa prywatna", "pen rûeang sùan tua khráp", "เป็นเรื่องส่วนตัวครับ", "Ludzie i rodzina", "Granice", "sentence", 4, "n",
 "Uprzejmy sposób zamknięcia wścibskiego pytania. Tajowie pytają o wiek, wagę i zarobki bez złych intencji.", "",
 ("To sprawa prywatna, wolałbym nie mówić.", "pen rûeang sùan tua khráp khǎw mâi bàwk dii kwàa", "เป็นเรื่องส่วนตัวครับ ขอไม่บอกดีกว่า")),
("wolałbym nie odpowiadać", "khǎw mâi tàwp dii kwàa khráp", "ขอไม่ตอบดีกว่าครับ", "Podstawy i grzeczność", "Granice", "sentence", 4, "n", "", "",
 ("Wolałbym nie odpowiadać na to pytanie.", "kham thǎam níi khǎw mâi tàwp dii kwàa khráp", "คำถามนี้ขอไม่ตอบดีกว่าครับ")),
("nie zgadzam się na takie traktowanie", "phǒm ráp kaan pà-tì-bàt bàep níi mâi dâai khráp", "ผมรับการปฏิบัติแบบนี้ไม่ได้ครับ",
 "Praca i nauka", "Granice", "sentence", 3, "f",
 "Mocne zdanie w rejestrze formalnym. Używaj świadomie — stawia sprawę na ostrzu noża.", "",
 ("Nie zgadzam się na takie traktowanie pracowników.", "phǒm ráp kaan pà-tì-bàt tàw phá-nák-ngaan bàep níi mâi dâai khráp", "ผมรับการปฏิบัติต่อพนักงานแบบนี้ไม่ได้ครับ")),
("proszę mówić do mnie spokojnie", "chûai phûut dûai dii dii ná khráp", "ช่วยพูดด้วยดีๆ นะครับ",
 "Podstawy i grzeczność", "Granice", "sentence", 4, "n", "", "",
 ("Proszę mówić do mnie spokojnie, wtedy się dogadamy.", "chûai phûut dûai dii dii ná khráp láew jà khui kan rúu rûeang", "ช่วยพูดด้วยดีๆ นะครับ แล้วจะคุยกันรู้เรื่อง")),

# =====================================================================
# EMOCJE POZYTYWNE
# =====================================================================
("kamień spadł mi z serca", "lǒng jai pai thii khráp", "โล่งใจไปทีครับ", "Cechy i opinie", "Emocje", "sentence", 4, "n",
 "IDIOM. „lǒng jai” = puste, przewiewne serce, czyli ulga. Bardzo częste w mowie.", "przewiewne serce",
 ("Kamień spadł mi z serca, wszystko się wyjaśniło.", "lǒng jai pai thii khráp thúk yàang chát láew", "โล่งใจไปทีครับ ทุกอย่างชัดแล้ว")),
("jestem naprawdę wdzięczny", "sâap súeng jing jing khráp", "ซาบซึ้งจริงๆ ครับ", "Cechy i opinie", "Emocje", "sentence", 3, "f",
 "„sâap súeng” to głębokie wzruszenie wdzięcznością, mocniejsze niż zwykłe „khàwp-khun”.", "",
 ("Jestem naprawdę wdzięczny za wszystko.", "sâap súeng jing jing khráp sǎm-ràp thúk yàang", "ซาบซึ้งจริงๆ ครับ สำหรับทุกอย่าง")),
("cieszę się razem z tobą", "dii jai dûai khráp", "ดีใจด้วยครับ", "Cechy i opinie", "Emocje", "sentence", 5, "n", "", "",
 ("Cieszę się razem z tobą, zasłużyłeś na to.", "dii jai dûai khráp khun sǒm khuan láew", "ดีใจด้วยครับ คุณสมควรแล้ว")),
("aż mnie zatkało", "thǔeng kàp phûut mâi àwk", "ถึงกับพูดไม่ออก", "Cechy i opinie", "Emocje", "sentence", 3, "p", "aż nie wychodzi mowa", "",
 ("Aż mnie zatkało, nie spodziewałem się.", "thǔeng kàp phûut mâi àwk mâi khâat khít maa kàwn", "ถึงกับพูดไม่ออก ไม่คาดคิดมาก่อน")),
("odetchnąłem z ulgą", "khôi yang chûa khûen nòi khráp", "ค่อยยังชั่วขึ้นหน่อยครับ",
 "Cechy i opinie", "Emocje", "sentence", 4, "n", "", "",
 ("Odetchnąłem z ulgą, kiedy oddzwonili.", "phaw khǎo thoo klàp maa kâw khôi yang chûa khûen khráp", "พอเขาโทรกลับมาก็ค่อยยังชั่วขึ้นครับ")),
("jestem z ciebie dumny", "phǒm phuum jai nai tua khun khráp", "ผมภูมิใจในตัวคุณครับ",
 "Ludzie i rodzina", "Emocje", "sentence", 3, "n", "", "",
 ("Jestem z ciebie dumny, świetnie to poprowadziłeś.", "phǒm phuum jai nai tua khun khráp khun tham dâai dii mâak", "ผมภูมิใจในตัวคุณครับ คุณทำได้ดีมาก")),
("mam dobre przeczucie", "rúu-sùek dii dii kàp rûeang níi khráp", "รู้สึกดีๆ กับเรื่องนี้ครับ",
 "Cechy i opinie", "Emocje", "sentence", 3, "n", "", "",
 ("Mam dobre przeczucie co do tego projektu.", "rúu-sùek dii dii kàp proo-jèk níi khráp", "รู้สึกดีๆ กับโปรเจกต์นี้ครับ")),

# =====================================================================
# EMOCJE TRUDNE
# =====================================================================
("mam tego dosyć", "phǒm thon mâi wǎi láew khráp", "ผมทนไม่ไหวแล้วครับ", "Cechy i opinie", "Emocje", "sentence", 4, "n",
 "„thon mâi wǎi” = nie mogę już wytrzymać. Sygnał, że cierpliwość naprawdę się skończyła.", "",
 ("Mam tego dosyć, muszę coś zmienić.", "phǒm thon mâi wǎi láew khráp tâwng plìan à-rai sák yàang", "ผมทนไม่ไหวแล้วครับ ต้องเปลี่ยนอะไรสักอย่าง")),
("jestem u kresu cierpliwości", "khwaam òt thon phǒm mòt láew khráp", "ความอดทนผมหมดแล้วครับ",
 "Cechy i opinie", "Emocje", "sentence", 3, "n", "", "",
 ("Jestem u kresu cierpliwości po trzech miesiącach.", "sǎam duean láew khwaam òt thon phǒm mòt khráp", "สามเดือนแล้วความอดทนผมหมดครับ")),
("czuję się zawiedziony", "phǒm phìt wǎng khráp", "ผมผิดหวังครับ", "Cechy i opinie", "Emocje", "sentence", 4, "n", "", "",
 ("Czuję się zawiedziony, liczyłem na coś innego.", "phǒm phìt wǎng khráp phǒm khâat wǎng ìik bàep", "ผมผิดหวังครับ ผมคาดหวังอีกแบบ")),
("to mnie stresuje", "man tham hâi phǒm khrîat khráp", "มันทำให้ผมเครียดครับ", "Zdrowie", "Emocje", "sentence", 4, "n", "", "",
 ("To mnie stresuje bardziej, niż się przyznaję.", "man tham hâi phǒm khrîat mâak kwàa thîi bàwk khráp", "มันทำให้ผมเครียดมากกว่าที่บอกครับ")),
("noszę to w sobie od dawna", "phǒm kèp wái nai jai maa naan láew khráp", "ผมเก็บไว้ในใจมานานแล้วครับ",
 "Cechy i opinie", "Emocje", "sentence", 3, "n",
 "„kèp wái nai jai” = trzymać w sercu. Tajowie często tak robią zamiast konfrontacji.", "",
 ("Noszę to w sobie od dawna, dlatego mówię teraz.", "phǒm kèp wái nai jai maa naan láew khráp thǔeng phûut tawn níi", "ผมเก็บไว้ในใจมานานแล้วครับ ถึงพูดตอนนี้")),
("jest mi po prostu smutno", "phǒm khâe rúu-sùek nòi jai khráp", "ผมแค่รู้สึกน้อยใจครับ",
 "Cechy i opinie", "Emocje", "sentence", 4, "n",
 "„nòi jai” to tajskie uczucie bez polskiego odpowiednika: żal, że nas pominięto lub nie doceniono.", "małe serce",
 ("Jest mi po prostu smutno, że nikt nie zapytał.", "phǒm khâe rúu-sùek nòi jai thîi mâi mii khrai thǎam khráp", "ผมแค่รู้สึกน้อยใจที่ไม่มีใครถามครับ")),
("potrzebuję chwili dla siebie", "khǎw wee-laa sùan tua sák nòi khráp", "ขอเวลาส่วนตัวสักหน่อยครับ",
 "Cechy i opinie", "Emocje", "sentence", 4, "n", "", "",
 ("Potrzebuję chwili dla siebie, zaraz wrócę.", "khǎw wee-laa sùan tua sák nòi khráp dǐao klàp maa", "ขอเวลาส่วนตัวสักหน่อยครับ เดี๋ยวกลับมา")),
("nie umiem tego opisać", "phǒm bàwk mâi thùuk khráp", "ผมบอกไม่ถูกครับ", "Cechy i opinie", "Emocje", "sentence", 4, "n", "", "",
 ("Nie umiem tego opisać, ale czuję, że coś nie tak.", "phǒm bàwk mâi thùuk khráp tàae rúu-sùek wâa man mâi chái", "ผมบอกไม่ถูกครับ แต่รู้สึกว่ามันไม่ใช่")),
("boję się, że będzie gorzej", "phǒm klua wâa man jà nàk kwàa doem khráp", "ผมกลัวว่ามันจะหนักกว่าเดิมครับ",
 "Cechy i opinie", "Emocje", "sentence", 3, "n", "", "",
 ("Boję się, że będzie gorzej, jeśli nic nie zrobimy.", "phǒm klua wâa man jà nàk kwàa doem thâa mâi tham à-rai khráp", "ผมกลัวว่ามันจะหนักกว่าเดิมถ้าไม่ทำอะไรครับ")),
("czuję się bezradny", "phǒm tham à-rai mâi thùuk loei khráp", "ผมทำอะไรไม่ถูกเลยครับ",
 "Cechy i opinie", "Emocje", "sentence", 3, "n", "", "",
 ("Czuję się bezradny w tej sytuacji.", "sà-thǎa-ná-kaan níi phǒm tham à-rai mâi thùuk loei khráp", "สถานการณ์นี้ผมทำอะไรไม่ถูกเลยครับ")),
("głowa mi pęka od tego", "khít jon pùat hǔa khráp", "คิดจนปวดหัวครับ", "Zdrowie", "Emocje", "sentence", 3, "p", "", "",
 ("Głowa mi pęka od tego, muszę odpocząć.", "khít jon pùat hǔa khráp tâwng phák kàwn", "คิดจนปวดหัวครับ ต้องพักก่อน")),
("odpuszczam, nie warto", "chàng man thòe mâi khúm khráp", "ช่างมันเถอะ ไม่คุ้มครับ",
 "Cechy i opinie", "Emocje", "sentence", 4, "p",
 "„chàng man” = odpuść, nieważne. Bardzo tajskie podejście, blisko „mâi pen rai”.", "",
 ("Odpuszczam, nie warto się tym zamęczać.", "chàng man thòe khráp mâi khúm thîi jà khrîat", "ช่างมันเถอะครับ ไม่คุ้มที่จะเครียด")),
]
