# -*- coding: utf-8 -*-
"""Leksyka etapu 3 (A2) — czesc B.

Zakres: hotel i problemy z pokojem, transport lokalny, ustalanie spotkan,
telefon i internet.

Format krotki jak w lex_a2_core_a.py.
"""

CORE_B = [

# =====================================================================
# HOTEL — meldunek, pokoj, obsluga
# =====================================================================
("Rezerwowałem przez internet.", "phǒm jawng phàan in-təə-nét khráp", "ผมจองผ่านอินเทอร์เน็ตครับ",
 "Hotel", "Meldunek", "phrase", 4, "n", "„phàan” = przez, za pośrednictwem.", "",
 ("Poproszę numer rezerwacji.", "khǎw mǎai lêek kaan jawng khráp", "ขอหมายเลขการจองครับ")),
("Czy mogę zameldować się wcześniej?", "chék-in kàwn wee-laa dâai mǎi khráp",
 "เช็คอินก่อนเวลาได้ไหมครับ", "Hotel", "Meldunek", "question", 4, "n", "", "kàwn wee-laa = przed czasem",
 ("Pokój będzie gotowy o dwunastej.", "hâwng phráwm tawn thîang khráp", "ห้องพร้อมตอนเที่ยงครับ")),
("Czy mogę wymeldować się później?", "chék-áo cháa kwàa dâai mǎi khráp", "เช็คเอาท์ช้ากว่าได้ไหมครับ",
 "Hotel", "Meldunek", "question", 4, "n", "", "",
 ("Do drugiej bez dopłaty.", "thǔeng bàai sǎwng mâi mii khâa chái jàai khráp",
  "ถึงบ่ายสองไม่มีค่าใช้จ่ายครับ")),
("Poproszę pokój na wyższym piętrze.", "khǎw hâwng chán sǔung nòi khráp", "ขอห้องชั้นสูงหน่อยครับ",
 "Hotel", "Pokój", "phrase", 3, "n", "", "chán = piętro",
 ("Mam pokój na siódmym.", "mii hâwng chán jèt khráp", "มีห้องชั้นเจ็ดครับ")),
("Poproszę cichy pokój.", "khǎw hâwng thîi ngîap nòi khráp", "ขอห้องที่เงียบหน่อยครับ",
 "Hotel", "Pokój", "phrase", 4, "n", "„ngîap” = cichy.", "",
 ("Damy od podwórza.", "jà hâi hâwng dâan lǎng khráp", "จะให้ห้องด้านหลังครับ")),
("Poproszę pokój z widokiem na morze.", "khǎw hâwng wiu thá-lee khráp", "ขอห้องวิวทะเลครับ",
 "Hotel", "Pokój", "phrase", 3, "n", "", "wiu = widok",
 ("Dopłata pięćset batów.", "phôoem hâa ráwi bàat khráp", "เพิ่มห้าร้อยบาทครับ")),
("Czy pokój ma balkon?", "hâwng mii rá-biang mǎi khráp", "ห้องมีระเบียงไหมครับ",
 "Hotel", "Pokój", "question", 3, "n", "", "",
 ("Ma mały balkon.", "mii rá-biang lék khráp", "มีระเบียงเล็กครับ")),
("Czy mogę zobaczyć pokój?", "khǎw duu hâwng kàwn dâai mǎi khráp", "ขอดูห้องก่อนได้ไหมครับ",
 "Hotel", "Pokój", "question", 4, "n", "", "",
 ("Zapraszam.", "choen khráp", "เชิญครับ")),
("Ten pokój mi nie odpowiada.", "hâwng níi mâi khâwi thùuk jai khráp", "ห้องนี้ไม่ค่อยถูกใจครับ",
 "Hotel", "Pokój", "phrase", 3, "n", "„thùuk jai” = przypaść do gustu.", "",
 ("Pokażę inny.", "dǐao hâi duu hâwng ùen khráp", "เดี๋ยวให้ดูห้องอื่นครับ")),
("Czy można zmienić pokój?", "plìan hâwng dâai mǎi khráp", "เปลี่ยนห้องได้ไหมครับ",
 "Hotel", "Problemy", "question", 4, "n", "", "",
 ("Sprawdzę wolne pokoje.", "khǎw chék hâwng wâang khráp", "ขอเช็คห้องว่างครับ")),

# ------------------------------------------------- problemy z pokojem
("Klimatyzacja hałasuje.", "ae sǐang dang khráp", "แอร์เสียงดังครับ",
 "Hotel", "Problemy", "phrase", 3, "n", "„sǐang dang” = głośny dźwięk.", "",
 ("Wyślę technika.", "jà sòng châang pai khráp", "จะส่งช่างไปครับ")),
("Nie działa wi-fi w pokoju.", "wai-faai nai hâwng chái mâi dâai khráp", "ไวไฟในห้องใช้ไม่ได้ครับ",
 "Hotel", "Problemy", "phrase", 5, "n", "„chái mâi dâai” = nie da się używać.", "",
 ("Podam nowe hasło.", "dǐao hâi phâat-woet mài khráp", "เดี๋ยวให้พาสเวิร์ดใหม่ครับ")),
("Nie mogę otworzyć drzwi.", "pòet prà-tuu mâi dâai khráp", "เปิดประตูไม่ได้ครับ",
 "Hotel", "Problemy", "phrase", 4, "n", "", "",
 ("Zaraz przyjdę.", "dǐao khûen pai khráp", "เดี๋ยวขึ้นไปครับ")),
("Karta do drzwi nie działa.", "khaat prà-tuu chái mâi dâai khráp", "การ์ดประตูใช้ไม่ได้ครับ",
 "Hotel", "Problemy", "phrase", 4, "n", "", "",
 ("Wyrobię nową.", "dǐao tham bai mài hâi khráp", "เดี๋ยวทำใบใหม่ให้ครับ")),
("Zgubiłem klucz do pokoju.", "phǒm tham kunjae hâwng hǎai khráp", "ผมทำกุญแจห้องหายครับ",
 "Hotel", "Problemy", "phrase", 3, "n", "„tham … hǎai” = zgubić coś.", "tham hǎai = zgubić",
 ("Poproszę dokument.", "khǎw bàt prà-chaa-chon khráp", "ขอบัตรประชาชนครับ")),
("Zatrzasnąłem klucz w pokoju.", "phǒm luem kunjae wái nai hâwng khráp", "ผมลืมกุญแจไว้ในห้องครับ",
 "Hotel", "Problemy", "phrase", 3, "n", "", "",
 ("Otworzę pokój.", "dǐao pòet hâwng hâi khráp", "เดี๋ยวเปิดห้องให้ครับ")),
("W łazience nie ma ciepłej wody.", "nai hâwng náam mâi mii náam ùn khráp", "ในห้องน้ำไม่มีน้ำอุ่นครับ",
 "Hotel", "Problemy", "phrase", 4, "n", "„náam ùn” = woda ciepła, letnia.", "",
 ("Przepraszam, sprawdzimy.", "khǎw-thôot khráp dǐao chék hâi", "ขอโทษครับ เดี๋ยวเช็คให้")),
("Toaleta jest zatkana.", "sûam tan khráp", "ส้วมตันครับ",
 "Hotel", "Problemy", "phrase", 3, "n", "„tan” = zatkany.", "",
 ("Zaraz kogoś przyślę.", "dǐao sòng khon pai khráp", "เดี๋ยวส่งคนไปครับ")),
("Prysznic cieknie.", "fàk bua rûa khráp", "ฝักบัวรั่วครับ",
 "Hotel", "Problemy", "phrase", 3, "n", "„rûa” = przeciekać.", "",
 ("Naprawimy dzisiaj.", "wan níi jà sâwm hâi khráp", "วันนี้จะซ่อมให้ครับ")),
("Nie ma ręczników.", "mâi mii phâa chét tua khráp", "ไม่มีผ้าเช็ดตัวครับ",
 "Hotel", "Problemy", "phrase", 4, "n", "", "",
 ("Przyniosę dwa.", "dǐao ao pai hâi sǎwng phǔen khráp", "เดี๋ยวเอาไปให้สองผืนครับ")),
("Pościel nie jest czysta.", "phâa puu thîi nawn mâi sà-àat khráp", "ผ้าปูที่นอนไม่สะอาดครับ",
 "Hotel", "Problemy", "phrase", 3, "n", "", "",
 ("Wymienimy od razu.", "dǐao plìan hâi loei khráp", "เดี๋ยวเปลี่ยนให้เลยครับ")),
("W pokoju jest brudno.", "hâwng mâi sà-àat khráp", "ห้องไม่สะอาดครับ",
 "Hotel", "Problemy", "phrase", 3, "n", "", "",
 ("Poślę sprzątaczkę.", "dǐao hâi mâe bâan khûen pai khráp", "เดี๋ยวให้แม่บ้านขึ้นไปครับ")),
("W pokoju są komary.", "nai hâwng mii yung khráp", "ในห้องมียุงครับ",
 "Hotel", "Problemy", "phrase", 4, "n", "", "",
 ("Dam spray.", "dǐao ao yaa kan yung pai hâi khráp", "เดี๋ยวเอายากันยุงไปให้ครับ")),
("Sąsiedzi są bardzo głośni.", "hâwng khâang khâang sǐang dang mâak khráp", "ห้องข้างๆ เสียงดังมากครับ",
 "Hotel", "Problemy", "phrase", 3, "n", "", "khâang khâang = obok, sąsiedni",
 ("Zwrócimy im uwagę.", "dǐao pai bàwk hâi khráp", "เดี๋ยวไปบอกให้ครับ")),
("Proszę posprzątać pokój.", "chûai tham khwaam sà-àat hâwng nòi khráp",
 "ช่วยทำความสะอาดห้องหน่อยครับ", "Hotel", "Obsługa", "phrase", 4, "n", "", "",
 ("O której godzinie?", "kìi moong dii khráp", "กี่โมงดีครับ")),
("Proszę dziś nie sprzątać.", "wan níi mâi tâwng tham khwaam sà-àat khráp",
 "วันนี้ไม่ต้องทำความสะอาดครับ", "Hotel", "Obsługa", "phrase", 3, "n", "", "",
 ("Dobrze, zanotuję.", "dâai khráp jà jòt wái", "ได้ครับ จะจดไว้")),
("Poproszę o pranie.", "khǎw sák phâa khráp", "ขอซักผ้าครับ",
 "Hotel", "Obsługa", "phrase", 3, "n", "„sák phâa” = prać ubrania.", "",
 ("Na kiedy?", "ao mûea-rài khráp", "เอาเมื่อไหร่ครับ")),
("Kiedy będzie gotowe?", "sèt mûea-rài khráp", "เสร็จเมื่อไหร่ครับ",
 "Hotel", "Obsługa", "question", 4, "n", "", "",
 ("Jutro rano.", "phrûng níi cháo khráp", "พรุ่งนี้เช้าครับ")),
("Czy mogę zamówić coś do pokoju?", "sàng aa-hǎan khûen hâwng dâai mǎi khráp",
 "สั่งอาหารขึ้นห้องได้ไหมครับ", "Hotel", "Obsługa", "question", 3, "n", "", "",
 ("Do dwudziestej drugiej.", "thǔeng sǎwng thûm khráp", "ถึงสองทุ่มครับ")),
("Poproszę o taksówkę na siódmą.", "chûai rîak tháek-sîi tawn jèt moong khráp",
 "ช่วยเรียกแท็กซี่ตอนเจ็ดโมงครับ", "Hotel", "Obsługa", "phrase", 4, "n", "„rîak” = wezwać.", "",
 ("Zamówione.", "jawng hâi láew khráp", "จองให้แล้วครับ")),

# ------------------------------------------------- slownictwo hotelowe
("piętro", "chán", "ชั้น", "Hotel", "Wyposażenie", "word", 4, "n",
 "To samo słowo znaczy „półka” i „klasa”.", "",
 ("Na którym piętrze?", "chán nǎi khráp", "ชั้นไหนครับ")),
("recepcja", "phà-nàek tâwn ráp", "แผนกต้อนรับ", "Hotel", "Wyposażenie", "word", 4, "f", "", "",
 ("Gdzie jest recepcja?", "WHERE")),
("sprzątaczka", "mâe bâan", "แม่บ้าน", "Hotel", "Ludzie", "word", 3, "n", "", "dosłownie: matka domu",
 ("Sprzątaczka już była.", "mâe bâan maa láew khráp", "แม่บ้านมาแล้วครับ")),
("kaucja", "ngoen mát jam", "เงินมัดจำ", "Hotel", "Płatności", "word", 3, "f", "", "",
 ("Ile wynosi kaucja?", "HOWMUCH")),
("sejf", "tûu sép", "ตู้เซฟ", "Hotel", "Wyposażenie", "word", 3, "n", "", "",
 ("Czy w pokoju jest sejf?", "HAVE")),
("lodówka w pokoju", "tûu yen nai hâwng", "ตู้เย็นในห้อง", "Hotel", "Wyposażenie", "word", 3, "n", "", "",
 ("Czy jest lodówka?", "HAVE")),
("balkon", "rá-biang", "ระเบียง", "Hotel", "Wyposażenie", "word", 3, "n", "", "",
 ("Balkon jest mały.", "rá-biang lék khráp", "ระเบียงเล็กครับ")),
("widok", "wiu", "วิว", "Hotel", "Wyposażenie", "word", 3, "n", "", "",
 ("Widok jest piękny.", "wiu sǔai mâak khráp", "วิวสวยมากครับ")),
("siłownia", "fít-nét", "ฟิตเนส", "Hotel", "Wyposażenie", "word", 2, "n", "", "",
 ("Gdzie jest siłownia?", "WHERE")),
("śniadanie w hotelu", "aa-hǎan cháo khǎwng roong-raem", "อาหารเช้าของโรงแรม",
 "Hotel", "Wyżywienie", "word", 4, "n", "", "",
 ("O której jest śniadanie?", "aa-hǎan cháo kìi moong khráp", "อาหารเช้ากี่โมงครับ")),

# =====================================================================
# TRANSPORT LOKALNY
# =====================================================================
("Ile kosztuje kurs do centrum?", "pai nai mueang thâo-rài khráp", "ไปในเมืองเท่าไหร่ครับ",
 "Transport", "Taksówka", "question", 5, "n", "„nai mueang” = do miasta, do centrum.", "",
 ("Dwieście batów.", "sǎwng ráwi bàat khráp", "สองร้อยบาทครับ")),
("Proszę włączyć taksometr.", "chûai pòet mí-tôe dûai khráp", "ช่วยเปิดมิเตอร์ด้วยครับ",
 "Transport", "Taksówka", "phrase", 5, "n",
 "Kluczowy zwrot: bez taksometru kierowca poda cenę z sufitu.", "mí-tôe = taksometr",
 ("Już włączony.", "pòet láew khráp", "เปิดแล้วครับ")),
("Bez taksometru nie jadę.", "mâi pòet mí-tôe phǒm mâi pai khráp", "ไม่เปิดมิเตอร์ผมไม่ไปครับ",
 "Transport", "Taksówka", "phrase", 3, "n", "", "",
 ("Dobrze, włączam.", "dâai khráp pòet hâi", "ได้ครับ เปิดให้")),
("Proszę tutaj skręcić w lewo.", "chûai líao sáai trong níi khráp", "ช่วยเลี้ยวซ้ายตรงนี้ครับ",
 "Transport", "Kierunki", "phrase", 4, "n", "", "líao = skręcać",
 ("Tutaj?", "trong níi rǔe khráp", "ตรงนี้หรือครับ")),
("Proszę tutaj skręcić w prawo.", "chûai líao khwǎa trong níi khráp", "ช่วยเลี้ยวขวาตรงนี้ครับ",
 "Transport", "Kierunki", "phrase", 4, "n", "", "",
 ("Rozumiem.", "khâo-jai khráp", "เข้าใจครับ")),
("Proszę jechać prosto.", "chûai trong pai khráp", "ช่วยตรงไปครับ",
 "Transport", "Kierunki", "phrase", 4, "n", "", "",
 ("Jak daleko?", "ìik klai mǎi khráp", "อีกไกลไหมครับ")),
("Proszę się zatrzymać tutaj.", "jàwt trong níi khráp", "จอดตรงนี้ครับ",
 "Transport", "Taksówka", "phrase", 5, "n", "„jàwt” = zaparkować, zatrzymać.", "",
 ("Dobrze.", "dâai khráp", "ได้ครับ")),
("Proszę zatrzymać się za rogiem.", "jàwt loei hǔa mum khráp", "จอดเลยหัวมุมครับ",
 "Transport", "Taksówka", "phrase", 3, "n", "„loei” tu znaczy „za, dalej niż”.", "hǔa mum = róg ulicy",
 ("Rozumiem.", "khâo-jai khráp", "เข้าใจครับ")),
("Proszę jechać wolniej.", "chûai khàp cháa cháa nòi khráp", "ช่วยขับช้าๆ หน่อยครับ",
 "Transport", "Taksówka", "phrase", 4, "n", "Podwojenie „cháa cháa” łagodzi polecenie.", "",
 ("Dobrze.", "dâai khráp", "ได้ครับ")),
("Śpieszę się.", "phǒm rîip khráp", "ผมรีบครับ",
 "Transport", "Taksówka", "phrase", 4, "n", "„rîip” = śpieszyć się.", "",
 ("Poszukam skrótu.", "jà pai thaang lát khráp", "จะไปทางลัดครับ")),
("Którędy najszybciej?", "thaang nǎi reo thîi sùt khráp", "ทางไหนเร็วที่สุดครับ",
 "Transport", "Kierunki", "question", 3, "n", "", "",
 ("Autostradą.", "pai thaang dùan khráp", "ไปทางด่วนครับ")),
("Czy jedziemy autostradą?", "khûen thaang dùan mǎi khráp", "ขึ้นทางด่วนไหมครับ",
 "Transport", "Taksówka", "question", 3, "n", "„thaang dùan” = droga ekspresowa.", "",
 ("Jest szybciej.", "reo kwàa khráp", "เร็วกว่าครับ")),
("Kto płaci za opłatę drogową?", "khâa thaang dùan khrai jàai khráp", "ค่าทางด่วนใครจ่ายครับ",
 "Transport", "Taksówka", "question", 3, "n", "", "",
 ("Zwykle pasażer.", "phûu doi-sǎan jàai khráp", "ผู้โดยสารจ่ายครับ")),
("Jest duży korek.", "rót tìt mâak khráp", "รถติดมากครับ",
 "Transport", "Ruch drogowy", "phrase", 5, "n", "„rót tìt” = korek uliczny.", "",
 ("Będziemy stać długo.", "khong naan khráp", "คงนานครับ")),
("Wysiądę tutaj.", "phǒm long trong níi khráp", "ผมลงตรงนี้ครับ",
 "Transport", "Podróż", "phrase", 4, "n", "„long” = wysiadać, schodzić.", "",
 ("Uważaj na motory.", "rá-wang rót maw-toe-sai khráp", "ระวังรถมอเตอร์ไซค์ครับ")),
("Gdzie mam wysiąść?", "phǒm khuan long thîi nǎi khráp", "ผมควรลงที่ไหนครับ",
 "Transport", "Podróż", "question", 4, "n", "„khuan” = powinienem.", "",
 ("Na następnym przystanku.", "long pâai nâa khráp", "ลงป้ายหน้าครับ")),
("Proszę mi powiedzieć, gdzie wysiąść.", "chûai bàwk dûai wâa long thîi nǎi khráp",
 "ช่วยบอกด้วยว่าลงที่ไหนครับ", "Transport", "Podróż", "phrase", 4, "n", "", "",
 ("Powiem ci.", "dǐao bàwk khráp", "เดี๋ยวบอกครับ")),
("Ile przystanków jeszcze?", "ìik kìi pâai khráp", "อีกกี่ป้ายครับ",
 "Transport", "Podróż", "question", 3, "n", "„pâai” = przystanek, tablica.", "",
 ("Jeszcze trzy.", "ìik sǎam pâai khráp", "อีกสามป้ายครับ")),
("Czy ten autobus jedzie na dworzec?", "rót khan níi pai sà-thǎa-nii mǎi khráp",
 "รถคันนี้ไปสถานีไหมครับ", "Transport", "Autobus", "question", 4, "n", "„khan” to słowo miarowe do pojazdów.", "",
 ("Jedzie.", "pai khráp", "ไปครับ")),
("Gdzie kupię bilet?", "súe tǔa dâai thîi nǎi khráp", "ซื้อตั๋วได้ที่ไหนครับ",
 "Transport", "Bilety", "question", 4, "n", "", "",
 ("W kasie na dole.", "thîi châwng khǎai tǔa chán lâang khráp", "ที่ช่องขายตั๋วชั้นล่างครับ")),
("Poproszę bilet w jedną stronę.", "khǎw tǔa thîao diao khráp", "ขอตั๋วเที่ยวเดียวครับ",
 "Transport", "Bilety", "phrase", 4, "n", "", "thîao diao = jeden kurs",
 ("Do której stacji?", "thǔeng sà-thǎa-nii nǎi khráp", "ถึงสถานีไหนครับ")),
("Poproszę bilet powrotny.", "khǎw tǔa pai klàp khráp", "ขอตั๋วไปกลับครับ",
 "Transport", "Bilety", "phrase", 4, "n", "", "pai klàp = tam i z powrotem",
 ("Na kiedy powrót?", "klàp wan nǎi khráp", "กลับวันไหนครับ")),
("O której odjeżdża?", "àwk kìi moong khráp", "ออกกี่โมงครับ",
 "Transport", "Rozkład", "question", 5, "n", "„àwk” = wyruszać, wychodzić.", "",
 ("Za piętnaście minut.", "ìik sìp-hâa naa-thii khráp", "อีกสิบห้านาทีครับ")),
("O której przyjeżdża?", "thǔeng kìi moong khráp", "ถึงกี่โมงครับ",
 "Transport", "Rozkład", "question", 5, "n", "„thǔeng” = dotrzeć, przybyć.", "",
 ("Około południa.", "prà-maan thîang khráp", "ประมาณเที่ยงครับ")),
("Spóźniłem się na autobus.", "phǒm tòk rót khráp", "ผมตกรถครับ",
 "Transport", "Problemy", "phrase", 3, "n", "„tòk rót” = nie zdążyć na pojazd.", "dosłownie: spaść z pojazdu",
 ("Następny za godzinę.", "khan tàw pai ìik nùeng chûa moong khráp", "คันต่อไปอีกหนึ่งชั่วโมงครับ")),
("Autobus ma opóźnienie.", "rót maa cháa khráp", "รถมาช้าครับ",
 "Transport", "Problemy", "phrase", 3, "n", "", "",
 ("Jak długo?", "cháa thâo-rài khráp", "ช้าเท่าไหร่ครับ")),
("Pomyliłem kierunek.", "phǒm khûen phìt thaang khráp", "ผมขึ้นผิดทางครับ",
 "Transport", "Problemy", "phrase", 3, "n", "„phìt” = błędny, nie ten.", "",
 ("Wysiądź i wróć.", "long láew klàp maa khráp", "ลงแล้วกลับมาครับ")),
("Wynajmę skuter na jeden dzień.", "phǒm khǎw châo maw-toe-sai nùeng wan khráp",
 "ผมขอเช่ามอเตอร์ไซค์หนึ่งวันครับ", "Transport", "Wynajem", "phrase", 4, "n", "„châo” = wynajmować.", "",
 ("Poproszę paszport.", "khǎw phaas-pàwt khráp", "ขอพาสปอร์ตครับ")),
("Czy kask jest w cenie?", "mùak kan náwk ruam mǎi khráp", "หมวกกันน็อกรวมไหมครับ",
 "Transport", "Wynajem", "question", 3, "n", "", "mùak kan náwk = kask",
 ("Tak, dwa kaski.", "ruam khráp sǎwng bai", "รวมครับ สองใบ")),
("Ile kosztuje paliwo?", "khâa náam man thâo-rài khráp", "ค่าน้ำมันเท่าไหร่ครับ",
 "Transport", "Wynajem", "question", 3, "n", "", "náam man = paliwo, olej",
 ("Bak kosztuje sto batów.", "tem thǎng ráwi nùeng khráp", "เต็มถังร้อยหนึ่งครับ")),
("Gdzie mogę zaparkować?", "jàwt rót dâai thîi nǎi khráp", "จอดรถได้ที่ไหนครับ",
 "Transport", "Parkowanie", "question", 4, "n", "", "",
 ("Za budynkiem.", "dâan lǎng tùek khráp", "ด้านหลังตึกครับ")),
("Czy parkowanie jest płatne?", "jàwt rót sǐa taang mǎi khráp", "จอดรถเสียตังค์ไหมครับ",
 "Transport", "Parkowanie", "question", 3, "p", "„sǐa taang” to potoczne „kosztuje”.", "",
 ("Pierwsza godzina gratis.", "chûa moong râek frii khráp", "ชั่วโมงแรกฟรีครับ")),

# ------------------------------------------------- slownictwo transportowe
("kierowca", "khon khàp rót", "คนขับรถ", "Transport", "Ludzie", "word", 4, "n", "", "",
 ("Gdzie jest kierowca?", "WHERE")),
("pasażer", "phûu doi-sǎan", "ผู้โดยสาร", "Transport", "Ludzie", "word", 3, "f", "", "",
 ("Ilu jest pasażerów?", "mii phûu doi-sǎan kìi khon khráp", "มีผู้โดยสารกี่คนครับ")),
("przystanek", "pâai rót", "ป้ายรถ", "Transport", "Miejsca", "word", 4, "n", "", "",
 ("Gdzie jest przystanek?", "WHERE")),
("stacja", "sà-thǎa-nii", "สถานี", "Transport", "Miejsca", "word", 5, "n", "", "",
 ("Gdzie jest stacja?", "WHERE")),
("peron", "chaan chaa-laa", "ชานชาลา", "Transport", "Miejsca", "word", 2, "f", "", "",
 ("Który peron?", "chaan chaa-laa nǎi khráp", "ชานชาลาไหนครับ")),
("kolejka miejska", "rót fai fáa", "รถไฟฟ้า", "Transport", "Środki transportu", "word", 4, "n",
 "Bangkockie BTS i MRT; dosłownie „pociąg elektryczny”.", "",
 ("Pojadę kolejką.", "phǒm jà pai rót fai fáa khráp", "ผมจะไปรถไฟฟ้าครับ")),
("prom", "ruea khâam fâak", "เรือข้ามฟาก", "Transport", "Środki transportu", "word", 3, "n", "", "",
 ("Gdzie jest prom?", "WHERE")),
("motocykl", "maw-toe-sai", "มอเตอร์ไซค์", "Transport", "Środki transportu", "word", 5, "n", "", "",
 ("Pojadę motocyklem.", "phǒm jà pai maw-toe-sai khráp", "ผมจะไปมอเตอร์ไซค์ครับ")),
("kask", "mùak kan náwk", "หมวกกันน็อก", "Transport", "Wyposażenie", "word", 4, "n", "", "",
 ("Poproszę kask.", "ORDER")),
("bilet", "tǔa", "ตั๋ว", "Transport", "Bilety", "word", 5, "n", "", "",
 ("Poproszę bilet.", "ORDER")),
("opłata", "khâa", "ค่า", "Transport", "Bilety", "word", 5, "n",
 "„khâa” przed rzeczownikiem tworzy nazwę opłaty: khâa rót = opłata za przejazd.", "khâa = koszt czegoś",
 ("Jaka jest opłata?", "khâa thâo-rài khráp", "ค่าเท่าไหร่ครับ")),
("rozkład jazdy", "taa-raang wee-laa", "ตารางเวลา", "Transport", "Rozkład", "word", 3, "f", "", "",
 ("Gdzie jest rozkład jazdy?", "WHERE")),
("opóźnienie", "kaan cháa", "การช้า", "Transport", "Problemy", "word", 2, "f",
 "„kaan” tworzy rzeczowniki odczasownikowe.", "kaan + czasownik = -anie",
 ("Czy jest opóźnienie?", "HAVE")),

# =====================================================================
# USTALANIE SPOTKAN
# =====================================================================
("Spotkajmy się jutro.", "phrûng níi jôe kan ná khráp", "พรุ่งนี้เจอกันนะครับ",
 "Czas i daty", "Spotkania", "phrase", 5, "i", "„jôe kan” = spotkać się.", "",
 ("O której?", "kìi moong khráp", "กี่โมงครับ")),
("O której się spotkamy?", "jôe kan kìi moong dii khráp", "เจอกันกี่โมงดีครับ",
 "Czas i daty", "Spotkania", "question", 5, "n",
 "„… dii khráp” na końcu pytania znaczy „jak będzie najlepiej?”.", "",
 ("Może o szóstej.", "hòk moong yen dii mǎi khráp", "หกโมงเย็นดีไหมครับ")),
("Pasuje ci o siódmej?", "nùeng thûm dâai mǎi khráp", "หนึ่งทุ่มได้ไหมครับ",
 "Czas i daty", "Spotkania", "question", 4, "i",
 "„thûm” liczy godziny wieczorne: nùeng thûm = 19:00.", "",
 ("Pasuje.", "dâai khráp", "ได้ครับ")),
("Może być trochę później?", "cháa kwàa nít nòi dâai mǎi khráp", "ช้ากว่านิดหน่อยได้ไหมครับ",
 "Czas i daty", "Spotkania", "question", 4, "n", "", "",
 ("Jasne.", "dâai khráp", "ได้ครับ")),
("Wcześniej mi nie pasuje.", "reo kwàa níi mâi dâai khráp", "เร็วกว่านี้ไม่ได้ครับ",
 "Czas i daty", "Spotkania", "phrase", 3, "n", "", "",
 ("To niech będzie później.", "ngán cháa kwàa kâw dâai khráp", "งั้นช้ากว่าก็ได้ครับ")),
("Gdzie się spotkamy?", "jôe kan thîi nǎi dii khráp", "เจอกันที่ไหนดีครับ",
 "Czas i daty", "Spotkania", "question", 5, "n", "", "",
 ("Przed hotelem.", "nâa roong-raem khráp", "หน้าโรงแรมครับ")),
("Spotkajmy się przed wejściem.", "jôe kan nâa thaang khâo khráp", "เจอกันหน้าทางเข้าครับ",
 "Czas i daty", "Spotkania", "phrase", 4, "n", "", "thaang khâo = wejście",
 ("Będę czekał.", "phǒm jà raw khráp", "ผมจะรอครับ")),
("Będę punktualnie.", "phǒm jà maa trong wee-laa khráp", "ผมจะมาตรงเวลาครับ",
 "Czas i daty", "Spotkania", "phrase", 4, "n", "„trong wee-laa” = punktualnie.", "",
 ("Świetnie.", "dii khráp", "ดีครับ")),
("Spóźnię się dziesięć minut.", "phǒm jà cháa sìp naa-thii khráp", "ผมจะช้าสิบนาทีครับ",
 "Czas i daty", "Spotkania", "phrase", 4, "n", "", "",
 ("Poczekam.", "phǒm raw dâai khráp", "ผมรอได้ครับ")),
("Muszę przełożyć spotkanie.", "phǒm tâwng lûean nát khráp", "ผมต้องเลื่อนนัดครับ",
 "Czas i daty", "Spotkania", "phrase", 3, "f", "„lûean nát” = przełożyć umówione spotkanie.", "",
 ("Na kiedy?", "lûean pen wan nǎi khráp", "เลื่อนเป็นวันไหนครับ")),
("Przepraszam, muszę odwołać.", "khǎw-thôot khráp phǒm tâwng yók-lôek", "ขอโทษครับ ผมต้องยกเลิก",
 "Czas i daty", "Spotkania", "phrase", 3, "f", "", "",
 ("Nie ma sprawy.", "mâi pen rai khráp", "ไม่เป็นไรครับ")),
("Może w przyszłym tygodniu?", "aa-thít nâa dâai mǎi khráp", "อาทิตย์หน้าได้ไหมครับ",
 "Czas i daty", "Spotkania", "question", 4, "n", "„nâa” po jednostce czasu = przyszły.", "",
 ("Pasuje mi.", "dâai khráp", "ได้ครับ")),
("Który dzień ci pasuje?", "wan nǎi sà-dùak khráp", "วันไหนสะดวกครับ",
 "Czas i daty", "Spotkania", "question", 4, "n", "„sà-dùak” = wygodny, dogodny.", "",
 ("Sobota.", "wan sǎo khráp", "วันเสาร์ครับ")),
("Jestem wolny cały dzień.", "phǒm wâang tháng wan khráp", "ผมว่างทั้งวันครับ",
 "Czas i daty", "Spotkania", "phrase", 4, "n", "", "",
 ("To wybierz godzinę.", "ngán lûeak wee-laa loei khráp", "งั้นเลือกเวลาเลยครับ")),
("Nie mam czasu w ten weekend.", "sǎo aa-thít níi phǒm mâi wâang khráp", "เสาร์อาทิตย์นี้ผมไม่ว่างครับ",
 "Czas i daty", "Spotkania", "phrase", 4, "n", "", "",
 ("To za tydzień.", "ngán aa-thít nâa khráp", "งั้นอาทิตย์หน้าครับ")),
("Potwierdzę wieczorem.", "dǐao yuen-yan tawn yen khráp", "เดี๋ยวยืนยันตอนเย็นครับ",
 "Czas i daty", "Spotkania", "phrase", 3, "f", "„yuen-yan” = potwierdzić.", "",
 ("Czekam na wiadomość.", "raw khâw-khwaam khráp", "รอข้อความครับ")),
("Umówione.", "nát wái láew khráp", "นัดไว้แล้วครับ",
 "Czas i daty", "Spotkania", "phrase", 4, "n", "", "",
 ("Do zobaczenia.", "jôe kan khráp", "เจอกันครับ")),

# =====================================================================
# TELEFON I INTERNET
# =====================================================================
("Zadzwonię do ciebie później.", "dǐao phǒm thoo pai mài khráp", "เดี๋ยวผมโทรไปใหม่ครับ",
 "Praca i nauka", "Telefon", "phrase", 5, "n", "„dǐao” = zaraz, za chwilę.", "",
 ("Dobrze, czekam.", "dâai khráp raw yùu", "ได้ครับ รออยู่")),
("Nie słyszę cię dobrze.", "phǒm dâi yin mâi chát khráp", "ผมได้ยินไม่ชัดครับ",
 "Praca i nauka", "Telefon", "phrase", 4, "n", "„chát” = wyraźny.", "dâi yin = słyszeć",
 ("Zadzwonię jeszcze raz.", "dǐao thoo mài khráp", "เดี๋ยวโทรใหม่ครับ")),
("Zasięg jest słaby.", "sǎn-yaan mâi dii khráp", "สัญญาณไม่ดีครับ",
 "Praca i nauka", "Telefon", "phrase", 4, "n", "„sǎn-yaan” = sygnał, zasięg.", "",
 ("Wyjdę na zewnątrz.", "dǐao àwk pai khâang nâwk khráp", "เดี๋ยวออกไปข้างนอกครับ")),
("Rozłączyło nas.", "sǎai lùt khráp", "สายหลุดครับ",
 "Praca i nauka", "Telefon", "phrase", 3, "n", "„sǎai lùt” = przerwane połączenie.", "",
 ("Przepraszam.", "khǎw-thôot khráp", "ขอโทษครับ")),
("Mam mało baterii.", "baet-toe-rîi nói láew khráp", "แบตเตอรี่น้อยแล้วครับ",
 "Praca i nauka", "Telefon", "phrase", 4, "p", "", "",
 ("Naładuj telefon.", "chaat thoo-rasàp sá khráp", "ชาร์จโทรศัพท์ซะครับ")),
("Wyślę ci wiadomość.", "dǐao phǒm sòng khâw-khwaam pai khráp", "เดี๋ยวผมส่งข้อความไปครับ",
 "Praca i nauka", "Telefon", "phrase", 5, "n", "", "khâw-khwaam = wiadomość",
 ("Dobrze.", "dâai khráp", "ได้ครับ")),
("Podaj mi swój numer.", "khǎw boe thoo dûai khráp", "ขอเบอร์โทรด้วยครับ",
 "Praca i nauka", "Telefon", "phrase", 5, "i", "„boe” to skrót od „number”.", "",
 ("Zapisz.", "jòt wái ná khráp", "จดไว้นะครับ")),
("Jaki masz numer?", "boe à-rai khráp", "เบอร์อะไรครับ",
 "Praca i nauka", "Telefon", "question", 4, "i", "", "",
 ("Zaraz podam.", "dǐao bàwk khráp", "เดี๋ยวบอกครับ")),
("Nie odbierał telefonu.", "khǎo mâi ráp sǎai khráp", "เขาไม่รับสายครับ",
 "Praca i nauka", "Telefon", "phrase", 3, "n", "„ráp sǎai” = odebrać telefon.", "",
 ("Spróbuj później.", "lawng mài thii lǎng khráp", "ลองใหม่ทีหลังครับ")),
("Oddzwonię.", "dǐao thoo klàp khráp", "เดี๋ยวโทรกลับครับ",
 "Praca i nauka", "Telefon", "phrase", 4, "n", "", "",
 ("Czekam.", "raw yùu khráp", "รออยู่ครับ")),
("Jakie jest hasło do internetu?", "phâat-woet wai-faai à-rai khráp", "พาสเวิร์ดไวไฟอะไรครับ",
 "Dom i codzienność", "Internet", "question", 5, "n", "", "",
 ("Jest na paragonie.", "yùu nai bai sèt khráp", "อยู่ในใบเสร็จครับ")),
("Internet jest bardzo wolny.", "nét cháa mâak khráp", "เน็ตช้ามากครับ",
 "Dom i codzienność", "Internet", "phrase", 4, "p", "„nét” to potoczny skrót od internetu.", "",
 ("Zrestartuję router.", "dǐao rii-sèt ráo-tôe khráp", "เดี๋ยวรีเซ็ตเราเตอร์ครับ")),
("Nie mogę się połączyć.", "phǒm chûeam tàw mâi dâai khráp", "ผมเชื่อมต่อไม่ได้ครับ",
 "Dom i codzienność", "Internet", "phrase", 4, "n", "„chûeam tàw” = połączyć się.", "",
 ("Spróbuj jeszcze raz.", "lawng mài ìik khráng khráp", "ลองใหม่อีกครั้งครับ")),
("Chcę kupić pakiet internetowy.", "phǒm yàak súe phék-kèet nét khráp", "ผมอยากซื้อแพ็กเกจเน็ตครับ",
 "Dom i codzienność", "Internet", "phrase", 4, "n", "", "",
 ("Na ile dni?", "kìi wan khráp", "กี่วันครับ")),
("Ile gigabajtów mam jeszcze?", "phǒm mii nét lǔea thâo-rài khráp", "ผมมีเน็ตเหลือเท่าไหร่ครับ",
 "Dom i codzienność", "Internet", "question", 3, "p", "", "",
 ("Sprawdzę.", "dǐao chék hâi khráp", "เดี๋ยวเช็คให้ครับ")),
("Skończył mi się internet.", "nét mòt láew khráp", "เน็ตหมดแล้วครับ",
 "Dom i codzienność", "Internet", "phrase", 3, "p", "„mòt” = wyczerpać się.", "",
 ("Doładuj pakiet.", "toem phék-kèet khráp", "เติมแพ็กเกจครับ")),
("Doładuję kartę.", "phǒm jà toem ngoen khráp", "ผมจะเติมเงินครับ",
 "Dom i codzienność", "Internet", "phrase", 3, "n", "„toem ngoen” = doładować konto.", "",
 ("Na ile?", "toem thâo-rài khráp", "เติมเท่าไหร่ครับ")),
("Napiszę do ciebie na czacie.", "dǐao tháek pai ná khráp", "เดี๋ยวแชทไปนะครับ",
 "Praca i nauka", "Telefon", "phrase", 4, "p",
 "„tháek” od angielskiego „chat”; w Tajlandii króluje LINE.", "",
 ("Dobrze.", "dâai khráp", "ได้ครับ")),
("Dodaj mnie do znajomych.", "âet phûean kan ná khráp", "แอดเพื่อนกันนะครับ",
 "Praca i nauka", "Telefon", "phrase", 3, "p", "", "",
 ("Już dodałem.", "âet láew khráp", "แอดแล้วครับ")),
("Zeskanuj mój kod.", "sà-kaen khiu-aa khǎwng phǒm khráp", "สแกนคิวอาร์ของผมครับ",
 "Praca i nauka", "Telefon", "phrase", 3, "n", "", "",
 ("Gotowe.", "sèt láew khráp", "เสร็จแล้วครับ")),

# ------------------------------------------------- slownictwo telefon/internet
("numer telefonu", "boe thoo-rasàp", "เบอร์โทรศัพท์", "Praca i nauka", "Telefon", "word", 5, "n", "", "",
 ("Poproszę numer telefonu.", "ORDER")),
("wiadomość", "khâw-khwaam", "ข้อความ", "Praca i nauka", "Telefon", "word", 4, "n", "", "",
 ("Wysłałem wiadomość.", "phǒm sòng khâw-khwaam láew khráp", "ผมส่งข้อความแล้วครับ")),
("połączenie", "sǎai", "สาย", "Praca i nauka", "Telefon", "word", 4, "n",
 "„sǎai” to dosłownie „linia”; używane też o połączeniu telefonicznym.", "",
 ("Połączenie jest złe.", "sǎai mâi dii khráp", "สายไม่ดีครับ")),
("zasięg", "sǎn-yaan", "สัญญาณ", "Praca i nauka", "Telefon", "word", 4, "n", "", "",
 ("Nie ma zasięgu.", "mâi mii sǎn-yaan khráp", "ไม่มีสัญญาณครับ")),
("aplikacja", "áep", "แอป", "Praca i nauka", "Internet", "word", 4, "p", "", "",
 ("Pobierz aplikację.", "loot áep khráp", "โหลดแอปครับ")),
("konto", "ban-chii", "บัญชี", "Praca i nauka", "Internet", "word", 3, "f", "", "",
 ("Nie mam konta.", "phǒm mâi mii ban-chii khráp", "ผมไม่มีบัญชีครับ")),
("hasło", "phâat-woet", "พาสเวิร์ด", "Dom i codzienność", "Internet", "word", 5, "p", "", "",
 ("Zapomniałem hasła.", "phǒm luem phâat-woet khráp", "ผมลืมพาสเวิร์ดครับ")),
("router", "ráo-tôe", "เราเตอร์", "Dom i codzienność", "Internet", "word", 2, "n", "", "",
 ("Gdzie jest router?", "WHERE")),
("ładowarka do telefonu", "thîi chaat thoo-rasàp", "ที่ชาร์จโทรศัพท์",
 "Dom i codzienność", "Sprzęt", "word", 4, "n", "", "",
 ("Czy masz ładowarkę?", "HAVE")),
("powerbank", "phaw-wôe-baeng", "พาวเวอร์แบงก์", "Dom i codzienność", "Sprzęt", "word", 3, "n", "", "",
 ("Wziąłem powerbank.", "phǒm ao phaw-wôe-baeng maa khráp", "ผมเอาพาวเวอร์แบงก์มาครับ")),
("gniazdko", "plák fai", "ปลั๊กไฟ", "Dom i codzienność", "Sprzęt", "word", 4, "n", "", "",
 ("Gdzie jest gniazdko?", "WHERE")),
("przejściówka", "hǔa plaeng", "หัวแปลง", "Dom i codzienność", "Sprzęt", "word", 3, "n", "", "",
 ("Czy macie przejściówkę?", "HAVE")),
]
