# -*- coding: utf-8 -*-
"""Leksyka etapu 4 (B1) — czesc C.

Zakres: problemy w uslugach, reklamacje, zwroty, bank, platnosci, formalnosci
codzienne (urzad, wiza, dokumenty).

Format jak w lex_b1_core_a.py.
"""

CORE_C = [

# =====================================================================
# ZGLASZANIE PROBLEMU
# =====================================================================
("Chciałbym zgłosić problem.", "phǒm yàak jâeng pan-hǎa khráp", "ผมอยากแจ้งปัญหาครับ",
 "Awarie i pomoc", "Reklamacje", "sentence", 4, "f",
 "„jâeng” = zgłaszać oficjalnie. W hotelu, banku i na policji to właściwe słowo.", "",
 ("Proszę powiedzieć, co się stało.", "lâo maa dâai loei khráp", "เล่ามาได้เลยครับ")),
("Mam problem z zamówieniem.", "phǒm mii pan-hǎa rûeang kaan sàng khráp",
 "ผมมีปัญหาเรื่องการสั่งครับ", "Awarie i pomoc", "Reklamacje", "sentence", 4, "n",
 "„kaan” przed czasownikiem tworzy rzeczownik: sàng = zamawiać, kaan sàng = zamówienie.", "",
 ("Sprawdzę.", "dǐao chék hâi khráp", "เดี๋ยวเช็คให้ครับ")),
("To nie jest to, co zamawiałem.", "nîi mâi châi thîi phǒm sàng wái khráp",
 "นี่ไม่ใช่ที่ผมสั่งไว้ครับ", "Awarie i pomoc", "Reklamacje", "sentence", 4, "n", "", "",
 ("Bardzo przepraszam.", "khǎw-thôot jing jing khráp", "ขอโทษจริงๆ ครับ")),
("Towar przyszedł uszkodzony.", "khǎwng thîi sòng maa chamrút khráp", "ของที่ส่งมาชำรุดครับ",
 "Zakupy i pieniądze", "Reklamacje", "sentence", 3, "f", "„chamrút” = uszkodzony, wadliwy.", "",
 ("Wymienimy.", "dǐao plìan hâi khráp", "เดี๋ยวเปลี่ยนให้ครับ")),
("Brakuje jednej rzeczy.", "khǎwng khàat pai nùeng yàang khráp", "ของขาดไปหนึ่งอย่างครับ",
 "Zakupy i pieniądze", "Reklamacje", "sentence", 3, "n", "„khàat” = brakować.", "",
 ("Czego dokładnie?", "khàat à-rai khráp", "ขาดอะไรครับ")),
("Czekam na to już tydzień.", "phǒm raw maa nùeng aa-thít láew khráp", "ผมรอมาหนึ่งอาทิตย์แล้วครับ",
 "Awarie i pomoc", "Reklamacje", "sentence", 3, "n", "", "",
 ("Przepraszam za zwłokę.", "khǎw-thôot thîi cháa khráp", "ขอโทษที่ช้าครับ")),
("Czy mogę to zwrócić?", "khǒen khǎwng dâai mǎi khráp", "คืนของได้ไหมครับ",
 "Zakupy i pieniądze", "Reklamacje", "question", 4, "n", "„khǒen” = zwracać, oddawać.", "",
 ("Proszę o paragon.", "khǎw bai sèt dûai khráp", "ขอใบเสร็จด้วยครับ")),
("Chciałbym wymienić na inny rozmiar.", "phǒm yàak plìan pen ìik sái nùeng khráp",
 "ผมอยากเปลี่ยนเป็นอีกไซส์หนึ่งครับ", "Zakupy i pieniądze", "Reklamacje", "sentence", 3, "n",
 "„sái” to zapożyczone angielskie size — w sklepach odzieżowych mówi się właśnie tak.", "",
 ("Jaki rozmiar?", "ao sái à-rai khráp", "เอาไซส์อะไรครับ")),
("Czy dostanę zwrot pieniędzy?", "khǒen ngoen dâai mǎi khráp", "คืนเงินได้ไหมครับ",
 "Zakupy i pieniądze", "Reklamacje", "question", 4, "n", "", "",
 ("Zwrot w ciągu trzech dni.", "khǒen ngoen phaai nai sǎam wan khráp", "คืนเงินภายในสามวันครับ")),
("Kto jest za to odpowiedzialny?", "khrai ráp phìt châwp rûeang níi khráp",
 "ใครรับผิดชอบเรื่องนี้ครับ", "Awarie i pomoc", "Reklamacje", "question", 3, "f",
 "„ráp phìt châwp” = brać odpowiedzialność. Mocne zdanie — używaj, gdy sprawa jest poważna.", "",
 ("Zawołam kierownika.", "dǐao rîak phûu jàt-kaan hâi khráp", "เดี๋ยวเรียกผู้จัดการให้ครับ")),
("Chciałbym rozmawiać z kierownikiem.", "khǎw khui kàp phûu jàt-kaan khráp",
 "ขอคุยกับผู้จัดการครับ", "Awarie i pomoc", "Reklamacje", "sentence", 3, "f",
 "„phûu jàt-kaan” = kierownik, menedżer.", "",
 ("Chwileczkę.", "raw sàk khrûu khráp", "รอสักครู่ครับ")),
("Rozumiem, że to nie pana wina.", "phǒm khâo-jai wâa mâi châi khwaam phìt khǎwng khun khráp",
 "ผมเข้าใจว่าไม่ใช่ความผิดของคุณครับ", "Awarie i pomoc", "Reklamacje", "sentence", 3, "f",
 "Zdanie łagodzące. W tajskiej kulturze pozwala rozmówcy zachować twarz i realnie przyspiesza pomoc.", "",
 ("Dziękuję za wyrozumiałość.", "khàwp-khun thîi khâo-jai khráp", "ขอบคุณที่เข้าใจครับ")),
("Proszę o rozwiązanie tej sprawy.", "chûai kâe khǎi hâi nòi khráp", "ช่วยแก้ไขให้หน่อยครับ",
 "Awarie i pomoc", "Reklamacje", "sentence", 3, "f", "„kâe khǎi” = naprawiać sytuację, korygować.", "",
 ("Zajmę się tym.", "dǐao jàt-kaan hâi khráp", "เดี๋ยวจัดการให้ครับ")),
("Ile to potrwa?", "tâwng chái wee-laa naan thâo-rài khráp", "ต้องใช้เวลานานเท่าไหร่ครับ",
 "Awarie i pomoc", "Reklamacje", "question", 4, "n", "", "",
 ("Około dwóch dni.", "prà-maan sǎwng wan khráp", "ประมาณสองวันครับ")),
("To już drugi raz.", "khráng níi khráng thîi sǎwng láew khráp", "ครั้งนี้ครั้งที่สองแล้วครับ",
 "Awarie i pomoc", "Reklamacje", "sentence", 3, "n", "", "",
 ("Przepraszamy.", "khǎw-thôot khráp", "ขอโทษครับ")),
("Nie jestem zadowolony z obsługi.", "phǒm mâi phaw jai kàp kaan bawrikaan khráp",
 "ผมไม่พอใจกับการบริการครับ", "Awarie i pomoc", "Reklamacje", "sentence", 3, "f",
 "„mâi phaw jai” = niezadowolony. Mocne — Tajowie rzadko mówią to wprost.", "",
 ("Bardzo przepraszamy.", "khǎw-thôot mâak khráp", "ขอโทษมากครับ")),
("Chcę złożyć skargę.", "phǒm khǎw ráwng rian khráp", "ผมขอร้องเรียนครับ",
 "Awarie i pomoc", "Reklamacje", "sentence", 2, "f", "„ráwng rian” = złożyć formalną skargę.", "",
 ("Proszę wypełnić formularz.", "krù-naa kràwk bàep fawm khráp", "กรุณากรอกแบบฟอร์มครับ")),

# =====================================================================
# BANK I PLATNOSCI
# =====================================================================
("Chciałbym założyć konto.", "phǒm yàak pòoet ban-chii khráp", "ผมอยากเปิดบัญชีครับ",
 "Zakupy i pieniądze", "Bank", "sentence", 3, "f", "„pòoet ban-chii” = otworzyć rachunek.", "",
 ("Proszę o paszport.", "khǎw phaas-pàwt dûai khráp", "ขอพาสปอร์ตด้วยครับ")),
("Jakie są opłaty za prowadzenie konta?", "khâa tham-niam ban-chii thâo-rài khráp",
 "ค่าธรรมเนียมบัญชีเท่าไหร่ครับ", "Zakupy i pieniądze", "Bank", "question", 3, "f",
 "„khâa tham-niam” = opłata, prowizja.", "",
 ("Dwieście bahtów rocznie.", "pii lá sǎwng ráwi bàat khráp", "ปีละสองร้อยบาทครับ")),
("Chcę zrobić przelew.", "phǒm yàak oon ngoen khráp", "ผมอยากโอนเงินครับ",
 "Zakupy i pieniądze", "Bank", "sentence", 4, "n", "„oon ngoen” = przelewać pieniądze.", "",
 ("Na jaki numer konta?", "oon khâo ban-chii nǎi khráp", "โอนเข้าบัญชีไหนครับ")),
("Przelew nie doszedł.", "ngoen thîi oon yang mâi khâo khráp", "เงินที่โอนยังไม่เข้าครับ",
 "Zakupy i pieniądze", "Bank", "sentence", 3, "n", "„ngoen khâo” = pieniądze wpłynęły.", "",
 ("Sprawdzę.", "dǐao chék hâi khráp", "เดี๋ยวเช็คให้ครับ")),
("Bankomat pobrał pieniądze, ale ich nie wydał.", "tûu ee-thii-em tàt ngoen tàae mâi jàai khráp",
 "ตู้เอทีเอ็มตัดเงินแต่ไม่จ่ายครับ", "Zakupy i pieniądze", "Bank", "sentence", 2, "f",
 "„tàt ngoen” = pobrać z konta.", "",
 ("Proszę zgłosić w oddziale.", "krù-naa jâeng thîi sǎa-khǎa khráp", "กรุณาแจ้งที่สาขาครับ")),
("Zgubiłem kartę.", "phǒm tham bàt hǎai khráp", "ผมทำบัตรหายครับ",
 "Zakupy i pieniądze", "Bank", "sentence", 3, "n", "", "",
 ("Zablokuję ją od razu.", "dǐao à-yàt bàt hâi loei khráp", "เดี๋ยวอายัดบัตรให้เลยครับ")),
("Proszę zablokować kartę.", "chûai à-yàt bàt hâi nòi khráp", "ช่วยอายัดบัตรให้หน่อยครับ",
 "Zakupy i pieniądze", "Bank", "sentence", 2, "f", "„à-yàt” = zablokować, zastrzec.", "",
 ("Już zrobione.", "riap ráwi khráp", "เรียบร้อยครับ")),
("Czy mogę zapłacić kartą?", "jàai bàt dâai mǎi khráp", "จ่ายบัตรได้ไหมครับ",
 "Zakupy i pieniądze", "Płatności", "question", 5, "n", "", "",
 ("Tylko gotówka.", "ráp chà-phǎw ngoen sòt khráp", "รับเฉพาะเงินสดครับ")),
("Płacę przez kod QR.", "phǒm sà-kaen jàai khráp", "ผมสแกนจ่ายครับ",
 "Zakupy i pieniądze", "Płatności", "sentence", 5, "n",
 "Skanowanie kodu QR to w Tajlandii domyślny sposób płatności, częstszy niż karta.", "",
 ("Proszę bardzo.", "choen khráp", "เชิญครับ")),
("Czy jest dodatkowa opłata?", "mii khâa chái jàai phôoem mǎi khráp", "มีค่าใช้จ่ายเพิ่มไหมครับ",
 "Zakupy i pieniądze", "Płatności", "question", 4, "f", "„khâa chái jàai” = koszty, wydatki.", "",
 ("Nie ma.", "mâi mii khráp", "ไม่มีครับ")),
("Zapłacę z góry.", "phǒm jàai lûang nâa khráp", "ผมจ่ายล่วงหน้าครับ",
 "Zakupy i pieniądze", "Płatności", "sentence", 3, "f", "„lûang nâa” = z wyprzedzeniem.", "",
 ("Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ")),
("Czy można zapłacić na raty?", "phàwn jàai dâai mǎi khráp", "ผ่อนจ่ายได้ไหมครับ",
 "Zakupy i pieniądze", "Płatności", "question", 3, "n", "„phàwn” = spłacać ratami.", "",
 ("Można na trzy raty.", "phàwn sǎam duean dâai khráp", "ผ่อนสามเดือนได้ครับ")),
("Rachunek się nie zgadza.", "bin mâi trong khráp", "บิลไม่ตรงครับ",
 "Restauracja", "Płatności", "sentence", 3, "n", "„mâi trong” = nie zgadza się, nie pasuje.", "",
 ("Sprawdzę jeszcze raz.", "dǐao chék mài khráp", "เดี๋ยวเช็คใหม่ครับ")),
("Policzyliście mi dwa razy.", "khít ngoen sáwn kan khráp", "คิดเงินซ้อนกันครับ",
 "Restauracja", "Płatności", "sentence", 2, "n", "„sáwn kan” = nałożone na siebie, podwójne.", "",
 ("Przepraszam, poprawię.", "khǎw-thôot khráp dǐao kâe hâi", "ขอโทษครับ เดี๋ยวแก้ให้")),
("Proszę o fakturę.", "khǎw bai kam-kàp phaa-sǐi dûai khráp", "ขอใบกำกับภาษีด้วยครับ",
 "Zakupy i pieniądze", "Płatności", "sentence", 2, "f", "„bai kam-kàp phaa-sǐi” = faktura VAT.", "",
 ("Potrzebne dane firmy.", "khǎw khâw-muun bà-rí-sàt dûai khráp", "ขอข้อมูลบริษัทด้วยครับ")),
("Chcę wymienić pieniądze.", "phǒm yàak lâek ngoen khráp", "ผมอยากแลกเงินครับ",
 "Zakupy i pieniądze", "Bank", "sentence", 4, "n", "„lâek” = wymieniać.", "",
 ("Jaki kurs?", "rêet thâo-rài khráp", "เรทเท่าไหร่ครับ")),
("Jaki jest dziś kurs?", "wan níi rêet thâo-rài khráp", "วันนี้เรทเท่าไหร่ครับ",
 "Zakupy i pieniądze", "Bank", "question", 3, "p",
 "„rêet” to potoczne zapożyczenie z angielskiego rate. W dokumencie bankowym pisze się „àt-traa lâek plìan”.", "",
 ("Sprawdzę.", "dǐao duu hâi khráp", "เดี๋ยวดูให้ครับ")),

# =====================================================================
# FORMALNOSCI
# =====================================================================
("Muszę przedłużyć wizę.", "phǒm tâwng tàw wii-sâa khráp", "ผมต้องต่อวีซ่าครับ",
 "Zakupy i pieniądze", "Formalności", "sentence", 3, "f", "„tàw” = przedłużyć, kontynuować.", "",
 ("Kiedy wygasa?", "mòt aa-yú mûea-rài khráp", "หมดอายุเมื่อไหร่ครับ")),
("Jakie dokumenty są potrzebne?", "tâwng chái èek-kà-sǎan à-rai bâang khráp",
 "ต้องใช้เอกสารอะไรบ้างครับ", "Praca i nauka", "Formalności", "question", 4, "f",
 "„èek-kà-sǎan” = dokumenty urzędowe. „… à-rai bâang” pyta o listę, nie o jedną rzecz.", "",
 ("Paszport i zdjęcie.", "phaas-pàwt kàp rûup thàai khráp", "พาสปอร์ตกับรูปถ่ายครับ")),
("Gdzie mam to podpisać?", "sen trong nǎi khráp", "เซ็นตรงไหนครับ",
 "Praca i nauka", "Formalności", "question", 4, "n", "„sen” = podpisać (od angielskiego sign).", "",
 ("Tu na dole.", "trong dâan lâang khráp", "ตรงด้านล่างครับ")),
("Czy potrzebna jest kopia?", "tâwng chái sǎm-nao dûai mǎi khráp", "ต้องใช้สำเนาด้วยไหมครับ",
 "Praca i nauka", "Formalności", "question", 3, "f", "„sǎm-nao” = kopia dokumentu.", "",
 ("Tak, jedna.", "khráp nùeng chút", "ครับ หนึ่งชุด")),
("Ile trwa rozpatrzenie wniosku?", "phíi-jaa-rá-naa naan thâo-rài khráp",
 "พิจารณานานเท่าไหร่ครับ", "Praca i nauka", "Formalności", "question", 2, "f",
 "„phíi-jaa-rá-naa” = rozpatrywać. Wyłącznie rejestr urzędowy.", "",
 ("Około dwóch tygodni.", "prà-maan sǎwng aa-thít khráp", "ประมาณสองอาทิตย์ครับ")),
("Termin już minął.", "loei kam-nòt láew khráp", "เลยกำหนดแล้วครับ",
 "Praca i nauka", "Formalności", "sentence", 3, "f", "„loei kam-nòt” = po terminie.", "",
 ("Będzie kara.", "tâwng sǐa khâa pràp khráp", "ต้องเสียค่าปรับครับ")),
("Ile wynosi kara?", "khâa pràp thâo-rài khráp", "ค่าปรับเท่าไหร่ครับ",
 "Zakupy i pieniądze", "Formalności", "question", 3, "f", "„khâa pràp” = grzywna, kara umowna.", "",
 ("Pięćset bahtów dziennie.", "wan lá hâa ráwi bàat khráp", "วันละห้าร้อยบาทครับ")),
("Czy mogę to załatwić online?", "tham awn-lai dâai mǎi khráp", "ทำออนไลน์ได้ไหมครับ",
 "Praca i nauka", "Formalności", "question", 4, "n", "", "",
 ("Można przez aplikację.", "tham phàan áep dâai khráp", "ทำผ่านแอปได้ครับ")),
("Muszę zgłosić adres zamieszkania.", "phǒm tâwng jâeng thîi yùu khráp", "ผมต้องแจ้งที่อยู่ครับ",
 "Praca i nauka", "Formalności", "sentence", 3, "f",
 "Zgłoszenie adresu (TM30/TM47) to realny obowiązek dla obcokrajowców w Tajlandii.", "",
 ("Proszę o umowę najmu.", "khǎw sǎn-yaa châo dûai khráp", "ขอสัญญาเช่าด้วยครับ")),
("Zgubiłem dokument.", "phǒm tham èek-kà-sǎan hǎai khráp", "ผมทำเอกสารหายครับ",
 "Awarie i pomoc", "Formalności", "sentence", 3, "n", "", "",
 ("Trzeba zgłosić na policję.", "tâwng jâeng tam-rùat khráp", "ต้องแจ้งตำรวจครับ")),
("Potrzebuję zaświadczenia.", "phǒm tâwng-kaan bai ráp-rawng khráp", "ผมต้องการใบรับรองครับ",
 "Praca i nauka", "Formalności", "sentence", 2, "f", "„bai ráp-rawng” = zaświadczenie, certyfikat.", "",
 ("W jakim celu?", "chái tham à-rai khráp", "ใช้ทำอะไรครับ")),
("Czy to wystarczy?", "khâe níi phaw mǎi khráp", "แค่นี้พอไหมครับ",
 "Praca i nauka", "Formalności", "question", 4, "n", "", "",
 ("Wystarczy.", "phaw khráp", "พอครับ")),
]
