# -*- coding: utf-8 -*-
"""Leksyka etapu 5 (B2) — idiomy, slang i kolokacje.

Zasada tego pliku: kazdy rekord ma w polu notes etykiete IDIOM, SLANG albo
KOLOKACJA, a przy slangu — wyrazne ostrzezenie, GDZIE tego nie uzywac.
Sama etykieta rejestru „potoczny” jest za slaba: uczacy sie musi wiedziec,
ze dane slowo obrazi rozmowce albo osmieszy mowiacego.

Format jak w lex_b2_core_a.py.
"""

CORE_IDIOM = [

# =====================================================================
# IDIOMY Z SERCEM (jai) — rdzen tajskiej frazeologii
# =====================================================================
("mieć dobre serce", "jai dii", "ใจดี", "Cechy i opinie", "Idiomy", "phrase", 5, "n",
 "IDIOM. Tajski buduje dziesiątki wyrażeń na słowie „jai” (serce). Warto poznać je jako rodzinę.", "dobre serce",
 ("Właściciel ma dobre serce, obniżył czynsz.", "jâo khǎwng jai dii lót khâa châo hâi khráp", "เจ้าของใจดีลดค่าเช่าให้ครับ")),
("być niecierpliwym", "jai ráwn", "ใจร้อน", "Cechy i opinie", "Idiomy", "phrase", 5, "n",
 "IDIOM. „gorące serce” — pośpiech i porywczość. To poważny zarzut w tajskiej kulturze.", "gorące serce",
 ("Nie bądź niecierpliwy, wszystko przyjdzie w swoim czasie.", "yàa jai ráwn khráp dǐao man kâw maa eeng", "อย่าใจร้อนครับ เดี๋ยวมันก็มาเอง")),
("być hojnym", "jai kwâang", "ใจกว้าง", "Cechy i opinie", "Idiomy", "phrase", 4, "n", "IDIOM. „szerokie serce” — hojność i otwartość na cudze zdanie.", "szerokie serce",
 ("Szef jest hojny, zawsze stawia zespołowi.", "hǔa-nâa jai kwâang líang thiim sà-mǒoe khráp", "หัวหน้าใจกว้างเลี้ยงทีมเสมอครับ")),
("stracić odwagę", "jai fàw", "ใจฝ่อ", "Cechy i opinie", "Idiomy", "phrase", 3, "p", "IDIOM. „skurczone serce” — strach, który odbiera zdolność działania.", "skurczone serce",
 ("Straciłem odwagę, kiedy zobaczyłem kolejkę.", "phaw hěn khiu yaao kâw jai fàw loei khráp", "พอเห็นคิวยาวก็ใจฝ่อเลยครับ")),
("mieć twarde serce", "jai khǎeng", "ใจแข็ง", "Cechy i opinie", "Idiomy", "phrase", 4, "n",
 "IDIOM. Nie ulegać prośbom — czasem pochwała, czasem zarzut. Kontekst decyduje.", "twarde serce",
 ("Miej twarde serce i nie pożyczaj mu znowu.", "jai khǎeng nòi khráp yàa hâi yuem ìik", "ใจแข็งหน่อยครับ อย่าให้ยืมอีก")),
("ulżyło mu na sercu", "sà-baai jai khûen", "สบายใจขึ้น", "Cechy i opinie", "Idiomy", "phrase", 4, "n", "IDIOM. Spokój ducha po zdjęciu ciężaru.", "wygodne serce",
 ("Ulżyło mu na sercu po rozmowie z szefem.", "khui kàp hǔa-nâa láew khǎo sà-baai jai khûen khráp", "คุยกับหัวหน้าแล้วเขาสบายใจขึ้นครับ")),
("wziąć sobie coś do serca", "kèp maa khít mâak", "เก็บมาคิดมาก", "Cechy i opinie", "Idiomy", "phrase", 4, "n",
 "IDIOM. Rozpamiętywanie cudzych słów. Tajowie często odradzają to rozmówcy.", "",
 ("Nie bierz sobie tego do serca, on tak mówi do wszystkich.", "yàa kèp maa khít mâak khráp khǎo phûut yàang níi kàp thúk khon", "อย่าเก็บมาคิดมากครับ เขาพูดอย่างนี้กับทุกคน")),
("dogadywać się bez słów", "khâo jai kan dii", "เข้าใจกันดี", "Ludzie i rodzina", "Idiomy", "phrase", 4, "n", "IDIOM. Wzajemne zrozumienie bez potrzeby tłumaczenia się.", "",
 ("Dogadujemy się bez słów po pięciu latach.", "yùu kan hâa pii láew khâo jai kan dii khráp", "อยู่กันห้าปีแล้วเข้าใจกันดีครับ")),

# =====================================================================
# IDIOMY OBRAZOWE
# =====================================================================
("wyszło szydło z worka", "khwaam jing pràa-kòt", "ความจริงปรากฏ", "Cechy i opinie", "Idiomy", "phrase", 3, "f",
 "IDIOM w rejestrze formalnym. W mowie częściej: „khwaam tàek”, czyli sprawa się wydała.", "prawda się ujawniła",
 ("W końcu wyszło szydło z worka i wszyscy wiedzą.", "sùt tháai khwaam jing kâw pràa-kòt thúk khon rúu khráp", "สุดท้ายความจริงก็ปรากฏ ทุกคนรู้ครับ")),
("sprawa się wydała", "khwaam tàek", "ความแตก", "Small talk", "Idiomy", "phrase", 4, "p",
 "IDIOM potoczny. Dosłownie „prawda pękła”. Bardzo częste w plotkach i serialach.", "prawda pękła",
 ("Sprawa się wydała, bo ktoś zrobił zdjęcie.", "khwaam tàek phráw mii khon thàai rûup wái khráp", "ความแตกเพราะมีคนถ่ายรูปไว้ครับ")),
("upiec dwie pieczenie na jednym ogniu", "yíng pun nát diao dâai nók sǎwng tua", "ยิงปืนนัดเดียวได้นกสองตัว",
 "Cechy i opinie", "Idiomy", "phrase", 3, "n", "IDIOM. Obraz identyczny jak w polskim „dwie pieczenie” — jeden strzał, dwa ptaki.", "jeden strzał, dwa ptaki",
 ("Upieczemy dwie pieczenie: spotkanie i zakupy przy okazji.", "yíng pun nát diao dâai nók sǎwng tua khráp prà-chum láew súe khǎwng dûai", "ยิงปืนนัดเดียวได้นกสองตัวครับ ประชุมแล้วซื้อของด้วย")),
("rzucać grochem o ścianę", "sǐi sáw hâi khwaai fang", "สีซอให้ควายฟัง", "Cechy i opinie", "Idiomy", "phrase", 3, "p",
 "IDIOM. Dosłownie „grać na skrzypcach bawołowi”. Uwaga: nazwanie kogoś bawołem to ciężka obraza, więc nie mów tego o rozmówcy.", "grać na skrzypcach bawołowi",
 ("Tłumaczenie mu tego to rzucanie grochem o ścianę.", "à-thí-baai hâi khǎo fang mǔean sǐi sáw hâi khwaai fang khráp", "อธิบายให้เขาฟังเหมือนสีซอให้ควายฟังครับ")),
("robić z igły widły", "tham rûeang lék hâi pen rûeang yài", "ทำเรื่องเล็กให้เป็นเรื่องใหญ่",
 "Cechy i opinie", "Idiomy", "phrase", 4, "n", "IDIOM. Bardzo częsty zarzut w tajskich sporach rodzinnych i biurowych.", "",
 ("Nie róbmy z igły wideł, to drobiazg.", "yàa tham rûeang lék hâi pen rûeang yài loei khráp", "อย่าทำเรื่องเล็กให้เป็นเรื่องใหญ่เลยครับ")),
("wiatr wieje w dobrą stronę", "duang kam-lang khûen", "ดวงกำลังขึ้น", "Cechy i opinie", "Idiomy", "phrase", 3, "p",
 "IDIOM. „duang” to los, gwiazda. Tajowie mówią o szczęściu jak o czymś, co rośnie i opada.", "gwiazda się wznosi",
 ("Wiatr wieje w dobrą stronę, dostał awans.", "duang kam-lang khûen dâai lûean khân khráp", "ดวงกำลังขึ้น ได้เลื่อนขั้นครับ")),
("mieć pecha", "duang tòk", "ดวงตก", "Cechy i opinie", "Idiomy", "phrase", 4, "p", "IDIOM. Przeciwieństwo poprzedniego. Bardzo częste wytłumaczenie niepowodzeń.", "gwiazda spadła",
 ("Mam ostatnio pecha, trzecia awaria w miesiącu.", "chûang níi duang tòk khráp sǐa pen khráng thîi sǎam", "ช่วงนี้ดวงตกครับ เสียเป็นครั้งที่สาม")),
("znać coś jak własną kieszeń", "rúu jon kràdìk", "รู้จนกระดิก", "Cechy i opinie", "Idiomy", "phrase", 2, "p",
 "IDIOM potoczny. W rejestrze neutralnym powiedz raczej „rúu dii thúk sàwk thúk mum”.", "",
 ("Zna tę dzielnicę jak własną kieszeń.", "khǎo rúu thǎew níi dii thúk sàwk thúk mum khráp", "เขารู้แถวนี้ดีทุกซอกทุกมุมครับ")),
("wpaść z deszczu pod rynnę", "nǐi sǔea pà jaw-rá-khêe", "หนีเสือปะจระเข้", "Cechy i opinie", "Idiomy", "phrase", 3, "n",
 "IDIOM. Dosłownie „uciec przed tygrysem, natknąć się na krokodyla”. Bardzo znany, każdy Taj go rozumie.", "uciec tygrysowi, spotkać krokodyla",
 ("Zmiana pracy to było wpaść z deszczu pod rynnę.", "plìan ngaan thîi mài mǔean nǐi sǔea pà jaw-rá-khêe khráp", "เปลี่ยนงานที่ใหม่เหมือนหนีเสือปะจระเข้ครับ")),
("krok po kroku dojdziesz", "khôi pen khôi pai", "ค่อยเป็นค่อยไป", "Cechy i opinie", "Idiomy", "phrase", 5, "n",
 "IDIOM. Filozofia stopniowości, bardzo tajska. Usłyszysz to jako radę na każdy problem.", "powoli być, powoli iść",
 ("Krok po kroku dojdziesz, nie spiesz się z nauką.", "khôi pen khôi pai khráp mâi tâwng rîip rian", "ค่อยเป็นค่อยไปครับ ไม่ต้องรีบเรียน")),
("cierpliwość popłaca", "khwaam phá-yaa-yaam yùu thîi nǎi khwaam sǎm-rèt yùu thîi nân", "ความพยายามอยู่ที่ไหนความสำเร็จอยู่ที่นั่น",
 "Cechy i opinie", "Idiomy", "sentence", 3, "f",
 "IDIOM ze szkolnych tablic — „gdzie wysiłek, tam sukces”. Każdy Taj zna go z dzieciństwa.", "",
 ("Cierpliwość popłaca — tak mówią tutaj dzieciom.", "khwaam phá-yaa-yaam yùu thîi nǎi khwaam sǎm-rèt yùu thîi nân khon thai sǎwn dèk yàang níi khráp", "ความพยายามอยู่ที่ไหนความสำเร็จอยู่ที่นั่น คนไทยสอนเด็กอย่างนี้ครับ")),

# =====================================================================
# SLANG — z wyraznym ostrzezeniem
# =====================================================================
("super, ekstra", "dèt", "เด็ด", "Cechy i opinie", "Slang", "phrase", 4, "p",
 "SLANG. Zachwyt nad jedzeniem, muzyką, wyglądem. NIE używaj w piśmie służbowym ani wobec urzędnika — zabrzmi niepoważnie.", "",
 ("Ten makaron jest ekstra, spróbuj.", "kǔai-tǐao ráan níi dèt mâak lawng duu sí", "ก๋วยเตี๋ยวร้านนี้เด็ดมาก ลองดูสิ")),
("odjazd, szał", "fin", "ฟิน", "Cechy i opinie", "Slang", "phrase", 4, "p",
 "SLANG młodzieżowy, od angielskiego „finale”. Oznacza szczyt przyjemności. Wobec osób starszych brzmi dziwacznie.", "",
 ("Masaż po pracy to odjazd.", "nûat lǎng lôek ngaan níi fin mâak", "นวดหลังเลิกงานนี่ฟินมาก")),
("nie ma opcji", "mâi mii thaang", "ไม่มีทาง", "Cechy i opinie", "Slang", "phrase", 4, "p",
 "Potoczne i stanowcze. Wobec klienta i przełożonego zamień na „khong jà yâak khráp”, bo brzmi jak zatrzaśnięcie drzwi.", "nie ma drogi",
 ("Nie ma opcji, żebym zdążył do południa.", "mâi mii thaang sèt kàwn thîang", "ไม่มีทางเสร็จก่อนเที่ยง")),
("olej to", "chàng hǔa man", "ช่างหัวมัน", "Cechy i opinie", "Slang", "phrase", 3, "p",
 "SLANG. Mocniejsze i grubsze niż „chàng man”. Wobec obcych i starszych brzmi wulgarnie — używaj tylko wśród bliskich.", "",
 ("Olej to, i tak niczego nie zmienisz.", "chàng hǔa man thòe yang-ngai kâw mâi plìan", "ช่างหัวมันเถอะ ยังไงก็ไม่เปลี่ยน")),
("zwiał, uciekł", "chín", "ชิ่ง", "Cechy i opinie", "Slang", "phrase", 3, "p",
 "SLANG. Znikanie bez uprzedzenia, także wymigiwanie się od rachunku. W rozmowie oficjalnej użyj „mâi maa taam nát”.", "",
 ("Zwiał przed płaceniem rachunku.", "khǎo chín kàwn jàai tang", "เขาชิ่งก่อนจ่ายตังค์")),
("drogo jak diabli", "phaeng wôoe", "แพงเว่อร์", "Zakupy i pieniądze", "Slang", "phrase", 4, "p",
 "SLANG od angielskiego „over”. Powiedziane sprzedawcy w twarz brzmi jak zarzut zdzierstwa — mów to raczej do znajomego.", "",
 ("Drogo jak diabli, w mieście jest o połowę taniej.", "phaeng wôoe nai mueang thùuk kwàa khrûeng nùeng", "แพงเว่อร์ ในเมืองถูกกว่าครึ่งหนึ่ง")),
("dawaj, no już", "réw dìi", "เร็วดิ", "Podstawy i grzeczność", "Slang", "phrase", 3, "p",
 "SLANG. Ponaglenie bez cienia grzeczności. Wobec kogokolwiek poza bliskim kolegą to afront.", "",
 ("Dawaj, no już, autobus odjeżdża.", "réw dìi rót mee jà àwk láew", "เร็วดิ รถเมล์จะออกแล้ว")),
("ale wtopa", "sǔai wôoe", "ซวยเว่อร์", "Cechy i opinie", "Slang", "phrase", 3, "p",
 "SLANG. „sǔai” to pech, ale słowo jest wulgarne w kontekście przesądów. Nie mów tego przy starszych ani w świątyni.", "",
 ("Ale wtopa, zgubiłem klucze drugi raz.", "sǔai wôoe tham kun-jae hǎai ìik láew", "ซวยเว่อร์ ทำกุญแจหายอีกแล้ว")),
("na luzie", "chill chill", "ชิลชิล", "Cechy i opinie", "Slang", "phrase", 4, "p",
 "SLANG z angielskiego, bardzo popularny. W piśmie służbowym zastąp go zwrotem „sà-baai sà-baai”.", "",
 ("Weekend spędzam na luzie, bez planów.", "sǎo aa-thít níi chill chill mâi mii phǎen", "เสาร์อาทิตย์นี้ชิลชิล ไม่มีแผน")),
("gadka szmatka", "phûut pai rûeai", "พูดไปเรื่อย", "Small talk", "Slang", "phrase", 3, "p",
 "Potoczne. Zarzut mówienia bez sensu. Powiedziane wprost do rozmówcy jest obraźliwe.", "",
 ("On tak gada bez ładu, nie słuchaj.", "khǎo phûut pai rûeai mâi tâwng fang", "เขาพูดไปเรื่อย ไม่ต้องฟัง")),
("wisieć komuś kasę", "tìt tang", "ติดตังค์", "Zakupy i pieniądze", "Slang", "phrase", 3, "p",
 "Potoczne. „tang” to potoczne pieniądze. W rozmowie z bankiem czy księgową użyj „khâang châm-rá”.", "",
 ("Wiszę mu jeszcze dwieście batów.", "phǒm yang tìt tang khǎo sǎwng ráwi", "ผมยังติดตังค์เขาสองร้อย")),
("odpuść sobie", "mâi tâwng sîi-ri-át", "ไม่ต้องซีเรียส", "Cechy i opinie", "Slang", "phrase", 4, "p",
 "SLANG z angielskiego „serious”. Bardzo częste między znajomymi, ale w sporze z klientem zabrzmi lekceważąco.", "",
 ("Odpuść sobie, to naprawdę drobiazg.", "mâi tâwng sîi-ri-át rûeang lék mâak", "ไม่ต้องซีเรียส เรื่องเล็กมาก")),

# =====================================================================
# KOLOKACJE — slowa, ktore chodza w parze
# =====================================================================
("podjąć decyzję", "tàt-sǐn jai", "ตัดสินใจ", "Praca i nauka", "Kolokacje", "phrase", 5, "n",
 "KOLOKACJA. Dosłownie „przeciąć serce” — decyzja to odcięcie wahania. Zawsze w tej parze, nigdy osobno.", "przeciąć serce",
 ("Muszę podjąć decyzję do jutra.", "phǒm tâwng tàt-sǐn jai kàwn phrûng-níi khráp", "ผมต้องตัดสินใจก่อนพรุ่งนี้ครับ")),
("ponieść odpowiedzialność", "ráp phìt châwp", "รับผิดชอบ", "Praca i nauka", "Kolokacje", "phrase", 5, "f",
 "KOLOKACJA. „przyjąć błąd i słuszność” — jedno pojęcie, dwa człony. Nie rozdzielaj.", "",
 ("Kto poniesie odpowiedzialność za opóźnienie?", "khrai jà ráp phìt châwp rûeang cháa khráp", "ใครจะรับผิดชอบเรื่องช้าครับ")),
("dotrzymać słowa", "rák-sǎa kham phûut", "รักษาคำพูด", "Ludzie i rodzina", "Kolokacje", "phrase", 4, "f",
 "KOLOKACJA. „pilnować wypowiedzianego słowa”. W Tajlandii to jedna z najważniejszych cnót w relacjach.", "",
 ("On zawsze dotrzymuje słowa, można mu ufać.", "khǎo rák-sǎa kham phûut sà-mǒoe wái jai dâai khráp", "เขารักษาคำพูดเสมอ ไว้ใจได้ครับ")),
("zachować twarz", "rák-sǎa nâa", "รักษาหน้า", "Ludzie i rodzina", "Kolokacje", "phrase", 4, "n",
 "KOLOKACJA i pojęcie kulturowe. Dbanie o godność swoją i cudzą w oczach innych. Klucz do zrozumienia tajskich rozmów.", "pilnować twarzy",
 ("Skrytykuj go na osobności, żeby zachował twarz.", "tì khǎo tawn sǎwng tàw sǎwng hâi khǎo rák-sǎa nâa dâai khráp", "ติเขาตอนสองต่อสองให้เขารักษาหน้าได้ครับ")),
("stracić twarz", "sǐa nâa", "เสียหน้า", "Ludzie i rodzina", "Kolokacje", "phrase", 4, "n",
 "KOLOKACJA. Publiczne upokorzenie. Doprowadzenie kogoś do „sǐa nâa” niszczy relację skuteczniej niż każda kłótnia.", "stracić twarz",
 ("Nie chcę, żeby stracił twarz przy zespole.", "phǒm mâi yàak hâi khǎo sǐa nâa tàw nâa thiim khráp", "ผมไม่อยากให้เขาเสียหน้าต่อหน้าทีมครับ")),
("mieć wpływ na coś", "mii phǒn tàw", "มีผลต่อ", "Praca i nauka", "Kolokacje", "phrase", 4, "f", "KOLOKACJA formalna, częsta w raportach i umowach.", "",
 ("To ma wpływ na cały harmonogram.", "man mii phǒn tàw taa-raang thóng mòt khráp", "มันมีผลต่อตารางทั้งหมดครับ")),
("wywiązać się z umowy", "tham taam sǎn-yaa", "ทำตามสัญญา", "Praca i nauka", "Kolokacje", "phrase", 4, "f", "KOLOKACJA. Podstawa języka umów.", "",
 ("Firma wywiązała się z umowy co do joty.", "bɔɔ-rí-sàt tham taam sǎn-yaa thúk khâw khráp", "บริษัททำตามสัญญาทุกข้อครับ")),
("zwrócić uwagę na szczegóły", "sǎi jai rai-lá-ìat", "ใส่ใจรายละเอียด", "Praca i nauka", "Kolokacje", "phrase", 4, "n",
 "KOLOKACJA. „sài jai” = wkładać serce, czyli przykładać się. Częsta pochwała w opinii o pracowniku.", "wkładać serce w szczegóły",
 ("Zwraca uwagę na szczegóły, dlatego mu ufam.", "khǎo sài jai rai-lá-ìat phǒm thǔeng wái jai khráp", "เขาใส่ใจรายละเอียด ผมถึงไว้ใจครับ")),
("nawiązać kontakt", "sâang khwaam sǎm-phan", "สร้างความสัมพันธ์", "Praca i nauka", "Kolokacje", "phrase", 3, "f", "KOLOKACJA. Budowanie relacji poprzedza w Tajlandii każdy interes.", "",
 ("Najpierw nawiąż kontakt, dopiero potem mów o cenie.", "sâang khwaam sǎm-phan kàwn khôi khui rûeang raa-khaa khráp", "สร้างความสัมพันธ์ก่อนค่อยคุยเรื่องราคาครับ")),
("dojść do porozumienia", "tòk long kan dâai", "ตกลงกันได้", "Praca i nauka", "Kolokacje", "phrase", 5, "n", "KOLOKACJA. Najczęstszy sposób powiedzenia „dogadaliśmy się”.", "",
 ("Doszliśmy do porozumienia po dwóch godzinach.", "khui sǎwng chûa-moong kâw tòk long kan dâai khráp", "คุยสองชั่วโมงก็ตกลงกันได้ครับ")),
("ponieść stratę", "khàat thun", "ขาดทุน", "Zakupy i pieniądze", "Kolokacje", "phrase", 4, "n", "KOLOKACJA. Przeciwieństwo: „dâai kam-rai” — osiągnąć zysk.", "brakuje kapitału",
 ("W tym miesiącu ponieśliśmy stratę.", "duean níi raw khàat thun khráp", "เดือนนี้เราขาดทุนครับ")),
("osiągnąć zysk", "dâai kam-rai", "ได้กำไร", "Zakupy i pieniądze", "Kolokacje", "phrase", 4, "n", "KOLOKACJA. Para z „khàat thun”. Ucz się ich razem.", "",
 ("Sklep osiągnął zysk dopiero w drugim roku.", "ráan dâai kam-rai tawn pii thîi sǎwng khráp", "ร้านได้กำไรตอนปีที่สองครับ")),
("wziąć urlop", "laa phák ráwn", "ลาพักร้อน", "Praca i nauka", "Kolokacje", "phrase", 4, "n",
 "KOLOKACJA. Dosłownie „urlop od gorąca” — nazwa pochodzi z czasów, gdy odpoczywano w porze upałów.", "urlop od gorąca",
 ("Wezmę urlop w kwietniu, w czasie Songkran.", "phǒm jà laa phák ráwn duean mee-sǎa chûang sǒng-kraan khráp", "ผมจะลาพักร้อนเดือนเมษาช่วงสงกรานต์ครับ")),
("złożyć wypowiedzenie", "yûen bai laa àwk", "ยื่นใบลาออก", "Praca i nauka", "Kolokacje", "phrase", 3, "f", "KOLOKACJA. „bai laa àwk” to konkretny dokument, nie sama decyzja.", "",
 ("Złożył wypowiedzenie miesiąc temu.", "khǎo yûen bai laa àwk duean thîi láew khráp", "เขายื่นใบลาออกเดือนที่แล้วครับ")),
("dostać podwyżkę", "dâai khûen ngoen duean", "ได้ขึ้นเงินเดือน", "Praca i nauka", "Kolokacje", "phrase", 4, "n", "KOLOKACJA. Rzadziej: „dâai prap ngoen duean”.", "",
 ("Dostał podwyżkę po roku pracy.", "tham-ngaan khróp pii kâw dâai khûen ngoen duean khráp", "ทำงานครบปีก็ได้ขึ้นเงินเดือนครับ")),
("dotrzymać terminu", "sèt than kam-nòt", "เสร็จทันกำหนด", "Praca i nauka", "Kolokacje", "phrase", 5, "n", "KOLOKACJA. „than” = zdążyć. Bez niego zdanie mówi tylko, że praca się skończyła.", "",
 ("Zespół dotrzymał terminu mimo problemów.", "thiim sèt than kam-nòt thǔeng jà mii pan-hǎa khráp", "ทีมเสร็จทันกำหนดถึงจะมีปัญหาครับ")),
("robić wrażenie", "sâang khwaam prà-tháp jai", "สร้างความประทับใจ", "Cechy i opinie", "Kolokacje", "phrase", 3, "f", "KOLOKACJA. Częste w obsłudze klienta i turystyce.", "",
 ("Obsługa zrobiła na mnie dobre wrażenie.", "kaan brí-kaan sâang khwaam prà-tháp jai hâi phǒm khráp", "การบริการสร้างความประทับใจให้ผมครับ")),
("mieć doświadczenie w czymś", "mii prà-sòp-kaan dâan", "มีประสบการณ์ด้าน", "Praca i nauka", "Kolokacje", "phrase", 4, "f", "KOLOKACJA. „dâan” wskazuje dziedzinę — zawsze po nim rzeczownik.", "",
 ("Mam doświadczenie w obsłudze klienta.", "phǒm mii prà-sòp-kaan dâan brí-kaan lûuk-kháa khráp", "ผมมีประสบการณ์ด้านบริการลูกค้าครับ")),
("zwrócić koszty", "bòoek khâa chái jàai khuen", "เบิกค่าใช้จ่ายคืน", "Praca i nauka", "Kolokacje", "phrase", 3, "f",
 "KOLOKACJA. „bòoek” = pobrać zwrot z firmowej kasy. Zapamiętaj razem z „bai-sèt” — paragonem.", "",
 ("Zwrócę koszty po przedstawieniu paragonów.", "bòoek khâa chái jàai khuen dâai mûea mii bai-sèt khráp", "เบิกค่าใช้จ่ายคืนได้เมื่อมีใบเสร็จครับ")),
("ustalić termin spotkania", "kam-nòt wan nát", "กำหนดวันนัด", "Praca i nauka", "Kolokacje", "phrase", 4, "n", "KOLOKACJA. „nát” to umówione spotkanie, nie sama data.", "",
 ("Ustalmy termin spotkania na przyszły wtorek.", "kam-nòt wan nát pen wan ang-khaan nâa ná khráp", "กำหนดวันนัดเป็นวันอังคารหน้านะครับ")),
("złożyć reklamację", "yûen rûeang rawng rian", "ยื่นเรื่องร้องเรียน", "Zakupy i pieniądze", "Kolokacje", "phrase", 3, "f",
 "KOLOKACJA formalna. Potocznie: „khleem”, od angielskiego „claim”.", "",
 ("Złożyłem reklamację na piśmie w zeszłym tygodniu.", "phǒm yûen rûeang rawng rian pen èek-kà-sǎan aa-thít thîi láew khráp", "ผมยื่นเรื่องร้องเรียนเป็นเอกสารอาทิตย์ที่แล้วครับ")),
("wywrzeć presję", "kòt dan", "กดดัน", "Praca i nauka", "Kolokacje", "phrase", 4, "n", "KOLOKACJA. Także w stronie biernej: „thùuk kòt dan” — być pod presją.", "naciskać i pchać",
 ("Nie chcę wywierać presji, ale termin goni.", "mâi yàak kòt dan ná khráp tàae kam-nòt klâi láew", "ไม่อยากกดดันนะครับ แต่กำหนดใกล้แล้ว")),
("stracić panowanie nad sobą", "khum aa-rom mâi yùu", "คุมอารมณ์ไม่อยู่", "Cechy i opinie", "Kolokacje", "phrase", 3, "n",
 "KOLOKACJA. W tajskiej kulturze utrata panowania kompromituje mówiącego bardziej niż sama sprawa sporu.", "",
 ("Straciłem panowanie nad sobą i tego żałuję.", "phǒm khum aa-rom mâi yùu láew kâw sǐa jai khráp", "ผมคุมอารมณ์ไม่อยู่แล้วก็เสียใจครับ")),
("zrobić dobre pierwsze wrażenie", "prà-tháp jai tâng tàae khráng râek", "ประทับใจตั้งแต่ครั้งแรก",
 "Cechy i opinie", "Kolokacje", "phrase", 3, "n", "KOLOKACJA. Częsta w recenzjach hoteli i restauracji.", "",
 ("Zrobili dobre pierwsze wrażenie już przy wejściu.", "prà-tháp jai tâng tàae khráng râek thîi khâo pai khráp", "ประทับใจตั้งแต่ครั้งแรกที่เข้าไปครับ")),
("nadrobić zaległości", "taam ngaan hâi than", "ตามงานให้ทัน", "Praca i nauka", "Kolokacje", "phrase", 3, "n", "KOLOKACJA. Także o nauce: „taam bòt rian hâi than”.", "",
 ("Muszę nadrobić zaległości po chorobie.", "phǒm tâwng taam ngaan hâi than lǎng jàak mâi sà-baai khráp", "ผมต้องตามงานให้ทันหลังจากไม่สบายครับ")),
("wyciągnąć wnioski", "thàwt bòt rian", "ถอดบทเรียน", "Praca i nauka", "Kolokacje", "phrase", 3, "f",
 "KOLOKACJA. Dosłownie „rozebrać lekcję na części”. Zwrot z języka zarządzania, brzmi bardzo profesjonalnie.", "",
 ("Wyciągnijmy wnioski, zanim zaczniemy kolejny etap.", "thàwt bòt rian kàwn rôoem fâet tàw pai khráp", "ถอดบทเรียนก่อนเริ่มเฟสต่อไปครับ")),
]
