# -*- coding: utf-8 -*-
"""Leksyka etapu 4 (B1) — czesc D.

Zakres: praca i rozmowy zawodowe, spotkania, uzgadnianie terminow, zadania,
opinia zwrotna, negocjacje, hierarchia w tajskim biurze.

Format jak w lex_b1_core_a.py.
"""

CORE_D = [

# =====================================================================
# SPOTKANIA
# =====================================================================
("Zwołajmy krótkie spotkanie.", "nát prà-chum sân sân kan ná khráp", "นัดประชุมสั้นๆ กันนะครับ",
 "Praca i nauka", "Spotkania", "sentence", 4, "f", "„nát” = umówić termin, „prà-chum” = zebranie.", "",
 ("Kiedy pasuje?", "sà-dùak wan nǎi khráp", "สะดวกวันไหนครับ")),
("Kiedy panu pasuje?", "khun sà-dùak wan nǎi khráp", "คุณสะดวกวันไหนครับ",
 "Praca i nauka", "Spotkania", "question", 5, "f",
 "„sà-dùak” = mieć czas, móc. Tajowie pytają o wygodę, nie o wolny termin.", "być wygodnym",
 ("W czwartek rano.", "wan phá-rúe-hàt cháo khráp", "วันพฤหัสเช้าครับ")),
("Czy możemy przesunąć spotkanie?", "lûean prà-chum dâai mǎi khráp", "เลื่อนประชุมได้ไหมครับ",
 "Praca i nauka", "Spotkania", "question", 4, "f", "", "",
 ("Na kiedy?", "lûean pen wan nǎi khráp", "เลื่อนเป็นวันไหนครับ")),
("Spotkanie się przeciągnęło.", "prà-chum yaao kwàa thîi khít khráp", "ประชุมยาวกว่าที่คิดครับ",
 "Praca i nauka", "Spotkania", "sentence", 3, "n", "", "",
 ("Nic nie szkodzi.", "mâi pen rai khráp", "ไม่เป็นไรครับ")),
("Spóźnię się dziesięć minut.", "phǒm jà thǔeng cháa sìp naa-thii khráp", "ผมจะถึงช้าสิบนาทีครับ",
 "Praca i nauka", "Spotkania", "sentence", 4, "n", "", "",
 ("Poczekamy.", "raw dâai khráp", "รอได้ครับ")),
("Zaczynajmy.", "rôoem loei khráp", "เริ่มเลยครับ", "Praca i nauka", "Spotkania", "phrase", 4, "n", "", "",
 ("Dobrze.", "khráp", "ครับ")),
("Przejdźmy do rzeczy.", "khâo rûeang loei khráp", "เข้าเรื่องเลยครับ",
 "Praca i nauka", "Spotkania", "phrase", 3, "n", "„khâo rûeang” = przejść do sedna.", "wejść w temat",
 ("Zgoda.", "khráp", "ครับ")),
("Mam jedno pytanie.", "phǒm mii kham thǎam nùeng khâw khráp", "ผมมีคำถามหนึ่งข้อครับ",
 "Praca i nauka", "Spotkania", "sentence", 4, "f", "„khâw” to jednostka do liczenia punktów i pytań.", "",
 ("Proszę.", "choen khráp", "เชิญครับ")),
("Chciałbym coś dodać.", "phǒm khǎw sòoem nòi khráp", "ผมขอเสริมหน่อยครับ",
 "Praca i nauka", "Spotkania", "sentence", 3, "f", "„sòoem” = dopowiedzieć, uzupełnić.", "",
 ("Śmiało.", "choen khráp", "เชิญครับ")),
("Zapiszę to.", "dǐao phǒm jòt wái khráp", "เดี๋ยวผมจดไว้ครับ",
 "Praca i nauka", "Spotkania", "sentence", 3, "n", "„jòt” = notować.", "",
 ("Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ")),
("Podsumujmy ustalenia.", "sà-rùp thîi tòk long kan khráp", "สรุปที่ตกลงกันครับ",
 "Praca i nauka", "Spotkania", "sentence", 3, "f", "", "",
 ("Dobrze.", "dâai khráp", "ได้ครับ")),
("Kto się tym zajmie?", "khrai jà duu rûeang níi khráp", "ใครจะดูเรื่องนี้ครับ",
 "Praca i nauka", "Spotkania", "question", 4, "n", "„duu rûeang” = zająć się sprawą.", "",
 ("Ja mogę.", "phǒm duu hâi dâai khráp", "ผมดูให้ได้ครับ")),
("Do kiedy to ma być gotowe?", "tâwng sèt phaai nai mûea-rài khráp", "ต้องเสร็จภายในเมื่อไหร่ครับ",
 "Praca i nauka", "Spotkania", "question", 4, "f", "", "",
 ("Do piątku.", "phaai nai wan sùk khráp", "ภายในวันศุกร์ครับ")),
("Prześlę notatkę po spotkaniu.", "dǐao sòng sà-rùp hâi lǎng prà-chum khráp",
 "เดี๋ยวส่งสรุปให้หลังประชุมครับ", "Praca i nauka", "Spotkania", "sentence", 3, "f", "", "",
 ("Świetnie.", "dii khráp", "ดีครับ")),

# =====================================================================
# ZADANIA I POSTEP PRAC
# =====================================================================
("Na czym stoimy?", "tawn níi thǔeng nǎi láew khráp", "ตอนนี้ถึงไหนแล้วครับ",
 "Praca i nauka", "Praca", "question", 4, "n",
 "Dosłownie „dokąd doszliśmy”. Standardowe pytanie o postęp prac.", "",
 ("Prawie skończone.", "kùeap sèt láew khráp", "เกือบเสร็จแล้วครับ")),
("Utknąłem na jednym punkcie.", "phǒm tìt yùu trong nùeng khráp", "ผมติดอยู่ตรงหนึ่งครับ",
 "Praca i nauka", "Praca", "sentence", 3, "n", "„tìt” = utknąć, zablokować się na czymś.", "",
 ("Pokaż, pomogę.", "ao maa duu khráp dǐao chûai", "เอามาดูครับ เดี๋ยวช่วย")),
("Potrzebuję więcej czasu.", "phǒm khǎw wee-laa phôoem khráp", "ผมขอเวลาเพิ่มครับ",
 "Praca i nauka", "Praca", "sentence", 4, "f", "", "",
 ("Ile dokładnie?", "khǎw ìik kìi wan khráp", "ขออีกกี่วันครับ")),
("Zajmę się tym w pierwszej kolejności.", "phǒm jà tham rûeang níi kàwn khráp",
 "ผมจะทำเรื่องนี้ก่อนครับ", "Praca i nauka", "Praca", "sentence", 3, "f", "", "",
 ("Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ")),
("Przekażę to koledze.", "dǐao sòng tàw hâi phûean khráp", "เดี๋ยวส่งต่อให้เพื่อนครับ",
 "Praca i nauka", "Praca", "sentence", 3, "n", "„sòng tàw” = przekazać dalej.", "",
 ("Dobrze.", "dâai khráp", "ได้ครับ")),
("To nie należy do moich obowiązków.", "man mâi châi ngaan khǎwng phǒm khráp",
 "มันไม่ใช่งานของผมครับ", "Praca i nauka", "Praca", "sentence", 2, "n",
 "Bezpośrednie. W tajskim biurze łagodniej brzmi: „phǒm mâi nâe-jai wâa tâwng tham rǔe plào”.", "",
 ("Sprawdzę, kto odpowiada.", "dǐao chék hâi wâa khrai duu khráp", "เดี๋ยวเช็คให้ว่าใครดูครับ")),
("Zrobię to do jutra.", "phǒm jà tham hâi sèt phrûng níi khráp", "ผมจะทำให้เสร็จพรุ่งนี้ครับ",
 "Praca i nauka", "Praca", "sentence", 4, "n", "", "",
 ("Liczę na to.", "fàak dûai ná khráp", "ฝากด้วยนะครับ")),
("Liczę na ciebie.", "fàak dûai ná khráp", "ฝากด้วยนะครับ",
 "Praca i nauka", "Praca", "phrase", 5, "n",
 "„fàak” dosłownie „powierzyć”. To jedno z najczęstszych zdań w tajskim biurze — nie ma dokładnego polskiego odpowiednika.", "powierzam ci",
 ("Zrobi się.", "dâai loei khráp", "ได้เลยครับ")),
("Sprawdzę i dam znać.", "dǐao chék láew bàwk ìik thii khráp", "เดี๋ยวเช็คแล้วบอกอีกทีครับ",
 "Praca i nauka", "Praca", "sentence", 5, "n", "", "",
 ("Czekam.", "raw yùu khráp", "รออยู่ครับ")),
("Coś poszło nie tak.", "man mii à-rai phìt phlâat khráp", "มันมีอะไรผิดพลาดครับ",
 "Praca i nauka", "Praca", "sentence", 3, "n", "", "",
 ("Sprawdźmy razem.", "maa duu dûai kan khráp", "มาดูด้วยกันครับ")),
("To był mój błąd.", "pen khwaam phìt khǎwng phǒm eeng khráp", "เป็นความผิดของผมเองครับ",
 "Praca i nauka", "Praca", "sentence", 3, "f",
 "Przyznanie się wprost. W tajskiej kulturze pracy robi dobre wrażenie, jeśli towarzyszy mu propozycja naprawy.", "",
 ("Naprawmy to.", "kâe kan khráp", "แก้กันครับ")),
("Poprawię to od razu.", "dǐao kâe hâi loei khráp", "เดี๋ยวแก้ให้เลยครับ",
 "Praca i nauka", "Praca", "sentence", 4, "n", "", "",
 ("Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ")),
("Zrobiłeś to dobrze.", "tham dâai dii mâak khráp", "ทำได้ดีมากครับ",
 "Praca i nauka", "Praca", "sentence", 4, "n", "", "",
 ("Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ")),
("Mam kilka uwag.", "phǒm mii khwaam-hěn baang khâw khráp", "ผมมีความเห็นบางข้อครับ",
 "Praca i nauka", "Praca", "sentence", 3, "f",
 "Uprzejmy wstęp do krytyki. Wprost „mâi dii” raniłoby twarz rozmówcy.", "",
 ("Słucham.", "wâa maa loei khráp", "ว่ามาเลยครับ")),
("Można to jeszcze poprawić.", "yang phát-thá-naa dâai ìik khráp", "ยังพัฒนาได้อีกครับ",
 "Praca i nauka", "Praca", "sentence", 3, "f", "„phát-thá-naa” = rozwijać, ulepszać.", "",
 ("Powiedz jak.", "náe-nam nòi khráp", "แนะนำหน่อยครับ")),

# =====================================================================
# ROZMOWA O PRACY I WARUNKACH
# =====================================================================
("Szukam pracy w Bangkoku.", "phǒm hǎa ngaan thîi krung-thêep khráp", "ผมหางานที่กรุงเทพครับ",
 "Praca i nauka", "Praca", "sentence", 3, "n", "„krung-thêep” to tajska nazwa Bangkoku.", "",
 ("W jakiej branży?", "sǎai ngaan à-rai khráp", "สายงานอะไรครับ")),
("Mam pięcioletnie doświadczenie.", "phǒm mii prà-sòp-kaan hâa pii khráp",
 "ผมมีประสบการณ์ห้าปีครับ", "Praca i nauka", "Praca", "sentence", 3, "f", "", "",
 ("Sporo.", "kâw yóe ná khráp", "ก็เยอะนะครับ")),
("Jakie są warunki?", "ngûean-khǎi pen yang-ngai khráp", "เงื่อนไขเป็นยังไงครับ",
 "Praca i nauka", "Praca", "question", 3, "f", "„ngûean-khǎi” = warunki umowy.", "",
 ("Wyjaśnię.", "dǐao à-thí-baai hâi khráp", "เดี๋ยวอธิบายให้ครับ")),
("Jakie są godziny pracy?", "wee-laa tham ngaan kìi moong thǔeng kìi moong khráp",
 "เวลาทำงานกี่โมงถึงกี่โมงครับ", "Praca i nauka", "Praca", "question", 3, "n", "", "",
 ("Od dziewiątej do szóstej.", "kâo moong thǔeng hòk moong yen khráp", "เก้าโมงถึงหกโมงเย็นครับ")),
("Czy są nadgodziny?", "mii oo-thii mǎi khráp", "มีโอทีไหมครับ",
 "Praca i nauka", "Praca", "question", 3, "p",
 "„oo-thii” to skrót od angielskiego OT. W umowie napisane będzie „lûang wee-laa”.", "",
 ("Czasami.", "baang khráng khráp", "บางครั้งครับ")),
("Czy mogę pracować zdalnie?", "tham ngaan thîi bâan dâai mǎi khráp", "ทำงานที่บ้านได้ไหมครับ",
 "Praca i nauka", "Praca", "question", 3, "n", "", "",
 ("Dwa dni w tygodniu.", "aa-thít lá sǎwng wan khráp", "อาทิตย์ละสองวันครับ")),
("Chciałbym omówić wynagrodzenie.", "phǒm yàak khui rûeang ngoen duean khráp",
 "ผมอยากคุยเรื่องเงินเดือนครับ", "Praca i nauka", "Praca", "sentence", 2, "f",
 "„ngoen duean” = pensja miesięczna.", "",
 ("Proszę podać oczekiwania.", "khǎw thâap thîi khâat wái khráp", "ขอทราบที่คาดไว้ครับ")),
("Czy jest możliwość podwyżki?", "mii oo-kàat khûen ngoen duean mǎi khráp",
 "มีโอกาสขึ้นเงินเดือนไหมครับ", "Praca i nauka", "Praca", "question", 2, "f", "", "",
 ("Raz w roku.", "pii lá khráng khráp", "ปีละครั้งครับ")),
("Chciałbym wziąć urlop.", "phǒm yàak lǎa phák ráwn khráp", "ผมอยากลาพักร้อนครับ",
 "Praca i nauka", "Praca", "sentence", 3, "f", "„lǎa phák ráwn” = urlop wypoczynkowy.", "",
 ("Od kiedy?", "tâng tàae wan nǎi khráp", "ตั้งแต่วันไหนครับ")),
("Muszę wyjść wcześniej.", "phǒm tâwng klàp kàwn khráp", "ผมต้องกลับก่อนครับ",
 "Praca i nauka", "Praca", "sentence", 3, "n", "", "",
 ("Nie ma sprawy.", "mâi pen rai khráp", "ไม่เป็นไรครับ")),
("Dziś zostaję dłużej.", "wan níi phǒm yùu tàw khráp", "วันนี้ผมอยู่ต่อครับ",
 "Praca i nauka", "Praca", "sentence", 3, "n", "", "",
 ("Nie przemęcz się.", "yàa nùeai koen pai ná khráp", "อย่าเหนื่อยเกินไปนะครับ")),
("Zmieniam pracę.", "phǒm plìan ngaan khráp", "ผมเปลี่ยนงานครับ",
 "Praca i nauka", "Praca", "sentence", 3, "n", "", "",
 ("Powodzenia.", "chôok dii ná khráp", "โชคดีนะครับ")),
("Składam wypowiedzenie.", "phǒm khǎw laa àwk khráp", "ผมขอลาออกครับ",
 "Praca i nauka", "Praca", "sentence", 2, "f", "„laa àwk” = zwolnić się z pracy.", "",
 ("Szkoda.", "sǐa daai khráp", "เสียดายครับ")),
("Dziękuję za współpracę.", "khàwp-khun sǎm-ràp kaan rûam ngaan khráp",
 "ขอบคุณสำหรับการร่วมงานครับ", "Praca i nauka", "Praca", "sentence", 3, "f", "", "",
 ("Nawzajem.", "chên-diao-kan khráp", "เช่นเดียวกันครับ")),
("Proszę o kontakt w razie pytań.", "mii kham thǎam thák maa dâai loei khráp",
 "มีคำถามทักมาได้เลยครับ", "Praca i nauka", "Praca", "sentence", 4, "n",
 "„thák maa” = odezwać się, napisać. Naturalne w komunikatorze, nie w piśmie urzędowym.", "",
 ("Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ")),
]
