# -*- coding: utf-8 -*-
"""Leksyka etapu 3 (A2) — czesc D.

Zakres: praca i podstawowa komunikacja zawodowa, hobby i czas wolny, relacje
miedzyludzkie, opisywanie problemow, proszenie o pomoc, porownywanie, czeste
reakcje w rozmowie, uprzejme odmawianie, opowiadanie o przeszlosci i planach.

Format krotki jak w lex_a2_core_a.py.
"""

CORE_D = [

# =====================================================================
# PRACA I KOMUNIKACJA ZAWODOWA
# =====================================================================
("Czym się zajmujesz?", "tham ngaan à-rai khráp", "ทำงานอะไรครับ",
 "Praca i nauka", "Small talk", "question", 5, "n", "", "",
 ("Pracuję w biurze.", "phǒm tham ngaan áwf-fít khráp", "ผมทำงานออฟฟิศครับ")),
("Pracuję zdalnie.", "phǒm tham ngaan thîi bâan khráp", "ผมทำงานที่บ้านครับ",
 "Praca i nauka", "Praca", "phrase", 4, "n", "", "dosłownie: pracuję w domu",
 ("Wygodnie.", "sà-dùak dii khráp", "สะดวกดีครับ")),
("Prowadzę własną firmę.", "phǒm tham thú-rá-kìt suan tua khráp", "ผมทำธุรกิจส่วนตัวครับ",
 "Praca i nauka", "Praca", "phrase", 3, "f", "„suan tua” = własny, prywatny.", "",
 ("Jaka branża?", "thú-rá-kìt à-rai khráp", "ธุรกิจอะไรครับ")),
("Jestem tu służbowo.", "phǒm maa tham ngaan khráp", "ผมมาทำงานครับ",
 "Praca i nauka", "Praca", "phrase", 3, "n", "", "",
 ("Na długo?", "yùu naan mǎi khráp", "อยู่นานไหมครับ")),
("Jestem tu na wakacjach.", "phǒm maa thîao khráp", "ผมมาเที่ยวครับ",
 "Praca i nauka", "Small talk", "phrase", 5, "n", "„thîao” = podróżować dla przyjemności.", "",
 ("Miłego pobytu.", "khǎw hâi sà-nùk ná khráp", "ขอให้สนุกนะครับ")),
("Ile godzin dziennie pracujesz?", "tham ngaan wan lá kìi chûa moong khráp",
 "ทำงานวันละกี่ชั่วโมงครับ", "Praca i nauka", "Praca", "question", 3, "n", "", "",
 ("Osiem godzin.", "pàet chûa moong khráp", "แปดชั่วโมงครับ")),
("Mam dziś dużo pracy.", "wan níi ngaan yóe khráp", "วันนี้งานเยอะครับ",
 "Praca i nauka", "Praca", "phrase", 4, "n", "„yóe” = dużo (potocznie).", "",
 ("Trzymaj się.", "sûu sûu ná khráp", "สู้ๆ นะครับ")),
("Kończę pracę o piątej.", "phǒm lôek ngaan hâa moong yen khráp", "ผมเลิกงานห้าโมงเย็นครับ",
 "Praca i nauka", "Praca", "phrase", 4, "n", "„lôek ngaan” = kończyć pracę.", "",
 ("To spotkajmy się potem.", "ngán jôe kan lǎng lôek ngaan khráp", "งั้นเจอกันหลังเลิกงานครับ")),
("Biorę jutro wolne.", "phrûng níi phǒm lǎa yùt khráp", "พรุ่งนี้ผมลาหยุดครับ",
 "Praca i nauka", "Praca", "phrase", 3, "n", "„lǎa yùt” = brać urlop.", "",
 ("Odpocznij dobrze.", "phák phàwn hâi tem thîi khráp", "พักผ่อนให้เต็มที่ครับ")),
("Jestem dziś na zwolnieniu.", "wan níi phǒm lǎa pùai khráp", "วันนี้ผมลาป่วยครับ",
 "Praca i nauka", "Praca", "phrase", 3, "f", "„lǎa pùai” = zwolnienie chorobowe.", "",
 ("Zdrowiej.", "hǎai reo reo ná khráp", "หายเร็วๆ นะครับ")),
("Mam spotkanie o dziesiątej.", "phǒm mii prà-chum sìp moong khráp", "ผมมีประชุมสิบโมงครับ",
 "Praca i nauka", "Spotkania", "phrase", 4, "f", "„prà-chum” = zebranie, narada.", "",
 ("Długie?", "naan mǎi khráp", "นานไหมครับ")),
("Spotkanie się przedłuża.", "prà-chum lâak yaao khráp", "ประชุมลากยาวครับ",
 "Praca i nauka", "Spotkania", "phrase", 2, "p", "", "",
 ("Poczekam.", "phǒm raw dâai khráp", "ผมรอได้ครับ")),
("Wyślę to mailem.", "dǐao sòng ii-meew pai hâi khráp", "เดี๋ยวส่งอีเมลไปให้ครับ",
 "Praca i nauka", "Komunikacja", "phrase", 4, "n", "", "",
 ("Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ")),
("Nie dostałem twojej wiadomości.", "phǒm mâi dâi ráp khâw-khwaam khráp", "ผมไม่ได้รับข้อความครับ",
 "Praca i nauka", "Komunikacja", "phrase", 3, "n", "", "",
 ("Wyślę jeszcze raz.", "dǐao sòng mài khráp", "เดี๋ยวส่งใหม่ครับ")),
("Prześlij mi to jeszcze raz.", "chûai sòng maa mài nòi khráp", "ช่วยส่งมาใหม่หน่อยครับ",
 "Praca i nauka", "Komunikacja", "phrase", 3, "n", "", "",
 ("Już wysyłam.", "sòng láew khráp", "ส่งแล้วครับ")),
("Kiedy jest termin?", "kam-nòt sòng mûea-rài khráp", "กำหนดส่งเมื่อไหร่ครับ",
 "Praca i nauka", "Komunikacja", "question", 3, "f", "", "kam-nòt = wyznaczony termin",
 ("W piątek.", "wan sùk khráp", "วันศุกร์ครับ")),
("Potrzebuję więcej czasu.", "phǒm khǎw wee-laa phôoem khráp", "ผมขอเวลาเพิ่มครับ",
 "Praca i nauka", "Komunikacja", "phrase", 3, "f", "", "",
 ("Ile jeszcze?", "khǎw ìik kìi wan khráp", "ขออีกกี่วันครับ")),
("Zajmę się tym dzisiaj.", "wan níi phǒm jà tham hâi khráp", "วันนี้ผมจะทำให้ครับ",
 "Praca i nauka", "Komunikacja", "phrase", 3, "n", "", "",
 ("Doceniam.", "khàwp-khun mâak khráp", "ขอบคุณมากครับ")),
("Rozumiem zadanie.", "phǒm khâo-jai ngaan láew khráp", "ผมเข้าใจงานแล้วครับ",
 "Praca i nauka", "Komunikacja", "phrase", 3, "f", "", "",
 ("Świetnie.", "dii mâak khráp", "ดีมากครับ")),
("Mam pytanie w sprawie projektu.", "phǒm mii kham thǎam rûeang khroong-kaan khráp",
 "ผมมีคำถามเรื่องโครงการครับ", "Praca i nauka", "Komunikacja", "phrase", 3, "f", "", "",
 ("Słucham.", "wâa maa dâai loei khráp", "ว่ามาได้เลยครับ")),
("Czy możemy to omówić jutro?", "khui rûeang níi phrûng níi dâai mǎi khráp",
 "คุยเรื่องนี้พรุ่งนี้ได้ไหมครับ", "Praca i nauka", "Komunikacja", "question", 3, "n", "„khui” = rozmawiać.", "",
 ("Może być.", "dâai khráp", "ได้ครับ")),
("Zgadzam się z tą propozycją.", "phǒm hěn dûai kàp khâw sà-nǒe níi khráp",
 "ผมเห็นด้วยกับข้อเสนอนี้ครับ", "Praca i nauka", "Komunikacja", "phrase", 2, "f", "", "khâw sà-nǒe = propozycja",
 ("Zatem ustalone.", "ngán tòk long khráp", "งั้นตกลงครับ")),
("Muszę to skonsultować.", "phǒm tâwng prùek-sǎa kàwn khráp", "ผมต้องปรึกษาก่อนครับ",
 "Praca i nauka", "Komunikacja", "phrase", 2, "f", "„prùek-sǎa” = konsultować się.", "",
 ("Rozumiem.", "khâo-jai khráp", "เข้าใจครับ")),

# ------------------------------------------------- slownictwo zawodowe
("firma", "bàw-rí-sàt", "บริษัท", "Praca i nauka", "Praca", "word", 4, "f", "", "",
 ("Gdzie jest ta firma?", "WHERE")),
("umowa", "sǎn-yaa", "สัญญา", "Praca i nauka", "Praca", "word", 3, "f", "", "",
 ("Poproszę umowę.", "ORDER")),
("pensja", "ngoen duean", "เงินเดือน", "Praca i nauka", "Praca", "word", 3, "n", "", "dosłownie: pieniądze miesięczne",
 ("Kiedy jest wypłata?", "ngoen duean àwk mûea-rài khráp", "เงินเดือนออกเมื่อไหร่ครับ")),
("nadgodziny", "oo-thii", "โอที", "Praca i nauka", "Praca", "word", 3, "p", "Skrót od angielskiego „OT”.", "",
 ("Dziś mam nadgodziny.", "wan níi mii oo-thii khráp", "วันนี้มีโอทีครับ")),
("urlop", "wan lǎa", "วันลา", "Praca i nauka", "Praca", "word", 3, "n", "", "",
 ("Ile mam urlopu?", "mii wan lǎa kìi wan khráp", "มีวันลากี่วันครับ")),
("zebranie", "prà-chum", "ประชุม", "Praca i nauka", "Spotkania", "word", 4, "f", "", "",
 ("Kiedy jest zebranie?", "prà-chum mûea-rài khráp", "ประชุมเมื่อไหร่ครับ")),
("projekt", "khroong-kaan", "โครงการ", "Praca i nauka", "Praca", "word", 3, "f", "", "",
 ("Projekt jest gotowy.", "khroong-kaan sèt láew khráp", "โครงการเสร็จแล้วครับ")),
("klient", "lûuk kháa", "ลูกค้า", "Praca i nauka", "Praca", "word", 4, "n", "", "",
 ("Klient już czeka.", "lûuk kháa raw yùu khráp", "ลูกค้ารออยู่ครับ")),
("dokument", "èek-kà-sǎan", "เอกสาร", "Praca i nauka", "Praca", "word", 4, "f", "", "",
 ("Poproszę dokumenty.", "ORDER")),
("podpis", "laai sen", "ลายเซ็น", "Praca i nauka", "Praca", "word", 3, "f", "", "",
 ("Poproszę o podpis.", "khǎw laai sen khráp", "ขอลายเซ็นครับ")),
("wizytówka", "naam bàt", "นามบัตร", "Praca i nauka", "Praca", "word", 3, "f", "", "",
 ("Poproszę wizytówkę.", "ORDER")),
("współpraca", "khwaam rûam mue", "ความร่วมมือ", "Praca i nauka", "Praca", "word", 2, "f", "", "",
 ("Dziękuję za współpracę.", "khàwp-khun sǎm-ràp khwaam rûam mue khráp",
  "ขอบคุณสำหรับความร่วมมือครับ")),

# =====================================================================
# HOBBY I CZAS WOLNY
# =====================================================================
("Co robisz w wolnym czasie?", "wee-laa wâang tham à-rai khráp", "เวลาว่างทำอะไรครับ",
 "Small talk", "Hobby", "question", 5, "n", "", "",
 ("Czytam książki.", "phǒm àan nǎng-sǔe khráp", "ผมอ่านหนังสือครับ")),
("Lubię czytać książki.", "phǒm châwp àan nǎng-sǔe khráp", "ผมชอบอ่านหนังสือครับ",
 "Small talk", "Hobby", "phrase", 4, "n", "", "",
 ("Jakie książki?", "nǎng-sǔe bàep nǎi khráp", "หนังสือแบบไหนครับ")),
("Lubię oglądać filmy.", "phǒm châwp duu nǎng khráp", "ผมชอบดูหนังครับ",
 "Small talk", "Hobby", "phrase", 4, "n", "„nǎng” = film.", "",
 ("Jaki gatunek?", "nǎng naew nǎi khráp", "หนังแนวไหนครับ")),
("Lubię słuchać muzyki.", "phǒm châwp fang phleeng khráp", "ผมชอบฟังเพลงครับ",
 "Small talk", "Hobby", "phrase", 4, "n", "„phleeng” = piosenka, muzyka.", "",
 ("Jakiej muzyki?", "phleeng naew nǎi khráp", "เพลงแนวไหนครับ")),
("Gram w piłkę.", "phǒm lên fút-bawn khráp", "ผมเล่นฟุตบอลครับ",
 "Small talk", "Hobby", "phrase", 4, "i", "„lên” = grać, bawić się.", "",
 ("Gdzie grasz?", "lên thîi nǎi khráp", "เล่นที่ไหนครับ")),
("Chodzę na siłownię.", "phǒm pai fít-nét khráp", "ผมไปฟิตเนสครับ",
 "Small talk", "Hobby", "phrase", 3, "n", "", "",
 ("Ile razy w tygodniu?", "aa-thít lá kìi khráng khráp", "อาทิตย์ละกี่ครั้งครับ")),
("Biegam rano.", "phǒm wîng tawn cháo khráp", "ผมวิ่งตอนเช้าครับ",
 "Small talk", "Hobby", "phrase", 3, "n", "", "",
 ("Zdrowo.", "dii tàw sùk-khà-phâap khráp", "ดีต่อสุขภาพครับ")),
("Lubię pływać.", "phǒm châwp wâai náam khráp", "ผมชอบว่ายน้ำครับ",
 "Small talk", "Hobby", "phrase", 4, "n", "", "",
 ("W morzu czy basenie?", "thá-lee rǔe sà wâai náam khráp", "ทะเลหรือสระว่ายน้ำครับ")),
("Uczę się tajskiego.", "phǒm rian phaa-sǎa thai khráp", "ผมเรียนภาษาไทยครับ",
 "Praca i nauka", "Nauka", "phrase", 5, "n", "", "",
 ("Dobrze ci idzie.", "kèng mâak khráp", "เก่งมากครับ")),
("Uczę się od pół roku.", "phǒm rian maa khrûeng pii láew khráp", "ผมเรียนมาครึ่งปีแล้วครับ",
 "Praca i nauka", "Nauka", "phrase", 3, "n", "„khrûeng” = pół.", "",
 ("Widać postępy.", "dii khûen yóe loei khráp", "ดีขึ้นเยอะเลยครับ")),
("Lubię gotować.", "phǒm châwp tham aa-hǎan khráp", "ผมชอบทำอาหารครับ",
 "Small talk", "Hobby", "phrase", 4, "n", "", "",
 ("Co gotujesz najczęściej?", "tham à-rai bàwi thîi sùt khráp", "ทำอะไรบ่อยที่สุดครับ")),
("Lubię robić zdjęcia.", "phǒm châwp thàai rûup khráp", "ผมชอบถ่ายรูปครับ",
 "Small talk", "Hobby", "phrase", 4, "n", "", "",
 ("Zrób mi zdjęcie.", "chûai thàai rûup hâi nòi khráp", "ช่วยถ่ายรูปให้หน่อยครับ")),
("Lubię podróżować.", "phǒm châwp doen thaang khráp", "ผมชอบเดินทางครับ",
 "Small talk", "Hobby", "phrase", 4, "n", "", "",
 ("Gdzie już byłeś?", "khoei pai thîi nǎi bâang khráp", "เคยไปที่ไหนบ้างครับ")),
("Nie mam żadnego hobby.", "phǒm mâi mii ngaan à-dì-rèek khráp", "ผมไม่มีงานอดิเรกครับ",
 "Small talk", "Hobby", "phrase", 2, "n", "", "ngaan à-dì-rèek = hobby",
 ("To znajdź jakieś.", "lawng hǎa duu sí khráp", "ลองหาดูสิครับ")),
("Idziemy dziś wieczorem na miasto?", "yen níi pai thîao kan mǎi khráp", "เย็นนี้ไปเที่ยวกันไหมครับ",
 "Small talk", "Wyjścia", "question", 4, "i", "", "",
 ("Chętnie.", "dâai loei khráp", "ได้เลยครับ")),
("Chodźmy na plażę.", "pai thá-lee kan thòe", "ไปทะเลกันเถอะ",
 "Small talk", "Wyjścia", "phrase", 4, "i", "„thòe” na końcu = zachęta „chodźmy”.", "thòe = no chodź",
 ("Świetny pomysł.", "khwaam khít dii khráp", "ความคิดดีครับ")),
("Chodźmy na targ nocny.", "pai tà-làat klaang khuen kan thòe", "ไปตลาดกลางคืนกันเถอะ",
 "Small talk", "Wyjścia", "phrase", 4, "i", "", "",
 ("O której?", "kìi moong khráp", "กี่โมงครับ")),
("Może kino?", "pai duu nǎng mǎi khráp", "ไปดูหนังไหมครับ",
 "Small talk", "Wyjścia", "question", 4, "i", "", "",
 ("Co grają?", "mii nǎng à-rai bâang khráp", "มีหนังอะไรบ้างครับ")),
("Wolałbym zostać w domu.", "phǒm yàak yùu bâan mâak-kwàa khráp", "ผมอยากอยู่บ้านมากกว่าครับ",
 "Small talk", "Wyjścia", "phrase", 3, "n", "", "",
 ("Rozumiem, odpocznij.", "khâo-jai khráp phák phàwn ná", "เข้าใจครับ พักผ่อนนะ")),

# ------------------------------------------------- slownictwo hobby
("film", "nǎng", "หนัง", "Small talk", "Hobby", "word", 4, "n", "", "",
 ("Ten film jest dobry.", "nǎng rûeang níi dii khráp", "หนังเรื่องนี้ดีครับ")),
("muzyka", "phleeng", "เพลง", "Small talk", "Hobby", "word", 4, "n", "", "",
 ("Lubię tę piosenkę.", "LIKE")),
("książka", "nǎng-sǔe", "หนังสือ", "Small talk", "Hobby", "word", 4, "n", "", "",
 ("Czytam książkę.", "phǒm àan nǎng-sǔe yùu khráp", "ผมอ่านหนังสืออยู่ครับ")),
("gra", "keem", "เกม", "Small talk", "Hobby", "word", 3, "p", "", "",
 ("Gram w gry.", "phǒm lên keem khráp", "ผมเล่นเกมครับ")),
("sport", "kii-laa", "กีฬา", "Small talk", "Hobby", "word", 4, "n", "", "",
 ("Jaki sport lubisz?", "châwp kii-laa à-rai khráp", "ชอบกีฬาอะไรครับ")),
("koncert", "khaw-sòet", "คอนเสิร์ต", "Small talk", "Hobby", "word", 2, "n", "", "",
 ("Idę na koncert.", "phǒm jà pai khaw-sòet khráp", "ผมจะไปคอนเสิร์ตครับ")),
("masaż", "nûat", "นวด", "Small talk", "Relaks", "word", 5, "n", "", "",
 ("Chcę masaż.", "phǒm yàak nûat khráp", "ผมอยากนวดครับ")),
("plaża", "chaai hàat", "ชายหาด", "Miejsca i orientacja", "Wypoczynek", "word", 4, "n", "", "",
 ("Gdzie jest plaża?", "WHERE")),
("wyspa", "kàw", "เกาะ", "Miejsca i orientacja", "Wypoczynek", "word", 4, "n", "", "",
 ("Popłyńmy na wyspę.", "pai kàw kan thòe", "ไปเกาะกันเถอะ")),
("wodospad", "náam tòk", "น้ำตก", "Miejsca i orientacja", "Wypoczynek", "word", 3, "n", "", "dosłownie: woda spada",
 ("Gdzie jest wodospad?", "WHERE")),
("wycieczka", "thua", "ทัวร์", "Miejsca i orientacja", "Wypoczynek", "word", 4, "n", "", "",
 ("Ile kosztuje wycieczka?", "HOWMUCH")),
("przewodnik (osoba)", "kái", "ไกด์", "Miejsca i orientacja", "Wypoczynek", "word", 3, "n", "", "",
 ("Czy jest przewodnik?", "HAVE")),

# =====================================================================
# RELACJE MIEDZYLUDZKIE
# =====================================================================
("Miło cię poznać.", "yin dii thîi dâi rúu-jàk khráp", "ยินดีที่ได้รู้จักครับ",
 "Podstawy i grzeczność", "Poznawanie", "phrase", 5, "f", "„rúu-jàk” = znać kogoś.", "",
 ("Mnie również.", "yin dii chên kan khráp", "ยินดีเช่นกันครับ")),
("Znamy się od dawna.", "raw rúu-jàk kan maa naan láew khráp", "เรารู้จักกันมานานแล้วครับ",
 "Ludzie i rodzina", "Relacje", "phrase", 3, "n", "", "",
 ("Od ilu lat?", "kìi pii láew khráp", "กี่ปีแล้วครับ")),
("To mój dobry znajomy.", "khǎo pen phûean sà-nìt khǎwng phǒm khráp", "เขาเป็นเพื่อนสนิทของผมครับ",
 "Ludzie i rodzina", "Relacje", "phrase", 3, "n", "„sà-nìt” = bliski, zażyły.", "",
 ("Miło mi.", "yin dii khráp", "ยินดีครับ")),
("Jesteśmy tylko przyjaciółmi.", "raw pen khâe phûean khráp", "เราเป็นแค่เพื่อนครับ",
 "Ludzie i rodzina", "Relacje", "phrase", 3, "i", "„khâe” = tylko, jedynie.", "",
 ("Rozumiem.", "khâo-jai khráp", "เข้าใจครับ")),
("Mam dziewczynę.", "phǒm mii faen láew khráp", "ผมมีแฟนแล้วครับ",
 "Ludzie i rodzina", "Relacje", "phrase", 4, "i",
 "„faen” obejmuje partnera obu płci — nie ma osobnego słowa.", "",
 ("Od dawna?", "naan rǔe yang khráp", "นานหรือยังครับ")),
("Poznaliśmy się w pracy.", "raw jôe kan thîi thîi tham ngaan khráp", "เราเจอกันที่ที่ทำงานครับ",
 "Ludzie i rodzina", "Relacje", "phrase", 3, "n", "", "",
 ("Ciekawe.", "nâa sǒn jai khráp", "น่าสนใจครับ")),
("Tęsknię za rodziną.", "phǒm khít thǔeng khrâwp-khrua khráp", "ผมคิดถึงครอบครัวครับ",
 "Ludzie i rodzina", "Relacje", "phrase", 4, "n", "„khít thǔeng” = tęsknić.", "dosłownie: myśleć aż do",
 ("To zrozumiałe.", "khâo-jai khráp", "เข้าใจครับ")),
("Tęsknię za tobą.", "phǒm khít thǔeng khun khráp", "ผมคิดถึงคุณครับ",
 "Ludzie i rodzina", "Relacje", "phrase", 4, "i", "", "",
 ("Ja też.", "khít thǔeng mǔean kan khráp", "คิดถึงเหมือนกันครับ")),
("Pokłóciliśmy się.", "raw thá-ló kan khráp", "เราทะเลาะกันครับ",
 "Ludzie i rodzina", "Relacje", "phrase", 2, "n", "„thá-ló” = kłócić się.", "",
 ("O co poszło?", "rûeang à-rai khráp", "เรื่องอะไรครับ")),
("Przeprośmy się.", "khǎw-thôot kan thòe", "ขอโทษกันเถอะ",
 "Ludzie i rodzina", "Relacje", "phrase", 2, "i", "", "",
 ("Zgoda.", "tòk long khráp", "ตกลงครับ")),
("Dziękuję za wszystko.", "khàwp-khun sǎm-ràp thúk yàang khráp", "ขอบคุณสำหรับทุกอย่างครับ",
 "Podstawy i grzeczność", "Podziękowania", "phrase", 4, "f", "", "",
 ("Nie ma za co.", "mâi pen rai khráp", "ไม่เป็นไรครับ")),
("Jesteś bardzo miły.", "khun jai dii mâak khráp", "คุณใจดีมากครับ",
 "Podstawy i grzeczność", "Uprzejmość", "phrase", 4, "n", "„jai dii” = dobre serce, życzliwy.", "",
 ("Drobiazg.", "mâi mii à-rai khráp", "ไม่มีอะไรครับ")),
("Przepraszam za spóźnienie.", "khǎw-thôot thîi maa cháa khráp", "ขอโทษที่มาช้าครับ",
 "Podstawy i grzeczność", "Przeprosiny", "phrase", 4, "f", "", "",
 ("Nic się nie stało.", "mâi pen rai khráp", "ไม่เป็นไรครับ")),
("Przepraszam za kłopot.", "khǎw-thôot thîi róp-kuan khráp", "ขอโทษที่รบกวนครับ",
 "Podstawy i grzeczność", "Przeprosiny", "phrase", 4, "f", "„róp-kuan” = kłopotać, przeszkadzać.", "",
 ("Żaden kłopot.", "mâi róp-kuan khráp", "ไม่รบกวนครับ")),
("To moja wina.", "pen khwaam phìt khǎwng phǒm khráp", "เป็นความผิดของผมครับ",
 "Podstawy i grzeczność", "Przeprosiny", "phrase", 3, "f", "", "",
 ("Nie szkodzi.", "mâi pen rai khráp", "ไม่เป็นไรครับ")),
("Gratulacje!", "yin dii dûai khráp", "ยินดีด้วยครับ",
 "Podstawy i grzeczność", "Życzenia", "phrase", 4, "n", "", "",
 ("Dziękuję!", "khàwp-khun khráp", "ขอบคุณครับ")),
("Wszystkiego najlepszego!", "sùk sǎn wan koet khráp", "สุขสันต์วันเกิดครับ",
 "Podstawy i grzeczność", "Życzenia", "phrase", 4, "n", "", "dosłownie: szczęśliwego dnia urodzin",
 ("Dzięki wielkie!", "khàwp-khun mâak khráp", "ขอบคุณมากครับ")),
("Powodzenia!", "chôok dii khráp", "โชคดีครับ",
 "Podstawy i grzeczność", "Życzenia", "phrase", 5, "n", "Używane też na pożegnanie.", "",
 ("Dziękuję!", "khàwp-khun khráp", "ขอบคุณครับ")),
("Trzymaj się.", "duu lae tua eeng dûai ná khráp", "ดูแลตัวเองด้วยนะครับ",
 "Podstawy i grzeczność", "Życzenia", "phrase", 4, "i", "", "dosłownie: zadbaj o siebie",
 ("Ty też.", "khun kâw mǔean kan khráp", "คุณก็เหมือนกันครับ")),

# =====================================================================
# PROBLEMY I PROSBA O POMOC
# =====================================================================
("Mam problem.", "phǒm mii panhǎa khráp", "ผมมีปัญหาครับ",
 "Awarie i pomoc", "Problemy", "phrase", 5, "n", "", "",
 ("Jaki problem?", "panhǎa à-rai khráp", "ปัญหาอะไรครับ")),
("Możesz mi pomóc?", "chûai phǒm nòi dâai mǎi khráp", "ช่วยผมหน่อยได้ไหมครับ",
 "Awarie i pomoc", "Prośby", "question", 5, "n",
 "„chûai … nòi” to najważniejszy wzorzec prośby po tajsku.", "nòi = łagodzi prośbę",
 ("Oczywiście.", "dâai loei khráp", "ได้เลยครับ")),
("Nie wiem, co robić.", "phǒm mâi rúu jà tham yang-ngai khráp", "ผมไม่รู้จะทำยังไงครับ",
 "Awarie i pomoc", "Problemy", "phrase", 4, "n", "", "",
 ("Spokojnie, pomogę.", "jai yen yen khráp dǐao chûai", "ใจเย็นๆ ครับ เดี๋ยวช่วย")),
("Zgubiłem się.", "phǒm lǒng thaang khráp", "ผมหลงทางครับ",
 "Awarie i pomoc", "Problemy", "phrase", 4, "n", "„lǒng thaang” = zabłądzić.", "",
 ("Dokąd chcesz dojść?", "jà pai nǎi khráp", "จะไปไหนครับ")),
("Nie mogę znaleźć mojego hotelu.", "phǒm hǎa roong-raem mâi jôe khráp", "ผมหาโรงแรมไม่เจอครับ",
 "Awarie i pomoc", "Problemy", "phrase", 3, "n", "„hǎa … mâi jôe” = szukam i nie znajduję.", "",
 ("Jak się nazywa?", "chûe à-rai khráp", "ชื่ออะไรครับ")),
("Skradziono mi portfel.", "krà-pǎo taang doon khà-mooi khráp", "กระเป๋าตังค์โดนขโมยครับ",
 "Awarie i pomoc", "Problemy", "phrase", 3, "n", "", "khà-mooi = kraść, złodziej",
 ("Trzeba iść na policję.", "tâwng pai jâeng khwaam khráp", "ต้องไปแจ้งความครับ")),
("Chcę zgłosić kradzież.", "phǒm yàak jâeng khwaam khráp", "ผมอยากแจ้งความครับ",
 "Awarie i pomoc", "Problemy", "phrase", 3, "f", "„jâeng khwaam” = złożyć zawiadomienie.", "",
 ("Poproszę paszport.", "khǎw phaas-pàwt khráp", "ขอพาสปอร์ตครับ")),
("Zostawiłem torbę w taksówce.", "phǒm luem krà-pǎo wái nai tháek-sîi khráp",
 "ผมลืมกระเป๋าไว้ในแท็กซี่ครับ", "Awarie i pomoc", "Problemy", "phrase", 3, "n", "", "",
 ("Masz paragon?", "mii bai sèt mǎi khráp", "มีใบเสร็จไหมครับ")),
("Proszę zadzwonić na policję.", "chûai thoo hǎa tam-rùat khráp", "ช่วยโทรหาตำรวจครับ",
 "Awarie i pomoc", "Prośby", "phrase", 3, "n", "", "",
 ("Już dzwonię.", "thoo láew khráp", "โทรแล้วครับ")),
("To pilne.", "rûeang dùan khráp", "เรื่องด่วนครับ",
 "Awarie i pomoc", "Problemy", "phrase", 3, "n", "„dùan” = pilny.", "",
 ("Co się stało?", "koet à-rai khûen khráp", "เกิดอะไรขึ้นครับ")),
("Co się stało?", "koet à-rai khûen khráp", "เกิดอะไรขึ้นครับ",
 "Awarie i pomoc", "Problemy", "question", 5, "n", "„koet khûen” = wydarzyć się.", "",
 ("Był wypadek.", "mii ù-bàt-tì-hèet khráp", "มีอุบัติเหตุครับ")),
("Był wypadek.", "mii ù-bàt-tì-hèet khráp", "มีอุบัติเหตุครับ",
 "Awarie i pomoc", "Problemy", "phrase", 3, "f", "", "",
 ("Ktoś jest ranny?", "mii khon jèp mǎi khráp", "มีคนเจ็บไหมครับ")),
("Proszę mi pokazać drogę.", "chûai bàwk thaang nòi khráp", "ช่วยบอกทางหน่อยครับ",
 "Awarie i pomoc", "Prośby", "phrase", 4, "n", "", "",
 ("Idź prosto.", "trong pai khráp", "ตรงไปครับ")),
("Proszę mówić wolniej.", "chûai phûut cháa cháa nòi khráp", "ช่วยพูดช้าๆ หน่อยครับ",
 "Awarie i pomoc", "Prośby", "phrase", 5, "n", "", "",
 ("Dobrze.", "dâai khráp", "ได้ครับ")),
("Proszę to powtórzyć.", "chûai phûut ìik khráng nòi khráp", "ช่วยพูดอีกครั้งหน่อยครับ",
 "Awarie i pomoc", "Prośby", "phrase", 5, "n", "", "",
 ("Powtórzę.", "phûut mài ná khráp", "พูดใหม่นะครับ")),
("Proszę to napisać.", "chûai khǐan hâi nòi khráp", "ช่วยเขียนให้หน่อยครับ",
 "Awarie i pomoc", "Prośby", "phrase", 4, "n", "", "",
 ("Chwileczkę.", "sàk khrûu khráp", "สักครู่ครับ")),
("Czy mówi pan po angielsku?", "phûut phaa-sǎa ang-krìt dâai mǎi khráp", "พูดภาษาอังกฤษได้ไหมครับ",
 "Awarie i pomoc", "Prośby", "question", 5, "n", "", "",
 ("Trochę.", "dâai nít nòi khráp", "ได้นิดหน่อยครับ")),
("Czy ktoś tu mówi po angielsku?", "mii khrai phûut phaa-sǎa ang-krìt dâai mǎi khráp",
 "มีใครพูดภาษาอังกฤษได้ไหมครับ", "Awarie i pomoc", "Prośby", "question", 4, "n", "", "",
 ("Zaraz kogoś zawołam.", "dǐao rîak hâi khráp", "เดี๋ยวเรียกให้ครับ")),

# =====================================================================
# REAKCJE W ROZMOWIE
# =====================================================================
("Naprawdę?", "jing rǔe khráp", "จริงหรือครับ",
 "Small talk", "Reakcje", "phrase", 5, "i", "", "",
 ("Naprawdę.", "jing khráp", "จริงครับ")),
("Serio?", "jing dì", "จริงดิ",
 "Small talk", "Reakcje", "phrase", 4, "p", "Bardzo potoczne — tylko wśród znajomych.", "",
 ("No serio.", "jing sí", "จริงสิ")),
("Nie może być!", "mâi nâa chûea", "ไม่น่าเชื่อ",
 "Small talk", "Reakcje", "phrase", 3, "i", "", "dosłownie: aż trudno uwierzyć",
 ("A jednak.", "tàe kâw jing ná khráp", "แต่ก็จริงนะครับ")),
("Świetnie!", "yîam loei khráp", "เยี่ยมเลยครับ",
 "Small talk", "Reakcje", "phrase", 4, "i", "", "",
 ("Cieszę się.", "dii jai khráp", "ดีใจครับ")),
("Rozumiem.", "khâo-jai láew khráp", "เข้าใจแล้วครับ",
 "Small talk", "Reakcje", "phrase", 5, "n", "", "",
 ("To dobrze.", "dii khráp", "ดีครับ")),
("Aha, rozumiem.", "âw khâo-jai láew khráp", "อ๋อ เข้าใจแล้วครับ",
 "Small talk", "Reakcje", "phrase", 4, "p", "„âw” to tajskie „aha”.", "",
 ("No właśnie.", "nân ná sí khráp", "นั่นน่ะสิครับ")),
("No właśnie.", "nân ná sí khráp", "นั่นน่ะสิครับ",
 "Small talk", "Reakcje", "phrase", 3, "p", "Wyraża zgodę z lekkim „a nie mówiłem”.", "",
 ("Dokładnie tak.", "châi loei khráp", "ใช่เลยครับ")),
("Dokładnie tak.", "châi loei khráp", "ใช่เลยครับ",
 "Small talk", "Reakcje", "phrase", 4, "i", "", "",
 ("Zgadza się.", "thùuk tâwng khráp", "ถูกต้องครับ")),
("Zgadza się.", "thùuk tâwng khráp", "ถูกต้องครับ",
 "Small talk", "Reakcje", "phrase", 4, "n", "", "",
 ("To dobrze.", "dii khráp", "ดีครับ")),
("Chwileczkę.", "raw dǐao ná khráp", "รอเดี๋ยวนะครับ",
 "Small talk", "Reakcje", "phrase", 5, "n", "", "",
 ("Poczekam.", "phǒm raw khráp", "ผมรอครับ")),
("Nie ma sprawy.", "mâi mii panhǎa khráp", "ไม่มีปัญหาครับ",
 "Small talk", "Reakcje", "phrase", 5, "i", "", "",
 ("Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ")),
("To straszne.", "yâe jang loei khráp", "แย่จังเลยครับ",
 "Small talk", "Reakcje", "phrase", 3, "i", "", "",
 ("Niestety.", "chân nán lâe khráp", "ชั้นนั้นแหละครับ")),
("Cieszę się z tego powodu.", "dii jai dûai khráp", "ดีใจด้วยครับ",
 "Small talk", "Reakcje", "phrase", 4, "n", "", "",
 ("Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ")),
("Przykro mi to słyszeć.", "sǐa jai dûai khráp", "เสียใจด้วยครับ",
 "Small talk", "Reakcje", "phrase", 3, "f", "„sǐa jai” = smutek, żal.", "",
 ("Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ")),
("Nic nie szkodzi.", "mâi tâwng khít mâak khráp", "ไม่ต้องคิดมากครับ",
 "Small talk", "Reakcje", "phrase", 3, "i", "", "dosłownie: nie myśl za dużo",
 ("Dziękuję.", "khàwp-khun khráp", "ขอบคุณครับ")),
("Zobaczymy.", "duu kàwn khráp", "ดูก่อนครับ",
 "Small talk", "Reakcje", "phrase", 4, "n", "", "",
 ("Dobrze.", "dâai khráp", "ได้ครับ")),
("Może później.", "wái thii lǎng khráp", "ไว้ทีหลังครับ",
 "Small talk", "Reakcje", "phrase", 4, "n", "", "",
 ("Jak wolisz.", "láew tàe khun khráp", "แล้วแต่คุณครับ")),

# =====================================================================
# UPRZEJME ODMAWIANIE
# =====================================================================
("Dziękuję, ale nie.", "khàwp-khun khráp tàe mâi ao", "ขอบคุณครับ แต่ไม่เอา",
 "Podstawy i grzeczność", "Odmowa", "phrase", 5, "n", "", "",
 ("W porządku.", "mâi pen rai khráp", "ไม่เป็นไรครับ")),
("Może innym razem.", "wái khráng nâa ná khráp", "ไว้ครั้งหน้านะครับ",
 "Podstawy i grzeczność", "Odmowa", "phrase", 5, "n",
 "Najczęstszy sposób uprzejmej odmowy — nie zamyka drzwi.", "",
 ("Jasne.", "dâai khráp", "ได้ครับ")),
("Niestety nie mogę.", "sǐa daai khráp phǒm mâi dâai", "เสียดายครับ ผมไม่ได้",
 "Podstawy i grzeczność", "Odmowa", "phrase", 4, "n", "", "",
 ("Szkoda.", "nâa sǐa daai khráp", "น่าเสียดายครับ")),
("Nie dzisiaj.", "wan níi mâi dâai khráp", "วันนี้ไม่ได้ครับ",
 "Podstawy i grzeczność", "Odmowa", "phrase", 4, "n", "", "",
 ("To kiedy indziej.", "wái wan lǎng ná khráp", "ไว้วันหลังนะครับ")),
("Mam już plany.", "phǒm mii nát láew khráp", "ผมมีนัดแล้วครับ",
 "Podstawy i grzeczność", "Odmowa", "phrase", 4, "n", "", "",
 ("Rozumiem.", "khâo-jai khráp", "เข้าใจครับ")),
("Nie jestem zainteresowany.", "phǒm mâi sǒn jai khráp", "ผมไม่สนใจครับ",
 "Podstawy i grzeczność", "Odmowa", "phrase", 4, "n",
 "Grzeczne, ale stanowcze — przydaje się wobec naganiaczy.", "",
 ("Rozumiem.", "khâo-jai khráp", "เข้าใจครับ")),
("Nie, dziękuję, tylko oglądam.", "mâi khráp khǎw duu kàwn", "ไม่ครับ ขอดูก่อน",
 "Zakupy i pieniądze", "Odmowa", "phrase", 5, "n",
 "Standardowa odpowiedź na „mogę pomóc?” w sklepie.", "",
 ("Proszę bardzo.", "choen duu dâai loei khráp", "เชิญดูได้เลยครับ")),
("Dla mnie to za drogo.", "phaeng koen pai sǎm-ràp phǒm khráp", "แพงเกินไปสำหรับผมครับ",
 "Zakupy i pieniądze", "Odmowa", "phrase", 4, "n", "", "",
 ("Dam zniżkę.", "lót hâi dâai khráp", "ลดให้ได้ครับ")),
("Muszę odmówić.", "phǒm khǎw pà-tì-sèet khráp", "ผมขอปฏิเสธครับ",
 "Podstawy i grzeczność", "Odmowa", "phrase", 2, "f", "„pà-tì-sèet” = odmówić (oficjalnie).", "",
 ("Rozumiem.", "khâo-jai khráp", "เข้าใจครับ")),
("Nie chcę, dziękuję.", "mâi ao khráp khàwp-khun", "ไม่เอาครับ ขอบคุณ",
 "Podstawy i grzeczność", "Odmowa", "phrase", 5, "i", "", "",
 ("W porządku.", "mâi pen rai khráp", "ไม่เป็นไรครับ")),

# =====================================================================
# PRZESZLOSC I PLANY
# =====================================================================
("Byłem już w Tajlandii.", "phǒm khoei maa mueang thai láew khráp", "ผมเคยมาเมืองไทยแล้วครับ",
 "Gramatyka użytkowa", "Przeszłość", "phrase", 4, "n",
 "„khoei” = mieć już za sobą jakieś doświadczenie.", "khoei = już kiedyś",
 ("Ile razy?", "kìi khráng láew khráp", "กี่ครั้งแล้วครับ")),
("Nigdy tam nie byłem.", "phǒm mâi khoei pai khráp", "ผมไม่เคยไปครับ",
 "Gramatyka użytkowa", "Przeszłość", "phrase", 4, "n", "", "mâi khoei = nigdy dotąd",
 ("Warto pojechać.", "nâa pai ná khráp", "น่าไปนะครับ")),
("Wczoraj byłem na targu.", "mûea waan phǒm pai tà-làat maa khráp", "เมื่อวานผมไปตลาดมาครับ",
 "Gramatyka użytkowa", "Przeszłość", "phrase", 4, "n",
 "„… maa” na końcu zdania sygnalizuje czynność zakończoną.", "maa = wróciłem skądś",
 ("Co kupiłeś?", "súe à-rai maa khráp", "ซื้ออะไรมาครับ")),
("W zeszłym tygodniu byłem chory.", "aa-thít thîi láew phǒm mâi sà-baai khráp",
 "อาทิตย์ที่แล้วผมไม่สบายครับ", "Gramatyka użytkowa", "Przeszłość", "phrase", 3, "n",
 "„thîi láew” po jednostce czasu = ubiegły.", "thîi láew = miniony",
 ("Już zdrowszy?", "dii khûen rǔe yang khráp", "ดีขึ้นหรือยังครับ")),
("Właśnie skończyłem.", "phôoeng sèt khráp", "เพิ่งเสร็จครับ",
 "Gramatyka użytkowa", "Przeszłość", "phrase", 4, "n", "„phôoeng” = dopiero co.", "phôoeng = dopiero co",
 ("Szybko poszło.", "reo jang khráp", "เร็วจังครับ")),
("Jeszcze tego nie zrobiłem.", "phǒm yang mâi dâi tham khráp", "ผมยังไม่ได้ทำครับ",
 "Gramatyka użytkowa", "Przeszłość", "phrase", 4, "n", "„yang mâi dâi” = jeszcze nie.", "",
 ("Kiedy zrobisz?", "jà tham mûea-rài khráp", "จะทำเมื่อไหร่ครับ")),
("Zamierzam pojechać na północ.", "phǒm jà pai phâak nǔea khráp", "ผมจะไปภาคเหนือครับ",
 "Gramatyka użytkowa", "Plany", "phrase", 3, "n", "„jà” przed czasownikiem = czas przyszły.", "jà = będzie, zamierza",
 ("Kiedy jedziesz?", "pai mûea-rài khráp", "ไปเมื่อไหร่ครับ")),
("Planuję zostać miesiąc.", "phǒm wǎang phǎen yùu nùeng duean khráp", "ผมวางแผนอยู่หนึ่งเดือนครับ",
 "Gramatyka użytkowa", "Plany", "phrase", 3, "f", "„wǎang phǎen” = planować.", "",
 ("Długo.", "naan mǔean kan ná khráp", "นานเหมือนกันนะครับ")),
("Jeszcze nie wiem.", "yang mâi rúu khráp", "ยังไม่รู้ครับ",
 "Gramatyka użytkowa", "Plany", "phrase", 5, "n", "", "",
 ("Daj znać.", "bàwk dûai ná khráp", "บอกด้วยนะครับ")),
("Zdecyduję jutro.", "phrûng níi jà tàt sǐn jai khráp", "พรุ่งนี้จะตัดสินใจครับ",
 "Gramatyka użytkowa", "Plany", "phrase", 3, "f", "„tàt sǐn jai” = podjąć decyzję.", "",
 ("Czekam na odpowiedź.", "raw kham tàwp khráp", "รอคำตอบครับ")),
("Chciałbym tu wrócić.", "phǒm yàak klàp maa ìik khráp", "ผมอยากกลับมาอีกครับ",
 "Gramatyka użytkowa", "Plany", "phrase", 4, "n", "", "",
 ("Czekamy.", "raw yùu ná khráp", "รออยู่นะครับ")),
("Może zostanę dłużej.", "àat jà yùu naan kwàa níi khráp", "อาจจะอยู่นานกว่านี้ครับ",
 "Gramatyka użytkowa", "Plany", "phrase", 3, "n", "„àat jà” = może, być może.", "àat jà = możliwe że",
 ("Byłoby miło.", "dii sí khráp", "ดีสิครับ")),
("Muszę wracać do Polski.", "phǒm tâwng klàp poo-laen khráp", "ผมต้องกลับโปแลนด์ครับ",
 "Gramatyka użytkowa", "Plany", "phrase", 3, "n", "", "",
 ("Kiedy lecisz?", "bin klàp mûea-rài khráp", "บินกลับเมื่อไหร่ครับ")),
("Mój lot jest w sobotę.", "thîao bin khǎwng phǒm wan sǎo khráp", "เที่ยวบินของผมวันเสาร์ครับ",
 "Gramatyka użytkowa", "Plany", "phrase", 3, "n", "", "thîao bin = lot",
 ("Szerokiej drogi.", "doen thaang plàwt-phai ná khráp", "เดินทางปลอดภัยนะครับ")),

# ------------------------------------------------- gramatyka uzytkowa
("już (dokonane)", "láew", "แล้ว", "Gramatyka użytkowa", "Czas", "word", 5, "n",
 "„láew” na końcu zdania zamyka czynność: kin láew = już zjadłem.", "",
 ("Już zjadłem.", "phǒm kin láew khráp", "ผมกินแล้วครับ")),
("jeszcze nie", "yang", "ยัง", "Gramatyka użytkowa", "Czas", "word", 5, "n", "", "",
 ("Jeszcze nie.", "yang khráp", "ยังครับ")),
("dopiero co", "phôoeng", "เพิ่ง", "Gramatyka użytkowa", "Czas", "word", 4, "n", "", "",
 ("Dopiero przyszedłem.", "phǒm phôoeng maa khráp", "ผมเพิ่งมาครับ")),
("kiedykolwiek, już kiedyś", "khoei", "เคย", "Gramatyka użytkowa", "Czas", "word", 5, "n", "", "",
 ("Czy już kiedyś próbowałeś?", "khoei lawng mǎi khráp", "เคยลองไหมครับ")),
("właśnie trwa", "kamlang", "กำลัง", "Gramatyka użytkowa", "Czas", "word", 5, "n",
 "„kamlang” przed czasownikiem = czynność w toku.", "",
 ("Właśnie jem.", "phǒm kamlang kin khráp", "ผมกำลังกินครับ")),
("zamiar, przyszłość", "jà", "จะ", "Gramatyka użytkowa", "Czas", "word", 5, "n", "", "",
 ("Pójdę jutro.", "phrûng níi jà pai khráp", "พรุ่งนี้จะไปครับ")),
("bardziej niż", "kwàa", "กว่า", "Gramatyka użytkowa", "Porównania", "word", 5, "n", "", "",
 ("Ten jest większy.", "an níi yài kwàa khráp", "อันนี้ใหญ่กว่าครับ")),
("najbardziej", "thîi sùt", "ที่สุด", "Gramatyka użytkowa", "Porównania", "word", 5, "n", "", "",
 ("To jest największe.", "an níi yài thîi sùt khráp", "อันนี้ใหญ่ที่สุดครับ")),
("tak samo jak", "mǔean kàp", "เหมือนกับ", "Gramatyka użytkowa", "Porównania", "word", 4, "n", "", "",
 ("To jest tak samo jak tamto.", "an níi mǔean kàp an nán khráp", "อันนี้เหมือนกับอันนั้นครับ")),
("mniej niż", "nói kwàa", "น้อยกว่า", "Gramatyka użytkowa", "Porównania", "word", 4, "n", "", "",
 ("To kosztuje mniej.", "an níi thùuk kwàa khráp", "อันนี้ถูกกว่าครับ")),
("dlatego", "phráw chà-nán", "เพราะฉะนั้น", "Gramatyka użytkowa", "Spójniki", "word", 3, "f", "", "",
 ("Dlatego nie poszedłem.", "phráw chà-nán phǒm mâi pai khráp", "เพราะฉะนั้นผมไม่ไปครับ")),
("ponieważ", "phráw wâa", "เพราะว่า", "Gramatyka użytkowa", "Spójniki", "word", 5, "n", "", "",
 ("Ponieważ pada deszcz.", "phráw wâa fǒn tòk khráp", "เพราะว่าฝนตกครับ")),
("ale", "tàe", "แต่", "Gramatyka użytkowa", "Spójniki", "word", 5, "n", "", "",
 ("Chcę, ale nie mogę.", "yàak tàe mâi dâai khráp", "อยากแต่ไม่ได้ครับ")),
("jeśli", "thâa", "ถ้า", "Gramatyka użytkowa", "Spójniki", "word", 5, "n", "", "",
 ("Jeśli będzie padać, zostanę.", "thâa fǒn tòk phǒm jà yùu bâan khráp", "ถ้าฝนตกผมจะอยู่บ้านครับ")),
("więc, w takim razie", "ngán", "งั้น", "Gramatyka użytkowa", "Spójniki", "word", 4, "p", "", "",
 ("W takim razie idziemy.", "ngán pai kan thòe", "งั้นไปกันเถอะ")),
("chociaż", "thǔeng máe wâa", "ถึงแม้ว่า", "Gramatyka użytkowa", "Spójniki", "word", 2, "f", "", "",
 ("Chociaż jest drogo, kupię.", "thǔeng máe wâa phaeng phǒm kâw jà súe khráp",
  "ถึงแม้ว่าแพงผมก็จะซื้อครับ")),
("na przykład", "chên", "เช่น", "Gramatyka użytkowa", "Spójniki", "word", 3, "f", "", "",
 ("Na przykład to.", "chên an níi khráp", "เช่นอันนี้ครับ")),
("około, mniej więcej", "rao rao", "ราวๆ", "Gramatyka użytkowa", "Określenia", "word", 3, "p", "", "",
 ("Około stu batów.", "rao rao ráwi bàat khráp", "ราวๆ ร้อยบาทครับ")),
]
