# -*- coding: utf-8 -*-
"""Leksyka etapu 5 (B2) — czesc C.

Zakres: negocjowanie i argumentowanie. Otwarcie negocjacji, kontrpropozycja,
ustepstwo, warunek, twarde stanowisko, zamykanie ustalen, budowanie wywodu,
podwazanie cudzego argumentu, wyrazanie watpliwosci.

Format jak w lex_b2_core_a.py.
"""

CORE_C = [

# =====================================================================
# OTWARCIE NEGOCJACJI
# =====================================================================
("porozmawiajmy o warunkach", "khui rûeang ngûean-khǎi kan nòi khráp", "คุยเรื่องเงื่อนไขกันหน่อยครับ",
 "Praca i nauka", "Negocjacje", "sentence", 4, "n",
 "„ngûean-khǎi” = warunki umowy. Kluczowe słowo w każdej negocjacji.", "",
 ("Porozmawiajmy o warunkach przed podpisaniem.", "khui rûeang ngûean-khǎi kàwn sen ná khráp", "คุยเรื่องเงื่อนไขก่อนเซ็นนะครับ")),
("jaka jest pana propozycja?", "khun sà-nǒoe yang-ngai khráp", "คุณเสนอยังไงครับ",
 "Praca i nauka", "Negocjacje", "sentence", 4, "n", "", "",
 ("Jaka jest pana propozycja co do ceny?", "rûeang raa-khaa khun sà-nǒoe yang-ngai khráp", "เรื่องราคาคุณเสนอยังไงครับ")),
("mam propozycję", "phǒm mii khâw sà-nǒoe khráp", "ผมมีข้อเสนอครับ", "Praca i nauka", "Negocjacje", "sentence", 4, "f",
 "„khâw sà-nǒoe” = oferta, propozycja. Rzeczownik urzędowy, ale częsty też w rozmowie.", "",
 ("Mam propozycję, która chyba obu nam pasuje.", "phǒm mii khâw sà-nǒoe thîi nâa jà dii thóng sǎwng fàai khráp", "ผมมีข้อเสนอที่น่าจะดีทั้งสองฝ่ายครับ")),
("otwarty jestem na rozmowę", "khui kan dâai khráp mâi pìt", "คุยกันได้ครับ ไม่ปิด",
 "Praca i nauka", "Negocjacje", "sentence", 4, "n", "", "",
 ("Otwarty jestem na rozmowę o innym terminie.", "rûeang wan khui kan dâai khráp mâi pìt", "เรื่องวันคุยกันได้ครับ ไม่ปิด")),
("co możemy zrobić, żeby się dogadać?", "tham yang-ngai thǔeng jà tòk long kan dâai khráp", "ทำยังไงถึงจะตกลงกันได้ครับ",
 "Praca i nauka", "Negocjacje", "sentence", 4, "n", "", "",
 ("Co możemy zrobić, żeby się dogadać dzisiaj?", "wan níi tham yang-ngai thǔeng jà tòk long kan dâai khráp", "วันนี้ทำยังไงถึงจะตกลงกันได้ครับ")),
("szukam rozwiązania, nie winnego", "phǒm hǎa thaang àwk mâi dâai hǎa khon phìt khráp", "ผมหาทางออกไม่ได้หาคนผิดครับ",
 "Praca i nauka", "Negocjacje", "sentence", 4, "n",
 "„thaang àwk” = wyjście, rozwiązanie. Zdanie od razu obniża temperaturę rozmowy.", "droga wyjścia",
 ("Szukam rozwiązania, nie winnego — usiądźmy do tego.", "phǒm hǎa thaang àwk mâi dâai hǎa khon phìt khráp maa khui kan", "ผมหาทางออกไม่ได้หาคนผิดครับ มาคุยกัน")),

# =====================================================================
# KONTRPROPOZYCJA I TARGOWANIE
# =====================================================================
("a co powiesz na taki układ", "ao yàang níi dii mǎi khráp", "เอาอย่างนี้ดีไหมครับ",
 "Praca i nauka", "Negocjacje", "phrase", 5, "n",
 "Najczęstsze wprowadzenie kontrpropozycji w mowie. Działa i na targu, i w biurze.", "",
 ("A co powiesz na taki układ: ja płacę transport.", "ao yàang níi dii mǎi khráp phǒm àwk khâa sòng eeng", "เอาอย่างนี้ดีไหมครับ ผมออกค่าส่งเอง")),
("spotkajmy się w połowie drogi", "maa khrûeng thaang kan khráp", "มาครึ่งทางกันครับ",
 "Praca i nauka", "Negocjacje", "sentence", 4, "n",
 "IDIOM o tym samym obrazie co polski. Bardzo dobrze odbierany, bo zapowiada ustępstwo obu stron.", "przyjść na pół drogi",
 ("Spotkajmy się w połowie drogi i zamknijmy temat.", "maa khrûeng thaang kan khráp láew jòp rûeang", "มาครึ่งทางกันครับ แล้วจบเรื่อง")),
("to moja ostateczna cena", "raa-khaa níi sùt tháai láew khráp", "ราคานี้สุดท้ายแล้วครับ",
 "Zakupy i pieniądze", "Negocjacje", "sentence", 4, "n",
 "Na targu ten zwrot kończy targowanie. Powiedziany za wcześnie odbiera ci pole manewru.", "",
 ("To moja ostateczna cena, taniej nie mogę.", "raa-khaa níi sùt tháai láew khráp lót ìik mâi wǎai", "ราคานี้สุดท้ายแล้วครับ ลดอีกไม่ไหว")),
("da się coś jeszcze zrobić z ceną?", "raa-khaa phaw jà khà-yàp dâai ìik mǎi khráp", "ราคาพอจะขยับได้อีกไหมครับ",
 "Zakupy i pieniądze", "Negocjacje", "sentence", 4, "n",
 "„khà-yàp” = przesunąć się. Uprzejmiejsze niż „lót nòi” i lepiej działa na wyższych kwotach.", "cena da się przesunąć",
 ("Da się coś jeszcze zrobić z ceną przy większym zamówieniu?", "thâa sàng yóe raa-khaa phaw jà khà-yàp dâai ìik mǎi khráp", "ถ้าสั่งเยอะราคาพอจะขยับได้อีกไหมครับ")),
("jeśli wezmę więcej, będzie taniej?", "thâa ao yóe lót hâi mǎi khráp", "ถ้าเอาเยอะลดให้ไหมครับ",
 "Zakupy i pieniądze", "Negocjacje", "sentence", 4, "n", "", "",
 ("Jeśli wezmę dziesięć sztuk, będzie taniej?", "thâa ao sìp an lót hâi mǎi khráp", "ถ้าเอาสิบอันลดให้ไหมครับ")),
("zgodzę się, ale pod jednym warunkiem", "tòk long khráp tàae khǎw ngûean-khǎi diao", "ตกลงครับ แต่ขอเงื่อนไขเดียว",
 "Praca i nauka", "Negocjacje", "sentence", 4, "n", "", "",
 ("Zgodzę się, ale pod jednym warunkiem — płatność z góry.", "tòk long khráp tàae khǎw ngûean-khǎi diao jàai kàwn", "ตกลงครับ แต่ขอเงื่อนไขเดียว จ่ายก่อน")),
("mogę ustąpić w tej sprawie", "rûeang níi phǒm yawm dâai khráp", "เรื่องนี้ผมยอมได้ครับ",
 "Praca i nauka", "Negocjacje", "sentence", 4, "n",
 "„yawm” = ustąpić, poddać się. W tajskiej kulturze ustąpienie nie jest przegraną, tylko dojrzałością.", "",
 ("Mogę ustąpić w tej sprawie, jeśli pan ustąpi w tamtej.", "rûeang níi phǒm yawm dâai khráp thâa rûeang nán khun yawm bâang", "เรื่องนี้ผมยอมได้ครับ ถ้าเรื่องนั้นคุณยอมบ้าง")),
("tego nie mogę odpuścić", "rûeang níi yawm mâi dâai khráp", "เรื่องนี้ยอมไม่ได้ครับ",
 "Praca i nauka", "Negocjacje", "sentence", 4, "n", "", "",
 ("Tego nie mogę odpuścić, to kwestia bezpieczeństwa.", "rûeang níi yawm mâi dâai khráp man pen rûeang khwaam plàwt-phai", "เรื่องนี้ยอมไม่ได้ครับ มันเป็นเรื่องความปลอดภัย")),
("proponuję kompromis", "khǎw sà-nǒoe thaang saai klaang khráp", "ขอเสนอทางสายกลางครับ",
 "Praca i nauka", "Negocjacje", "sentence", 3, "f",
 "„thaang saai klaang” = droga środka. Pojęcie mocno zakorzenione w buddyjskim myśleniu, więc brzmi bardzo naturalnie.", "droga środkowej linii",
 ("Proponuję kompromis: połowa teraz, połowa po odbiorze.", "khǎw sà-nǒoe thaang saai klaang khráp jàai khrûeng nùeng kàwn", "ขอเสนอทางสายกลางครับ จ่ายครึ่งหนึ่งก่อน")),
("obie strony coś zyskają", "dâai kan thóng sǎwng fàai khráp", "ได้กันทั้งสองฝ่ายครับ",
 "Praca i nauka", "Negocjacje", "sentence", 3, "n", "", "",
 ("Obie strony coś zyskają na takim rozwiązaniu.", "bàep níi dâai kan thóng sǎwng fàai khráp", "แบบนี้ได้กันทั้งสองฝ่ายครับ")),
("to dla mnie nieopłacalne", "bàep níi phǒm mâi khúm khráp", "แบบนี้ผมไม่คุ้มครับ",
 "Zakupy i pieniądze", "Negocjacje", "sentence", 4, "n",
 "„khúm” = opłacalny, wart ceny. Jedno z najczęściej używanych słów przy zakupach.", "",
 ("To dla mnie nieopłacalne przy takim kursie.", "àt-traa lâek-plìan níi phǒm mâi khúm khráp", "อัตราแลกเปลี่ยนนี้ผมไม่คุ้มครับ")),
("cena zawiera wszystko?", "raa-khaa níi ruam thúk yàang láew rǔe yang khráp", "ราคานี้รวมทุกอย่างแล้วหรือยังครับ",
 "Zakupy i pieniądze", "Negocjacje", "sentence", 4, "n",
 "Pytanie ratujące przed dopłatami. Warto zadawać zawsze przed potwierdzeniem.", "",
 ("Cena zawiera wszystko, czy dochodzi podatek?", "raa-khaa níi ruam thúk yàang láew rǔe yang khráp rǔe tâwng bùak phaa-sǐi", "ราคานี้รวมทุกอย่างแล้วหรือยังครับ หรือต้องบวกภาษี")),
("chciałbym to porównać z innymi ofertami", "khǎw pìap thîap kàp thîi ùen kàwn khráp", "ขอเปรียบเทียบกับที่อื่นก่อนครับ",
 "Zakupy i pieniądze", "Negocjacje", "sentence", 3, "n", "", "",
 ("Chciałbym to porównać z innymi ofertami przed decyzją.", "khǎw pìap thîap kàp thîi ùen kàwn tàt-sǐn jai khráp", "ขอเปรียบเทียบกับที่อื่นก่อนตัดสินใจครับ")),
("potrzebuję czasu do namysłu", "khǎw wee-laa khít duu kàwn khráp", "ขอเวลาคิดดูก่อนครับ",
 "Praca i nauka", "Negocjacje", "sentence", 5, "n", "", "",
 ("Potrzebuję czasu do namysłu, odezwę się jutro.", "khǎw wee-laa khít duu kàwn khráp phrûng-níi bàwk", "ขอเวลาคิดดูก่อนครับ พรุ่งนี้บอก")),

# =====================================================================
# ZAMYKANIE USTALEN
# =====================================================================
("umowa stoi", "tòk long taam nán khráp", "ตกลงตามนั้นครับ", "Praca i nauka", "Negocjacje", "sentence", 5, "n", "", "",
 ("Umowa stoi, przygotuję dokumenty.", "tòk long taam nán khráp dǐao triam èek-kà-sǎan hâi", "ตกลงตามนั้นครับ เดี๋ยวเตรียมเอกสารให้")),
("zapiszmy to, żeby było jasno", "khǎw jòt pen laai lák àk-sǎwn ná khráp", "ขอจดเป็นลายลักษณ์อักษรนะครับ",
 "Praca i nauka", "Negocjacje", "sentence", 3, "f", "", "",
 ("Zapiszmy to, żeby było jasno dla obu stron.", "khǎw jòt pen laai lák àk-sǎwn hâi chát thóng sǎwng fàai ná khráp", "ขอจดเป็นลายลักษณ์อักษรให้ชัดทั้งสองฝ่ายนะครับ")),
("kiedy dostanę potwierdzenie?", "jà dâai kaan yuen-yan mûea rài khráp", "จะได้การยืนยันเมื่อไหร่ครับ",
 "Praca i nauka", "Negocjacje", "sentence", 4, "f",
 "„yuen-yan” = potwierdzić. Słowo obowiązkowe przy rezerwacjach i zamówieniach.", "",
 ("Kiedy dostanę potwierdzenie na piśmie?", "jà dâai kaan yuen-yan pen èek-kà-sǎan mûea rài khráp", "จะได้การยืนยันเป็นเอกสารเมื่อไหร่ครับ")),
("kto za co odpowiada?", "khrai ráp phìt châwp sùan nǎi khráp", "ใครรับผิดชอบส่วนไหนครับ",
 "Praca i nauka", "Negocjacje", "sentence", 4, "n", "", "",
 ("Kto za co odpowiada, gdyby coś poszło nie tak?", "thâa mii pan-hǎa khrai ráp phìt châwp sùan nǎi khráp", "ถ้ามีปัญหาใครรับผิดชอบส่วนไหนครับ")),
("ustalmy termin ostateczny", "kam-nòt wan sùt tháai kan ná khráp", "กำหนดวันสุดท้ายกันนะครับ",
 "Praca i nauka", "Negocjacje", "sentence", 4, "f", "", "",
 ("Ustalmy termin ostateczny na koniec miesiąca.", "kam-nòt wan sùt tháai pen sîn duean ná khráp", "กำหนดวันสุดท้ายเป็นสิ้นเดือนนะครับ")),
("co się stanie, jeśli się nie uda?", "thâa mâi sǎm-rèt jà tham yang-ngai khráp", "ถ้าไม่สำเร็จจะทำยังไงครับ",
 "Praca i nauka", "Negocjacje", "sentence", 3, "n", "", "",
 ("Co się stanie, jeśli się nie uda w terminie?", "thâa mâi sǎm-rèt taam kam-nòt jà tham yang-ngai khráp", "ถ้าไม่สำเร็จตามกำหนดจะทำยังไงครับ")),
("wracamy do rozmowy w przyszłym tygodniu", "khui kan tàw aa-thít nâa ná khráp", "คุยกันต่ออาทิตย์หน้านะครับ",
 "Praca i nauka", "Negocjacje", "sentence", 4, "n", "", "",
 ("Wracamy do rozmowy w przyszłym tygodniu z liczbami.", "aa-thít nâa khui tàw phráwm tua lêek ná khráp", "อาทิตย์หน้าคุยต่อพร้อมตัวเลขนะครับ")),

# =====================================================================
# BUDOWANIE ARGUMENTU
# =====================================================================
("po pierwsze", "yàang râek", "อย่างแรก", "Gramatyka użytkowa", "Argumentacja", "phrase", 4, "n", "", "",
 ("Po pierwsze, koszty są wyższe niż zakładaliśmy.", "yàang râek khâa chái jàai sǔung kwàa thîi khâat khráp", "อย่างแรกค่าใช้จ่ายสูงกว่าที่คาดครับ")),
("po drugie", "yàang thîi sǎwng", "อย่างที่สอง", "Gramatyka użytkowa", "Argumentacja", "phrase", 4, "n", "", "",
 ("Po drugie, brakuje nam ludzi.", "yàang thîi sǎwng khon mâi phaw khráp", "อย่างที่สองคนไม่พอครับ")),
("najważniejsze jest to, że", "sìng sǎm-khan thîi sùt khue", "สิ่งสำคัญที่สุดคือ", "Gramatyka użytkowa", "Argumentacja", "phrase", 4, "f", "", "",
 ("Najważniejsze jest to, że klient czeka.", "sìng sǎm-khan thîi sùt khue lûuk-kháa raw yùu khráp", "สิ่งสำคัญที่สุดคือลูกค้ารออยู่ครับ")),
("dowodem na to jest", "sìng thîi yuen-yan dâai khue", "สิ่งที่ยืนยันได้คือ", "Gramatyka użytkowa", "Argumentacja", "phrase", 3, "f", "", "",
 ("Dowodem na to jest zeszłoroczny raport.", "sìng thîi yuen-yan dâai khue raai-ngaan pii thîi láew khráp", "สิ่งที่ยืนยันได้คือรายงานปีที่แล้วครับ")),
("z drugiej strony trzeba pamiętać", "tàae kâw tâwng mâi luem wâa", "แต่ก็ต้องไม่ลืมว่า",
 "Gramatyka użytkowa", "Argumentacja", "phrase", 4, "n", "", "",
 ("Z drugiej strony trzeba pamiętać o kosztach.", "tàae kâw tâwng mâi luem wâa mii khâa chái jàai dûai khráp", "แต่ก็ต้องไม่ลืมว่ามีค่าใช้จ่ายด้วยครับ")),
("to prowadzi do wniosku, że", "man kâw loei sà-rùp dâai wâa", "มันก็เลยสรุปได้ว่า",
 "Gramatyka użytkowa", "Argumentacja", "phrase", 3, "f", "", "",
 ("To prowadzi do wniosku, że trzeba zmienić dostawcę.", "man kâw loei sà-rùp dâai wâa tâwng plìan sáp-plai-yôoe khráp", "มันก็เลยสรุปได้ว่าต้องเปลี่ยนซัพพลายเออร์ครับ")),
("właśnie dlatego uważam, że", "phráw yàang níi phǒm thǔeng khít wâa", "เพราะอย่างนี้ผมถึงคิดว่า",
 "Gramatyka użytkowa", "Argumentacja", "phrase", 4, "n", "", "",
 ("Właśnie dlatego uważam, że warto poczekać.", "phráw yàang níi phǒm thǔeng khít wâa khuan raw kàwn", "เพราะอย่างนี้ผมถึงคิดว่าควรรอก่อน")),
("praktyka pokazuje, że", "jàak prà-sòp-kaan jing man khue", "จากประสบการณ์จริงมันคือ",
 "Praca i nauka", "Argumentacja", "phrase", 3, "f", "", "",
 ("Praktyka pokazuje, że to zajmuje dwa razy dłużej.", "jàak prà-sòp-kaan jing man chái wee-laa sǎwng thâo khráp", "จากประสบการณ์จริงมันใช้เวลาสองเท่าครับ")),
("liczby mówią same za siebie", "tua lêek fâwng yùu láew khráp", "ตัวเลขฟ้องอยู่แล้วครับ",
 "Praca i nauka", "Argumentacja", "sentence", 3, "n",
 "IDIOM. „fâwng” = donosić, oskarżać — liczby same wydają wyrok. Mocne, używaj świadomie.", "liczby donoszą",
 ("Liczby mówią same za siebie, sprzedaż spadła.", "tua lêek fâwng yùu láew khráp yâwt khǎai lót long", "ตัวเลขฟ้องอยู่แล้วครับ ยอดขายลดลง")),
("nie mówię tego bez powodu", "phǒm mâi dâai phûut loi loi khráp", "ผมไม่ได้พูดลอยๆ ครับ",
 "Praca i nauka", "Argumentacja", "sentence", 3, "n", "", "",
 ("Nie mówię tego bez powodu, mam dane.", "phǒm mâi dâai phûut loi loi khráp phǒm mii khâw-muun", "ผมไม่ได้พูดลอยๆ ครับ ผมมีข้อมูล")),
("porównajmy oba warianty", "lawng pìap thîap sǎwng bàep duu khráp", "ลองเปรียบเทียบสองแบบดูครับ",
 "Praca i nauka", "Argumentacja", "sentence", 3, "n", "", "",
 ("Porównajmy oba warianty na spokojnie.", "lawng pìap thîap sǎwng bàep duu jai yen yen khráp", "ลองเปรียบเทียบสองแบบดูใจเย็นๆ ครับ")),

# =====================================================================
# PODWAZANIE CUDZEGO ARGUMENTU
# =====================================================================
("zgadzam się co do zasady, ale", "lák kaan phǒm hěn dûai khráp tàae wâa", "หลักการผมเห็นด้วยครับ แต่ว่า",
 "Praca i nauka", "Argumentacja", "phrase", 4, "f",
 "Tajski schemat sporu: najpierw zgoda, dopiero potem „tàae”. Otwarcie od zaprzeczenia zamyka rozmowę.", "",
 ("Zgadzam się co do zasady, ale nie co do terminu.", "lák kaan phǒm hěn dûai khráp tàae wâa mâi hěn dûai rûeang wan", "หลักการผมเห็นด้วยครับ แต่ว่าไม่เห็นด้วยเรื่องวัน")),
("to prawda tylko częściowo", "man jing baang sùan khráp", "มันจริงบางส่วนครับ", "Cechy i opinie", "Argumentacja", "sentence", 3, "n", "", "",
 ("To prawda tylko częściowo, sytuacja się zmieniła.", "man jing baang sùan khráp sà-thǎa-ná-kaan plìan pai láew", "มันจริงบางส่วนครับ สถานการณ์เปลี่ยนไปแล้ว")),
("skąd te dane?", "khâw-muun níi maa jàak nǎi khráp", "ข้อมูลนี้มาจากไหนครับ",
 "Praca i nauka", "Argumentacja", "sentence", 4, "n", "", "",
 ("Skąd te dane? Chciałbym zobaczyć źródło.", "khâw-muun níi maa jàak nǎi khráp khǎw duu thîi maa nòi", "ข้อมูลนี้มาจากไหนครับ ขอดูที่มาหน่อย")),
("to się nie zgadza z tym, co widziałem", "man mâi trong kàp thîi phǒm hěn maa khráp", "มันไม่ตรงกับที่ผมเห็นมาครับ",
 "Praca i nauka", "Argumentacja", "sentence", 3, "n", "", "",
 ("To się nie zgadza z tym, co widziałem wczoraj.", "man mâi trong kàp thîi phǒm hěn mûea waan khráp", "มันไม่ตรงกับที่ผมเห็นเมื่อวานครับ")),
("a jak wytłumaczyć to, że", "láew jà à-thí-baai yang-ngai wâa", "แล้วจะอธิบายยังไงว่า",
 "Praca i nauka", "Argumentacja", "phrase", 3, "n", "", "",
 ("A jak wytłumaczyć to, że koszty wzrosły?", "láew jà à-thí-baai yang-ngai wâa khâa chái jàai sǔung khûen khráp", "แล้วจะอธิบายยังไงว่าค่าใช้จ่ายสูงขึ้นครับ")),
("to nie do końca tak działa", "man mâi dâai pen bàep nán sǎa thii-diao khráp", "มันไม่ได้เป็นแบบนั้นซะทีเดียวครับ",
 "Cechy i opinie", "Argumentacja", "sentence", 3, "n", "", "",
 ("To nie do końca tak działa, są wyjątki.", "man mâi dâai pen bàep nán sǎa thii-diao khráp mii khâw yók wén", "มันไม่ได้เป็นแบบนั้นซะทีเดียวครับ มีข้อยกเว้น")),
("myślę, że pomijasz jedną rzecz", "phǒm wâa khun khâat pai nùeng yàang khráp", "ผมว่าคุณขาดไปหนึ่งอย่างครับ",
 "Praca i nauka", "Argumentacja", "sentence", 3, "n", "", "",
 ("Myślę, że pomijasz jedną rzecz — czas dostawy.", "phǒm wâa khun khâat pai nùeng yàang khráp wee-laa sòng khǎwng", "ผมว่าคุณขาดไปหนึ่งอย่างครับ เวลาส่งของ")),
("popatrzmy na to z innej strony", "lawng mawng ìik mum nùeng khráp", "ลองมองอีกมุมหนึ่งครับ",
 "Cechy i opinie", "Argumentacja", "sentence", 4, "n", "", "",
 ("Popatrzmy na to z innej strony: co zyskuje klient?", "lawng mawng ìik mum nùeng khráp lûuk-kháa dâai à-rai", "ลองมองอีกมุมหนึ่งครับ ลูกค้าได้อะไร")),
("nie przekonuje mnie ten argument", "hèet-phǒn níi yang mâi phaw khráp", "เหตุผลนี้ยังไม่พอครับ",
 "Cechy i opinie", "Argumentacja", "sentence", 3, "n", "", "",
 ("Nie przekonuje mnie ten argument, potrzebuję liczb.", "hèet-phǒn níi yang mâi phaw khráp khǎw tua lêek", "เหตุผลนี้ยังไม่พอครับ ขอตัวเลข")),
("masz rację, nie pomyślałem o tym", "khun phûut thùuk khráp phǒm khít mâi thǔeng", "คุณพูดถูกครับ ผมคิดไม่ถึง",
 "Cechy i opinie", "Argumentacja", "sentence", 4, "n",
 "Przyznanie racji buduje twarz rozmówcy i twoją wiarygodność. Tajowie to bardzo cenią.", "",
 ("Masz rację, nie pomyślałem o tym wcześniej.", "khun phûut thùuk khráp phǒm khít mâi thǔeng maa kàwn", "คุณพูดถูกครับ ผมคิดไม่ถึงมาก่อน")),

# =====================================================================
# WYRAZANIE WATPLIWOSCI
# =====================================================================
("mam co do tego poważne wątpliwości", "phǒm khâwn khâang sǒng-sǎi khráp", "ผมค่อนข้างสงสัยครับ",
 "Cechy i opinie", "Wątpliwości", "sentence", 4, "n", "", "",
 ("Mam co do tego poważne wątpliwości, sprawdźmy jeszcze raz.", "phǒm khâwn khâang sǒng-sǎi khráp lawng chék ìik khráng", "ผมค่อนข้างสงสัยครับ ลองเช็คอีกครั้ง")),
("brzmi zbyt pięknie", "man dii koen jing pai nòi khráp", "มันดีเกินจริงไปหน่อยครับ",
 "Cechy i opinie", "Wątpliwości", "sentence", 4, "n",
 "Przydatne przy ofertach z targu i w internecie. Sygnalizuje ostrożność bez oskarżenia.", "",
 ("Brzmi zbyt pięknie, wolę sprawdzić opinie.", "man dii koen jing pai nòi khráp khǎw duu rí-wiu kàwn", "มันดีเกินจริงไปหน่อยครับ ขอดูรีวิวก่อน")),
("wolę być ostrożny", "khǎw rá-mát rá-wang wái kàwn khráp", "ขอระมัดระวังไว้ก่อนครับ",
 "Cechy i opinie", "Wątpliwości", "sentence", 3, "f", "", "",
 ("Wolę być ostrożny przy takiej kwocie.", "ngoen jam-nuan níi khǎw rá-mát rá-wang wái kàwn khráp", "เงินจำนวนนี้ขอระมัดระวังไว้ก่อนครับ")),
("coś mi tu nie gra", "man tha-mâi tha-mai khráp", "มันแปลกๆ ครับ", "Cechy i opinie", "Wątpliwości", "sentence", 4, "p",
 "Wyczucie, że coś jest nie tak, bez wskazania konkretu. W piśmie zastąp to „mii khâw sǒng-sǎi”.", "",
 ("Coś mi tu nie gra, cena jest podejrzanie niska.", "man plàek plàek khráp raa-khaa thùuk phìt pòk-kà-tì", "มันแปลกๆ ครับ ราคาถูกผิดปกติ")),
("czy to na pewno legalne?", "an níi thùuk kòt-mǎai nâe mǎi khráp", "อันนี้ถูกกฎหมายแน่ไหมครับ",
 "Praca i nauka", "Wątpliwości", "sentence", 3, "n", "", "",
 ("Czy to na pewno legalne dla obcokrajowca?", "sǎm-ràp chaao tàang châat an níi thùuk kòt-mǎai nâe mǎi khráp", "สำหรับชาวต่างชาติอันนี้ถูกกฎหมายแน่ไหมครับ")),
("wolałbym mieć to na piśmie", "khǎw pen èek-kà-sǎan dii kwàa khráp", "ขอเป็นเอกสารดีกว่าครับ",
 "Praca i nauka", "Wątpliwości", "sentence", 4, "n", "", "",
 ("Wolałbym mieć to na piśmie, dla pewności.", "khǎw pen èek-kà-sǎan dii kwàa khráp phûea khwaam nâe-nawn", "ขอเป็นเอกสารดีกว่าครับ เพื่อความแน่นอน")),
("nie jestem przekonany", "phǒm yang mâi mân-jai khráp", "ผมยังไม่มั่นใจครับ", "Cechy i opinie", "Wątpliwości", "sentence", 4, "n", "", "",
 ("Nie jestem przekonany, dajmy sobie dzień.", "phǒm yang mâi mân-jai khráp khǎw wee-laa ìik wan", "ผมยังไม่มั่นใจครับ ขอเวลาอีกวัน")),
("kto to gwarantuje?", "khrai pen khon káan-tii khráp", "ใครเป็นคนการันตีครับ",
 "Praca i nauka", "Wątpliwości", "sentence", 3, "n", "", "",
 ("Kto to gwarantuje, jeśli sprzęt się zepsuje?", "thâa khrûeang sǐa khrai pen khon káan-tii khráp", "ถ้าเครื่องเสียใครเป็นคนการันตีครับ")),
("na jakiej podstawie?", "ùen jàak à-rai khráp", "อิงจากอะไรครับ", "Praca i nauka", "Wątpliwości", "sentence", 3, "f",
 "„ing jàak” = opierać się na czymś. W wersji potocznej: „duu jàak à-rai khráp”.", "",
 ("Na jakiej podstawie wyliczono tę kwotę?", "tua lêek níi ing jàak à-rai khráp", "ตัวเลขนี้อิงจากอะไรครับ")),
("chcę zobaczyć to na własne oczy", "khǎw duu kàp taa kàwn khráp", "ขอดูกับตาก่อนครับ",
 "Cechy i opinie", "Wątpliwości", "sentence", 3, "n", "", "",
 ("Chcę zobaczyć to na własne oczy przed zapłatą.", "khǎw duu kàp taa kàwn jàai khráp", "ขอดูกับตาก่อนจ่ายครับ")),
]
