# -*- coding: utf-8 -*-
"""Sesja F — PRZYMIOTNIKI OPISOWE.

Tajski przymiotnik jest zarazem czasownikiem stanu: „aa-hǎan à-ròi” znaczy
doslownie „jedzenie jest smaczne”, bez slowa „byc”. Dlatego kazde haslo dziala
w zdaniu bez zadnego lacznika — to warto pokazac uczacemu sie na przykladach.

Osobna rodzina to przymiotniki z „jai” (serce), ktore opisuja charakter:
jai dii, jai ráwn, jai yen, jai kwâang, jai ráai. Tworza spojny uklad
i sa w tej liscie powiazane ze soba.
"""

CO = "Cechy i opinie"

ADJ = [

# =========================================================== KSZTALT I ROZMIAR
("A1", "szeroki", "kwâang", "กว้าง", CO, "Wymiary", 4, "n",
 "O drodze, pokoju, przestrzeni. To samo słowo w „jai kwâang” znaczy „hojny” — dosłownie „szerokie serce”.",
 "",
 [("Ta droga jest szeroka.", "thà-nǒn níi kwâang khráp", "ถนนนี้กว้างครับ"),
  ("Pokój jest szeroki i jasny.", "hâwng kwâang láe sà-wàang khráp", "ห้องกว้างและสว่างครับ")],
 ["wąski", "hojny", "pokój"], []),

("A2", "wąski", "khâep", "แคบ", CO, "Wymiary", 4, "n",
 "Para do „kwâang”. O uliczce, przejściu, ale też o ciasnym pokoju.",
 "",
 [("Ta uliczka jest wąska.", "sawi níi khâep khráp", "ซอยนี้แคบครับ"),
  ("Pokój jest trochę wąski.", "hâwng khâep nòi khráp", "ห้องแคบหน่อยครับ")],
 ["szeroki", "ciasny"], []),

("A2", "gruby (o przedmiocie)", "nǎa", "หนา", CO, "Wymiary", 3, "n",
 "O książce, tkaninie, ścianie. O człowieku mówi się „ûan”, nie „nǎa”.",
 "",
 [("Ta książka jest gruba.", "nǎng-sǔe lêm níi nǎa khráp", "หนังสือเล่มนี้หนาครับ"),
  ("Poproszę grubszy koc.", "khǎw phâa hòm nǎa kwàa níi khráp", "ขอผ้าห่มหนากว่านี้ครับ")],
 ["cienki", "książka", "koc"], []),

("A2", "cienki", "baang", "บาง", CO, "Wymiary", 3, "n",
 "Para do „nǎa”. To samo słowo znaczy też „niektóre” w „baang khon” — niektórzy ludzie.",
 "",
 [("Ta koszula jest cienka.", "sûea tua níi baang khráp", "เสื้อตัวนี้บางครับ"),
  ("Niektórzy nie lubią ostrego.", "baang khon mâi châwp phèt khráp", "บางคนไม่ชอบเผ็ดครับ")],
 ["gruby (o przedmiocie)", "koszula"], []),

("A2", "okrągły", "klom", "กลม", CO, "Wymiary", 3, "n",
 "O kształcie. „nâa klom” to okrągła twarz — w Tajlandii komplement.",
 "",
 [("Ten stół jest okrągły.", "tó tua níi klom khráp", "โต๊ะตัวนี้กลมครับ"),
  ("Poproszę okrągły talerz.", "khǎw jaan klom khráp", "ขอจานกลมครับ")],
 ["kwadratowy", "stół", "talerz"], []),

("A2", "kwadratowy", "sìi-lìam", "สี่เหลี่ยม", CO, "Wymiary", 2, "n",
 "Dosłownie „czterokątny”. To samo słowo obejmuje prostokąt.",
 "cztery kąty",
 [("Ta torba jest kwadratowa.", "krà-pǎo bai níi sìi-lìam khráp", "กระเป๋าใบนี้สี่เหลี่ยมครับ"),
  ("Poproszę kwadratowe pudełko.", "khǎw klàwng sìi-lìam khráp", "ขอกล่องสี่เหลี่ยมครับ")],
 ["okrągły", "pudełko"], []),

("A2", "pełny", "tem", "เต็ม", CO, "Stan", 5, "n",
 "O naczyniu, autobusie, hotelu. „tem láew” znaczy „nie ma już miejsc”.",
 "",
 [("Autobus jest pełny.", "rót tem láew khráp", "รถเต็มแล้วครับ"),
  ("Hotel jest pełny.", "roong-raem tem khráp", "โรงแรมเต็มครับ")],
 ["pusty", "hotel", "autobus"], []),

("A2", "niski (o człowieku)", "tîa", "เตี้ย", CO, "Wygląd", 3, "n",
 "O wzroście człowieka. O niskim poziomie albo cenie mówi się „tàm”.",
 "",
 [("On jest niski.", "kháo tîa khráp", "เขาเตี้ยครับ"),
  ("Jestem niższy od brata.", "phǒm tîa kwàa phîi chaai khráp", "ผมเตี้ยกว่าพี่ชายครับ")],
 ["wysoki", "niski (o poziomie)"], []),

("A2", "niski (o poziomie)", "tàm", "ต่ำ", CO, "Wymiary", 3, "n",
 "O temperaturze, cenie, ciśnieniu. Nie używa się o wzroście.",
 "",
 [("Cena jest niska.", "raa-khaa tàm khráp", "ราคาต่ำครับ"),
  ("Mam niskie ciśnienie.", "khwaam dan phǒm tàm khráp", "ความดันผมต่ำครับ")],
 ["niski (o człowieku)", "wysoki", "cena"], []),

("A2", "ciasny (o ubraniu)", "kháp", "คับ", CO, "Ubrania", 3, "n",
 "Kluczowe przy przymierzaniu. Para do „lǔam”.",
 "",
 [("Jest za ciasne.", "kháp pai khráp", "คับไปครับ"),
  ("Te buty są ciasne.", "rawng-tháo khûu níi kháp khráp", "รองเท้าคู่นี้คับครับ")],
 ["luźny", "przymierzyć", "rozmiar"], []),

("A2", "luźny", "lǔam", "หลวม", CO, "Ubrania", 3, "n",
 "Para do „kháp”. Ton rosnący.",
 "",
 [("Jest za luźne.", "lǔam pai khráp", "หลวมไปครับ"),
  ("Poproszę mniejszy rozmiar.", "khǎw sái lék kwàa níi khráp", "ขอไซส์เล็กกว่านี้ครับ")],
 ["ciasny (o ubraniu)", "rozmiar"], []),

# ================================================================ FAKTURA
("A2", "ostry (o narzędziu)", "khom", "คม", CO, "Właściwości", 3, "n",
 "O nożu. Ostry w smaku to zupełnie inne słowo — „phèt”. Nie mylić.",
 "",
 [("Ten nóż jest ostry.", "mîit lêm níi khom khráp", "มีดเล่มนี้คมครับ"),
  ("Uważaj, ostre.", "rá-wang khom ná khráp", "ระวังคมนะครับ")],
 ["nóż", "tępy", "uważać"], []),

("A2", "tępy", "thûe", "ทื่อ", CO, "Właściwości", 2, "n",
 "Para do „khom”. O człowieku znaczy „tępy, powolny w myśleniu” — wtedy jest obraźliwe.",
 "",
 [("Ten nóż jest tępy.", "mîit lêm níi thûe khráp", "มีดเล่มนี้ทื่อครับ"),
  ("Nóż jest tępy, nie tnie.", "mîit thûe tàt mâi khâo khráp", "มีดทื่อตัดไม่เข้าครับ")],
 ["ostry (o narzędziu)", "nóż"], []),

("A2", "gładki", "rîap", "เรียบ", CO, "Właściwości", 3, "n",
 "O powierzchni, ale też o stroju bez wzoru: „bàep rîap” to wersja prosta, bez ozdób.",
 "",
 [("Ta ściana jest gładka.", "fǎa níi rîap khráp", "ฝานี้เรียบครับ"),
  ("Poproszę prostą wersję.", "khǎw bàep rîap khráp", "ขอแบบเรียบครับ")],
 ["szorstki", "prosty (zwykły)"], []),

("A2", "szorstki", "khrù-khrà", "ขรุขระ", CO, "Właściwości", 2, "n",
 "O nierównej drodze i powierzchni. Cztery spółgłoski w dwóch sylabach — ćwicz powoli.",
 "",
 [("Ta droga jest wyboista.", "thà-nǒn khrù-khrà khráp", "ถนนขรุขระครับ"),
  ("Powierzchnia jest szorstka.", "phǐu khrù-khrà khráp", "ผิวขรุขระครับ")],
 ["gładki", "ulica"], ["wyboisty"]),

("A2", "kleisty", "nǐao", "เหนียว", CO, "Właściwości", 4, "n",
 "„khâao nǐao” to ryż kleisty — podstawa kuchni północno-wschodniej. To samo słowo w „khîi nǐao” znaczy „skąpy”.",
 "",
 [("Poproszę ryż kleisty.", "khǎw khâao nǐao khráp", "ขอข้าวเหนียวครับ"),
  ("To jest kleiste.", "an níi nǐao khráp", "อันนี้เหนียวครับ")],
 ["skąpy", "ryż"], []),

("A2", "chrupiący", "kràwp", "กรอบ", CO, "Właściwości", 4, "n",
 "Częsty opis w karcie dań: „mǔu kràwp” to chrupiąca wieprzowina.",
 "",
 [("Poproszę chrupiącą wieprzowinę.", "khǎw mǔu kràwp khráp", "ขอหมูกรอบครับ"),
  ("To jest ładnie chrupiące.", "kràwp dii khráp", "กรอบดีครับ")],
 ["smażyć na głębokim", "świnia"], []),

("A2", "śmierdzący", "mǐen", "เหม็น", CO, "Właściwości", 3, "n",
 "Para do „hǎwm”. Mocne słowo — o jedzeniu użyte wprost jest niegrzeczne.",
 "",
 [("Tu brzydko pachnie.", "thîi nîi mǐen khráp", "ที่นี่เหม็นครับ"),
  ("To już śmierdzi.", "an níi mǐen láew khráp", "อันนี้เหม็นแล้วครับ")],
 ["pachnący", "psuć się"], []),

("A2", "pachnący", "hǎwm", "หอม", CO, "Właściwości", 4, "n",
 "O kwiatach, jedzeniu, perfumach. W tajskim to również czasownik „całować przez powąchanie policzka” — tradycyjny gest wobec dziecka.",
 "",
 [("Ładnie pachnie.", "hǎwm dii khráp", "หอมดีครับ"),
  ("Te kwiaty pięknie pachną.", "dàwk-mái níi hǎwm mâak khráp", "ดอกไม้นี้หอมมากครับ")],
 ["śmierdzący", "kwiat"], []),

# ============================================================ CHARAKTER: jai
("A1", "miły (dobry dla ludzi)", "jai dii", "ใจดี", CO, "Charakter", 5, "n",
 "Dosłownie „dobre serce”. Rdzeń całej rodziny przymiotników charakteru — w tajskim cechy człowieka opisuje się przez stan serca.",
 "serce dobre",
 [("Ona jest bardzo miła.", "kháo jai dii mâak khâ", "เขาใจดีมากค่ะ"),
  ("Dziękuję, jest pan bardzo miły.", "khàwp khun khráp khun jai dii mâak", "ขอบคุณครับคุณใจดีมาก")],
 ["złośliwy", "cierpliwy", "hojny"], []),

("A2", "złośliwy", "jai ráai", "ใจร้าย", CO, "Charakter", 3, "n",
 "Dosłownie „złe serce”. Para do „jai dii”. Mocne oskarżenie — nie rzuca się nim lekko.",
 "serce złe",
 [("Nie bądź złośliwy.", "yàa jai ráai khráp", "อย่าใจร้ายครับ"),
  ("To było niedobre z jego strony.", "kháo jai ráai kàp phǒm khráp", "เขาใจร้ายกับผมครับ")],
 ["miły (dobry dla ludzi)", "kłócić się"], []),

("A1", "cierpliwy", "jai yen", "ใจเย็น", CO, "Charakter", 5, "n",
 "Dosłownie „chłodne serce”. Ważne słowo kulturowo: „jai yen yen” to prośba „spokojnie, bez nerwów” i najczęstszy sposób łagodzenia napięcia.",
 "serce chłodne",
 [("Spokojnie, bez nerwów.", "jai yen yen ná khráp", "ใจเย็นๆนะครับ"),
  ("On jest bardzo cierpliwy.", "kháo jai yen mâak khráp", "เขาใจเย็นมากครับ")],
 ["niecierpliwy", "miły (dobry dla ludzi)", "spokojny"], []),

("A2", "niecierpliwy", "jai ráwn", "ใจร้อน", CO, "Charakter", 4, "n",
 "Dosłownie „gorące serce”. Para do „jai yen”. Opisuje kogoś porywczego, kto działa pod wpływem impulsu.",
 "serce gorące",
 [("Nie bądź niecierpliwy.", "yàa jai ráwn khráp", "อย่าใจร้อนครับ"),
  ("Jestem trochę niecierpliwy.", "phǒm jai ráwn nòi khráp", "ผมใจร้อนหน่อยครับ")],
 ["cierpliwy", "spieszyć się"], []),

("A2", "hojny", "jai kwâang", "ใจกว้าง", CO, "Charakter", 3, "n",
 "Dosłownie „szerokie serce”. Ten sam „kwâang” co przy szerokiej drodze.",
 "serce szerokie",
 [("On jest bardzo hojny.", "kháo jai kwâang mâak khráp", "เขาใจกว้างมากครับ"),
  ("Dziękuję za hojność.", "khàwp khun thîi jai kwâang khráp", "ขอบคุณที่ใจกว้างครับ")],
 ["skąpy", "szeroki", "miły (dobry dla ludzi)"], []),

("A2", "skąpy", "khîi nǐao", "ขี้เหนียว", CO, "Charakter", 3, "i",
 "Dosłownie „lepki”. Przedrostek „khîi” tworzy cechy nawykowe i jest nieco żartobliwy: khîi kìat (leniwy), khîi aai (nieśmiały), khîi luem (zapominalski).",
 "kleisty",
 [("On jest skąpy.", "kháo khîi nǐao khráp", "เขาขี้เหนียวครับ"),
  ("Nie bądź skąpy.", "yàa khîi nǐao sí khráp", "อย่าขี้เหนียวสิครับ")],
 ["hojny", "kleisty", "leniwy"], []),

("A2", "leniwy", "khîi kìat", "ขี้เกียจ", CO, "Charakter", 4, "i",
 "Ten sam przedrostek „khîi”. Używane też o sobie, żartobliwie: „wan-níi khîi kìat” — dziś mi się nie chce.",
 "",
 [("Dziś mi się nie chce.", "wan-níi phǒm khîi kìat khráp", "วันนี้ผมขี้เกียจครับ"),
  ("Nie bądź leniwy.", "yàa khîi kìat khráp", "อย่าขี้เกียจครับ")],
 ["pracowity", "skąpy", "zmęczony"], []),

("A2", "pracowity", "khà-yǎn", "ขยัน", CO, "Charakter", 4, "n",
 "Para do „khîi kìat”. Mocna pochwała w kontekście pracy i nauki.",
 "",
 [("On jest bardzo pracowity.", "kháo khà-yǎn mâak khráp", "เขาขยันมากครับ"),
  ("Ucz się pilnie.", "khà-yǎn rian ná khráp", "ขยันเรียนนะครับ")],
 ["leniwy", "uczyć się", "praca"], []),

("A2", "nieśmiały", "khîi aai", "ขี้อาย", CO, "Charakter", 3, "n",
 "Ten sam przedrostek „khîi”. Cecha oceniana w Tajlandii raczej pozytywnie niż jako wada.",
 "",
 [("Jestem nieśmiały.", "phǒm khîi aai khráp", "ผมขี้อายครับ"),
  ("Ona jest nieśmiała.", "kháo khîi aai khâ", "เขาขี้อายค่ะ")],
 ["odważny", "leniwy"], []),

("A2", "odważny", "klâa", "กล้า", CO, "Charakter", 3, "n",
 "„klâa” samo znaczy „śmieć coś zrobić”: „mâi klâa” — nie odważę się.",
 "",
 [("Nie odważę się.", "phǒm mâi klâa khráp", "ผมไม่กล้าครับ"),
  ("On jest odważny.", "kháo klâa hǎan khráp", "เขากล้าหาญครับ")],
 ["nieśmiały", "bać się"], []),

("A2", "mądry", "chà-làat", "ฉลาด", CO, "Charakter", 3, "n",
 "O bystrości. „ch” czytaj jak „cz”.",
 "",
 [("To mądre dziecko.", "dèk khon níi chà-làat khráp", "เด็กคนนี้ฉลาดครับ"),
  ("To mądra decyzja.", "pen kaan tàt sǐn jai thîi chà-làat khráp", "เป็นการตัดสินใจที่ฉลาดครับ")],
 ["głupi", "dziecko", "decydować"], []),

("A2", "głupi", "ngôo", "โง่", CO, "Charakter", 2, "i",
 "Mocne słowo, obraźliwe wobec człowieka. O sobie w żartach bywa używane, o innych — nie.",
 "",
 [("Zrobiłem głupstwo.", "phǒm tham à-rai ngôo ngôo khráp", "ผมทำอะไรโง่ๆครับ"),
  ("To był głupi pomysł.", "pen khwaam khít thîi ngôo khráp", "เป็นความคิดที่โง่ครับ")],
 ["mądry"], []),

("A2", "uprzejmy", "sù-phâap", "สุภาพ", CO, "Charakter", 4, "f",
 "O zachowaniu i o stroju: „chút sù-phâap” to strój odpowiedni do świątyni albo urzędu.",
 "",
 [("On jest bardzo uprzejmy.", "kháo sù-phâap mâak khráp", "เขาสุภาพมากครับ"),
  ("Proszę o odpowiedni strój.", "kà-rú-naa tàeng kaai sù-phâap khráp", "กรุณาแต่งกายสุภาพครับ")],
 ["miły (dobry dla ludzi)", "świątynia"], []),

("A2", "szczery", "jing jai", "จริงใจ", CO, "Charakter", 3, "n",
 "Dosłownie „prawdziwe serce”. Kolejny człon rodziny „jai”.",
 "prawdziwe serce",
 [("On jest szczery.", "kháo jing jai khráp", "เขาจริงใจครับ"),
  ("Mówię szczerze.", "phǒm phûut jing jai khráp", "ผมพูดจริงใจครับ")],
 ["miły (dobry dla ludzi)", "prawdziwy"], []),

("A2", "poważny", "jing jang", "จริงจัง", CO, "Charakter", 3, "n",
 "O podejściu do sprawy, nie o smutnej minie. „ao jing jang” — brać coś na serio.",
 "",
 [("Mówisz poważnie?", "khun phûut jing jang mǎi khráp", "คุณพูดจริงจังไหมครับ"),
  ("Podchodzi do pracy poważnie.", "kháo jing jang kàp ngaan khráp", "เขาจริงจังกับงานครับ")],
 ["żartować", "szczery"], []),

# ================================================================ STAN
("A2", "zajęty", "yûng", "ยุ่ง", CO, "Stan", 5, "n",
 "O człowieku i o sytuacji. „yûng” znaczy też „zagmatwany, skomplikowany”.",
 "",
 [("Jestem dziś zajęty.", "wan-níi phǒm yûng khráp", "วันนี้ผมยุ่งครับ"),
  ("Sprawa jest skomplikowana.", "rûeang níi yûng khráp", "เรื่องนี้ยุ่งครับ")],
 ["wolny (niezajęty)", "praca"], []),

("A1", "wolny (niezajęty)", "wâang", "ว่าง", CO, "Stan", 5, "n",
 "O człowieku, stoliku, pokoju. „mii hâwng wâang mǎi” — czy są wolne pokoje?",
 "",
 [("Czy jest wolny stolik?", "mii tó wâang mǎi khráp", "มีโต๊ะว่างไหมครับ"),
  ("Jutro jestem wolny.", "phrûng-níi phǒm wâang khráp", "พรุ่งนี้ผมว่างครับ")],
 ["zajęty", "pusty", "pokój"], []),

("A2", "gotowy", "phráwm", "พร้อม", CO, "Stan", 5, "n",
 "„phráwm láew” — już gotowe. Zbitka „phr” jest trudna: przydech, potem „r”.",
 "",
 [("Jestem gotowy.", "phǒm phráwm láew khráp", "ผมพร้อมแล้วครับ"),
  ("Jedzenie jest gotowe.", "aa-hǎan phráwm láew khráp", "อาหารพร้อมแล้วครับ")],
 ["czekać", "zaczynać"], []),

("A2", "senny", "ngûang nawn", "ง่วงนอน", CO, "Stan", 4, "n",
 "„ng” na początku to jeden dźwięk. Częste po obfitym obiedzie w upale.",
 "",
 [("Jestem senny.", "phǒm ngûang nawn khráp", "ผมง่วงนอนครับ"),
  ("Zrobiło mi się sennie.", "chái phǒm ngûang khráp", "ทำให้ผมง่วงครับ")],
 ["zmęczony", "spać", "zasypiać"], []),

("A2", "silny (fizycznie)", "khǎeng raeng", "แข็งแรง", CO, "Stan", 4, "n",
 "O zdrowiu i sile. „khǎeng” samo znaczy twardy, „raeng” — mocny.",
 "twardy mocny",
 [("Jest silny i zdrowy.", "kháo khǎeng raeng khráp", "เขาแข็งแรงครับ"),
  ("Dbaj o zdrowie.", "raksǎa sù-khà-phâap hâi khǎeng raeng ná khráp", "รักษาสุขภาพให้แข็งแรงนะครับ")],
 ["słaby", "zdrowy", "mięsień"], []),

("A2", "zdrowy", "sù-khà-phâap dii", "สุขภาพดี", CO, "Stan", 4, "n",
 "Dosłownie „dobre zdrowie”. Na pytanie o samopoczucie odpowiada się jednak „sà-baai dii”.",
 "zdrowie dobre",
 [("Jestem zdrowy.", "phǒm sù-khà-phâap dii khráp", "ผมสุขภาพดีครับ"),
  ("Zdrowe jedzenie.", "aa-hǎan sù-khà-phâap khráp", "อาหารสุขภาพครับ")],
 ["chory", "silny (fizycznie)"], []),

("A2", "mocny (o smaku)", "khêm", "เข้ม", CO, "Smak", 4, "n",
 "O kawie, herbacie i o kolorze. Nie o sile fizycznej.",
 "",
 [("Poproszę mocną kawę.", "khǎw kaa-fae khêm khráp", "ขอกาแฟเข้มครับ"),
  ("Za mocne dla mnie.", "khêm koen pai khráp", "เข้มเกินไปครับ")],
 ["ciemny odcień", "kawa"], []),

("A2", "mdły (bez smaku)", "cùet", "จืด", CO, "Smak", 4, "n",
 "Ważne przy zamawianiu: „súp cùet” to zupa łagodna, klarowna — bezpieczny wybór dla kogoś, kto nie znosi ostrego.",
 "",
 [("Poproszę łagodną zupę.", "khǎw súp cùet khráp", "ขอซุปจืดครับ"),
  ("To jest bez smaku.", "an níi cùet khráp", "อันนี้จืดครับ")],
 ["ostry (pikantny)", "zupa", "sól"], ["łagodny"]),

("A1", "ostry (pikantny)", "phèt", "เผ็ด", CO, "Smak", 5, "n",
 "Zdanie „mâi phèt” bywa dla obcokrajowca ważniejsze niż całe menu. Uwaga: „mâi phèt” po tajsku i tak może oznaczać poziom ostry po polsku.",
 "",
 [("Poproszę nieostre.", "mâi phèt khráp", "ไม่เผ็ดครับ"),
  ("Czy to jest ostre?", "an níi phèt mǎi khráp", "อันนี้เผ็ดไหมครับ"),
  ("Za ostre dla mnie.", "phèt koen pai khráp", "เผ็ดเกินไปครับ")],
 ["mdły (bez smaku)", "chili"], []),

("A2", "brzydki", "nâa klìat", "น่าเกลียด", CO, "Wygląd", 3, "n",
 "Dosłownie „godny nienawiści”. Mocniejsze niż polskie „brzydki” — o człowieku brzmi obraźliwie.",
 "godny nienawiści",
 [("Ten wzór jest brzydki.", "laai níi nâa klìat khráp", "ลายนี้น่าเกลียดครับ"),
  ("To zachowanie jest niestosowne.", "tham yàang níi nâa klìat khráp", "ทำอย่างนี้น่าเกลียดครับ")],
 ["ładny", "kolor (barwa)"], []),

("A2", "fałszywy (podrobiony)", "plawm", "ปลอม", CO, "Ocena", 4, "n",
 "Bardzo praktyczne na targu: „khǎwng plawm” to podróbka, „khǎwng tháe” — oryginał.",
 "",
 [("To jest podróbka.", "an níi khǎwng plawm khráp", "อันนี้ของปลอมครับ"),
  ("Czy to jest oryginalne?", "khǎwng tháe rǔe plào khráp", "ของแท้หรือเปล่าครับ")],
 ["prawdziwy", "targ", "oszukać"], ["podrobiony"]),

("A2", "nowoczesny", "than sà-mǎi", "ทันสมัย", CO, "Ocena", 3, "n",
 "Dosłownie „nadążający za epoką”. Para do „láa sà-mǎi” (przestarzały).",
 "nadążać epoka",
 [("Ten hotel jest nowoczesny.", "roong-raem níi than sà-mǎi khráp", "โรงแรมนี้ทันสมัยครับ"),
  ("To już przestarzałe.", "an níi láa sà-mǎi láew khráp", "อันนี้ล้าสมัยแล้วครับ")],
 ["stary", "nowy"], []),

("A2", "sławny", "dang", "ดัง", CO, "Ocena", 4, "n",
 "To samo słowo znaczy „głośny” o dźwięku. „ráan dang” to znany lokal.",
 "",
 [("Ta restauracja jest znana.", "ráan níi dang khráp", "ร้านนี้ดังครับ"),
  ("To znany piosenkarz.", "kháo pen nák ráwng dang khráp", "เขาเป็นนักร้องดังครับ")],
 ["głośny", "popularny", "restauracja"], ["znany"]),

("A2", "popularny", "níyom", "นิยม", CO, "Ocena", 3, "n",
 "O modzie i upodobaniu ogółu. „pen thîi níyom” — cieszący się popularnością.",
 "",
 [("To danie jest popularne.", "aa-hǎan jaan níi pen thîi níyom khráp", "อาหารจานนี้เป็นที่นิยมครับ"),
  ("Ta aplikacja jest popularna.", "áep níi níyom mâak khráp", "แอปนี้นิยมมากครับ")],
 ["sławny", "aplikacja"], []),

("A2", "bogaty", "ruai", "รวย", CO, "Ocena", 3, "n",
 "Ton średni, „uai” to dyftong. Para do „jon” (biedny).",
 "",
 [("On jest bogaty.", "kháo ruai khráp", "เขารวยครับ"),
  ("Chcę być bogaty.", "phǒm yàak ruai khráp", "ผมอยากรวยครับ")],
 ["ubogi", "pieniądze"], []),

("A2", "ubogi", "jon", "จน", CO, "Ocena", 3, "n",
 "Para do „ruai”. To samo słowo w innym użyciu znaczy „aż do” — „jon kwàa”.",
 "",
 [("Byłem wtedy biedny.", "tawn nán phǒm jon khráp", "ตอนนั้นผมจนครับ"),
  ("To biedna okolica.", "thǎew níi khon jon khráp", "แถวนี้คนจนครับ")],
 ["bogaty", "pieniądze"], []),

("A2", "dziwny", "plàek", "แปลก", CO, "Ocena", 4, "n",
 "Znaczy też „obcy, nieznany”: „khon plàek nâa” — ktoś nieznajomy.",
 "",
 [("To dziwne.", "plàek dii khráp", "แปลกดีครับ"),
  ("Ten smak jest dziwny.", "rót plàek khráp", "รสแปลกครับ")],
 ["normalny", "specjalny"], []),

("A2", "normalny", "pòk-kà-tì", "ปกติ", CO, "Ocena", 5, "n",
 "Znaczy też „zwykle” jako przysłówek. „taam pòk-kà-tì” — jak zwykle.",
 "",
 [("Wszystko normalnie.", "pòk-kà-tì khráp", "ปกติครับ"),
  ("Zwykle wstaję o szóstej.", "pòk-kà-tì phǒm tùen hòk mohng khráp", "ปกติผมตื่นหกโมงครับ")],
 ["dziwny", "specjalny", "zwykle"], []),

("A2", "specjalny", "phí-sèet", "พิเศษ", CO, "Ocena", 5, "n",
 "W restauracji „phí-sèet” oznacza dużą porcję: „khâao phàt phí-sèet” to powiększone danie, nie danie specjalne.",
 "",
 [("Poproszę dużą porcję.", "khǎw phí-sèet khráp", "ขอพิเศษครับ"),
  ("Mam specjalną prośbę.", "phǒm mii khǎw phí-sèet khráp", "ผมมีขอพิเศษครับ")],
 ["normalny", "porcja", "dokładka"], []),

("A2", "darmowy", "frii", "ฟรี", CO, "Ocena", 4, "n",
 "Zapożyczenie z angielskiego, w pełni przyswojone. Tradycyjne „mâi khít ngoen” brzmi bardziej formalnie.",
 "",
 [("Czy wi-fi jest darmowe?", "wai-faai frii mǎi khráp", "ไวไฟฟรีไหมครับ"),
  ("Śniadanie jest w cenie.", "aa-hǎan cháo frii khráp", "อาหารเช้าฟรีครับ")],
 ["cena", "wi-fi", "śniadanie"], []),

("A2", "konieczny", "jam pen", "จำเป็น", CO, "Ocena", 4, "n",
 "„mâi jam pen” to uprzejmy sposób odmowy: „nie trzeba”.",
 "",
 [("Nie trzeba.", "mâi jam pen khráp", "ไม่จำเป็นครับ"),
  ("To konieczne.", "an níi jam pen khráp", "อันนี้จำเป็นครับ")],
 ["ważny", "potrzebować"], ["potrzebny"]),

("A2", "możliwy", "pen pai dâai", "เป็นไปได้", CO, "Ocena", 4, "n",
 "Dosłownie „może iść”. Zaprzeczenie „pen pai mâi dâai” to „niemożliwe”.",
 "być iść móc",
 [("Czy to możliwe?", "pen pai dâai mǎi khráp", "เป็นไปได้ไหมครับ"),
  ("To możliwe.", "pen pai dâai khráp", "เป็นไปได้ครับ")],
 ["móc", "konieczny"], []),

("A2", "pewny (przekonany)", "nâe jai", "แน่ใจ", CO, "Ocena", 5, "n",
 "Kolejne wyrażenie z „jai”. „mâi nâe jai” — nie jestem pewien, bardzo częste.",
 "pewne serce",
 [("Jesteś pewien?", "khun nâe jai mǎi khráp", "คุณแน่ใจไหมครับ"),
  ("Nie jestem pewien.", "phǒm mâi nâe jai khráp", "ผมไม่แน่ใจครับ")],
 ["wierzyć", "decydować"], []),

("A2", "spokojny (o miejscu)", "sà-ngòp", "สงบ", CO, "Ocena", 3, "n",
 "O ciszy i braku zamieszania. O człowieku spokojnym mówi się „jai yen”.",
 "",
 [("To spokojne miejsce.", "thîi nîi sà-ngòp khráp", "ที่นี่สงบครับ"),
  ("Szukam spokojnego pokoju.", "phǒm hǎa hâwng sà-ngòp khráp", "ผมหาห้องสงบครับ")],
 ["cierpliwy", "milczeć", "pokój"], []),

("A2", "wolny (powolny)", "cháa", "ช้า", CO, "Ocena", 5, "n",
 "Kluczowe dla uczącego się: „phûut cháa cháa nòi khráp” to prośba o wolniejsze mówienie.",
 "",
 [("Proszę mówić wolniej.", "phûut cháa cháa nòi khráp", "พูดช้าๆหน่อยครับ"),
  ("Internet jest wolny.", "net cháa khráp", "เน็ตช้าครับ")],
 ["szybki", "powtórzyć", "internet"], []),

("A2", "prosty (zwykły)", "thammá-daa", "ธรรมดา", CO, "Ocena", 5, "n",
 "W restauracji oznacza wersję zwykłą, w odróżnieniu od „phí-sèet” (dużej).",
 "",
 [("Poproszę zwykłą porcję.", "khǎw thammá-daa khráp", "ขอธรรมดาครับ"),
  ("To zwykły dzień.", "pen wan thammá-daa khráp", "เป็นวันธรรมดาครับ")],
 ["specjalny", "normalny", "porcja"], ["zwykły"]),

("A2", "trudny do znalezienia", "hǎa yâak", "หายาก", CO, "Ocena", 3, "n",
 "Konstrukcja „czasownik + yâak” tworzy całą serię: „kin yâak” (niejadalny), „tham yâak” (trudny do zrobienia).",
 "szukać trudny",
 [("Trudno to znaleźć.", "hǎa yâak khráp", "หายากครับ"),
  ("To trudne do zrobienia.", "tham yâak khráp", "ทำยากครับ")],
 ["łatwy", "szukać"], []),

("A2", "wart zobaczenia", "nâa duu", "น่าดู", CO, "Ocena", 4, "n",
 "Przedrostek „nâa” tworzy przymiotniki „warty czegoś”: nâa kin (apetyczny), nâa sǒn-jai (ciekawy), nâa rák (uroczy).",
 "warto oglądać",
 [("To warto zobaczyć.", "nâa duu khráp", "น่าดูครับ"),
  ("Ten film jest wart obejrzenia.", "nǎng rûeang níi nâa duu khráp", "หนังเรื่องนี้น่าดูครับ")],
 ["apetyczny", "oglądać", "film"], []),

("A2", "apetyczny", "nâa kin", "น่ากิน", CO, "Ocena", 4, "n",
 "Ten sam przedrostek „nâa”. Dosłownie „godny zjedzenia” — komplement dla kucharza.",
 "warto jeść",
 [("Wygląda apetycznie.", "nâa kin mâak khráp", "น่ากินมากครับ"),
  ("To danie wygląda apetycznie.", "jaan níi nâa kin khráp", "จานนี้น่ากินครับ")],
 ["wart zobaczenia", "smaczny", "jedzenie"], []),

("A2", "przerażający", "nâa klua", "น่ากลัว", CO, "Ocena", 3, "n",
 "Ten sam przedrostek „nâa” plus „klua” (bać się).",
 "warto bać się",
 [("To było straszne.", "nâa klua mâak khráp", "น่ากลัวมากครับ"),
  ("Ta droga jest niebezpieczna.", "thaang níi nâa klua khráp", "ทางนี้น่ากลัวครับ")],
 ["bać się", "niebezpieczny"], ["straszny"]),

("A2", "godny pożałowania", "nâa sǒng-sǎan", "น่าสงสาร", CO, "Ocena", 3, "n",
 "Wyrażenie współczucia. „nâa sǒng-sǎan jang” to reakcja na czyjeś nieszczęście.",
 "warto współczuć",
 [("Biedaczek.", "nâa sǒng-sǎan jang khráp", "น่าสงสารจังครับ"),
  ("Szkoda go.", "kháo nâa sǒng-sǎan khráp", "เขาน่าสงสารครับ")],
 ["smutny", "współczuję"], []),
]
