# -*- coding: utf-8 -*-
"""Leksyka etapu 4 (B1) — czesc B.

Zakres: opowiadanie historii, doswiadczenia z przeszlosci, plany, marzenia,
cele, decyzje, zmiany w zyciu.

Format jak w lex_b1_core_a.py.
"""

CORE_B = [

# =====================================================================
# OPOWIADANIE HISTORII — RAMA NARRACYJNA
# =====================================================================
("Opowiem ci, co się stało.", "jà lâo hâi fang wâa man kòet à-rai khûen khráp",
 "จะเล่าให้ฟังว่ามันเกิดอะไรขึ้นครับ", "Small talk", "Opowiadanie", "sentence", 4, "n",
 "„kòet … khûen” = wydarzyć się. Standardowy początek opowieści.", "",
 ("Słucham.", "fang yùu khráp", "ฟังอยู่ครับ")),
("Na początku wszystko było w porządku.", "tawn râek thúk yàang kâw pòk-kà-tì dii khráp",
 "ตอนแรกทุกอย่างก็ปกติดีครับ", "Gramatyka użytkowa", "Opowiadanie", "sentence", 4, "n",
 "„tawn râek” = na początku, początkowo. Otwiera opowieść z zaskoczeniem w środku.", "",
 ("A potem?", "láew ngai tàw khráp", "แล้วไงต่อครับ")),
("Potem sprawy się skomplikowały.", "lǎng jàak nán rûeang kâw yûng khráp",
 "หลังจากนั้นเรื่องก็ยุ่งครับ", "Gramatyka użytkowa", "Opowiadanie", "sentence", 3, "n",
 "„lǎng jàak nán” = potem, po tym.", "",
 ("Co się stało?", "kòet à-rai khûen khráp", "เกิดอะไรขึ้นครับ")),
("Nagle coś się zmieniło.", "yùu yùu man kâw plìan pai khráp", "อยู่ๆ มันก็เปลี่ยนไปครับ",
 "Gramatyka użytkowa", "Opowiadanie", "sentence", 3, "n",
 "„yùu yùu” = ni stąd, ni zowąd. Ta konstrukcja nie ma polskiego odpowiednika słowo w słowo.", "",
 ("Co takiego?", "à-rai khráp", "อะไรครับ")),
("W końcu wszystko się ułożyło.", "sùt-tháai thúk yàang kâw dii khûen khráp",
 "สุดท้ายทุกอย่างก็ดีขึ้นครับ", "Gramatyka użytkowa", "Opowiadanie", "sentence", 4, "n",
 "„sùt-tháai” = w końcu, ostatecznie.", "",
 ("Całe szczęście.", "khôi yang chûa khráp", "ค่อยยังชั่วครับ")),
("Okazało się, że to nieporozumienie.", "pràa-kòt wâa man khâo-jai phìt kan khráp",
 "ปรากฏว่ามันเข้าใจผิดกันครับ", "Gramatyka użytkowa", "Opowiadanie", "sentence", 3, "f",
 "„pràa-kòt wâa” = okazało się, że. Rejestr wyższy niż potoczne „thîi thae kâw…”.", "",
 ("Dobrze, że się wyjaśniło.", "dii thîi khîi-jaeng khráp", "ดีที่ชี้แจงครับ")),
("Wtedy jeszcze o tym nie wiedziałem.", "tawn nán phǒm yang mâi rúu loei khráp",
 "ตอนนั้นผมยังไม่รู้เลยครับ", "Gramatyka użytkowa", "Opowiadanie", "sentence", 4, "n",
 "„tawn nán” = wtedy, w tamtym momencie.", "",
 ("A kiedy się dowiedziałeś?", "rúu tawn nǎi khráp", "รู้ตอนไหนครับ")),
("Dopiero później to zrozumiałem.", "phôoeng maa khâo-jai thii lǎng khráp",
 "เพิ่งมาเข้าใจทีหลังครับ", "Gramatyka użytkowa", "Opowiadanie", "sentence", 3, "n",
 "„thii lǎng” = później, po fakcie.", "",
 ("Bywa.", "kâw mii bâang khráp", "ก็มีบ้างครับ")),
("Krótko mówiąc, nie wyszło.", "sà-rùp khue mâi sǎm-rèt khráp", "สรุปคือไม่สำเร็จครับ",
 "Gramatyka użytkowa", "Opowiadanie", "sentence", 3, "n", "„sǎm-rèt” = udać się, powieść się.", "",
 ("Szkoda.", "sǐa daai khráp", "เสียดายครับ")),
("To była długa historia.", "man pen rûeang yaao khráp", "มันเป็นเรื่องยาวครับ",
 "Small talk", "Opowiadanie", "sentence", 3, "n", "", "",
 ("Opowiedz kiedyś.", "wái khui kan wan lǎng khráp", "ไว้คุยกันวันหลังครับ")),
("Nigdy tego nie zapomnę.", "phǒm mâi mii wan luem loei khráp", "ผมไม่มีวันลืมเลยครับ",
 "Small talk", "Opowiadanie", "sentence", 3, "n", "„mâi mii wan …” = nigdy w życiu, przenigdy.", "nie ma dnia, bym zapomniał",
 ("Aż tak?", "khà-nàat nán loei rǒe khráp", "ขนาดนั้นเลยหรือครับ")),
("Do dziś to pamiętam.", "jon thǔeng wan níi phǒm yang jam dâai khráp",
 "จนถึงวันนี้ผมยังจำได้ครับ", "Gramatyka użytkowa", "Opowiadanie", "sentence", 3, "n",
 "„jon thǔeng” = aż do.", "",
 ("Musiało zrobić wrażenie.", "khong prà-tháp-jai mâak khráp", "คงประทับใจมากครับ")),

# =====================================================================
# DOSWIADCZENIA Z PRZESZLOSCI
# =====================================================================
("Mieszkam tu od trzech lat.", "phǒm yùu thîi nîi maa sǎam pii láew khráp",
 "ผมอยู่ที่นี่มาสามปีแล้วครับ", "Gramatyka użytkowa", "Przeszłość", "sentence", 4, "n",
 "Wzorzec „… maa X pii láew” opisuje czynność trwającą do teraz. Po polsku jest czas teraźniejszy, po tajsku — „przyszło mi to trwać”.", "",
 ("To już sporo.", "kâw naan mǔean kan ná khráp", "ก็นานเหมือนกันนะครับ")),
("Kiedyś było zupełnie inaczej.", "mûea kàwn man mâi mǔean tawn níi loei khráp",
 "เมื่อก่อนมันไม่เหมือนตอนนี้เลยครับ", "Gramatyka użytkowa", "Przeszłość", "sentence", 4, "n",
 "„mûea kàwn” = dawniej, kiedyś.", "",
 ("Co się zmieniło?", "plìan pai yang-ngai khráp", "เปลี่ยนไปยังไงครับ")),
("Za dawnych czasów mieszkałem na wsi.", "sà-mǎi kàwn phǒm yùu tâang jang-wàt khráp",
 "สมัยก่อนผมอยู่ต่างจังหวัดครับ", "Gramatyka użytkowa", "Przeszłość", "sentence", 3, "n",
 "„tâang jang-wàt” = poza Bangkokiem, na prowincji. Tajowie mówią tak o całym kraju spoza stolicy.", "inna prowincja",
 ("Ładnie tam?", "thîi nân sǔai mǎi khráp", "ที่นั่นสวยไหมครับ")),
("Pracowałem tam przez rok.", "phǒm tham ngaan thîi nân yùu nùeng pii khráp",
 "ผมทำงานที่นั่นอยู่หนึ่งปีครับ", "Praca i nauka", "Przeszłość", "sentence", 3, "n", "", "",
 ("Podobało się?", "châwp mǎi khráp", "ชอบไหมครับ")),
("To było zanim się tu przeprowadziłem.", "man pen kàwn thîi phǒm jà yáai maa yùu thîi nîi khráp",
 "มันเป็นก่อนที่ผมจะย้ายมาอยู่ที่นี่ครับ", "Gramatyka użytkowa", "Przeszłość", "sentence", 3, "n",
 "„kàwn thîi … jà …” = zanim. „yáai” = przeprowadzać się.", "",
 ("Rozumiem.", "khâo-jai khráp", "เข้าใจครับ")),
("Wiele się od tego czasu nauczyłem.", "tâng tàae nán phǒm rian rúu yóe loei khráp",
 "ตั้งแต่นั้นผมเรียนรู้เยอะเลยครับ", "Gramatyka użytkowa", "Przeszłość", "sentence", 3, "n",
 "„tâng tàae nán” = od tamtej pory.", "",
 ("To dobrze.", "dii khráp", "ดีครับ")),
("Żałuję, że tego nie zrobiłem.", "sǐa daai thîi mâi dâi tham khráp", "เสียดายที่ไม่ได้ทำครับ",
 "Cechy i opinie", "Przeszłość", "sentence", 3, "n",
 "„sǐa daai thîi …” = szkoda, że… Tajski nie ma osobnego trybu żalu.", "",
 ("Jeszcze będzie okazja.", "yang mii oo-kàat khráp", "ยังมีโอกาสครับ")),
("Gdybym wiedział, zrobiłbym inaczej.", "thâa rúu tâng tàae râek kâw tham ìik bàep khráp",
 "ถ้ารู้ตั้งแต่แรกก็ทำอีกแบบครับ", "Gramatyka użytkowa", "Przeszłość", "sentence", 3, "n",
 "Tajski buduje tryb przypuszczający przez „thâa …, kâw …”, bez zmiany formy czasownika.", "",
 ("Teraz już wiesz.", "tawn níi kâw rúu láew khráp", "ตอนนี้ก็รู้แล้วครับ")),
("To był dla mnie ważny okres.", "chûang nán sǎm-khan sǎm-ràp phǒm mâak khráp",
 "ช่วงนั้นสำคัญสำหรับผมมากครับ", "Gramatyka użytkowa", "Przeszłość", "sentence", 3, "f",
 "„chûang” = okres, przedział czasu.", "",
 ("Dlaczego?", "thammai khráp", "ทำไมครับ")),
("Dużo wtedy przeszedłem.", "chûang nán phǒm phàan à-rai maa yóe khráp",
 "ช่วงนั้นผมผ่านอะไรมาเยอะครับ", "Gramatyka użytkowa", "Przeszłość", "sentence", 3, "n",
 "„phàan … maa” = przejść przez coś, mieć coś za sobą.", "",
 ("Trzymaj się.", "sûu sûu ná khráp", "สู้ๆ นะครับ")),
("Nie miałem wtedy wyboru.", "tawn nán phǒm mâi mii thaang lûeak khráp",
 "ตอนนั้นผมไม่มีทางเลือกครับ", "Gramatyka użytkowa", "Przeszłość", "sentence", 3, "n",
 "„thaang lûeak” = możliwość wyboru, opcja.", "droga wyboru",
 ("Rozumiem.", "khâo-jai khráp", "เข้าใจครับ")),
("Robiłem to przez wiele lat.", "phǒm tham maa lǎai pii khráp", "ผมทำมาหลายปีครับ",
 "Gramatyka użytkowa", "Przeszłość", "sentence", 3, "n", "", "",
 ("Widać wprawę.", "duu chamnaan ná khráp", "ดูชำนาญนะครับ")),
("Wcześniej nigdy o tym nie słyszałem.", "kàwn nâa níi mâi khoei dâi yin loei khráp",
 "ก่อนหน้านี้ไม่เคยได้ยินเลยครับ", "Gramatyka użytkowa", "Przeszłość", "sentence", 3, "n",
 "„kàwn nâa níi” = wcześniej, przedtem.", "",
 ("Teraz już wiesz.", "tawn níi rúu láew khráp", "ตอนนี้รู้แล้วครับ")),
("Uczyłem się na własnych błędach.", "phǒm rian jàak khwaam phìt phlâat khǎwng tua eeng khráp",
 "ผมเรียนจากความผิดพลาดของตัวเองครับ", "Praca i nauka", "Przeszłość", "sentence", 3, "f",
 "„khwaam phìt phlâat” = błąd, pomyłka.", "",
 ("To najlepsza szkoła.", "pen khruu thîi dii thîi sùt khráp", "เป็นครูที่ดีที่สุดครับ")),

# =====================================================================
# PLANY
# =====================================================================
("Zamierzam zostać tu dłużej.", "phǒm tâng-jai wâa jà yùu tàw ìik nòi khráp",
 "ผมตั้งใจว่าจะอยู่ต่ออีกหน่อยครับ", "Gramatyka użytkowa", "Plany", "sentence", 4, "n",
 "„tâng-jai wâa jà” = mieć zamiar. Mocniejsze niż samo „jà”.", "",
 ("Jak długo?", "naan thâo-rài khráp", "นานเท่าไหร่ครับ")),
("Planuję to na przyszły miesiąc.", "phǒm waang phǎen wái duean nâa khráp",
 "ผมวางแผนไว้เดือนหน้าครับ", "Gramatyka użytkowa", "Plany", "sentence", 4, "n",
 "„waang phǎen” = planować.", "kłaść plan",
 ("Brzmi dobrze.", "duu dii khráp", "ดูดีครับ")),
("Jeszcze się zastanawiam.", "phǒm yang khít yùu khráp", "ผมยังคิดอยู่ครับ",
 "Gramatyka użytkowa", "Plany", "phrase", 4, "n", "", "",
 ("Nie spiesz się.", "mâi tâwng rîip khráp", "ไม่ต้องรีบครับ")),
("Nic jeszcze nie postanowiłem.", "yang mâi dâi tàt-sǐn jai khráp", "ยังไม่ได้ตัดสินใจครับ",
 "Gramatyka użytkowa", "Plany", "sentence", 4, "n", "„tàt-sǐn jai” = zdecydować.", "",
 ("Daj znać.", "bàwk dûai ná khráp", "บอกด้วยนะครับ")),
("Wszystko zależy od pracy.", "thúk yàang khûen yùu kàp ngaan khráp", "ทุกอย่างขึ้นอยู่กับงานครับ",
 "Praca i nauka", "Plany", "sentence", 3, "n", "", "",
 ("Zrozumiałe.", "khâo-jai khráp", "เข้าใจครับ")),
("Chciałbym to zrobić przed końcem roku.", "phǒm yàak tham hâi sèt kàwn sîn pii khráp",
 "ผมอยากทำให้เสร็จก่อนสิ้นปีครับ", "Praca i nauka", "Plany", "sentence", 3, "f",
 "„sîn pii” = koniec roku.", "",
 ("Zdążysz?", "than mǎi khráp", "ทันไหมครับ")),
("Odkładam to na później.", "phǒm khǎw lûean pai kàwn khráp", "ผมขอเลื่อนไปก่อนครับ",
 "Praca i nauka", "Plany", "sentence", 3, "n", "„lûean” = przesunąć termin.", "",
 ("Bez problemu.", "mâi mii pan-hǎa khráp", "ไม่มีปัญหาครับ")),
("Jeśli się uda, pojadę na północ.", "thâa dâai phǒm jà pai phâak nǔea khráp",
 "ถ้าได้ผมจะไปภาคเหนือครับ", "Transport", "Plany", "sentence", 3, "n",
 "„phâak nǔea” = północ Tajlandii: Chiang Mai, Chiang Rai, Pai.", "",
 ("Polecam.", "náe-nam loei khráp", "แนะนำเลยครับ")),
("Mam to w planach na ten rok.", "pii níi mii phǎen wái láew khráp", "ปีนี้มีแผนไว้แล้วครับ",
 "Gramatyka użytkowa", "Plany", "sentence", 3, "n", "", "",
 ("Powodzenia.", "chôok dii khráp", "โชคดีครับ")),
("Zobaczymy, jak się potoczy.", "duu pai kàwn khráp", "ดูไปก่อนครับ",
 "Gramatyka użytkowa", "Plany", "phrase", 4, "p",
 "Bardzo tajskie podejście: nie zamykaj planu na sztywno. Potoczne, ale słyszalne wszędzie.", "",
 ("Racja.", "châi khráp", "ใช่ครับ")),
("Trzeba to dobrze przygotować.", "tâwng triam hâi dii khráp", "ต้องเตรียมให้ดีครับ",
 "Praca i nauka", "Plany", "sentence", 3, "n", "„triam” = przygotować.", "",
 ("Pomogę.", "dǐao chûai khráp", "เดี๋ยวช่วยครับ")),
("Może zmienię plany.", "àat jà plìan phǎen khráp", "อาจจะเปลี่ยนแผนครับ",
 "Gramatyka użytkowa", "Plany", "sentence", 3, "n", "", "",
 ("Daj znać wcześniej.", "bàwk lûang-nâa dûai ná khráp", "บอกล่วงหน้าด้วยนะครับ")),

# =====================================================================
# MARZENIA I CELE
# =====================================================================
("Marzy mi się własny mały lokal.", "phǒm fǎn yàak mii ráan lék lék khǎwng tua eeng khráp",
 "ผมฝันอยากมีร้านเล็กๆ ของตัวเองครับ", "Praca i nauka", "Marzenia", "sentence", 3, "n",
 "„fǎn yàak” = marzyć o czymś. „khǎwng tua eeng” = swój własny.", "",
 ("Fajny pomysł.", "khwaam-khít dii ná khráp", "ความคิดดีนะครับ")),
("Moim celem jest mówić płynnie po tajsku.", "pâo-mǎai khǎwng phǒm khue phûut thai hâi khlâwng khráp",
 "เป้าหมายของผมคือพูดไทยให้คล่องครับ", "Praca i nauka", "Marzenia", "sentence", 4, "f",
 "„pâo-mǎai” = cel. „khlâwng” = płynnie, biegle.", "",
 ("Uda się.", "tham dâai nâe nawn khráp", "ทำได้แน่นอนครับ")),
("Powoli do tego dążę.", "khôi khôi tham pai khráp", "ค่อยๆ ทำไปครับ",
 "Gramatyka użytkowa", "Marzenia", "phrase", 4, "n",
 "„khôi khôi” = powoli, stopniowo. Bardzo częste w rozmowie o nauce i pracy.", "",
 ("Dobra postawa.", "dii khráp", "ดีครับ")),
("Chcę to osiągnąć w ciągu dwóch lat.", "phǒm yàak tham hâi dâai phaai nai sǎwng pii khráp",
 "ผมอยากทำให้ได้ภายในสองปีครับ", "Praca i nauka", "Marzenia", "sentence", 3, "f",
 "„phaai nai” = w ciągu, w obrębie.", "",
 ("Ambitnie.", "tâng jai dii khráp", "ตั้งใจดีครับ")),
("Robię to dla siebie, nie dla innych.", "phǒm tham phûea tua eeng mâi châi phûea khon ùen khráp",
 "ผมทำเพื่อตัวเองไม่ใช่เพื่อคนอื่นครับ", "Ludzie i rodzina", "Marzenia", "sentence", 3, "n",
 "„phûea” = dla, ze względu na.", "",
 ("I dobrze.", "kâw dii khráp", "ก็ดีครับ")),
("Nie poddam się.", "phǒm mâi yawm pháe khráp", "ผมไม่ยอมแพ้ครับ",
 "Cechy i opinie", "Marzenia", "phrase", 3, "n", "„yawm pháe” = poddać się.", "",
 ("Trzymam kciuki.", "pen kamlang jai hâi khráp", "เป็นกำลังใจให้ครับ")),
("To dla mnie ważne.", "man sǎm-khan sǎm-ràp phǒm khráp", "มันสำคัญสำหรับผมครับ",
 "Cechy i opinie", "Marzenia", "sentence", 4, "n", "", "",
 ("Rozumiem.", "khâo-jai khráp", "เข้าใจครับ")),
("Jeszcze mi się to nie udało.", "yang tham mâi sǎm-rèt khráp", "ยังทำไม่สำเร็จครับ",
 "Gramatyka użytkowa", "Marzenia", "sentence", 3, "n", "", "",
 ("Spróbuj dalej.", "lawng tàw pai khráp", "ลองต่อไปครับ")),
("Krok po kroku.", "thii lá khân khráp", "ทีละขั้นครับ", "Gramatyka użytkowa", "Marzenia", "phrase", 3, "n",
 "„thii lá …” = po jednym naraz. Bardzo produktywna konstrukcja: thii lá kham = słowo po słowie.", "",
 ("Zgadza się.", "châi khráp", "ใช่ครับ")),
("Warto mieć jakiś cel.", "mii pâo-mǎai wái kâw dii khráp", "มีเป้าหมายไว้ก็ดีครับ",
 "Praca i nauka", "Marzenia", "sentence", 3, "n", "", "",
 ("Prawda.", "jing khráp", "จริงครับ")),
("Chcę żyć spokojniej.", "phǒm yàak chai chii-wít hâi ngîap long khráp",
 "ผมอยากใช้ชีวิตให้เงียบลงครับ", "Ludzie i rodzina", "Marzenia", "sentence", 3, "n",
 "„chái chii-wít” = żyć, prowadzić życie.", "używać życia",
 ("Rozumiem cię.", "khâo-jai khráp", "เข้าใจครับ")),
("Nie chodzi mi o pieniądze.", "mâi dâi tham phûea ngoen khráp", "ไม่ได้ทำเพื่อเงินครับ",
 "Zakupy i pieniądze", "Marzenia", "sentence", 3, "n", "", "",
 ("A o co?", "láew phûea à-rai khráp", "แล้วเพื่ออะไรครับ")),
("Muszę się do tego lepiej przyłożyć.", "tâwng tâng-jai hâi mâak kwàa níi khráp",
 "ต้องตั้งใจให้มากกว่านี้ครับ", "Praca i nauka", "Marzenia", "sentence", 3, "n",
 "„tâng-jai” = przykładać się, skupiać uwagę.", "",
 ("Dasz radę.", "tham dâai khráp", "ทำได้ครับ")),
("Wierzę, że się uda.", "phǒm chûea wâa tâwng dâai khráp", "ผมเชื่อว่าต้องได้ครับ",
 "Cechy i opinie", "Marzenia", "sentence", 3, "n", "„chûea wâa” = wierzyć, że.", "",
 ("Ja też.", "phǒm kâw chûea khráp", "ผมก็เชื่อครับ")),
("Zaczynam od nowa.", "phǒm rôoem mài khráp", "ผมเริ่มใหม่ครับ",
 "Gramatyka użytkowa", "Marzenia", "phrase", 3, "n", "", "",
 ("Powodzenia.", "chôok dii ná khráp", "โชคดีนะครับ")),
]
