# -*- coding: utf-8 -*-
"""Leksyka etapu 3 (A2) — czesc A.

Zakres: rozszerzona restauracja, preferencje i opinie o jedzeniu, rezerwacje.

Rekord rdzenny, krotka:
    (pl, ph, th, kategoria, podkategoria, typ, frequency, rejestr, notatka, literal, przyklad)

rejestr: "n" neutralny, "f" formalny, "i" nieformalny, "p" potoczny

Przyklad ma dwie dozwolone postacie:
    ("Polskie zdanie.", "NAZWA_WZORCA")        -> strona tajska z PAT3 w stage3.py
    ("Polskie zdanie.", "fonetyka", "tajski")  -> wpisana recznie

Polska strona jest ZAWSZE pisana recznie i odmieniona.
"""

CORE_A = [

# =====================================================================
# RESTAURACJA — wejscie, stolik, rezerwacja
# =====================================================================
("Chciałbym zarezerwować stolik.", "phǒm yàak jawng tó khráp", "ผมอยากจองโต๊ะครับ",
 "Restauracja", "Rezerwacja", "phrase", 5, "f",
 "„jawng” to rezerwować — tak samo hotel, bilet i stolik.", "jawng = rezerwować",
 ("Na którą godzinę?", "kìi moong khráp", "กี่โมงครับ")),
("Mam rezerwację na nazwisko Kowalski.", "phǒm jawng wái nai chûe Kowalski khráp",
 "ผมจองไว้ในชื่อโควาลสกีครับ", "Restauracja", "Rezerwacja", "phrase", 4, "f",
 "„jawng wái” = mam zarezerwowane wcześniej.", "wái = z góry, na zapas",
 ("Proszę chwilę poczekać.", "raw sàk khrûu ná khráp", "รอสักครู่นะครับ")),
("Stolik dla czterech osób poproszę.", "khǎw tó sǎm-ràp sìi khon khráp", "ขอโต๊ะสำหรับสี่คนครับ",
 "Restauracja", "Rezerwacja", "phrase", 5, "n", "", "sǎm-ràp = dla",
 ("Tędy proszę.", "choen thaang níi khráp", "เชิญทางนี้ครับ")),
("Czy macie wolny stolik?", "mii tó wâang mǎi khráp", "มีโต๊ะว่างไหมครับ",
 "Restauracja", "Rezerwacja", "question", 5, "n", "„wâang” = wolny, niezajęty.", "",
 ("Niestety wszystko zajęte.", "tem mòt láew khráp", "เต็มหมดแล้วครับ")),
("Jak długo trzeba czekać?", "tâwng raw naan thâo-rài khráp", "ต้องรอนานเท่าไหร่ครับ",
 "Restauracja", "Rezerwacja", "question", 4, "n", "", "naan = długo (o czasie)",
 ("Jakieś dwadzieścia minut.", "prà-maan yîi-sìp naa-thii khráp", "ประมาณยี่สิบนาทีครับ")),
("Poczekamy.", "raw dâai khráp", "รอได้ครับ", "Restauracja", "Rezerwacja", "phrase", 4, "n",
 "Dosłownie „można poczekać” — naturalna zgoda.", "",
 ("Zapiszę państwa nazwisko.", "khǎw chûe dûai khráp", "ขอชื่อด้วยครับ")),
("Wolimy stolik na zewnątrz.", "raw châwp tó khâang nâwk mâak-kwàa khráp",
 "เราชอบโต๊ะข้างนอกมากกว่าครับ", "Restauracja", "Preferencje", "phrase", 3, "n",
 "„mâak-kwàa” na końcu = wolimy, bardziej.", "",
 ("Proszę bardzo, tam jest wolne.", "choen khráp mii thîi wâang", "เชิญครับ มีที่ว่าง")),
("Czy można usiąść przy oknie?", "nâng khâang nâa-tàang dâai mǎi khráp", "นั่งข้างหน้าต่างได้ไหมครับ",
 "Restauracja", "Preferencje", "question", 3, "n", "", "",
 ("Oczywiście.", "dâai loei khráp", "ได้เลยครับ")),
("Czy jest sala z klimatyzacją?", "mii hâwng ae mǎi khráp", "มีห้องแอร์ไหมครับ",
 "Restauracja", "Preferencje", "question", 4, "n", "", "",
 ("Jest, na piętrze.", "mii khráp yùu chán bon", "มีครับ อยู่ชั้นบน")),
("Odwołuję rezerwację.", "phǒm khǎw yók-lôek kaan jawng khráp", "ผมขอยกเลิกการจองครับ",
 "Restauracja", "Rezerwacja", "phrase", 3, "f", "„yók-lôek” = odwołać, anulować.", "",
 ("Rozumiem, dziękuję za informację.", "khâo-jai khráp khàwp-khun khráp", "เข้าใจครับ ขอบคุณครับ")),
("Spóźnimy się kwadrans.", "raw jà maa cháa prà-maan sìp-hâa naa-thii khráp",
 "เราจะมาช้าประมาณสิบห้านาทีครับ", "Restauracja", "Rezerwacja", "phrase", 3, "n", "", "cháa = późno, wolno",
 ("Nie ma problemu.", "mâi pen rai khráp", "ไม่เป็นไรครับ")),

# ------------------------------------------------- zamawianie
("Jesteśmy gotowi zamówić.", "raw phráwm sàng láew khráp", "เราพร้อมสั่งแล้วครับ",
 "Restauracja", "Zamawianie", "phrase", 5, "n", "„phráwm” = gotowy.", "",
 ("Słucham, co podać?", "ráp à-rai dii khráp", "รับอะไรดีครับ")),
("Co pan poleca?", "náe-nam à-rai dii khráp", "แนะนำอะไรดีครับ",
 "Restauracja", "Zamawianie", "question", 5, "f", "„náe-nam” = polecać, doradzać.", "",
 ("Dziś polecam rybę.", "wan níi náe-nam plaa khráp", "วันนี้แนะนำปลาครับ")),
("Jakie jest danie dnia?", "meen-nuu phí-sèet wan níi khue à-rai khráp", "เมนูพิเศษวันนี้คืออะไรครับ",
 "Restauracja", "Zamawianie", "question", 3, "n", "„phí-sèet” = specjalny.", "",
 ("Dziś jest zupa z krewetkami.", "wan níi mii tôm yam kûng khráp", "วันนี้มีต้มยำกุ้งครับ")),
("To samo dla mnie.", "phǒm ao mǔean kan khráp", "ผมเอาเหมือนกันครับ",
 "Restauracja", "Zamawianie", "phrase", 4, "i", "„mǔean kan” = tak samo, to samo.", "",
 ("Czyli dwa razy to samo.", "sǎwng thîi mǔean kan ná khráp", "สองที่เหมือนกันนะครับ")),
("Najpierw napoje.", "khǎw khrûeang dùem kàwn khráp", "ขอเครื่องดื่มก่อนครับ",
 "Restauracja", "Zamawianie", "phrase", 4, "n", "„kàwn” na końcu = najpierw.", "",
 ("Coś do picia?", "ráp khrûeang dùem à-rai khráp", "รับเครื่องดื่มอะไรครับ")),
("Zamówimy później.", "khǎw sàng thii lǎng khráp", "ขอสั่งทีหลังครับ",
 "Restauracja", "Zamawianie", "phrase", 4, "n", "", "",
 ("Proszę zawołać, gdy będą państwo gotowi.", "rîak dâai loei khráp", "เรียกได้เลยครับ")),
("Czy to danie jest ostre?", "aa-hǎan níi phèt mǎi khráp", "อาหารนี้เผ็ดไหมครับ",
 "Restauracja", "Zamawianie", "question", 5, "n", "", "",
 ("Trochę ostre.", "phèt nít nòi khráp", "เผ็ดนิดหน่อยครับ")),
("Proszę bardzo mało ostre.", "khǎw phèt nói mâak khráp", "ขอเผ็ดน้อยมากครับ",
 "Restauracja", "Zamawianie", "phrase", 5, "n",
 "„nói” to mało; „phèt nói” = słabo ostre.", "",
 ("Zrozumiałem, bez chili.", "khâo-jai khráp mâi sài phrík", "เข้าใจครับ ไม่ใส่พริก")),
("Bez cukru poproszę.", "khǎw mâi sài náam-taan khráp", "ขอไม่ใส่น้ำตาลครับ",
 "Restauracja", "Zamawianie", "phrase", 5, "n", "„sài” = wkładać, dodawać.", "",
 ("Dobrze, bez cukru.", "dâai khráp mâi sài náam-taan", "ได้ครับ ไม่ใส่น้ำตาล")),
("Proszę bez orzeszków.", "khǎw mâi sài thùa khráp", "ขอไม่ใส่ถั่วครับ",
 "Restauracja", "Zamawianie", "phrase", 4, "n", "Ważne przy alergii.", "",
 ("Uczulenie?", "pháe rǔe khráp", "แพ้หรือครับ")),
("Mam uczulenie na owoce morza.", "phǒm pháe aa-hǎan thá-lee khráp", "ผมแพ้อาหารทะเลครับ",
 "Zdrowie", "Alergie", "phrase", 4, "f", "„pháe” = mieć uczulenie.", "",
 ("Powiem kucharzowi.", "jà bàwk phâw khrua khráp", "จะบอกพ่อครัวครับ")),
("Nie jem mięsa.", "phǒm mâi kin núea sàt khráp", "ผมไม่กินเนื้อสัตว์ครับ",
 "Restauracja", "Preferencje", "phrase", 4, "n", "", "núea sàt = mięso zwierzęce",
 ("Jest wersja wegetariańska.", "mii bàep mang-sà-wí-rát khráp", "มีแบบมังสวิรัติครับ")),
("Jestem wegetarianinem.", "phǒm kin jee khráp", "ผมกินเจครับ",
 "Restauracja", "Preferencje", "phrase", 4, "n",
 "„kin jee” to ściśle kuchnia bez mięsa, jajek i czosnku — Tajowie rozumieją to natychmiast.", "",
 ("Wszystko bez mięsa?", "mâi sài núea loei rǔe khráp", "ไม่ใส่เนื้อเลยหรือครับ")),
("Czy w tym jest sos rybny?", "nîi mii náam plaa mǎi khráp", "นี่มีน้ำปลาไหมครับ",
 "Restauracja", "Preferencje", "question", 3, "n", "", "",
 ("Jest, ale mogę pominąć.", "mii khráp tàe mâi sài kâw dâai", "มีครับ แต่ไม่ใส่ก็ได้")),
("Poproszę o mniejszą porcję.", "khǎw thîi lék nòi khráp", "ขอที่เล็กหน่อยครับ",
 "Restauracja", "Zamawianie", "phrase", 3, "n", "", "thîi = porcja, sztuka dania",
 ("Dla dziecka?", "sǎm-ràp dèk rǔe khráp", "สำหรับเด็กหรือครับ")),
("Poproszę o dużą porcję.", "khǎw thîi yài nòi khráp", "ขอที่ใหญ่หน่อยครับ",
 "Restauracja", "Zamawianie", "phrase", 3, "n", "", "",
 ("Dopłata dwadzieścia batów.", "phôoem yîi-sìp bàat khráp", "เพิ่มยี่สิบบาทครับ")),
("Czy mogę zmienić zamówienie?", "khǎw plìan raai-kaan dâai mǎi khráp", "ขอเปลี่ยนรายการได้ไหมครับ",
 "Restauracja", "Zamawianie", "question", 3, "n", "„plìan” = zmienić.", "",
 ("Jeszcze nie zaczęliśmy gotować.", "yang mâi dâi tham khráp", "ยังไม่ได้ทำครับ")),
("Anuluję jedno danie.", "khǎw yók-lôek nùeng yàang khráp", "ขอยกเลิกหนึ่งอย่างครับ",
 "Restauracja", "Zamawianie", "phrase", 3, "n", "", "yàang = rodzaj, pozycja",
 ("Które to danie?", "yàang nǎi khráp", "อย่างไหนครับ")),
("Czy to danie jest już gotowe?", "aa-hǎan sèt rǔe yang khráp", "อาหารเสร็จหรือยังครับ",
 "Restauracja", "Zamawianie", "question", 4, "n", "„… rǔe yang” = czy już…?", "",
 ("Zaraz podajemy.", "sàk khrûu khráp", "สักครู่ครับ")),
("Prosimy o wszystko naraz.", "khǎw sèt phráwm kan khráp", "ขอเสร็จพร้อมกันครับ",
 "Restauracja", "Zamawianie", "phrase", 3, "n", "", "phráwm kan = razem, jednocześnie",
 ("Dobrze, podamy razem.", "dâai khráp sèet phráwm kan", "ได้ครับ เสิร์ฟพร้อมกัน")),

# ------------------------------------------------- w trakcie posilku
("Bardzo mi smakuje.", "à-ràwi mâak khráp", "อร่อยมากครับ",
 "Restauracja", "Opinie", "phrase", 5, "n", "", "",
 ("Cieszę się.", "dii jai khráp", "ดีใจครับ")),
("Smakuje wyśmienicie.", "à-ràwi sùt yâwt khráp", "อร่อยสุดยอดครับ",
 "Restauracja", "Opinie", "phrase", 3, "i", "„sùt yâwt” to mocna pochwała, jak „ekstra”.", "",
 ("Dziękujemy.", "khàwp-khun khráp", "ขอบคุณครับ")),
("Trochę za ostre dla mnie.", "phèt pai nòi sǎm-ràp phǒm khráp", "เผ็ดไปหน่อยสำหรับผมครับ",
 "Restauracja", "Opinie", "phrase", 4, "n", "", "",
 ("Przynieść wodę?", "ao náam mǎi khráp", "เอาน้ำไหมครับ")),
("To jest za słone.", "khem koen pai khráp", "เค็มเกินไปครับ",
 "Restauracja", "Opinie", "phrase", 4, "n", "„koen pai” = ponad miarę.", "",
 ("Przepraszam, wymienię.", "khǎw-thôot khráp dǐao plìan hâi", "ขอโทษครับ เดี๋ยวเปลี่ยนให้")),
("Danie jest zimne.", "aa-hǎan yen khráp", "อาหารเย็นครับ",
 "Restauracja", "Problemy", "phrase", 4, "n",
 "Uwaga: „aa-hǎan yen” znaczy też „kolacja” — tu decyduje kontekst reklamacji.", "",
 ("Podgrzejemy.", "dǐao ùn hâi mài khráp", "เดี๋ยวอุ่นให้ใหม่ครับ")),
("To nie jest to, co zamawiałem.", "nîi mâi châi thîi phǒm sàng khráp", "นี่ไม่ใช่ที่ผมสั่งครับ",
 "Restauracja", "Problemy", "phrase", 4, "n", "", "",
 ("Bardzo przepraszam.", "khǎw-thôot jing jing khráp", "ขอโทษจริงๆ ครับ")),
("Brakuje jednego dania.", "aa-hǎan khàat pai nùeng yàang khráp", "อาหารขาดไปหนึ่งอย่างครับ",
 "Restauracja", "Problemy", "phrase", 3, "n", "„khàat” = brakować.", "",
 ("Sprawdzę zamówienie.", "khǎw chék raai-kaan khráp", "ขอเช็ครายการครับ")),
("Czekamy już bardzo długo.", "raw raw naan mâak láew khráp", "เรารอนานมากแล้วครับ",
 "Restauracja", "Problemy", "phrase", 3, "n", "", "",
 ("Przepraszam za opóźnienie.", "khǎw-thôot thîi cháa khráp", "ขอโทษที่ช้าครับ")),
("Poproszę jeszcze jedną wodę.", "khǎw náam ìik khùat khráp", "ขอน้ำอีกขวดครับ",
 "Restauracja", "Zamawianie", "phrase", 5, "n", "„khùat” to słowo miarowe do butelek.", "",
 ("Zimną?", "ao yen mǎi khráp", "เอาเย็นไหมครับ")),
("Poproszę o dodatkowy talerzyk.", "khǎw jaan lék phôoem khráp", "ขอจานเล็กเพิ่มครับ",
 "Restauracja", "Zastawa", "phrase", 3, "n", "„phôoem” = dodatkowo, więcej.", "",
 ("Ile sztuk?", "kìi bai khráp", "กี่ใบครับ")),
("Poproszę widelec i nóż.", "khǎw sâwm láe mîit khráp", "ขอส้อมและมีดครับ",
 "Restauracja", "Zastawa", "phrase", 4, "n",
 "W Tajlandii standardem są łyżka i widelec — nóż bywa trzeba poprosić osobno.", "",
 ("Zaraz przyniosę.", "dǐao ao maa hâi khráp", "เดี๋ยวเอามาให้ครับ")),
("Poproszę serwetki.", "khǎw krà-dàat chét pàak khráp", "ขอกระดาษเช็ดปากครับ",
 "Restauracja", "Zastawa", "phrase", 4, "n", "", "dosłownie: papier do wycierania ust",
 ("Proszę.", "nîi khráp", "นี่ครับ")),
("Poproszę o lód osobno.", "khǎw náam khǎeng yâek khráp", "ขอน้ำแข็งแยกครับ",
 "Restauracja", "Zamawianie", "phrase", 3, "n", "„yâek” = osobno, oddzielnie.", "",
 ("Dobrze.", "dâai khráp", "ได้ครับ")),
("Bez lodu poproszę.", "khǎw mâi sài náam khǎeng khráp", "ขอไม่ใส่น้ำแข็งครับ",
 "Restauracja", "Zamawianie", "phrase", 4, "n", "", "",
 ("Zwykła woda?", "náam plào châi mǎi khráp", "น้ำเปล่าใช่ไหมครับ")),
("Czy można to zapakować na wynos?", "hàw klàp bâan dâai mǎi khráp", "ห่อกลับบ้านได้ไหมครับ",
 "Restauracja", "Na wynos", "question", 4, "n", "„hàw” = zapakować, zawinąć.", "",
 ("Dorzucę torebkę.", "sài thǔng hâi khráp", "ใส่ถุงให้ครับ")),
("Reszta na wynos poproszę.", "thîi lǔea khǎw hàw klàp bâan khráp", "ที่เหลือขอห่อกลับบ้านครับ",
 "Restauracja", "Na wynos", "phrase", 3, "n", "„lǔea” = zostać, pozostawać.", "",
 ("Chwileczkę.", "sàk khrûu khráp", "สักครู่ครับ")),

# ------------------------------------------------- rachunek
("Poproszę rachunek.", "chék bin dûai khráp", "เช็คบิลด้วยครับ",
 "Restauracja", "Rachunek", "phrase", 5, "n",
 "„chék bin” to zapożyczenie z angielskiego, w Tajlandii całkowicie naturalne.", "",
 ("Razem trzysta batów.", "tháng mòt sǎam ráwi bàat khráp", "ทั้งหมดสามร้อยบาทครับ")),
("Płacimy osobno.", "jàai yâek kan khráp", "จ่ายแยกกันครับ",
 "Restauracja", "Rachunek", "phrase", 4, "n", "", "",
 ("Rozpiszę rachunek.", "dǐao yâek bin hâi khráp", "เดี๋ยวแยกบิลให้ครับ")),
("Ja stawiam.", "phǒm líang eeng khráp", "ผมเลี้ยงเองครับ",
 "Restauracja", "Rachunek", "phrase", 3, "i", "„líang” = postawić komuś, ugościć.", "",
 ("Dziękuję bardzo!", "khàwp-khun mâak khráp", "ขอบคุณมากครับ")),
("Następnym razem ja płacę.", "khráng nâa phǒm jàai eeng khráp", "ครั้งหน้าผมจ่ายเองครับ",
 "Restauracja", "Rachunek", "phrase", 3, "i", "", "khráng nâa = następny raz",
 ("Umowa stoi.", "tòk long khráp", "ตกลงครับ")),
("Czy w rachunku jest już serwis?", "ruam khâa bawrí-kaan láew rǔe yang khráp",
 "รวมค่าบริการแล้วหรือยังครับ", "Restauracja", "Rachunek", "question", 3, "f",
 "„khâa bawrí-kaan” = opłata serwisowa.", "ruam = wliczone",
 ("Tak, dziesięć procent.", "ruam láew khráp sìp poe-sen", "รวมแล้วครับ สิบเปอร์เซ็นต์")),
("Chyba jest błąd w rachunku.", "bin nâa jà phìt khráp", "บิลน่าจะผิดครับ",
 "Restauracja", "Rachunek", "phrase", 3, "n", "„nâa jà” łagodzi zarzut: „chyba, zdaje się”.", "",
 ("Zaraz sprawdzę.", "dǐao chék hâi khráp", "เดี๋ยวเช็คให้ครับ")),
("Nie zamawialiśmy tego.", "raw mâi dâi sàng an níi khráp", "เราไม่ได้สั่งอันนี้ครับ",
 "Restauracja", "Rachunek", "phrase", 3, "n", "", "mâi dâi + czasownik = nie zrobiłem tego",
 ("Przepraszam, poprawię.", "khǎw-thôot khráp dǐao kâe hâi", "ขอโทษครับ เดี๋ยวแก้ให้")),
("Czy mogę zapłacić kartą?", "jàai dûai bàt dâai mǎi khráp", "จ่ายด้วยบัตรได้ไหมครับ",
 "Restauracja", "Rachunek", "question", 5, "n", "", "bàt = karta",
 ("Tylko gotówka.", "ráp ngoen sòt yàang diao khráp", "รับเงินสดอย่างเดียวครับ")),
("Poproszę paragon.", "khǎw bai sèt khráp", "ขอใบเสร็จครับ",
 "Restauracja", "Rachunek", "phrase", 3, "f", "", "bai sèt = pokwitowanie",
 ("Proszę bardzo.", "nîi khráp", "นี่ครับ")),
("Reszty nie trzeba.", "mâi tâwng thawn khráp", "ไม่ต้องทอนครับ",
 "Restauracja", "Rachunek", "phrase", 3, "i", "„thawn” = wydawać resztę.", "",
 ("Dziękuję!", "khàwp-khun khráp", "ขอบคุณครับ")),

# ------------------------------------------------- slownictwo restauracyjne
("karta dań", "meen-nuu", "เมนู", "Restauracja", "Wyposażenie", "word", 5, "n", "", "",
 ("Poproszę kartę.", "ORDER")),
("kelner", "phá-nák-ngaan sèep", "พนักงานเสิร์ฟ", "Restauracja", "Ludzie", "word", 4, "f", "", "",
 ("Gdzie jest kelner?", "WHERE")),
("kucharz", "phâw khrua", "พ่อครัว", "Restauracja", "Ludzie", "word", 3, "n", "", "",
 ("Kucharz gotuje bardzo dobrze.", "phâw khrua tham aa-hǎan kèng mâak", "พ่อครัวทำอาหารเก่งมาก")),
("stolik", "tó", "โต๊ะ", "Restauracja", "Wyposażenie", "word", 5, "n", "", "",
 ("Czy jest wolny stolik?", "HAVE")),
("porcja", "thîi", "ที่", "Restauracja", "Zamawianie", "word", 4, "n",
 "„thîi” liczy porcje: „sǎwng thîi” = dwie porcje.", "",
 ("Poproszę dwie porcje.", "khǎw sǎwng thîi khráp", "ขอสองที่ครับ")),
("dokładka", "phôoem", "เพิ่ม", "Restauracja", "Zamawianie", "word", 4, "n", "", "",
 ("Poproszę dokładkę ryżu.", "khǎw khâao phôoem khráp", "ขอข้าวเพิ่มครับ")),
("przystawka", "aa-hǎan riak náam yâwi", "อาหารเรียกน้ำย่อย",
 "Restauracja", "Menu", "word", 2, "f", "", "dosłownie: jedzenie wywołujące soki trawienne",
 ("Czy są przystawki?", "HAVE")),
("danie główne", "aa-hǎan jaan làk", "อาหารจานหลัก", "Restauracja", "Menu", "word", 3, "n", "", "",
 ("Co jest daniem głównym?", "aa-hǎan jaan làk mii à-rai bâang khráp", "อาหารจานหลักมีอะไรบ้างครับ")),
("deser", "khǎwng wǎan", "ของหวาน", "Restauracja", "Menu", "word", 4, "n", "", "dosłownie: rzecz słodka",
 ("Czy jest deser?", "HAVE")),
("napoje", "khrûeang dùem", "เครื่องดื่ม", "Restauracja", "Menu", "word", 5, "n", "", "",
 ("Gdzie są napoje w karcie?", "WHERE")),
("rachunek", "bin", "บิล", "Restauracja", "Rachunek", "word", 5, "n", "", "",
 ("Poproszę rachunek.", "ORDER")),
("napiwek", "thíp", "ทิป", "Restauracja", "Rachunek", "word", 3, "n",
 "Napiwek nie jest obowiązkowy; zwykle zostawia się drobne.", "",
 ("Zostawię napiwek.", "phǒm jà hâi thíp khráp", "ผมจะให้ทิปครับ")),
("gotówka", "ngoen sòt", "เงินสด", "Zakupy i pieniądze", "Płatności", "word", 5, "n", "", "",
 ("Płacę gotówką.", "phǒm jàai ngoen sòt khráp", "ผมจ่ายเงินสดครับ")),
("karta płatnicza", "bàt kre-dìt", "บัตรเครดิต", "Zakupy i pieniądze", "Płatności", "word", 4, "n", "", "",
 ("Czy przyjmujecie karty?", "ráp bàt kre-dìt mǎi khráp", "รับบัตรเครดิตไหมครับ")),
("przelew", "oon ngoen", "โอนเงิน", "Zakupy i pieniądze", "Płatności", "word", 4, "f", "", "",
 ("Mogę zrobić przelew.", "phǒm oon ngoen dâai khráp", "ผมโอนเงินได้ครับ")),
("kod QR", "khiu-aa khôot", "คิวอาร์โค้ด", "Zakupy i pieniądze", "Płatności", "word", 4, "n",
 "Płatność kodem QR jest w Tajlandii bardzo powszechna.", "",
 ("Zeskanuję kod.", "phǒm sà-kaen khôot khráp", "ผมสแกนโค้ดครับ")),
("smak", "rót châat", "รสชาติ", "Jedzenie i napoje", "Smaki", "word", 4, "n", "", "",
 ("Jaki to smak?", "rót châat pen yang-ngai khráp", "รสชาติเป็นยังไงครับ")),
("ostrość", "khwaam phèt", "ความเผ็ด", "Jedzenie i napoje", "Smaki", "word", 3, "n",
 "„khwaam” tworzy rzeczowniki abstrakcyjne z przymiotników.", "khwaam + cecha = -ość",
 ("Ostrość jest w sam raz.", "khwaam phèt kamlang dii khráp", "ความเผ็ดกำลังดีครับ")),
("łagodny (w smaku)", "mâi phèt", "ไม่เผ็ด", "Jedzenie i napoje", "Smaki", "word", 4, "n", "", "",
 ("Poproszę coś łagodnego.", "khǎw à-rai thîi mâi phèt khráp", "ขออะไรที่ไม่เผ็ดครับ")),
("tłusty", "man", "มัน", "Jedzenie i napoje", "Smaki", "word", 3, "n",
 "To samo słowo znaczy „on/ono” w mowie potocznej — kontekst rozstrzyga.", "",
 ("To jest dla mnie za tłuste.", "man koen pai sǎm-ràp phǒm khráp", "มันเกินไปสำหรับผมครับ")),
("chrupiący", "kràwp", "กรอบ", "Jedzenie i napoje", "Smaki", "word", 3, "n", "", "",
 ("Lubię chrupiące.", "LIKE")),
("miękki (o jedzeniu)", "nûm", "นุ่ม", "Jedzenie i napoje", "Smaki", "word", 3, "n", "", "",
 ("Mięso jest bardzo miękkie.", "núea nûm mâak khráp", "เนื้อนุ่มมากครับ")),
("twardy (o jedzeniu)", "nǐao", "เหนียว", "Jedzenie i napoje", "Smaki", "word", 3, "n",
 "„nǐao” to raczej „ciągnący się, żylasty” niż twardy jak kamień.", "",
 ("Mięso jest trochę twarde.", "núea nǐao nít nòi khráp", "เนื้อเหนียวนิดหน่อยครับ")),
("świeżo zrobione", "tham mài mài", "ทำใหม่ๆ", "Jedzenie i napoje", "Smaki", "word", 3, "p",
 "Podwojenie „mài mài” wzmacnia: całkiem świeże.", "",
 ("To jest świeżo zrobione.", "an níi tham mài mài khráp", "อันนี้ทำใหม่ๆ ครับ")),
("na parze", "nûeng", "นึ่ง", "Jedzenie i napoje", "Przygotowanie", "word", 3, "n", "", "",
 ("Poproszę rybę na parze.", "khǎw plaa nûeng khráp", "ขอปลานึ่งครับ")),
("smażony", "thâwt", "ทอด", "Jedzenie i napoje", "Przygotowanie", "word", 4, "n",
 "„thâwt” to smażenie w głębokim tłuszczu, „phàt” to smażenie na woku.", "",
 ("Czy to jest smażone?", "ISIT")),
("grillowany", "yâang", "ย่าง", "Jedzenie i napoje", "Przygotowanie", "word", 4, "n", "", "",
 ("Poproszę grillowanego kurczaka.", "khǎw kài yâang khráp", "ขอไก่ย่างครับ")),
("gotowany", "tôm", "ต้ม", "Jedzenie i napoje", "Przygotowanie", "word", 4, "n", "", "",
 ("To jest gotowane.", "THIS")),
("pieczony", "òp", "อบ", "Jedzenie i napoje", "Przygotowanie", "word", 3, "n", "", "",
 ("Lubię pieczone.", "LIKE")),
("surowy", "dìp", "ดิบ", "Jedzenie i napoje", "Przygotowanie", "word", 3, "n", "", "",
 ("To jest surowe.", "THIS")),
("dobrze wysmażony", "sùk sùk", "สุกๆ", "Jedzenie i napoje", "Przygotowanie", "word", 3, "n",
 "„sùk” = dojrzały, ugotowany; podwojenie znaczy „porządnie ugotowane”.", "",
 ("Poproszę dobrze wysmażone.", "khǎw sùk sùk khráp", "ขอสุกๆ ครับ")),

# =====================================================================
# PREFERENCJE I OPINIE
# =====================================================================
("Wolę kawę niż herbatę.", "phǒm châwp kaa-fae mâak-kwàa chaa khráp", "ผมชอบกาแฟมากกว่าชาครับ",
 "Cechy i opinie", "Preferencje", "phrase", 4, "n",
 "Schemat: A + mâak-kwàa + B = wolę A od B.", "mâak-kwàa = bardziej niż",
 ("A ja odwrotnie.", "phǒm klàp kan khráp", "ผมกลับกันครับ")),
("Wolałbym coś innego.", "phǒm yàak dâai yàang ùen mâak-kwàa khráp", "ผมอยากได้อย่างอื่นมากกว่าครับ",
 "Cechy i opinie", "Preferencje", "phrase", 3, "n", "", "yàang ùen = coś innego",
 ("Co dokładnie?", "yàang nǎi khráp", "อย่างไหนครับ")),
("Wszystko mi jedno.", "à-rai kâw dâai khráp", "อะไรก็ได้ครับ",
 "Cechy i opinie", "Preferencje", "phrase", 5, "i",
 "Bardzo częsty zwrot; brzmi swobodnie, nie obojętnie.", "dosłownie: cokolwiek też może być",
 ("Naprawdę wszystko jedno?", "à-rai kâw dâai jing jing rǔe khráp", "อะไรก็ได้จริงๆ หรือครับ")),
("Zdecyduj ty.", "khun lûeak loei khráp", "คุณเลือกเลยครับ",
 "Cechy i opinie", "Preferencje", "phrase", 3, "i", "„lûeak” = wybierać.", "",
 ("No dobrze.", "dâai khráp", "ได้ครับ")),
("Nie mam nic przeciwko.", "phǒm mâi wâa à-rai khráp", "ผมไม่ว่าอะไรครับ",
 "Cechy i opinie", "Opinie", "phrase", 3, "n", "„mâi wâa à-rai” = nie mam zastrzeżeń.", "",
 ("To dobrze.", "dii khráp", "ดีครับ")),
("Moim zdaniem to dobry pomysł.", "phǒm khít wâa pen khwaam khít thîi dii khráp",
 "ผมคิดว่าเป็นความคิดที่ดีครับ", "Cechy i opinie", "Opinie", "phrase", 4, "n",
 "„khít wâa” = myślę, że — podstawa wyrażania opinii.", "khít wâa = sądzę, że",
 ("Ja też tak myślę.", "phǒm khít mǔean kan khráp", "ผมคิดเหมือนกันครับ")),
("Nie zgadzam się.", "phǒm mâi hěn dûai khráp", "ผมไม่เห็นด้วยครับ",
 "Cechy i opinie", "Opinie", "phrase", 4, "f", "„hěn dûai” = zgadzać się.", "",
 ("Dlaczego?", "phráw à-rai khráp", "เพราะอะไรครับ")),
("Zgadzam się z tobą.", "phǒm hěn dûai kàp khun khráp", "ผมเห็นด้วยกับคุณครับ",
 "Cechy i opinie", "Opinie", "phrase", 4, "n", "", "",
 ("Dobrze, że tak uważasz.", "dii khráp", "ดีครับ")),
("Częściowo się zgadzam.", "hěn dûai bang sùan khráp", "เห็นด้วยบางส่วนครับ",
 "Cechy i opinie", "Opinie", "phrase", 2, "f", "", "bang sùan = częściowo",
 ("Czyli nie do końca?", "mâi tháng mòt rǔe khráp", "ไม่ทั้งหมดหรือครับ")),
("Nie jestem pewien.", "phǒm mâi nâe jai khráp", "ผมไม่แน่ใจครับ",
 "Cechy i opinie", "Opinie", "phrase", 5, "n", "„nâe jai” = być pewnym.", "",
 ("Zastanów się spokojnie.", "khít duu kàwn khráp", "คิดดูก่อนครับ")),
("Chyba tak.", "khong châi khráp", "คงใช่ครับ",
 "Cechy i opinie", "Opinie", "phrase", 4, "i", "„khong” = pewnie, chyba.", "",
 ("Sprawdźmy.", "lawng chék duu khráp", "ลองเช็คดูครับ")),
("Raczej nie.", "khong mâi khráp", "คงไม่ครับ",
 "Cechy i opinie", "Opinie", "phrase", 4, "i", "", "",
 ("Rozumiem.", "khâo-jai khráp", "เข้าใจครับ")),
("To zależy.", "láew tàe khráp", "แล้วแต่ครับ",
 "Cechy i opinie", "Opinie", "phrase", 4, "n", "„láew tàe” = to zależy, jak wolisz.", "",
 ("Od czego?", "láew tàe à-rai khráp", "แล้วแต่อะไรครับ")),
("Dla mnie w porządku.", "sǎm-ràp phǒm kâw dii khráp", "สำหรับผมก็ดีครับ",
 "Cechy i opinie", "Opinie", "phrase", 4, "i", "", "",
 ("To ustalone.", "tòk long khráp", "ตกลงครับ")),
("Podoba mi się.", "phǒm châwp khráp", "ผมชอบครับ",
 "Cechy i opinie", "Opinie", "phrase", 5, "n", "", "",
 ("Co ci się podoba?", "châwp trong nǎi khráp", "ชอบตรงไหนครับ")),
("Nie bardzo mi się podoba.", "mâi khâwi châwp khráp", "ไม่ค่อยชอบครับ",
 "Cechy i opinie", "Opinie", "phrase", 4, "n",
 "„mâi khâwi” = niezbyt — łagodzi odmowę, bardzo przydatne.", "mâi khâwi = niezbyt",
 ("Szkoda.", "nâa sǐa daai khráp", "น่าเสียดายครับ")),
("Wcale mi się nie podoba.", "mâi châwp loei khráp", "ไม่ชอบเลยครับ",
 "Cechy i opinie", "Opinie", "phrase", 3, "i", "„loei” na końcu wzmacnia przeczenie.", "",
 ("Aż tak?", "khà-nàat nán loei rǔe khráp", "ขนาดนั้นเลยหรือครับ")),
("Bardzo mi się podoba.", "châwp mâak loei khráp", "ชอบมากเลยครับ",
 "Cechy i opinie", "Opinie", "phrase", 4, "i", "", "",
 ("Cieszę się.", "dii jai khráp", "ดีใจครับ")),
("Jest nieźle.", "kâw dii ná khráp", "ก็ดีนะครับ",
 "Cechy i opinie", "Opinie", "phrase", 4, "p", "„kâw … ná” brzmi swobodnie i uprzejmie zarazem.", "",
 ("Tylko nieźle?", "khâe dii rǔe khráp", "แค่ดีหรือครับ")),
("Jest tak sobie.", "ngán ngán khráp", "งั้นๆ ครับ",
 "Cechy i opinie", "Opinie", "phrase", 3, "p", "Potoczne „średnio, nic specjalnego”.", "",
 ("Czyli nie polecasz.", "mâi náe-nam sǐ khráp", "ไม่แนะนำสิครับ")),
("Nic specjalnego.", "mâi mii à-rai phí-sèet khráp", "ไม่มีอะไรพิเศษครับ",
 "Cechy i opinie", "Opinie", "phrase", 3, "n", "", "",
 ("Rozumiem.", "khâo-jai khráp", "เข้าใจครับ")),
("To najlepsze, co jadłem.", "à-ràwi thîi sùt thîi khoei kin khráp", "อร่อยที่สุดที่เคยกินครับ",
 "Cechy i opinie", "Opinie", "phrase", 3, "i",
 "„khoei” = kiedykolwiek, mieć za sobą doświadczenie.", "thîi sùt = naj-",
 ("Aż tak dobre?", "à-ràwi khà-nàat nán loei rǔe khráp", "อร่อยขนาดนั้นเลยหรือครับ")),
("Nie polecam.", "mâi náe-nam khráp", "ไม่แนะนำครับ",
 "Cechy i opinie", "Opinie", "phrase", 3, "n", "", "",
 ("Dobrze wiedzieć.", "dii thîi bàwk khráp", "ดีที่บอกครับ")),
("Warto spróbować.", "nâa lawng khráp", "น่าลองครับ",
 "Cechy i opinie", "Opinie", "phrase", 4, "n",
 "Przedrostek „nâa” tworzy „warto/godne”: nâa kin = apetyczne.", "nâa = warto, godne",
 ("To spróbuję.", "ngán lawng duu khráp", "งั้นลองดูครับ")),
("Wygląda apetycznie.", "nâa kin mâak khráp", "น่ากินมากครับ",
 "Cechy i opinie", "Opinie", "phrase", 4, "i", "", "",
 ("Zamów śmiało.", "sàng loei khráp", "สั่งเลยครับ")),
("Wygląda ciekawie.", "nâa sǒn jai khráp", "น่าสนใจครับ",
 "Cechy i opinie", "Opinie", "phrase", 4, "n", "", "sǒn jai = interesować się",
 ("Zobaczmy z bliska.", "pai duu klâi klâi khráp", "ไปดูใกล้ๆ ครับ")),
("Szkoda.", "nâa sǐa daai khráp", "น่าเสียดายครับ",
 "Cechy i opinie", "Reakcje", "phrase", 4, "n", "", "",
 ("Następnym razem.", "khráng nâa ná khráp", "ครั้งหน้านะครับ")),
("To ma sens.", "kâw mii hèet-phǒn khráp", "ก็มีเหตุผลครับ",
 "Cechy i opinie", "Opinie", "phrase", 3, "n", "„hèet-phǒn” = powód, racja.", "",
 ("Dokładnie.", "chân nán khráp", "ชั้นนั้นครับ")),
("Nie rozumiem tego.", "phǒm mâi khâo-jai rûeang níi khráp", "ผมไม่เข้าใจเรื่องนี้ครับ",
 "Cechy i opinie", "Opinie", "phrase", 4, "n", "„rûeang” = sprawa, temat.", "",
 ("Wytłumaczę.", "dǐao à-thí-baai hâi khráp", "เดี๋ยวอธิบายให้ครับ")),
("Zależy mi na tym.", "phǒm hùang rûeang níi khráp", "ผมห่วงเรื่องนี้ครับ",
 "Cechy i opinie", "Opinie", "phrase", 2, "n", "„hùang” = martwić się o kogoś, zależeć na kimś.", "",
 ("Rozumiem.", "khâo-jai khráp", "เข้าใจครับ")),
("To dla mnie ważne.", "sǎm-khan sǎm-ràp phǒm khráp", "สำคัญสำหรับผมครับ",
 "Cechy i opinie", "Opinie", "phrase", 3, "n", "", "",
 ("Zapamiętam.", "jà jam wái khráp", "จะจำไว้ครับ")),
("Nie ma to znaczenia.", "mâi sǎm-khan khráp", "ไม่สำคัญครับ",
 "Cechy i opinie", "Opinie", "phrase", 3, "n", "", "",
 ("Na pewno?", "nâe jai ná khráp", "แน่ใจนะครับ")),

# ------------------------------------------------- slownictwo opinii
("pomysł", "khwaam khít", "ความคิด", "Cechy i opinie", "Opinie", "word", 4, "n", "", "",
 ("Mam pomysł.", "phǒm mii khwaam khít khráp", "ผมมีความคิดครับ")),
("powód", "hèet-phǒn", "เหตุผล", "Cechy i opinie", "Opinie", "word", 3, "n", "", "",
 ("Jaki jest powód?", "hèet-phǒn khue à-rai khráp", "เหตุผลคืออะไรครับ")),
("wybór", "thaang lûeak", "ทางเลือก", "Cechy i opinie", "Opinie", "word", 3, "n", "", "dosłownie: droga wyboru",
 ("Nie mam wyboru.", "phǒm mâi mii thaang lûeak khráp", "ผมไม่มีทางเลือกครับ")),
("różnica", "khwaam tàek tàang", "ความแตกต่าง", "Cechy i opinie", "Porównania", "word", 3, "f", "", "",
 ("Jaka jest różnica?", "tàek tàang kan yang-ngai khráp", "แตกต่างกันยังไงครับ")),
("podobny", "khláai kan", "คล้ายกัน", "Cechy i opinie", "Porównania", "word", 4, "n", "", "",
 ("To jest podobne.", "THIS")),
("taki sam", "mǔean kan", "เหมือนกัน", "Cechy i opinie", "Porównania", "word", 5, "n",
 "„mǔean kan” działa też jako „ja też”.", "",
 ("To jest takie samo.", "THIS")),
("inny", "tàang kan", "ต่างกัน", "Cechy i opinie", "Porównania", "word", 4, "n", "", "",
 ("To jest zupełnie inne.", "tàang kan loei khráp", "ต่างกันเลยครับ")),
("lepszy", "dii kwàa", "ดีกว่า", "Cechy i opinie", "Porównania", "word", 5, "n",
 "„kwàa” po przymiotniku tworzy stopień wyższy.", "kwàa = bardziej",
 ("Ten jest lepszy.", "an níi dii kwàa khráp", "อันนี้ดีกว่าครับ")),
("gorszy", "yâe kwàa", "แย่กว่า", "Cechy i opinie", "Porównania", "word", 3, "n", "", "",
 ("To jest gorsze.", "THIS")),
("najlepszy", "dii thîi sùt", "ดีที่สุด", "Cechy i opinie", "Porównania", "word", 5, "n",
 "„thîi sùt” tworzy stopień najwyższy.", "thîi sùt = naj-",
 ("To jest najlepsze.", "THIS")),
("najgorszy", "yâe thîi sùt", "แย่ที่สุด", "Cechy i opinie", "Porównania", "word", 3, "n", "", "",
 ("To było najgorsze.", "an nán yâe thîi sùt khráp", "อันนั้นแย่ที่สุดครับ")),
("wystarczająco", "phaw", "พอ", "Cechy i opinie", "Określenia", "word", 5, "n", "", "",
 ("To wystarczy.", "phaw láew khráp", "พอแล้วครับ")),
("za mało", "nói koen pai", "น้อยเกินไป", "Cechy i opinie", "Określenia", "word", 4, "n", "", "",
 ("Tego jest za mało.", "an níi nói koen pai khráp", "อันนี้น้อยเกินไปครับ")),
("prawie", "kùeap", "เกือบ", "Cechy i opinie", "Określenia", "word", 4, "n", "", "",
 ("Prawie gotowe.", "kùeap sèt láew khráp", "เกือบเสร็จแล้วครับ")),
("dokładnie", "phaw dii", "พอดี", "Cechy i opinie", "Określenia", "word", 4, "n",
 "„phaw dii” = w sam raz, akurat.", "",
 ("W sam raz.", "phaw dii khráp", "พอดีครับ")),
("mniej więcej", "prà-maan", "ประมาณ", "Cechy i opinie", "Określenia", "word", 5, "n", "", "",
 ("Mniej więcej dziesięć minut.", "prà-maan sìp naa-thii khráp", "ประมาณสิบนาทีครับ")),
]
