# -*- coding: utf-8 -*-
"""Sesja F — CZASOWNIKI, czesc II: mowienie, umysl, emocje, kontakty z ludzmi,
praca i pieniadze, zmiana stanu.
"""

CV = "Czasowniki"
CW = "Praca i nauka"
CS = "Zakupy i pieniądze"
CO = "Cechy i opinie"
CH = "Podstawy i grzeczność"

VERBS_B = [

# ================================================================ MOWIENIE
("A2", "opowiadać", "lâo", "เล่า", CV, "Mówienie", 4, "n",
 "O historii, wydarzeniu. Nie mylić z „phûut” (mówić) ani „bàwk” (powiedzieć komuś).",
 "",
 [("Opowiedz mi o tym.", "lâo hâi fang nòi khráp", "เล่าให้ฟังหน่อยครับ"),
  ("Opowiadał o podróży.", "kháo lâo rûeang thîao khráp", "เขาเล่าเรื่องเที่ยวครับ")],
 ["mówić", "słuchać"], []),

("A2", "powiedzieć komuś", "bàwk", "บอก", CV, "Mówienie", 5, "n",
 "Zawsze z odbiorcą: „bàwk phǒm” — powiedz mi. Samo „phûut” to mówić w ogóle.",
 "",
 [("Powiedz mi, proszę.", "bàwk phǒm nòi khráp", "บอกผมหน่อยครับ"),
  ("Nikomu nie mów.", "yàa bàwk khrai ná khráp", "อย่าบอกใครนะครับ")],
 ["mówić", "opowiadać", "pytać"], []),

("A2", "tłumaczyć (na język)", "plae", "แปล", CV, "Mówienie", 4, "n",
 "„plae wâa à-rai” to „co to znaczy?” — jedno z najużyteczniejszych pytań dla uczącego się.",
 "",
 [("Co to znaczy?", "plae wâa à-rai khráp", "แปลว่าอะไรครับ"),
  ("Możesz to przetłumaczyć?", "chûai plae hâi nòi dâai mǎi khráp", "ช่วยแปลให้หน่อยได้ไหมครับ")],
 ["rozumieć", "mówić"], []),

("A2", "powtórzyć", "phûut ìik thii", "พูดอีกที", CV, "Mówienie", 5, "n",
 "Zdanie ratunkowe każdego początkującego. „ìik thii” znaczy „jeszcze raz” i dokleja się do dowolnego czasownika.",
 "mówić jeszcze raz",
 [("Proszę powtórzyć.", "chûai phûut ìik thii khráp", "ช่วยพูดอีกทีครับ"),
  ("Proszę powtórzyć wolniej.", "chûai phûut ìik thii cháa cháa khráp", "ช่วยพูดอีกทีช้าๆครับ")],
 ["mówić", "rozumieć", "wolno"], []),

("A2", "krzyczeć", "tà-kohn", "ตะโกน", CV, "Mówienie", 2, "n",
 "O podniesionym głosie. Uwaga kulturowa: podnoszenie głosu w Tajlandii kompromituje mówiącego, nie odbiorcę.",
 "",
 [("Nie krzycz, proszę.", "yàa tà-kohn khráp", "อย่าตะโกนครับ"),
  ("Ktoś krzyczał na zewnątrz.", "mii khon tà-kohn khâang nâwk khráp", "มีคนตะโกนข้างนอกครับ")],
 ["milczeć", "głośny"], []),

("A2", "milczeć", "ngîap", "เงียบ", CV, "Mówienie", 4, "n",
 "To samo słowo znaczy „cichy” o miejscu. „ngîap ngîap” to prośba o ciszę.",
 "",
 [("Proszę o ciszę.", "ngîap ngîap nòi khráp", "เงียบๆหน่อยครับ"),
  ("Tu jest cicho.", "thîi nîi ngîap dii khráp", "ที่นี่เงียบดีครับ")],
 ["krzyczeć", "noc"], ["cicho"]),

("A2", "obiecać", "sǎn-yaa", "สัญญา", CV, "Mówienie", 3, "n",
 "To samo słowo oznacza umowę jako dokument. Kontekst rozstrzyga.",
 "",
 [("Obiecuję.", "phǒm sǎn-yaa khráp", "ผมสัญญาครับ"),
  ("Obiecał, że przyjdzie.", "kháo sǎn-yaa wâa jà maa khráp", "เขาสัญญาว่าจะมาครับ")],
 ["umowa", "zgodzić się"], []),

("A2", "zgodzić się", "tòk long", "ตกลง", CV, "Mówienie", 5, "n",
 "Dosłownie „spaść w dół”. Znaczy zarówno „zgadzam się”, jak i „umówione”. Jedno z najczęstszych słów przy dobijaniu targu.",
 "spaść w dół",
 [("Zgoda.", "tòk long khráp", "ตกลงครับ"),
  ("Zgodziliśmy się na tę cenę.", "rao tòk long raa-khaa níi khráp", "เราตกลงราคานี้ครับ")],
 ["odmówić", "obiecać", "targować się"], ["umówione"]),

("A2", "odmówić", "pà-tì-sèet", "ปฏิเสธ", CV, "Mówienie", 3, "f",
 "Słowo formalne. W rozmowie codziennej Tajowie odmawiają pośrednio — wprost brzmi ostro.",
 "",
 [("Odmówił.", "kháo pà-tì-sèet khráp", "เขาปฏิเสธครับ"),
  ("Muszę odmówić.", "phǒm tâwng pà-tì-sèet khráp", "ผมต้องปฏิเสธครับ")],
 ["zgodzić się", "nie"], []),

("A2", "polecać", "náe-nam", "แนะนำ", CV, "Mówienie", 5, "n",
 "To samo słowo znaczy „przedstawiać kogoś”. W restauracji: „náe-nam à-rai dii khráp” — co pan poleca?",
 "",
 [("Co pan poleca?", "náe-nam à-rai dii khráp", "แนะนำอะไรดีครับ"),
  ("Polecam to danie.", "phǒm náe-nam jaan níi khráp", "ผมแนะนำจานนี้ครับ")],
 ["radzić", "menu"], ["przedstawiać"]),

("A2", "ostrzegać", "tuean", "เตือน", CV, "Mówienie", 3, "n",
 "To samo słowo znaczy „przypominać”. „tuean phǒm dûai” — przypomnij mi.",
 "",
 [("Ostrzegałem cię.", "phǒm tuean láew khráp", "ผมเตือนแล้วครับ"),
  ("Przypomnij mi, proszę.", "chûai tuean phǒm dûai khráp", "ช่วยเตือนผมด้วยครับ")],
 ["uważać", "pamiętać"], ["przypominać"]),

("A2", "narzekać", "bòn", "บ่น", CV, "Mówienie", 3, "i",
 "Ton niski. Nieco potoczne — o narzekaniu jako nawyku, nie o formalnej reklamacji.",
 "",
 [("Ciągle narzeka.", "kháo bòn tà-làwt wee-laa khráp", "เขาบ่นตลอดเวลาครับ"),
  ("Nie narzekaj.", "yàa bòn khráp", "อย่าบ่นครับ")],
 ["kłócić się", "problem"], []),

("A2", "kłócić się", "thá-ló", "ทะเลาะ", CV, "Mówienie", 3, "n",
 "O sprzeczce między ludźmi. „thá-ló kan” — pokłócić się ze sobą.",
 "",
 [("Pokłócili się.", "kháo thá-ló kan khráp", "เขาทะเลาะกันครับ"),
  ("Nie chcę się kłócić.", "phǒm mâi yàak thá-ló khráp", "ผมไม่อยากทะเลาะครับ")],
 ["godzić się", "narzekać"], []),

("A2", "godzić się (po kłótni)", "khuen dii", "คืนดี", CV, "Mówienie", 2, "n",
 "Dosłownie „wrócić do dobrego”. O odnowieniu relacji.",
 "wrócić dobry",
 [("Pogodzili się.", "kháo khuen dii kan láew khráp", "เขาคืนดีกันแล้วครับ"),
  ("Chcę się pogodzić.", "phǒm yàak khuen dii khráp", "ผมอยากคืนดีครับ")],
 ["kłócić się", "przyjaciel"], []),

("A2", "żartować", "phûut lên", "พูดเล่น", CV, "Mówienie", 4, "i",
 "Dosłownie „mówić na niby”. „lên” dokleja się do czasowników w znaczeniu „dla zabawy”.",
 "mówić bawić się",
 [("Żartuję.", "phûut lên khráp", "พูดเล่นครับ"),
  ("On tylko żartował.", "kháo phûut lên thâo nán khráp", "เขาพูดเล่นเท่านั้นครับ")],
 ["śmiać się", "poważny"], []),

# =============================================================== UMYSL
("A2", "wierzyć", "chûea", "เชื่อ", CV, "Myślenie", 4, "n",
 "Znaczy zarówno wierzyć w coś, jak i wierzyć komuś. Ufać komuś to „wái jai”.",
 "",
 [("Nie wierzę.", "phǒm mâi chûea khráp", "ผมไม่เชื่อครับ"),
  ("Wierzę ci.", "phǒm chûea khun khráp", "ผมเชื่อคุณครับ")],
 ["ufać", "myśleć"], []),

("A2", "ufać", "wái jai", "ไว้ใจ", CV, "Myślenie", 3, "n",
 "Dosłownie „złożyć serce”. Jedno z wielu wyrażeń z „jai”, które w tajskim tworzą całą rodzinę uczuć.",
 "złożyć serce",
 [("Ufam mu.", "phǒm wái jai kháo khráp", "ผมไว้ใจเขาครับ"),
  ("Nie ufam temu sklepowi.", "phǒm mâi wái jai ráan níi khráp", "ผมไม่ไว้ใจร้านนี้ครับ")],
 ["wierzyć", "serce"], []),

("A2", "decydować", "tàt sǐn jai", "ตัดสินใจ", CV, "Myślenie", 4, "n",
 "Dosłownie „przeciąć osąd serca”. Kolejne wyrażenie z „jai”.",
 "przeciąć osąd serce",
 [("Jeszcze nie zdecydowałem.", "phǒm yang mâi tàt sǐn jai khráp", "ผมยังไม่ตัดสินใจครับ"),
  ("Zdecyduj sam.", "tàt sǐn jai eeng khráp", "ตัดสินใจเองครับ")],
 ["myśleć", "wybierać", "serce"], []),

("A2", "planować", "waang phǎen", "วางแผน", CV, "Myślenie", 3, "n",
 "Dosłownie „położyć plan”. Ten sam czasownik „waang” co przy kładzeniu przedmiotu.",
 "położyć plan",
 [("Planuję wyjazd.", "phǒm waang phǎen pai thîao khráp", "ผมวางแผนไปเที่ยวครับ"),
  ("Musimy to zaplanować.", "rao tâwng waang phǎen khráp", "เราต้องวางแผนครับ")],
 ["kłaść", "decydować"], []),

("A2", "próbować (usiłować)", "lawng", "ลอง", CV, "Myślenie", 5, "n",
 "Odróżnij od „chim” (próbować smak). „lawng duu” to „spróbuj, zobacz”.",
 "",
 [("Spróbuję.", "phǒm jà lawng duu khráp", "ผมจะลองดูครับ"),
  ("Spróbuj jeszcze raz.", "lawng ìik thii khráp", "ลองอีกทีครับ")],
 ["próbować (smakować)", "przymierzyć"], []),

("A2", "udać się (powieść)", "sǎm-rèt", "สำเร็จ", CV, "Myślenie", 3, "f",
 "Bardziej formalne. W mowie codziennej częściej „tham dâai” — dało się zrobić.",
 "",
 [("Udało się.", "sǎm-rèt láew khráp", "สำเร็จแล้วครับ"),
  ("Nie udało się.", "mâi sǎm-rèt khráp", "ไม่สำเร็จครับ")],
 ["próbować (usiłować)", "problem"], []),

("A2", "zależeć od", "khûen yùu kàp", "ขึ้นอยู่กับ", CV, "Myślenie", 4, "n",
 "Bardzo częsta odpowiedź wymijająca. Dosłownie „wznosić się przy”.",
 "wznosić się przy",
 [("To zależy.", "láew tàe khráp", "แล้วแต่ครับ"),
  ("Zależy od pogody.", "khûen yùu kàp aa-kàat khráp", "ขึ้นอยู่กับอากาศครับ")],
 ["decydować", "pogoda"], []),

("A2", "czuć", "rúu-sùek", "รู้สึก", CV, "Myślenie", 5, "n",
 "O odczuciu fizycznym i emocji. „rúu-sùek mâi sà-baai” — źle się czuję.",
 "wiedzieć odczuwać",
 [("Źle się czuję.", "phǒm rúu-sùek mâi sà-baai khráp", "ผมรู้สึกไม่สบายครับ"),
  ("Czuję się lepiej.", "phǒm rúu-sùek dii khûen khráp", "ผมรู้สึกดีขึ้นครับ")],
 ["chory", "cieszyć się"], []),

("A2", "wyglądać (na)", "duu", "ดู", CO, "Ocena", 5, "n",
 "To samo słowo znaczy „oglądać”. „duu dii” — wygląda dobrze, „duu nǔeai” — wyglądasz na zmęczonego.",
 "",
 [("Wyglądasz na zmęczonego.", "khun duu nùeai khráp", "คุณดูเหนื่อยครับ"),
  ("To wygląda dobrze.", "duu dii khráp", "ดูดีครับ")],
 ["oglądać", "podobny"], []),

("A2", "być podobnym", "mǔean", "เหมือน", CO, "Ocena", 5, "n",
 "Podstawowe słowo porównania: „mǔean kan” — tak samo, „mǔean kàp” — podobnie jak.",
 "",
 [("To jest podobne.", "mǔean kan khráp", "เหมือนกันครับ"),
  ("Smakuje jak kurczak.", "rót mǔean kài khráp", "รสเหมือนไก่ครับ")],
 ["wyglądać (na)", "różnica", "inny"], []),

# =============================================================== EMOCJE
("A1", "bać się", "klua", "กลัว", CO, "Emocje", 4, "n",
 "Ton średni. „klua wâa …” znaczy „obawiam się, że…” i łagodzi złą wiadomość.",
 "",
 [("Boję się psów.", "phǒm klua mǎa khráp", "ผมกลัวหมาครับ"),
  ("Nie bój się.", "mâi tâwng klua khráp", "ไม่ต้องกลัวครับ")],
 ["martwić się", "wąż", "pies"], []),

("A2", "martwić się", "pen hùang", "เป็นห่วง", CO, "Emocje", 4, "n",
 "O troskę o kogoś. Zmartwienie o sprawę to raczej „kang-won”.",
 "",
 [("Martwię się o ciebie.", "phǒm pen hùang khun khráp", "ผมเป็นห่วงคุณครับ"),
  ("Nie martw się.", "mâi tâwng pen hùang khráp", "ไม่ต้องเป็นห่วงครับ")],
 ["bać się", "rodzina"], []),

("A2", "cieszyć się", "dii jai", "ดีใจ", CO, "Emocje", 5, "n",
 "Dosłownie „dobre serce”. Kolejne wyrażenie rodziny „jai”. Para do „sǐa jai” (być smutnym).",
 "dobre serce",
 [("Cieszę się.", "phǒm dii jai khráp", "ผมดีใจครับ"),
  ("Cieszę się, że cię widzę.", "dii jai thîi dâai jòoe khun khráp", "ดีใจที่ได้เจอคุณครับ")],
 ["smutny", "szczęśliwy", "serce"], []),

("A2", "złościć się", "kròot", "โกรธ", CO, "Emocje", 3, "n",
 "Uwaga kulturowa: okazywanie złości publicznie jest w Tajlandii poważnym nietaktem. Częściej usłyszysz „mâi phaw jai” — niezadowolony.",
 "",
 [("Nie złość się.", "yàa kròot khráp", "อย่าโกรธครับ"),
  ("Chyba się zdenerwował.", "kháo khong kròot khráp", "เขาคงโกรธครับ")],
 ["kłócić się", "spokojny"], []),

("A2", "nudzić się", "bùea", "เบื่อ", CO, "Emocje", 4, "i",
 "Znaczy też „mieć czegoś dość”: „bùea aa-hǎan níi” — znudziło mi się to jedzenie.",
 "",
 [("Nudzę się.", "phǒm bùea khráp", "ผมเบื่อครับ"),
  ("Mam dość tej pracy.", "phǒm bùea ngaan níi khráp", "ผมเบื่องานนี้ครับ")],
 ["nudny", "zmęczony"], []),

("A2", "śmiać się", "hǔa-ráw", "หัวเราะ", CO, "Emocje", 3, "n",
 "Ton rosnący na pierwszej sylabie. Dosłownie zawiera „hǔa” — głowę.",
 "",
 [("Wszyscy się śmiali.", "thúk khon hǔa-ráw khráp", "ทุกคนหัวเราะครับ"),
  ("Dlaczego się śmiejesz?", "khun hǔa-ráw tham-mai khráp", "คุณหัวเราะทำไมครับ")],
 ["żartować", "uśmiechać się"], []),

("A2", "uśmiechać się", "yím", "ยิ้ม", CO, "Emocje", 4, "n",
 "Tajlandia nazywa siebie krajem uśmiechu — uśmiech bywa tu też sposobem na wyjście z niezręcznej sytuacji, nie tylko oznaką radości.",
 "",
 [("Uśmiechnij się.", "yím nòi sí khráp", "ยิ้มหน่อยสิครับ"),
  ("Ona zawsze się uśmiecha.", "kháo yím sà-mǒoe khâ", "เขายิ้มเสมอค่ะ")],
 ["śmiać się", "cieszyć się"], []),

("A2", "płakać", "ráwng hâi", "ร้องไห้", CO, "Emocje", 3, "n",
 "Dosłownie „krzyczeć płacząc”. Samo „ráwng” znaczy też „śpiewać”.",
 "",
 [("Dziecko płacze.", "dèk ráwng hâi khráp", "เด็กร้องไห้ครับ"),
  ("Nie płacz.", "yàa ráwng hâi khráp", "อย่าร้องไห้ครับ")],
 ["smutny", "dziecko", "śpiewać"], []),

# ============================================================= LUDZIE
("A2", "opiekować się", "duu lae", "ดูแล", CV, "Ludzie", 4, "n",
 "O człowieku, zwierzęciu i sprawie. „duu lae tua eeng” — dbaj o siebie, częste pożegnanie.",
 "",
 [("Opiekuję się mamą.", "phǒm duu lae mâe khráp", "ผมดูแลแม่ครับ"),
  ("Dbaj o siebie.", "duu lae tua eeng ná khráp", "ดูแลตัวเองนะครับ")],
 ["pomagać", "rodzina"], []),

("A2", "pozwolić", "à-nú-yâat", "อนุญาต", CV, "Ludzie", 3, "f",
 "Formalne. W rozmowie codziennej raczej „dâai mǎi” — można?",
 "",
 [("Czy wolno tu palić?", "sùup bù-rìi thîi nîi dâai mǎi khráp", "สูบบุหรี่ที่นี่ได้ไหมครับ"),
  ("Nie wolno tu wchodzić.", "mâi à-nú-yâat hâi khâo khráp", "ไม่อนุญาตให้เข้าครับ")],
 ["zabronić", "można"], []),

("A2", "zabronić", "hâam", "ห้าม", CV, "Ludzie", 4, "n",
 "Słowo z tabliczek zakazu. Zobaczysz je wszędzie: „hâam jàwt” (zakaz parkowania), „hâam sùup bù-rìi”.",
 "",
 [("Zakaz parkowania.", "hâam jàwt khráp", "ห้ามจอดครับ"),
  ("Nie wolno tego robić.", "hâam tham yàang níi khráp", "ห้ามทำอย่างนี้ครับ")],
 ["pozwolić", "uważać"], []),

("A2", "prosić o", "khǎw", "ขอ", CH, "Prośby", 5, "n",
 "Najważniejszy czasownik dla obcokrajowca. „khǎw” plus rzeczownik załatwia większość sytuacji w sklepie i restauracji.",
 "",
 [("Poproszę wodę.", "khǎw nám khráp", "ขอน้ำครับ"),
  ("Poproszę rachunek.", "khǎw chék bin khráp", "ขอเช็คบิลครับ"),
  ("Czy mogę prosić o pomoc?", "khǎw khwaam chûai lǔea nòi khráp", "ขอความช่วยเหลือหน่อยครับ")],
 ["pomagać", "dawać", "rachunek"], []),

("A2", "kazać (zlecić)", "sàng", "สั่ง", CV, "Ludzie", 4, "n",
 "To samo słowo znaczy „zamówić” w restauracji i sklepie internetowym.",
 "",
 [("Zamówiłem już.", "phǒm sàng láew khráp", "ผมสั่งแล้วครับ"),
  ("Zamówię online.", "phǒm jà sàng awn-lai khráp", "ผมจะสั่งออนไลน์ครับ")],
 ["zamawiać", "menu"], ["zamówić"]),

("A2", "ukraść", "khà-mooi", "ขโมย", "Awarie i pomoc", "Kradzież", 3, "n",
 "To samo słowo oznacza złodzieja. Potrzebne przy zgłoszeniu na policji.",
 "",
 [("Ukradli mi portfel.", "krà-pǎo taang phǒm thùuk khà-mooi khráp", "กระเป๋าตังผมถูกขโมยครับ"),
  ("Chcę zgłosić kradzież.", "phǒm yàak jâeng khwaam khráp", "ผมอยากแจ้งความครับ")],
 ["policjant", "portfel", "zgubić"], ["złodziej"]),

("A2", "oszukać", "kohng", "โกง", "Awarie i pomoc", "Oszustwo", 3, "n",
 "Mocne słowo — użyte wprost wobec sprzedawcy jest oskarżeniem. Bezpieczniej powiedzieć „raa-khaa mâi thùuk” (cena się nie zgadza).",
 "",
 [("Chyba mnie oszukali.", "phǒm khít wâa thùuk kohng khráp", "ผมคิดว่าถูกโกงครับ"),
  ("Nie oszukuj.", "yàa kohng khráp", "อย่าโกงครับ")],
 ["ukraść", "cena", "targować się"], []),

("A2", "spieszyć się", "rîip", "รีบ", CV, "Czynności", 4, "n",
 "„rîip rîip” to prośba o pośpiech. Ton opadający, samogłoska długa.",
 "",
 [("Spieszę się.", "phǒm rîip khráp", "ผมรีบครับ"),
  ("Proszę się pospieszyć.", "chûai rîip nòi khráp", "ช่วยรีบหน่อยครับ")],
 ["czekać", "szybki"], []),

# ==================================================== PRACA, NAUKA, PIENIADZE
("A1", "uczyć się", "rian", "เรียน", CW, "Nauka", 5, "n",
 "„rian phaa-sǎa thai” — uczyć się tajskiego. To samo słowo w formie grzecznościowej znaczy „zwracać się do kogoś wyżej postawionego”.",
 "",
 [("Uczę się tajskiego.", "phǒm rian phaa-sǎa thai khráp", "ผมเรียนภาษาไทยครับ"),
  ("Gdzie się uczysz?", "khun rian thîi nǎi khráp", "คุณเรียนที่ไหนครับ")],
 ["uczyć kogoś", "szkoła", "ćwiczyć (umiejętność)"], []),

("A2", "uczyć kogoś", "sǎwn", "สอน", CW, "Nauka", 4, "n",
 "Para do „rian”. „khruu sǎwn” — nauczyciel uczy.",
 "",
 [("Uczę angielskiego.", "phǒm sǎwn phaa-sǎa ang-krìt khráp", "ผมสอนภาษาอังกฤษครับ"),
  ("Nauczysz mnie?", "sǎwn phǒm nòi dâai mǎi khráp", "สอนผมหน่อยได้ไหมครับ")],
 ["uczyć się", "nauczyciel"], []),

("A2", "ćwiczyć (umiejętność)", "fùek", "ฝึก", CW, "Nauka", 4, "n",
 "O wprawianiu się. Odróżnij od „àwk kam-lang kaai”, które dotyczy tylko sportu.",
 "",
 [("Ćwiczę mówienie po tajsku.", "phǒm fùek phûut phaa-sǎa thai khráp", "ผมฝึกพูดภาษาไทยครับ"),
  ("Trzeba dużo ćwiczyć.", "tâwng fùek yóe yóe khráp", "ต้องฝึกเยอะๆครับ")],
 ["uczyć się", "powtórzyć"], []),

("A2", "zdać egzamin", "sàwp phàan", "สอบผ่าน", CW, "Nauka", 3, "n",
 "„sàwp” to egzamin, „phàan” — przejść. Para: „sàwp tòk” to oblać.",
 "egzamin przejść",
 [("Zdałem egzamin.", "phǒm sàwp phàan láew khráp", "ผมสอบผ่านแล้วครับ"),
  ("Kiedy masz egzamin?", "khun sàwp mûea-rài khráp", "คุณสอบเมื่อไหร่ครับ")],
 ["uczyć się", "uniwersytet"], []),

("A2", "składać podanie", "sà-màk", "สมัคร", CW, "Praca", 3, "n",
 "O pracy, kursie, karcie SIM. „sà-màk ngaan” — ubiegać się o pracę.",
 "",
 [("Składam podanie o pracę.", "phǒm sà-màk ngaan khráp", "ผมสมัครงานครับ"),
  ("Chcę się zapisać na kurs.", "phǒm yàak sà-màk khàwt khráp", "ผมอยากสมัครคอร์สครับ")],
 ["praca", "dokument"], ["zapisać się"]),

("A2", "zatrudniać", "jâang", "จ้าง", CW, "Praca", 3, "n",
 "Znaczy też „wynająć kogoś do usługi” — na przykład kierowcę na dzień.",
 "",
 [("Zatrudnili nowego pracownika.", "kháo jâang phá-nák-ngaan mài khráp", "เขาจ้างพนักงานใหม่ครับ"),
  ("Wynająłem kierowcę.", "phǒm jâang khon khàp rót khráp", "ผมจ้างคนขับรถครับ")],
 ["praca", "kierowca", "pensja"], []),

("A2", "odejść z pracy", "laa àwk", "ลาออก", CW, "Praca", 3, "n",
 "Z własnej woli. Zwolnienie przez pracodawcę to „thùuk lâi àwk”.",
 "prosić o urlop wyjść",
 [("Odchodzę z pracy.", "phǒm jà laa àwk khráp", "ผมจะลาออกครับ"),
  ("Odszedł w zeszłym miesiącu.", "kháo laa àwk duean thîi láew khráp", "เขาลาออกเดือนที่แล้วครับ")],
 ["praca", "zatrudniać"], []),

("A2", "zarabiać", "hǎa ngoen", "หาเงิน", CS, "Pieniądze", 4, "n",
 "Dosłownie „szukać pieniędzy”. Ten sam czasownik „hǎa” co przy szukaniu rzeczy.",
 "szukać pieniądze",
 [("Pracuję, żeby zarobić.", "phǒm tham ngaan hǎa ngoen khráp", "ผมทำงานหาเงินครับ"),
  ("Ile zarabiasz?", "khun dâai ngoen thâo-rài khráp", "คุณได้เงินเท่าไหร่ครับ")],
 ["pensja", "szukać", "oszczędzać"], []),

("A2", "oszczędzać", "kèp ngoen", "เก็บเงิน", CS, "Pieniądze", 4, "n",
 "Dosłownie „zbierać pieniądze”. Samo „kèp” znaczy schować, odłożyć.",
 "zbierać pieniądze",
 [("Oszczędzam na podróż.", "phǒm kèp ngoen pai thîao khráp", "ผมเก็บเงินไปเที่ยวครับ"),
  ("Trzeba oszczędzać.", "tâwng kèp ngoen khráp", "ต้องเก็บเงินครับ")],
 ["zarabiać", "wydawać (pieniądze)", "bank"], []),

("A2", "wydawać (pieniądze)", "chái ngoen", "ใช้เงิน", CS, "Pieniądze", 4, "n",
 "„chái” to używać. Dosłownie „używać pieniędzy”.",
 "używać pieniądze",
 [("Wydałem dużo.", "phǒm chái ngoen yóe khráp", "ผมใช้เงินเยอะครับ"),
  ("Nie wydawaj za dużo.", "yàa chái ngoen yóe koen pai khráp", "อย่าใช้เงินเยอะเกินไปครับ")],
 ["oszczędzać", "używać", "drogi"], []),

("A2", "targować się", "tàw raa-khaa", "ต่อราคา", CS, "Zakupy", 4, "n",
 "Na targu jak najbardziej; w sklepie z ceną na metce nie. Samo „tàw” znaczy „przedłużać, kontynuować”.",
 "przedłużać cena",
 [("Można się potargować?", "tàw raa-khaa dâai mǎi khráp", "ต่อราคาได้ไหมครับ"),
  ("Potargowałem się.", "phǒm tàw raa-khaa láew khráp", "ผมต่อราคาแล้วครับ")],
 ["cena", "zniżka", "targ"], []),

("A2", "wymieniać", "lâek", "แลก", CS, "Pieniądze", 4, "n",
 "O pieniądzach i o zamianie rzeczy. „lâek ngoen” — wymienić walutę.",
 "",
 [("Chcę wymienić pieniądze.", "phǒm yàak lâek ngoen khráp", "ผมอยากแลกเงินครับ"),
  ("Czy mogę to wymienić?", "lâek an níi dâai mǎi khráp", "แลกอันนี้ได้ไหมครับ")],
 ["kantor", "zwracać"], []),

("A2", "zwracać (oddać)", "khuen", "คืน", CS, "Zakupy", 4, "n",
 "O towarze i o pożyczonej rzeczy. „khuen ngoen” — zwrot pieniędzy.",
 "",
 [("Chcę to zwrócić.", "phǒm yàak khuen khǎwng khráp", "ผมอยากคืนของครับ"),
  ("Zwrócę ci jutro.", "phǒm jà khuen hâi phrûng-níi khráp", "ผมจะคืนให้พรุ่งนี้ครับ")],
 ["wymieniać", "pożyczyć", "paragon"], []),

("A2", "dostarczać", "sòng", "ส่ง", CV, "Czynności", 5, "n",
 "Bardzo szeroko: wysłać paczkę, odwieźć kogoś, dostarczyć jedzenie. „sòng aa-hǎan” to dowóz.",
 "",
 [("Czy dowozicie?", "mii sòng aa-hǎan mǎi khráp", "มีส่งอาหารไหมครับ"),
  ("Wyślę to jutro.", "phǒm jà sòng phrûng-níi khráp", "ผมจะส่งพรุ่งนี้ครับ")],
 ["wysyłać", "poczta"], []),

# ========================================================== ZMIANA STANU
("A2", "rosnąć", "tôo", "โต", CV, "Zmiana", 3, "n",
 "O dziecku, roślinie, firmie. Ton opadający.",
 "",
 [("Dzieci szybko rosną.", "dèk tôo reo khráp", "เด็กโตเร็วครับ"),
  ("Wyrosłem w Polsce.", "phǒm tôo thîi poh-laen khráp", "ผมโตที่โปแลนด์ครับ")],
 ["dziecko", "duży"], []),

("A2", "zwiększać", "phôoem", "เพิ่ม", CV, "Zmiana", 5, "n",
 "Najczęściej usłyszysz przy dokładce: „khǎw khâao phôoem” — poproszę więcej ryżu.",
 "",
 [("Poproszę dokładkę ryżu.", "khǎw khâao phôoem khráp", "ขอข้าวเพิ่มครับ"),
  ("Cena wzrosła.", "raa-khaa phôoem khûen khráp", "ราคาเพิ่มขึ้นครับ")],
 ["zmniejszać", "dokładka"], []),

("A2", "zmniejszać", "lót", "ลด", CV, "Zmiana", 5, "n",
 "Para do „phôoem”. „lót raa-khaa” to obniżka, stąd „lót ráa-khaa” na wywieszkach wyprzedażowych.",
 "",
 [("Może pan opuścić cenę?", "lót raa-khaa dâai mǎi khráp", "ลดราคาได้ไหมครับ"),
  ("Poproszę mniej cukru.", "lót nám-taan nòi khráp", "ลดน้ำตาลหน่อยครับ")],
 ["zwiększać", "zniżka", "cena"], []),

("A2", "kończyć się", "mòt", "หมด", CV, "Zmiana", 5, "n",
 "„mòt láew” to „już się skończyło” — usłyszysz to w każdej restauracji o wyczerpanym daniu.",
 "",
 [("Skończyło się.", "mòt láew khráp", "หมดแล้วครับ"),
  ("Bateria mi się skończyła.", "baet-toe-rîi mòt khráp", "แบตเตอรี่หมดครับ")],
 ["brakować", "zostawać"], []),

("A2", "zostawać (pozostać)", "lǔea", "เหลือ", CV, "Zmiana", 4, "n",
 "O reszcie, która została. „lǔea thâo-rài” — ile zostało?",
 "",
 [("Zostały dwa.", "lǔea sǎwng an khráp", "เหลือสองอันครับ"),
  ("Ile zostało czasu?", "lǔea wee-laa thâo-rài khráp", "เหลือเวลาเท่าไหร่ครับ")],
 ["kończyć się", "wystarczyć"], []),

("A2", "brakować", "khàat", "ขาด", CV, "Zmiana", 4, "n",
 "Znaczy też „przerwać się” o sznurku i „opuścić” o zajęciach.",
 "",
 [("Brakuje jednego.", "khàat pai nùeng an khráp", "ขาดไปหนึ่งอันครับ"),
  ("Brakuje mi pieniędzy.", "phǒm khàat ngoen khráp", "ผมขาดเงินครับ")],
 ["kończyć się", "wystarczyć"], []),

("A2", "wystarczyć", "phaw", "พอ", CV, "Zmiana", 5, "n",
 "Jedno z najużyteczniejszych słów przy stole i w sklepie. Samo „phaw láew” znaczy „już wystarczy”.",
 "",
 [("Wystarczy, dziękuję.", "phaw láew khráp khàwp khun", "พอแล้วครับขอบคุณ"),
  ("To nie wystarczy.", "mâi phaw khráp", "ไม่พอครับ")],
 ["brakować", "zostawać"], []),

("A2", "zdarzyć się", "kòoet khûen", "เกิดขึ้น", CV, "Zmiana", 4, "n",
 "„kòoet à-rai khûen” — co się stało? Pierwsze pytanie przy wypadku.",
 "rodzić się w górę",
 [("Co się stało?", "kòoet à-rai khûen khráp", "เกิดอะไรขึ้นครับ"),
  ("Zdarzył się wypadek.", "kòoet ù-bàt-tì-hèet khráp", "เกิดอุบัติเหตุครับ")],
 ["problem", "wypadek"], []),

("A2", "umieć", "pen", "เป็น", CV, "Możliwość", 5, "n",
 "Po czasowniku „pen” znaczy umiejętność nabytą: „phûut thai pen” — umiem mówić po tajsku. Odróżnij od „dâai”, które znaczy „móc, dać radę”.",
 "",
 [("Umiem mówić po tajsku.", "phǒm phûut thai pen khráp", "ผมพูดไทยเป็นครับ"),
  ("Nie umiem prowadzić.", "phǒm khàp rót mâi pen khráp", "ผมขับรถไม่เป็นครับ")],
 ["móc", "uczyć się"], []),

("A2", "móc", "dâai", "ได้", CV, "Możliwość", 5, "n",
 "Kluczowe słowo gramatyczne. Po czasowniku znaczy „dać radę, być w stanie”; „dâai mǎi” to pytanie „można?”.",
 "",
 [("Czy można?", "dâai mǎi khráp", "ได้ไหมครับ"),
  ("Nie mogę.", "mâi dâai khráp", "ไม่ได้ครับ"),
  ("Możesz mi pomóc?", "chûai phǒm nòi dâai mǎi khráp", "ช่วยผมหน่อยได้ไหมครับ")],
 ["umieć", "pozwolić"], []),
]
