# -*- coding: utf-8 -*-
"""Sesja F — RZECZY: ubrania, elektronika, dokumenty, materialy, narzedzia.

Uwaga systemowa: przy ubraniach czasownik zalezy od czesci ciala.
„sài” — wkladac (ogolnie), „sài” tez o butach i spodniach, „sài waen”
o pierscionku. Nie ma jednego uniwersalnego „ubierac” jak w polskim.
"""

ZP = "Zakupy i pieniądze"
CD = "Dom i codzienność"
PN = "Praca i nauka"

THINGS = [

# ============================================================ UBRANIA
("A1", "ubranie", "sûea phâa", "เสื้อผ้า", ZP, "Ubrania", 4, "n",
 "Złożenie „sûea” (góra) i „phâa” (tkanina) — ogólne słowo na odzież.",
 "koszula tkanina",
 [("Kupuję ubrania.", "phǒm súe sûea phâa khráp", "ผมซื้อเสื้อผ้าครับ"),
  ("Gdzie sprzedają ubrania?", "khǎai sûea phâa thîi nǎi khráp", "ขายเสื้อผ้าที่ไหนครับ")],
 ["koszula", "spodnie", "prać"], ["odzież"]),

("A1", "koszulka", "sûea yûet", "เสื้อยืด", ZP, "Ubrania", 4, "n",
 "„yûet” znaczy rozciągliwy — dosłownie „rozciągliwa góra”. Najczęstszy strój codzienny w Tajlandii.",
 "góra rozciągliwy",
 [("Poproszę czarną koszulkę.", "khǎw sûea yûet sǐi dam khráp", "ขอเสื้อยืดสีดำครับ"),
  ("Ta koszulka jest za mała.", "sûea yûet tua níi lék koen pai khráp", "เสื้อยืดตัวนี้เล็กเกินไปครับ")],
 ["koszula", "ubranie", "czarny"], ["t-shirt"]),

("A2", "koszula", "sûea chóoet", "เสื้อเชิ้ต", ZP, "Ubrania", 3, "n",
 "Zapożyczenie z angielskiego „shirt”. Strój biurowy — w piątki często koszula w kolorach.",
 "",
 [("Noszę koszulę do pracy.", "phǒm sài sûea chóoet pai tham ngaan khráp", "ผมใส่เสื้อเชิ้ตไปทำงานครับ"),
  ("Poproszę białą koszulę.", "khǎw sûea chóoet sǐi khǎao khráp", "ขอเสื้อเชิ้ตสีขาวครับ")],
 ["koszulka", "krawat", "praca"], []),

("A1", "spodnie", "kaang keeng", "กางเกง", ZP, "Ubrania", 4, "n",
 "„kaang keeng khǎa sân” to krótkie spodnie — dosłownie „o krótkich nogawkach”.",
 "",
 [("Te spodnie są za długie.", "kaang keeng tua níi yaao koen pai khráp", "กางเกงตัวนี้ยาวเกินไปครับ"),
  ("Poproszę krótkie spodnie.", "khǎw kaang keeng khǎa sân khráp", "ขอกางเกงขาสั้นครับ")],
 ["ubranie", "spódnica", "długi"], []),

("A2", "spódnica", "krà-prong", "กระโปรง", ZP, "Ubrania", 3, "n",
 "Do świątyń wymagana spódnica zakrywająca kolana — praktyczna informacja przy zwiedzaniu.",
 "",
 [("Do świątyni potrzebna jest długa spódnica.", "khâo wát tâwng sài krà-prong yaao khráp", "เข้าวัดต้องใส่กระโปรงยาวครับ"),
  ("Ta spódnica jest ładna.", "krà-prong tua níi sǔai khráp", "กระโปรงตัวนี้สวยครับ")],
 ["sukienka", "spodnie", "świątynia"], []),

("A2", "sukienka", "chút drét", "ชุดเดรส", ZP, "Ubrania", 3, "n",
 "„chút” samo znaczy komplet, zestaw ubrań: „chút wâai nám” to strój kąpielowy.",
 "komplet sukienka",
 [("Poproszę tę sukienkę.", "khǎw chút drét tua níi khráp", "ขอชุดเดรสตัวนี้ครับ"),
  ("Ta sukienka jest droga.", "chút drét tua níi phaeng khráp", "ชุดเดรสตัวนี้แพงครับ")],
 ["spódnica", "ubranie", "drogi"], []),

("A2", "kurtka", "sûea jáek-kèt", "เสื้อแจ็คเก็ต", ZP, "Ubrania", 3, "n",
 "Rzadko potrzebna na dworze, ale bardzo w autobusach i kinach z silną klimatyzacją.",
 "",
 [("W autobusie jest zimno, weź kurtkę.", "bon rót yen ao sûea jáek-kèt pai khráp", "บนรถเย็นเอาเสื้อแจ็คเก็ตไปครับ"),
  ("Zapomniałem kurtki.", "phǒm luem sûea jáek-kèt khráp", "ผมลืมเสื้อแจ็คเก็ตครับ")],
 ["ubranie", "zimno", "klimatyzacja"], []),

("A1", "buty", "rawng tháo", "รองเท้า", ZP, "Ubrania", 5, "n",
 "Dosłownie „podpórka stopy”. Kluczowa zasada: buty zdejmuje się przed wejściem do domu, świątyni i wielu sklepów.",
 "podpierać stopa",
 [("Proszę zdjąć buty.", "thàwt rawng tháo khráp", "ถอดรองเท้าครับ"),
  ("Gdzie są moje buty?", "rawng tháo phǒm yùu nǎi khráp", "รองเท้าผมอยู่ไหนครับ")],
 ["klapki", "stopa", "zdejmować"], []),

("A2", "klapki", "rawng tháo tàe", "รองเท้าแตะ", ZP, "Ubrania", 4, "n",
 "„tàe” znaczy dotykać lekko. Codzienne obuwie — ale nie wpuszczą w nich do urzędu.",
 "buty dotykać",
 [("Noszę klapki.", "phǒm sài rawng tháo tàe khráp", "ผมใส่รองเท้าแตะครับ"),
  ("W klapkach nie wolno.", "sài rawng tháo tàe mâi dâai khráp", "ใส่รองเท้าแตะไม่ได้ครับ")],
 ["buty", "stopa"], []),

("A2", "skarpetki", "thǔng tháo", "ถุงเท้า", ZP, "Ubrania", 3, "n",
 "„thǔng” to worek, torba — bardzo produktywne: thǔng mue (rękawiczki), thǔng nawn (śpiwór).",
 "worek stopa",
 [("Poproszę skarpetki.", "khǎw thǔng tháo khráp", "ขอถุงเท้าครับ"),
  ("Skarpetki są mokre.", "thǔng tháo pìak khráp", "ถุงเท้าเปียกครับ")],
 ["buty", "torba", "stopa"], []),

("A2", "czapka", "mùak", "หมวก", ZP, "Ubrania", 3, "n",
 "To samo słowo na kapelusz i kask: „mùak kan náwk” to kask motocyklowy, obowiązkowy.",
 "",
 [("Kask jest obowiązkowy.", "tâwng sài mùak kan náwk khráp", "ต้องใส่หมวกกันน็อคครับ"),
  ("Poproszę czapkę.", "khǎw mùak khráp", "ขอหมวกครับ")],
 ["okulary przeciwsłoneczne", "słońce", "motocykl"], ["kapelusz"]),

("A2", "okulary", "wâen taa", "แว่นตา", ZP, "Ubrania", 3, "n",
 "„wâen kan dàet” to okulary przeciwsłoneczne — dosłownie „chroniące przed słońcem”.",
 "szkło oko",
 [("Noszę okulary.", "phǒm sài wâen taa khráp", "ผมใส่แว่นตาครับ"),
  ("Zgubiłem okulary przeciwsłoneczne.", "phǒm tham wâen kan dàet hǎai khráp", "ผมทำแว่นกันแดดหายครับ")],
 ["oko", "słońce", "gubić"], []),

("A2", "torebka", "krà-pǎo", "กระเป๋า", ZP, "Ubrania", 4, "n",
 "Jedno słowo na torbę, torebkę, plecak i walizkę. Doprecyzowuje się: „krà-pǎo doen thaang” to walizka podróżna.",
 "",
 [("Moja torebka zniknęła.", "krà-pǎo phǒm hǎai khráp", "กระเป๋าผมหายครับ"),
  ("Torba jest ciężka.", "krà-pǎo nàk khráp", "กระเป๋าหนักครับ")],
 ["portfel", "walizka", "ciężki"], ["torba"]),

("A2", "pierścionek", "wǎen", "แหวน", ZP, "Ubrania", 2, "n",
 "Uwaga na parę minimalną: „wǎen” (pierścionek) i „wâen” (szkło, okulary) — różni je tylko ton.",
 "",
 [("To złoty pierścionek.", "pen wǎen thawng khráp", "เป็นแหวนทองครับ"),
  ("Ładny pierścionek.", "wǎen sǔai khráp", "แหวนสวยครับ")],
 ["okulary", "złoty", "srebrny"], []),

("A2", "rozmiar", "khà-nàat", "ขนาด", ZP, "Ubrania", 4, "n",
 "Najczęstsze pytanie w sklepie: „mii khà-nàat ìik mǎi khráp” — czy jest inny rozmiar.",
 "",
 [("Czy jest większy rozmiar?", "mii khà-nàat yài kwàa mǎi khráp", "มีขนาดใหญ่กว่าไหมครับ"),
  ("Jaki rozmiar pan nosi?", "sài khà-nàat à-rai khráp", "ใส่ขนาดอะไรครับ")],
 ["przymierzać", "duży", "mały"], []),

("A2", "przymierzać", "lawng sài", "ลองใส่", ZP, "Ubrania", 4, "n",
 "„lawng” znaczy próbować. „lawng chim” to spróbować jedzenia — ta sama konstrukcja.",
 "próbować wkładać",
 [("Czy mogę przymierzyć?", "lawng sài dâai mǎi khráp", "ลองใส่ได้ไหมครับ"),
  ("Przymierzę ten mniejszy.", "phǒm lawng sài tua lék kwàa khráp", "ผมลองใส่ตัวเล็กกว่าครับ")],
 ["rozmiar", "próbować", "przebieralnia"], []),

("A2", "przebieralnia", "hâwng lawng sûea", "ห้องลองเสื้อ", ZP, "Ubrania", 2, "n",
 "Dosłownie „pokój do przymierzania”. Pytanie o nią kończy zwykle rozmowę w sklepie z odzieżą.",
 "pokój próbować ubranie",
 [("Gdzie jest przebieralnia?", "hâwng lawng sûea yùu nǎi khráp", "ห้องลองเสื้ออยู่ไหนครับ"),
  ("Przebieralnia jest zajęta.", "hâwng lawng sûea mâi wâang khráp", "ห้องลองเสื้อไม่ว่างครับ")],
 ["przymierzać", "rozmiar"], []),

# ============================================================ ELEKTRONIKA
("A2", "ładowarka", "thîi chárt", "ที่ชาร์จ", CD, "Elektronika", 4, "n",
 "„thîi” tworzy nazwy narzędzi: thîi pòoet khùat (otwieracz), thîi nâng (siedzenie).",
 "narzędzie ładować",
 [("Zapomniałem ładowarki.", "phǒm luem thîi chárt khráp", "ผมลืมที่ชาร์จครับ"),
  ("Czy mogę pożyczyć ładowarkę?", "khǎw yuem thîi chárt dâai mǎi khráp", "ขอยืมที่ชาร์จได้ไหมครับ")],
 ["telefon", "gniazdko", "bateria"], []),

("A2", "bateria", "bàet-toe-rîi", "แบตเตอรี่", CD, "Elektronika", 4, "n",
 "Skracane w mowie do „bàet”. „bàet mòt” — bateria się skończyła.",
 "",
 [("Padła mi bateria.", "bàet mòt khráp", "แบตหมดครับ"),
  ("Bateria szybko się rozładowuje.", "bàet mòt reo khráp", "แบตหมดเร็วครับ")],
 ["ładowarka", "telefon", "kończyć się"], []),

("A2", "słuchawki", "hǔu fang", "หูฟัง", CD, "Elektronika", 3, "n",
 "Dosłownie „ucho do słuchania”. „hǔu” to ucho, „fang” to słuchać.",
 "ucho słuchać",
 [("Gdzie są moje słuchawki?", "hǔu fang phǒm yùu nǎi khráp", "หูฟังผมอยู่ไหนครับ"),
  ("Słuchawki są zepsute.", "hǔu fang sǐa khráp", "หูฟังเสียครับ")],
 ["ucho", "słuchać", "telefon"], []),

("A2", "głośnik", "lam-phoong", "ลำโพง", CD, "Elektronika", 2, "n",
 "Przydatne przy skardze na hałas u sąsiada albo w barze.",
 "",
 [("Głośnik jest za głośny.", "lam-phoong dang koen pai khráp", "ลำโพงดังเกินไปครับ"),
  ("Proszę ściszyć głośnik.", "chûai bao lam-phoong nòi khráp", "ช่วยเบาลำโพงหน่อยครับ")],
 ["głośny", "cicho", "muzyka"], []),

("A2", "ekran", "nâa jaw", "หน้าจอ", CD, "Elektronika", 3, "n",
 "„nâa” to twarz i przód. Dosłownie „przednia tafla”.",
 "twarz ekran",
 [("Ekran jest pęknięty.", "nâa jaw tàek khráp", "หน้าจอแตกครับ"),
  ("Ekran nie działa.", "nâa jaw mâi tìt khráp", "หน้าจอไม่ติดครับ")],
 ["telefon", "komputer", "pękać"], []),

("A2", "hasło", "rá-hàt phàan", "รหัสผ่าน", CD, "Elektronika", 4, "n",
 "„rá-hàt” to kod. Najczęściej używane przy pytaniu o wifi w kawiarni.",
 "kod przechodzić",
 [("Jakie jest hasło do wifi?", "rá-hàt wai-faai à-rai khráp", "รหัสไวไฟอะไรครับ"),
  ("Zapomniałem hasła.", "phǒm luem rá-hàt phàan khráp", "ผมลืมรหัสผ่านครับ")],
 ["internet", "telefon", "zapominać"], []),

("A2", "aplikacja", "áep", "แอป", CD, "Elektronika", 4, "n",
 "Skrót od angielskiego „application”. W Tajlandii płatności przez aplikację bankową są standardem.",
 "",
 [("Płacę przez aplikację.", "phǒm jàai phàan áep khráp", "ผมจ่ายผ่านแอปครับ"),
  ("Proszę pobrać aplikację.", "chûai doon-lòot áep khráp", "ช่วยดาวน์โหลดแอปครับ")],
 ["telefon", "płacić", "internet"], []),

("A2", "wiadomość", "khâw khwaam", "ข้อความ", CD, "Elektronika", 4, "n",
 "„khâw” to punkt, pozycja. Bardzo produktywne: khâw mun (dane), khâw sǎwp (egzamin).",
 "punkt treść",
 [("Wyślę wiadomość.", "phǒm jà sòng khâw khwaam khráp", "ผมจะส่งข้อความครับ"),
  ("Dostałem wiadomość.", "phǒm dâai ráp khâw khwaam khráp", "ผมได้รับข้อความครับ")],
 ["wysyłać", "telefon"], []),

("A2", "zdjęcie", "rûup", "รูป", CD, "Elektronika", 4, "n",
 "„thàai rûup” to robić zdjęcie. W świątyniach warto zapytać, czy wolno.",
 "",
 [("Czy mogę zrobić zdjęcie?", "thàai rûup dâai mǎi khráp", "ถ่ายรูปได้ไหมครับ"),
  ("Ładne zdjęcie.", "rûup sǔai khráp", "รูปสวยครับ")],
 ["aparat", "telefon", "świątynia"], ["fotografia"]),

("A2", "aparat", "klâwng thàai rûup", "กล้องถ่ายรูป", CD, "Elektronika", 3, "n",
 "„klâwng” to lufa, tubus. To samo słowo w „klâwng wong-jawn” — kamera monitoringu.",
 "tubus robić zdjęcie",
 [("Zapomniałem aparatu.", "phǒm luem klâwng thàai rûup khráp", "ผมลืมกล้องถ่ายรูปครับ"),
  ("Tutaj jest kamera.", "thîi nîi mii klâwng khráp", "ที่นี่มีกล้องครับ")],
 ["zdjęcie", "telefon"], []),

# ============================================================ DOKUMENTY
("A2", "dokument", "èek-kà-sǎan", "เอกสาร", PN, "Dokumenty", 4, "f",
 "Słowo urzędowe, słyszane w każdym biurze imigracyjnym i banku.",
 "",
 [("Proszę przynieść dokumenty.", "kà-rú-naa ao èek-kà-sǎan maa khráp", "กรุณาเอาเอกสารมาครับ"),
  ("Jakich dokumentów potrzeba?", "tâwng chái èek-kà-sǎan à-rai bâang khráp", "ต้องใช้เอกสารอะไรบ้างครับ")],
 ["paszport", "formularz", "kopia"], []),

("A2", "formularz", "bàep fawm", "แบบฟอร์ม", PN, "Dokumenty", 3, "f",
 "„kràwk bàep fawm” to wypełnić formularz — obowiązkowe przy meldunku w hotelu.",
 "wzór formularz",
 [("Proszę wypełnić formularz.", "kà-rú-naa kràwk bàep fawm khráp", "กรุณากรอกแบบฟอร์มครับ"),
  ("Gdzie wypełniam formularz?", "kràwk bàep fawm thîi nǎi khráp", "กรอกแบบฟอร์มที่ไหนครับ")],
 ["dokument", "wypełniać", "podpis"], []),

("A2", "podpis", "laai sen", "ลายเซ็น", PN, "Dokumenty", 3, "f",
 "„sen chûe” to czasownik — podpisać się. „laai” znaczy wzór, deseń.",
 "wzór podpis",
 [("Proszę tu podpisać.", "sen chûe trong níi khráp", "เซ็นชื่อตรงนี้ครับ"),
  ("Potrzebny jest podpis.", "tâwng mii laai sen khráp", "ต้องมีลายเซ็นครับ")],
 ["formularz", "dokument", "umowa"], []),

("A2", "kopia", "sǎm-nao", "สำเนา", PN, "Dokumenty", 3, "f",
 "Urzędy zwykle wymagają kopii paszportu z podpisem. Potocznie mówi się też „káw-pîi”.",
 "",
 [("Poproszę kopię paszportu.", "khǎw sǎm-nao phaas-pàwt khráp", "ขอสำเนาพาสปอร์ตครับ"),
  ("Gdzie mogę zrobić kopię?", "thàai èek-kà-sǎan dâai thîi nǎi khráp", "ถ่ายเอกสารได้ที่ไหนครับ")],
 ["dokument", "paszport"], []),

("A2", "umowa", "sǎn-yaa", "สัญญา", PN, "Dokumenty", 3, "f",
 "To samo słowo znaczy „obietnica”. „sen sǎn-yaa” — podpisać umowę.",
 "",
 [("Podpisałem umowę.", "phǒm sen sǎn-yaa láew khráp", "ผมเซ็นสัญญาแล้วครับ"),
  ("Umowa jest na rok.", "sǎn-yaa nùeng pii khráp", "สัญญาหนึ่งปีครับ")],
 ["podpis", "wynajmować (mieszkanie)", "obiecywać"], []),

("A2", "pieczątka", "traa", "ตรา", PN, "Dokumenty", 2, "f",
 "„prà-thàp traa” to przystawić pieczęć — bez niej wiele dokumentów jest nieważnych.",
 "",
 [("Potrzebna jest pieczątka.", "tâwng mii traa prà-thàp khráp", "ต้องมีตราประทับครับ"),
  ("Proszę o pieczątkę.", "khǎw prà-thàp traa khráp", "ขอประทับตราครับ")],
 ["dokument", "podpis", "urząd"], ["pieczęć"]),

# ============================================================ MATERIALY
("A2", "drewno", "mái", "ไม้", CD, "Materiały", 3, "n",
 "„mái” to zarazem drewno, drzewo i przedrostek narzędzi. Nie mylić z „mài” (nowy) ani „mâi” (nie).",
 "",
 [("Ten stół jest z drewna.", "tó tua níi tham dûai mái khráp", "โต๊ะตัวนี้ทำด้วยไม้ครับ"),
  ("Drewniany dom.", "bâan mái khráp", "บ้านไม้ครับ")],
 ["drzewo", "metal", "plastik"], []),

("A2", "metal", "lò-hà", "โลหะ", CD, "Materiały", 2, "f",
 "Słowo raczej techniczne. W mowie codziennej częściej „lèk” — żelazo, stal.",
 "",
 [("Jest z metalu.", "tham dûai lò-hà khráp", "ทำด้วยโลหะครับ"),
  ("Metal jest ciężki.", "lò-hà nàk khráp", "โลหะหนักครับ")],
 ["drewno", "plastik", "ciężki"], []),

("A2", "plastik", "pláat-sà-tìk", "พลาสติก", CD, "Materiały", 3, "n",
 "„thǔng pláat-sà-tìk” to reklamówka. Odmowa: „mâi ao thǔng khráp”.",
 "",
 [("Nie chcę reklamówki.", "mâi ao thǔng pláat-sà-tìk khráp", "ไม่เอาถุงพลาสติกครับ"),
  ("Jest z plastiku.", "tham dûai pláat-sà-tìk khráp", "ทำด้วยพลาสติกครับ")],
 ["torebka", "metal", "drewno"], []),

("A2", "papier", "krà-dàat", "กระดาษ", CD, "Materiały", 3, "n",
 "„krà-dàat chét pàak” to serwetka, „krà-dàat cham-rá” to papier toaletowy.",
 "",
 [("Poproszę kartkę papieru.", "khǎw krà-dàat nùeng phàen khráp", "ขอกระดาษหนึ่งแผ่นครับ"),
  ("Poproszę serwetkę.", "khǎw krà-dàat chét pàak khráp", "ขอกระดาษเช็ดปากครับ")],
 ["papier toaletowy", "pisać", "długopis"], []),

("A2", "szkło", "krà-jòk", "กระจก", CD, "Materiały", 3, "n",
 "To samo słowo na szybę i lustro. „kâew” to z kolei szklanka i szkło naczyniowe.",
 "",
 [("Szyba jest pęknięta.", "krà-jòk tàek khráp", "กระจกแตกครับ"),
  ("Jest ze szkła.", "tham dûai kâew khráp", "ทำด้วยแก้วครับ")],
 ["lustro", "okno", "pękać"], []),

("A2", "skóra (materiał)", "nǎng", "หนัง", ZP, "Materiały", 2, "n",
 "To samo słowo znaczy „film” — „duu nǎng” to oglądać film. Kontekst rozstrzyga.",
 "",
 [("To skórzana torba.", "pen krà-pǎo nǎng khráp", "เป็นกระเป๋าหนังครับ"),
  ("Idziemy na film.", "rao pai duu nǎng khráp", "เราไปดูหนังครับ")],
 ["torebka", "film"], []),

("A2", "bawełna", "fâai", "ฝ้าย", ZP, "Materiały", 2, "n",
 "„phâa fâai” to tkanina bawełniana — w tym klimacie praktyczniejsza niż syntetyk.",
 "",
 [("To bawełna.", "pen phâa fâai khráp", "เป็นผ้าฝ้ายครับ"),
  ("Wolę bawełnę.", "phǒm châwp phâa fâai mâak kwàa khráp", "ผมชอบผ้าฝ้ายมากกว่าครับ")],
 ["jedwab", "ubranie"], []),

("A2", "jedwab", "phâa mǎi", "ผ้าไหม", ZP, "Materiały", 2, "n",
 "Jedwab z Isanu to typowa pamiątka. Uwaga: „mǎi” tu znaczy jedwab, nie mylić z pytajnym „mǎi”.",
 "tkanina jedwab",
 [("To prawdziwy jedwab.", "pen phâa mǎi tháe khráp", "เป็นผ้าไหมแท้ครับ"),
  ("Jedwab jest drogi.", "phâa mǎi phaeng khráp", "ผ้าไหมแพงครับ")],
 ["bawełna", "drogi", "prezent"], []),

# ============================================================ NARZEDZIA
("A2", "narzędzie", "khrûeang mue", "เครื่องมือ", CD, "Narzędzia", 3, "n",
 "„khrûeang” zaczyna nazwy urządzeń: khrûeang bin (samolot), khrûeang sák phâa (pralka).",
 "urządzenie ręka",
 [("Potrzebuję narzędzi.", "phǒm tâwng chái khrûeang mue khráp", "ผมต้องใช้เครื่องมือครับ"),
  ("Nie mam narzędzi.", "phǒm mâi mii khrûeang mue khráp", "ผมไม่มีเครื่องมือครับ")],
 ["młotek", "śrubokręt", "naprawiać"], []),

("A2", "młotek", "kháwn", "ค้อน", CD, "Narzędzia", 2, "n",
 "Krótkie słowo z tonem opadająco-wysokim. Nie mylić z „khon” (osoba).",
 "",
 [("Poproszę młotek.", "khǎw kháwn nòi khráp", "ขอค้อนหน่อยครับ"),
  ("Gdzie jest młotek?", "kháwn yùu nǎi khráp", "ค้อนอยู่ไหนครับ")],
 ["narzędzie", "gwóźdź"], []),

("A2", "gwóźdź", "tà-puu", "ตะปู", CD, "Narzędzia", 2, "n",
 "Nie mylić z „puu” (krab) ani „pùu” (dziadek) — tu sylaba jest częścią złożenia.",
 "",
 [("Potrzebuję gwoździa.", "phǒm tâwng chái tà-puu khráp", "ผมต้องใช้ตะปูครับ"),
  ("Uważaj, tam jest gwóźdź.", "rá-wang tà-puu khráp", "ระวังตะปูครับ")],
 ["młotek", "narzędzie", "uważać"], []),

("A2", "śrubokręt", "khǎi khuang", "ไขควง", CD, "Narzędzia", 2, "n",
 "„khǎi” znaczy odkręcać. To samo „khǎi” w „khǎi kun-jae” — przekręcić klucz.",
 "odkręcać wiercić",
 [("Poproszę śrubokręt.", "khǎw khǎi khuang nòi khráp", "ขอไขควงหน่อยครับ"),
  ("Nie mam śrubokręta.", "phǒm mâi mii khǎi khuang khráp", "ผมไม่มีไขควงครับ")],
 ["narzędzie", "naprawiać"], []),

("A2", "nożyczki", "kan-krai", "กรรไกร", CD, "Narzędzia", 3, "n",
 "Uwaga w bagażu podręcznym — na lotnisku pytanie o nożyczki pada często.",
 "",
 [("Poproszę nożyczki.", "khǎw kan-krai nòi khráp", "ขอกรรไกรหน่อยครับ"),
  ("Nożyczek nie wolno.", "ao kan-krai khûen mâi dâai khráp", "เอากรรไกรขึ้นไม่ได้ครับ")],
 ["ciąć", "nóż", "narzędzie"], []),

("A2", "sznurek", "chûeak", "เชือก", CD, "Narzędzia", 2, "n",
 "„phùuk chûeak” to zawiązać sznurek — także o bransoletce z błogosławieństwem z świątyni.",
 "",
 [("Poproszę sznurek.", "khǎw chûeak nòi khráp", "ขอเชือกหน่อยครับ"),
  ("Zawiąż sznurek.", "phùuk chûeak khráp", "ผูกเชือกครับ")],
 ["wiązać", "narzędzie"], []),

("A2", "klej", "kaao", "กาว", CD, "Narzędzia", 2, "n",
 "Krótkie i łatwe. „tìt kaao” — przykleić.",
 "",
 [("Potrzebuję kleju.", "phǒm tâwng chái kaao khráp", "ผมต้องใช้กาวครับ"),
  ("Przyklej to.", "tìt kaao khráp", "ติดกาวครับ")],
 ["taśma", "narzędzie"], []),

("A2", "taśma klejąca", "théep kaao", "เทปกาว", CD, "Narzędzia", 2, "n",
 "Zapożyczenie „tape” plus „kaao”. Przydatne przy pakowaniu paczki na poczcie.",
 "taśma klej",
 [("Poproszę taśmę.", "khǎw théep kaao khráp", "ขอเทปกาวครับ"),
  ("Zaklej pudełko taśmą.", "tìt théep kaao thîi klàwng khráp", "ติดเทปกาวที่กล่องครับ")],
 ["klej", "pudełko", "pakować"], []),

("A2", "latarka", "fai chǎai", "ไฟฉาย", CD, "Narzędzia", 2, "n",
 "Dosłownie „światło świecące”. Praktyczne przy częstych przerwach w dostawie prądu na wyspach.",
 "światło świecić",
 [("Masz latarkę?", "mii fai chǎai mǎi khráp", "มีไฟฉายไหมครับ"),
  ("Nie ma prądu, weź latarkę.", "fai dàp ao fai chǎai maa khráp", "ไฟดับเอาไฟฉายมาครับ")],
 ["prąd", "światło", "ciemny"], []),

("A2", "bateria (paluszek)", "thàan fai chǎai", "ถ่านไฟฉาย", CD, "Narzędzia", 2, "n",
 "Inne słowo niż „bàet” — to bateria jednorazowa. „thàan” to węgiel.",
 "węgiel latarka",
 [("Poproszę baterie.", "khǎw thàan fai chǎai khráp", "ขอถ่านไฟฉายครับ"),
  ("Baterie się skończyły.", "thàan mòt khráp", "ถ่านหมดครับ")],
 ["latarka", "bateria"], []),
]
